### ISSUE TITLE
[Bug] Network Image Loading not working on Android Pie Simulator

### ISSUE THREAD

**Issue by pulimento** [xamarin/Xamarin.Forms#7814] opened 2019-10-04 10:41 UTC
### Description

When I try to load a image hosted on a HTTPs endpoint, using the Android Emulator (only Android 9, API 28, x86) and Xamarin Forms, the image can not be loaded. Tried with different images. Image loads on UWP, desktop and mobile browsers just fine. Tried on debug and release build configurations. Works on devices, fails on emulator. Works on x86_64 emulator.

### Steps to Reproduce

1. Create new Xamarin.Forms Project
2. On MainPage.xaml, create a Image element, with a HTTP source 
(eg: 	`<Image Source="https://dummyimage.com/600x400/000/fff.jpg" />` )
3.  Test it on a Android Emulator

### Expected Behavior

The image must load

### Actual Behavior

The image doesn't load

### Basic Information

- Version with issue: Tested on Xamarin.Forms 4.0.X and 4.2.X
- Last known good version: N/A
- IDE: Visual Studio 2019 16.3.2 (latest ATM)
- Platform Target Frameworks: Android Only
  - Android: 9.0 only (Google APIs Image rev.9). x86 version only.
- Android Support Library Version: Removed explicit dependency. 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: Android Emulators. Tried on 29.2.1 (latest). x86 images only.

### Screenshots

![image](https://user-images.githubusercontent.com/503313/66201325-5dd7eb00-e6a3-11e9-8775-51a169d1f2fe.png)

### Reproduction Link

> Create a new Xamarin.Forms project, add to XAML:

		<Image
			Source="https://dummyimage.com/600x400/000/fff.jpg" />

### Related Stack Trace

10-04 12:34:17.704 D/skia    ( 6808): --- Failed to create image decoder with message 'unimplemented'
10-04 12:34:17.738 D/OpenGLRenderer( 6808): Skia GL Pipeline
[0:] ImageLoaderSourceHandler: Could not retrieve image or image data was invalid: Uri: https://dummyimage.com/600x400/000/fff.jpg

**Comment by samhouts** [comment] 2019-10-04 16:53
Duplicate of #7751

**Closed by samhouts** 2019-10-04 16:53 UTC
Labels: p/Android, s/unverified, t/bug :bug:
