### ISSUE TITLE
[Bug] Xamarin.Forms -> Switch are Broken with Dynamic Resources (Android)

### ISSUE THREAD

**Issue by MickLesk** [xamarin/Xamarin.Forms#10228] opened 2020-04-06 19:33 UTC
### Description
Hey Guys,

We have a switch (Xamarin.Forms - Shared Project) with dynamic colors. 
On iOS this works perfectly, but on Android 10 (S9+ / Xiaomi Mi9+T) not really.
The app is already switched to AndroidX libraries. 

Short XAML-Code:
```
<StackLayout Orientation="Horizontal" VerticalOptions="End" Spacing="0" x:Name="BottomBarMainPage" HorizontalOptions="FillAndExpand">
        <Switch x:Name="OfflineSwitch" Margin="5, 0, 5, 0" Toggled="OfflineSwitch_Toggled" VerticalOptions="CenterAndExpand" 
                     OnColor="{DynamicResource BrandColorButton}"  ThumbColor="{DynamicResource BrandColor}"/>
            <Label x:Name="OfflineSwitchLabel" VerticalOptions="CenterAndExpand" FontSize="Small" HeightRequest="50" VerticalTextAlignment="Center" />
</StackLayout>
```

### Steps to Reproduce

1.  Use a StackLayout - Switch 
2.  Use Dynamic-Resources for Colors
3.  Build the App with Android 10 or 9

### Expected Behavior
Switch is displayed correctly, with the correct Color and ThumbColor

### Actual Behavior
1. Switch = False => Square over the round switch
2. Switch = True => square over the round switch + whole switch becomes square around

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: ---
- IDE: VStudio 16.5.2
- Platform Target Frameworks: 
  - iOS:  All Good!
  - Android: Android 10 API 29, Android 9 API 28
- Android Support Library Version: _Include with NuGet Packages below_
- Nuget Packages:
```
Following NuGet-Packages are installed
Xamarin.AndroidX.AppCompat
Xamarin.AndroidX.Browser
Xamarin.AndroidX.CardView
Xamarin.AndroidX.ConstraintLayout
Xamarin.AndroidX.ConstraintLayout.Solver
Xamarin.AndroidX.Legacy.Support.Core.Utils
Xamarin.AndroidX.Legacy.Support.V4
Xamarin.AndroidX.MediaRouter
Xamarin.AndroidX.Migration
Xamarin.Essentials
Xamarin.Forms
Xamarin.Forms.Maps
```

- Affected Devices:
- Xiaomi Mi9 + Mi9T
- Galaxy Tab S4
- Samsung S9+

### Screenshots
![2020_04_06_21_09_26_Window](https://user-images.githubusercontent.com/47820557/78597290-8a84df00-784d-11ea-822a-691011526937.png)

### Workaround
Look at the XAML code above, if I remove "onColor" and "onThumb" there, the switch looks correct.
This only affects Android, so we urgently need a fix here, as we need to play back the changes now, as Android users won't be happy with them.

**Comment by rmarinho** [comment] 2020-04-08 14:49
this is a duplicate of #9951 , we merged a fix that should be in a 4.6.0 release

**Closed by rmarinho** 2020-04-08 14:49 UTC
Labels: p/Android, t/bug :bug:
