### ISSUE TITLE
Xamarin 4.3 Picker not updating when backing ObservableCollection changes on UWP

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8333] opened 2019-10-31 16:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/793474/xamarin-43-picker-not-updating-when-backing-observ.html)._

---
Starting in the latest Xamarin 4.3 release. 
Defining a Picker in XAML

```
&lt;Picker x:Name=&quot;MyPicker&quot; ItemsSource=&quot;{Binding PickerItems}&quot; SelectedItem=&quot;{Binding SelectedPickerItem}&quot; &gt;&lt;/Picker&gt;
```

If PickerItems is an ObservableCollection and an item is added or removed from the collection, the Picker will not reflect the change.
The original items will still show in the picker's list.

In the previous Xamarin version 4.2 it behaved as expected.

It seems to work OK on Android.

---
#### Visual Studio Feedback System on 10/24/2019, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### solomon.fried on 10/30/2019, 08:22 AM: 

Seems to have been reported in GitHub
#### solomon.fried on 10/30/2019, 08:22 AM: 

https://github.com/xamarin/Xamarin.Forms/issues/8177<br>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment] 2019-10-31 22:06
Yes, this is a duplicate of #8177.

**Comment by solomonfried** [comment] 2019-11-07 16:38
Any idea when this will be fixed. It is causing my test users to have to close and restart the app whenever an item is added to a list in order to see the changes.
I doubt I can pass the Windows App Store with this bug in place. (which was first reported 2 weeks ago!)

**Comment by squizfloats** [comment] 2019-11-12 18:29
Can the Xamarin team please provide a workaround/hack we can use to refresh the UWP Picker contents. For use until this bug is fixed. Thanks, Alan

**Comment by cheles** [comment] 2019-11-14 14:04
@squizfloats check XF 4.3.0.991211 (just released) and let us know if you still see this issue.

**Comment by MooVC** [comment] 2019-11-14 14:14
> @squizfloats check XF 4.3.0.991211 (just released) and let us know if you still see this issue.

I just tested it and I can confirm it is now working as intended in UWP.

**Comment by jfversluis** [comment] 2019-11-14 14:24
@squizfloats @solomonfried looks like this has been solved in the NuGet package that was just released. Closing this for now. If you think otherwise, please let us know!

**Closed by jfversluis** 2019-11-14 14:24 UTC
Labels: i/regression, in-progress, p/UWP, t/bug :bug:

**Comment by squizfloats** [comment] 2019-11-14 17:25
Updated to XF 4.3.0.991211  on 11/14/19.  Updating the Picker contents (bound to an ObservableCollection) now works on UWP. Thank you.
