### ISSUE TITLE
[Bug] [iOS] SwipeView shifted in direction of swipe permanently

### ISSUE THREAD

**Issue by ASkiff-F360** [xamarin/Xamarin.Forms#14528] opened 2021-08-23 17:51 UTC
### Description
If a SwipeView has Left or Right items added and the user swipes to open the view while it is in the process of closing, the entire View is shifted in the direction of the swipe and stays there permanently.

The screenshot shown below as well as the sample has the SwipeView inside a ListView to make it easier to see the bug visually. Having the SwipeView inside a ListView is not a requirement to reproduce this issue

### Steps to Reproduce

1. Create a swipe view with Left/Right items
2. Swipe the view open
3. Tap on the view to close it (Can also be reproduced when programmatically closing the view)
4. Before it finishes closing, quickly swipe on the item again

### Expected Behavior
I would expect one of two behaviors:
1. The SwipeView interactions are disabled until the SwipeView is fully closed/reset
2. The SwipeView close gets cancelled and the view is correctly re-opened

### Actual Behavior
The SwipeView closes and re-opens simultaneously causing the Content to be shifted as if it was open.

### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version: None
- Platform Target Frameworks:
  - iOS:  15
- NuGet Packages: None
- Affected Devices: All iOS devices

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Professional 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA978
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
</details>

### Screenshots
![image0](https://user-images.githubusercontent.com/52086924/130493306-f9f3aaca-895a-4346-9fdb-fc819211adc1.png)

### Reproduction Link
[SwipeViewBugSample.zip](https://github.com/xamarin/Xamarin.Forms/files/7033906/SwipeViewBugSample.zip)

### Workaround
None

**Comment by jsuarezruiz** [comment] 2021-09-08 10:15
Could you try again with the NuGet package from https://github.com/xamarin/Xamarin.Forms/pull/14586?

**Comment by ASkiff-F360** [comment] 2021-09-08 13:52
> Could you try again with the NuGet package from #14586?

@jsuarezruiz Sorry for not knowing, but how do I get the NuGet package from that? I'm not sure where I should be looking

**Comment by jfversluis** [comment] 2021-09-09 09:16
@ASkiff-F360 have a look [here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) 

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by ASkiff-F360** [comment] 2021-09-09 14:35
Using the NuGet package for 5.0.0.7465 the issue does appear to be fixed. As for other accidental side-effects I have not come across any of those either. 

I do have one other question though. When downloading the artifacts from the pipeline build, it seems to only come with debug builds of the nuget packages. Is there any way to get a release build from this exact version other than cloning the repo and building it myself? It would be great to have this fix available for release builds before waiting on an official update to include it. Thank you :)

**Comment by jfversluis** [comment] 2021-09-09 14:39
That is great, thanks for checking!

I see what you're saying, but I'd rather have people not use these builds in their production apps, so, no that is not going to happen. The good news, hopefully, is that the version with this fix should be here this week or very soon at least. And from there I am going to make sure that there will be service releases each months, so waits shouldn't be as long :)

**Comment by jfversluis** [comment] 2021-09-09 14:39
In fact, @jsuarezruiz... What version is this fix in? Because your PR only adds test scenarios, so the actual functionality is fixed already?

**Comment by ASkiff-F360** [comment] 2021-09-09 14:41
> That is great, thanks for checking!
> 
> I see what you're saying, but I'd rather have people not use these builds in their production apps, so, no that is not going to happen. The good news, hopefully, is that the version with this fix should be here this week or very soon at least. And from there I am going to make sure that there will be service releases each months, so waits shouldn't be as long :)

Makes sense, thank you for the update!

**Comment by FlavioGoncalves-Cayas** [comment] 2021-09-14 11:24
Great work! 5.0.0.7465 finally makes SwipeView in a CollectionView usable. I hope it will be released soon.

**Comment by jfversluis** [comment] 2021-09-14 11:48
@FlavioGoncalves-Cayas thanks for confirming!

You could try the version here: https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr5

That is the one that is about to be released :) I'd love to confirm this one fixes it because I'm unsure when it got fixed :)

**Comment by FlavioGoncalves-Cayas** [comment] 2021-09-14 12:35
That's how I came here. I saw there is a new service release that fixes a ScrollView bug and tested it, but then I noticed the bug described here. Then tried the PR build, which works.

However, now I notice that the latest nupkg I could update to was not service release 5, but sr4. For some reason sr5 is not available yet on nuget.

Looks like the issue is fixed in sr5 already 👍

**Comment by jfversluis** [comment] 2021-09-14 18:26
Perfect! Indeed SR5 is going through the latest hoops to go to NuGet, should be soon :) thanks again! 

Closing this one as fixed then

**Closed by jfversluis** 2021-09-14 18:26 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/swipeview
