### ISSUE TITLE
[Bug] Can't type double number on android

### ISSUE THREAD

**Issue by NPadrutt** [xamarin/Xamarin.Forms#6167] opened 2019-05-10 22:19 UTC
### Description
When I set the region of a android emulator or device to the following, I can't write any double numbers to my entries when I have the keyboard set to numeric.
As far as I found out the correct seperator sign would be the point but that one is not written in that keyboard, but is in the default text keyboard.

### Steps to Reproduce

1. set language to 
![image](https://user-images.githubusercontent.com/1764367/57558964-21b48e80-7380-11e9-950c-85600d79e619.png)

2. start test project as debug
3.  type a number and a point
4. see that the point is not written
5. write a comma 
6. see that comma is written but removed in the property when assigned

### Expected Behavior
The point is written in the entry and a floating number is assigned in the property.

### Actual Behavior
Double values can be written with the numeric keyboard.

### Basic Information

- Version with issue: 3.6.0.344457
- Last known good version: unknown
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1

  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3168247/App1.zip)

**Comment by samhouts** [comment] 2019-05-10 23:47
Duplicate of #2049

**Closed by samhouts** 2019-05-10 23:47 UTC
Labels: s/unverified, t/bug :bug:

**Comment by NPadrutt** [comment] 2019-05-15 07:15
@samhouts  is that really the same issue? Since I can't even type a point (which would be the correct seperator sign) in the language above. I have a video here: https://github.com/MoneyFox/MoneyFox/files/3140027/device-2019-05-02-183502.zip
