### ISSUE TITLE
[Bug] An element with the same key already exists in Namescope

### ISSUE THREAD

**Issue by yrest** [xamarin/Xamarin.Forms#9366] opened 2020-01-30 08:19 UTC
### Description
From Play Store on released version, running Xamarin.Forms.Xaml.Extensions.LoadFromXaml causes subject exception. Development / debugging works as expected.

Perhaps it is related to https://github.com/xamarin/Xamarin.Forms/issues/7833 

### Steps to Reproduce

1. Release app
2. Call Xamarin.Forms.Xaml.Extensions.LoadFromXaml to load custom page
3. Observe failure

### Expected Behavior
Page is loaded correctly

### Actual Behavior
Generates exception

### Basic Information

- Version with issue: 4.4
- Last known good version: 4.1
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0

### Workaround

Roll back to 4.1

**Comment by StephaneDelcroix** [comment] 2020-01-30 10:45
please provide a repro sample. Thanks

**Comment by dotMorten** [comment] 2020-03-02 18:45
I'm seeing this too after upgrading. I'll get you a repro...

**Comment by dotMorten** [comment] 2020-03-02 20:07
Ignore that repro. For some reason the repro code I got, is calling InitializeComponents twice (a more useful error here could be useful though)

**Comment by samhouts** [comment] 2020-03-18 22:35
@yrest  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by dotMorten** [comment] 2020-03-18 22:36
@samhouts I provided a repro how to get the error from a user error. And as mentioned a better error here to catch that would be really useful

**Comment by samhouts** [comment] 2020-03-18 23:34
@dotMorten I guess I didn't understand your last comment to ignore the repro. I thought you determined it was a different problem...?

**Comment by dotMorten** [comment] 2020-03-18 23:36
@samhouts Well in this specific case it was caused by a user error. But troubleshooting that was near-impossible. With some better error messaging here, these would get easier to trouble shoot, and might even address the above issue. It at least shows one way to repro the specific error - and that error didn't occur on older versions even with my buggy code

**Comment by samhouts** [comment] 2020-03-18 23:37
I see. Thanks!

**Comment by yrest** [comment] 2020-03-19 08:47
In order to provide reproducible solution in my case I would need to register new app in google play store and then follow the full release path, which I simply don’t have capacity to do, unfortunately. I well maybe doing it all wrong, I accept that. What works for me on 4.1 is this:
- have default release version of xaml page inside apk
- have a customised version of the same xaml on web
- before launching the target page I download it
- then load it using below code, construct and launch

**Comment by yrest** [comment] 2020-03-19 13:10
In the next couple of days we'll try releasing a beta with latest XF4.5 and check if it's the same behaviour.

**Comment by StephaneDelcroix** [comment] 2020-03-19 15:58
@yrest as documented elsewhere, you should probably clear the namescope before using LoadFromXaml() (by doing view.SetNameScope(null));

**Comment by StephaneDelcroix** [comment] 2020-03-19 16:04
@dotMorten the error message was enhanced in #8702. re-closing this.

**Closed by StephaneDelcroix** 2020-03-19 16:05 UTC
Labels: a/Xaml </>, a/binding ⛓, e/3 :clock3:, t/bug :bug:

**Comment by yrest** [comment] 2020-03-19 16:44
Thanks Stephane! Where the "elsewhere" is i wonder, can you give some guidance please? Am struggling a bit to figure that one out.

**Comment by yrest** [comment] 2020-04-01 09:22
Can anyone give a correct reference to the implementation of view.SetNameScope(null) please?
