### ISSUE TITLE
[Bug] XF 4.3 Entry HorizontalTextAlignment display wrong position

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [xamarin/Xamarin.Forms#8137] opened 2019-10-22 02:48 UTC
### Description
Encounted since 4.3 pre1, Entry HorizontalTextAlignment display wrong position

### Basic Information

- Version with issue: 4.3
- Last known good version: 4.2
- IDE: VS 16.3.4

### Screenshots
4.2
![screenshot-2019-10-22_09 40 27 578](https://user-images.githubusercontent.com/16578966/67256425-18902780-f4b1-11e9-8bb4-7945390dc350.png)
4.3
![screenshot-2019-10-22_09 27 18 38](https://user-images.githubusercontent.com/16578966/67256432-1d54db80-f4b1-11e9-92d4-68b7bd8ffca5.png)

**Comment by xamarindevelopervietnam** [comment] 2019-10-22 04:00
I set HorizontalTextAlignment ="End" for this case.

**Comment by adrianknight89** [comment] 2019-10-22 19:00
Unfortunately, this has been an ongoing issue for Forms (mostly on Android). It seems the controls with horizontal text alignment sometimes lose their Gravity upon user action.

#7538 , #4976 , #4679 , #1557

**Comment by xamarindevelopervietnam** [comment] 2019-10-23 01:55
i think they added https://github.com/xamarin/Xamarin.Forms/pull/6463 but they don't check on Horizontal side

**Comment by samhouts** [comment] 2019-10-23 23:17
@xamarindevelopervietnam  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by oscarjaergren** [comment] 2019-10-28 12:54
Omg this issue is so old. Seems to have been fixed once before but the latest update broke it. Spent so long time on this before I figured out it was a bug that fucked up my layouts. 

Does anyone have a work around?

**Comment by Happypig375** [comment] 2019-10-28 13:52
Related to #7538

**Comment by bugaga6enika** [comment] 2019-11-05 13:22
Yes, it looks like this issue comes back from time to time.  Here is the repo that reproduces this issue
[EntryHorizontalTextAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/3809126/EntryHorizontalTextAlignment.zip)

**Comment by xamarindevelopervietnam** [comment] 2019-11-08 02:02
hope that issues will be fixed in the next release 4.3 SR2 @samhouts , I'm still using 4.2

**Comment by rubenc57** [comment] 2019-11-08 19:16
Workaround:

create a custom render for entry just for android and fix gravity

**Comment by stoff99** [comment] 2019-12-04 09:19
Same problem here, pls fix

**Comment by xamarindevelopervietnam** [comment] 2019-12-04 10:58
for now you can create custom renderer like this:
public class CrossBorderEntryRenderer : EntryRenderer
    {
        public CrossBorderEntryRenderer(Android.Content.Context context) : base(context: context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            UpdateHorizontalTextAlignment();
        }
}

internal static class TextAlignmentExtensions
    {
        internal static void UpdateHorizontalAlignment(this EditText view, TextAlignment alignment, bool hasRtlSupport,
            AGravityFlags orMask = AGravityFlags.NoGravity)
        {
            if ((int) Build.VERSION.SdkInt < 17 || !hasRtlSupport)
                view.Gravity = alignment.ToHorizontalGravityFlags() | orMask;
            else
                view.TextAlignment = alignment.ToTextAlignment();
        }

        internal static void UpdateVerticalAlignment(this EditText view, TextAlignment alignment,
            AGravityFlags orMask = AGravityFlags.NoGravity)
        {
            view.Gravity = alignment.ToVerticalGravityFlags() | orMask;
        }
    }

    internal static class AlignmentExtensions
    {
        internal static ATextAlignment ToTextAlignment(this TextAlignment alignment)
        {
            switch (alignment)
            {
                case TextAlignment.Center:
                    return ATextAlignment.Center;

                case TextAlignment.End:
                    return ATextAlignment.ViewEnd;

                default:
                    return ATextAlignment.ViewStart;
            }
        }

        internal static AGravityFlags ToHorizontalGravityFlags(this TextAlignment alignment)
        {
            switch (alignment)
            {
                case TextAlignment.Center:
                    return AGravityFlags.CenterHorizontal;

                case TextAlignment.End:
                    return AGravityFlags.End;

                default:
                    return AGravityFlags.Start;
            }
        }

        internal static AGravityFlags ToVerticalGravityFlags(this TextAlignment alignment)
        {
            switch (alignment)
            {
                case TextAlignment.Start:
                    return AGravityFlags.Top;

                case TextAlignment.End:
                    return AGravityFlags.Bottom;

                default:
                    return AGravityFlags.CenterVertical;
            }
        }
    }

**Closed** 2019-12-13 00:10 UTC
Labels: e/2 :clock2:, i/regression, in-progress, p/Android, t/bug :bug:

**Comment by luismts** [comment] 2020-01-03 14:55
Same problem here
