### ISSUE TITLE
[Bug] Misalignment of multi line label when using RTL on IOS

### ISSUE THREAD

**Issue by amr-moomen** [xamarin/Xamarin.Forms#9751] opened 2020-02-27 13:18 UTC
### Description
Misalignment of multi line label when using RTL on IOS but works fine on android
### Steps to Reproduce

1. Create ContentPage with label 
2. change FlowDirection of page to RightToLeft 
3. set label HorizontalTextAlignment="Start" 
4. observe the result

### Expected Behavior
label Text aligned right (start)

### Actual Behavior
label Text aligned left (end)
### Basic Information

- Version with issue: All versions of IOS
- Last known good version: None
- IDE: Visual Studio 2019 Version 16.4.3
- Platform Target Frameworks: 
  - iOS:  all versions
- Nuget Packages: Xamarin.Forms version 4.5.0.356
- Affected Devices: All Iphone 

### Screenshots

![image](https://user-images.githubusercontent.com/56504816/75447519-36472f00-5972-11ea-8db4-14448b99fdce.png)

![image](https://user-images.githubusercontent.com/56504816/75447577-5545c100-5972-11ea-9296-8816f0587696.png)

### Reproduction Link

https://github.com/amr-moomen/LabelMisalignment

### Workaround
Custom render for label on IOS

**Comment by amr-moomen** [comment] 2020-02-27 13:21
@samhouts @yurkinh

**Comment by yurkinh** [comment] 2020-02-27 13:57
@amr-moomen  Could you clarify issue?

I've tried your reproduction link. Also I have added label with "HorizontalTextAlignment="Start"" and it is aligned correctly when changing FlowDirection.
Here are my changes
MainPage
`<Label
                x:Name="Testlabel"
                Grid.Row="5"
                Grid.Column="0"
                Grid.ColumnSpan="2"
                HorizontalTextAlignment="Start"
                Label.TextColor="Black"
                Text="TestLabel" />`
and 
MainArabicPage
`<Label
                x:Name="Testlabel"
                Grid.Row="5"
                Grid.Column="0"
                Grid.ColumnSpan="2"
                HorizontalOptions="Start"
                HorizontalTextAlignment="Start"
                Label.TextColor="Black"
                Text="الحالة العسكرية / خدمه عامة" />`
![RTL](https://user-images.githubusercontent.com/17849938/75451373-2252fb80-5979-11ea-8aba-f7422b93b1cc.Gif)

**Comment by amr-moomen** [comment] 2020-02-27 15:03
@yurkinh the misalignment occurred when label dont fit area and take multi line

**Comment by jsuarezruiz** [comment] 2020-02-27 15:17
Thanks for the detailed description. I can reproduce the problem. However, only happens if the text is multi-line.

![issue9751](https://user-images.githubusercontent.com/6755973/75456037-524ece80-597a-11ea-8fb8-88cd1ae15473.gif)
(Reduced font size)

Seems to be the same as #9046 as @AmrAlSayed0 has commented.

**Comment by Cloudtrackers** [comment] 2020-02-28 07:07
> Thanks for the detailed description. I can reproduce the problem. However, only happens if the text is multi-line.
> 
> ![issue9751](https://user-images.githubusercontent.com/6755973/75456037-524ece80-597a-11ea-8fb8-88cd1ae15473.gif)
> (Reduced font size)
> 
> Seems to be the same as #9046 as @AmrAlSayed0 has commented.

Not only if the text is multiline.  if the Label  HorizontalOptions is "FillAndExpand" and
HorizontalTextAlignment is "Start" , in this case also bug happens.

**Comment by rmarinho** [comment] 2020-11-06 12:04
this should have been fixed on #10046

**Closed by rmarinho** 2020-11-06 12:04 UTC
Labels: a/label, a/rtl, e/3 :clock3:, in-progress, p/iOS 🍎, t/bug :bug:, up-for-grabs
