### ISSUE TITLE
Binding Image.IsVisible in ListView ItemTemplate is broken in Android

### ISSUE THREAD

**Issue by oskarskog** [xamarin/Xamarin.Forms#6899] opened 2019-07-17 14:09 UTC
### Description

An Image, inside a ListView's ItemTemplate, with properties IsVisible and Source bound, is not shown correctly when scrolling the page. When scrolling, the image is sometimes not visible even if IsVisible is true and Source is an existing image resource.

I have only been able to repro this when using RecycleElement caching strategy.

This behaviour is reproducible on Android with Xamarin.Forms 4.0.0.304370-pre8 to 4.2.0.608146-pre1 (latest)

### Steps to Reproduce

1. Deploy the project linked
2. Scroll down and up a few times in the app.
3. Notice that the icons aren't always visible when IsVisible is true, i.e. the number is 1 or 2.

### Expected Behavior

The icon is visible when the IsVisible property is true. 
See screenshot 1.

### Actual Behavior

The icon is not always visible when the IsVisible property is true. 
See screenshot 2.

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.304370-pre8 to 4.2.0.608146-pre1 (latest)
- Last known good version: 4.0.0.250467-pre7
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS:  N/A
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: 28.0.0.1 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: Tested on Samsung S8 and Samsung Galaxy A3

### Screenshots

1)
![Screenshot_20190717-163631](https://user-images.githubusercontent.com/19431886/61379955-2d0cc480-a8b1-11e9-8d5d-f047cfa78591.png)

2)
![Screenshot_20190717-163639](https://user-images.githubusercontent.com/19431886/61380146-87a62080-a8b1-11e9-9ef9-ff0355cc4e9f.png)

### Reproduction Link

[listviewtest.zip](https://github.com/xamarin/Xamarin.Forms/files/3402234/listviewtest.zip)

**Comment by jsuarezruiz** [comment] 2019-07-17 14:55
Thanks for the repro sample. I can reproduce the problem. Some details:
- The problem only happens on **Android**.
- It seems to be a problem related to **recycling cells**. If you use RetainElement as CachingStrategy everything works as expected.
- I've tried several versions. In Xamarin.Forms 3.6 it does not happen.

**Comment by lassana** [comment] 2019-07-17 19:08
We got the same problem in our app. We have a `ListView`:
```
<ListView x:Name="lvMasterData" 
          ItemTapped="OnMasterDataItemTapped" 
          IsPullToRefreshEnabled="False"
          ItemTemplate="{StaticResource ArticleDataTemplateSelector}"
          CachingStrategy="RecycleElement">
    <ListView.HasUnevenRows>
        <OnIdiom Tablet="false" Phone="true" />
    </ListView.HasUnevenRows>
</ListView>
```

And the cell has an image:

```
<Image Source="check.png"
       IsVisible="{Binding IsSelected}"
       Margin="6,0,0,0"
       Grid.Row="0"
       Grid.Column="0"
       HorizontalOptions="Center"
       VerticalOptions="Center"
       WidthRequest="24"
       HeightRequest="24" />
```

It happens with both `RecycleElement` and `RetainElement`. I tried to replace `Image` with `Label` but it's still unreliable. I also tried `Forms.SetFlags("UseLegacyRenderers");` with no luck. 

It looks like I can only revert back to 3.6. :(

**Comment by oskarskog** [comment] 2019-07-17 19:48
Seems this could be related #6297

**Comment by samhouts** [comment] 2019-07-18 03:10
closed by #6390

**Closed by samhouts** 2019-07-18 03:10 UTC
Labels: a/listview, e/5 :clock5:, i/regression, p/Android, t/bug :bug:

**Comment by nicolasmab** [comment] 2019-09-25 15:16
Still broken in 4.2.0
[Temporary workaround](https://github.com/xamarin/Xamarin.Forms/pull/6390#issuecomment-535070005)

**Comment by rajeshtamda** [comment] 2020-07-10 13:57
This issue still exists in 4.5.0.617. changing caching strategy to RetainElement seems to fix it.
