### ISSUE TITLE
UWP: DisplayActionSheet is not displaying if using in a void function

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#3890] opened 2018-09-24 23:52 UTC
### Description

Code below is not working because DisplayActionSheet  is not awaiting for a result on UWP. thats why i dont see display action. Reason cold be possible because using "async avoid" but this works on Android and It works also with the previous versions. It only fails with the latest version. 
I am not able to change this to be Task instead of Void as the tools itemtapped event is not accepting it.

```
 private async void SfKanban_ItemTapped(object sender, Syncfusion.SfKanban.XForms.KanbanTappedEventArgs e)
        {
            var action = await DisplayActionSheet ("ActionSheet: Send to?", "Cancel", null, "Email", "Twitter", "Facebook");
 
                    if (result =="Email")
                    {
                        await Email();
                    }
        }
```

### Steps to Reproduce

1.  Use any async void event as above
2. 
3. 

### Expected Behavior

that it awaits for the result

### Actual Behavior

it doesnt await. thats why no popup is displayed
 
- Version with issue: 3.2.0
- Last known good version: any version lower thatn 3.2.0
- IDE: VS 2017 15,8.5
- Platform Target Frameworks: 
 
  - UWP:  
```
 <TargetPlatformVersion>10.0.17134.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
```

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: UWP Local

**Comment by PureWeen** [comment] 2018-09-24 23:54
@EmilAlipiev  if you try catch the await do you see an exception?

**Comment by EmilAlipiev** [comment] 2018-09-25 11:16
@PureWeen  this is weird. i tried to create a repro but it worked and i deleted bin, obj, temp, .vs, cleaned nuget cache and now it looks like working. 

There is just one more difference i recognized. See the images below.. Older versions had white transparent background while 3.2 seems like has no transparency. And plus, clicking outside of ActionSheet pops the popup. this is not the case in older version. It even pops if you click outside app, somewhere in windows. Not sure if that is by design and we can control it or it is a bug.

older version

![image](https://user-images.githubusercontent.com/10422347/46010963-adfd9400-c0c4-11e8-8fb1-0cbed5279c74.png)

3.2 version

![image](https://user-images.githubusercontent.com/10422347/46011026-e2715000-c0c4-11e8-9934-2b9ae1b61229.png)

**Comment by hartez** [comment] 2018-10-19 04:37
@EmilAlipiev This is by design: https://github.com/xamarin/Xamarin.Forms/pull/881

**Comment by hartez** [comment] 2018-10-19 04:38
@EmilAlipiev It looks like your original issue has been resolved? I'm closing this for now, if I'm mistaken please re-open. Thanks.

**Closed by hartez** 2018-10-19 04:38 UTC
