### ISSUE TITLE
CarouselView.Position and CarouselIndicators are not there in Xamarin.Forms 3.6.

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#5869] opened 2019-04-10 09:54 UTC
## Summary
CarouselView in Xamarin.Forms 3.6 does not have the two properties of Position and CarouselIndicators.

## API Changes

Xamarin.Forms 3.6 has included the CarouselView, so I cant use the nuget package anymore, but shipped version seems to be lacking some features, more specifically indicators seems to be missing entirely?

e.g.

Here is my old code, which does not compile anymore:

   ```
// Create the carousel
            _carouselView = new CarouselView()
		    {
		        VerticalOptions = LayoutOptions.FillAndExpand,
		        HorizontalOptions = LayoutOptions.FillAndExpand,
		    };
      
            _carouselView.ItemTemplate = template;
            _carouselView.SetBinding(ItemsView.ItemsSourceProperty, nameof(_viewModel.CarouselItems));
		    _carouselView.SetBinding(CarouselView.PositionProperty, nameof(_viewModel.Position));

		    // Create page-indicator
		    var indicator = new CarouselIndicators { ItemsSource = _viewModel.CarouselItems };
            indicator.Margin = new Thickness(20, 20, 20, 0);
		    indicator.SetBinding(CarouselIndicators.PositionProperty, nameof(_viewModel.Position));

```
CarouselView.Position and CarouselIndicators are not there in 3.6

## Other try
 Have a try this CarouselView.FormsPlugin NuGet, it also not have  CarouselIndicators 
in CarouselView .https://github.com/alexrainman/CarouselView

**Comment by samhouts** [comment] 2019-04-10 18:04
We're planning to add Position. CarouselIndicators will be slightly different (see the spec for details). We're currently targeting 4.1 for continued work on CarouselView. Thanks for your patience!

**Comment by samhouts** [comment] 2019-04-10 18:04
Duplicate of #4996

**Closed by samhouts** 2019-04-10 18:04 UTC
Labels: proposal-open, t/enhancement ➕

**Comment by numb3r** [comment] 2019-08-09 14:29
Is there any alternative to PositionSelected event in Xamarin.Forms v3.6?
