### ISSUE TITLE
Nullable DateTime with value is null in a constructor

### ISSUE THREAD

**Issue by azuken** [xamarin/Xamarin.Forms#5457] opened 2019-03-05 15:12 UTC
### Steps to Reproduce

1. Have a nullable DateTime ViewModel property, bound to a Xamarin.Forms view (Custom widget extended from DatePicker)
2. Have a model with a constructor, which have a nullable DateTime parameter
3. Get ViewModel property, pass it to constructor

```
       // CODE FROM VIEW MODEL
        private DateTime? _installationDate;
        public DateTime? InstallationDate
        {
            get => _installationDate;
            set
            {
                _installationDate = value;
                RaisePropertyChanged();
            }
        }

        private async Task EditEquipment() {
            var info = new CustomerEquipmentInfo(EquipmentInfo.Id, InstallationDate);
        }
       // CODE FROM VIEW MODEL

public class CustomerEquipmentInfo {
       public CustomerEquipmentInfo(Guid id, DateTime? installationDate) {
            Id = id;
            InstallationDate = installationDate;
       }

        public Guid Id { get; private set; }
        public DateTime? InstallationDate { get; private set; }
}
```

### Expected Behavior

I expect that my DateTime passed to object is not null

### Actual Behavior

Nullable datetime set with a valid date value become null when passed to a constructor, in Release mode, on Xamarin iOS, on a real device (iPad Air 2 with iOS 12.1 & iPhone 8 with iOS 12.1) (Xamarin iOS Debug works, Xamarin Android Debug and Release works). On iPhone Emulator, it works too.

### Basic Information

- Version with issue: 3.4.0.1029999
- Last known good version: -
- IDE: Visual Studio For Mac 7.8.2 Build 1
- Platform Target Frameworks: 
  - iOS:  XCode 10.1
  - Android: -
  - UWP:  -
- Android Support Library Version: -
- Nuget Packages:
- Affected Devices: iPad Air 2 & iPhone 8

**Comment by azuken** [comment] 2019-03-05 15:54
After some tests, I have two case which resolve issue : 

- When I set me nullable datetime after instanciate object (with public property setter), it works.
- When I put nullable datetime parameter at the end of constructor, it works.

**Comment by kingces95** [comment] 2019-03-05 22:09
Wha? This sounds exciting...

**Comment by kingces95** [comment] 2019-03-06 02:29
@azuken Could you please attached a zip solution that exhibits the unexpected behavior?

**Comment by azuken** [comment] 2019-03-06 08:28
@kicsiede I cannot provide my solution, because it's from my company. All I can do is providing you more samples.

**Comment by samhouts** [comment] 2019-03-11 22:02
Duplicate of #5469

**Closed by samhouts** 2019-03-11 22:02 UTC
Labels: p/iOS 🍎, s/needs-repro ❔, t/bug :bug:
