### ISSUE TITLE
[Bug] Xamarin.Forms.Shell FlyoutHeaderBehavior Collapse On Scroll

### ISSUE THREAD

**Issue by koddek** [xamarin/Xamarin.Forms#9959] opened 2020-03-13 16:58 UTC
### Description
FlyoutHeaderBehavior="CollapseOnScroll" does not work.
### Steps to Reproduce

1. Add multiple flyout items till they all cant fit on the screen at once.
2. Set FlyoutHeaderBehavior="CollapseOnScroll"
3. Run the app and try scrolling. (Nothing happens)

### Expected Behavior
I expect that when the screen is swiped/pushed up (scroll down) that the flyout header to collapse up (hide) and when swiped/push down (scroll up), come back into view (show).
### Actual Behavior
Nothing happens. The header is always shown.
### Basic Information

- Version with issue: Xamarin.Forms v4.5
- Last known good version: _
- IDE: Visual Studio 2019 Community Win.
- Platform Target Frameworks: .NET Standard 2.1
  - Android: API 21, 24, 26, 28

**Comment by jfversluis** [comment] 2020-03-16 13:20
Hey @koddek thanks for reporting this.

I have added a reproduction project, but it seems to work as expected? When I scroll up the header is collapsed and when I scroll down it expands again. Could you add to this code what is specific to your situation and causes the issue? Also, only on Android? Does it work on iOS as you would expect?

Thanks!

[Repro9959.zip](https://github.com/xamarin/Xamarin.Forms/files/4338350/Repro9959.zip)

**Comment by koddek** [comment] 2020-03-16 14:21
> Hey @koddek thanks for reporting this.
> 
> I have added a reproduction project, but it seems to work as expected? When I scroll up the header is collapsed and when I scroll down it expands again. Could you add to this code what is specific to your situation and causes the issue? Also, only on Android? Does it work on iOS as you would expect?
> 
> Thanks!
> 
> [Repro9959.zip](https://github.com/xamarin/Xamarin.Forms/files/4338350/Repro9959.zip)

The XAML below is what my design had. I was looking for the bar/header to disappear completely, but in your example, I see that the header's height was 200 and it collapsed down to 56 (which is the starting height of mine), so I errored in how I expected the feature to work.

That being said, it would be nice if it collapsed completely (The header completely disappear on scroll up) and also 'off-topic' if NavBar in ContentPage had that same ability. The ability to collapse/expand on the Listview/CollectionView scroll.


    <Shell.FlyoutHeader>
        <Grid BackgroundColor="Black"
              HeightRequest="56">
            <Label Margin="16"
                   FontAttributes="Bold"
                   Text="Animals"
                   TextColor="White"
                   VerticalTextAlignment="Center" />
        </Grid>
    </Shell.FlyoutHeader>

P.S Thanks for your reply!

**Comment by jfversluis** [comment] 2020-03-20 20:23
Yeah I don't think that is something we support right now. This more mimics the way iOS has the big title and then it collapses into something smaller. 

So either you can come up with a creative solution or please open a feature request for it so we can gauge interest and hopefully implement it in the near future. Closing this for now as its not a bug :)

**Closed by jfversluis** 2020-03-20 20:23 UTC
Labels: s/unverified, t/bug :bug:
