### ISSUE TITLE
[Bug] ListView with HasUnevenRows on iOS inferior to 11

### ISSUE THREAD

**Issue by Holsten** [xamarin/Xamarin.Forms#6201] opened 2019-05-15 16:19 UTC
### Description
On iOS versions inferior to 11; ListViews with HasUnevenRows are broken in latest versions of XamarinForms.

### Steps to Reproduce

1. Create a ListView with a complex ItemTemplate
2. Set HasUnevenRows to true
3. Populate the list
3. Deploy the application on an iOS device with OS version inferior to 11

### Expected Behavior

The ListView adapts to the complex items.

### Actual Behavior

It does not.

### Basic Information

- Version with issue: 3.6.0.293080
- Last known good version:3.6.0.364807
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  10.3.1
- Nuget Packages: Xamarin.Forms
- Affected Devices: IPhone 6s plus, IPhone 5 ..

### Screenshots

iPhone 6s plus with iOS 10.3.1
![Screen Shot champ](https://user-images.githubusercontent.com/639516/57790874-e9280280-773b-11e9-9cc1-bc817ccf04bf.png)

iPhone XR with iOS 12.1.4:
![Screen Shot xr](https://user-images.githubusercontent.com/639516/57790925-0a88ee80-773c-11e9-9fcd-86c159a8cb32.png)

### Reproduction Link
https://github.com/Holsten/XF-3.6-ListView-bug

**Comment by kingces95** [comment] 2019-05-16 21:44
Reproduces as described on iPhone 6s Plus 10.3.1

**Comment by radioactiveman** [comment] 2019-05-20 08:52
This is likely a duplicate of #5888.

**Comment by samhouts** [comment] 2019-05-28 20:16
Yep, this should be currently fixed in 4.0.0. Thanks!

**Comment by samhouts** [comment] 2019-05-28 20:16
Duplicate of #5888

**Closed by samhouts** 2019-05-28 20:16 UTC
Labels: i/regression, s/unverified, t/bug :bug:
