### ISSUE TITLE
[Bug] SwipeView TapGestureRecognizer causes SwipeItems to be not accessible

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#11758] opened 2020-08-12 12:15 UTC
### Description 

When using a TapGestureRecognizer within a SwipeView, the SwipeItems are no longer accessible. 

### Steps to Reproduce

1. Use a SwipeView
2. Setup a TapGestureRecognizer on the content of it

### Expected Behavior

TapGestureRecognizer should not block the swipe gesture

### Actual Behavior

TapGestureRecognizer is blocking the swipe gesture

### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: -

**Comment by rmarinho** [comment] 2020-08-12 16:38
Hi @Sebastian1989101  i tried to reproduce this issue but wasn't able, i added a tap and i could use the swipe and get the tapped fired. The code i used:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App11742.Views.AboutPage"
             Title="{Binding Title}">

    <Grid BackgroundColor="Green">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="30"/>
            <RowDefinition Height="30"/>
        </Grid.RowDefinitions>
        <SwipeView>
            <SwipeView.LeftItems>
                <SwipeItems>
                    <SwipeItem Text="Favorite"
                       IconImageSource="favorite.png"
                       BackgroundColor="LightGreen"
                       Invoked="OnFavoriteSwipeItemInvoked" />
                    <SwipeItem Text="Delete"
                       IconImageSource="delete.png"
                       BackgroundColor="LightPink"
                       Invoked="OnDeleteSwipeItemInvoked" />
                </SwipeItems>
            </SwipeView.LeftItems>
            <!-- Content -->
            <Grid HeightRequest="60"
          WidthRequest="300"
          BackgroundColor="LightGray">
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
                </Grid.GestureRecognizers>
                <Label Text="Swipe right"
               HorizontalOptions="Center"
               VerticalOptions="Center" />
            </Grid>
        </SwipeView>
    </Grid>
</ContentPage>
```

Can you please upload a small repo. And btw is this iOS or Android?

**Comment by Sebastian1989101** [comment] 2020-08-12 16:43
@rmarinho I tested it with Android. Only difference to your code is, that my SwipeView is in a ItemTemplate of a CollectionView, otherwise it is identical. I just started testing with iOS with the SwipeView and already had 2 issues out of the box with the very same code that worked on Android at the end.. at least I did not encounter the TapGesture issue on iOS..

**Comment by rmarinho** [comment] 2020-08-12 17:30
Ok i used the sample for file->new project and change a bit for this and it works

I can click on the swipe items, and i can use the tap gesture to go to next page

``` 
<RefreshView x:DataType="local:ItemsViewModel" Command="{Binding LoadItemsCommand}" IsRefreshing="{Binding IsBusy, Mode=TwoWay}">
        <CollectionView x:Name="ItemsListView"
                ItemsSource="{Binding Items}"
                SelectionMode="None">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <SwipeView>
                        <SwipeView.LeftItems>
                            <SwipeItems>
                                <SwipeItem Text="Favorite"
                       IconImageSource="favorite.png"
                       BackgroundColor="LightGreen"
                       Invoked="OnFavoriteSwipeItemInvoked" />
                                <SwipeItem Text="Delete"
                       IconImageSource="delete.png"
                       BackgroundColor="LightPink"
                       Invoked="OnDeleteSwipeItemInvoked" />
                            </SwipeItems>
                        </SwipeView.LeftItems>
                        <StackLayout Padding="10" x:DataType="model:Item">
                            <Label Text="{Binding Text}" 
                            LineBreakMode="NoWrap" 
                            Style="{DynamicResource ListItemTextStyle}" 
                            FontSize="16" />
                            <Label Text="{Binding Description}" 
                            LineBreakMode="NoWrap"
                            Style="{DynamicResource ListItemDetailTextStyle}"
                            FontSize="13" />
                            <StackLayout.GestureRecognizers>
                                <TapGestureRecognizer 
                                NumberOfTapsRequired="1"
                                Command="{Binding Source={RelativeSource AncestorType={x:Type local:ItemsViewModel}}, Path=ItemTapped}"		
                                CommandParameter="{Binding .}">
                                </TapGestureRecognizer>
                            </StackLayout.GestureRecognizers>
                        </StackLayout>
                    </SwipeView>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </RefreshView>
</ContentPage>
```

**Comment by rmarinho** [comment] 2020-08-12 17:30
Please upload a sample if you can. 
Thanks

**Comment by Sebastian1989101** [comment] 2020-08-12 21:59
@rmarinho hmm thats strange that is exactly how I can recreate the error. I will try to setup a sample in the next hours/days.

**Comment by Sebastian1989101** [comment] 2020-08-13 13:11
[XamarinIssue11758.zip](https://github.com/xamarin/Xamarin.Forms/files/5069206/XamarinIssue11758.zip)

Here is a sample project showing this problem on Android.

**Comment by jsuarezruiz** [comment] 2020-08-14 09:02
Thanks for the reproduction sample. I have done tests and the issue seems to be fixed in 4.8. Could you try?.
![issue11758](https://user-images.githubusercontent.com/6755973/90232883-9432da80-de1d-11ea-966c-b088fc34a6d0.gif)

**Comment by Sebastian1989101** [comment] 2020-08-20 18:20
@jsuarezruiz seems to be working with 4.8

**Comment by jsuarezruiz** [comment] 2020-08-28 07:12
Thanks for the feedback, we are going to close this issue but if you find any other details, do not hesitate to open another one or let me know and we can reopen etc.

**Closed by jsuarezruiz** 2020-08-28 07:12 UTC
Labels: a/swipeview, s/unverified, t/bug :bug:
