### ISSUE TITLE
[Bug] UWP ScrollView Entry's text is blank until a tap on it

### ISSUE THREAD

**Issue by vardansargsyan92** [xamarin/Xamarin.Forms#11259] opened 2020-07-01 14:18 UTC
### Description

Hi folks.

I am using a scroll view in my application and after updating "Xamarin.Forms" it does not work correctly. I have input items inside the scroll view (Entry) and they are blank until I tap on them. I have attached a gif file that shows the scenario explained above.

### Steps to Reproduce

1. Clone/Download a [sample](https://github.com/vardansargsyan92/ScrollViewIssue)
2.  Run the application

### Expected Behavior

The inputs should not be blank.

### Actual Behavior

The inputs are blank.

### Basic Information

- Version with issue: 4.6.0.968
- Last known good version: 4.6.0.967
- IDE: Visual Studio
- Platform Target Frameworks: 
  - UWP: 16299  

### Screenshots
![emptyEntry](https://user-images.githubusercontent.com/19687305/86254686-3a58b700-bbc7-11ea-85b1-c492cd03ecfe.gif)

### Reproduction Link

[Sample](https://github.com/vardansargsyan92/ScrollViewIssue)

### Workaround

N/A

**Comment by jsuarezruiz** [comment] 2020-07-01 14:34
Could be the same as: https://github.com/xamarin/Xamarin.Forms/issues/8787

**Comment by vardansargsyan92** [comment] 2020-07-01 14:48
@jsuarezruiz  this was working fine on the previous version of XF. The version of XF mentioned [here](https://github.com/xamarin/Xamarin.Forms/issues/8787) is 4.3.0.991221. Perhaps this could be the same.

**Comment by samhouts** [comment] 2020-07-01 16:28
This might be a duplicate of #11106. Please try the latest version of 4.7.0.1080 published today.

**Comment by vardansargsyan92** [comment] 2020-07-02 07:14
@samhouts   I have updated XF version to 4.7.0.1080 and I am still getting the same issue. I have pushed the changes into the master branch in my GitHub [repo.](https://github.com/vardansargsyan92/ScrollViewIssue)

**Comment by bmacombe** [comment] 2020-07-02 15:57
#11140 merged today into 4.8 might fix this

**Comment by PureWeen** [comment] 2020-07-09 22:54
This is still happening with #11140 merged in

**Comment by bmacombe** [comment] 2020-07-09 23:38
I'll try to test against #11351 and see if that resolves this.

**Comment by bmacombe** [comment] 2020-07-10 02:41
@PureWeen Looks like #11351 might fix this one.

Tested by making an issue page which is just a copy of the repro in this issue.  Screenshots are just after opening the issue 11259 and doing nothing else.

Before putting Packager.Load in the Loaded event
![image](https://user-images.githubusercontent.com/15127788/87110368-77a6ef80-c22c-11ea-9f0d-c832b6bfd37a.png)

After
![image](https://user-images.githubusercontent.com/15127788/87110571-f69c2800-c22c-11ea-8ec4-91d69843f035.png)

**Comment by samhouts** [comment] 2020-07-30 01:22
closed by #11351

**Closed by samhouts** 2020-07-30 01:22 UTC
Labels: 4.6.0, a/scrollview, i/regression, in-progress, p/UWP, t/bug :bug:
