### ISSUE TITLE
CollectionView EmptyView in arabic on IOS is mirrored 

### ISSUE THREAD

**Issue by mohamadayash** [xamarin/Xamarin.Forms#11645] opened 2020-08-04 10:07 UTC
CollectionView EmptyView in arabic on IOS is mirrored 

Steps to Reproduce

```
<CollectionView ItemsSource="{Binding Path=BindingContext.ReceivedReminders, Source={x:ReferenceName=DashBoardView}}" 
                                            EmptyView="ما من بنود ممكن عرضها">
....

</CollectionView>
```

- Xamarin.Forms 4.7.0.1080
- iOS:  13.5.1
- Affected Devices: iphone 6,7,8

Screenshots

![image](https://user-images.githubusercontent.com/11196273/89281769-3bac5200-d653-11ea-9cd2-9ffe8db495be.png)

**Comment by mohamadayash** [comment] 2020-08-04 13:57
A work around is to create an iOS renderer as follow:

[assembly: ExportRenderer(typeof(CollectionView), typeof(CustomCollectionViewRenderer))]
namespace MyApp.iOS.Renderers
{
class CustomCollectionViewRenderer : CollectionViewRenderer
    {

        protected override void OnElementChanged(ElementChangedEventArgs<GroupableItemsView> e)
        {
            base.OnElementChanged(e);
            if (Control.PreferredFocusEnvironments[0] is UICollectionView collectionView)
            {
                CollectionView cv = (CollectionView)e.NewElement;
                UICollectionView control = (UICollectionView)Control.PreferredFocusEnvironments[0];
                if (control.EffectiveUserInterfaceLayoutDirection == UIUserInterfaceLayoutDirection.RightToLeft)
                {

                    if (cv.EmptyView != null && cv.EmptyView is VisualElement)
                    {
                        var emptyView = (VisualElement)cv.EmptyView;
                        emptyView.ScaleX = -1;
                        emptyView.ScaleY = 1;
                    }
                    else if (cv.EmptyView is string)
                    {
                        cv.EmptyView = new Label()
                        {
                            Text = (string)cv.EmptyView,
                            VerticalOptions = LayoutOptions.Center,
                            HorizontalOptions = LayoutOptions.Center,
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            ScaleX = -1,
                            ScaleY = 1
                        };
                    }
                }
            }
        }
    }`
}

**Comment by darrabam** [comment] 2020-08-08 14:07
Another workaround purely using xaml EmptyView data template, I just don't like CustomRenderers ;)

![image](https://user-images.githubusercontent.com/33980667/89712380-42abcb00-d999-11ea-95b5-4ed8e24457cb.png)

**Comment by mohamadayash** [comment] 2020-08-09 08:54
> Another workaround purely using xaml EmptyView data template, I just don't like CustomRenderers ;)
> 
> ![image](https://user-images.githubusercontent.com/33980667/89712380-42abcb00-d999-11ea-95b5-4ed8e24457cb.png)

Nice workaround I liked it

**Comment by Sasha111ua** [comment] 2020-09-14 18:30
collectionview.header has the same problem

**Comment by hartez** [comment] 2021-02-06 16:18
This was fixed by #13247. Should be working correctly from 5.0.0.1931 onward.

**Closed by hartez** 2021-02-06 16:18 UTC
Labels: a/collectionview, e/3 :clock3:, t/bug :bug:

**Comment by hartez** [comment] 2021-02-06 16:19
Adding a repro project in case it's useful in the future:
[_11645 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5937176/_11645.Repro.zip)

**Comment by aalqouzi** [comment] 2021-02-17 14:42
The issue is appearing again when adding views to EmptyView, the content is mirrored in iOS only.

`<CollectionView.EmptyView>
                <Label
                    FontSize="Large"
                    HorizontalOptions="Center"
                    Text="ما من بنود ممكن عرضها"
                    VerticalOptions="Center" />
            </CollectionView.EmptyView>`
