### ISSUE TITLE
[Bug] Regression in XF5: SwipeView glitches when pulled out

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#13495] opened 2021-01-21 18:50 UTC
### Description

I am currently running XF 5.0.0-pre4 (locked to this version until https://github.com/xamarin/Xamarin.Forms/issues/13203 is fixed) and tested with the latest nightly build (5.0.1.1917-nightly).

This version seems to have a regression in the how the SwipeView is rendered.

Please see the following video of the issue:
https://user-images.githubusercontent.com/60286968/105397419-b2e99880-5c29-11eb-8362-f464663972cb.mov
(The SwipeView seems to get drawn fully stretched out for a fraction of a second -- this does not happen with XF 5.0.0-pre4).

iOS 14.2, ios:SwipeView.SwipeTransitionMode="Drag".

### Expected Behavior

The SwipeView should not have the glitch when pulled out.

### Actual Behavior

The SwipeView glitches briefly when pulled out.

### Basic Information

- Version with issue: 5.0.1.1917-nightly
- Last known good version: XF 5.0.0-pre4 (don't know exactly in which version this got broken)
- Platform Target Frameworks: 
  - iOS:  iOS 14.2

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio Community 2019 for Mac (Preview)
Version 8.9 Preview (8.9 build 1451)
Installation UUID: daace8a9-7979-4b83-abc1-309136692d2f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

Mono Framework MDK
Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

Xamarin Designer
Version: 16.9.0.266
Hash: c4842c761
Branch: remotes/origin/c4842c761b9b6a95407f72278ca7fb42f8f7fdf0
Build date: 2021-01-07 06:17:08 UTC

Roslyn (Language Service)
3.9.0-3.20619.14+df59a33fd9beff9790e01a2a1ab21e4a1e6921b3

NuGet
Version: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	5.0.101
	5.0.100
	3.1.405
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	5.0.1
	5.0.0
	3.1.11
	3.1.10
	3.1.9

.NET Core 3.1 SDK
SDK: 3.1.405

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.2 (17535)
Build 12B45b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 14.9.0.27 (Visual Studio Community)
Hash: f4c9327fa
Branch: main
Build date: 2020-11-19 10:57:31-0500

Xamarin.Android
Version: 11.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d16-9/f908d16
Android SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@1d382be
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.32.2@cfe06e0
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ad80a42

Microsoft OpenJDK for Mobile
Java SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.9.0.21
Hash: 57e40ba
Branch: remotes/origin/main
Build date: 2021-01-08 01:57:14 UTC

Android Device Manager
Version: 16.9.0.14
Hash: 0fdccda
Branch: remotes/origin/main
Build date: 2021-01-08 01:57:36 UTC

Build Information
Release ID: 809001451
Git revision: cfd15313a6388ef8dada0182e22a058131c46f9d
Build date: 2021-01-15 08:42:21-05
Build branch: release-8.9
Xamarin extensions: cfd15313a6388ef8dada0182e22a058131c46f9d

Operating System
Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

</details>

**Comment by jsuarezruiz** [comment] 2021-01-21 19:23
@Tommigun1980 Could you share a piece of code to see how you are creating the `SwipeView` Content and SwipeItems?. I am interested to know if you use SwipeItem, SwipeItemView, etc.

**Comment by Tommigun1980** [comment] 2021-01-22 05:27
> @Tommigun1980 Could you share a piece of code to see how you are creating the `SwipeView` Content and SwipeItems?. I am interested to know if you use SwipeItem, SwipeItemView, etc.

Hi @jsuarezruiz!

It is a SwipeView -> SwipeItems -> SwipeItem inside a DataTemplate coming from a DataTemplateSelector inside a ListView.
I replaced the ListView with a CollectionView and the issue does not happen with a CollectionView!

```xaml
                <SwipeView
                    IsEnabled="{Binding Message, Converter={StaticResource HasValueConverter}}"
                    ios:SwipeView.SwipeTransitionMode="Drag">
                    <SwipeView.RightItems>
                        <SwipeItems SwipeBehaviorOnInvoked="RemainOpen">
                            <SwipeItem
                                Text="Delete"
                                BackgroundColor="Red"
                                Invoked="OnChatMessage_Swiped" />
                        </SwipeItems>
                    </SwipeView.RightItems>

                    ...
```

(it uses RemainOpen as it's still using the workaround https://github.com/xamarin/Xamarin.Forms/issues/11643#issuecomment-668872047, as I haven't gotten around to removing it yet even though https://github.com/xamarin/Xamarin.Forms/issues/11643 has been fixed -- I don't know if it's relevant).

Considering it doesn't happen with the CollectionView I am good, but I'll be more than happy to help in case you guys want to take a closer look at this.

Thank you.

**Comment by jsuarezruiz** [comment] 2021-01-22 09:46
I have tried to reproduce the same behavior in a small example using Xamarin.Forms 5.0.1.1917-nightly:
[Issue13495.zip](https://github.com/xamarin/Xamarin.Forms/files/5854928/Issue13495.zip)

But I can't reproduce the glitch. Could you take a look to the example?

**Comment by jsuarezruiz** [comment] 2021-01-26 13:04
@Tommigun1980 Could you take a look to the previous attached sample? We must be doing something different. I can't reproduce the glitch.

**Comment by Tommigun1980** [comment] 2021-01-26 13:45
> @Tommigun1980 Could you take a look to the previous attached sample? We must be doing something different. I can't reproduce the glitch.

Hi. I will try to figure out what exactly causes the glitch today.
Unfortunately it started to happen with the CollectionView now as well, so it seems random as it doesn't happen every time. I didn't change anything between now and when I last tested it, so presumably some condition will need to happen for the bug to materialise. I'll try to isolate what exactly it is and add it to the repro case.

**Comment by Tommigun1980** [comment] 2021-01-26 14:40
[Issue13495.zip](https://github.com/xamarin/Xamarin.Forms/files/5873943/Issue13495.zip)

Hi @jsuarezruiz. Please find updated repro case in this project. A couple of notes:

1) It **never** happens on the first pull out, and **always** happens on consecutive pulls of the swipe items.
2) I removed the forced background color on the grid, as it was masking the issue. I have a background image and not a solid color on my background grid, so masking the issue with a background color is not an option.

Please let me know if you have trouble reproducing the issue with the updated repro case.

**Comment by Tommigun1980** [comment] 2021-01-26 17:22
I wonder if this is related to https://github.com/xamarin/Xamarin.Forms/issues/13307 and is a generic problem that regressed in 5.0.0-pre5? Ie modifications done to elements while invisible are not applied until drawn/interacted with?

**Comment by jsuarezruiz** [comment] 2021-01-27 11:30
Thanks for the feedback!. The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13557

**Closed** 2021-10-19 11:46 UTC
Labels: t/bug :bug:, p/iOS 🍎, e/3 :clock3:, in-progress, a/swipeview
