### ISSUE TITLE
[Enhancement] Android NavigationPageRenderer navigation behaviour

### ISSUE THREAD

**Issue by alexanderzuban** [xamarin/Xamarin.Forms#4995] opened 2019-01-16 03:27 UTC
## Summary
Will be great to change Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer OnClick handlers for the back button to be consistent with the hardware button. There are some "hacks" in forums with ways to customize back button behavior, and it seems they don't work with the master detail page.
 
## API Changes

Change 
 
`
public void OnClick(AView v)
		{
			Element?.PopAsync();
		}
`
and 
`
public void OnClick(AView v)
			{
				_element?.PopAsync();
			}
`
with the Element?.OnBackButtonPressed(); 

From source code default implementation if the OnBackButtonPressed does PopAsync but this will give a way to customize back behaviour in a unify way without ugly hacks.

**Comment by PureWeen** [comment] 2019-01-17 16:48
Pretty much a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/1944

We have a spec in the works to provide a more accurate API and most likely deprecate *OnBackButtonPressed* 

OnBackButtonPressed is specifically for the hardware back button

**Closed by PureWeen** 2019-01-17 16:48 UTC
Labels: t/enhancement ➕

**Comment by alexanderzuban** [comment] 2019-01-18 15:14
Great! Hope it is scheduled in a observable future :)
