### ISSUE TITLE
Broken cell height in ListView on XF 3.5

### ISSUE THREAD

**Issue by bares43** [xamarin/Xamarin.Forms#5206] opened 2019-02-11 21:28 UTC
### Description
On Android (iOS is ok) are mixed height of cells in ListView with uneven rows. Maybe it's related with other ListView issues in 3.5 like #5200 or #5184 

### Steps to Reproduce

1. Create ListView with HasUnevenRows=True and many cells with dynamic height
2. Scroll in list view

### Expected Behavior
Every cell should have right height, dependent on its content.

### Actual Behavior
Height of items are mixed.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.4.0.1029999
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.2.1

### Screenshots

**Broken - XF 3.5**
![Broken - XF 3.5](https://raw.githubusercontent.com/bares43/XFListViewIssue/master/images/wrong.png)

**OK - XF 3.4**
![OK - XF 3.4](https://raw.githubusercontent.com/bares43/XFListViewIssue/master/images/ok.png)

### Reproduction Link

[https://github.com/bares43/XFListViewIssue](https://github.com/bares43/XFListViewIssue)

**Comment by samhouts** [comment] 2019-02-13 23:29
Yep, confirmed this is the same root cause as #5184

**Comment by samhouts** [comment] 2019-02-13 23:29
Duplicate of #5184

**Closed** 2019-03-12 16:49 UTC
Labels: a/listview, e/2 :clock2:, i/regression, p/Android, t/bug :bug:
