### ISSUE TITLE
[Bug] CarouselView on iOS has a little padding on the up and left side

### ISSUE THREAD

**Issue by PTEC3D50** [xamarin/Xamarin.Forms#8970] opened 2019-12-19 13:55 UTC
### Description
On iOS the Carousel View has a little padding on the up and left side. 

### Steps to Reproduce

1.  Create a new project and make the update the Xamarin Forms Nuget
2.  Set The flags for add Carousel View on your AppDelegate class on your iOS Project
3. Add a Carousel View to your MainPage and inside a view with a blackground like red or blue. 

### Expected Behavior
The Carousel View have no padding (like on Android)

### Actual Behavior
The Carousel View has a little padding 

### Basic Information

- Version with issue:  4.4.0.991265
- Last known good version: / 
- IDE: Visual Studio

**Comment by rmarinho** [comment] 2019-12-19 17:21
can you show as an example of what you see and what you would expect  to be the padding.

I made a test and seems to work as expected. here are examples for iOS and Android

![image](https://user-images.githubusercontent.com/1235097/71194277-8bd0d280-2283-11ea-9831-b79e23592db4.png)

![image](https://user-images.githubusercontent.com/1235097/71194456-d7837c00-2283-11ea-8d9e-ab59a914de35.png)

**Comment by ddomengeaux** [comment] 2019-12-23 20:23
I am seeing the same thing on iOS only. 

Repo sample here: https://github.com/ddomengeaux/Bug8970

<img width="457" alt="Screen Shot 2019-12-23 at 2 22 40 PM" src="https://user-images.githubusercontent.com/5462178/71379091-c1c9cb80-258f-11ea-8777-4121968c57db.png">

**Comment by samhouts** [comment] 2020-01-03 00:03
Duplicate of #8961

**Closed by samhouts** 2020-01-03 00:03 UTC
Labels: a/carouselview, p/iOS 🍎, t/bug :bug:
