### ISSUE TITLE
[Bug] [UWP] LayoutChildren method is not called in custom control after upgrade Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by bharathirajauk** [xamarin/Xamarin.Forms#13492] opened 2021-01-21 17:32 UTC
### Description

I have created a custom control which is extended from ContentView in Xamarin.Forms. I have layout the **Content** for some scenario using LayoutChildren override method in Forms. This is working fine up to XF version 4.8. After upgrade to Xamarin.Forms 5.0, this LayouChildren override method is not called and Content also not displayed. I suspect that in Xamarin.Forms 5.0, layout process is not performed for Content.

**Note:** If i add the same custom control within Grid, custom control's Content is displayed. 

1. I simply created a small custom control to reproduce my issue. Created custom control in Xamarin.Forms

```
public class CustomContentView: ContentView
    {
        public CustomContentView()
        {
           
        }

        protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
        {
            return base.OnMeasure(widthConstraint, heightConstraint);
        }
        protected override void LayoutChildren(double x, double y, double width, double height)
        {
            base.LayoutChildren(x, y, width, height);
        }
    }
```

2. Created custom renderer for this Forms control in UWP renderer project. Native UWP control is extended from ContentPresenter. I have converted Forms content to native and set to content control's content. Then assigned content control to Native control. 
3. 
**Native control**

```
  public class CustomView : ContentPresenter
    {
        public CustomView()
        {
        }
    }
```

**Renderer class**

```
public class CustomRenderer : VisualElementRenderer<CustomControl.CustomContentView, CustomView>
    {
        private CustomView customView;
        public CustomRenderer()
        {
            this.AutoPackage = false;
        }
        protected override void OnElementChanged(ElementChangedEventArgs<CustomContentView> e)
        {
            if (e.NewElement == null)
            {
                return;
            }

            this.customView = new CustomView();
            this.customView.DataContext = this.Element.BindingContext;
            this.SetNativeControl(this.customView);

            if (Element.Content != null)
            {
                var renderer = Element.Content.GetOrCreateRenderer();
                var contentControl = new ContentControl();

                contentControl.Content = renderer.ContainerElement;
                this.customView.Content = contentControl;
            }
            base.OnElementChanged(e);
        }
    }
```

### Steps to Reproduce

1. Run the attached sample (Sample link given in Reproduction Link)
2. Added Button control as content in my custom control. But it is not displayed. 

### Expected Behavior

Content (Button) should be displayed

### Actual Behavior

Display with blank page.

### Basic Information

 - UWP:  All SDK version 
- NuGet Packages: Xamarin.Forms: 5.0.0.1905

### Reproduction Link

Sample link with custom control: https://github.com/bharathirajauk/MySamples/blob/master/CustomControl_XF5.0.zip?raw=true

**Comment by PureWeen** [comment] 2021-01-21 21:23
@hartez it looks like this is a regression from 

https://github.com/xamarin/Xamarin.Forms/pull/12017

It looks like because the Layout is no longer marshaled to the UI Thread the layout code never gets beyond this point

https://github.com/xamarin/Xamarin.Forms/blob/51d840a00e0f7a9fb481087b813c637e6b4d4058/Xamarin.Forms.Core/Layout.cs#L473

I'm guessing before when it was all being executed from `Device.BeginInvoke` that the renderers were getting attached before the layout code processed

**Comment by Tommigun1980** [comment] 2021-01-21 21:57
> @hartez it looks like this is a regression from
> 
> #12017
> 
> It looks like because the Layout is no longer marshaled to the UI Thread the layout code never gets beyond this point
> 
> https://github.com/xamarin/Xamarin.Forms/blob/51d840a00e0f7a9fb481087b813c637e6b4d4058/Xamarin.Forms.Core/Layout.cs#L473
> 
> I'm guessing before when it was all being executed from `Device.BeginInvoke` that the renderers were getting attached before the layout code processed

Could that commit also be causing the cause for https://github.com/xamarin/Xamarin.Forms/issues/13126#issuecomment-751310883? This regression was introduced in XF 5.0.0-pre5, and makes CollectionViews show up as empty.

https://github.com/xamarin/Xamarin.Forms/commit/c419953e86aa4de9a680439564abe69d60331ab5#diff-af8af62afd20e030f39b075a80366258189203886d6945708511607ee820d511R472 attempted to solve it (technically it solved https://github.com/xamarin/Xamarin.Forms/issues/13203, which was closed as fixed), but the issue still persists.

I am really at my wit's end with this one as it forces me to stay on XF 5.0.0-pre4, as it is the latest working version.
Thank you.

**Closed** 2021-02-05 21:16 UTC
Labels: 5.0.0, i/regression, in-progress, t/bug :bug:
