### ISSUE TITLE
Xamarin.forms 4.0.0.169046-pre5  ScrollView "Orientation=both" crashes on Android and iOS

### ISSUE THREAD

**Issue by Refka-Benmahmoud** [xamarin/Xamarin.Forms#5441] opened 2019-03-04 14:49 UTC
### Description
In ContentPage, ScrollView with property "Orientation=both" crashes the application in xamarin.forms 4.0.0.169046-pre5.

-- Platform Target Frameworks: 
-iOS
-Android
-not tested on UWP

**Comment by jcmanke** [comment] 2019-03-04 17:38
Duplicate of #5247 fixed by #5383

**Comment by samhouts** [comment] 2019-03-04 17:43
Duplicate of #5247

**Closed by samhouts** 2019-03-04 17:43 UTC
Labels: t/bug :bug:
