### ISSUE TITLE
[Bug] iOS crash on startup (SIGABRT) when updating to v4.5

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Xamarin.Forms#10271] opened 2020-04-09 05:17 UTC
After updating from Xamarin Forms 4.4.0.991640 to 4.5.0.495, my iOS builds are failing review due to a crash on startup.  Minimal code changes were made between these releases and I've only witnessed one build/device configuration myself where repeated attempts to launch crashed immediately before App Center could generate a crash report.  In all other cases, my testing on the simulator and three different devices running iOS 9.3.5, 12.4.5 and 13.4.1 have all run fine.

### Steps to Reproduce

1. Launch app on some iOS devices

### Expected Behavior
Should get splash screen and login

### Actual Behavior
Crashes immediately.  Crash logs indicate:

> Exception Type:  EXC_BAD_ACCESS (SIGABRT)
> Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
> VM Region Info: 0 is not in any region.  Bytes before following region: 4335779840
>       REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
>       UNUSED SPACE AT START
> --->  
>       __TEXT                 00000001026ec000-0000000102768000 [  496K] r-x/r-x SM=COW  ...S.app/TRC.iOS

### Basic Information
Repeated attempts to launch don't generate any crash reports from App Center, so this SIGABRT exception is happening very early.  **Did you by any chance make recent linker changes?**

- Version with issue:  Xamarin.Forms v4.5.0.495 & v4.5.0.530
- Last known good version:  Xamarin Forms v4.4.0.991640
- Xamarin 16.5000.533
- IDE: VS 2019 16.5.3
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS SDK 13.16.0.13
  - Deployment Target: 9.3
- Affected Devices:
 - iPad Air 3rd Gen (Wi-Fi Only):  Six instances during app review
 - iPhone 5S:  Witnessed with only one build

Note that I also updated Xamarin.Essentials to v1.5.2 and I use the Geolocator heavily.  I haven't changed the relevant keys in my Info.plist, though.  The geolocation features also seem to work normally in most cases, even if permission is denied or location services is disabled.

### Crash Logs

[attachment-8441424318993819585crashlog-DB9F837F-39C6-45EC-A55B-FA289F4496EC.txt](https://github.com/xamarin/Xamarin.Forms/files/4454154/attachment-8441424318993819585crashlog-DB9F837F-39C6-45EC-A55B-FA289F4496EC.txt)
[attachment-13654476269670716592crashlog-0782A52A-D756-45D0-B9DF-559E3ABA4C9A.txt](https://github.com/xamarin/Xamarin.Forms/files/4454156/attachment-13654476269670716592crashlog-0782A52A-D756-45D0-B9DF-559E3ABA4C9A.txt)
[attachment-16232193551272583459crashlog-669B874D-3162-44C9-BBA2-2406FE47BBD1.txt](https://github.com/xamarin/Xamarin.Forms/files/4454157/attachment-16232193551272583459crashlog-669B874D-3162-44C9-BBA2-2406FE47BBD1.txt)
[attachment-16894243783913967682crashlog-5E5364A0-DD92-4C8D-8A1E-E988085C20DD.txt](https://github.com/xamarin/Xamarin.Forms/files/4454158/attachment-16894243783913967682crashlog-5E5364A0-DD92-4C8D-8A1E-E988085C20DD.txt)
[attachment-7081511181916664364crashlog-E0AD848F-AF9A-4B94-B171-8B1B26957A45.txt](https://github.com/xamarin/Xamarin.Forms/files/4454159/attachment-7081511181916664364crashlog-E0AD848F-AF9A-4B94-B171-8B1B26957A45.txt)
[attachment-7887135452841600072crashlog-7D6005FC-3FC4-470D-B25E-0AA382EBF174.txt](https://github.com/xamarin/Xamarin.Forms/files/4454160/attachment-7887135452841600072crashlog-7D6005FC-3FC4-470D-B25E-0AA382EBF174.txt)

**Comment by Magendanz** [comment] 2020-04-09 05:40
Some others on StackOverflow recently reporting similar issues:
https://stackoverflow.com/questions/60873678/xamarin-ios-sigabrt-crash-on-startup
https://stackoverflow.com/questions/61104836/xaramin-forms-ios-application-crashes-at-startup

**Comment by spouliot** [comment] 2020-04-09 15:56
> Did you by any chance make recent linker changes?

Based on your description you did not updated Xamarin.iOS between the working and crashing apps. So no, there would not be any linker changes. They also generally would fail every time

> Crash Logs

The attached crash logs are not symbolicated so they are not, in this state, useful to diagnose the issue.

If you can crash the app locally then you should be able to open Xcode, get the symbolicated crash report (you might have to wait a bit for it to index) and attach them back to this issue.

**Comment by Magendanz** [comment] 2020-04-09 20:23
Looking at the only consistently repeatable case here, it seems to involve the iPad Air 3rd Gen (Wi-Fi Only).  What's unique about this hardware model (iPad11,3) is that it doesn't have a GPS module.  (Even my old iPad Mini from 2012 that I use to test iOS 9.3.5 includes a GPS module.)  Given that I'm using Xamarin.Essentials.Geolocator, is it possible that we're assuming a library that's not present on this particular device because it lacks GPS?  (Unfortunately, I don't have this particular model to confirm, but that might explain why I'm generally unable to reproduce the crash...even when I disable Location Services.)

**Comment by spouliot** [comment] 2020-04-09 20:53
@Magendanz It's a theory that fits the data you provided.

But only
* a symbolicated crash report 
* a small repro case

could answer that for sure :)

Can you create a small sample app that _should_ repro this ? (and if so attach it here). I (and others) have multiple devices (some Wifi only) so we should be able to confirm this.

**Comment by Magendanz** [comment] 2020-04-09 23:42
@spouliot, the problem is that only the Apple review team seems to be able to reproduce this crash.  I've only seen it once, and I'm not even convinced that it was caused by the same issue.  I'll be ready to generate a symbolicated crash report when I do, but without the device that has consistently been able to reproduce the bug, I can't give you any of the things that you're asking for.  I also don't think it's appropriate that I use the App Store review process as my only way of reproducing the crash, and every attempt would take days.  That's just not feasible.

**Comment by rezamohamed** [comment] 2020-04-10 06:30
When I upgraded to 4.6.0.529 Pre3 I was seeing this along with crashes in Main.cs when I press the home button when inside the app. It was really hard to debug this, luckily I had the same app on a different machine, and the only difference was that it had 4.6.0.494 pre2. After I downgraded my primary solution back to pre2 it seems to be working fine (fingers crossed) but I will keep an eye out.

**Comment by Magendanz** [comment] 2020-04-24 23:33
I think we may have discovered the root cause in Xamarin.Essentials.  https://github.com/xamarin/Essentials/issues/1238

**Comment by samhouts** [comment] 2020-05-30 00:07
Duplicate of xamarin/Essentials#1238

**Closed by samhouts** 2020-05-30 00:07 UTC
Labels: external-macios, s/unverified, t/bug :bug:
