### ISSUE TITLE
Xamarin Forms Android - App won't start after changing OS time to earlier date

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11176] opened 2020-06-23 14:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1084385/xamarin-forms-android-app-wont-start-after-changin.html)._

---
I encounter a problem where my Xamarin Forms Android app won't start (blank screen) after I change the Android OS date to an earlier date. I only happens when it's not connected through the debugger.

I'm using the latest version of Visual Studio and Xamarin. At the time of this post, I tested with:

- Visual Studio 2019 - 16.6.2 (Also happens in 16.5.3)
    - Xamarin Forms 4.7.0.968 (Also happens in previous 4.X versions)
    - Phone: Samsung Galaxy S8, Android 9.

Steps to reproduce:

1) Create the sample Xamarin Forms app using the "Blank Page" template.
    2) Run it through the debugger first (The app works and displays the welcome message).
    3) Close the app.
    4) Set the OS date/time to manual and go back one day.
    5) From the phone itself (without using the debugger), run the app.

After the last step, the app won't start but will instead display a blank screen. No crash. Resetting the time to automatic date when the app is closed, the app will run correctly again. If I do the same procedure but always start the app using the debugger, everything works fine.

Thanks for your time.

---
#### gilles-philippe.paille on 6/18/2020, 01:02 PM: 

<p>Additional info: It also happens in Release mode. Moreover, since it doesn't happen when the debugger is attached, I added logs that I retrieve with logcat. Using this method, I realized that when it freezes, it doesn't even seem to reach the "OnCreate" method of my "MainActivity".</p>

#### Visual Studio Feedback System on 6/19/2020, 01:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-06-23 16:02
Duplicate of #11128

**Closed by samhouts** 2020-06-23 16:02 UTC
Labels: feedback-ticket, p/Android, s/unverified, t/bug :bug:
