### ISSUE TITLE
Xamarin.Forms : CommandParameter no longer working on  buttons in a listview (MVVM + Prism)

### ISSUE THREAD

**Issue by chenaimt** [xamarin/Xamarin.Forms#9238] opened 2020-01-17 01:37 UTC
### Steps to Reproduce

1. Include the CommandParameter binding on a button in a datatemplate (list view). Run the code
2. Include the CommandParameter binding on a button in a datatemplate (list view). Run the code
3. 

### Expected Behavior
The listviews should populate with all controls including buttons. The buttons should also work accordingly when clicked

### Actual Behavior
The listviews are created with empty rows. If you hover over with a mouse you will see the rows that have been created but at first sight it just looks like an empty page

### Basic Information
The code has been working till the update

- Version with issue: 4.4.0.991477
- Last known good version: Most likey 4.1.0.618606
- IDE: Visual Studio 2019
- Platform Target Frameworks: .Net Standard 2.0
  - iOS:  NA
  - Android: NA
  - UWP:  Windows 10 version 1809, Build 17763
- Android Support Library Version: NA
- Nuget Packages: Many including Sqlite, Prism, XamarinForms, .Net, Flurl, etc
- Affected Devices: All

### Screenshots
![image](https://user-images.githubusercontent.com/51409372/72577197-8397a180-38da-11ea-94c1-ba7881242b65.png)

### Workaround

I am going to try to roll back Xamarin.Forms

**Comment by chenaimt** [comment] 2020-01-17 02:00
Rolled back my Xamarin.Forms and my listviews now display the data correctly
![image](https://user-images.githubusercontent.com/51409372/72578153-ef2f3e00-38dd-11ea-8a34-c44bc5e9f4ed.png)

**Comment by StephaneDelcroix** [comment] 2020-01-17 15:55
could you please provide a reproduction project ? thanks

**Comment by PureWeen** [comment] 2020-01-17 16:56
This is a duplicate of 
https://github.com/xamarin/Xamarin.Forms/issues/8918

It's interesting because if you just use our command and not prisms everything works fine but it's definitely a regression

**Closed by PureWeen** 2020-01-17 16:56 UTC
Labels: i/regression, s/needs-repro ❔, s/unverified, t/bug :bug:
