### ISSUE TITLE
Xamarin IOS EntryRenderer throw exception

### ISSUE THREAD

**Issue by haiduong741** [xamarin/Xamarin.Forms#14869] opened 2021-11-11 08:47 UTC
### Description
I have a Entry on IOS 12.4, When EntryRenderer dispose, my application throw a exception:
Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <...CustomEntryBaseRenderer 0x7fbd4094a330> for the key path "sublayers" from <CALayer 0x600007f03f40> because it is not registered as an observer.
Native stack trace:
	0   CoreFoundation                      0x0000000107b988db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011597cac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107b98735 +[NSException raise:format:] + 197
	3   Foundation                          0x000000011051d425 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 488
	4   Foundation                          0x000000011051d8ac -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   FastMobileDevice.iOS                0x0000000106fada99 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x000000013da2e19e 0x0 + 5329052062

###Stack trace
  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:449 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:392 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
  at Foundation.NSObject.RemoveObserver (Foundation.NSObject observer, Foundation.NSString keyPath) [0x00020] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/Foundation/NSObject.g.cs:415 
  at Xamarin.Forms.Platform.iOS.EntryRendererBase`1[TControl].Dispose (System.Boolean disposing) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\EntryRenderer.cs:96 
  at FastMobile.FXamarin.Core.FiOS.FEntryBaseRenderer.Dispose (System.Boolean disposing) [0x00002] in E:\FastMB\Version5\5.0\FastMobile.FXamarin.Core.FiOS\Renderer\FEntryBaseRenderer.cs:52 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
  at Foundation.NSObject.RemoveObserver (Foundation.NSObject observer, Foundation.NSString keyPath) [0x00020] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/Foundation/NSObject.g.cs:415 
  at Xamarin.Forms.Platform.iOS.EntryRendererBase`1[TControl].Dispose (System.Boolean disposing) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\EntryRenderer.cs:96 
  at ...CustomEntryBaseRenderer.Dispose (System.Boolean disposing) [0x00002] in ...CustomEntryBaseRenderer.cs:52 

- Version with issue:
- Last known good version 5.0.0.1xxx:
- Platform Target Frameworks: 
  - iOS:  12.4

**Comment by lee-m** [comment] 2021-11-11 09:06
Dupe of #14804

**Comment by jfversluis** [comment] 2021-11-11 13:15
Duplicate of #14804

**Closed by jfversluis** 2021-11-11 13:15 UTC
Labels: t/bug :bug:, s/unverified
