### ISSUE TITLE
[Bug] How to create custom entry

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#11312] opened 2020-07-04 05:33 UTC
Hello,
as am new to this platform I have no idea how to create a custom entry like this with a label (field name) on the border of the entry
![3](https://user-images.githubusercontent.com/39983941/86505711-ef68ba80-bde5-11ea-8def-13b8d0b15d87.PNG)

Please Help!!!!!

**Comment by EmilAlipiev** [comment] 2020-07-05 14:29
Hi, this is not a bug and you should ask your question on[ Xamarin.forum](https://forums.xamarin.com/) or stackoverflow. there are more important issues here. Beside that your screenshot looks like syncfusion tool. if it is syncfusion, go to syncfusion forum and ask there please. you will get faster answer. thanks for your understanding.

**Comment by StephaneDelcroix** [comment] 2020-07-08 09:12
I see that you've created a discussion for ti already. closing

**Closed by StephaneDelcroix** 2020-07-08 09:12 UTC
Labels: a/entry, s/unverified, t/bug :bug:, t/question
