### ISSUE TITLE
[iOS] CollectionView selection does not happen in iOS 13.4

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#10160] opened 2020-04-01 09:07 UTC
### Description
Selection in CollectionView does not happen in iOS 13.4. Works fine in Android and UWP.

### Steps to Reproduce

1. Run the sample in iOS 13.4
2. Select an item
3. Note: Item does not select.

### Expected Behavior
The collection view item should select when tapping the item.

### Actual Behavior
Item will not be selected.

### Basic Information
When updating Mac to the below configuration, CollectionView selection stops working in the iOS platform.

**Configuration**:
Mac Catalina 10.15.4
VS2019 to 16.5.2
Xamarin VS package 13.6.0.11

- Version with issue: XF 4.5.0.495
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  iOS 13.4, XCode 11.4
  - Android:  
  - UWP:   

### Reproduction Link

[CollectionViewSelectionIssue](https://www.syncfusion.com/downloads/support/directtrac/general/ze/CollectionViewSelectionIssue_74357279-1100279715)

**Comment by solomonfried** [comment] 2020-04-01 12:44
Likely closely associated to this
[Bug] [iOS] GestureRecognizers not working in iOS 13.4

(https://github.com/xamarin/Xamarin.Forms/issues/10162)

**Comment by samhouts** [comment] 2020-04-01 23:06
Duplicate of #10162

**Closed by samhouts** 2020-04-01 23:06 UTC
Labels: s/unverified, t/bug :bug:
