### ISSUE TITLE
Android Editor - Text selection menu does not appear when selecting text on an editor placed within a ScrollView

### ISSUE THREAD

**Issue by SachinCS1992** [xamarin/Xamarin.Forms#8291] opened 2019-10-29 16:53 UTC
### Description
Cannot get text selection menu to show in Android editor if  the editor lives in the following hierarcy:
TabbedPage
---ScrollView
------Editor

### Steps to Reproduce
1. On any Android device, create any layout with an editor placed inside a ScrollView, which lives inside a TabbedPage
2. Type in some text
3. Try to select a word by long pressing or double tapping - notice it doesn't show up the text selection menu to be able to copy/paste/select text

### Expected Behavior
Show text selection menu when selecting a text on editor.

### Actual Behavior
No text selection menu shown when selecting a text on editor inside a ScrollView, which lives inside a TabbedPage

### Basic Information
- **Version with issue**: 4.0.0.618610 and above
- **Last known good version:** 4.0.0.540366
- **IDE:** VS 2019 for Windows and Mac
- **Platform Target Frameworks:** 
  - Android: 9.0
- **Nuget Packages**: Xamarin.Forms 4.0.0.540366
- **Affected Devices:** All Android devices
- Possible **PR** that introduced the issue - **#6390** 

### Screenshots

![EditorIssue](https://user-images.githubusercontent.com/3442194/67789669-4276ba80-fa6c-11e9-8128-888ac759ff0a.gif)

**Comment by hartez** [comment] 2019-10-31 03:29
@SachinCS1992 I'm trying to reproduce this issue, but so far I'm not having any luck. In the attached project, I have an Editor inside of a ScrollView, and long press works just fine to select text and pull up the cut/copy/paste menu. Is there some detail I'm missing?

[_8291 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3792051/_8291.Repro.zip)

**Comment by SachinCS1992** [comment] 2019-10-31 10:16
@hartez I just tried your repro and compared it against my use case - just noticed that the ScrollView actually needs to be inside a TabbedPage for the issue to occur. I've updated the issue above, and your repro to replicate the issue and re-uploaded it for your perusal, thanks.
[_8291.Repro_modified.zip](https://github.com/xamarin/Xamarin.Forms/files/3793252/_8291.Repro_modified.zip)

**Comment by SachinCS1992** [comment] 2019-11-06 09:41
@hartez have you had a chance to review updated repro steps from above?

**Comment by hartez** [comment] 2019-11-11 23:50
Yep, that update repro definitely demonstrates this issue. 

Also ... that's weird.

**Comment by SachinCS1992** [comment] 2019-12-12 10:16
Any updates on this? It's causing a lot of frustration and headache for thousands of our customers. Also haven't been able to find a workaround without removing them from under a tabbed page or a scrollview, but it's not feasible in the context/use-case of our applications.

Any updates would be appreciated, thanks.

**Comment by craigwi** [comment] 2019-12-15 01:57
I'd like to see this fixed too.  In my case, the editor parents up to a ContentPage.  If I remove the ScrollView in the middle, the issue goes away.

**Comment by AmrAlSayed0** [comment] 2019-12-15 05:52
Does it have to do with the fact that the application is listening to 2 types of swipes now and it is blocking the selection gesture as a possible swipe? Vertical swipes for the ScrollView, Horizontal for the Tab switching? Try disabling swipe tab switching and see what happens.

**Comment by craigwi** [comment] 2019-12-15 18:25
There is no horizontal scrolling or swiping in my case.

**Comment by SachinCS1992** [comment] 2019-12-15 21:13
No horizontal scroll/swipe in my case either. I think it's the PR I've linked to in the above description is what introduced this issue.

**Comment by TingtingAn** [comment] 2020-01-19 07:57
same issue here.  Any plan to fix?

**Comment by juniorba** [comment] 2020-01-22 18:07
I'm using version 4.3.0.908675 of Xamarin Forms Android. After adding scrollview, the copy-paste inside editor stops working. Does anyone have a workaround for this issue?

`Example:
    <ContentPage.Content>
        <ScrollView>
            <StackLayout>
                <Editor HeightRequest="100"></Editor>
            </StackLayout>
        </ScrollView>       
    </ContentPage.Content>`

**Comment by IzyPro** [comment] 2020-04-11 19:18
I'm facing this issue also..... Is there a work around for this?
Like a custom renderer or something

**Comment by saamerm** [comment] 2020-04-13 20:16
Seems like the bug should be fixed in this file : https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.Android/Renderers/ConditionalFocusLayout.cs
There was no changes made there since 2017 so it seems to be an old bug.

Also, there were changes made in other files related to the Editor, but none of them seemed relevant.

**Comment by PureWeen** [comment] 2020-04-21 23:03
It looks like this is a bug on the google side

https://issuetracker.google.com/issues/37095917
I added this to our EditorRenderer and it starts to work after that

PR Incoming 

In the mean time you can use a custom renderer and copy the code below which should resolve for you

```C#
		protected override void OnAttachedToWindow()
		{
			base.OnAttachedToWindow();

			EditText.Enabled = false;
			EditText.Enabled = true;
		}
```

**Comment by JohnSpahr** [comment] 2020-04-23 00:15
I had an issue like this where the menu didn't appear when I used ```Navigation.PushAsync()```. I was able to fix this by switching to ```Naviation.PushModalAsync()```. I don't know if this is of any help, but it fixed the issue for me.

**Comment by PureWeen** [comment] 2020-04-23 00:22
Here's a link to the nuget if anyone would like to test this out

https://dev.azure.com/xamarin/public/_build/results?buildId=17360&view=artifacts&type=publishedArtifacts

**Closed** 2020-04-27 09:25 UTC
Labels: 4.0.0, e/4 :clock4:, i/regression, in-progress, p/Android, t/bug :bug:
