### ISSUE TITLE
[Android] multi clicks make picker dialog fires many times

### ISSUE THREAD

**Issue by minaairsupport** [xamarin/Xamarin.Forms#5061] opened 2019-01-25 17:23 UTC
### Description
when the user clicks many times in a fast way at the picker , it fires dialog multiple times 
### Steps to Reproduce

1. create a picker 
2. fill with data 
3. click many times in a fast way 

### Expected Behavior
old dialog closed before new one opened 
### Actual Behavior
many instances of dialogs appears 
### Basic Information

- Version with issue: All Version , 
- Last known good version:
- IDE: visual studio mac 
- Platform Target Frameworks: 
  - Android: All APIs 

actually, I have a solution to this bug as well , just before showing the dialog check if it already displayed dismiss old one or dont show it at all 

the source code 

	```
                void OnClick()
		{
			Picker model = Element;
			var picker = new NumberPicker(Context);
			if (model.Items != null && model.Items.Any())
			{
				picker.MaxValue = model.Items.Count - 1;
				picker.MinValue = 0;
				picker.SetDisplayedValues(model.Items.ToArray());
				picker.WrapSelectorWheel = false;
				picker.DescendantFocusability = DescendantFocusability.BlockDescendants;
				picker.Value = model.SelectedIndex;
			}

			var layout = new LinearLayout(Context) { Orientation = Orientation.Vertical };
			layout.AddView(picker);

			ElementController.SetValueFromRenderer(VisualElement.IsFocusedPropertyKey, true);

			var builder = new AlertDialog.Builder(Context);
			builder.SetView(layout);
			builder.SetTitle(model.Title ?? "");
			builder.SetNegativeButton(global::Android.Resource.String.Cancel, (s, a) =>
			{
				ElementController.SetValueFromRenderer(VisualElement.IsFocusedPropertyKey, false);
				// It is possible for the Content of the Page to be changed when Focus is changed.
				// In this case, we'll lose our Control.
				Control?.ClearFocus();
				_dialog = null;
			});
			builder.SetPositiveButton(global::Android.Resource.String.Ok, (s, a) =>
			{
				ElementController.SetValueFromRenderer(Picker.SelectedIndexProperty, picker.Value);
				// It is possible for the Content of the Page to be changed on SelectedIndexChanged. 
				// In this case, the Element & Control will no longer exist.
				if (Element != null)
				{
					if (model.Items.Count > 0 && Element.SelectedIndex >= 0)
						Control.Text = model.Items[Element.SelectedIndex];
					ElementController.SetValueFromRenderer(VisualElement.IsFocusedPropertyKey, false);
					// It is also possible for the Content of the Page to be changed when Focus is changed.
					// In this case, we'll lose our Control.
					Control?.ClearFocus();
				}
				_dialog = null;
			});

			_dialog = builder.Create();
			_dialog.DismissEvent += (sender, args) =>
			{
				ElementController?.SetValueFromRenderer(VisualElement.IsFocusedPropertyKey, false);
			};
			_dialog.IsShowing{
				_dialog.Dismiss();
			}
			_dialog.Show();
		}
```

[Reference](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs#L169)

**Comment by samhouts** [comment] 2019-01-26 17:57
Duplicate of #4909

**Closed by samhouts** 2019-01-26 17:57 UTC
Labels: t/bug :bug:
