### ISSUE TITLE
 Could not resolve type with token 01000015 from typeref (expected class 'Xamarin.Forms.Xaml.Diagnostics.VisualDiagnostics

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11362] opened 2020-07-08 15:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1095737/xamarin-app-wont-start.html)._

---
[regression] [worked-in:16.6.2]
System.TypeLoadException: 'Could not resolve type with token 01000015 from typeref (expected class 'Xamarin.Forms.Xaml.Diagnostics.VisualDiagnostics' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')'

this error occurs when initializecomponent() is executed in App.xaml.cs

I have tried deleting the bin and obj directories from all the projects in the solution and then rebuilding the solution but that has not fixed the problem.  The project was starting ok.  It quit starting while I was attempting to step through the code to track down another issue.  (The CanExecute method for a register command is not being executed.  I still don't have a solution for that issue but can't even begin to step through the code now.  After this problem is fixed I will have to submit another problem report.)

Here is the code in App.xaml.cs

using Xamarin.Forms;
using MyStuff.Model;
using Microsoft.WindowsAzure.MobileServices;
using Microsoft.WindowsAzure.MobileServices.Sync;
using Microsoft.WindowsAzure.MobileServices.SQLiteStore;

namespace MyStuff
{
    public partial class App : Application
    {
        public static string DatabaseLocation = string.Empty;

        public static MobileServiceClient client
            = new MobileServiceClient("https://mystuff.azurewebsites.net");
        public static IMobileServiceSyncTable<Password> passwordsTable;

        public static Password user = new Password();
        public App()
        {
            InitializeComponent();

            MainPage = new NavigationPage(new MainPage()); 
        }
        public App(string databaseLocation)
        {
            InitializeComponent();  **THE ERROR OCCURS HERE**

            MainPage = new NavigationPage(new MainPage());

            DatabaseLocation = databaseLocation;

        }
        protected override void OnStart()
        {
        }

        protected override void OnSleep()
        {
        }

        protected override void OnResume()
        {
        }
    }
}

Here is the csproj contents.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Mobile.Client" Version="4.1.2" />
    <PackageReference Include="Microsoft.Azure.Mobile.Client.SQLiteStore" Version="4.1.2" />
    <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Plugin.Permissions" Version="3.0.0.12" />
    <PackageReference Include="sqlite-net-pcl" Version="1.6.292" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Forms" Version="4.7.0.968" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CategoryListPage.xaml.cs">
      <DependentUpon>CategoryListPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="NewPasswordPage.xaml.cs">
      <DependentUpon>NewPasswordPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="SourceListPage.xaml.cs">
      <DependentUpon>SourceListPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="CategoryListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="DocListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="HomePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="ItemDetailPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="ItemListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="NewCategoryPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="NewItemPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="NewPasswordPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="NewSourcePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PasswordListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PicListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="RegisterPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="SourceListPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>

---
#### Feedback Bot on 6/29/2020, 10:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Emanuel Fernandez Dell'Oca [MSFT] on 7/1/2020, 03:08 PM: 

<p>Hi!<br>
In order to identify the root cause of this problem we’ll need more information from your side. Could you answer the following questions?<br>
1- Does this happen with an specific platform (iOS or Android)?<br>
2- If it’s only happening with iOS, does it happen when using a simulator, a device connected to a Mac or Hot Restart?<br>
3- Could you attach the content of the Debug output pane?<br>
4- Did you make any change on your XAML files or updated the Xamarin.Forms version before this problem started to happen?</p>
<p>Thanks for your help!</p>

#### durbinjw on 7/3/2020, 10:20 AM: 

<p>I am having trouble responding to your request.  I add the answers in this window and click submit and see no changes in the problem report and receive no acknowledgment that the answers have been submitted.</p>

#### durbinjw on 7/3/2020, 10:26 AM: 

<p>Try this simplified answer</p><p>Android emulator is being used. Not using iOS debugging.  No changes to XAML or Xamarin.Forms.</p><p>Maybe there is another way to submit the development system information, the compiler output, and the debug output.  The submission seems to fail when those are inserted.  I have tried submission using both Viasat and Edge browsers.  Lenovo S340 with VS 16.6.2 (just upgraded tp 16.6.3 yesterday - same error) </p><p>Jim</p>

#### durbinjw on 7/3/2020, 10:27 AM: 

(private comment, text removed)
#### durbinjw on 7/3/2020, 10:28 AM: 

(private comment, text removed)
#### durbinjw on 7/3/2020, 10:28 AM: 

<p>Microsoft Visual Studio Community 2019 (2)
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Community
Visual C++ 2019   00435-60000-00000-AA113
Microsoft Visual C++ 2019
ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools
ASA Service Provider   1.0
ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019
ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.
ASP.NET Web Frameworks and Tools 2019   16.6.954.58314
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio
Azure Functions and Web Jobs Tools   16.6.954.58314
Azure Functions and Web Jobs Tools
Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio
C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events
IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info
Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query
Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio
Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1
Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.
NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.
Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
VisualStudio.DeviceLog   1.0
Information about my package
VisualStudio.Foo   1.0
Information about my package
VisualStudio.Mac   1.0
Mac Extension for Visual Studio
Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3
Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.</p>

#### durbinjw on 7/3/2020, 10:29 AM: 

<p>OS NameMicrosoft Windows 10 Home
Version10.0.18362 Build 18362
Other OS Description Not Available
OS ManufacturerMicrosoft Corporation
System NameJIM5
System ManufacturerLENOVO
System Model81QF
System Typex64-based PC
System SKULENOVO_MT_81QF_BU_idea_FM_IdeaPad S340-15IWLTouch
ProcessorIntel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/DateLENOVO ALCN28WW(V2.05), 11/25/2019
SMBIOS Version3.0
Embedded Controller Version2.28
BIOS ModeUEFI
BaseBoard ManufacturerLENOVO
BaseBoard ProductLNVNB161216
BaseBoard VersionSDK0J40709 WIN
Platform RoleMobile
Secure Boot StateOff
PCR7 ConfigurationElevation Required to View
Windows DirectoryC:\Windows
System DirectoryC:\Windows\system32
Boot Device\Device\HarddiskVolume1
LocaleUnited States
Hardware Abstraction LayerVersion = "10.0.18362.752"
User NameJIM5\Jim
Time ZonePacific Daylight Time
Installed Physical Memory (RAM)12.0 GB
Total Physical Memory11.8 GB
Available Physical Memory3.39 GB
Total Virtual Memory20.3 GB
Available Virtual Memory8.74 GB
Page File Space8.50 GB
Page FileC:\pagefile.sys
Kernel DMA ProtectionNot Available
Virtualization-based securityNot enabled
Device Encryption SupportElevation Required to View
Hyper-V - VM Monitor Mode ExtensionsYes
Hyper-V - Second Level Address Translation ExtensionsYes
Hyper-V - Virtualization Enabled in FirmwareYes
Hyper-V - Data Execution ProtectionYes</p>

#### durbinjw on 7/3/2020, 10:32 AM: 

<p>had to insert the dev environment and system information by themselves and click submit.  also added the compiler output the same way.  Submission fails if they are included with other text in the comments.</p>

#### Feedback Bot on 7/6/2020, 02:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### durbinjw on 7/6/2020, 02:32 PM: 

<p>When can I expect that to happen?  The last issue I submitted was about synchronization between the mobile database and an Azure database and I never heard anything after the notification that it was also triaged.  That was weeks ago.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment] 2020-07-08 15:40
This likely indicates a mismatch between the XF version used to compiled some project in the solution, and the version picked at runtime (https://stackoverflow.com/questions/41163887/could-not-resolve-type-with-token-0100000f).

Make sure ALL version of XF are in sync, in all projects.

If the problem persists, please attach a small project reproducing the issue.

**Comment by StephaneDelcroix** [comment] 2020-07-08 15:42
> When can I expect that to happen?

RIGHT NOW. IT'S HAPPENING. LIVE.

Sorry about the other issue not triaged in a timely manner. We do our best, really, but sometimes it's not enough.

**Comment by durbinjw** [comment] 2020-07-10 20:18
1.  VS Xamarin Mystuff solution has three projects.  Mystuff, Mystuff.Android, Mystuff.iOS.  Mystuff project in solution explorer shows a dependencies node that has Xamairn.Forms (4.7.0.968) and Xamarin.Essentials (1.5.3.2).  Xamarin.Android project solution explorer shows a References node with Xamarin.Forms and Xamarin.Essentials listed but without a version number.  Similar for the Mystuff.iOS project. **Bottom line is that there is no way to ensure the versions are the same through Solution Explorer.**

2.  I followed this procedure and it did not help - exact same error:  Stop  the debug session; Run Build - Clean Solution;  Close the project;  Delete the bin and obj directories in all three projects; Open the Mystuff solution through file - Start Menu;  Rebuild Solution; Start the debug either from the debug menu or from the debug start button.  **I am expecting this procedure to rebuild using the same version of Xamarin.Forms and Xamarin.Essentials in all three projects.**

3.  When I open Help - Send Feedback - Report a problem from the VS project, the Visual Studio Feedback window opens and it shows that my problem report for "xamarin app wont start" has a status of c"Closed - Duplicate"  **However, I have received no notification via email that the status was changed , and furthermore, no indication of what the solution is.**

4.  To get to this point, I had to log directly into Git, at which time I could see the latest comments from Samhouts suggesting that the version of XF had to be the same in all projects.  See comment one above - there seems to be no direct way of doing that through Solution explorer.  **The fact that I received no notification would probably have resulted in the problem report being marked as closed due to lack of feedback from me.  - NOT GOOD.**

5.  I should say that I have another totally different solution for a tutorial in a separate directory.  That solution compiles and executes correctly.  Could there be some kind of hidden relationship between the packages for the two solutions?  The Xamarin packages are the same for both solutions.

**Comment by durbinjw** [comment] 2020-07-10 21:42
I looked at that link re managing the packages.  It recommends running git clear -xfd.  It does not say what environment to use to do that.  Is it done from VS?  Is it done from a directory?  What directory?  Does it required installing a Git application?  Please clarify.

**Comment by durbinjw** [comment] 2020-07-10 21:47
re point 4 in my previous comments.  there seems to be confusing and inadequate information for doing a problem report from VS.  It tells me this current problem is Closed - Duplicate.  It provides no way to follow up.  I hope that I will receive an email notification through this Git group that something has been done or needs to be done,  And I hope that problems will not be marked as closed in the VS problem reporting when they have not been resolved through this group.

**Comment by PureWeen** [comment] 2020-07-10 21:50
> Bottom line is that there is no way to ensure the versions are the same through Solution Explorer.

If you go into 'manage nuget' for the SLN do they all have the same version?

> I looked at that link re managing the packages. It recommends running git clear -xfd.

This mainly applies if your solution is managed by git. If it is then you type it from the root directory at the command line

> And I hope that problems will not be marked as closed in the VS problem reporting when they have not been resolved through this group.

The issues are closed on vsfeedback so we can make sure to consolidate all the information. It's not going to get closed here because it's closed there

**Comment by durbinjw** [comment] 2020-07-10 22:32
Hi Shane,

They should be marked as "pending in github", not as closed.

The Mystuff solution is not under source control at present.

I did not know that I could bring up manage nugget by right clicking in the
references for the android an iOS projects.  They were different.
Corrected that and the project now comes up.  Many thanks for the hint.  I
am new to Xamarin.  Can now proceed with development.  I will submit a
couple of new issues separately.  Have a toolbar button that is not being
enabled and an Azure / local db sync problem.

Jim

**Comment by PureWeen** [comment] 2020-07-10 23:11
Hey @durbinjw sorry about all the issues getting going and really appreciate all your comments here. It's always insightful to see these processes through the lens of someone new to Xamarin. I'll close this issue for now but I'm pinging a couple people below who are in charge of the areas you've had some issues with.

The Nuget experience can definitely be frustrating for new users

> I did not know that I could bring up manage nugget by right clicking in the references for the android an iOS projects.  

FYI @JonDouglas 

> They should be marked as "pending in github", not as closed.
> When I open Help - Send Feedback - Report a problem from the VS project, the Visual Studio Feedback window opens and it shows that my problem report for "xamarin app wont start" has a status of c"Closed - Duplicate" However, I have received no notification via email that the status was changed , and furthermore, no indication of what the solution is.
> 
> To get to this point, I had to log directly into Git, at which time I could see the latest comments from Samhouts suggesting that the version of XF had to be the same in all projects. See comment one above - there seems to be no direct way of doing that through Solution explorer. The fact that I received no notification would probably have resulted in the problem report being marked as closed due to lack of feedback from me. - NOT GOOD.

FYI @samhouts

**Closed by PureWeen** 2020-07-10 23:11 UTC
Labels: a/Xaml </>, a/buildchain, feedback-ticket, s/needs-info ❓, s/unverified, t/bug :bug:
