### ISSUE TITLE
[Bug] [UWP] Picker Height

### ISSUE THREAD

**Issue by dannythomas13** [xamarin/Xamarin.Forms#8439] opened 2019-11-08 20:31 UTC
After updating from Xamarin 3 to 4 I noticed that the picker control (ends up as combobox) now has a height so small I can no longer see its contents or select from it. It works fine on iOS, has anyone else seen this issue?

**Comment by hartez** [comment] 2019-11-08 20:35
@dannythomas13 When you say "3 to 4" - which version of 4?

If it's 4.3, then you might be experiencing the same thing as #8177/#8333/#8307, where the Picker simply ends up having no items in it. If that's the issue, you can expect a fix in the next service release for 4.3.

**Comment by dannythomas13** [comment] 2019-11-08 20:41
Thanks @hartez I manually put some items in the xaml and now it at least opens but still a difference in height, I'm guessing the HeightRequest of 50 put a nice chunky box in v3 but no longer in v4, has anyone noticed this?

**Comment by dannythomas13** [comment] 2019-11-08 20:43
Ok, so rolling back to v4.2 fixed the issue...I'm now worried that I may bring in another issue that has been fixed since :(

**Comment by hartez** [comment] 2019-11-11 23:41
Repro project:
[_8439 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3833612/_8439.Repro.zip)

There's an extra space at the top of the Picker in 4.3, and that compresses the height of the actual combo box.

Notice the difference between 3.6:
![3dot6](https://user-images.githubusercontent.com/538025/68629691-f121ee80-04a1-11ea-8a40-3b1f366d4f5e.png)


And 4.3:
![4dot3](https://user-images.githubusercontent.com/538025/68629697-f54e0c00-04a1-11ea-8e2c-dbec6b619703.png)

**Comment by joshminor** [comment] 2019-11-14 21:18
The gap is caused by a new header content control that wasn't previously there.
![pickerissue](https://user-images.githubusercontent.com/3455312/68896791-1486ac80-06e1-11ea-8854-f07e8b2a795f.jpg)
This is breaking a lot of my layouts unfortunately.

**Comment by Bosch-Eli-Black** [comment] 2019-12-30 03:42
Looks like this has been fixed via #8150

**Comment by hartez** [comment] 2020-02-07 06:12
I think @Bosch-Eli-Black is correct, this has been fixed. I'm closing this - if anyone is still running into it, tag me here and I'll reopen.

**Closed by hartez** 2020-02-07 06:12 UTC
Labels: 4.3.0, e/3 :clock3:, i/regression, p/UWP, t/bug :bug:
