### ISSUE TITLE
Unable to set focus to button after selecting an Item from Picker

### ISSUE THREAD

**Issue by StuartFergusonVme** [xamarin/Xamarin.Forms#6425] opened 2019-06-06 09:35 UTC
### Description

Unable to set focus to button from a Picker control on item selection.

### Steps to Reproduce

1.  Add 3 controls to the main page

```    
    <Entry x:Name="TestEntry" Completed="TestEntry_OnCompleted"></Entry>
    <Picker x:Name="TestPicker" Title="Choose type" Focused="TestPicker_OnFocused" 
                  Unfocused="TestPicker_OnUnfocused">
        <Picker.Items>
            <x:String>Supplier Return</x:String>
            <x:String>Insurance Claim</x:String>
        </Picker.Items>
    </Picker>
    <Button x:Name="SaveButton" Text="Save" Focused="SaveButton_OnFocused" 
                  Clicked="SaveButton_OnClicked"></Button>
```
2.  Wire up the events as follows:

```
    private void TestEntry_OnCompleted(Object sender,
                                           EventArgs e)
        {
            this.TestPicker.Focus();
        }

        private void TestPicker_OnFocused(Object sender,
                                          FocusEventArgs e)
        {
            Plugin.Toast.CrossToastPopUp.Current.ShowToastMessage("Picker Focused");
        }

        private void TestPicker_OnUnfocused(Object sender,
                                            FocusEventArgs e)
        {
            Plugin.Toast.CrossToastPopUp.Current.ShowToastMessage("Picker unfocused");
            this.SaveButton.Focus();
        }

        private void SaveButton_OnFocused(Object sender,
                                          FocusEventArgs e)
        {
            Plugin.Toast.CrossToastPopUp.Current.ShowToastMessage("Button Focused");
        }

        private void SaveButton_OnClicked(Object sender,
                                          EventArgs e)
        {
            Plugin.Toast.CrossToastPopUp.Current.ShowToastMessage("Button Clicked");
        }
```
 
### Expected Behavior

When the user presses enter on the Entry Box the focus moves to the picker.
When the user selects an item from the picker, by pressing enter the focus moves to the button.
When the user selects an item from the picker, by tapping on the item the focus moves to the button.

### Actual Behavior
When the user presses enter on the Entry Box the focus moves to the picker.
When the user selects an item from the picker, by pressing enter the focus moves to the button.
When the user selects an item from the picker, by tapping on the item the focus stays on the picker.

### Basic Information

- Version with issue: Xamarin Forms 3.6 & v4.0
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - iOS:  N/A
  - Android: 9.0 Pie
  - UWP:  N/A 
- Affected Devices: All devices (including emulator)

### Reproduction Link

https://github.com/StuartFergusonVme/PickerFocusIssue

**Comment by samhouts** [comment] 2019-06-06 22:34
Duplicate of #5616

**Closed by samhouts** 2019-06-06 22:34 UTC
Labels: p/Android, s/unverified, t/bug :bug:
