### ISSUE TITLE
MasterDetailPage navigation is not aligned to RTL

### ISSUE THREAD

**Issue by Rajeswari06** [xamarin/Xamarin.Forms#3805] opened 2018-09-17 11:35 UTC
###Description
Created a MasterDetailPage app in xamarin forms as PCL application which supports android.
Did the RTL changes and changed the device language and region to Arabic.
Tested the app in android device, the hamburger menu and navigation title is still left aligned.

### Steps to Reproduce

1. Change the device language and region to Arabic.
2. Open the app 
3. Check the alignment

### Expected Behavior

The Hamburger menu and navigation title should align from right side

### Actual Behavior

The Hamburger menu and navigation title is still left aligned.

### Basic Information

- Version with issue:xamarin forms : 3.0.0.561731
- Affected Devices: Android devices

### Screenshots
![settings](https://user-images.githubusercontent.com/23097051/45620852-d28db680-ba9b-11e8-808c-a88dc6fc6642.png)
![masterdetailopen](https://user-images.githubusercontent.com/23097051/45620910-05d04580-ba9c-11e8-9216-7d571e9b7b58.png)
![masterdetail](https://user-images.githubusercontent.com/23097051/45620861-d7526a80-ba9b-11e8-898a-cd141a8f7aa0.png)

### Reproduction Link
[Masterdetail.zip](https://github.com/xamarin/Xamarin.Forms/files/2388151/Masterdetail.zip)

**Comment by samhouts** [comment] 2018-09-19 22:15
Duplicate of #2818

**Closed by samhouts** 2018-09-19 22:15 UTC
