### ISSUE TITLE
Xamarin Forms Native embedding Memory issue

### ISSUE THREAD

**Issue by toupilsner** [xamarin/Xamarin.Forms#4671] opened 2018-12-07 09:51 UTC
### Description
I am trying to use Xamarin Forms pages in a Xamarin IOS Native app. To do that I am using the CreateViewController. The issue I am facing is that every time I push a new view controller, memory are allocated that are not released when I click on the back button. This results in that the app will crash. 
### Steps to Reproduce

Explanation about attached image

1. I am navigating back and fort to a Xamarin forms page (contains image and is created with xaml). I am doing this multiple times, and that is displayed with the stepping increase in memory consumption
2. I am waiting to se if the memory is released, but that do not happen. I am then adding native uiviewcontrollers (contains one image) to the same navigation controller the same way as Xamarin forms.
3. The memory are released for the native view controllers.

![](https://us.v-cdn.net/5019960/uploads/editor/is/eau2f82g4q60.png)

Link to testcode
 github.com/toupilsner/XamarinFormsEmbedded/blob/master/README.md

Xamairn Forms: 3.4.0

**Comment by kingces95** [comment] 2018-12-07 23:01
`ApiKey.cs` not found.

**Comment by toupilsner** [comment] 2018-12-12 08:16
just remove ApiKey.cs and add a random key where the code is asking for the key.This part is not important. If you click on the icon up at the right corner, you will open a new Xamarin forms page. That page is creating a memory leak.

 The image I have attached is not directly related to the code. The image is simulating when I navigate backward and forward between Xamarin forms page and a native uiviewPage.

**Comment by hartez** [comment] 2018-12-19 04:02
Confirmed. For some reason, even without any other references to the ContentPage, it's being retained.

**Comment by toupilsner** [comment] 2019-03-27 12:11
Any ETA on this issue?

**Comment by danielwebstep** [comment] 2019-04-02 10:18
I've seen this issue working with native Xamarin.iOS and code behind/handling navigation manually. I do not believe this is Xamarin Forms spesific. I do believe this is something that's also an issue in Swift/C++ (see StackOverflow)

Using the PopToRootViewController(native.iOS) does not seem to remove the ContentPage/dispose the controller from the app. 

Hence; if you are not disposing images the images are in memory. What can be done? This is how I've done this the last years when working with Xamarin apps

**Images**
1. Look at the image size, it's a 6mb sized image (3561x4704). With my iPad mini this adds 24mb of memory every time you go to the history page. Which then eventually will crash the app.

For iOS images and how you should handle  images in iOS, I would look at this: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/

The different device screen resolutions will scale/downscale images if they are not scaled correctly to begin with. Which may size the image to be larger in memory. An iPad Mini has a screen resolution of 1024x768. A 3xlarger image will need to be downscaled quite a lot.

A simple test resizing the image to 1024x1353 gives me a memory usage of 2mb per new HistoryPage which is a decrease of memory usage over 10 times the original.

**Adding new controller every time**
1. If you are newing the controller every time, you will get a new page in memory (and image) every time. 

If you reuse the viewcontroller the memory-usage will stay stable as you are only creating the page once and the image is only put in memory once.

For this app you can simply reuse the HistoryViewController instead of newing it up, which then only creates the Xaml page once. If the image in the HistoryPage is to be changed(based on which location you are looking at) I would bind the image source in the code-behind instead of in the XAML.

**Eventhandling**
If you are adding a new button every time you pop the view controller in the "ViewDidAppear" method, you will then add a new button and a new eventhandler every time you go back to the controller. Which might also leak memory.

If you are using the viewDidAppear, you should then also use the viewdiddisappear and release the button and eventhandling when you go to a new controller.

For this app, you can simple add the History button once in the ViewDidLoad() as it only has one function (take you to the historypage).

Example 1: App as is with no re-use and 6mb base image. Adds 24,12 mb of memory each time you go to the historypage.

![image](https://user-images.githubusercontent.com/23522213/55394921-c7364000-5540-11e9-91a6-de1c22c7e552.png)

Example 2: Re-use of HistoryController, and also adding history button only once and only 2mb of memory. (I believe using the HIG from Apple would reduce this even more. Or use binding instead of a static image).

![image](https://user-images.githubusercontent.com/23522213/55394982-e8972c00-5540-11e9-995f-4b68f65208f8.png)

In AppDelegate the iOS has a DidReceiveMemoryWarning:

> Your app never calls this method directly. Instead, this method is called when the system determines that the amount of available memory is low.
> 
> You can override this method to release any additional memory used by your view controller. If you do, your implementation of this method must call the super implementation at some point.

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621409-didreceivememorywarning?language=objc

The docs states that if the memory is low, you should release additional memory used by your views. That said; if the PopToRootViewController does not dispose the controller and reserouces, you must do it yourself.

**Comment by hartez** [comment] 2019-06-23 22:33
@toupilsner We don't automatically clean up the resources from the embedded page when you navigate back, because Forms doesn't have visibility to navigating happening outside of it. So the proper way to clean up these resources once you're done with them (for instance, after popping the view controller) would be to call `Dispose()` on the `UIViewController` that is returned by `CreateViewController()`. 

However - there's a problem with cleaning that up right now. In the current version, calling `Dispose()` on that view controller won't clean everything up correctly. We've created a PR to fix that (#6636). Once that change is merged, calling `Dispose()` should allow the garbage collector to clean up the memory used by the embedded page.

**Closed** 2019-06-24 23:39 UTC
Labels: a/embedding 📦, e/3 :clock3:, t/bug :bug:
