### ISSUE TITLE
[Bug] Visual Studio for Mac. Could not locate the assembly "Xamarin.iOS"...

### ISSUE THREAD

**Issue by fjavaler** [xamarin/Xamarin.Forms#13019] opened 2020-12-02 07:00 UTC
### Description
Hi, I have a solution generated in VS 2019 (Windows) and runs fine in it, however, in VS for Mac I get the following error: 

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xamarin.iOS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (MSB3245)

I am making a few references to the UIKit, CoreGraphics, and Foundation namespaces in my code and those namespaces are not able to be found. E.g. UIKit.UIImage, UIColor.Yellow, etc. I have tried uninstalling and reinstalling the Xamarin.Forms NuGet package and have also ensured that the iOS project is referencing Xamarin.iOS and that no other projects are referencing it.

### Steps to Reproduce

1. Make reference to any UIKit namespaces.
2. VS cannot find namespace UIKit despite having a "using UIKit;" statement.

### Expected Behavior
Namespace should be found as in Windows VS 2019.

### Actual Behavior
Namespaces not found.

### Basic Information

- Version with issue: VS for Mac 8.8.3.
- Last known good version: First time trying on VS for Mac.
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms 4.8.0.1687
- Affected Devices:

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 9377e409-c603-4fe4-88aa-828a3863e75a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Professional)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/gpsdev/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/gpsdev/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

```

### Build Logs

https://gist.github.com/fjavaler/3ac64356a67b2e2e6290aacbe2559f25

### Screenshots

![Screen Shot 2020-12-01 at 11 57 09 PM](https://user-images.githubusercontent.com/9067250/100839362-56d87400-3431-11eb-8e35-70b1a8523214.png)

**Comment by StephaneDelcroix** [comment] 2020-12-02 12:13
I can't reproduce this issue. There's either something wrong with your solution, or your installation. I don't know how to help but here's how I'd debug this:

1/ can you reproduce this in a fresh solution ? If yes, clean your solution, drop all obj/ and bin/ folders, restart the IDE...
2/ if no, make sure your VS and dependencies are up to date, if they aren't update them
3/ if it still doesn't work, reinstall VSMac

or...

you could report this issue to VSMac

hope it helps a bit

**Comment by StephaneDelcroix** [comment] 2020-12-02 12:13
(closing as it's unrelated to XF)

**Closed by StephaneDelcroix** 2020-12-02 12:13 UTC
Labels: s/unverified, t/bug :bug:
