### ISSUE TITLE
[Bug] NullReferenceException in EntryRendererBase.ShouldChangeCharacters on iOS

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#11965] opened 2020-08-30 17:32 UTC
### Description

NullReferenceException observed in Xamarin.iOS/Xamarin.Forms code in the wild.

Stack trace:
```
EntryRendererBase`1[TControl].ShouldChangeCharacters (UIKit.UITextField textField, Foundation.NSRange range, System.String replacementString)
UITextField+_UITextFieldDelegate.ShouldChangeCharacters (UIKit.UITextField textField, Foundation.NSRange range, System.String replacementString)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

The code that crashed (https://github.com/xamarin/Xamarin.Forms/blame/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs, lines 391-395) has not been changed for 3 years, but is replete with null checks, so the only opportunity for a null would be for the `replacementString` argument to be null. Seems that either this should handle a possible null, or the calling code needs a null check?

### Steps to Reproduce

Unknown

### Expected Behavior

No crash

### Actual Behavior

NullReferenceException

### Basic Information

- Version with issue: 4.7.0.1142
- Last known good version: n/a
- IDE: VS 2019 16.7
- Platform Target Frameworks: 
  - iOS: Default
- Nuget Packages: Microsoft.AppCenter.Analytics 3.3.0, Microsoft.AppCenter.Crashes 3.3.0, Microsoft.EntityFrameworkCore.Sqlite 3.1.6, Plugin.InAppBilling 2.0.0, Xamarin.Essentials 1.5.3.2
- Affected Devices: iPhone 6s Plus, iOS 13.5.1, AT&T, Spanish (Mexico), crashed after 2.5 hours

### Reproduction Link

This has been observed via AppCenter and is demonstrably rare. Thus, I have no reproduction.

**Comment by StephaneDelcroix** [comment] 2020-09-10 09:01
could you have a quick look, @jfversluis ?

**Comment by jfversluis** [comment] 2020-09-10 09:51
Hm interesting. I mean, I could just add that null check to be sure. This is kind of hard to figure out without a reproduction.

I've taken a quick look and the event basically is an iOS one and I see no indication why that string should be null at any point.

@BioTurboNick you already mentioned it's in the wild, so no clue as to what text was going in? Where are you using this? Are you using `MaxLength` somewhere in your code?

**Comment by BioTurboNick** [comment] 2020-09-10 13:59
@BioTurboNick - not an iota of an idea, sorry. I'm not referencing this code directly. For the heck of it, I tried entering emojis into all my Entry controls and nothing unexpected happened. I'm not deliberately assigning nulls to Entry.Text, though that's the default value so should be fine? I am not using MaxLength, no.

This may not be relevant, but recently I've been getting a crash in my Android project too but only when I *upload* it to the Google Play Store, for its EditText widget  (not test, not release; I upload it to the store and the crash appears). I wrote it off because that's the only time it happens, and it doesn't even occur during their Prelaunch testing. I only mention it because it's also a weird Entry-related crash. Though it appears an Android bug is active for something like it: https://issuetracker.google.com/issues/153434501 https://stackoverflow.com/questions/54779200/android-app-crash-in-play-store-prelaunch-report-but-working-in-real-device

```
android.text.SpannableStringBuilder.checkRange
java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 1
```

```
android.text.SpannableStringBuilder.checkRange SpannableStringBuilder.java:1090
android.text.SpannableStringBuilder.setSpan SpannableStringBuilder.java:665
android.text.SpannableStringBuilder.setSpan SpannableStringBuilder.java:658
android.text.Selection.setSelection Selection.java:76
android.text.Selection.setSelection Selection.java:87
android.widget.EditText.setSelection EditText.java:98
android.widget.EditText.performAccessibilityActionInternal EditText.java:138
android.view.View.performAccessibilityAction View.java:8889
android.view.AccessibilityInteractionController.performAccessibilityActionUiThread AccessibilityInteractionController.java:668
android.view.AccessibilityInteractionController.-wrap6 AccessibilityInteractionController.java
android.view.AccessibilityInteractionController$PrivateHandler.handleMessage AccessibilityInteractionController.java:1194
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:5421
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:726
com.android.internal.os.ZygoteInit.main ZygoteInit.java:616
```

**Comment by jfversluis** [comment] 2020-09-11 08:58
What are the things that you are doing with the `Entry`? Anything special?

The interesting thing you mention in the affected devices

> crashed after 2.5 hours

So you do have some session information? Can you somehow figure out vaguely what the user was doing to lead up to the crash?

The Android bits is something different I guess, since the concept is different and are two very different renderers. Also a curious issue though.

**Comment by BioTurboNick** [comment] 2020-09-11 13:17
@jfversluis 

I have very limited information from AppCenter, and am not taking advantage of telemetry to see details of app behavior. Was a privacy move, but maybe I should have more.

As far as what I'm doing with them, maybe there are a couple unorthodox things. I have an Entry where Text is OneWay bound to its ViewModel property (which is publicly read only and `Nullable<int>`), while a TextChanged handler is hooked up to set the value via a Command on the View Model. I'll just paste the relevant parts.

```
<Entry x:Name="counterSetterEntry1"
            Text="{Binding SelectedSquare.Counters[0].Value, Converter={StaticResource NullableIntConverter}, ConverterParameter=—, Mode=OneWay}"
                               TextChanged="CounterSetterEntry1_TextChanged" />

void CounterSetterEntry1_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (string.IsNullOrEmpty(e.NewTextValue) || _viewModel is null || isGridChanging)
                return;

            if (_viewModel.Hemocytometer.CountersCount > 0 && _viewModel.SelectedSquare?.Counters.Count > 0)
                _viewModel.SelectedSquare?.Counters[0].Set.Execute(new NullableIntConverter().ConvertBack(e.NewTextValue, typeof(int?), null!, CultureInfo.InvariantCulture));
        }


public class NullableIntConverter :
        IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (targetType != typeof(string) && targetType != typeof(object)) // object is for SelectedItem binding in SettingsPage.
                return new object();

            return value switch
            {
                null  => parameter as string ?? string.Empty,
                int a => a.ToString(culture),
                _     => string.Empty
            };
        }

        public object? ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (targetType != typeof(int?))
                return null;

            bool success = int.TryParse(value as string, out int intValue);
            return success ? (int?)intValue : null;
        }
    }
}
```

Maybe not the simplest design, would mean occasionally the backing property wouldn't match the Entry value. But Entry shouldn't care about it's backing field, right? Just what is in it and what it is being changed to?

The other Entry boxes are fairly normal. String is passed through a DoubleConverter or IntConverter if it's backed by a double or int:

```
public class IntConverter : IValueConverter
    {
        public object? Convert(object value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (targetType != typeof(string))
                return new object();
            if (!(value is int intValue))
                return string.Empty;
            return intValue.ToString(culture);
        }

        public object? ConvertBack(object value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (targetType != typeof(int))
                return new object();
            bool success = int.TryParse(value as string, out int result);
            return success ? result : 0;
        }
    }

public class DoubleConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (targetType != typeof(string))
                return new object();
            if (!(value is double doubleValue))
                return string.Empty;
            return double.IsNaN(doubleValue) ? string.Empty : doubleValue.ToString(culture);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (targetType != typeof(double))
                return new object();
            bool success = double.TryParse(value as string, NumberStyles.AllowDecimalPoint, culture, out double result);
            return success ? result : double.NaN;
        }
    }
```

**Comment by jfversluis** [comment] 2020-09-11 13:53
> I have very limited information from AppCenter, and am not taking advantage of telemetry to see details of app behavior. Was a privacy move, but maybe I should have more.

I wouldn't want to see it any other way, so that's very good :)

Hm I see some things that could possible pass `null` in there, right?

I think I will just go ahead and make that last string null checked as well just to be sure. It won't harm anyone and hopefully will resolve this. The problem is that there is no real way of knowing. So I think what I'll do is open a PR for that, let that close this issue and ask you to keep an eye out to see if that actually fixes things if that's OK :)

**Comment by BioTurboNick** [comment] 2020-09-11 14:09
I was wondering about null, but the default value for Entry.Text is null, too, so it seems like that shouldn't be an issue?

But yeah, your idea seems sensible to me. Thanks!

**Closed** 2020-09-14 22:24 UTC
Labels: a/entry, in-progress, p/iOS 🍎, s/unverified, t/bug :bug:
