### ISSUE TITLE
[Bug] [Android] Buttons and Entries are not working in a SwipeView

### ISSUE THREAD

**Issue by bricefriha** [xamarin/Xamarin.Forms#9363] opened 2020-01-29 22:19 UTC
### Description
When I put any controls such as Entries or buttons in a SwipeView.content they are not usable.

but, sorry I didn't test on IOS.

### Steps to Reproduce

1. Create a SwipeView
2. Put a button or an Entry in it
3. Try to interact with these components

### Expected Behavior
Interact with the button and being able to write into the Entry

### Actual Behavior
Litterally nothing happen, as if the "IsEnable" attribut of the button/entry was at false

### Basic Information

- Version with issue: 4.4.0.991537 (also tested on 4.5.0.187-pre2)
- IDE: Visual Studio Enterprise 2019 version 16.4.3

### Reproduction Link

[https://github.com//bricefriha/SwipecontentIssueDemo/archive/master.zip](url)

**Comment by samhouts** [comment] 2020-02-04 02:13
Duplicate of #8779

**Closed by samhouts** 2020-02-04 02:13 UTC
Labels: a/button, a/entry, a/swipeview, p/Android, s/unverified, t/bug :bug:
