### ISSUE TITLE
VS2019 Can't serialize class inherited from BindableObject, yet VS2019 succeeds.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9094] opened 2020-01-06 18:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/807939/xmlserializer-fails-on-2019-succeeds-in-2017-for-s.html)._

---
<p>Moving an existing Xamarin solution from Android 5 to Android 9.<br>
Moving from Visual Studio 2017 to VS2019.<br>
But no logic changes: Just tweeks to make the app run.</p>
<p>I have a class of <code>ScanDocument</code> with properties for a document that has been scanned (via USB scanner on Android tablet).<br>
This class has zero changes between the 2017 and 2019 solutions.<br>
Yet - 2017 has no issue serializing the class where 2019 throws “There was a problem reflecting type bla blah blah”</p>
<pre><code>        public void Save(string filePath)
        {
            <span class=hljs-keyword>bool</span> result = <span class=hljs-literal>false</span>;
            filePath = System.IO.Path.ChangeExtension(filePath, <span class=hljs-string>&quot;.sdoc&quot;</span>);

            <span class=hljs-keyword>try</span>
            {
                fileHelper.DeleteFile(filePath);

                <span class=hljs-keyword>var</span> xmlSerializer = <span class=hljs-keyword>new</span> XmlSerializer(<span class=hljs-keyword>typeof</span>(ScanDocument)); <span class=hljs-comment>// &lt;--- Here</span>
                <span class=hljs-keyword>var</span> stream = FHelper.Instance().CreateTextStreamWriter(filePath, <span class=hljs-literal>false</span>);
                <span class=hljs-keyword>if</span> (stream != <span class=hljs-literal>null</span>)
                {
                    xmlSerializer.Serialize(stream, <span class=hljs-keyword>this</span>);
                    stream.Flush(); <span class=hljs-comment>//Because I'm paranoid</span>
                    stream.Close();
                    stream.Dispose();
                }

                result = <span class=hljs-literal>true</span>;
                SavePath = filePath;
            }
            <span class=hljs-keyword>catch</span> (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                result = <span class=hljs-literal>false</span>;
            }
        }
</code></pre>
<p>So what changed in the XMLSerializer, if it wasn’t a change in the class being serialized?</p>

---
#### Clint StLaurent on 11/5/2019, 01:38 PM: 

<p>Updated information from testing.</p><p>` public class DummyDoc : BindableObject , IEqualityComparer&lt;ScanDocument&gt;` - Fails</p><p>` public class DummyDoc : BindableObject // , IEqualityComparer&lt;ScanDocument&gt;` - Fails</p><p>` public class DummyDoc// : BindableObject , IEqualityComparer&lt;ScanDocument&gt;` - Success</p>

#### Visual Studio Feedback System on 11/6/2019, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jonathan Peppers [MSFT] on 11/11/2019, 10:14 AM: 

<p>Can you post the full <code>adb logcat</code> output of the crash?<br>
<a target='_blank' href="https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log">https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log</a><br>
What version of Xamarin.Forms are you using. Anything you can send would help us look into this, thanks!</p>

#### Clint StLaurent on 11/11/2019, 11:35 AM: 

<p>There is **so much** going on with other aspects of the application that the logcat is a monster.</p><p>I'll make a little "Welcome to xamarin" default app that does the same thing and point you at it.  Give me a couple days.</p>

#### Joaquin Jares [MSFT] on 11/20/2019, 05:46 AM: 

<p>Hi! Any updates on the log? Thanks! J</p>

#### Clint StLaurent on 11/20/2019, 07:05 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/8304/9d323fbb-0835-48f8-a81b-80063d7115f3.html" nodeid="8304">@Joaquin Jares [MSFT]</a></p><p>Thanks for the nudge - I admit that I totally forgot about this.</p><p>I'll jump on this this afternoon.</p>

#### Joaquin Jares [MSFT] on 11/20/2019, 07:11 AM: 

<p>To be totally honest, we have systems in place to remind us :). Please do tell when you have the info. Thanks! J</p>

#### Clint StLaurent on 11/20/2019, 01:22 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/8304/9d323fbb-0835-48f8-a81b-80063d7115f3.html" nodeid="8304">@Joaquin Jares [MSFT]</a></p><p>I have a dead simple sample solution to demonstrate this. Its a 57mb zip file that doesn't seem to upload.  So how would you like it?<br></p><p>Or... You can make a basic, blank "Welcome to Xamarin" app, add two buttons to the default page and wire them to the handlers in this code (See UI.jpg attached0<br></p><p>As you can see in the attached, trying to serialize an object inherited from `BindableObject` crashes the app and a stand alone class does not.<br></p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/106056-exception.jpg">exception.jpg</a><br></p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/106058-output.jpg">output.jpg</a><br></p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/106059-ui.jpg">ui.jpg</a><br></p><p><br></p><p>**C# code behind the MainPage (MainPage.xaml.cs)**<br></p><pre>using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Xamarin.Forms;

namespace DemoProblem
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            InheritedInstance = new InheritedClass() { MyName = "Fred" };
            StandAloneInstance = new StandAloneClass() { MyName = "Barney" };
        }

        #region InheritedInstance (InheritedClass)
        private InheritedClass _InheritedInstance;
        public InheritedClass InheritedInstance
        {
            get
            {
                //if (_InheritedInstance == null) InheritedInstance = new InheritedClass();
                return _InheritedInstance;
            }

            set
            {
                if (_InheritedInstance == value) return;
                _InheritedInstance = value;
                OnPropertyChanged();
            }
        }
        #endregion InheritedInstance  (InheritedClass)

        #region StandAloneInstance (StandAloneClass)
        private StandAloneClass _StandAloneInstance;
        public StandAloneClass StandAloneInstance
        {
            get
            {
                //if (_StandAloneInstance == null) StandAloneInstance = new StandAloneClass();
                return _StandAloneInstance;
            }

            set
            {
                if (_StandAloneInstance == value) return;
                _StandAloneInstance = value;
                OnPropertyChanged();
            }
        }
        #endregion StandAloneInstance  (StandAloneClass)

        private void btnWorks_OnClicked(object sender, EventArgs e)
        {
            Console.WriteLine("INFORMATION&gt; Serializing StandAloneInstance");

            var xmlSerializer = new XmlSerializer(typeof(StandAloneClass)); // &lt;--- Here
            var stream = new MemoryStream();
            if (stream != null)
            {
                xmlSerializer.Serialize(stream, StandAloneInstance);
                stream.Flush(); //Because I'm paranoid
                stream.Close();
                stream.Dispose();
            }
        }

        private void btnBroken_OnClicked(object sender, EventArgs e)
        {
            Console.WriteLine("INFORMATION&gt; Serializing Inherited Instance");

            var xmlSerializer = new XmlSerializer(typeof(InheritedClass)); // &lt;--- Here
            var stream = new MemoryStream();
            if (stream != null)
            {
                xmlSerializer.Serialize(stream, InheritedInstance);
                stream.Flush(); //Because I'm paranoid
                stream.Close();
                stream.Dispose();
            }
        }
    }

    public class InheritedClass : BindableObject
    {
        public InheritedClass()
        {

        }

        #region MyName (string)
        private string _MyName;
        public string MyName
        {
            get
            {
                //if (_MyName == null) MyName = new string();
                return _MyName;
            }

            set
            {
                if (_MyName == value) return;
                _MyName = value;
                OnPropertyChanged();
            }
        }
        #endregion MyName  (string)

    }

    public class StandAloneClass
    {
        public StandAloneClass()
        {

        }

        #region MyName (string)
        private string _MyName;
        public string MyName
        {
            get
            {
                //if (_MyName == null) MyName = new string();
                return _MyName;
            }

            set
            {
                if (_MyName == value) return;
                _MyName = value;
                //OnPropertyChanged();
            }
        }
        #endregion MyName  (string)

    }
}

<br></pre>

#### Visual Studio Feedback System on 11/21/2019, 05:29 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Joaquin Jares [MSFT] on 12/3/2019, 05:29 AM: 

<p>This looks like a mono issue. Sending over to them to investigate.</p>

#### Visual Studio Feedback System on 12/19/2019, 06:22 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
#### Clint StLaurent solved on 11/5/2019, 01:37 PM, 0 votes: 

<p>{delete] Comment not a solution</p>

**Comment by samhouts** [comment] 2020-01-06 19:29
see https://github.com/mono/mono/issues/18008#issuecomment-561655465

**Comment by hartez** [comment] 2020-01-07 18:56
This is a duplicate of #8400

**Comment by hartez** [comment] 2020-01-07 19:06
> “There was a problem reflecting type bla blah blah”

@tlhintoq You want to tell us what the "bla blah blah" part was? That stack trace might help.

**Comment by tlhintoq** [comment] 2020-01-07 19:37
@hartez 
Its was a custom object.  It doesn't matter what object.  Make a `cat` type... 
if it is derived from `BindableObject`... it doesn't serialize.

Original Comments
Clint StLaurent on 11/5/2019, 01:38 PM:

Updated information from testing.

` public class DummyDoc : BindableObject , IEqualityComparer<ScanDocument>` - Fails

` public class DummyDoc : BindableObject // , IEqualityComparer<ScanDocument>` - Fails

` public class DummyDoc// : BindableObject , IEqualityComparer<ScanDocument>` - Success

**Comment by hartez** [comment] 2020-01-07 19:51
Let's try this again: does the the stack trace include something like:

`Cannot serialize member 'Xamarin.Forms.BindableObject.Dispatcher' of type 'Xamarin.Forms.IDispatcher'`?

**Comment by samhouts** [comment] 2020-02-06 18:06
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2020-02-06 18:06 UTC
Labels: a/buildchain, feedback-ticket, i/regression, p/Android, s/needs-info ❓, s/unverified, t/bug :bug:
