### ISSUE TITLE
[Bug] CarouselView strange Left,Top padding on iOS 

### ISSUE THREAD

**Issue by badstorm** [xamarin/Xamarin.Forms#9617] opened 2020-02-18 08:55 UTC
### Description
Creating a simple project with a nasted CarouselView, on iOS thare is a strange left,top padding. 

For more info: [Xamarin Forum Post](https://forums.xamarin.com/discussion/177794/question-strange-padding-in-a-nasted-collectionview-how-to-remove#latest)

### Steps to Reproduce
I create a simple project here: [githug demo repo](https://github.com/badstorm/xamarin_forms_collectionview_bug)

### Basic Information

Tested with:
- Xamarin Forms version: 4.4.0.991640
- Visual Studio for Mac version 8.4.5
- iOS SDK 11.3.1

**Comment by samhouts** [comment] 2020-02-19 04:39
Duplicate of #8961

**Closed by samhouts** 2020-02-19 04:39 UTC
Labels: a/carouselpage, p/iOS 🍎, s/unverified, t/bug :bug:
