### ISSUE TITLE
[Android] Setting Automation properties causes view to increase width

### ISSUE THREAD

**Issue by CarnageMarkus** [xamarin/Xamarin.Forms#3453] opened 2018-08-01 10:00 UTC
### Description
I have few controls next to each other In horizontal stack layout. Few at the start, one at the end.
When I set AutomationProperties.SetHelpText(); to button, button grows in width, sometimes even off screen.
Also adding AutomationProperties to Switch causes to string appear as label next to the control....

In iOS no such behavior occurs.
### Steps to Reproduce

1. Create Switch
2. Set AutomationProperties.SetName();
3. UI gets blown up
4. ??
5. Try not to cry. Cry a lot.

### Expected Behavior
AutomationProperties should just change text for voice over...

### Actual Behavior
Controls grow in width, labels appear

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version:
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 27
- Android Support Library Version: v7

**Comment by samhouts** [comment] 2018-08-01 21:53
duplicate of #2580

**Closed by samhouts** 2018-08-01 21:53 UTC
