### ISSUE TITLE
Xamarin Forms Title View not centered on non modal screens (With a back button)

### ISSUE THREAD

**Issue by asj-it** [xamarin/Xamarin.Forms#5862] opened 2019-04-09 15:19 UTC
### Description
When creating a title view, centered label is off centered on non modal screens, with a back button.
### Steps to Reproduce

Create a custom TitleView

``` xml
    <ContentView.Content>
        <Grid HorizontalOptions="FillAndExpand" Margin="0">

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="40" />
            </Grid.ColumnDefinitions>
            <Label Text="{Binding Title}" Grid.Row="0" Grid.ColumnSpan="2" Style="{StaticResource HeaderTitle}" >
                <Label.HorizontalOptions>
                    <OnPlatform x:TypeArguments="LayoutOptions">
                        <On Platform="iOS" Value="Center" />
                        <On Platform="Android" Value="Start" />
                    </OnPlatform>
                </Label.HorizontalOptions>
            </Label>
            <forms:SvgCachedImage x:Name="MainImage" HeightRequest="30" Grid.Row="0" Grid.Column="1"
                                  Source="{Binding CurrentConnectionStatus, Converter={StaticResource BluetoothStatusConverter}}"
                                  HorizontalOptions="End" />
        </Grid>
    </ContentView.Content>

```

Then set the TitleView to use the control

``` c#
            defaultTitleView = new DefaultTitleView();
            NavigationPage.SetTitleView(this, defaultTitleView);
```

### Expected Behavior

The Title Should be centered on the screen

### Actual Behavior
It  appears to be centered between the right of the Back button and the Right of the screen.  This is even more pronounced on Android where the back button is larger.

<img width="747" alt="Screenshot 2019-04-09 at 16 00 39" src="https://user-images.githubusercontent.com/16338022/55811730-79da4580-5ae1-11e9-888c-c89aaa8c49dd.png">

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: n/a
- IDE: Visual Studio (mac) v8.0
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: 8.1
- Android Support Library Version: v7
- Nuget Packages:
- Affected Devices: iOS & Android Devices

**Comment by samhouts** [comment] 2019-04-12 01:23
Duplicate of #4848

**Closed by samhouts** 2019-04-12 01:23 UTC
Labels: s/unverified

**Comment by rscholey** [comment] 2019-08-15 22:16
This has been marked as a duplicate but the duplicate has been closed with no solution
