### ISSUE TITLE
[Bug] TailTruncation doesn't work properly if last drawn character is a space

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11633] opened 2020-08-02 22:44 UTC
Setting a label's LineBreakMode to TailTruncation (and possibly others, didn't test) doesn't draw the ellipsis if the last line's last character is a space. This is problematic as if you have a long string that doesn't fully fit it's customary to show an ellipsis to denote that there's more text (accessible via whatever means). Because Xamarin.Forms doesn't draw the ellipsis when the last draw character is a space, it is indistinguishable from a string that would have fit fully in its designated area. There is a possibility that the issue requires the last characters to be ". " (without the quotes; ie a dot and a space) for it to materialise.

My use case is to display part of a user's profile description, and when the ellipses are not drawn, there's no reason to tap the view profile button as it looks like you read the whole thing.

Please advice on a workaround if this takes a long time to fix.

Thanks.

**Comment by PureWeen** [comment] 2020-08-06 20:53
I can't reproduce. Can you attach a repro? I tried a few different permutations and the ellipses are always there. 
FYI this is all managed by the platform. We don't draw or calculate when to show the ellipses it's all just the native platforms TextView

It might be a problem with MaxLines and Height of the label? If your label is causing text to go to the next line but that makes the label grow outside the visible bounds you won't see the ellipses

```xaml
<StackLayout Margin="20">
            <Label MaxLines="2"
                   Text=" awhefhiuawef  aef awef awef awe faw efa wef awef aw feaw ef  sawhefhiuawef sawhefhiuawef sawhefhiuawef fe      nnn  "
                   HeightRequest="100" WidthRequest="20"
                   LineBreakMode="TailTruncation"></Label>
        </StackLayout>
```

![image](https://user-images.githubusercontent.com/5375137/89581527-c0869f80-d7fc-11ea-9566-df6f3bece76e.png)

**Comment by Tommigun1980** [comment] 2020-08-09 10:10
Hi @PureWeen.

I reported https://github.com/xamarin/Xamarin.Forms/issues/11713 which I think is a different manifestation of the same problem, with repro.

**Comment by rmarinho** [comment] 2020-08-14 18:32
Can you provide the styles you are using ? THanks

**Comment by Tommigun1980** [comment] 2020-08-19 02:06
Hi @rmarinho. I uploaded a repro case at https://github.com/xamarin/Xamarin.Forms/issues/11713. I'm pretty sure this is the same issue as https://github.com/xamarin/Xamarin.Forms/issues/11713 as setting the LineBreakMode to different options all draw the text incorrectly in different ways, so maybe this report should be closed and focus go to https://github.com/xamarin/Xamarin.Forms/issues/11713 instead? Please feel free to close this if you agree.

**Comment by samhouts** [comment] 2020-08-19 14:33
Duplicate of #11713

**Closed by samhouts** 2020-08-19 14:33 UTC
Labels: a/label, p/Android, s/needs-info ❓, s/unverified, t/bug :bug:
