### ISSUE TITLE
Getting error "xamarin.forms.dll" is being used by another process when debugging xamarin.forms application 

### ISSUE THREAD

**Issue by takaz-ams** [xamarin/Xamarin.Forms#9035] opened 2019-12-28 07:47 UTC
I have created at least 3 applications from scratch and works fine for the first couple of debug  sessions (at least 2 in my case). Then i get the error in the screen shot

![image](https://user-images.githubusercontent.com/54239149/71540672-4765c680-2956-11ea-9ea1-d00d5149b4a6.png)

The connection with the debugger has been lost. The target application may have exited.
System.IO.IOException: The process cannot access the file 'C:\Users\takaz\.nuget\packages\xamarin.forms\4.4.0.991265\lib
etstandard2.0\Xamarin.Forms.Core.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Debugging.VisualStudio.SymbolsAdapter.FindPathInDll(String path) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 184
   at Mono.Debugging.VisualStudio.SymbolsAdapter.RefreshSymbolPath(String assemblyPath) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 71
   at Mono.Debugging.VisualStudio.SymbolsAdapter.OnAssemblyLoaded(Object sender, AssemblyEventArgs e) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 62
   at Mono.Debugging.Client.DebuggerSession.OnAssemblyLoaded(String assemblyLocation) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1191
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleAssemblyLoadEvents(AssemblyLoadEvent[] events) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2070
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1708
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1639

I have deleted the obj folder and bin tried running again but still get same problem. This never used to happen.

I  am using xamarin.forms 4.4
i have tried previous versions as well.

I am also using Visual Studio 2019 (16.5.0 Preview 1.0)

**Comment by jfversluis** [comment] 2019-12-28 07:54
Looks like #8945

**Comment by brunck** [comment] 2019-12-30 02:43
Also looks the same as #9001

**Comment by samhouts** [comment] 2019-12-30 19:26
@takaz-ams This is an issue in VS 16.5 P1. It will be fixed in the next preview. This is being tracked here: https://developercommunity.visualstudio.com/content/problem/846153/the-connection-with-the-debugger-has-been-lost-the-1.html. Thanks!

**Closed by samhouts** 2019-12-30 19:26 UTC
Labels: s/unverified, t/bug :bug:

**Comment by rachmataditiya** [comment] 2020-01-15 10:59
I've got same issues here

**Comment by Nullstr1ng** [comment] 2020-02-07 01:42
wasting a lot of my time. getting the same in 4.4.0.991640 and 4.4.0.991537

**Comment by samhouts** [comment] 2020-02-07 04:15
You should be able to update to P2 now! I can confirm it is fixed there.

**Comment by Nullstr1ng** [comment] 2020-02-07 04:19
> You should be able to update to P2 now! I can confirm it is fixed there.

Downloading P2 now

**Comment by Nullstr1ng** [comment] 2020-02-07 05:05
fixed and installed the latest XF version
