### ISSUE TITLE
[XAMARIN-FORMS-WPF] Label's VerticalOptions and VerticalTextAlignment doesn't work when loaded inside Layout<View>

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#8064] opened 2019-10-17 12:44 UTC
# Description

Greetings,

We at Syncfusion have started implementation for providing support in Xamarin.Forms WPF platform for our controls. We have noticed that specified VerticalOptions or VerticalTextAlignment doesn't work for label element added as child for a Layout<View>, while the same structure works fine in UWP platform. We have attached a simple sample showcasing the issue. Can you please provide us with any solution or workaround to overcome this issue as soon as possible?

### Steps to Reproduce

1. Run the attached sample in WPF platform.
Note that the Label text is at top centered position.

### Expected Behavior
Label should be page centered as like in UWP platform.

### Actual Behavior
Label text is at top centered position.

### Basic Information

- Version with issue: Latest XForms
- Platform Target Frameworks:
WPF

### Reproduction Link
[AlignmentIssueWPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3739301/AlignmentIssueWPF.zip)

**Comment by mohachouch** [comment] 2019-10-22 07:35
Hi @Muthukumaran-G , Thank you for reporting this bug.

WPF renderers work differently than UWP renderers.

Xamarin Forms controls are converted to a single WPF control.

A Label is a TextBlock without the container that UWP adds.

Unfortunately the TextBlock component does not allow to center a text vertically. : https://stackoverflow.com/questions/1491649/text-vertical-alignment-in-wpf-textblock

To solve this problem two solutions:
1. Change the renderer to Label: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.label?view=netframework-4.8

2. Manually add a grid to center the text:
```

Label label = new Label() { Text = "Hello", FontSize = 50, BackgroundColor = Color.Blue,
                VerticalOptions = LayoutOptions.Center,
                HorizontalTextAlignment = TextAlignment.Center
            };

            ScrollView scrollView = new ScrollView();
            var container = new ContainerControl();

            scrollView.Content = container;

            gridExt.Children.Add(scrollView);

            LayoutControl cellsControl = new LayoutControl();
            VertualizingCellsControl vertualizingCellsControl = new VertualizingCellsControl();

            Grid gridExt2 = new Grid() { BackgroundColor = Color.Blue };
            gridExt2.Children.Add(label);
            cellsControl.Content = gridExt2;
            container.Children.Add(vertualizingCellsControl);

            vertualizingCellsControl.Children.Add(cellsControl);
```

**Comment by Muthukumaran-G** [comment] 2019-10-29 12:10
Hi @mohachouch ,

> 1. Change the renderer to Label: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.label?view=netframework-4.8

We can't use this workaround as we need to inherit from custom native element.

Although currently we are using another workaround to achieve the requirement by defining the size of the TextBlock element to Auto and aligning it based on forms element alignment options by loading inside a native Grid element.

**Comment by mohachouch** [comment] 2019-10-31 17:17
Hi @samhouts, it's not a bug, it's a limitation of the Wpf platform. The TextBlock control can not be vertically aligned.

https://stackoverflow.com/questions/1491649/text-vertical-alignment-in-wpf-textblock

**Comment by samhouts** [comment] 2019-11-20 22:20
Thanks, @mohachouch ! Closing...

**Closed by samhouts** 2019-11-20 22:20 UTC
Labels: help wanted, p/WPF, partner, s/unverified, t/bug :bug:, up-for-grabs
