### ISSUE TITLE
[Bug] Argument Null Exception on Android

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#6614] opened 2019-06-20 21:48 UTC
### Description

When using the new Dialog Service in Prism with XF 4.0 on Android we get a ArgumentNullException. This only happens with Android, and only with 4.0+. It seems this could be related to #2789. 

### Steps to Reproduce

1. Use Prism Dialog Service with Android and XF 4.0

### Expected Behavior

No Exception

### Actual Behavior

```
System.ArgumentNullException: Value cannot be null.
Parameter name: dictionary
  at System.Collections.Generic.SortedDictionary`2[TKey,TValue]..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] dictionary, System.Collections.Generic.IComparer`1[T] comparer) [0x00009] in <74989b9daab94528ac2c4b7da235b9c5>:0 
  at System.Collections.Generic.SortedDictionary`2[TKey,TValue]..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] dictionary) [0x00000] in <74989b9daab94528ac2c4b7da235b9c5>:0 
  at Xamarin.Forms.TabIndexExtensions.GetSortedTabIndexesOnParentPage (Xamarin.Forms.VisualElement element, System.Int32& countChildrensWithTabStopWithoutThis) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\TabIndexExtensions.cs:12 
  at Xamarin.Forms.Platform.Android.PageRenderer.Xamarin.Forms.Platform.Android.IOrderedTraversalController.UpdateTraversalOrder () [0x00041] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:164 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateParentPageTraversalOrder () [0x00025] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:404 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00116] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:369 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:211 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:353 
  at Xamarin.Forms.Element.set_Parent (Xamarin.Forms.Element value) [0x00094] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:210 
  at Xamarin.Forms.Element.OnChildAdded (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:322 
  at Xamarin.Forms.VisualElement.OnChildAdded (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:742 
  at Xamarin.Forms.Layout.OnInternalAdded (Xamarin.Forms.View view) [0x0001d] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:453 
  at Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00078] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:443 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in <74989b9daab94528ac2c4b7da235b9c5>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00009] in <74989b9daab94528ac2c4b7da235b9c5>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].InsertItem (System.Int32 index, T item) [0x0001a] in <74989b9daab94528ac2c4b7da235b9c5>:0 
  at System.Collections.ObjectModel.Collection`1[T].Add (T item) [0x00020] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
  at Xamarin.Forms.TemplateUtilities.OnContentChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00041] in D:\a\1\s\Xamarin.Forms.Core\TemplateUtilities.cs:67 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:445 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:379 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x00042] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:316 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:293 
  at Xamarin.Forms.ContentView.set_Content (Xamarin.Forms.View value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\ContentView.cs:11 
  at Prism.Services.Dialogs.DialogService.InsertPopupViewInCurrentPage (Xamarin.Forms.ContentPage currentPage, Xamarin.Forms.View popupView, System.Boolean hideOnBackgroundTapped, System.Action`1[T] callback) [0x000b7] in d:\a\1\s\Source\Xamarin\Prism.Forms\Services\Dialogs\DialogService.cs:237 
  at Prism.Services.Dialogs.DialogService.ShowDialog (System.String name, Prism.Services.Dialogs.IDialogParameters parameters, System.Action`1[T] callback) [0x000a5] in d:\a\1\s\Source\Xamarin\Prism.Forms\Services\Dialogs\DialogService.cs:74 
```

### Basic Information

- Version with issue: 4.0+
- Last known good version: 3.6
- IDE: VS2019
- Platform Target Frameworks: 
  - Android

### Screenshots

see repro

### Reproduction Link

[BlankApp1.zip](https://github.com/xamarin/Xamarin.Forms/files/3312220/BlankApp1.zip)

**Comment by samhouts** [comment] 2019-06-21 22:50
@dansiegel I ran this reproduction on a couple of different emulators, and I didn't get an exception. Do I need to do something other than tap the button? Use a certain device/API? Thanks!

**Comment by dansiegel** [comment] 2019-06-21 22:59
all you need to do is tap on the button. I was using a Motorola moto g7

**Comment by samhouts** [comment] 2019-06-21 23:52
I put it on a real device (OnePlus 3T API26), just to be sure, and it still doesn't crash for me. Weird! What API level is the G7?

**Comment by dansiegel** [comment] 2019-06-22 02:48
the G7 uses API28

**Comment by samhouts** [comment] 2019-06-25 00:12
@dansiegel I'll see if someone else on the team has better (worse?) luck, but it is definitely not crashing for me, even on API 28.

**Comment by kvpt** [comment] 2019-06-25 21:38
From the stacktrace and the code, this line can throw a NullReference
https://github.com/xamarin/Xamarin.Forms/blob/5aeebd12528ec59bc02f741c1db3c680d453fc20/Xamarin.Forms.Core/TabIndexExtensions.cs#L19

Need to be :
```cs
(element as NavigableElement)?.Parent
```

It think it will fix the crash, but perhaps it will move the issue elsewhere.

**Comment by samhouts** [comment] 2019-06-26 18:42
@dansiegel What version of Xamarin.Android? What Visual Studio 2019 version specifically? Thanks!

**Comment by PureWeen** [comment] 2019-06-26 19:53
I've recreated now I'm just coordinating with @samhouts on the fix

**Comment by PureWeen** [comment] 2019-06-27 05:44
@dansiegel I'm having a little trouble recreating this issue within our test environment so I can write a UI test for it.

The crash is happening because this code returns null

https://github.com/xamarin/Xamarin.Forms/blob/37c22eb1cb64afc5d62b9386a50bb6090446a65a/Xamarin.Forms.Core/TabIndexExtensions.cs#L21

Which then causes this code to return null 

https://github.com/xamarin/Xamarin.Forms/blob/37c22eb1cb64afc5d62b9386a50bb6090446a65a/Xamarin.Forms.Core/TabIndexExtensions.cs#L29

Which passes null into this constructor

https://github.com/xamarin/Xamarin.Forms/blob/37c22eb1cb64afc5d62b9386a50bb6090446a65a/Xamarin.Forms.Core/TabIndexExtensions.cs#L12

But what I'm unclear about is why an unparented value is being passed into this code at all. 

The structure of the elements I'm seeing passed in are
- DialogContainer
  - StackLayout

Which is triggered from this code
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/VisualElementRenderer.cs#L369

Why would DialogContainer not have it's parent set to Page? do you unparent it? How is DialogContainer realized as a platform renderer?

**Comment by dansiegel** [comment] 2019-06-27 05:51
@PureWeen I'm a bit confused myself. As I recall the issue was occurring when we were creating the Dialog. The [code](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs#L209-L284) is all pretty standard where we create the UI elements, add them to a layout then when we're all done the final step would be to add it as the Content of the ContentPage. The only time anything would be "Unparented" would be when we're pulling out the original content and resetting the Page to it's original state.

**Comment by PureWeen** [comment] 2019-06-27 06:11
@dansiegel 

Is the view created here
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs#L31

Used more than once? 

It seems like there's a platform renderer created for that view before it's being assigned to the DialogContainer

**Comment by dansiegel** [comment] 2019-06-27 14:17
@PureWeen that actually sounds about right. We are taking the content that already exists on the page, putting into a container we can quickly identify then resetting the layout... then at the end unwrapping it all and resetting it to it's original state.

**Closed** 2019-06-29 14:19 UTC
Labels: i/high, i/regression, m/high impact :black_large_square:, p/Android, partner, s/needs-info ❓, s/unverified, t/bug :bug:
