### ISSUE TITLE
[Bug] SwipeView re-enables TabbedPage.IsSwipePagingEnabled

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#14364] opened 2021-06-23 11:06 UTC
### Description
When using a `TabbedPage` on Android you can set `TabbedPage.IsSwipePagingEnabled="False"` on the `TabbedPage` to disable the swipe gesture that changes the active tab.

But if one of the tab contains a `SwipeView`, after this `SwipeView` is used once (by swiping it) the global `TabbedPage` swipe gesture is re-enabled and messing with the `SwipeView`, making it very hard/impossible to use.

### Steps to Reproduce

1.  Create a `TabbedPage`, set `TabbedPage.IsSwipePagingEnabled="False"`, and add 2 tabs.
2.  In the second tab put a `SwipeView`.
3. Use a left to right swipe gesture on a blank space (it will do nothing)
4. Use the `SwipeView`.
5. Use a left to right swipe gesture on a blank space (it will switch tab)

### Expected Behavior
The gesture at step 5 should not switch tabs.

### Actual Behavior
The gesture at step 5 slides to tab 1.

### Basic Information

- Version with issue: all
- Last known good version: none
- Platform Target Frameworks: 
  - Android 10
- Affected Devices: all Android devices

### Environment

<details><summary>Show/Hide Visual Studio info</summary>
VS2019, not pertinent
</details>

### Workaround

none

I tried with a custom render without success.

I've checked the source code of https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/AppCompat/FormsViewPager.cs
as `EnableGesture` is the final target property of `IsSwipePagingEnabled` but nothing relevant in this code.

**Comment by AlleSchonWeg** [comment] 2021-07-15 09:14
Possible duplicate:
https://github.com/xamarin/Xamarin.Forms/issues/13337
https://github.com/xamarin/Xamarin.Forms/pull/13404

**Comment by jfversluis** [comment] 2021-09-06 13:29
Duplicate of #13337

**Closed by jfversluis** 2021-09-06 13:29 UTC
Labels: t/bug :bug:, s/unverified, a/swipeview
