### ISSUE TITLE
[Bug] Clear Cookies not working on WEBVIEW when SI

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/Xamarin.Forms#12998] opened 2020-11-30 07:12 UTC
### Description
After login into App, we encountered a problem when call clear cookies
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

**Comment by StephaneDelcroix** [comment] 2020-11-30 08:46
Duplicate of #12999

**Closed by StephaneDelcroix** 2020-11-30 08:46 UTC
Labels: s/unverified, t/bug :bug:
