### ISSUE TITLE
Add an Underline flag to FontAttributes t/enhancement

### ISSUE THREAD

**Issue by mattallscripts** [xamarin/Xamarin.Forms#1643] opened 2018-01-23 14:56 UTC
Duplicate of #1632 

### Description

In Xamarin Forms add a Underline flag to the FontAttributes enum. This would be accessible and used for the FontAttributes property of Labels, and Spans (for FormattedString).

### Actual Behavior

There is no built-in underline functionality in Xamarin.Forms.

### Basic Information

- Latest date with issue: January 2018

### UserVoice Link

https://xamarin.uservoice.com/forums/144858-xamarin-platform-suggestions/suggestions/19948573-add-an-underline-flag-to-fontattributes

t/enhancement

**Comment by pauldipietro** [comment] 2018-01-23 15:17
Duplicate of #1632

**Closed by pauldipietro** 2018-01-23 15:17 UTC
