### ISSUE TITLE
ReadOnly property for Entry, Editor and others

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3484] opened 2018-08-04 18:04 UTC
HI,

I know you already have IsEnabled for the controls but it will disable it which is totally different than the purpose of ReadOnly where the control is enabled but user cannot change it and it won't gray the color of control as well.

Appreciate if you add the ReadOnly property for the Entry, Editor and other controls..

Thanks,

**Comment by samhouts** [comment] 2018-08-06 23:11
This is a duplicate of #1678. Please follow that issue for updates. Thank you!

**Closed by samhouts** 2018-08-06 23:11 UTC
