### ISSUE TITLE
Crash on resume on Android device

### ISSUE THREAD

**Issue by SamuelLioult** [xamarin/Xamarin.Forms#2504] opened 2018-04-19 13:38 UTC
Hi,

I have an issue in my Android app life cycle. So when the app goes in background after a back button click, it crash. Note this issue does not appear when the app goes in background after a home button click.

Here is a part of my logs:

> 04-19 15:22:03.126 W/Mono    (13585): The request to load the assembly mscorlib v4.0.0.0 was remapped to v2.0.5.0
04-19 15:22:03.128 D/Mono    (13585): Unloading image mscorlib.dll [0x99406100].
04-19 15:22:03.128 D/Mono    (13585): Config attempting to parse: 'mscorlib.dll.config'.
04-19 15:22:03.128 D/Mono    (13585): Config attempting to parse: '/usr/local/etc/mono/assemblies/mscorlib/mscorlib.config'.
04-19 15:22:03.130 W/Mono    (13585): The request to load the assembly mscorlib v4.0.0.0 was remapped to v2.0.5.0
04-19 15:22:03.131 D/Mono    (13585): Unloading image mscorlib.dll [0x99406100].
04-19 15:22:03.131 D/Mono    (13585): Config attempting to parse: 'mscorlib.dll.config'.
04-19 15:22:03.131 D/Mono    (13585): Config attempting to parse: '/usr/local/etc/mono/assemblies/mscorlib/mscorlib.config'.
04-19 15:22:03.361 E/OpenGLRenderer(13585): resultIndex is -1, the polygon must be invalid!
04-19 15:22:03.361 E/mono-rt (13585): /proc/self/maps:
04-19 15:22:03.361 E/mono-rt (13585): 12c00000-12de4000 rw-p 00000000 00:04 8802       /dev/ashmem/dalvik-main space (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 12de4000-12fe4000 rw-p 001e4000 00:04 8802       /dev/ashmem/dalvik-main space (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 12fe4000-1ec00000 ---p 003e4000 00:04 8802       /dev/ashmem/dalvik-main space (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 32c00000-32c01000 rw-p 00000000 00:04 8803       /dev/ashmem/dalvik-main space 1 (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 32c01000-3ec00000 ---p 00001000 00:04 8803       /dev/ashmem/dalvik-main space 1 (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 70bb0000-7158f000 rw-p 00000000 b3:1c 105874     /data/dalvik-cache/arm/system@framework@boot.art
04-19 15:22:03.361 E/mono-rt (13585): 7158f000-73465000 r--p 00000000 b3:1c 105875     /data/dalvik-cache/arm/system@framework@boot.oat
04-19 15:22:03.361 E/mono-rt (13585): 73465000-74b92000 r-xp 01ed6000 b3:1c 105875     /data/dalvik-cache/arm/system@framework@boot.oat
04-19 15:22:03.361 E/mono-rt (13585): 74b92000-74b93000 rw-p 03603000 b3:1c 105875     /data/dalvik-cache/arm/system@framework@boot.oat
04-19 15:22:03.361 E/mono-rt (13585): 74b93000-74cde000 rw-p 00000000 00:04 8801       /dev/ashmem/dalvik-zygote space (deleted)
04-19 15:22:03.361 E/mono-rt (13585): 74cde000-74cdf000 rw-p 00000000 00:04 10631      /dev/ashmem/dalvik-non moving space (deleted)
04-19 15:22:03.362 E/mono-rt (13585): 74cdf000-74cea000 rw-p 00001000 00:04 10631      /dev/ashmem/dalvik-non moving space (deleted)
04-19 15:22:03.362 E/mono-rt (13585): 74cea000-78394000 ---p 0000c000 00:04 10631      /dev/ashmem/dalvik-non moving space (deleted)
04-19 15:22:03.362 E/mono-rt (13585): 78394000-78b93000 rw-p 036b6000 00:04 10631      /dev/ashmem/dalvik-non moving space (deleted)
...
04-19 15:22:03.399 F/libc    (13585): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 13661 (hwuiTask1)

- Version with issue: Xamarin.Forms 2.5.0.122203
- IDE: Visual Studio 2017 Community 15.5.4
- Platform Target Frameworks:
  - Android: 6.0
- Android Support Library Version: 4
- Affected Devices: Nexus 5 Android 6.0.1

Thanks.
Samuel

**Comment by samhouts** [comment] 2018-04-19 16:58
From the stack trace, it looks like you're using OpenGL. I wonder if something is being disposed too early or too late. Can you provide a small reproduction project that demonstrates this issue? I'm not sure we'll have much luck diagnosing the issue without at least knowing more information about your app (e.g., structure, controls, etc.). Thanks!

**Comment by SamuelLioult** [comment] 2018-04-20 07:36
Hi @samhouts ,
Thanks for your time. After you told me about OPENGL, I asked myself the right questions. And it occurred to me that my use of OPENGL was probably an animation. After new investigations it turns out that a translation animation was called twice almost simultaneously by two different threads. So I was able to solve this problem that we can perhaps rather attribute to the management of my life cycle than XF.

**Comment by samhouts** [comment] 2018-04-20 16:56
Very good! I'll go ahead and close this now, but if you experience any other issues or believe that work still needs to be done here, please feel free to reopen the issue or create a new one. Thank you!

**Closed by samhouts** 2018-04-20 16:56 UTC
Labels: i/critical, p/Android, s/needs-info, s/needs-repro
