### ISSUE TITLE
[UWP]XF3.6 Exception with Switch on StackLayout with IsVisible="false"

### ISSUE THREAD

**Issue by sude22** [xamarin/Xamarin.Forms#5517] opened 2019-03-12 11:12 UTC
### Description
Exception is thrown while showing a page with a Switch in a `<StackLayout IsVisible="false"/>`
StackTrace:
   at Windows.UI.Xaml.VisualStateManager.GetVisualStateGroups(FrameworkElement obj)
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.UpdateOnColor()
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)
Message:
System.ArgumentException: Falscher Parameter.

element
   at Windows.UI.Xaml.VisualStateManager.GetVisualStateGroups(FrameworkElement obj)
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.UpdateOnColor()
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)

### Basic Information

- Version with issue:3.6.0.220655
- Last known good version:3.4
- IDE:
- Platform Target Frameworks: 
  - UWP:  17134 -->

**Comment by samhouts** [comment] 2019-03-12 17:48
[Issue5517.zip](https://github.com/xamarin/Xamarin.Forms/files/2958102/Issue5517.zip)

**Comment by samhouts** [comment] 2019-03-12 17:48
Caused by #4883, probably

**Comment by sude22** [comment] 2019-03-13 06:07
This one is a real blocker. It would be very much appreciated if this could be fixed in the next release..

**Comment by AnEnglishmanInNorway** [comment] 2019-03-17 18:05
For me the problem seems to be independent of whether there is a StackLayout. My <Switch> was set IsVisible=false, and I got exactly the crash described here. Changing it to true fixed the problem (though my UI looked weird). But setting IsVisible to false in the code of the handler for Toggle gave me a workaround.

**Comment by jalbertSyncroTech** [comment] 2019-03-19 15:26
There's a discussion on the forums regarding the issue, the only work-around appears to be writing a custom renderer that overrides OnElementChanged() and OnElementPropertyChanged() to avoid the call to UpdateOnColor()
https://forums.xamarin.com/discussion/151252/switch-crashing-uwp-app-post-upgrade-to-xf-3-6

**Comment by yrest** [comment] 2019-03-21 09:38
Same for me, but 3.5 works fine https://github.com/xamarin/Xamarin.Forms/pull/4883#discussion_r267342643

**Comment by JKennedy24** [comment] 2019-03-27 10:48
also getting this error

**Comment by vividos** [comment] 2019-04-25 16:54
I think this was fixed by PR #5633; the error goes away for my UWP project when I update to the latest Xamarin.Forms 3.6.0 NuGet package (tested with 3.6.0.344457).

**Comment by psp589** [comment] 2019-04-26 10:13
As @vividos says it seems to be fixed, it is working for me as well ( with version 3.6.0.344457)

**Comment by samhouts** [comment] 2019-05-10 16:30
closed by #5633

**Closed by samhouts** 2019-05-10 16:30 UTC
Labels: blocker, e/1 :clock1:, i/regression, p/UWP, t/bug :bug:

**Comment by delaney31** [comment] 2020-03-25 14:16
It's back! I'm getting the same error after updating my UWP projects to 4.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.UpdateOnColor()
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)
