### ISSUE TITLE
[Bug] The group footer appears always when CollectionView is set grouped

### ISSUE THREAD

**Issue by ionixjunior** [xamarin/Xamarin.Forms#8558] opened 2019-11-18 23:16 UTC
### Description

I created a grouped list and defined a data template for group header. After this the group footer was displayed in the page.

I made a workaround for this defining the group footer and add an empty label.

### Steps to Reproduce

1. Open the project at attachment and run in iOS simulator
2. See the name of the class (toString) in the group footer (the group footer is not defined in the XAML)

### Expected Behavior

The group footer should not be displayed until group footer data template is defined.

### Actual Behavior

The group footer is displayed without any group footer defined in XAML.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.991211 (but occurs in the pre-release too)
- Last known good version: I don't know
- IDE: Visual Studio for Mac 8.3.9
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS 13.6.0.12

This problem is happening in iOS only. Android is fine and UWP I don't tested.

### Screenshots

<img width="300" src="https://user-images.githubusercontent.com/519642/69101901-a410c000-0a3f-11ea-9e85-8c52694a4828.png" />

### Reproduction Link

[CollectionViewBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/3861086/CollectionViewBugs.zip)

**Comment by GalaxiaGuy** [comment] 2019-11-19 09:53
https://github.com/xamarin/Xamarin.Forms/issues/8228

There is also a PR in progress: https://github.com/xamarin/Xamarin.Forms/pull/8341

**Comment by jfversluis** [comment] 2019-11-23 20:32
Duplicate of #8228

**Closed by jfversluis** 2019-11-23 20:32 UTC
Labels: a/collectionview, p/iOS 🍎, s/unverified, t/bug :bug:
