### ISSUE TITLE
[Bug] [iOS] SfExpander does not render and occurs error with XF latest version 4.3.0.991221

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#8825] opened 2019-12-10 10:50 UTC
### Description
SfExpander loads properly until the version XF 4.3.0.991211. After updating the forms version, 
the Expander application did not load in the iOS platform.

### Steps to Reproduce

1.  Run the sample.
Note: Below error occurs.

### Expected Behavior
The expander should render in iOS without any error.

### Actual Behavior
![image](https://user-images.githubusercontent.com/44390143/70523247-9f37bb80-1b68-11ea-8fde-a7c1ed620580.png)

### Basic Information

- Version with issue: XF 4.3.0.991221
- Last known good version: XF 4.3.0.991211
- Platform Target Frameworks: 
  - iOS: 

### Screenshots

![image](https://user-images.githubusercontent.com/44390143/70523336-d8702b80-1b68-11ea-88ba-9a2ba91666a0.png)

### Reproduction Link

https://www.syncfusion.com/downloads/support/directtrac/general/ze/ExpanderSample-1043310308

**Comment by kingces95** [comment] 2019-12-18 00:37
Worked for me on VS after upgrading all nuget packages.

![image](https://user-images.githubusercontent.com/4120386/71045892-b895b600-20da-11ea-8aef-9bc98cddb114.png)

**Comment by samhouts** [comment] 2019-12-30 20:32
@GnanaPriyaNamasivayam Can you please try updating to the latest version and verify that it still crashes for you? Thanks!

**Comment by GnanaPriyaNamasivayam** [comment] 2019-12-31 05:07
@samhouts , Yes. It works fine with latest version.
![image](https://user-images.githubusercontent.com/44390143/71610731-7c258800-2bb9-11ea-99a8-f4e27e1b22b7.png)

Thanks for the update.

**Comment by samhouts** [comment] 2019-12-31 18:36
Duplicate of #8765

**Closed by samhouts** 2019-12-31 18:36 UTC
Labels: 4.3.0, a/buildchain, i/regression, p/iOS 🍎, partner, s/needs-info ❓, s/unverified, t/bug :bug:
