### ISSUE TITLE
SizeChanged not fired after NavigationPage.SetHasNavigationBar

### ISSUE THREAD

**Issue by OABsoftware** [xamarin/Xamarin.Forms#3291] opened 2018-07-13 10:01 UTC
Since I applied the latest Xamarin.Forms update to my project(3.1.0.637273), I no longer receive a SizeChanged event after having called NavigationPage.SetHasNavigationBar().

Steps to Reproduce:
1. Make a form
2. Add a handler for the SizeChanged event of the form
2. Add a button
3. In the clickhandler of that button call the NavigationPage.SetHasNavigationBar method to make the navigationbar disappear
4. Notice that the SizeChanged event is not fired after the NavigationPage.SetHasNavigationBar has been called.

Expected Behavior:
In previous versions the SizeChanged event was raised after having called NavigationPage.SetHasNavigationBar.

**Comment by pauldipietro** [comment] 2018-07-13 12:04
I believe the platform in question having the issue here is UWP based on what I can tell.

**Comment by OABsoftware** [comment] 2018-07-13 14:08
No, sorry for not mentioning this, but the issue manifests itself on the Android platform.

**Comment by pauldipietro** [comment] 2018-07-13 14:33
I was not able to reproduce it on Android although UWP seemed to have some issues between 3.0 and 3.1. Can you provide a repro and clarify which version of Android you're running against?

**Comment by AwsomeCode** [comment] 2018-07-13 17:49
@pauldipietro We having issue of tool bar items are not visible after upgrading XF 3.1.0.583944 to Current 3.1.0.637273 in UWP.

**Comment by samhouts** [comment] 2018-08-15 16:44
@AwsomeCode You have a different issue (#3297) that is resolved in the latest service release. Thank you!

@OABsoftware Since we did not receive the information requested in more than 30 days, we are hoping that this issue no longer affects you. If it does, please feel free to reopen this issue and attach a small project that exhibits the problem. Thank you!

**Closed by samhouts** 2018-08-15 16:44 UTC
Labels: e/5 :clock5:, i/high, i/regression, p/Android, s/needs-repro, t/bug :bug:
