### ISSUE TITLE
Collectionview scrolling choppy when loading cells [Android][Spec]  

### ISSUE THREAD

**Issue by lorenzobrusco** [xamarin/Xamarin.Forms#9562] opened 2020-02-13 14:23 UTC
### Description
We use xamarin forms to create a social media app and we create a page that contains two collectionview, the first one that contains an image, a button and the second one , inside the first one that contains six images with also labels.
The problem persists also after loaded the image, and it occurs only on Android.
I found many other threads over this problem.

### Steps to Reproduce

1. Create two collection view, one inside the other
2. Put inside the second one six images, we use ffimageloading to fast loading,  and some labels, and set it in Horizontal mode
3. Add many items, we test with at least 20 items, and scroll up and down

### Expected Behavior
smooth scroll

### Actual Behavior
choppy scroll

### Basic Information
- Version with issue: 1.0
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - iOS:  >= 13.x 
  - Android: >= 9.x
- Affected Devices: All devices that we used to test, such us:
    - Samsung galaxy s9
    - Samsung galaxy s10
    - Huawei Mate 20 lite

**Comment by Huaba93** [comment] 2020-02-13 16:07
maybe duplicate of my issue #9556 ?

**Comment by lorenzobrusco** [comment] 2020-02-13 17:16
Yes it's the same

Il Gio 13 Feb 2020, 17:07 Huaba93 <notifications@github.com> ha scritto:

**Comment by samhouts** [comment] 2020-02-13 18:00
Duplicate of #9556

**Closed by samhouts** 2020-02-13 18:00 UTC
Labels: a/collectionview, a/performance, p/Android, s/unverified, t/bug :bug:
