### ISSUE TITLE
[Bug] Crash in Xamarin.Forms - Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <Syncfusion_SfPdfViewer_XForms_iOS_CustomPageRenderer 0x7fdd9e3c0fe0> for the key path "sublayers" from <CALayer 0x600007b66aa0> because it is not registered as an observer.

### ISSUE THREAD

**Issue by Essaadani** [xamarin/Xamarin.Forms#14901] opened 2021-11-17 16:29 UTC
### Description
After upgrading Xamarin.Forms to the latest version > 5, I had this crash on my application with the Syncfusion PdfViewer control.
The bug seems more related to the latest versions of Xamarin.Forms since the SF control works fine with previous versions of XF.

### Steps to Reproduce

1. Use Xamarin.Forms 5 and SfPdfViewer
2. Add SfPdfViewer to a page
3. Run the application and navigate to the page containing the SfPdfViewer
4. Return to the previous page
5. The application crashes

### Expected Behavior
The app should work as expected.

### Actual Behavior
The application crashes and displays the following exception:
`Objective-C exception thrown.  Name: NSRangeException Reason: Cannot remove an observer <Syncfusion_SfPdfViewer_XForms_iOS_CustomPageRenderer 0x7fdd9e3c0fe0> for the key path "sublayers" from <CALayer 0x600007b66aa0> because it is not registered as an observer.`
### Basic Information

- Xamarin.Forms version: 5.0.0.2244
- SfPdfViewer version: 19.3.0.54

### Environment
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.13 (build 11)
Installation UUID: 79d427f6-9c60-4ba9-9f33-793792058232
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.403/Sdks
SDK Versions:
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.203
	5.0.202
	5.0.201
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.409
	3.1.408
	3.1.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.6
	5.0.5
	5.0.4
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.15
	3.1.14
	3.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.415

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Version: 8.2.0.1 (Visual Studio Enterprise)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:55-0400

=== Xamarin.iOS ===

Version: 15.2.0.1 (Visual Studio Enterprise)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 20:09:18 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/khalidessaadani/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
2021-09-14
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:12 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:30 UTC

=== Build Information ===

Release ID: 810130011
Git revision: 53e3946a0f6b630a1124eb7ff26c1b545d040d32
Build date: 2021-11-04 11:20:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Thu Sep 30 06:41:59 PDT 2021
    root:xnu-8019.40.96.0.2~12/RELEASE_X86_64 x86_64

**Comment by jfversluis** [comment] 2021-11-18 08:06
Duplicate of #14887

**Comment by jfversluis** [comment] 2021-11-18 08:07
Should be fixed in the next version and already be fixed in the current nightly. Would be great if you could confirm. Thanks! :)

**Closed by jfversluis** 2021-11-18 08:06 UTC
Labels: t/bug :bug:, s/unverified

**Comment by Essaadani** [comment] 2021-11-18 12:31
Hi @jfversluis,

Indeed it's fixed in the nightly build, thank you very much for your help.

**Comment by davibittencourtome** [comment] 2021-11-24 11:59
Which version did you solve with @Essaadani  ? I upgraded to version nightly 5.0.1.1876 and now another problem has arisen:

`System.TypeLoadException: 'Could not load type Syncfusion.SfPdfViewer.XForms.Droid.ButtonRendererAndroid while decoding custom attribute: (null)'`

**Comment by jfversluis** [comment] 2021-11-24 12:06
@davibittencourtome that doesn't look like the right nightly version. Make sure that you use the (updated) link in the README. The right version should be 5.0.0.xxx

**Comment by davibittencourtome** [comment] 2021-11-24 14:28
Really @jfversluis , I was using a url from your old blog "https://aka.ms/xf-ci/index.json", I updated it to url from README and managed to download the latest version 5.0.0.xxx-nightly.

Forgive me. Thanks!

**Comment by jfversluis** [comment] 2021-11-24 14:54
No worries, it's us who quietly changed the URL :)

Glad we got it figured out!

**Comment by GivennameSurname** [comment] 2021-11-30 12:24
Stumbled over this as well. 

Unfortunately, I can't wait for the update but (if anyone else also needs a quick workaround) just use Version ["5.0.0.2125"](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-sr5) on your iOS-Project.
