### ISSUE TITLE
iOS: Listview item loses binding, does not respond to tapped event, when ObservableCollection item is moved

### ISSUE THREAD

**Issue by michaeldimoudis** [xamarin/Xamarin.Forms#5117] opened 2019-02-03 04:04 UTC
### Description

When a ListView item is reordered, that reordered item no longer fires ItemTapped events. Issue is in iOS only, works in Android.

It works in 3.4.0.1008975. It does not work in 3.4.0.1009999, and still does not work in 3.5.0.94564-pre3 (I did not try 4.0.0-pre's)

To test, slide to activate context menus, and tap up/down icon to move item up or down.

### Steps to Reproduce

1. Minimal repro is available here https://github.com/michaeldimoudis/listview-move-repro
2. Once built and running, slide to activate context menus, and tap up/down icon to move item up or down.
3. You can no longer tap on that item to fire ItemTapped events.

### Expected Behavior
When moving an item up or down in a ListView, you should still be able to tap on that item and it should fire the ItemTapped event.

### Actual Behavior
When moving an item up or down in a ListView, you can no longer tap on that item to fire the ItemTapped event.

### Basic Information

- Version with issue: 3.4.0.1009999
- Last known good version: 3.4.0.1008975
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS: 12.1
- Nuget Packages: Only Xamarin Forms
- Affected Devices: iOS devices only

### Reproduction Link

https://github.com/michaeldimoudis/listview-move-repro

**Comment by samhouts** [comment] 2019-02-05 20:43
Duplicate of #4987

**Closed by samhouts** 2019-02-05 20:43 UTC
Labels: t/bug :bug:
