### ISSUE TITLE
Unhandled Exception with boolean binding when ConverterParameter set instead of Converter

### ISSUE THREAD

**Issue by bmacombe** [xamarin/Xamarin.Forms#4446] opened 2018-11-16 17:19 UTC
### Description
If you accidentally set a binding where you intended to add a IValueConverter, but accidentally set the ConverterParameter instead, it generates an exception at runtime that is only caught by the app level exception handling and causes the app to crash.  I've only noticed this on IsVisible, but I've tested against a string property and it does not error then.  My assumption is this only matters where the property is of a non-nullable type

IsVisible="{Binding Text, ConverterParameter={StaticResource DummyValueConverter}}" - Errors
Text="{Binding Text, ConverterParameter={StaticResource DummyValueConverter}}" - Works
### Steps to Reproduce

1. Create a binding to a non-nullable type and set the ConverterParameter instead of the Coverter on the binding

### Expected Behavior
Generates an exception, but with better detail of what the error is.  

### Actual Behavior
Get a null reference exception from part of the binding system that isn't clear what caused it.

- Version with issue: 3.3.0.967563
- IDE: VS 15.9.0

### Reproduction Link

https://github.com/bmacombe/XFValueConveterRepo

Start the reproduction app, it will not load the items in the main list (or at least the xaml for them).  Click anywhere in the main window and it will crash.

Object reference not set to an instance of an object.

   at Xamarin.Forms.VisualElement.<>c.<.cctor>b__268_3(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)
   at Xamarin.Forms.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)
   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.Cell.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.UpdateContent(TItem content, Int32 index, Object item)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.ActivateContent(Int32 index, Object item)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.CreateContent(Int32 index, Object item, Boolean insert)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.GetOrCreateContent(Int32 index, Object item)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.get_Item(Int32 index)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnListItemClicked(Object sender, ItemClickEventArgs e)

**Comment by bmacombe** [comment] 2018-11-16 17:20
Related to #4440

**Comment by StephaneDelcroix** [comment] 2018-11-16 20:38
could you please attach your repro app ? I can't reproduce with the xaml you posted.

**Comment by bmacombe** [comment] 2018-11-16 20:40
https://github.com/bmacombe/XFValueConveterRepo

Sorry, thought I had that in there

**Comment by kingces95** [comment] 2018-11-16 23:54
Stephane to triage...

**Comment by StephaneDelcroix** [comment] 2018-11-17 12:39
it's unrelated to the ConverterParameter. I can reproduce this in your sample without it. It's about the text being cast to a bool...

also, I can repro in 3.4.0

**Comment by bmacombe** [comment] 2018-11-17 16:35
Let me add another case to the repro project to see what happens.  In my app the value converter I was using did indeed return  boolean unlike the dummy converter in the sample.

**Comment by bmacombe** [comment] 2018-11-17 16:42
Nevermind...to early on a Saturday :) ...what the converter does doesn't matter.  It's the binding to something that isn't a bool that is cause the error.  So having the ConverterParameter set doesn't matter..it's the fact that it can't cast the bound value.  That makes perfect sense.  An improved exception message would be great.

**Comment by StephaneDelcroix** [comment] 2018-11-17 19:13
We actually test for incompatible types, Log a Warning, and continue. What I don't get is why it doesn't work in your project...

**Comment by bmacombe** [comment] 2018-11-17 20:13
Got curious and pulled the source.  I wonder if BindableObject.TryConvert isn't handling bool correctly...but I can't prove it yet

**Comment by StephaneDelcroix** [comment] 2018-11-17 20:14
I found out too, and just pushed a fix

**Comment by bmacombe** [comment] 2018-11-17 20:15
Cool, I just missed it..I'll check it out.  Thanks for the quick fix!

**Closed** 2018-11-20 08:47 UTC
Labels: a/binding ⛓, s/needs-repro ❔, t/bug :bug:
