### ISSUE TITLE
[Bug] CollectionView Cells Content Shift Issue on iOS

### ISSUE THREAD

**Issue by rudyspano** [xamarin/Xamarin.Forms#10786] opened 2020-05-20 07:34 UTC
### Description
CollectionView cells are shifted by 1 pixel on left and on top on iOS.
-Same behavior on Header and Footer.
-Same behavior with GridItemsLayout

Analysis:
The Root Container of cells (of DataTemplate) adds by default Bounds of (-1, -1, width, height) on native views.

It can be seen using XCode UI debug tool.

### Steps to Reproduce

1. Add a CollectionView with Cells, Header, Footer

### Expected Behavior

No Shift.

### Actual Behavior

1 Pixel's shift on left and on top for each cell

### Basic Information

Version with issue: 4.5.0.657
IDE: Visual Studio Mac
Platform Target Frameworks:
iOS: 9.3
Affected Devices: All iOS devices

### Screenshots
![image](https://user-images.githubusercontent.com/21014908/82418523-61c34c80-9a7d-11ea-8711-64f48d84e17c.png)

### Reproduction Link

[ColectionViewiOSShift.zip](https://github.com/xamarin/Xamarin.Forms/files/4655267/ColectionViewiOSShift.zip)

Red parts should not be displayed:

>             <CollectionView.ItemTemplate>
>                 <DataTemplate>
>                     <Grid HeightRequest="75" BackgroundColor="Red">
>                         <Grid BackgroundColor="White">
>                             <Label HorizontalOptions="Center" VerticalOptions="Center" Text="Cell"/>
>                         </Grid>
>                     </Grid>
>                 </DataTemplate>
>             </CollectionView.ItemTemplate>

### Workaround

- OnPlatform Margins of -1 on left and top (adds complexity on views...)
- Platform Effect on iOS to set on root Container of cells. (See Reproduction sample)

**Comment by samhouts** [comment] 2020-05-26 22:03
Duplicate of #8961

**Closed by samhouts** 2020-05-26 22:03 UTC
Labels: a/collectionview, p/iOS 🍎, s/unverified, t/bug :bug:
