### ISSUE TITLE
[Bug] [iOS] Navigation.PushAsync not work 

### ISSUE THREAD

**Issue by devinZhou102** [xamarin/Xamarin.Forms#10233] opened 2020-04-07 06:05 UTC
### Description

Navigation.PushAsync not work 

```C#
    public partial class App : Application
    {
        AppShell AppShellCache;
        public App()
        {
            InitializeComponent();
            AppShellCache = new AppShell();
            MainPage = AppShellCache;
        }


        protected override void OnResume()
        {
            // I need do something here,then set AppShellCache as MainPage
            // after that, Navigation in Shell not work
            MainPage = new ContentPage();
            MainPage = AppShellCache;
        }
    }
```

### Steps to Reproduce

1. Create a Xamarin Forms Shell mobile application
2. In App.cs set MainPage as AppShell and cached AppShell
3. In OnResume method, first set ContentPage as MainPage,then set cached AppShell as MainPage 
4. Click "Add" button

### Expected Behavior

After OnResume , Navigation.PushAsync can work nomally.

### Actual Behavior

After OnResume , Navigation.PushAsync not work.

### Basic Information

Demo:[NavigationTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4442300/NavigationTest.zip)

- IDE: VS2019 16.5.2

**Comment by PureWeen** [comment] 2020-04-09 15:41
@devinZhou102 why are you setting ContentPage and then directly after setting Shell?

This might just be a duplicate of this issue
https://github.com/xamarin/Xamarin.Forms/issues/6697

**Comment by samhouts** [comment] 2020-05-26 18:28
@devinZhou102 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2020-05-26 18:28 UTC
Labels: a/navigation, a/shell :shell:, p/iOS 🍎, s/needs-info ❓, s/unverified, t/bug :bug:
