### ISSUE TITLE
Multible Entries in ListView Header causes wrong bindings behavior

### ISSUE THREAD

**Issue by Schullebernd** [xamarin/Xamarin.Forms#7069] opened 2019-08-05 21:18 UTC
### Description
If a ListView is defined with a header and the header contains multible Entries the Bindings are not working anymore or only for the first entry.

### Steps to Reproduce

1. Create a new XAML Page
2. Add a Listview with a header
3. Insert two or more Entries to the header
4. Add a ViewModel for the Page and add a View Model Property for each Entry in the Header.
5. Add the appropriate Bindings to the Entries.

### Expected Behavior
After loading the page and changing the content of Entry 1, the Property of Entry 1 Binding should change. Changing the content of Entry 2, the Property of Entry 2 Binding should change.

### Actual Behavior
Changing the content of Entry 1 works. If you change the content of Entry 2, nothing happens. Or, in case you have changed Entry 1 before, then the Property on Entry 1 changes, when typing some text into Entry 2.

### Basic Information

- Version with issue: 
XAMARIN 16.2.0.90
XAMARIN Android SDK 9.4.0.51
- Last known good version: not known
- IDE: VS 2019 16.2.0
- Platform Target Frameworks: 
  - iOS:  no Problems
  - Android: Here the problems occures.
  - UWP:  not tested
- Android Support Library Version: v28.0.0.1
- Nuget Packages:
- Affected Devices:
 No Problems on Emulator with Android Oreo 8.1 API 27
 Problem exists on real device ZTE Blade with Android 7.0 API 24

### Screenshots
![image](https://user-images.githubusercontent.com/11478863/62495607-b0497800-b7d6-11e9-8ced-25749142e921.png)
Editting the second entry is not possible. No input is recognized. Editting the first entry 'Kennung' and then start to edit the second Entry 'Name', the content of 'Kennung' changes.

Here is the code of my listview header.
```XAML
<ContentPage.Content>
        <StackLayout Padding="10,10,10,10">
            <ListView x:Name="listView" Margin="0,0,0,0" HasUnevenRows="True" SelectionMode="None" ItemTapped="ListView_ItemTapped" ItemsSource="{Binding Series}">
                <!-- ItemSource is set in the code behind, because there is no update to the labels after changing values of a series and returning back to this page -->
                <ListView.Header>
                    <StackLayout>
                        <Label Text="Disziplin Basisdaten" VerticalOptions="Start" HorizontalOptions="Start" FontAttributes="Bold" FontSize="Large"/>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Kennung" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="100" WidthRequest="100"></Label>
                            <controls:MyEntry HorizontalOptions="FillAndExpand" Text="{Binding ShortName}" IsEnabled="{Binding IsChangeable}" FontSize="Medium" BackgroundColor="White"/>
                        </StackLayout>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Name" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="100" WidthRequest="100"></Label>
                            <controls:MyEntry HorizontalOptions="FillAndExpand" Text="{Binding Name}" IsEnabled="{Binding IsChangeable}" FontSize="Medium" BackgroundColor="White" MaxLength="50"/>
                        </StackLayout>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Details" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="100" WidthRequest="100"></Label>
                            <Editor HorizontalOptions="FillAndExpand" Text="{Binding Description}" IsEnabled="{Binding IsChangeable}" FontSize="Small" BackgroundColor="White" HeightRequest="70"/>
                        </StackLayout>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Distanz" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="200" WidthRequest="200"></Label>
                            <controls:MyEntry Keyboard="Numeric" HorizontalOptions="Start" WidthRequest="50" Text="{Binding Distance}" IsEnabled="{Binding IsChangeable}" FontSize="Medium" BackgroundColor="White"/>
                            <Label Text="m" VerticalOptions="Center" FontSize="Medium"></Label>
                        </StackLayout>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Dezimalanzeige" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="200" WidthRequest="200"></Label>
                            <Switch HorizontalOptions="Start" IsToggled="{Binding ShowDecimal}" ></Switch>
                        </StackLayout>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Als Favorit wählen" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Medium" MinimumWidthRequest="200" WidthRequest="200"></Label>
                            <Switch HorizontalOptions="Start" IsToggled="{Binding IsFavorite}" ></Switch>
                        </StackLayout>
                        <Label Text="Schuss-Serien" VerticalOptions="Start" HorizontalOptions="Start" FontAttributes="Bold" FontSize="Large" Margin="0,20,0,0"/>
                        <Label Margin="0, 0, 0, 0" Text="{Binding TotalShots, StringFormat='Insgesamt werden {0} Schüsse abgegeben.'}" VerticalOptions="Start" HorizontalOptions="Start" FontAttributes="Bold" FontSize="Small" x:Name="TotalShotsLabel" TextColor="DarkGray"/>                        
                    </StackLayout>
                </ListView.Header>`

**Comment by jfversluis** [comment] 2019-08-06 08:54
Hey @Schullebernd, thanks for reporting this!

Would it be possible to add a small reproduction project for this? That way we can see what your actual scenario is and hopefully quickly find out what is going on.

Thanks!

**Comment by Schullebernd** [comment] 2019-08-06 15:50
Of course, no problem. Just created a simple example project.
[MyTests.zip](https://github.com/xamarin/Xamarin.Forms/files/3472954/MyTests.zip)

The weird thing is that it seems not depending on the mono framework that is installed. I just tried it in the emulator with Android 7.0 an everything is ok there. Also some other real devices seems not to have the problem. Here is a screen recording of my phone where I run this example app.
[recording_ZTE_BLADE_V0850.zip](https://github.com/xamarin/Xamarin.Forms/files/3473061/recording_ZTE_BLADE_V0850.zip)

**Comment by jfversluis** [comment] 2019-08-07 08:15
Hm it doesn't show the problem on my emulators (both 7.0 or newer) or Samsung S10e. That makes it a bit hard to say what is going on here.

Also, the app shown in your video and the one attached seem a bit different? Are you sure it's the exact same code?

**Comment by Schullebernd** [comment] 2019-08-07 08:31
The Problem does not occure on all devices, that is the strange thing.
But the video should belong to the test project I have uploaded. Are there any differentes between the video and the source code? I pressed the play button, the App started on the device and I started the screen recorder. 

I only removed the bin and obj folders before zipping the project.

I also did a factory reset on the device before.

**Comment by Schullebernd** [comment] 2019-08-07 08:36
Oh, I just see, that the zip does not contain the final viewpage. (I only addded some labels and Exempel list items). Have to zip and upload again. Sorry for this confusion. But the Problem should also occure in this version.

**Comment by jfversluis** [comment] 2019-08-07 08:43
No worries, I just want to be sure we are looking at the same thing to rule out any discrepancies :) 

The strange thing is I see that the right field seems to have the focus and even the caret but when you type it goes somewhere else. At this point it seems pretty specific to the ZTE phone.

**Comment by Schullebernd** [comment] 2019-08-07 10:53
Maybe, but with this behavior I don‘t know which further devices are affected. 
Maybe there will be a Developer here, who can reproduce the Problem with his device.

**Comment by PureWeen** [comment] 2019-08-16 18:12
@Schullebernd does this look like the same issue?

https://github.com/xamarin/Xamarin.Forms/issues/7141

**Comment by Schullebernd** [comment] 2019-08-20 16:22
@PureWeen
Yes, looks exactly like my problem. But it seems to appear only on special devices.

**Comment by samhouts** [comment] 2019-08-20 21:49
Duplicate of #7069

**Closed by samhouts** 2019-08-20 21:49 UTC
Labels: a/listview, p/Android, s/needs-repro ❔, s/unverified, t/bug :bug:
