### ISSUE TITLE
Not able to select item in Collection View. Please see the sample attached !

### ISSUE THREAD

**Issue by asifmahmud-bd** [xamarin/Xamarin.Forms#14489] opened 2021-08-03 11:26 UTC
Not able to select item in Collection View. Please see the sample attached ! 
Xamarin Forms Version : 5.0.0.2012
VSMac : 8.9.10 (build 4)
https://github.com/samirgcofficial/CollectionViewBug

_Originally posted by @samirgcofficial in https://github.com/xamarin/Xamarin.Forms/issues/11179#issuecomment-845607723_

**Comment by Tommigun1980** [comment] 2021-08-03 12:25
Selection in CollectionView just doesn’t work: https://github.com/xamarin/Xamarin.Forms/issues/13592

I don’t think they’ll fix it.

**Comment by jfversluis** [comment] 2021-08-24 13:46
Duplicate of #13592

**Closed by jfversluis** 2021-08-24 13:46 UTC
Labels: t/bug :bug:, a/collectionview, s/unverified
