### ISSUE TITLE
[Enhancement] Better animations

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#6999] opened 2019-07-29 03:52 UTC
## Summary
The current `Animation` implementation seems complex and performs poorly when multiple non-trivial views are animated (such as translating two ListViews at the same time). There should be a new way for us to animate objects by taking advantage of hardware acceleration and avoiding things like a timer.

I can't find a good substitute for the current implementation. I've looked at [Xamarin Transitions](https://github.com/OliveTreeBible/Xamarin.Transitions), but the project is not actively being maintained and doesn't seem to work as of now.

**Comment by jfversluis** [comment] 2019-07-29 06:46
Would #4233 help with that?

**Comment by adrianknight89** [comment] 2019-07-29 13:04
It's not clear to me if `Storyboard` is building on top of the existing animation implementation. It sounds like that's the case. If it is true, then `Storyboard` will have the same issues. We need to be able to leverage hardware acceleration (see this [post](https://blog.danlew.net/2015/10/20/using-hardware-layers-to-improve-animation-performance/)) and use native animation APIs as much as possible. The current implementation was written back in [2012](https://github.com/xamarin/Xamarin.Forms/blob/88577eac76e5a20fe1415ed0e67ac3e3d97bdd21/Xamarin.Forms.Core/Animation.cs#L7) and needs to be re-thought, imo.

**Comment by jrahma** [comment] 2019-08-03 20:52
I would say it should apply to all form navigation so it will look like this:

` 
Navigation.PushModalAsync(new NavigationPage(new MyForm()), Transition.SlideFromTop, 2000);
`

Where 2000 is the time to take in milliseconds

The Transition can be:

- SlideFropTop
- SlideFropButtom
- SlideFropRight
- SlideFropLeft
- Scale
- Zoom
- Fade

The same thing can e applied to OnDisappearing, 

for example below I am opening the page using SlideFromLeft:

`Navigation.PushModalAsync(new NavigationPage(new MyForm()), Transition.SlideFromLeft(2000));
`

and closing it using Fade:

```
protected override void OnDisappearing()
{
     base.OnDisappearing();

     Transition.Fade(2000);
}

```
Thanks,
[Jassim](https://www.softnames.com)

**Comment by adrianknight89** [comment] 2019-08-04 00:12
@jrahma I believe there is an existing issue / PR for what you need. This issue is different in that I want a better animation framework that hands off as much work as possible to the native layers to do basic translate, scale, fade, etc. So, when I do something like:

```
await Task.WhenAll
(
      view1.TranslateTo (-100, 0),
      view2.TranslateTo (0, 0)
);
```

this animation should be smooth when `view1` and `view2` are complex instead of simple box views or buttons.

I've recently created a simple, **hacky** dependency service that animates views for me. The animations are 10x better compared to using Xamarin Forms' animation framework. I directly use `ObjectAnimator` on Android and `UIViewPropertyAnimator` on iOS. It does the job for me for my use case, but it skips a lot of visual element tracking Forms does, so it's not for production use. :)

**Comment by raindeer** [comment] 2019-10-01 18:29
@adrianknight89 would you care to share your hacky solution?

**Comment by adrianknight89** [comment] 2019-10-03 21:48
@raindeer I'll get back to you on this later. I'm a bit busy right now with work and other things. I hope to update you back this weekend.

**Comment by adrianknight89** [comment] 2019-10-16 02:55
@raindeer Hi, sorry I forgot about this...

Here's the Android implementation:

```
public async Task TranslateViewAsync(View view)
 {
      var renderer = view.GetRenderer();

      renderer.View.SetLayerType(LayerType.Hardware, null);

      ObjectAnimator objectAnimator;

      objectAnimator = ObjectAnimator.OfFloat(renderer.View, "translationX", 0);
      objectAnimator.SetInterpolator(new DecelerateInterpolator());

      var animatorSet = new AnimatorSet();
      var animators = new List<Animator> { objectAnimator };

     animatorSet.SetDuration(300);
     animatorSet.PlayTogether(animators);
     animatorSet.AnimationEnd += (sender, args) =>
     {
          renderer.View.SetLayerType(LayerType.None, null);

          view.TranslationX = 0;
     };

    await animatorSet.StartAsync();
}
```

```
public static class AnimatorExtensions
{
   public static Task StartAsync(this Animator animator)
   {
       var taskAnimationListener = new TaskAnimationListener();

       animator.AddListener(taskAnimationListener);
       animator.Start();

       return taskAnimationListener.Task;
   }
}
```

This one translates the view on the x axis to point 0. For other properties, you'll need to swap the corresponding Android property names. Make sure to notify Forms of the final change in the `AnimationEnd` event.

iOS is a bit tricky. I'm sure there is a better way to do this.

```
public async Task TranslateViewAsync(View view)
{
    var finished = false;

    CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
     {
        var renderer = Platform.GetRenderer(view);
        renderer.NativeView.Transform = CGAffineTransform.MakeTranslation(375, 0);

        var uiViewPropertyAnimator = new UIViewPropertyAnimator(0.3, UIViewAnimationCurve.EaseOut, () =>
        {
             renderer.NativeView.Transform = CGAffineTransform.MakeTranslation(0, 0);
        });

        uiViewPropertyAnimator.AddCompletion(p =>
        {
             finished = true;
        });

        uiViewPropertyAnimator.StartAnimation();
    });

    while (!finished)
       await Task.Delay(10);

    await Task.CompletedTask;
 }
```
On iOS, you need to first translate the transform to its original position. Then, inside `UIViewPropertyAnimator`, you need to specify the final transform so iOS can carry out the animation. Forms should not be aware of native property changes during the animation begin and end phases.

**Comment by raindeer** [comment] 2019-10-19 08:02
@adrianknight89 interesting, will have a look at it. thanks!

**Comment by GiampaoloGabba** [comment] 2019-12-20 23:44
I was trying to do some animations on complex views and i had to stop it immediately :( 
So i found this issue and investigated the animation layer in forms: i had no idea that was implemented with an internal timer, completely skipping the native implementations  :(

So i tried to compare some small animations with the forms engine and the native ones....
Ouch,  the results are quite noticeable: even small animations are much more smooth using the native framework.

Maybe the community can help to create a more modern and performant engine for animations, lets see if the forms teams will ever approve this request :)

**Comment by adrianknight89** [comment] 2019-12-28 17:21
@GiampaoloGabba 

> Maybe the community can help to create a more modern and performant engine for animations, lets see if the forms teams will ever approve this request :)

Honestly, this should not be left to the community. While I understand Forms is an open source project, big corporations like Microsoft should be expected to hire people and develop a full-fledged cross-platform framework, especially considering Microsoft needs to attract more startups to the Azure ecosystem.

I'm extremely worried about the future of Xamarin Forms and recently decided to give up after many many years of contributing to this project. Right now, I'm migrating my code base to Xamarin.Android and Xamarin.iOS and noticing visible changes with respect to performance and layouting. With nearly 2000 open issues (some of them are very serious indeed) and a botched `CollectionView` implementation, I don't see how anyone can deliver Forms production code and go to bed at night.

I've implemented my own `UICollectionView` and `RecyclerView` instead of using `CollectionView` and also started using `SDWebImage` and `Glide` instead of `FFImageLoading`, and I'm never going back. Finally, no more terrible animations. :)

Cheers.

**Comment by davidortinau** [comment] 2020-01-11 01:47
@adrianknight89 I’ve sent you an email. Let’s talk. I’d really like to see your performance comparisons and get to the bottom of this. We should be able to achieve the same performance since all those same controls you note are either being used or may be substituted.

**Comment by GiampaoloGabba** [comment] 2020-01-26 22:55
I have to say that in ios the animations are quite smooth (not as native, but they are good), in android on the other hand... they are a bit jittering, not fluid at all.
Maybe its just me, 'cause it seems that no one else is interested in this issue :(

Lately i was experimenting some simple UI with other cross-platforms frameworks. The custom animations in Xamarin Forms doesnt felt "natural" and fluid. I dont know... now that i noted see i cant stop to see it in every app i developed :) But, again, maybe its just me...

**Comment by samhouts** [comment] 2020-02-13 01:21
Duplicate of #6033

**Closed by samhouts** 2020-02-13 01:21 UTC
Labels: a/animation 🎬, proposal-open, t/enhancement ➕

**Comment by raindeer** [comment] 2020-02-13 07:30
Is this really a duplicate of #6033? This is about hw accelerated animations while #6033 just mentions more advanced page transitions.
