### ISSUE TITLE
[Android] Label break text in ViewCell in XF 3.5

### ISSUE THREAD

**Issue by MarMarIV** [xamarin/Xamarin.Forms#5267] opened 2019-02-15 07:42 UTC
### Description
Having Label wrapped by frame in ViewCell, text is randomly breaking

### Steps to Reproduce

Label Wrapper:

`<Frame Margin="0" Padding="0" BackgroundColor="#34495E" CornerRadius="2" HasShadow="False" OutlineColor="Transparent"><StackLayout Margin="6,2" Spacing="0"><Label x:Name="contentLabel" FontSize="Default" HorizontalTextAlignment="Center" /></StackLayout></Frame>`

### Actual Behavior
text is randomly breaking

### Basic Information

- Version with issue: 3.5
- Last known good version: 3.4.0.1029999
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: SDK 8.1 

### Screenshots
![labelbreak](https://user-images.githubusercontent.com/10964247/52841828-8ce22200-30fd-11e9-8368-cd33922cf4ce.png)

**Comment by chrisfoulds** [comment] 2019-03-04 12:08
Why is this schedule for 3.6 ? , basically 3.5 is unusable currently due to this issue. I have had to roll back 10 clients projects from 3.5 to 3.4 due to it and most of them are now putting in all sorts of overly complex 'integration and upgrade procedures' on the projects now which is really going to hamper uptake onto the latest version. A rapid SR with the fix may help ease managements minds.
It's also not just frameview its any listview with a label on Android in my experience.

Below is my listview template on a VERY simple list page - the label size calculation does not work at all on 3.5.0.169047  on Android, fine on iOS

<Grid Padding="2" Margin="5,0,0,0">

                            <Grid.RowDefinitions>
                                <RowDefinition Height="*" />

                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="10*" />
                                <ColumnDefinition Width="90*" />
                            </Grid.ColumnDefinitions>
                            <ffimageloading:CachedImage DownsampleToViewSize="True" Grid.Column="0" Grid.Row="0" HeightRequest="45" Source="{Binding ImageName}" />
                            <Label Grid.Column="1" Grid.Row="0" Text="{Binding Name}"
                                       VerticalTextAlignment="Center" FontSize="18" HorizontalOptions="StartAndExpand"
                                       TextColor="Black" Margin="15,0,0,0"  FontFamily ="{OnPlatform Android='Roboto-Regular.ttf#Roboto-Regular', iOS='Roboto-Regular'}"/>
                        </Grid>

**Comment by yuv4ik** [comment] 2019-03-14 09:00
This seems to be a critical issue affecting multiple projects I am working on. As a nasty workaround that does not cover the issue 100% -> replace the `Grid` by a `StackLayout` on Android only.

**Comment by chrisfoulds** [comment] 2019-03-14 09:34
@yuv4ik we have downgraded all products to 3.4 and there they will remain until at least June now as the company has now put in a full impact process of xamarin forms upgrades after this basic but fundamental issue crept in and they failed to be fix through multiple releases.

**Comment by kingces95** [comment] 2019-08-20 23:24
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3522962/App1.zip)
@chrisfoulds @yuv4ik Could you please include a reproduction solution with actual and expected (or annotated actual) screenshots using the latest version of forms similar to the attached? There are many ways of specifying how text is wrapped and clipped and without a complete reproduction we'd be unable to target the issue you are encountering.

**Comment by jfversluis** [comment] 2022-02-15 16:27
Seems there has not been activity here for a long time. I hope that's because this is fixed in the meantime. If you happen to find this and think something is still wrong, please open a new issue. Thanks!

**Closed by jfversluis** 2022-02-15 16:27 UTC
Labels: t/bug :bug:, p/Android, s/needs-info ❓, i/regression, e/5 :clock5:, m/high impact :black_large_square:, a/listview, 3.5.0
