### ISSUE TITLE
Bindable Property Number type is not working[Bug] 

### ISSUE THREAD

**Issue by Strypper** [xamarin/Xamarin.Forms#12561] opened 2020-10-21 22:12 UTC
### Description
I have been trying to create a custom control with "ContentView", and expose all of my properties so the outsider could pass data in. But the problem is when I create bindable property with data type like "string" or "bool" they are all workout fine, but when use number type such as "double", "int" and "float", the property is not working even "DefaultValue" isn't show up to my UI 
### Steps to Reproduce

1. Create ContentView
2. Create number type Bindable Properties
3. x:Binding it to the ContentView XAML UI

### Expected Behavior
Default value show up and binding happen
### Actual Behavior
Default value not showing up and the binding is fail
### Basic Information
Just to clarify is this the right way to set it up ? 

```
      public static BindableProperty PercentageProperty = BindableProperty.Create("Percentage", typeof(double), typeof(DeviceViewCell), 0.0, BindingMode.TwoWay);

        public double Percentage
        {
            get { return (double)GetValue(PercentageProperty); }
            set { SetValue(PercentageProperty, value); }
        }
```

`<Label Text="{x:Binding Percentage}" HorizontalOptions="End" VerticalOptions="Center"/>`

- Version with issue: 4.8.0.1534
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: 9.0
- Affected Devices: Google Pixel 2

**Comment by StephaneDelcroix** [comment] 2020-10-26 15:56
2 quick remarks:

1/ there's no such thing as `{x:Binding}`, the syntax is `{Binding}`
2/ Text="{Binding Percentage}": the point of BP is to be the TARGET of Binding, not the SOURCE (even if that works)

so.... I don't really get what the question is... the Binding is unable to convert 2Way the text from the label back to a double ?

**Comment by Strypper** [comment] 2020-10-27 03:47
> 2 quick remarks:
> 
> 1/ there's no such thing as `{x:Binding}`, the syntax is `{Binding}`
> 2/ Text="{Binding Percentage}": the point of BP is to be the TARGET of Binding, not the SOURCE (even if that works)
> 
> so.... I don't really get what the question is... the Binding is unable to convert 2Way the text from the label back to a double ?

First of all no, x:binding exist and it's working without a problem on every my project
Second, the question the not about the converting the property, the property "default value" not even show up on the UI
Third, there is nothing wrong with my xaml set-up because as staged before. I move the entire UI of the "ContentView" put it directly into the "CollectionView" and the all 3 properties with 3 different types (string, bool, double) work just fine. So yes the issue sitting somewhere inside the way setting up the bindable property in code behind "ContentView"

**Comment by StephaneDelcroix** [comment] 2020-10-27 10:46
what I meant is that x:Binding isn't supposed to work. the syntax is wrong. BindingExtension shouldn't be resolved in the x: xmlns

for the rest of your question/problem, please attach the minimal project that can reproduce the error.

**Comment by Strypper** [comment] 2020-10-28 03:54
Have a look at this repo: [(https://github.com/E-vaTRON/SmartZone)]
Custom Control
Name: DeviceViewCell
Location: SmartZone/ControlZone/ControlZone/Components/DeviceViewCell/

Issue Bindable Property
Name: Percentage
Location: SmartZone/ControlZone/ControlZone/Components/DeviceViewCell/DeviceViewCell.xaml.cs

Testing Place
Name: "SubjectRequestList" CollationView
Location: SmartZone/ControlZone/ControlZone/Views/DeviceViews/DeviceList.xaml
Action: Remove the existing data template and replace it with the DeviceViewCell custom controll with 4 bindable values
IconImageSource = {x:Binding IconImageSource }
Model = {x:Binding Model}
PowerStatus = {x:Binding PowerStatus }
Percentage = {x:Binding OverallProcess }


**Place to see result**
Start the emulator and navigate to DeviceList.xaml by pressing the "Vật dụng" button
The progress bar on each every Device item should have a value of the percentage property
**Expectation **
All 4 of properties show up value 
**Reality **
Percentage property isn't show up value

**Comment by GalaxiaGuy** [comment] 2020-10-28 09:01
`DeviceViewCell` is trying to bind to a `Percentage` property. Since no source is specified this is looking for that property on the `BindingContext`, i.e. your viewmodel, an instance of `DeviceBase`.

If you intend to bind to the `PercentageProperty` you have created on `DeviceViewCell` you need to specify the source, with something like:

`Progress="{x:Binding Percentage, Mode=TwoWay, Source={RelativeSource AncestorType={x:Type deviceviewcell:DeviceViewCell}}}"`

You also need to make sure you bind something to that property when creating the viewcell:

`<deviceviewcell:DeviceViewCell Percentage="{Binding OverallProcess}" />`

Finally, the `PercentageProperty` property was not declared `readonly`.

**Comment by Strypper** [comment] 2020-10-28 17:13
I got the Percentage work now, but why ?
Why is Percentage need so specify the source while other props doesn't

**Comment by GalaxiaGuy** [comment] 2020-10-29 08:33
The other properties aren't really working either. `IconImageSourceProperty`, `PowerStatus` and `Model` are also the names of properties on your viewmodel, and the control is binding directly to them, instead of the the bindable properties you have created on the control.

To make it all work in a nicely encapsulated fashion, you would need to pass the properties through to the control:

```<deviceviewcell:DeviceViewCell Percentage="{Binding OverallProcess}" PowerStatus="{Binding PowerStatus}" IconImageSource="{Binding IconImageSource}" Model="{Binding Model}"  />```

and then update the source in each of the bindings in `DeviceViewCell`.

As an alternative to explicitly setting the source, a common approach is to set the control's `BindingContext` to itself in the constructor.

**Closed** 2020-11-01 15:50 UTC
Labels: a/binding ⛓, s/unverified
