### ISSUE TITLE
[Bug] [Xamarin-Forms-iOS] CollectionView scrolling issues when incrementally loading items of dynamic height

### ISSUE THREAD

**Issue by andos716** [xamarin/Xamarin.Forms#8604] opened 2019-11-21 10:22 UTC
### Description
When incrementally adding items of dynamic height to an ObservableCollection and scrolling up before the bottom of the list has been reached will result in a buggy UI.

### Steps to Reproduce

1. Download attached example project
2. Select RemainingItemsThreshold in the menu and scroll down and so that data is appended 2 times.
3. Before you reach the end of the collection view start to scroll up slowly. The UI will not update correctly.

### Expected Behavior
![Simulator Screen Shot - iPhone 11 - 2019-11-21 at 10 49 15](https://user-images.githubusercontent.com/10289931/69326759-a136ea80-0c4c-11ea-9f0f-fbee9253feea.png)

### Actual Behavior
![Simulator Screen Shot - iPhone 11 - 2019-11-21 at 10 49 25](https://user-images.githubusercontent.com/10289931/69326785-b14eca00-0c4c-11ea-932f-fda3aad6273e.png)

- Version with issue: Xamarin.Forms 4.3.0.991211
- IDE: Visual Studio for Mac 8.3.9
- Platform Target Frameworks: 
  - iOS:  13.2
- Affected Devices: Tested on iPhone 8 (device) and iPhone 11 (simulator)

### Reproduction Link

See attached project based on the CollectionView Example project:

[Xamarin_Forms___CollectionView_iOS_Issue 2.zip](https://github.com/xamarin/Xamarin.Forms/files/3874122/Xamarin_Forms___CollectionView_iOS_Issue.2.zip)

**Comment by PureWeen** [comment] 2019-12-06 19:28
@andos716 can you test this with the latest 4.4 pre and/or nightly? https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

I also tried testing your sample and I'm not able to reproduce. 

Can you attach a gif? 

I can see a little dance that comes in as things are coming in but I'm not seeing what you have in your screen shot above


![F44338F3-A91A-4E93-A89C-949BE80484FE](https://user-images.githubusercontent.com/5375137/70350385-e437b700-1823-11ea-9da7-cd71fe389229.GIF)

**Comment by andos716** [comment] 2019-12-09 13:04
@PureWeen attaching a gif of the behaviour.
![RPReplay_Final1574328017-2](https://user-images.githubusercontent.com/10289931/70437767-9f628900-1a8c-11ea-9adf-8711c5b8af1f.gif)

I'll test with 4.4 pre and get back to you.

**Comment by andos716** [comment] 2019-12-09 13:20
Same behaviour with 4.4.0.991220-pre3 @PureWeen

**Comment by samhouts** [comment] 2020-01-31 01:59
I can reproduce this with the attached version and with 4.5.0-pre2. Thanks

**Comment by boris-df** [comment] 2020-03-02 13:26
I have this problem even simpler when loading Items with variable height (even with a most simple xaml for the items)

Example attached
On App-Start you see additional space after some items
If you scroll, the spaces are eliminated and display is correct
Hit the Reload-Button to refresh the Item-Collection - Same Problem

![CollectionView_Item_Bug_beforeScrolling_2](https://user-images.githubusercontent.com/49982409/75680139-2f316100-5c91-11ea-9140-d0a2f959978b.png)
![CollectionView_Item_Bug_afterScrolling_2](https://user-images.githubusercontent.com/49982409/75680146-32c4e800-5c91-11ea-8a24-14aec7b6bfb4.png)

[ColViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4275608/ColViewBug.zip)

**Comment by demoh2019** [comment] 2021-02-07 16:00
Any Update?

**Comment by hartez** [comment] 2021-02-09 23:34
This is fixed in 5.0.0.1931.

**Closed by hartez** 2021-02-09 23:34 UTC
Labels: a/collectionview, e/4 :clock4:, p/iOS 🍎, t/bug :bug:, up-for-grabs

**Comment by demoh2019** [comment] 2021-02-10 01:28
@hartez my version 5.0.1.1965-nightly
