### ISSUE TITLE
XamlC throws Object reference not set to an instance of an object on DevOps

### ISSUE THREAD

**Issue by cheles** [xamarin/Xamarin.Forms#5598] opened 2019-03-18 10:19 UTC
### Description
XamlC crashes in Xamarin.Forms project under DevOps build with "Object reference not set to an instance of an object ".

### Expected Behavior
XF solution should build in DevOps as it does in local VS 

### Actual Behavior
Error thrown: `
```
 error : Object reference not set to an instance of an object. [C:\agent\_work\4\s\Controller\ControllerApp\ControllerApp.csproj]
2019-03-18T09:19:56.8468956Z      at Xamarin.Forms.Build.Tasks.TypeReferenceExtensions.<GetMethods>d__14.MoveNext()
2019-03-18T09:19:56.8468994Z      at Xamarin.Forms.Build.Tasks.TypeReferenceExtensions.<GetMethods>d__14.MoveNext()
2019-03-18T09:19:56.8469381Z      at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
2019-03-18T09:19:56.8469437Z      at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2019-03-18T09:19:56.8469484Z      at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2019-03-18T09:19:56.8469524Z      at Xamarin.Forms.Build.Tasks.TypeReferenceExtensions.GetImplicitOperatorTo(TypeReference fromType, TypeReference toType, ModuleDefinition module)
2019-03-18T09:19:56.8469580Z      at Xamarin.Forms.Build.Tasks.SetPropertiesVisitor.<Add>d__54.MoveNext()
2019-03-18T09:19:56.8469618Z      at Xamarin.Forms.Build.Tasks.ILProcessorExtensions.Append(ILProcessor processor, IEnumerable`1 instructions)
2019-03-18T09:19:56.8469655Z      at Xamarin.Forms.Build.Tasks.SetPropertiesVisitor.Visit(ElementNode node, INode parentNode)
2019-03-18T09:19:56.8469691Z      at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
2019-03-18T09:19:56.8469754Z      at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
2019-03-18T09:19:56.8469788Z      at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
2019-03-18T09:19:56.8469830Z      at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
2019-03-18T09:19:56.8469882Z      at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
2019-03-18T09:19:56.8469923Z      at Xamarin.Forms.Build.Tasks.XamlCTask.TryCoreCompile(MethodDefinition initComp, MethodDefinition initCompRuntime, ILRootNode rootnode, Exception& exception) (TaskId:535)`
```

### Basic Information
XF project builds successful in local VS and from MSBuild command line. 
DevOps has MSBuildVersion = 15.9.21.
- Platform Target Frameworks: Android

I can send the output log to assignee as it's a non-public log

**Comment by cheles** [comment] 2019-04-03 12:34
@samhouts @StephaneDelcroix  any updates on this from your side?

**Comment by samhouts** [comment] 2019-04-05 18:20
We're having trouble reproducing this issue. We're working on it, and hopefully we will have more information next week. Thanks!

**Comment by cheles** [comment] 2019-04-30 13:52
hey @samhouts any updates from your side? let me know if you need further logs

**Comment by samhouts** [comment] 2019-05-11 19:25
@cheles No update. Please do send me the logs. Thanks!

**Comment by cheles** [comment] 2019-05-14 15:32
@samhouts customer discontinued the case for now. how do you want to proceed with this?

**Comment by samhouts** [comment] 2019-05-14 20:56
@cheles Since we were unable to reproduce it, I guess we should go ahead and close this issue. However, do let me know if you have any ideas that would help us find the problem.  Thanks!

**Closed by samhouts** 2019-05-14 20:56 UTC
Labels: a/Xaml </>, a/buildchain, mobcat, s/unverified, t/bug :bug:
