### ISSUE TITLE
[Bug] iOS 14 App freezes when password is entered after email

### ISSUE THREAD

**Issue by mtsrdr** [xamarin/Xamarin.Forms#12246] opened 2020-09-25 01:53 UTC
### Description

When you are using Xamarin.Forms.Visual.Material package and create a style like this:
```
        <Style TargetType="Entry">
            <Setter Property="BackgroundColor" Value="#DCDCDC" />
            <Setter Property="PlaceholderColor" Value="#454344" />
            <Setter Property="TextColor" Value="Black" />
        </Style>
```

And create a layout like this:
```
        <StackLayout Padding="16" VerticalOptions="Center">
            <Entry
                x:Name="EmailEntry"
                Visual="Material"
                Keyboard="Email"
                Placeholder="Email" />
            <Entry
                x:Name="PasswordEntry"
                Visual="Material"
                IsPassword="True"
                Placeholder="Password" />
            <Button 
                x:Name="LoginButton"
                Visual="Material"
                Text="Login" />
            <ActivityIndicator 
                x:Name="BusyIndicator"
                Visual="Material"
                IsRunning="False"
                IsVisible="{Binding Source={x:Reference BusyIndicator}, Path=IsRunning}" />
        </StackLayout>
```

Then the following behavior occurs:
* If a username is entered and then a password is entered, focus is locked on the password control and nothing else on the screen (like the login button or the username control) can be tapped.
* If a password is entered and then a username is entered, focus is not locked and all controls react to taps normally. The password can even be re-entered without focus being locked.

More details in: https://forums.xamarin.com/discussion/185124/xcode12-ios-14-breaking-entry-controls

### Steps to Reproduce
1. Run the attached project on iOS 14
2. Enter an email
3. Then enter a password

### Expected Behavior
Focus is not locked and all controls react to taps normally

### Actual Behavior
Focus is locked on the password control and nothing else on the screen can be tapped

### Basic Information

- Version with issue: 4.8
- IDE: Visual Studio for Mac 8.8 (Preview)
- Platform Target Frameworks: 
  - iOS:  14.0 (XCode 12)
- Nuget Packages:
  - Xamarin.Forms.Visual.Material
- Affected Devices:
  - iOS Simulator:  14.0 (Haven't tested on physical device)

### Reproduction Link

[EntryTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5279873/EntryTest.zip)

**Comment by inimirpaz** [comment] 2020-09-25 07:43
Same here, this issue is pretty serious as it prevented many user to login in into the apps!
The issue is with Visual="Material" try to get rid of that as a workaround and it should work.

**Comment by Sivaraman761** [comment] 2020-09-25 08:13
I am too, Faced the same issue.

**Comment by Raystorm7** [comment] 2020-09-25 09:39
Same issue here.
When a fix?
In our business application we can't have a different style for some Entries.

**Comment by vecalion** [comment] 2020-09-25 10:41
We're experiencing similar issue in our project. The iOS app freezes when tries to navigate to a page with two entries (Visual = "Material"). Works OK if there is only one entry on the page. Also works OK without Visual = "Material".

@samhouts, I would say this is a critical issue, isn't it?

**Comment by nikkla19** [comment] 2020-09-25 10:49
Same Problem here. I'cant release my app unless it is fixed. Without `Visual = "Material"` the app is not so pretty...

**Comment by nikkla19** [comment] 2020-09-25 10:52
I have tested it on a real device (iPhone SE 2020) on iOS 14.0.0 and 14.0.1.

**Comment by freever** [comment] 2020-09-25 11:19
Plus one for me - also getting it with the password entries. It's super nasty

**Comment by jBijsterboschNL** [comment] 2020-09-25 11:49
We also experience the same issue. We are using the latest Xamarin.Forms version (v4.8.xxx). We have an Entry field and have set Visual="Material" and IsPassword="True". It only occurs on iOS 14 devices (on emulators and fysical devices). Anyone has a work-around for this? Or the Xamarin.Forms team has any idea how to work-around this for now, until a decent fix is released?

**Comment by LucGal** [comment] 2020-09-25 20:29
I'm facing the same issue both on simulator and real device. Urgent fix needed!

**Comment by oythorsen** [comment] 2020-09-28 08:08
Same issue here also. Tested on iPhone 8 and Simulator. Using Xamarin.Forms version (v4.6.0.1180).  Also tested on latest v4.8.xxx, but not using that due to error with Frame CornerRadius error (not showing rounded corners)

**Comment by marcojak** [comment] 2020-09-29 16:33
Same here, tested on simulator and my iPad with iOS 14. Some of my clients have the same issue too. 
No problem with devices with iOS <14

**Comment by hartez** [comment] 2020-09-30 01:29
Well, this is a weird one.

Here's my repro for this:

```
var layout = new StackLayout() { Padding = 16, VerticalOptions = LayoutOptions.Center};

var entry = new Entry() {  Visual = VisualMarker.Material, Keyboard = Keyboard.Email, Placeholder = "Email", TextColor = Color.Purple };
//var password = new Entry { Visual = VisualMarker.Material, IsPassword = true, Placeholder = "Password", TextColor = Color.Purple }; // App locks up

var color3 = Color.FromRgba(Color.Purple.R, Color.Purple.G, Color.Purple.B, Color.Purple.A - 0.01);
var password = new Entry {  Visual = VisualMarker.Material, IsPassword = true, Placeholder = "Password", TextColor = color3 }; // Works fine

layout.Children.Add(entry);
layout.Children.Add(password);

Content = layout;
```

If the two entries have the same TextColor, the app locks up if you follow the steps upthread. Only seems to happen with TextColor; PlaceholderColor and BackgroundColor don't cause it (though other properties may, I haven't test them). 

If the TextColors are set to different values, no issues - everything works fine. A copy of the color variable isn't enough - it needs to be an actually different value (note the very slight opacity change; if we change `Color.Purple.A - 0.01` to `Color.Purple.A`, the issue pops up again).

**Comment by ManfredRohleder** [comment] 2020-09-30 06:39
@hartez Your comment put me on the right track. I tested the following workaround and it works again.

**Before**
<Entry x:Name="txtPassword" 
                                Text="{Binding Password}" Margin="30,0,30,0"
                                TextColor="{DynamicResource **TextThemeColor**}"
                                Placeholder="Passwort"
                                IsPassword="True"
                                PlaceholderColor="{DynamicResource **TextThemeColor**}"
                                ClearButtonVisibility="WhileEditing"/>

**After**
<Entry x:Name="txtPassword" 
                                Text="{Binding Password}" Margin="30,0,30,0"
                                TextColor="{DynamicResource **TextThemeColorPassword**}"
                                Placeholder="Passwort"
                                IsPassword="True"
                                PlaceholderColor="{DynamicResource **TextThemeColorPassword**}"
                                ClearButtonVisibility="WhileEditing"/>

In my theme files (DarkTheme.xaml and LightTheme.xaml) I made the following changes.

**DarkTheme.xaml**
<Color x:Key="TextThemeColor">**#e7e7e7**</Color>
    <Color x:Key="TextThemeColorPassword">**#e7e7e6**</Color>

**LightTheme.xaml**
<Color x:Key="TextThemeColor">**#55575c**</Color>
    <Color x:Key="TextThemeColorPassword">**#55575b**</Color>

**Comment by LucGal** [comment] 2020-09-30 07:42
If you have more than one password text in the same Page (eg Change password feature) setting a different color don't work for me. If you don't set any color (remove TextColor = ".....") it works fine.

**Comment by jBijsterboschNL** [comment] 2020-09-30 10:43
@hartez, you saved my day! :) great find! Although this is obscure for sure, but rather a work-around then my users being unable to login! Thanks!!

**Comment by Baophp1805e** [comment] 2020-10-01 10:47
@hartez I have change color between entrys, but It's not work. The first that screen it work, but when I back to it, My iOS 14 App freezes . Example Screen 1: Login, Screen 2: Home, From App run the first -> Login -> Home, It's work! But Form Home -> Logout back to Login, iOS 14 App freezes :((( Someone help me ?

**Comment by mtsrdr** [comment] 2020-10-01 13:26
@Baophp1805e I haven't tested the text color workaround yet, but even following the steps I mentioned earlier (first entering the password and then email) the first time it works, but if I go back to the login page and focus on the password control again these steps no longer work and the app freezes.

**Comment by Baophp1805e** [comment] 2020-10-01 15:35
> @Baophp1805e I haven't tested the text color workaround yet, but even following the steps I mentioned earlier (first entering the password and then email) the first time it works, but if I go back to the login page and focus on the password control again these steps no longer work and the app freezes.
Delete Visual Material, It work.

**Comment by Baophp1805e** [comment] 2020-10-02 01:01
> Delete Visual Material, It works.

@hartez Did you try with prism ?  I have changed color between entrys, The first that screen it work, but when I back to it, My iOS 14 App freezes . Example Screen 1: Login, Screen 2: Home, From App run the first -> Login -> Home, It's work! But Form Home -> Logout back to Login, iOS 14 App freezes ...

**Comment by SteveGrixti-Remax** [comment] 2020-10-06 13:33
I am experiencing the same issue too. Since upgrading to IOS 14 in my login page, if the user first enters the email and then the password the application freezes. However, if the user enters the password first and then the email, the application does not freeze and proceeds..

I can also confirm that changing the color of the entries for some *miraculous* reason fixes this issue .. :joy: 

Any idea when this will be fixed? As due to this reason, users are unable to log in to the app..

**Comment by hartez** [comment] 2020-10-06 19:23
> Any idea when this will be fixed? As due to this reason, users are unable to log in to the app..

Can't say when it will be _fixed_, since it's an issue with either iOS or the iOS Material library. But Forms has a workaround for it in the works: #12316 

After that's merged and released, you shouldn't have to manually fix the colors to make it work.

**Comment by hartez** [comment] 2020-10-06 19:26
> > Delete Visual Material, It works.
> 
> @hartez Did you try with prism ? I have changed color between entrys, The first that screen it work, but when I back to it, My iOS 14 App freezes . Example Screen 1: Login, Screen 2: Home, From App run the first -> Login -> Home, It's work! But Form Home -> Logout back to Login, iOS 14 App freezes ...

What happens if you use different colors for _every_ Entry on those pages? Not just different colors for the Entries on a single page, but for every single Entry. I'm wondering if Prism is keeping two instances of pages using a single color around, and that's why you're seeing the application hang.

**Comment by NeilN1** [comment] 2020-10-07 14:31
While we wait for the workaround to be released, has anyone successfully implemented a version of the workaround in their code? I tried the below but it didn't work.

        public LoginPage()
        {
            Title = "Login";
            InitializeComponent();
            PasswordEntry.TextColor = AdjustTextColor(PasswordEntry);
        }
        static Color AdjustTextColor(Entry element)
        {

            var elementTextColor = element.TextColor;
            AlphaAdjustment += 0.0000001;

            var adjustedAlpha = elementTextColor.A - AlphaAdjustment;
            if (adjustedAlpha < 0)
            {
                adjustedAlpha = 0;
            }

            return new Color(elementTextColor.R, elementTextColor.G, elementTextColor.B, adjustedAlpha);
        }

**Comment by rhaly** [comment] 2020-10-08 07:52
It looks like it's solved in native Material Components iOS library.
https://github.com/material-components/material-components-ios/issues/10081

Wouldn't be better to release new binding for Material Components library than weird workaround with colors which does not work in every scenario?

**Closed** 2020-10-09 22:23 UTC
Labels: a/visual, e/3 :clock3:, iOS 14, in-progress, m/high impact :black_large_square:, p/iOS 🍎, t/bug :bug:

**Comment by hartez** [comment] 2020-10-14 21:13
> It looks like it's solved in native Material Components iOS library.
> [material-components/material-components-ios#10081](https://github.com/material-components/material-components-ios/issues/10081)
> 
> Wouldn't be better to release new binding for Material Components library than weird workaround with colors which does not work in every scenario?

@rhaly That's absolutely the ideal scenario, and we're looking into it. Believe me, the color workaround is not our first choice. But it's the option that we could get out the door quickly while we figure out whether we can do a material components update, verify that it fixes the problem, and figure out timings/releases.

**Comment by nikkla19** [comment] 2020-10-15 10:14
In my case the workaround doesn't fix the problem... I tested to change the _visual_ to _default_ but it did not help me..
I don't know whats going on here..

**Comment by mtsrdr** [comment] 2020-10-15 14:28
I successfully implemented the workaround with a renderer to ensure that each Material Entry has a unique text color.

Here's the code:

```
[assembly: ExportRenderer(typeof(Entry), typeof(FixIssueEntryRenderer), new[] { typeof(VisualMarker.MaterialVisual) })]
namespace YourNamespace
{
    public class FixIssueEntryRenderer : MaterialEntryRenderer
    {
        static double AlphaAdjustment = 0.0;

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null)
            {
                AdjustNativeControlTextColor();
            }
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            if (e.PropertyName == nameof(Entry.TextColor))
            {
                AdjustNativeControlTextColor();
            }
        }

        void AdjustNativeControlTextColor()
        {
            Control.TextColor = AdjustTextColor(Element).ToUIColor();
        }

        static Color AdjustTextColor(Entry entry)
        {
            var elementTextColor = entry.TextColor;
            AlphaAdjustment += 0.0000001;

            var adjustedAlpha = elementTextColor.A - AlphaAdjustment;
            if (adjustedAlpha < 0)
            {
                adjustedAlpha = 0;
            }

            return new Color(elementTextColor.R, elementTextColor.G, elementTextColor.B, adjustedAlpha);
        }
    }
}
```

**Comment by janschoelchAtOK** [comment] 2020-10-21 07:24
**Why is this even closed?** @samhouts @hartez 
- There might be a workaround but this is not a fix at all. Shouldn't this ticket be held open until a verified, solid and stable fix is out? I did not find any issue in [Issues](https://github.com/xamarin/Xamarin.Forms/issues?q=is%3Aissue+is%3Aopen+entry) stating that there is a need for a proper fix.
- [material-components/material-components-ios#10081](material-components/material-components-ios#10081) is a confirmed fix. Is there an issue for following-up the status of the binding update? I did not find any.
- The workaround might work, but only in most basic scenarios. For instance, setting a `CharacterSpacing` on the `Entry` makes the app freeze again. This prevents almost all of our (few thousand) iOS users from signing in.

**What is your advice for developers here?**
- Moving from XF4.6 to XF4.8 means breaking changes for us. In almost every other case the team states that backwards compatibility is most important, but in this case, conventions seem to be ignored.
- Will the workaround - as this issue is closed - be around forever now? [The release notes](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-4.8.0-sr4) state that that this is an "Issue Fixed".

**Comment by rhaly** [comment] 2020-10-21 07:32
@janschoelchAtOK in our team we decided to downgrade Xcode to 11.7 and Xamarin.iOS to 13.20.2.2.

**Comment by hartez** [comment] 2020-10-21 15:47
@janschoelchAtOK As I mentioned [upthread](https://github.com/xamarin/Xamarin.Forms/issues/12246#issuecomment-708663405), we're looking at updating the Material Components. If and when we can do that, we'll remove the color workaround. 

> The workaround might work, but only in most basic scenarios. For instance, setting a CharacterSpacing on the Entry makes the app freeze again. 

We were unaware of this. Could you open a new issue and post the properties you're setting on your Entry and Password controls? And tag me in the issue - I'll take a look. It may be that when the renderer applies the character spacing, it's having to reset some other properties on the native control and it's override the color workaround. Or we may just have to come up with a different workaround.

**Comment by hartez** [comment] 2020-10-21 15:48
> * Moving from XF4.6 to XF4.8 means breaking changes for us.

Which breaking changes are you referring to?

**Comment by janschoelchAtOK** [comment] 2020-10-21 15:58
> Which breaking changes are you referring to?

We faced crashes and flaky UI when moving to XF4.8 as `Brush`es now are heavily included in the platform renderers. We still investigate and we will try to create issues for everything we find (+ workarounds).

**Comment by janschoelchAtOK** [comment] 2020-10-21 16:00
> We were unaware of this. Could you open a new issue and post the properties you're setting on your Entry and Password controls? And tag me in the issue - I'll take a look. It may be that when the renderer applies the character spacing, it's having to reset some other properties on the native control and it's override the color workaround. Or we may just have to come up with a different workaround.

Thanks for following-up. Will do! Stay tuned as we might need some time to fully investigate what exactly is affected by this bug/workaround and what comes from the XF update.

**Comment by NeilN1** [comment] 2020-10-22 14:39
Did upgrading to 4.8.0.1560 fix this issue for anyone? Still seeing the same freezing behaviour.

**Comment by mina5500** [comment] 2020-11-03 09:57
any update ?

**Comment by ArtjomP** [comment] 2020-11-09 08:30
4.8.0.1560 freezing still

**Comment by mina5500** [comment] 2020-11-09 08:32
i tested on latest version 4.8.0.1560
and it is working fine

**Comment by mina5500** [comment] 2020-11-09 08:56
may be the order of the attributes matter

<H:HEntry FontSize="15" HeightRequest="60" Margin="-3" TextColor="White" Placeholder="User Name" PlaceholderColor="White" x:Name="usernameEntry" Keyboard="Email" BackgroundColor="Transparent" Unfocused="Entry_OnUnfocused" Focused="Entry_OnFocused" ReturnType="Next" TextChanged="usernameEntry_TextChanged" />

 <H:HEntry FontSize="15" HeightRequest="60" Margin="-3" TextColor="White" Placeholder="Password" IsPassword="true" PlaceholderColor="White" x:Name="passwordEntry" BackgroundColor="Transparent"  Unfocused="Entry_OnUnfocused" Focused="Entry_OnFocused" Completed="OnLoginButtonClicked" TextChanged="passwordEntry_TextChanged" />

**Comment by Raffro** [comment] 2022-02-02 17:13
Any news on this issue? 
I am also using visual studio 2022 community and xamarin forms and all labels I define don't display them texts until I define the label textcolor explicitly
