### ISSUE TITLE
[Bug] ListView doesn't work right with HasUnevenRows

### ISSUE THREAD

**Issue by td1311** [xamarin/Xamarin.Forms#6277] opened 2019-05-23 08:45 UTC
### Description
On iOS: ListViews with HasUnevenRows has layout broken 
### Steps to Reproduce

1. Add a ListView with complex ItemTemplate
2. Set HasUnevenRows to true
3. Populate the list
4. Layout is broken on iOS 10
5. Change text of label in ListView's cell
6. Label's alignment doesn't work well on iOS 12

### Expected Behavior
The ListView adapts to the complex items.
### Actual Behavior
It doesn't
### Basic Information

- Version with issue: Xamarin Forms 3.6.0.344457
- Last known good version: Xamarin Forms 3.4.0.1039999
- IDE: Visual Studio 2017(15.9.4)
- Platform Target Frameworks: 
  - iOS:  10.2,1, 12.2

### Screenshots

iPhone 6 with iOS 10.2.1
![IMG_5789](https://user-images.githubusercontent.com/41880710/58237825-404b5a00-7d70-11e9-90bd-f4038419d7c1.PNG)

iPod Touch gen 6 with iOS 12.2
before data changed
![IMG_0765](https://user-images.githubusercontent.com/41880710/58237912-68d35400-7d70-11e9-856b-f5db2f379aab.PNG)

after data changed
![Untitled](https://user-images.githubusercontent.com/41880710/58238076-c10a5600-7d70-11e9-8100-4a2c233be844.png)

### Reproduction Link

[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3211122/ListViewBug.zip)

**Comment by GalaxiaGuy** [comment] 2019-05-23 09:58
The layout being broken on iOS 10 appears to be a duplicate of #6201 and #5888.

**Comment by samhouts** [comment] 2019-05-28 20:15
Yep, this should be currently fixed in 4.0.0. Thanks!

**Comment by samhouts** [comment] 2019-05-28 20:15
Duplicate of #5888

**Closed by samhouts** 2019-05-28 20:15 UTC
Labels: a/listview, i/regression, p/iOS 🍎, s/unverified, t/bug :bug:
