### ISSUE TITLE
Picker.Focus() throws exception in 3.6

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5657] opened 2019-03-21 17:35 UTC
Hi @samhouts 

At Xamarin forms version 3.6 last stable also, Picker.Focus() calls throws exception , I have attached the exception details, Also Issue replicated sample, follow the replication procedure

Replication Procedure:
1. Run the attached sample and Enable the Exception settings (C++ Extensions, Common Language Runtime Exceptions)
2. Click the Button named as LoadLabel to load the label View
3. Click the Button named as LoadPicker to load the Xamarin forms Picker View
4. Click the Button named as FocusPicker to get the focus for Picker 
5. Now select any item from the displayed list
6. Click the Button named as UnFocusPicker to get the Unfocus for Picker 
7. Again Click the Button named as LoadLabel to load the label View
8. Click the Button named as LoadPicker to load the Xamarin forms Picker View
9. Click the Button named as FocusPicker to get the focus for Picker 
10. Now object disposed exception occurred at picker.Focus() calls 

Exception screenshot: 

![image](https://user-images.githubusercontent.com/42173947/54519095-bce64480-498b-11e9-877a-b4834165970a.png)

Sample: 
http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGridNet-1266236982

So Focus System.ObjectDisposedException: Cannot access a disposed object issue does not get fixed in **xamarin forms 3.6** last stable version and last **pre release version 4.6** for Xamarin.Forms.Picker View and Xamarin.Forms.DatePicker view, Attached sample is related to Picker.Focus() calls. 

Please look in to this issue and provide the fix for upcoming releases.

_Originally posted by @DeepikaBalaSubramaniyan in https://github.com/xamarin/Xamarin.Forms/issues/5202#issuecomment-473830078_

**Comment by jalbertSyncroTech** [comment] 2019-03-25 16:24
@samhouts @DeepikaBalaSubramaniyan Any known work-arounds for this until the next release?  We just updated to X.F 3.6.0-sr1 but this control is on the home page of one of our consumer apps.

**Comment by jalbertSyncroTech** [comment] 2019-03-26 15:19
Have some more information and a work-around:

To work-around the issue I made a custom Picker renderer which overrides Dispose() and OnFocusChangeRequested().  The latter checks whether the renderer has been disposed before calling the base class.

As to the cause, it looks like FocusChangeRequested event of the underlying VisualElement is not getting properly removed from disposed Pickers.  In my work-around renderer the OnFocusChangeRequested() is getting called multiple times, 3 in my case.  The first two times the Renderer has already been disposed, and for the last one it hasn't.

**Comment by PureWeen** [comment] 2019-03-26 16:53
duplicate of #5376
fixed by https://github.com/xamarin/Xamarin.Forms/pull/5670

**Closed by PureWeen** 2019-03-26 16:53 UTC
Labels: e/2 :clock2:, partner, t/bug :bug:

**Comment by DeepikaBalaSubramaniyan** [comment] 2019-03-28 05:38
Hi @PureWeen 

Still at last stable Xamarin Forms version 3.6.0.264807 and Last pre release version 4.0.0.250467-pre7 Picker.Focus() calls throws object disposed exception, But bug report was closed as fixed. Still in this simple sample able to reproduce the issue with  Xamarin Forms version 3.6.0.264807 http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGridNet-1266236982.
Kindly check this issue by installing last xamarin forms version too.

**Comment by benjaminsommerfeld** [comment] 2019-03-28 06:59
@PureWeen Same here, in latest 3.6 as well as latest 4.0 pre we also get this bug when calling Picker.Focus(). Desperately waiting for a final fix, cause this is crashing one of our customer apps in App Store.

**Comment by PureWeen** [comment] 2019-03-28 18:11
https://github.com/xamarin/Xamarin.Forms/pull/5670 hasn't been released yet

I tested your sample with the next SR coming out and it doesn't crash anymore

**Comment by benjaminsommerfeld** [comment] 2019-03-29 05:52
@PureWeen Thanks for your reply, can you give us an approximate release date for this fix? Will it be included in the upcoming 3.6.0 and 4.0-pre8 nuget-packages?

https://www.nuget.org/packages/Xamarin.Forms

Our customers are desperately waiting for the app-update with this fix, that's why I'm asking.

**Comment by jalbertSyncroTech** [comment] 2019-03-29 14:20
Just an FYI, there's half a dozen other controls also effected by this bug.

eg. Entry:
OnFocusChangeRequested() EditText.HideKeyboard() throws an ObjectDisposedException
https://github.com/xamarin/Xamarin.Forms/blob/35f830502e97cba966f32a11706f3f976143bade/Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs#L122

It looks like the following Android control renderers use OnFocusChangeRequested() and would all be effected by this issue:
* https://github.com/xamarin/Xamarin.Forms/blob/533e13019129b298f775308cf1ef79655bc97a7a/Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
* https://github.com/xamarin/Xamarin.Forms/blob/24b4b554ad1bf8aaa5d3f7c76269e4cd917ccf8e/Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
* https://github.com/xamarin/Xamarin.Forms/blob/24b4b554ad1bf8aaa5d3f7c76269e4cd917ccf8e/Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
* https://github.com/xamarin/Xamarin.Forms/blob/42345ed82e6079968c1f5b3cff378a7552900082/Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
* https://github.com/xamarin/Xamarin.Forms/blob/533e13019129b298f775308cf1ef79655bc97a7a/Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
* https://github.com/xamarin/Xamarin.Forms/blob/08c6bdf2dd18ac806362d12cbc9c4eb4b814c4ec/Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs

**Comment by PureWeen** [comment] 2019-03-29 16:13
Can't give an exact date but the release is in the cooker so as long as it passes through the QA cycles then it should be out soon

**Comment by benjaminsommerfeld** [comment] 2019-04-04 09:28
@PureWeen With today's build 3.6.0.293080 I still get this error when calling Picker.Focus(). Was this fix not part of the current 3.6.0.293080 build?

**Comment by PureWeen** [comment] 2019-04-04 17:43
@benjaminsommerfeld if you can create a new issue and a reproduction that would be really helpful.
I tested your scenario with the project attached to this issue and for me it's working on the first call to focus.
