### ISSUE TITLE
Image GIF support

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7014] opened 2019-07-30 02:28 UTC
Hi,

Please add GIF support to the Image control to display animated GIF..

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by jfversluis** [comment] 2019-07-30 07:47
Thanks for the issue! I will close this one and mark it as a duplicate since this was already on our radar and some discussion has already happened. I invite you to join the conversation there.

**Comment by jfversluis** [comment] 2019-07-30 07:47
Duplicate of #1704

**Closed by jfversluis** 2019-07-30 07:47 UTC
Labels: proposal-open, t/enhancement ➕
