### ISSUE TITLE
Keep on getting this "System.ObjectDisposedException: Cannot access a disposed object"... GC related...

### ISSUE THREAD

**Issue by MichelMatthey** [xamarin/Xamarin.Forms#1338] opened 2017-12-07 01:44 UTC
### Description
The problem is that the App crashes on the Android emulator with the following exception, it is related to a Mono8 issue I was lead to believe, how do I fix it  please ?

See stack trace below...

People are talking about this solution, can you please explain exactly what I need to do with the latest Garbage Collector from Mono, where do I set it up so it uses the old/new GC so the problems goes away until they fix it: 
MONO_GC_PARAMS=bridge-implementation=new

### Steps to Reproduce

1. Just run the app for long enough and eventually it crashes, nothing to do with our code we don't believe...

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.91635
- Last known good version: ?
- IDE: VS2017
- Platform Target Frameworks: Android, iOS
  - iOS:  xamarinios10
  - Android: Monodroid80
  - UWP:  Not used

- Android Support Library Version: Xamarin.Android.Support.Compat 25.4.0.2

- Nuget Packages: 
Packages for PCL project:
```
  <package id="Com.Airbnb.Xamarin.Forms.Lottie" version="1.0.0.7" targetFramework="portable45-net45+win8+wp8" />
  <package id="HtmlAgilityPack" version="1.6.5" targetFramework="portable45-net45+win8+wp8" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable45-net45+win8+wp8" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable45-net45+win8+wp8" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="portable45-net45+win8+wp8" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="portable45-net45+win8+wp8" />
  <package id="PCLStorage" version="1.0.2" targetFramework="portable45-net45+win8+wp8" />
  <package id="UXDivers.Artina.Shared" version="2.5.14-RC3" targetFramework="portable45-net45+win8+wp8" />
  <package id="UXDivers.Artina.Shared.Base" version="2.5.14-RC3" targetFramework="portable45-net45+win8+wp8" />
  <package id="UXDivers.Effects" version="0.6.1" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xam.Plugin.Connectivity" version="3.0.3" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xam.Plugins.Notifier" version="2.1.0" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xam.Plugins.Settings" version="3.1.1" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading" version="2.2.25" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.25" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.25" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.Forms" version="2.5.0.91635" targetFramework="portable45-net45+win8+wp8" />

Packages for Droid Project:
`  <package id="Com.Airbnb.Android.Lottie" version="1.0.0.7" targetFramework="monoandroid70" />
  <package id="Com.Airbnb.Xamarin.Forms.Lottie" version="1.0.0.7" targetFramework="monoandroid70" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="monoandroid80" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="monoandroid80" />
  <package id="Microsoft.CSharp" version="4.3.0" targetFramework="monoandroid80" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="monoandroid80" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="monoandroid80" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="UXDivers.Artina.Shared" version="2.5.14-RC3" targetFramework="monoandroid80" />
  <package id="UXDivers.Artina.Shared.Base" version="2.5.14-RC3" targetFramework="monoandroid80" />
  <package id="UXDivers.Effects" version="0.6.1" targetFramework="monoandroid80" />
  <package id="Xam.Plugin.Connectivity" version="3.0.3" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Notifier" version="2.1.0" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Settings" version="3.1.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Annotations" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Compat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Design" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Fragment" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Transition" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v4" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.4.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.FFImageLoading" version="2.2.25" targetFramework="monoandroid80" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.25" targetFramework="monoandroid80" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.25" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms" version="2.5.0.91635" targetFramework="monoandroid80" />
`
```
```

- Affected Devices: Android device + Android emulator

### Reproduction Link

<!-- Please upload or provide a link to a reproduction case -->

STACK TRACE:See comment further below... Other stack trace that is more relevant...

**Comment by jassmith** [comment] 2017-12-07 03:21
Can you please fill in as much of the missing info from the template as you can? Something seems to be impacting whatever this CustomFontLabelRenderer is that allows it to end up failing to unhook all events when disposed (thus triggering the crash you are reporting).

**Comment by MichelMatthey** [comment] 2017-12-07 23:26
From what I read it has more to do with the latest version of the Garbage collector and it is not caused by our code...

Note: We do make use of Sections and ViewCells and remove them or show them in order to hide them so it displays better than just setting the Labels inside the ViewCells to empty or hidden, as these leave the 2 separator lines in the section... We do make sure we re-add them on Disappearing as we thought that might be causing the issue... 

But it fails on other pages too, sometimes it takes a long time to happen, maybe 30-45 minutes, other times just seconds after it starts...

Looks like we are not the only ones with this problem, and it does look like a lower level issue, i.e. Garbage collector ?

**Comment by MichelMatthey** [comment] 2017-12-08 05:13
I attempted to create a environment.txt file and set it's build action to AndroidEnvironment in my Android project and tried these 2 envs (one then the other) and that didn't fix the issue:

MONO_GC_PARAMS=bridge-implementation=old

MONO_GC_PARAMS=bridge-implementation=new


Any other idea ?

**Comment by MichelMatthey** [comment] 2017-12-08 05:50
It came up with thios one, note the different class, we don't have any implementation of this class and yet it still crashes...:


12-08 05:47:37.925 I/MonoDroid(11290): UNHANDLED EXCEPTION:
12-08 05:47:37.988 I/MonoDroid(11290): System.ObjectDisposedException: Cannot access a disposed object.
12-08 05:47:37.988 I/MonoDroid(11290): Object name: 'Xamarin.Forms.Platform.Android.FormsTextView'.
12-08 05:47:37.988 I/MonoDroid(11290):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <7cfbebb561c54efc9010b018c0846c7e>:0 
12-08 05:47:37.988 I/MonoDroid(11290):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <7cfbebb561c54efc9010b018c0846c7e>:0 
12-08 05:47:37.988 I/MonoDroid(11290):   at Android.Views.View.Measure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00035] in <e975227ac8644a30bb0866117325de0d>:0 
12-08 05:47:37.988 I/MonoDroid(11290):   at Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].GetDesiredSize (System.Int32 widthConstraint, System.Int32 heightConstraint) [0x00032] in D:\agent\_work\2\s\Xamarin.Forms.Platform.Android\ViewRenderer.cs:92 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.Platform.Android.LabelRenderer.GetDesiredSize (System.Int32 widthConstraint, System.Int32 heightConstraint) [0x000f8] in D:\agent\_work\2\s\Xamarin.Forms.Platform.Android\Renderers\LabelRenderer.cs:69 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Internals.IPlatform.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint) [0x0008e] in D:\agent\_work\2\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:185 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.VisualElement.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x0002d] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:632 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:601 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x00053] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:477 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags) [0x00054] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:535 
12-08 05:47:37.989 I/MonoDroid(11290):   at Xamarin.Forms.Grid.CalculateAutoCells (System.Double width, System.Double height) [0x002a3] in D:\agent\_work\2\s\Xamarin.Forms.Core\GridCalc.cs:164 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.Grid.MeasureGrid (System.Double width, System.Double height, System.Boolean requestSize) [0x0000c] in D:\agent\_work\2\s\Xamarin.Forms.Core\GridCalc.cs:483 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0000e] in D:\agent\_work\2\s\Xamarin.Forms.Core\GridCalc.cs:17 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x0014b] in D:\agent\_work\2\s\Xamarin.Forms.Core\Layout.cs:245 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\agent\_work\2\s\Xamarin.Forms.Core\Layout.cs:205 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\agent\_work\2\s\Xamarin.Forms.Core\VisualElement.cs:637 
12-08 05:47:37.990 I/MonoDroid(11290):   at Xamarin.Forms.Layout+<>c.<OnChildMeasureInvalidated>b__40_0 () [0x00080] in D:\agent\_work\2\s\Xamarin.Forms.Core\Layout.cs:346 
12-08 05:47:37.990 I/MonoDroid(11290):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
12-08 05:47:37.991 I/MonoDroid(11290):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
12-08 05:47:37.991 I/MonoDroid(11290):   at (wrapper dynamic-method) System.Object:05633d17-59d8-47cf-bf95-46bb5b858b7d (intptr,intptr)

**Comment by jassmith** [comment] 2017-12-08 19:35
Somehow you're getting a layout happening to a view which has a disposed renderer. The only thing I can imagine is happening is you either have a really screwy thing going on in some custom renderer somewhere OR this is happening in a ListView and something in the accounting is going wrong.

Without a reproduction however we can't track this down very well. If you are using a ListView try changing the caching strategy to see if that helps.

**Comment by MichelMatthey** [comment] 2017-12-09 00:39
Yes, there are a couple of ListView and we use the MVVM and Observable collections and we have set the caching strategy but that doesn't solve it...

I mentioned that we do remove ViewCells from TableSections on Appearing and re-Add them on Disappearing one of the pages, but it still crashes even after we disable that...

The only Custom LabelRenderer is provided by UXDivers and it doesn;t do anything but output exceptions and call the base methods so it can't be the custom renderer...

Any other idea ? That used to work with Mono70 a while back, I was led to believe it has something to do with the Garbage Collector and howthe latest version causes this issue... ???

**Comment by jassmith** [comment] 2017-12-11 19:32
I am very reluctant to blame the GC at any time. In my experience the GC is rarely at fault. I am keeping this open but we desperately need a repro case here :(

**Comment by MichelMatthey** [comment] 2017-12-11 22:57
Hi Jason,

Thanks for that, I worked out the following and fixed them:
1) We use TableSections and ViewCells with Labels inside the ViewCells
2) Labels had Text="{ Binding Fieldname }" bindings
3) Sometimes the field value is empty so we want to hide the ViewCell but there is no "IsVisible" attribute for the ViewCell and leaving an empty value in the Label renders with an empty section between 2 lines so we found that removing the ViewCell foreces the rendering to not show the sparator lines...
4) We did keep track of all TableSections and the Removed ViewCells and recreate the Removed ViewCells on Disapearing

The problem is that the Text="{ Binding FieldName }" in the XAML actually makes it crash with the reported exception when the ViewCell has been removed from C#, so the solution is to remove all binding from XAML and set the value of each label when it is not hidden in C#, this way the system doesn't try to bind to a missing ViewCell...


So it looks like it is not GC related in the end, However, I believe this is still something that should be covered in the XF code that handles the rendering around XAML "{ Binding... }" so it properly handles missing information or container ?

**Ultimately the best would be to provide a "IsVisible" attribute at the ViewCell level ?**

_Also, as another side effect of removing ViewCells dynamically, the rendering on iOS works the first time the form is rendered but not well at all on subsequent rendering. This is not a problem on Android..._

**Comment by MichelMatthey** [comment] 2017-12-12 00:40
I will close this issue once Jason advises what is going to be done so a new IsVisible attribute is added and handled for all Elements including ViewCells or alternatively so the XF handles missing containers on the XAML { Binding FieldName } issue properly, or BOTH ?

**Comment by ssc4gemos** [comment] 2017-12-12 12:57
I also get this error occasionally since Xamarin.Forms 2.5 (see below), but I can not figure out how it could be reproduced.

Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.ViewCellRenderer+ViewCellContainer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <4c21040fb94e4d95aad65fc352e8e781>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <4c21040fb94e4d95aad65fc352e8e781>:0 
  at Android.Views.View.get_Width () [0x0000a] in <c8cab2efd85f442389020057942eca89>:0 
  at Xamarin.Forms.Platform.Android.CellRenderer+<>c__DisplayClass14_0.<WireUpForceUpdateSizeRequested>b__0 (System.Object sender, System.EventArgs e) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Cells\CellRenderer.cs:100 
  at Xamarin.Forms.Cell+<OnForceUpdateSizeRequested>d__39.MoveNext () [0x00086] in D:\agent\_work\1\s\Xamarin.Forms.Core\Cells\Cell.cs:189 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <c8cab2efd85f442389020057942eca89>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <c8cab2efd85f442389020057942eca89>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c8cab2efd85f442389020057942eca89>:0 
  at (wrapper dynamic-method) System.Object:1c41e54b-aecc-477f-8c0b-c5593ca05b06 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5872)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by jassmith** [comment] 2017-12-12 18:40
I'm not sure what you want to do with the visibility? Generally speaking we dont have a mechanism to exclude items from the itemsource from producing a View. The ideal mechanism is to wrap whatever List you are passing to your ItemsSource with an IList implementation that lets you exclude the items you want to hide and emit the INCC events.

**Comment by jassmith** [comment] 2017-12-12 18:45
I'm closing this to clear out the triage queue. It sounds like you're removing ViewCells from their parents in C# in some manner. This is very likely to cause a crash as the ListView expects to fully manage these. Please feel free to open a feature request for what you need to be able to support.

**Closed by jassmith** 2017-12-12 18:45 UTC
Labels: p/Android, s/needs-info, s/needs-repro, t/bug

**Comment by MichelMatthey** [comment] 2017-12-12 22:02
The reason we have to remove the ViewCells is because if we don't it doesn't render the page/form properly and shows the ViewCell empty between thin lines and looks too ugly! 

So maybe you need to fix that instead so we don't have to use backdoors kind of solutions, this is because XF is quite flimsy in the way it renders pages and is not consistent across platforms so we do what we can to get the results we need... If the support was a bit better we wouldn't have to resort to such drastic solutions either...

---> If a ViewCell is blank or empty, the renderer should not display it at all, and should not display the thin separator lines either ? This way would be the expected behaviour you would think ? Can you fix that please ? And also make sure it also works properly on iOS ?
