### ISSUE TITLE
Also getting this issue on iPhone 11 Pro devices but can’t narrow down a reproducible scenario yet. My screen has a CollectionView in a TabPage and it happens sporadically. Very frustrating.

### ISSUE THREAD

**Issue by adha-admin** [xamarin/Xamarin.Forms#11435] opened 2020-07-15 01:26 UTC
Also getting this issue on iPhone 11 Pro devices but can’t narrow down a reproducible scenario yet. My screen has a CollectionView in a TabPage and it happens sporadically. Very frustrating.

_Originally posted by @znelson32 in https://github.com/xamarin/Xamarin.Forms/issues/6908#issuecomment-621350437_

I also get this on my iPhone X.
I open the app one time and it shows the ListView in half a screen.
Next time I open the app, it will show in full screen.
I cannot work out why

**Comment by adha-admin** [comment] 2020-07-15 01:30
Code: This screen is in a TabView

    <StackLayout>
        <ListView x:Name="ItemsListView" ItemsSource="{Binding Items}" VerticalOptions="FillAndExpand"
                  HasUnevenRows="true" RefreshCommand="{Binding LoadItemsCommand}"
                  IsPullToRefreshEnabled="true" IsRefreshing="{Binding IsBusy, Mode=OneWay}"
                  CachingStrategy="RecycleElement" ItemSelected="OnItemSelected">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>

                        <StackLayout Padding="10">
                            <Grid Padding="0">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto"/>
                                </Grid.RowDefinitions>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="220"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <Label Text="{Binding divisionText}" LineBreakMode="NoWrap"
                                       Style="{StaticResource LabelStyle}" 
                                       FontSize="16"
                                       HorizontalTextAlignment="Start"
                                       VerticalTextAlignment="Start"
                                       Grid.Column="0"  />

                                <Label Text="{Binding leagueText}" LineBreakMode="NoWrap"
                                       Style="{StaticResource LabelStyle}" 
                                       FontSize="8"
                                       HorizontalTextAlignment="Start"
                                       VerticalTextAlignment="End"
                                       Grid.Column="0"  />

                                <Button Text="Ladder"
                                        Clicked="Ladder_OnButtonClicked"
                                        FontSize="16"
                                        CommandParameter="{Binding .}"
                                        Grid.Column="1" />

                            </Grid>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>

**Comment by jsuarezruiz** [comment] 2020-07-15 08:51
@adha-admin  I am creating an example where I will try to reproduce the issue, but I have some questions.
- Do you use CollectionView or ListView?. In the description you indicate CollectionView but the example is with ListView.
- Is the collection used within a ContentPage in a TabbedPage?

Thanks for the feedback!

**Comment by adha-admin** [comment] 2020-07-16 01:50
I am using a Listview in a StackLayout in a ContentPage which is in a NavigationPage which is in a tabbedPage

**Comment by znelson32** [comment] 2020-07-16 01:52
> I am using a Listview in a StackLayout in a ContentPage which is in a NavigationPage which is in a tabbedPage

Me too. Same scenario and problem.

**Comment by hartez** [comment] 2020-07-24 14:24
Closing as duplicate of #6908 so we can keep track of this issue in one place.

**Closed by hartez** 2020-07-24 14:24 UTC
Labels: a/collectionview, a/tabbedpage, s/unverified, t/bug :bug:
