### ISSUE TITLE
ItemSizingStrategy MeasureAllItems does not work for iOS

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#9152] opened 2020-01-10 14:54 UTC
### Description

"Accordion effect" when adding an item to the CollectionView with ItemSizingStrategy = MeasureAllItems.

### Expected Behavior

When adding an item to the CollectionView, the present items should maintain the same sizes.

### Actual Behavior
When adding an item, the present items are squeezed together momentarily until the item is added, see screen recording: [Screen Recording.mov.zip](https://github.com/xamarin/Xamarin.Forms/files/4046148/Screen.Recording.mov.zip)

I get the same effect when removing all layout and use simple labels only.

### Basic Information

Xamarin.Forms 4.4.0.991265
Tested on iOS simulator iOS 12.2 and iPhone 6s with iOS 12.4

**Comment by samhouts** [comment] 2020-01-10 17:42
Duplicate of #5455

**Closed by samhouts** 2020-01-10 17:42 UTC
Labels: s/unverified, t/bug :bug:

**Comment by nielscup** [comment] 2020-01-11 08:36
@samhouts Are you sure this is a duplicate? Looks like different scenarios to me.

**Comment by samhouts** [comment] 2020-01-22 19:39
@nielscup I strongly suspect it's the same root cause, but we'll double check when we implement the fix. Thanks!

**Comment by nielscup** [comment] 2020-01-24 07:23
@samhouts better leave it open then until you have checked it.
