### ISSUE TITLE
[Bug] MaterialPickerRenderer ignore colorAccent on Android

### ISSUE THREAD

**Issue by SamuelLioult** [xamarin/Xamarin.Forms#13809] opened 2021-02-19 14:30 UTC
### Description

The Android colorAccent is ignored in the Picker dialog. So it is not possible to change the cancel text colo with Visual=Material.

### Steps to Reproduce

1. Set Android colorAccent
2. User Picker with Visual=Material
3. Try it!

### Expected Behavior

The cancel text color should be your colorAccent

### Actual Behavior

The cancel text color is always a kind of pale green

### Basic Information

- Version with issue: Xamarin Forms 5.0.0.1905
- Platform Target Frameworks:
  - Android: API 29

**Comment by PureWeen** [comment] 2021-03-03 22:58
@SamuelLioult I think this is duplicate of the request here
https://github.com/xamarin/Xamarin.Forms/issues/11652

Which has some workarounds you can try

**Closed by PureWeen** 2021-03-03 22:58 UTC
Labels: a/visual, p/Android, s/unverified, t/bug :bug:
