### ISSUE TITLE
[Enhancement] Xamarin.Forms package with a net6 target?

### ISSUE THREAD

**Issue by jahmai-ca** [xamarin/Xamarin.Forms#14964] opened 2021-12-07 22:32 UTC
## Summary

I are trying to migrate our net5 projects to net6. This includes our current netstandard shared projects (shared with server code), and our multi-targeted shared projects (xamarinios10, monoandroid10, net5.0-windows). To compile this I have had to update a number of Xamarin.* projects due to compile issues with Java.Object, such as `Xamarin.AndroidX.Work.Runtime` to `2.7.0.1` which depends on  `Xamarin.AndroidX.Lifecycle.LiveData` >= 2.4.0.1. However the Xamarin.Forms package only targets monoandroid10 and requires that `Xamarin.AndroidX.Lifecycle.LiveData` be <= 2.4.0.0.

Can we get an updated Xamarin.Forms that can be used inside a net6-android targetted project, or at least updated to support `Xamarin.AndroidX.Lifecycle.LiveData` >= 2.4.0.1?

We are not yet ready to move to MAUI.

## API Changes

None

## Intended Use Case

As described in summary.

**Comment by jfversluis** [comment] 2021-12-08 09:28
Duplicate of #14960 and #14829

**Closed by jfversluis** 2021-12-08 09:28 UTC
Labels: t/enhancement ➕, proposal-open
