### ISSUE TITLE
[Spec]  Categorize regressions separately and prioritise fixing them

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#13665] opened 2021-02-05 02:44 UTC
# [The feature] 

5.0.0 has introduced a lot of breaking regressions, but there doesn't seem to be much urgency to fix them.

Suggestion: Add a separate flair for regressions. Focus on fixing them first (so people can go back to working normally). Push out service releases with regression fixes. Regression fixes should take absolute priority over anything else.

The current process where regressions don't seem to be prioritised is untenable, and wastes time for developers for no reason. It also makes adopting new XF versions a risky play.

# Difficulty : [low/medium/high]

Non-existent

**Comment by jsuarezruiz** [comment] 2021-02-05 08:26
Thanks for the feedback. I agree on the priority in regressions.
In case it helps to understand everything a little better. There are flags to mark regressions. The specific **regression** flag and then specific flags to indicate if a regression is from a specific version.
On the other hand, we have the **blocker** flag to indicate that it is something critical that can block the release of the next version and must be fixed.

**Comment by Tommigun1980** [comment] 2021-02-05 08:28
> Thanks for the feedback. I agree on the priority in regressions.
> In case it helps to understand everything a little better. There are flags to mark regressions. The specific **regression** flag and then specific flags to indicate if a regression is from a specific version.
> On the other hand, we have the **blocker** flag to indicate that it is something critical that can block the release of the next version and must be fixed.

Thank you for the info, I appreciate it, along with all the hard work you guys do!

**Comment by MitchBomcanhao** [comment] 2021-02-05 11:03
I believe I've seen people raising regression-style issues only for them to be ignored because (for example) "this will be rewritten in the future" - we were told the current releases would be stabilised and perfected, not abandoned because something newer and shinier could be released in the future. I can't recall which issue I read this in, but I think it was related to checkboxes or radiobuttons. makes it risky to take on any new features right now, which may regress and then those issues may simply not be looked at because it is seen as not cost effective by the xamarin team.

**Comment by jfversluis** [comment] 2021-12-23 13:58
Thanks for raising this. We're doing everything we can right now to make things better and have been discussing this in the span of multiple issues and other places. Closing this one for now.

**Closed by jfversluis** 2021-12-23 13:58 UTC
Labels: t/enhancement ➕, proposal-open
