### ISSUE TITLE
[Bug] Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer' 

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/Xamarin.Forms#9075] opened 2020-01-03 12:10 UTC
I thought this one has been fixed in the latest version, but I can still see the following bug on my client's devices via AppCenter

Currently, this is in Android (iOS is not published yet)
XF: 4.4.0.991265

I have a Collection view that has a footer and header with dynamic ItemTemplate (DataTemplateSelector - three types of items)

I am unable to reproduce it on my device, but I can see a lot of devices have this issue in AppCenter

> JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
> JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
> ImageView.get_Drawable ()
> ImageElementManager.TryUpdateBitmap (Xamarin.Forms.Platform.Android.IImageRendererController rendererController, Android.Widget.ImageView Control, Xamarin.Forms.IImageElement newImage, Xamarin.Forms.IImageElement previous)
> ImageElementManager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e)
> AsyncMethodBuilderCore+<>c.b__7_0 (System.Object state)
> SyncContext+<>c__DisplayClass2_0.b__0 ()
> Thread+RunnableImplementor.Run ()
> IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
> (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr)

**Comment by samhouts** [comment] 2020-01-03 17:07
@moustafashaban  Can you please attach a small project that demonstrates this issue? Which devices are showing this issue? Thanks!

**Comment by moustafashaban** [comment] 2020-01-03 17:10
@samhouts  thanks for replying, 
as I mentioned in the description, I am unable to reproduce it on my device, it is coming from my clients' devices, the stack trace above coming from the AppCenter

**Comment by samhouts** [comment] 2020-01-03 17:26
@moustafashaban Sometimes AppCenter reports which devices were affected. That information is helpful. The stack trace is also helpful, but it does not narrow down the root cause. If you can create a small project that mimics the code you have in production (i.e., show what sort of ImageSource you're using, what layouts you've used, etc.), that might help us reproduce the issue. Thanks!

**Comment by PureWeen** [comment] 2020-01-03 17:54
This should get fixed by 
https://github.com/xamarin/Xamarin.Forms/pull/9034

**Comment by ddillmancode** [comment] 2020-01-06 18:12
Hello @PureWeen and @samhouts . I am experiencing the same issue as @moustafashaban . For me this occur specifically when loading my main AppShell after a login. The page consists of a collectionview with a static list of elements for its ItemsSource. These elements have an ImageSource bound to them which is used in the custom ItemTemplate. The ImageSource objects are contained within a Resources.drawable folder with the build action set to AndroidResource. 

System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.'

The page does not throw the above mentioned exception all the time, but rather sporadically when logging in. There is no stacktrace provided in VisualStudios 2019, however I did retrieve this stacktrace from AppCenter. This error is occurring on Android OS 8.0, 8.1, 9.0 and 10.0 as of this morning.

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
ImageView.get_Drawable ()
ImageElementManager.TryUpdateBitmap (Xamarin.Forms.Platform.Android.IImageRendererController rendererController, Android.Widget.ImageView Control, Xamarin.Forms.IImageElement newImage, Xamarin.Forms.IImageElement previous) D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\ImageElementManager.cs:139
ImageElementManager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e) D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\ImageElementManager.cs:54
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.53(intptr,intptr)

Please note for any users that might be looking for a workaround - I was able to continue working as normal by downgrading my Xamarin.Forms from v4.4.0.991265 to v4.3.0.991211.

**Comment by PureWeen** [comment] 2020-01-06 19:19
The fixed has been merged into 4.4 which should be released soon

**Comment by ddillmancode** [comment] 2020-01-06 19:48
Great news PureWeen. Thanks for the fast reply.

**Comment by samhouts** [comment] 2020-01-07 22:04
closed by #9034

**Closed by samhouts** 2020-01-07 22:04 UTC
Labels: a/collectionview, has-stacktrace, i/high, in-progress, p/Android, s/needs-info ❓, s/needs-repro ❔, t/bug :bug:
