### ISSUE TITLE
[Bug] [Grid] Row's height gets messed up in X.F 4.8 sr5

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/Xamarin.Forms#13177] opened 2020-12-17 08:21 UTC
### Description

(see attached project)
With absolute no change to the code, since Xamarin.Forms 4.8.0.1687 (4.8 sr5) the height of the rows in a grid is different from previous versions (shorter) and gets completely messed up if you play with the visibility of the last row items of a grid. Both on iOS and Android.

### Steps to Reproduce

1. Have a grid with more than 1 row item
2. Make the last items visibility change
3. Switch between 4.8 sr5 and sr4 back and forth

### Expected Behavior

Same as before 4.8 sr5, that is, rows should keep their height and most importantly they must not shrink when changing the visibility of row items.

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: 4.8.0.1560 and lower
- Platform Target Frameworks: 
  - iOS:  (tested on 14.2)
  - Android: (tested on Android 10 and lower)

### Screenshots
4.8 sr4: correct behavior (default row height is ok; when showing/hiding items rows keep their height still)
![4_8_0_1560](https://user-images.githubusercontent.com/56956625/102461337-877ef700-4048-11eb-985d-574e016fa927.gif)

4.8 sr5: wrong behavior (default row height is shorter when compared with previous version; showing/hiding items get the row item all messed up)
![4_8_0_1687](https://user-images.githubusercontent.com/56956625/102461547-d2007380-4048-11eb-864c-9ef2a6e36864.gif)

Left 4.8 sr4, right 4.8 sr5
![comparison](https://user-images.githubusercontent.com/56956625/102461788-33284700-4049-11eb-9029-741e29465537.png)

### Reproduction Link
[GridRowBug.zip](https://github.com/xamarin/Xamarin.Forms/files/5707890/GridRowBug.zip)

**Comment by inimirpaz** [comment] 2020-12-18 08:23
Latest X.F release (4.8.0.1821 sr6) seems to have fixed this issue (?)...

**Comment by jsuarezruiz** [comment] 2020-12-18 09:55
This issue seems to be fixed by #12475
cc @hartez

**Comment by CometSL9** [comment] 2020-12-18 10:53
The issue persists on XF 4.8.0.1821 under WPF.

![image](https://user-images.githubusercontent.com/46746288/102606504-1f531280-4127-11eb-805d-21141bb9dd30.png)

The word "missing" comes from the label placed in (*) width sized grid column 4. The grid row height is calculated incorrect.

Very annoying!

**Comment by PureWeen** [comment] 2021-01-22 17:54
@CometSL9 can you test with the latest release of 5.0 ?
There were a number of changes made there

**Comment by CometSL9** [comment] 2021-01-27 08:08
Sure, it still persists as of v5.0.0.1931.

The bug is really annoying because it hinders this part of my project from getting the "OK" of the colleagues.

Screenshot:
![image](https://user-images.githubusercontent.com/46746288/105961558-f35c7280-607e-11eb-91f8-7bfd715495c3.png)

Code to reproduce the error:
` <ListView
            HasUnevenRows="True"
            HeightRequest="200"
            HorizontalOptions="Center"
            WidthRequest="300">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Grid>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="100" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Label Grid.Column="0" Text="Fixed width" />
                            <Label
                                Grid.Column="1"
                                LineBreakMode="WordWrap"
                                Text="{Binding .}" />
                        </Grid>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
            <ListView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Test</x:String>
                    <x:String>Text is too long to display on a single line</x:String>
                    <x:String>Another Test</x:String>
                </x:Array>
            </ListView.ItemsSource>
        </ListView>`

**Comment by rmarinho** [comment] 2021-01-29 11:20
@CometSL9  can you please  upload a small reproduction? Or open a new issue ? thanks!

**Comment by rmarinho** [comment] 2021-01-29 11:36
Closing at this issue is fixed on 4.8-sr6 , @CometSL9  please open a new issue with your reproduction

**Closed by rmarinho** 2021-01-29 11:36 UTC
Labels: a/grid, a/layout, i/high, s/unverified, t/bug :bug:
