### ISSUE TITLE
[Bug] [5.0] [Android] Interacting with a SwipeView on a TabbedPage with IsSwipePagingEnabled="false" re-enables page swiping

### ISSUE THREAD

**Issue by sjordanGSS** [xamarin/Xamarin.Forms#13337] opened 2021-01-08 13:39 UTC
### Description

Page Swiping on the TabbedPage on Android can be disabled by setting IsSwipePagingEnabled="false", however this setting appears to be ignored after interacting with a SwipeView on one of the TabbedPage's child pages.

### Steps to Reproduce

I've added a repro link further down which might be easier to understand than a text description, but here goes:
1. Create a new XF app with a TabbedPage 
2. add 'xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
            android:TabbedPage.IsSwipePagingEnabled="False"' to the TabbedPage to disable page swiping on Android
3. add 2 child pages, one with a SwipeView
4. Run the app, interact with the SwipeView then swipe the page

### Expected Behavior
TabbedPage page swiping should remain disabled

### Actual Behavior
TabbedPage page swiping is re-enabled

### Basic Information

- Version with issue: 5.0
- Last known good version: 4.8sr5 with "SwipeView_Experimental" flag set
- Platform Target Frameworks: 
  - Android: 10.0
- NuGet Packages:
  - Xamarin.Forms
  - Xamarin.Essentials.Interfaces
  - Prism.DryIoc.Forms
- Affected Devices: Tested on Android 7 device

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

https://github.com/sjordanGSS/SwipeViewBreaksNonSwipeTabbedPage

### Workaround

None Found, aside from using something that isn't a SwipeView.

**Comment by rachelkang** [comment] 2021-01-08 19:51
Hi, @sjordanGSS - thanks for submitting this issue! hmm very interesting behavior. It seems that the SwipeView is somehow overwriting the `android:TabbedPage.IsSwipePagingEnabled` property, not to mention that SwipeView doesn't appear to work properly within a swipable TabbedPage.

@jsuarezruiz do you know what might be going on here?

**Comment by kkppstudios** [comment] 2021-01-08 23:50
Thank you for logging this. I experienced this issue too and it is preventing me from being able to update to XF 5. It's subtle because the IsSwipePagingEnabled = false works at first but as soon as I interact with the SwipeView on one of my TabbedPages the IsSwipePagingEnabled behaves like it's set to true.

**Comment by sjordanGSS** [comment] 2021-01-09 12:34
> 
> 
> Hi, @sjordanGSS - thanks for submitting this issue! hmm very interesting behavior. It seems that the SwipeView is somehow overwriting the `android:TabbedPage.IsSwipePagingEnabled` property, not to mention that SwipeView doesn't appear to work properly within a swipable TabbedPage.
> 
> @jsuarezruiz do you know what might be going on here?

Hi Rachel, I hadn't actually noticed that the SwipeView itself wasn't swiping in the repro: my production app places the SwipeView inside of a CollectionView and it swipes properly there, albeit that the TabbedPage SwipePaging bug still occurs. I'm not sure if this might be because of the large amount of padding I placed on the repro SwipeView to make it easier to press: I'll have a play around with the repro at some point and see what happens.

**Comment by jsuarezruiz** [comment] 2021-01-14 15:46
@sjordanGSS Thanks for the attached sample!. The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13404

**Comment by sjordanGSS** [comment] 2021-02-08 15:13
@jsuarezruiz Thanks for the fix, any idea when it will be available in a Xamarin.Forms release?

**Comment by nicoriff** [comment] 2021-03-11 12:55
Hi. Same problem here with latest release of Xamarin Forms. Any news on when this will be shipped?.

**Comment by Daniel0b1b** [comment] 2021-03-17 09:53
Thanks! When will it be available in a new release?

**Comment by tranb3r** [comment] 2021-06-09 15:41
Can we expect a fix to be released soon ?

**Comment by skyapps-co** [comment] 2021-06-14 13:28
Looking for a fix as well. The problem is still there in XF 5.0.0.2012. Thanks!!

**Comment by jasonboyda** [comment] 2021-07-30 19:31
Any updates on when this will be released?

**Comment by geoffwc** [comment] 2021-08-13 15:33
Just come across this issue myself and managed to come up with a smile workaround after a lot of trial and error.
Basically the problem stems from the SwipeView disabling the TabbedPage gesture whenever it is swiping, but then enabling it regardless of the IsSwipePagingEnabled attached property.
I initially tried a custom renderer for the TabbedPage and although it's possible to halt the swipe, the scroll moves slightly which is no good. 
This workaround is a custom SwipeView renderer which finds the FormsViewPager on the page, then disables it for any SwipeView touch event.

`public class CustomSwipeViewRenderer : SwipeViewRenderer
                {
                                private ViewPager viewPager;
                                private PropertyInfo enableGestureProperty;
 
                                public CustomSwipeViewRenderer(Context context) : base(context)
                                {
                                }
 
                                public override bool OnTouchEvent(MotionEvent e)
                                {
                                                var result = base.OnTouchEvent(e);
 
                                                if (viewPager == null)
                                                {
                                                                viewPager = Control.Parent.GetParentOfType<ViewPager>();
                                                                enableGestureProperty = viewPager.GetType().GetProperty("EnableGesture");
                                                }
 
                                                enableGestureProperty.SetValue(viewPager, false);
 
                                                return result;
                                }
                }`

Because I only want the swipe disabled it's always set to false. If you want something else, you will need to use IsSwipePagingEnabled and probably only apply on touch up action.
You can grab a copy of the internal GetParentOfType method from the repo.

**Closed** 2021-10-18 18:36 UTC
Labels: t/bug :bug:, p/Android, e/3 :clock3:, in-progress, a/swipeview, a/tabbedpage, 5.0.0
