### ISSUE TITLE
semi-transparent grey box overlay stopped working after update to Xamarin.Forms 4.6.0.379-pre1

### ISSUE THREAD

**Issue by nerdtronn** [xamarin/Xamarin.Forms#10535] opened 2020-05-01 13:54 UTC
### Description

I'm using a semi-transparent grey BoxView overlay (and an ActivityIndicator on top of that) on top of some other views.  This is done within a Grid.  The other views are laid out in the grid using rows.  The grey overlay box (and ActivityIndicator) is declared in the XAML inside the grid but after the other views, is set to Row 0 with a RowSpan to cover the other rows.  The idea is for this grey box and activity indicator to display on top of the other views, covering them.

This overlay is turned on when the app is "busy" which gives the appearance of disabled controls.  I'm turning it on/off by binding IsVisible to a variable in my view model which gets updated when the app is "busy".

As late as v4.5.0.725 this worked correctly.  When the app was busy, the semi-transparent grey overlay box (and activity indicator) would appear on top of the other controls.  I tried updating to the latest, v4.6.0.726 and the box no longer appears.  I discovered that the problem appears to have been introduced in v4.6.0.379-pre1.

Furthermore, the problem only occurs when running on UWP.  I verified Android works correctly and does not exhibit the problem.  I have not yet tried on iOS (waiting to get a mac).

### Steps to Reproduce

1.  Setup a view with a Grid with multiple rows, views in those rows, then after the views, add a BoxView with < 1 Opacity and specify Row 0 and RowSpan as the # rows being used, bind the IsVisbile of the BoxView to a property in the view model
2. Toggle the property on/off and see that the semi-transparent overlay appears on top of the other views
3. Using Xamarin.Forms v4.5.0.725 this works, using v4.6.0.379-pre1 (or later, even up to the latest v4.6.0.726) this does not work and the box does not appear
4. The problem occurs on UWP, but it works correctly on Android even with the latest version of Xamarin.Forms

### Expected Behavior

The box should appear on top of the other views when IsVisible is true.

### Actual Behavior

The box no longer appears when IsVisible is true.

### Basic Information

- Version with issue: v4.6.0.379-pre1 or later (including latest v4.6.0.726)
- Last known good version: v4.5.0.725
- IDE: Visual Studio Enterprise 2019 v16.5.4
- Platform Target Frameworks: 
  - iOS:  13.16.0.13 (have not tested iOS)
  - Android: 10.2.0.100 (works correctly, no regression)
  - UWP:  UWP Nuget 6.2.10 (exhibits the problem, but where do I get the framework version?)
- Android Support Library Version: 
- Nuget Packages:
Microsoft.NETCore.UniversalWindowsPlatform 6.2.10
NETStandard.Library 2.0.3
Xamarin.Essentials 1.5.3.1
Xamarin.Forms 4.6.0.379-pre1 (or later, including v4.6.0.726)
- Affected Devices:

### Workaround

I was using the Color attribute of the BoxView to set it to "LightGray".  MitchBomcanhao suggested using BackgroundColor instead due to changes in the renderer.  Switching over to BackgroundColor fixed the problem and it now works great on UWP in the latest version.

UPDATE: While that workaround of using BackgroundColor fixed the problem when running from source in Visual Studio, when building an app package and installing it on my local machine, it no longer worked.  I finally ended up reverting back to v4.5.0.725 which then worked.  So it seems something is different about the deployed app package vs. running it from source?

**Comment by MitchBomcanhao** [comment] 2020-05-01 16:12
Are you setting the Color or the BackgroundColor of the BoxView? I've found that either would work in older XF versions, but 4.6 uses a new renderer for BoxView and only BackgroundColor will work with that new renderer. 
You can try that or try switching back to the old renderer by adding this [assembly: ExportRenderer(typeof(BoxView), typeof(BoxViewRenderer))]

**Comment by nerdtronn** [comment] 2020-05-01 17:08
> Are you setting the Color or the BackgroundColor of the BoxView? I've found that either would work in older XF versions, but 4.6 uses a new renderer for BoxView and only BackgroundColor will work with that new renderer.
> You can try that or try switching back to the old renderer by adding this [assembly: ExportRenderer(typeof(BoxView), typeof(BoxViewRenderer))]

Thanks!  That worked.  I was using Color, switching to BackgroundColor fixes it even with the latest version.  Much appreciated!

**Comment by nerdtronn** [comment] 2020-05-01 20:43
While switching to using BackgroundColor seemed to fix the problem when running from Visual Studio in debug, when I created a UWP app package (project >> Publish) and installed that on my local machine and ran it, the box no longer showed up.

I went back and used rebuild all from Visual Studio and it worked fine from there, even when using Release configuration.  But when I install from a created UWP app package it doesn't work and the box doesn't show up.

**Comment by nerdtronn** [comment] 2020-05-01 21:17
I rolled back to v4.5.0.725, then built a new UWP app package and installed that on my machine and it worked correctly.  So the change to BackgroundColor appears to work when running from source, but not with the installed UWP app package.

**Comment by charlesroddie** [comment] 2020-05-04 16:12
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/10528

**Closed** 2020-05-06 18:18 UTC
Labels: e/2 :clock2:, i/regression, in-progress, p/UWP, t/bug :bug:
