### ISSUE TITLE
[Shell] CSS is not working when referencing CSS-file in App.xaml

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#4872] opened 2018-12-29 23:40 UTC
### Description
When I using a CSS to style buttons when inside a Shell is dosen't work if I references the CSS-fole in the App.xaml file. If I references with Grid.Resources it will work for the buttons inside that Grid.

### Steps to Reproduce

1. Create a page inside a Shell
2. Create a CSS file
3. Reference the CSS file in App.xaml

### Expected Behavior
CSS styling should be applied according to specified values in the CSS-file.

### Actual Behavior
Styles is not applies.

### Basic Information

- Version with issue: 4.0.0.8055-pre1
- Last known good version:
- IDE: Visual Studio for Mac 7.7.2 (build 21)
- Platform Target Frameworks: 
  - iOS:  12.2.1.12
- Affected Devices: iOS simulator iPhone XS 12.1

### Reproduction Link

[Source.zip](https://github.com/xamarin/Xamarin.Forms/files/2716790/Source.zip)

Parent: #2415

**Comment by PureWeen** [comment] 2019-04-29 15:59
related
https://github.com/xamarin/Xamarin.Forms/issues/5956

**Comment by samhouts** [comment] 2019-05-01 00:15
Hmm. With pre1, it did eventually apply the green style if you switched between the pages. When I updated to pre9, it refused to show the green at all. Progress? I think not. Still an issue.

**Comment by samhouts** [comment] 2019-05-03 00:42
Duplicate of #4683

**Closed by samhouts** 2019-05-03 00:42 UTC
Labels: a/CSS, a/shell :shell:, blocker, e/3 :clock3:, t/bug :bug:
