### ISSUE TITLE
[Bug] iOS: Shell + CollectionView: CollectionView item stuck on screen while browsing using Shell

### ISSUE THREAD

**Issue by matteopiccioni** [xamarin/Xamarin.Forms#6070] opened 2019-05-02 12:03 UTC
### Description
In my project I have a collectionview with a two columns of items.
All is working as expected, but if I browse to another page using side menu, when I come back to the first page, then the first row of items is printed/stuck on the screen.

### Steps to Reproduce
I found the same issue on Gastropds project:
https://github.com/davidortinau/Gastropods.git
1. 
Open the app
2. 
On side menu go to 'Tab Sandwitch'
3. 
From side menu go back to 'Home'

- Version with issue:
The problem is only present in iOS (i try real device) and with all version of xf (4.0.0 Pre Release 9 and 4.0.1.383393-nightly)

### Reproduction Link
https://github.com/davidortinau/Gastropods.git

**Comment by kingces95** [comment] 2019-05-03 01:59
![Image from iOS (1)](https://user-images.githubusercontent.com/4120386/57116816-3eebbc00-6cf3-11e9-9045-6895ed9e73bf.jpg)

**Comment by samhouts** [comment] 2019-05-06 17:32
Duplicate of #5831

**Closed by samhouts** 2019-05-06 17:32 UTC
Labels: a/collectionview, a/shell :shell:, e/10:clock10:, p/iOS 🍎, s/unverified, t/bug :bug:
