### ISSUE TITLE
[iOS] TouchDragExit on Xamarin.Forms.Button don't fire a Release Event

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#3523] opened 2018-08-09 12:02 UTC
### Description
The TouchDragExit Event on the ButtonRenderer on iOS does't fire a Release Event

### Steps to Reproduce

1. Put a breakpoint on the release EventHandler,
    Or change the style of a Button when Pressed Event and another style when Released Event
2. Press the Button and move outside the Button when pressing
3. The Button don't fire the Released Event.

### Expected Behavior
Send Release Event when TouchDragExit in ButtonRenderer
```
        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);

            if (Control != null && e.NewElement is Button view)
            {
                Control.TouchDragExit +=  SendReleased;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (Control != null)
            {
                Control.TouchDragExit -= SendReleased;
            }

            base.Dispose(disposing);
        }

        void SendReleased(object sender, EventArgs e)
        {
            ((IButtonController)Element)?.SendReleased();
        }
```

### Basic Information

- Xamarin.Forms: 3.1.0.697729

**Comment by clovs** [comment] 2018-08-12 15:36
Hello,

There is the project with a custom Button Renderer to console all exit events of the Button.
[Issue35238-1.zip](https://github.com/xamarin/Xamarin.Forms/files/2281070/Issue35238-1.zip)

Let me know,
Regards.

**Comment by hartez** [comment] 2018-08-25 03:43
Yes, the Xamarin.Forms ButtonRenderer for iOS does not respond to the TouchDragExit event by default. This is by design. If you want to modify the button to respond to this event, the custom renderer in the project @samhouts posted will work quite nicely. 

Since this has a simple solution and since making this the default would break the behavior of existing apps, I'm closing this issue.

**Closed by hartez** 2018-08-25 03:43 UTC
Labels: p/iOS 🍎

**Comment by Phenek** [comment] 2018-08-29 14:05
Hello,

Definitely regarding the code on [iOS Button Renderer here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs)

Some release event are not fire when iOS fire a TouchDragExit, not even for TouchCancel (Fired when the button is on a scrollView or a DetailView)
And a pressed event are not fire when iOS fire a TouchDragEnter.

The good practise on IOS is to send some event like below: 
```
            if (Control != null && e.NewElement is Button view)
            {
                Control.TouchCancel += SendReleased;
                Control.TouchDragExit += SendReleased;
                Control.TouchDragEnter += SendPressed;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (Control != null)
            {
                Control.TouchDragExit -= SendReleased;
                Control.TouchCancel -= SendReleased;
                Control.TouchDragExit -= SendPressed;
            }

            base.Dispose(disposing);
        }

        void SendReleased(object sender, EventArgs e)
        {
            ((IButtonController)Element)?.SendReleased();
        }

        void SendPressed(object sender, EventArgs e)
        {
            ((IButtonController)Element)?.SendPressed();
        }
```

I will not reopen this issue again, regarding the code these events are missing.
don't even try to load a project, just read the [ iOS Button Renderer here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs)

Regards,

**Comment by Phenek** [comment] 2019-01-23 14:47
On Android like on iOS there is no event when touch is canceled 
(when scrollView is scrolling for example)

There my fix on Android, iOS is already fix on top of it.
```
        public override bool OnTouchEvent(MotionEvent e)
        {
            if (e.Action == MotionEventActions.Cancel)
            {
                SendReleased();
            }
            return base.OnTouchEvent(e);
        }

        public override bool OnInterceptTouchEvent(MotionEvent ev)
        {
            if (ev.ActionMasked == MotionEventActions.Cancel)
            {
                SendReleased();
            }
            return false;
        }
```
I'm sure this will help some body.
Regards,
