### ISSUE TITLE
the password entry flow direction (Right to left) is not working !!!

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#9640] opened 2020-02-19 19:00 UTC

**Comment by samhouts** [comment] 2020-02-20 18:15
@mhrastegary77 Please fill out the entire issue template.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by yurkinh** [comment] 2020-02-26 13:57
@mhrastegary77 @mhrastegary77  This is the same issue as  [#9684](https://github.com/xamarin/Xamarin.Forms/issues/9684)

**Comment by samhouts** [comment] 2020-03-02 22:24
Duplicate of #9684

**Closed by samhouts** 2020-03-02 22:24 UTC
Labels: a/entry, a/rtl, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
