### ISSUE TITLE
Error referencing Nightly NuGet Package for Xamarin.Forms

### ISSUE THREAD

**Issue by nlraley** [xamarin/Xamarin.Forms#2155] opened 2018-03-21 15:56 UTC
### Description
When we start a new cross-platform shared project, add a WPF project.  Update the Xamarin.Forms to nightly 3.1.0.304117-nightly and also add the package to the WPF project.

Looking at the requirements for the NuGet packages, there seems to be a mismatch.  Trying to determine what needs to be done to reference the 2 packages.

### Steps to Reproduce

1. Start a new cross-platform shared project.
3. Update to the Xamarin.Forms package 3.1.0.304117-nightly or pre-2.
4. Try to build the UWP project.

### Expected Behavior
Builds fine.
### Actual Behavior
Exception:
C:\Users\...\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard1.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\...\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
### Basic Information

- Version with issue: 3.1.0.304117-nightly
- Last known good version: unknown
- IDE: Visual Studio 2017 15.6.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms, Xamarin.Forms.Platform.WPF
- Affected Devices:

***NOTE*** I modified this a bit since the cause of the issue is not with the Xamarin.Forms.Platform.WPF, but rather the Xamarin.Forms package itself.  Updating that itself is causing the failure.

**Comment by mohachouch** [comment] 2018-03-21 18:34
Hi, can you attached a reproduction project.

**Comment by nlraley** [comment] 2018-03-21 18:42
Sure thing.
[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/1834756/App3.zip)

Hopefully it's something small, but I'm not sure enough about the dependencies to identify the root cause.  Thanks again!

**Comment by mohachouch** [comment] 2018-03-21 18:54
Hi,

I don't see the link between the wpf and xamarin forms project.

You can read this tutorial for quick start 

https://mohachouch.github.io/Xamarin-Forms-WPF-QuickStart/

**Comment by nlraley** [comment] 2018-03-21 18:57
Yes, I should be able to build before making that link though, right?

**Comment by nlraley** [comment] 2018-03-21 19:00
Also, adding the reference to the PCL/Shared project has no affect on the build error.

**Comment by mohachouch** [comment] 2018-03-21 19:20
I created a new WPF project but this time if I use the package.config file to manage the nuget packages and I no longer have the problem.

I do not know that it is the problem but it does not download the useful packages

[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/1834888/App3.zip)

**Comment by nlraley** [comment] 2018-03-21 19:21
Yes, I was coming to that conclusions as well.  Not sure why it wouldn't be, that's quite odd.

Are there any known issues with using the project reference for NuGet packages not adding the corresponding dependencies?

**Comment by mohachouch** [comment] 2018-03-21 19:25
I was not aware of this problem may be the report to the relevant team.

Do not hesitate to check out all the bugs on Xamarin Forms for WPF. I need user feedback to make it reliable. Thank you

**Comment by nlraley** [comment] 2018-03-21 19:28
Yea, we have to do a major refactor due to permission issues on Server 2016 with our UWP app, i.e. it won't load all the assets unless the user is an admin or all the group policy stuff is disabled.  

We are looking at this as an alternative to having to re-write all our Xamarin controls to wpf, so we are seeing what can be re-used with this library.

We'll definitely keep you informed if we proceed with this route.  We were just having a difficult time getting the dependencies pulled, which as you can see, don't appear to be occurring for whatever reason using the package reference.

Do we need to report this issue elsewhere?

**Comment by nlraley** [comment] 2018-03-21 19:34
Btw, I still can't build WpfApp1 or 2 from that zip you sent.  I still get the:

> C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Exceptions.

**Comment by nlraley** [comment] 2018-03-21 19:43
Also, this appears to be occurring as soon as the Xamarin.Forms nightly package is added, before the WPF package is added.

**Comment by mohachouch** [comment] 2018-03-21 19:45
Try rebuild WpfApp2,

I removed all packages for zip the directory

**Comment by nlraley** [comment] 2018-03-21 20:25
Still now go.  Details on build output is showing:

> 1>------ Rebuild All started: Project: WpfApp2, Configuration: Debug Any CPU ------
1>Build started 3/21/2018 3:24:47 PM.
1>Building with tools version "15.0".
1>Target "_ValidateXFTasks" in file "C:\Users\nathan.raley\source\repos\App3\packages\Xamarin.Forms.3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.targets" from project "C:\Users\nathan.raley\source\repos\App3\WpfApp2\WpfApp2.csproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
1>Task "Error" skipped, due to false condition; ('$(_XFTargetsImportedAgain)' == 'True') was evaluated as ('' == 'True').
1>C:\Users\nathan.raley\source\repos\App3\packages\Xamarin.Forms.3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\source\repos\App3\packages\Xamarin.Forms.3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building target "_ValidateXFTasks" in project "WpfApp2.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>"C:\Users\nathan.raley\source\repos\App3\WpfApp2\WpfApp2.csproj" (Rebuild target) (1) ->
1>(_ValidateXFTasks target) -> 
1>  C:\Users\nathan.raley\source\repos\App3\packages\Xamarin.Forms.3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\source\repos\App3\packages\Xamarin.Forms.3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.00
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by mohachouch** [comment] 2018-03-21 20:32
Did you try to close Visual Studio then rebuild?

**Comment by nlraley** [comment] 2018-03-21 20:33
Yep, as well as clearing the NuGet cache.

**Comment by mohachouch** [comment] 2018-03-21 20:37
Try delete obj and bin.

**Comment by nlraley** [comment] 2018-03-21 20:59
Closed the solution.
Cleared all bin and obj folders.
Cleared NuGet cache.  Cleared secondary repository of NuGet caches as well to be safe.  Ensured all the pacakges folders were cleared and gone.
Re-Opened the solution.
Re-built.
Same error.

Not sure what's going on with this thing.

**Comment by mohachouch** [comment] 2018-03-21 21:09
Try recreate a new WPF projet => Build
Add Xamarin.Forms => Build
Add Xamarin.Forms.Platform.WPF => Build

**Comment by nlraley** [comment] 2018-03-21 21:20
Okay, trying just the Xamarin.Forms piece.  Here are the results:
Create Xamarin.Forms cross-platform Shared project/solution.
Build UWP.  Success.
Update all Xamarin.Forms packages to the latest nightly.
Re-build.  Fail, error recommends restarting IDE if the problem persists.
Restarted Visual Studio.
Re-opened the solution.
Re-build.  Error:

> 1>Build FAILED.
1>
1>"C:\Users\nathan.raley\source\repos\App1\App1\App1.UWP\App1.UWP.csproj" (Rebuild target) (1) ->
1>(_ValidateXFTasks target) -> 
1>  C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.1.0.304117-nightly\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.02
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

So, apparently as soon as I update to the latest nightly, it blows up.

**Comment by mohachouch** [comment] 2018-03-21 21:33
I did the same thing as you.

Except that before reopening visual studio I deleted the obj and bin folders.

And I was able to compile

**Comment by nlraley** [comment] 2018-03-21 22:01
Looks like that may have worked.  I'll try reproducing once more tomorrow and let you know.

That sure was annoying.

**Comment by nlraley** [comment] 2018-03-22 21:34
I am consistently getting this even using the Pre-2 target for 3.0.

The issue isn't with the WPF portion, it's the Xamarin.Forms package itself.  Even updating existing projects to this is having consistent issues.  Closing Visual Studio, deleting all the bin and obj folders from all the projects, restarting visual studio, clearing NuGet cache, and re-opening the project doesn't even appear to fix it 95% of the time.

**Comment by nlraley** [comment] 2018-03-22 22:17
Here is a dump of the build for one of the projects that is failing:

> 2>------ Rebuild All started: Project: Aeros.Mapping.UWP, Configuration: Debug x86 ------
> 2>Build started 3/22/2018 5:07:04 PM.
> 2>Building with tools version "15.0".
> 2>Target "_ValidateXFTasks" in file "C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard1.0\Xamarin.Forms.targets" from project "C:\Projects\ADM_CRS\AerosCore\Aeros.Mapping\Sprint 11\Aeros.Mapping\Aeros.Mapping.UWP\Aeros.Mapping.UWP.csproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
> 2>Task "Error" skipped, due to false condition; ('$(_XFTargetsImportedAgain)' == 'True') was evaluated as ('' == 'True').
> 2>C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard1.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
> 2>Done building target "_ValidateXFTasks" in project "Aeros.Mapping.UWP.csproj" -- FAILED.
> 2>
> 2>Build FAILED.
> 2>
> 2>"C:\Projects\ADM_CRS\AerosCore\Aeros.Mapping\Sprint 11\Aeros.Mapping\Aeros.Mapping.UWP\Aeros.Mapping.UWP.csproj" (Rebuild target) (1) ->
> 2>(_ValidateXFTasks target) -> 
> 2>  C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard1.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\nathan.raley\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
> 2>
> 2>    0 Warning(s)
> 2>    1 Error(s)
> 2>
> 2>Time Elapsed 00:00:00.01
> ========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by mohachouch** [comment] 2018-03-23 20:59
Hi, 

I think it's not a WPF platform bug.

@samhouts @pauldipietro

**Comment by mohachouch** [comment] 2018-03-23 21:55
Can you give the list of things that are missing for your project? I am working on a list of tasks to finish the Xamarin forms project for WPF as soon as possible.

**Comment by Caballo5** [comment] 2018-04-05 09:49
Blank Xamarin.Android project using XF3.0 won't build with identical build error:
"The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly c:\Users\..\source\repos\App1\packages\Xamarin.Forms.3.0.0.296286-pre2\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	App1			
"

**Comment by nlraley** [comment] 2018-04-05 14:29
Caballo5, for what it's worth, installing the 4.6 and 4.6.1 .NET SDKs appeared to resolve many of those problems for me.

**Comment by Caballo5** [comment] 2018-04-06 06:44
On my PC 4.5.1, 4.6 and 4.7.1 are already installed. 4.6.1 cannot be installed since 4.7.1 is in-place upgrade for 4.6.1.

**Comment by samhouts** [comment] 2018-04-16 22:39
@nlraley: Make sure you update the Microsoft.NETCore.UniversalWindowsPlatform package in your UWP project and set the minimum version to Fall Creators Update if you continue to get issues with the UWP build.


@Caballo5: I can't reproduce the issue. Did you ensure that you restarted Visual Studio after the upgrade?

**Comment by edamreed** [comment] 2018-05-09 08:59
Hi, same issue here.
VS 15.7.0
New Xamarin.Forms project using .net standard.
Xamarin.Forms 3.0.0.446417
NETCore.UniversalWindowsPlatform 6.1.4
Updated VS to 15.7.1
Clean Solution. Close VS, delete obj and bin from all projects.
Open Solution, Clean, Rebuild.

The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly blah\.nuget\packages\xamarin.forms\3.0.0.446417\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by edamreed** [comment] 2018-05-09 14:29
Downgrading Xamarin.Forms to 2.5.1.527436 seems to fix the issue.

**Comment by edamreed** [comment] 2018-05-14 14:51
Strange, opening the solution, upgrading Xamarin.Forms to the v3.0.0.446417 is working now.

**Comment by PureWeen** [comment] 2018-05-23 19:43
Duplicate of
https://github.com/xamarin/Xamarin.Forms/issues/2667

should be fixed in upcoming service release

**Closed by PureWeen** 2018-05-23 19:43 UTC
Labels: s/needs-info

**Comment by AlexDelRosario** [comment] 2019-07-17 21:08
**### El siguiente problema se me presento al instalar windows 10 y Luego Instalar Visual 2017**
Error La tarea "Xamarin.Forms.Build.Tasks.GetTasksAbi" no se pudo cargar desde el ensamblado
 C:\Users\Admin\.nuget\packages\xamarin.forms\3.1.0.697729\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll.
 No se puede cargar el archivo o ensamblado 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ni una de sus dependencias. El sistema no puede encontrar el archivo especificado. Confirme que la declaración <UsingTask> sea correcta; 
que el ensamblado y todas sus dependencias estén disponibles; y que la tarea contenga una clase public que implemente Microsoft.Build.Framework.ITask.	Project.Android

**Comment by AlexDelRosario** [comment] 2019-07-18 00:58
El mismo error me paso lo que realize para el funcionamiento fue Eliminar las carpetas Bin y Obj de cada archivo Luego limpie y recompile luego actualice mi Windows 10 a la ultima versión y todo empezó a funcionar correctamente. Saludos.
