### ISSUE TITLE
Focus System.ObjectDisposedException: Cannot access a disposed object

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#5202] opened 2019-02-11 18:24 UTC
### Description

Since xamarin forms 3.5 I'm having this error when call .Focus()

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_Context ()
ViewRenderer2[TView,TNativeView].OnFocusChangeRequested (System.Object sender, Xamarin.Forms.VisualElement+FocusRequestArgs e) (wrapper delegate-invoke) System.EventHandler1[Xamarin.Forms.VisualElement+FocusRequestArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.VisualElement/FocusRequestArgs)
VisualElement.Focus ()

### Steps to Reproduce

1. Call Entry.Focus()

### Expected Behavior
the keyboard focus was set to this element

### Actual Behavior
System.ObjectDisposedException: Cannot access a disposed object

### Basic Information

- Version with issue: 3.5
- Last known good version: 3.4
- IDE: Visual Studio 2017 Professional

**Comment by transis2** [comment] 2019-02-11 18:42
It also happens on Unfocus

Java.Interop
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
Java.Interop
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Android.Views
View.ClearFocus ()

Xamarin.Forms
VisualElement.Unfocus ()

**Comment by transis2** [comment] 2019-02-12 12:32
I've collected this error automatically with Microsoft App Center
I can't reproduce it during the tests, it happens on production release with my users.
It happens when the program call .Focus(). Every Entry field is faccing this problem, but to sample, its a button that call an Entry.Focus();

    private void LBL_UNIT_LIQ_Tapped(object sender, EventArgs e)
    {
         TXT_PRECO_INFORMADO_UNIT?.Focus();
    }

I've downgrade XF to 3.4 and this problem stops. So, it's a 3.5 problem...

**Comment by c4tTi** [comment] 2019-02-13 16:27
I do have the same error - also downgrading back to 3.4

**Comment by transis2** [comment] 2019-02-13 18:04
They have no time to fix, unless a lot of people complain.
So, let's wait...

**Comment by grandconjuration** [comment] 2019-02-20 13:05
We are also experiencing this issue

**Comment by transis2** [comment] 2019-02-20 13:29
Not solved with build 3.5.0.169047

**Comment by andreinitescu** [comment] 2019-02-20 14:29
Would be great if you could give a reproduction sample, I could try help fixing the issue

**Comment by grandconjuration** [comment] 2019-02-20 14:40
The other thread has an example zip.
#5238

**Comment by andreinitescu** [comment] 2019-02-20 15:49
Good news, it looks fixed with 4.0.0.135214-pre4, would be helpful to confirm

**Comment by luveti** [comment] 2019-02-20 16:33
@andreinitescu that build works for the test case I added to #5202. But I think most of us would like to see this fixed in 3.5.x since 4 is still in preview!

**Comment by samhouts** [comment] 2019-03-01 18:03
The fix will be in 3.6 stable, which should be out next week. Thanks!

**Comment by transis2** [comment] 2019-03-01 19:09
Thank you @samhouts

**Comment by transis2** [comment] 2019-03-06 12:30
Fixed with 3.6.* and 4.*

**Closed** 2019-03-08 13:29 UTC
Labels: blocker, i/high, i/regression, p/Android, t/bug :bug:

**Comment by DeepikaBalaSubramaniyan** [comment] 2019-03-13 09:54
Hi @samhouts 

At Xamarin forms version 3.6 latest stable, After enabling the Exception setting(C++ Extensions, Common Language Runtime Exceptions), same object disposed exception of entry view was thrown while calling entry.UnFocus() method 

I have attached the screen shot for this issue 
![image](https://user-images.githubusercontent.com/42173947/54269800-0a396f00-45a4-11e9-9ca0-da6a3050a19b.png)
Can you look in to this and include the fix with upcoming nuget?

**Comment by transis2** [comment] 2019-03-13 12:54
The unfocus problem is related with other issue:
https://github.com/xamarin/Xamarin.Forms/issues/5376

**Comment by DeepikaBalaSubramaniyan** [comment] 2019-03-13 12:56
OK Can you let us know when this issue get fixed? , Please provide approximate time line.

**Comment by DeepikaBalaSubramaniyan** [comment] 2019-03-18 09:19
Hi @samhouts 

At Xamarin forms version 3.6 last stable also, Picker.Focus() calls throws exception , I have attached the exception details, Also Issue replicated sample, follow the replication procedure

Replication Procedure:
1. Run the attached sample and Enable the Exception settings (C++ Extensions, Common Language Runtime Exceptions)
2. Click the Button named as LoadLabel to load the label View
3. Click the Button named as LoadPicker to load the Xamarin forms Picker View
4. Click the Button named as FocusPicker to get the focus for Picker 
5. Now select any item from the displayed list
6. Click the Button named as UnFocusPicker to get the Unfocus for Picker 
7. Again Click the Button named as LoadLabel to load the label View
8. Click the Button named as LoadPicker to load the Xamarin forms Picker View
9. Click the Button named as FocusPicker to get the focus for Picker 
10. Now object disposed exception occurred at picker.Focus() calls 

Exception screenshot: 

![image](https://user-images.githubusercontent.com/42173947/54519095-bce64480-498b-11e9-877a-b4834165970a.png)

Sample: 
http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGridNet-1266236982

So Focus System.ObjectDisposedException: Cannot access a disposed object issue does not get fixed in xamarin forms 3.6 last stable version for Xamarin.Forms.Picker View and Xamarin.Forms.DatePicker view, Attached sample is related to Picker.Focus() calls. 

Please look in to this issue and provide the fix for upcoming releases.
