### ISSUE TITLE
Android Bottom Tab Pages - Title Missing  Verified in Xamarin Forms 3.1 and 3.2.0

### ISSUE THREAD

**Issue by anee146** [xamarin/Xamarin.Forms#3813] opened 2018-09-18 02:36 UTC
Android Bottom Tab Pages - Title Missing
### Description
One of the improvements in Xamarin Forms 3.1 and 3.2.0 version is the Android Bottom Tab Concept. If the pages contains more than 3 bottom tabs, the app will appear without page title.
### Steps to Reproduce

1. Create Xamarin Forms Project and implement Android bottom tab concept (Xamarin Forms 3.1 feature) 
2.  Add more 4 tab pages
3. https://blog.xamarin.com/xamarin-forms-3-1-improvments/
4. Also I referred the project in below mentioned repository. 
    https://github.com/davidortinau/TheLittleThingsPlayground
5. Add an additional page to MainPage.

### Expected Behavior
Tab page should appear with title and icon.
### Actual Behavior
Tab page title is missing and icon only appearing

### Basic Information

- Version with issue: Xamarin Forms 3.1/3.2.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android:  
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms 3.1/3.2.0
- Affected Devices:
Android
### Reproduction Link
https://github.com/davidortinau/TheLittleThingsPlayground
![screenshot_20180918-103351](https://user-images.githubusercontent.com/24631131/45663212-7c6a5300-bb2f-11e8-9d18-f4c4c9a034da.jpg)
![screenshot_20180918-104016](https://user-images.githubuse
![screenshot_20180918-103401](https://user-images.githubusercontent.com/24631131/45663217-84c28e00-bb2f-11e8-8cb6-4aefbaa9af9e.jpg)
![screenshot_20180918-103405](https://user-images.githubusercontent.com/24631131/45663225-8d1ac900-bb2f-11e8-9189-5a122d3a6f97.jpg)

rcontent.com/24631131/45663214-7e341680-bb2f-11e8-9315-bcf7153125b8.jpg)

**Comment by GalaxiaGuy** [comment] 2018-09-18 14:34
This appears to be a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3312, and is basically expected behavior.

There is a planned option to disable it: https://github.com/xamarin/Xamarin.Forms/issues/3083 .

**Closed** 2018-09-18 14:45 UTC

**Comment by anee146** [comment] 2018-09-19 07:10
@GalaxiaGuy 

Thanks for the information. I followed #3083 and the link https://gist.github.com/LynoDesu/64904b6d143892cf14a60a32798a36bb. It works.
