### ISSUE TITLE
[Android] Entry Focused/Unfocused problems

### ISSUE THREAD

**Issue by Ryukote** [xamarin/Xamarin.Forms#2183] opened 2018-03-26 08:32 UTC
### Steps to Reproduce

1. Add 2 Entry Controls in Grid
2. Assign Focused and Unfocused event handlers to them (I do this with lamda expressions)
3. First tap on first Entry, then on second 

### Expected Behavior
Expected behavior is to trigger only Focused event when you tap on Entry. Another issue with that is that Text value of 2nd Entry will be assigned to 1st Entry control even tho I am not setting it to the 1st Entry control. And since I have XamForms.Controls.Calendar package from rebeccaXam Calendar is showing after Unfocused event on 2nd Entry even tho I never stated for that control to be visible. Initial is false for property IsVisible for that calendar control. When I remove that calendar control issue is still here so that calendar control is not a problem.

### Actual Behavior
When I first tap on first Entry only Focused event is triggered which is ok, but after that when I tap on 2nd Entry first Focused is triggered then Unfocused after Focused even tho I didn't unfocused that Entry.

### Basic Information
I have basic Xamarin.Forms project where in Grid I placed one Entry after another (I have two of them) which I placed in Row="1" and Row="2". I am deploying this app on Android 7.0 and this issue happen on both my Samsung Galaxy S7 Edge and friends Huawei

- Version with issue: Last Xamarin.Forms version
- Last known good version: (tested on random several versions of Xamarin and had same issues on all of them)
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 7.0
- Nuget Packages: XamForms.Controls.Calendar (rebeccaXam), Newtonsoft JSON
- Affected Devices: Samsung Galaxy S7 Edge (SM-G935F), HuaweiP9 Lite (HUAWEI VNS-L31)

**Comment by hartez** [comment] 2018-07-05 22:02
> Version with issue: Last Xamarin.Forms version

Please give us a version number; "last version" changes over time.

> (tested on random several versions of Xamarin and had same issues on all of them)

Please let us know what the earliest version you tested was.

Could you please post a minimal reproduction project? Or at least the XAML and code you used to create your Entry controls and to hook up the Focused/Unfocused events?

**Comment by OneVideo** [comment] 2018-08-04 01:27
We have experienced similar unexpected behavior in a slightly different circumstance:
In a Xaml page description that includes both EntryCell(s) and Entry elements (in a single TableSection in a TableView), ..
where the Entry has an event handler declared for the Focus event and the EntryCell does not (a. because there is no Focus property, and b. there is no event handler declared on those Xaml elements), ...
  And where the event handler code calls .Unfocus() on the sender (first received event handler parameter) typecast from object to Entry
  THEN the event handler on the Entry element does not fire (as it should not) when the user touches the EntryCell
    And the event handler on the Entry element does fire (as it should) when the user touches the Entry
  HOWEVER, the event handler on the Entry element <emphasis>DOES FIRE, when it should not</emphasis> upon a touch of the EntryCell, subsequent
     to the touch on the (single) Entry element, And the first parameter passed upon calling the event handler is of type Xamarin.Forms.Entry (i.e., NOT .EntryCell)
     and pointed to the prior-clicked/tapped/touched Entry element (which has been updated with results of the prior firing)

**Comment by samhouts** [comment] 2018-08-06 22:56
@OneVideo Your experience does sound similar, but I think it might be different enough to warrant a new issue. Would you mind opening a new issue and possibly provide a small test project to show the problem? Thanks!

@Ryukote Can you please tell us which versions of Xamarin.Forms you have tested and possibly provide a small test project to show the problem? Thanks!

**Comment by OneVideo** [comment] 2018-08-07 03:44
@Ryukote The Forms version was well-specified in my original post, namely "Xamarin Forms: 3.0.0.482510"
@samhouts Please advise whether the attached Visual Studio 2017 (version 15.7.0) project, in WinRAR ZIP format, suffices.
[FocusOnEntry.zip](https://github.com/xamarin/Xamarin.Forms/files/2264883/FocusOnEntry.zip)

**Comment by PureWeen** [comment] 2018-09-10 23:58
@Ryukote  hasn't responded about the original issue so I'm going to close this one for now

@OneVideo  I couldn't run your project as is but here it is modified a bit so I can run it
[Uploading FocusUnfocusProblem.zip…]()

I'm either not seeing the issue you describe or I'm just not quite following your instructions

Can you open up a new issue and just list out the steps I can take with the attached sample to see the issue you are describing?

**Closed by PureWeen** 2018-09-10 23:58 UTC
Labels: p/Android

**Comment by OneVideo** [comment] 2018-09-11 01:37
Shane-

 

I ran your project here and got the undesired result.  I used the 8.1 build toolchain instead of the 9.0 originally configured in the project files.  And, Visual Studio complained the .Net 4.7.2 was not installed so relied instead on 4.6.1.

 

Using the interactive debugger, I set a breakpoint on Line 21 in MainPage.xaml.cs (in the OnEntryClicked method).

And, in fact, as displayed at the top of the View, after selecting the box “First Placeholding” (to the right of the Label displayed “ViewCell + Label + Entry”), the breakpoint is fired.  After F5 Continue, I type on the onscreen keyboard “The Text”, and select “Done”.

 

THEN,  I select the box “Second Placeholding” and the same breakpoint is fired.  THAT is incorrect.  There is no such handler express on Line 31 of MainPage.xaml:

<EntryCell Label="EntryCell" Placeholder="Second Placeholding" HorizontalTextAlignment="Center" Completed="OnEntryCompeted" />

 

Please reply ..

 

Regards, OneVideo

**Comment by OneVideo** [comment] 2018-09-11 01:39
Shane-

I ran your project here and got the undesired result.  I used the 8.1 build toolchain instead of the 9.0 originally configured in the project files downloaded.  And, Visual Studio complained that .Net 4.7.2 was not installed so I relied instead on 4.6.1.

Using the interactive debugger, I set a breakpoint on Line 21 in MainPage.xaml.cs (in the OnEntryClicked method).  And, in fact, as displayed at the top of the View, after selecting the box “First Placeholding” (to the right of the Label displayed “ViewCell + Label + Entry”), the breakpoint is fired.  After F5 Continue, I type on the onscreen keyboard “The Text”, and select “Done”.

THEN,  I select the box “Second Placeholding” and the same breakpoint is fired.  THAT is incorrect.  There is no such handler express on Line 31 of MainPage.xaml:
<EntryCell Label="EntryCell" Placeholder="Second Placeholding" HorizontalTextAlignment="Center" Completed="OnEntryCompeted" />

Do you see the same behavior there?

Regards, OneVideo
