### ISSUE TITLE
using TabbedPage SetTabIcon found a bug?

### ISSUE THREAD

**Issue by Jockeyvb** [xamarin/Xamarin.Forms#3850] opened 2018-09-20 10:20 UTC
### Steps to Reproduce

 on android and set     On<Android>().SetToolbarPlacement(ToolbarPlacement.Bottom); 
 and Render  TabbedPageRenderer class   SetTabIcon function not use

and find source code :

 protected override void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
          
             if (e.PropertyName == Page.IconProperty.PropertyName)
            {
                var page = (Page)sender;
                var index = Element.Children.IndexOf(page);
                FileImageSource icon = page.Icon;

                if (IsBottomTabPlacement)
                {
                    var menuItem = _bottomNavigationView.Menu.GetItem(index);
                    menuItem.SetIcon(GetIconDrawable(icon));
                }
                else
                {
                    TabLayout.Tab tab = _tabLayout.GetTabAt(index);
                    SetTabIcon(tab, icon);
                }
            }
        }
 

-----------------------------

   if (IsBottomTabPlacement)
                {
                    var menuItem = _bottomNavigationView.Menu.GetItem(index);
                    menuItem.SetIcon(GetIconDrawable(icon));

so if IsBottomTabPlacemen ==true ,is BottomNavigationView not tablayout not trig SetTabIcon function

is bug?

**Comment by PureWeen** [comment] 2018-09-20 22:37
Agreed duplicate of #3397

**Closed by PureWeen** 2018-09-20 22:37 UTC
