### ISSUE TITLE
[Bug] [Android] If one frame has a shadow, all frames on screen have shadow even if HasShadow=false

### ISSUE THREAD

**Issue by activa** [xamarin/Xamarin.Forms#7345] opened 2019-09-01 16:22 UTC
### Description

ANDROID ONLY!

When adding more than one frame on a page, AND one frame has a shadow (HasShadow=true), any frame added after that will also have a shadow, regardless of the HasShadow property.

### Steps to Reproduce

1. Add two Frames to a page, the first one with HasShadow=true, the 2nd one with HasShadow=false

Markup:

```
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <Frame Grid.Column="0" x:Name="Frame1" HasShadow="True" BackgroundColor="#f0f8ff"><Label>HasShadow=True</Label></Frame>
    <Frame Grid.Column="1" x:Name="Frame2" HasShadow="False" BackgroundColor="#f0f8ff"><Label>HasShadow=False</Label></Frame>
</Grid>
```
This is the result:
![Screenshot_1567353530](https://user-images.githubusercontent.com/650710/64079113-2db6ba00-cca9-11e9-936c-c67f69f8cd6f.png)

When setting HasShadow of the 2nd Frame to False after the screen is rendered, the shadow is removed. This is the event handler for the button:

```
private void Button_OnClicked(object sender, EventArgs e)
{
    Frame2.HasShadow = true;
    Frame2.HasShadow = false;
}
```

However, when switching the frames around, first the one without shadow and then the one with shadow, it works as expected:

![Screenshot_1567353615](https://user-images.githubusercontent.com/650710/64079152-9140e780-cca9-11e9-9d7a-8eeeb520da3b.png)

After some digging, it turns out that whenever there's one Frame with HasShadow=true, any frame after that will also have HasShadow=true.

### Expected Behavior

Frames should honor the HasShadow property

### Basic Information

- Version with issue: 4.2.0.709249 (and also 4.0.1.*)
- Last known good version: ?
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 9.0 
- Android Support Library Version: 28.0.0.1

### Reproduction Link

Example project demonstrating the issue:

[AndroidShadowBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3563686/AndroidShadowBug.zip)

**Comment by sthewissen** [comment] 2019-09-06 08:49
I have a similar issue, but it's not a `Frame` but a `Grid` that all of a sudden gets a shadow. And all that while `Grid` doesn't even support shadows :) A repro project can be found here:
https://github.com/sthewissen/WeirdShadow

Might be related to #7218.

**Comment by samhouts** [comment] 2019-09-06 21:22
Duplicate of #7218

**Closed by samhouts** 2019-09-06 21:22 UTC
Labels: p/Android, s/unverified, t/bug :bug:

**Comment by activa** [comment] 2019-09-06 21:38
@samhouts Maybe you can move the repro project to #7218 since that one doesn't have any.
