### ISSUE TITLE
CollectionViews GroupHeaderTemplate does not span all of the columns on iOS

### ISSUE THREAD

**Issue by AndyRogers86** [xamarin/Xamarin.Forms#9219] opened 2020-01-15 17:21 UTC
### Description

When creating a grouped collection view that has 2 columns the header template only has a width of the first column in iOS. In Android the header spans all of the columns.

This causes issues if the text wraps and goes over more than one line as it pushes the first item below down so it is out of sync with the other items.

### Steps to Reproduce

1. See simple example in https://github.com/AndyRogers86/GroupedCVTest

### Expected Behavior

For the header template to span all columns in iOS as it does in Android

### Basic Information

- Version with issue: 4.4.0.991477
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.8
  - Android: 8.1.0 

### Screenshots

Android

![Screenshot_1579107254](https://user-images.githubusercontent.com/36670353/72455774-51dbe900-37bb-11ea-8266-16b97ef54624.png)

iOS

![Screenshot 2020-01-15 at 16 53 30](https://user-images.githubusercontent.com/36670353/72455814-61f3c880-37bb-11ea-8116-8486752b1cc4.png)

### Reproduction Link

https://github.com/AndyRogers86/GroupedCVTest

### Workaround

Could not find one

**Comment by Hamster-ZA** [comment] 2020-01-16 13:47
looks like a duplicate of  #8557

**Comment by AndyRogers86** [comment] 2020-01-17 14:27
> looks like a duplicate of #8557

Yes, definitely similar.

**Comment by StephaneDelcroix** [comment] 2020-01-17 16:20
Duplicate of #8557

**Closed by StephaneDelcroix** 2020-01-17 16:20 UTC
Labels: a/collectionview, s/unverified, t/bug :bug:
