### ISSUE TITLE
[Bug] When SwipeGesture is used with ListView, it doesn't work.

### ISSUE THREAD

**Issue by MackYang** [xamarin/Xamarin.Forms#5867] opened 2019-04-10 08:16 UTC
### Description
I uploaded the Demo and hoped to help solve this bug.

### Steps to Reproduce

1. 
2. [BugDemo](https://github.com/MackYang/UpLoad/blob/master/SwipeGesture.zip)
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment] 2019-04-12 01:02
Duplicate of #4628

**Closed by samhouts** 2019-04-12 01:02 UTC
Labels: a/gestures 🖖, a/listview, s/unverified, t/bug :bug:
