### ISSUE TITLE
[Enhancement] Please add custom renderer lifecycle

### ISSUE THREAD

**Issue by davidpsaylor** [xamarin/Xamarin.Forms#6854] opened 2019-07-11 13:26 UTC
## Summary
Please add methods and/or events that we can use to know when a custom renderer has executed. 

## API Changes

A control would have an event, similar to the old `Loaded` or `VisibilityChanged` events so that we know that any associated custom renderers will have had their `OnElementChanged` methods executed.

## Intended Use Case

We have been using an open source control -- [SignaturePad](https://github.com/xamarin/SignaturePad) but found a significant behavior deficiency which we would be unable to work around without forking and "owning" the code, which we would strongly prefer not to do.  The github repo and issues have not been touched in over a year, but there does not seem to be any alternative to that control. The lifecycle event would allow us to use this control as-is.

**Comment by samhouts** [comment] 2019-07-11 21:57
Duplicate of #2210

**Closed by samhouts** 2019-07-11 21:57 UTC
Labels: proposal-open, t/enhancement ➕
