### ISSUE TITLE
Pages containing a Button with a Command are not removed from memory after PopAsync

### ISSUE THREAD

**Issue by Yves-Be** [xamarin/Xamarin.Forms#3566] opened 2018-08-14 08:59 UTC
### Description

A page containing a button that has a command bound to it will not be removed from memory after calling `PopAsync()` on Navigation. This eventually leads to a large number of pages that are still active.
I have not seen these pages being GC'ed once.

### Steps to Reproduce

1. Create an app with two pages
2. Put a button with a command in Xaml on the second page
3. Navigate back and forth.
4. Use the Xamarin Profiler to create snapshots, and see the amount of active pages increase. 

### Expected Behavior

Pages containing a button with a Command should be removed from memory, just like pages without them.

### Actual Behavior

The pages remain in memory and consume resources, while the increasing amount of bindings that are still active eventually slow down the app.

### Basic Information

- Version with issue: 3.1.0.697729 and 3.2.0.637442-pre1
- Last known good version: ¯\\\_(ツ)\_/¯ even 2.5.1 shows this behavior
- IDE: VS 15.7.6
- Platform Target Frameworks: 
  - Android: 8.0 
  - UWP:  16299
- Android Support Library Version: 26.1.0.1

### Screenshots

![2018_08_14_08_46_18_xamarin_profiler_com companyname](https://user-images.githubusercontent.com/1593717/44081455-07ac219c-9faf-11e8-96b4-45baaa7e4b59.png)

### Reproduction Link

[MemoryLeakSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2286187/MemoryLeakSample.zip)

**Comment by andreinitescu** [comment] 2018-08-14 09:46
@Yves-Be Try to call GC.Collect and GC.SuppressFinalize after navigating away, in order to be really sure it's a memory leak.

**Comment by Yves-Be** [comment] 2018-08-14 10:00
I tried calling this:

```     private void _navigation_Popped(object sender, NavigationEventArgs e)
        {
            GC.Collect();
            GC.SuppressFinalize(e.Page);
        }
```
But the results are the same when taking snapshots before and after navigating.

**Comment by andreinitescu** [comment] 2018-08-14 10:16
First things first, I see you have the view-models static (singletons). This is not a good idea in my opinion for a number of reasons. View-models should lives as long as the views (Pages).

It appears like the view or view-model it's being held by a static object. 
What's interesting is, theoretically I think, this should still not create a leak. The only thing I could think of is since the view (the button) subscribes to ICommand:CanExecuteChanged of the view-model, this makes the view-model hold a reference to its listener (the button) which can creates the leak.
This is just an example. Usually most people do not use view-models as singletons, hence this issue doesn't' appear.

I don't have time right to do it, but I'd have to dig into the XF source code, normally implementation should use weak references to both views and view-models.

Hope this helps somehow.

**Comment by andreinitescu** [comment] 2018-08-14 10:17
Even if switching from having view-model singletons will (probably) solve your issue, it's still worth investigating to see what's causing the leak in your specific example.

**Comment by Yves-Be** [comment] 2018-08-14 11:14
The sample is derived from a larger project that uses MvvmLight. A static ViewModelLocator is usually used there in combination with its SimpleIoc, which leads to the singleton ViewModels.
Recreating the ViewModel each time does cause the page to be cleared from memory, but I agree it is still worth investigating.

**Comment by andreinitescu** [comment] 2018-08-14 11:40
Basically what I mean is to handle the button clicks without commands.

**Comment by Yves-Be** [comment] 2018-08-14 11:54
Setting the command of the button in the constructor of the page (not through binding) still exhibits the behavior. Using events instead of commands, there is no issue, as well as setting no BindingContext of the Page.

**Comment by andreinitescu** [comment] 2018-08-14 13:29
It leaks because the view-model is static. In the `Button` class implementation, it subscribes to command's `CanExecuteChanged`:

		void OnCommandChanged()
		{
			if (Command != null)
			{
				Command.CanExecuteChanged += CommandCanExecuteChanged;
				CommandCanExecuteChanged(this, EventArgs.Empty);
			}
			else
				IsEnabledCore = true;
		}

You should not use static view-models.

**Comment by Yves-Be** [comment] 2018-08-20 08:57
Setting the BindingContext of the page to null when navigating away works in the sample, but for some reason it was not enough in the application built with MvvmLight that I derived it from.
I managed to solve it there by unregistering the ViewModel's instance when navigating away backwards.

It is still my opinion that reusing ViewModel instances should not keep a page from being removed from memory, as this does not appear to be a problem in WPF. This practice is also widely used in combination with MvvmLight, as seen from @lbugnion 's [Xamarin Forms sample](https://github.com/lbugnion/sample-crossplatform-flowers/). In that sample, only one page is added to the ViewModelLocator, but adding a second one with a button and navigating back and forth shows the same issue.

**Comment by hartez** [comment] 2018-08-24 23:55
@Yves-Be  Andrei is correct - your ViewModel is holding a reference to your Button via the CommandCanExecuteChanged subscription. If you're going to keep your model around for an extended period of time (in your case, throughout the lifetime of the application), you need to set the Command property to `null` so that the Button can unsubscribe from that event and the Button (and the rest of its graph) can be collected. Probably the easiest way to do this right now would be to set `SecondPage.BindingContext` to `null` in `OnDisappearing`.

That said, there may be an opportunity for us to widen the pit of success here by using the WeakEventManager in our Command implementation (as Andrei pointed out upthread).

**Comment by hartez** [comment] 2018-08-25 00:02
I'm going to close this issue for now since there's a workaround available and it's not a bug so much as a design issue. I've created an enhancement case #3656 that references this discussion.

**Closed by hartez** 2018-08-25 00:03 UTC
Labels: p/Android, p/UWP
