### ISSUE TITLE
UIStatusBarStyle not respected by Forms

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#4343] opened 2018-11-08 06:22 UTC
### Description

When setting UIStatusBarStyle to UIStatusBarStyleLightContent the status bar text is white while the storyboard Launch Screen is displayed, and then black once a Xamarin Forms Page is pushed.

### Steps to Reproduce

1. Create new application 
2. Set `UIStatusBarStyle` to `UIStatusBarStyleLightContent` in the iOS Info.plist

### Expected Behavior

Pages should display white text in the Status Bar

### Actual Behavior

Page display default black text in the Status Bar once a Xamarin Forms Page is pushed.

### Basic Information

- Version with issue: current
- Last known good version: n/a

### Screenshots

During App Launch - LaunchScreen.storyboard
![image](https://user-images.githubusercontent.com/3860573/48181115-143c2000-e2db-11e8-9133-948670249521.png)

Xamarin Forms Page
![image](https://user-images.githubusercontent.com/3860573/48181143-30d85800-e2db-11e8-93b4-49a67ca9e47c.png)

### Reproduction Link

[LightUIStatusBar.zip](https://github.com/xamarin/Xamarin.Forms/files/2560510/LightUIStatusBar.zip)

**Comment by adammeaney** [comment] 2018-11-08 15:03
As an fyi, this can be fixed by settings the BarTextColor of your NavigationPage, but I do agree that it should keep the same default.

**Comment by dansiegel** [comment] 2018-11-08 15:34
@adammeaney if you look at the screenschots, and code you'll notice the BarTextColor of the NavigationPage actually is set. There is also a difference between the Navigation Bar Text and the Status Bar Text... it's the Status Bar Text that gets the wrong color.

**Comment by adammeaney** [comment] 2018-11-08 15:37
I would agree if I hadn't just solved it using that.

You also need 

	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>

In your info.plist.

I mean in the last hour I encountered the same issue as you, did this, and then had a white status bar appearance.

**Comment by rmarinho** [comment] 2018-11-09 23:06
We can try to figure a better way to pick the default, but we can also introduce a Platform specific to handle this.

**Comment by dansiegel** [comment] 2018-11-10 00:47
@rmarinho love the idea of adding a platform specific to control a specific page. I do think the default should be based on what you explicitly set in the Info.plist.

**Comment by dansiegel** [comment] 2019-04-30 02:46
Just a quick update on this... Looking at the [NavigationRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L673-L688) I would tend to believe that this is actually the major culprit. It seems that the PlatformSpecific `StatusBarTextColorMode` was done entirely wrong. There are a couple of changes that should be made.. 

1. The Enum for the Platform Specific should match the values coming from UIStatusBarStyle
1. The Enum for the Platform Specific should continue to have a DoNotAdjust like it currently does
1. The default value if not set should be DoNotAdjust… leave the StatusBar the heck alone.

```cs
public enum StatusBarTextColorMode
{
    DoNotAdjust = -1,
    Default = 0,
    LightContent = 1, // equal to BlackTranslucent
    BlackOpaque = 2
}

if(statusBarColorMode >= 0)
{
    UIApplication.SharedApplication.StatusBarStyle = (UIStatusBarStyle)statusBarColorMode;
}
else if(barTextColor.Luminosity <= 0.5 && UIApplication.SharedApplication.StatusBarStyle == UIStatusBarStyle.Default)
{
    UIApplication.SharedApplication.StatusBarStyle = UIStatusBarStyle.LightContent;
}
```

**Comment by acuntex** [comment] 2020-06-25 14:25
Are there any reasons why methods like SetStatusBarStyle or UpdateBarTextColor are not virtual?

The problem is that these methods are flawed. They might work in certain apps but if I want an app that has a StatusBarStyle LightContent and also a back button in a different color, it's basically impossible with the current logic.

If I set BarTextColor to White, the StatusBarStyle is correct, but the IconColor is then also White because UpdateBarTextColor() sets the TintColor of the NavigationBar to the BarTextColor.

There is a possibility to set IconColor, but it's also implemented invalid. 
`var iconColor = NavigationPage.GetIconColor(Current);
`
should be
`var iconColor = NavigationPage.GetIconColor(NavPage);
`

There is no way for us developers to create a small workaround.

Yes, I could fix it in the base but then I'd have to wait until a new version is released that works (current version e.g. does throw a NullReferenceException on iOS)

I don't mean to disrespect anyone from the Xamarin.Forms Team, but please, either make virtual necessary or do proper code review before merging especially in cases where a XF-property changes various native properties.

**Comment by jfversluis** [comment] 2022-08-23 11:37
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Closed by jfversluis** 2022-08-23 11:37 UTC
Labels: t/enhancement ➕, proposal-open, p/iOS 🍎, e/3 :clock3:, partner
