### ISSUE TITLE
[Bug] [UWP] Picker control has unwanted margin on top in Xamarin.Forms 4.3.x

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Forms#8150] opened 2019-10-22 14:05 UTC
# Description
When using a Picker control in UWP you get an unwanted margin on top of the picker.

### Steps to Reproduce
    <StackLayout>
        <Label Text="Welcome to Xamarin.Forms!" BackgroundColor="Yellow"/>
        <Picker BackgroundColor="Green"/>
    </StackLayout>

### Expected Behavior
The picker should en up right under the label (it does in xamarin forms 4.2.x)

### Actual Behavior
You get a margin (about as high as the picker itself) between the picker and the label

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.910310
- IDE: VS 2019 (16.3.5) for Windows 
- Platform Target Frameworks: 
  - UWP:  1903

### Screenshots
![uwp_picker](https://user-images.githubusercontent.com/10629345/67294068-a0902480-f4e5-11e9-8e96-566fd8424873.png)

**Comment by hartez** [comment] 2019-10-22 20:59
Confirmed.
[_8150 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3758555/_8150.Repro.zip)

**Comment by Depechie** [comment] 2019-10-22 21:24
Seems the Header will always be rendered on UWP even though no Picker Title property is filled in... I submitted PR #8160 to amend this.

**Comment by jimmccurdy** [comment] 2019-10-23 03:01
If anyone needs a workaround while waiting for the fix, add the following custom picker renderer in your UWP project:

using AppShack.UWP.Renderers;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Platform.UWP;

[assembly: ExportRenderer(typeof(Picker), typeof(CustomPickerRenderer))]
namespace AppShack.UWP.Renderers
{
	[Preserve(AllMembers = true)]
	public class CustomPickerRenderer : PickerRenderer
	{
		protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
		{
			base.OnElementChanged(e);
			if (Control != null)
				Control.Header = null;
		}
	}
}

**Comment by MitchBomcanhao** [comment] 2019-10-23 11:49
I have this on my project so that the title displays as the placeholder text instead, which is more consistent to what other platforms do in Xamarin.forms
```
protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                if (!string.IsNullOrWhiteSpace(Element?.Title))
                {
                    Control.Header = null;
                    Control.PlaceholderText = Element.Title;
                }                
            }
        }
```

**Comment by MagicAndre1981** [comment] 2019-11-18 10:40
Your workaround doesn't fix anything for me @jimmccurdy and the workaround from @MitchBomcanhao breaks picker completely.

**Comment by slakul** [comment] 2019-11-18 10:46
@MagicAndre1981 I made another workaround in my code. You can try replace

`Control.Header = null;`

with

`if (Control.Header is UIElement tb)
{
    tb.Visibility = Visibility.Collapsed;
}`

**Comment by MagicAndre1981** [comment] 2019-11-18 10:47
ok, with some code of the linked PR it works fine for my case:

        protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            base.OnElementChanged(e);
            if (Control != null)
            {
                Control.Header = null;
                Control.HeaderTemplate = string.IsNullOrEmpty(Element.Title) ? null : (Windows.UI.Xaml.DataTemplate)Windows.UI.Xaml.Application.Current.Resources["ComboBoxHeader"];
                Control.DataContext = Element;
            }
        }

I'll use this now until PR gets merged and released in next 4.3 version.

**Comment by MagicAndre1981** [comment] 2019-11-26 09:41
> I submitted PR #8160 to amend this.

Hi, @Depechie can you respond to the change requests so that it can be merged?

**Comment by Depechie** [comment] 2019-11-26 09:43
Talked to Gerald about it. Normally end of this week I will have some time to test the PR again to see if everything is ok to merge it.

**Comment by MagicAndre1981** [comment] 2019-11-26 09:44
ok, thanks

**Comment by MagicAndre1981** [comment] 2019-12-12 07:20
Is the issue still present in 4.4? Looks like @Depechie was not able to make the changes in his PR.

**Comment by Brosten** [comment] 2019-12-12 07:50
Yes, still present in 4.4.0991265  :(

**Comment by SoledadIce** [comment] 2019-12-12 12:55
Any info about when this will be fixed?

**Closed** 2019-12-19 17:39 UTC
Labels: in-progress, p/UWP, t/bug :bug:

**Comment by Bosch-Eli-Black** [comment] 2019-12-30 04:16
@jimmccurdy's workaround didn't work for me, but got me on the right track.

For me, I had to use the line

`Control.HeaderTemplate = new Windows.UI.Xaml.DataTemplate();`

instead of

`Control.Header = null;`

Hope this helps, and thanks to @jimmccurdy for the original workaround :)
