### ISSUE TITLE
[Bug] Xamarin.Forms IOS project on IOS14 - Entry with isPassword=true , focus and navigation problems.

### ISSUE THREAD

**Issue by tomsol432** [xamarin/Xamarin.Forms#12359] opened 2020-10-05 09:32 UTC
Hello!

After upgrading my solution to newest XamarinForms I encountered problems with Entry control.

### Description

When Entry is marked as a password and user starts interacting with it (like typing some data) it's not possible to interact with any other component on page. Navigation to different Pages don't work.

### Steps to Reproduce

1. Make a project with newest Xamarin.Forms.
2. Place two (or more) interactive components on Page.
3. Navigate to this Page.
4. Start typing in Entry marked as Password.
5. Try to "lost focus" on it.

### Expected Behavior

Anytime User interacts with any different control on page, Entry with password lost focus to make other interactions possible.

### Actual Behavior

Focus is stuck on Entry with password, user can't interact with other buttons/entries on Page. Navigation is stuck on Page with Entry.

### Basic Information

- Version with issue: 4.8.0.1451+372-sha.54a167945-azdo.4064655
- Last known good version: Everythin worked on IOS 13.X and Xamarin.Forms 4.7.X
- IDE: VisualStudio for Windows 16.7.5 | VisualStudio for MacOs (newest one)
- Platform Target Frameworks: 
  - iOS:  > 14
- Nuget Packages:
- Affected Devices: IPhone 11 with IOS > 14, simulator devices with IOS > 14

### Screenshots

![Screenshot_25](https://user-images.githubusercontent.com/39550133/95063076-25c41780-06fe-11eb-9753-c89b548d0f9c.png)

### Reproduction Link

Example Xaml:

```
<StackLayout Margin="0,0,0,20">

<Entry Placeholder="{x:Static resources:AppResources.Login}" x:Name="enLogin" IsPassword="False"  ReturnType="Next"></Entry>
<Entry Placeholder="{x:Static resources:AppResources.Password}" x:Name="enPass" IsPassword="True"  ReturnType="Done"></Entry>
</StackLayout>
```

### Workaround

Set IsPassword to false.

**Comment by jsuarezruiz** [comment] 2020-10-05 15:45
I have created a sample to try to reproduce the issue:
[Issue12345.zip](https://github.com/xamarin/Xamarin.Forms/files/5328388/Issue12345.zip)

But cannot reproduce it:
![issue12359](https://user-images.githubusercontent.com/6755973/95101107-178fee80-0732-11eb-9a37-3b7f696ccaf9.gif)

Tested with iOS 14 simulators and Xamarin.Forms 4.8 and 5.0-pre1. @tomsol432 Could you take a look to the sample?

**Comment by tomsol432** [comment] 2020-10-05 16:31
Hey, thanks for reply!

I think something went horribly wrong when I updated Xamarin.Forms in my project. I made a new project and everything works well. 

I found somewhat related problem at [stackoverflow](https://stackoverflow.com/questions/63486793/xamarin-forms-disable-auto-create-strong-password-on-login-page) - making a custom renderer solved my problem.

If you are interested in my project files I can strip all personal info from it and upload a sample tomorrow.

**Comment by wermino** [comment] 2020-10-06 13:45
I'm having the same exact issue, password entry gets stuck if IsPassword="True", once I type a char inside the password entry can't even close the soft keyboard
So far in my team 2 people face this issue, 1 iphone X ios 14, 1 iphone SE 2020 ios 14

**Comment by wermino** [comment] 2020-10-06 17:01
this sounds similar https://github.com/xamarin/Xamarin.Forms/issues/12246
changing the TextColor to make it slightly different for the Username and Password entries, actually worked, but issue then shows up on different iphones. aaaaaaah!

**Comment by jsuarezruiz** [comment] 2020-10-07 15:18
Ok, I'm going to close this issue to concentrate all the feedback on #12246.

**Closed by jsuarezruiz** 2020-10-07 15:18 UTC
Labels: a/entry, i/high, iOS 14, s/unverified, t/bug :bug:
