### ISSUE TITLE
[Bug] CollectionView's SelectedItems can't be bound to an ObservableCollection

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12008] opened 2020-09-02 20:06 UTC
Hi.

CollectionView's SelectedItems bindable property is of type `IList<object>`. If you try to assign say an `ObservableCollection<MyType>` it won't accept it, as the ObservableCollection implements `IList<MyType>` which can't be assigned into an `IList<object>`. Any reason why it's not just an IList without generic parameter?

So currently I can't find a way to feed it with any data, unless I write a ton of boilerplate code.

Thanks.

**Comment by hartez** [comment] 2020-09-02 20:25
@Tommigun1980 Which version of Xamarin.Forms are you using?

**Comment by hartez** [comment] 2020-09-02 20:30
@Tommigun1980 We've got a PR in progress for allowing arbitrary types for the SelectedItems: https://github.com/xamarin/Xamarin.Forms/pull/8323 (though it's been stalled for a bit).

**Comment by hartez** [comment] 2020-09-02 20:31
Closing as duplicate of issue #8155.

**Closed by hartez** 2020-09-02 20:31 UTC
Labels: s/unverified, t/bug :bug:
