### ISSUE TITLE
[Bug] Shell tab page on Android is destroyed when you select anothre tab

### ISSUE THREAD

**Issue by rayita** [xamarin/Xamarin.Forms#13869] opened 2021-02-25 19:13 UTC
### Description

When you shell tabed navigation, page is destroyed when you change to another tab, and recreated again when back to the tab.

iOS do not show this behavior, when you can back the page is in same state that when you leave.

### Steps to Reproduce

1.  Create a shell project whith tabbed page navigation
2. Create several tabs
3. Interact with one tab to alter the content
4. Select another tab an the return to the tab, tab it's created again

### Expected Behavior

You you return to a tab the page must be in same state that was when you leave.

### Actual Behavior

Tab pages are destroyed when you change tabs.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  14
  - Android:  11
  - UWP: N/A
- Android Support Library / AndroidX Version: /NA
- NuGet Packages: Xamarin.Forms
- Affected Devices: All

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019
Version 16.8.5
VisualStudio.16.Release/16.8.5+31005.135
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.8.559.8768
Azure App Service Tools v3.0.0

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2020.3.3   Build 203.0.20210128.162058
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.73
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   16.8.000.262 (d16-8@4d60f9c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.10.0.4 (5a05865f6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

**Comment by StephaneDelcroix** [comment] 2021-03-01 09:24
not sure it qualifies as a bug, but it's probably more by design... your view model is probably maintained, and, if designed correctly, your view will be recreated as it was...

**Comment by rayita** [comment] 2021-03-01 10:57
I think that must be considered a bug.

For instance, some controls like CollectionView or a ScrollView with a large text, once they are scrolled by user, lost the scroll position when their renderers are recreated. There is no way to track this in view model you need to "patch" this in the code behind because user will expect to have the control in same position when return to the page,
This is not happenig in iOS just Android, so I will need to code different solutions in code behind for both operating systems to just "workaround" this behavior, and in some cases (like ColecctionViews) there is not a perfect solution.
No, definitely I think that is a bug, if not bug, it's a really poor definition (and documentation) of shell tab page behavior. It is really silly to define a behavior (the one  user expect) for iOS and another one entirely different (the one user don't expect) for Android.

**Comment by dmariogatto** [comment] 2021-03-02 00:23
@StephaneDelcroix @rayita 

This seems to be the same issue as described in #8795 & #11738.

This prevents me from using Shell on Android. I have a map in one of my tabs and having that reload every time and lose it's UI state (i.e. the last scrolled to position) is not a great user experience, plus it's slow. I can confirm that the view model is not recreated.

**Comment by rayita** [comment] 2021-03-02 02:01
> @StephaneDelcroix @rayita
> 
> This seems to be the same issue as described in #8795 & #11738.
> 
> This prevents me from using Shell on Android. I have a map in one of my tabs and having that reload every time and lose it's UI state (i.e. the last scrolled to position) is not a great user experience, plus it's slow. I can confirm that the view model is not recreated.

Yes, neither the page it self or the view model  are recreated, just all page elements renderers are destroyed and recreated again.

I have same issue than yuo, a have tabs with collections and scroll and a map. It's a real pain because the map must be recreated and reloaded, but just in Android.

**Comment by PureWeen** [comment] 2021-03-02 23:38
Closing as duplicate

**Closed by PureWeen** 2021-03-02 23:38 UTC
Labels: s/unverified, t/bug :bug:

**Comment by rayita** [comment] 2021-03-30 05:34
> Closing as duplicate
> 
> We are aware of this issue and will hopefully have a solution for this with MAUI or soon after MAUI

That is a relly long time :(

**Comment by ianthetechie** [comment] 2021-06-14 12:18
Bump? @PureWeen can we get a link to the relevant tracking issue? What's MAUI?
