### ISSUE TITLE
[Bug] Android : Shell Toolbar/NavBar overlap content of pushed Page

### ISSUE THREAD

**Issue by PTEC3D50** [xamarin/Xamarin.Forms#7378] opened 2019-09-04 11:20 UTC
### Description
Shell Toolbar/NavBar overlap content of pushed page

### Steps to Reproduce

1. Create new Shell Xamarin Forms Project
2. Buid & Run
3. Select First Item (navigate to ItemDetailPage) => Top of Page ItemDetailPage is hidden under toolbar/navbar

### Expected Behavior
Content of the Page should not be hidden by toolbar/navbar

### Actual Behavior
Content of the Page is hidden by toolbar/navbar

### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forms 4.1.0.709244
- IDE: Visual Studio 2019 15.9.13
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 9.0
  - UWP:  not tested
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.2.0.709249 (still KO in Xamarin.Forms 4.3.0.1099-nightly)

- Affected Devices: OnePlus 5T & Samsung Galaxy S8 

### Screenshots

![image](https://user-images.githubusercontent.com/54659630/64249897-0f54f680-cf15-11e9-9844-60c1c28a150c.png)

### Reproduction Link
[ContentUnderToolbar.zip](https://github.com/xamarin/Xamarin.Forms/files/3574236/ContentUnderToolbar.zip)

**Comment by BrunoLogan** [comment] 2019-09-04 13:46
I'm experiencing the same behavior in iOS.

Information: 
Microsoft Visual Studio Community 2019
Version 16.2.3
VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Version 4.7.03190

Xamarin   16.2.0.95 (d16-2@37df81894)
Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Xamarin Templates   16.3.117 (59a59e8)
Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)

**Comment by samhouts** [comment] 2019-09-04 17:21
Duplicate of #7240

**Closed by samhouts** 2019-09-04 17:21 UTC
Labels: a/shell :shell:, i/regression, p/Android, p/iOS 🍎, s/unverified, t/bug :bug:
