### ISSUE TITLE
Xamarin Forms Shell.TabBarBackgroundColor

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14824] opened 2021-11-03 00:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Forms-ShellTabBarBackgroundColo/1545143)._

---
[regression] [worked-in:8.10.10 (Build 8)]
TabBar background colour always transparent.  Android fine.  Code hasn't changed for two years just the latest update.

Help.

---
#### Feedback Bot on 10/5/2021, 08:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2021-11-03 09:31
If the original author happens to read this: this should be fixed in the latest service release. It was caused by changes in iOS 15 that we needed to add some code for. If this is not the case, please feel free to ping me here with more details or open a new issue on this repository. Thanks!

**Closed by jfversluis** 2021-11-03 09:31 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/shell :shell:, s/unverified, a/tabbedpage
