### ISSUE TITLE
Pull to refresh doesn't work if iOS 11 large titles is enabled

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#1905] opened 2018-02-16 21:19 UTC
### Description
Pull to refresh doesn't work if iOS 11 large titles is enabled. If I disable large titles it works.

### Steps to Reproduce

Implement large titles like in my blog post, http://danielhindrikes.se/xamarin/ios-11-large-titles-in-xamarin-forms-apps/

### Expected Behavior
Listview to refresh

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 2.5.0.280555
- IDE: Visual Studio for mac 7.3.3
- Platform Target Frameworks: 
  - iOS:  11.2
  
- Affected Devices: iPhone simulator

**Comment by kevtiq** [comment] 2018-02-28 15:11
Might be helpful information. I have the same issue on a page with preferslargetitles on (within a customrenderer for adding the UISearchController to the navigation). When I click on one of the items in the list, I get redirected to a new page (intended behavior). However, when I use the backbutton to go back to the listview, Pull-to-Refresh is working on the page.

**Comment by rmarinho** [comment] 2018-03-01 12:17
@kevtiq can you tri this package see if it helps .. 
[win-5.zip](https://github.com/xamarin/Xamarin.Forms/files/1771093/win-5.zip)

**Comment by kevtiq** [comment] 2018-03-01 13:32
@rmarinho I used the Xamarin Forms package in my app but it does not resolve the issue :( Still on the initial load of the page, pull to refresh is not working.

**Comment by JCCP3** [comment] 2018-04-10 08:43
@kevtiq you should set refreshControl in viewDidAppear

**Comment by samhouts** [comment] 2018-05-08 23:35
closed by #1984

**Closed by samhouts** 2018-05-08 23:35 UTC
Labels: p/iOS, t/bug :bug:
