### ISSUE TITLE
[Bug] System.TypeLoadException: 'VTable setup of type Xamarin.Forms.Forms+AndroidPlatformServices failed'

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#11157] opened 2020-06-22 08:06 UTC
### Description

After updating from XF 4.6 SR4 to 4.7.0, the Android app stops with `TypeLoadException`

`System.TypeLoadException: 'VTable setup of type Xamarin.Forms.Forms+AndroidPlatformServices failed'`

### Steps to Reproduce

1. update XF from 4.6.0.967 to 4.7.0.968
2. run app

### Expected Behavior

app runs fine

### Actual Behavior

app crashes with System.TypeLoadException at `global::Xamarin.Forms.Forms.Init(this, bundle);`

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version:
- IDE: VS2019 16.6
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices: Android 7.1, Android 10 (Emulator, Pixel 3a)

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/85263234-27c7da80-b46f-11ea-9d85-cb3c6de7bf0c.png)

During research I found [this topic on stackoverflow](https://stackoverflow.com/q/62447717), which shows the same error.

App is not using Shell, it uses NavigationPage.

### Workaround

use `packages.config` instead of `PackageReference Include`, here the app works fine with XF4.7.

**Comment by cas8180** [comment] 2020-06-22 20:58
I am getting the same bug just on iOS
    at com.xxx.mobile.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication uiApplication, Foundation.NSDictionary launchOptions) [0x00017] in C:\Users\cas81\Documents\GitHub\com.xxx.mobile\Notouch Mobile.iOS\AppDelegate.cs:36 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.0.22/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.0.22/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at com.lazlo326.notouch.mobile.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\cas81\Documents\GitHub\com.xxx.mobile\Notouch Mobile.iOS\Main.cs:12

**Comment by samhouts** [comment] 2020-06-23 15:46
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by cas8180** [comment] 2020-06-23 17:17
I was able to repro it by creating a new project. Just set the iOS project as your startup project and run on a iOS 13.5 simulator. I used iPhone 11
[DebugXF47.zip](https://github.com/xamarin/Xamarin.Forms/files/4820886/DebugXF47.zip)

**Comment by MagicAndre1981** [comment] 2020-06-25 10:07
today the app works.

I cloned a new working copy (without commiting the XF upgrade from 4.6 to 4.7), updated SfDataGrid from 18.1.0.57 to 18.1.0.59, got now System.MissingMethodException with message that Xamarin.Forms.Internals.Registrar.RegisterStylesheets(Xamarin.Forms.InitializationFlags) was missing, which is expected as it was added in 4.7 (and syncfusion still compiles against 3.6), so I also updated XF from 4.6 to 4.7 and now the app starts.

So this is somehow a build tooling issue.

**Comment by samhouts** [comment] 2020-06-26 20:29
Duplicate of #10785

**Closed by samhouts** 2020-06-26 20:29 UTC
Labels: 4.7.0, i/high, i/regression, p/Android, p/iOS 🍎, s/unverified, t/bug :bug:

**Comment by thedee** [comment] 2020-07-02 04:00
Application crashes in release mode but not debug mode for Android.  We are on Xamarin.Forms 4.6.0.967.  Logcat shows:

```
android.runtime.JavaProxyThrowable: System.TypeLoadException: VTable setup of type Xamarin.Forms.Forms+AndroidPlatformServices failed
  at Xamarin.Forms.Forms.Init (Android.Content.Context activity, Android.OS.Bundle bundle) [0x0002e] in <d12be6fea8ff46ae816f5b18676473d5>:0 
  at RPT.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00032] in <10e40b3150e445a2bf0bfe4c242ce9bc>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <eaa205f580954a64824b74a79fa87c62>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.20(intptr,intptr,intptr)
	at crc645841afa52016fd7b.MainActivity.n_onCreate(Native Method)
	at crc645841afa52016fd7b.MainActivity.onCreate(MainActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
