### ISSUE TITLE
[Bug] ContentPage Height Wrong when used in Shell if child is a Grid that contains a full heigh ScrollView on iOS

### ISSUE THREAD

**Issue by lachlanwgordon** [xamarin/Xamarin.Forms#7690] opened 2019-09-26 11:28 UTC
### Description
When using Shell as MainPage, with a bottom TabBar and NavigationBar visible. If a ContentPage has the RootElement as a Grid, the grid has a ScrollView as a Child which fills the whole height(i.e. ScrollView's RowSpan is same as total number of rows).

The ContentPage's Height extends to the full height of the phone behind the NavigationBar and the TabBar. 

This bug appears on iOS but not on Android. Tested on iOS 13 on iPhone 11(with notch) and iPhone 7(no notch) with latest XF4.3 Preview and with 4.2 Stable. 

Repro link provided below shows a content page showing the bug on the first tab and a behaving correctly on the second tab.

### Steps to Reproduce

1. File>New>XamarinForms Shell App
2. Add this snippet 
```
<Tab Title="Bug Page">
            <ShellContent Title="Page 2">
                <ContentPage Title="Page 2">
                    <Grid>
                        <ScrollView
                            >
                            <StackLayout/>
                        </ScrollView>
                        <BoxView BackgroundColor="Lime" Margin="20"/>
                    </Grid>
                </ContentPage>
            </ShellContent>
        </Tab>
```
3. Run on iOS Device or Simulator
4. You will see that the BoxView is not inset 20dp as expected.

### Expected Behavior
ContentPage's content appears within the area below the NavBar and above the TabBar
### Basic Information

- Version with issue: 4.3 and 4.2
- Last known good version: none
- IDE:VS for Mac 8.3 (Build 1805)
- Platform Target Frameworks: 
  - iOS:  13.2.0.42 
- Nuget Packages:
- Affected Devices: iPhone 8, iPhone 11

### Screenshots
This Previewer screen shot shows a BoxView with a margin of 20 on all side correctly inset on Sides but not visible at top and bottom.
![Screen Shot 2019-09-26 at 7 54 34 pm](https://user-images.githubusercontent.com/29908924/65679037-b3a30680-e097-11e9-99be-564622a3cbf9.png)

### Reproduction Link
https://github.com/lachlanwgordon/ShellScrollViewMarginIssueRepro

**Comment by lachlanwgordon** [comment] 2019-09-26 11:52
Playing around a little more, the details about it having to cover full height aren't quite correct but the repro steps above still show the issue.

I think the content page grows whenever there is a scrollview inside a grid inside a page in a shell.

**Comment by PureWeen** [comment] 2019-10-02 20:10
@lachlanwgordon So this is an interesting one :-)

This is basically all caused by Shell just trying to guess what it should do with the insets. When you have a scrollview as part of the layout it assumes you are going to want the behavior where the scroll view goes under the appbar/tabbar. This behavior is what enables things like large titles and visual changes of the appbar. So when there is a ScrollView the code just let's iOS take over on the insets

If you still want the page to inset based on the notch then you need to tell the page to use Safe area insets

Here are two tabs where you can compare

```XAML
 <Tab Title="Bug Page 1">
            <ShellContent Title="Page 1">
                <ContentPage Title="Page 2">
                    <Grid>
                        <ScrollView>
                            <StackLayout/>
                        </ScrollView>
                        <BoxView BackgroundColor="Lime" Margin="20"/>
                    </Grid>
                </ContentPage>
            </ShellContent>
        </Tab>
        <Tab Title="Bug Page 2">
            <ShellContent Title="Page 2">
                <ContentPage Title="Page 2" ios:Page.UseSafeArea="true">
                    <Grid>
                        <ScrollView>
                            <StackLayout/>
                        </ScrollView>
                        <BoxView BackgroundColor="Lime" Margin="20"/>
                    </Grid>
                </ContentPage>
            </ShellContent>
        </Tab>
```

I'm going to close this for now. Let me know if you still think there's a bug here

**Closed by PureWeen** 2019-10-02 20:10 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:

**Comment by lachlanwgordon** [comment] 2019-10-14 21:38
Excellent, thank @PureWeen this fixed my problem. It's useful to know I've got a choice between behaviours on iOS.
