### ISSUE TITLE
Entry Border color can not be changed

### ISSUE THREAD

**Issue by akarthikraja18** [xamarin/Xamarin.Forms#5273] opened 2019-02-15 12:52 UTC
### Description
We have used  Entry control in  Xamarin.Forms. We need to change Entry border color but can't find any property or method to change. 
### Steps to Reproduce

1. Run the attached sample Entry sample,  
2.I have changed Text and Background Color, but text border color remains black
Please suggest a way to change border color.    

### Expected Behavior
Need to change entry border color in Xamarin.Forms (Android,iOS ,UWP)

### Actual Behavior
Can't find anything related to change entry border color.

### Basic Information
- Version with issue: Xamarin.Forms : 3.1.0.687729
- Last known good version: Don't Know
- IDE: Visual Studio 2017

### Reproduction Link

[EntryRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2869252/EntryRenderer.zip)

**Comment by samhouts** [comment] 2019-02-15 21:09
Duplicate of #1695

**Closed by samhouts** 2019-02-15 21:09 UTC
Labels: t/bug :bug:
