### ISSUE TITLE
Compiled Bindings does not work with Inherited Generic Interfaces

### ISSUE THREAD

**Issue by inforithmics** [xamarin/Xamarin.Forms#5651] opened 2019-03-21 10:31 UTC
### Description

Compiled Bindings does not work with Inherited Generic Interfaces

 ```
public interface IViewModel : IEditViewModel<string>{}

 public interface IEditViewModel<T> : IBaseViewModel<T>{}

 public interface IBaseViewModel<T>
 {
     T SelectedItem { get; set; }
 }
```

The SelectedItem  is not found in IViewModel and causes a Object reference not set to an instance of an object exception.

Removing IEditViewModel from the inheritence hierarchy makes the program to compile

### Steps to Reproduce

1. 

Interfaces

 ```
public interface IViewModel : IEditViewModel<string>{}

 public interface IEditViewModel<T> : IBaseViewModel<T>{}

 public interface IBaseViewModel<T>
 {
     T SelectedItem { get; set; }
 }
```
[App25.zip](https://github.com/xamarin/Xamarin.Forms/files/2991638/App25.zip)

View Model

 ```
public class ViewModel : IViewModel
    {
        public ViewModel()
        {            
            this.SelectedItem = "Hello from Generic Property";
        }

        public string SelectedItem { get; set; }
    }
```

XAML
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App25"
             x:Class="App25.MainPage"
             x:DataType="local:IViewModel">

    <StackLayout>
        <!-- Place new controls here -->        
        <Label Text="{Binding SelectedItem}" 
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" />
        </StackLayout>    
</ContentPage>
```
Code Behind
```
 [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {               
            InitializeComponent();                        
            this.BindingContext = new ViewModel();
        }
    }
```

2. 

Compile Project ->
Object reference not set to an instance of an object.

3. 

### Expected Behavior
Does compile and work
### Actual Behavior
Does not compile
### Basic Information

- Version with issue: 4.0.0 pre7
- Last known good version: None
- IDE: Visual Studio 2017 15.9.9
- Platform Target Frameworks: 
  - iOS:  12.1 
  - Android: 8.1
  - UWP:  16299 
- Android Support Library Version: v28.0.0.1
- Nuget Packages: Xamarin Forms 4.0.0 pre7

### Reproduction Link

[App25.zip](https://github.com/xamarin/Xamarin.Forms/files/2991642/App25.zip)

**Comment by samhouts** [comment] 2019-03-22 22:19
Duplicate of #5486

**Closed by samhouts** 2019-03-22 22:19 UTC
Labels: a/Xaml </>, a/binding ⛓, t/bug :bug:
