### ISSUE TITLE
[Bug] Updating CollectionView in CarouselView causes error on iOS.

### ISSUE THREAD

**Issue by StevenGranados** [xamarin/Xamarin.Forms#7006] opened 2019-07-29 15:54 UTC
### Description
I have a CollectionView within a CarouselView within a Content Page.
The CollectionView is bound to an ObservableCollection within a ViewModel.
Clicking a button to add to the ObservableCollection crashes in iOS.
Works with ListView,
Works in Android.

- Version with issue: 4.1.0.618606
- Last known good version: N/A
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  12.2
- Affected Devices:iPhone 8

### Reproduction Link
[CarouselViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3443102/CarouselViewTest.zip)
### Full Error

 *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.103.12/UICollectionView.m:6165

Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).
Native stack trace:
	0   CoreFoundation                      0x000000010d5ba6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e2c9ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d5ba482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000109a60927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x0000000116ed6479 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 16127
	5   UIKitCore                           0x0000000116ed2239 -[UICollectionView _updateRowsAtIndexPaths:updateAction:updates:] + 519
	6   UIKitCore                           0x0000000116ed22c4 -[UICollectionView insertItemsAtIndexPaths:] + 64
	7   CarouselViewTest.iOS                0x0000000100446eb9 xamarin_dyn_objc_msgSend + 217
	8   ???                                 0x0000000132a18ab8 0x0 + 5144414904
'

**Comment by samhouts** [comment] 2019-07-29 23:07
Duplicate of #6620

**Closed by samhouts** 2019-07-29 23:07 UTC
Labels: s/unverified, t/bug :bug:
