### ISSUE TITLE
[Bug] IsClippedToBounds="True" iOS not work

### ISSUE THREAD

**Issue by ChipiCoding** [xamarin/Xamarin.Forms#11120] opened 2020-06-18 20:38 UTC
**Description**
IsClippedToBounds="True" does not work in iOS

**Steps to Reproduce**

1.  Create Page
2. Add frame with corner radius = 10
3. Add Grid wit 2 rows
4. In row = 1, add 2 buttons with corner radius = 0

**Expected Behavior**
No crashes

**Actual Behavior**
Crashes

Basic Information

- Version with issue:  4.7.0.968
- Last known good version: 4.6.0.800
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS: Xamarin.iOS Version: 13.18.1.31

`<?xml version="1.0" encoding="UTF-8"?>
<popup:PopupPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="App.ConfirmationDialog"
    xmlns:popup="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup">

    <Frame
        IsClippedToBounds="True">

        <Frame.Resources>
            <ResourceDictionary>
                <Style
                    TargetType="Frame">
                    <Setter Property="BackgroundColor" Value="WhiteSmoke"/>
                    <Setter Property="CornerRadius" Value="10"/>
                    <Setter Property="HasShadow" Value="False"/>
                    <Setter Property="HorizontalOptions" Value="FillAndExpand"/>
                    <Setter Property="Margin" Value="40"/>
                    <Setter Property="Padding" Value="20"/>
                    <Setter Property="VerticalOptions" Value="Center"/>
                </Style>  
            </ResourceDictionary>
        </Frame.Resources>

        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            
            <Label
                FontFamily="{StaticResource TradeGothicLTBold}"
                FontSize="Subtitle"
                HorizontalOptions="Center"
                HorizontalTextAlignment="Center"
                Text="..."
                VerticalOptions="Center"/>

            <Grid
                Grid.Row="1"
                ColumnSpacing="0"
                Padding="-20, 20, -20, -20">
            
                <Grid.RowDefinitions>
                    <RowDefinition Height="50"/>
                </Grid.RowDefinitions>

                <Button
                    BackgroundColor="{StaticResource MainBlue}"
                    CornerRadius="0"
                    Grid.Column="1"
                    Text="YES"/>

                <Button                   
                    BackgroundColor="{StaticResource GrayColor}"
                    CornerRadius="0"
                    Text="NO"/>

            </Grid>
        </Grid>
    </Frame>

</popup:PopupPage>
`

### Screenshots

Failed
![image](https://user-images.githubusercontent.com/8869059/85069047-103fd780-b179-11ea-90c5-7556a86fdcf5.png)

OK
![image](https://user-images.githubusercontent.com/8869059/85069058-159d2200-b179-11ea-9ef2-19e194af4a7b.png)

**Comment by CarrotSolutions** [comment] 2020-06-18 23:10
Confirmed!  So glad someone else experienced the same thing!  I also confirmed no problem on Android just in iOs.  So is the workaround to roll back?

**Comment by StephaneDelcroix** [comment] 2020-06-19 09:42
Duplicate of #11091

**Closed by StephaneDelcroix** 2020-06-19 09:42 UTC
Labels: a/frame, e/2 :clock2:, i/high, i/regression, p/iOS 🍎, t/bug :bug:
