### ISSUE TITLE
"NullReferenceException" in "Xamarin.Forms.Platform.iOS.Renderers.LabelRenderer.cs" within "UpdateText()" & "UpdateTextColor()"

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1435] opened 2017-12-20 01:17 UTC
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=59813

### Description
It happens within a list view which gets cyclically updated every second if it is visible. 
The list view only contains labels with different colors and is part of a child page within a carousel page.

It happens when swiping into the child page containing the list view (The list view has been updated with new items shortly before).

Proposed Fixes:
https://github.com/xamarin/Xamarin.Forms/pull/1216
https://github.com/xamarin/Xamarin.Forms/pull/1226
https://github.com/xamarin/Xamarin.Forms/pull/1244 

### Basic Information

- Version with issue: 2.4.0.280, 2.5.0.77107
- Last known good version: 2.3.5.239-pre3

### Reproduction Link

[XamarinBugzillaBug59813.zip](https://github.com/xamarin/Xamarin.Forms/files/1573815/XamarinBugzillaBug59813.zip)

**Comment by MitchBomcanhao** [comment] 2017-12-22 10:45
We have these in a different scenario.

Master/detail page with a tabbed page.
Three tabs, each with their own listview, sources are observable collections.
Listviews are grouped and have uneven rows.

Selecting an item from one of the listviews will navigate to another page, and that page will offer controls that can cause the items in the listview to change its data.
This will SOMETIMES cause the app to crash with a NRE in the iOS LabelRenderer, as it attempts to access properties in a null Control. 

There are various methods in LabelRenderer that can fail as they do not check for Control being null.
Overriding the LabelRenderer and doing null checks for Control before trying to set its properties prevents the NRE. With the override, when going back to the listview page the item appears to have been updated correctly.

This is still happening on 2.5.0.122203 (sr3)

**Comment by rmarinho** [comment] 2018-01-03 12:46
@davidortinau can you check if this if fixed with latest nightly .

**Comment by rmarinho** [comment] 2018-01-09 14:49
@MitchBomcanhao can you upload a small reproduction ? 
Thanks

**Comment by ThumbGen** [comment] 2018-01-09 15:49
See original bugzilla issue for a detailed discussion (AFAIK there's a repro project there too).

[LINK](https://bugzilla.xamarin.com/show_bug.cgi?id=59813)

**Comment by MitchBomcanhao** [comment] 2018-01-09 17:04
@rmarinho 
Was off for a few days, just saw your mention.

using a nightly build isn't a straightforward swap as the newer packages have moved on to .netstandard and seems like a decent chunk of work to replace 2.5.0 in our portable project with the current nightly (unless we're missing something obvious?). 

Regarding a repro project, I'll bring this up to the team, but I expect the amount of time trying to reproduce the issue when its workaround has been effective so far will be a likely impediment for our small team.

sorry I haven't much to add right now - this is surely something we want to see/help get fixed...
Will post an update when I have something to add.
Thanks

**Comment by rmarinho** [comment] 2018-01-09 17:39
Not being able to reproduce this issue, or run the sample .

**Comment by jamesatgithub** [comment] 2018-01-10 05:48
[XFBugShowDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/1617645/XFBugShowDemo.zip)
@rmarinho we encountered same bug in XF 2.4 and 2.5. attached is a demo with two list, clicking left list item will refresh the right one, if you keep refreshing and then click the item in right one, you'll see the crash

**Comment by farcasclaudiu** [comment] 2018-01-11 17:52
This sample will repro easily this issue
https://1drv.ms/u/s!ADs3KP_7p6sPifI2

In the cell template we have a boxview with a tap gesture that seems to cause the issue. 
Still I don't know a fix for this :(

```
<BoxView >
  <BoxView.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding SomeCommand}"></TapGestureRecognizer>
  </BoxView.GestureRecognizers>
</BoxView>
```

**Comment by rmarinho** [comment] 2018-01-11 18:48
@jamesatgithub thanks i can repro with that..

**Comment by rmarinho** [comment] 2018-01-11 19:05
@jamesatgithub if you remove Fody, does the issue still happens ?

**Comment by rmarinho** [comment] 2018-01-11 19:13
```
public class MainPage1 : ContentPage
		{
			public MainPageModel ViewModel { get { return this.BindingContext as MainPageModel; } }

			public MainPage1()
			{
				this.Title = "XFBugShow";
				SetThisViewUIsFunc();
			}

			private void SetThisViewUIsFunc()
			{
				ListView leftList = new ListView(ListViewCachingStrategy.RetainElement)
				{
					HasUnevenRows = true,
					RowHeight = 44,
					IsPullToRefreshEnabled = false,
					SeparatorVisibility = SeparatorVisibility.None,
					HorizontalOptions = LayoutOptions.FillAndExpand,
				};
				leftList.ItemTapped += LeftList_ItemTapped;
				leftList.ItemTemplate = new DataTemplate(typeof(CustomCell));
				leftList.SetBinding(ListView.ItemsSourceProperty, nameof(ViewModel.LeftList), BindingMode.TwoWay);

				ListView rightList = new ListView()
				{
					HasUnevenRows = true,
					IsPullToRefreshEnabled = false,
					SeparatorVisibility = SeparatorVisibility.None,
					HorizontalOptions = LayoutOptions.FillAndExpand,
				};

				rightList.ItemTemplate = new DataTemplate(typeof(CustomCell));
				rightList.ItemTapped += RightList_ItemTapped;
				rightList.SetBinding(ListView.ItemsSourceProperty, nameof(ViewModel.RightList), BindingMode.TwoWay);

				Content = new StackLayout
				{
					Orientation = StackOrientation.Horizontal,
					Children =
				{
					leftList,rightList
				}
				};
			}

			private void RightList_ItemTapped(object sender, ItemTappedEventArgs e)
			{
				var item = e.Item as PivotItemModel;
				item.SelectedColor = Color.Green;
				foreach (var newItem in ViewModel.RightList)
				{
					if (newItem.Id != item.Id)
					{
						newItem.SelectedColor = Color.Blue;
					}
				}
			}

			private void LeftList_ItemTapped(object sender, ItemTappedEventArgs e)
			{
				ViewModel.RightList.Clear();
				var item = e.Item as PivotItemModel;
				item.SelectedColor = Color.Green;
				foreach (var newItem in ViewModel.LeftList)
				{
					if (newItem.Id != item.Id)
					{
						newItem.SelectedColor = Color.Blue;
					}
				}
				ViewModel.InitRightDatas();
			}
		}
		public class CustomCell : ViewCell
		{

			private Image iconImage;
			private Label titleLabel;

			public CustomCell()
			{
				iconImage = new Image()
				{

				};
				iconImage.SetBinding(Image.SourceProperty, "IconImg");

				titleLabel = new Label()
				{

				};
				titleLabel.SetBinding(Label.TextProperty, "TitleStr");
				titleLabel.SetBinding(Label.TextColorProperty, "SelectedColor");

				View = new StackLayout()
				{
					Orientation = StackOrientation.Horizontal,
					Children = { iconImage, titleLabel }
				};
			}
		}
		
		public class MainPageModel
		{
			public ObservableCollection<PivotItemModel> LeftList { get; set; }
			public ObservableCollection<PivotItemModel> RightList { get; set; }


			public MainPageModel()
			{

				LeftList = new ObservableCollection<PivotItemModel>();
				RightList = new ObservableCollection<PivotItemModel>();
				InitLeftDatas();
				InitRightDatas();
			}
			public void InitLeftDatas()
			{
				for (int i = 1; i < 10; i++)
				{
					LeftList.Add(new PivotItemModel { Id = i, SelectedColor = Color.Red, TitleStr = "TestLeftListVStr" });
				}
			}
			public void InitRightDatas()
			{
				for (int i = 1; i < 10; i++)
				{
					RightList.Add(new PivotItemModel
					{
						Id = i,
						SelectedColor = Color.Red,
						TitleStr = "TestRightListVStr",
						IconImg = "Icon.png"
					});
				}
			}
		}
		public class PivotItemModel
		{
			public Color SelectedColor { get; set; }
			public int? Id { get; set; }
			public string TitleStr { get; set; }
			public ImageSource IconImg { get; set; }
		}
```

**Comment by rmarinho** [comment] 2018-01-11 19:14
this Works just fine.

**Comment by farcasclaudiu** [comment] 2018-01-11 19:32
Updated link for sample : https://1drv.ms/u/s!Ajs3KP_7p6sPifI2h-5igH-JN782tw

**Comment by btrdurfee** [comment] 2018-01-11 21:42
I agree with @farcasclaudiu - I can repro this error when using an Image with a GestureRecognizer attached and HasUnevenRows is true. If I set HasUnevenRows to false, then it works but the UI is messed up. Or if I remove the GestureRecognizer, then it works. As a workaround, instead of an image tapped gesture, I am using the list view itemselected command. In this particular case, I can do this, but this bug needs to be fixed.

**Comment by jamesatgithub** [comment] 2018-01-12 03:44
@rmarinho yes removing Fody seems OK. But we used Fody heavily in our project since 2.3 and it worked fine but started getting crash since 2.4 and 2.5

**Comment by kntiwary** [comment] 2018-01-12 10:13
{System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateText () [0x00070] in <c95050a8f6d640e8927ac3f95b517dff>:0 
  at Xamarin.Forms.Platform.iOS.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00097] in <c95050a8f6d640e8927ac3f95b517dff>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:137 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:388 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:593 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:390 
  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:174 
  at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) [0x0006b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:77 
  at Xamarin.Forms.Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) [0x00042] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Binding.cs:126 
  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext) [0x0003b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:421 
  at Xamarin.Forms.BindableObject.ApplyBindings () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:125 
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x0005a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:119 
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:498 
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:341 
  at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\View.cs:99 
  at Xamarin.Forms.Grid.OnBindingContextChanged () [0x00006] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Grid.cs:139 
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:120 
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:498

**Comment by kntiwary** [comment] 2018-01-12 10:14
Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateText () [0x00070] in <c95050a8f6d640e8927ac3f95b517dff>:0 
  at Xamarin.Forms.Platform.iOS.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00097] in <c95050a8f6d640e8927ac3f95b517dff>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:137 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:388 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:593 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:390 
  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:174 
  at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) [0x0006b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:77 
  at Xamarin.Forms.Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) [0x00042] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Binding.cs:126 
  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext) [0x0003b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:421 
  at Xamarin.Forms.BindableObject.ApplyBindings () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:125 
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x0005a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:119 
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:498 
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:341 
  at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\View.cs:99 
  at Xamarin.Forms.Grid.OnBindingContextChanged () [0x00006] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Grid.cs:139 
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:120 
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:498 
  at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00008] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TemplatedView.cs:65 
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:341 
  at Xamarin.Forms.View.OnBindingContextChanged () [0x00042] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\View.cs:99 
  at Xamarin.Forms.ContentView.OnBindingContextChanged () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\ContentView.cs:16 
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) [0x00060] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:120 
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:498 
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00021] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:341 
  at Xamarin.Forms.Cell.OnBindingContextChanged () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Cells\Cell.cs:114 
  at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x0000e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:441 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00108] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:596 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:390 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:543 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:83 
  at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:24 
  at Xamarin.Forms.Internals.TemplatedItemsList`2+<UnhookItem>d__154[TView,TItem].MoveNext () [0x000b0] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TemplatedItemsList.cs:1217 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.2.1.0/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
  at UIKit.UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/5481/12e80e01/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24 
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/5481/12e80e01/source/xamarin-macios/src/Foundation/NSAction.cs:163 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5481/12e80e01/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5481/12e80e01/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at Coronis.Mobile.GP.iOS.Application.Main (System.String[] args) [0x00002] in /Users/kamta/Coronis/Coronis.Mobile.GP/iOS/Main.cs:20

**Comment by kntiwary** [comment] 2018-01-12 10:16
I have been facing the same error in my project, when the refresh count exceeds three the app crashes. I can't downgrade the Xamarin.Forms to 2.3.* as there are other dependencies (Like Microcharts) This is a serious problem , that needs to be resolved.

**Comment by rmarinho** [comment] 2018-01-12 15:12
@farcasclaudiu ok can repo it, but tha's related with gesture, let's open a new bug for this #1567

**Comment by kntiwary** [comment] 2018-01-15 19:10
Any Progress @rmarinho

**Comment by kpronz** [comment] 2018-01-19 21:21
Hello.  I am experiencing the same issue in Xamarin Forms 2.5.0.122203.

**Comment by rmarinho** [comment] 2018-01-19 22:45
i think i found the issue https://github.com/xamarin/Xamarin.Forms/pull/1569

**Comment by kntiwary** [comment] 2018-01-21 17:04
@rmarinho  Is it fixed?

**Comment by kntiwary** [comment] 2018-01-30 21:15
@rmarinho  Looks Like this is not fixed list view crashes for count greater than 3. There's tap gesture 
 <Label.GestureRecognizers>
                                                                     <TapGestureRecognizer Tapped="PatientTransactionHistory" CommandParameter = "{Binding}" />
                                                                 </Label.GestureRecognizers></Label>

**Comment by ThumbGen** [comment] 2018-02-05 11:20
I have lost hope that this crash will ever be fixed :(

Xamarin.Forms 2.5.0.122203

- [LabelRenderer UpdateTextColor()]
System.NullReferenceException: Object reference not set to an instance of an object

Xamarin.Forms.Platform.iOS.LabelRenderer.UpdateTextColor()
Xamarin.Forms.Platform.iOS.LabelRenderer.OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
<Module>.invoke_void_object_PropertyChangedEventArgs(object, PropertyChangedEventArgs)(wrapper delegate-invoke)
Xamarin.Forms.BindableObject.OnPropertyChanged(string propertyName)
Xamarin.Forms.Element.OnPropertyChanged(string propertyName)
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, SetValueFlags attributes, bool silent)
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)
Xamarin.Forms.BindingExpression.ApplyCore(object sourceObject, BindableObject target, BindableProperty property, bool fromTarget)
Xamarin.Forms.BindingExpression.Apply(bool fromTarget)
Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__47_0()
Foundation.NSAsyncActionDispatcher.Apply()
UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
UIKit.UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate)
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)

**Comment by kntiwary** [comment] 2018-02-05 11:40
I have been waiting for this bug to be fixed. This is a major Bug

**Comment by davidortinau** [comment] 2018-02-07 20:59
Closed by #1216 #1226 #1244

**Comment by kpronz** [comment] 2018-02-12 20:32
I'm still seeing this issue in Xamarin.Forms v2.5.0.122203.  How do I get the version of code that this is fixed in?

Thanks.

**Comment by kntiwary** [comment] 2018-02-13 05:42
As  I matter of fact, I am also facing the same Issue. This has not been
resolved in the current build.

**Comment by ilkeSylmz** [comment] 2018-02-13 06:53
I am also having the same problem

**Comment by ThumbGen** [comment] 2018-02-13 08:19
Everybody has the exception, except the Xamarin guys :) The original bugzilla entry (opened in September 2017) was abandoned, now this issue too...

**Comment by ilkeSylmz** [comment] 2018-02-13 08:39
Just a workaround, modifying HasUnevenRows and CachingStrategy and additionally defining row height solves the problem, not a perfect solution though :)

**Comment by ThumbGen** [comment] 2018-02-13 08:50
The workaround is unfortunately not always feasible (same as using List instead of ObservableCollection which might also address the issue AFAIK)

**Comment by kntiwary** [comment] 2018-02-13 09:08
True, I already tried  adding row height and hasUneven low, it didn't
worked though. Moreover it impacts my UI design.

**Comment by ilkeSylmz** [comment] 2018-02-13 09:35
I got it solved but same here, it impacts the ui design.

**Comment by GamesAgeddon** [comment] 2018-02-13 13:09
Same here. Still struggling with this issue.

**Comment by runnerdev** [comment] 2018-02-13 21:37
I gave up on a fix for this issue and implemented a custom label renderer to protect against the app crashing by catching and ignoring the exception in overrides for both OnElementPropertyChanged and OnElementChanged.

Not ideal but so far the UI appears to render correctly without crashes.

**Comment by rmarinho** [comment] 2018-02-14 15:20
Can someone give me another repo to look?! @runnerdev @GamesAgeddon @ThumbGen   thanks

**Comment by runnerdev** [comment] 2018-02-14 15:37
I don't have an example available for access but this is the same as this new issue which does.
https://github.com/xamarin/Xamarin.Forms/issues/1795

**Comment by kntiwary** [comment] 2018-02-14 16:54
Yes, it's the same bug with different bug number.


On Feb 14, 2018 9:07 PM, "runnerdev" <notifications@github.com> wrote:

I don't have an example available for access but this is the same as this
new issue which does.
#1795 <https://github.com/xamarin/Xamarin.Forms/issues/1795>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xamarin/Xamarin.Forms/issues/1435#issuecomment-365645146>,
or mute the thread

**Comment by farcasclaudiu** [comment] 2018-02-14 17:05
Please have a look on my sample above,
> This sample will repro easily this issue
> https://1drv.ms/u/s!ADs3KP_7p6sPifI2
> ...
> ...

The issue is still happening :(

**Comment by uwantfries** [comment] 2018-02-15 12:32
I have also got this. I need uneven rows due to the nature of the data :( 
XF:2.5.0.122203 

Can we get fix for this plz?

**Comment by jassmith** [comment] 2018-02-16 22:19
Closing this issue and moving future discussion to #1795 which has a more up to date repro that hits master.

**Closed by jassmith** 2018-02-16 22:19 UTC
Labels: p/iOS, s/needs-info, s/needs-repro, s/reopened, t/bug
