### ISSUE TITLE
[Enhancement] Button - corner radius for all single corners

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8594] opened 2019-11-20 23:14 UTC
## Summary
Right now **Button** control has **CornerRadius** property which is always applied to all corners. It would be nice if there was the possibility to define the corner radius for all single corners.

## API Changes

Similar to margin and padding properties there should be a possibility to define corner radius for all corners, like this:
```
<Button CornerRadius="10,20,10,5"/> 
```
This will apply a corner radius of 10 to the top left corner, 20 to the top right corner, 10 to the bottom right corner and 5 to bottom left corner.

## Intended Use Case
A lot of use cases when creating beautiful UI.

**Comment by KSemenenko** [comment] 2019-11-21 15:36
It would be nice to do good rounding management. #7208

**Comment by samhouts** [comment] 2020-02-13 00:56
Duplicate of #1814

**Closed by samhouts** 2020-02-13 00:56 UTC
Labels: proposal-open, t/enhancement ➕
