### ISSUE TITLE
Prevent WebView Reload after switching the tab in Shell-Application on Android

### ISSUE THREAD

**Issue by ronnycsharp** [xamarin/Xamarin.Forms#15373] opened 2022-05-15 06:38 UTC
Hi,
I created a Shell-App with a Tab-Bar. 
On the first tab, I have a ShellContent with a WebView, which loads a complex web page.
If I switch the tab on iOS and get back to the first tab - everything is fine, the WebView is in the
same state and already loaded, but on Android, the whole WebView will be reloaded every time.
Is there a way to solve this or may be an other solution?

Kind regards
Ronny

**Comment by greg84** [comment] 2022-05-21 16:52
Think this is a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/9073

It's in the current backlog, but [no idea if/when it'll be fixed](https://github.com/xamarin/Xamarin.Forms/issues/9073#issuecomment-1091617310).

If you have a custom renderer for the WebView, remove it and it should fix the issue.

If you need the custom renderer, you might be able to put together a workaround. I've had to put in a load of hacky code that reloads the page and restores the original scroll position - it's a bit of mess!

**Comment by jfversluis** [comment] 2022-08-23 12:53
Duplicate of #9073

**Closed by jfversluis** 2022-08-23 12:53 UTC
