### ISSUE TITLE
[Bug] iOS CollectionView not updating VisualState on pre-selected items when loaded

### ISSUE THREAD

**Issue by MaxHampton** [xamarin/Xamarin.Forms#6967] opened 2019-07-24 19:50 UTC
### Description

I am using a CollectionView to handle multiple selection on a bound ItemsSource. The bindings work fine for both ItemsSource and SelectedItems. I am using a templated view for the cells in the CollectionView, and have set up VisualState Setters for both the Selected and Normal states in the CommonStates VisualStateGroup.

On Android, when the CollectionView loads, the VisualStates are applied correctly, and pre-selected items in the bound SelectedItems property are displaying as expected.

On iOS, when the CollectionView loads, the VisualStates are not applied correctly. When the first item in ItemsSource is selected, the VisualState is applied. Any other selected items do not get the Visual State style, but get the default selected style. When the first item in ItemsSource is not selected, all selected items get the default selected styling, and none get the VisualState style.

### Expected Behavior

Selected VisualState should behave the same on both platforms, with defined styles applied to selected cells when the CollectionView loads.

### Actual Behavior

Selected VisualState is not applied at load time to all selected items in the bound collection. This VisualState is not applied until the user interacts with the CollectionView by selecting another item, or scrolling the view.

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version: NA
- IDE: VS 2017 Enterprise
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by MaxHampton** [comment] 2019-07-24 21:40
When selected items are scrolled out of view, then scrolled back into view, while the scroll gesture is still occurring the style is the default CollectionView selected style. When the scroll gesture ends, the VisualState styles are applied.

**Comment by PureWeen** [comment] 2019-07-25 04:11
@MaxHampton this sounds like a duplicate of these
https://github.com/xamarin/Xamarin.Forms/issues/5563
https://github.com/xamarin/Xamarin.Forms/issues/5622#issuecomment-478171083

If your issues looks different than can you attach a repro and we can reopen

**Closed by PureWeen** 2019-07-25 04:11 UTC
Labels: s/unverified, t/bug :bug:

**Comment by MaxHampton** [comment] 2019-07-25 16:22
@PureWeen this isn't quite a duplicate of those tickets, but may be related. I'm attaching a screenshot to demonstrate the issue, I'll work on getting a repro together.

![IMG_0003blurred](https://user-images.githubusercontent.com/4153653/61891076-b4fc5b00-aebd-11e9-95bd-01e570cf4535.png)

**Comment by kajetangit** [comment] 2019-09-14 14:15
@PureWeen  I do not think it's a duplicate.
On iOS the issue can be replicated by adding the below to VerticalListMultiplePreSelectionPage.xaml
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos

```XML
<ContentPage.Resources>
    <Style TargetType="Grid">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal" />
                    <VisualState x:Name="Selected">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="Red" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>
</ContentPage.Resources>
```

When the page is loaded pre-selected elements have grey background color.
After selection is changed all selected elements have red background color.

**Comment by hunii** [comment] 2019-10-28 23:41
@PureWeen  Definitely not same as those tickets. Have you tested? This exist on iOS

**Comment by JeffTobin** [comment] 2019-12-20 15:14
having this problem as well in 4.4

**Comment by ValonK** [comment] 2020-02-12 12:56
also having this issue in 4.4

**Comment by Jzrzmy** [comment] 2020-03-03 16:11
Also having the issue in 4.5

**Comment by burakyigit** [comment] 2020-04-19 20:38
also having this issue in 4.5

Does anyone have a workaround?

**Comment by lucas-zimerman** [comment] 2020-07-21 22:04
Yeah it's happening in 4.8.0.
Pre selected item is marked with the default selected color, if you scroll it the color is then set to the VisualState Selected Color.
I also noticed that the Focused State doesn't seems to be working on ios

**Comment by astralmaster** [comment] 2020-08-09 18:42
A year later, not even a workaround?

**Comment by lucas-zimerman** [comment] 2020-08-14 20:33
> A year later, not even a workaround?

before I mark select the selected item I added a delay of 1ms, that seems to do the trick

**Comment by shalinasanga** [comment] 2020-08-20 04:18
why is this bug closed and even after a year we experiencing the issue.
programmatic scrolling, thread sleeps are not helping for me

**Comment by domagojmedo** [comment] 2020-09-23 08:59
@PureWeen @samhouts why is this closed when the issue is still not fixed?

**Comment by LeoJHarris** [comment] 2021-03-01 01:09
Still not fixed... programmatically preselecting a row item as the page is appearing/navigate to has no affect on the row color unless I select another item manually then color takes affect... android has no issues with this only iOS for me.

**Comment by justinasfour04** [comment] 2021-05-07 17:49
![image](https://user-images.githubusercontent.com/6599551/117488847-dd423600-af3a-11eb-954c-15d95fd2c5cf.png)
Not sure if this is also related but for some reason on iOS it doesn't recognize those properties and therefore doesn't do what I want

**Comment by adolfo1981** [comment] 2021-08-17 02:50
Can someone provide an alternative to show custom images based on Visual State for `CollectionView` items? E.g. show unchecked checkbox for non-selected and checked checkbox image for selected items.
