### ISSUE TITLE
[Bug] Forms 4.2 Shell Flyout is displayed when using TabBar on Android

### ISSUE THREAD

**Issue by aryobenholzner** [xamarin/Xamarin.Forms#7362] opened 2019-09-03 08:30 UTC
### Description

When using a shell with a TabBar and a few Tabs, on Android the Hamburger icon is still displayed and when clicked. Even when i set FlyoutBehaviour to Disabled. On iOS it works as desired.

This occurs since Xamarin Forms 4.2.

### Steps to Reproduce

1. Create a Shell with TabBar and a few Tabs
2. Update to Xamarin Forms 4.2

### Expected Behavior

Only the Tabs should be displayed

### Actual Behavior

The Flyout Hamburger menu is displayed and can be opened

### Basic Information

- Version with issue: 4.2
- Last known good version: 4.1
- Platform Target Frameworks: 
  - Android: 9

### Screenshots

<img width="814" alt="image" src="https://user-images.githubusercontent.com/52825527/64156769-b3677080-ce35-11e9-9dcc-06b5abd624bb.png">

### Reproduction Link

[tabbar.zip](https://github.com/xamarin/Xamarin.Forms/files/3568553/tabbar.zip)

**Comment by mjfreelancing** [comment] 2019-09-04 11:41
I am also experiencing this issue after upgrading to v4.2 and I cannot roll back as v4.1 has a show stopper defect.

**Comment by James3UK** [comment] 2019-09-05 13:51
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/7238

**Comment by samhouts** [comment] 2019-09-05 17:01
Duplicate of #7238

**Closed by samhouts** 2019-09-05 17:01 UTC
Labels: a/shell :shell:, i/regression, p/Android, s/unverified, t/bug :bug:
