### ISSUE TITLE
[Bug] Xamarin.Forms.Entry/Label does not diyplay decimal separator when binding a float to it.

### ISSUE THREAD

**Issue by nicolaiw** [xamarin/Xamarin.Forms#6069] opened 2019-05-02 11:37 UTC
### Description  
Hello guys,

I think i encountered a Bug with the Xamarin.Forms.Entry and the Xamarin.Forms.Label. This Bug seems to be culture/system language dependent. The Entry and Label does not show the decimal separator if I bind a float to it (system language de). The double and decimal values are displayed as expected (see screenshots below).  I did not found a similar Issue/duplicate. Sorry if I missed one.

### Steps to Reproduce  

[Sample repository](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel)

I created an empty new project with one xaml page. The corresponding ViewModel has three different properties. A float, a double and a decimal property as you can see in my uploaded sample.

[ViewModel](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel/blob/master/FloatEntryBug/FloatEntryBug/FloatEntryBugViewModel.cs)  

The corresponding xaml view contains a Label and an Entry for each of the mentioned properties.  

[View](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel/blob/master/FloatEntryBug/FloatEntryBug/MainPage.xaml)  

The BindingContext I set in the CodeBehind of the xaml view.

[CodeBehind](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel/blob/master/FloatEntryBug/FloatEntryBug/MainPage.xaml.cs#L20)  

This problem occures when the system language is set to de-DE. With e.g. en-US it seems to wok fine. 

Another issue is that, when system language is set to de-DE, the numeric keyboards separator key does not work. This seems to bee related to [#1898](https://github.com/xamarin/Xamarin.Forms/issues/1898).

### Expected Behavior  

Entry and Label shows decimal separator on binded float value.

### Actual Behavior  

Decimal separator is not shown on Entry and Label for the bound float.

### Basic Information

- Xamarin.Forms 3.6.0.344457

- IDE: VisualStudio Professional 2019 Version 16.0.1
- Platform Target Frameworks: Android 8.1
- iOS:  not tested
- Android Affected Devices
     Android 5.0 - API 21 (Samsung S4)
     Android 8.0 - API 26 (HUAWEI P Smart)
     Android 8.0 - API 26 (Galaxy Tab S3)
- UWP:  not tested
- Android Support Library Version: Xamarin.Android.Support.v4 28.0.0.1
- Nuget Packages: No **additional** Nuget Packages installed (Blank Xamarin Forms Template)

### Screenshots

de-DE
![alt tag](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel/blob/master/misc/Screenshot_de-DE.png "de-DE")

en-US
![alt tag](https://github.com/nicolaiw/XamarinFormsFloatEntryLabel/blob/master/misc/Screenshot_en-US.png "en-US")

### Reproduction Link

https://github.com/nicolaiw/XamarinFormsFloatEntryLabel

Please let me know if I could provide more information.

Best regards.

**Comment by kingces95** [comment] 2019-05-02 22:52
![image](https://user-images.githubusercontent.com/4120386/57111765-1787f580-6cd9-11e9-977b-cd86cc55564b.png)

**Comment by kingces95** [comment] 2019-05-02 22:54
![image](https://user-images.githubusercontent.com/4120386/57111853-603fae80-6cd9-11e9-8b7d-850fb108fae1.png)

**Comment by samhouts** [comment] 2019-05-06 17:38
Duplicate of #2049

**Closed by samhouts** 2019-05-06 17:38 UTC
Labels: e/5 :clock5:, s/unverified, t/bug :bug:

**Comment by Crunch91** [comment] 2019-07-02 11:23
> 
> 
> Duplicate of #2049

I don't think that this is a duplicate. Issue #2049 is about converting DateTimes in local format instead of leaving them in default en-US format.
But it's not the point for this issue #6069. When Binding a **double** value to a label/entry with `culture == de` the point seperator appears. However binding a **float** value the point seperator does not appear. To be straightforward the point seperator should appear either for double **and** for float. I do not complain about the wrong separator for the given culture (it's the content of tickets #2049 #3700).
