### ISSUE TITLE
Android WebClient.DownloadString  Invalid URL Fatal signal 11

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#6333] opened 2019-05-28 15:58 UTC
Create a fresh app change App.xaml.cs to:

        public App()
        {
            InitializeComponent();
            var test = GetString();
            MainPage = new MainPage();
        }

        /// <summary>
        /// Downloads the encryption key for webservices.
        /// </summary>
        public static string GetString()
        {
            try
            {
                var client = new WebClient();
                var key = client.DownloadString("test.txt");
                return key;
            }
            catch
            {
                System.Console.WriteLine("Error Caught");
                return "";
            }
        }

App crashes with:
05-28 16:58:20.438 F/libc    (24451): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 24451 (.WebClientCrash), pid 24451 (.WebClientCrash)

Android Crash
IOS Ok

- IDE: VS 2019 16.1.1
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Affected Devices:
Tested on a Galaxy S9 PLus
Xamarin.Forms 4.0.0.425677

[WebClientCrash.zip](https://github.com/xamarin/Xamarin.Forms/files/3228589/WebClientCrash.zip)

**Comment by brendanzagaeski** [comment] 2019-05-28 22:31
Thanks for the report and the test case! I can confirm that this behavior has the same native backtrace as <https://github.com/xamarin/xamarin-android/issues/3112>, so I will close this Xamarin.Forms issue as a duplicate of that issue. The fix will require a new version of Xamarin.Android that will be based on a new version of the Mono runtime and debugger. (The Xamarin.Forms NuGet package version will not affect this behavior.)

For reference, here's the top of the native backtrace with symbols that I got from the test case in the [description](https://github.com/xamarin/Xamarin.Forms/issues/6333#issue-449351930):

```
  * frame #0: 0x0000007126cf5da8 libart.so`art_sigsegv_fault
    frame #1: 0x0000007126cf62b4 libart.so`art::FaultManager::HandleFault(int, siginfo*, void*) + 356
    frame #2: 0x00000058b5382b5c app_process64`___lldb_unnamed_symbol20$$app_process64 + 572
    frame #3: 0x00000071acbdd870 [vdso]
    frame #4: 0x00000071100c5640 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x0000000000000000) at mini-runtime.h:390
    frame #5: 0x00000071100c5638 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #6: 0x00000071100c5640 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x0000007109bfda08) at mini-runtime.h:390
    frame #7: 0x00000071100c5638 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #8: 0x00000071100c52b8 libmonosgen-2.0.d.so`mono_handle_exception(ctx=<unavailable>, obj=<unavailable>) at mini-exceptions.c:2988
    frame #9: 0x00000071100fd01c libmonosgen-2.0.d.so`mono_arm_throw_exception(arg=<unavailable>, pc=<unavailable>, int_regs=0x0000007fcd282d70, fp_regs=0x0000007fcd282e70, corlib=<unavailable>, rethrow=1) at exceptions-arm64.c:410
```

**Closed by brendanzagaeski** 2019-05-28 22:31 UTC
Labels: i/high, p/Android, s/unverified, t/bug :bug:
