### ISSUE TITLE
[Bug] ListView and CollectionView do not consider VerticalOption="Start"

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#5942] opened 2019-04-17 16:11 UTC
### Description
By default, ListView and CollectionView used FilleAndExpand VerticalOption. If you change this, 
it has no effect.

### Steps to Reproduce

1. Test my example

### Expected Behavior
List and Collection Height adapt to the content height.

### Actual Behavior
List and Collection height="*" (expand)

### Reproduction Link

[CollectionViewMaterialBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3090532/CollectionViewMaterialBug.zip)

**Comment by samhouts** [comment] 2019-04-19 18:09
@Moltroon `ListView` and `CollectionView` (and similar controls, like `ScrollView`) always vertically expand to available space unles you've specificed a `HeightRequest`. This is expected behavior. Thanks!

**Comment by samhouts** [comment] 2019-04-19 19:00
You can also wrap them with a StackLayout to impose the behavior you're wanting. See #5763.

**Comment by Lelelo1** [comment] 2019-06-01 22:10
That's not true. `ScrollView` adapts after content. `ListView` and `CollectionView` don't. I would expect `ListView` and `CollectionView` to do so.

Also you can't wrap `ListView` or `CollectionView` to impose that behaviour.

**Comment by JunkyXL86** [comment] 2019-08-12 10:47
> 
> 
> You can also wrap them with a StackLayout to impose the behavior you're wanting. See #5763.

I mean if there is the VerticalOptions property, it should take effect. If the CollectionView is meant to expand to available space, default value of VerticalOptions would be 'Fill'.
VerticalOptions=Start should be working, not forcing us to wrap in a StackPanel, though this doesn't even work.

**Comment by balazserd** [comment] 2019-10-04 15:51
CollectionView is constantly messing up carefully calculated layout due to this **BUG**. It is a bug, because HeightRequests are not respected. And the way they are not respected is full random too. Setting the same height request for an element on a page with a CollectionView below has a different height than on a page where there is no CollectionView below. Not to mention how the element has the properties Vertical and Horizontal options, yet not acting on them when they are set.

Make CollectionView not derive from VisualElement if you violate its definitions.

**Comment by EvoPulseGaming** [comment] 2019-11-21 06:24
@samhouts You closed this one referencing a duplicate, and then closed the duplicated referencing this as the duplicate. Apparently the default behavior of collectionview and listview is to take up all the space. There appears no way to disable this. Even on latest preview.

**Comment by samhouts** [comment] 2019-12-16 18:23
Actually, I closed this as "expected behavior". I can reopen this as an enhancement request. Thanks!

**Comment by RyanGaudion** [comment] 2019-12-19 16:10
+1 to this, it is causing really annoying effects in our applications,

**Comment by WilliamDumontRT** [comment] 2020-02-24 22:29
+1 Having the CollectionView locked on expanding makes it very difficult and impractical to incorporate them in a page with multiples CollectionViews or complex layout.

**Comment by maexsp** [comment] 2020-04-03 12:57
Run also into this issue. Its a major faulty behviour. Was also described long time ago here [#6497](https://github.com/xamarin/Xamarin.Forms/issues/6497)

When will this be fixed?

**Comment by AbdellahOusrhireDev** [comment] 2020-04-15 15:40
This is a serious issue, collection view is a really good view two show dynamic data in a grid like shape easily but this extra space is annoying

**Comment by ahmadalgarni** [comment] 2020-04-19 12:55
Same in here, 
I get extra spaces that I can't get rid off. hence, I can't also place two collectionviews inside a scroll, extra soace is really annoying.

lightgray is collection1 , lightblue is collection2 , why is the white spaces. 


![Simulator Screen Shot - iPhone 11 - 2020-04-19 at 15 54 22](https://user-images.githubusercontent.com/14974746/79688300-1f2c0b80-8256-11ea-9a85-0819967393d6.png)

**Comment by SharpMobileCode** [comment] 2020-04-21 16:36
I was going absolutely insane trying to figure out what I was doing wrong.  This is obviously a gross oversight and certainly not expected behavior.  I've been a year since reported, so I hope this gets fixed soon.

**Comment by samhouts** [comment] 2020-04-21 17:53
I'm going to take back what I said earlier and call this a bug. We plan to fix this for CollectionView/CarouselView. Thanks for your patience!

**Comment by samhouts** [comment] 2020-04-21 17:53
Duplicate of #8640

**Closed by samhouts** 2020-04-21 17:53 UTC
Labels: a/collectionview, a/layout, a/listview, m/high impact :black_large_square:, proposal-open, t/enhancement ➕

**Comment by jefffhaynes** [comment] 2020-04-22 17:56
@samhouts Why isn't this a bug for ListView as well?  It is definitely not "expected" behavior by any reasonable definition of the word.

**Comment by samhouts** [comment] 2020-04-22 18:02
@jefffhaynes We're prioritizing CollectionView; we're hoping CollectionView is a more performant and easy to use version of ListView that you'll be happy to switch to.

**Comment by jefffhaynes** [comment] 2020-04-22 18:05
@samhouts Unfortunately I've tried switching to CollectionView and it seems to over-zealously retrieve data from the source (in my case a database so not great).  ListView at least gives you the (undocumented) option of defining a IReadOnlyList, forcing retrieval via the indexer of only what is visible.  I'm kind of working on a bug for CollectionView but it's a complicated thing to capture.  Basically, if CollectionView had better data virtualization I would consider it but until then it isn't an option.  Glad to hear you're working on it though.

**Comment by samhouts** [comment] 2020-04-22 18:06
@jefffhaynes That's great feedback! Definitely submit an issue for that. Thanks!

**Comment by jefffhaynes** [comment] 2020-04-22 19:03
#10416

**Comment by lobbo232** [comment] 2020-05-04 12:14
> I'm going to take back what I said earlier and call this a bug. We plan to fix this for CollectionView/CarouselView. Thanks for your patience!

This is good news, but rather than enhancements should it not be prioritised and fixed as a bug? There are a lot of people stuck with it as an issue.

**Comment by stanleywailers** [comment] 2020-07-03 23:19
I had the same problem 
I resolved the bug setting VerticalItemSpacing in "0"
like this example

   <CollectionView
                VerticalOptions="FillAndExpand"
                x:Name="cvProductResult"
                ItemSizingStrategy="MeasureAllItems"
                VerticalScrollBarVisibility="Never"
                SelectionMode="Single"
                BackgroundColor="White"
                ItemsSource="{Binding Model}"
                RemainingItemsThreshold="1"
                ItemTemplate="{StaticResource ProductSelectorList}"
                IsVisible="{Binding Model, Converter={StaticResource hasDataConverter}}"
                RemainingItemsThresholdReachedCommand="{Binding NewPaginationCommand}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout
                        Orientation="Vertical"
                        Span="2" **VerticalItemSpacing="0"** HorizontalItemSpacing="5"/>
                </CollectionView.ItemsLayout>
            </CollectionView>

**Comment by Tommigun1980** [comment] 2020-08-03 03:48
Please put collection view back in preview mode. It is not ready for prime time as there’s too many layout issues atm.

**Comment by chaosifier** [comment] 2020-09-03 10:43
Any updates on the issue?

**Comment by tuliomarks** [comment] 2020-09-10 08:50
Any updates on the issue?

**Comment by Kingamattack** [comment] 2020-09-28 08:20
I don't understand why all the issues related to this bug are "Closed". We all still have it unfortunately

**Comment by rapcgutz** [comment] 2020-10-12 15:06
Inside CollectionView, Use StackLyout instead of using Grid and it will solve your problem

**Comment by rerickson1** [comment] 2020-11-06 21:32
> Inside CollectionView, Use StackLyout instead of using Grid and it will solve your problem

Can you provide a quick example in XAML? I am trying this without success.

**Comment by volcano619** [comment] 2020-12-04 08:42
may be enclose the collectionview inside a scrollview and disable the scroll of the collectionview using renderer, this might fix it

**Comment by Tuurash** [comment] 2021-10-20 19:25
This seems to be a very effective workaround :)
https://stackoverflow.com/questions/65767461/xamarin-forms-adjusting-height-of-collectionview-to-be-minimum-size-to-fit-chi
