### ISSUE TITLE
[Bug] Device.OpenUri double encodes spaces on iOS

### ISSUE THREAD

**Issue by StevenGranados** [xamarin/Xamarin.Forms#6779] opened 2019-07-04 09:26 UTC
Using Device.OpenUri to open a remote pdf, leads to safari double padding spaces in the Uri to %2520.  Works fine on Android. The string as soon as it goes into the function is fine and the originalstring property is with unencoded spaces.

### Expected Behavior
Safari will open and display the pdf.
### Actual Behavior
Safari opens and gives a 404 because spaces have been double encoded.

- Version with issue:
- Last known good version: Fails in 3.4 and 4.1
- IDE:Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: Works fine.
- Nuget Packages: I'm using Octane Video Player in addition to Xamarin Forms.
- Affected Devices: Tested on real iPhone 8. Can't test on a simulator below iOS12.2 because it's not working.

**Comment by jfversluis** [comment] 2019-07-04 09:29
Thanks for reporting! However, this is a duplicate I will mark it as such and you can follow the status in the other issue.

**Comment by jfversluis** [comment] 2019-07-04 09:29
Duplicate of #5615

**Closed by jfversluis** 2019-07-04 09:29 UTC
Labels: s/unverified, t/bug :bug:
