### ISSUE TITLE
[UWP] StackLayouts / NavigationPage leaks memory

### ISSUE THREAD

**Issue by balazsbonis** [xamarin/Xamarin.Forms#1352] opened 2017-12-08 08:48 UTC
### Description
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=61027.

On UWP with Xamarin.Forms pushing and then popping a page with `StackLayout`s on it to the navigation stack several times will cause the memory consumption grow infinitely.

### Steps to Reproduce
Either take the sample project attached, or create a simple one with the following setup:
- The main app should have a `NavigationPage` with the main page wrapped inside
- That main page should have a `ListView` of elements
- Clicking on any of those elements should take the user to another page (call it details page), by pushing it to the stack
- Details page should have a back button that will pop the top of the navigation stack and taking it back to the main page

This navigation back-and-forth has to be done several times to see the memory usage increase. The problem is that the memory will never be released, `GC` will not collect it, even by forcing from either code or from Visual Studio's performance profiler set to monitor memory usage.

You can take a snapshot in the profiler when the app starts and then navigate to a page and then back maybe 20, 30 times. Take another snapshot again, and then let VS analyse the difference. See attached screenshot for the results.

Over longer periods of time this leads to crashes in every single UWP app with Xamarin.Forms that has this navigation capability.

### Expected Behavior
Going back from a page should release the memory used by it, or at least the garbage collector should be able to clean it up at a certain point.

### Actual Behavior
Memory usage increases indefinitely, eventually crashing the app.

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: I went back as far as 2.2, none of the versions I've tried worked
- IDE: VS 2017 Community Edition on Windows 10
- Platform Target Frameworks: 
  - UWP:  15063
- Nuget Packages: Xamarin.Forms

### Screenshots
The issue is not visual, but using visual studio's performance profiler, you can get the following proof of the memory increase:
![image](https://user-images.githubusercontent.com/7962460/33757833-cf2bde72-dbf3-11e7-80d7-95e622baa2f5.png)

### Reproduction Link
[UWPMemoryLeakXamarinBugzilla.zip](https://github.com/xamarin/Xamarin.Forms/files/1542007/UWPMemoryLeakXamarinBugzilla.zip)

**Comment by hartez** [comment] 2018-03-26 19:37
@balazsbonis 

If I run the attached repro project with the memory profiler attached and navigate to the Details page and back 30 times, I do not see the results displayed in the attached screen shot. The number of allocated StackLayouts remains constant, and the StackLayout count difference remains at +1 (the one displayed on the Details page). Likewise, the number of instances of DetailsPage remains constant at 1.

Am I missing a step in the reproduction? Can you attach the full `.diagsession` file from your tests to this issue so I can view more of the data?

**Comment by jassmith** [comment] 2018-04-07 04:34
Closing due to inactivity. Hopefully this is just resolved in master.

**Comment by balazsbonis** [comment] 2018-04-09 10:16
@hartez Thank you for taking the time trying to reproduce the issue.

I have updated the nuget package in the solution to the latest (not pre-release) version of Xamarin Forms available (2.5.1.444934) and running the same test I can still very well reproduce this issue. I will be attaching the `.diagsession` file here, please have a look:

https://drive.google.com/file/d/1IIIKPGfeBye1bDyGlwt1-9suqkwnOW2c/

In an application of ours, we got around this issue by greatly limiting the number of `StackLayout`s we use (most of the time we could actually substitute `Grid`s or `AbsoluteLayout`s in place), but maintaining those pages are a bit more cumbersome without the option of stacking elements. However, the memory footprint is significantly smaller using them.

@jassmith I am sorry, but I can not let this one go: Closing a ticket for not responding for 14 days on the basis of inactivity after not doing anything on this for more than 3 months (11th Dec - 26th Mar) in my opinion is a little bit unfair. Some people happen to take holidays this long and won't have access to their computers to do a VS session 🙂

**Comment by PureWeen** [comment] 2018-04-23 16:26
I have a PR with some additional UWP cleanup calls here
https://github.com/xamarin/Xamarin.Forms/pull/2416
Not sure if those will apply to this issue

I wasn't seeing memory leaks in the use case I was testing though just that dispose calls weren't being called which could lead to leaks in user code though or other scenarios that I hadn't tested.

**Comment by balazsbonis** [comment] 2018-04-25 15:14
@PureWeen That was exactly my suspicion as a root cause for this issue. I do hope your fixes will correct this one as well. Thanks for picking it up! 👍

**Comment by balazsbonis** [comment] 2018-05-11 09:54
@hartez I shall do so in the weekend, and come back with the results. Thanks for the update!

**Comment by samhouts** [comment] 2018-06-12 18:38
Since this issue hasn't been updated in more than 30 days, we will close it now. Please feel free to reopen it if you are still experiencing this issue and have more information. Thank you!

**Closed by samhouts** 2018-06-12 18:38 UTC
Labels: p/UWP, s/needs-info, t/bug :bug:
