### ISSUE TITLE
[Bug] MediaElement HeightRequest, VerticalOptions and Background black

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#10534] opened 2020-05-01 11:56 UTC
### Description

I'm reproducing an audio (not video) in mp3, it only plays if I set a height or VerticalOptions="FillAndExpand" with Hot Reload, also a black background appears, how to remove the black background?

### Steps to Reproduce
```
            <MediaElement  Source="ms-appx:///fire.mp3" IsLooping="True" 
                          KeepScreenOn="True" HeightRequest="1"  />

            <MediaElement  Source="ms-appx:///fire.mp3" IsLooping="True" 
                          KeepScreenOn="True" VerticalOptions="FillAndExpand" />
```

### Expected Behavior
audio can be played without the black background

### Actual Behavior
audio plays with vertical height and properties and with a black background

### Basic Information

- Version with issue: 4.6
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9, 10
- Affected Devices: Xiaomi mi6 and Emulator Andorid 10

### Screenshots
![Screenshot_1588334177](https://user-images.githubusercontent.com/11645585/80803776-985f2300-8bb3-11ea-9da3-ed7f9fc54dac.png)
![Screenshot_1588334191](https://user-images.githubusercontent.com/11645585/80803778-98f7b980-8bb3-11ea-87fc-4c92b05a60bd.png)

**Comment by hartez** [comment] 2020-05-01 22:20
This is a duplicate of #10428

**Closed by hartez** 2020-05-01 22:20 UTC
Labels: s/unverified, t/bug :bug:
