### ISSUE TITLE
[Bug] [Android] HorizontalTextAlignment=Center does not center text on Entry

### ISSUE THREAD

**Issue by janschoelchAtOK** [xamarin/Xamarin.Forms#7538] opened 2019-09-16 15:10 UTC
### Description
When setting the HorizontalTextAlignment property on an Entry on Android, it is being ignored as the text is always left-aligned. 

As the issue seems to happen within the `EntryRenderer` class, it also occurs when using the Material Visual.

### Steps to Reproduce

1. Create an empty project using XF4.2+
2. To the `MainPage.xaml` add an `Entry` and set `HorizontalTextAlignment="Center"`
3. Run the app

OR

1. Start the attached solution.

### Expected Behavior

The text should be centered within the Entry on all platforms.

### Actual Behavior

On iOS, the Text within the Entry is being centered horizontally as expected. 
But on Android, the text stays on the left.

I did not test this on UWP as it seems only to be connected to a miscalculation on the Android view's GravityFlags.

### Additional Information

When using the attached demo solution, you can see where the issue occurs.
I hooked into the `EntryRenderer.OnElementChanged` and checked the `GravityFlags` on the underlying `EditText`. They are being reset when setting the `VerticalTextAlignment`.
It seems like the changes made to `Xamarin.Forms.Platform.Android/Extensions/TextAlignmentExtensions.cs` (Line 19) in PR https://github.com/xamarin/Xamarin.Forms/pull/6463 made the issue occur as the GravityFlags are being overwritten in `UpdateVerticalAlignment` (the `orMask` is not set correctly in the call). 

### Basic Information

- Version with issue: XF4.2+
- Last known good version: XF4.1
- IDE: Tested it on Visual Studio 2017 Professional 15.9.11
- Platform Target Frameworks: 
  - iOS: 12.2
  - Android: 9.0
  - UWP:  N/A (Not tested)
- Android Support Library Version: 28.0.0.1
- Nuget Packages: Tested on XF4.3.0.778476-pre1
- Affected Devices: Tested on Huawei P Smart+ (Android 8.1) and on a Google Nexus 5X Emulator (Android 9.0) - but this seems to affect not only a specific device.

### Reproduction Link

[TextLayout.zip](https://github.com/xamarin/Xamarin.Forms/files/3616819/TextLayout.zip)

**Comment by Oxoproline** [comment] 2019-12-20 12:11
Just the note the issue is for any `HorizontalTextAlignment ` attribute.

**Comment by luismts** [comment] 2020-01-03 14:55
Same problem here

**Comment by hartez** [comment] 2020-02-05 21:18
This is fixed in 4.5.0.187-pre2.

**Closed by hartez** 2020-02-05 21:18 UTC
Labels: 4.2.0, e/2 :clock2:, i/regression, p/Android, t/bug :bug:
