### ISSUE TITLE
BoxView not working in 3.2.0.637442-pre1

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#3349] opened 2018-07-20 07:35 UTC
### Description

BoxView not working in 3.2.0.637442-pre1

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment] 2018-07-20 13:58
This is most likely a duplicate of
https://github.com/xamarin/Xamarin.Forms/issues/3342

**Closed by PureWeen** 2018-07-20 13:58 UTC
