### ISSUE TITLE
[Android] Release build crashes on launch

### ISSUE THREAD

**Issue by RalphJacobson** [xamarin/Xamarin.Forms#2671] opened 2018-05-11 07:47 UTC
### Description
When deploying a release build to a device with either "ProGuard" or "Bundle assemblies into native code" enabled, the app crashes on launch.

### Steps to Reproduce

1. Create a new Xamarin Forms Mobile App.
2. Change solution configuration to Release.
3. Under Android options, enabled either "ProGuard" or "Bundle assemblies into native code".
4. Deploy to a **device.**

### Expected Behavior
App to launch successfully.

### Actual Behavior
Crashes on launch.

### Basic Information

- Version with issue: 3.0.0.446417
- Last known good version: 2.5.1.527436
- IDE: Visual Studio Enterprise 2017 v15.7.1
- Platform Target Frameworks:
  - Android: 8.1

.NET Framework 4.7.2
Android SDK Platform-Tools 27.0.1
Android SDK Build-Tools 27.0.3
Proguard 6.0.3
JDK 8 Update 171
Android NDK R17

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/1994395/App1.zip)

**Comment by JaeWLee** [comment] 2018-05-12 08:07
I had same issue, too

**Comment by napalmDaz** [comment] 2018-05-13 00:15
Same issue here. Release build fails is proguard enabled AND Link SDK enabled.

**Comment by brendanzagaeski** [comment] 2018-05-14 20:07
Quick cross-referencing note for the Microsoft team

This item does not yet mention the messages from the device log output that are seen when the crash occurs, but based on the mention of "Bundle assemblies into native code" in the description, this might be related to (or a duplicate of) <https://github.com/xamarin/xamarin-android/issues/1651>.

**Comment by PureWeen** [comment] 2018-05-14 23:44
I'm isolating this down a bit more and seeing if we can just include a proguard file into the nuget for this but for now if you create a proguard file

With at least these entries
```
-keep class android.support.v7.widget.** { *; }
-dontwarn android.support.v7.widget.*
```

That will get you a proguard build that works

As you add other things into your application you might need to add additional entries.

As far as the embedding assemblies one ... I'm still looking at that

**Comment by PureWeen** [comment] 2018-05-15 04:55
I'm going to close this for now

I added a specific enhancement issue and referenced all the other issues that came up around this
https://github.com/xamarin/Xamarin.Forms/issues/2709

 Please let me know if that issue doesn't seem to apply to this issue and I'll reopen

**Closed by PureWeen** 2018-05-15 04:55 UTC
Labels: i/regression, p/Android, t/bug :bug:
