### ISSUE TITLE
Data parsing to next view not working on Android. iOS works fine.

### ISSUE THREAD

**Issue by TimVanDenEnden** [xamarin/Xamarin.Forms#4051] opened 2018-10-10 11:46 UTC
I have this list view with items in it loaded from an API. When I load the app on an IOS device emulator or real device it works fine but on the android platform it keeps crashing.

The function that it calls when you click on the item works fine with a alert. but when you try to navigate to different page it crashes. 

The function you call when you click on the item from listview:

```
void ClickOnStudent(object sender, SelectedItemChangedEventArgs e)
{
            // Set preset for list and select right student.
            StudentsPreset student = (StudentsPreset)((ListView)sender).SelectedItem;
                ((ListView)sender).SelectedItem = null;

            // Load student view.
            Application.Current.MainPage = new StudentView(student.StudentId);
}
```

**Comment by TemplemanWeb** [comment] 2018-10-10 12:05
Running into the same problem. Any solution jet?

**Comment by TimVanDenEnden** [comment] 2018-10-10 12:32
<img width="1680" alt="screenshot 2018-10-10 at 14 31 12" src="https://user-images.githubusercontent.com/21998860/46736404-3a997c00-cc99-11e8-8d0a-4cd190ee1c6b.png">

**Comment by TimVanDenEnden** [comment] 2018-10-10 14:05
The stack trace is empty.

**Comment by PureWeen** [comment] 2018-10-10 14:12
@TimVanDenEnden can you create a break point that breaks on all exceptions see if the exception is further up?

Can you try rebuilding your android project?

Can you try
- close VS
- delete bin/obj
- open VS
- try again?

**Comment by TimVanDenEnden** [comment] 2018-10-10 14:15
you mean delete bin folder and obj folder?

**Comment by PureWeen** [comment] 2018-10-10 15:31
@TimVanDenEnden 

> you mean delete bin folder and obj folder
In your project folders you'll see two folders (bin and obj) that unfortunately can get out of date and sometime cause an issue during runtime. Deleting those just resets everything back to a base line point and thus just ensures nothing weird is happening

> can you maybe also explain what a repro is?
A reproduction of your issue that I can run myself which will let me more easily figure out and fix the issue. If you can recreate the issue, zip up the project, and then attach to this Issue then we can address it much quicker

**Comment by TimVanDenEnden** [comment] 2018-10-10 15:51
<img width="1680" alt="screenshot 2018-10-10 at 17 50 10" src="https://user-images.githubusercontent.com/21998860/46748903-f9af6080-ccb4-11e8-84af-9aae19bb0c56.png">

I removed the folder like you told now I am getting this error Android only.

**Comment by PureWeen** [comment] 2018-10-10 16:07
Can you zip up your project and attach?

Token exception usually means there's a dll or library that isn't in sync somewhere.
Can you make sure all your projects have the same version of forms and other libraries? Rebuild the projects? Did you delete the bin/obj folders for both the "myDevApp" and "myDevApp.Android" projects?

**Comment by KaelSuncaster** [comment] 2018-10-10 22:31
Seeing similar issues after updating to Xamarin.Forms 3.2.0.871581 (3.2.0 Service Release 1).

Android seems to be hitting ios specific code?

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

10-11 00:29:15.042 D/Mono    ( 4853): DllImport attempting to load: '/system/lib/liblog.so'.
10-11 00:29:15.042 D/Mono    ( 4853): DllImport loaded library '/system/lib/liblog.so'.
10-11 00:29:15.042 D/Mono    ( 4853): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
10-11 00:29:15.042 D/Mono    ( 4853): Searching for '__android_log_print'.
10-11 00:29:15.042 D/Mono    ( 4853): Probing '__android_log_print'.
10-11 00:29:15.042 D/Mono    ( 4853): Found as '__android_log_print'.
10-11 00:29:15.049 I/MonoDroid( 4853): UNHANDLED EXCEPTION:
10-11 00:29:15.114 I/MonoDroid( 4853): System.NullReferenceException: Object reference not set to an instance of an object.
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Page.On[T] () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:427 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page.UpdatePadding (Xamarin.Forms.Thickness thickness, Xamarin.Forms.Page page) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\PlatformConfiguration\iOSSpecific\Page.cs:126 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page+<>c.<.cctor>b__27_0 (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00027] in D:\a\1\s\Xamarin.Forms.Core\PlatformConfiguration\iOSSpecific\Page.cs:70 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:625 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:417 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0003d] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:573 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:351 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x000ba] in D:\a\1\s\Xamarin.Forms.Core\Setter.cs:65 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Style.ApplyCore (Xamarin.Forms.BindableObject bindable, Xamarin.Forms.Style basedOn) [0x0001e] in D:\a\1\s\Xamarin.Forms.Core\Style.cs:135 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply (Xamarin.Forms.BindableObject bindable) [0x0002b] in D:\a\1\s\Xamarin.Forms.Core\Style.cs:98 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style) [0x000f8] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:156 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:77 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle.OnImplicitStyleChanged () [0x00038] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:115 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:128 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:625 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:417 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:362 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Element.OnResourceChanged (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:623 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Element.OnSetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key) [0x00020] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:473 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key, System.Boolean fromStyle) [0x00066] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:346 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:326 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle.RegisterImplicitStyles () [0x00044] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:130 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.MergedStyle..ctor (System.Type targetType, Xamarin.Forms.BindableObject target) [0x0001f] in D:\a\1\s\Xamarin.Forms.Core\MergedStyle.cs:30 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.VisualElement..ctor () [0x0005f] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:154 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.Page..ctor () [0x0000b] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:48 
10-11 00:29:15.114 I/MonoDroid( 4853):   at Xamarin.Forms.TemplatedPage..ctor () <0x86bbd010 + 0x0002b> in <036ea626158e48a4b8dcc52d0593c6a6>:0 
10-11 00:29:15.115 I/MonoDroid( 4853):   at Xamarin.Forms.ContentPage..ctor () <0x86bbce90 + 0x0002b> in <036ea626158e48a4b8dcc52d0593c6a6>:0 
10-11 00:29:15.115 I/MonoDroid( 4853):   at tartPage..ctor () [0x00000] in C:\SandBox\MobileTrunkTrunk\src\User\Start\StartPage.xaml.cs:9 
10-11 00:29:15.115 I/MonoDroid( 4853):   at App+<>c.<Bootstrap>b__2_2 () [0x00000] in C:\SandBox\MobileTrunkTrunk\src\Mobile\App.xaml.cs:168 
10-11 00:29:15.115 I/MonoDroid( 4853):   at PageResolvers.StartPageResolver.GetStartPage () [0x00001] in C:\SandBox\MobileTrunkTrunk\src\PageResolvers\StartPageResolver.cs:12 
10-11 00:29:15.115 I/MonoDroid( 4853):   at Bootstrap () [0x003fe] in C:\SandBox\MobileTrunkTrunk\src\App.xaml.cs:175 
10-11 00:29:15.115 I/MonoDroid( 4853):   at App.OnStart () [0x00001] in C:\SandBox\MobileTrunkTrunk\src\App.xaml.cs:194 
10-11 00:29:15.115 I/MonoDroid( 4853):   at Xamarin.Forms.Application.SendStart () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:305

**Comment by PureWeen** [comment] 2018-10-10 22:41
@KaelSuncaster your issues will be fixed by the  PR for this issue
https://github.com/xamarin/Xamarin.Forms/issues/3866

**Comment by KaelSuncaster** [comment] 2018-10-10 22:42
Cheers!

**Comment by TimVanDenEnden** [comment] 2018-10-11 06:42
@PureWeen This the link where you can download the project as zip file.

https://project2.t1mdevelopment.nl

**Comment by TimVanDenEnden** [comment] 2018-10-12 07:03
Can someone explain me what the problem is?

**Comment by TimVanDenEnden** [comment] 2018-10-18 07:47
I also tried to make new project and replace ever single back. And I am still getting the same error mean while on IOS is it all fine it works very smoothly.

**The error I get after clicking the item in the list view:**
`System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by TimVanDenEnden** [comment] 2018-10-18 10:38
```
void ClickOnStudent(object sender, ItemTappedEventArgs e)
{
 // Set preset for list and select right student.
 StudentsPreset student = (StudentsPreset)((ListView)sender).SelectedItem;
           ((ListView)sender).SelectedItem = null;

 // Load student view.
 Application.Current.MainPage = new StudentView(student.StudentId, student.Fullname);
}
```
When I use a view with no data it works fine. 

When I hardcode the student.StudentId and student.Fullname it crashes and gives this error:
`System.NullReferenceException: Object reference not set to an instance of an object.`

Only on the android platform it keeps crashing. On iOS platform it already works.

**Comment by TemplemanWeb** [comment] 2018-10-18 13:00
Any solution yet?

**Comment by TimVanDenEnden** [comment] 2018-10-18 16:05
Fixed my button did not have any function...... so it kept crashing

**Closed** 2018-10-18 16:38 UTC
