### ISSUE TITLE
[Bug] [UWP] [SHELL] CollectionView is not visible until screen resize

### ISSUE THREAD

**Issue by leo-adm** [xamarin/Xamarin.Forms#9299] opened 2020-01-23 16:52 UTC
### Description
When a CollectionView is loaded, it stays blank until screen resize

### Steps to Reproduce
1. Create a project with a CollectionView on UWP with Shell
2. Open the page containing the Collection
3. Notice it doesnt appear until you change the resolution

### Expected Behavior
CollectionView loads immediatly when showed

### Actual Behavior
Stays blank until resize

### Basic Information
- Platform Target Frameworks: 
  - UWP   

### Screenshots
![d35e9109a23a1d807ae1db53e5b3fd29](https://user-images.githubusercontent.com/40642381/73004742-97fe0180-3de6-11ea-8320-9ad8d4b1baa5.gif)

### Reproduction Link
https://drive.google.com/file/d/19sU_rjsCNh5oUalQowwUYu1ISQZEWoYi/view

**Comment by leo-adm** [comment] 2020-01-23 17:07
#8814 Update

**Comment by samhouts** [comment] 2020-01-27 23:38
Duplicate of #8814

**Closed by samhouts** 2020-01-27 23:38 UTC
Labels: a/collectionview, a/shell :shell:, p/UWP, s/unverified, t/bug :bug:
