### ISSUE TITLE
[Bug] Xamarin.Forms.Shell TableView does not scroll on Android [Bug]

### ISSUE THREAD

**Issue by XXcharlosXX** [xamarin/Xamarin.Forms#7009] opened 2019-07-29 19:57 UTC
### Description
Xamarin.Forms.Shell TableView does not scroll on Android
### Steps to Reproduce

1. Create Xamarin.Forms.Shell Tabbed application.
2.Populate some tabs with dummy pages.
3. Create a ContentPage with a Fully populated tableview that should extend beyond the screens bounds.
4. Build and run on Android Device
5.Navigate to the tableview page (tap on the tab)
6.Try scrolling

### Expected Behavior
Scrolling should go up or down smoothly
### Actual Behavior
Nothing happens no scroll or budge at all.
### Basic Information

- Version with issue:4.1.0.618606
- Last known good version:????
- IDE:VS for Mac
- Platform Target Frameworks:
  - Android: 5.0-9.0 

### Screenshots
<img width="912" alt="Screen Shot 2019-07-29 at 12 45 20 PM" src="https://user-images.githubusercontent.com/40214085/62077944-375b8680-b200-11e9-83c0-1b45d1d2ae37.png">

### Reproduction Link

Cannot provide a link to the project I am working on due to sensitive information.
If necessary, I can build a project with the issue excluding all the sensitive information.

**Comment by samhouts** [comment] 2019-07-29 23:06
Duplicate of #6611

**Closed by samhouts** 2019-07-29 23:06 UTC
Labels: s/unverified, t/bug :bug:
