### ISSUE TITLE
[Bug] Shell.TitleView broken in v5.0.0.2012 when using multiple Views

### ISSUE THREAD

**Issue by davidaramantSEP** [xamarin/Xamarin.Forms#13949] opened 2021-03-05 19:39 UTC
### Description

This is a previous bug that has resurfaced: https://github.com/xamarin/Xamarin.Forms/issues/13420

It was fixed in 5.0.0.1931 but is broken against in 5.0.0.2012.

All information is in the discussion for the original bug.

**Comment by AndreasReitberger** [comment] 2021-03-10 16:24
@PureWeen 
Is there a workaround for this issue? This is the only thing keeping me from releasing my next app update.
Thank you!

**Comment by davidaramantSEP** [comment] 2021-03-10 16:34
Unfortunately I don't think there is a workaround. I have fought with negative margin hacks but they don't seem to work reliably anymore.  I tried using toolbar items instead but they crash due to a different bug.

_Maybe_ you can get around it with a custom renderer, but that felt too heavyweight for a bug workaround for us to explore right now.

**Comment by philtomblin** [comment] 2021-03-28 13:50
I'm unable to see a workaround for this either and, while the width is fixed in 5.0.0.1931, the height is broken. So I'm stuck back on 4.8.0.1821 until this is fixed.

**Comment by AdamDiament** [comment] 2021-03-28 15:47
Also waiting for a fix for this, it's delaying us going live. Running Xamarin forms 5.0.0.2012. Thanks!

**Comment by AndreasReitberger** [comment] 2021-03-29 08:35
> I'm unable to see a workaround for this either and, while the width is fixed in 5.0.0.1931, the height is broken. So I'm stuck back on 4.8.0.1821 until this is fixed.
There is a workaround for the height issue, so you can go with 5.0.0.1931
See here: https://github.com/xamarin/Xamarin.Forms/issues/13476#issue-790114262

**Comment by AdamDiament** [comment] 2021-03-29 11:43
@AndreasReitberger @philtomblin If you absolutely have to have the latest XF, have got a workaround for 5.0.0.2012, which combines using HeightRequest="{OnPlatform iOS=44}" on the parent view, and Margin="{OnPlatform 0, iOS='0,0,70,0',Android='0,0,5,0'}" to add right margin to the subview that is offscreen. Ew, but it displays ok.

**Comment by davidaramantSEP** [comment] 2021-03-29 15:07
> @AndreasReitberger @philtomblin If you absolutely have to have the latest XF, have got a workaround for 5.0.0.2012, which combines using HeightRequest="{OnPlatform iOS=44}" on the parent view, and Margin="{OnPlatform 0, iOS='0,0,70,0',Android='0,0,5,0'}" to add right margin to the subview that is offscreen. Ew, but it displays ok.

Are you sure that works with rotation? When we tried doing something like this it was still behaving badly when rotating a tablet.

We were not testing with 5.0.0.2012 because it crashes for an unrelated issue (`FormattedText` in a `Label`), so maybe the nightly build we were using has different behavior.

**Comment by AdamDiament** [comment] 2021-03-29 16:11
> > @AndreasReitberger @philtomblin If you absolutely have to have the latest XF, have got a workaround for 5.0.0.2012, which combines using HeightRequest="{OnPlatform iOS=44}" on the parent view, and Margin="{OnPlatform 0, iOS='0,0,70,0',Android='0,0,5,0'}" to add right margin to the subview that is offscreen. Ew, but it displays ok.
> 
> Are you sure that works with rotation? When we tried doing something like this it was still behaving badly when rotating a tablet.
> 
> We were not testing with 5.0.0.2012 because it crashes for an unrelated issue (`FormattedText` in a `Label`), so maybe the nightly build we were using has different behavior.

TBH I didn't test it because my app is portrait only, so perhaps it would have the same issue for those with landscape.

**Comment by AndreasReitberger** [comment] 2021-05-20 16:33
> @AdamDiament @davidaramantSEP @AndreasReitberger @philtomblin
> 
> Apologies if I missed it but do you have some XAML I can paste into a TitleView to see the bug?
> 
> I tested the XAML from the original issue and it's showing up fine for me

Hi @PureWeen 
I replied to the previous issue with a code example.
https://github.com/xamarin/Xamarin.Forms/issues/13476#issuecomment-779585785

Maybe this helps you to reproduce the issue on your end.

**Comment by PureWeen** [comment] 2021-05-20 18:19
There we go!

thank you @AndreasReitberger

**Comment by PureWeen** [comment] 2021-05-24 17:57
If anyone wants to test the nugets from my PR

https://dev.azure.com/xamarin/public/_build/results?buildId=40567&view=artifacts&pathAsName=false&type=publishedArtifacts

Let me know if it resolves the issue for you

**Comment by davidaramantSEP** [comment] 2021-05-24 18:21
@PureWeen Am I supposed to just click on `nuget`? Do I need an Azure account to download things? The page doesn't seem to do anything.

**Comment by PureWeen** [comment] 2021-05-24 18:37
@davidaramantSEP yea it's a bit confusing :-/ 

Hover over the "nugets" row and you'll see 3 vertical dots on the right side of the column. Click those dots and you'll be able to download the package

**Comment by davidaramantSEP** [comment] 2021-05-24 21:35
Didn't notice the dots _way_ over there...

From a quick check on iOS it seems fixed. I wasn't able to check Android because our app explodes for some other reason on XF5.

**Comment by PureWeen** [comment] 2021-05-24 21:49
> From a quick check on iOS it seems fixed. I wasn't able to check Android because our app explodes for some other reason on XF5.

Yay!!

What's the exception on Android?

**Comment by davidaramantSEP** [comment] 2021-05-24 21:54
I think it was some random Android package (file related?). Probably has nothing to do with this change; I didn't update all the Google packages. We couldn't update those because of the Material issue that I think I saw was fixed.

**Comment by PureWeen** [comment] 2021-05-25 00:20
@davidaramantSEP does it seems like this issue?
https://github.com/xamarin/Xamarin.Forms/issues/13843

That this PR fixes?
https://github.com/xamarin/Xamarin.Forms/pull/14101

**Comment by davidaramantSEP** [comment] 2021-05-25 14:25
@PureWeen I tried updating every package to the latest. For Android, the behavior is the same as when I just updated using your XF preview packages. It crashes at startup with a `Java.Lang.Runtime` exception complaining about not finding `android.support.v4.content.FileProvider`.

**Comment by PureWeen** [comment] 2021-05-25 14:48
@davidaramantSEP are you explicitly referencing any androidx packages? If you remove them all and just reference Xamarin.Forms does that help?

**Closed** 2021-06-02 15:05 UTC
Labels: a/shell :shell:, t/bug :bug:
