### ISSUE TITLE
[Bug] IndicatorView isn't rendering indicators

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#12028] opened 2020-09-04 20:55 UTC
### Description

I'm not seeing any indicators. Perhaps an iOS 14 related thing. I verified the `IndicatorView` is present.

![Simulator Screen Shot - iPhone 11 Pro - 2020-09-04 at 15 51 00](https://user-images.githubusercontent.com/41873/92284024-cb4d5680-eec6-11ea-915e-7cac3b53d80c.png)

```xaml
<StackLayout Margin="15" Spacing="10">
            <Frame BackgroundColor="White"
                   Padding="10"
                   BorderColor="Black"
                   CornerRadius="0">
                <CarouselView x:Name="reiCV"
                              IndicatorView="indicatorView"
                              HeightRequest="160">
                    <CarouselView.ItemsSource>
                        <x:Array Type="{x:Type x:String}">
                            <x:String>h01.png</x:String>
                            <x:String>h02.png</x:String>
                            <x:String>h03.png</x:String>
                            <x:String>h04.png</x:String>
                        </x:Array>
                    </CarouselView.ItemsSource>
                    <CarouselView.ItemTemplate>
                        <DataTemplate>
                            <Image Source="{Binding .}"/>
                        </DataTemplate>
                    </CarouselView.ItemTemplate>
                </CarouselView>
            </Frame>

            <IndicatorView 
                IndicatorColor="LightGray"
                SelectedIndicatorColor="Black"
                IndicatorSize="10"
                HorizontalOptions="Center"
                x:Name="indicatorView"/>
            
        </StackLayout>
```

### Basic Information

- Version with issue: 5.0.0.4865 (build from latest valid commit on that branch)
- Platform Target Frameworks: 
  - iOS:  iOS 14 using preview 2 of Xamarin.iOS

### Reproduction Link

https://github.com/davidortinau/CarouselGallery

Several examples use `IndicatorView`. None of them work properly.

**Comment by TiagoPicao-V23437** [comment] 2020-09-18 15:38
I was able to show custom indicators through IndicatorTemplate. Created a frame with rounded corners to mimic a round indicator.

**Comment by PawKanarek** [comment] 2020-09-30 16:55
@TiagoPicao-V23437 can you share your code with custom indicator template? I have the same issue with missing indicators iOS 14. And i've tied to make some custom template like you said, but my frame with rounded corners is as big as 40px, even if i said it height/width request should be 5px...

**Comment by TiagoPicao-V23437** [comment] 2020-10-01 08:25
@PawKanarek I did have to tinker a little bit with (and on another screen again due to different layout), but this was working on a very simple layout:

` <IndicatorView.IndicatorTemplate>
                      <DataTemplate>
                          <Frame HasShadow="False"  Padding="3" HeightRequest="3" WidthRequest="3">
                              <Frame.CornerRadius>
                                  <OnPlatform x:TypeArguments="x:Single">
                                      <On Platform="iOS" Value="5"></On>
                                      <On Platform="Android" Value="10"></On>
                                  </OnPlatform>
                              </Frame.CornerRadius>
                          </Frame>
                      </DataTemplate>
                    </IndicatorView.IndicatorTemplate>`

**Comment by Tommigun1980** [comment] 2020-10-04 05:22
Is this a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/12318 ?

**Closed** 2020-10-29 15:56 UTC
Labels: a/indicatorview, blocker, e/5 :clock5:, iOS 14, p/iOS 🍎, t/bug :bug:
