### ISSUE TITLE
ListView: TapGestureRecognizer and ContextActions

### ISSUE THREAD

**Issue by FlashTek** [xamarin/Xamarin.Forms#3680] opened 2018-08-30 07:18 UTC
### Description
When using a `TapGestureRecognizer` inside a `Grid` in a `ViewCell` together with `ContextActions` the `tap` event will be fired every time the user interacts with the item, even when the user is doing a longclick, which should open to action menu.

### Steps to Reproduce

1.  Long press on an item

### Expected Behavior
The context action menu should open and the user should be able to interact which the actions.

### Actual Behavior
The context action menu is opened, but at the same time tap event of the gesture recognizer is called. If you are using this event to navigate (e.g. to a detail page) the user will not be able to use the action menu properly.

### Basic Information

- Version with issue: 3.1 
- Last known good version: could not find a working version
- IDE: Visual Studio Enterprise 2017 
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 
- Nuget Packages: v27.0.2.1
- Affected Devices: All physical devices and emulators

### Reproduction Link
I uploaded a gist of the [xaml ](https://gist.github.com/FlashTek/992d22c4c137492d41a85620c90fda43)which creates this problem.

**Comment by TerryDieckmann** [comment] 2018-09-07 07:57
I can confirm that this issue is indeed present.

**Comment by mfeingol** [comment] 2018-09-14 02:49
I'm seeing the same issue.

**Comment by mfeingol** [comment] 2018-10-02 02:53
Still an issue with Xamarin Forms 3.2.0.839982.

**Comment by FlashTek** [comment] 2018-10-13 01:48
Can anyone report a version which does not have this bug?

**Comment by mfeingol** [comment] 2018-11-04 01:42
Still an issue with Xamarin Forms 3.3.0.967583.

**Comment by TerryDieckmann** [comment] 2018-11-05 06:58
Any progress on this issue?

**Comment by mfeingol** [comment] 2018-12-20 03:21
Still an issue with Xamarin Forms 3.4.0.1008975. :-(

**Comment by mfeingol** [comment] 2018-12-22 22:00
A workaround: override `StartSupportActionMode` and `OnSupportActionModeFinished` on your main activity, use that to determine when to ignore the single click. Horrible, but seems to work.

**Comment by samhouts** [comment] 2019-02-05 20:15
Duplicate of #1932

**Closed by samhouts** 2019-02-05 20:15 UTC
Labels: a/gestures 🖖, e/6 :clock6:, t/enhancement ➕
