### ISSUE TITLE
iOS: Crash in: RemoveObserversFromList. "Terminating app due to uncaught exception 'SIGABRT', reason: 'Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index'"

### ISSUE THREAD

**Issue by mclillill** [xamarin/Xamarin.Forms#7000] opened 2019-07-29 06:44 UTC
### Description

Application Specific Information:
*** Terminating app due to uncaught exception 'SIGABRT', reason: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

Xamarin Exception Stack:
```System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) <0x103171ec0 + 0x00063> in <4fffe1dab0494c34a2a213216932b318#546fb5f289cd70b491fcb0b0cc6e8748>:0
  at Foundation.NSNotificationCenter.RemoveObserversFromList (Foundation.NSObject observer, System.String aName, Foundation.NSObject anObject) <0x103d42dd0 + 0x0004f> in <b28d782d99614fe0b872da2da418b7b8#546fb5f289cd70b491fcb0b0cc6e8748>:0
  at Foundation.NSNotificationCenter.RemoveObserver (Foundation.NSObject observer) <0x103d43110 + 0x0004b> in <b28d782d99614fe0b872da2da418b7b8#546fb5f289cd70b491fcb0b0cc6e8748>:0
  at System.Net.Http.NSUrlSessionHandler.RemoveNotification () <0x103db62f0 + 0x00033> in <0da8ced3e38d42039920e99e08ca9321#546fb5f289cd70b491fcb0b0cc6e8748>:0
  at System.Net.Http.NSUrlSessionHandler.RemoveInflightData (Foundation.NSUrlSessionTask task, System.Boolean cancel) <0x103db6440 + 0x000eb> in <0da8ced3e38d42039920e99e08ca9321#546fb5f289cd70b491fcb0b0cc6e8748>:0
  at System.Net.Http.NSUrlSessionHandler+NSUrlSessionHandlerDelegate.DidCompleteWithError (Foundation.NSUrlSession session, Foundation.NSUrlSessionTask task, Foundation.NSError error) <0x103db77d0 + 0x00113> in <0da8ced3e38d42039920e99e08ca9321#546fb5f289cd70b491fcb0b0cc6e8748>:0
```

### Steps to Reproduce

?

### Expected Behavior

Not crashing.

### Actual Behavior

Crashing.

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version: ?
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
- Nuget Packages:
- Affected Devices:  Hardware Model:  iPhone11,6

**Comment by jfversluis** [comment] 2019-07-29 06:47
Hi @mclillill, thanks for the report. Without any code that triggers this it is kind of hard to understand what is going on here. Would you mind adding some relevant code or steps that lead up to this crash? If possible, a sample reproduction project?

Thanks!

**Comment by mclillill** [comment] 2019-07-29 08:42
@jfversluis Unfortunately I can't provide sample code. I also don't understand the code steps that lead up to the crash. I seems to happen randomly. I suspect some kind of threading issue. Sorry, I can't be of more help...

**Comment by ronsplinter** [comment] 2019-07-30 13:31
I am getting the same crash too. The strange thing is that when the app crashes, I can continue debugging or stop debugging. When I choose stop debugging and start the app again, I get the same issue. When I choose continue, and then stop and start debugging, the issue is gone. Until my app crashes because of another issue and I start debugging again. Then I am back to square one...

**Comment by mclillill** [comment] 2019-07-31 06:35
@ronsplinter Can you provice a sample app. You seem to be able to reproduce it? To me it happens randomly and I'm not allowed to share the code.

**Comment by ronsplinter** [comment] 2019-08-06 08:40
@mclillill I just tried to reproduce the problem but I was unable to. Somehow the issue disappeared. If I run into this again, I will try to reproduce and upload it.

**Comment by jfversluis** [comment] 2019-08-06 08:44
@ronsplinter did you use a newer version of Forms?

@mclillill I wish we could help but without any concrete information it's a bit hard to see what would be going wrong here. If Ron indeed is using a newer version could you please try that as well and see if that is better?

For now I'm closing this, if you can provide some more information on how this happens exactly please feel free to open it again or open a new issue.

**Closed by jfversluis** 2019-08-06 08:44 UTC
Labels: i/high, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:

**Comment by ronsplinter** [comment] 2019-08-06 08:46
@mclillill Yes, I updated to the newer Forms.

**Comment by jerryhuang-net** [comment] 2019-08-06 14:33
keep getting the crash every day.... below is the stack trace log just capture in run time:

  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <4fffe1dab0494c34a2a213216932b318>:0 
  at Foundation.NSNotificationCenter.RemoveObserversFromList (Foundation.NSObject observer, System.String aName, Foundation.NSObject anObject) [0x00010] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.157/src/Xamarin.iOS/Foundation/NSNotificationCenter.cs:131 
  at Foundation.NSNotificationCenter.RemoveObserver (Foundation.NSObject observer) [0x00034] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.157/src/Xamarin.iOS/Foundation/NSNotificationCenter.g.cs:177 
  at System.Net.Http.NSUrlSessionHandler.RemoveNotification () [0x00008] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:187 
  at System.Net.Http.NSUrlSessionHandler.RemoveInflightData (Foundation.NSUrlSessionTask task, System.Boolean cancel) [0x0004f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:216 
  at System.Net.Http.NSUrlSessionHandler+NSUrlSessionHandlerDelegate.DidCompleteWithError (Foundation.NSUrlSession session, Foundation.NSUrlSessionTask task, Foundation.NSError error) [0x0005b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:471

**Comment by jfversluis** [comment] 2019-08-06 14:37
@jerryhuang-net if you can provide us with a reproduction project on the latest Xamarin.Forms stable package please add it and reopen the issue so we can see it in action.

Thanks!
