### ISSUE TITLE
SearchBox FlowDirection not working

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9549] opened 2020-02-12 22:16 UTC
Hi,

I have set the FlowDirection for my page an it's working fine for all except the SearchBox

I am using Android

Here is the code:

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:TaqyeemConverter="clr-namespace:Taqyeem.Converters"
    xmlns:SyncfusionListView="clr-namespace:Syncfusion.ListView.XForms;assembly=Syncfusion.SfListView.XForms"
    xmlns:SyncfusionShimmer="clr-namespace:Syncfusion.XForms.Shimmer;assembly=Syncfusion.Core.XForms"
    xmlns:SyncfusionBorder="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
    xmlns:FFImageLoading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    mc:Ignorable="d" FlowDirection="RightToLeft"
    x:Class="Taqyeem.HomePage">
    <ContentView.Resources>
        <TaqyeemConverter:BoolInverseConverter x:Key="boolConverter"/>
    </ContentView.Resources>
    <NavigationPage.TitleView>
        <Grid ColumnSpacing="0" RowSpacing="0" BackgroundColor="{DynamicResource NavBarMainPageBackColor}">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="Auto" />
            </Grid.ColumnDefinitions>

            <Label x:Name="LabelNavigationTitle" Grid.Column="0" Text="Members" TextColor="{DynamicResource NavBarMainPageTextColor}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center" VerticalOptions="Center" />

            <Image Grid.Column="1" Source="Close.png" Margin="10" WidthRequest="35" HeightRequest="35" HorizontalOptions="End" VerticalOptions="Center" />
        </Grid>
    </NavigationPage.TitleView>
    <Grid ColumnSpacing="0" RowSpacing="0" Margin="5" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <SearchBar x:Name="SearchBoxMembers" Grid.Row="0" Placeholder="البحث.." Margin="0,20,0,20" TextChanged="OnFilterTextChanged" />

        <SyncfusionListView:SfListView x:Name="ListViewHomePage" Grid.Row="1" SelectionBackgroundColor="Transparent" IsScrollBarVisible="False" AutoFitMode="DynamicHeight" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" ItemSpacing="3" ItemTapped="ListViewHomePage_ItemTapped">
            <SyncfusionListView:SfListView.ItemTemplate>
                <DataTemplate>
                    <SyncfusionShimmer:SfShimmer x:Name="ShimmerMembers" VerticalOptions="Fill" IsActive="{Binding BindingContext.IsLoaded, Converter={StaticResource Key=boolConverter}, Source={x:Reference ListViewHomePage}}">
                        <SyncfusionShimmer:SfShimmer.CustomView>
                            <Grid VerticalOptions="Center" HeightRequest="100" HorizontalOptions="Start">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="100" />
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>

                                <SyncfusionBorder:SfBorder HorizontalOptions="Center" VerticalOptions="Center" CornerRadius="30" HeightRequest="60" WidthRequest="60" BorderWidth="0" BackgroundColor="Gray" />

                                <StackLayout Grid.Column="1" Spacing="10" VerticalOptions="Center">
                                    <SyncfusionBorder:SfBorder HeightRequest="20" WidthRequest="150" BorderWidth="0" BackgroundColor="Gray" />
                                    <SyncfusionBorder:SfBorder HeightRequest="20" WidthRequest="200" BorderWidth="0" BackgroundColor="Gray" />
                                </StackLayout>
                            </Grid>
                        </SyncfusionShimmer:SfShimmer.CustomView>
                        <SyncfusionShimmer:SfShimmer.Content>
                            <Grid ColumnSpacing="0" RowSpacing="0" HorizontalOptions="FillAndExpand">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>

                                <SyncfusionBorder:SfBorder Grid.Column="0" Grid.RowSpan="3" BorderColor="LightGray" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BorderWidth="1" CornerRadius="20">
                                    <FFImageLoading:CachedImage Source="{Binding nuwab_image}" LoadingPlaceholder="Logo.png" ErrorPlaceholder="Logo.png" FadeAnimationEnabled="True" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" DownsampleToViewSize="True">
                                        <FFImageLoading:CachedImage.HeightRequest>
                                            <OnIdiom x:TypeArguments="x:Double" Phone="60" Tablet="100" />
                                        </FFImageLoading:CachedImage.HeightRequest>
                                        <FFImageLoading:CachedImage.WidthRequest>
                                            <OnIdiom x:TypeArguments="x:Double" Phone="60" Tablet="100" />
                                        </FFImageLoading:CachedImage.WidthRequest>
                                    </FFImageLoading:CachedImage>
                                </SyncfusionBorder:SfBorder>

                                <Label Grid.Column="1" Grid.Row="0" Text="{Binding nuwab_name}" FontAttributes="Bold" TextColor="Red" HorizontalTextAlignment="Start" VerticalTextAlignment="Center" Margin="20,0,0,0" />
                                <Label Grid.Column="1" Grid.Row="1" Text="{Binding nuwab_name, StringFormat='Member# {0}'}" TextColor="Black" HorizontalTextAlignment="Start" VerticalTextAlignment="Center" Margin="20,0,0,0" />
                                <Label Grid.Column="1" Grid.Row="2" Text="{Binding nuwab_name}" TextColor="Black" HorizontalTextAlignment="Start" VerticalTextAlignment="Center" Margin="20,0,0,0" />

                                <BoxView Grid.ColumnSpan="2" Grid.Row="3" HeightRequest="1" BackgroundColor="LightGray" HorizontalOptions="FillAndExpand" Margin="8" />
                            </Grid>
                        </SyncfusionShimmer:SfShimmer.Content>
                    </SyncfusionShimmer:SfShimmer>
                </DataTemplate>
            </SyncfusionListView:SfListView.ItemTemplate>
        </SyncfusionListView:SfListView>
    </Grid>
</ContentView>

```

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by samhouts** [comment] 2020-02-13 17:18
Duplicate of #6538

**Closed by samhouts** 2020-02-13 17:18 UTC
Labels: a/rtl, a/searchbar, p/Android, s/unverified, t/bug :bug:
