### ISSUE TITLE
[Bug] Using an old version of the Google Play Developer API

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#6528] opened 2019-06-14 05:57 UTC
### Description

My Xamarin Forms app is receiving the following somewhat scary message in the Google Play Console:

```We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date. Learn more: https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html```

I'm not directly calling any older Google Play Developer APIs, at least that I'm aware of. Is this a known issue with Xamarin.Forms or Xamarin.Forms.Maps? If not, can you suggest a reasonable way to figure out which package is triggering this message?

The app does depend on a number of NuGet packages (listed below). However, most of the ones that might use Google Play APIs are semi-official plugins with fairly recent updates.

Thanks.

### Basic Information

- Version with issue:
- Last known good version: Unknown
- IDE: VS 2019 latest
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages:

```
PM> get-package
Id                                  Versions                                 ProjectName                                                                                                                                                                                            
--                                  --------                                 -----------                 
Angle                               {2.0.0}                                  Sideroads.Android                                                                                                                                                                                      
AsyncUsageAnalyzers                 {1.0.0-alpha003}                         Sideroads.Android                                                                                                                                                                                      
DarkSkyCore                         {5.1.15}                                 Sideroads.Android                                                                                                                                                                                      
Geo                                 {0.15.0}                                 Sideroads.Android                                                                                                                                                                                      
Geocoding.Core                      {4.0.1}                                  Sideroads.Android                                                                                                                                                                                      
Geocoding.Google                    {4.0.1}                                  Sideroads.Android                                                                                                                                                                                      
GeoTimeZone                         {3.2.0}                                  Sideroads.Android                                                                                                                                                                                      
HtmlAgilityPack                     {1.11.7}                                 Sideroads.Android                                                                                                                                                                                      
Markdig                             {0.17.0}                                 Sideroads.Android                                                                                                                                                                                      
Microcharts                         {0.7.1}                                  Sideroads.Android                                                                                                                                                                                      
Microcharts.Forms                   {0.7.1}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.AppCenter                 {2.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.AppCenter.Analytics       {2.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.AppCenter.Crashes         {2.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.CSharp                    {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Data.Sqlite.Core          {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.DotNet.PlatformAbstrac... {2.1.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.EntityFrameworkCore       {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.EntityFrameworkCore.Ab... {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.EntityFrameworkCore.An... {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.EntityFrameworkCore.Re... {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.EntityFrameworkCore.Sq... {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Caching.Abs... {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Caching.Memory {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Configuration  {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Configurati... {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Configurati... {2.2.4}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.DependencyI... {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.DependencyI... {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.DependencyM... {2.1.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Logging        {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Logging.Abs... {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Options        {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Extensions.Primitives     {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Graph                     {1.15.0}                                 Sideroads.Android                                                                                                                                                                                      
Microsoft.Graph.Core                {1.15.0}                                 Sideroads.Android                                                                                                                                                                                      
Microsoft.Identity.Client           {4.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.NETCore.Platforms         {2.2.1}                                  Sideroads.Android                                                                                                                                                                                      
Microsoft.Win32.Primitives          {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
NETStandard.Library                 {2.0.3}                                  Sideroads.Android                                                                                                                                                                                      
Newtonsoft.Json                     {12.0.2}                                 Sideroads.Android                                                                                                                                                                                      
NLog                                {4.6.4}                                  Sideroads.Android                                                                                                                                                                                      
NodaTime                            {2.4.5}                                  Sideroads.Android                                                                                                                                                                                      
Plugin.CurrentActivity              {2.1.0.4}                                Sideroads.Android                                                                                                                                                                                      
Plugin.InAppBilling                 {2.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Plugin.Permissions                  {4.0.2-beta}                             Sideroads.Android                                                                                                                                                                                      
Plugin.StoreReview                  {2.0.0.5}                                Sideroads.Android                                                                                                                                                                                      
Remotion.Linq                       {2.2.0}                                  Sideroads.Android                                                                                                                                                                                      
Rg.Plugins.Popup                    {1.1.5.188}                              Sideroads.Android                                                                                                                                                                                      
SharpKml.Core                       {5.0.1}                                  Sideroads.Android                                                                                                                                                                                      
SkiaSharp                           {1.68.0}                                 Sideroads.Android                                                                                                                                                                                      
SkiaSharp.Svg                       {1.60.0}                                 Sideroads.Android                                                                                                                                                                                      
SkiaSharp.Views                     {1.68.0}                                 Sideroads.Android                                                                                                                                                                                      
SkiaSharp.Views.Forms               {1.68.0}                                 Sideroads.Android                                                                                                                                                                                      
SolarCalculator                     {2.0.4}                                  Sideroads.Android                                                                                                                                                                                      
SQLitePCLRaw.bundle_green           {1.1.14}                                 Sideroads.Android                                                                                                                                                                                      
SQLitePCLRaw.core                   {1.1.14}                                 Sideroads.Android                                                                                                                                                                                      
SQLitePCLRaw.lib.e_sqlite3.android  {1.1.14}                                 Sideroads.Android                                                                                                                                                                                      
SQLitePCLRaw.provider.e_sqlite3.... {1.1.14}                                 Sideroads.Android                                                                                                                                                                                      
System.AppContext                   {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Buffers                      {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Collections                  {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Collections.Concurrent       {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Collections.Immutable        {1.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.ComponentModel               {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.ComponentModel.Annotations   {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.ComponentModel.TypeConverter {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Console                      {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Data.Common                  {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Diagnostics.Debug            {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Diagnostics.DiagnosticSource {4.5.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Diagnostics.Tools            {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Diagnostics.Tracing          {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Dynamic.Runtime              {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Globalization                {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Globalization.Calendars      {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Interactive.Async            {3.2.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO                           {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO.Compression               {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO.Compression.ZipFile       {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO.FileSystem                {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO.FileSystem.Primitives     {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.IO.Packaging                 {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Linq                         {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Linq.Expressions             {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Linq.Queryable               {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Memory                       {4.5.3}                                  Sideroads.Android                                                                                                                                                                                      
System.Net.Http                     {4.3.4}                                  Sideroads.Android                                                                                                                                                                                      
System.Net.Primitives               {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Net.Sockets                  {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Numerics.Vectors             {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.ObjectModel                  {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Reflection                   {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Reflection.Extensions        {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Reflection.Primitives        {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Reflection.TypeExtensions    {4.5.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Resources.ResourceManager    {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime                      {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.CompilerServices.... {4.5.2}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Extensions           {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Handles              {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.InteropServices      {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.InteropServices.R... {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Numerics             {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Serialization.For... {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Serialization.Pri... {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Runtime.Serialization.Xml    {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Security.Cryptography.Alg... {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Security.Cryptography.Enc... {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Security.Cryptography.Pri... {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Security.Cryptography.X50... {4.3.2}                                  Sideroads.Android                                                                                                                                                                                      
System.Security.SecureString        {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Text.Encoding                {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Text.Encoding.Extensions     {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Text.RegularExpressions      {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Threading                    {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Threading.Tasks              {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Threading.Timer              {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.ValueTuple                   {4.5.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.ReaderWriter             {4.3.1}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.XDocument                {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.XmlDocument              {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.XmlSerializer            {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.XPath                    {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
System.Xml.XPath.XmlDocument        {4.3.0}                                  Sideroads.Android                                                                                                                                                                                      
TimeZoneConverter                   {3.2.0}                                  Sideroads.Android                                                                                                                                                                                      
WeakEventListener                   {1.0.0}                                  Sideroads.Android                                                                                                                                                                                      
Xam.Forms.MarkdownView              {0.6.1-pre}                              Sideroads.Android                                                                                                                                                                                      
Xam.Plugins.Forms.ImageCircle       {3.0.0.5}                                Sideroads.Android                                                                                                                                                                                      
Xam.Plugins.Settings                {3.1.1}                                  Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Core.Common    {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Core.Runtime   {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Lifecycle.C... {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Lifecycle.L... {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Lifecycle.L... {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Lifecycle.R... {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Arch.Lifecycle.V... {1.1.1.1}                                Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Animated... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Annotations {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.AsyncLay... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Collections {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Compat      {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Coordina... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Core.UI     {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Core.Utils  {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.CursorAd... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.CustomTabs  {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.CustomView  {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Design      {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Document... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.DrawerLa... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Fragment    {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Interpol... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Loader      {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.LocalBro... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Media.Co... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Print       {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.SlidingP... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.SwipeRef... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Transition  {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v4          {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v7.AppCo... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v7.CardView {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v7.Media... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v7.Palette  {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.v7.Recyc... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Vector.D... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.Versione... {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Android.Support.ViewPager   {28.0.0.1}                               Sideroads.Android                                                                                                                                                                                      
Xamarin.Build.Download              {0.4.11}                                 Sideroads.Android                                                                                                                                                                                      
Xamarin.Essentials                  {1.1.0}                                  Sideroads.Android                                                                                                                                                                                      
Xamarin.Firebase.Ads                {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Firebase.Analytics          {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Firebase.Analytics.Impl     {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Firebase.Common             {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Firebase.Iid                {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Forms                       {3.6.0.344457}                           Sideroads.Android                                                                                                                                                                                      
Xamarin.Forms.Contacts              {1.0.5}                                  Sideroads.Android                                                                                                                                                                                      
Xamarin.Forms.Maps                  {3.6.0.344457}                           Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Ads      {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Ads.Lite {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Base     {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Basement {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Gass     {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Location {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Maps     {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.GooglePlayServices.Tasks    {60.1142.1}                              Sideroads.Android                                                                                                                                                                                      
Xamarin.Plugin.FilePicker           {2.0.135}                                Sideroads.Android 
```

**Comment by jfversluis** [comment] 2019-06-14 07:16
In the link from Google I see in-app billing mentioned specifically. In your list of NuGet's I see James' plugin for that. After looking at his issues there I came across this one: https://github.com/jamesmontemagno/InAppBillingPlugin/issues/221

It seems (at least) this one is the culprit. 

Unfortunately, this is not something that has to do with Forms directly. I will close the issue here, I suggest you add to the issue I mentioned above.

**Closed by jfversluis** 2019-06-14 07:16 UTC
Labels: p/Android, s/unverified, t/bug :bug:

**Comment by mfeingol** [comment] 2019-06-14 15:39
Thanks, @jfversluis; really appreciate the help.

**Comment by AndreCL** [comment] 2019-06-22 15:07
Hi, having the same issue on a Xamarin Android project. Like mfeingol.
But I have no nuget packages installed:

Basic Information
IDE: VS 2019 latest
Platform Target Frameworks: Android: 9.0
Nuget Packages:
```
PM> get-package
No packages installed.
PM> 
```

**Comment by jfversluis** [comment] 2019-06-23 13:20
Do you have any warnings in your project saying that you are using obsolete methods?

**Comment by AndreCL** [comment] 2019-06-23 19:23
It is not showing any warnings. 
It is a fairly simple app. A main activity with a webview. This webview loads a website (simple HTML, CSS, JS) that is stored in the assets folder.

From the previous version, these were the changes:
- Added the 64bit (see https://stackoverflow.com/questions/54537469/targeting-64-bit-architectures-on-xamarin-android)
- Increased target Android APK version
- Did minor changes to the HTML/CSS/JS code
- Made a custom class inheriting from WebViewClient. All it contains is override method to ShouldOverrideUrlLoading(WebView view, IWebResourceRequest request)

**Comment by rvalitov** [comment] 2019-07-10 12:49
I have the same problem with latest release of Visual Studio 2019. I don't see any warning during build process, I see a warning message in the Google's developer console that I should upgrade to Google Play Developer API v.3:

![image](https://user-images.githubusercontent.com/16267156/60970227-34205980-a32a-11e9-96d7-bf70c3064560.png)

@jfversluis in the link it says not only about in-app purchase, but also about distribution workflow. I have a simple app without any in-app purchase. I believe the problem here is related to the distribution workflow, may be the Visual Studio uses old methods to upload the app in the dialog below?

![image](https://user-images.githubusercontent.com/16267156/60969887-641b2d00-a329-11e9-96fb-78648f11f804.png)

**Comment by Zero-K** [comment] 2019-07-11 17:14
Same issue here. It was working fine without any errors when I pushed a build a couple days ago. Visual Studios updated to 16.1.6 today, and now I'm getting this same error.

**Comment by JonDouglas** [comment] 2019-08-07 21:05
@rvalitov Does this occur if you ad hoc publish an APK or .AAB to the play store? I suspect it's an issue with the publishing workflow of Google Play which uses that API under the hood.

**Comment by MouthOfMadness** [comment] 2019-08-07 21:18
I just started receiving this error, my last good build was about a week ago.

It's not clear to me if the publish task is failing on the google play api V3, or it's actually a 64 bit compiler issue.

##[error]Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"releaseValidationErrorKeyNotCompliantWith64BitRequirementError","message":"Release is not compliant with the Play 64-bit requirement."}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"releaseValidationErrorKeyNotCompliantWith64BitRequirementError","message":"Release is not compliant with the Play 64-bit requirement."}]}
My android build task looks like this:
task: XamarinAndroid@1
displayName: "build android"
inputs:
projectFile: '**/droid.csproj'
outputDirectory: '$(outputDirectory)'
configuration: '$(buildConfiguration)'
msbuildArchitectureOption: x64
createAppPackage: true

My publish task looks like this:
task: GooglePlayRelease@2
inputs:
authType: 'JsonFile'
serviceAccountKey: $(googleApi.secureFilePath)
apkFile: '$(outputDirectory)/*.apk'
track: 'internal'
changeLogFile: 'droid/ReleaseNotes.txt'

**Comment by JonDouglas** [comment] 2019-08-07 21:21
@MouthOfMadness The 64 bit requirement requires 64-bit ABIs inside your Android project. These are properties you can enable here: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/cpu-architectures?tabs=windows#how-to-specify-supported-architectures

From the looks of the task, that is just running MSBuild as x64 which isn't going to help the requirement.

It looks more specific to the 64-bit issue here given that you are not using the Visual Studio Publishing workflow which is a separate issue regarding it using v2 under the hood instead of v3.

Can you double check that you have arm64 / x86_64 ABIs in your release artifact? (APK).

**Comment by MouthOfMadness** [comment] 2019-08-07 21:32
This is one of the first things I checked, I've tried checking them all
My current configuration is: x86_64;arg64-v8a

I've also bumped the min android version of (API Level 27 - Oreo) and target to (API Level 28 - Pie)

**Comment by JonDouglas** [comment] 2019-08-07 21:37
@MouthOfMadness You're right. Thanks for clearing that up first. It's an issue here: https://github.com/microsoft/google-play-vsts-extension/issues/129 Again the same root cause is that v2 apis are used under the hood when they need to use v3. Luckily the fixed it 3 hours ago!

**Comment by MouthOfMadness** [comment] 2019-08-07 21:42
@JonDouglas  
I saw the update when it was only 2 hours old, but I receive the same error, tried updating the task from GooglePlayRelease@2 to GooglePlayRelease@3 without luck. Also attempted to update the component from the market but claimed the latest version was installed.

**Comment by JonDouglas** [comment] 2019-08-07 21:44
@MouthOfMadness Does uploading manually work?

**Comment by MouthOfMadness** [comment] 2019-08-07 22:00
@JonDouglas 

Yes, manual upload works.
However, there's a correction in my previous statement,

When I use GooglePlayRelease@3, I get a different error: 
##[error]Error: Release is not compliant with the Play 64-bit requirement.

Which is different from that 403 error I was receiving with version 2.

**Comment by andrelundin** [comment] 2019-08-08 06:24
Make sure you also target 64-bit in release, not only in debug.
Jon: Thank you for the heads up about the fix. I will try again tonight and see if it works properly now.

**Comment by MouthOfMadness** [comment] 2019-08-09 18:36
@JonDouglas 

Here's the fix to my issue.

After updating my pipeline to use the GoogleRelease@3 task, I had to hand edit the android csproj file to be arm64-v8a;x86_64.

It all worked after that.

**Comment by karhukoti** [comment] 2019-10-29 09:22
@MouthOfMadness I am new to this but having this issue.   What do you mean (and how to fix) "After updating my pipeline to use the GoogleRelease@3 task" ?

Thanks in advance.

**Comment by EvoPulseGaming** [comment] 2019-11-04 03:05
I see your comment from Aug 9, and I have the same question.... How do you update the pipeline?

**Comment by jfversluis** [comment] 2019-11-04 09:15
I think this is a reference to the Azure DevOps task for this. You can choose the version of the task to use for backwards compatibility. If you are using YAML, you can specify the version with the `@3` syntax, where 3 would be the number. In the classic editor you can choose it through the dropdown box.

More info can be found here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions

**Comment by boris-df** [comment] 2019-11-19 09:46
I think i missed something in this discussion - so pardon me for asking:

i'm using Visual Studio 2019 V16.3.4
I build a Xamarin.Android Project (release)
Then i "Archive..." it 
Then i click on "Distribute" in the Archive Manager

Google Play Store shows me a big warning on the top of the dashboard of this App, that my is using an old "Google Play Developer API" and i should switch to Version 3

I have no idea what to do nor where i should look at. I thought it has to do with the upload/distribute-process but non of what you all wrote here says me anything - as far as i know i have no azure tasks to look at?! It's all in Visual Studio.

any hint for me about where i could look / search if some nuget or other library is using the old API or if this is a known problem with VS 16.3.4 and fixed with later ones would be helpful.

Thank you

**Comment by andreas-gabriel** [comment] 2019-11-20 06:32
Having exactly the same problem and would be very happy about some help.
The only warning I have is because of this piece of code, but I think that should be OK:

 if (Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                var importance = Android.App.NotificationImportance.Max;
                NotificationChannel notificationChannel = new NotificationChannel("myChannelId" + notifyID, "myChannelName", importance);
                notificationManager.CreateNotificationChannel(notificationChannel);
                builder = new NotificationCompat.Builder(ApplicationContext, notificationChannel.Id);
            }
            else
            {
                builder = new NotificationCompat.Builder(ApplicationContext);
                builder.SetChannelId("myChannelId" + notifyID);
            }



Thank you

**Comment by MouthOfMadness** [comment] 2019-11-21 17:12
@boris-df @andreas-gabriel 

I experienced 2 problems, the VSTS task endpoint and VS not properly updating the project file to do a 64x build.

**Visual Studio:**
The way I fixed VS is - **I opened the *.csproj file in notepad** and edited the file so the API's would do a 64x build.  I often find that VS does get's a little confused in handling the project file and requires a manual intervention on your part; **verify that the release build is doing a 64x build**.

**Pipeline task**
At the time I first raised this issue, the pipeline task GooglePlayRelease@2 hadn't caught up to the 64x endpoint required by google, so I used GooglePlayRelease@3.  However, version 2 of the endpoint appears to be updated, this should no longer be an issue (at least in my testing).

Hope that helps.

**Comment by karhukoti** [comment] 2019-11-23 13:00
@MouthOfMadness Hi, can you please specify **exactly where** one needs to change this pipeline you mention?  

What file and/or what piece of UI is this?

**Comment by rvalitov** [comment] 2019-11-23 19:10
Dear all,
I also experienced this issue, but I didn't modify the VS project file. I just updated the VS to latest version and it worked. 

Below is a partial content from my VS Android project file (.csproj) that may help you with the config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>None</AndroidLinkMode>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <BundleAssemblies>false</BundleAssemblies>
    <MandroidI18n />
    <AndroidSupportedAbis />
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidUseAapt2>true</AndroidUseAapt2>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <BundleAssemblies>false</BundleAssemblies>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <AndroidSupportedAbis>armeabi-v7a;x86;x86_64;arm64-v8a</AndroidSupportedAbis>
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <MandroidI18n />
  </PropertyGroup>
</Project>
```

**Comment by karhukoti** [comment] 2019-11-24 09:46
What version of VS are you now running @rvalitov  ?

**Comment by EvoPulseGaming** [comment] 2019-11-24 16:10
Try visual studio 2019, preview

**Comment by andreas-gabriel** [comment] 2019-11-24 19:01
Same as karhukoti, I will try out the preview

**Comment by Eltee-Taiwo** [comment] 2019-11-24 19:18
@karhukoti and @andreas-gabriel Please let me know if that works for you. I did a release yesterday that was fine but did a release today and got that warning.

Thanks.

**Comment by andreas-gabriel** [comment] 2019-11-24 21:05
Same as karhukoti, I will try out the preview

**Comment by andreas-gabriel** [comment] 2019-11-24 21:06
still the same problem with the preview

**Comment by rvalitov** [comment] 2019-11-24 23:12
@karhukoti as far as I remember it was VS 2019 with version around 16.2 that fixed the issue for me in July or August 2019. And I didn't experience this problem ever since then. Now I have 16.3.10. May be I skipped some VS releases, but usually I update to latest versions of VS when they become available.

**Comment by andreas-gabriel** [comment] 2019-11-25 06:59
can I help you? Can you reproduce the issue? Is my code/manifest/nuget packages interesting for you? I detected the issue with 16.3.9 (and 16.3.10). Before I didn't upload for a longer time, so I can't say what has been my last good version.

**Comment by karhukoti** [comment] 2019-11-25 10:56
I am running very latest VS 16.3.10, installed yesterday.    After clicking the Distribute button and getting the release gets publish, my Release Management dashboard at the top still says today:


ACTION REQUIRED: Your automated publishing to Google Play will stop working on December 1, 2019
Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. Learn more

**Comment by jfversluis** [comment] 2019-11-25 12:23
Hey everyone! Thanks for the very lively discussion here. 

I think we have determined that this is not a Xamarin.Forms problem, but has to do with tooling in either Visual Studio, Azure DevOps or whatever other way you might have of delivering versions to the Google Play Store.

Have a good look at what tools you are using to deliver your app to the store and see if you can update anything in that area. I would find it hard to believe that the bigger projects will not have updated these API endpoints by now.

For now, I will lock the conversation here since it isn't relevant for us. For more information please refer to some of the links below.

- Fastlane issue (resolved): https://github.com/fastlane/fastlane/issues/14573
- Azure DevOps task issue (resolved): https://github.com/microsoft/google-play-vsts-extension/issues/129
- StackOverflow question: https://stackoverflow.com/questions/56700332/what-is-we-ve-detected-that-your-app-is-using-an-old-version-of-the-google-play

If everything else fails, you will still be able to create an APK locally and upload it to the Play Store manually through the portal.
