### ISSUE TITLE
Java.Lang.NullPointerException using FastRenderers

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9538] opened 2020-02-12 01:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/904413/javalangnullpointerexception-using-fastrenderers.html)._

---
My app is throwing a NullPointerException when using FastRenderers.
The exception is coming from a Suncfusion conttrol and I have also reported it to them, though I am not sure where the source of the issue lies.

If I use the Forms.SetFlags("UseLegacyRenderers"); option, the app runs fine.

This is the stack trace.

	
	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#
 	0x33 in Android.Runtime.DynamicMethodNameCounter.48	C#
 	0x12 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:157,13	C#
 	0x8E in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x21 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod	C#
 	0x30 in Android.Widget.TextView.set_HintFormatted	C#
 	0xF in Android.Widget.TextView.set_Hint	C#
 	0x161 in Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.GetDesiredSize at D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:127,4	C#
 	0xB3 in Xamarin.Forms.Platform.Android.Platform.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1333,4	C#
 	0x3 in Xamarin.Forms.Forms.AndroidPlatformServices.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Forms.cs:776,5	C#
 	0x2D in Xamarin.Forms.VisualElement.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:779,4	C#
 	0x3 in Xamarin.Forms.VisualElement.OnMeasure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:762,4	C#
 	0x56 in Xamarin.Forms.VisualElement.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:644,4	C#
 	0x57 in Xamarin.Forms.VisualElement.Measure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:702,4	C#
 	0x36 in Syncfusion.SfChart.XForms.Droid.SfChartRenderer.GetNativeView	C#
 	0x4A in Syncfusion.SfChart.XForms.Droid.ChartSeriesMapping.OnDoughnuSeriesPropertiesChanged	C#
 	0xB2D in Syncfusion.SfChart.XForms.Droid.ChartSeriesMapping.GetNativeSeries	C#
 	0x125 in Syncfusion.SfChart.XForms.Droid.SfChartMapping.OnChartPropertiesChanged	C#
 	0xA2 in Syncfusion.SfChart.XForms.Droid.SfChartRenderer.GetNativeChart	C#
 	0x95 in Syncfusion.SfChart.XForms.Droid.SfChartRenderer.OnElementChanged	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Syncfusion.SfChart.XForms.SfChart>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231,4	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Syncfusion.SfChart.XForms.SfChart>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x21 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:344,4	C#
 	0xC0 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:138,6	C#
 	0x14C in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:110,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetPackager at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:440,4	C#
 	0xDD in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:128,4	C#
 	0x33 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:391,4	C#
 	0x1B in Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:56,5	C#
 	0x24 in Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_	C#
 	0x23 in Android.Runtime.DynamicMethodNameCounter.48	C#

---
#### Visual Studio Feedback System on 2/3/2020, 05:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### solomon.fried on 2/6/2020, 07:58 AM: 

This seems to be a duplicate of <br><br>https://github.com/xamarin/Xamarin.Forms/issues/8801<br><br>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-02-12 01:53
Duplicate of #8801

**Closed by samhouts** 2020-02-12 01:53 UTC
Labels: a/fastrenderers, feedback-ticket, i/high, p/Android, s/unverified, t/bug :bug:
