### ISSUE TITLE
Android textAllCaps no longer works

### ISSUE THREAD

**Issue by atexinspect** [xamarin/Xamarin.Forms#11703] opened 2020-08-08 12:50 UTC
### Description
Android textAllCaps no longer works when using XF 4.8.0.1269

### Steps to Reproduce

1. Install XF 4.8.0.1269
2. Run Android App
3. Button text is always in capitals

### Expected Behavior
Button text should be camel case

### Actual Behavior
Button text always capitals

### Basic Information

- Version with issue:
- Last known good version: XF 4.7.0.1260
- IDE: VS 2019 V16.7.0
- Platform Target Frameworks: 
  - Android:

**Comment by rmarinho** [comment] 2020-08-10 09:56
@atexinspect text on android was always all caps no? do you have an example we can look?! 

Thanks

**Comment by atexinspect** [comment] 2020-08-10 17:54
In styles.xml 
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <style name="Theme.Splash"
        parent="android:Theme">
    <item name="android:windowBackground">@drawable/splashscreen</item>
    <item name="android:windowNoTitle">true</item>
  </style>
  <style name="MainTheme" parent="MainTheme.Base">
  </style>
  
  <style name="MainTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
    
    <item name="windowNoTitle">true</item>
    
    <item name="windowActionBar">false</item>
    
    
    <item name="colorPrimary">#2196F3</item>
    
    <item name="colorPrimaryDark">#1976D2</item>
    
    <item name="colorAccent">#96BCE3</item>
    
    <item name="windowActionModeOverlay">true</item>
    <item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item> 
    <item name="android:colorPressedHighlight">@color/ListViewSelected</item>
    <item name="android:colorLongPressedHighlight">@color/ListViewHighlighted</item>
    <item name="android:colorFocusedHighlight">@color/ListViewSelected</item>
    <item name="android:colorActivatedHighlight">@color/ListViewSelected</item>
    <item name="android:activatedBackgroundIndicator">@color/ListViewSelected</item>

    <item name="android:textAllCaps">false</item>  

     
    
  </style>   
  <style name="AppCompatDialogStyle" parent="Theme.AppCompat.Light.Dialog">
    <item name="colorAccent">#96BCE3</item>
  </style>
</resources>

Tabbar.xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.TabLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_tabs"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="?attr/colorPrimary"
    app:tabTextAppearance="@android:style/TextAppearance.Widget.TabWidget"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    app:tabIndicatorColor="@android:color/white"
    app:tabGravity="fill"
    app:tabMode="fixed" /

Tabbar.xml still gives correct camel case on tabs with XF 4.7.0.1260 &  XF 4.8.0.1269

Regards
Paul.

**Comment by rmarinho** [comment] 2020-08-10 18:01
@atexinspect can you upload a small repro?!  Thanks

**Comment by atexinspect** [comment] 2020-08-10 19:02
https://github.com/atexinspect/CapsTest

**Comment by Pantheas** [comment] 2020-08-12 07:35
Creating a custom button renderer and calling `SetAllCaps(false);` does not work aswell...

**Comment by Pantheas** [comment] 2020-08-17 14:52
@atexinspect setting `TextTransform="None"` in global Button style worked for me...

**Comment by atexinspect** [comment] 2020-08-17 20:36
> @atexinspect setting `TextTransform="None"` in global Button style worked for me...

Worked for me too. Thanks.

**Comment by manikandantk88** [comment] 2020-09-01 04:32
@atexinspect Thanks for the solution. Worked.

**Comment by kevcrooks** [comment] 2020-11-16 09:50
We'd previously fixed the issue using the workaround mentioned above too.

We tried removing it just now on Xamarin.Forms version `4.8.0.1687`, and the capitalisation issue seems to have been fixed for us. I haven't checked which version this seems to have been fixed from though.

**Comment by Cfun1** [comment] 2020-11-30 12:30
@samhouts isn't a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/11556 ?

**Comment by rmarinho** [comment] 2020-12-02 09:00
This should be fixed by  #12170

**Closed by rmarinho** 2020-12-02 09:00 UTC
Labels: 4.8.0, e/3 :clock3:, i/regression, in-progress, p/Android, t/bug :bug:
