### ISSUE TITLE
[Bug] WPF: ViewCell content width does incorrect update

### ISSUE THREAD

**Issue by Xamarin2019** [xamarin/Xamarin.Forms#9029] opened 2019-12-27 15:15 UTC
### Description
If the ListView width changes on WPF (e.g. on resizing the window), the part of ViewCell's  is resized but the others ViewCell's is not resized. The behavior depends on the content, if StackLayout, then when the application starts,  the first few Viewcell's are incorrect width. After repeatedly changing the window width and scrolling, Viewcell's have different widths in the same ListView.

### Steps to Reproduce
Try to make Viewcell's in the ListView with elements bound to the left and right side.
For example: the text of the left edge and the checkbox on the right

### Expected Behavior
The ViewCell's content should resize whenever the ListView's width changes, such that the checkboxes stay near the right window border.

### Actual Behavior
Checkboxes disappear beyond the window border or may have a different distance from the window border in the same ListView.

### Basic Information

- Version with issue: Latest stable 4.4.0.991265
- IDE: Visual Studio 15.9.18
- Platform Target Frameworks: WPF: .NET Framework 4.6.1

### Screenshots
In the first case of ListView, I applied StackLayout in the second Grid, and in the third I tried to fix this behavior by changing the width of Viewcell's on the width change event, but it still doesn't always work.
On Android all three Listviews work as expected.

**At start**
![image](https://user-images.githubusercontent.com/59281307/71521030-1642b300-28d0-11ea-8309-130ec8654469.png)
**After scrolling**
![image](https://user-images.githubusercontent.com/59281307/71521075-383c3580-28d0-11ea-84be-a21e5500b9f7.png)
**full screen mode**
![image](https://user-images.githubusercontent.com/59281307/71521254-fc55a000-28d0-11ea-848b-1cb5e5fcc56d.png)

**Return from full screen mode**
![image](https://user-images.githubusercontent.com/59281307/71521300-2eff9880-28d1-11ea-8297-bf1423fe4569.png)
**Changing the window width and scrolling**
![image](https://user-images.githubusercontent.com/59281307/71521344-6bcb8f80-28d1-11ea-8d1a-b8902c9b90d4.png)

**On Android 4.4 is OK**
![image](https://user-images.githubusercontent.com/59281307/71520982-e1366080-28cf-11ea-9f97-a10346ad924f.png)

### Reproduction Link

[AppListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4005597/AppListViewBug.zip)
without **packages** folder

**Comment by Xamarin2019** [comment] 2019-12-27 15:24
And why SeparatorVisibility and SeparatorColor has no effect on WPF ListView?

**Comment by VladislavAntonyuk** [comment] 2019-12-28 06:06
Might be fixed by https://github.com/xamarin/Xamarin.Forms/pull/8440

**Comment by Xamarin2019** [comment] 2019-12-28 06:16
> Might be fixed by #8440
Здравствуйте, Владислав. Насколько я понял в приведенной Вами ссылке речь о высоте первого элемента списка. Здесь проблемы с шириной элементов списка, причем зависит ов внутреннего содержимого.

**Comment by VladislavAntonyuk** [comment] 2019-12-28 06:24
> Might be fixed by #8440
> Здравствуйте, Владислав. Насколько я понял в приведенной Вами ссылке речь о высоте первого элемента списка. Здесь проблемы с шириной элементов списка, причем зависит от внутреннего содержимого.

Здравствуйте, на скриншоте в pull request вы можете увидеть отличие до и после ( listview cell занимает все пространство, как это работает на других платформах). Я думаю это может решить проблему, если я ее правильно понял.

**Comment by Xamarin2019** [comment] 2019-12-28 06:55
> ### Description
> If the ListView width changes on WPF (e.g. on resizing the window), the part of ViewCell's is resized but the others ViewCell's is not resized. The behavior depends on the content, if StackLayout, then when the application starts, the first few Viewcell's are incorrect width. After repeatedly changing the window width and scrolling, Viewcell's have different widths in the same ListView.
> 
> ### Steps to Reproduce
> Try to make Viewcell's in the ListView with elements bound to the left and right side.
> For example: the text of the left edge and the checkbox on the right
> 
> ### Expected Behavior
> The ViewCell's content should resize whenever the ListView's width changes, such that the checkboxes stay near the right window border.
> 
> ### Actual Behavior
> Checkboxes disappear beyond the window border or may have a different distance from the window border in the same ListView.
> 
> ### Basic Information
> * Version with issue: Latest stable 4.4.0.991265
> * IDE: Visual Studio 15.9.18
> * Platform Target Frameworks: WPF: .NET Framework 4.6.1
> 
> ### Screenshots
> In the first case of ListView, I applied StackLayout in the second Grid, and in the third I tried to fix this behavior by changing the width of Viewcell's on the width change event, but it still doesn't always work.
> On Android all three Listviews work as expected.
> 
> **At start**
> ![image](https://user-images.githubusercontent.com/59281307/71521030-1642b300-28d0-11ea-8309-130ec8654469.png)
> **After scrolling**
> ![image](https://user-images.githubusercontent.com/59281307/71521075-383c3580-28d0-11ea-84be-a21e5500b9f7.png)
> **full screen mode**
> ![image](https://user-images.githubusercontent.com/59281307/71521254-fc55a000-28d0-11ea-848b-1cb5e5fcc56d.png)
> 
> **Return from full screen mode**
> ![image](https://user-images.githubusercontent.com/59281307/71521300-2eff9880-28d1-11ea-8297-bf1423fe4569.png)
> **Changing the window width and scrolling**
> ![image](https://user-images.githubusercontent.com/59281307/71521344-6bcb8f80-28d1-11ea-8d1a-b8902c9b90d4.png)
> 
> **On Android 4.4 is OK**
> ![image](https://user-images.githubusercontent.com/59281307/71520982-e1366080-28cf-11ea-9f97-a10346ad924f.png)
> 
> ### Reproduction Link
> [AppListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4005597/AppListViewBug.zip)
> without **packages** folder

**Comment by Xamarin2019** [comment] 2019-12-28 07:02
#5682

**Comment by jfversluis** [comment] 2019-12-28 07:35
Can we keep the conversation in English please? That way most people can benefit from your knowledge :) thanks!

**Comment by VladislavAntonyuk** [comment] 2019-12-28 08:06
As @jsuarezruiz mentioned in related issue OnRenderSizeChanged is not called. Probably because we check if layout.HorizontalOptions.Expands.

Can you try to set horizontalOptions = FillAndExpands. Does it solve the issue?

**Comment by Xamarin2019** [comment] 2019-12-28 08:26
Here is a link to an example.
[https://github.com/Xamarin2019/Xamarin.Forms_ListView](url)

I tried different options.

**Comment by Xamarin2019** [comment] 2019-12-28 09:58
When the app starts
![image](https://user-images.githubusercontent.com/59281307/71541933-0929d080-2971-11ea-87d8-2e14b6bdf301.png)

Increase the width of the window
![image](https://user-images.githubusercontent.com/59281307/71541949-3aa29c00-2971-11ea-85e6-323aa208f827.png)

Scroll down ListView's
![image](https://user-images.githubusercontent.com/59281307/71541975-82c1be80-2971-11ea-8051-88d4f72d31a3.png)

Change the width a little more
![image](https://user-images.githubusercontent.com/59281307/71541989-b997d480-2971-11ea-9717-0b123677747a.png)

**Comment by VladislavAntonyuk** [comment] 2019-12-28 10:21
I will try with my PR and check if the issue is solved

**Comment by VladislavAntonyuk** [comment] 2019-12-28 16:41
I have fixed the issue. you can try it with new dll

[Debug.zip](https://github.com/xamarin/Xamarin.Forms/files/4007224/Debug.zip)

**Comment by VladislavAntonyuk** [comment] 2019-12-28 16:50
I have updated my pull request, because it is related to the same issue.

**Closed** 2020-04-15 19:44 UTC
Labels: a/listview, in-progress, p/WPF, t/bug :bug:
