### ISSUE TITLE
[Bug] Can't click Button in Xamarin.UWP for cursor offset exist

### ISSUE THREAD

**Issue by evolcano** [xamarin/Xamarin.Forms#11174] opened 2020-06-23 14:07 UTC
### Description
After upgrade Xamarin Git package, Cursor of Xamarin.UWP APP runs in Windows 10 react improperly. You just cann't click Button even the cursor is just above the Button. The Button is in ScrollView.

### Steps to Reproduce

1. Before scroll, everything is OK. The color of Button changed to bright gray when Cursor hover over, and can click
![滚动前](https://user-images.githubusercontent.com/18514981/85413288-31e7f700-b59d-11ea-8fbc-0c87037d7f06.png)

2. After scroll, the Button don't response to the hover of cursor, and can not click
![滚动后](https://user-images.githubusercontent.com/18514981/85413299-38766e80-b59d-11ea-98fc-b7d997d8c04d.png)

3. If you move the cursor lower to some extent，the Button response to the hover of cursor, and click is vaild
![实际位置](https://user-images.githubusercontent.com/18514981/85413328-45935d80-b59d-11ea-83be-f63489540590.png)

_Obvirouly, the offset exist._

### Expected Behavior
Button response to cursor.

### Actual Behavior
Button do not response to cursor properly.

### Basic Information

- Version with issue: 
- visual studio  16.6.2
- Xamarin.Forms  Version="4.7.0.968"
- netstandard 2.0
- TargetPlatformVersion:10.0.18362.0 - 10.0.17134.0
- Affected Devices: window 10

### Reproduction Link

Example code:
[examplecode.txt](https://github.com/xamarin/Xamarin.Forms/files/4819892/examplecode.txt)

**Comment by samhouts** [comment] 2020-06-23 16:00
perhaps related to https://github.com/xamarin/Xamarin.Forms/issues/11106

**Comment by rmarinho** [comment] 2020-06-23 16:29
Hum, something weird here, i can't reproduce, can you take a look at this sample @evolcano see what i m missing.

Thanks 

[Issue11106_11174.zip](https://github.com/xamarin/Xamarin.Forms/files/4820650/Issue11106_11174.zip)

**Comment by evolcano** [comment] 2020-06-24 00:47
Hi, @rmarinho 
    Thank you!
    Issue11106_11174.zip is fine on my computer. The only difference which I could found  is the TargetPlatformVersion of UWP Project:
**1.Issue11106_11174**
    
![image](https://user-images.githubusercontent.com/18514981/85482341-a64e8480-b5f5-11ea-8707-c4a6b9cc4516.png)

**2. My example project**
![image](https://user-images.githubusercontent.com/18514981/85482592-c67e4380-b5f5-11ea-8925-129815c73a51.png)

According to  #11106 which samhouts mentioned before, maybe Windows 10, version 1903 (10.0; Build 18362) cause the error due to ScrollView. But the scroller is OK just one week before. 

  ps: my test solution

[App21.zip](https://github.com/xamarin/Xamarin.Forms/files/4822592/App21.zip)

**Comment by MagicAndre1981** [comment] 2020-06-24 06:54
I also can't click buttons in UWP. Eventhandler is not fired at all as breakpoint is not hit. 

I use NavigationPage, no Shell and have a Grid Layout inside a ScrollView. On a different page without ScrollView, the click event is fired and clickedhandler is called.

MinVersion: 16299/Target: 19041, XF 4.6 SR4 worked, upgraded to 4.7 and it is broken.

**Comment by evolcano** [comment] 2020-06-24 16:41
@MagicAndre1981  It turns out like after upgrade Xamarin,  as long as you use a ScrollView and scrolled, the Y coordinate of Cursor  is mis-culculated, The offset maybe relate to ScrollView  scrolled.

**Comment by rmarinho** [comment] 2020-06-25 15:32
Thanks we identified the issue and working for a fix ASAP

**Comment by MagicAndre1981** [comment] 2020-07-02 05:38
for me it works with [4.7 SR1](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-4.7.0-sr1.2)

**Comment by samhouts** [comment] 2020-07-13 23:29
closed by #11207

**Closed by samhouts** 2020-07-13 23:29 UTC
Labels: a/button, a/scrollview, e/2 :clock2:, i/regression, in-progress, p/UWP, t/bug :bug:
