### ISSUE TITLE
The TitleView has disappeared on iOS again

### ISSUE THREAD

**Issue by eddieyanez** [xamarin/Xamarin.Forms#15564] opened 2022-10-13 14:41 UTC
### Description
The TitleView has disappeared on iOS again. This is a similar issue to the one I have reported a while back https://github.com/xamarin/Xamarin.Forms/issues/13310, meaning that the issue is back.

### Steps to Reproduce

1. Create a brand-new Flyout Project in Visual Studio for Mac 2022.
2. Inside AboutPage.xaml
```
<ContentPage ...  />
```
add:
```
    <Shell.TitleView>
        <Label Text="Something"
               HorizontalOptions="StartAndExpand"
               VerticalOptions="StartAndExpand"
               HeightRequest="40"
               WidthRequest="100"
               BackgroundColor="Red"
               TextColor="White"
               />
    </Shell.TitleView>
```

### Expected Behavior
As on Android, but on iOS:
<img width="433" alt="Screenshot 2022-10-13 at 15 17 30" src="https://user-images.githubusercontent.com/1080027/195626799-4653568a-3d5a-4b31-a544-8cb5da93e0b7.png">

### Actual Behavior
See various versions of the simulator below, none working:
<img width="435" alt="Screenshot 2022-10-13 at 15 18 47" src="https://user-images.githubusercontent.com/1080027/195627017-5bb6c7f6-f6f5-4811-af45-4a319f5af9a0.png">
<img width="479" alt="Screenshot 2022-10-13 at 15 18 14" src="https://user-images.githubusercontent.com/1080027/195627013-58c7569d-d6c4-47a9-a7e0-fd26e29dd1f0.png">
<img width="468" alt="Screenshot 2022-10-13 at 15 21 08" src="https://user-images.githubusercontent.com/1080027/195627024-097497b8-0daa-497e-a5ee-5438699370b8.png">
<img width="490" alt="Screenshot 2022-10-13 at 15 22 16" src="https://user-images.githubusercontent.com/1080027/195627032-460fd614-8ae0-4f5e-96f2-3361c86b03f4.png">
<img width="436" alt="Screenshot 2022-10-13 at 15 22 59" src="https://user-images.githubusercontent.com/1080027/195627033-d0fa93bb-12bd-4117-8de4-6cee069b05e4.png">

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2196, but noticed also on latest 5.0.0.2515
- Last known good version: I don't know, apologies.
- Platform Target Frameworks: 
  - iOS:  Latest
  - Android: Latest
  - UWP:  N/A
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: N/A
- Affected Devices: Tried on simulators only.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.7 (build 11)
Installation UUID: aaa6b6a7-4988-4e48-9ca7-b3bc50b0060d

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	5.0.408
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	5.0.17
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.0.1 (21336)
Build 14A400

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:22:59 UTC

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/eyanez/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:23:04 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-05 17:23:04 UTC

Build Information
Release ID: 1703070011
Git revision: b625496a1b9780a50e1935e641beecf8979c795b
Build date: 2022-10-05 17:21:01+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64


```

</details>

### Screenshots
As above.

### Reproduction Link
As above.

### Workaround
No workarounds known.

**Comment by Goldstrike** [comment] 2022-10-14 08:23
This is probably related to this existing [bug](https://github.com/xamarin/Xamarin.Forms/issues/15512).

**Comment by jfversluis** [comment] 2022-11-01 12:12
Duplicate of #15512

**Closed by jfversluis** 2022-11-01 12:12 UTC
Labels: t/bug :bug:, s/unverified
