### ISSUE TITLE
The ItemTapped event for a grouped ListView is not working as expected.

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1439] opened 2017-12-20 01:52 UTC
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=60720

### Description
The ItemTapped event for a grouped ListView is not working as expected. 

ItemTappedEventArgs.Group is populated as expected, however ItemTappedEventArgs.Item is null sometimes, and not the item expected for all items further down the list.

In the sample i got two lists inside a GroupList, in the first list I get a Null in the ItemTappedEventArgs.item when I click the first element of that list, on my second list I get that behaviour (get a Null in the ItemTappedEventArgs) when I clicked the second element of that second list…

I’m sending a complete solution (in attach) where this is replicable.

### Basic Information

- Version with issue: 2.5.0
- Last known good version: 2.3.4.270

### Reproduction Link

[Grouping ListView.zip](https://github.com/xamarin/Xamarin.Forms/files/1573892/Grouping.ListView.zip)

**Comment by bkaankose** [comment] 2017-12-20 12:11
Possible duplication of this issue #1401

**Comment by mhdtahawi** [comment] 2017-12-21 08:16
I confirm I have the same issue as well.
For onItemSelected event, once the items are grouped my first item is null.
when the rest of the items are clicked, the onItemSelected has e.SelectedItem as the item before the one I actually selected. 

I have this issue on UWP

**Comment by r-a-y-w** [comment] 2017-12-21 22:12
@davidortinau @pauldipietro **Bugfix Proposal Attached** So, after hours of trying to debug Xamarin.Forms from my project, I decided to debug directly, with existing test cases (like G1763). I tried with multiple groups and without any groups.

[UWP-Fix-click-and-tap-returns-incorrect-ListItem-1439.patch.txt](https://github.com/xamarin/Xamarin.Forms/files/1580796/UWP-Fix-click-and-tap-returns-incorrect-ListItem-1439.patch.txt)

Explanation:
The problem seems to be with the ...UAP/ListViewRender.cs `void OnListItemClicked(object sender, ItemClickEventArgs e)` it passes the index based on the Items and not based on the global-index. This value gets sent to the  Xamarin core's ListView.cs `NotifyRowTapped` and again to `TemplatedItems.GetGroupIndexFromGlobal`. This method expects the index to be a globalIndex. So, I changed the original passed index to be the global-index value using the `TemplatedItemsView.TemplatedItems.GetGlobalIndexOfItem(e.ClickedItem)` method.

**Comment by seankanderson** [comment] 2017-12-29 17:55
Possibly experiencing the same issue on Android/UWP.  Have not tested iOS.  

When my listview has one item the itemselected event fires once but does not fire on subsequent attempts after navigating back.

Debug output annotated with user actions:


**** Sitting on my listview (with data template) bound to ICommand in view model, waiting for touch **** 
12-29 12:34:50.141 D/AbsListView(11423): viewType is heaer or footer
12-29 12:34:50.161 D/AbsListView(11423): viewType is heaer or footer
Thread finished: <Thread Pool> #3
The thread 0x3 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #5
The thread 0x5 has exited with code 0 (0x0).
12-29 12:35:15.737 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 0
12-29 12:35:15.824 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 1
12-29 12:35:15.825 D/AbsListView(11423): onTouchUp() mTouchMode : 0
12-29 12:35:15.826 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:15.826 D/AbsListView(11423): viewType is heaer or footer
**** Touched listitem, Command fired, data is sent to detail view successfully ****
[0:] ListViewHandleItem FIRED ***************
[0:] /data/user/0/com.nucleus_mobile.NucleusInvoice/files/DataVirtue.db
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
Thread started: <Thread Pool> #8
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
Thread started: <Thread Pool> #15
[0:] 0
[0:] 0
[0:] 0
[0:] 0
[0:] 0
12-29 12:35:16.395 D/Mono    (11423): DllImport searching in: '__Internal' ('(null)').
12-29 12:35:16.395 D/Mono    (11423): Searching for 'java_interop_jnienv_new_float_array'.
12-29 12:35:16.395 D/Mono    (11423): Probing 'java_interop_jnienv_new_float_array'.
12-29 12:35:16.395 D/Mono    (11423): Found as 'java_interop_jnienv_new_float_array'.
12-29 12:35:16.396 D/Mono    (11423): DllImport searching in: '__Internal' ('(null)').
12-29 12:35:16.396 D/Mono    (11423): Searching for 'java_interop_jnienv_set_float_array_region'.
12-29 12:35:16.396 D/Mono    (11423): Probing 'java_interop_jnienv_set_float_array_region'.
12-29 12:35:16.396 D/Mono    (11423): Found as 'java_interop_jnienv_set_float_array_region'.[0:] FileImageSourceHandler: Could not find image or image file was invalid: File: 

12-29 12:35:16.398 D/Mono    (11423): DllImport searching in: '__Internal' ('(null)').
12-29 12:35:16.398 D/Mono    (11423): Searching for 'java_interop_jnienv_get_float_array_region'.
12-29 12:35:16.398 D/Mono    (11423): Probing 'java_interop_jnienv_get_float_array_region'.
12-29 12:35:16.398 D/Mono    (11423): Found as 'java_interop_jnienv_get_float_array_region'.
12-29 12:35:16.404 D/Mono    (11423): DllImport searching in: '__Internal' ('(null)').
12-29 12:35:16.404 D/Mono    (11423): Searching for 'java_interop_jnienv_call_float_method_a'.
12-29 12:35:16.404 D/Mono    (11423): Probing 'java_interop_jnienv_call_float_method_a'.
12-29 12:35:16.404 D/Mono    (11423): Found as 'java_interop_jnienv_call_float_method_a'.
12-29 12:35:16.405 D/InputMethodManager(11423): HSI from window - flag : 0 Pid : 11423
12-29 12:35:16.410 I/Choreographer(11423): Skipped 30 frames!  The application may be doing too much work on its main thread.
12-29 12:35:16.412 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:16.412 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:16.424 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.426 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.467 W/ResourceType(11423): No package identifier when getting value for resource number 0x00000000
12-29 12:35:16.506 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.513 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.518 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.523 D/TextView(11423): setTypeface with style : 0
12-29 12:35:16.675 D/ScrollView(11423):  onsize change changed 
12-29 12:35:16.676 W/View    (11423): requestLayout() improperly called by md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewContainer{583b951 V.E...... ......ID 0,0-1300,6445} during layout: running second layout pass
12-29 12:35:16.677 I/ViewRootImpl@78cb657[MainActivity](11423): requestLayout is already in process
12-29 12:35:16.677 I/ViewRootImpl@78cb657[MainActivity](11423): requestLayoutDuringLayout is already in process
[0:] 0
12-29 12:35:16.730 W/View    (11423): requestLayout() improperly called by md5270abb39e60627f0f200893b490a1ade.NavigationPageRenderer{e64fab6 V.E...... ......ID 0,0-1440,2876 #1d} during second layout pass: posting in next frame
Thread finished: <Thread Pool> #11
The thread 0xb has exited with code 0 (0x0).
**** Sitting on the "detail" page, I touch the UWP/Android navigation back soft button, have also tried binding my own navigation calls to a button, with same results ****
12-29 12:35:28.246 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 0
12-29 12:35:28.353 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 1
12-29 12:35:28.382 D/InputMethodManager(11423): HSI from window - flag : 0 Pid : 11423
12-29 12:35:28.390 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.390 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.391 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.391 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.393 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.393 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.395 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.395 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.396 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.396 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.397 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.397 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.398 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.398 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.399 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.399 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.400 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.400 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.401 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.401 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.401 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.402 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.402 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.402 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.403 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.403 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.404 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.404 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.405 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.405 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.406 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.406 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.407 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.407 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.408 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.408 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.409 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.409 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.410 D/TextView(11423): SYANI: Clipboard API is calling: clearFilter()
12-29 12:35:28.410 D/TextView(11423): SYANI: Clipboard API is calling: unregisterClipboardEventListener()
12-29 12:35:28.475 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:28.487 D/AbsListView(11423): viewType is heaer or footer
[0:] Could not load image named: {0}: icons8_Plus_Math_32px.png
12-29 12:35:28.629 W/ResourceType(11423): No package identifier when getting value for resource number 0x00000000
12-29 12:35:28.631 E/BitmapFactory(11423): Unable to decode stream: java.io.FileNotFoundException: icons8_Plus_Math_32px.png (No such file or directory)
12-29 12:35:28.634 W/ResourceType(11423): No package identifier when getting value for resource number 0x00000000
[0:] FileImageSourceHandler: Could not find image or image file was invalid: File: icons8_Plus_Math_32px.png
12-29 12:35:28.653 D/TextView(11423): setTypeface with style : 0
12-29 12:35:37.956 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 0
**** Touched listitem again, it just highlights and no event is fired ****
12-29 12:35:38.010 D/ViewRootImpl@78cb657[MainActivity](11423): ViewPostImeInputStage processPointer 1
12-29 12:35:38.011 D/AbsListView(11423): onTouchUp() mTouchMode : 0
12-29 12:35:38.012 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:38.012 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:38.082 D/AbsListView(11423): viewType is heaer or footer
12-29 12:35:38.082 D/AbsListView(11423): viewType is heaer or footer
Thread finished: <Thread Pool> #7
The thread 0x7 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #10
The thread 0xa has exited with code 0 (0x0).
Thread finished: <Thread Pool> #2
The thread 0x2 has exited with code 0 (0x0).
Thread started: <Thread Pool> #16
Thread finished: <Thread Pool> #12

**Comment by r-a-y-w** [comment] 2017-12-29 18:17
@seankanderson Does this have to do with grouped items in lists? I'm quite certain I could only reproduce this issue on Windows (RT and UWP). I think yours is a different issue.

**Comment by seankanderson** [comment] 2017-12-29 19:54
@r-a-y-w  What is a grouped items list?  Looking for examples that fit this terminology, I do not see anything that stands out as special.  I have the below XAML with binding on an ObservableCollection:

  <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <ViewCell.View>

                                    <Grid Padding="5">
                                        <Grid.RowDefinitions>
                                            <RowDefinition></RowDefinition>
                                        </Grid.RowDefinitions>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="85*"></ColumnDefinition>
                                            <ColumnDefinition Width="15*"></ColumnDefinition>
                                        </Grid.ColumnDefinitions>

                                        <Label Grid.Column="0"
                                               Text="{Binding ShortDescription}" />

                                        <Label Grid.Column="1"
                                               Text="{Binding Quantity}" />

                                    </Grid>

                                </ViewCell.View>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>

**Comment by sander1095** [comment] 2018-01-03 07:50
@davidortinau @pauldipietro Is there an update on this huge bug? It prevents me from updating the UWP app and this is a problem. Will the research on this issue from @r-a-y-w help to fix this issue?

Any ETA on when this will be fixed?

**Comment by leecaci** [comment] 2018-01-03 15:31
I am also struggling with this issue.  Any ETA would be useful as I need to get a new release out to the customer this month....

**Comment by peterwake** [comment] 2018-01-03 17:17
@davidortinau @pauldipietro we have the same issue.. we are going to have to wait to release our UWP app until it is fixed. This seems like a pretty fundamental bug that should be easily fixed.

**Closed** 2018-01-05 10:06 UTC
Labels: p/UWP, t/bug

**Comment by sander1095** [comment] 2018-01-05 10:31
@rmarinho  @samhouts  Thank you very much for fixing this issue! Can you tell me when this fix will be released on Nuget/as a new version? I'd like to update my app with this fix as fast as possible!

**Comment by peterwake** [comment] 2018-01-05 11:18
Thanks @samhouts and @rmarinho :)

**Comment by fschneider1509** [comment] 2018-01-16 09:51
@rmarinho @samhouts Same here. When will it be available?

**Comment by rmarinho** [comment] 2018-01-16 11:12
Should be available on the nightly, can you try that ?

**Comment by sander1095** [comment] 2018-01-16 11:20
@rmarinho we don't want to use the nightly, do you have an eta for actual release

**Comment by sander1095** [comment] 2018-01-16 11:20
@rmarinho we don't want to use the nightly, do you have an eta for actual release

**Comment by alistair23** [comment] 2018-01-19 02:02
Which nightly version? I just tried the latest 2.5.1 nightly and it doesn't seem to be fixed. I tried the 2.6.1 nightly as well, but I hit a few compile issues.

**Comment by marciosouzajunior** [comment] 2018-01-23 11:01
Works good in nightly 2.6.0.108998

**Comment by kingces95** [comment] 2018-01-23 23:44
Yep, works on latest nightly. @alistair23 did you update your legacy PCL projects to .NET 2.0 projects before upgrading the nuget packages?

**Comment by alistair23** [comment] 2018-01-24 00:06
The latest 2.6 nightly @kingces95?  I did see compilation errors mentioning I had to use .NET standard 2.0. .NET Standard 2.0 doesn't work on older versions of Windows though, so I can't use that. Maybe I can try .NET standard 1.4 and see if that works. I was hoping to be able to use XF2.5.

**Comment by kingces95** [comment] 2018-01-24 00:14
@alistair23 Some platforms that do not support .NET Standard 2.0 will no longer be supported with XF2.5. What platform are you trying to use that won't work on .NET Standard 2.0?

**Comment by alistair23** [comment] 2018-01-24 00:15
I'm trying to run on all Windows 10 versions, including Windows 10 Mobile. At the moment the latest XF2.5 release works, it just had this bug.

**Comment by r-a-y-w** [comment] 2018-01-24 00:20
For us WinRT and UWP is important. I hope at least that if it won’t work, a cherry-pick and an older release will be made for just this bug.

**Comment by alistair23** [comment] 2018-01-24 00:24
The fix is in master, which isn't that far ahead of the latest tagged 2.5 release (release-2.5.0-sr3). It doesn't seem that hard to cut another 2.5 release with the fix. I can't figure out what the 2.5.1 or 2.6 nighties are being built from though, so it's hard to say.

**Comment by r-a-y-w** [comment] 2018-01-24 00:26
PS: I’ve seen commits removing older Windows support but no official response nor any deprecation/breaking change info on any roadmap, so I assumed those breaking changes wouldn’t be merged into the release branch yet.

**Comment by alistair23** [comment] 2018-01-24 00:33
Ah, that is tougher. I see the commit removing Windows 8.1 support in the 2.4 and 2.5 releases.

**Comment by r-a-y-w** [comment] 2018-01-24 00:40
That sucks! Was it ever mentioned anywhere that it’d break? The latest 2.5 release seemed to work fine except for this bug, which is why we couldn’t make a new release and why I spent time helping to get it fixed. I’m sure they can make an old 2.5.0.1 release with a cherry-pick, or not? It sort of makes the effort of the last realeases for anyone using a grouped list on Windows pointless. I hope in the end I won’t have to downgrade to 2.3.7 again :D

**Comment by davidortinau** [comment] 2018-01-24 03:32
The roadmap has reflected the Win 8.1, 8.0 removal for nearly 6 months if memory serves. Current version https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap

Official support ended July 2017 for most of that. You can find it on different Microsoft sites.

Our vNext (master) release is yet a ways off, and we will be shipping addition bug fix releases on the vCurrent release branch. So it seems reasonable to consider back porting this fix. Will discuss with the team.

**Comment by alistair23** [comment] 2018-01-24 04:18
Is the vCurrent branch visible? I'd be happy to help with the back porting effort.

**Comment by r-a-y-w** [comment] 2018-02-01 11:34
@samhouts (or @davidortinau) So, I'm a bit confused, what is missing for the current NuGet release to get this bugfix? You said it is already in the 8.0/8.1 Branch? I'm using 2.5.0.122203 and this bug still exists. Is it possible to make a 2.5.0.xxx release with this fix so we can finally make a release for 8.1 & UWP?

@davidortinau Thanks for the Wiki.
@alistair23 It's apparently already in the branch: https://github.com/xamarin/Xamarin.Forms/pull/1499#issuecomment-360246566

**Comment by alistair23** [comment] 2018-02-01 19:55
Ah awesome! So it looks like the 15-5 branch is the 2.5 release branch: https://github.com/xamarin/Xamarin.Forms/commits/15-5

Can nightlies just be turned on for that branch/2.5 release?

**Comment by r-a-y-w** [comment] 2018-02-02 09:07
Sorry, it's fixed since a month, no minor version release and I'm sure you could easily make a cherry-pick etc. and release a 2.5.0.12220*4* quickly.

Where do I find the nightly that works with WIn8.1/UWP? It's been months, and finally got fixed, a month ago, and still nothing? If you won't do a release, where do I get the build (guess won't work with NuGet then). What is missing to get this working, so anyone using a Microsoft product and using grouped lists, since 2.3.7 can upgrade and have all the other hard effort from Xamarin working on their device?

@davidortinau @samhouts @anyone
Not trying to sound harsh, I just want a link to the build (8.1/UWP) or a response, or something I can work with. I've invested my time to track down the exact bug, and @samhouts thankfully fixed it. So, now what? I'm sure we spent more time than it would take to create a release. Don't such critical bugs get a quick minor release (even more so when it affects your mother company's devices)?

**Comment by r-a-y-w** [comment] 2018-02-02 09:10
...or create a minor release 2.5.0.1.2220**4**, which would take less time than each of us probably spent commenting here 😆

**Comment by sander1095** [comment] 2018-02-02 09:41
What @r-a-y-w is saying makes perfect sense; why is this not happening?

**Comment by r-a-y-w** [comment] 2018-02-06 14:56
😔 *Sigh* Guess it'll take another month for someone to tackle this, and by then it won't happen anyways. Where is the Win 8.1. nightly? Guess there is none, as a maintainer would've answered instead of ignoring us.

@davidortinau @pauldipietro @samhouts @rmarinho Guess, a simple cherry-pick, minor 2.5 release (although critical bug), etc. is too much work for one of the maintainers?

**Comment by alistair23** [comment] 2018-02-06 16:40
They are getting close. There is a new 2.5 tag (https://github.com/xamarin/Xamarin.Forms/releases/tag/release-2.5.0-sr4). There just aren't any builds available via NuGet yet

**Comment by peterwake** [comment] 2018-02-06 17:05
It .. feels .. so .. close.

The whole reason we chose Xamarin over React Native was UWP support because it was bought by Microsoft. Aaargh!

**Comment by alistair23** [comment] 2018-02-06 22:24
History seems to show that it takes up to three days from a tag to get a release. We are now overdue for a release, by roughly a day.

Assuming the release means that we can get the package via NuGet. We should be seeing it extremely soon.

**Comment by r-a-y-w** [comment] 2018-02-12 10:16
10 days old... Hmm, really don't get this release process, unless they want to add more to the release?

**Comment by sander1095** [comment] 2018-02-12 10:44
Can't this issue get re-opened until it is actually released?

**Comment by alistair23** [comment] 2018-02-12 18:13
Yeah, I'm a little confused too. You can't change a tag in git (It is technically possible, but it's such a bad idea that no one ever would) so they aren't going to add anything to it. I'm not sure what we are waiting for.

**Comment by alistair23** [comment] 2018-02-13 19:46
Apparently they just changed the tag.... I don't think I've ever seen that done before. The git documentation literately describes that as "The insane thing".

Now I guess there is no way to know how close we are.

**Comment by davidortinau** [comment] 2018-02-14 00:02
Rebuilding for QA. Expecting to ship as soon as it's approved.

**Comment by alistair23** [comment] 2018-02-14 19:34
Woo! The release is made. I can see he package here: https://github.com/xamarin/Xamarin.Forms/releases/tag/release-2.5.0-sr4

**Comment by alistair23** [comment] 2018-02-14 19:46
I manually downloaded it and it fixes the problem for me :)

**Comment by r-a-y-w** [comment] 2018-02-15 10:08
@alistair23 Saw there's already an sr5 release, minor fix https://github.com/xamarin/Xamarin.Forms/releases/tag/release-2.5.0-sr5

**Comment by r-a-y-w** [comment] 2018-02-16 13:48
NuGet Release is available now 💯 
Thanks all and especially @davidortinau & @samhouts for making this happen!!!
