### ISSUE TITLE
WebView.Navigated event not being hit

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9873] opened 2020-03-06 22:55 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/937286/webviewnavigated-event-not-being-hit.html)._

---
I have a forms Webview that gets a URL from a webservice which the VM tthen assigns to the view. 

On Android, the Navigated event is hit constantly, but never on iOS. 

My code behind is minimal, but is this

public partial class MainPage : ContentPage
    {
        MainViewModel viewModel;

public MainPage(MainViewModel model)
        {
            BindingContext = viewModel = model;

InitializeComponent();

viewModel.PropertyChanged += ViewModel_PropertyChanged;
        }

void ViewModel_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == &quot;RewardsUrl&quot;)
                Device.BeginInvokeOnMainThread(() =&gt; webView.Source = viewModel.RewardsUrl);
        }

void webView_Navigated(object sender, WebNavigatedEventArgs e)
        {
            Console.WriteLine($&quot;result = {e.Result}&quot;);
            switch (e.Result)
            {
                case WebNavigationResult.Failure:
                    Console.WriteLine(&quot;failed&quot;);
                    break;
                case WebNavigationResult.Success:
                    Console.WriteLine(&quot;success&quot;);
                    break;
            }
        }

void webView_Navigating(object sender, WebNavigatingEventArgs e)
        {
            Console.WriteLine(e.NavigationEvent);
            Console.WriteLine(viewModel.RewardsUrl);
        }
    }

The Navigating event is hit on both, but onky the Navigated is hit on android.

---
#### Visual Studio Feedback System on 3/3/2020, 04:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment] 2020-03-08 17:44
What version of Forms are you using? How are you hooking up your handler to the Navigated event?

**Comment by nodoid** [comment] 2020-03-08 18:41
Using the latest version of forms from Nuget. Events are being set up in Xaml and acted on in the code behind like this:

 <WebView x:Name="webView" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Source="{Binding RewardsUrl}" Navigated="webView_Navigated" Navigating="webView_Navigating"/>

and in the code behind

void webView_Navigated(object sender, WebNavigatedEventArgs e)
        {
            Console.WriteLine($"result = {e.Result}");
            switch (e.Result)
            {
                case WebNavigationResult.Failure:
                    Console.WriteLine("failed");
                    break;
                case WebNavigationResult.Success:
                    Console.WriteLine("success");
                    break;
            }
        }

        void webView_Navigating(object sender, WebNavigatingEventArgs e)
        {
            Console.WriteLine(e.NavigationEvent);
            Console.WriteLine(viewModel.RewardsUrl);
        }

Android works perfectly, iOS never hits navigated

**Comment by Johno-ACSLive** [comment] 2020-03-09 08:37
I can confirm the same, for simple HTML string such as in the examples it gets hit (and text shown) but not when using complex local files using JavaScript.

This has been a problem on iOS (12.4.5 or older but works on 13.x.x) only since 4.4 of Xamarin Forms. Strangely this works in the simulator on 12.4.5 or older.

**Comment by nodoid** [comment] 2020-03-09 09:56
The website the URL points do contain JS, not sure of the complexity though (I don't have access to the source). Tested on a real device (running 13.3.1) and the end point isn't hit. I get the same fail on the emulators from v12 up

**Comment by Johno-ACSLive** [comment] 2020-03-10 10:07
I should mention, although the JavaScript local files do work on the simulator (all iOS versions - not sure why it's working in the simulator for older versions of iOS but on real hardware I see a blank screen) or real devices running 13.0 or newer, they do not trigger the Navigated event. Only the simple HTML string works on all and triggers the navigated event.

I can't supply the source, however, I know that the local files for the app I developed are generated by converting PowerPoint presentations to HTML using an iSpring plugin for PowerPoint.

**Comment by hartez** [comment] 2020-03-10 15:09
> Using the latest version of forms from Nuget.

Latest stable version, or latest pre-release?

**Comment by hartez** [comment] 2020-03-10 15:12
@nodoid Can you tell us the URL you are trying to load when you see this issue? I'm not seeing this problem when I load some random pages, but I wonder if the specific page content is an issue.

**Comment by nodoid** [comment] 2020-03-10 17:05
https://app.dragonperks.co.uk//rewards.html?sso=B855F3F344FE7EF8063BED1C6134C76585543E1EB78D79DBE871078BD76F674C8E2E47BEB820EC643E91BF60D51D5A39&cid=2433

**Comment by nodoid** [comment] 2020-03-10 17:05
Using the release version rather than pre-release

**Comment by jfversluis** [comment] 2020-03-19 19:54
So, it would be super helpful if we could get a simple reproduction project that shows this issue. It seems to work fine on our end. I see some mention of JavaScript, are we talking about navigation within single page applications where parts of the DOM are replaced through JS? Or also from one real URL to another? All that would be clear from a reproduction :)

**Comment by nodoid** [comment] 2020-03-23 11:21
> So, it would be super helpful if we could get a simple reproduction project that shows this issue. It seems to work fine on our end. I see some mention of JavaScript, are we talking about navigation within single page applications where parts of the DOM are replaced through JS? Or also from one real URL to another? All that would be clear from a reproduction :)

I'll need to email the page to you as it's part of a commercial package

**Comment by jfversluis** [comment] 2020-03-23 22:04
I didn't mean the actual source necessarily, a small project with just the bits to show us the issue.

I did however have a quick look at the thing you send me and it seems that indeed there is some navigation happening by some JavaScript magic? Or am I not reading that correctly?

Not saying that the event shouldn't be fired then, just trying to figure out what the exact scenario is here

**Comment by nodoid** [comment] 2020-03-23 23:40
The project takes a user/pass and sends to the service which returns the HTML I emailed to you. This then is fired to another service held on another server (in this case, a membership website) so my server sends the HTML to the WebView, the WebView runs the HTML and JS which is then passed to another server as the login credentials and token.

**Comment by nodoid** [comment] 2020-03-23 23:40
I'm happy to send you the project as a zip file if it helps.

**Comment by PureWeen** [comment] 2020-03-28 19:39
@nodoid shneuvil at microsoft.com

**Comment by nodoid** [comment] 2020-03-28 22:40
Sent

**Comment by jsuarezruiz** [comment] 2020-04-22 11:48
Thanks to @PureWeen  I have take a look to the App. On Android we have the following result (I voluntarily cut Urls for privacy reasons).

```
NewPage
https://app...
NewPage
https://app...
result = Success
success
result = Success
success
```
Where NewPage comment is from Navigating event and success message from Navigated event.
However, on iOS I see the following:

```
NewPage
https://app...
NewPage
https://app...
Connection 1: received failure notification
Connection 1: failed to connect 3:-9816, reason -1
Connection 1: encountered error(3:-9816)
```

Could it be a problem related to certificates?

**Comment by nodoid** [comment] 2020-04-22 12:12
Which certs do you need? The ones held on the server that creates the redirect or the one it ends on or both?

**Comment by PureWeen** [comment] 2020-05-21 23:13
Closing as a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/10350 for now

**Closed by PureWeen** 2020-05-21 23:13 UTC
Labels: a/webview, p/iOS 🍎, s/unverified, t/bug :bug:
