### ISSUE TITLE
MasterDetails UWP Navigation back loses the menu

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#5958] opened 2019-04-19 02:37 UTC
### Steps to Reproduce

- Create master detail project
- Click item on the menu to set Details to NavigationPage
- Push a new page on the stack
- Click back arrow (The menu button disappears)

### Expected Behavior
Going back to NavigationPage previous page and keeping the menu button

### Actual Behavior
Goes back to NavigationPage previous page but the menu button disappears

### Basic Information

VS 2019, Xamarin Forms 3.6.0.264807

**Comment by samhouts** [comment] 2019-04-19 18:00
Duplicate of #5412

**Closed by samhouts** 2019-04-19 18:00 UTC
Labels: p/UWP, s/unverified, t/bug :bug:
