### ISSUE TITLE
[Bug] iOS Safe Area Insets wrong on iPhone 14 Pro and Pro Max 

### ISSUE THREAD

**Issue by iamlawrencev** [xamarin/Xamarin.Forms#15584] opened 2022-10-27 04:07 UTC
### Description

On iPhones with the new dynamic island (iPhone 14 Pro and Pro Max) there is a bit of space when using the Page.UseSafeArea="true" iOS specific.

### Expected Behavior

There should be no blank space.

### Actual Behavior

There is a white blank space.

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2515
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  Xcode 14.0.1
- Affected Devices: iPhone 14 Pro, iPhone 14 Pro Max

### Screenshots

![Screen Shot 2022-10-27 at 12 02 02 PM](https://user-images.githubusercontent.com/14250426/198188977-1826c311-4251-4f26-b821-235bf05fd603.png)

**Comment by giuseppenovielli** [comment] 2022-10-27 11:50
@jfversluis @davidortinau
Please not abandoned Xamarin.Forms's support.
Xamarin.Forms support is until 2024, right?

When possible check these iOS 16 issues, so we can upgrade Xamarin.iOS SDK.

Thanks a lot!

**Comment by jfversluis** [comment] 2022-11-14 14:24
Is there anyone that can provide a bit of code or better yet, a reproduction of what you're seeing here? How do I trigger this behavior? Just want to make sure that I fix your scenarios.

**Comment by jfversluis** [comment] 2022-11-15 20:14
Are these apps that have been recompiled against Xcode 14? Or is this showing up with apps that are currently released and now running on iOS 16? 

I don't really see this behavior, so I'm wondering if you recompile the app with all the latest bits installed if that will help. 

Any new info here will be appreciated, thanks!

**Comment by msibalik** [comment] 2022-11-16 18:20
I just built my app using VS 2022 Version 17.4.1 connected to XCode 14.0. It still has the issue. I'll try to create a small app that replicates the issue

**Comment by jfversluis** [comment] 2022-11-16 18:55
@msibalik cool, thanks! Not to rush you but rather sooner than later so I can include it in the next Forms release that I want to release soon :)

**Comment by msibalik** [comment] 2022-11-17 13:02
I've been working on this, but I'm having a hard time recreating the error when I implement just a single page of my app in a new solution. Hopefuly something today...

**Comment by msibalik** [comment] 2022-11-17 14:03
I have determined that this issue is not casued by Page.UseSafeArea="true", but rather the following code in AppDelegate.cs commonly used to change the color of the status bar.

                var statusBarColor = UIColor.FromRGB(9, 31, 47); // #091F2F

                if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
                {
                    foreach (var window in UIApplication.SharedApplication.Windows)
                    {
                        const int statusBarTag = 38482;

                        if (window.ViewWithTag(statusBarTag) != null) continue;

                        var statusBar = new UIView(UIApplication.SharedApplication.StatusBarFrame)
                        {
                            Tag = 38482,
                            BackgroundColor = statusBarColor
                        };
                        window.AddSubview(statusBar);
                    }
                }
                else
                {
                    var statusBar = UIApplication.SharedApplication.ValueForKey(new NSString("statusBar")) as UIView;
                    if (statusBar.RespondsToSelector(new Selector("setBackgroundColor:")))
                    {
                        statusBar.BackgroundColor = statusBarColor;
                    }
                }

**Comment by msibalik** [comment] 2022-11-18 15:37
[DynamicIslandTest.zip](https://github.com/xamarin/Xamarin.Forms/files/10042589/DynamicIslandTest.zip)
Here is a smalll app that demos the issue. Select Dynamic Island Test from the menu. An area of whitespace appears below the status bar on devices with the dynamic island.

**Comment by jfversluis** [comment] 2022-11-18 19:48
So, I wonder if something is actually going wrong or if this is by (iOS) design. 

If I look at [this guide](https://useyourloaf.com/blog/iphone-14-screen-sizes/) I see that the status bar height is 54, which is also reported when I debug through your code. But the safe area inset is 59, which, in effect, means there is a gap in between of 5.

The question then remains... What is the right fix here? 😅

**Comment by jfversluis** [comment] 2022-11-21 11:12
Alright, here is my thinking. It's a bit too risky to fix it on our side, at least at this short notice to rush it into a next release.

As pointed out through the above guide, technically everything functions correctly. There now simply is a gap between what is the status bar and what is the safe area.

Because of that I will close this as not a bug on our side. What I would suggest doing is updating your status bar coloring code with something like this:

```
var statusBar = new UIView(new CGRect(UIApplication.SharedApplication.StatusBarFrame.X,
UIApplication.SharedApplication.StatusBarFrame.Y,
UIApplication.SharedApplication.StatusBarFrame.Width,
UIApplication.SharedApplication.Windows.FirstOrDefault()?.SafeAreaInsets.Top ?? 0))
```

The code for the `UIApplication.SharedApplication.Windows.FirstOrDefault()?.SafeAreaInsets.Top` returns the actual height for the status bar + the safe area (59 in case of a iPhone 14 Pro) and thus will connect your status bar to the rest again.

You might want to check if this code still checks out for iPhone <14 devices and/or not Dynamic Island devices. Else you can implement some code to only do it for these devices. However, there doesn't seem to be a great way to detect the Dynamic Island programmatically at the time.

**Closed by jfversluis** 2022-11-21 11:12 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/unverified
