### ISSUE TITLE
DatePicker and TimePicker are not working on xamarin.forms macOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6921] opened 2019-07-18 18:54 UTC
On xamarin.forms macOS I can’t get DatePicker and TimePicker to work.

I have attached a video of how the DatePicker and TimePicker is working. 

In the video I click the up and down arrows to increase and decresáse date (day, month and year) and time (hour, minute and second) . It doesn’t work either if I try to type in the date or time.

As you can see some of the numbers in date and time doesn’t show (e.g. 2020).

What can I do to solve the problems ?

Best regards,
Eigil

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/635812/datepicker-and-timepicker-are-not-working-on-xamar.html
VSTS ticketId: 943431_
_These are the original issue comments:_

Visual Studio Feedback System on 7/7/2019, 11:22 PM (10 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by jsuarezruiz** [comment] 2019-07-19 07:35
Duplicate of #6817

**Closed** 2019-07-19 07:35 UTC
Labels: p/macOS, t/bug :bug:
