### ISSUE TITLE
[Enhancement] CollectionView allow for User to re-order the list

### ISSUE THREAD

**Issue by CliffAgius** [xamarin/Xamarin.Forms#8800] opened 2019-12-09 10:21 UTC
## Summary
Allow the user to hold and then drag an item in the list that is displayed on screen and drop it into a position elsewhere on the list and in doing re-order the list.

There is a Syncfusion version of this but it requires a licence which is fine but I now think the CollectionView is now better than the Syncfusion version so adding this one last missing part will mean not needing the licence or Nugets that need to be managed. (Sorry Syncfusion)

I have been looking about within the CollectionView code and think this could be done but it's not a simple task to add so looking for ideas and feedback on this and if anyone else would like to see it.

## API Changes

There would need to be an 

    Bool IsReOrderEnabled

This will allow this function to be turned on/off and then UI changes such that the User can see that they have selected an item and can drag it about within the list.

Need to be sure we cater for both Horizontal and Vertical scrolling lists and that the item is the whole cell within the list so that it includes all the styling and elements within that cell.

## Intended Use Case

I am working on a project where the user has a need to re-order the list items, in this case it's a very short list of 4-7 items but the order really matters to the user.  When the user has finished getting the order correct they then save for later use.

**Comment by Go2sites** [comment] 2020-02-03 12:04
I agree with this feature, the Syncfusion way of handling it is very good and we have used the plug-in with a couple of apps but we really want to move away from it now.

We are starting a new app that needs a draggable list, the items at the top of the list have higher priority. Having drag and drop is a must for this type of app, doing it any other way is not as good as a simple drag  and drop into place. I feel it is a must have, it is the one last missing part.

**Comment by CliffAgius** [comment] 2020-02-03 14:08
@Go2sites I am awaiting feedback from the Xamarin team on the idea and if I can start working on it as it would be a waste of time if they decide they don't want it.

However if your looking for a Non-Syncfusion version that is open source I have just last week heard of and started using @roubachof Sharpnado Nuget which does an amazing job of exactly what I have described.

You can find it here https://www.sharpnado.com/sharpnado-1-4-0-drag-and-refresh/ and maybe use that until XamarinForms gets it pulled in or build a copy.

Have fun.

**Comment by samhouts** [comment] 2020-02-13 00:49
Duplicate of #4676

**Closed by samhouts** 2020-02-13 00:49 UTC
Labels: a/collectionview, proposal-open, t/enhancement ➕
