### ISSUE TITLE
[Android] MonoBtlsObject.CheckThrow ()

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Xamarin.Forms#3560] opened 2018-08-14 06:47 UTC
### MOST AFFECTED OS
- SDK 23: 85.7%
- SDK 26: 14.3%

<pre>
Xamarin Exception Stack:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MonoBtlsSsl'.
  at Mono.Btls.MonoBtlsObject.CheckThrow () [0x00024] in <5a97d41d36694fb19855c17429527b10>:0
  at Mono.Btls.MonoBtlsObject.get_Handle () [0x00000] in <5a97d41d36694fb19855c17429527b10>:0
  at Mono.Btls.MonoBtlsSslCtx.get_Handle () [0x00000] in <5a97d41d36694fb19855c17429527b10>:0
  at Mono.Btls.MonoBtlsSslCtx.SetSelectCallback (Mono.Btls.MonoBtlsSelectCallback callback) [0x0000d] in <5a97d41d36694fb19855c17429527b10>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x97275f08 + 0x00033> in <f32579baafc1404fa37ba3ec1abdc0bd>:0

Thread 1:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:135)
3   android.app.ActivityThread.main(ActivityThread.java:7329)
4   java.lang.reflect.Method.invoke(Method.java:-2)
5   com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
6   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Thread 134840:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:162)
2   java.lang.Thread.run(Thread.java:818)

Thread 134841:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:423)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
5   java.lang.Thread.run(Thread.java:818)

Thread 134842:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:1031)
2   java.lang.Thread.sleep(Thread.java:985)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:288)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:299)
5   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:247)
6   java.lang.Thread.run(Thread.java:818)

Thread 134843:
0   dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-2)
1   java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:370)
2   java.lang.Thread.run(Thread.java:818)

Thread 134847:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134865:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134871:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:135)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 134873:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:135)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 134876:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:580)
2   java.lang.Thread.getAllStackTraces(Thread.java:522)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:923)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)

Thread 134891:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134894:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134895:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:135)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 134898:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:135)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 134900:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134901:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   com.google.android.gms.internal.zzbge.run
10  java.lang.Thread.run(Thread.java:818)

Thread 134905:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134907:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   com.google.android.gms.internal.zzbge.run
10  java.lang.Thread.run(Thread.java:818)

Thread 134908:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
9   java.lang.Thread.run(Thread.java:818)

Thread 134910:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
2   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 134925:
0   com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-2)
1   com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:811)
2   com.android.okhttp.okio.Okio$2.read(Okio.java:140)
3   com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
4   com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
5   com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
6   com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
7   com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
8   com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
9   com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1151)
10  com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:982)
11  com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
12  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
13  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
14  com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
15  com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
16  com.microsoft.appcenter.http.DefaultHttpClient.doHttpCall(DefaultHttpClient.java:233)
17  com.microsoft.appcenter.http.DefaultHttpClient.doCall(DefaultHttpClient.java:141)
18  com.microsoft.appcenter.http.DefaultHttpClient.access$000(DefaultHttpClient.java:33)
19  com.microsoft.appcenter.http.DefaultHttpClient$Call.doInBackground(DefaultHttpClient.java:326)
20  com.microsoft.appcenter.http.DefaultHttpClient$Call.doInBackground(DefaultHttpClient.java:302)
21  android.os.AsyncTask$2.call(AsyncTask.java:295)
22  java.util.concurrent.FutureTask.run(FutureTask.java:237)
23  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
24  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
25  java.lang.Thread.run(Thread.java:818)

Thread 134926:
0   com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java:-2)
1   com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
2   com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
3   com.android.okhttp.Connection.connect(Connection.java:1322)
4   com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
5   com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
6   com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485)
7   com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
8   com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372)
9   com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
10  com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:118)
11  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:249)
12  com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
13  com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
14  com.microsoft.appcenter.http.DefaultHttpClient.doHttpCall(DefaultHttpClient.java:227)
15  com.microsoft.appcenter.http.DefaultHttpClient.doCall(DefaultHttpClient.java:141)
16  com.microsoft.appcenter.http.DefaultHttpClient.access$000(DefaultHttpClient.java:33)
17  com.microsoft.appcenter.http.DefaultHttpClient$Call.doInBackground(DefaultHttpClient.java:326)
18  com.microsoft.appcenter.http.DefaultHttpClient$Call.doInBackground(DefaultHttpClient.java:302)
19  android.os.AsyncTask$2.call(AsyncTask.java:295)
20  java.util.concurrent.FutureTask.run(FutureTask.java:237)
21  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
22  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
23  java.lang.Thread.run(Thread.java:818)
</pre>

---

No code to reproduce
Latest XF

**Comment by kingces95** [comment] 2018-08-15 21:07
@paleicikas We'll need a reproduction for this one. There are no Xamarin.Forms frames captured in the stack traces.

**Comment by paleicikas** [comment] 2018-08-16 05:37
unfortunately no reproduction available (large project, unknown location), thanks

**Comment by PureWeen** [comment] 2018-09-14 17:16
Reached out to mono team to see if they have any advice

**Comment by samhouts** [comment] 2018-10-14 21:14
Since we are unable to get a reproduction of this issue, we will close it for now. If you happen to find a way to reproduce the issue, please feel free to reopen it. Thank you for your report!

**Closed by samhouts** 2018-10-14 21:14 UTC
Labels: has-stacktrace, p/Android, s/needs-info ❓, s/needs-repro ❔, t/bug :bug:

**Comment by Vikashkumar117** [comment] 2019-01-31 09:22
**I have the same issue. Here is the log**  Please help
02-17 12:26:59.082 21372 21436 E AppCenterCrashes: Unhandled Exception from source=AppDomain

02-17 12:26:59.082 21372 21436 E AppCenterCrashes: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.082 21372 21436 E AppCenterCrashes:   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1[TResult].GetAwaiter () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.082 21372 21436 E AppCenterCrashes:   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.272 21372 21397 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsObject.CheckThrow () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsObject.get_Handle () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.get_Handle () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.get_CanModify () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at Mono.Btls.MonoBtlsX509VerifyParam.WantToModify () [0x00000] in <3e9b3e26c4694baab3f689687ad40612>:0 

02-17 12:26:59.272 21372 21397 E mono-rt :   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.292  3007  3860 D libEGL  : eglTerminate EGLDisplay = 0x7f7653ee78

02-17 12:26:59.292  3007  3860 D libEGL  : eglTerminate EGLDisplay = 0x7f7653ee78

02-17 12:26:59.292 21372 21436 E mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.

02-17 12:26:59.292 21372 21436 E mono-rt :   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1[TResult].GetAwaiter () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

02-17 12:26:59.292 21372 21436 E mono-rt :   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0xd4876f98 + 0x00033> in <d4a23bbd2f544c30a48c44dd622ce09f>:0

**Comment by WilliamWatterson86** [comment] 2019-02-25 08:42
@paleicikas, @Vikashkumar117 - did you get any further on this one - i too am having the same issue
