### ISSUE TITLE
[Bug] [iOS] [Shell] GoToAsync fails after navigating back via Tab

### ISSUE THREAD

**Issue by roycornelissen** [xamarin/Xamarin.Forms#8457] opened 2019-11-11 13:50 UTC
### Description
On iOS, the `GoToAsync()` method stops working after using the tab bar to pop back to the tab bar's root. On iOS, it is common behavior to tap the tab bar to return back to the root page of the navigation stack.

On Android, this doesn't happen since tapping the tab bar does not trigger any navigation.

### Steps to Reproduce

1. See/run the attached solution. This solution was generated using the standard Xamarin.Forms AppShell template in VS for Mac. I modified the implementation to use URI based navigation from the `ItemsPage` to the `ItemDetailPage` with `GoToAsync()`
2. Navigate back and forth between the list and a few items using the Back button on the Navigation Bar. This works as expected.
3. Navigate to an item detail
4. Tap the `Browse` tab, causing the page to pop back to the Items list
5. Try to navigate to another item. This is now broken.

### Expected Behavior
`GoToAsync` should continue to work

### Actual Behavior
`GoToAsync` does nothing anymore (no exceptions either)

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: N/A
- IDE: Visual Studio for Mac Enterprise, Version 8.3.7 (build 1)
- Platform Target Frameworks:
  - iOS: 13.2
- Nuget Packages: Xamarin.Forms (4.3.0.947036) and Xamarin.Essentials (1.3.1)
- Affected Devices: iPhone

### Screenshots

[Screen recording](https://www.dropbox.com/s/ir5uc5ylf9jwtwa/Screen%20Recording%202019-11-11%20at%2014.16.18.mov?dl=0)

### Reproduction Link

[navigationbug.zip](https://github.com/xamarin/Xamarin.Forms/files/3831576/navigationbug.zip)

**Comment by jfversluis** [comment] 2019-11-22 10:51
Thanks for reporting @roycornelissen ! We already had an issue tracking this, I will close this as a duplicate, please follow the progress there.

Thanks!

**Comment by jfversluis** [comment] 2019-11-22 10:52
Duplicate of #7024

**Closed by jfversluis** 2019-11-22 10:52 UTC
Labels: s/unverified, t/bug :bug:
