### ISSUE TITLE
Can not use Safe area in xamarin.android

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#14179] opened 2021-04-18 11:12 UTC
I want to the status bar be transparent 
`Window.AddFlags(WindowManagerFlags.TranslucentStatus);`

![image](https://user-images.githubusercontent.com/46642851/115143447-ef3a6280-a079-11eb-80a6-ac349b232de6.png)

I am using xamarin.forms Shell android.

**Comment by jpobst** [comment] 2021-04-19 15:16
I think XF may affect this, assigning to them to check first.

**Comment by mcguu** [comment] 2021-04-20 05:33
the issue have been post since 18 Aug 2020 · 22 but never be fixed.

nearly 8 months past.

I have to tell you @jpobst 

yes it is XF Shell which affect this they do not want to fix it.

**Comment by rachelkang** [comment] 2021-04-28 18:28
Hi, @mcguu - thanks for submitting this issue. I'm closing as it's a duplicate of the issue you mentioned https://github.com/xamarin/Xamarin.Forms/issues/11828. We'll take a look as soon as we get the chance - in the meantime, please check out the workaround shared there if you haven't already!

**Closed by rachelkang** 2021-04-28 18:28 UTC
Labels: a/shell :shell:, p/Android, s/unverified, t/bug :bug:

**Comment by mcguu** [comment] 2021-04-29 00:36
@rachelkang  I have gave up of it but thank you  Mrs kang

**Comment by mcguu** [comment] 2021-05-07 01:31
@rachelkang  As you can see. 8 days past and nothing changed.
