### ISSUE TITLE
[Bug] Page on navigation stack in tabbed view is overlapped

### ISSUE THREAD

**Issue by Basti82b** [xamarin/Xamarin.Forms#7287] opened 2019-08-27 09:30 UTC
### Steps to Reproduce

1. Load the [Xaminals project](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals)
2. Go to MonkeyDetailPage.xaml
3. Optional: Remove the Margin of the StackLayout

### Expected Behavior
All content is shown.

### Actual Behavior
First/second Label is/are overlapped/hidden.

### Basic Information

Version with issue: Xamarin.Forms 4.2.0.709249
Platform Target Frameworks:
Android: 9.0
### Screenshots
![Screenshot_1566896979](https://user-images.githubusercontent.com/49757194/63758085-8528e480-c8bb-11e9-8599-14c47ceb1b35.png)
![Screenshot_1566897006](https://user-images.githubusercontent.com/49757194/63758086-8528e480-c8bb-11e9-8211-43a48c86766c.png)

**Comment by Basti82b** [comment] 2019-08-29 09:22
Maybe Duplicate of #7240

**Comment by Basti82b** [comment] 2019-08-29 09:46
Not fixed in 4.3.0.1106-nightly

**Comment by Phoenixkaze** [comment] 2019-09-01 15:13
Facing same problem in my own project.
This happens when pushing a new page with `Navigation.PushAsync`

**Comment by samhouts** [comment] 2019-09-10 23:44
Confirmed this is fixed by #7265

**Comment by samhouts** [comment] 2019-09-10 23:44
Duplicate of #7240

**Closed by samhouts** 2019-09-10 23:44 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:

**Comment by Basti82b** [comment] 2019-09-12 07:57
I can confirm that the problem no longer exists in version 4.4.0.1142-nightly.
