### ISSUE TITLE
TableView Does Not Scroll[Bug] 

### ISSUE THREAD

**Issue by Nickjgniklu** [xamarin/Xamarin.Forms#6611] opened 2019-06-20 17:53 UTC
### Description
When using shell pages with a table view scroll is very buggy. Scroll will only work if you first tap and hold a section header then drag with another finger on the screen.
### Steps to Reproduce

1. Create a shell application with a flyout menu
2. Register a route to a page with a TableView ie `Routing.RegisterRoute(,);
`
3. From a page in the shell application navigate to it using await `Shell.Current.GoToAsync();`
4. TableView will not scroll correctly

### Expected Behavior
Table View Scrolls with simple up down drag
### Actual Behavior
First tap and hold a section header then drag with another finger on the screen.
### Basic Information

- Version with issue: 4.1.0.496342-pre2
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0  
- Android Support Library Version: v28.0.0.1
- Nuget Packages:
- Affected Devices:

`

    <ContentPage.Content>
            <TableView Intent="Settings" >
                <TableRoot>
                    <TableSection Title="section1" >
                        <EntryCell Label="Name"></EntryCell>
                        <EntryCell Label="thing2"></EntryCell>

                    </TableSection>
                    <TableSection Title="section2">
                        <EntryCell Label="thing3"></EntryCell>
                        <EntryCell Label="thing4"></EntryCell>

                    </TableSection>
                    <TableSection Title="section3">
                        <EntryCell Label="thing5"></EntryCell>
                        <EntryCell Label="thing6"></EntryCell>
                    </TableSection>
                    <TableSection Title="section4">
                        <EntryCell Label="thing7"></EntryCell>
                    </TableSection>
                    <TableSection Title="section5">
                        <EntryCell Label="thing8"></EntryCell>
                        <EntryCell Label="thing9"></EntryCell>
                    </TableSection>
                    
                    <TableSection Title="section6">
                        <EntryCell Label="Note"></EntryCell>

                    </TableSection>

                </TableRoot>
            </TableView>
    </ContentPage.Content>
</ContentPage>`

**Comment by samhouts** [comment] 2019-06-21 01:00
probably same root cause as #6381

**Comment by samhouts** [comment] 2019-06-21 01:00
@Nickjgniklu  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Nickjgniklu** [comment] 2019-06-24 16:06
Thanks!,
Here is an example.
[TableScrollIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3321640/TableScrollIssue.zip)

**Comment by samhouts** [comment] 2019-07-17 22:43
#6310

**Comment by samhouts** [comment] 2019-08-19 19:20
closed by #7032

**Closed by samhouts** 2019-08-19 19:20 UTC
Labels: a/gestures 🖖, a/listview, a/shell :shell:, e/6 :clock6:, p/Android, t/bug :bug:
