### ISSUE TITLE
Error Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Material.Android.MaterialSliderRenderer::OnElementPropertyChanged

### ISSUE THREAD

**Issue by mariohik** [xamarin/Xamarin.Forms#9724] opened 2020-02-26 13:56 UTC
### Description
Can't compile my application on Release mode anymore

`
Error		Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Material.Android.MaterialSliderRenderer::OnElementPropertyChanged(System.Object,System.ComponentModel.PropertyChangedEventArgs)' in assembly: 'Xamarin.Forms.Material.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Boolean Xamarin.Forms.Platform.Android.PropertyChangedEventArgsExtensions::IsOneOf(System.ComponentModel.PropertyChangedEventArgs,Xamarin.Forms.BindableProperty[])
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()`

**Comment by jsuarezruiz** [comment] 2020-02-26 15:55
Could you attach a repro sample?. If this is not possible, you could share more information such as:
- Xamarin.Forms version used, etc.

**Comment by mariohik** [comment] 2020-02-26 16:07
Xamarin.Forms: 4.5.0.282-pre4
Xamarin.Forms.Visual.Material 4.4.0.991640

**Comment by mariohik** [comment] 2020-02-26 16:53
I returned Xamarin.Forms until version 4.2, and the error continued.
After that, I installed the stable version of Visual Studio and managed to compile normally.

**Comment by samhouts** [comment] 2020-03-02 22:26
@mariohik What version of Visual Studio were you previously using and what version are you now using? Thanks!

**Comment by mariohik** [comment] 2020-03-02 23:03
This error was happening in Version 16.5.0 Preview 4.0.
I just upgraded to Version 16.5.0 Preview 5.0 and the error is no longer occurring.

**Comment by stesvis** [comment] 2020-04-12 18:49
I have this error in Visual Studio 16.5.3

> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Material.Android.MaterialColors::ApplySeekBarColors(Android.Widget.AbsSeekBar,Xamarin.Forms.Color,Xamarin.Forms.Color,Xamarin.Forms.Color)' in assembly: 'Xamarin.Forms.Material.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.DrawableExtensions::SetColorFilter(Android.Graphics.Drawables.Drawable,Android.Graphics.Color,Xamarin.Forms.Platform.Android.FilterMode)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    --- End of inner exception stack trace ---
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process()
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Mono.Linker.Pipeline.Process(LinkContext context)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1942,5): error XALNK7000:    at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by ArifImran-apex** [comment] 2020-04-22 12:51
I am also having this issue
XF version 4.5.0.617
VS 16.5.4

**Comment by aaafgcfg** [comment] 2020-07-10 16:21
i got same problem.
 but i just maked (versions of nuget packages on MyApp.android)=(versions of nuget packages on MyApp) and this solved problem

**Comment by Nullstr1ng** [comment] 2020-08-18 13:33
Seeing this in VS 16.8.0 Preview 1.0

**Comment by alexeystrakh** [comment] 2021-03-05 21:16
Having the same issue and the same solution to upgrade the material package helps. For some reason, when you upgrade XF 4.x -> 5.0, the material package is not upgraded

**Comment by BlueRaja** [comment] 2021-03-06 03:14
I'm having the same issue after upgrading from Xamarin Forms 4.5 --> 5.0, except updating all my NuGet packages didn't help. I don't have anything called "Material Package"...

**Comment by DanwithArduino** [comment] 2021-03-07 23:20
Having this error after updating Visual Studio to 16.9.0. The issue is occurring on two different computers (why oh why did I update both computers at once without testing... :( 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.ComponentModel.ICustomTypeDescriptor System.Data.Entity.ModelConfiguration.Utilities.AttributeProvider::GetTypeDescriptor(System.Type)' in assembly: 'EntityFramework.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider::.ctor(System.Type)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	MyApp.Android	
```

**Comment by AnthonyWeirbach** [comment] 2021-03-21 03:47
This might be too simplistic of an answer but I was also having the same error mentioned above and then I stumbled upon a message board from 2018 that had this same type of error and someone said that deleting the bin and obj folders was their fix. 

I manually deleted my bin and obj folders and like magic.... everything worked.... 
Hey, Its worth a try.... (if you haven't done it already)

**Comment by fhintsch** [comment] 2021-03-31 10:48
deleting my bin and obj folders worked for me too

**Comment by Meekohi** [comment] 2021-04-07 20:07
Upgrading Xamarin.Google.Android.Material and deleting bin/obj worked for more also. Incredible anyone still chooses these busted tools for new projects 😆

**Comment by lobbo232** [comment] 2021-07-12 13:50
> Upgrading Xamarin.Google.Android.Material and deleting bin/obj worked for more also. Incredible anyone still chooses these busted tools for new projects 😆

Anyone coming here wondering why this doesn't work you them, try Xamarin.Google.Android.Material version 1.3.0.1. 

1.4.0 causes this issue again for me with Xamarin.Forms 5.0.0.2012

**Comment by jfversluis** [comment] 2021-10-05 11:52
For a lot of people this seems fixed. The last comment reminds me of some other issues that have been opened like #14646. Closing this one to avoid a big number of issues describing the same thing :)

**Closed by jfversluis** 2021-10-05 11:52 UTC
Labels: t/bug :bug:, p/Android, s/needs-info ❓, mobcat, a/visual, s/unverified
