### ISSUE TITLE
[Enhancement] Make ParameterAttribute public

### ISSUE THREAD

**Issue by mattiascibien** [xamarin/Xamarin.Forms#11388] opened 2020-07-10 10:17 UTC
## Summary
Make the Parameter attribute public in order to let custom controls develpers to access the constructor parameters inside Xaml. I had a real case where this was needed and had to rely on a hacky solution like https://stackoverflow.com/questions/46188243/how-to-define-an-constructor-argument-accessible-from-xaml.

**Comment by StephaneDelcroix** [comment] 2020-07-27 14:19
Duplicate of #10847

**Closed by StephaneDelcroix** 2020-07-27 14:19 UTC
Labels: a/Xaml </>, proposal-open, t/enhancement ➕
