### ISSUE TITLE
Migrate to .NET Standard - Can't compile XAML

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#1316] opened 2017-12-05 02:16 UTC
I have included a Repro.

I converted a working PCL app (X.Forms 2.5) to .NET Standard (Runs on X.Forms 2.5 as well)

On only 1 XAML I get the error:
"No property, bindable property, or event found for 'FontSize', or mismatching type between value and property"

To reproduce the error.

Create a .NET Standard 2 project with XForms 2.4 or 2.5, fails on both. Add this "Login.xaml" page. Attempt to compile.

If you Comment out the Labels and it compiles.

-------------------------------------------

    <?xml version="1.0" encoding="utf-8"?>

    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
 
             x:Class="CoApp.Views.Test.LoginPageD"
             Title="Login">

    <Grid>
        
        

        
        <ScrollView
             >
            
            <Grid
                ColumnSpacing="0"
                RowSpacing="0"
                HorizontalOptions="Fill"
                VerticalOptions="FillAndExpand">

                <Grid.RowDefinitions>
                    <RowDefinition Height="120" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="*" />
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>

                
                <Grid
                    Grid.Row="0"
                    WidthRequest="60"
                    HeightRequest="60"
                    Margin="20"
                    VerticalOptions="End"
                    HorizontalOptions="Start">

                    <Image HorizontalOptions="Start" VerticalOptions="Center" WidthRequest="95" HeightRequest="95"
                           Source="icon.png" Aspect="AspectFill" />
                </Grid>

                
                <StackLayout
                    Grid.Row="1"
                    Spacing="10"
                    Padding="20,10"
                    Orientation="Vertical"
                    VerticalOptions="Center">
                    <Label 
                        LineBreakMode="WordWrap"
 
                        VerticalTextAlignment="Center"
                        FontAttributes="Bold">
                        <Label.FontSize>
                            <OnIdiom x:TypeArguments="x:Double" Phone="26" Tablet="36" />
                        </Label.FontSize>
                    </Label>

                    <Label
                        LineBreakMode="WordWrap"
                        Text="Login using your email and password."
                    
                        VerticalTextAlignment="Center">
                        <Label.FontSize>
                            <OnIdiom x:TypeArguments="x:Double"
                                     Phone="17"
                                     Tablet="27" />
                        </Label.FontSize>
                    </Label>

                    <BoxView
             
                        />

                </StackLayout>

                
                <Grid
                    Grid.Row="2"
                    Padding="20,0"
                    ColumnSpacing="0"
                    RowSpacing="0"
                    VerticalOptions="CenterAndExpand"
                    HeightRequest="180">

                    <StackLayout
                        Grid.Row="0"
                        VerticalOptions="StartAndExpand">
                        <StackLayout.Spacing>
                            <OnPlatform x:TypeArguments="x:Double">
                                <On Platform="Android">20</On>
                                <On Platform="iOS">40</On>
                            </OnPlatform>
                        </StackLayout.Spacing>
                        
                        <Entry
                            AutomationId="txtEmail"
                            Placeholder="E-mail"
                            >
                      
          

                        </Entry>

                        
                        <Entry
                            AutomationId="txtPassword"
                            Placeholder="Password"
                        
                            IsPassword="true"
                         
                            VerticalOptions="StartAndExpand" >
 
                        </Entry>
 
                  
                    </StackLayout>

                </Grid>
 

            </Grid>
        </ScrollView>

    </Grid>

</ContentPage>

**Comment by davidortinau** [comment] 2017-12-05 02:50
Confirmed on 2.5.0.91635 only when XAMLC enabled:

`[XamlCompilation(XamlCompilationOptions.Compile)]`

It's fixed on master testing nightly build 2.5.1.102606-nightly

**Comment by ianvink** [comment] 2017-12-05 03:04
Dude, the Xamarin Forms PM is answering bugs? That’s so cool.

I’m a MVP and that still impresses...

**Comment by dhaligas** [comment] 2017-12-06 22:44
is there a work around for this?  I can't use the nightly builds

@StephaneDelcroix @davidortinau

**Comment by StephaneDelcroix** [comment] 2017-12-07 08:24
There's no workaround, unless you want to disable `XamlC`.

This is not a regression, and we do not support netstandard projects on XF 2.5, so it's very unlikely that we'll release a service release for that.

If you want to build your own binaries for 2.5, you can cherry-pick the fix from master.

**Comment by StephaneDelcroix** [comment] 2017-12-11 14:39
> This is not a regression, and we do not support netstandard projects on XF 2.5, so it's very unlikely that we'll release a service release for that.

we apparently support net standard project since 2.4. I missed that

**Comment by abrasat** [comment] 2017-12-11 18:07
Does vNext mean a new XForms 2.5xxx version ?

**Comment by StephaneDelcroix** [comment] 2017-12-12 09:59
@abrasat this has been moved to `vCurrent`, and should be part of the next `2.5` service release

@bruzkovsky the OP mentions this is failing on both 2.4 and 2.5. Your issue might be different. In that case, open a new issue

**Comment by bruzkovsky** [comment] 2017-12-12 10:16
@StephaneDelcroix Ok thanks, I read over that part... I also use XamlC, so I will evaluate if the fix already does it for me

**Closed** 2017-12-14 10:53 UTC
Labels: a/netstandard, t/bug

**Comment by EmilAlipiev** [comment] 2017-12-28 19:29
why dont you just make small release and fix this problem for all of us?

**Comment by bruzkovsky** [comment] 2018-01-02 15:44
> why dont you just make small release and fix this problem for all of us?

There is a SR3 with the fix in it, but it is not on nuget.org:

https://github.com/xamarin/Xamarin.Forms/releases/download/release-2.5.0-sr3/Xamarin.Forms.2.5.0.122203.nupkg

Can someone upload that please @davidortinau

**Comment by MarcusSpecht** [comment] 2018-02-15 15:54
@bruzkovsky Version 2.5.0.122203 seems to be avaiable through [nuget](https://www.nuget.org/packages/Xamarin.Forms/2.5.0.122203).

**Comment by bruzkovsky** [comment] 2018-02-15 16:10
@MarcusSpecht  You are right. It just takes a really long time until the versions are listed on nuget. SR4 was released yesterday, still no sign on nuget... 😕

**Comment by muhaym** [comment] 2018-02-22 09:13
```
<OnPlatform x:TypeArguments="x:Boolean"
                                         iOS="false"
                                         Android="true"/>
```

Position 23:22. No property, bindable property, or event found for 'HasShadow', or mismatching type between value and property.	

Tried with Xamarin Forms 2.5.0.280555 and 2.5.0.122203, Can't Build the Project after converting from PCL to .NET Standard.

**Comment by StephaneDelcroix** [comment] 2018-02-22 09:15
@muhaym please open a new issue with your repro attached. thanks

**Comment by muhaym** [comment] 2018-02-22 09:28
@StephaneDelcroix Is there any way to share repo offline. Since I am not able to recreate the issue in fresh project
