### ISSUE TITLE
[Bug] Button inside collectionview not appearing until UWP window is resized #13552

### ISSUE THREAD

**Issue by Shelbyabounds** [xamarin/Xamarin.Forms#13588] opened 2021-01-29 15:04 UTC
### Description
I am running into an issue with my collection view where I have a collection view and there on buttons inside of the collection view.
The buttons do not appear until I make some sort of screen size adjustment to the UWP's window size. I have tried calling ForceLayout() in my code as a work around and that does not seem to fix the issue either. My project was previously on the 4.7 version of Xamarin.Forms and this issue did not arise until I updated to 5.0.0.1931. Does anyone know of a work around for this, I am desperately needing one as this is holding up a lot of bug fixes to my project.
### Steps to Reproduce

1. Open page with collection view that has button inside of it 
2. Resize window and the buttons that are inside the collection view will appear 
3. 

### Expected Behavior
Buttons to appear on initialization of the page

### Actual Behavior
Buttons do not appear until you resize the page

### Basic Information

- Version with issue: 50.0.1935
- Last known good version:4.8.0
- Platform Target Frameworks: 
  - UWP
- Affected Devices: Desktop

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![105918712-04af6b80-5ffa-11eb-8692-bff76a94cf70](https://user-images.githubusercontent.com/78054266/106290902-9d1f3900-6210-11eb-95b8-5ef3a437cacf.gif)

### Reproduction Link
The xaml files with the buttons and collection view that are having the issue

[SinglePrintStatusThumb.txt](https://github.com/xamarin/Xamarin.Forms/files/5894523/SinglePrintStatusThumb.txt)
[SinglePrintStatusPage.txt](https://github.com/xamarin/Xamarin.Forms/files/5894533/SinglePrintStatusPage.txt)

### Workaround
I am desperately looking for a workaround for this issue as it is holding up a lot of bug fixes for my product

**Comment by Shelbyabounds** [comment] 2021-01-31 14:30
Bump

**Comment by rachelkang** [comment] 2021-02-04 22:24
Hi, @Shelbyabounds - thanks for sharing this issue. Would you be able to share your full project or sample project reproducing the issue?

I tried to reproduce a simple version based on the sample you shared, but didn't experience the issue you're describing, so I'm thinking it might have to do with the bindings/styles or other related code you have.

[Issue13588.zip](https://github.com/xamarin/Xamarin.Forms/files/5928873/Issue13588.zip)

**Comment by jsuarezruiz** [comment] 2021-02-09 15:18
Attached reproduction sample:
[Issue13588.zip](https://github.com/xamarin/Xamarin.Forms/files/5952234/Issue13588.zip)

**Comment by jsuarezruiz** [comment] 2021-02-09 15:20
Need to verify but maybe could be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13470 (update wrong item size).

**Comment by Shelbyabounds** [comment] 2021-02-12 15:15
@jsuarezruiz Is there any sort of workaround for this until the version with the fix is released?

**Comment by Shelbyabounds** [comment] 2021-02-18 22:41
@jsauvexamarin bug fix #13470 that went into Xamarin Forms 5.0.0.2012 did not fix this issue

**Comment by Shelbyabounds** [comment] 2021-03-03 14:44
bump

**Comment by rubiktubik** [comment] 2021-04-28 09:20
I have the same issue too. Its a major blocker for me 😌

**Comment by anton-yashin** [comment] 2021-05-11 15:06
This regression caused by https://github.com/xamarin/Xamarin.Forms/commit/5525491faa9e6c2155d5f2a1889cc30aaef49e3b. There something about IsNativeStateConsistent = true on Xamarin.Forms.Button. In attachment is workaround with dirty hack.
[Workaround13588.zip](https://github.com/xamarin/Xamarin.Forms/files/6460182/Workaround13588.zip)

**Comment by brettchangus** [comment] 2021-08-12 02:29
Same problem.

**Closed** 2021-10-07 18:24 UTC
Labels: t/bug :bug:, p/UWP, e/2 :clock2:, a/button
