### ISSUE TITLE
[Bug] Once we launch a page from the More list in IOS, we couldn't navigate to another page.

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#9198] opened 2020-01-14 08:55 UTC
### Description

In IOS, when there are more than 5 tabs, a More list is generated in iOS.Once we launch a page from the More list, we couldn't navigate to another page. 

### Steps to Reproduce

1. create a xamarin form project with Tabbed template
2. add more than five NavigationPage in TabbedPage, for example:
```
    <TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:TabbedPageWithNavigationPage;assembly=TabbedPageWithNavigationPage" x:Class="TabbedPageWithNavigationPage.MainPage">

    <NavigationPage Title="TestPage1" IconImageSource="img1.png">
        <x:Arguments>
            <local:TestPage1 />
        </x:Arguments>
    </NavigationPage>

    <NavigationPage Title="TestPage2" IconImageSource="img2.png">
        <x:Arguments>
            <local:TestPage2 />
        </x:Arguments>
    </NavigationPage>

    <NavigationPage Title="TestPage3" IconImageSource="img3.png">
        <x:Arguments>
            <local:TestPage3 />
        </x:Arguments>
    </NavigationPage>


    <NavigationPage Title="TestPage4" IconImageSource="img4.png">
		<x:Arguments>
			<local:TestPage4 />
		</x:Arguments>
	</NavigationPage>
    <!-- More -->

    <NavigationPage Title="TestPage5" IconImageSource="img5.png">
        <x:Arguments>
            <local:TestPage5 />
        </x:Arguments>
    </NavigationPage>
    <NavigationPage Title="TestPage6" IconImageSource="img4.png">
        <x:Arguments>
            <local:TestPage6 />
        </x:Arguments>
    </NavigationPage>
</TabbedPage>
```
 
3. add a click event in TestPage5 or TestPage6 and navigate to a new page (eg. TestPage7).After that, when we click Button to trigger the event,  we will find that we couldn't go to TestPage7.

```
    void Button_Clicked(object sender, EventArgs e)
    { 
        Navigation.PushAsync(new TestPage7());
   }
```

### Expected Behavior
We expect the current page in more list could navigate to another page  just as in android.

### Actual Behavior

The  page in more list couldn't navigate to another page in IOS.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment] 2020-01-14 14:22
I think this is known, and it's the case for a long time because of [reasons I can't recall]. But it shouldn't be a problem in Shell

**Comment by samhouts** [comment] 2020-01-14 18:32
Duplicate of #1336

**Comment by samhouts** [comment] 2020-01-14 18:33
Unfortunately has a problem in shell, too: https://github.com/xamarin/Xamarin.Forms/issues/7594

**Closed by samhouts** 2020-01-14 18:32 UTC
Labels: s/unverified, t/bug :bug:

**Comment by PureWeen** [comment] 2020-01-14 18:36
Reason
https://github.com/xamarin/Xamarin.Forms/issues/8749#issuecomment-562295566

**Comment by burrowj** [comment] 2020-08-07 00:02
I'm confused a bit.  
I have this issue with Shell but is it fixed?  is there a workaround? 
Shell can't handle more than 4 tabs on IOS and work properly?

**Comment by theBottinels** [comment] 2021-02-08 08:55
issue still present in xamarin forms 5, any news on this bug? thanks

**Comment by theBottinels** [comment] 2021-02-22 12:00
hi someone can help in order to find a fix for this bug? thanks
