### ISSUE TITLE
carouselview stopped supporting right to left navigation between views

### ISSUE THREAD

**Issue by arickatz** [xamarin/Xamarin.Forms#8319] opened 2019-10-31 07:18 UTC
### Steps to Reproduce

1. use carouselview in xaml page
2. set  FlowDirection="RightToLeft"
3. try to move on page

### Expected Behavior
scrolls from right to left
### Actual Behavior
only scrolls from left to right
### Basic Information

- Version with issue: 4.5.0.13...
- Last known good version: 4.5.0.1297
- IDE: VS 2019 MAC
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment] 2019-10-31 22:33
Both UWP and iOS appear to ignore the FlowDirection when laying out the items in the carousel.

**Comment by hartez** [comment] 2019-10-31 22:35
[_8319 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3796029/_8319.Repro.zip)

**Comment by davidortinau** [comment] 2019-11-24 20:09
Related to or duplicate of #7780

**Comment by rmarinho** [comment] 2020-02-04 11:08
Yes duplicated of #7780

**Closed by rmarinho** 2020-02-04 11:08 UTC
Labels: a/carouselview, blocker, e/4 :clock4:, p/UWP, p/iOS 🍎, t/bug :bug:
