### ISSUE TITLE
[Bug][Android] CarouselView ArgumentOutOfRangeException when filtering

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7793] opened 2019-10-03 10:33 UTC
### Description

Filtering a `CarouselView` on a filter term that should result in no data results in a crash (ArgumentOutOfRangeException) on Android. iOS works fine.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the EmptyViewFilteredPage (EmptyView string - filtering on the menu).
3. Filter on a search term that should clear the CarouselView (e.g. Xamarin).

### Expected Behavior

String empty view is displayed.

### Actual Behavior

`ArgumentOutOfRangeException` thrown: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

Stack trace:

  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <46c2fa109b574c7ea6739f9fe2350976>:0 
  at System.Collections.ObjectModel.Collection`1[T].System.Collections.IList.get_Item (System.Int32 index) [0x00000] in <46c2fa109b574c7ea6739f9fe2350976>:0 
  at Xamarin.Forms.CarouselView.GetItemForPosition (Xamarin.Forms.CarouselView carouselView, System.Int32 index) [0x00017] in D:\a\1\s\Xamarin.Forms.Core\Items\CarouselView.cs:229 
  at Xamarin.Forms.CarouselView.OnScrolled (Xamarin.Forms.ItemsViewScrolledEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Items\CarouselView.cs:192 
  at Xamarin.Forms.ItemsView.SendScrolled (Xamarin.Forms.ItemsViewScrolledEventArgs e) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\Items\ItemsView.cs:198 
  at Xamarin.Forms.Platform.Android.CollectionView.RecyclerViewScrollListener`2[TItemsView,TItemsViewSource].OnScrolled (Android.Support.V7.Widget.RecyclerView recyclerView, System.Int32 dx, System.Int32 dy) [0x000bb] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\RecyclerViewScrollListener.cs:57 
  at Android.Support.V7.Widget.RecyclerView+OnScrollListener.n_OnScrolled_Landroid_support_v7_widget_RecyclerView_II (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_recyclerView, System.Int32 dx, System.Int32 dy) [0x0000f] in <844c913cb32f4510879031be59eb1dce>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.82(intptr,intptr,intptr,int,int)

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VSMac 8.3.1
  - Android: API 28

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3685577/CarouselViewDemos.zip)

**Comment by davidbritch** [comment] 2019-10-03 10:36
Update: In the sample, none of the seven pages that demonstrate empty view scenarios in a `CarouselView` work. They all work fine on iOS.

**Comment by jsuarezruiz** [comment] 2019-10-04 08:55
Super nice samples David. I have done tests and although I can reproduce the problem in 4.3-pre3, with version 4.4.0.1206-nightly (Nightly) the issue is already fixed. I attach your sample updated to 4.4:
[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3689714/CarouselViewDemos.zip)

**Comment by PureWeen** [comment] 2019-10-04 18:40
Closing for now @davidbritch let me know if you're not seeing what @jsuarezruiz is seeing

**Closed by PureWeen** 2019-10-04 18:40 UTC
Labels: a/carouselview, p/Android, s/unverified, t/bug :bug:
