### ISSUE TITLE
Can't scroll ListView vertically when inside CarouselView on Android

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/Xamarin.Forms#9311] opened 2020-01-24 13:05 UTC
ListView Impossible to scroll vertically when inside the Carousel view on android. On iOS work fine. On android when try to vertical scroll, carousel view tries to scroll itself horizontally to go to next view which stops the listview scrolling

### Steps to Reproduce

Below is my Carousel View Code

<CarouselView VerticalOptions="FillAndExpand" ItemsSource="{Binding ScheduleCrouselItems}">
                        <CarouselView.ItemsLayout>
                            <LinearItemsLayout Orientation="Horizontal"
                                               SnapPointsType="MandatorySingle"
                                               SnapPointsAlignment="Center" />
                        </CarouselView.ItemsLayout>
                        <CarouselView.ItemTemplate>
                            <DataTemplate>
                                <StackLayout>
                                    <ListView SeparatorVisibility="None" ItemTemplate="{StaticResource bookingTemplateSelector}" x:Name="scheduleListView" HasUnevenRows="True" VerticalOptions="FillAndExpand" ItemsSource="{Binding ScheduleListItems}">
                                    </ListView>
                                </StackLayout>
                            </DataTemplate>
                        </CarouselView.ItemTemplate>
                    </CarouselView>

### Basic Information

- Version with issue: Latest Xamarin forms version

**Comment by Phenek** [comment] 2020-01-24 16:10
#9315

**Comment by samhouts** [comment] 2020-01-27 23:47
Duplicate of #9315

**Closed by samhouts** 2020-01-27 23:47 UTC
Labels: a/carouselview, a/listview, p/Android, s/unverified, t/bug :bug:

**Comment by jivanro** [comment] 2020-07-14 00:07
I had the same problem and the following code helped me to alleviate the situation.
You only have to create an Android Custom Render for ListView like this and you will see some difference right away:

I hope that helps.

```C#
/*** Code starts here ***//

[assembly: ExportRenderer(typeof(Xamarin.Forms.ListView), typeof(OneListViewRenderer))]
namespace Yournamespace
{
  public class OneListViewRenderer : ListViewRenderer
  {
    public OneListViewRenderer(Context context) : base(context)
   {
   }

    public override bool OnInterceptTouchEvent(Android.Views.MotionEvent ev)
    {
        if (ev.Action == MotionEventActions.Move)
        {
            // Disallow ScrollView to intercept touch Move events.
            this.Parent.RequestDisallowInterceptTouchEvent(true);

        }
         return base.OnInterceptTouchEvent(ev);


    }

 }
}
