### ISSUE TITLE
Puchase ? In AppPurchase ? Pay ?

### ISSUE THREAD

**Issue by Mo-ha-mmed** [xamarin/Xamarin.Forms#9454] opened 2020-02-06 21:16 UTC
Hello guys, Its 2020
Xamarin is awesome but come ooon, There is almost no plugin or a correct way nor a good and updated tutorial . Even the Microsoft docs and the xamarin team isn't providing a good resource on how to implement a purchase of a product or a subscription using xamarin forms . Come ooon ! Almost all apps use inApp purchase or there is some sort of subscription or a payed services !

How can the xamarin official team recommend a single person maintained plugin that hasn't been updated in 3 months

- No official plugin for google and apple inApp Purchase and subscription
- No official PayPal plugin
- And the list is going

HOW CAN YOU PAY ANYTHING !!!

I'm sure my request or my issue will be closed by the bot and no one will take the time to read and decide to do something about it.

Come on guys im begging you ! We love xamarin but its 2020 and its still missing basics things

**Comment by samhouts** [comment] 2020-02-06 21:23
Duplicate of #5045

**Closed by samhouts** 2020-02-06 21:23 UTC
Labels: proposal-open, t/enhancement ➕

**Comment by Mo-ha-mmed** [comment] 2020-02-06 21:26
All they did is to mark it as duplicated, Its not even in their roadmap .... So sad

**Comment by samhouts** [comment] 2020-02-06 21:28
It's an accepted proposal that is up for grabs for anyone that would like to contribute. Thanks!

**Comment by Mo-ha-mmed** [comment] 2020-02-06 21:36
I'm a simple dev that chose xamarin because i love c# . If i was able to contribute i would. Now i have to wait for you guys to do something ...

Look at flutter and react native ...

**Comment by Hbib-drif** [comment] 2020-02-06 22:44
@Mo-ha-mmed Stop using xamarin bro, They dont care about devs and certainly not trying to compete in the market. Join the flutter community bro in one year it became so popular with so much features at the meantime the xamarin folks didnt add a pay button not even a radio button 😂
