### ISSUE TITLE
[Enhancement] [F100] Fix code comments <summary>To be added.</summary>

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#11108] opened 2020-06-18 14:46 UTC
## Summary
There is an increasingly large number of API comments that say `\\\<summary>To be added.</summary>`, and while the majority of the API is quite self-explanitory, it would be of huge benefit to start knocking off these summaries instead of just allowing the list of undocumented APIs to continue to grow

## API Changes

Find all instances of `\\\<summary>To be added.</summary>` and update the comments to be meaningful for their context.

## Intended Use Case
Developer productivity

**Comment by samhouts** [comment] 2020-06-18 15:05
Duplicate of #7252

**Comment by samhouts** [comment] 2020-06-18 15:06
We have definitely fallen behind on this! If anyone is interested in helping, the API docs are actually fully open source at https://github.com/xamarin/Xamarin.Forms-api-docs. We'd love the assistance! Thanks!!!

**Comment by ChaseFlorell** [comment] 2020-06-18 15:08
I did search before adding this new issue, I think the terminology is so pervasive that it's found in search results across many issues.

**Comment by ChaseFlorell** [comment] 2020-06-18 15:09
I'm not talking about the API docs repo as much as the `summary` code documentation within _this_ repo.

**Comment by samhouts** [comment] 2020-06-18 15:20
The summary code documentation for this repo _is_ in the API docs repo. :)

**Comment by jfversluis** [comment] 2023-03-08 10:27
We're working hard to make this better for .NET MAUI, won't happen for Forms anymore though. Thanks!

**Closed by jfversluis** 2023-03-08 10:27 UTC
Labels: t/enhancement ➕, proposal-open, a/docs
