### ISSUE TITLE
[Bug] ShellContent navigation not triggering OnAppearing / OnDisappearing overrides when displayed / hidden

### ISSUE THREAD

**Issue by markti** [xamarin/Xamarin.Forms#6098] opened 2019-05-05 19:11 UTC
4.0.0.394984-pre10

### Description

I'm following the pattern from Tailwind Traders where they have a BaseContentPage that implements viewmodel initializeAsync on navigation but its not working because the OnAppearing / OnDisappearing is not being triggered when you are using Shell Navigation... Unlike tailwind traders, I'm using ShellItem/ShellSection/ShellContent to use flyout/bottom tabs/top tabs to do navigation...

### Steps to Reproduce

1. Override the onappearing method of a contentpage
2. Set that content page inside a shellitem/shellsection using the ContentTemplate="{DataTemplate local:MyPage" trick
3. Use shell UI to navigate to MyPage and 

### Expected Behavior
notice that onappearing does not fire...

### Actual Behavior
expect to see the override OnAppearing would be triggered...

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by HobDev** [comment] 2019-05-06 15:47
@markti Shell have OnNavigating and OnNavigated to cover OnDisappearing and OnAppearing respectively.

**Comment by markti** [comment] 2019-05-07 16:20
> @markti Shell have OnNavigating and OnNavigated to cover OnDisappearing and OnAppearing respectively.

@HobDev But OnNavigating / OnNavigated only have a reference to the URI of the source / target of the navigation. How am I able to trigger InitializeAsync on the view model of the page I am navigating to without a reference to my target view object?

**Comment by samhouts** [comment] 2019-05-11 01:07
@markti Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by robintschroeder** [comment] 2019-05-21 15:11
@HobDev @markti @samhouts 
This is an interesting problem. If you have a tabbed shell app, it looks like the FIRST tabbed content page in the group is firing the OnAppearing() override in the code behind. The rest of the pages in the tab group do not fire the OnAppearing() override, unless the user navigates away from the tab group and then back to the tab group. In this case, the 'top' tab (the last tab that was showing previously) will fire OnAppearing(). As far as replacing OnAppearing and OnDisappearing with OnNavigating and OnNavigated, I agree with @markti, this is not a good idea. Most apps require an async method to load/refresh data from HTTPClient. I am going to try to wire up some workaround with an interface, but I am not sure how well it will work. The best solution would be to have the OnAppearing and OnDisappearing() overrides fire when the user navigates around a tab group.

**Comment by robintschroeder** [comment] 2019-05-23 14:58
I forked a SimpleShell repo that @davidortinau  built for Luce Carter per a twitter request yesterday. It was a great starting point show / ask how to handle this. https://github.com/robintschroeder/SimpleShell  
Hope it is clear what the question is. ;-)

**Comment by Basti82b** [comment] 2019-06-11 10:44
I can confirm that. Any workaround yet?

**Comment by Drutol** [comment] 2019-06-29 21:34
Stumbled upon this too... quite annoying to deal with. Any ETA?

**Comment by NirmalSubedi17** [comment] 2019-07-09 14:53
Looks like Messaging Center is only solution. But these events should be functional without any workarounds. Any plans on fixing these? Waiting for the updates !

**Comment by PureWeen** [comment] 2019-07-09 15:02
This will be apart of 4.2 

https://github.com/xamarin/Xamarin.Forms/pull/6527

The Pre should be out soon if you want to test it there and give us feedback!

**Comment by hollen9** [comment] 2019-07-17 02:30
I upgraded from 4.1-stable to the latest build, 4.2.0.608146-pre1, and OnAppearing() is now working.

**Comment by samhouts** [comment] 2019-07-18 03:09
closed by #6527

**Closed by samhouts** 2019-07-18 03:09 UTC
Labels: a/shell :shell:, e/6 :clock6:, t/bug :bug:
