### ISSUE TITLE
CollectionView keep snapping to last item and doesn't respond to swiping in MandatorySingle 

### ISSUE THREAD

**Issue by mshwf** [xamarin/Xamarin.Forms#9723] opened 2020-02-26 11:17 UTC
### Steps to Reproduce

1. Set the `SnapPointsAlignment` to `Center` And `SnapPointsType` to `MandatorySingle`
2. Swipe to the last item and keep swiping forward for **_3 times_** for example
3. Swipe back 

### Expected Behavior
The second-last item is centered at the first time
### Actual Behavior
The second-last item is centered after the **_third swipe_**

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.991250
- Last known good version: 
- IDE: Visual Studio for Windows (16.4.5)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
https://drive.google.com/file/d/1xCXpSEnaD5w4dH4BHny2WTx-PODhkw1A/view
### Reproduction Link

https://drive.google.com/file/d/1RQnwlND-Pe-laKdeJGPEQJjJiI2oX0ul/view?usp=sharing
### Workaround

I didn't find a workaround

**Comment by maurosampietro** [comment] 2020-02-26 11:42
Same issue as #9020

**Comment by jsuarezruiz** [comment] 2020-02-26 13:21
As @maurosampietro has mentioned, it seems to be the same issue as #9020. 
Will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/9700 

cc @rmarinho

**Comment by mshwf** [comment] 2020-02-26 13:32
@jsuarezruiz  Is it going to be available on the stable release 4.5 version?

**Comment by rmarinho** [comment] 2020-02-26 15:05
duplicate of  #9020

**Closed by rmarinho** 2020-02-26 15:05 UTC
Labels: a/carouselview, a/collectionview, p/Android, t/bug :bug:
