### ISSUE TITLE
Xamarin.Forms 4.2 Android ScrollView with Horizontal orientation blocks Vertical scroll of nested ListView 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7413] opened 2019-09-05 20:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/712841/xamarinforms-42-android-scrollview-with-horizontal.html)._

---
Xamarin.Forms build 4.2.0.709249 ScrollView with Horizonatal orientation blocks vertical scroll of a nested ListView.
Xamarin.Forms build 4.1.0.709244 and earlier passed vertical scroll to a nested ListView allowing the ListView content to scroll in both directions.

Very easy to replicate. I made a test app with main grid that has Horizontal orientation ScrollView with ListView as content. Building the app with Xamarin.Forms 4.2.0.709249 introduces the issue. Downgrading Xamarin.Forms to 4.1.0.709244 makes it go away.

Xamarin.Forms for iOS never had that issue.

---
#### Visual Studio Feedback System on 8/27/2019, 01:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2019-09-09 22:06
Duplicate of #7329

**Closed by samhouts** 2019-09-09 22:06 UTC
Labels: a/listview, i/regression, p/Android, s/unverified, t/bug :bug:
