### ISSUE TITLE
[Bug] Nullreference exception when Master.IconImageSource not set

### ISSUE THREAD

**Issue by pspeybro** [xamarin/Xamarin.Forms#6958] opened 2019-07-23 20:28 UTC
### Description
After upgrading the Xamarin Forms libraries from 3.4 to 4.1, my app in Android crashes with a nullreference exception. This happens when I set a MasterDetailPage as the MainPage after the user went through a login screen.

Investigation gave me the following stacktrace in the android device log:
System.NullReferenceException: Object reference not set to an instance of an object.  
	at Xamarin.Forms.Platform.Android.Platform.UpdateMasterDetailToggle (System.Boolean update) [0x00018] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:585   
	at Xamarin.Forms.Platform.Android.Platform.UpdateActionBar () [0x000b6] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:548   at Xamarin.Forms.Platform.Android.Platform.SetPage (Xamarin.Forms.Page newRoot) [0x000ad] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:502   
	at Xamarin.Forms.Platform.Android.FormsApplicationActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0001a] in D:\a\1\s\Xamarin.Forms.Platform.Android\FormsApplicationActivity.cs:234   
	at Xamarin.Forms.Platform.Android.FormsApplicationActivity.AppOnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args) [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.Android\FormsApplicationActivity.cs:222   
	at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:211   
	at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:359   at Xamarin.Forms.Application.set_MainPage (Xamarin.Forms.Page value) [0x0008b] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:87   
	at Bullseye.App.<ShowMainPage>b__10_0 () [0x00007] in D:\irex\irexOne\NETStandard_Test\Bullseye\Bullseye\Bullseye\App.cs:137   
	at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/builder/data/lanes/6102/4b951a3e/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36   
	at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/6102/4b951a3e/source/monodroid/external/xamarin-android/src/Mono.Android/obj/Release/android-28/mcw/Java.Lang.IRunnable.cs:81   
	at (wrapper dynamic-method) System.Object.60(intptr,intptr)

This stacktrace points to the following code:
https://github.com/xamarin/Xamarin.Forms/blob/4.1.0/Xamarin.Forms.Platform.Android/Platform.cs#L585

It seems that this line of code changed starting in version 4.0.
In this case, the following code throws the nullreference:
CurrentMasterDetailPage.Master.IconImageSource.IsEmpty

This is because CurrentMasterDetailPage.Master.IconImageSource is null if you do not set an IconImageSource for the Master contentpage of a MasterDetailPage.
Setting this property avoids the issue.

I also created this issue for the documentation: https://github.com/MicrosoftDocs/xamarin-docs/issues/1956

### Steps to Reproduce
All pages created in cs, no xaml involved.

1. In App.cs, I set MainPage to a Login page that derives from CarousselPage.
2. If login succesfull, create a MasterDetailPage 
3. The MasterDetailPage has a ContentPage as Master and a NavigationPage as the Detail.
4. The Master ContentPage does not set the IconImageSource, 
5. Set the MasterDetailPage as the MainPage
5. Debug in Android
6. A nullreference happens the moment you assign the MasterDetailPage to the MainPage property and crashes the app.

### Expected Behavior
does not crash when IconImageSource not set.

### Actual Behavior
nullreference
### Basic Information

- Version with issue: 4.0, 4.1
- Last known good version: 3.6
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages: Xamarin.Forms
- Affected Devices: HTC10

**Comment by jfversluis** [comment] 2019-07-24 11:55
Would you be able to create a small reproduction project that shows this crash? Thanks!

**Comment by pspeybro** [comment] 2019-07-24 22:21
I tried to create a blank project to reproduce, but it did not crash. I will have to strip down my existing application to get a sample. I suppose there might be a remnant of a long history of upgrading that might be causing an issue.

**Comment by jfversluis** [comment] 2019-07-25 07:11
If that is possible that would be awesome and we would be happy to take a look. Thanks again!

**Comment by davidbritch** [comment] 2019-08-02 12:42
This issue was also opened in the docs repo (https://github.com/MicrosoftDocs/xamarin-docs/issues/1956) and there were no problems with leaving the MasterDetailPage.IconImageSource property unset in v4.1.0.618606.

**Comment by PureWeen** [comment] 2019-08-14 19:08
I'm guessing the blank project didn't reproduce because the template doesn't use nonappcompat and this is only an issue with the nonappcompat code

@pspeybro I would recommend updating your app to AppCompat
https://devblogs.microsoft.com/xamarin/android-tips-hello-material-design-v7-appcompat/

Can you please try to upgrade your application to AppCompat and let us know any issues you can encounter?

**Comment by samhouts** [comment] 2019-08-19 19:21
closed by #7162

**Closed by samhouts** 2019-08-19 19:21 UTC
Labels: PreAppCompat, i/high, i/regression, p/Android, t/bug :bug:
