### ISSUE TITLE
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'void android.graphics.Rect.set(android.graphics.Rect)' on a null object reference'

### ISSUE THREAD

**Issue by fakhravari** [xamarin/Xamarin.Forms#9976] opened 2020-03-16 16:40 UTC
### Description
https://forums.xamarin.com/discussion/comment/406079#Comment_406079
CollectionView Bored of this error

I'm displaying a simple list, but this error occurs while scrolling

Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'void android.graphics.Rect.set(android.graphics.Rect)' on a null object reference'

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
https://us.v-cdn.net/5019960/uploads/editor/og/86a4ssipyuhl.png
https://us.v-cdn.net/5019960/uploads/editor/2n/u71v8t4rfim2.gif

**Comment by jfversluis** [comment] 2020-03-16 19:17
Duplicate of #7877 

If you have any useful information to add to the information there, please do. We'd really like to get this fixed, but it seems hard to reproduce. Closing this one so we won't have information all over the place. Thank you!

**Closed by jfversluis** 2020-03-16 19:17 UTC
Labels: s/unverified, t/bug :bug:

**Comment by fakhravari** [comment] 2020-04-23 19:12
Button to ImageButton
