### ISSUE TITLE
TabbedPage with NavigationPage doesn't behave well on UWP

### ISSUE THREAD

**Issue by HazyFish** [xamarin/Xamarin.Forms#1627] opened 2018-01-21 05:12 UTC
### Description
When placing a NavigationPage into a TabbedPage, I want to hide the Navigation Bar which appears at the top. However, setting the NavigationPage.HasNavigationBar property to false doesn't work on UWP.  

### Steps to Reproduce

1. Create a Tabbed Page with a Navigation Page inside;
2. Set the NavigationPage.HasNavigationBar to false for the NavigationPage;
3. Run the UWP App;
4. Click the Navigation Page tab;
5. The navigation bar appears.

### XAML Code
```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TabbedPageWithNavigationPage"
             x:Class="TabbedPageWithNavigationPage.MainPage">

    <local:TodayPage Title="Today"/>
    <NavigationPage Title="Schedule">
        <x:Arguments>
            <local:SchedulePage NavigationPage.HasNavigationBar="False"/>
        </x:Arguments>
    </NavigationPage>

</TabbedPage>
```

### Expected Behavior
The navigation bar should not show up at the top

### Actual Behavior
The navigation bar shows up at the top

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.122203
- IDE: Visual Studio 2017 Version 15.5.4
- Platform Target Frameworks: 
  - UWP:  Windows 10 FCU Build 16299

### Screenshots

<img width="652" alt="1" src="https://user-images.githubusercontent.com/28922700/35190953-951d610a-fea9-11e7-9b42-2312d2d91146.png">
<img width="652" alt="2" src="https://user-images.githubusercontent.com/28922700/35190998-af53e8e0-feaa-11e7-8c57-aa517af6bc77.png">

**Comment by pauldipietro** [comment] 2018-01-21 17:44
Duplicate of #1437

**Closed by pauldipietro** 2018-01-21 17:44 UTC
