### ISSUE TITLE
Xamarin.Forms - ListView/CollectionView with Drag-Drop Functionality to Move Items Around

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms#7508] opened 2019-09-13 14:51 UTC
## Summary
Xamarin.Forms is cross-platform mobile framework and it should support more of swiping / dragging-dropping than it does.  For example, drag-drop style moving items in a ListView would be helpful in scenarios where ListView is used as some sort of organizer.  User could easily then tap on item 5 and drag it to position 2 and shift item from position 2 to position 3 **on all 3 platforms UWP, iOS, and Android**..

## API Changes

For example, add property on ListView called EnableDragDrop and if enabled, user can rearange the ListView items by dragging and dropping.  Or implement same in the new CollectionView supporting **all 3 platforms UWP, iOS, and Android.**

## Intended Use Case
Drag-drop style moving items in a ListView would be helpful in scenarios where ListView is used as some sort of an organizer.  User could easily tap on the item 5 and drag it to position 2.  This would shift item that was at position 2 to position 3.  

Let's say, I use ListView to show a list of tasks.  Top tasks are most important and I want to re-prioritize my tasks, so I want to move task 5 to 1st position in this ListView by simply long tapping on task item 5, then drag and drop it over task item that is in position 2.  That would shift task item in position 2 to position 3 and insert task item 5 at the 2nd position in the list.

Or ListView represents list of orders grouped by some group such as days.  I want to reprioritize the order that was planned to be shipped on Wednesday to Monday just by dragging the items in the list.  

Another example, the ListView represents list of food entries ordered at a table.  Table has seats and each food entry is displayed in the ListView under its seat.  I want to move pizza that was accidentally added to seat 3 up to seat 2  or down to seat 4 simply by dragging and dropping it to the right location in the ListView.

There is lots of examples where this would be useful but the bottom line is that if it is used on mobile devices, we should not have to use buttons or context menus for such actions but swiping and dragging and dropping.

**Comment by samhouts** [comment] 2019-09-13 16:56
@dinobu Would you be willing to upgrade to CollectionView for this functionality if we added it there instead? Thanks!

**Comment by dinobu** [comment] 2019-09-13 17:19
> @dinobu Would you be willing to upgrade to CollectionView for this functionality if we added it there instead? Thanks!

Would you mind elaborating a bit?  Maybe an example?  Thanks

**Comment by pauldipietro** [comment] 2019-09-13 17:29
@dinobu CollectionView is intended to be a successor to ListView for use in your apps. #3172 is the full spec where you can read about it, and you can refer to the docs [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/index). Further information in the introduction including [moving from one to the other](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction#move-from-listview-to-collectionview) is available as well.

Moving forward we plan to focus our efforts on CollectionView, which includes the potential for functionality you suggested such as drag-and-drop. As @samhouts asked, we'd like to know if you'd be willing and able to upgrade your existing ListView(s) to CollectionView in your app(s) if this functionality were implemented for CollectionView rather than ListView.

Thanks again for your interest and feedback.

**Comment by dinobu** [comment] 2019-09-13 17:42
> @dinobu CollectionView is intended to be a successor to ListView for use in your apps. #3172 is the full spec where you can read about it, and you can refer to the docs [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/index). Further information in the introduction including [moving from one to the other](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction#move-from-listview-to-collectionview) is available as well.
> 
> Moving forward we plan to focus our efforts on CollectionView, which includes the potential for functionality you suggested such as drag-and-drop. As @samhouts asked, we'd like to know if you'd be willing and able to upgrade your existing ListView(s) to CollectionView in your app(s) if this functionality were implemented for CollectionView rather than ListView.
> 
> Thanks again for your interest and feedback.

That sounds great as long as this is supported on all 3 platforms, UWP, iOS, and Droid.
Thanks for sharing

**Comment by dinobu** [comment] 2019-09-23 14:43
@samhouts @pauldipietro Any movement on this topic?  Drag and drop functionality to rearange items in ListView or CollectionView for all 3 platforms (UWP, Android, iOS)?

**Comment by samhouts** [comment] 2019-11-20 22:51
@dinobu For the sake of backlog management, I'm going to mark this as a duplicate of #4676. Please add your upvote there! Thanks!!!

**Comment by samhouts** [comment] 2019-11-20 22:51
Duplicate of #4676

**Closed by samhouts** 2019-11-20 22:51 UTC
Labels: a/collectionview, a/listview, mobcat, proposal-open, t/enhancement ➕
