### ISSUE TITLE
[Bug][SwipeView][Content] Events aren't reaching the SwipeView's content

### ISSUE THREAD

**Issue by SDKexplorer** [xamarin/Xamarin.Forms#9382] opened 2020-01-31 07:45 UTC
### Description
UI Controls that are placed inside SwipeView's content don't receive the tap events.

### Steps to Reproduce
`        
        <SwipeView>
            <SwipeView.LeftItems>
                <SwipeItems>
                    <SwipeItem Text="SomeItem"/>
                </SwipeItems>
            </SwipeView.LeftItems>
            <StackLayout>
                <Button Command="{Binding TestCommand}"/>
            </StackLayout>
        </SwipeView>
`

1. Create new project
2. Add a SwipeView
3. Place a Button control inside SwiveView's content
4. Run the project and tap on the newly added Button
5. Notice that the button's command isn't triggered

### Note: 
This issue also occurs with Entry (on screen keyboard doesn't appear) Picker (selection modal is not showing) CheckBoxes etc.

### Expected Behavior
Button Command should be triggered. 
SwipeView should catch only the drag event, and the content should be able to catch the tap event.

### Actual Behavior
Nothing happens.

### Basic Information
- Version with issue: 4.4.0.991265
- Last known good version: none
- IDE: Microsoft Visual Studio Community 2019

**Comment by samhouts** [comment] 2020-01-31 19:19
@SDKexplorer Is this happening on one platform or all of them?  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by SDKexplorer** [comment] 2020-02-03 06:45
@samhouts This issue occurs on Android platform, I can't test this on iOS because I don't have a Mac.
[https://github.com/SDKexplorer/SwipeViewIssue](url)

**Comment by samhouts** [comment] 2020-02-03 23:40
Duplicate of #8779

**Closed by samhouts** 2020-02-03 23:40 UTC
Labels: a/button, a/swipeview, p/Android, s/unverified, t/bug :bug:

**Comment by SDKexplorer** [comment] 2020-02-04 02:13
I'm not entirely sure that this should labeled as a duplicate since the issue on #8779 is about SwipeView's SwipeViewItem and this one is about it's SwipeView's Content.

**Comment by samhouts** [comment] 2020-02-04 02:19
@SDKexplorer The associated PR (#8653) covers this test case.

**Comment by Tommigun1980** [comment] 2020-03-27 22:24
I am using Xamarin.Forms 4.6.0.494-pre2 and swipe view items don't invoke commands or send events when interacted with. Have only tested on iOS. Is this fix supposed to be in that version?

My code:
SwipeItems>
                                    <SwipeItem
                                        Text="Leave"
                                        BackgroundColor="Red"
                                        Command="{Binding LeaveChatCommand, Source={x:Reference root}}"
                                        CommandParameter="{Binding .}" />
                                </SwipeItems>

Thanks.

**Comment by Tommigun1980** [comment] 2020-05-09 06:19
@samhouts What version will the fix land in? Swipe view buttons can't be interacted with at all atm.

Also, would it be possible to write this information down before closing bug reports?

Thanks.

**Comment by Tommigun1980** [comment] 2020-05-09 06:25
@samhouts Please see the following video of the problem. The button inside the swipe view doesn't react to clicks, nor does it ever go to the 'pressed state':
https://streamable.com/ma47i6

(Bonus issue is that even a tiny swipe completely reveals the button, only sometimes does it reveal it smoothly).

You said on Feb 4 that it was fixed by https://github.com/xamarin/Xamarin.Forms/pull/8653, which says it landed in 4.5.0. **Is any of this information accurate?**

Thank you.

**Comment by samhouts** [comment] 2020-06-03 21:05
@Tommigun1980 Yep, that information is all accurate, so if you're still experiencing this issue, please open a new one and attach a small project demonstrating the behavior. Thanks!!

**Comment by Tommigun1980** [comment] 2020-06-03 21:07
> @Tommigun1980 Yep, that information is all accurate, so if you're still experiencing this issue, please open a new one and attach a small project demonstrating the behavior. Thanks!!

Thank you for confirming! I will do that.
