### ISSUE TITLE
[Bug] The Focus problem in ViewCell of TableView.

### ISSUE THREAD

**Issue by yelinzh** [xamarin/Xamarin.Forms#6584] opened 2019-06-19 13:32 UTC
### Description
When I enter and delete the contents of the `Entry` in the second, the **UnFocus** event of the first input control is called. The second `Entry`'s **UnFocus** event will then be called.
### Related Code
```
public Page()
{
    InitializeComponent();

    TableView tableView = new TableView();
    TableRoot root = new TableRoot();
    tableView.Intent = TableIntent.Settings;

    Entry entry1 = new Entry
    {
        HorizontalTextAlignment = TextAlignment.Start,
        BackgroundColor = Color.White,
        HeightRequest = 50,
        MaxLength = 256,
        FontSize = 16
    };
    entry1.Unfocused += Entry_Unfocused_1;

    Entry entry2 = new Entry
    {
        HorizontalTextAlignment = TextAlignment.Start,
        BackgroundColor = Color.White,
        HeightRequest = 50,
        MaxLength = 256,
        FontSize = 16
    };
    entry2.Unfocused += Entry_Unfocused_2;

    TableSection section = new TableSection();
    ViewCell label_cell_1 = new ViewCell();
    label_cell_1.View = new Label { Text = "Entry_1" };
    ViewCell entry_cell_1 = new ViewCell();
    entry_cell_1.View = entry1;
    section.Add(label_cell_1);
    section.Add(entry_cell_1);

    ViewCell label_cell_2 = new ViewCell();
    label_cell_2.View = new Label { Text = "Entry_2" };
    ViewCell entry_cell_2 = new ViewCell();
    entry_cell_2.View = entry2;
    section.Add(label_cell_2);
    section.Add(entry_cell_2);

    root.Add(section);
    tableView.Root = root;
    Content = tableView;
}

private void Entry_Unfocused_1(object sender, FocusEventArgs e)
{
    DisplayAlert("UnFocus", "Entry1 lost focus", "OK");
}
private void Entry_Unfocused_2(object sender, FocusEventArgs e)
{
    DisplayAlert("UnFocus", "Entry2 lost focus", "OK");
}
```

### Basic Information

- IDE: VS 15.9
- Xamarin Forms: 3.6.0.344457
- Platform Target Frameworks: 
  - Android:  8.1

### Screenshots
![](https://us.v-cdn.net/5019960/uploads/editor/ao/cd4wj9w1di4d.gif "")

**Comment by rmarinho** [comment] 2019-06-19 16:48
Happens on 3.6.0 and master

**Comment by samhouts** [comment] 2019-07-30 00:17
Duplicate of #1600

**Closed by samhouts** 2019-07-30 00:17 UTC
Labels: p/Android, t/bug :bug:
