### ISSUE TITLE
[Bug] AppThemeBinding with color as a StaticResource and DynamicResource throws exception

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12952] opened 2020-11-23 21:43 UTC
### Description
Linked to https://github.com/xamarin/Xamarin.Forms/issues/12951

When using the below style given `MainColor` as a `StaticResource` the color change normally but throwing 17 times the exception below, when using  `DynamicResource` instead it still throwing exception but the color is not changing.
```
<Color x:Key="MainColor">#00F798</Color>

<Style TargetType="{x:Type ShellContent}">
    <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Dark=Black, Light={StaticResource MainColor}}}"/>           
</Style>
```
> [0:] SetValue: Cannot convert Xamarin.Forms.Internals.DynamicResource to type 'Xamarin.Forms.Color'
### Steps to Reproduce

1. Give `AppThemeBinding `a color as a `StaticResource`  and then as a `DynamicResource `.
2.  Siwtch theme.

### Expected Behavior
Color change to `MainColor ` when Light theme is selected.
### Actual Behavior
Color changeing in the case of `StaticResource ` and not changing in the case of `DynamicResource`,  but both throwing the exception 17 times.
### Basic Information

- Version with issue: 5.0.0.1709
- Platform Target Frameworks: Tested on Android 10 only.
- Android Support Library / AndroidX Version: Xamarin.Google.Android.Material 1.0.0.1

### Environment

1. Visual studio 2019 Version 16.8.1

**Comment by StephaneDelcroix** [comment] 2020-11-24 07:52
duplicate of #12951

**Closed by StephaneDelcroix** 2020-11-24 07:52 UTC
Labels: s/unverified, t/bug :bug:
