### ISSUE TITLE
ObjectDisposedException setting property value on property bound to disposed page

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#9419] opened 2020-02-04 03:39 UTC
### Description

Apologies for the post-and-run on this. I'm traveling and seeing this in my travel app while using it.

When a bound property changes on a page that's already been disposed, it appears to throw an unhandled ObjectDisposedException. It seems unreasonable for the user to have to catch this kind of exception, or to find ways to completely avoid interactions with pages that might be disposed. But advice appreciated regardless.

Here's the stack trace.

```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_Context ()
NavigationPageRenderer.OnToolbarItemPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
BindingExpression.Apply (System.Boolean fromTarget)
BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 ()
BindingExpression+BindingExpressionPart.PropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args)
BindingExpression+WeakPropertyChangedProxy.OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
Observable.OnPropertyChanged (System.String propertyName)
Observable.Set[T] (T& storage, T value, System.String propertyName)
TrackingLogic.set_HasTrackPoints (System.Boolean value)
TrackingLogic.<OnTrackCleared>b__84_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr)
```

### Steps to Reproduce

The issue seems to happen when a property is changed (perhaps due to a callback) on a page's viewmodel after the page has been disposed.

### Expected Behavior

The case should be succeed silently and not result in an ObjectDisposedException, since it no longer really matters.

### Actual Behavior

An ObjectDisposedException is thrown back to the user.

### Basic Information

- Version with issue: 4.4.0.991537
- Last known good version: Unknown, but this seems fairly new
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

**Comment by mfeingol** [comment] 2020-02-06 20:13
For what it's worth, I also observed a similar crash adding a field to a listview-bound observable collection, in a view model that was no longer current. So I don't think this is specific to toolbars - it seems to happen with any activity that touches bound properties after a page's renderer (?) has been disposed.

I've reverted back to `4.4.0.991265` and it doesn't appear to have the issue. So that suggests the regression showed up in `4.4.0.991477`. This is a bad issue, so hopefully someone can take care of it soon.

**Comment by samhouts** [comment] 2020-02-06 20:35
@mfeingol Can you please test with 4.4.0.991640? We put in a bunch of related fixes in that release. Thanks!

**Comment by mfeingol** [comment] 2020-02-06 21:06
@samhouts: the problem still exists in `4.4.0.991640`:

**System.ObjectDisposedException:** 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer'.'

```
 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#	Annotated Frame
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#	Annotated Frame
 	0x20 in Android.Runtime.DynamicMethodNameCounter.32	C#	Annotated Frame
 	0x2E in Java.Interop.JniPeerMembers.AssertSelf	C#	Annotated Frame
 	0x1 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualObjectMethod	C#	Annotated Frame
 	0x12 in Android.Views.View.get_Context	C#	Annotated Frame
 	0x20 in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnToolbarItemPropertyChanged at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:911,4	C#	Annotated Frame
 	0x12 in Xamarin.Forms.BindableObject.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229,7	C#	Annotated Frame
 	0x2 in Xamarin.Forms.Element.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\Element.cs:353,4	C#	Annotated Frame
 	0x11B in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:461,5	C#	Annotated Frame
 	0x17C in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397,5	C#	Annotated Frame
 	0x227 in Xamarin.Forms.BindingExpression.ApplyCore at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:156,5	C#	Annotated Frame
 	0x48 in Xamarin.Forms.BindingExpression.Apply at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:52,5	C#	Annotated Frame
 	0x7 in Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0 at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:741,27	C#	Annotated Frame
 	0xBF in Xamarin.Forms.BindingExpression.BindingExpressionPart.PropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:752,6	C#	Annotated Frame
 	0x15 in Xamarin.Forms.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:645,6	C#	Annotated Frame
>	0x13 in Sideroads.Observable.OnPropertyChanged at C:\Operations\Build\Home\Sideroads\Source\Sideroads.Core\Helpers\Observable.cs:23,63	C#	Symbols loaded.
 	0x28 in Sideroads.Observable.Set<bool> at C:\Operations\Build\Home\Sideroads\Source\Sideroads.Core\Helpers\Observable.cs:19,13	C#	Symbols loaded.
 	0xE in Sideroads.TrackingLogic.set_HasTrackPoints at C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Shared\Helpers\TrackingLogic.cs:188,19	C#	Symbols loaded.
 	0x25 in Sideroads.TrackingLogic. at C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Shared\Helpers\TrackingLogic.cs:673,17	C#	Symbols loaded.
 	0xE in Java.Lang.Thread.RunnableImplementor.Run	C#	Annotated Frame
 	0xA in Java.Lang.IRunnableInvoker.n_Run	C#	Annotated Frame
 	0x11 in Android.Runtime.DynamicMethodNameCounter.32	C#	Annotated Frame
```

**Comment by samhouts** [comment] 2020-02-06 21:11
@mfeingol  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mfeingol** [comment] 2020-02-06 23:07
@samhouts: here's a small repro project, based on your master/detail sample: https://github.com/mfeingol/repros/tree/master/PropertyChangeODE.

This code is likely triggering the issue: https://github.com/mfeingol/repros/blob/master/PropertyChangeODE/PropertyChangeODE/Views/ConditionalToolbarItem.cs#L23

To reproduce the issue:

1. Run the project in an Android emulator. I'm using Android 10.
2. Click on the hamburger menu and select 'About'. You should see the crash in a second or two.

And yes, the project works with `4.4.0.991265`, but crashes with `4.4.0.991640`.

**Comment by mjfreelancing** [comment] 2020-02-07 12:40
I have a similar issue at the moment with `4.4.0.991640`

```
System.ObjectDisposedException
  Message=Cannot access a disposed object.
Object name: 'Android.Graphics.Drawables.GradientDrawable'.
```
In my case I have two pages that I am toggling between (bottom tabs). As I switch from one page to the other I am changing themes (changing XAML resources). After I have switched pages around 6 times the app crashes with the above error.

My two pages each call something like this:

```
protected override void OnAppearing()
{
  SetCurrentTheme(_styles);
  base.OnAppearing();
}
```

where:
* _styles is a new'd up XAML file (which is a ResourceDictionary)
* the styles are simply merged into the app ResourceDictionary
* the pages are using dynamic resources (obvious, but thought I'd mention it)

**Comment by mjfreelancing** [comment] 2020-02-08 08:30
> I don't have a cut down demo, but my project isn't complex; especially for this issue.
> https://github.com/mjfreelancing/XF.Material.Themer

I should mention that the class called `CurrentTheme` currently assigns property values using reflection. The code below is my original code (still present for your reference) and using this results in the provided stack trace and exception (a different set of errors are reported when then reflection version is used but the underlying problem is the same.

```
//Primary = themeColors.Primary;
//PrimaryVariant = themeColors.PrimaryVariant;
etc...
```

**Comment by kvpt** [comment] 2020-02-08 17:15
@mfeingol I tested your reproduction.
The reproduction is a bit extreme, it use a while(true), if I use a booleen to exit the loop when the page disappear it doesn't crash anymore. 

That being said, this reveal an issue caused by the removal of an ToolbarItem.
The problem is I think a design flaw in the ToolbarTracker class.
The CollectionChange EventHandler take an EventArgs and not NotifyCollectionChangedEventArgs.
Because of that when an item is removed, the toolbar is always reconstructed, but the removed item(s) are lost (because not NotifyCollectionChangedEventArgs) which cause the event to not be unsubscribed which cause leak or even a crash with a specific timing.

To fix that, two solutions :
- Use covariance to send NotifyCollectionChangedEventArgs instead of EventArgs, but will need cast in the consumer of the class which is not very maintainable
- Introduce a new EventHandler ItemChange with a NotifyCollectionChangedEventArgs, cleaner but will introduce two similar events
@samhouts 

@mjfreelancing Your case is different, open an new issue, this will allow a better tracking.

**Comment by mfeingol** [comment] 2020-02-08 17:29
@kvpt thanks for looking.

It's definitely an extreme repro. I used a while loop to ensure the repro was sufficiently illustrative.

Real life is more what you'd expect: relevant event happens, property is set, toolbar management code runs. In that case, I see the same crash a decent percentage of the time. I'm using a weakeventlistener to subscribe to the trigger event, so the window of opportunity is between (I think) departure from the page and the GC running to dispose the weakeventlistener.

**Comment by kvpt** [comment] 2020-02-08 17:46
Made a PR that fix the issue by adding a new event which allow to track the deletion.
@samhouts  If another approach is preferable, let me know.

**Comment by mjfreelancing** [comment] 2020-02-08 22:26
@kvpt I will raise a new issue after trying to trim down the sample repo into a project I can attach

**Comment by mjfreelancing** [comment] 2020-02-08 23:19
@kvpt I have added #9488

**Closed** 2020-02-19 04:25 UTC
Labels: a/toolbar, e/2 :clock2:, has-stacktrace, i/high, i/regression, in-progress, mobcat, p/Android, t/bug :bug:
