### ISSUE TITLE
[Shell] navigation - flickering

### ISSUE THREAD

**Issue by Zelenoocko** [xamarin/Xamarin.Forms#5755] opened 2019-03-29 16:09 UTC
### Description
When user navigates between pages (via shell flyout menu) you can see black flickering. You can see same behavior, when you use Shell.GoToAsync method (in second example there is redirect from Page 2 to Page 3).

### Steps to Reproduce

1. Open flyout menu
2. Navigate to another page
3. See black screen between navigation

Or

1. Go to page 2
2. There is redirect to Page 3 
3. See black screen between both navigations

### Expected Behavior
Some kind of transition between pages

### Actual Behavior
Black screen between navigation

### Basic Information

- Version with issue: 4.0.0.250467-pre7
- IDE: Visual Studio 2017 (15.9.10)
- Platform Target Frameworks: .NET Standard 2.0.3 
  - Android: 9
- Android Support Library Version: 28.0.0.1
- Affected Devices: Samsung Galaxy Note9

### Reproduction Link

Original: [NavigationFlickering.zip](https://github.com/xamarin/Xamarin.Forms/files/3023389/NavigationFlickering.zip)

Updated: [NavigationFlickeringWithRedirect.zip](https://github.com/xamarin/Xamarin.Forms/files/3025263/NavigationFlickeringWithRedirect.zip)

**Comment by kingces95** [comment] 2019-03-30 03:52
![1D42E232-0C0F-45AF-B8E0-33EDB08D6F2C](https://user-images.githubusercontent.com/4120386/55271076-70ccb700-524b-11e9-879b-d8104dbacaf5.GIF)
I guess it could be flickering a bit...

**Comment by Zelenoocko** [comment] 2019-03-30 08:15
> ![1D42E232-0C0F-45AF-B8E0-33EDB08D6F2C](https://user-images.githubusercontent.com/4120386/55271076-70ccb700-524b-11e9-879b-d8104dbacaf5.GIF)
> I guess it could be flickering a bit...

Hi, first It looks much more smoother then what I can see on my mobile. Second it's much more visible in case when you call GoToAsync manualy when flayout is not displayed. I've added updated example, so now when you go to Page 2, there is redirect to Page 3.

**Comment by hhuseyinpay** [comment] 2019-04-24 10:23
I guess this is related #4398

**Comment by samhouts** [comment] 2019-05-07 23:13
Duplicate of #5216

**Closed by samhouts** 2019-05-07 23:13 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:

**Comment by wesoos** [comment] 2019-05-30 15:51
The flickering is still happening when using GoToAsync

**Comment by wagenheimer** [comment] 2019-08-23 11:21
This bug is not closed! It's still happening!

**Comment by ahmedalejo** [comment] 2020-03-28 10:40
Pre anniversary for this bug 🎂😂

**Comment by aodegov** [comment] 2022-01-13 02:32
It's still happening.
Only not on Android emulators, but on real Android devices.
Once you pressed on shell menu Item you'll see the flickering

**Comment by Diaver** [comment] 2023-11-14 01:53
Issue still here :(
