### ISSUE TITLE
[Bug] Using FontImageSource for a ToolbarItem makes problems with using the font for a Label in Android

### ISSUE THREAD

**Issue by leshy06** [xamarin/Xamarin.Forms#6719] opened 2019-06-30 10:22 UTC
### Description

I have two pages. On the first page this a ToolbarItem with Icon as FontImageSource.

On the second page there is a Label, which uses the same Font as FontImageSource on the first page.

By navigating first time to second page everything is OK. After navigating back and again to the second page the displayed image in the Label is corrupt.

The problem occurs only in Android.

### Basic Information

- Version with issue: 4.0.0.540366

### Screenshots
![image](https://user-images.githubusercontent.com/884112/60395171-d6249280-9b2f-11e9-984b-9484efcb6545.png)
![image](https://user-images.githubusercontent.com/884112/60395177-f2c0ca80-9b2f-11e9-87c7-0b9b208fcc14.png)
![image](https://user-images.githubusercontent.com/884112/60395186-1126c600-9b30-11e9-8b76-6fdd12797c0e.png)

### Reproduction Link

https://downloads.membrain-it.com/bugs/app1.zip

**Comment by toomasz** [comment] 2019-06-30 11:08
Duplicate of #6317
See my comment for workaround

**Comment by samhouts** [comment] 2019-07-04 04:42
Duplicate of #6317

**Closed by samhouts** 2019-07-04 04:42 UTC
Labels: p/Android, s/unverified, t/bug :bug:
