### ISSUE TITLE
MasterDetailPage loses menu icon on iOS after reusing NavigationPage as Detail

### ISSUE THREAD

**Issue by OPunktSchmidt** [xamarin/Xamarin.Forms#1509] opened 2018-01-05 11:08 UTC
### Description

MasterDetailPage loses menu icon on iOS after reusing NavigationPage as Detail. This happens only on iPhone.

Workaround: Always create a new NavigationPage  and don't use methods like PopToRootAsync / PushAsync.

Bug already reported here but still not fixed: https://bugzilla.xamarin.com/show_bug.cgi?id=41038

### Steps to Reproduce

To reproduce the issue run this application:

    public class App : Application
    {
        public App()
        {
            MainPage = new MainMasterDetailPage();
        }
    }

    public class MainMasterDetailPage : MasterDetailPage
    {
        NavigationPage _navPage;

        public MainMasterDetailPage()
        {
            Title = "Main";

            var btnViewA = new Button() { Text = "ViewA" };
            btnViewA.Clicked += Button_Clicked;

            var btnViewB = new Button() { Text = "ViewB" };
            btnViewB.Clicked += Button_Clicked;

            var stack = new StackLayout();
            stack.Children.Add(btnViewA);
            stack.Children.Add(btnViewB);

            var master = new ContentPage() { Title = "Master", Content = stack };

            _navPage = new NavigationPage(new ViewA());

            Master = master;
            Detail = _navPage;
        }

        private async void Button_Clicked(object sender, EventArgs e)
        {
            Page root = _navPage.Navigation.NavigationStack[0];

            await _navPage.Navigation.PopToRootAsync(false);

            Page newRoot = null;

            var btn = (Button)sender;
            if (btn.Text == "ViewA")
                newRoot = new ViewA();
            else
                newRoot = new ViewB();

            await _navPage.Navigation.PushAsync(newRoot);

            _navPage.Navigation.RemovePage(root);
        }
    }

    public class ViewA : ContentPage
    {
        public ViewA()
        {
            Title = "ViewA";
            Content = new Label() { Text = "View A" };
        }
    }

    public class ViewB : ContentPage
    {
        public ViewB()
        {
            Title = "ViewB";
            Content = new Label() { Text = "View B" };
        }
    }

### Expected Behavior

MasterDetailPage **should not** lose menu icon when reusing NavigationPage 

### Actual Behavior

MasterDetailPage lose menu icon when reusing NavigationPage 

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: -
- IDE: VS 2017
- Platform Target Frameworks: iOs 11.2
- Affected Devices: iPhone, Works on iPad

### Reproduction Link

https://bugzilla.xamarin.com/show_bug.cgi?id=41038

**Comment by dhaligas** [comment] 2018-01-05 16:01
I can confirm this as well

**Comment by kingces95** [comment] 2018-01-06 00:39
@OPunktSchmidt @dhaligas I'm unable to reproduce this issue on the latest version of forms. Have you verified this on the latest version of forms? Could you attach a screen shot to show which icon you expect to persist after clicking on either ViewA or ViewB?

**Comment by PureWeen** [comment] 2018-09-28 23:39
I've tested this one as well with the provided use case and can't reproduce.

Closing for now. If the issue is still present in the latest 3.2 Forms release can you please attach a repro?

**Closed by PureWeen** 2018-09-28 23:39 UTC
Labels: e/2 :clock2:, p/iOS 🍎, t/bug :bug:

**Comment by eltonmrk** [comment] 2018-10-13 19:38
Please check that issue again. It still occurs in XF 3.2.0.871581 under similar conditions. Mainly by rotating from portrait to landscape mode after showing the root page by poping child pages.

**Comment by phamthanhtong** [comment] 2018-10-15 08:09
I have the same issue in XF 3.2.0.871581
