### ISSUE TITLE
[Enhancement] Map Pin Icons in Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by JamesRoche** [xamarin/Xamarin.Forms#9878] opened 2020-03-07 09:11 UTC
## Summary
Setting the icon of a map is such a common use case it should be included in the framework without the need to create a custom renderer.

## API Changes

The Pin class should expose a property of type ImageSource and this should be fed into the relevant native renderer for map pins. Null image properties would default to the current behavior.

The Pin class should expose an Achor property that would be passed into the native renderer to allow for flexible anchoring of pin icons.

e.g.

           var pin = new Pin
            {
                Type = PinType.Place,
                Position = new Position(lat, lon),
                Label = "L:abel",
                Address = "Address",
               Icon = new ImageSource(),
               Anchor = new Point(0.5,0.5)
            };
            Map.Pins.Add(pin);

## Intended Use Case
Development of map focused applications that show multiple data types as Pins on the Map control. Use of non-standard icons shapes for adding a unique styling to map pins.

**Comment by VladislavAntonyuk** [comment] 2020-03-07 09:50
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/8252

**Comment by jfversluis** [comment] 2020-03-25 09:57
Thanks for finding that @VladislavAntonyuk :)

As pointed out this is a duplicate @JamesRoche. I'll close this one so we can track progress in the other. If you have any additional needs or more detailed ideas, please feel free to add them there.

**Comment by jfversluis** [comment] 2020-03-25 09:57
Duplicate of #9878

**Closed by jfversluis** 2020-03-25 09:57 UTC
Labels: proposal-open, t/enhancement ➕

**Comment by surens19** [comment] 2020-12-10 14:09
pin does not contain Icon
