### ISSUE TITLE
[Android] PanGestureRecognizer doesn't work with ScrollView/ListView and TapGesture

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#1977] opened 2018-02-26 13:48 UTC
Hi Xamarin

//Here is pseudocode below
var parent = new AbsoluteLayout(); // Has got PAN gesture
var child = new AbsoluteLayout(); // Has got TAP gesture OR ScrollView/ListView
parent.Children.Add(child);

So, in those cases we lose ability to handle PanGesture, because Scroller/TapGesture prevent pan touches..

**Comment by kingces95** [comment] 2018-03-02 20:37
Please include a full reproduction.

**Comment by AndreiMisiukevich** [comment] 2018-03-02 21:40
@kingces95 

here is the repository with reproduction
https://github.com/AndreiMisiukevich/PanGestureRecognizerIssueReproduction

**Comment by AndreiMisiukevich** [comment] 2018-03-05 18:41
@kingces95 sorry for disturb.
Is it, what you asked me? Is it clear?

I can provide more info, if you wish.

**Comment by hartez** [comment] 2018-03-09 23:40
@AndreiMisiukevich That is what we needed. Thank you.

**Comment by GihanWijesingheCreative** [comment] 2018-03-15 03:49
I am also having the same issue.

**Comment by hartez** [comment] 2019-01-29 20:53
@ViktorBylbas Please file a separate issue for SwipeGesture.

**Comment by AndreiMisiukevich** [comment] 2019-01-29 21:02
@hartez i guess, it can be the same one

Scrollable views steal touches (have more priority)..

**Comment by nwilliams** [comment] 2019-02-27 01:39
I just ran into this bug trying to use a SwipeGestureRecognizer on a Frame inside a ScrollView. Is there a known workaround? Considering this issue was opened a year ago I don't have much hope for a fix in the near future.

**Comment by AndreiMisiukevich** [comment] 2019-02-27 01:42
@nwilliams for my nuget package i solve it with renderer

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs

OnTouchEvent
OnInterceptTouchEvent

But i had to write renderer for scrollview too https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/ParentScrollViewRenderer.cs

**Comment by nwilliams** [comment] 2019-02-27 01:55
@AndreiMisiukevich, thank you for the fast reply. I was hoping to avoid building a custom renderer but there may not be any way around it.

Also, your CardsView package looks very well made. I'll keep it in mind for future projects. :)

**Comment by groege** [comment] 2019-11-05 13:57
Any news on this? Would be nice to have a Swipe delete feature (same thing for collectionview)

**Comment by samhouts** [comment] 2020-06-03 17:02
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by AndreiMisiukevich** [comment] 2020-06-03 21:22
hey @samhouts 
I still can replicate this issue on my sample https://github.com/AndreiMisiukevich/PanGestureRecognizerIssueReproduction

**I updated to latest PRE-release version**

**Comment by samhouts** [comment] 2020-06-03 21:52
Thank you, @AndreiMisiukevich !!!

**Comment by ViktorBylbas** [comment] 2020-06-04 04:43
I resolved my problem SwipeGesture does not work with ScrollView:
https://stackoverflow.com/questions/54202966/xamarin-forms-swipegesture-and-scrollview-dont-work-together-on-android/54480748#54480748

**Comment by kefyru** [comment] 2020-06-30 12:17
Is there any solutions for this problem?
PanGesture still does not work inside ScrollView on Android. On IOS works fine.

**Comment by AndreiMisiukevich** [comment] 2020-06-30 12:33
> Is there any solutions for this problem?
> PanGesture still does not work inside ScrollView on Android. On IOS works fine.

Yes, it is

Check how I handled it in my nuget https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs (This Carousel works fine inside Scrollable views)

**Comment by kefyru** [comment] 2020-07-02 09:32
Thanks, but i found that setting ScrollView.InputTransparent="True"  solves my problem

**Comment by eli191** [comment] 2020-07-31 20:07
> Thanks, but i found that setting ScrollView.InputTransparent="True" solves my problem
Doing so for me doesn't allow the scroll of the elements in the fingers are on the elements but only swipe outside the elements in the scrollview.

**Comment by Abdel-Fattah-Radwan** [comment] 2021-01-06 09:20
> Thanks, but i found that setting ScrollView.InputTransparent="True" solves my problem

This fixes the issue but may not be the desired solution for some people. (It works for me though)

**Comment by jorgediegocrespo** [comment] 2021-04-16 20:32
Is there any solutions for this problem?
I´m using a pangesture and a carouselView and it works fine on iOS, but on Android doesn´t. Anyone knows how to solve it?
Thanks!!

**Comment by Abdel-Fattah-Radwan** [comment] 2021-04-16 21:32
> Is there any solutions for this problem?
> I´m using a pangesture and a carouselView and it works fine on iOS, but on Android doesn´t. Anyone knows how to solve it?
> Thanks!!

Try setting `InputTransparent` to `True` on your `CarouselView`.

**Comment by jorgediegocrespo** [comment] 2021-04-17 20:48
It doesn’t work. I have solved my problem using the pancardview nuget and extending cardviewrenderer to customize pan gestures as I need.

**Comment by jeyakasipandi** [comment] 2021-06-24 12:17
@samhouts  Any update on this?

**Comment by fireflypulse** [comment] 2021-09-23 16:53
I'm currently using a Webview and running into the same issue. Works fine on iOS, but not Android.

Setting `InputTransparent` to `True` does fix the problem, but creates another issue, can no longer interact with the webview.  

@samhouts can we get an update on this?

**Closed** 2022-10-25 03:06 UTC
Labels: t/bug :bug:, help wanted, e/9 :clock9:, a/gestures 🖖, up-for-grabs, a/listview
