### ISSUE TITLE
[Previewer, Android] Custom font throws an error 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3687] opened 2018-08-31 02:14 UTC
### Description

Original issue. https://bugzilla.xamarin.com/show_bug.cgi?id=57417#c5

I can confirm this still happens.

### Steps to Reproduce

1. Preview an Android UI with a custom font. 

### Expected Behavior
Renders

### Actual Behavior
Errors

### Basic Information

- Version with issue: still present in 3.2

### Reproduction
https://github.com/microsoft/ConferenceVision

**Comment by alanmcgovern** [comment] 2018-09-11 13:15
I don't know why this is assigned to me, but ill assume this is a dupe of: https://github.com/xamarin/Xamarin.Forms/issues/3520

**Closed by alanmcgovern** 2018-09-11 13:15 UTC
Labels: e/2 :clock2:, p/Android, t/bug :bug:

**Comment by alanmcgovern** [comment] 2018-09-11 13:17
NOTE: Issues which are actually in the forms previewer should be tagged with the 'forms-previewer' label. That's what surfaces them to us.
