### ISSUE TITLE
Argument null exception for TextDecorations on null  strings

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/Xamarin.Forms#5312] opened 2019-02-19 14:03 UTC
_From @wadebaird on February 15, 2019 20:10_

### Steps to Reproduce

0. iOS only
1. Model a Label bound to a string that is null such as this:
 `<Label` x:Name="AddressLabel" Text="{Binding Business.FullAddress}" TextDecorations="Underline" />`
2. Load the Form

### Expected Behavior
Form loads fine, doesn't show the label
### Actual Behavior
System.ArgumentNull exception occurs with parameter "other"
### Environment

```
```

### Example Project (If Possible)

_Copied from original issue: xamarin/xamarin-macios#5617_

**Comment by mandel-macaque** [comment] 2019-02-19 14:03
_From @dalexsoto on February 15, 2019 20:24_

Hello @wadebaird, thank you for your report!

Is there any chance you could provide either an example project or a code snippet of what you are trying to accomplish?

Also your version information would be handy, the easiest way to get exact version information:

 - On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
 - On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

 Then copy/paste the version information (you can use the "Copy Information" button).

 We look forward to hearing from you!

**Comment by mandel-macaque** [comment] 2019-02-19 14:03
_From @wadebaird on February 15, 2019 21:46_

Haha, I did, but it got hidden with the formatting. I updated it so it shows.

**Comment by mandel-macaque** [comment] 2019-02-19 14:03
@wadebaird  thanks for the report! Looking at the sample code (xml) this is a forms issue. I'll be moving the issue to the correct repo.

**Comment by mandel-macaque** [comment] 2019-02-19 14:04
@wadebaird developers in this repo should be able to deal with the issue correctly.

**Comment by AndreiMisiukevich** [comment] 2019-02-19 15:01
https://github.com/xamarin/Xamarin.Forms/pull/5013 ?

**Comment by samhouts** [comment] 2019-02-19 17:19
Duplicate of #5003

**Closed by samhouts** 2019-02-19 17:19 UTC
Labels: iOS
