### ISSUE TITLE
[Bug] Shell.FlyoutBehavior="Disabled" not working android emulator

### ISSUE THREAD

**Issue by xam-dev** [xamarin/Xamarin.Forms#7985] opened 2019-10-14 00:08 UTC
### Description
Shell.FlyoutBehavior="Disabled" does not make the flyout not appear when the user swipes from left to right. I have encountered this in android emulator (Android 9.0) and on an android phone.

### Steps to Reproduce

1.  In a xamarin.forms shell project, add flyout to AppShell.Xaml
2. `<FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent Title="browse" ContentTemplate="{DataTemplate local:ItemsPage}" />
        <ShellContent Title="about" ContentTemplate="{DataTemplate local:AboutPage}" />
    </FlyoutItem>`
3. In one of the pages like say AboutPage add `Shell.FlyoutBehavior="Disabled"` in the ContentPage tag

### Expected Behavior
Flyout should not appear when the user swipes from left to right

### Actual Behavior
The flyout appears.

- Version with issue: 4.2.0.848062
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0 - API 28 
  - UWP:   
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

**Comment by techduggu** [comment] 2019-10-15 08:30
Hi @jsuarezruiz / @PureWeen ,

I tried to reproduce this issue with official Shell Sample 'Xaminals' initially with version v.4.2.0.709249 (purposely as I know that it has broken FlyoutBehavior as per https://github.com/xamarin/Xamarin.Forms/issues/7656#issuecomment-537648518) and as expected, it didn't work.

I then upgraded 'Xaminals' to latest stable version v.4.2.0.848062 (considering your [PR#7254](https://github.com/xamarin/Xamarin.Forms/pull/7254) was merged to vCurrent (4.2.0)) but again it didn't work.

In order to fix this issue, I then tried to reproduce this in Xamarin.Forms solution (master branch), but unable to reproduce the mentioned issue as it is working fine (tried replicating using existing `ShellFlyoutBehavior.cs` 'Disable Flyout Behavior' button and also created a new Issue7985.xaml page with Shell as a base class).

Does 'master' branch of Xamarin.Forms is not pointing to latest stable: v.4.2.0.848062 ? Or Is this issue fixed with any pre-release of v.4.3 (though unable to see any associated PR)?

Another thing as a side note I noticed that [FlyoutBehavior](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#flyout-behavior) can no longer be set to `FlyoutItem`, `ShellContent`, and page objects, to override the default flyout behavior. It is only available to set on `Shell` object. If this is correct, we should probably update the Xamarin doc. to avoid issues (refer 'Steps to Reproduce' section of this ticket).

Thanks!

**Comment by techduggu** [comment] 2019-10-15 08:35
This is with Xamarin.Forms (master) branch (where Flyout Behavior is working as expected):

![image](https://user-images.githubusercontent.com/17450941/66814698-acfc0680-ef54-11e9-9a2e-db84b4a00c5f.png)

**Comment by techduggu** [comment] 2019-10-15 08:40
This is with Xaminals (v.4.2.0.848062) (where Flyout Behavior is not working as expected):

![image](https://user-images.githubusercontent.com/17450941/66815151-64911880-ef55-11e9-91b7-fb35db2f8bca.png)

**Comment by techduggu** [comment] 2019-10-15 09:24
Reg. this question - 

> Does 'master' branch of Xamarin.Forms is not pointing to latest stable: v.4.2.0.848062 ? Or Is this issue fixed with any pre-release of v.4.3 (though unable to see any associated PR)?

Just watched @jfversluis yesterday's stream recording and now it's clear. So 'master' branch contains future release changes (probably v.4.4) and may be that's the reason I'm not able to reproduce this bug with master branch. So, Does it mean this issue fix will be available with future versions? (I think it might be blocker for the people using the latest stable version v.4.2.0.848062).
Thanks!

**Comment by PureWeen** [comment] 2019-10-15 23:14
@techduggu Thank you for looking into this one!!!

> I'm not able to reproduce this bug with master branch

Same... Which I'm currently confused about :-/ 
I tested against the latest nightly and it's broken there so I'm thinking it's some ordering of initialization that's causing this but not sure yet.

**Comment by PureWeen** [comment] 2019-10-16 00:40
Alright it looks like when you use ContentTemplate the flyout is calculated too early before the content page is renderered so it fails to walk up the tree and find the effective value :-/ 

If you define the default page inside the ShellContent opposed to in the ContentTemplate that should let you work around it for now

**Comment by PureWeen** [comment] 2019-10-16 16:15
@techduggu I'll get it

I should have a PR today or tomorrow. Thanks again for all the exploration

**Closed** 2019-10-29 23:52 UTC
Labels: a/shell :shell:, in-progress, p/Android, t/bug :bug:
