### ISSUE TITLE
[Bug] [Android] Shell layout issue on Android devices

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#7359] opened 2019-09-03 06:33 UTC
### Description
Hi,
I have a XF Shell application.
In this application I have declared a route outside the AppShell route using 

> RegisterRoute:Routing.RegisterRoute("NextPage", typeof(NextPage));

(this code is inside the App.xaml.cs)

Then, in my main Page I have added a button that would open the NextPage.
```
<Button HorizontalOptions="StartAndExpand" VerticalOptions="StartAndExpand" Command="{Binding OpenNextPageCommand}" Text="click me" />
```
The `OpenNextPageCommandCommad `is this (do not pay attention to the parameter):

```
Guid key = Guid.NewGuid();
Shell.Current.GoToAsync($"NextPage?guid={key.ToString()}");
```
In the NextPage I have added some labels with `VerticalOptionsand HorizontalOptions` set to **Start** and some others with these properties set to **CenterAndExpand**.

On Android the labels that have the two properties setted to Start, aren't shown.
On iOS all labels are shown correctly.

Attached a video and a sample.

### Expected Behavior
Same behavior on iOS, the label should be shown in the correct position.

### Actual Behavior
The labels that have the two properties setted to Start, aren't shown.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: 4.1.0.709244
- Affected Devices: Android

### Screenshots
![Image](https://i.imgur.com/rqnY2Mj.gif)

### Reproduction Link
[Here](https://ufile.io/wfp8w613)

**Comment by mjfreelancing** [comment] 2019-09-03 14:28
I have the same issue. To test, I created a brand new shell project. Prior to updating Xamarin forms I confirmed the page navigation was perfect. After the update from v4.1.0.555618 to v4.2.0.709249 the navigated page is missing the top content.

In a seperate test I added a StackLayout and filled it with labels - the first 3 labels are not shown.

**Comment by BioTurboNick** [comment] 2019-09-03 20:25
Probably duplicate of #7240. Content hidden by top bar.

**Comment by samhouts** [comment] 2019-09-04 17:21
Duplicate of #7240

**Closed by samhouts** 2019-09-04 17:21 UTC
Labels: a/shell :shell:, i/regression, p/Android, s/unverified, t/bug :bug:
