### ISSUE TITLE
Xamarin.Forms Button

### ISSUE THREAD

**Issue by SokHeangKhun** [xamarin/Xamarin.Forms#3256] opened 2018-07-10 09:07 UTC
I have an issue of Xamarin.Forms button on Android. I have ask the quest on stackoverflow. Here is the link https://stackoverflow.com/questions/50824759/xamarin-forms-button-background

**Comment by GalaxiaGuy** [comment] 2018-07-10 10:19
This could be a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3220

**Comment by SokHeangKhun** [comment] 2018-07-10 10:24
How could I solve this?

**Comment by pauldipietro** [comment] 2018-07-10 13:48
Duplicate of the aforementioned issue; please use the other issue for further discussion

**Closed by pauldipietro** 2018-07-10 13:48 UTC
