### ISSUE TITLE
[Bug]Blank Space in TabbedPage Xamarin.iOS 13

### ISSUE THREAD

**Issue by pdamco** [xamarin/Xamarin.Forms#8710] opened 2019-11-28 18:30 UTC
Version with issue:

Last known good version: iOS 12 | Xamarin.iOS 12

IDE: VS Mac 8.3.10

Platform Target Frameworks:

iOS: 11.2
Android: 10
Nuget Packages: 3.4

Affected Devices: iOS

XF version is 3.4 but i have tryed to upgrad to 4.3 nothing happened same space is showing.
iOS version is 13
This is only on iOS not happening on Android.

Blank Space is showing after installing Xamarin.iOS 13. This is working fine with Xamarin.iOS 12 till now.

Attached is the image.
![Screenshot 2019-11-25 at 11 25 50 PM](https://user-images.githubusercontent.com/40819488/69826749-8c54eb00-123a-11ea-8428-fac11e893255.png)

And Attaching the sample
[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3902781/Sample.zip)

I am raising this issue again just to highlight because I need to fix this to update app on App Store.

Please suggest any workaround for this.

This issue is happening because of navigation page.

If I do this 
Application.Current.MainPage = new NavigationPage(new MainPage());

Bottom space is showing.

but if I do this
Application.Current.MainPage = new MainPage();

No bottom space is showing.

**Comment by jfversluis** [comment] 2019-11-28 18:59
Thanks for the reproduction @pdamco!

If I run it though, I don't see anything weird... What am I supposed to see?

<img width="505" alt="Screenshot 2019-11-28 at 19 55 08" src="https://user-images.githubusercontent.com/939291/69827749-0eccb300-1219-11ea-9017-7e325375ab07.png">

The other thing I am noticing is that you are using a custom renderer to hide the actual tabbar and render your own. While this is pretty awesome! This also makes me think that this is not so much an issue with Xamarin.Forms, but probably something that changed in iOS 13 and now you need to change some code in your renderer.

I'd love to give you a suggestion, but since I don't really see anything weird in your reproduction that is kind of hard.

For instance I see someone here [on the forums](https://forums.xamarin.com/discussion/172083/hide-tabbar-in-a-tabbedpage) with the same problem. Although this is not Xamarin, I think this might be your problem right here: https://stackoverflow.com/questions/37040313/hiding-the-tabbar-and-removing-the-space

Can you work with that?

**Comment by pdamco** [comment] 2019-11-30 07:48
![Screenshot 2019-11-30 at 1 13 34 PM](https://user-images.githubusercontent.com/40819488/69897581-e0171f80-1373-11ea-8019-12c1b6cc1141.png)


I have tried these ways but nothing working.

**Comment by jfversluis** [comment] 2019-12-02 09:39
What you are seeing is a concept introduced since the "notch iPhones" came out and is described here: https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area

Documentation specific to Xamarin.Forms can be found here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout

Since this is not an issue in Forms I will be closing this issue. For questions, you will probably get better and faster answers on the Xamarin Forums or StackOverflow.

If you believe that there is an actual issue, please feel free to add more info and reopen.

Thanks!

**Closed by jfversluis** 2019-12-02 09:39 UTC
Labels: a/customrenderer, iOS 13, s/needs-info ❓, s/unverified, t/bug :bug:, t/question

**Comment by KevinAnass** [comment] 2020-04-25 15:13
Does anyone solve this white space?

**Comment by rickclephas** [comment] 2021-05-04 10:09
This is definitely a Xamarin Forms issue! 
The blank space that is visible in the original screenshot isn't the safe area.
From my tests this issue only affects physical device and not the simulators.
See #14239 for some workarounds.
