### ISSUE TITLE
[Bug][iOS] Xaminals UISearchController crash

### ISSUE THREAD

**Issue by LamijaV** [xamarin/Xamarin.Forms#7712] opened 2019-09-27 12:02 UTC
### Description
I downloaded Xaminals example. When I touch search bar, app crashes on iOS. Works on Android.

### Steps to Reproduce

1. Download example
2. Build on iOS
3. Click on search bar

### Expected Behavior
Ability to enter text and search animals.
### Actual Behavior
Keyboard opens and app crashes with unhandled exception.

2019-09-27 13:07:53.432 Xaminals.iOS[1304:176570675] -[UIKit_UISearchController___Xamarin_UISearchResultsUpdating updateSearchResultsForSearchController:]: unrecognized selector sent to instance 0x280649600

Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIKit_UISearchController___Xamarin_UISearchResultsUpdating updateSearchResultsForSearchController:]: unrecognized selector sent to instance 0x282bd7b80
Native stack trace:
	0   CoreFoundation                      0x0000000239a48530 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000238c239f8 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000239965278 <redacted> + 0
	3   CoreFoundation                      0x0000000239a4da5c <redacted> + 636
	4   CoreFoundation                      0x0000000239a4f9fc _CF_forwarding_prep_0 + 92
	5   UIKitCore                           0x000000026602e884 <redacted> + 836
	6   UIKitCore                           0x000000026602e50c <redacted> + 284
	7   UIKitCore                           0x000000026602dc68 <redacted> + 32
	8   UIKitCore                           0x00000002658494e8 <redacted> + 152
	9   UIKitCore                           0x0000000265fc1230 <redacted> + 96
	10  UIKitCore                           0x0000000265a6aaf8 <redacted> + 80
	11  UIKitCore                           0x0000000265a6ae18 <redacted> + 440
	12  UIKitCore                           0x00000002662aa104 <redacted> + 720
	13  UIKitCore                           0x000000026629d084 <redacted> + 180
	14  UIKitCore                           0x000000026584c7b0 <redacted> + 92
	15  UIKitCore                           0x000000026629cea4 <redacted> + 28
	16  UIKitCore                           0x000000026584caa0 <redacted> + 304
	17  UIKitCore                           0x0000000265fcafdc <redacted> + 296
	18  UIKitCore                           0x0000000265fb9b2c <redacted> + 352
	19  UIKitCore                           0x0000000265fe6744 <redacted> + 116
	20  CoreFoundation                      0x00000002399d989c <redacted> + 32
	21  CoreFoundation                      0x00000002399d45c4 <redacted> + 412
	22  CoreFoundation                      0x00000002399d4b40 <redacted> + 1228
	23  CoreFoundation                      0x00000002399d4354 CFRunLoopRunSpecific + 436
	24  GraphicsServices                    0x000000023bbd479c GSEventRunModal + 104
	25  UIKitCore                           0x0000000265fbfb68 UIApplicationMain + 212
	26  Xaminals.iOS                        0x00000001006bd768 Xaminals.iOS + 4298600
	27  Xaminals.iOS                        0x000000010064447c Xaminals.iOS + 3802236
	28  Xaminals.iOS                        0x000000010064443c Xaminals.iOS + 3802172
	29  Xaminals.iOS                        0x00000001002d6940 Xaminals.iOS + 207168
	30  Xaminals.iOS                        0x00000001005a5988 Xaminals.iOS + 3152264
	31  Xaminals.iOS                        0x0000000101655f44 mono_pmip + 24460
	32  Xaminals.iOS                        0x00000001016c3bbc mono_pmip + 474116
	33  Xaminals.iOS                        0x00000001016c8de4 mono_pmip + 495148
	34  Xaminals.iOS                        0x000000010163ce98 Xaminals.iOS + 20549272
	35  Xaminals.iOS                        0x000000010176e81c _Z9__isctypeim + 46888
	36  Xaminals.iOS                        0x00000001002d683c Xaminals.iOS + 206908
	37  libdyld.dylib                       0x000000023949a8e0 <redacted> + 4

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.709249, Mono 4.13.12-pre, Xamarin.iOS 12.4.0.64
- Last known good version: N/A
- IDE: VS Professional, 15.9.16
- Platform Target Frameworks:
  - iOS:  SDK 12.2 (XCode 10.2)
  - Android: SDK 28 (Works correctly)
  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone 7 plus, 12.2

### Reproduction Link
Sample from:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/

**Comment by PureWeen** [comment] 2019-10-03 00:02
@LamijaV can you try with the latest 4.3 pre3 or 4.2.0.848062 releases that just came out and let me know if those work for you?

**Comment by hartez** [comment] 2019-10-21 23:06
> I am using the search handler in my own app, not the sample app

@varyamereon Could you post the code for your search handler? Maybe that will give us a clue what it happening.

**Comment by varyamereon** [comment] 2019-10-22 13:59
> I am using the search handler in my own app, not the sample app
> 
> @varyamereon Could you post the code for your search handler? Maybe that will give us a clue what it happening.

Having tried to isolate the problem, I have found the issue only occurs when using a third party control. So whether the issue is with the third party control or the search bar I'm not sure. I will contact the publisher of the control directly, but [here](https://github.com/varyamereon/ShellSearchIssue) is a link to a sample app demonstrating the issue.

**Comment by hartez** [comment] 2019-10-28 00:07
If I remove the SF TabView from your sample app, the crash no longer occurs. I'm going to assume this is an issue with the third-party control and close this for now. If you get any new information that suggests this is an issue with Forms, reply here and we'll re-open this issue.

**Closed by hartez** 2019-10-28 00:07 UTC
Labels: a/shell :shell:, i/high, p/iOS 🍎, s/unverified, t/bug :bug:
