### ISSUE TITLE
[Feedback] Xamarin.Forms Image, Loads on Android, does not on iOS

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4547] opened 2018-11-27 20:31 UTC
### Description

<p>Using Visual Studio for Mac Community (updated to latest stable)

1.) New “Blank Xamarin.Forms App”
2.) Update all of the Nuget Packages to current
3.) Under the “Welcome to Xamarin.Forms” label add a new image control

&lt;Image Source=&quot;https://img.discogs.com/P2bwDyNI_40_POp15pPOj3lOahY=/600x437/smart/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-158120-1490159581-3776.jpeg.jpg&quot; /&gt; 
4a.) Run Android Project “Android_Accelerated_Nougat (API 25)”
     - Observe Image is displayed as expected.
4b.) Run iOS Project on “iPhone 8 iOS 12.1” Simulator
     - Observe nothing is displayed under the label, no erros are thrown and no logging is giving in the application output.

This behavior has been 100% repeatable on physical devices as well, works on any android device, fails on any iOS device.  I’ve ensured I was using the “NSUrlSession” http client and I event tried adding the “NSAllowsArbitraryLoads” to my info.plist. dispite it being a valid https endpoint w/ a good certificate.

I posted a question on the Xamarin.Forms Forums and was given a work-around but it is flaky at best and sometimes the View with refresh and the images will dissapear.  

Link to question: https://forums.xamarin.com/discussion/142154/

A note about the URL.  I’m writing a media app to integrate with https://www.discogs.com developer API and these are the url’s that are returned via their api calls and there’s really nothing I can do about it.

Thanks,
Rich</p>
<a href="https://developercommunity.visualstudio.com/content/problem/378950/xamarinforms-image-loads-on-android-does-not-on-io.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/726192">original linked feedback ticket</a>.

### Source

[736035](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736035)

**Comment by PureWeen** [comment] 2018-11-30 23:51
duplicate of
https://github.com/xamarin/Xamarin.Forms/issues/4357

**Closed by PureWeen** 2018-11-30 23:51 UTC
Labels: feedback-ticket, p/iOS 🍎
