### ISSUE TITLE
TableView FlowDirection not working with EntryCell

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3368] opened 2018-07-21 20:53 UTC
Hi,

I am doing this to show EntryCell for first name and last name with FlowDirection is RightToLeft but as you can see in the attached image it works for the Label of the EntryCell but not for the Entry cell itself.

<TableView Intent="Settings" FlowDirection="RightToLeft">
    <TableRoot>
        <TableSection Title="الاسم">
            <EntryCell x:Name="MyProfileMyNameFirstName" Label="الاسم الأول :" />
            <EntryCell x:Name="MyProfileMyNameLastName" Label="اسم العائلة:" />
        </TableSection>
    </TableRoot>
</TableView>

<img width="391" alt="screen shot 2018-07-22 at 00 52 05" src="https://user-images.githubusercontent.com/6236241/43039966-8394a1da-8d49-11e8-884a-c817d2b1c903.png">

Thanks,
Jassim

**Comment by jrahma** [comment] 2018-07-21 21:21
Also in Android it's totally ruined.

<img width="410" alt="screen shot 2018-07-22 at 01 20 08" src="https://user-images.githubusercontent.com/6236241/43040156-808bb3c6-8d4d-11e8-9fbb-c8c4be8108eb.png">

**Comment by PureWeen** [comment] 2018-07-24 16:36
Most likely a duplicate of 
https://github.com/xamarin/Xamarin.Forms/issues/3359

**Comment by jassmith** [comment] 2018-07-30 03:23
As shane said, dupe of 3359

**Closed by jassmith** 2018-07-30 03:23 UTC
