### ISSUE TITLE
I can't see Shell titleview in iOS 16. [Bug] 

### ISSUE THREAD

**Issue by swetaVanjara** [xamarin/Xamarin.Forms#15557] opened 2022-10-07 08:29 UTC
### Description
I can't see shell.titleview in iOS 16.0. It's working well in all versions except this one.

![IMG_2226](https://user-images.githubusercontent.com/30111967/194508803-ef651bf4-ec85-4c91-b933-47a8111aecb4.PNG)

     <Shell.TitleView>
        <StackLayout >

            <StackLayout Orientation="Horizontal" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">

                <Label HorizontalOptions="Center" VerticalOptions="Center" FontSize="15"  FontAttributes="Bold" TextColor="{StaticResource White}">Cart</Label>
            </StackLayout>
        </StackLayout>
    </Shell.TitleView>

### Expected Behavior
It should work in iOS 16 as well
### Actual Behavior
Right now it's not working with iOS 16 only.
### Basic Information

- Version with issue: iOS 16
- Last known good version: iOS 15

**Comment by bnoffer** [comment] 2022-10-09 12:24
This is a duplicate of #15512

@swetaVanjara check the issue mentioned above, there is a workoraound posted there that works. Implemented it myself and it works perfectly. Use the latest version of at the bottom of the issue thread.

**Comment by jfversluis** [comment] 2022-11-01 12:11
Duplicate of #15512

**Closed by jfversluis** 2022-11-01 12:11 UTC
Labels: t/bug :bug:, s/unverified
