### ISSUE TITLE
UIWebView deprecated workaround not working with a bare shell app

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Xamarin.Forms#10967] opened 2020-06-05 11:49 UTC
Trying to get an app to build for submission and can't get rid of the UIWebView reference so I tried a bare bones out of the box shell app .. same failure ...

I need help ASAP!

- Visual Studio is the latest on both Mac and Windows

![image](https://user-images.githubusercontent.com/12648793/83872885-d397c900-a700-11ea-9785-49c438e951c3.png)
Xcode is current

- I created a Xamarin Forms Shell app targeting iOS and Android on a Windows machine
- 
- Made the settings changes like you indicated
- 
- Updated the NuGet packages, none used except the ones that are defaulted with a new Xamarin Forms Shell app
![image](https://user-images.githubusercontent.com/12648793/83872933-e6120280-a700-11ea-867d-a3f067bfec60.png)

Here are my iOS build settings
![image](https://user-images.githubusercontent.com/12648793/83872975-f5914b80-a700-11ea-875b-0fa6d1e1fb41.png)

Here is the output
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/stephenhauck/Library/Caches/Xamarin/mtbs/builds/UIWebKitTest.iOS/1188bde15273392423d3b6bb90f2fefd/obj/iPhone/Release/response-file.rsp --optimize=experimental-xforms-product-type --warn-on-type-ref=UIKit.UIWebView
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1502: One or more reference(s) to type 'UIKit.UIWebView' already exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' before linking
**3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1503: One or more reference(s) to type 'UIKit.UIWebView' still exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' after linking
3>** /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -num-threads 4 -z -o bin/iPhone/Release/UIWebKitTest.iOS.app.dSYM bin/iPhone/Release/UIWebKitTest.iOS.app/UIWebKitTest.iOS
3> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/iPhone/Release/mtouch-symbols.list bin/iPhone/Release/UIWebKitTest.iOS.app/UIWebKitTest.iOS
3> /usr/bin/mdimport bin/iPhone/Release/UIWebKitTest.iOS.app/../
3> /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/iPhone/Release/UIWebKitTest.iOS.app
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

**Comment by stephenhauck** [comment] 2020-06-05 13:44
I did forget to mention that I run Resharper and MFractor as well so I have attached my source in case the generation of the project from the template was affected in some way.
[UIWebKitTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4736423/UIWebKitTest.zip)

**Comment by jfversluis** [comment] 2020-06-05 13:57
Did you actually submit this to Apple? I have seen cases where you get false positives in the build output, but Apple will accept them without a problem.

Furthermore please provide the information and output from the suggestions here: https://github.com/xamarin/Xamarin.Forms/issues/10739#issuecomment-630049076

**Comment by stephenhauck** [comment] 2020-06-05 14:03
I have not submitted to Apple .. until it stops reporting the error why try, I mean I don;t want to "wonder" every time right?

I start a command prompt 
change to the project output directory ..\UIWebKitTest.iOS\bin\iPhone\Release>

run this command "FINDSTR /M /s /i uiwebview *.* > uiwebviewresults.txt"

get this output in the file
Xamarin.Forms.Platform.iOS.dll

**Comment by stephenhauck** [comment] 2020-06-05 14:07
PLEASE, don't hesitate to ask me to run with some debug options / switches or something turned on if it will get you more information ....

I have been a paid user of Xamarin since it was Monotouch and was EXPENSIVE so I know we are in a MUCH BETTER PLACE now but we still have some issues occasionally and I am willing to help...

**Comment by stephenhauck** [comment] 2020-06-05 17:40
FYI, I just upgraded OSX (wasn't that far behind) and still get the same results ....

**Comment by saidbehaine** [comment] 2020-06-08 03:58
Hi @stephenhauck. Did you find a solution? I was trying this too: --optimize=experimental-xforms-product-type but the app crashed when apple team made tests.

[This is the crash log result](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/57/68/1b/57681b5a-5874-59a3-a9c0-e82a2126cf3f/attachment-11947709215841236295crashlog-4C187E11-7086-49A5-B28C-E4EF25A9B805.txt?accessKey=1591847375_2019382684816236850_fo%2BGivY4HcvlszekxBjhkREpOkwR3GzdFj8OgYKGqDtxbXLsJcGynfE1rh3fPHgst5rzAt6DZeMXH%2BzI%2BulNWUJsKsPln3XsUAKjR8yXlXARI9pMZceEWD2PrRxFkUDQR8L4TKOydmml1FlbbweMOYS6JoI4n%2FrAsGLWhl5adrLVS6vy4IUeE63uZMWapL86vAEH9p0U7drvJvh6EugS7MLG0QcenzU4RcaLjyg5z4DK98fGSePPlH3Irc7xfclG)

**Comment by stephenhauck** [comment] 2020-06-08 09:25
Thanks for the additional information!

I have not submitted to the app store because when I grep (findstr) after the build it finds the reference so why even bother.

I am NOT interested in GUESSING or HOPING, this is programming and I should know that when the software leaves my control that I have built the best product possible and that it will pass without issue.

Are you able to simply start a new project and get it to build without the reference being included ?

**Comment by jfversluis** [comment] 2020-06-08 10:36
I’ve just created a File > New Shell App. Applied all the necessary bits and it’s accepted by Apple without any warning. So I’m not really able to reproduce this behavior unfortunately

**Comment by stephenhauck** [comment] 2020-06-08 11:03
@jfversluis if you grep of findstr it finds the reference correct ?

**Comment by stephenhauck** [comment] 2020-06-08 11:12
I just updated to Xamarin.Forms 4.6.0.847 and findstr still reports it found a reference in 
**Xamarin.Forms.Platform.iOS.dll**

**Comment by jfversluis** [comment] 2020-06-08 11:30
I am not seeing any references or warnings in Visual Studio as well.

I have to note that this is on a Mac with Visual Studio for Mac although that shouldn't matter.
Just now I have taken the repro project that you've attached here and tried it on that.

The thing I'm noticing is that the build configuration sometimes will jump back to using the Simulator. Not sure if this is a bug in VS/VSMac or anything and if it even has to do with anything, but it's strange.

So, with your project I do see the warnings pop up in VSMac at least. Can't really determine what the difference is between your project and mine

[TestShellWebview.zip](https://github.com/xamarin/Xamarin.Forms/files/4745643/TestShellWebview.zip)

**Comment by stephenhauck** [comment] 2020-06-08 11:43
I am comparing right now ... 
Initially it builds without warning but it only has an iOS app, it is not targeting Android and iOS in the same solution.

**Comment by jfversluis** [comment] 2020-06-08 11:46
Why should Android be involved? This is a pure iOS specific problem. But I guess that is a difference. So one testing scenario could be to create a separate solution with just the bits for your iOS app then

**Comment by stephenhauck** [comment] 2020-06-08 11:57
Android should not affect it I agree ... 

So .. I made a new Shell app on VS Mac (Android included), updated nuget packages included by default and built .. it DOES NOT give the warnings !

**Comment by stephenhauck** [comment] 2020-06-08 12:09
I just created an iOS only Shell app on Visual Studio Windows and updated the included nuget packages and it fails with the warnings.

It selected the correct build configuration ...
2>------ Rebuild All started: Project: UIWebView_iOS_Only.iOS, Configuration: Release iPhone ------
![image](https://user-images.githubusercontent.com/12648793/84028721-3b4b4f80-a95f-11ea-81fa-385d83f414b5.png)


But warns ....
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1502: One or more reference(s) to type 'UIKit.UIWebView' already exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' before linking
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1503: One or more reference(s) to type 'UIKit.UIWebView' still exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' after linking

**Comment by stephenhauck** [comment] 2020-06-08 12:31
I just brought the same project from the Mac to a Windows Machine and it fails with the warnings.

**Comment by stephenhauck** [comment] 2020-06-08 12:37
BTW, not sure I mentioned .. I ONLY use the stable channel for updates and release NuGet packages!

**Comment by stephenhauck** [comment] 2020-06-08 18:17
@jfversluis can you confirm you are seeing the same thing as me ?

**Comment by jfversluis** [comment] 2020-06-09 08:12
From a quick test I think I see the same thing happening, yes.
Have you tried taking the Mac project (without warnings) to Windows and see what happens then?

If that works, then it almost certainly has to be something inside the csproj file messing things up between Mac and Windows.

**Comment by stephenhauck** [comment] 2020-06-09 09:31
OK, I just confirmed your assessment that if it's created on a Mac and built on a Mac it works.
So ... are you saying that if you get the warning and it's in **Xamarin.Forms.Platform.iOS** that it should be passed by Apple without issue and warnings outside that assembly / dll should be ignored ?

**Comment by jfversluis** [comment] 2020-06-09 10:20
The problem with these findings is, is that the results are unreliable for this part. I mean, it _could_ pass on Apples side, but you as the developer could also have done something wrong and it won't pass.

In any case, I would say this is more something on the tooling/Visual Studio/Xamarin.iOS side of things rather than a Forms thing.

**Comment by stephenhauck** [comment] 2020-06-09 10:27
OK ... so ... how would you advise us to deal with the issue at this time ?

**Comment by jfversluis** [comment] 2020-06-09 10:47
Since the binary is accepted by Apple, I would expect that the "string search" method would need to come up empty whenever a build is valid. That might be something interesting to try in this whole scenario.

Other than that, only Apple gets to decide what they accept or not and how they determine they do, so trial and error.

**Comment by stephenhauck** [comment] 2020-06-09 11:47
I am a little confused because I get these results when I build and check using "FINDSTR /M /s /i UIWebView *.* > uiwebviewresults.txt"   in the output folder 
  "..\TestUIWebView_OnMac.iOS\bin\iPhone\Release"  it still finds references 

TestUIWebView_OnMac.dll
TestUIWebView_OnMac.iOS.exe
TestUIWebView_OnMac.pdb
Xamarin.Forms.Platform.iOS.dll

with these settings..
![image](https://user-images.githubusercontent.com/12648793/84143943-6d26e980-aa25-11ea-9778-68ce56db41de.png)

It's really not supposed to be this hard ...

**Comment by jfversluis** [comment] 2020-06-09 12:09
Tbh I don't think it is that hard. Because all we are talking about here is theory. Well, not all, I have submitted two builds and they were both accepted without any problem.

I think the results you are seeing are valid. What happens is, is that the actual build happens on your Mac. So the binaries that you are looking on on Windows and you are running the `findstr` against aren't the right ones.

If you build and IPA and extract that, or locate the temp files on your mac, and inspect those, I'm sure the references won't show up. I'll open an issue for the false positives on the Xamarin.iOS repo, other than that I don't see any problem here :)

**Comment by jfversluis** [comment] 2020-06-09 12:24
As mentioned, whatever is going on, it's not Forms related. Added an issue on the X.iOS repo here: https://github.com/xamarin/xamarin-macios/issues/8814

Hence, closing this one.

Thank you so much for all the investigation, collaboration and patience so far!

**Closed by jfversluis** 2020-06-09 12:24 UTC
Labels: a/shell :shell:, a/webview, s/unverified, t/bug :bug:
