### ISSUE TITLE
[Bug] [UWP] Entry.ClearButtonVisibility="Never" does nothing on UWP

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#9229] opened 2020-01-16 08:58 UTC
### Description
I have a Simple Entry like so:

`<Entry BackgroundColor="Blue" ClearButtonVisibility="Never"/>`

And if I click into the the entry box and type something in, the clear button is visible

Xamarin.Forms V4.4.0

### Expected Behavior

Clear button invisible

### Actual Behavior

Clear button is visible

**Comment by samhouts** [comment] 2020-01-17 18:00
Duplicate of #8836

**Closed by samhouts** 2020-01-17 18:00 UTC
Labels: a/entry, p/UWP, s/unverified, t/bug :bug:
