### ISSUE TITLE
[Bug] Deployment failed on Android emulators after updating Visual Studio for Mac to 8.5 or latest version

### ISSUE THREAD

**Issue by kgouraw** [xamarin/Xamarin.Forms#10188] opened 2020-04-02 22:30 UTC
Deployment failed on Android emulators after updating Visual Studio for Mac to 8.5  (build 3183) or latest version
### Description
Build FAILED. /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: Deployment failed /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_INVALID_APK: Package couldn't be installed

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess (System.String output, System.String packageName) [0x00152] in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Internal/AdbOutputParsing.cs:341 /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass95_0.<InstallPackage>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x00016] in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/AndroidDevice.cs:753 /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in <f9d1b832704f410aa8ec771f4fe80552>:0 /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(612,2): error ADB0010: at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319

### Steps to Reproduce

1. Update Visual Studio for Mac with latest version.
2. We cannot run or deploy on any Android emulators.
3. 

### Expected Behavior
Able to deploy or debug on Android emulators 
### Actual Behavior
Unable to deploy or debug on Android emulators 
### Basic Information

- Version with issue: Visual Studio for Mac 8.5 or greater
- Last known good version: Visual Studio for Mac 8.4.x
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 

  - Android: 
- Android Support Library Version:
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/14645617/78305853-f4308080-750f-11ea-92f0-4a951fc97041.png)

### Workaround
Haven't found yet

**Comment by xamarindevelopervietnam** [comment] 2020-04-03 04:41
same on VS for Windows, v16.5

**Comment by chowarth** [comment] 2020-04-05 19:52
I ran into this a couple of weeks ago after a VS2019 update on Windows. I'm not sure of the exact problem or why it is happening but I managed to solve it by adding the following to my `*.Android.csproj`:
```xml
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <BundleAssemblies>false</BundleAssemblies>
    <AndroidDexTool>dx</AndroidDexTool>
```
These are all the default values that matched the project settings, I simply added the property. It's as though VS isn't picking up non-declared properties?

**Comment by PureWeen** [comment] 2020-04-05 20:01
@JonDouglas  ?

**Comment by JonDouglas** [comment] 2020-04-06 14:23
Does this continue to happen for those who uninstall their app manually from the device and re-deploy? How often does this happen if so? Does anyone have a `.csproj` available to share of their Android project so we can understand if there's any features being used here that might enable this behavior? Does this happen in a `File -> New Project?`

@chowarth What property exactly did you add here? The only differing one to the defaults I see is using `dx` as `d8` is the new default in 16.5 / 8.5.

https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.2#d8-enabled-by-default-for-all-projects

**Comment by chowarth** [comment] 2020-04-06 14:45
@JonDouglas the properties in my previous comment were ones I added. They were not needed to be set prior to the recent update.

**Comment by JonDouglas** [comment] 2020-04-06 14:51
@chowarth Yes please try that out and let us know! That will help us pinpoint this issue.

**Comment by JonDouglas** [comment] 2020-04-06 15:55
This may be related to https://github.com/xamarin/xamarin-android/issues/4478 which seems to have a solution in progress.

**Comment by chowarth** [comment] 2020-04-06 18:34
@JonDouglas that does appear to be related.

I tried `File -> New Project` with a Xamarin.Forms blank page app, I was able to deploy to the emulator without any issues.

With the existing project I experienced this on before, I rolled back to the commit before my fix, these are the current settings - this does not deploy:
![existing-android-project-settings](https://user-images.githubusercontent.com/10574476/78592187-9b792480-783c-11ea-9286-448faf45c38b.PNG)

Opening the project and closing it again automatically added the following properties to the `csproj` that were not present before:
```xml
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <BundleAssemblies>false</BundleAssemblies>
```
Building the project does not deploy to the emulator. I then did the following:

- Changed the `Dex compiler` option to `d8` - this does not build and deploy to the emulator
  - This added the `<AndroidDexTool>d8</AndroidDexTool>` property to the `csproj`
- Changed the `Dex compiler` option back to `dx`, which it was originally supposed to be set to
  - This updated the `csproj` property to `<AndroidDexTool>dx</AndroidDexTool>`

I am now able to build and deploy to the emulator.

**Comment by kgouraw** [comment] 2020-04-09 16:28
I did below and it solved the issue.  So from now, do we need to use next generation dex compiler and code shrinker?

-  <AndroidLinkTool>proguard</AndroidLinkTool>
+    <AndroidLinkTool>r8</AndroidLinkTool>   
-    <AndroidDexTool>dx</AndroidDexTool>
+    <AndroidDexTool>d8</AndroidDexTool> 
+<AndroidEnableMultiDex>false</AndroidEnableMultiDex>

**Comment by samhouts** [comment] 2020-05-30 00:09
Duplicate of xamarin/xamarin-android#4478

**Closed by samhouts** 2020-05-30 00:09 UTC
Labels: p/Android, s/unverified, t/bug :bug:
