### ISSUE TITLE
[Bug] 4.0 Regression ListView with RecycleElement and HasUnevenRows does not resize items correctly

### ISSUE THREAD

**Issue by fpiribauer** [xamarin/Xamarin.Forms#7100] opened 2019-08-08 09:35 UTC
### Description
Since XF 4.0 the ListView with `CachingStrategy=RecycleElement` and `HasUnevenRows=True` doesn't seem to always invalidate the sizes of Elements even if it would be needed. 

Maybe related issue: #1568
PR with related issues: #6390
### Steps to Reproduce

1. Define a ListView like, so:

```
<ListView  x:Name="lView" CachingStrategy="RecycleElement" HasUnevenRows="True">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto" />
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>
                    <Label Text="{Binding .}" FontSize="Large" BackgroundColor="LightGoldenrodYellow" />
                </Grid>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

2. Scroll through the ListView

### Expected Behavior

The Label has always exactly the width it needs.

### Actual Behavior

The Label sometimes has the width of other Labels from the ListView, resulting in some text being cut off or the BackgroundColor taking up more space than it should. 

### Basic Information

- Version with issue: 4.0 (tested with 4.1.0.673156)
- Last known good version: 3.6.0
- IDE: VS2019
- Platform Target Frameworks:
  - Android: 7.1 

### Screenshots

![ScrolLIssue](https://user-images.githubusercontent.com/31340681/62691800-b35b8880-b9cf-11e9-86ac-2d092b280936.gif)

### Reproduction Link

[ListViewRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3482260/ListViewRepro.zip)

**Comment by jfversluis** [comment] 2019-08-08 13:25
Hi @fpiribauer thanks for reporting!

Unfortunately, I am not able to reproduce this at this time. Both with a physical device (Android 9) and emulator (Android 7) all the labels show up fine. Is there any specific device or emulator that you are testing with?

Also, did you test this on iOS?

Thanks!

**Comment by fpiribauer** [comment] 2019-08-08 14:56
Hey @jfversluis!

I tested this in Android 7.1 with both an emulator and a physical device (Denso BHT-1700). Just now I also tested with an Android 9 emulator, getting the same results. I created the Andrdoid 9 emulator using the defaults provided by VisualStudio19, should that matter. 

I didn't test on iOS and I'm not able to either since I got no iOS emulator on hand, sadly. 

PS: I noticed that the Repro Project did not generate enough items so one could scroll on higher resolution devices, it is necessary to scroll "larger" distances for reproduction. I updated the project in the initial post to generate more items.

**Comment by DavidCFreire** [comment] 2019-10-09 21:17
Any news on that? having same issues here with XF4.0 or XF4.1

**Comment by jfversluis** [comment] 2019-10-10 06:32
@DavidCFreire I'm afraid not, sorry! As an experiment, would you be able to try a newer version? 4.2 or maybe even 4.3-pre? To see if a fix might be in there.

**Comment by DavidCFreire** [comment] 2019-10-12 01:34
I just updated to XF4.3.0.778476-pre1 and apparently this solved the problem... no problems until now

**Comment by jfversluis** [comment] 2019-10-14 06:37
That is great to hear! 4.3 stable should be here pretty soon. I will close this for now, if you have an issue coming up again, please feel free to reopen or open a new one, referring to this one. Thanks!

**Closed by jfversluis** 2019-10-14 06:37 UTC
Labels: 4.0.0, a/listview, e/5 :clock5:, i/regression, p/Android, t/bug :bug:
