### ISSUE TITLE
16.6.2 - Xamarin Forms - release mode - Various Problems - Unhandled exception (KernelBase.dll)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11114] opened 2020-06-18 16:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1076549/1662-xamarin-forms-release-mode-various-problems-u.html)._

---
[regression] [worked-in:16.6.2]
Upgraded to 16.6.2, xamarin forms uwp apps,   
running in debug mode works fine   Without code changes.. now running in release mode has various issues different issues on different apps... 

Some apps show blank screens on home pages, some apps have the below error msgs..

Another App i get this error now (replaced my app name with xx's)
**Unhandled exception at 0x770F4402 (KernelBase.dll) in [XXXXX]: 0xE0434352 (parameters: 0x80070002, 0x00000000, 0x00000000, 0x00000000, 0x74220000). occurred**

workmate on older version of Visual Studio can still run the release mode from same git branch, so we are thinking it's this 16.6.2 build.

---
#### Visual Studio Feedback System on 6/15/2020, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-06-18 17:20
Duplicate of #11008

**Comment by VladislavAntonyuk** [comment] 2020-06-18 22:11
@samhouts this is runtime issue, while 11008 is a build issue

**Comment by samhouts** [comment] 2020-06-18 23:02
sorry, I meant to put "Related to". Otherwise, I would have closed it.

**Comment by samhouts** [comment] 2020-06-26 20:34
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by comfr3ak** [comment] 2020-07-08 21:31
Can confirm this is still happening in version 16.6.3. Same error when running or deploying in release mode in x86 or x64.

It is noteworthy that if I build a release package for the Microsoft store, it runs fine in x86 or x64 on systems that install it from the store but gives this error in VS when running on development machine:

**Error message:** (replace X's with app name)

Unhandled exception at 0x00007FF98417A799 (KernelBase.dll) in XXXXXXX.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF9619B0000).

**Comment by PureWeen** [comment] 2020-07-10 16:54
@comfr3ak @VladislavAntonyuk can you attach a repro ? With UWP there's always a lot that goes into these errors. UWP SDK versions and 3rd party libraries can effect how this all works. A lot of the times these exceptions come from compiling with the native tool chain and all the linking that happens there

If you uncheck native tool chain while in release mode dose the exception still happen?

**Comment by comfr3ak** [comment] 2020-07-10 17:18
My project is very large, difficult to attach a repro. 

I unchecked the "native toolchain link" option and found these results:

**x86 Release** builds, deploys, and runs with 

**x64 Release** builds and deploys, but does not run. It crashes immediately after the app window appears. Error message in debug window:

The program '[21596] XXXXXXX.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.
Activation of the Windows Store app 'XXXXXX' failed with error 'The app didn't start'.

**Comment by PureWeen** [comment] 2020-07-10 17:22
if you enable first chance exceptions do you get more info?

https://devblogs.microsoft.com/devops/understanding-exceptions-while-debugging-with-visual-studio/

In your output is there more of an exception?

if you change your app to just init an empty content page do you get the same exception

**Comment by comfr3ak** [comment] 2020-07-10 17:56
If I re-enable compile with .net toolchain and then change the Debugger type from "Managed Only" to "Mixed (Managed and Native)" I am getting a little more error information in x86 and x64:

**x64 error:**

Exception thrown at 0x00007FF98417A799 in XXXXXXX.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000075713FBC00.

**x86 error:**

Exception thrown at 0x76814402 in XXXXXXX.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0947D0F4. occurred

Also more from the x86 output:

vcruntime140_clr0400.i386.pdb contains the debug information required to find the source for the module vcruntime140_clr0400.dll

**Comment by PureWeen** [comment] 2020-07-10 19:15
what are your compile targets set to?

Does the app crash afterr?
>  EEFileLoadException at memory location 0x00000075713FBC00.

Or is it just breaking on that and you can continue through?

**Comment by comfr3ak** [comment] 2020-07-16 17:58
It crashes on that exception and cannot continue any further. 

The platform target is set to x64 or x86.

**Comment by comfr3ak** [comment] 2020-07-16 18:05
If I set to x64 release, with the compule with .NET toolchain box checked and try to run it, I get this output in the debug window. If I keep pressing "Continue" when the exceptions come up, this is as far as it goes after several exceptions you can see in the output:

'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\mscoree.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_clr0400.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase_clr0400.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\Windows.ApplicationModel.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\rmclient.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Unloaded 'C:\Windows\System32\rmclient.dll'
'XXXXXXXXX.UWP.exe' (Win32): Unloaded 'C:\Windows\System32\twinapi.appcore.dll'
'XXXXXXXXX.UWP.exe' (Win32): Unloaded 'C:\Windows\System32\SHCore.dll'
'XXXXXXXXX.UWP.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.ApplicationModel.dll'
Exception thrown at 0x00007FF80E38A799 (KernelBase.dll) in XXXXXXXXX.UWP.exe: 0x04242420 (parameters: 0x0000000031415927, 0x00007FFFE67B0000, 0x0000000D357FEBC0).
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\psapi.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\5c1b7b73113a6f079ae59ad2eb210951\mscorlib.ni.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000000D357FC090.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000000D357FC090.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000000D357FC090.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000000D357FC090.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

Exception thrown at 0x00007FF80E38A799 in XXXXXXXXX.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000000D357FC090.

'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runtime\bafd9d547145de890faa49386051d848\System.Runtime.ni.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runtbff93e24#\7c003185896eb311ba73cc5c27db8d95\System.Runtime.InteropServices.WindowsRuntime.ni.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\MrmCoreR.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\Windows.StateRepositoryCore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\Windows.UI.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMessaging.dll'
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\BCP47mrm.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. 
'XXXXXXXXX.UWP.exe' (Win32): Loaded 'C:\Windows\System32\rmclient.dll'. 
Exception thrown at 0x00007FF80E38A799 (KernelBase.dll) in XXXXXXXXX.UWP.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFFE67B0000).

Unhandled exception at 0x00007FF80E38A799 (KernelBase.dll) in XXXXXXXXX.UWP.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFFE67B0000).

The program '[4408] XXXXXXXXX.UWP.exe' has exited with code -2146233082 (0x80131506).
Activation of the Windows Store app 'XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX_nbxra8s3mgtzg!App' failed with error 'The app didn't start'.

**Comment by PureWeen** [comment] 2020-08-04 21:47
@comfr3ak did you try enabling first chance exceptions?

https://github.com/xamarin/Xamarin.Forms/issues/11114#issuecomment-656790759

if you right click => properties your UWP project and set the target platform to 18362 does that help?

**Comment by samhouts** [comment] 2020-09-09 20:37
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2020-09-09 20:37 UTC
Labels: feedback-ticket, i/high, p/UWP, s/needs-info ❓, s/unverified, t/bug :bug:

**Comment by Rothanan** [comment] 2020-11-12 12:44
I've bumped into this, after I updated Visual Studio to 16.8.0.

**Comment by ichijikuibo** [comment] 2020-12-25 19:19
If anyone is still having the same problem I just spent all day trying to fix it and eventually found that a file {project Name}.csproj.user was the problem. I deleted it cleaned and rebuilt and it works fine now.

**Comment by ichijikuibo** [comment] 2020-12-27 18:55
Did i bit more looking into it today the line that caused the problem in my case was <UapAppxPackageBuildMode>StoreOnly</UapAppxPackageBuildMode> 
Not sure what that line does or why it interfering with the compile but removing it fixed it for me.

**Comment by dmitrymal** [comment] 2021-02-08 07:38
Just in case if someone runs into this problem, we had the exact same issue for our UWP project which does not even use Xamarin Forms. Changing the UapAppxPackageBuildMode value in csproj.user file from `StoreOnly` to `StoreAndSideload`  fixed the problem: `<UapAppxPackageBuildMode>StoreAndSideload</UapAppxPackageBuildMode>`

**Comment by comfr3ak** [comment] 2021-02-08 14:33
Thanks all, where is this line supposed to go in the project file? I checked and it's not present in my UWP .csproj file with either value:

<UapAppxPackageBuildMode>StoreAndSideload</UapAppxPackageBuildMode>

**Comment by ichijikuibo** [comment] 2021-02-08 14:37
its in the  [projectname].UWP.csproj.user file in xamarin forms projects

 <PropertyGroup>
    <UapAppxPackageBuildMode>StoreAndSideload</UapAppxPackageBuildMode>
  </PropertyGroup>
