### ISSUE TITLE
[Bug] [4.2.0.709249] iOS only - Spinner on top of list

### ISSUE THREAD

**Issue by josegallardo** [xamarin/Xamarin.Forms#7313] opened 2019-08-29 17:45 UTC
### Description

Using latest VS Internal Preview:  16.3.0 Preview 3.0 [29227.170.d16.3] *and creating* a new Master Detail solution from scratch, the items view shows a spinner always on the top of the list as if it's constantly refreshing when it's not.
It disappears if you add a new item on the app.
This issue is reproducible  *only in iOS* in either Simulator or physical device.
The solution is pointing to Xamarin.Forms 4.2.0.709249

Taking that same solution created with internal Preview, and now using VS 2019 16.2.3 (current stable) trying to build it, it will show the exact same behavior.

### Steps to Reproduce

1. Create a new Master-Detail app pointing to X.Forms 4.2.0.709249 (i.e. using VS 2019 Internal Preview)
2. Build and start the iOS Application

Alternatively, you can use the following solution as a repro solution:
[App101.zip](https://github.com/xamarin/Xamarin.Forms/files/3556744/App101.zip)

### Expected Behavior

The items list should just show the items.

### Actual Behavior

The items list shows the spinner always on top as in:
![image](https://user-images.githubusercontent.com/1863118/63963395-55204380-ca6b-11e9-81ad-2f80e5331dd1.png)

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version:
- IDE: VS 2019 Internal Preview Windows
- Platform Target Frameworks:
  - iOS

### Screenshots

![image](https://user-images.githubusercontent.com/1863118/63963395-55204380-ca6b-11e9-81ad-2f80e5331dd1.png)

### Reproduction Link

[App101.zip](https://github.com/xamarin/Xamarin.Forms/files/3556744/App101.zip)

**Comment by matteopiccioni** [comment] 2019-08-30 07:02
I have the same problem,
with Visual Studio 8.2.5
I think the problem is on the latest x.f. and is on IsRefreshing property of the listview, 
when the binded property (for example 'IsBusy') is set to false in viewmodel, the spinner still is visible

**Comment by lassana** [comment] 2019-09-02 05:10
Same problem:

1. Set `IsRefreshing` to `true` when `OnSizeAllocated` is called for the first time.
2. Set `IsRefreshing` to `false` after few milliseconds (e.g. if data is loaded from the local cache)
3. Notice that the spinner is still showing.

X.F 4.2 is buggy, 4.1 is okay.

**Comment by PureWeen** [comment] 2019-09-13 19:18
It looks like this caused the regression

https://github.com/xamarin/Xamarin.Forms/pull/6473/files#diff-198607f4ce97efcc515a271473524b08R1482

The method is resolving after the refresh has already started and then stopped from the VM so it's getting started up again when it shouldn't be

**Closed** 2019-09-17 22:59 UTC
Labels: a/listview, e/2 :clock2:, i/regression, p/iOS 🍎, t/bug :bug:
