### ISSUE TITLE
Object disposed exception when binding changes on a

### ISSUE THREAD

**Issue by mjfreelancing** [xamarin/Xamarin.Forms#9488] opened 2020-02-08 23:18 UTC
### Description
While testing my app for changing themes I am getting the following exception after switching between two pages (after 4-6 switches)

```
Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.
```

The app modifies the app's ResourceDictionary on each page switch by merging in a XAML file containing resources. Each page contains a binding to a static class that contains colors used by those styles. I suspect the issue occurs because the value of the binding is changing but a renderer has already been disposed of.

### Steps to Reproduce

1. Refer to the attached project
2. At the bottom of the page are two tabs to switch pages. Switch between the two pages approx 4-6 times.
3. The exception will be raised when trying to update a dependency property

### Expected Behavior
I should be able to switch back to a tabbed page after navigating away from it, even if a binding to that page is being modified when navigating back.

### Actual Behavior
After 4-6 page switches an ObjectDisposedException is raised

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: Unknown
- IDE: VS 2019, Windows
- Platform Target Frameworks: I have only tested Android

### Reproduction Link
Stack trace and a cut down version of my project is attached
[RendererDisposed.zip](https://github.com/xamarin/Xamarin.Forms/files/4175555/RendererDisposed.zip)

### Workaround
None
[stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/4175551/stacktrace.txt)

**Comment by PureWeen** [comment] 2020-02-08 23:34
I feel like the bug here is that the old renderer isn't getting unassigned from the label when you navigate away

Currently with shell when you click between tabs it disposes of the entire object graph. 

And it looks like when you navigate back it's trying to update fields on an already disposed of renderer. 

The only other thought I'd have is that the LabelRenderer Control is getting disposed of for some other reason 

The easiest fix would be to check the handle on the control inside UpdateText but I think that would just treat the symptom

**Comment by kvpt** [comment] 2020-02-09 19:19
@mjfreelancing I tested your project and have the same crash.
But when trying to fix it in my sandbox project it doesn't crash.
I noticed that my project is currently based on the 4.5 branch, so I updated your repro project with the 4.5 preview, and it doesn't crash anymore for me.
So a PR included in the 4.5 branch seem to have fixed it.

**Comment by mjfreelancing** [comment] 2020-02-10 09:05
@kvpt I can confirm I cannot reproduce using v4.5.0.266-pre3

**Comment by mjfreelancing** [comment] 2020-02-10 10:49
@kvpt I just noticed my icons have disappeared with v4.5.0.266-pre3. Is that a known regression or do I need to raise a new issue for that?

**Comment by kvpt** [comment] 2020-02-10 12:39
@mjfreelancing You can check the issues list but I think it's a new one.
For the comment I think it's because your commit message contain a link to this issue, the others commits should't be added.

**Comment by mjfreelancing** [comment] 2020-02-10 13:05
@kvpt Thanks, I have created a new issue for the icon observation.

**Comment by samhouts** [comment] 2020-02-10 19:50
@mjfreelancing Are you saying that this issue is resolved in 4.5.0-pre3? Are we good to close this one? Thanks!

**Comment by mjfreelancing** [comment] 2020-02-10 21:10
Yes, I have not been able to reproduce this issue since updating to 4.5.0-pre3.

**Comment by mjfreelancing** [comment] 2020-03-14 09:28
I have just upgraded my application to v4.5.0.356 and the issue has presented itself again. I have modified the originally provided sample

* updated to the latest Xamarin.Forms / Essentials  (4.5.0.356 and 1.5.1 respectively)
* updated the CarouselView to point to the IndicatorView (as per latest release requirements).

Attached is a new version of the sample as well as a stack trace.

Reproducing the issue is a lot harder. I had to switch between light/dark themes multiple times. I wa also sliding the carousel view between switches.

[sample.zip](https://github.com/xamarin/Xamarin.Forms/files/4332473/sample.zip)
[StackTrace.txt](https://github.com/xamarin/Xamarin.Forms/files/4332474/StackTrace.txt)

**Comment by eramrit78** [comment] 2020-03-19 05:37
I have same issue in XF 4.5 latest

**Comment by PureWeen** [comment] 2020-03-26 01:54
@eramrit78 your error is probably different. Can you create a new issue with a stack trace?

**Comment by PureWeen** [comment] 2020-03-26 01:57
I moved this over to shell to do blockers

@hartez made a series of changes to fast renderers to not call PropertyChanged if the class IsDisposed. The exception @mjfreelancing has in the txt file above is

```

  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
  at Android.Views.View.SetBackgroundColor (Android.Graphics.Color color) [0x00028] in <d706cf8faf5542949900cf6d57864528>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateBackgroundColor () [0x00000] in d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:455 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00017] in d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:356 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\Element.cs:353 
```

Which refers to a layout renderer so we could add that same code to VisualElementRenderer but we should rule out a memory leak first. 

It looks like the navigation renderer might need to be removed sooner
```
at Xamarin.Forms.Platform.Android.ShellItemRenderer.ChangeSection (Xamarin.Forms.ShellSection shellSection) [0x00000] in d:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellItemRenderer.cs:147 
  at Xamarin.Forms.Platform.Android.ShellItemRenderer.OnItemSelected (Android.Views.IMenuItem item) [0x0008a] in d:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellItemRenderer.cs:298 
  at Xamarin.Forms.Platform.Android.ShellItemRenderer.Android.Support.Design.Widget.BottomNavigationView.IOnNavigationItemSelectedListener.OnNavigationItemSelected (Android.Views.IMenuItem item) [0x00000] in d:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellItemRenderer.cs:34 
  at Android.Support.Design.Widget.BottomNavigationView+IOnNavigationItemSelectedListenerInvoker.n_OnNavigationItemSelected_Landroid_view_MenuItem_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_item) [0x0000f] in <2899ffe2b3534c2b9c09eb66776436ae>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.47(intptr,intptr,intptr)
```

**Comment by rmarinho** [comment] 2021-02-11 23:16
Hi updated to 5.0.0.1931 and I can't reproduce the issue anymore.

**Closed by rmarinho** 2021-02-11 23:16 UTC
Labels: a/fastrenderers, a/label, a/shell :shell:, a/tabbedpage, i/high, p/Android, t/bug :bug:
