### ISSUE TITLE
[Bug] We can't bind a int value to `RadioButtonGroup.SelectedValue` ,even if using  a Converter to convert int to string

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#15239] opened 2022-03-21 02:14 UTC
### Description

We can't bind a int value to RadioButtonGroup.SelectedValue ,even if using a Converter to convert int to string

### Steps to Reproduce

**1. in xaml**
    
        <ContentPage.Resources>
        <ResourceDictionary>
            <radiobuttondemos:IntToStringConverter x:Key="MyIntStringConverter"  />
        </ResourceDictionary>
       </ContentPage.Resources>

       <ContentPage.BindingContext>
         <radiobuttondemos:MyViewModel ></radiobuttondemos:MyViewModel>
       </ContentPage.BindingContext>
     <StackLayout>

        <StackLayout Orientation="Horizontal" RadioButtonGroup.GroupName="{Binding GroupName}"
                 RadioButtonGroup.SelectedValue="{Binding Parity, Converter={StaticResource MyIntStringConverter}, Mode=TwoWay}">
            <RadioButton Value="1" Content="Income" />
            <RadioButton Value="-1" Content="Expense" />
            <RadioButton Value="0" Content="Neutral" />
        </StackLayout>
    </StackLayout>
**2.  IntToStringConverter.cs**

    public class IntToStringConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {

            var temp = value as int?;
            var result = string.Empty;

            if (temp.HasValue)
            {
                result = temp.Value.ToString();
            }

            return result;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var stringValue = value as string;
            int intValue;
            int? result = null;

            if (int.TryParse(stringValue, out intValue))
            {
                result = new Nullable<int>(intValue);
            }
            return result;
        }
    }

**3. MyViewModel.cs**

```
public class MyViewModel : INotifyPropertyChanged
{
    string groupName;

    object parity;
    public object Parity
    {
        get => parity;
        set
        {
            parity = value;
            OnPropertyChanged(nameof(Parity));
        }
    }


    public MyViewModel () {

        GroupName = "Parities";

        Parity = 1;
    }

    public string GroupName
    {
        get => groupName;
        set
        {
            groupName = value;
            OnPropertyChanged(nameof(GroupName));
        }
    }


    public event PropertyChangedEventHandler PropertyChanged;

    void OnPropertyChanged(string propertyName)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```
### Expected Behavior

 we could bind a int to `RadioButtonGroup.SelectedValue` using `Converter`. 

### Actual Behavior

 We could not bind a int to `RadioButtonGroup.SelectedValue` even if  using `Converter`. 
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment] 2022-03-21 09:42
Duplicate of #13752

**Closed by jfversluis** 2022-03-21 09:42 UTC
Labels: t/bug :bug:, s/unverified
