### ISSUE TITLE
Picker.SelectedItem gets called twice in xamarin forms

### ISSUE THREAD

**Issue by amalu2020** [xamarin/Xamarin.Forms#7646] opened 2019-09-24 10:12 UTC
Description
Picker.SelectedItem programmatically leads to call twice 

Steps to Reproduce

1. XAML:

<Picker ... SelectedIndex="{Binding SelectedIndexY}" SelectedIndexChanged="Handle_SelectedChanged" SelectedItem="{Binding SelectedItemY}"" />
Code:

public string SelectedItemY { get; set; }
        public int SelectedIndexY { get; set; } = -1;

2. Navigate to page
3. Choose any picker option, eg, index 0,
then leave the page and navigated to the same page, choose any different picker option, eg, index 1.

 Expected Behavior
SelectedIndexY should be 1
Actual Behavior
SelectedIndexY is coming 1 for the first Handle_SelectedChanged method, and it changes to 0 on the automatic Handle_SelectedChanged second call.

 Basic Information

- Version with issue:
IDE: Visual Studio 2017 version 8.2.4
Platform Target Frameworks: Android - xamarin forms

**Comment by StephaneDelcroix** [comment] 2019-09-24 18:57
Binding to both the SelectedIndex and the SelectedItem is probably what causes it, in addition to a missing equality comparer in your VM.

Without a repro project, and a proper version number, and after doing a quick test (works for me), I'm going to close this. feel free to reopen with more information

**Closed by StephaneDelcroix** 2019-09-24 18:57 UTC
Labels: s/unverified, t/bug :bug:

**Comment by amalu2020** [comment] 2019-09-25 05:43
I got solution for the issue that i was facing. 

Solution 1: Update Xamarin Forms, the issue has been resolved in new version.
Solution 2 : The picker item i was using as List<string>; , but when i changed it to ObservableCollection class it works fine.

**Comment by StephaneDelcroix** [comment] 2019-09-25 07:46
dupe of #2075, #2073

**Comment by Bosch-Eli-Black** [comment] 2019-12-27 09:51
Thanks to @amalu2020 for his hint on how to solve this.

I had my Picker's `ItemSource` binding mode set to `TwoWay` (i.e. `ItemsSource="{Binding Path=MyOptions, Mode=OneTime}"`), and I was binding to a property that created a new list every time it was called.

Changing the binding mode to `OneTime` was the best fix in my case.

Making it so that the property that `ItemsSource` was bound to didn't generate a new `List` every time it was accessed also seemed like it fixed the problem.

**Comment by jaysonragasa** [comment] 2020-04-23 16:42
This issue exists on 4.5.0495

I added a Debug.WriteLine when the SelectedItem property gets called  
`Debug.WriteLine($"DEBUG> call index{this._callIndex} | SelectedItem called. Is value null? " + (value == null ? "YES" : "NO") );`  
  
so when I run the app the first time, I get this  
```
[0:] DEBUG> call index1 | SelectedItem called. Is value null? NO
[0:] DEBUG> call index2 | SelectedItem called. Is value null? YES
```
  
Picker ItemSource is bound to an `ObservableCollection` too 
  
When I set a default item in the Picker, it gets call 3x in on startup and it shows like this  
```
[0:] DEBUG> call index1 | SelectedItem called. Is value null? NO
[0:] DEBUG> call index2 | SelectedItem called. Is value null? NO
[0:] DEBUG> call index3 | SelectedItem called. Is value null? YES
```
  
repo here if you want to try it out  
https://github.com/jaysonragasa/XamarinBugs/tree/Picker
