### ISSUE TITLE
shell TitleView Binding doesn't work

### ISSUE THREAD

**Issue by SoniaCH** [xamarin/Xamarin.Forms#5578] opened 2019-03-15 11:54 UTC
### Description
the using of the Shell.TitleView work only when I set the Title staticly , but with binding itis not working.
### Steps to Reproduce

1. Create a project with shell
2. Now set Shell.TitleView property of ContentPage.
3. chenge the title view with the custom that I want and bind the value of the Title

### Expected Behavior
the Title takes the value of the binding
### Actual Behavior
t only work when I set the title in the xaml staticly
### Basic Information

- Version with issue:Xamarin.Forms (3.6.0.220655)
- Last known good version:using navigation does the job
- IDE:Visual studio for windows15.9.9
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android:  8.1,7.1,7.0 etc

**Comment by rmarinho** [comment] 2019-03-15 12:28
Hi @SoniaCH can you please add a reproduction example? 

Thanks

**Comment by SoniaCH** [comment] 2019-03-15 14:22
I used to work like this:
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Style="clr-namespace:Mobile.StyleViews.Styles"
             xmlns:UserControl="clr-namespace:Mobile.UserControl"
             x:Class="Mobile.Views.CartWithTickets"
             BackgroundColor="#FFF6F7F8"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
             ios:Page.UseSafeArea="true">
    <Shell.TitleView>
        <StackLayout Style="{x:Static Style:GeneralStyles.navBarSpaceStyle}">
            <StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
                <Label  x:Name="TitleLabel" Style="{x:Static Style:GeneralStyles.navBarTitleStyle}" 
                         Text="{Binding Title}"/>
            </StackLayout>
        </StackLayout>
    </Shell.TitleView>
    <ContentPage.Content>
       
    </ContentPage.Content>
</ContentPage>


this is when the shell doesn't take the value of the title.

but now  I gave my contentpage a name an then added a reference to it for the binding 
now it does work: here is the code:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Style="clr-namespace:Mobile.StyleViews.Styles"
             xmlns:UserControl="clr-namespace:Mobile.UserControl"
             x:Class="Mobile.Views.CartWithTickets"
             BackgroundColor="#FFF6F7F8"
			 x:Name="parent"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
             ios:Page.UseSafeArea="true">
    <Shell.TitleView>
        <StackLayout Style="{x:Static Style:GeneralStyles.navBarSpaceStyle}">
            <StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
                <Label  x:Name="TitleLabel" Style="{x:Static Style:GeneralStyles.navBarTitleStyle}" 
                        Text="{Binding Source={x:Reference parent}, Path=BindingContext.Title}"/>
            </StackLayout>
        </StackLayout>
    </Shell.TitleView>
    <ContentPage.Content>
       
    </ContentPage.Content>
</ContentPage>

**Comment by samhouts** [comment] 2019-03-16 00:59
@SoniaCH Please attach a sample project that demonstrates this issue. At the very least, please post your XAML in such a way that we can copy and paste it. Thanks!

**Comment by HobDev** [comment] 2019-03-21 09:47
I think the problem is Andorid only. Please see this:
https://github.com/xamarin/Xamarin.Forms/issues/5650

**Comment by samhouts** [comment] 2019-03-22 21:55
Duplicate of #5650

**Closed by samhouts** 2019-03-22 21:55 UTC
Labels: a/shell :shell:, s/needs-info ❓, s/needs-repro ❔, t/bug :bug:
