### ISSUE TITLE
Please provide radio button feature in Xamarin.Forms

### ISSUE THREAD

**Issue by GovardhanNag** [xamarin/Xamarin.Forms#8066] opened 2019-10-17 13:50 UTC
## Summary
Please provide radio button feature in Xamarin.Forms just like that of Checkbox.

Many of our projects require this feature, even though we have many custom renderers and plugins for that, its better to have our own feature in Xamarin.Forms. And in many cases the plugins fail to provide radio button feature to UWP, its very appreciable if radio button feature is integrated in Xamarin.Forms.

**Comment by jfversluis** [comment] 2019-10-17 13:52
Thanks for the suggestion! However there is already an issue for this. Please express your love for it by giving it a comment and/or emoji to prioritize this the right way. 

I will be closing this one so progress can be tracked accurately in the earlier issue.

**Comment by jfversluis** [comment] 2019-10-17 13:53
Duplicate of #2404

**Closed by jfversluis** 2019-10-17 13:53 UTC
Labels: proposal-open, t/enhancement ➕
