### ISSUE TITLE
FlexLayout.Layout - System.NullReferenceException

### ISSUE THREAD

**Issue by craighanson** [xamarin/Xamarin.Forms#3183] opened 2018-06-29 12:01 UTC
I am getting a NullReferenceException in FlexLayout.Layout. Below is my stack trace..

FlexLayout.Layout (System.Double x, System.Double y, System.Double width, System.Double height)
FlexLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
Layout.UpdateChildrenLayout ()
Layout.OnSizeAllocated (System.Double width, System.Double height)
VisualElement.SizeAllocated (System.Double width, System.Double height)
Layout+<>c.<OnChildMeasureInvalidated>b__45_0 ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

I assumes this is due to _root being null.

- Version with issue: Latest version on github

**Comment by hartez** [comment] 2018-07-04 21:59
@craighanson Could you provide a minimal reproduction project? Or at least some sample code/XAML to tell us how you're using FlexLayout?

**Comment by aeonblaire** [comment] 2018-08-08 16:37
I also encounter this, when the children views becomes invisible/visible. In my case, I am using data triggers to set IsVisible in the children views.

**Comment by samhouts** [comment] 2018-08-08 21:40
@aeonblaire Do you have a small project you can share with us that shows the problem? Thank you!

**Comment by aeonblaire** [comment] 2018-08-09 07:55
@samhouts Hi! I tried to make one, but I found out that IsVisible is not the problem but the removal of the FlexLayout from the visual tree. I guess this will be fixed with #3235 . Can you suggest a temporary workaround? Thanks!

**Comment by samhouts** [comment] 2018-08-09 19:30
Hmm, I am not aware of a workaround at this time, but if you would like to test the change, you can try updating to the latest nightly build. In the meantime, we'll close this as a duplicate of #3234. If you find that your issue is not resolved by #3235, please reopen this issue and let us know. Thanks!

**Closed by samhouts** 2018-08-09 19:30 UTC
Labels: a/flex, s/needs-info
