### ISSUE TITLE
[Bug] Problems with IconOverride

### ISSUE THREAD

**Issue by MarcosAC** [xamarin/Xamarin.Forms#8389] opened 2019-11-05 20:05 UTC
Hello. I'm having trouble using IconOverride property Shell.BackButtonBehavior. The image does not load. I put the image in the drawable folder and it still doesn't work. I am using Xamarin Forms 4.3.0. Would it be a bug or am I doing something wrong?

**Comment by hartez** [comment] 2019-11-08 19:17
@MarcosAC How are you setting the BackButtonBehavior? Note that you need to set it on the ContentPage where you want to override the button: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#back-button-behavior

**Comment by MarcosAC** [comment] 2019-11-11 12:15
My code looks like this:

`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Views="clr-namespace:Laep.Views"
             x:Class="Laep.Views.CadastroProjetoEletrico"
             Shell.TabBarIsVisible="{Binding TabBarIsVisible}">    

    <Shell.BackButtonBehavior>
        <BackButtonBehavior Command="{Binding BackCommand}"
                            IconOverride="btnVoltar.png" />
    </Shell.BackButtonBehavior>

    <Views:Cadastro />
</ContentPage>`

**Comment by MarcosAC** [comment] 2019-11-11 12:18
My code looks like this:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Views="clr-namespace:Laep.Views"
             x:Class="Laep.Views.CadastroProjetoEletrico"
             Shell.TabBarIsVisible="{Binding TabBarIsVisible}">

        <Shell.BackButtonBehavior>
        <BackButtonBehavior Command="{Binding BackCommand}"
                            IconOverride="btnVoltar.png" />
    </Shell.BackButtonBehavior>

    <Views:Cadastro />
</ContentPage>

**Comment by hartez** [comment] 2019-11-11 19:10
@MarcosAC Here's my repro project - I'm setting the BackButtonBehavior with the IconOverride on the ItemDetailPage. It seems to be working fine - is there a detail I'm missing?

[_8389 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3832854/_8389.Repro.zip)

**Comment by MarcosAC** [comment] 2019-11-12 18:01
Here is the code link for you to see how you were doing. But no problem, I decided to do otherwise. Thanks. :D

[https://github.com/MarcosAC/Laep/blob/teste/Laep/Laep/Views/CadastroProjetoEletrico.xaml](url)

**Comment by hartez** [comment] 2019-11-21 17:31
@MarcosAC Since we haven't been able to reproduce this, your link doesn't seem to work, and you've gone a different direction, I'm going to close this. If you have any updates for us, I'll reopen it.

**Closed by hartez** 2019-11-21 17:31 UTC
Labels: a/shell :shell:, s/needs-info ❓, s/unverified, t/bug :bug:
