### ISSUE TITLE
Every HTML Label bug is still present in 4.3.0.991211

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#8506] opened 2019-11-14 12:19 UTC
The issue #8156 is already closed but it is still not working in the 4.3.0 release from yesterday. Was this not merged into it? For a new feature that is headlining 4.3.0 it is very bad that there are so many, obviously untested, issues with it. 

Also all of this issues are still unresolved regarding the HTML Label feature: #8157, #8158, #8159. Why was this "feature" even pushed to "stable" if it is so broken and works completely different across iOS and Android? And the worst part not even fixed in the 2nd service release for that release featuring it..

**Comment by jfversluis** [comment] 2019-11-14 13:13
Thanks for reporting @Sebastian1989101 

I've tried reproducing it, but it seems to work just fine for me as shown in the screenshot below. Would you be able to add a reproduction project showing the behavior you are seeing?

![image](https://user-images.githubusercontent.com/939291/68859873-8c0c0a00-06e8-11ea-823e-0b7ee2e6b81d.png)

As for the rest, personally, I think is also a bit of a grey area. If you decide to use HTML, you could also include styling in there. If you define styling in the HTML _and_ on the `Label` which will take precedence over which and how do we strip out the HTML styling? 

There are some things still to figure out and we are working on it.

**Comment by jfversluis** [comment] 2019-11-14 13:19
Thanks for reporting @Sebastian1989101

I see the PR was merged into master, so it should be part of the 4.4-pre2 package. Would you be able to confirm it works there?

As for the rest, personally, I think is also a bit of a grey area. If you decide to use HTML, you could also include styling in there. If you define styling in the HTML and on the Label which will take precedence over which and how do we strip out the HTML styling?
There are some things still to figure out and we are working on it.

**Comment by Sebastian1989101** [comment] 2019-11-14 13:22
@jfversluis Just use "ä" instead of "&auml;" in the text and it won't work on iOS but it does on Android. If the encoding is properly set to UTF-8 this should work and it does work in other libraries. Otherwise the label should encode the input string properly with HTML escape chars. 

I would expect the Label styling as long as the HTML does not define own styles. This is exactly how it works on Android but not on iOS. And for a Framework having completly different behavior on two platforms is just bad and I assume nobody would expect that. 

In fact, I would expect the same behavior as https://github.com/matteobortolazzo/HtmlLabelPlugin does. The current implementation of Xamarin.Forms is, sorry for that, just garbage and a waste of space. 

Espacially the part with the different font is a nogo. I don't change the font of the rest of my app so why is it different on the HTML Label? Yes I could add all of this to the HTML too and blow up my code which is working fine on Android just to make this implementation work or I will just switch back to the https://github.com/matteobortolazzo/HtmlLabelPlugin and use a properly working control instead.

**Comment by jfversluis** [comment] 2019-11-14 13:25
Please see my updated comment. About everything else; noted. And like I said; we are working on it.

I would appreciate it though to not refer to anyones code as garbage or anything of the like. I think everyone is doing their best, it would be great to show some respect. Thanks!

**Comment by Sebastian1989101** [comment] 2019-11-14 13:33
@jfversluis Having a feature announced for a specific version, in this case 4.3.0, and than implement it with so many undocumented issues is not a very good way todo things. In fact the definition for "garbage" is something that is not needed and not working which is clearly the case here. If we would deliver such things to our customers we would pretty fast generate 1-Star ratings and make our apps worse then before just because we used a "Framework" from Microsoft. 

btw. just tested 4.4.0-pre2 and the issue is still the same in español and français. So not fixed even if the issue is already closed. Didn't test the german umlauts again.

But it is not the only part that isn't working for decades. The beloved iPad SplitView with MasterDetail is reported as broken since 2016 and no changes yet. That speaks enough for "everyone is doing their best". At least this feature was never announced as a new big thing like it was with the HTML Label for 4.3.0...

**Comment by jfversluis** [comment] 2019-11-14 13:55
Looks like the fix might have just missed the 4.4-pre2 package. It does work on our master though, so it should be working for 4.4 as of next release for sure, sorry about that.

**Comment by hartez** [comment] 2019-11-17 21:44
Closing, as this report does not provide any additional information about the issues.

**Closed by hartez** 2019-11-17 21:44 UTC
Labels: s/unverified, t/bug :bug:
