### ISSUE TITLE
[Shell] Setting FlyoutBackgroundColor doesn't colour the entire flyout

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5872] opened 2019-04-10 11:36 UTC
### Description

I just decided to quickly check that `FlyoutBackgroundColor` would set the flyout background colour, only to discover that it doesn't set it for every flyout item in my scenario.

This occurs on both iOS and Android (see screenshots below).

### Steps to Reproduce

1. Run the attached sample.
2. Present the flyout.

### Expected Behavior

The flyout background colour is red. Everywhere.

### Actual Behavior

All but one flyout item has a red background.

### Basic Information

- Version with issue: 4.0-pre8
- Last known good version: N/A
- IDE: VSMac 8
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: API 27

### Screenshots

iOS:

![Simulator Screen Shot - iPhone X - 2019-04-10 at 12 25 24](https://user-images.githubusercontent.com/8092460/55875311-b9aa3700-5b8c-11e9-96fd-b18cf7330a45.png)

Android:

![Screenshot_1554895490](https://user-images.githubusercontent.com/8092460/55875322-bf078180-5b8c-11e9-9264-cc81554d62c0.png)

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3063527/Xaminals.zip)

**Comment by samhouts** [comment] 2019-05-07 23:38
Duplicate of #5662

**Closed by samhouts** 2019-05-07 23:38 UTC
Labels: a/shell :shell:, e/2 :clock2:, p/Android, p/iOS 🍎, t/bug :bug:
