### ISSUE TITLE
Unwanted Behavior of Master-Detail Menu/Hamburger button

### ISSUE THREAD

**Issue by rails-hub** [xamarin/Xamarin.Forms#5842] opened 2019-04-08 07:57 UTC
### Description
XF: 3.6.0.293080
Platform: iOS
Device: iPad
Using the basic template for Master-Detail App with `SplitOnLandscape` MasterBehavior the menu/hamburger button does not work as expected. The button shows in the `Landscape` mode while it shouldn't and it gets hidden in the `Portrait` mode while we return back to the `Detail` page.
### Steps to Reproduce

1. Create a `Master-Detail Forms` app from the given templates. 
2. Add `SplitOnLandscape` as `MasterBehavior`.
3. Launch the app in Portrait mode.
4. At this point you should be able to see the `Hamburger/Menu` button clicking which should show the `Menu/Master` page.
5. Change the orientation to `Landscape` which will hide the `Hamburger/Menu` button which is expected behavior.
6. Now tap on any of the `items` on the `Detail` page which should take you to the item detail page. (at this point the orientation is still in Landscape)
7. Now, change the orientation to `Portrait` mode and press back button.
8. Now once you come back to the detail page you won't be able to see the `Hamburger/Menu` button in the navigation and the only way to show the drawer is to swift left-to-right.
### Expected Behavior
The app should show the `Hamburger/Menu` button in the Navigation page in Portrait mode and should hide in Landscape.

### Actual Behavior
The app looses the `Hamburger/Menu` button after coming back to the detail page while changing the device orientation while we drill down the Detail page item.
### Basic Information

- Version with issue: 3.6.0.293080
- Last known good version:
- IDE: Visual Studio Community (7.7.2 build 21)
- iOS:  12.2
- Device: iPad

### Screenshots
I'm running the default Master Detail app for Xamarin.Forms which shows the Menu/Master button on the top left.

https://us.v-cdn.net/5019960/uploads/editor/mp/uekm800oye76.png
<img width="485" alt="Screen Shot 2019-04-05 at 12 34 58 PM" src="https://user-images.githubusercontent.com/6818028/55707659-8be2b800-59fd-11e9-9556-bcf95c70136a.png">

And this is how it looks when I rotate it to landscape.

https://us.v-cdn.net/5019960/uploads/editor/ei/uib4c1qg7j4d.png
<img width="688" alt="Screen Shot 2019-04-05 at 12 35 23 PM" src="https://user-images.githubusercontent.com/6818028/55707669-91d89900-59fd-11e9-914e-fc2670dd2e24.png">

When I drill down into detail page while in Landscape...

https://us.v-cdn.net/5019960/uploads/editor/jv/krqrco48asso.png
<img width="684" alt="Screen Shot 2019-04-05 at 12 36 24 PM" src="https://user-images.githubusercontent.com/6818028/55707674-969d4d00-59fd-11e9-993d-a12de54ae19c.png">

Then I rotate the device to portrait mode on this page.

https://us.v-cdn.net/5019960/uploads/editor/2k/u38obug5kd2r.png
<img width="493" alt="Screen Shot 2019-04-05 at 12 38 00 PM" src="https://user-images.githubusercontent.com/6818028/55707688-9ef58800-59fd-11e9-991b-09d2e3e65bc0.png">

Everything is working as expected until I press back button from this page.

https://us.v-cdn.net/5019960/uploads/editor/bi/ayb16prrwzm3.png
<img width="495" alt="Screen Shot 2019-04-05 at 12 38 35 PM" src="https://user-images.githubusercontent.com/6818028/55707702-a87ef000-59fd-11e9-9d2f-36e0d5e11a6c.png">

you might see it is missing the Master/menu button(or the hamburger button).

### Reproduction Link

https://github.com/rails-hub/MasterDetailTest

## SCREEN RECORDING###
https://cl.ly/dc56d20c32e2

**Comment by samhouts** [comment] 2019-04-08 20:50
Duplicate of #3085

**Closed by samhouts** 2019-04-08 20:50 UTC
Labels: t/bug :bug:
