### ISSUE TITLE
[Bug] Shell cannot display secondary toolbar items properly 

### ISSUE THREAD

**Issue by luismts** [xamarin/Xamarin.Forms#7982] opened 2019-10-13 19:48 UTC
### Description
The shell application cannot display secondary toolbar items properly. I have also tried changing the order and cannot seem to work.

### Steps to Reproduce

`<ContentPage.ToolbarItems>`
`        <ToolbarItem IconImageSource="icon.png" />`
`        <ToolbarItem Order="Secondary" Text="Option 1" />`
`        <ToolbarItem Order="Secondary" Text="Option 2" />`
`        <ToolbarItem Order="Secondary" Text="Option 3" />`
`    </ContentPage.ToolbarItems>`

### Expected Behavior
The application displays a secondary menu in the toolbar.

### Actual Behavior
The application displays all the options that it can in the toolbar.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.848062
- IDE: Visual Studio 16.3.0
- Platform Target Frameworks: 
  - Android: 9.0 (Pie) 
 
### Screenshots

![image](https://user-images.githubusercontent.com/20643876/66721111-a775b380-edd0-11e9-85eb-c49e1ae86318.png)

### Reproduction Link

https://github.com/lacomarcaDO/app-community/tree/ShellBug/src/Community.Clients

**Comment by monetelli** [comment] 2019-10-14 01:42
SOLUTION: 
<img alt="react-native-gifted-chat" src="https://i.pinimg.com/originals/16/52/6d/16526d6fb587fbb2a3eaef630393e6d4.png" width="960" height="350" />
 </a>

**Comment by luismts** [comment] 2019-10-14 04:25
> SOLUTION

No, it's not. The secondary button is in a submenu.

Like this one
![image](https://user-images.githubusercontent.com/20643876/66729377-0c54fc00-ee19-11e9-87c1-4235a344714d.png)

**Comment by monetelli** [comment] 2019-10-14 04:56
> > SOLUCIÓN
> 
> No, no es. El botón secundario está en un submenú.
> 
> Como éste
> ![imagen](https://user-images.githubusercontent.com/20643876/66729377-0c54fc00-ee19-11e9-87c1-4235a344714d.png)


You're right, wait for it to be resolved.

**Comment by monetelli** [comment] 2019-10-14 04:56
> > SOLUTION
> 
> No, it's not. The secondary button is in a submenu.
> 
> Like this one
> ![image](https://user-images.githubusercontent.com/20643876/66729377-0c54fc00-ee19-11e9-87c1-4235a344714d.png)

You're right, wait for it to be resolved.

**Comment by jfversluis** [comment] 2019-10-14 06:45
Duplicate of #6127

**Closed by jfversluis** 2019-10-14 06:45 UTC
Labels: a/shell :shell:, p/Android, s/unverified, t/bug :bug:
