### ISSUE TITLE
[Bug] Xamarin Forms 4.8.0.1451 causes Invalid URI exception at app startup on UWP

### ISSUE THREAD

**Issue by SunshineSpring666** [xamarin/Xamarin.Forms#12184] opened 2020-09-20 05:08 UTC
### Description

For latest stable release Xamarin Forms 4.8.0.1451, some bug causes Invalid URI exception at app startup on UWP.
"Invalid URI: The format of the URI could not be determined."
BTW, no custom fonts are included.

### Steps to Reproduce

1. Upgrade to Xamarin.Forms 4.8.0.1451

### Expected Behavior
Work as usual.

### Actual Behavior
Crash at startup immediately with Invalid URI exception.

### Basic Information

- Version with issue: Xamarin Forms 4.8.0.1451
- Last known good version: Xamarin Forms 4.8.0.1364
- IDE: Visual Studio 2019  16.8.0 Preview 3
- Platform Target Frameworks:
  - UWP:   20206
- Nuget Packages: Xamarin Forms 4.8.0.1451
- Affected Devices: Windows PC

### Screenshots
![UriExceptionPic](https://user-images.githubusercontent.com/42401603/93694767-49099700-fb42-11ea-98a2-9d4546e81d1a.jpg)

### Workaround
Downgrade to Xamarin Forms 4.8.0.1364

**Comment by holecekp** [comment] 2020-09-20 13:58
This might be a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/12153

**Comment by rmarinho** [comment] 2020-09-21 10:20
Duplicate of #12153

**Closed by rmarinho** 2020-09-21 10:20 UTC
Labels: s/unverified, t/bug :bug:

**Comment by rajababusharma** [comment] 2021-02-24 12:28
Yes, I have resolve this issue by uninstalling Xamarin.forms 4.8.0.1451 causes invalid URI exception at app start up on UWP and installed the stable version of Xamarin.forms 4.8.0.1364

<img width="898" alt="Untitled" src="https://user-images.githubusercontent.com/39822786/109000580-e8baea80-76c9-11eb-93f0-a7a62be15382.png">

**Comment by SunshineSpring666** [comment] 2021-02-24 15:27
@rajababusharma, thanks for your reply.
