### ISSUE TITLE
Null Refresh Exception When BackButton Pressed On Shell(Anroid)

### ISSUE THREAD

**Issue by Sarthak261995** [xamarin/Xamarin.Forms#8084] opened 2019-10-18 13:31 UTC
App Crashes with the message of System.NullReferenceException: Object reference not set to an instance of an object. When I clicked on Android Back Button with the Shell as a main page app minimize first and then got exception.

Back button works when we have more then one page in navigation stack so in this case current page navigate to last page.

So the app crashes when there is you know only current page in navigation stack and app should minimize when clicked on hardware back button.But it crashes :(

Below is the stack trace of Exception
  at Xamarin.Forms.Platform.Android.ShellSectionRenderer.UnhookEvents () [0x00022] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellSectionRenderer.cs:254 
  at Xamarin.Forms.Platform.Android.ShellSectionRenderer.OnDestroy () [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellSectionRenderer.cs:180 
  at Android.Support.V4.App.Fragment.n_OnDestroy (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <fefee6c2c695459088a9df092723e052>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.69(intptr,intptr)

Xamarin Forms Version : 4.2.0.848062

**Comment by samhouts** [comment] 2019-10-18 18:05
Duplicate of #7327

**Closed by samhouts** 2019-10-18 18:05 UTC
Labels: a/shell :shell:, i/high, p/Android, s/unverified, t/bug :bug:
