### ISSUE TITLE
[Bug] [iOS] CollectionView - blank spaces beetween items on updating list when items has different heights

### ISSUE THREAD

**Issue by mariaszek9003** [xamarin/Xamarin.Forms#11511] opened 2020-07-22 15:17 UTC
There some blank spaces appears between items on CollectionView on iOS if items has different heights. Best way to show these spaces is updating the list, for example inserting new item at the top. This problem occurs only on iOS, works fine on Android.
 
### Steps to Reproduce

1.  Use my reproduction repo at the bottom of this post
2. Run application on iOS device/simulator
3. Click on "Get better stuff" button

### Expected Behavior
These blank spaces should not appears after inserting new item to list, like on image below:
![Simulator Screen Shot - iPhone 11 - 2020-07-22 at 16 47 44](https://user-images.githubusercontent.com/9110951/88191193-74076580-cc3b-11ea-9eb2-7f2053ac4826.png)

### Actual Behavior
Blank spaces appears after inserting new item to list. Look how it looks on image below:

![Simulator Screen Shot - iPhone 11 - 2020-07-22 at 16 47 41](https://user-images.githubusercontent.com/9110951/88191272-8d101680-cc3b-11ea-8de1-89a45a159adc.png)

### Additional comments
Besides, CollectionView doesn't scroll smoothly, when you try to implement pagination on your list and if items on this list have different heights you can observe that list is jumping a bit, it should stay on same scrolling position. Look at video below:
https://streamable.com/b4tsmv

### Basic Information

- Xamarin Forms: 4.7.0.11.42
- Visual Studio for Mac 8.6.5 (build 23)
- Xcode ver 11.5

### Reproduction Link
https://github.com/mariaszek9003/XamarinFormsCollectionViewTest

**Comment by joix97** [comment] 2020-07-24 16:20
I experience that, too. It's quite annoying bug

**Comment by DuncWatts** [comment] 2020-07-29 14:48
In the example you haven't got ItemSizingStrategy="MeasureAllItems" set, the default behaviour is to measure the first item and use that size for all items.

**Comment by mariaszek9003** [comment] 2020-07-29 16:22
@DuncWatts MeasureAllItems is a default value for ItemSizingStrategy, so it not make any difference to set it explicitly https://docs.microsoft.com/pl-pl/dotnet/api/xamarin.forms.itemsizingstrategy?view=xamarin-forms

**Comment by Tommigun1980** [comment] 2020-10-21 12:37
Maybe this is the root cause of https://github.com/xamarin/Xamarin.Forms/issues/12554 and https://github.com/xamarin/Xamarin.Forms/issues/12555?

If so Xamarin please fix this as it introduces so many follow-up bugs that it's almost impossible to use the CollectionView. It would be such a useful component.

Thanks.

**Comment by Codelisk** [comment] 2020-10-22 17:38
Thats a big one

**Comment by joix97** [comment] 2020-10-23 13:38
A huge one

**Comment by Tommigun1980** [comment] 2020-10-24 02:43
That's what she said.

**Comment by hartez** [comment] 2021-02-08 18:09
This is fixed in 5.0.0.1931.

**Closed by hartez** 2021-02-08 18:09 UTC
Labels: a/collectionview, e/5 :clock5:, m/high impact :black_large_square:, p/iOS 🍎, t/bug :bug:
