### ISSUE TITLE
[iOS,Shell] Incorrect ContentPage position

### ISSUE THREAD

**Issue by mrutter** [xamarin/Xamarin.Forms#5811] opened 2019-04-04 15:02 UTC
### Description
The content page displayed inside a ShellSection (bottom tabs mode) is incorrectly positioned: the top of the page goes behind the top edge of the screen. I tried only the iOS emulator (not a real device). It works fine with Android emulator.

It looks to me that the portion of the ContentPage that overlaps the top edge has the same height of the bottom tab bar.

### Steps to Reproduce
I just created a new solution with Visual Studio for Mac (Enterprise 2019) using the "Xamarin.Forms Shell" template and I ran it. Nothing more. As you can see, both the pages (Browse and About) are cut in the upper side (part of the page is positioned beyond the upper side).
 
### Expected Behavior
The ContentPage should be fully visible. 

### Actual Behavior
The ContentPage is cut at the top side.

### Basic Information
- Xamarin.Forms 3.6.0.264807
- iOS emulator (different iPhones and iPads) with iOS 12.2
- Visual Studio 2019 for Mac

### Screenshots

<img width="350" alt="screen-1" src="https://user-images.githubusercontent.com/5046792/55565966-19bb5c00-56fb-11e9-8cc1-0e09c2ac0369.png">
<img width="350" alt="screen-2" src="https://user-images.githubusercontent.com/5046792/55565968-19bb5c00-56fb-11e9-89ed-5042215dc10c.png">

**Comment by samhouts** [comment] 2019-04-05 00:05
Please see https://github.com/xamarin/Xamarin.Forms/issues/4752#issuecomment-470157545. Thanks!

**Comment by samhouts** [comment] 2019-04-05 00:05
Duplicate of #4752

**Closed by samhouts** 2019-04-05 00:05 UTC
Labels: a/shell :shell:, p/iOS 🍎, t/bug :bug:
