### ISSUE TITLE
trying to focus the next Entry in a ListView

### ISSUE THREAD

**Issue by qualifood** [xamarin/Xamarin.Forms#3806] opened 2018-09-17 13:08 UTC
### Description
When displaying Data in a ListView and trying to Focus the next Entry, the next Entry can't be focused. You have to manually target the Entry to Focus it.

### Steps to Reproduce

1. Have a ListView with <Entry Completed="..."/> Elements
2. target the First Entry
3. Click Enter
4. No New Entry is selected

### Expected Behavior
The selected Entry should be Focused.

### Actual Behavior
Nothing is in Focus.

### Basic Information

- Version with issue: v3.1.0.697729 & 3.2.0.729530-pre2
- Last known good version: -
- IDE: Visual Studio Professional 2017 Version 15.8.4
- Platform Target Frameworks: 
  - Android: 8.1
- Affected Devices: Samsung Galaxy Tab A (2016)

### Reproduction Link

[XFFocus.zip](https://github.com/xamarin/Xamarin.Forms/files/2388640/XFFocus.zip)

**Comment by samhouts** [comment] 2019-02-07 18:47
Duplicate of #1600

**Closed by samhouts** 2019-02-07 18:47 UTC
