### ISSUE TITLE
[Bug] Frame and other views shadow 

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#7827] opened 2019-10-04 15:08 UTC
### Description
This bug appear after updating from v3.6.0.344457 to v4.2.0.848062.
If you put any view under frame it will have shadows(even if frame invisible).

### Code example
    <StackLayout>
        <Frame HorizontalOptions="FillAndExpand" HeightRequest="35" BackgroundColor="#252525" HasShadow="True"/>

        <Grid HorizontalOptions="FillAndExpand" HeightRequest="43" BackgroundColor="#EEEEEE">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.7*"/>
                <ColumnDefinition Width="0.3*"/>
            </Grid.ColumnDefinitions>
        </Grid>

        <BoxView BackgroundColor="#EEEEEE" HorizontalOptions="FillAndExpand" HeightRequest="43"/>

        <Image HorizontalOptions="FillAndExpand" HeightRequest="43" BackgroundColor="#EEEEEE" Source="nature"/>
    </StackLayout>

### Screenshots
![photo_2019-10-04_18-06-36](https://user-images.githubusercontent.com/32664004/66218385-bfaf4980-e6d1-11e9-92f0-7c49d1f1d00d.jpg)

**Comment by samhouts** [comment] 2019-10-04 16:50
Duplicate of #7218

**Closed by samhouts** 2019-10-04 16:50 UTC
Labels: i/regression, s/unverified, t/bug :bug:
