### ISSUE TITLE
Picker in UWP does not show empty entry correctly. [Bug] 

### ISSUE THREAD

**Issue by Terminator24** [xamarin/Xamarin.Forms#7778] opened 2019-10-02 13:05 UTC
### Description
Xamarin.Forms.Picker doesn't show correctly an empty entry (for example: String.Empty) in UWP.

### Steps to Reproduce
1. Create a Picker and add some string element as items.
2. Add an empry string as item.
3. Execute in UWP and see the wrong behavior.

### Expected Behavior
Picker showing the items plus the empty string as an empty row,
and when selecting the empty row (as empty string), showing an empty string.

### Actual Behavior
Picker showing the items plus the empty string as an empty row,
and when selecting the empty row (as empty string), it shows the actual namespace of the current class instead of the empty string.

### Basic Information
- Version with issue: Xamarin.Forms 4.2.0.815419.
- Last known good version: Unknown.
- IDE: Visual Studio 2019 Community
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  Build 18362 (version 1903).
- Android Support Library Version: 
- Nuget Packages:
  - Microsoft.NETCore.UniversalWindowsPlatform 6.2.9.
- Affected Devices:
  - Windows 10.

### Screenshots

![Image1](https://user-images.githubusercontent.com/17992288/66046401-f21c4380-e525-11e9-8d55-06ef438847b6.jpg)
![Image2](https://user-images.githubusercontent.com/17992288/66046402-f2b4da00-e525-11e9-811c-11920defd31e.jpg)

**Comment by PureWeen** [comment] 2019-10-02 17:31
@Terminator24 can you attach a repro? I'm not having the best of luck reproducing

**Comment by Terminator24** [comment] 2019-10-02 19:05
[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3682923/TestApp.zip)

**Comment by PureWeen** [comment] 2019-10-02 19:26
@Terminator24 this looks like it's fixed in 4.3

I saw the behavior in your attached repro and after upgrading to the latest 4.3 pre2 it no longer displays the type

**Closed by PureWeen** 2019-10-02 19:26 UTC
Labels: s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
