### ISSUE TITLE
Xamarin.Forms MacOS: Cannot access a disposed object. Object name: 'FormsNSTextField'.

### ISSUE THREAD

**Issue by ammadj** [xamarin/Xamarin.Forms#4268] opened 2018-10-31 10:12 UTC
### Description
Cannot access a disposed object.
Object name: 'FormsNSTextField'.
We have a very simple requirment. 

GUI is navigated to a BaseControl via adding the BaseControl window as a Children to Grid ContentView.
We are trying to achieve a simple functionality of hiding the Entry box upon successful registration. But when registred, navigated to other menuitems and switching the applications , Main GUI Crashes of application crashes with the above error, if **NotRegistered stack panel** with **Entry**(**eRegistrationBox**) is set to IsVisibility = false from Code behind.

We are currently using 2 stackpanels like below in a ContentView which are upon navigation are added to Grid.Children after Clearing the calling Grid.Children.Clear()

```
<StackLayout>                      
         <StackLayout x:Name="Registered" IsVisible="true">                 
                <Label Text="Product is registered"/>              
         </StackLayout>              
         <StackLayout x:Name="NotRegistered" IsVisible="false">                
                <Label Text="Product is not registered" />
                <Entry  x:Name="eRegistrationBox" TextChanged="eRegistrationKey_TextChanged"/>                                           <controls:TextButton x:Name="tbRegister" Text="Register" Tapped="btnRegister_Tapped" />              
          </StackLayout>         
</StackLayout>
```

When registered the NotRegistered stackpanel's visibility is hidden. and vice versa.

The issue only happens when **Entry**(**eRegistrationBox**) is shown first as a part of our logic of **Un-Registered**, then **NotRegistered stack panel** is set **IsVisible =False** from **IsVisible = True**. But if we run GUI with application already registered i.e.  **NotRegistered stackpanel** is already set to **IsVisible = false**, the application doesn't crash.

### Steps to Reproduce

1.  **Entry** is shown first with in a stackpanel (like shown above)
2.  StackPanel Visibility set to false
3.  Navigated to other tabs
4. Applications switched
5. Clicked on the GUI again. and it crashes

The crash happens when HandleWindowDidBecomeKey gets invoked, and accesses Window and CurrentEditor, which are now disposed as part of the current object.
at 

```
void HandleWindowDidBecomeKey(object sender, EventArgs args)
{
    if (Window != null && CurrentEditor == Window.FirstResponder)
        FocusChanged?.Invoke(this, new BoolEventArgs(true));
}
```

after Disposing at

```
if (Window != null)
{
    Window.DidResignKey -= HandleWindowDidResignKey;
    Window.DidBecomeKey -= HandleWindowDidBecomeKey;
}
```
### Additional Findings

We were able to find a workaround if we use **Editor**(**eRegistrationBox**) instead of **Entry**(**eRegistrationBox**) and stop using visibility part. So this rules out the problem of this being caused by navigation of tabs. Moreover, if we start using **Editor**(**eRegistrationBox**) and IsVisibility part the GUI Crashes. 
3rdly. It gives an **exception** if we use **Entry** and **dont** use the **Visibility** properties too. in other words it gives exception anyways with Entry upon navigating to other BaseControls but works fine if we use **Editor** and donot use Visibility options

### Expected Behavior
GUI runs smoothly. 
### Actual Behavior
GUI Crashes
### Basic Information

- Version with issue: 3.2.0.839982
- IDE: Visual Studio For Mac 2017

**Comment by warthenr** [comment] 2018-10-31 10:53
Does this only happen on Mojave?  Does it happen on High Sierra also?  Looks similar to another recently fixed issue #4076 .

**Comment by ammadj** [comment] 2018-10-31 11:00
Nop it is currently happening on High Sierra and Mojave both. and I agree it does seems similar but our issues are entirely different. If you look at the additional information part. It works fine with Editor and without visibility part upon navigation. but with Entry it crashes everytime (with and without visibility)

**Comment by ech0matrix** [comment] 2018-10-31 14:58
I've reproduced this on Sierra.

It looks like a couple of events are intended to be unregistered during the dispose, however Window is already null, so the unregistration is skipped. BUT, the handlers still get called later. The crash happens when HandleWindowDidBecomeKey gets invoked, and accesses Window and CurrentEditor, which look to now be disposed as part of the current object.

The only way I've been able to work around this is to copy the EntryRenderer into my own code, and modify the HandleWindowDidResignKey and HandleWindowDidBecomeKey handlers to return immediately if _disposed is set. However, this is a pretty bad cludge, and the real fix would be to make sure those handlers don't get called in the first place.

**Comment by pauldipietro** [comment] 2018-10-31 18:52
I was able to cause a crash by selecting the Entry, switching to another tab, command-tabbing to another application and then back.

**Comment by ech0matrix** [comment] 2018-11-05 22:29
It looks like this issue may have been introduced with this commit, when the event handlers in question were added:
https://github.com/xamarin/Xamarin.Forms/commit/02050d7b6e25b93d0c13e62c06764f79245df55c#diff-6c0cb2c7530eb6279612f5c2aa615331

**Comment by ammadj** [comment] 2018-11-13 11:32
Guys is there an ETA for this?  @ech0matrix @pauldipietro

**Comment by ammadj** [comment] 2018-12-17 07:04
@PureWeen @pauldipietro  guys would be great if you can update on this please.. thanks

**Comment by jcapellman** [comment] 2019-01-07 20:11
@PureWeen @pauldipietro 
Are update here?

**Comment by jcapellman** [comment] 2019-03-14 22:12
Doing another ping on this issue - still plaguing us

**Comment by ammadj** [comment] 2019-03-29 06:52
@PureWeen  @samhouts  @pauldipietro 

Hellpp required on this one :-)
would be great if an ETA can be provided

**Comment by jcapellman** [comment] 2019-03-30 01:17
Or at least a work around, as this causes the app to crash

**Comment by baywolf-studios** [comment] 2019-04-15 21:04
> I've reproduced this on Sierra.
> 
> It looks like a couple of events are intended to be unregistered during the dispose, however Window is already null, so the unregistration is skipped. BUT, the handlers still get called later. The crash happens when HandleWindowDidBecomeKey gets invoked, and accesses Window and CurrentEditor, which look to now be disposed as part of the current object.
> 
> The only way I've been able to work around this is to copy the EntryRenderer into my own code, and modify the HandleWindowDidResignKey and HandleWindowDidBecomeKey handlers to return immediately if _disposed is set. However, this is a pretty bad cludge, and the real fix would be to make sure those handlers don't get called in the first place.

Really not the way I want to get it working but it works and gives a workaround until Xamarin decides to fix the issue. Had to recreate quite a few classes to get the renderer copied in. Thanks!

**Comment by RadWes** [comment] 2019-04-18 16:07
Just seeing if there was any movement on this.  I created a simple solution that easily reproduces the issue here.  In this scenario, it happens when you click off the app and then back on to it. 
 The login page has two hidden Entry controls. 
https://github.com/RadWes/XamTest
Can anyone share a sample of the work around?

**Comment by baywolf-studios** [comment] 2019-04-18 16:19
> Can anyone share a sample of the work around?

Here's the files I copied and modified to not call the events if the window is disposed like ech0matrix posted above.

https://gist.github.com/baywolf-studios/03caf8b9879d9ec6619a37e5e52a9671

probably some better way to organize and recreate them but... it seems to work.

**Comment by baywolf-studios** [comment] 2019-06-06 17:50
Any updates on this getting fixed?

**Comment by Jacko1394** [comment] 2019-06-17 04:24
I'm interested in a fix for this also 😄

**Closed** 2019-06-19 21:15 UTC
Labels: e/4 :clock4:, help wanted, i/high, p/macOS, t/bug :bug:, up-for-grabs
