### ISSUE TITLE
[Bug] AppIcons don't work when debugging to physical iOS device

### ISSUE THREAD

**Issue by rezamohamed** [xamarin/Xamarin.Forms#14846] opened 2021-11-08 21:23 UTC
When Icon images are added to the Assets.xcassets as a new appicon set, the icon does not show up when debugging to a physical iOS device (iPhone). The icons do work in the iOS Simulator just fine. On the device, just the default compass-looking icon is shown.

Steps to Reproduce
1. Create a new project
2. Add icon images to the AppIcons.iconset
3. Add entry to info.plist if this entry doesn't exist - "XSAppIconAssets" - "Assets.xcassets/AppIcon.appiconset"
4. Debug to connected iPhone

Expected Behavior
AppIcon on device should show the updated icons.

Actual Behavior
Default empty icon appears (white grid)

Environment
=== Visual Studio Community 2019 for Mac ===

Version 8.10.13 (build 11)
Installation UUID: 75489e36-68d6-4c6f-b6ac-ad20cca3d851
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.403/Sdks
SDK Versions:
	5.0.403
	5.0.402
	5.0.401
	5.0.203
	5.0.202
	3.1.415
	3.1.414
	3.1.413
	3.1.409
	3.1.408
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.12
	5.0.11
	5.0.10
	5.0.6
	5.0.5
	3.1.21
	3.1.20
	3.1.19
	3.1.15
	3.1.14

=== .NET Core 3.1 SDK ===

SDK: 3.1.415

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 20:09:18 UTC

=== Xamarin.iOS ===

Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/rezamohamed/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0_302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:12 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:30 UTC

=== Build Information ===

Release ID: 810130011
Git revision: 53e3946a0f6b630a1124eb7ff26c1b545d040d32
Build date: 2021-11-04 11:20:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Wed Oct 13 17:33:23 PDT 2021
    root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

**Comment by jfversluis** [comment] 2021-11-09 09:40
Have you tried deleting the app from the physical device? Maybe delete the bin & obj folders from the file system and do a complete rebuild? Also check you csproj for any weird entries related to this.

I doubt that this is actually something that is a bug because then we would be overloaded with people reporting this which is not the case :)

If that all doesn't work, could you try to create a new application that shows this problem and attach it here?

**Comment by themronion** [comment] 2021-11-13 07:24
@jfversluis i think the guys uses hot restart, and one of its limitation are app icons

**Comment by jfversluis** [comment] 2021-11-13 10:09
Also are you using Hot Restart? This is one of the limitations I think

**Comment by rezamohamed** [comment] 2021-11-13 16:54
Yea I have tried with and without Hot Restart. It’s weird cause I’m finding that projects created with Visual Studio work fine, but when I create a project with Rider it doesn’t work. I couldn’t figure out what was wrong with my existing solution, I had to recreate a new solution using Visual Studio and recreate everything and it works.

**Comment by federicobenedetti** [comment] 2021-11-15 09:08
I can confirm i have the same exact problem.

**Comment by jfversluis** [comment] 2021-11-17 14:25
Hm strange, I also see #14077 that seems to describe this behavior. However deploying to the store it seems to be there. I will close this for now. If you see it happening again, I think the proper place for this would be on the Xamarin.iOS repository :) thanks!

**Closed by jfversluis** 2021-11-17 14:25 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/unverified
