### ISSUE TITLE
PageRenderer in Xamarin Forms hides the TabBar of a TabbedPage 

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#4193] opened 2018-10-24 07:07 UTC
Attached solution TabTest shows the problem. Run it, tap “Click me”, and you see the TabBar, everything is normal. Now go to MainTabbedPagePageRenderer. You will see that the content is commented out. Uncomment the content and run the app again. Now the TabBar is not visible. It should be visible. 

https://devdiv.visualstudio.com/DevDiv/_queries/edit/711784/

**Comment by samhouts** [comment] 2018-11-29 18:31
Duplicate of #4222

**Closed by samhouts** 2018-11-29 18:31 UTC
Labels: e/4 :clock4:, feedback-ticket, t/bug :bug:
