### ISSUE TITLE
[Bug] The Picker margin is not working properly from 4.3.0.778476-pre1 above.

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#8547] opened 2019-11-18 10:21 UTC
### Description

We have currently noticed an issue with the picker on setting Margin value. Up to 4.2.0.910310  Margin for a picker it's working fine and when we upgraded the Forms version  4.3.0.778476-pre1 and above we have noticed the strange behavior of Picker Margin.

We have only set the Margin to the Picker but we have facing different behavior in different forms version and we didn't change any code on changing the version 

![image](https://user-images.githubusercontent.com/45868997/69043633-6bf68680-0a19-11ea-855b-460400e72f90.png)

Please refer to the below attached image for reference.

**Xamarin.Forms 4.2.0.910310**

![image](https://user-images.githubusercontent.com/45868997/69043355-e83c9a00-0a18-11ea-8ace-b03f82ce319e.png)

**Xamarin.Forms 4.3.0.778476-pre1**

![image](https://user-images.githubusercontent.com/45868997/69043411-f985a680-0a18-11ea-9ffb-0b9c66937973.png)

We have also attached the sample, please refer to the sample too...
Note: We have checked only in the UWP platform need to ensure in both android as well in ios.
### Steps to Reproduce

1. Run the attached sample already we have Xamarin Version 4.3.0.778476-pre1 in the sample so see the behavior 
2. Then downgrade the Forms version to  4.2.0.910310 and run the sample.
3. Please see the behavior.

### Expected Behavior
Margin should behave as per the  provided range
### Actual Behavior
Margin getting extra pixel from the provided range
### Basic Information

- Version with issue:
- Last known good version: 4.2.0.910310 
- IDE: Visual Studio 2019 
- Platform Target Frameworks: 
  - iOS:  Need to check 
  - Android: Need to chcek 
  - UWP:  
  ![image](https://user-images.githubusercontent.com/45868997/69044038-38682c00-0a1a-11ea-9909-a02bef6090b4.png)

### Reproduction Link
[SupportXForms.zip](https://github.com/xamarin/Xamarin.Forms/files/3858104/SupportXForms.zip)

**Comment by StephaneDelcroix** [comment] 2019-11-19 09:49
@BalasubramaniSundaram this is not the place to promote your product. please refrain from doing so from now on. make sure your team is aware of that too. Thanks

**Comment by jfversluis** [comment] 2019-11-22 11:00
Duplicate of #8150

**Closed by jfversluis** 2019-11-22 11:00 UTC
Labels: a/layout, i/regression, p/UWP, s/unverified, t/bug :bug:
