### ISSUE TITLE
[Bug] Entry with isPassword=true does not display value on iOS 13.2 till 13.7

### ISSUE THREAD

**Issue by Sweekriti91** [xamarin/Xamarin.Forms#12498] opened 2020-10-15 19:08 UTC
### Description
When using the Entry element with `isPassword = true`, on iOS 13.2 till iOS 13.7 the Entry field doesn't load any value, the UI stays blank. The behavior is as expected on iOS 13.0 and 13.1.3. The behavior was seen when running the app on Device and verified by running the DemoApp (attached to this issue) and screenshots attached below. 

I've run multiple runs across all the iOS 13 devices I could find on App Center and for a control set, also ran it against iOS 12 devices. I've also run it using Xamarin.Forms nuget version 4.6 and 4.8 as the initial issue reported was with version 4.6 but updating the nuget didn't fix the issue. 

### Steps to Reproduce

1. Create Entry element (in XAML or C#), set BackgroundColor to transparent, TextColor to Gray and set isPassword flag to true
2. Run it on iOS device running iOS 13.2 till 13.7 
3. The Password entry field, when you type into it, you will not see any text appear in the UI

### Expected Behavior
The Entry element should display typed text but change to the hidden password character symbol. 
![image](https://user-images.githubusercontent.com/5553548/96171326-9840ae80-0ed9-11eb-83b2-a7f5f7061c91.png)

### Actual Behavior
There is no visual change seen, the Text Entry on the UI remains unchanged
![image](https://user-images.githubusercontent.com/5553548/96171376-abec1500-0ed9-11eb-9986-1390c199f426.png)

### Basic Information

- Version with issue: Tested with Xamarin.Forms 4.6 and latest Xamarin.Forms 4.8
- Last known good version: Doesn't seem to be related to Forms version but last iOS version that worked is 13.1.3

- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  Version: 14.4.0.9
  - Android: Version: 11.1.0.17 
  - UWP:  N/A
- Android Support Library Version: Issue only seen on iOS 
- Nuget Packages:
Xamarin.Forms 4.8.1534
Test Cloud Agent 0.21.9
Xamarin.Essentials 1.5.3.2
- Affected Devices:
Any iOS device running iOS 13.2 till iOS 13.7

### Screenshots

For controlled set testing, I ran UITests with the DemoApp with devices from all iOS 13 versions and all iOS 12 versions. 
It works as expected on iOS 12 devices :
![image](https://user-images.githubusercontent.com/5553548/96172041-a642ff00-0eda-11eb-98d7-77aa3eb903b2.png)

It does not work as expected on iOS 13.2 till 13.7 but *does* work on iOS 13.0 and 13.1.3 : 
![image](https://user-images.githubusercontent.com/5553548/96172451-544ea900-0edb-11eb-9ffa-d20e4435e5a9.png)

I also ran individual runs on all the different iOS 13 devices by sub version and I can verify it is not isolated to a specific phone/device. It is related to the iOS versions on the device. I can share those detailed test runs links if needed, just let me know 😄 

### Reproduction Link

[PasswordEntry.zip](https://github.com/xamarin/Xamarin.Forms/files/5387123/PasswordEntry.zip)

### Workaround

None found yet.

**Comment by Sweekriti91** [comment] 2020-10-15 21:47
Quick update, 

Kicked off a new test run using yesterday's Xamarin.Forms update, I'll post the results of that test run here once it is complete. Meanwhile, I was able to find an iPhone 7 running iOS 13.6.1 locally and I tried running the sample on the device directly. I tested 3 versions (Xamarin.Forms 4.6, 4.8.1534 and 4.8.1560) and the behavior works correctly locally on my device. I am able to type into the Entry and I see the circle symbols.

 The weirdness is happening only on App Center Test so far.  Also for reference, this is the run I did on App Center using Xamarin.Forms 4.8.1534 on all the 13.6.1 iPhones they have :

![image](https://user-images.githubusercontent.com/5553548/96189442-56256600-0ef5-11eb-861a-3693be415b39.png)

**Comment by StephaneDelcroix** [comment] 2020-10-19 07:35
Hey @Sweekriti91,

As you weren't able to reproduce this on device/emu, nor was @rachelkang, I'm moving this to need-info for now. As soon as you have facts we can act on, we'll resume our investigation.

In the meantime, you might want to try to reproduce this issue on AppCenter, with Xam.iOS only code...

**Comment by Redth** [comment] 2020-12-15 16:35
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by Redth** 2020-12-15 16:35 UTC
Labels: mobcat, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
