### ISSUE TITLE
The iOS App built on Xamarin Forms; the app size is increasing 3 times when uploading to App Store.

### ISSUE THREAD

**Issue by NiladriPadhy** [xamarin/Xamarin.Forms#15285] opened 2022-04-05 08:15 UTC
Hi Team,

We have build a mobile with Xamarin Forms. The IPA file size is around 37MB, but when its upload to AppStore the file size is showing 87MB. What is the reason behind this and how can we minimise the file size in App Store?

Thanks
Niladri

**Comment by GalaxiaGuy** [comment] 2022-04-06 09:48
This is just an iOS thing:

https://stackoverflow.com/questions/42478186/app-size-on-app-store-is-7x-larger-than-uploaded-app-size#:~:text=When%20your%20application%20is%20approved,the%20compressed%20file%20will%20increase.

https://developer.apple.com/forums/thread/108603

https://forum.unity.com/threads/app-store-ipa-file-size-is-3-times-bigger-that-it-should.485705/

**Comment by jfversluis** [comment] 2022-04-07 08:17
In addition to what @GalaxiaGuy says, I see you also asked your question elsewhere and got an answer along the same lines: https://docs.microsoft.com/en-us/answers/questions/800380/the-ios-app-built-on-xamarin-forms-the-app-size-is.html

Not a bug on our part, so closing this for now

**Closed by jfversluis** 2022-04-07 08:17 UTC
