### ISSUE TITLE
[Bug] Android Entry on appearing weird effect upon Forms 4.4

### ISSUE THREAD

**Issue by taublast** [xamarin/Xamarin.Forms#8986] opened 2019-12-20 16:15 UTC
### Description
After upgrading forms from 4.3 to 4.4 all android entries now show an ugly fading indicator upon page appearing. In different projects, different layouts and pages, with or without any custom renderer, the only thing that made that happend was forms 4.4, on 4.3 it's all fine. 

You can see animated gif and get more info here: 
https://forums.xamarin.com/discussion/comment/398840

Repro project is here: 
https://github.com/taublast/droidentrybug

### Steps to Reproduce

run repro project

or 

1. put entry inside frame with a scrollview above using forms 4.4 
2. open this page

### Expected Behavior

as in Forms 4.3 and below, nothing special.

### Actual Behavior

a wierd fading out rectangle upon apearing

### Basic Information

- Version with issue:
forms 4.4

- Last known good version:

forms 4.3

- IDE:
VS 2019

- Platform Target Frameworks: 
  - Android: compiled vs 9.0

- Affected Devices:
tested on Android emulators api 23 (6.0) and api 25

### Screenshots

https://us.v-cdn.net/5019960/uploads/editor/mf/oewnktd9pug2.gif
https://us.v-cdn.net/5019960/uploads/editor/p4/cxpw3ulizwmk.gif

more here: https://forums.xamarin.com/discussion/comment/398840 

### Reproduction Link

https://github.com/taublast/droidentrybug

**Comment by jfversluis** [comment] 2019-12-23 15:02
Interesting. Seems to be linked to #8626, but clearly it's not exclusive to `CollectionView` and the linked issue also already shows in 4.3.

**Comment by LGFox** [comment] 2020-01-10 13:45
I observe the same glitch on v. 4.4. I checked it on Samsung devices API26/API27. I see this glitch on some labels as well.
It worked well on v. 4.3. iOS works well on v. 4.4.
Rolled back to 4.3 for now.

**Comment by LanceMcCarthy** [comment] 2020-01-28 18:46
I can confirm this happens with Labels as well. A solid bar is visible, which then animates down to the bottom of the view over the course of ~1.5s (instead of upwards as seen in OP's GIF).

**Comment by truedem0n** [comment] 2020-01-31 19:36
did anyone find a fix for this? I have the same issue happening inside a collectionview but with forms9patch

**Comment by taublast** [comment] 2020-02-01 10:19
just use forms 4.3

**Comment by APopatanasov** [comment] 2020-02-06 15:57
When is this issue expected to be fixed? Currently, I cannot update to the latest version of Xamarin.Forms because of it.
Downgrading to 4.3 is also not an appropriate solution because there are fixes in 4.4 that I need.

**Comment by Huaba93** [comment] 2020-02-10 12:01
Same problem with Forms 4.4.0.991640. 

Working:
* ListView

Not working:
* CollectionView
* BindableLayout (StackLayout)

![Screenshot_20200210-124220_Dtonestro - learn Recorder](https://user-images.githubusercontent.com/21239003/74148274-6322e480-4c05-11ea-9691-44729bfb6819.jpg)

**Comment by Reveon** [comment] 2020-02-10 15:53
I am having the same problem on 4.5.0.266-pre3. Labels in CollectionView and BindableLayout (StackLayout).

**Comment by brminnick** [comment] 2020-03-01 16:53
I can confirm this is still exists in v4.5.0.356 when using a `CollectionView`

Here's a reproduction:
 - Download/clone this repo: https://github.com/brminnick/GitTrends
 - Run `GitTrends.Android` on an Android Emulator or Device
 - In the GitTrends app, on the Settings page, connect to your GitHub Account (or tap `ENTER DEMO MODE` if you don't want to connect to your GitHub account)
- In the GitTrends app, navigate back to the main page, titled Repositories
- In the GiTrends app, ensure the `CollectionView` inside of a `RefreshView` is refreshing (if not, execute a pull-to-refresh)
- As the `RefreshView` is refreshing, confirm the effect
- Once the `RefreshView` finishes refreshing, confirm the effect has disappeared 
- On the Repositories page, scroll the list
- While the list is scrolling, confirm the effect appears
- Once the scrolling stops, confirm the effect has disappeared

| `IsRefreshing` is `true` | `IsRefreshing` is `false` | While Scrolling | 
| -----------------------  | ------------------------ | --------------- |
| ![Screenshot_1583081198](https://user-images.githubusercontent.com/13558917/75629776-ae436e00-5b99-11ea-836b-51dbedda656a.png) | ![Screenshot_1583081203](https://user-images.githubusercontent.com/13558917/75629732-383f0700-5b99-11ea-997f-455ad3f59a4a.png) | ![Screenshot_1583081270](https://user-images.githubusercontent.com/13558917/75629802-fc587180-5b99-11ea-9922-0c0ca94147c0.png) |

**Comment by brminnick** [comment] 2020-03-01 17:07
# Work Around

As a workaround, I added [this custom renderer](https://github.com/brminnick/GitTrends/blob/master/GitTrends.Android/CustomRenderers/LabelCustomRenderer.cs) recommended [here](https://github.com/xamarin/Xamarin.Forms/issues/8626#issuecomment-585148662) to solve the problem in my app:

```csharp
using Android.Content;
using GitTrends.Droid;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

//workaround for this issue: https://github.com/xamarin/Xamarin.Forms/issues/8626 and https://github.com/xamarin/Xamarin.Forms/issues/8986

[assembly: ExportRenderer(typeof(Label), typeof(LabelCustomRenderer))]
namespace GitTrends.Droid
{
    class LabelCustomRenderer : Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer
    {
        public LabelCustomRenderer(Context context) : base(context)
        {

        }

        protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
        {
            base.OnElementChanged(e);

            if (Control is null || e.NewElement is null)
                return;

            Control.VerticalScrollBarEnabled = false;
        }
    }
}
```

| `IsRefreshing` is `true` | `IsRefreshing` is `false` | While Scrolling | 
| -----------------------  | ------------------------ | --------------- |
![Screenshot_1583082257](https://user-images.githubusercontent.com/13558917/75629978-b8666c00-5b9b-11ea-8941-af8abbd55d8d.png) | ![Screenshot_1583082259](https://user-images.githubusercontent.com/13558917/75629982-bef4e380-5b9b-11ea-9a33-7e9b1c030f2b.png) | ![Screenshot_1583082262](https://user-images.githubusercontent.com/13558917/75629981-bd2b2000-5b9b-11ea-9839-4eac1867e511.png) |

**Closed** 2020-04-28 01:19 UTC
Labels: 4.4.0, e/3 :clock3:, i/regression, in-progress, p/Android, t/bug :bug:
