### ISSUE TITLE
[Bug] CollectionView ItemSpacing has no effect on UWP

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#8667] opened 2019-11-26 10:49 UTC
### Description
Setting ItemSpacing does nothing on UWP

### Steps to Reproduce

```
<CollectionView ItemsSource="{Binding CallDetails}" Margin="5,5,15,0" Grid.Row="1" Grid.Column="1">
        <CollectionView.ItemsLayout>
                 <LinearItemsLayout ItemSpacing="10" Orientation="Vertical"/>
         </CollectionView.ItemsLayout>
        <CollectionView.ItemTemplate>
               <DataTemplate>
                     <BoxView BackgroundColor="Green"/>
                </DataTemplate>
         </CollectionView.ItemTemplate>
</CollectionView>
```

### Expected Behavior
ItemSpacing applied to green box like android

### Actual Behavior
No Item Spacing

**Comment by jfversluis** [comment] 2019-11-26 10:53
Hey @JKennedy24! Thanks!

I think this was already reported in #7842. I will close this one and mark it as duplicate, please follow the progress in the other issue. Thanks!

**Comment by jfversluis** [comment] 2019-11-26 10:53
Duplicate of #7842

**Closed by jfversluis** 2019-11-26 10:53 UTC
Labels: s/unverified, t/bug :bug:
