### ISSUE TITLE
[Bug] RTL does not support SearchBar  on android 

### ISSUE THREAD

**Issue by amr-moomen** [xamarin/Xamarin.Forms#9061] opened 2020-01-02 15:02 UTC
### Description
SearchBar text, search icon and place holder position should be right when FlowDirection="RightToLeft" on android
i want to change the cancel word on ios to arabic word "الغاء" 
### Steps to Reproduce

1. Create SearchBar 
2. change RTL of page to RightToLeft
3. observe the result

### Expected Behavior
android support RTL for SearchBar  like IOS
the position of text, search icon and place holder should be right when FlowDirection="RightToLeft" on android  
i want to change the cancel word on ios to arabic word "الغاء" 

### Actual Behavior
android does not support RTL for SearchBar and the position of text, search icon and place holder still left

### Basic Information

- Version with issue: all versions of android
- Last known good version: none
- IDE: Visual Studio 2019 Version 16.4.1
- Platform Target Frameworks: 
  - iOS: iphone 11  
  - Android: all versions 
- Android Support Library Version: 
- Nuget Packages:Xamarin.Forms version 4.4.0.991265

### Screenshots

![searchbarandroid](https://user-images.githubusercontent.com/56504816/71671956-30bbd700-2d7d-11ea-957e-f887b79882f2.gif)

![iossearchbar](https://user-images.githubusercontent.com/56504816/71673112-83e35900-2d80-11ea-927b-3060aad3db66.gif)

### Reproduction Link
https://github.com/amr-moomen/SearchBarRTL

**Comment by samhouts** [comment] 2020-01-02 19:58
This is a known limitation:

> Searchbar orientation is controlled by the device locale, not the FlowDirection setting.

If your device is set to a RTL language, the search bar will be RTL.

**Comment by mina5500** [comment] 2020-01-05 07:16
we have this control supports RTL on Android since it supports RTL on iOS
Also for a cancel button caption "Property" in iOS

**Comment by samhouts** [comment] 2020-02-13 17:18
Duplicate of #6538

**Closed by samhouts** 2020-02-13 17:18 UTC
Labels: a/rtl, e/7 :clock7:, p/Android, t/bug :bug:
