### ISSUE TITLE
[Bug] iOS Collectionview Applying 1px Padding to Views

### ISSUE THREAD

**Issue by JMNewsome** [xamarin/Xamarin.Forms#12287] opened 2020-09-28 14:24 UTC
### Description

When using a collectionview and passing a view to a itemTemplate that contains a layout (tested contentView, grid, etc) views are recieving a 1x1 added spacing to the top and left portion of the view, setting margin or padding to 0 does not remove this issue. 

### Steps to Reproduce

1.  Create a collectionview with an itemtemplate that simply passes a view
2.  Set the background color of the content holding view to a color easily visible
3.  Issue only appears to affect iOS

### Expected Behavior
View should be shown without additional padding

### Actual Behavior
View is shown with additional padding

### Basic Information

- Version with issue:
4.6.0.1141, 4.8.0.1451, 5.0.0.1487-pre1
- Last known good version:
N/A
- IDE:
- Platform Target Frameworks: 
  - iOS:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Bug](https://user-images.githubusercontent.com/31290658/94444715-9c986800-0174-11eb-852d-06a1c327b83b.png)

### Reproduction Link

[CollectionViewPaddingIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5292911/CollectionViewPaddingIssue.zip)

**Comment by Confusedfish** [comment] 2020-09-30 11:19
I too have this issue but only with the header template not the main collection elements and again only on iOS using 4.8.0.1451 and 5.0.0.1487-pre1

I can confirm that the workaround mentioned on [#8961](https://github.com/xamarin/Xamarin.Forms/issues/8961#issuecomment-584811051) of wrapping the content in a frame worked for me andresolved the issue on iOS.

**Comment by JMNewsome** [comment] 2020-10-01 12:26
@Confusedfish thank you, that workaround worked great for me using the Frame for my content holders!

**Comment by Silic0nS0ldier** [comment] 2020-12-01 06:50
Issue reproduced with nested `ContentView`. Suggested workaround of `Frame` with zero padding worked.

For those looking in the future (quite possibly myself included), here is an example before/after of the workaround.

Before
```xml
...
<CarouselView x:Name="TabContainer" IsSwipeEnabled="False">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <ContentView Content="{Binding .}" />
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
...
```

After
```xml
...
<CarouselView x:Name="TabContainer" IsSwipeEnabled="False">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <Frame Content="{Binding .}" Padding="0" />
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
...
```

**Comment by jfversluis** [comment] 2022-02-09 09:37
Duplicate of #8961

**Closed by jfversluis** 2022-02-09 09:37 UTC
Labels: p/iOS 🍎, e/5 :clock5:, a/collectionview, duplicate
