### ISSUE TITLE
[Bug] [UWP] Button has height bigger than Picker

### ISSUE THREAD

**Issue by Sonic3R** [xamarin/Xamarin.Forms#8577] opened 2019-11-20 10:18 UTC
### Description

The button height is big than near Picker. I set HeightRequest to a value and seems that not working (is ignored somehow).

### Steps to Reproduce

1. Create picker and button near it
2. Run app

### Expected Behavior
The button height should be same with picker like in Xamarin Forms latest 4.2.x version.

### Basic Information

- Version with issue:
- Last known good version: latest 4.2.x
- IDE: VS 2019 16.3
- Platform Target Frameworks: 
  - UWP:  17163
- Nuget Packages: Xamarin Forms latest 4.3.x
- Affected Devices: Windows

### Screenshots
![image](https://user-images.githubusercontent.com/6311947/69229962-1fcd5280-0b8f-11ea-90b4-0c6d9a22252f.png)

### Reproduction Link
See attached item

[XamarinTests.zip](https://github.com/xamarin/Xamarin.Forms/files/3868625/XamarinTests.zip)

**Comment by joshminor** [comment] 2019-11-20 16:57
This looks like the same issue as #8439

**Comment by Sonic3R** [comment] 2019-11-21 07:12
> This looks like the same issue as #8439

I think that problem is related to button not picker. For me, the picker looks fine but button's height is not ok.

**Comment by jfversluis** [comment] 2019-11-27 14:17
I have actually confirmed that the fix in #8160 fixes this issue, so it is that problem

**Comment by WayaFlyfeather** [comment] 2020-01-21 15:38
@jfversluis If this is fixed by #8160, and #8160 is merged… where does that leave this issue?

**Comment by jfversluis** [comment] 2020-01-22 14:41
@WayaFlyfeather I see the PR was merged for 4.4. So the fix should be in 4.4 and 4.5 by now. Would you be able to confirm this fixed it with that version? If so, we can close this :)

Thanks for paying attention!

**Comment by WayaFlyfeather** [comment] 2020-01-22 16:04
@jfversluis Actually, I was just looking for potential bugs to fix, and this one was in Ready for Work, so was confused if it was fixed or not… ;) Also I was wondering if it might be related to #9123.

Will try checking later if it seems to be fixed with latest versions.

**Comment by WayaFlyfeather** [comment] 2020-01-23 14:28
@jfversluis So I ran the repro-project, updated to latest stable XF 4.4.0.991537, and yes, it does indeed appear to be fixed :)

![2020-01-23](https://user-images.githubusercontent.com/3807144/72992705-83c10100-3df4-11ea-9463-33cb0116af83.png)

**Comment by jfversluis** [comment] 2020-01-23 14:31
@WayaFlyfeather thanks! I’ll close this one for now then :)

If you need any help finding another issue to fix let me know

**Closed by jfversluis** 2020-01-23 14:31 UTC
Labels: 4.3.0, e/3 :clock3:, i/regression, p/UWP, t/bug :bug:
