### ISSUE TITLE
xamarin.forms Ver.: 4.8.0.1451 gives UriFormatException at runtime

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12417] opened 2020-10-08 16:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1207356/xamarinforms-ver-4801451-gives-uriformatexception.html)._

---
[severity:It bothers me. A fix would be nice]
xamarin.forms Ver.: 4.8.0.1451 gives UriFormatException at runtime (see error reported below)
xamarin.forms Ver.: 4.8.0.1364 does not give that runtime error.

Error reported at runtime:
"
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The format of the URI could not be determined.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Unhandled exception at 0x00007FFC2B1AB65C (KernelBase.dll) in SetVerNumbers.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001D8D75C7E40, 0x0000000000000002).
"

I don't know where  that exception comes from ?

-- Eigil

---
#### Feedback Bot on 10/2/2020, 02:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MagicAndre1981** [comment] 2020-10-08 18:20
Duplicate of #12153 and fixed in [4.8.0.1534 (4.8 SR3)](https://www.nuget.org/packages/Xamarin.Forms/4.8.0.1534)

**Comment by jsuarezruiz** [comment] 2020-10-09 07:36
This issue have been fixed. Seems to be the same as: https://github.com/xamarin/Xamarin.Forms/issues/12153

**Closed by jsuarezruiz** 2020-10-09 07:36 UTC
Labels: a/embedded fonts, p/UWP, s/unverified, t/bug :bug:
