### ISSUE TITLE
[Bug] Flickering lines in Android CollectionView in 4.2.0

### ISSUE THREAD

**Issue by roleemosh** [xamarin/Xamarin.Forms#7281] opened 2019-08-26 17:47 UTC
### Description
In CollectionView
Flickering lines at the end of the label.Text when use this: StringFormat='{0:MMMM}'}
Xamarins.Forms 4.2.0.709249
but not in Xamarin.Forms 4.1.0.709244
### Steps to Reproduce

1. 
in collectionview, datatemplate
<pancake:PancakeView
                    Grid.Row="1"
                    Grid.Column="1"
                    BackgroundColor="{StaticResource PickerBackgroundColor}"
                    BorderThickness="0"
                    CornerRadius="20"
                    HasShadow="True">
                    <Grid ColumnSpacing="0" RowSpacing="0">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="35" />
                            <RowDefinition Height="22" />
                            <RowDefinition Height="*" />
                        </Grid.RowDefinitions>
                        <Label
                            Grid.Row="1"
                            FontSize="16"
                            HorizontalOptions="Center"
                            Style="{StaticResource TreatmentText}"
                            Text="{Binding ApproxStartDate, StringFormat='{0:MMMM}'}" 
                            TextColor="{StaticResource BackgroundGradientStartColor}"
                            VerticalOptions="Center" />
                    </Grid>
                </pancake:PancakeView>
2.     public DateTime ApproxStartDate { get; set; }
3. 

### Expected Behavior
None
### Actual Behavior
Flickering lines
### Basic Information

- Version with issue:
- Last known good version:
- IDE: 
- Platform Target Frameworks: 
  - iOS:  
  - Android: 28 Android 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![69050763_385553278810336_5187685860610408448_n](https://user-images.githubusercontent.com/22876507/63710801-51f24100-c83a-11e9-9e45-3760638425b6.png)

**Comment by ArifImran-apex** [comment] 2019-08-30 20:27
Is there a workaround for this, till the fix for this gets packaged for a stable release?

**Comment by AlanPikholtz** [comment] 2019-09-02 19:53
Im having the same issue

**Comment by ArifImran-apex** [comment] 2019-09-05 16:23
@AlanPikholtz decreasing the font size of the label worked for me.

**Comment by hudaIT** [comment] 2019-09-08 09:42
Same issue for me

**Comment by samhouts** [comment] 2019-09-13 17:13
Can someone please attach a small project that demonstrates this issue? Thanks!

**Comment by ArifImran-apex** [comment] 2019-09-13 17:18
Ok, will try to do it, over the weekend.

**Comment by samhouts** [comment] 2019-09-16 21:14
Thanks, we'll keep looking for it.

**Comment by samhouts** [comment] 2019-10-17 20:42
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ShahmanTeh** [comment] 2019-11-01 03:40
Please re-open this issue, I can verify this issue still persists.

**Comment by ShahmanTeh** [comment] 2019-11-01 05:09
Attached is the xaml snippets and the gif that displayed the issue

```xaml
...
<CollectionView
            Grid.Column="0"
            Grid.ColumnSpan="2"
            Grid.Row="1"
            ItemsSource="{Binding DataSource_1}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <AbsoluteLayout
                        Margin="0,1">
                      <Grid
                          AbsoluteLayout.LayoutBounds="0,0,1,1"
                          AbsoluteLayout.LayoutFlags="All"
                          ColumnSpacing="2"
                          Padding="16,10">
                        <Grid.ColumnDefinitions>
                          <ColumnDefinition Width="2*" />
                          <ColumnDefinition Width="Auto" />
                          <ColumnDefinition Width="90" />
                          <ColumnDefinition Width="Auto" />
                          <ColumnDefinition Width="0.5*" />
                        </Grid.ColumnDefinitions>
                        <Label
                            Grid.Column="0"
                            VerticalTextAlignment="Center"
                            TextColor="Black"
                            Text="{Binding Binded_Text_1}"/>

                        <Label
                            Grid.Column="2"
                            Margin="0"
                            MaxLines="1"
                            LineBreakMode="TailTruncation"
                            HorizontalTextAlignment="Center"
                            VerticalOptions="Center"
                                    >
                          <Label.FormattedText>
                            <FormattedString>
                              <Span Text="{Binding Binded_Formatted_Text_1, Mode=TwoWay}" />
                              <Span Text=" / " />
                              <Span Text="{Binding Binded_Formatted_Text_2}" />
                            </FormattedString>
                          </Label.FormattedText>
                        </Label>

                        <!--Control is from XF-Material-Library: Refer to https://github.com/BaseflowIT/XF-Material-Library -->
                        <mtrl:MaterialIconButton
                            Grid.Column="3"
                            WidthRequest="36"
                            HeightRequest="36"
                            VerticalOptions="Center"
                            BorderColor="Orange"
                            BackgroundColor="White"
                            BorderWidth="2"
                            Padding="0"
                            CornerRadius="4"
                            ButtonType="Flat"
                            Image="ic_add_white"
                            TintColor="Orange"
                            Command="{Binding AddCommand}"
                            CommandParameter="{Binding .}" />
                        
                        <!--Control is from XF-Material-Library: Refer to https://github.com/BaseflowIT/XF-Material-Library -->
                        <mtrl:MaterialIconButton
                            Grid.Column="1"
                            WidthRequest="36"
                            HeightRequest="36"
                            VerticalOptions="Center"
                            BorderColor="Orange"
                            BackgroundColor="White"
                            BorderWidth="2"
                            Padding="0"
                            CornerRadius="4"
                            ButtonType="Flat"
                            Image="ic_subtract_white"
                            TintColor="Orange"
                            Command="{Binding SubtractCommand}"
                            CommandParameter="{Binding .}" />

                        <!--Control is a modified from Intelliabb: Refer to https://github.com/Intelliabb/XamarinControls -->
                        <IntelliAbb:Checkbox
                            Grid.Column="4"
                            HorizontalOptions="EndAndExpand"
                            Margin="0"
                            Design="Unified"
                            Shape="Circle"
                            CheckColor="White"
                            FillColor="Orange"
                            OutlineColor="Orange"
                            OutlineWidth="2"
                            IsChecked="true" />
                      </Grid>

                    </AbsoluteLayout>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
...
```


![Problem4](https://user-images.githubusercontent.com/4898138/68003142-1abf6680-fca7-11e9-8f74-97e2baba31cf.gif)

**Comment by mojazu** [comment] 2019-12-14 03:44
Hi. Any updates on this bug? I can confirm this is still an Issue in Xamarin.Forms 4.4.0.991265.

In my case the random lines appear on each element while scrolling a CollectionView. They seem to appear on every item in the collection at the same time, and they fade out at the same time after a couple of seconds.

Has anybody found a workaround for this issue yet? Thanks.

**Comment by jenscski** [comment] 2019-12-18 13:01
Same problem here. Only appearing when using FontSize="Medium".

**Comment by jarkko-koskinen** [comment] 2020-01-24 13:10
Hi, we just updated our Xamarin Forms to version 4.4.0.991477 and after the update we are getting some flickering on our entry inputs. We are not using CollectionView, but the flickering is still there on our StackLayouts. 

It seems that this is caused by the HorizontalTextAlignment and VerticalTextAlignment properties set to the entry input fields. When I removed those properties the flickering disappeared. Our UI will break if those are removed permanently, so hopefully this issue will be fixed soon, thanks.

**Comment by jsuarezruiz** [comment] 2020-04-21 07:53
Attached a repro sample: https://github.com/xamarin/Xamarin.Forms/files/4497151/ButtonProblem.zip

**Comment by giuseppenovielli** [comment] 2020-04-21 08:20
With this custom renderer, 
https://forums.xamarin.com/discussion/180400/android-button-rendering-problems/
i fix, temporary this issues, but please fix this!!

Thanks!!

**Comment by Kubion70** [comment] 2020-04-22 15:11
This workaround may hep you with labels.
Create class in android project:

```csharp
public class CustomLabelRenderer : Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer
{
    public CustomLabelRenderer(Context context)
        : base(context)
    {
    }

    protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
    {
        base.OnElementChanged(e);

        if (Control == null)
        {
            return;
        }

        Control.HorizontalScrollBarEnabled = false;
        Control.VerticalScrollBarEnabled = false;
    }
}
```

Then add to android project AssemblyInfo (or over created class namespace if you wish) following code:

```csharp
[assembly: ExportRenderer(typeof(Label), typeof(CustomLabelRenderer))]
```

**Closed** 2020-06-03 04:27 UTC
Labels: a/collectionview, i/regression, in-progress, m/high impact :black_large_square:, p/Android, t/bug :bug:
