### ISSUE TITLE
AppShell navigation fails to return top level item

### ISSUE THREAD

**Issue by DaveBrickley** [xamarin/Xamarin.Forms#10930] opened 2020-06-02 10:03 UTC
### Description
My scenario is I have a list view accessed via AppShell flyout
The list contains links to pages
The AppShell link returns to the point in history when returning rather than the page that is referenced by the link itself

### Steps to Reproduce

A user clicks an option on the flyout menu
It returns a list of pages
The click through a succession of pages via this list
They go to another option in the flyout menu
They now return to the original flyout menu
Instead of the top level page referenced in this link, they get the last page they viewed, with only the back button and every page they browsed to go through before they get the list again
### Expected Behavior
Show the page directly linked to the AppShell flyout every time it is clicked
### Actual Behavior
Goes through the entire history of pages requiring back button to be pressed through them all

### Basic Information

- Version with issue: 4.5.0.617
- Last known good version: NA
- IDE: VSE
- Platform Target Frameworks: 
  - iOS:

**Comment by jsuarezruiz** [comment] 2020-06-04 12:09
@DaveBrickley I would be interested to know how you navigate on the page with the list of pages. Could you attach a small example where reproduce the issue?.

**Comment by DaveBrickley** [comment] 2020-06-04 12:13
@jsuarezruiz Hi, see this thread below in which I am discussing it with another user, this is up to date as of now

https://forums.xamarin.com/discussion/comment/413499?

That person correctly determined that the basic use case I am describing is expected, based on official demo code, however my response to which they have not yet answered is it's the fact it remembers every page you went to before it'll show you the list again

so say someone looked at 10 pages off my list view, then went to another flyout menu option, then returned, they would see the last page they visited and then have to click back 9 more times before they saw the list again

**Comment by DaveBrickley** [comment] 2020-06-05 06:30
I've added further comments to the thread above as the person didn't quite understand the problem, so I will reiterate here

- The official demo has a list of animals (monkey, lion and so on) in the flyout
- When you click either you get subspecies list from which there is a page
- If you click the page, then go to another flyout menu option, then return, you get the page and must click back before you get the list
- If however you click all the monkeys in the list, then go to lion, then return, you click back 10 times or more to get to the list

If this really is as designed then I struggle to see people not getting really frustrated with it

**Comment by DaveBrickley** [comment] 2020-06-11 10:55
@jsuarezruiz just wanted to check, have I explained my scenario clearly enough? Or do you need more info? Thank you! @samhouts

**Comment by samhouts** [comment] 2020-06-26 21:14
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by DaveBrickley** [comment] 2020-06-27 14:53
@samhouts Hi, so I believe the official demo code (the animals one) exhibits the behaviour - see the link below

https://forums.xamarin.com/discussion/comment/413499

The person I am conversing with there shows that it occurs with the example code

However as I pointed out it shows only one page in the history array and so it doesn't look too bad 

The problem, and I think it's an entirely common use case, is if the user visits 10 or 20 pages off the list, then goes to another Flyout, then comes back, they'll have to click back button 10 or 20 times before seeing the list again

**Comment by PureWeen** [comment] 2020-06-27 15:25
@DaveBrickley this is a duplicate of this issue correct?

https://github.com/xamarin/Xamarin.Forms/issues/6855#issuecomment-591721930

The main thing I need to figure out here is how to light up this behavior.

Should it be from an enum?

```C#
enum NavigationStackBehavior
{
     Default, Retain, Clear
}
```

Or maybe this is a behavior you can influence during navigation. For example once shell has the URI it's going to navigate you to then you can remove URIs

**Closed by PureWeen** 2020-06-27 15:25 UTC
Labels: a/navigation, a/shell :shell:, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:

**Comment by DaveBrickley** [comment] 2020-06-27 15:48
@PureWeen hi, thanks for confirming, I hadn't seen this issue. Is the example in the one you link to a valid workaround? As I can't see how you'd apply it in my case, both my pages are shell pages, and I cannot see any way to override the default behaviour of a Flyout menu click since there doesn't appear to be any way of trapping the click? Hmm, one thought does occur, can you set a view model to be binding context for appshell and then use a command in the flyout entry references that would pass the context to the related commant method for ontapped?
