### ISSUE TITLE
Cases where in UWP an Entry does not display existing data until the field is tapped. Works in Droid[Bug] 

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/Xamarin.Forms#10137] opened 2020-03-30 16:05 UTC
### Description
If an Entry is contained within a ScrollView, in UWP, the second and subsequent ones to not display their content until they get focus. It works in Droid and iOS.
### Steps to Reproduce

1. create a basic Xamarin Forms cross platform Solution (include Droid, iOS, UWP
2. use this xaml as the Content:
`    <StackLayout Orientation="Vertical" BackgroundColor="White">
        <ScrollView>
            <StackLayout  Orientation="Vertical" BackgroundColor="Black">

                <StackLayout Orientation="Horizontal">
                        <Label FontSize="20"   TextColor="Black" Text="Description" 
                            HorizontalOptions="Start"   HeightRequest="28"  VerticalOptions="Center"/>

                        <Entry  BackgroundColor="White" 
                            FontSize="18" 
                            VerticalOptions="Center"
                            Text="Sam"/>
                </StackLayout>

                <StackLayout Orientation="Horizontal">
                    <Label FontSize="20"   TextColor="Black" Text="Description" 
                        HorizontalOptions="Start"   HeightRequest="28"  VerticalOptions="Center"/>

                    <Entry  BackgroundColor="White" 
                        FontSize="18" 
                        VerticalOptions="Center"
                        Text="Fred"/>
                </StackLayout>

            </StackLayout>
        </ScrollView>
    </StackLayout>`

3. run in Droid and in UWP

### Expected Behavior
Both Sam and Fred appear immediately in all platforms.

### Actual Behavior
Sam and Fred appear immediately in Droid and iOS. 
In UWP, Sam (the content of the first Entry) appears but Fred only appears when it received focus.
However, if the ScrollView is removed, then everything works in all platforms
### Basic Information

- Version with issue: XF 4.5.0.495
- Last known good version: unknown
- IDE:VS 2019 16.4.5
- Platform Target Frameworks: 
  - iOS:      n/a
  - Android:  n/a
  - UWP:      18362
- Android Support Library Version: 
- Nuget Packages:
Microsoft.NETCore.UniversalWindowsPlatform 6.2.9
NETStandard.Library 2.0.3
Xamarin.Android.Support.Design 28.0.0.3
Xamarin.Android.Support.v4  28.0.0.3
Xamarin.Android.Support.v7.AppCompat 28.0.0.3
Xamarin.Android.Support.v7.CardView 28.0.0.3
Xamarin.Android.Support.v7.MediaRouter 28.0.0.3
Xamarin.Forms 4.5.0.495

- Affected Devices:

### Workaround
Do not include Entry within a ScrollView or remove the ScrollView.

**Comment by kingces95** [comment] 2020-04-04 01:32
Please attach a zipped reproduction.

**Comment by WillAutioItrax** [comment] 2020-04-06 14:19
@kingces95 Thanks for looking at this. Does it need to be a zip? 
Will this do:
https://github.com/WillAutioItrax/XFEntryFail

**Comment by apolloLegends** [comment] 2020-04-08 16:41
I'm seeing a similar issue with Editor.

**Basic Information**
Last worked - 4.2.0.910310
First broke - 4.3.0.908675

**Expected Behavior**
When the page loads the text of the Editor is shown

**Actual Behavior**
iOS - text of editor is shown
UWP - text of the editor is not shown, user must set the focus for the text to appear

**Workaround**
Do not include Editor within a ScrollView or remove the ScrollView

I suspect that the cause is the same as above so i'm not sure if I should create a separate case - please advise.

**Comment by rmarinho** [comment] 2020-04-09 17:13
Sames happens to Editor on uwp

**Comment by bmacombe** [comment] 2020-04-09 23:01
This is likely a duplicate of #8787

**Comment by samhouts** [comment] 2020-08-26 22:45
closed by #11140

**Closed by samhouts** 2020-08-26 22:45 UTC
Labels: a/editor, a/entry, e/4 :clock4:, p/UWP, t/bug :bug:
