### ISSUE TITLE
Frame background it's not sticky to rounded borders [UWP]

### ISSUE THREAD

**Issue by patsadow2** [xamarin/Xamarin.Forms#3027] opened 2018-06-13 06:29 UTC
As in title 
Does't work in [uwp] xamarin 3.0

```
         <Frame CornerRadius="10"  
                   OutlineColor="Red" 
                   IsClippedToBounds ="True"
                   Padding="0" BackgroundColor="Aqua">
                <StackLayout  BackgroundColor="Chartreuse" HeightRequest="40" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
                        <Label Text="ssssssss"></Label>
                </StackLayout>
            </Frame>
```

**Comment by samhouts** [comment] 2018-07-30 21:06
I believe this is resolved by #3239 and is a duplicate of #2838.

**Closed by samhouts** 2018-07-30 21:06 UTC
Labels: p/UWP, t/bug :bug:
