### ISSUE TITLE
ScrollY value always getting zero while host PDF based website in WebView

### ISSUE THREAD

**Issue by KarthikRaja26** [xamarin/Xamarin.Forms#8575] opened 2019-11-20 06:14 UTC
### Description
While scrolling the PDF-based website in WebView, I always get the ScrollY value as 0, but this problem does not occur in WebView's Normal website. I prepared a sample to show the difference for your confirmation. In that sample go to page 1, then open the output window and scroll through the web page, now you can see ScrollY being written. Go to page 2, open the output window and scroll through the webpage, now you can see that ScrollY is always zero.

### Steps to Reproduce

1. Run the attached sample.
2. Go to Page 2
3. Now open the OutPut window.
4. Now scroll the webview.
5. You could see ScrollY value always is Zero.

### Expected Behavior
ScrollY value should not zero 
### Actual Behavior
ScrollY value is zero.
### Basic Information

- Version with issue:
- Last known good version: no
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  Need to check
  - Android: 
![image](https://user-images.githubusercontent.com/46777511/69213251-88193580-0b89-11ea-8fbc-73a28ec71442.png)
 
  - UWP:  Need to check
- Nuget Packages: Xamarin Forms 4.3.0.991211

### Reproduction Link

[WebView_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/3867569/WebView_Issue.zip)

**Comment by jfversluis** [comment] 2019-11-26 13:44
Hi @KarthikRaja26 thanks for reporting this!

However, I don't think this is a Xamarin.Forms issue, sorry.

As you already said yourself: with a "regular" page it works fine. With the PDF one, it doesn't. That is probably because the PDF page loads all kinds of things in JavaScript and a container somewhere deep inside the DOM of the page is scrolling, but not the actual webpage itself. Does that make sense?

So, basically this same problem is described in this StackOverflow question with native Android: https://stackoverflow.com/questions/29134082/webview-getscrolly-always-returns-0

I see someone mentioning that they solved it with a gesture recognizer. A harder solution would be to hook into some JavaScript events and surface that to your c# code.

In any case, like I said, this is not an issue with our framework. You'd probably be better off opening a question on StackOverflow or the Xamarin Forums. Therefore I will close the issue here.

However, thank you for the issue and taking the time to create a reproduction!

**Closed by jfversluis** 2019-11-26 13:44 UTC
Labels: a/webview, p/Android, s/unverified, t/bug :bug:
