### ISSUE TITLE
Xamarin iOS Large Title Scroll Transition: Snapping vs Smoothing

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15018] opened 2022-01-03 18:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-iOS-Large-Title-Scroll-Transitio/1618087)._

---
[severity:It's more difficult to complete my work]
Hello, 
Using a ScrollView with a Large Title on iOS forces the Large Title to snap when scrolling instead of the desired smooth transition.

Current behavior: 
! [eO9Yh.gif] (https://aka.ms/dc/image?name=B597587f0495e4ceda6f45d5ff564f808637756107932709023_eO9Yh.gif&tid=597587f0495e4ceda6f45d5ff564f808637756107932709023)

Desired behavior
! [ZxSJ1.gif] (https://aka.ms/dc/image?name=B97513ddb96ca4d72aa6dd6035396402d637756108115289763_ZxSJ1.gif&tid=97513ddb96ca4d72aa6dd6035396402d637756108115289763)

Using a custom renderer I have these settings:

```
ExtendedLayoutIncludesOpaqueBars = True;
EdgesForExtendedLayout = UIRectEdge.Top;
AutomaticallyAdjustsScrollViewInsets = true;
NavigationController.NavigationBar.PrefersLargeTitles = true;
NavigationItem.LargeTitleDisplayMode = UINavigationItemLargeTitleDisplayMode.Automatic;
NavigationController.NavigationBar.Translucent = true;
```

It seems there is a solution for this in Swift but unable to implement using custom renderers: [https://stackoverflow.com/questions/47649375/ios-11-large-navigation-bar-title-unexpected-velocity?noredirect=1&lq=1](https://stackoverflow.com/questions/47649375/ios-11-large-navigation-bar-title-unexpected-velocity?noredirect=1&lq=1)

---
#### Feedback Bot on 12/20/2021, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-01-03 19:00
Duplicate of #15006

**Closed by jfversluis** 2022-01-03 19:00 UTC
