### ISSUE TITLE
Setting a view as the TitleView on a NavigationPage doesn't work on UWP

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3502] opened 2018-08-07 15:30 UTC
### Description

Setting `NavigationPage.TitleView` to different views on UWP has no effect. The navigation bar remains blank. On iOS and Android the feature works as intended.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the cross-platform TitleViewPage and cycle the TitleViews.

### Expected Behavior

A series of views are set as the `TitleView` on the `NavigationPage` (on UWP).

### Actual Behavior

The navigation bar remains empty (on UWP).

### Basic Information

- Version with issue: 
- Last known good version: 3.2.0.637442-pre1
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP: 10.0.16299.0 (as created by the VS2017 template).  

### Reproduction Link

[NavigationPageTitleView.zip](https://github.com/xamarin/Xamarin.Forms/files/2266999/NavigationPageTitleView.zip)

**Comment by samhouts** [comment] 2018-08-21 22:41
Turns out, this is a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3297 and is fixed in pre2. Thanks!

**Closed by samhouts** 2018-08-21 22:41 UTC
Labels: e/2 :clock2:, p/UWP, t/bug :bug:
