### ISSUE TITLE
[Bug] SwipeView commands and click events not executed

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10114] opened 2020-03-28 12:33 UTC
Hi.

I have a swipe view inside a collection view's item template, and it's not registering taps on the swipe items. Neither command nor click event works, instead it just closes the swipe menu, and the buttons never go to a pressed state. Only tested on iOS, don't know if it happens on Android.

I'm using the latest preview version 4.6.0.494-pre2.

**Comment by jfversluis** [comment] 2020-03-28 14:07
Looks like this has been reported a number of times before, for instance #8774 and will most likely be fixed by #9638

**Comment by jfversluis** [comment] 2020-03-28 14:08
Duplicate of #8774

**Closed by jfversluis** 2020-03-28 14:07 UTC
Labels: s/unverified, t/bug :bug:

**Comment by a4anu10** [comment] 2020-05-26 18:05
Update the xamarin forms
