### ISSUE TITLE
[Android] Regression HorizontalTextAlignment of Entry control no longer works

### ISSUE THREAD

**Issue by AlexeyStarkov** [xamarin/Xamarin.Forms#2167] opened 2018-03-22 21:12 UTC
### Description
HorizontalTextAlignment not working for entry

*Note*
When testing Entry inside the Xamarin.ControlGallery project the HorizontalTextAlignment for entry works fine but when you use HorizontalTextAlignment in a Xamarin Forms project then HorizontalTextAlignment  doesn't work so most likely one of the custom renderers in the ControlGallery project is giving the illusion that this is working

### Steps to Reproduce

1. Add Entry control to page
2. Set "Center" or "End" to HorizontalTextAlignment property
3. Run

### Expected Behavior
Placeholder and text can be placed to Center or End.
### Actual Behavior
Placeholder and text are allways in Start position
### Basic Information

- Version with issue: 3.0.0.296286-pre2
- Last known good version: 2.5.****
- IDE: Visual Studio 2017 (PC)
- Platform Target Frameworks: 
  - Android: Target 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages:
- Affected Devices: Test device: samsung galaxy a5 2017 android 7.0

**Comment by jassmith** [comment] 2018-03-22 22:09
Works fine for me in testing. Can you give me a repro?

**Comment by kingnguyen1993** [comment] 2018-03-23 02:47
I have too, May be it happen when use custom renderer.

**Comment by AlexeyStarkov** [comment] 2018-03-23 11:41
No, I have default Entry control without custom renderer.
<Entry Margin="20,3" Text="{Binding CardNumber, Mode=TwoWay}" Placeholder="0000 0000 0000 0000" HorizontalTextAlignment="Center"  Keyboard="Numeric" PlaceholderColor="{StaticResource PlaceholderColor}"/>

I am trying create new empty project, but I can't because I can't update Xamarin.Android.Support packages (NU1107: Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue.) Working with Xamarin is incredibly annoying. All the time something falls off and breaks down. By the way I was forced to do update to 3.0.0.296286-pre2 because after update to last stable version I got the wrong button mapping. After them I tried to do downgrade, but I got any errors too and I could not do it. I had no choice but to update Xamarin to 3.0.0.296286-pre2. (*Facepalm*). Now my buttons are look right, but I've problem with entries (*head to wall*)

**Comment by PureWeen** [comment] 2018-03-28 19:06
Sorry to hear you're having issues.  Can you attach a repro ? Maybe from that I can also see why your having issues getting things updated and see the issue you've originally referenced

**Comment by AlexeyStarkov** [comment] 2018-03-29 14:07
Obviously I have some problem with dependencies in nuget, but I was able to update the packages and I did sample. I had uploaded project to my google drive: [https://drive.google.com/open?id=1TAAfjQ_PRxI-9bHeTN1ALapvAdE3sD5r](url)

**Comment by PureWeen** [comment] 2018-03-31 16:05
Hmmm yea this looks like a 3.0 regression :-/  thank you for the repro. I see it works fine in 2.5.1 though

**Comment by PureWeen** [comment] 2018-03-31 16:42
@AlexeyStarkov  looks like this is fixed on the 3.0.0 branch .  I'll close this for now and once the next pre-release comes out if you're still having issues let me know

**Comment by AlexeyStarkov** [comment] 2018-03-31 17:17
@PureWeen
Thank you for help. I'll update XF.

**Comment by kyluke** [comment] 2018-05-08 12:57
I'm facing this issue with v3.0.0.446417, is there a later version I should be looking out for?

**Comment by PureWeen** [comment] 2018-05-08 15:31
@kyluke  do you have a reproduction we can see by chance? I had done my tests with the one included and it all seemed well. 

There's another PR coming later on
https://github.com/xamarin/Xamarin.Forms/pull/2215

That addresses some additional measuring issues in Android but not sure if that will address what you are seeing

**Comment by kyluke** [comment] 2018-05-08 15:37
@PureWeen I'll see if I can pop some sample code up on here, I suspect you've already solved my problem. That PR (https://github.com/xamarin/Xamarin.Forms/pull/2215), is that in v3.0.0.446417 or is that still to come?

**Comment by PureWeen** [comment] 2018-05-08 15:38
@kyluke  Still to come

**Comment by kyluke** [comment] 2018-05-08 15:39
@PureWeen, okay cool. Is there an ETA on that?

**Comment by PureWeen** [comment] 2018-05-09 15:43
@kyluke  can you try 
https://www.nuget.org/packages/Xamarin.Forms/3.1.0.469394-pre1

See if that fixes your issue?

**Comment by dominik-weber** [comment] 2018-05-15 16:15
@PureWeen I think the PR you mentioned fixes a different problem than the one in this issue alltogether ☹ Have you looked into the repro project posted by @AlexeyStarkov ? Please note that the repro has this line in MainPage.xaml:
`<Entry BackgroundColor="Green" Placeholder="0000 0000 0000 0000" PlaceholderColor="AliceBlue" HorizontalTextAlignment="Center" VerticalOptions="Center"/>` So basically the text (and placeholder) of the Entry should be horizontally centered. This does work with Xamarin Forms 2.5.1, but it does NOT work with Xamarin Forms 3.XX. I have tested this with the current stable version 3.0.0.482510 as well as 3.1.0.469394-pre1.
Could you please reopen the issue until this is fixed? Please also see this Forum post regarding the same problem: https://forums.xamarin.com/discussion/126338/horizontaltextalignment-not-working-after-3-0-update

Please see these screenshots:

**Xamarin Forms 2.5.1 (good):**
![image](https://user-images.githubusercontent.com/1771927/40069328-3e33d754-586b-11e8-8a0b-4739ecc9d434.png)

**Xamarin Forms 3.XX (bad):**
![image](https://user-images.githubusercontent.com/1771927/40069356-53ff1bde-586b-11e8-9cd5-545fe0f527fe.png)

**Comment by PureWeen** [comment] 2018-05-16 19:27
The core of this issue came around during the RTL updates because of a change to use TextAlignment instead of gravity for aligning the text. But the TextAlignment API only has any effect when you have RtlSupport enabled for an android application

I have a PR checked in for a fix but for now I can think of two workarounds
- implement a custom renderer for all the Entry elements and just set the gravity of the TextView yourself
- or if you set  *application android:supportsRtl="true"* in your Manifest then that should cause text to start centering again

**Closed** 2018-05-22 08:47 UTC
Labels: 3.0.0, i/regression, p/Android, t/bug :bug:

**Comment by tmt242001** [comment] 2018-06-06 01:55
Issue still exist in 3.0.0.530893

**Comment by dominik-weber** [comment] 2018-06-06 17:33
@tmt242001 have you tried rebuilding / delete bin and obj folders? 3.0.0.530893 seems to resolve the issue for me

**Comment by tmt242001** [comment] 2018-06-07 02:27
Yes, works now. Tested on 3.0.0.550146 (rebuild after deleting bin and obj folders)

**Comment by gceaser** [comment] 2019-12-03 16:13
This appears to be back in 4.3.0.99121.  

<Entry x:Name="txtIPAddress" HorizontalOptions="FillAndExpand" VerticalOptions="Start"
                       Text="{Binding ServerIPAddress, Mode=TwoWay}" 
                       BackgroundColor="White" Margin="16,0,16,0" HorizontalTextAlignment="Center" />

Works on iOS not android.  This I an Android 9 emulator screenshot:

![Screenshot_1575389513](https://user-images.githubusercontent.com/8093949/70068394-ed274f00-15bd-11ea-934d-0c2696d17114.png)

**Comment by realprogik** [comment] 2019-12-30 13:37
I have the same issue with 4.4.0.991265 version. As @gceaser mentioned with support rtl it's working but we need a real fix because I don't need the right to left layout support in my app.
