### ISSUE TITLE
[Bug] Formatted text of Label when setted Italic FontAttributes ,the FontSize not works in Xamarin Forms .

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#8859] opened 2019-12-12 02:02 UTC
### Description

Refer to [this document](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/label/?tabs=vswin&tutorial-step=3) to set formatted text of Label in Xamarin Forms . However , when `FontAttributes="Italic"` the `FontSize `of **Label** can not work. 

### Steps to Reproduce

1. Create a new Xamarin Forms Application
2. Adding follow code in Xaml

```
<Label TextColor="Gray"
       FontSize="Large">
    <Label.FormattedText>
        <FormattedString>
            <Span Text="This sentence contains " />
            <Span Text="words that are emphasized, "
                  FontAttributes="Italic" />
            <Span Text="and underlined."
                  TextDecorations="Underline" />
        </FormattedString>
    </Label.FormattedText>
</Label>
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/7145819/70675875-5fd2b180-1cc5-11ea-8b8b-3727e5cb6848.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/7145819/70675896-6e20cd80-1cc5-11ea-9db0-1128c1d4816c.png)

### Basic Information

- IDE: Visual Studio 16.3.10
 - Android:  9.0
- Nuget Packages: Xamarin Forms  4.2.0.709249

### Screenshots

![image](https://user-images.githubusercontent.com/7145819/70675896-6e20cd80-1cc5-11ea-9db0-1128c1d4816c.png)

### Reproduction Link

https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/label/?tabs=vswin&tutorial-step=3

**Comment by kingces95** [comment] 2019-12-14 00:09
Hm. Works for me. Please attached a zipped reproduction.

**Comment by jfversluis** [comment] 2019-12-30 11:05
Duplicate of #3901

**Closed by jfversluis** 2019-12-30 11:05 UTC
Labels: p/Android, s/unverified, t/bug :bug:
