### ISSUE TITLE
WebView.Focused event works on Android, but not on iOS

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#5526] opened 2019-03-13 04:20 UTC
### Steps to Reproduce

I create a StackLayout which contains a WebView .And I set the Focused event.It works fine in Android but not works in iOS.
`webView.Focused += WebView_Focused;`

   ```
private void WebView_Focused(object sender, FocusEventArgs e)
   {
       //do some thing            
   }
```

I think it because of in native iOS platform.UIWebview and WKWebview do not support focus event( in native iOS we call becomeFirstResponder ).

So,is there a solution to solve it?

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 11.4
 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment] 2019-03-19 22:53
Duplicate of #5616

**Closed by samhouts** 2019-03-19 22:53 UTC
Labels: p/iOS 🍎, t/bug :bug:
