### ISSUE TITLE
[Bug] Shell completely breaks PanGesture

### ISSUE THREAD

**Issue by hudaIT** [xamarin/Xamarin.Forms#6533] opened 2019-06-14 12:27 UTC
#

### Description
PanGestures do not work when using a shell

### Steps to Reproduce

1.  Create a shellPage
2.  Create a ContentPage with a PanGesture in it
3.  Try to move your element

### Basic Information
- Version with issue: Xamarin 4.1.0.483098-pre1

Only tested in Android

[PanGestureBrokeSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3290781/PanGestureBrokeSample.zip)

**Comment by jfversluis** [comment] 2019-06-14 12:30
Would it be possible to provide a reproduction project for this showing the issue @hudaIT? Thanks!

**Comment by hudaIT** [comment] 2019-06-14 12:36
Yes i will make one.
I would really apreciate a workaround or something similar because its pretty urgent for our company. :')

**Comment by hudaIT** [comment] 2019-06-14 12:36
> Would it be possible to provide a reproduction project for this showing the issue @hudaIT? Thanks!



> Would it be possible to provide a reproduction project for this showing the issue @hudaIT? Thanks!

Yes i will make one.
I would really apreciate a workaround or something similar because its pretty urgent for our company. :')

**Comment by hudaIT** [comment] 2019-06-14 12:36
> Would it be possible to provide a reproduction project for this showing the issue @hudaIT? Thanks!

Yes i will make one.
I would really apreciate a workaround or something similar because its pretty urgent for our company. :')

**Comment by hudaIT** [comment] 2019-06-14 12:53
Sample Added

**Comment by jfversluis** [comment] 2019-06-14 14:01
Got your sample, thank you! 

I've added a normal `ContentPage` next to it to verify that that works as expected and it seems to do that. In your sample the black box moves only very little and does not seem to do anything beyond that.

It's note directly clear to me what the cause is so I also can't provide you with a workaround at this time. Maybe @PureWeen has some idea. If you find anything in this regard @hudaIT please keep us updated. The more information the better :)

**Comment by jfversluis** [comment] 2019-06-14 14:21
Duplicate of #6060

**Closed by jfversluis** 2019-06-14 14:21 UTC
Labels: a/shell :shell:, t/bug :bug:
