### ISSUE TITLE
Flyout behavior Disabled - Does not disable Flyout.

### ISSUE THREAD

**Issue by wesleyscaldwell** [xamarin/Xamarin.Forms#6783] opened 2019-07-05 01:08 UTC
### Description
In Shell, Flyout behavior : Disabled - Does not actually disable the flyout menu. 
- A workaround can be done by hiding the top bar but the user can still swipe in from the left side to access the menu. 

It appears intended functionality is described as "Disabled – indicates that the flyout can't be opened by the user."

### Steps to Reproduce
Trial 1:
1.  Use the latest Xaminals project
2.  FlyoutBehavior="Disabled" to the shell object
3.  Tested on multiple android devices - Did not test on iOS.
4.  Flyout never gets disabled.

Trial 2:
1.  Created Blank project
2.  Added Shell Flyout with two basic flyout items
3.  FlyoutBehavior="Disabled" to the shell object
4.  Tested on multiple android devices - Did not test on iOS.
5.  Flyout never gets disabled.

### Expected Behavior
Flyout behavior
The flyout can be accessed through the hamburger icon or by swiping from the side of the screen. However, this behavior can be changed by setting the Shell.FlyoutBehavior attached property to one of the FlyoutBehavior enumeration members:

**Disabled – indicates that the flyout can't be opened by the user.**
Flyout – indicates that the flyout can be opened and closed by the user. This is the default value for the FlyoutBehavior property.
Locked – indicates that the flyout can't be closed by the user, and that it doesn't overlap content.

### Actual Behavior
The flyout is still available to the user and all flyout items are active but the once disabled the flyout menu does not collapse.

### Basic Information
VS 2019 - 16.1.5
Xamarin.Forms - 4.1.0.555618
NETStandard.Library 2.0.3

**Comment by jfversluis** [comment] 2019-07-05 08:24
Thanks for the report @wesleyscaldwell !

I indeed see this happen, there is already an issue for this. I will mark this as a duplicate and please follow the progress there. Thanks!

**Comment by jfversluis** [comment] 2019-07-05 08:24
Duplicate of #6261

**Closed by jfversluis** 2019-07-05 08:24 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:

**Comment by wesleyscaldwell** [comment] 2019-07-05 13:22
Thanks, not sure how i missed the original.

**Comment by v2vehooi** [comment] 2019-09-07 15:17
may i know this issue solve already ? even as at today, when i create tab bar using xamarin form shell. i'll still get the hamburger menu on the top navigation bar although i already add : Flyoutbehavior to disabled.
Please help. thank you

**Comment by WahidinAji** [comment] 2019-10-10 15:47
Yes, me too. and I think this is a bug of a new update @v2vehooi,

**Comment by WahidinAji** [comment] 2019-10-10 15:50
and now that I'm solving my problem, I'm downgrading xamarin.form, from 4.2 to 4.1

**Comment by ektoplasma23** [comment] 2020-01-02 20:35
Please fix this!

**Comment by zerokewl88** [comment] 2020-10-08 10:05
Still seeing this issue today. FlyoutBehavior="Disabled" set in XAML not being respected.

Xamarin.Forms 4.5.0.495

**Comment by mrissaoussama** [comment] 2022-06-10 22:14
this issue is still not fixed
