### ISSUE TITLE
[Bug] Android Button align text to left on TabbedPage

### ISSUE THREAD

**Issue by alexanderzuban** [xamarin/Xamarin.Forms#6561] opened 2019-06-17 22:54 UTC
### Description

When content is dynamically switched inside of the TabbedPage for some reason button render text at the left side on the second attach

### Steps to Reproduce
1. Create a tabbed page
2. Display a page which is dynamically replacing its part with views which have Button
3. When view used the second time button layout text left side

### Expected Behavior
Text remains centered 
 
### Actual Behavior
Text align to left side

### Basic Information

- Version with issue: 4.0

### Screenshots
![Screenshot_20190617-185134](https://user-images.githubusercontent.com/45107947/59641907-113ac500-9131-11e9-9e86-8a1751365d25.jpg)

![Screenshot_20190617-185144](https://user-images.githubusercontent.com/45107947/59641910-139d1f00-9131-11e9-8253-ff64aa73dea6.jpg)
### Reproduction Link
Sample project attached
[ButtonTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3299123/ButtonTest.zip)

**Comment by TFreudi1** [comment] 2019-06-18 11:44
Same thing here, it is happen since Forms 4.0, I must go back to 3.6.

**Comment by xXdRaGoNrIdDeRXx** [comment] 2019-06-18 14:53
I have found this issue with just reusing pre constructed views the first time it is visible the buttons look fine then sometimes the second or subsequent view of the same page renders the text left aligned.

**Comment by PureWeen** [comment] 2019-06-18 15:04
Possible duplicate of https://github.com/xamarin/Xamarin.Forms/issues/6282

Once the Nuget for this
https://github.com/xamarin/Xamarin.Forms/pull/6329

Is ready then we'll test!!

**Comment by PureWeen** [comment] 2019-06-18 15:51
I tested with the attached nuget and it appears fixed by https://github.com/xamarin/Xamarin.Forms/pull/6329

I've attached the nuget if you'd like to test it yourself

[Xamarin.Forms.4.2.0.533156.nupkg.zip](https://github.com/xamarin/Xamarin.Forms/files/3302347/Xamarin.Forms.4.2.0.533156.nupkg.zip)

**Closed** 2019-06-18 15:52 UTC
Labels: s/unverified, t/bug :bug:
