### ISSUE TITLE
[iOS] Incorrect Text Alignment for Label's FormattedText when FlowDirection = RightToLeft

### ISSUE THREAD

**Issue by OmerHmead** [xamarin/Xamarin.Forms#3311] opened 2018-07-15 08:38 UTC
### Steps to Reproduce
1. Create new project;
2. Add the following xaml to the main page ;

```
<StackLayout VerticalOptions="Center">
    <Label BackgroundColor="Yellow" FlowDirection="RightToLeft">
      <Label.FormattedText>
        <FormattedString>
          <Span Text="Formatted"></Span>
          <Span Text=" "></Span>
          <Span Text="Text"></Span>
        </FormattedString>
      </Label.FormattedText>
    </Label>
    <Label  Text="Normal Text" BackgroundColor="Pink" FlowDirection="RightToLeft"/>
  </StackLayout>
```
 
### Expected Behavior
The text should be aligned to the right 

### Actual Behavior
The text is aligned to the left.

### Basic Information

- Version with issue: (Latest) 3.1.0.637273
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  (Tested on) 11.4
- Affected Devices: All

### Screenshots

![image](https://user-images.githubusercontent.com/41253169/42732057-77231c82-8822-11e8-95ae-60bb3524cc4f.png)

**Comment by PureWeen** [comment] 2018-07-17 22:12
This looks like it will be fixed in an upcoming release

I tested using our nightly 
https://blog.xamarin.com/try-the-latest-in-xamarin-forms-with-nightly-builds/

And we should have a 3.2 pre-release out soon that looks to also have this issue resolved

![image](https://user-images.githubusercontent.com/5375137/42848285-24ad1da2-89dc-11e8-9e4e-7db3a325dcec.png)

**Comment by Omarkth** [comment] 2019-10-07 21:58
Hi, looks like this has bug is a regression, it was working up until 3.4

4.2.X
<img width="362" alt="image" src="https://user-images.githubusercontent.com/822615/66351033-7aa34580-e965-11e9-82b8-83939c598140.png">

It's even worse in 4.3-pre3 where even the normal text stopped responding to the set FlowDirection 
4.3-pre3
<img width="359" alt="image" src="https://user-images.githubusercontent.com/822615/66350813-e507b600-e964-11e9-8d7a-2a15a6d3f0b5.png">

**Comment by jfversluis** [comment] 2019-10-08 13:55
Added a repro project, seems to not work at all anymore for both iOS and Android

[Repro3311.zip](https://github.com/xamarin/Xamarin.Forms/files/3702729/Repro3311.zip)

**Comment by samhouts** [comment] 2020-11-05 23:41
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Elashi** [comment] 2020-11-14 23:14
I am still having the problem on iOS devices

**Comment by Elashi** [comment] 2020-11-23 13:53
Any news about this issue

**Comment by rachelkang** [comment] 2020-11-30 21:22
@Elashi would you share what version of XF you're using? I'm able to repro the formattedText label RTL issues on both platforms, but only able to repro the normal label RTL issue on Android (works fine on iOS for me)

**Comment by rachelkang** [comment] 2020-11-30 22:41
@Elashi are you having issues with RTL for just the FormattedText on iOS, or also for the normal Label?

**Comment by Elashi** [comment] 2020-12-01 07:28
Only when I use <Label.FormattedText>

**Comment by sjorsmiltenburg** [comment] 2021-01-18 15:23
@Elashi do you have a workaround?

**Comment by Elashi** [comment] 2021-01-20 09:28
Yes, not to use `<Label.FormattedText>`.  I just use multiple `<Labe>`s instead now.
Instead of using one single big label with a lot of `<Span>`s in it , I use multiple `<Label>`s
Actually , `<Span>`s  have another problem.  If you add Tap gesture handler to it, it will not catch it if you tap on it, you have to tap bellow the actual `<Span>` to be handled correctly.
do NOT use `<Span>` !

**Closed** 2021-01-27 16:34 UTC
Labels: 3.1.0, a/rtl, e/3 :clock3:, help wanted, i/regression, p/iOS 🍎, t/bug :bug:, up-for-grabs
