### ISSUE TITLE
[Bug] Frame has shadow since 4.0.0

### ISSUE THREAD

**Issue by truonglam5555** [xamarin/Xamarin.Forms#8772] opened 2019-12-06 01:42 UTC
on the Android version when creating the 2nd Frame that has Shadow on 4.4 or above but in 4.3 it still works normally hope xamarin to fix the error please thanks !!

**Comment by truonglam5555** [comment] 2019-12-06 01:49
[ExambleFrame.zip](https://github.com/xamarin/Xamarin.Forms/files/3929985/ExambleFrame.zip)

**Comment by PureWeen** [comment] 2019-12-06 05:24
@truonglam5555 can you include a screen shot comparison?


Below is 4.3 compared to 4.4

![image](https://user-images.githubusercontent.com/5375137/70298169-ea8b4c00-17ad-11ea-9e80-6ce073383958.png)

**Comment by truonglam5555** [comment] 2019-12-06 05:50
![Untitled](https://user-images.githubusercontent.com/58577606/70299235-e94a3580-1826-11ea-8da1-2e5f1ce98f0e.png)

**Comment by truonglam5555** [comment] 2019-12-06 06:00
![Untitled](https://user-images.githubusercontent.com/58577606/70299698-35e24080-1828-11ea-8798-32b128edfd59.png)


If you download xamarin froms version 4.3 or lower ,then the bug will see that the boxview has no Shadow, and it will bounce back.

**Comment by PureWeen** [comment] 2019-12-06 17:14
@truonglam5555 what's the API of the devices you are testing?

In your screen shot above are you saying the left or the right image is correct? Which one is 4.3 and which one is 4.4?

**Comment by truonglam5555** [comment] 2019-12-09 02:05
The version on the left is version 4.3 on the right with ipa being the latest current version.

**Comment by truonglam5555** [comment] 2019-12-09 02:13
The interface structure is the same !!

**Comment by truonglam5555** [comment] 2019-12-14 01:14
> @truonglam5555 what's the API of the devices you are testing?
> 
> In your screen shot above are you saying the left or the right image is correct? Which one is 4.3 and which one is 4.4?



Additional API 21 and above and Starting from version 4.1 will appear errors, exactly from Android 5.0 on iOS does not.

**Comment by PureWeen** [comment] 2019-12-20 19:08
@truonglam5555 Apologies but I'm still having trouble seeing the issue

Does the zip project here https://github.com/xamarin/Xamarin.Forms/issues/8772#issuecomment-562396790 still exhibit the issue you describe?

If it does can you please indicate the steps I should take with that project to see the issue you are seeing?

**Comment by truonglam5555** [comment] 2019-12-23 01:30
> @truonglam5555 Apologies but I'm still having trouble seeing the issue
> 
> Does the zip project here [#8772 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/8772#issuecomment-562396790) still exhibit the issue you describe?
> 
> If it does can you please indicate the steps I should take with that project to see the issue you are seeing?

![don'terorr](https://user-images.githubusercontent.com/58577606/71330097-6f6fb700-255d-11ea-9cfb-7641b7fadbf0.PNG)

The image on the right is affected by HasShadown in the second item, it is in the latest version ie currently in xamarin 4.4.x and anhdroid 5. If in android 9 you will see it more clearly. Do you see Boxview is bigger than Boxview on the right?

**Comment by truonglam5555** [comment] 2019-12-23 03:29
> @truonglam5555 Apologies but I'm still having trouble seeing the issue
> 
> Does the zip project here [#8772 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/8772#issuecomment-562396790) still exhibit the issue you describe?
> 
> If it does can you please indicate the steps I should take with that project to see the issue you are seeing?


If necessary, you should download the Exam version to Nuget Xamarin Froms to version 4.0.xxxxx pre1, you will see the difference, if you want to see more clearly, you should let it run on Android 9.

**Comment by samhouts** [comment] 2019-12-31 22:39
Introduced between 3.6.0 and 4.0.0. 
![image](https://user-images.githubusercontent.com/7827070/71635678-60cb7480-2bdb-11ea-8f03-4d2cf6c62b9b.png)

**Comment by samhouts** [comment] 2019-12-31 22:41
Duplicate of #7218

**Closed by samhouts** 2019-12-31 22:41 UTC
Labels: 4.0.0, i/regression, p/Android, s/unverified, t/bug :bug:
