### ISSUE TITLE
[Bug] [UWP] ListView renders very slowly on UWP when in a Grid or StackLayout

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#6233] opened 2019-05-21 02:46 UTC
### Description

If a simple ListView is inside of a Grid or StackLayout, it renders very slowly and you can see black area slowly uncover the ListView.

### Steps to Reproduce

1. Open attached sample
2. Run on UWP in Debug (Issue is most pronounced in Debug, but is visible in release as well)

### Expected Behavior
ListView should appear with no visible loading

### Actual Behavior
ListView appears all black at first and slowly ListView is shown

## Notes
Test project uses a StackLayout as the top level layout. Swap with a Grid and the behavior is the same. 

Remove the StackLayout and the issue goes away. 

Issue is most pronounced when debugging, but is still noticeable in a Release build. 

I know having a single child of a StackLayout or a Grid is not good practice, but the issue persists if I add other controls to the StackLayout or Grid, and certainly it should be OK to have a ListView inside a Grid or StackLayout. I did not test other layout types, but I suspect the issue would remain. 

### Basic Information

- Version with issue: 3.6 and 4.0.pre-10
- Last known good version: unknown
- IDE: VS 2019
- Platform Target Frameworks: 
  
  - UWP:   17763

### Screenshots

[ListViewSlowRender.mp4.zip](https://github.com/xamarin/Xamarin.Forms/files/3200515/ListViewSlowRender.mp4.zip)

### Reproduction Link

[ListViewSlowUWP.zip](https://github.com/xamarin/Xamarin.Forms/files/3200516/ListViewSlowUWP.zip)

**Comment by samhouts** [comment] 2019-05-28 20:22
Duplicate of #6154

**Closed by samhouts** 2019-05-28 20:22 UTC
Labels: a/listview, e/2 :clock2:, p/UWP, t/bug :bug:

**Comment by taskbasic** [comment] 2019-06-06 00:22
This is not the same issue.  Though the wording makes it seem so.  This issue is about ListViewItems rendering into place individually as if on a webpage, which isn't typical behavior for ListViews on UWP.
