### ISSUE TITLE
[Feedback] PageRenderer in Xamarin Forms hides the TabBar of a TabbedPage

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4219] opened 2018-10-26 01:00 UTC
### Description

<p>Attached solution TabTest shows the problem. Run it, tap “Click me”, and you see the TabBar, everything is normal. Now go to MainTabbedPagePageRenderer. You will see that the content is commented out. Uncomment the content and run the app again. Now the TabBar is not visible. It should be visible.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/363048/pagerenderer-in-xamarin-forms-hides-the-tabbar-of.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/711784">original linked feedback ticket</a>.

### Source

[715223](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/715223)

**Comment by StephaneDelcroix** [comment] 2018-10-26 07:08
dupe of #4193

**Closed by StephaneDelcroix** 2018-10-26 07:08 UTC
Labels: feedback-ticket, s/duplicate
