### ISSUE TITLE
Editor does not show a border unlike Entry

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3369] opened 2018-07-21 20:54 UTC
Hi,

Why the Editor control does not show a border or at least provide option property for border as the Editor will just show a white area on iOS without any border.

Why do we need the Editor inside a Frame  or use platform specific dependencies just to show a border when we don't have to do that in the Entry

Thanks,
Jassim

**Comment by VladislavAntonyuk** [comment] 2018-07-22 09:53
you can set border color and border width

**Comment by jrahma** [comment] 2018-07-22 10:03
Editor does not have border property

**Comment by AndreiMisiukevich** [comment] 2018-10-17 09:04
@samhouts this changes will be breaking
would it be acceptable to adjust them like in iOS Entry?

**Comment by samhouts** [comment] 2019-02-06 19:31
Duplicate of #3727

**Closed by samhouts** 2019-02-06 19:31 UTC
Labels: t/enhancement ➕
