### ISSUE TITLE
[Bug] Issue Binding Entry Text

### ISSUE THREAD

**Issue by branch97** [xamarin/Xamarin.Forms#9713] opened 2020-02-25 22:15 UTC
### Description
The text in an Entry doesn't show up unless the entry is clicked on. This issue only occurs in UWP when the Entry text is bound to a value.

### Steps to Reproduce
1.  Bind the entry text to value
2.  Once the entry is displayed, click the entry to make the text appear

### Expected Behavior
Text automatically appears in the entry once it appears

### Actual Behavior
Text doesn't show in the entry until the entry is clicked

- Version with issue: 4.4.0.991640
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - UWP:  16299
- Affected Devices: All devices running UWP apps

### Workaround
No workaround found

![2020-02-25 16-11-43](https://user-images.githubusercontent.com/42125274/75292564-0ec55a80-57ea-11ea-8b07-7d0c4f1204e5.gif)

**Comment by jsuarezruiz** [comment] 2020-02-26 09:13
I have created a small example where I try to reproduce the problem but without success.

[Issue9713.zip](https://github.com/xamarin/Xamarin.Forms/files/4254530/Issue9713.zip)

<img width="874" alt="Captura de pantalla 2020-02-26 a las 10 09 41" src="https://user-images.githubusercontent.com/6755973/75329700-60b8bf80-5880-11ea-8018-e121e9c3c306.png">

Could you attach a repro sample?

**Comment by GalaxiaGuy** [comment] 2020-02-26 15:48
Sounds like https://github.com/xamarin/Xamarin.Forms/issues/8503

**Comment by samhouts** [comment] 2020-03-18 22:37
Duplicate of #8503

**Closed by samhouts** 2020-03-18 22:37 UTC
Labels: a/entry, p/UWP, s/needs-repro ❔, s/unverified, t/bug :bug:
