### ISSUE TITLE
[iOS] Editor with material visuals value binding not working on physical device

### ISSUE THREAD

**Issue by mkratsch** [xamarin/Xamarin.Forms#5500] opened 2019-03-08 12:43 UTC
### Description
Xamarin Forms 3.6.0.220655 & Xamarin.Forms.Visual.Material (I only tested iOS)
Using an editor with visual="Material" works on simulator but when deploying on a physical device the values entered in the editor will not be updated.
### Steps to Reproduce

1. use editor control in xaml
2. apply visual="Material" and Text={Binding ValueInModel}

### Expected Behavior
ValueInModel should change
### Actual Behavior
ValueInModel changes only in Simulator not on physical device
### Basic Information

- Version with issue:
- Platform Target Frameworks: 
  - iOS:  11.0 (12.1 has the same behavior)
- Nuget Packages: Xamarin Forms 3.6.0.220655 & Xamarin.Forms.Visual.Material
- Affected Devices: iPhone 7 and iPhone 8 Plus

**Comment by kingces95** [comment] 2019-03-08 20:23
Could you please supply a zipped up reproduction?

**Comment by mfow** [comment] 2019-03-14 17:18
I can repro on:
- Xamarin.Forms, Xamarin.Forms.Visual.Material 3.6.0.220655
- iOS 12.1.4
- iPhone XS Max

**Comment by samhouts** [comment] 2019-03-25 22:02
@mfow Are you able to provide us with a reproduction project? Thanks!

**Comment by ianvink** [comment] 2019-04-25 16:02
I'm getting the same issue on iOS devices. XF 3.6, running on a PC with VS 2019

Here's my Editor:
`			<Editor Placeholder="Enter a note"   Text="{Binding NoteText}" x:Name="NoteEditor" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"  IsVisible="{Binding IsLoading, Converter={StaticResource NegateBooleanConverter}}" ></Editor>`

and I set the Material in the App.xaml

			<Style
				TargetType="Editor"
				ApplyToDerivedTypes="true">
                <Setter Property="Visual">
                    <Setter.Value>
                        
                        <OnPlatform x:TypeArguments="IVisual"  iOS="Material"  Android="Material"/>
                    </Setter.Value>
                </Setter>
                <Setter
					Property="HorizontalOptions"
					Value="FillAndExpand" />
				<Setter
					Property="TextColor"
					Value="{ DynamicResource BaseTextColor }" />
			</Style>


If I set the Editor to Visual="Default" it works fine on physical devices.

XF 3.6 on VS 2019, PC

**Comment by ianvink** [comment] 2019-04-25 16:12
I have a repro project, but it's confidential. Let me know the email to send it to if you need it. @kingces95 or @samhouts

**Comment by PureWeen** [comment] 2019-04-27 01:45
@ianvink shneuvil at microsoft.com

**Comment by Goksly** [comment] 2019-05-07 16:06
We are getting this as well. Tried various combinations of switching the visual mode to default, or switching the underlying type from entry to editor and its only when the control type is editor and the visual is material that we experience the issue.

**Comment by samhouts** [comment] 2019-05-11 01:20
@Goksly  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Goksly** [comment] 2019-05-13 09:34
Just a simple project showing entry working as expected for default and material, and editor working as expected for default but not material. Note that, as per the purpose of this issue, it works fine on the simulator but not on a physical device.

[XamarinMaterialBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3172148/XamarinMaterialBug.zip)

To replicate, use the sliders to update the entry / editor values, and then amend the associated input control (values between 0 and 1). For all instances except the material editor the binding works as expected both ways. For the exception, slider updates the editor, editor doesn't update the slider.

**Comment by kingces95** [comment] 2019-05-22 01:42
WOOT! Confirmed.

**Comment by jamesmcmenamin** [comment] 2019-05-29 16:38
Are you sure this is a error.... If you set the slider to Mode=TwoWay it works just fine.

**Comment by Goksly** [comment] 2019-05-29 16:46
Surely the Visual property shouldn't change the behaviour? It works fine with default... so why would I need to change the binding mode if I go with material (I've not tried it - just making a statement)...

**Comment by jamesmcmenamin** [comment] 2019-05-29 16:55
Probably cause the default in material is oneway. either way it works in the Playground posted above.

Why is it with default you can do on appearing but with visual="material" it will crash the app... same issue different cupcake.

**Comment by bbenetskyy** [comment] 2019-06-17 11:56
Hi all, got the same bug with Xamarin.Forms 4.0.
Adding `Mode=TwoWay` at Text Binding also does not solve that.
When set `Visual="Default"` for Editor that it works, but looking weird, means that it's not looking like we need

**Comment by jeetendra18** [comment] 2019-06-25 04:30
Any news for this issue, I am facing the same issue on IOS device

**Comment by NunoBem** [comment] 2019-07-03 17:56
The bug remains in Xamarin.Forms 4.1.
Only works with Visual="Default", but it ruins the whole app experience.

**Comment by PureWeen** [comment] 2019-07-04 00:04
I can't recreate on my physical devices so someone else will need to run with this one

@kingces95  ?

**Comment by profteck** [comment] 2019-07-04 17:27
Any news on this issue - same happening with me on IPhone 7 with latest version of Xamarin.Forms and Material.

**Comment by gaocan1992** [comment] 2019-07-10 17:55
Observed this issue.

**Comment by arrteamgun** [comment] 2019-08-22 13:25
We have this bug too - still ain't fixed

**Comment by joehanna** [comment] 2019-08-23 05:50
Still happening in Xamarin Forms 4.2.0.709249

**Comment by RobertHedgate** [comment] 2019-08-26 11:53
For me it works sometimes, perhaps 1 in 10. Have a Editor in a modal and checking the text for empty/null when saving. About 1/10 I have text in the binding. If I remove visual=material it works all the time.

**Comment by Raystorm7** [comment] 2019-09-03 14:22
> Still happening in Xamarin Forms 4.2.0.709249

Same here.. this is very annoying :(

**Comment by NunoBem** [comment] 2019-09-03 16:39
> > Still happening in Xamarin Forms 4.2.0.709249
> 
> Same here.. this is very annoying :(

Unable to have a coherent Material app. Don't people use forms?

**Comment by PureWeen** [comment] 2019-09-03 16:41
@NunoBem if you use the Android X versions of the support libraries does that resolve?

https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/

https://www.nuget.org/packages/Xamarin.Google.Android.Material/1.0.0-preview02

**Comment by NunoBem** [comment] 2019-09-03 16:53
> @NunoBem if you use the Android X versions of the support libraries does that resolve?
> 
> https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/
> 
> https://www.nuget.org/packages/Xamarin.Google.Android.Material/1.0.0-preview02

That influence the IOS version? I will give it a try.

**Comment by NunoBem** [comment] 2019-09-03 16:54
> @NunoBem if you use the Android X versions of the support libraries does that resolve?
> 
> https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/
> 
> https://www.nuget.org/packages/Xamarin.Google.Android.Material/1.0.0-preview02

@PureWeen That influence the IOS version? I will give it a try.

**Comment by PureWeen** [comment] 2019-09-03 16:54
@NunoBem WAIT nm sorry I was thinking you were having this issue on Android :-/ Sorry about that

**Comment by NunoBem** [comment] 2019-09-03 16:59
@PureWeen Ok no problem. This is a bug back from Xamarin Forms 3.6.0.220655 and Xamarin.Forms.Visual.Material on a physical IOS device.

A binding on a Editor doesn't work properly with Material Design.

**Comment by marcojak** [comment] 2019-09-07 17:54
I have the same issue on iOS (Xamarin.Forms 4.2.0.709249)

I can confirm that using Visual="Default" fixes the issue.
It's not just the binding, if I try to directly access the "Text" property, it is usually null or not updated, for example I could write abcdef and sometimes Text is null and other times is something like abc.

**Comment by mindtheappsrl** [comment] 2019-09-10 16:36
> I can confirm that using Visual="Default" fixes the issue.

Me too, even without binding the problem is the same on iOS, if you set Visual="Default" everything woks fine

**Comment by matteopiccioni** [comment] 2019-09-11 15:28
Same problem here.
As added info I can say that if behind code you try to take the 'text' value of the editor object, the return value is null (only when Visual=Material)

**Comment by mzhukovs** [comment] 2019-09-27 10:24
Seeing the same thing almost pulled my damn hair out, should have googled sooner! Any ETA on a fix, or anyone have a suitable workaround in the meantime?

**Comment by kelvincwk** [comment] 2019-10-07 03:24
Any updates where we are at for this?

**Comment by PureWeen** [comment] 2019-10-14 17:45
For some reason none of these handlers are firing when this is deployed to a physical device
https://github.com/xamarin/Xamarin.Forms/blob/5d010511c6fc49fe185f010c17fa9249820ad3d2/Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs#L180

I tested a native Xamarin.IOS application and the events fire there so not sure yet why it's different for us :-/

**Comment by PureWeen** [comment] 2019-10-15 22:22
For now this should fix
https://github.com/xamarin/Xamarin.Forms/pull/8011

Here's the root of the problem being investigated by the iOS team
https://github.com/xamarin/xamarin-macios/issues/7235

**Comment by PureWeen** [comment] 2019-10-16 18:45
In the mean time if you want to fix this locally 

- Create a custom Renderer for material Editor
[assembly: ExportRenderer(typeof(Xamarin.Forms.Editor), typeof(CustomEditorRenderer), new[] { typeof(VisualMarker.Material) })]
- Override OnElementChanged
- And just store the TextView into a local variable on the class

That should stop the TextView from getting GC'd

**Comment by samhouts** [comment] 2019-10-17 19:09
closed by #8011

**Closed by samhouts** 2019-10-17 19:09 UTC
Labels: a/visual, e/3 :clock3:, in-progress, p/iOS 🍎, s/unverified, t/bug :bug:
