### ISSUE TITLE
Image CornerRadius Property

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3600] opened 2018-08-17 16:23 UTC
Hi,

Please add CornerRadius property to the Image instead of adding the image inside a Frame and set the Frame's CornerRadius value.

Thanks,
Jassim

**Comment by VladislavAntonyuk** [comment] 2018-08-17 18:37
You can use CircleImage nuget package

**Comment by AndreiMisiukevich** [comment] 2019-02-06 00:31
I think, it is much more better to add this property to VisualElement (or View).

**Comment by adrianknight89** [comment] 2019-04-14 00:26
I too would like to see this property for all visuals if possible. For now, @jrahma could use FFImageLoading and apply a RoundedTransformation to avoid using a frame which doesn't seem to work on iOS with images.

**Comment by samhouts** [comment] 2020-02-12 20:09
Duplicate of #1754

**Closed by samhouts** 2020-02-12 20:09 UTC
