### ISSUE TITLE
[Bug] Updating to latest packages breaks the VS 2017 build

### ISSUE THREAD

**Issue by omghb** [xamarin/Xamarin.Forms#7638] opened 2019-09-23 14:46 UTC
### Description
After updating the following packages of my Xamarin Forms App resulted in a broken build:
* Xamarin.Android.Support.* from 28.0.0.1 to 28.0.0.3
* Xamarin.Forms from 4.2.0.709249 to 4.2.0.815419
* Xamarin.Essentials from 1.3.0 to 1.3.1

The build worked in VS 2017 with the previous versions on all platforms.

### VS 2019 
Build is ok

#### UWP: 
Build is ok

#### iOS: 
```
MTOUCH : error MT2002: Failed to resolve "System.Collections.Generic.Stack`1" reference from "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" 
```

#### Android
```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Stack`1' (defined in assembly 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Stack`1
```

**Comment by MagicAndre1981** [comment] 2019-09-23 17:31
it was [already reported](https://github.com/xamarin/Xamarin.Forms/issues/7602)

**Comment by StephaneDelcroix** [comment] 2019-09-24 11:04
thanks @MagicAndre1981 . indeed, it's a dupe of #7602

**Closed by StephaneDelcroix** 2019-09-24 11:04 UTC
Labels: s/unverified, t/bug :bug:
