### ISSUE TITLE
[Bug] Label not rendered when placed on top of button with fast renderers enabled

### ISSUE THREAD

**Issue by rhouweling** [xamarin/Xamarin.Forms#6488] opened 2019-06-11 08:26 UTC
### Description
A label on top of a button does not render when FastRenderers_Experimental is enabled.

### Steps to Reproduce
When creating a badge we encountered this issue. In XAML, create the following:
`<Grid Padding="0">
    <Button BackgroundColor="blue" CornerRadius="22" WidthRequest="44" HeightRequest="44" HorizontalOptions="Center" VerticalOptions="Center"></Button>
    <Label Text="1" HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" Margin="0" />
</Grid>`
When running this displays a blue round button with a label with text "1" on top of the button. When enabling FastRenderers_Experimental in MainActivity the text no longer renders. When using a boxview instead of a button all is fine.

### Expected Behavior
The label with should appear on top of the button

### Actual Behavior
No text is rendered on top of the button, only the button is visible.

### Basic Information

- Version with issue: 3.4.0.1039999, 3.6.0.344457, 4.0.0.482894
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: v28.0.0.1
- Nuget Packages: default
- Affected Devices: all tested devices, Nokia 5.1, Nokia 6.1, Honor 10 and pixel_xl_pie emulator.

### Screenshots
![Screenshot_1560241517](https://user-images.githubusercontent.com/50869531/59256006-517edc80-8c33-11e9-8450-988df46d4691.png)

### Reproduction Link

[ReproApp.FastRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/3275436/ReproApp.FastRenderer.zip)

**Comment by jfversluis** [comment] 2019-06-11 09:35
Downloaded the reproduction project, no changes, and ran it on an emulator, seems to work fine on this one. Tried both API 27 and 28 with which I both cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/939291/59260269-973fa300-8c3b-11e9-823c-758c583b307c.png)

**Comment by rhouweling** [comment] 2019-06-11 09:43
Just switched mine to 27 and that seems to be fine, no rendering issue there. Switching back to 28 results in the bug again.

**Comment by samhouts** [comment] 2019-06-13 21:19
@PureWeen Any idea?

**Comment by PureWeen** [comment] 2019-06-13 21:31
@rhouweling have you updated to the latest version of 4.0? We only recently fixed this issue

It sounds like @jfversluis wasn't able to reproduce using the latest version

**Comment by rhouweling** [comment] 2019-06-14 06:12
I can confirm it is fixed in 4.0.0.497661. So this means we need to skip 3.6 entirely to prevent this issue and upgrade to 4.0.0.497661? Or will this bug also be fixed in a 3.6 version as well? We are not very keen on upgrading to 4.0 yet... Thanks guys!

**Comment by rhouweling** [comment] 2019-06-14 07:29
Looks like I made a mistake, it seems to have been fixed from version 4.0.0.482894. Is there any chance this will be fixed in version 3.6? We are not ready to go to Forms 4 yet.
Thanks for the quick responses and keep up the good work guys and girls ;)

**Comment by jfversluis** [comment] 2019-06-14 07:33
I don't think this will be fixed in 3.6 anymore unless @samhouts thinks otherwise. For now this issue is fixed then.

We probably do like to hear why you are not keen of upgrading to 4.0 yet. @davidortinau is probably interested in that. If there is anything we can do to support you in that area, please let us know!

**Closed by jfversluis** 2019-06-14 07:33 UTC
Labels: a/fastrenderers, p/Android, s/unverified, t/bug :bug:

**Comment by samhouts** [comment] 2019-06-17 17:51
@PureWeen Was this resolved by #6271? Should we port it to 3.6.0? Thanks!

**Comment by PureWeen** [comment] 2019-06-17 21:17
@rhouweling 

For now we're not going to port this back to 3.6.0 but there's a fairly easy workaround
The fix that @samhouts refers to sets the elevations in such a way that things will display correctly along the Z axis. So a quick way for you to resolve this in 3.6 is to set the elevation on the label so it's higher than the button

```XAML
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Xamarin.Forms.Sandbox.MainPage"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
             xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core" 
             ios:Page.UseSafeArea="true"
             >
    <ContentPage.Content>
        <Grid Padding="0">
            <Button BackgroundColor="blue" CornerRadius="22" WidthRequest="44" HeightRequest="44" HorizontalOptions="Center" VerticalOptions="Center"></Button>
            <Label android:VisualElement.Elevation="6"  Text="1" HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" Margin="0" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```


also can you elaborate on this please?
> We are not very keen on upgrading to 4.0 yet

We would like to resolve whatever is holding you up on upgrading to 4.0 if possible

**Comment by rhouweling** [comment] 2019-06-18 05:59
Thanks for the additional info and the workaround. The reason we won't upgrade to 4.0 yet is because of time. We need time to test the entire app after a major update and that time is just not available yet.

**Comment by tedlindstrom01** [comment] 2020-03-04 10:58
This is occuring again in 4.5.0.356 targeting android 9.
