### ISSUE TITLE
Xamarin.Forms with WPF build issue

### ISSUE THREAD

**Issue by dcuccia** [xamarin/Xamarin.Forms#13217] opened 2020-12-22 21:32 UTC
As previously described by @schnerring, there is still an issue with XamlC XFC0000 compilation errors for XF in WPF.

Environment:
* netcoreapp3.1 with WPF
* VS2019
* Windows 10
* Xamarin.Forms.Platform.WPF 4.8.0.1269

`Error		 : XamlC error XFC0000 : Cannot resolve type "Application".`

Repro: https://github.com/schnerring/XamarinWPFCompilationBug

I found a fix I don't understand [in this article](https://dev.to/krdmllr/setting-up-a-xamarin-forms-wpf-backend-on-net-core-109l) which I think is what @dfyx meant with removing the EmbeddedResource build action. I couldn't find anything about that in the official docs.

I added the fix to my repro code inside the csproj file and commented it:

```
<ItemGroup>
    <EmbeddedResource Remove="**/*.xaml" />
</ItemGroup>
```

As soon as you uncomment, the project compiles successfully.

_Originally posted by @schnerring in https://github.com/xamarin/Xamarin.Forms/issues/11101#issuecomment-678329339_

**Comment by mr5z** [comment] 2021-01-23 23:37
Still experiencing this on XF 5.0.0.1905

![image](https://user-images.githubusercontent.com/6318395/105617048-ee958580-5e16-11eb-99ad-36a0aae9758e.png)

**Comment by zaratul77** [comment] 2021-02-12 12:13
Did anybody solve this?

**Comment by cris-m** [comment] 2021-02-20 02:40
I am expecting this issues after updating to the latest Xamarin Form (5.0.0) in Visual Studio for Mac.
<img width="1748" alt="Screen Shot 2021-02-20 at 11 38 15" src="https://user-images.githubusercontent.com/29815096/108580787-67352680-7370-11eb-999d-53128427eb4a.png">

**Comment by cris-m** [comment] 2021-02-25 16:01
I think it is not a problem, since many experimental controllers and converters have been remove in ``Xamarin Form``  and placed in `` Xamarin Community Toolkit``.  [Here](https://docs.microsoft.com/en-us/xamarin/community-toolkit/) is the documentation about `` Xamarin Community Toolkit``

**Comment by cdytoby** [comment] 2021-03-06 22:31
Same issue here, and the solution which the author provided works.

It only happens on .NET Core version or .NET 5 version of WPF. .NET Framework WPF doesn't have this issue.

Also, I'm not sure if this is caused by Xamarin.Forms or not, because this issue appears as soon as WPF project is created without any modification.

**Comment by GeoDirk** [comment] 2021-05-28 13:25
Same problem that is only found when trying to compile the WPF .NET 5.0 application.  Running version Xamarin.Forms 5.0.0.2012

`Error : XamlC error XFC0000 : Cannot resolve type "Application".`

Was resolved with the author's solution.

**Closed** 2022-11-16 13:23 UTC
Labels: t/bug :bug:, p/WPF, s/unverified
