### ISSUE TITLE
[Bug] Cannot access a disposed object.Object name: GroupableItemsViewController`1'.

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#8582] opened 2019-11-20 15:20 UTC
### Description
I have a MasterDetailPage. The Detail Page Contains a Collection View Nested inside of a RefreshView

```
            <RefreshView IsRefreshing="{Binding Refresher.IsRefreshing}" Command="{Binding RefreshDataCommand}">
                <CollectionView x:Name="lstStockTakes" ItemsSource="{Binding StocktakeList}" SelectionChangedCommand="{Binding SelectListCommand}" SelectedItem="{Binding SelectedList}" SelectionMode="Single" >
```

The RefreshDataCommand gets executed:
```
        public ICommand RefreshDataCommand => new Command(async () =>
        {
            await getCompanyList();
            if (SelectedComapny != null)
            {
                await getStockTakeLists();
            }
            Refresher.RemoveFromRefresh("Refresh");
        });
```

```
        private async Task getCompanyList()
        {
            try
            {
                if (CompList == null || CompList.Count == 0)
                {
                    throw new Exception("test");
                    //CompList = await MainDataFunctions.GetCompanyListAsync();
                }
            }
            catch (Exception ex)
            {
                ShowError(ex);
                ((MasterDetailPage)Application.Current.MainPage).Detail = new HomePage();
                //Navigator.PresentAsNavigatableMainPage(new HomeViewModel(Navigator));
            }
        }
```

Using the above code the app crashes with:

{System.ObjectDisposedException: Cannot access a disposed object.Object name: 'GroupableItemsViewController`1'.  at Foundation.NSObject.get_SuperHandle () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/Foundation/NSObject2.cs:456   at UIKit.UICollectionViewController.get_CollectionView () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UICollectionViewController.g.cs:1101   at Xamarin.Forms.Platform.iOS.ItemsViewDelegator`2[TItemsView,TViewController].Scrolled (UIKit.UIScrollView scrollView) [0x00006] in <695eeca9e078498fa11f4895d0fa4d3f>:0   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65   at StockTake.iOS.Application.Main (System.String[] args) [0x00001] in C:\Xamarin Projects\Apps\StockTake\StockTake\StockTake.iOS\Main.cs:17 }

- Version with issue: 4.3.0.991211
- IDE: VS 2019 Pro 16.3.9
- Affected Devices: Tested on a Iphone 6 running IOS 12.4.2

**Comment by daves1992** [comment] 2019-11-20 15:59
I think I made have raised a duplicate of:
https://github.com/xamarin/Xamarin.Forms/issues/8308

**Comment by samhouts** [comment] 2019-11-25 19:55
Duplicate of #8308

**Closed by samhouts** 2019-11-25 19:55 UTC
Labels: a/collectionview, i/high, p/iOS 🍎, s/unverified, t/bug :bug:
