### ISSUE TITLE
Button shows artifact on click when it has background color on Android

### ISSUE THREAD

**Issue by MarcKammermann** [xamarin/Xamarin.Forms#8714] opened 2019-11-29 12:13 UTC
### Description
When a button gets a background color it shows a little square shape in the top left corner.
See this vid: https://vimeo.com/376347411
This happens to me on Android 7 and 8, Android 9 doesn't have this issue.

Can't be a fault of my code, I created a new solution and just inserted two buttons like in the video.
Code of xaml containing the buttons: 

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="TestApp.Views.AboutPage">

    <StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
        <Button Text="With Background"
                BackgroundColor="Green"
                VerticalOptions="Center"/>
        <Button Text="Without Background"
                VerticalOptions="Center"/>
    </StackLayout>
</ContentPage>

### Basic Information
- Version with issue: 4.2.0.709249
- IDE: VisualStudio 16.3.10
  - Android: 8.0, 7.0
- Affected Devices: Samsung Galaxy

### Screenshots
https://vimeo.com/376347411

**Comment by jfversluis** [comment] 2019-11-29 19:27
I'm going to assume that you are using Shell, in that case this is a duplicate. I will close this one, please track the progress and add your findings there. If you think this is a different problem from that one, please feel free to reopen.

**Comment by jfversluis** [comment] 2019-11-29 19:27
Duplicate of #8385

**Closed by jfversluis** 2019-11-29 19:27 UTC
