### ISSUE TITLE
Not able to change the "Entry text" alignment 

### ISSUE THREAD

**Issue by royaza** [xamarin/Xamarin.Forms#8266] opened 2019-10-28 09:00 UTC
### Description

After updating the xamarin forms, I can not change the entry text alignment to the center of the entry. 
### Steps to Reproduce

1. Update the Xamarin forms to 4.3
2.  HorizontalTextAlignment = TextAlignment.Center 
3. The text position is not changed, and it is still shown on the left instead of the center. 

### Expected Behavior

The text must appear in the center of the entry. 

### Actual Behavior

The text position is the left.
### Basic Information

- Version with issue: 4.3
- Last known good version: 4.2
- IDE: Visual Studio (MAC)
- Platform Target Frameworks: 
  
  - Android:  
10.0 - Q
- Android Support Library Version: 
- Nuget Packages: 28.0.0.3

**Comment by Happypig375** [comment] 2019-10-28 10:05
Duplicate of #7538

**Comment by jfversluis** [comment] 2019-10-28 10:07
Hey @royaza thank you for making us aware of this issue!

Like @Happypig375 already pointed out, this seems to be a duplicate. Please track the mentioned issue for further progress and add any information that might be relevant there.

Thanks!

**Closed by jfversluis** 2019-10-28 10:07 UTC
Labels: s/unverified, t/bug :bug:
