### ISSUE TITLE
[Bug] CollectionView Extra Space at bottom 

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#13216] opened 2020-12-22 17:52 UTC
### Description
When writing any collectionView Horizontal it adds extra space at bottom, and the only workaround it is to set the height of the collectionview, which is wrong, it should be dynamic 

Tested on Android using XF : 5 pre5

**Comment by rachelkang** [comment] 2020-12-23 00:35
Hi, @AhmedAbuelnour - thanks for submitting this issue! I'm closing as it's a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/6554 but we'll continue to keep our eye on it. Feel free to follow the convo there and add any further thoughts you may have to that thread!

**Closed by rachelkang** 2020-12-23 00:35 UTC
Labels: s/unverified, t/bug :bug:
