### ISSUE TITLE
[Bug] [iOS] RightToLeft flow direction doesn't work with Label

### ISSUE THREAD

**Issue by efhayati** [xamarin/Xamarin.Forms#8210] opened 2019-10-24 21:59 UTC
### Description
After upgrade to 4.3, the `Label `doesn't respect to RTL flow direction in iOS. 

### Steps to Reproduce

1. Set the `FlowDirection` property on `Label` (or on a page containing a `Label`) to `RightToLeft`.

### Expected Behavior
The `Label` should render text from Right

### Actual Behavior
The `Label` doesn't respect the RTL flow direction.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.910310
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: 9.0

**Comment by samhouts** [comment] 2020-08-13 22:51
Duplicate of #2447

**Closed by samhouts** 2020-08-13 22:51 UTC
Labels: 4.3.0, a/l10n, a/rtl, e/1 :clock1:, hackathon, i/regression, p/Android, p/iOS 🍎, t/bug :bug:
