### ISSUE TITLE
iOS: Cant use DataTemplateSelector as CollectionView.GroupHeaderTemplate

### ISSUE THREAD

**Issue by timahrentlov** [xamarin/Xamarin.Forms#8609] opened 2019-11-21 14:02 UTC
I'm in the process of migrating ListViews to CollectionsViews. When I use a DataTemplateSelector as CollectionView.GroupHeaderTemplate I get a "LoadTemplate should not be null" exception.

This seems to come from ElementTemplate.cs, method CreateContent(), where 

`
if (LoadTemplate == null)
   throw new InvalidOperationException("LoadTemplate should not be null");
if (this is DataTemplateSelector)
   throw new InvalidOperationException("Cannot call CreateContent directly on a DataTemplateSelector");
`

Could a "SelectTemplate" be missing?

**Comment by jfversluis** [comment] 2019-11-22 10:29
Hey @timahrentlov thanks for reporting this.

Is there any particular reason that you did not use the issue template?

I would like to know a little bit more about what version of Xamarin.Forms you're seeing this in, if it worked in a previous version and it would be totally amazing to get a reproduction project. Thanks!

**Comment by timahrentlov** [comment] 2019-11-22 11:18
Hi Gerald,

I’m working with a large customer repo. I’m unable to share this, or fill the Issue Template with information from this.

We’re using latest 4.3 stable where CollectionView is said to be stable. Hence we’ve commenced porting some of our ListViews to CollectionViews.


Tim Ahrentløv
Frozengnu ApS

**Comment by jfversluis** [comment] 2019-11-22 12:01
I understand that you can't share that whole project, but it would be great if you could extract the necessary bits into a minimal project.

This helps greatly with speeding up to pinpoint where the bug is exactly and how possibly to fix it. It also eliminates any possible external other factors in your code that might influence this behavior. That is why we ask for reproduction projects :)

Thanks

**Comment by MariovanZeist** [comment] 2019-11-25 09:44
@jfversluis 
I ran into the same issue and did some investigation.
The problem is in the Xamarin.Forms.Platform.iOS.GroupableItemsViewController class
in the UpdateTemplatedSupplementaryView function.

This function get's the group header or footer datatemplate, and then calls a cell.Bind override that does not check if the datatemplate is actually a DataTemplateSelector (code is around line 105)
hence the crash.

**Comment by jfversluis** [comment] 2019-11-25 13:08
Closing this one in favor of the linked one which describes the same issue but in a bit more detail.

**Comment by jfversluis** [comment] 2019-11-25 13:08
Duplicate of #8647

**Closed by jfversluis** 2019-11-25 13:08 UTC
Labels: a/collectionview, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
