### ISSUE TITLE
[Enhancement] Left-aligned ToolbarItems on Android & iOS

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1719] opened 2018-01-26 23:55 UTC
## Rationale

`ToolbarItem`s currently display aligned to the right on all platforms. There is no way to display a `ToolbarItem` on the left. This is useful for many designs, including completely customizing the back button on a `NavigationPage`.

## Implementation

Add new platform specific properties to `ToolbarItem`:

```csharp
public enum ToolbarItemPosition { Start, End }

ToolbarItem.On<Android>().ToolbarItemPosition = ToolbarItemPosition.Start;
ToolbarItem.On<iOS>().ToolbarItemPosition = ToolbarItemPosition.Start;
```

Renderers will need to be updated accordingly.

### Android

- `ToolbarItemPosition` will default to `End`.
- If the `ToolbarItemPosition` is set to `Start`, `ToolbarItem` will be displayed on the left side of the screen when in LTR mode and on the right side of the screen when in RTL mode. 

### iOS

See Android

### UWP

No change. This is not a supported paradigm for UWP, so it will not be affected.

## Implications for CSS

None

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that a `ToolbarItem`'s Position defaults to the right side of the screen, as is the expected behavior now.
2. We ensure that any Effects or Custom Renderers that may have been created to produce this behavior take precedence over any values that we set, to the best of our ability.

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Easy

See https://forums.xamarin.com/discussion/85097/left-toolbaritems-in-xamarin-forms for original proposal.

**Comment by netapau** [comment] 2018-01-28 17:34
Hi, i would like to see if i can deal with this issue

**Comment by dhaligas** [comment] 2018-02-08 17:09
@samhouts will this allow both left and right toolbar items? we need the ability to have both.

below is exactly what forms needs to allow

![image](https://user-images.githubusercontent.com/923696/35987099-7a920ca8-0cc0-11e8-91ce-2e93221fcd41.png)

**Comment by samhouts** [comment] 2018-02-08 17:27
@dhaligas Yes, that's the idea.

**Comment by jassmith** [comment] 2018-02-17 00:09
@netapau you still working on this?

**Comment by netapau** [comment] 2018-02-17 12:49
@jassmith 			
I think someone a little more experienced should take it.
I was able to advance to the creation of the enumeration and modification of ToolbarItem
Here are my questions: do you have to make new renderers?
Do we have to work at Page.cs?
For the first time I look in this code I can not advance anymore.

**Comment by jassmith** [comment] 2018-02-17 19:17
The answers are no and no to both, though the second would be ideally a yes for an optimal implementation. I have moved this back to the available for implementation column

**Comment by dhaligas** [comment] 2018-02-17 19:19
@jassmith i need this .. do I have to modify the NavigationPageRenderer to make this work?

**Comment by jassmith** [comment] 2018-02-17 19:31
@dhaligas the implementation of this for iOS is straightforward and similar on ANdroid/UWP

1) Implement the PlatformSpecific API as shown in the spec.

2) Go to https://github.com/xamarin/Xamarin.Forms/blob/6668ff6458b8587a39333ce1ca5fd6ae5f285a7e/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L1008 and modify such that there are now 3 lists. The `primaries` list needs to be split into two lists based on the whether it is "start" or "end". The "end" list goes into where it goes normally:

```charp
NavigationItem.SetRightBarButtonItems(primaries == null ? new UIBarButtonItem[0] : primaries.ToArray(), false);
```

and the start list would basically be a duplicate of that line of code, but instead calling `SetLeftBarButtonItems`

This is such an easy issue it will surely be picked up by the team or myself very soon now that its in the F100 list which gives us approval to do it.

**Comment by dhaligas** [comment] 2018-02-17 21:25
@jassmith the iOS one seems simple and I am able to do it without modifying the core.  But android seems like you have to get into the internals of NavigationPageRenderer to support this

**Comment by jfversluis** [comment] 2018-02-20 08:29
For Android it's basically the same as @jassmith describes, but then here I guess?

https://github.com/xamarin/Xamarin.Forms/blob/c18e85ee434d7bacb730215fecf15acc0230917f/Xamarin.Forms.Platform.Android/Platform.cs#L383

**Comment by dhaligas** [comment] 2018-02-20 18:19
@jfversluis on android there is the Toolbar.NavigationIcon that can be used to set the Left Toolbar Item but that is buried in the NavigationPageRenderer.  This only allows one item which is fine for left Left Toolbar Items the majority of the time

**Comment by jfversluis** [comment] 2018-02-20 19:30
@dhaligas I didn't really look into it, but NavigationIcon sounds like it can hold just one?

**Comment by jassmith** [comment] 2018-02-20 19:48
Upon further review I was too hasty with my statements about Android. The API will need to be modified to only allow one icon for Android and to make it clear its an override for the back button.

**Comment by dhaligas** [comment] 2018-02-23 15:54
@jassmith I have to do this now.  is there a way to hack this in on Android with a renderer or effect?

**Comment by smartprogrammer93** [comment] 2018-04-25 21:56
If there is a custom renderer we can write to do this, it would be optimal. i am in desperate need for it.

**Comment by pnda489** [comment] 2018-05-14 08:07
Is it possible to add options to set the Toolbaricon?

**Left, Middle, Right** ? It would be more easy to set an image icon of a company in the center of the Navbar or align it to the left Controlbutton (Back or Hamburger)

**Comment by Shaboo** [comment] 2018-05-22 14:53
their is a custom renderer for ContentPage in order to move toolbar items to the left [iOS only],
so, If using the same logic for TabbedRenderer in order to move toolbar items to left when using tabbedpage, the following behavior happened:

when the app first lunch, every thing is fine, but when navigate to other tab, the items on left duplicate on the right,

and till now I can't fix this issue, and I think the problem in these lines 

https://github.com/xamarin/Xamarin.Forms/blob/8ed7a287ed9a476bb61e47c11cc9a2d15d8b0526/Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs#L172-L176


I don't know exactly but please keep this in mind when implementing this feature

**Comment by jassmith** [comment] 2018-08-16 19:47
Learnings from the shell branch are that this will 100% not work as specced. We need to take the API back to the drawing board hear and make sure it reflects the actual capabilities of the platfomrs.

**Comment by xamarindevelopervietnam** [comment] 2019-01-02 14:41
any update for this enhancement?

**Comment by Osmosis311** [comment] 2019-01-15 00:08
Would love it if this can be made to happen, or at least if anyone has the CustomRenderer code for Android.  I've got pages where I need Save and Cancel buttons, and if the user, clicks Cancel, I need to show a confirmation that they really want to leave and lose unsaved data...

**Comment by minaairsupport** [comment] 2019-02-06 22:13
yea I think these different things, toolbar position is very important to release it as soon as possible

**Comment by smartprogrammer93** [comment] 2019-05-19 09:56
Any Idea if this will be implemented?

**Comment by TingtingAn** [comment] 2019-07-10 10:01
Any luck?

**Comment by decv86** [comment] 2019-08-29 21:06
Pls implementation!

**Comment by decv86** [comment] 2019-08-29 21:06
Pls implementation!

**Comment by YZahringer** [comment] 2019-10-24 08:06
I think UWP should also be supported: https://www.rudyhuyn.com/blog/2015/12/23/display-an-appbarbutton-on-the-left-side-of-a-commandbar/

**Comment by mackayn** [comment] 2020-02-19 10:19
This is something our UX designers are demanding for the iOS client (already did it in Android and UWP with style tweaks). Would be cool if it was built into the framework

**Comment by winterdouglas** [comment] 2020-02-27 08:25
I'm just in the need of it again :( Any updates on this one?

**Comment by jfversluis** [comment] 2020-02-27 09:33
Sorry to hear that @winterdouglas! I'm afraid not.

Although the initial spec still states this as easy, I don't think it is. From what I remember looking into it, iOS for example only allows 1 button on the left. And from Jasons comments it looks like it's not that easy on Android as well. Maybe the APIs changed meanwhile, that would be awesome, I'm happy to be proven wrong in this case :)

That would mean, in order to achieve this, we would have to create a fully customized Navigation bar/page ourselves which is a huge investment to get right. One alternative could be to use the TitleView as suggested. Or if you have any other suggestions to make this happen, I'm all ears.

**Comment by dionisoliveira** [comment] 2020-04-02 18:35
iOS solution.

[assembly: ExportRenderer(typeof(CustomBackButtonPage), typeof(CustomContentPageRenderer))]
namespace SMC.BackButton.iOS.Renderer
  public class CustomContentPageRenderer : PageRenderer
    {
        public static bool pushPage = false;
        public static bool closePage = false;

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            try
            {
                var page = (Element as IBackPage);
                
                var root = this.NavigationController.TopViewController;
           
                var icon = UIImage.FromBundle("ico_freq_off.png");
              
                root.NavigationItem.SetLeftBarButtonItem(new UIBarButtonItem(icon, UIBarButtonItemStyle.Plain, (sender, args) =>
                {
                    MessagingCenter.Send<object>(this, "ClosePAge");
                }), false);

               
               
            }
            catch (Exception e)
            {
                closePage = false;
                pushPage = false;
            }
        }

      


    }

**Comment by jfversluis** [comment] 2021-11-04 14:51
Hey everyone, thanks for all the input and effort here. This won't be able to make it into Xamarin.Forms anymore unfortunately. If it's something you're still interested in, make sure to see if it's on the roadmap for .NET MAUI or open an issue with a feature request and add all the details.

Thanks!

**Closed by jfversluis** 2021-11-04 14:51 UTC
Labels: t/enhancement ➕, proposal-open, F100, community-sprint, m/high impact :black_large_square:, a/toolbar

**Comment by mackayn** [comment] 2021-11-04 15:28
@jfversluis Given up on the native toolbar renderer completely. It's only useful for basic scenarios. On the last 4 commercials apps I've been involved with, we rolled out own toolbar as it was the way we could realize the designs. Allowing drawing like Flutter is the way to go.

**Comment by jfversluis** [comment] 2021-11-04 19:49
Thanks @mackayn! That seems definitely be the thing holding us back here and something we're keeping in mind.
