### ISSUE TITLE
Tabbed Page  title hide back shell navigation bar

### ISSUE THREAD

**Issue by eramrit78** [xamarin/Xamarin.Forms#7335] opened 2019-08-31 05:48 UTC
### Description
When use Tabbed Page with shell. The Tabbed Page Tab hide back of Shell Navigation bar.It should be show after navigation bar.It work before in Forms 4.1.But give issue in Forms 4.2. This issue come in content pages also. content page top part hide back shell navigation bar.

In Android
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:4.2
- Last known good version: 4.1
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![Annotation 2019-08-31 124110](https://user-images.githubusercontent.com/48124576/64060606-adcb1a00-cbec-11e9-85c8-0b8e355094ac.png)
![Screenshot_1567235148](https://user-images.githubusercontent.com/48124576/64060607-b02d7400-cbec-11e9-9f38-08c5780b6e6a.png)

**Comment by Luisney** [comment] 2019-09-02 19:25
Happens on content pages pushed into the navigation stac,, had to rollback to Forms 4.1

**Comment by James3UK** [comment] 2019-09-02 21:50
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/7240 ?

**Comment by samhouts** [comment] 2019-09-03 20:16
@eramrit78  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by BioTurboNick** [comment] 2019-09-03 20:35
@samhouts - it looks like the same issue as my #7240, and the work appears to be marked as "done" if I understand it correctly?

**Comment by eramrit78** [comment] 2019-09-03 22:44
Yes it same issue as #7240 7240

**Comment by samhouts** [comment] 2019-09-03 23:23
Thank you @BioTurboNick and @eramrit78 !!

**Comment by samhouts** [comment] 2019-09-03 23:23
Duplicate of #7240

**Closed by samhouts** 2019-09-03 23:23 UTC
Labels: a/shell :shell:, i/regression, p/Android, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
