### ISSUE TITLE
False Binding Error Messages on ListViews

### ISSUE THREAD

**Issue by DRAirey1** [xamarin/Xamarin.Forms#12845] opened 2020-11-13 22:12 UTC
Description
When using ListView, if you set its ItemsSource, the binding engine will report an error that parent (owner of the ItemsSource) couldn't bind to the properties in the templated control. This is a false error because the parent doesn't need to/shouldn't bind to an item in a list.  It does this for every item in the list, try unsuccessfully to bind to the parent, then successfully bind to the item in the list.  So if you have, say, 100 items in your list with 5 bindings per item, you end up with 500 errors in the debug window.

These false errors make it impossible to find actual errors when debugging.  In addition, This impacts performance because you're attempting 500 binding operations on the parent of the list for no good reason (as in the example above) before you find the right view model when you could have done it right the first time.

Steps to Reproduce
Build the application according to this tutorial: [https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/listview/?tabs=vswin](url)
Expected Behavior
The app works. No error in the VS Output window.

Actual Behavior
The app works but we have the following in the debug window:

> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'ImageUrl' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Image.Source'
> Binding: 'Name' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> Binding: 'Location' property not found on 'App1.MainPage', target property: 'Xamarin.Forms.Label.Text'
> 

Basic Information
Version with issue: 4.8.0.1687
IDE: Visual Studio 2019 Windows
Platform Target Frameworks: UWP, iOS, Android

**Comment by MitchBomcanhao** [comment] 2020-11-13 22:22
FYI I've logged a similar issue quite some time ago https://github.com/xamarin/Xamarin.Forms/issues/10437

**Comment by rachelkang** [comment] 2020-11-13 22:37
Hi, @DRAirey1 - thanks for submitting this issue. As @MitchBomcanhao mentioned, this is a duplicate of #10437 so I'm closing this issue now.

**Closed by rachelkang** 2020-11-13 22:37 UTC
Labels: s/unverified, t/bug :bug:

**Comment by DRAirey1** [comment] 2020-11-13 22:53
Why did you remove my problem report when it has a simple repo.  There is no repo in issue [https://github.com/xamarin/Xamarin.Forms/issues/10437](#10437).
