### ISSUE TITLE
Xamarin.Forms 3.1 , OnAppearing is not fired starting from second page 

### ISSUE THREAD

**Issue by Legolas87** [xamarin/Xamarin.Forms#3215] opened 2018-07-04 14:22 UTC
### Description
[App24.zip](https://github.com/xamarin/Xamarin.Forms/files/2163502/App24.zip)

The example is attached.

Issue exists on Android only.

**Comment by opcodewriter** [comment] 2018-07-04 16:31
@Legolas87 Dude, at least bother to say which platform has this problem...

**Comment by Legolas87** [comment] 2018-07-04 17:53
Oh, I just updated, it is not working..., Can you please run also on real device?

**Comment by hartez** [comment] 2018-07-05 15:34
Confirmed running on a Galaxy Tab S3; swiping to new pages in the CarouselPage does not fire the Appearing event for those pages on Android.

**Comment by Legolas87** [comment] 2018-09-18 09:50
why this bug is not fixed in this release? :(

**Comment by Legolas87** [comment] 2018-10-08 06:32
still waiting...

**Comment by AndreiMisiukevich** [comment] 2018-10-30 20:42
@Legolas87 
I tried to switch between pages and it didn't fire OnAppearing on iOS, as you can see (breakpoint and output). But it fired OnAppearing twice on app start (what is wrong from my point of view)
![car](https://user-images.githubusercontent.com/10124814/47749016-36132280-dc9d-11e8-8224-b9ab1633ed8b.gif)

**Comment by Legolas87** [comment] 2018-10-31 13:14
nothing's wrong here.. ios renders two pages for start, then u must add new page before swipe to see onapperaring fire

**Comment by AndreiMisiukevich** [comment] 2018-10-31 13:18
@Legolas87 from my point of view it should raise OnAppearing, when I really see the page and OnDisapparing, when it goes out. Does it make sense?) I think yes.

Btw, as for carousel.. i propose to try this one https://github.com/AndreiMisiukevich/CardView

As I see, Xamarin team are keen to refuse using CarouselPage and force developers to use CarouselView instead. You can try that one (ItemAppearing, ItemDisappearing work properly there)

**Comment by AndreiMisiukevich** [comment] 2018-11-05 14:23
@Legolas87 it isn't related to that plugin :) 
It's external package https://github.com/luberda-molinet/FFImageLoading

So, you can use Xamarin.Forms.Image instead

**Comment by Legolas87** [comment] 2018-11-05 14:30
@AndreiMisiukevich  it looks good :) did you try to use it with heavy views and can we dynamically add new pages?

**Comment by AndreiMisiukevich** [comment] 2018-11-05 15:51
@Legolas87 1) yes, now there is a PR for fixing heavy views for Android. iOS works fine
2) yes, we can. Use observable collection ;)

**Comment by Legolas87** [comment] 2018-11-09 08:00
![new bitmap image 5](https://user-images.githubusercontent.com/3896306/48250165-ce847200-e416-11e8-9d74-604881ac833e.jpg)

@AndreiMisiukevich  found a bug in uwp and where is right and lift arrows that uwp's FlipView has
https://csharpcorner-mindcrackerinc.netdna-ssl.com/article/how-to-use-flipview-control-in-universal-application-development-with-xaml-and-c/Images/image008.png

**Comment by AndreiMisiukevich** [comment] 2018-11-09 08:05
@Legolas87 could you please create bug with all info (including sample) on my github project?
Unfortunately, i don't have windows PC.. UWP is supported by community contributors. Hope somebody will help to solve it :)

**Comment by Legolas87** [comment] 2018-11-13 06:41
Anybody, somebody from Xamarin, please fix this bug

**Comment by Legolas87** [comment] 2018-11-21 09:00
@samhouts   why the hell you are not fixing this bug?

**Comment by samhouts** [comment] 2018-11-21 17:41
duplicate of #2951

**Closed by samhouts** 2018-11-21 17:41 UTC
Labels: e/2 :clock2:, p/Android, t/bug :bug:
