### ISSUE TITLE
[Bug] GroupFooterTemplate is shown on iOS even if template not is defined

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#8632] opened 2019-11-23 19:59 UTC
### Description
GroupFooterTemplate is shown on iOS even if template not is defined. Works fine on Android.

### Steps to Reproduce

1. Create a CollectionView
2.  Set IsGrouped to true
3. Define a GroupHeaderTemplate
4. Run the app on iOS

### Expected Behavior
Group footer should not be visible.

### Actual Behavior
Group header shows namespace and class name as string, see attached screenshot

### Basic Information

- Version with issue:
- IDE: Visual Studio for Mac 8.3.10 (build 2)
  - iOS:  13.6.0.12
  - Android: 10.0.6.2

- Nuget Packages: 4.3.0.991211

### Screenshots

![Simulator Screen Shot - iPhone 11 - 2019-11-23 at 20 50 52](https://user-images.githubusercontent.com/6691971/69484424-5b884680-0e33-11ea-960d-42afb48b5ebf.png)

### Reproduction Link

https://github.com/dhindrik/Xamarin.Forms-Projects/tree/weather-chapter/Chapter07

**Comment by jfversluis** [comment] 2019-11-23 20:33
Thanks for reporting @dhindrik ! 

There is already an issue and for this. I’m closing this one, please follow the progress there. Thanks!

**Comment by jfversluis** [comment] 2019-11-23 20:33
Duplicate of #8228

**Closed by jfversluis** 2019-11-23 20:33 UTC
Labels: s/unverified, t/bug :bug:
