### ISSUE TITLE
[Enhancement] Add StepValue to Slider

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6185] opened 2019-05-13 11:55 UTC
## Summary
In certain scenarios the slider value is required in  steps. So StepValue can cover this. 

## API Changes
Add new Property : StepValue

## Intended Use Case
In one of my projects the slider Value needs to be increased by 50 with every drag step. Lots of time a whole number is required in value.

**Comment by toomasz** [comment] 2019-05-14 13:54
Good idea, I also needed it so i had to create custom renderer :(

**Comment by HobDev** [comment] 2019-05-15 06:55
I manage to get stepvalue functionality by adding some code in the code behind:
```
public void OnSliderValueChanged(object sender, ValueChangedEventArgs e)
      {
                    var newStep = Math.Round(e.NewValue / 50);
                   slider.Value = newStep * 50;
            }
        }
```
Thus the slider add 50 with every step.

**Comment by charlesroddie** [comment] 2019-09-03 10:02
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3351

**Comment by jfversluis** [comment] 2021-11-30 13:56
Duplicate of #3351

**Closed by jfversluis** 2021-11-30 13:56 UTC
Labels: t/enhancement ➕, proposal-open
