### ISSUE TITLE
Command Binding for a Switch Behavior doesn't work when wired in a DataTemplate

### ISSUE THREAD

**Issue by IoTFier** [xamarin/Xamarin.Forms#9954] opened 2020-03-13 09:02 UTC
### Description
I am wiring an EventToCommandBehavior (via prism mvvm) to the toggled event of a switch used in a DataTemplate serving itemTemplate of a listview. The binding source of the Command is of type RelativeSource defined using x:Type that points to the viewmodel of the page.
But, getting following exception.
{System.InvalidOperationException: Operation is not valid due to the current state of the object.
at Xamarin.Forms.Binding.ApplyRelativeSourceBinding (Xamarin.Forms.BindableObject targetObject, Xamarin.Forms.BindableProperty targetProperty) [0x00023] in d:\a\1\s\Xamarin.Forms.Core\Binding.cs:147 }

The same command when wired via EventToCommandBehavior to a switch in a standalone Stacklayout works just fine.

Do you think this [github #9610](https://github.com/xamarin/Xamarin.Forms/issues/9610) issue is also applicable in my scenario ?
I would appreciate your thoughts and a working sample as per the solution suggested in #9610.
Thank you.

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
A command defined in the contentpage's view model to get wired to the switch defined in an DataTemplate of a ListView.

### Actual Behavior
Throws error - "**{System.InvalidOperationException: Operation is not valid due to the current state of the object.  
at Xamarin.Forms.Binding.ApplyRelativeSourceBinding (Xamarin.Forms.BindableObject targetObject, Xamarin.Forms.BindableProperty targetProperty) [0x00023] in d:\a\1\s\Xamarin.Forms.Core\Binding.cs:147 }**"

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 16.4.6
- Platform Target Frameworks: XF 4.5 latest stable
  - iOS: 11.3
  - Android: 8.1 and above
  - UWP:  n/a
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/26844611/76605415-6ba95c00-64de-11ea-9003-ec0e4e40f073.png)
![image](https://user-images.githubusercontent.com/26844611/76605712-ebcfc180-64de-11ea-8e27-a12366cf5a32.png)

**Comment by StephaneDelcroix** [comment] 2020-03-13 12:43
duplicate of #9610

**Closed by StephaneDelcroix** 2020-03-13 12:43 UTC
Labels: s/unverified, t/bug :bug:

**Comment by IoTFier** [comment] 2020-03-13 14:24
Hi @davidortinau,  @StephaneDelcroix , @pauldipietro , @samhouts - 
Why this issue is closed before getting any response to my request in the issue? Please ?
This is not appreciated.

The explanation of the @StephaneDelcroix in the #9610 is too theoretical without any sample solution. 

Please reopen this issue. I would appreciate your help.

Thank you
