### ISSUE TITLE
[Bug] IOS Label text alignment in RTL

### ISSUE THREAD

**Issue by vrijil-NMC** [xamarin/Xamarin.Forms#9447] opened 2020-02-06 06:04 UTC
### Description

In RTL, Arabic text for the Label is not working. in both FlowDirection (RTL or LTR) it is aligned in the left. it happens only in iOS.

### Steps to Reproduce

1. HorizontalOptions is "FillAndExpand"
2. HorizontalTextAlignment is "Start"
3.  FlowDirection is RTL
4. and the Label Text is Arabic
 

### Expected Behavior

In RTL Mode, Text should be aligned in the right.

### Actual Behavior

In both mode (RTL or LTR), Text is aligned in the left

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991537
- Last known good version: Xamarin.Forms 4.2.0.910310
- IDE:  Version: 6.10.0.17 (Visual Studio Community)
             Version 8.4.4 (build 91)

- Platform Target Frameworks:  
  - iOS:  Version: 13.10.0.17 (Visual Studio Community)
  - Android: Version: 16.4.0.10

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All iOS Devices

**Comment by AmrAlSayed0** [comment] 2020-02-06 07:32
This is most likely a duplicate of #9046 .

**Comment by samhouts** [comment] 2020-02-06 18:10
Duplicate of #9046

**Closed by samhouts** 2020-02-06 18:10 UTC
Labels: a/rtl, p/iOS 🍎, s/unverified, t/bug :bug:
