### ISSUE TITLE
Shell TitleView Not Working in iOS 16 [Bug]

### ISSUE THREAD

**Issue by mmholtman** [xamarin/Xamarin.Forms#15515] opened 2022-08-18 13:37 UTC
### Description
Shell content is not visible within a TitleView when testing against iOS 16.

https://github.com/mmholtman/xamarinios16bug.git

### Steps to Reproduce

1. Download xCode 14 beta & get iOS 16 simulators
2. Create a test Flyout App in Xamarin Forms 
3. Add a label within a <Shell.TitleView> on a XAML View.

### Expected Behavior
The title is visible on the view

### Actual Behavior
The title is not visible on the view

### Basic Information

- Version with issue: iOS 16 beta 
- Last known good version: any iOS version other than 16
- Platform Target Frameworks: 
  - iOS: 16
- Affected Devices: iOS 16 devices

**Comment by jfversluis** [comment] 2022-08-23 08:37
Duplicate of #15512

**Closed by jfversluis** 2022-08-23 08:37 UTC
