### ISSUE TITLE
GestureRecognizer on cell template causes iOS crash when using ObservableCollection

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#1904] opened 2018-02-16 19:31 UTC
### Description
A custom cell template with a GestureRecognizer attached causes iOS crash when using ObservbableCollection

### Steps to Reproduce

Use attached sample program:

1. Launch sample app
2. Verify items are loaded after 3 seconds
3. Click the Fav button on the right to verify it prints out debug information to console
4. Click Refresh toolbar button
5. Crash!

### Expected Behavior
No crash

### Actual Behavior
Crash:

```
Object reference not set to an instance of an object
    at Xamarin.Forms.Platform.iOS.EventTracker.LoadRecognizers () [0x0005d] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.EventTracker.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs e) [0x0004e] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x0002c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.FrameRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x00000] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00118] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers (Xamarin.Forms.Element newElement) [0x0008c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) [0x00080] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00050] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) [0x0001c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x0002c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00118] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.ListViewRenderer+UnevenListViewDataSource.CalculateHeightForCell (UIKit.UITableView tableView, Xamarin.Forms.Cell cell) [0x00035] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.ListViewRenderer+UnevenListViewDataSource.GetEstimatedRowHeight (UIKit.UITableView table) [0x0008c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.ListViewRenderer.UpdateEstimatedRowHeight () [0x0006c] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.ListViewRenderer.UpdateItems (System.Collections.Specialized.NotifyCollectionChangedEventArgs e, System.Int32 section, System.Boolean resetWhenGrouped) [0x000bc] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Platform.iOS.ListViewRenderer.OnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in <13d193f5a21b4e309afc67e0a5508db5>:0 
    at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:771 
    at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnProxyCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e, System.Boolean fixWindows) [0x0001a] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:981 
    at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnProxyCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:968 
    at Xamarin.Forms.ListProxy.OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Core\ListProxy.cs:233 
    at Xamarin.Forms.ListProxy+<>c__DisplayClass33_0.<OnCollectionChanged>b__0 () [0x00018] in D:\agent\_work\1\s\Xamarin.Forms.Core\ListProxy.cs:206 
    at Xamarin.Forms.ListProxy.OnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x000a0] in D:\agent\_work\1\s\Xamarin.Forms.Core\ListProxy.cs:225 
    at Xamarin.Forms.ListProxy+WeakNotifyProxy.OnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00031] in D:\agent\_work\1\s\Xamarin.Forms.Core\ListProxy.cs:394 
    at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:288 
    at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:351 
    at System.Collections.ObjectModel.ObservableCollection`1[T].InsertItem (System.Int32 index, T item) [0x00024] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/System/compmod/system/collections/objectmodel/observablecollection.cs:219 
    at System.Collections.ObjectModel.Collection`1[T].Add (T item) [0x00020] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/referencesource/mscorlib/system/collections/objectmodel/collection.cs:67 
    at EnergyAlert.Pages.ArticlesPage+<LoadNextPage>d__69.MoveNext () [0x00252] in /TFS/Mobile/Applications/EnergyAlert/EnergyAlert.Shared/Pages/ArticlesPage.cs:431 
```
### Basic Information

- Version with issue:
XF 2.4+
- Last known good version:
last XF 2.3.X

### Reproduction Link

[TestRecognizerCrash.zip](https://github.com/xamarin/Xamarin.Forms/files/1732563/TestRecognizerCrash.zip)

**Comment by SamuelDebruyn** [comment] 2018-03-09 15:39
Did you find a workaround?

**Comment by woutermeuwis** [comment] 2018-03-09 15:53
Workaround --> A button with transparent colors and an image set

**Comment by samhouts** [comment] 2018-03-10 02:13
I believe this is a duplicate of #1567. Confirmed that PR #1569 fixes this issue.

**Closed by samhouts** 2018-03-10 02:13 UTC
Labels: i/critical, i/regression, p/iOS, t/bug

**Comment by zoli13** [comment] 2018-04-09 08:33
Sample to reproduce: https://github.com/xamarin/Xamarin.Forms/issues/1333#issuecomment-377153224

**Comment by gsgou** [comment] 2020-01-06 10:10
happens again withGestureRecognizers attached on Images:

"  at Xamarin.Forms.Platform.iOS.EventTracker.LoadRecognizers () [0x00059] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\EventTracker.cs:578 \n  at Xamarin.Forms.Platform.iOS.EventTracker.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs e) [0x0004e] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\EventTracker.cs:646 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x00020] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs:369 \n  at Xamarin.Forms.Platform.iOS.ViewRenderer`2[TView,TNativeView].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\ViewRenderer.cs:128 \n  at Xamarin.Forms.Platform.iOS.ImageRenderer.<>n__0 (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) <0x11418afc0 + 0x0005a> in <b598fe3406fe4a7a9d7aa402bf8a0ef8>:0 \n  at Xamarin.Forms.Platform.iOS.ImageRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x000ad] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\ImageRenderer.cs:75 \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 \n  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/Foundation/NSAction.cs:178 "

i will add a sample at a later time that reproduces this one.

**Comment by michaelstonis** [comment] 2020-02-13 05:15
I don't believe that this has been resolved. I am still experiencing the same issue when attaching a tap gesture to an Image, BoxView and custom control (backed via SKFormsView) on iOS using Xamarin.Forms version 4.4.0.991537.
