### ISSUE TITLE
PushModalAsync not modal on WPF

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3261] opened 2018-07-10 12:07 UTC
On WPF, when a modal page is invoked like this:

``` c#
sourcePage.Navigation.PushModalAsync(new NavigationPage(modalRoot));
```

The resulting page is not modal. It has a back button, and the toolbar in the navigation page is not displayed, which is opposite of the expected results.

Xamarin.Forms.Platform.WPF 3.1.0.583944

**Comment by pauldipietro** [comment] 2018-07-10 13:57
Described behavior confirmed using 3.1

**Comment by mohachouch** [comment] 2018-07-10 17:47
It is a modal page but I still put the back button. I can delete the back button. 

But I confirm that the navigation bar is missing in the modals pages

**Comment by vinnivan** [comment] 2019-02-11 22:29
Any updates on this one? 
I have a couple of modal settings dialogs with buttons on the toolbar to apply changes - without the toolbar the dialogs obviously don't work. 
Thanks for your work on the WPF!
Xamarin Forms v3.5.0.12952

**Comment by woody3k** [comment] 2019-05-21 02:56
Dug into this very briefly to understand the current behaviour. It looks like when a page is pushed modally, it triggers the window navigation bar to synchronize (FormsWindow.SynchronizeAppBar). However this attempts to synchronize to the first visual child page (which will probably be the topmost page of the main window's root page), and doesn't consider pages that might have been add later (modal pages).

**Comment by vinnivan** [comment] 2020-01-03 00:06
I have this fixed and am working on a pull request.  As mentioned by woody3k it was syncing to the wrong FormsPage- but then also the PART_ModalContentControl was being displayed over the navigation bar.

**Comment by mhrastegary77** [comment] 2020-04-22 12:05
Still no navigation bar on modal pages for WPF :(

**Comment by samhouts** [comment] 2020-11-05 23:40
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by breyed** [comment] 2020-11-10 19:29
Yes, it's still an issue.

**Comment by jfversluis** [comment] 2022-11-16 13:06
I think it's highly unlikely this will be fixed during the lifetime that Xamarin.Forms still has. If this is still important to you, please consider open a PR for it. Thanks!

**Closed by jfversluis** 2022-11-16 13:06 UTC
Labels: t/bug :bug:, p/WPF, e/4 :clock4:
