### ISSUE TITLE
[Bug] [iOS] Xamarin Hot Restart issue: TapGestureRecognizer doesn't work on iOS

### ISSUE THREAD

**Issue by avorobjovs** [xamarin/Xamarin.Forms#10240] opened 2020-04-07 12:56 UTC
### Description

I try to start the Xamarin.Forms app for iOS from the Windows Visual Studio as it is described in your documentation
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart

But I found that there is a bug. The TabGestureRecognizer doesn't work if the iOS app is started from the Windows Visual Studio.

I provide a small demo app for this issue demonstration. 
If I build and start it from the Azure DevOps (Hosted macOS -> App Center), then the TabGestureRecognizer works as expected. 
But if I build and start it from the Visual Studio for Windows with the Xamarin Hot Restart, then the TabGestureRecognizer doesn't work at all. Neither the Command nor the Tapped event handler is reacted on a tapping.

### Basic Information

Windows 10 Version 1909 (OS Build 18363.720)

Microsoft Visual Studio Enterprise 2019
Version 16.5.2
VisualStudio.16.Release/16.5.2+29926.136

Xamarin 16.5.000.528 (d16-5@2b54082)
Xamarin.iOS and Xamarin.Mac SDK 13.16.0.11 (aa73e41)
Xamarin.Forms 4.4.0.991265

Device: iPhone 7 Plus
iOS version 13.4

### Reproduction Link

Demo app source code is provided

[XamarinHotRestartIssue_DemoApp_Source.zip](https://github.com/xamarin/Xamarin.Forms/files/4444406/XamarinHotRestartIssue_DemoApp_Source.zip)

Demo app screen recording is provided

[Xamarin_Hot_Restart_issue_ScreenRecording.zip](https://github.com/xamarin/Xamarin.Forms/files/4444414/Xamarin_Hot_Restart_issue_ScreenRecording.zip)

**Comment by SunnyMukherjee** [comment] 2020-04-07 13:32
https://github.com/xamarin/Xamarin.Forms/issues/10162

**Comment by rmarinho** [comment] 2020-04-07 15:39
Duplicated, we are releasing a hotfix for Xamarin.IOS

**Comment by samhouts** [comment] 2020-04-07 15:39
Duplicate of #10162

**Closed by rmarinho** 2020-04-07 15:39 UTC
Labels: s/unverified, t/bug :bug:
