### ISSUE TITLE
Context actions in ListView for android should improve

### ISSUE THREAD

**Issue by GovardhanNag** [xamarin/Xamarin.Forms#8068] opened 2019-10-17 14:18 UTC
## Summary
Please enhance the Context actions interface in Android as similar to that of iOS.
When it comes to iOS, its just perfect in using this Context Action, but in android its some what annoying with the UI design, if it's implemented similar to that of iOS then we would be very grateful.

**Comment by samhouts** [comment] 2019-10-17 20:55
@GovardhanNag Can you be more explicit about how you would like Context Actions to behave on Android? Thanks!

**Comment by GovardhanNag** [comment] 2019-10-18 09:27
@samhouts 
Thanks for replying,
Currently the Context Action in android looks like this:
![image](https://user-images.githubusercontent.com/8640402/67082413-66e3b480-f199-11e9-9733-d859aa55e6cc.png)
But I would like to see Context Action similar to this. The below screen shot is an example of iOS device, but I'm expecting Context Action functionality to work similar to that of iOS.
![image](https://user-images.githubusercontent.com/8640402/67082589-b75b1200-f199-11e9-8806-940eba37e3da.png)

**Comment by samhouts** [comment] 2019-10-18 16:17
Duplicate of #3171

**Closed by samhouts** 2019-10-18 16:17 UTC
Labels: a/listview, p/Android, proposal-open, t/enhancement ➕
