### ISSUE TITLE
[Bug] MediaElement [Android] Doesn't resize on rotation

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#9875] opened 2020-03-07 00:50 UTC
### Description

Given the following code:
```xml
  <Grid CascadeInputTransparent="True">
        <Grid.GestureRecognizers>
            <TapGestureRecognizer Tapped="OnTapGestureRecognizerTapped"/>
        </Grid.GestureRecognizers>
        <MediaElement
            x:Name="MediaElementVideo"
            Aspect="AspectFit"
            AutoPlay="False"
            BackgroundColor="{DynamicResource WindowBackgroundColor}"
            HorizontalOptions="FillAndExpand"
            MediaOpened="MediaElementVideo_MediaOpened"
            ShowsPlaybackControls="True"
            Source="{Binding VideoUrl}"
            VerticalOptions="FillAndExpand" />

        <ImageButton Clicked="Button_Clicked"
                     Margin="12"
                     BackgroundColor="{DynamicResource WindowBackgroundColor}"
                     CornerRadius="15"
                     WidthRequest="30"
                     HeightRequest="30"
                     Source="{StaticResource CloseIcon}"
                     HorizontalOptions="End"
                     VerticalOptions="Start"
                     x:Name="CloseButton"/>
    </Grid>
```

When you rotate the device the media on Android doesn't resize. Not sure how to force it to update.

### Steps to Reproduce

1. Run code above.
2. 
3. 

### Expected Behavior
Resizes to fit aspect.

### Actual Behavior
Stays the original
### Basic Information

- Version with issue: 4.6.x

### Screenshots

![image](https://user-images.githubusercontent.com/1676321/76132945-6cb42800-5fca-11ea-8f1a-238e00513bfe.png)

![image](https://user-images.githubusercontent.com/1676321/76132953-763d9000-5fca-11ea-85c0-db808f324ceb.png)

Interestingly the playback controls are spanning, it is just the video not updating
![image](https://user-images.githubusercontent.com/1676321/76132961-85bcd900-5fca-11ea-83fe-8f3da833c1e2.png)

**Comment by hartez** [comment] 2020-03-07 01:08
Duplicate of #9805

**Comment by jamesmontemagno** [comment] 2020-03-07 03:41
Might be worth renaming #9805 :)

**Closed** 2020-03-07 03:41 UTC
Labels: a/mediaelement, e/5 :clock5:, p/Android, t/bug :bug:

**Comment by Ariosi** [comment] 2021-03-01 08:42
Hi, I have this bug too. any changes? 
can't find #9805!!!!!!!
