### ISSUE TITLE
[Bug] ToolbarItem Order property ignored

### ISSUE THREAD

**Issue by Darlingtone** [xamarin/Xamarin.Forms#6127] opened 2019-05-08 10:59 UTC
### Description
Then Order property of ToolbarItem is totally ignored, the item is always displayed as primary even when set to secondary
 
### Steps to Reproduce
1.  Create a new XF project using the Shell template
2.  On a ContentPage add  ToolbarItem and set Order to secondary
3.  Run on Android device 

### Expected Behavior
Items with order set to primary show on navigation bar while items with order set to secondary shows as a pop up menu when the 3-dots icon is tapped

### Actual Behavior
All ToolbarItem show up on the Navigation bar regardless of their order settings, the 3-dots icon don't even show

### Basic Information

- Version with issue: Xamarin.Forms  4.0.0.394984-pre10
- IDE: Visual Studio Community 2019

**Comment by kingces95** [comment] 2019-05-22 01:30
Would you mind attaching a zipped reproduction?

**Comment by Darlingtone** [comment] 2019-05-22 06:24
Here is a GitHub repo [XamToolbarDemo](https://github.com/Darlingtone/XamToolbarDemo)

This is a just the default VS 2019 Xamarin.Forms App template I only more Toolbar items abd set their Order property to Secondary

**Comment by marcellangmaier** [comment] 2019-05-28 07:51
Experienced the same behaviour.

**Comment by anotherlab** [comment] 2019-06-13 16:35
I'm experiencing the same behavior on Android & iOS.

VS 2019
XF 4.0.0.482894

**Comment by marcellangmaier** [comment] 2019-06-20 18:35
same with
XF 4.1.0.496342-pre2

**Comment by eramrit78** [comment] 2019-07-12 13:10
same issue i have.
in XF 4.1

![Annotation 2019-07-12 184004](https://user-images.githubusercontent.com/48124576/61130553-88ffd380-a4d4-11e9-851f-448433b719b2.png)
[safebuilding.pdf](https://github.com/xamarin/Xamarin.Forms/files/3386516/safebuilding.pdf)
[nonobj.pdf](https://github.com/xamarin/Xamarin.Forms/files/3386517/nonobj.pdf)

**Comment by Munde** [comment] 2019-08-22 15:39
Experiencing the same
![screenshot-1566484382764](https://user-images.githubusercontent.com/2358895/63528759-33273e00-c50c-11e9-9514-5e240921e39c.jpg)

**Comment by edupxavier** [comment] 2019-08-29 15:11
Same with XF 4.2.0.709249

![image](https://user-images.githubusercontent.com/49204455/63952505-159b2c80-ca56-11e9-80e5-53f831f3bc9d.png)

**Comment by eramrit78** [comment] 2019-08-29 23:34
Issue come when used shell.

**Comment by mfeingol** [comment] 2019-09-19 01:27
Same issue here with 4.2.0.778463. This is blocking my intended migration from Master-Detail to Shell.

@samhouts: I don't suppose there are any workarounds for this?

**Comment by samhouts** [comment] 2019-09-26 21:22
I'm afraid I'm not aware of any workarounds at this time. @PureWeen ?

**Comment by jfversluis** [comment] 2019-09-27 16:59
The error originates [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs#L465). The `Order` simply is not taken into account.

I've opened a PR to fix that

**Comment by mfeingol** [comment] 2019-09-27 17:04
@jfversluis: greatly appreciated!

One question, while you're in the area: I probably should have filed an issue for this, but when I was evaluating porting over to Shell, I noticed that ToolbarItems from sub-pages inside a TabbedPage weren't being picked up by the Shell at all. Is that by design, or does it also need to be fixed?

(I can provide a repro if needed.)

**Comment by jfversluis** [comment] 2019-09-27 17:14
@mfeingol that's what we do it for! 😉 

For the other thing, if you wouldn't mind opening a new issue (with a reproduction would be superduper awesome) please do. That way we can track the two things separate from each other. From the top of my head I'm not sure if that is by design (@PureWeen ?) but my gut feeling says it's not and it should just work as it does on non-Shell apps

**Comment by PureWeen** [comment] 2019-09-27 17:16
So you have TabbedPage inside of your Shell?

**Comment by mfeingol** [comment] 2019-09-27 17:52
@PureWeen: I was moving my existing app into the Shell, and the existing app has TabbedPages, so... yes.

Once it's clear that Shell doesn't have any showstoppers, then I'll put some work into porting tabs over to the way Shell does them. One complication is my viewmodels are shared with a native UWP app where the separate tabs are not separate pages, so there's a little bit of entanglement between tabbed pages. But it's just work.

In any case, this is why I was asking whether it was by design or not... I expected it to just work, but I can see why you'd say "well, TabbedPage is deprecated and shouldn't be used with Shell".

**Comment by PureWeen** [comment] 2019-09-27 20:16
Yea it's definitely by design. If you could log an issue with your use case then we (or someone from the community) can look into making things like that work with Shell

The problem is that getting those inner pages to work with Shell starts to add layers of complexity we'd like to avoid. So ideally we could just get you full Shell

**Comment by mfeingol** [comment] 2019-09-27 21:00
That's what I thought. I'll file an issue so you have it in mind, but no surprises if it gets closed as WF. :-)

**Comment by zionek** [comment] 2019-10-02 07:45
@samhouts I'm still experiencing the same issue. Do I need to perform some special action? I've already tried cleaning the solution.

**Comment by iooovolts** [comment] 2019-10-02 10:20
I can see https://github.com/xamarin/Xamarin.Forms/pull/7718 has been completed with UI test passed. I have updated to XF 4.2.0.815419. Is there anything I am missing? Or has the fix simply not yet been rolled out?

**Closed** 2019-10-02 13:08 UTC
Labels: a/shell :shell:, e/3 :clock3:, m/high impact :black_large_square:, p/Android, t/bug :bug:

**Comment by Darlingtone** [comment] 2019-10-03 13:50
Just update to XF 4.2.0.848062 released 2nd of Oct. 2019 issue not yet fixed. also tried the lasted 4.3-preview no luck

**Comment by jfversluis** [comment] 2019-10-04 10:00
@iooovolts @Darlingtone I think the fix in my PR has just missed the release that just came out. Please be on a lookout for the next 4.2 or 4.3-pre release which should include it for sure.

**Comment by KoenMat** [comment] 2019-10-31 13:34
Since  4.3.0.908675 it is fixed for Android, but not for IOS. 
ToolbarItems always appear as primary even if configered as secondary.

**Comment by jfversluis** [comment] 2019-10-31 14:33
@KoenMat it seems you are totally right. Since this was focussed on Android I didn't pay any attention to iOS. I've opened a new issue for it to track it properly.
