### ISSUE TITLE
[Bug] SwipeView is too sensitive - opens when scrolling

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12518] opened 2020-10-19 05:34 UTC
Hi.

Issue one: SwipeView is great. I use it for deleting chat messages and leaving chat rooms, by the user swiping left on a message or a chat. However, there seems to be absolutely no threshold for the swipe to happen, as it constantly opens whenever I scroll the list of chat messages or chat rooms. It is almost impossible to swipe perfectly vertically, so any even absolutely slight horizontal movement opens the swipe menu. The threshold value should be at least equal to a tap gesture recognisers default threshold value (and preferably scriptable) - because currently both a tap and swipe start open overlap.

This might sound like a small thing, but it completely breaks the experience as almost every scroll opens the swipe menu.

I think this would be a small fix that would make it immensely more usable so I am eagerly awaiting a fix for it.

Tested with latest XF 5 pre-release on iOS. I used the SwipeView in a bindable stack layout, enclosed in a scroll view.

Thank you.

**Comment by Tommigun1980** [comment] 2020-10-19 05:38
Another bug with the swipe menu, which is almost as bad, is that when you are scrolling a view and during that same scroll do a slight horizontal movement, the swipe menu starts opening.

If a vertical scroll is ongoing the swipe menu should not open. It should only open if the user **starts** with a horizontal swipe.
These issues are mostly apparent when using an actual device, not so much with a mouse in the simulator.

**Comment by Tommigun1980** [comment] 2020-10-19 05:49
A third bug with the swipe view is that very often when you start scrolling and the swipe menu accidentally opens (as outlined in the initial message) and you stop scrolling, the UI breaks in two possible ways (seemingly randomly)
1) The item stays stuck in the position it would be as if the swipe view was visible, but it is not. Tapping, scrolling, nothing seems to bring it back.
2) The UI completely locks up and a restart of the app is required.

So to clarify:
1) You start scrolling a view vertically
2) Due to the sensitivity of the swipe view it opens on the first item (from right in my case)
3) You continue scrolling normally
4) The swipe view either disappears at this stage or stays visible
5) No matter if it disappears or not, the item stays on the left side
6) The UI may lock up

I think these are all related and possibly the same issue, can't say for sure.

**Comment by Tommigun1980** [comment] 2020-10-19 05:52
I am positive that a repro with merely a list of items (enough to simulate a normal scrolling of content experience) and swipe view in all of them, when run on an actual device, is enough to repro all these issues. It is very important to do this on a real device, use it one handedly as people normally do and they should all be reproducible. If for whatever reason they are not I can try to give additional information, but I don't know if there's much more I can do.

Thank you for a prompt fix!

**Comment by Tommigun1980** [comment] 2020-10-19 06:24
I took a screenshot where two items are docked to the left with no swipe view visible, and when starting to scroll in that state the entire UI locked up. Please let me know where to send it in case it would be useful (don't want to post it publicly).

I think I have to disable all the swipe view for now because they constantly lock up the UI. I am holding out hope for a somewhat quick fix instead of remaking the UI right now.

Thanks again.

**Comment by Tommigun1980** [comment] 2020-10-19 16:32
Issue four: It a swipe view is open and you try to invoke it again (in my case swipe left twice on an item), it bounces funnily. Expected behavior is that the open swipe view gesture wouldn’t do anything if it’s already open.

**Comment by Tommigun1980** [comment] 2020-10-19 16:38
Fix suggestions:
1) Lock the panning axes: if the user is scrolling vertically, no horizontal movement during that swipe should invoke the swipe view. Conversely if the user is opening the swipe menu, no vertical movement should scroll the view.
2) Add some threshold before it goes into the above “opening swipe view” state.
3) Fix the state where a previously opened swipe view stays “open”, and the UI lockup.

@jsuarezruiz Hi, I saw you added the collection view tag. This is not exclusive to collection views, I use bindable stack layouts with a scroll view. In fact I haven’t tested this with a collection view (updated the OP to say this).

**Comment by Kapusch** [comment] 2020-10-21 16:52
Same as @Tommigun1980 , I do also encountered many times the "UI break" (not able to scroll anymore until I swipe an item).

My configuration :
- SwipeView nested in a CollectionView
- XF 4.8.0.1560
- iOS 14
- VS for Mac

This is how I'm able to reproduce it :

1. Start swiping horizontally (I generally swipe half long of the phone width)
2. Keep your finger pressed on the swiped item, and start scrolling up & down
3. Release your finger

Up to this point :
- there is a high percent of not being able to scroll anymore,
- if I want to unlock my collectionview, I must swipe on an item before to scroll.


I will try your suggestions Tommigun.

**Comment by Tommigun1980** [comment] 2020-11-20 00:01
Thank you @jsuarezruiz for fixing the lock up issue. Is there a PR for the sensitivity issue yet or do you think it will also be fixed hopefully soonish? It is a real problem that panning a collection constantly opens the swipe view by accident, as it's so hard to do pixel perfect vertical swipes with your fingers on an actual device?

Thank you so much for working so hard to fix these issues, we really appreciate it!

**Comment by kaniosm** [comment] 2021-01-03 17:53
After a quick look at the current SwipeView android render, I noticed the constant "SwipeMinimumDelta".
I suspect this was used to prevent the scroll issue referred above since I can see it is used in OnParentScrolled methods.
At first, I believe the same can be used in ShouldInterceptTouch to release the touch event to the parent in case the delta is too small.
Later, the SwipeMinimumDelta constant or a new property can be exposed to the forms control to allow developers to define this value according to their needs.
e.g.

`bool ShouldInterceptTouch(MotionEvent e)
		{
			if (_initialPoint == null)
				return false;

			var interceptPoint = new Point(e.GetX() / _density, e.GetY() / _density);

			var diffX = interceptPoint.X - _initialPoint.X;
			var diffY = interceptPoint.Y - _initialPoint.Y;

			//Check if swipe delta is too small and release touch
			if (diffX < SwipeMinimumDelta && diffY < SwipeMinimumDelta)
				return false;

			SwipeDirection swipeDirection;

			if (Math.Abs(diffX) > Math.Abs(diffY))
				swipeDirection = diffX > 0 ? SwipeDirection.Right : SwipeDirection.Left;
			else
				swipeDirection = diffY > 0 ? SwipeDirection.Down : SwipeDirection.Up;

			var items = GetSwipeItemsByDirection(swipeDirection);

			if (items == null || items.Count == 0)
				return false;

			return ShouldInterceptScrollChildrenTouch(swipeDirection);
		}`

**Comment by Tommigun1980** [comment] 2021-01-09 12:27
Hi!

This issue still persists, that when a view is scrolled the SwipeViews constantly pop up by accident. It is so bad I don't think I could use it in production yet.

Do you guys think this could be fixed at some point?

Thanks so much!

**Comment by kkppstudios** [comment] 2021-02-03 01:09
Hi, just checking in on where this stands. This is still an issue on Android and I only see [#12758](https://github.com/xamarin/Xamarin.Forms/pull/12758) which is only targeting ios. Should a new request be opened?

**Comment by kaniosm** [comment] 2021-02-03 17:56
From what I understand the current issue is still open, therefore there is no need to open a new one.
This issue is open for quite some time now.
In my case, I cloned the Xamarin.Forms repo and I did the below changes to the Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer class, which solved the issue for me.
I'm recompiling the assembly where with every new release and I'm replacing the Xamarin.Forms.Platform.Android.dll in my Nuget cache folder with the compiled one, and therefore all my projects are updated with the new dll!
Line 238 on the sr2 Tag

//Check if swipe delta is too small and release touch 

`if (Math.Abs(diffX) < SwipeMinimumDelta && Math.Abs(diffY) < SwipeMinimumDelta)
return false;`

**Comment by kkppstudios** [comment] 2021-02-03 23:00
> From what I understand the current issue is still open, therefore there is no need to open a new one.
> This issue is open for quite some time now.
> In my case, I cloned the Xamarin.Forms repo and I did the below changes to the Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer class, which solved the issue for me.
> I'm recompiling the assembly with every new release and I'm replacing the Xamarin.Forms.Platform.Android.dll in my Nuget cache folder with the compiled one, and therefore all my projects are updated with the new dll!
> Line 238 on the sr2 Tag
> 
> //Check if swipe delta is too small and release touch
> 
> `if (Math.Abs(diffX) < SwipeMinimumDelta && Math.Abs(diffY) < SwipeMinimumDelta) return false;`
> 
> I hope this helps some of you, until this is taken care in a future release

This is a great work-around, thanks kaniosm. I haven't tried this yet as it adds a bit of overhead to my releases but I may have to resort to using it.

**Comment by decv86** [comment] 2021-02-04 16:20
why can't it take so long to fix such seemingly simple things ... it just kills

**Comment by meJevin** [comment] 2021-03-28 00:31
SwipeView is not ready for production use. UX is absolutely horrible.

**Comment by decv86** [comment] 2021-03-28 08:13
@jsuarezruiz we need help! tell me this issue will be resolved?

**Comment by kkppstudios** [comment] 2021-03-29 01:18
> SwipeView is not ready for production use. UX is absolutely horrible.

Sadly, I agree. I've removed it from my production app in replace of just straight buttons. It ended up being a good decision especially since the SwipeView has not gotten enough love.

**Comment by KaeTar** [comment] 2021-04-20 01:10
@samhouts @jsuarezruiz do you know if there is some sort of ETA on this?  I have 4 applications that have been holding release due to this one little issue.  I am now working to remove SwipeView because in order to get other features released.

**Comment by vhugogarcia** [comment] 2021-05-12 20:55
> > SwipeView is not ready for production use. UX is absolutely horrible.
> 
> Sadly, I agree. I've removed it from my production app in replace of just straight buttons. It ended up being a good decision especially since the SwipeView has not gotten enough love.

Is there any other alternative or library that we can use for swipeview?

**Comment by vhugogarcia** [comment] 2021-05-12 21:02
i found out this alternative, maybe it can work: https://github.com/AndreiMisiukevich/ContextMenu

**Comment by AlleSchonWeg** [comment] 2021-07-15 09:22
Hi @Tommigun1980 ,
do you find a workaround for this issue?

**Comment by lightwalker01** [comment] 2021-07-20 09:11
Is there nothing new on this issue?
Thanks

**Comment by vhugogarcia** [comment] 2021-07-20 11:53
> Is there nothing new on this issue?
> 
> Thanks

There is a threshold property that you can use. I set it to 300 to make it compatible with Iphone 5 screens. It worked OK as temporary solution to this. I hope this get fixed properly on future xamarin.forms releases. 

"SwipeView includes a Threshold property, of type double, which represents the number of device-independent units that trigger a swipe gesture to fully reveal swipe items."

**Comment by lightwalker01** [comment] 2021-07-20 12:33
> There is a threshold property that you can use. I set it to 300 to make it compatible with Iphone 5 screens. It worked OK as temporary solution to this. I hope this get fixed properly on future xamarin.forms releases.
> 
> "SwipeView includes a Threshold property, of type double, which represents the number of device-independent units that trigger a swipe gesture to fully reveal swipe items."

@vhugogarcia Thank you for your response!
But the `Threshold` property declare how many units are required to **fully reveal** swipe items, not how many units are required to **initiate** the swipe action (`Sensitivity`, i presume).

We have this issue that actually blocks the release of our app: on a CollectionView with tap gesture **AND** SwipeView on items, when the user tap over an item, the swipe action prevent the tap execution very often.

**Comment by vhugogarcia** [comment] 2021-07-20 12:40
> > There is a threshold property that you can use. I set it to 300 to make it compatible with Iphone 5 screens. It worked OK as temporary solution to this. I hope this get fixed properly on future xamarin.forms releases.
> 
> > 
> 
> > "SwipeView includes a Threshold property, of type double, which represents the number of device-independent units that trigger a swipe gesture to fully reveal swipe items."
> 
> 
> 
> @vhugogarcia Thank you for your response!
> 
> But the `Threshold` property declare how many units are required to **fully reveal** swipe items, not how many units are required to **initiate** the swipe action (`Sensitivity`, i presume).
> 
> 
> 
> We have this issue that actually blocks the release of our app: on a CollectionView with tap gesture **AND** SwipeView on items, when the user tap over an item, the swipe action prevent the tap execution very often.

That is correct my friend. There is no solution for the sensitivity. However, that property helped me to define a 300 and prevented users to open it while scrolling. Give it a try. It is a temp solution only.

**Comment by Zwawoo** [comment] 2021-07-31 17:34
I wrote a dirty workaround via CustomRenderer and Refelection for Android which implements the solution from @kaniosm 
but without having to recompile Xamarin forms.
My first impression is that it works. Please check it out and give some feedback:
`public class CustomSwipeView : SwipeView
{
}
`
```

using Android.Content;
using Android.Views;
using App.Util.CustomViews;
using System;

using System.Reflection;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using APointF = Android.Graphics.PointF;

[assembly: ExportRenderer(typeof(CustomSwipeView), typeof(App.Droid.CustomRenderer.DroidCustomSwipeViewRenderer))]
namespace App.Droid.CustomRenderer
{
    public class DroidCustomSwipeViewRenderer : SwipeViewRenderer
    {
        float _density;
        APointF _initialPoint;
        const float SwipeMinimumDelta = 10f;
        public DroidCustomSwipeViewRenderer(Context context) : base(context)
        {
            
        }
        protected override void OnElementChanged(ElementChangedEventArgs<SwipeView> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null)
            {
                _density = Resources.DisplayMetrics.Density;
            }
        }
        public override bool OnTouchEvent(MotionEvent e)
        {
            if (e.Action == MotionEventActions.Move && !ShouldInterceptTouch(e))
                return true;

            return base.OnTouchEvent(e);
        }

        public override bool DispatchTouchEvent(MotionEvent e)
        {
            if (e.Action == MotionEventActions.Down)
            {
                _initialPoint = new APointF(e.GetX() / _density, e.GetY() / _density);
            }

            return base.DispatchTouchEvent(e);
        }
        public override bool OnInterceptTouchEvent(MotionEvent e)
        {
            return ShouldInterceptTouch(e);
        }
        bool ShouldInterceptTouch(MotionEvent e)
        {
            if (_initialPoint == null)
                return false;

            var interceptPoint = new Point(e.GetX() / _density, e.GetY() / _density);

            var diffX = interceptPoint.X - _initialPoint.X;
            var diffY = interceptPoint.Y - _initialPoint.Y;

            if (Math.Abs(diffX) < SwipeMinimumDelta && Math.Abs(diffY) < SwipeMinimumDelta)
            {
                return false; 
            }
            SwipeDirection swipeDirection;

            if (Math.Abs(diffX) > Math.Abs(diffY))
                swipeDirection = diffX > 0 ? SwipeDirection.Right : SwipeDirection.Left;
            else
                swipeDirection = diffY > 0 ? SwipeDirection.Down : SwipeDirection.Up;

            SwipeItems items = null;
            var baseType = GetType().BaseType;
            if (baseType != null)
            {
                var getSwipeItemsByDirection = baseType.GetMethod("GetSwipeItemsByDirection",
                    BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[] { typeof(SwipeDirection) }, null);
                items = (SwipeItems)getSwipeItemsByDirection.Invoke(this, new object[] { swipeDirection });
            }
            

            if (items == null || items.Count == 0)
                return false;

            var shouldInterceptScrollChildrenTouch = baseType.GetMethod("ShouldInterceptScrollChildrenTouch",
                    BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[] { typeof(SwipeDirection) }, null);
            bool result = (bool)shouldInterceptScrollChildrenTouch.Invoke(this, new object[] { swipeDirection });

            return result;
        }
    }
}
```

Does this sensitivity problem also still exist on iOS? Haven't tried it out yet on iOS.

**Comment by kaniosm** [comment] 2021-08-01 16:09
Very good @Zwawoo! I've tested this approach and it works well...
I've made a minor change...
`[assembly: ExportRenderer(typeof(SwipeView), typeof(App.Droid.CustomRenderer.DroidCustomSwipeViewRenderer))]`

since you can apply the render to SwipeView and there is no need to create a new control.
It's cleaner this way, and there is no need to recompile Xamarin.Forms.Platforms.Android.

Regarding SwipeView in iOS, unfortunately things are much worse their.
I'll have to agree with others that SwipeView is not production ready for iOS. In my case I face way too many issues...
Just to name a few:
1. The scroll on the parent component remains disabled in several cases
2. The contents of the SwipeView items are getting rendered in the wrong place (offset according to the swipe direction)
3. Swipe will not always disable the parent scroll
4. For both iOS and Android, swipe will stop if your finder jumps to the next item in the list. This is not the case for native swipe items (check how swipe behaves in iMessages for example)

I really hope all those issues are resolved with MAUI since... I've lost my hope with Xamarin since those issues are there for quite some time now.

**Comment by GivennameSurname** [comment] 2021-08-24 07:12
> Very good @Zwawoo! I've tested this approach and it works well...
> I've made a minor change...
> `[assembly: ExportRenderer(typeof(SwipeView), typeof(App.Droid.CustomRenderer.DroidCustomSwipeViewRenderer))]`
> 
> since you can apply the render to SwipeView and there is no need to create a new control.
> It's cleaner this way, and there is no need to recompile Xamarin.Forms.Platforms.Android.
> 
> Regarding SwipeView in iOS, unfortunately things are much worse
> I'll have to agree with others that SwipeView is not production ready for iOS. In my case I faced way too many issues...
> Just to name a few:
> 
> 1. The scroll on the parent component remains disabled in several cases
> 2. The contents of the SwipeView items are getting rendered in the wrong place (offset according to the swipe direction)
> 3. Swipe will not always disable the parent scroll
> 4. For both iOS and Android, swipe will stop if your finder jumps to the next item in the list. This is not the case for native swipe items (check how swipe behaves in iMessages for example)
> 
> I really hope all those issues are resolved with MAUI...
> I've lost my hope with Xamarin, since most issues are open for quite some time now.

Besides your points (which I can confirm), I´ll add another Point:

5.1 If you try to disable swipe while scrolling in a listview it will start flickering or
5.2 it simple disable it all the time

**Closed** 2021-09-01 11:29 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/collectionview, in-progress, a/swipeview
