### ISSUE TITLE
xamarin forms 3.6 shell crash 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6350] opened 2019-05-29 22:37 UTC
VSF_TYPE_MARKDOWNJust creat new xamarin forms app then choose shell as template.
Run the app directly without any change on real deivce or emulator.
Keep pressing on the &quot;Browse&quot; tab then &quot;About&quot; tab (switch fast between tabs)
repeate this step more than 8 times 
the app will close with no error and even depugger will not catch anything.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/543774/xamarin-forms-36-shell-crash.html
VSTS ticketId: 854214_
_These are the original issue comments:_

Visual Studio Feedback System on 4/23/2019, 10:44 PM (35 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/26/2019, 10:27 AM (33 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment] 2019-05-29 22:55
Duplicate of #6174

**Closed by samhouts** 2019-05-29 22:55 UTC
Labels: a/shell :shell:, feedback-ticket, i/high, s/unverified, t/bug :bug:
