### ISSUE TITLE
Crash when dismissing modally presented page on iOS

### ISSUE THREAD

**Issue by btschumy** [xamarin/Xamarin.Forms#12300] opened 2020-09-29 17:51 UTC
### Description
I have a Xamarin Forms app and am having a crash with the iOS target and the more recent Xamarin Forms builds.

On non-phone devices, I present all my secondary NavigationPages using the UIModalPresentationStyle.FormSheet style. I do this via a NavigationPage subclass that does this in the constructor.

```
        if (Utility.IsLargeScreen())
        {
            On<iOS>().SetModalPresentationStyle(UIModalPresentationStyle.FormSheet);
        }

```
I would love to have the Navigation page be dismissed by clicking outside the NavigationPage, but that doesn't seem to work in Xamarin Forms (I've spent days on it). So instead I have a "Done" button in the title bar that dismisses it via:

```
    private void Done_Clicked(object sender, EventArgs e)
    {
        Navigation.PopModalAsync();
    }

```
This normally works just fine. However, if I tap outside the NavigationPage frame (which should dismiss it) and then tap Done, I always get the following crash when the page is being dismissed:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <b2309b0f34c14f2999df87941bbffcf9>:0 
  at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) [0x00011] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:430 
```
It seems like the page is being popped off the stack is already gone, resulting in a negative index.

I would prefer the page be dismissed when tapping outside the bounds, but I am not opposed to having a Done button. However, in that case I need to find away to prevent this crash.

In case you're curious, I have tried setting ModalInPresentation both true and false but that doesn't seem to have an effect. I think that is a known Xamarin Forms bug.
### Steps to Reproduce

1. Please download the demo project: www.otherwise.com/ModalPresentation.zip
2. Run the project on iOS on an iPad (real device or simulator) and click the Show Modal Page button
3. Now click the Hide Modal Page button in the presented window.  This works fine and the modal page can be shown and hidden multiple times.
4. Now after showing the modal page, tap outside the modal page.  Then try to dismiss the page.  The crash shown above will happen.

### Expected Behavior
No crash when dismissing the modal page
### Actual Behavior
Crash
### Basic Information

- Version with issue:
Xamarin Forms 4.8.0.1451
- Last known good version:
4.1.0.55618 seems to work
However, starting with 4.2.0.910310, the app doesn't crash but you are unable to display the modal window again.
In 4.5.0.725, the app actually crashes when dismissing the window after tapping outside.
- IDE:
Jetbrains Rider
- Platform Target Frameworks:
  - iOS:  11.0
- Nuget Packages:
- Affected Devices:
iPad running iOS 13 or iOS 14 (and possibly earlier)

### Reproduction Link
www.otherwise.com/ModalPresentation.zip

### Workaround
I have not found a workaround other than downgrading to 4.1.0.555618 (which may have its own problems).

**Comment by btschumy** [comment] 2020-09-30 22:42
I see this has been assigned an "e/5" tag.  I have been unable to find exactly what that means but I suspect it means it will be worked on for Xamarin forms 5.x ??

This is really a stop ship bug for me.  If a workaround if found or if you see I am doing something incorrectly in the code that is causing this, please let me know.

Thanks.

**Comment by lassana** [comment] 2020-10-02 14:54
> - Affected Devices:
> iPad running iOS 13 or iOS 14 (and possibly earlier)

FYI: this doesn't happen on iOS 11.4 simulator

**Comment by jvv-sk** [comment] 2021-01-20 10:02
I'm facing this exact same issue in our app. Lots of users complaining about the crashes

**Comment by Burgler-dev** [comment] 2021-01-25 11:07
I'm experiencing the exact same problem, a fix is needed! App crashes are serious. Does anyone has found a way around this? I still would like to be able to use sheets.

**Comment by orikworld** [comment] 2021-01-25 11:27
I have same issue, any workarounds?

**Comment by JohnHDev** [comment] 2021-02-20 22:02
The only workaround Ive seen is to not use UIModalPresentationStyle.FormSheet. Which leads to a poor user experience (and 1 star reviews!) for all Xamarin apps on iPad. At least this is now in in the planning stage for service release 4 of XF 5. But *please* don't descope this for a later release, which tends to happen with the XF bugs I watch.

**Comment by JohnHDev** [comment] 2021-04-25 06:49
Due to the poor support from Xamarin and the huge number of bugs that don't get fixed in a timely manner (or just poorly fixed), we are dropping Xamarin Forms going forward and are no longer recommending Xamarin to our clients. Our existing Xamarin Forms apps will be placed into legacy support mode (we have maintenance contracts to honour), but we cab now offer alternative technologies.
We just can't run a business using Xamarin Forms.

**Comment by btschumy** [comment] 2021-04-25 12:13
I’m the original poster.  I’ve also abandoned Xamarin because of things like this.  Too bad.

**Comment by AndreasReitberger** [comment] 2021-04-29 04:25
> I’m the original poster. I’ve also abandoned Xamarin because of things like this. Too bad.

May I ask what you are using now? I'm facing the same problems... Thank you!

**Comment by btschumy** [comment] 2021-04-29 13:38
Well, I switched to Unity.  In addition to Xamarin, I also was using UrhoSharp to do a 3D rendering of the Galaxy.  UrhoSharp has been abandoned by Microsoft.  I thought I could get by with it as is but found a number of insurmountable problems in UrhoSharp as well as those in Xamarin.

I wouldn't recommend Unity unless 3D is a large part of the project.  It is not the best for creating a standard UI (although it can be done).

**Comment by JohnHDev** [comment] 2021-05-01 18:05
@hartez why hasn't this been fixed already? It was raised *over 7 months* ago, and its a *hard crash* on iPads. I have already pointed out the XF code at fault that needs investigating by better minds than mine on the ticket you 'closed' (you didn't close it btw).

@davidortinau do you still work at MS and on Xamarin at all? Is this standard MS policy to ignore crashing bugs? We have switched all our the Xamarin apps that we can into legacy support mode, but we still need to support our existing apps until we migrate.

If @davidortinau is no longer a Xamarin PM, who can we escalate these issues to?

**Comment by orikworld** [comment] 2021-05-01 20:03
We also had this problem, we just changed the modal pages to Rg.Plugins.Popup, implementation took a bit of time, but it helped

**Comment by JohnHDev** [comment] 2021-05-02 06:43
thanks @orikworld, but we are dropping Xamarin in the long term and are not interested in purchasing third party purchases to work around a failing product. We expect to see fixes in the core product, but it appears Microsoft themselves no longer support Xamarin. Would you agree @davidortinau?

**Comment by AndreasReitberger** [comment] 2021-05-13 05:48
@PureWeen @jsuarezruiz @davidortinau @hartez 
Any news on this issue? I cannot release my app updates because of this critical bug.

I'm using the "Automatic" ModalPresentationStyle for tablets

```
<Style x:Key="ModalPageStyle" TargetType="ContentPage" BasedOn="{StaticResource DefaultPageStyle}">
        <Setter Property="Shell.PresentationMode" Value="ModalAnimated" />
        <!--<Setter Property="ios:Page.ModalPresentationStyle" Value="FormSheet" />-->
        <Setter Property="ios:Page.ModalPresentationStyle" Value="{OnIdiom Tablet=Automatic, Default=FormSheet}" />
    </Style>
```

Once I dismiss the modal, the app crashes on a Tablet. IPhones seems to be fine. Also using "FormSheet" on the iPad is working fine if this helps.

**Comment by AndreasReitberger** [comment] 2021-06-13 09:25
@PureWeen 
Any update on this issue? It's critical and open almost a year...
Thank you.

**Comment by JohnHDev** [comment] 2021-06-16 08:55
@AndreasReitberger I spoke with @davidortinau and the lead developer for XF a few weeks back, they aren't prioritising bugs over .NET Maui migration work unless you have a support contract to raise the priority of bugs. some of the bugs would be very difficult to resolve in the old XF codebase, but this should be relatively easy. I would hope they can prioritise this instead.

The fact that no-one from support replies to our messages is a separate issue that I also raised...

**Comment by AndreasReitberger** [comment] 2021-06-16 09:44
> @AndreasReitberger I spoke with @davidortinau and the lead developer for XF a few weeks back, they aren't prioritising bugs over .NET Maui migration work unless you have a support contract to raise the priority of bugs. some of the bugs would be very difficult to resolve in the old XF codebase, but this should be relatively easy. I would hope they can prioritise this instead.
> 
> 
> 
> The fact that no-one from support replies to our messages is a separate issue that I also raised...

Hi @JohnHDev 
thank you very much for you reply.
I see that NET Maui is your prio, however you are loosing trust by leaving Xamarin.Forms unstable like this. I would understand if Maui is ready to use and we can port Xamarin.Forms projects over. But this seems not to be the case atm.
Who guarantees us, that the same doesn't happen with maui when the next evolution is coming up? Some Critical bugs haven't been fixes over years. Don't get me wrong, I really appreciate your hard work and effort providing us a free platform to create awesome apps.
But wouldn't it be better to fix the currently "stable" project Xamarin.Forms before putting all effort into a new one?

Thank you for your time & effort!

**Comment by JohnHDev** [comment] 2021-06-16 11:44
@AndreasReitberger i don’t actually work for Microsoft, I just replied as I had information that might be relevant and hopefully helpful to you and others, as the support here is almost non existent. 

Having looked at some of the XF code, I can completely see why they want to distance themselves from that code base, but they really should be able to prioritise easily fixable bugs like this.

**Comment by AndreasReitberger** [comment] 2021-06-16 12:54
@JohnHDev 
Yes, just saw that after submitting my comment ;) 
Hopefully we will hear more soon. The last "stable" update was in february, and this version is far from stable..
We will see what the time brings... ;)
Thanks!

**Comment by SwarupaKM** [comment] 2021-07-08 06:14
Till fix comes,
Set 
   `ModalInPresentation = true;`
But the side effect is this stops closing on modal on tap outside or swipe down. (naturally crash stops :))
so you will have to implement these.
I was able to implement close on swipe down, that was what I needed.

**Comment by AndreasReitberger** [comment] 2021-07-08 07:05
> Till fix comes,
> 
> Set 
> 
>    `ModalInPresentation = true;`
> 
> But the side effect is this stops closing modal on tap outside or swipe down. (naturally crash stops :))
> 
> so you will have to implement these.
> 
> I was able to implement close on swipe down, that was what I needed. 

I actually tried this with a custom page renderer, however with no effect. How did you set it in your code?

**Comment by SwarupaKM** [comment] 2021-07-15 06:11
> > Till fix comes,
> > Set
> > `ModalInPresentation = true;`
> > But the side effect is this stops closing modal on tap outside or swipe down. (naturally crash stops :))
> > so you will have to implement these.
> > I was able to implement close on swipe down, that was what I needed.
> 
> I actually tried this with a custom page renderer, however with no effect. How did you set it in your code?

1. override WillMoveToParentViewController(UIViewController parent) - Add parent.ModalInPresentation = true; you will need this value of parent to get presentedView later.
2. In the ViewDidAppear-> Create UISwipeGestureRecognizer and  PopModalAsync() in its action. Add this gesture to the PresentedView.
3. Remove it the ViewWillDisappear.

**Comment by AndreasReitberger** [comment] 2021-07-27 05:20
> 2\. PresentedView

Thanks for the hint. Based on your comment I was able to create a PageRenderer which avoids the swipe to dismiss of the modal.
This is how I solved it for now.
```
public class ModalPageRenderer : PageRenderer
    {
        UISwipeGestureRecognizer uISwipe;

        public override void WillMoveToParentViewController(UIViewController parent)
        {
            base.WillMoveToParentViewController(parent);
            parent.ModalInPresentation = true;
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            uISwipe = new(async() =>
            {
                await App.Current.MainPage.Navigation.PopModalAsync(animated);
            });
            View.AddGestureRecognizer(uISwipe);
        }

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
            View.RemoveGestureRecognizer(uISwipe);
        }
    }
```

Thank you!

**Comment by InquisitorJax** [comment] 2021-08-19 09:31
... just a note on the work-around above by @AndreasReitberger - you need implement this for >= iOS 13 only, as it will crash <= iOS 12.

I added a local flag on the constructor of the page renderer:
_needsWorkAround = UIDevice.CurrentDevice.CheckSystemVersion(13, 0);

**Comment by AndreasReitberger** [comment] 2021-08-19 09:33
> ... just a note on the work-around above by @AndreasReitberger - you need implement this for >= iOS 13 only, as it will crash <= iOS 12.
> 
> 
> 
> I added a local flag on the constructor of the page renderer:
> 
> _needsWorkAround = UIDevice.CurrentDevice.CheckSystemVersion(13, 0);

Thanks for the hint, I'll update this in my code and the example above.

**Comment by jfversluis** [comment] 2021-08-23 14:04
It seem [this little thing right here](https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Platform.iOS/ModalWrapper.cs#L63) is the cause of the weird behavior. The weird thing is that it doesn't happen when you close it by swiping down, only by touching outside. Trying to come up with the best way to fix this and not reintroduce the thing that was trying to prevented here :)

**Closed** 2021-09-02 15:43 UTC
Labels: t/bug :bug:, p/iOS 🍎, i/regression, e/5 :clock5:, i/high, iOS 13, p/tablet, a/modal, iOS 14
