### ISSUE TITLE
UWP error when starting from blank project: The Windows store app [package Name] cannot be activated. The activation request failed with error "Access denied".

### ISSUE THREAD

**Issue by XamDevv** [xamarin/Xamarin.Forms#2125] opened 2018-03-17 14:09 UTC
### Description

When I create a new xamarin.forms Project and try to run the uwp app, following error appears (translated from german): The Windows store app [package Name] cannot be activated. The activation request failed with error "Access denied".

The Problem appeared when I updated Visual Studio 2017 to Version 15.6.2. Now the Problem persists even with earlier version 15.5.7 which worked fine before.

It seems to be xamarin related as starting a UWP app in a blank uwp project it works just fine.

Things I've tried:
- Cleaning and rebuilding the solution
- Different build configurations debug/release x86/x64
- Different Visual Studio versions
- Different Xamarin.Forms versions

### Steps to Reproduce

Probably can't be reproduced easily as it's an enviroment error.

### Expected Behavior

UWP app should Launch.

### Actual Behavior

Doesn't Launch.

### Basic Information

- Version with issue: 2.5.0.280555 as well as 2.5.1.340284-pre2
- Last known good version: -
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP:  16299
- Android Support Library Version: -
- Nuget Packages: All packages in template
- Affected Devices: Win 10 Laptop

### Screenshots

![vserror_windowsstoreappcantbeactivated](https://user-images.githubusercontent.com/33662088/37556156-c18979de-29e9-11e8-8177-dd7dbd631e7b.PNG)

### Reproduction Link

-

**Comment by XamDevv** [comment] 2018-03-20 08:01
I see that this has been moved to Needs Info. Which kind of info would be helpful?

**Comment by PureWeen** [comment] 2018-03-28 19:29
Hey @XamDevv  can you attach a repro? Maybe check the debug out logs see if you see an additional error message? Maybe try running VS in admin mode? Are you launching to Local Machine or to the Simulator?

**Comment by jassmith** [comment] 2018-04-07 04:30
I apologize for the incorrect early triage. This does appear to be a permissions issue though Xamarin isn't really related to that. I would very much like to see a project that repros this since I cant seem to get it.

**Comment by pauldipietro** [comment] 2018-05-18 14:56
Closing for sake of upkeep as we have yet to receive a reproduction. Please reopen with more information and a reproduction if the issue still occurs on 3.0/3.1-pre.

**Closed by pauldipietro** 2018-05-18 14:56 UTC
Labels: p/UWP, s/needs-repro
