### ISSUE TITLE
[Bug] UWP : DeviceInformation.FindAllAsync and empty Picker since version 4.3.0.908675

### ISSUE THREAD

**Issue by cbs-cbt** [xamarin/Xamarin.Forms#8307] opened 2019-10-30 14:04 UTC
### Description
Calling Windows.Devices.Enumeration.DeviceInformation.FindAllAsync() function in UWP project of a Xamarin Forms application prevents picker's items from displaying.
This, only from version 4.3.0.908675 of Xamarin NuGet Package

### Steps to Reproduce

1. Create a dependency class in UWP project with a function that make a call to DeviceInformation.FindAllAsync
2. Call the function using DependencyService in the Click event from a button on the main form of the application
3. Fill a picker with any values
4. In older versions the picker show its content, since version 4.3.0.908675 the picker stays empty

### Expected Behavior

The picker should show its content in version 4.3.0.908675 and later

### Actual Behavior

The picker doesn't show its content in version 4.3.0.908675 and later

### Basic Information

- Version with issue: from Xamarin.Forms NuGet 4.3.0.908675
- Last known good version: Xamarin.Forms NuGet 4.2.0.910310
- IDE: Microsoft Visual Studio 2019 Professional
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages: Microsoft.NETCore.UniversalWindowsPlatform 6.2.9, NETStandard.Library 2.0.3, Xamarin.Essentials 1.3.1, Xamarin.Forms 4.3.0.908675

### Screenshots

![DeviceInformation FindAllAsync with Xamarin Forms 4 2 0 778463](https://user-images.githubusercontent.com/15328452/67864410-dfe1f500-fb25-11e9-9299-c51ae73ad935.gif)
![DeviceInformation FindAllAsync with Xamarin Forms 4 3 0 908675](https://user-images.githubusercontent.com/15328452/67864472-f5efb580-fb25-11e9-801b-df4da514ca80.gif)

### Reproduction Link

Here is a test project. To compare behaviors of different version, please change Xamarin.Forms NuGet package version of the UWP project

[TestBluetoothUWP.zip](https://github.com/xamarin/Xamarin.Forms/files/3789276/TestBluetoothUWP.zip)

**Comment by hartez** [comment] 2019-11-01 04:13
Duplicate of #8177.

**Comment by samhouts** [comment] 2020-02-18 17:02
Duplicate of #8177

**Closed by samhouts** 2020-02-18 17:02 UTC
Labels: p/UWP, t/bug :bug:
