### ISSUE TITLE
[Bug] CollectionView sometimes doesn't render label 

### ISSUE THREAD

**Issue by Eilon** [xamarin/Xamarin.Forms#6988] opened 2019-07-26 18:21 UTC
# Description

I"m migrating an app from ListView to CollectionView, otherwise using the same data and ItemTemplate, and sometimes some of the label content in the CollectionView doesn't render. If you scroll away and back again then it renders (but some other label might stop rendering).

Full repro app at https://github.com/Eilon/XamarinGitHubViewer/commit/24a231eac461531d208ff6e2435b6a1ffc0f7b9c

### Steps to Reproduce

Have a CollectionView bound to some data, and with some ItemTemplate. Here's what my XAML looks like:
```xml
        <CollectionView
            x:Name="ReposCollectionView"
            ItemsSource="{Binding Repos}"
            SelectionMode="Single"
            SelectedItem="{Binding SelectedRepo}"
            SelectionChangedCommand="{Binding SelectionChangedCommand}"
        >
            <d:CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>First Item</x:String>
                    <x:String>Second Item</x:String>
                    <x:String>Third Item</x:String>
                    <x:String>Fourth Item</x:String>
                    <x:String>Fifth Item</x:String>
                    <x:String>Sixth Item</x:String>
                </x:Array>
            </d:CollectionView.ItemsSource>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <StackLayout Padding="10" Orientation="Vertical">
                        <StackLayout Orientation="Horizontal">
                            <Label Text="{Binding Node.Name}" 
                                    d:Text="{Binding .}"
                                    LineBreakMode="NoWrap" 
                                    Style="{DynamicResource ListItemTextStyle}" 
                                    FontSize="16" />
                            <Label Text="*" 
                                    LineBreakMode="NoWrap"
                                    Style="{DynamicResource ListItemDetailTextStyle}"
                                    FontSize="13" />
                            <Label Text="{Binding Node.Stargazers.TotalCount}" 
                                    d:Text="5"
                                    LineBreakMode="NoWrap"
                                    Style="{DynamicResource ListItemDetailTextStyle}"
                                    FontSize="13" />
                        </StackLayout>
                        <Label Text="{Binding Node.Description}" 
                                d:Text="Item description"
                                LineBreakMode="NoWrap"
                                Style="{DynamicResource ListItemDetailTextStyle}"
                                FontSize="13" />
                        <Label Text="{Binding Node.Url}" 
                                d:Text="http://repo_url"
                                LineBreakMode="NoWrap"
                                Style="{DynamicResource ListItemDetailTextStyle}"
                                FontSize="13" />
                    </StackLayout>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
```

### Expected Behavior

All visible controls should render.

### Actual Behavior

Some controls don't render until you scroll away and scroll back to "force" them to re-render.

### Basic Information

Broken with latest public packages:
* Xamarin.Forms 4.1.0.618606.
* Xamarin.Essentials 1.2.0.

And also broken with latest pre-rel on nuget.org:
* Xamarin.Forms 4.2.0.618605-pre2.
* Xamarin.Essentials 1.3.0-pre.

Reproed in Android x86 Oreo emulator on Win10.

### Screenshots

Some labels not rendering:
![image](https://user-images.githubusercontent.com/202643/61972657-f4e34100-af96-11e9-9d79-186f6476cd7a.png)

Scrolled away and back, now the label renders:
![image](https://user-images.githubusercontent.com/202643/61972689-075d7a80-af97-11e9-8264-9f2feb9e2914.png)

### Reproduction Link

Run this app:
https://github.com/Eilon/XamarinGitHubViewer/commit/24a231eac461531d208ff6e2435b6a1ffc0f7b9c

**Comment by Eilon** [comment] 2019-07-26 19:06
Small tidbit: When I have selection (single) enabled on my CollectionView, then selecting (i.e. tapping) an incorrectly-rendered item, will cause it to re-render properly.

**Comment by hartez** [comment] 2019-07-26 23:26
Are you seeing any sort of error output in the debug window as this is happening?

**Comment by muhaym** [comment] 2019-07-27 06:01
My understanding of this issue is the recycling of rows.

Suppose the list have rows with data
1) ABC
2) DEFGHI
3) JKL
4) MNOPQRST
5) UV 
6) W
7) X
8) YZ12345678

and if at a time 3 rows are rendered, when you scroll to the second set (4,5,6) and scroll back (1,2,3), the space for text label requested is just for 5) UV and at same space, we are trying to show 2) DEFGHI, which will break DEFGHI to DE

**Comment by Eilon** [comment] 2019-07-29 17:24
I looked at the debug output window and didn't see anything that seemed particularly interesting.

**Comment by jfversluis** [comment] 2019-07-30 14:00
@hartez I noticed something similar happening on iOS and decided to fix that. I noticed this was just targeting Android, also, my cause cannot be the cause on Android, but maybe it gives you some hint.

On iOS I found out that when you bounced, the `CellDisplayingEnded` was called and the (templated) cell would be removed together with the `BindingContext` but never put back. So, I was thinking a fix like this: https://github.com/xamarin/Xamarin.Forms/commit/2902d480a2087fca12ea3017fb83015c78e14822

However, since Android does not bounce, this cannot be the cause here. 🤔

**Comment by Eilon** [comment] 2019-07-30 16:25
Yeah that's a good point @jfversluis , the static text so far *always* seems to render. It's only the labels with the bindings that sometimes disappear.

**Comment by hartez** [comment] 2019-07-30 16:58
> On iOS I found out that when you bounced, the `CellDisplayingEnded` was called and the (templated) cell would be removed together with the `BindingContext` but never put back. So, I was thinking a fix like this: [2902d48](https://github.com/xamarin/Xamarin.Forms/commit/2902d480a2087fca12ea3017fb83015c78e14822)

Good call - definitely PR that fix.

**Comment by Tragetaschen** [comment] 2019-08-14 13:45
I noticed the same: A label with bound text inside the DataTemplate for a CollectionView, actually a Grid with column-Width="*". There's also a converter in the Binding. My converter is properly called when the binding source changes.

I noticed that the Label doesn't seem to resize when the Binding changes. Initially, my converter returned `null` for `null` and later some actual text. Nothing was displayed then. When I started to return some text for the initial `null` parts of my actual text appeared. Right now, there's `"This is a very long placeholder text to enlarge the label"` for `null` and my label properly sizes and shows content later.

**Comment by hudaIT** [comment] 2019-08-22 12:03
Same issue for nearly evry bigger list for me. It seems to appear even more often when i use Stringformat at the label.

**Comment by Riibit** [comment] 2019-09-17 06:32
Additional piece of info on the topic:  I have had the same thing happen in an almost identical layout as OP. While trying to figure out what was going on, I realized this only happens when the label/s are in a horizontal StackLayout, which is to say that when I change the Orientation to vertical, the labels always rendered. When I replaced the StackLayout container with a Grid, the labels sometimes failed to render again. With the container removed the labels also rendered again. Hope it helps.

**Comment by jfversluis** [comment] 2019-09-17 08:11
@Riibit and all, a PR (#7426) was merged that should address this problem. I see that unfortunately it didn't make it into 4.3-pre1 but is should be in 4.3-pre2. If it's not too much trouble would you please test it again whenever that is released? 

Or, if you're a bit adventurous, dig into our nightly feed and see if the package currently in there fixes this for you?

**Comment by samhouts** [comment] 2019-10-08 00:16
@Eilon I was unable to reproduce this with the 4.2.0 version _or_ with the 4.3.0-pre3 version of forms. I saw all the labels. Could you retest with 4.3.0-pre3 to see if it's resolved for you? Thanks!

**Comment by samhouts** [comment] 2019-10-08 00:17
Also, this is probably the same as #6369

**Comment by Riibit** [comment] 2019-10-08 09:32
@samhouts @jfversluis  Hi, been busy with other stuff for a while. I have managed to get back to this part of the project again and this issue does seem to have been fixed with pre2 or pre3. Thanks for the help guys.

**Comment by jfversluis** [comment] 2019-10-08 09:35
Great @Riibit! Thanks for the confirmation!

**Comment by hartez** [comment] 2019-10-08 16:05
Not reproducible on pre3.

**Closed by hartez** 2019-10-08 16:05 UTC
Labels: a/collectionview, blocker, p/Android, t/bug :bug:

**Comment by Eilon** [comment] 2019-10-09 23:46
@samhouts - I tried on the latest bits and couldn't repro it. Though, I couldn't repro it on whatever older build I was using, either. As mentioned earlier, it can be difficult to reproduce, though it often reproduced fairly quickly. So, I'm OK saying this is fixed. It could be I'm using a newer Android emulator, which maybe somehow affected this as well.

**Comment by agouriou** [comment] 2019-11-04 13:33
Hello. I reproduce this bug with release 4.3.

![missing_label](https://user-images.githubusercontent.com/7474936/68124566-fc0fd880-ff0f-11e9-8018-21d29e73137a.png)

Same screen after scrolling up and down :

![missing_label2](https://user-images.githubusercontent.com/7474936/68124570-fe723280-ff0f-11e9-8d92-321d8ab2fd25.png)

**Comment by agouriou** [comment] 2019-11-04 13:55
This occurs with a grid in the data template. If I get rid of the grid and use multiple stack layouts instead, this seem to work

`                <DataTemplate>
                        <Grid Padding="4" ColumnSpacing="12"
                              BackgroundColor="{StaticResource TransparentLightBlueColor}">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Label Grid.Row="0" Grid.ColumnSpan="4"
                                   Text="{Binding Name}"
                                   TextColor="{StaticResource BlueColor}" 
                                   FontSize="Medium"
                                   FontAttributes="Bold" />

                            <Label Grid.Row="1" Grid.Column="0"
                                   Style="{StaticResource subLabelStyle}"
                                   Text="{Binding Gender}" />
                            <Label Grid.Row="1" Grid.Column="1"
                                   Style="{StaticResource subLabelStyle}"
                                   Text="{Binding Birthdate, StringFormat='{0:d MMM yyyy}'}" />
                            <Label Grid.Row="1" Grid.Column="2"
                                   Style="{StaticResource subLabelStyle}"
                                   HorizontalOptions="Center"
                                   Text="{Binding PatientId}"/>
                            <Label Grid.Row="1" Grid.Column="3"
                                   Style="{StaticResource subLabelStyle}"
                                   HorizontalOptions="End"
                                   Text="{Binding BBB}"/>
                        </Grid>
                    </DataTemplate>`

**Comment by geojorg** [comment] 2019-11-20 19:40
Using Forms 4.4 Pre and the same issue. It only happens on fast scroll down and then up again.
![image](https://user-images.githubusercontent.com/54997758/69271845-9bd19580-0ba3-11ea-92db-f0fa497cb3de.png)

<CollectionView
                SelectedItem="{Binding Selection, Mode=TwoWay}"
                SelectionMode="Single"
                SelectionChangedCommand="{Binding CardSelectedCommand}"
                Margin="15"
                ItemsSource="{Binding Cards}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout 
                        Orientation="Vertical"
                        Span="2"/>
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="model:Card">
                        <StackLayout 
                            Padding="10">
                            
                            <Frame
                                BackgroundColor="#fcd1d7"
                                CornerRadius="10">
                                <Label
                                    Text="{Binding CardName}"
                                    HorizontalOptions="Center"
                                    FontSize="Medium">
                                </Label>
                            </Frame>
                        </StackLayout>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
