### ISSUE TITLE
OnPopAsync crashes on iOS tablet when using FormSheet presentation style

### ISSUE THREAD

**Issue by jantanis** [xamarin/Xamarin.Forms#13273] opened 2021-01-04 08:25 UTC
### Description
When clicking outside of the formsheet and then do a PopModalAsync the app crashed on an ArgumentOutOfRangeException.

### Steps to Reproduce

1. Open the attached solution
2. Start on an iOS tablet simulator
3. Click on the button in center of the screen.
4. Click outside the formsheet
5. Click on close

### Expected Behavior
Closes the formsheet without error.

### Actual Behavior
Crashes the app.

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: unknown 
- Platform Target Frameworks: 
- iOS:  12.3 (17715)
- NuGet Packages:
- Affected Devices: iOS tablets

### Environment
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 1f325176-c86a-4895-9adf-d9041652f96e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.100
	2.1.810
	2.1.809
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Enterprise)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Enterprise)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/jan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
Straight8's SpecFlow Integration 1.11.3.0
NuGet Package Management Extensions 0.24
MFractor 4.4.5
AapIdeExtension.Mac 1.1.64

### Screenshots
https://user-images.githubusercontent.com/11005949/103515247-abc33c00-4e6e-11eb-82a7-069fe4d8b2fe.mov

### Reproduction Link
[Xamarin.OnPopAsync.zip](https://github.com/xamarin/Xamarin.Forms/files/5763686/Xamarin.OnPopAsync.zip)

**Comment by Tommigun1980** [comment] 2021-01-04 19:37
I’m suffering of this too and it’s a very frequent crash, to the point that I wouldn’t release apps on iPad before it’s fixed.

so could this be prioritized as it’s a very frequent crash issue?

Thanks.

**Comment by hartez** [comment] 2021-01-04 22:51
Seems to only happen on iOS 13+.

**Comment by jantanis** [comment] 2021-01-05 06:42
> I’m suffering of this too and it’s a very frequent crash, to the point that I wouldn’t release apps on iPad before it’s fixed.

Have you tried without using the formsheet @Tommigun1980? That worked for us.

**Comment by Tommigun1980** [comment] 2021-01-05 07:58
> > I’m suffering of this too and it’s a very frequent crash, to the point that I wouldn’t release apps on iPad before it’s fixed.
> 
> Have you tried without using the formsheet @Tommigun1980? That worked for us.

Thanks for the suggestion, but I’m tired of implementing everything in five ways until finding something that works and doesn’t crash. The problem is that I can’t really take any more compromises in the design or it will start to look like an app from 2010 so I’m waiting for a fix :/

**Comment by jantanis** [comment] 2021-02-01 14:07
Looks like #12300

**Comment by hartez** [comment] 2021-02-18 23:24
Closing this as a duplicate of #12300 so we can track everything in one place.

**Closed by hartez** 2021-02-18 23:24 UTC
Labels: e/5 :clock5:, i/high, iOS 13, iOS 14, p/iOS 🍎, p/tablet, t/bug :bug:
