### ISSUE TITLE
[Bug] InvalidCastException encountered when Entry control is bound to a style for a Label

### ISSUE THREAD

**Issue by wadebaird** [xamarin/Xamarin.Forms#6268] opened 2019-05-22 18:35 UTC
### Description
Binding a entry control to a style for a label that has properties that are not applicable to an Entry control causes an InvalidCastException. This should be caught at compilation time, or a minimum of a descriptive exception saying it is not correct to do this.

### Steps to Reproduce
1. Model a style for a label with a label only property:
`<Style x:Key="LeftLabel" TargetType="Label">
            <Setter Property="VerticalTextAlignment" Value="Center" />
        </Style>`
Bind an entry control to that style (or really any other type of control would probably do as well):
`<Entry Style="{StaticResource LeftLabel}"/>`
2. Run the app

### Expected Behavior
Compilation error should occur in this case.
Good runtime error should be raised in the case that this binding is performed through code instead of modeling.

### Actual Behavior
InvalidCastException:
 	0x0 in Xamarin.Forms.Label.OnVerticalTextAlignmentPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\Label.cs:324,4	C#
 	0x12E in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:624,5	C#
 	0x182 in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422,5	C#

on this line of code from Label.cs
    var label = (Label)bindable;

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: N/A
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 8.1

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by wadebaird** [comment] 2019-05-22 18:42
I am guessing this is also a problem on other properties.  All properties should be verified and corrected.

**Comment by kingces95** [comment] 2019-05-22 22:39
Please attached a zipped solution with a reproduction project. Thanks!

**Comment by samhouts** [comment] 2019-06-27 01:42
Duplicate of #6535

**Comment by wadebaird** [comment] 2019-06-27 04:29
Umm... this is the older bug.... how is it a duplicate of a newer logged one?

**Comment by samhouts** [comment] 2019-06-27 16:28
@wadebaird We're crazy like that :D   Actually, it's because the newer bug has an attached sample project, so it's easier for the developer to verify the fix. Thanks for reporting this!!!!

**Closed by samhouts** 2019-06-27 16:28 UTC
Labels: a/Xaml </>, a/style, e/2 :clock2:, i/high, t/bug :bug:
