### ISSUE TITLE
Add Web Project

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9476] opened 2020-02-07 20:35 UTC
Hi

As we now have iOS, Android and UWP projects as well as Watch and other platforms

It will be great if you add Web project so users can also have Web project from the same solutions and using the same tech with XAML and C#

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by samhouts** [comment] 2020-02-07 21:46
Duplicate of #1895

**Closed by samhouts** 2020-02-07 21:46 UTC
Labels: proposal-open, t/enhancement ➕
