### ISSUE TITLE
[Enhancement] Make Frame.CornerRadius as CornerRadius (implement ICornerElement )  to be able to control radius per each corner

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#7208] opened 2019-08-20 06:59 UTC
## Summary
Implement _ICornerElement_ interface as  in BoxView and make Frame.CornerRadius as CornerRadius to be able to control radius per each corner.
This can help make custom Frame shapes.

## API Changes
``` cs
public CornerRadius CornerRadius { get;set; }
```

**Comment by Mikilll94** [comment] 2019-11-21 17:01
Any update on this?

**Comment by samhouts** [comment] 2020-02-12 20:18
Duplicate of #1814

**Closed by samhouts** 2020-02-12 20:18 UTC
Labels: proposal-open, t/enhancement ➕
