### ISSUE TITLE
[Bug] NavigationPage Bug with Animation (Blank Screen)

### ISSUE THREAD

**Issue by PeterLinecker** [xamarin/Xamarin.Forms#15129] opened 2022-02-08 12:20 UTC
If you use a NavigationPage and navigate to a page with animation: Navigation.PushAsync(new Page1(), true)
then pop the page without animation: Navigation.PopAsync(false); you get a blank page.
The other way around it works normal.
The bug only occurs on android devices.

### Steps to Reproduce

1.  Make a new Xamarin.Forms project
2.  Set MainPage = new NavigationPage(new MainPage()) 
3.  Make a second page (Page1)
4.  Navigate from the MainPage to the second page (Page1) with animation: Navigation.PushAsync(new Page1(), true)
5.  In Page1 pop the page without animation: Navigation.PopAsync(false);

### Expected Behavior
Blank screen

### Basic Information

- Version with issue: >5.0.0.2196
- Last known good version: 4.8.0.1821
- Platform Target Frameworks: 
  - Android: 10
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment] 2022-02-09 09:21
Duplicate of #14994

**Closed by jfversluis** 2022-02-09 09:22 UTC
Labels: t/bug :bug:, s/unverified
