### ISSUE TITLE
Custom view rendering issue occurs when converting the Xamarin Forms Switch control from Forms to native view in android platform

### ISSUE THREAD

**Issue by Eswaran17392** [xamarin/Xamarin.Forms#5456] opened 2019-03-05 14:17 UTC
### Description
Custom view rendering issue occurs when converting the Xamarin Forms Switch control from Forms to native android platform. 

### Basic Information
We have a custom control in which we use the below code to convert the Xamarin Forms view to native view in iOS platform. When trying to convert the switch control I am getting a null reference exception. 

Code:
```csharp
public static IVisualElementRenderer Convert(Xamarin.Forms.View source, Xamarin.Forms.VisualElement valid)
		{
			IVisualElementRenderer render = (IVisualElementRenderer)source.GetValue(RendererProperty);
			if (render == null)
			{
                object oldBindingContext = source.BindingContext;
                source.Parent = valid;
                if (oldBindingContext != null && source.BindingContext.ToString() != oldBindingContext.ToString())
                {
                    source.Parent.BindingContext = oldBindingContext;
                }

				render = Platform.CreateRenderer(source);
				source.SetValue(RendererProperty, render);
			}

			return render;
		}
````

**Comment by kingces95** [comment] 2019-03-06 02:30
Could you please include a zipped solution that includes your custom renderer that exhibits the unexpected behavior you're observing?

**Comment by Eswaran17392** [comment] 2019-03-29 13:04
Hi Kingces95,

Please have the solution from the below link. 

Solution Link: [](http://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample_(4)251856686 )

Converting the view from forms to native works correctly in the Xamarin version 2.4.0.280 but the reported issue occurs only in the latest Xamarin forms. We suspect that the issue is occurred due to the latest of Xamarin Forms.

**Comment by samhouts** [comment] 2019-04-09 00:19
@Eswaran17392 I think that's the wrong link. I am seeing a DrawerControl, and the only projects are Android, not iOS.

**Comment by samhouts** [comment] 2019-04-09 00:22
Hmm, ok, I guess you misreported it as iOS, since I see the problem in Android.

**Comment by samhouts** [comment] 2019-04-09 00:22
Duplicate of #5553

**Closed by samhouts** 2019-04-09 00:22 UTC
Labels: i/regression, p/Android, partner, t/bug :bug:

**Comment by samhouts** [comment] 2019-04-10 00:16
@Eswaran17392 I've verified that #5851 will fix the `NullReferenceException`. You will then hit a new exception: `Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference`. This is because you are using `Forms.Context` and `Platform.CreateRenderer`. Please use the Android View's `Context` and `Platform.CreateRendererWithContext` to resolve this issue. Also note that this exception only occurs when you are using the SplashScreen.

**Comment by Eswaran17392** [comment] 2019-04-22 09:57
@samhouts, We have checked the provided code changes with the latest Xamarin Forms preview version. We have tried to change the code, but unfortunately, we have only got the "int java.lang.CharSequence.length()' on a null object reference" exception. Can you please change the provided code changes in our attached sample and share us. I will help a lot to us.

**Comment by samhouts** [comment] 2019-04-22 17:45
@Eswaran17392 Hope this helps! I strongly recommend that SyncFusion update all controls to use a local Context like this. It *will* cause strange behavior if you try to keep using `Forms.Context`. Thanks!

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3104304/App1.zip)
