### ISSUE TITLE
Listview binding without template 

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#4426] opened 2018-11-15 12:45 UTC
### Description

Was looking at some samples and when using the ModalNavigation on 3.0.0 I could see all items in a Listview. Updating to a more recent version the Text for each cell stop showing up. Instead on the logs I can see this:

```
Binding: John Doe can not be converted to type 'System.String'
Binding: John Smith can not be converted to type 'System.String'
Binding: Kath Smith can not be converted to type 'System.String'
Binding: Steve Smith can not be converted to type 'System.String'
```

### Steps to Reproduce

1. Open Modal sample with 3.0.0 
2. Open Modal sample with 3.4.0-pre2

### Expected Behavior
Both should show the same listview with items

### Actual Behavior
Sample in 3.4.0 doesn't show the items 

### Basic Information

- Version with issue: 3.4.0-pre2
- Last known good version: 3.0.0
- IDE: vs4mac
- Platform Target Frameworks:
  - Android:
  - iOS

### Screenshots

<img width="508" alt="screenshot 2018-11-15 at 12 42 33" src="https://user-images.githubusercontent.com/1235097/48553692-266a1f80-e8d4-11e8-9c90-89e5359cf96b.png">
<img width="520" alt="screenshot 2018-11-15 at 12 40 52" src="https://user-images.githubusercontent.com/1235097/48553693-266a1f80-e8d4-11e8-84ce-fda2ea7f6c70.png">

### Reproduction Link

[Modal.zip](https://github.com/xamarin/Xamarin.Forms/files/2585320/Modal.zip)

**Comment by StephaneDelcroix** [comment] 2018-11-15 12:51
according to @rmarinho, it's no longer present in `master`

**Comment by rmarinho** [comment] 2018-11-15 12:53
yea I copied the pages to master, and it worked there. at same time didn't work with the nightly so I was confuse. 
Could be android playing me tricks also.

**Comment by StephaneDelcroix** [comment] 2018-11-16 10:34
and it works fine on iOS...

**Comment by StephaneDelcroix** [comment] 2018-11-16 12:33
dupe of #3715

**Closed by StephaneDelcroix** 2018-11-16 12:33 UTC
Labels: a/binding ⛓, a/listview, i/regression, p/Android
