### ISSUE TITLE
Crash Xamarin Forms in Android <= 6.0

### ISSUE THREAD

**Issue by flaviogf** [xamarin/Xamarin.Forms#2175] opened 2018-03-23 20:42 UTC
occurs when the user quickly returns through the NavigationPage stack

Exception:

android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.LabelRenderer from native handle 0xbea265fc (key_handle 0x1f64cd9). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.LabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
                                                                --- End of inner exception stack trace ---
                                                               at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                                --- End of inner exception stack trace ---
                                                               at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                                 at (wrapper dynamic-method) System.Object.d4b5c8af-5212-461e-b172-51f8d975839f(intptr,intptr,intptr)
                                                             --- End of stack trace from previous location where exception was thrown ---
                                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
                                                               at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <3cb12bce834a498199b2be6cd3e00922>:0 
                                                               at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <3cb12bce834a498199b2be6cd3e00922>:0 
                                                               at Android.Views.ViewGroup.RemoveAllViews () [0x0000a] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00088] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
                                                               at Java.Lang.Object.Dispose () [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0007b] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
                                                               at Java.Lang.Object.Dispose () [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Xamarin.Forms.Platform.Android.ListViewRenderer.ClearRenderer (Android.Views.View renderedView) [0x00036] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
                                                               at Xamarin.Forms.Platform.Android.ListViewRenderer.Dispose (System.Boolean disposing) [0x0002a] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
                                                               at Java.Lang.Object.Dispose () [0x00000] in <ff199c98c3f84852925dd37a0ef6113a>:0 
                                                               at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0007b] in <173f39d71f0d4d928f5bbea42e96ffa8>:0 
                                                               at Xamarin.Forms.Platform.Android.PageRenderer.Dispose (System.Boolean disposing) [0x00011] in <173f39d71f0d4d

**Comment by pauldipietro** [comment] 2018-03-23 20:52
Please attach a reproduction when able as well as verify if the latest 3.0.0-pre doesn't resolve your issue.

**Comment by jassmith** [comment] 2018-04-07 04:35
This looks like the ListView issue that was fixed, closing unless a repro is provided.

**Closed by jassmith** 2018-04-07 04:35 UTC
Labels: i/critical, p/Android, s/needs-repro, t/bug
