### ISSUE TITLE
NCrunch fails to build project

### ISSUE THREAD

**Issue by powerdude** [xamarin/Xamarin.Forms#3249] opened 2018-07-09 17:03 UTC
##Summary
Prior to 3.1(at least with 2.4), one could use NCrunch to do unit testing.  Now, NCrunch fails to build the project if it has a XAML file in it and the project uses `XamlCompilation` attribute.  What has changed in the tooling to now cause this error with every view:
```
App.xaml (0, 0): Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

##API Changes

none
##Intended Use Case
faster velocity with unit testing

[NCrunchBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2177233/NCrunchBug.zip)

**Comment by pauldipietro** [comment] 2018-07-11 17:49
Unsure of how to proceed so this could possibly be marked as needs info until we find out if they're related.

**Comment by PureWeen** [comment] 2018-07-16 22:16
http://forum.ncrunch.net/yaf_postsm12200_ncrunch-cant-build-Xamarin-Forms-3-0.aspx#post12200

**Comment by StephaneDelcroix** [comment] 2018-07-25 12:31
dupe of #3004

**Closed by StephaneDelcroix** 2018-07-25 12:31 UTC
Labels: e/5 :clock5:, i/low, s/duplicate, t/enhancement ➕
