### ISSUE TITLE
Compiled binding fails when the sub-property of a Path is a different type to x:DataType

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3614] opened 2018-08-20 11:15 UTC
### Description

A compiled binding with a binding source should presumably be compiled using a `x:DataType` with the type of the `x:Reference`. However, in the BoxView example below the compiler can't resolve the sub-property of the binding path:

```
    <Grid Margin="5">
        ...
        <ListView x:Name="colorListView" 
                  Grid.Row="0"
                  ItemsSource="{x:Static local:NamedColor.All}"
                  RowHeight="40">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="local:NamedColor">
                    ...
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

       <BoxView x:DataType="ListView"
                     Grid.Row="1"
                     Color="{Binding Source={x:Reference colorListView},
                                 Path=SelectedItem.Color}" />        
    </Grid>
```

`SelectedItem` is a property on the `ListView`, with `Color` being a property of `NamedColor`.

### Steps to Reproduce

1. Attempt to build the attached sample.

### Expected Behavior

Sample builds and the `CompiledColorListPage`, which uses compiled bindings, can be executed.

### Actual Behavior

Sample fails to build with error message: Binding: Property `Color` not found on `System.Object`.

### Basic Information

- Version with issue: 3.2.0.729530-pre2
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  Not tried.
- Android Support Library Version: 27.0.2

### Reproduction Link

[DataBindingDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/2302115/DataBindingDemos.zip)

**Comment by StephaneDelcroix** [comment] 2018-08-21 07:35
dupe of #3606

**Closed by StephaneDelcroix** 2018-08-21 07:35 UTC
Labels: a/Xaml </>, a/binding ⛓, s/duplicate
