### ISSUE TITLE
Xamarin.Forms problem with ScrollView - when the content is scrolled, it is impossible to focus the right fields or click or right button.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11180] opened 2020-06-23 15:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1087530/xamarinforms-problem-with-scrollview-when-the-cont.html)._

---
I have a form with multiple Entry fields, and the page is in ScrollView. When i try to click on (for example) 3rd entry, it clicks on the 1st one, when I click on 4th it clicks on second, and if I scroll even further, as further as I click, the distance from the right field is bigger. This has happened to me after the latest update of Xamarin.Forms nugget package.

---
#### Visual Studio Feedback System on 6/22/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### anisa.ciric on 6/23/2020, 01:40 AM: 

<p>To confirm that this is a problem, i downgraded Xamarin.Forms versions, and there, it works fine :)</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-06-23 17:40
On what platform are you experiencing this issue? Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment] 2020-06-23 17:43
I suspect this is a duplicate of #11106, but I'll wait until I hear what platform and version of Xamarin.Forms this is on. :)

**Comment by AnnieMonk** [comment] 2020-06-24 17:22
This is Xamarin.Forms version 4.6.0.968, and yes it is a duplicate, so I will comment there :)

**Comment by samhouts** [comment] 2020-06-26 20:09
Duplicate of #11106

**Closed by samhouts** 2020-06-26 20:09 UTC
Labels: a/entry, a/scrollview, feedback-ticket, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
