### ISSUE TITLE
[enhancement] Incorporate line number into compiled bindings error message

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1948] opened 2018-02-22 10:28 UTC
### Description

When a XAML file contains a binding error, which is reported when using compiled bindings, the error message doesn't specify the line number in the XAML file that contains the binding error.

### Steps to Reproduce

1. Build the attached sample.

### Expected Behavior

Sample fails to build and returns an error message indicating the line in the XAML file containing the binding error.

### Actual Behavior

Sample fails to build and reports a binding error with no indication where it is within the file.

### Basic Information

- Version with issue: 2.6.0.200305-nightly
- IDE: VSMac 7.3.3
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: API 26

### Reproduction Link

[CompiledBindings.zip](https://github.com/xamarin/Xamarin.Forms/files/1747490/CompiledBindings.zip)

**Comment by MelbourneDeveloper** [comment] 2018-02-23 04:03
Yeah, we also need the line and column number when there is an exception dynamically rendering XAML inside the app as well. In Silverlight, when there is a XAML error, we get the line and column editor. That allows our XML syntax highlighting control to move the cursor to where the XAML bug is like in Visual Studio. It's very useful so you don't have to sift through tonnes of XAML.

**Comment by StephaneDelcroix** [comment] 2018-02-23 08:12
@MelbourneDeveloper error reporting for dynamically loaded xaml is another topic. please open a new issue.

**Comment by StephaneDelcroix** [comment] 2018-04-24 09:08
dupe of #2517.

**Closed by StephaneDelcroix** 2018-04-24 09:08 UTC
Labels: a/Xaml, duplicate, t/enhancement
