### ISSUE TITLE
MaterialCustomRenderer seems will never been called

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#7310] opened 2019-08-29 07:23 UTC
### Description

I'm trying to customise an Entry field for iOS platform with Visual=Material enabled.

I tried via CustomRenderer but since is iOS platform. But it never been called in runtime .

```
[assembly: ExportRenderer(typeof(Entry), typeof(CustomMaterialEntryRenderer), new[] { typeof(VisualMarker.MaterialVisual) })]

    public class CustomMaterialEntryRenderer : MaterialEntryRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (Control == null || e.NewElement == null) return;

            Layer.BorderColor = Color.FromHex("#cedee7").ToCGColor();
        }
    }
```

- Version with issue:
- Last known good version:
- IDE: VS2019 for window
- Platform Target Frameworks: 
  - iOS:  12.1 and 12.4
  

### Reproduction Link

https://stackoverflow.com/questions/57687779/is-there-any-way-to-customise-a-control-style-in-ios-using-material-visual

**Comment by rmarinho** [comment] 2019-08-29 16:46
Dupe of #6939

**Closed by rmarinho** 2019-08-29 16:46 UTC
Labels: s/unverified, t/bug :bug:
