### ISSUE TITLE
Xamarin.forms add support for LineBreakMode in Button

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#3290] opened 2018-07-13 07:12 UTC
### Description

Add Support for LineBreakMode in Button it is expanding more line like 2 -3 depends on content 

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment] 2018-07-13 10:43
Possible duplicate of #3106

**Comment by samhouts** [comment] 2020-02-12 20:09
Duplicate of #3106

**Closed by samhouts** 2020-02-12 20:09 UTC
