### ISSUE TITLE
[Enhancement] Context Menu (activated via long-press/right-click)

### ISSUE THREAD

**Issue by SmartmanApps** [xamarin/Xamarin.Forms#9540] opened 2020-02-12 10:46 UTC
## Summary
As far as I can see, context menus are only currently supported in a ListView. I have a need to bring them up in an Entry, and can easily see uses for it in Buttons and Labels as well. e.g. there is currently no way for a user to copy/paste text from a Label in a Xamarin app (I have a partial work-around of I just automatically put the most recent output into Clipboard so that users can paste that. e.g. when they get an error message). Context menu should be activated via long-press on mobile, and right-click on desktop.

## API Changes
1. need LongPress events (which I can see is close to ready xamarin/Xamarin.Forms#3480)
2. need RightClick events. As far as I can tell, not currently supported.
3. add ContextActions to Entry, Label, Button, etc.

## Intended Use Case
The most obvious example is copy/paste text from screen. Select required text, from a Label say, then long-press/right-click brings up context menu from which one can select copy/cut/paste/share etc. Another case is an Entry for barcodes, where one can type in barcode, or (hopefully) do a long-press/right-click and activate a barcode scanner which upon scanning then puts the barcode into the Entry (I'd like to do this directly, but happy to do it from a context menu as that has wider applications, though an option to do directly if only 1 item in the context menu would be good to bypass that step. i.e. just bring up the menu if it contains more than 1 option, otherwise directly run the 1 defined option).

**Comment by samhouts** [comment] 2020-02-12 15:51
Duplicate of #5883

**Closed by samhouts** 2020-02-12 15:51 UTC
Labels: proposal-open, t/enhancement ➕

**Comment by SmartmanApps** [comment] 2020-02-12 18:30
Thanks @samhouts When I created this, it said there were 4 "similar" issues, but that wasn't one of them, so I never saw it (seems to have an interesting idea about what "similar" is).
