### ISSUE TITLE
[Bug] CollectionView items does not always snap on Android

### ISSUE THREAD

**Issue by vikern22** [xamarin/Xamarin.Forms#9986] opened 2020-03-17 12:10 UTC
### Description
In a CollectionView using LinearItemsLayout(ItemSpacing="10", Orientation="Vertical", SnapPointsAlignment="Start", SnapPointsType="Mandatory") snapping works as expected on the iOS platform, but has a more random behavior on the Android platform.

### Steps to Reproduce

1. Run the attached sample on Android
2. Do some different swipes(short, long, swipe half of the item out of visible area)

### Expected Behavior
The item closest to the top of the visible area should align with the top of the visible area(like on iOS).

### Actual Behavior
Some times it aligns, some times nothing happens.

### Basic Information

- Version with issue: 4.5.0.396
- Last known good version:
- IDE: VS 2019 Enterprise
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: 10
- Nuget Packages: NETStandard.Library, Xamarin.Essentials, Xamarin.Forms
- Affected Devices: Pixel 2 emulator, Galaxy Note 4

### Screenshots

[https://drive.google.com/open?id=1--JqmAfZsSPUp0vdpwcgDGU-vDwidNjd](url)

### Reproduction Link

[https://drive.google.com/open?id=1Ci6NjRY9KvE3RbYSDZQ4f0pV1IsGY_LN](url)

**Comment by vikern22** [comment] 2020-03-18 08:53
@jfversluis Tagged with s/needs-info, anything more you need from me?

**Comment by jfversluis** [comment] 2020-03-18 09:29
Hey @vikern22! So sorry, I must've not submitted my comment or mixed up my open browser tabs or something sorry about that.

Trying to retrace my steps here... I do see it happening, I also found this issue #8608 does that describe the same problem?

**Comment by vikern22** [comment] 2020-03-18 09:47
@jfversluis No problem! I ran the repro project on my Android emulator, and it looks and feels similar.

**Comment by jfversluis** [comment] 2020-03-18 09:50
Alright, I'm closing this one then as a duplicate. If you have any additional info over the other one, please add it to that. This way we won't have information scattered over multiple issues describing the same. Having another reproduction certainly helps though, so thank you!

**Comment by jfversluis** [comment] 2020-03-18 09:50
Duplicate of #8608

**Closed by jfversluis** 2020-03-18 09:50 UTC
Labels: a/collectionview, p/Android, s/needs-info ❓, s/unverified, t/bug :bug:
