### ISSUE TITLE
The custom text field doesn't scroll the view to the top of the Keyboard

### ISSUE THREAD

**Issue by RubaShanmugamm** [xamarin/Xamarin.Forms#11006] opened 2020-06-10 12:24 UTC
### Description

The custom text field doesn't scroll the view to the top of the Keyboard when we tap.

### Steps to Reproduce

Run the below sample in iOS
https://www.syncfusion.com/downloads/support/directtrac/general/ze/TextField-1559863123 

1. Tap the last text field on the view.
2. Notice the view doesn't scroll to the top of the keyboard.

### Expected Behavior

The text field needs to be scrolled to the top of the keyboard.

### Actual Behavior

The text field doesn't scroll to the top of the keyboard.

### Basic Information

Xamarin: 4.6.0.847

iOS simulator version: iPhone X iOS 11.4

### Reproduction Link

https://www.syncfusion.com/downloads/support/directtrac/general/ze/TextField-1559863123

**Comment by hartez** [comment] 2020-06-10 23:28
I would suggest following the instructions on line 46 of TextField.cs in your sample project:

> //// Uncomment the below line and comment the 40th line, it's working.

I did, and the field scrolled up as expected.

You've written a completely custom control, and you seem to know how to make it work the way you want it to. What exactly are you asking us to do?

**Comment by RubaShanmugamm** [comment] 2020-06-11 05:30
**As I want the text field needs to be scrolled up when it's added into the view also.**

**Comment by hartez** [comment] 2020-06-12 15:17
This issue tracker is for bugs with Xamarin.Forms. What you have submitted is not a bug in Xamarin.Forms. You have written a completely custom custom iOS control which does not work. I would suggest finding an appropriate forum for asking questions about how to write custom iOS controls. 

If you can give us a sample, reproduction, or any information at all which tells us why a bug in Xamarin.Forms is preventing you from implementing your custom control, please do so; we will do our best help you. Until then, I am closing this issue.

**Closed by hartez** 2020-06-12 15:17 UTC
Labels: a/entry, p/iOS 🍎, s/unverified, t/bug :bug:
