### ISSUE TITLE
[Bug] [UWP] Stepper display error when using Slider

### ISSUE THREAD

**Issue by wangguan1888** [xamarin/Xamarin.Forms#7361] opened 2019-09-03 07:31 UTC
### Steps to Reproduce

1. Create MainPage.xaml
`    <ContentPage.Content>
        <StackLayout Padding="12,12,12,12">
            <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                <Slider x:Name="Slider1" Maximum="100" Minimum="1" ValueChanged="SliderChanged" HorizontalOptions="FillAndExpand"
                        MinimumTrackColor="LightPink" MaximumTrackColor="LightPink"/>
                <Stepper x:Name="Stepper1" Maximum="100" Minimum="1" Increment="1" 
                         ValueChanged="StepperChanged" HorizontalOptions="End"/>
            </StackLayout>
            <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                <Label Text="Value:" FontSize="Large"/>
                <Label x:Name="ShowValue" FontSize="Large"/>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>`
2. Create MainPage.xaml.cs
public MainPage()
        {
            InitializeComponent();

            Stepper1.Value = 50;
            Slider1.Value = 50;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
        }

        private void SliderChanged(object sender, ValueChangedEventArgs e)
        {
            Stepper1.Value = e.NewValue;
            ShowValue.Text = e.NewValue.ToString();
        }

        private void StepperChanged(object sender, ValueChangedEventArgs e)
        {
            Slider1.Value = e.NewValue;
            ShowValue.Text = e.NewValue.ToString();
        }
3. Using Slider to Max
4. Using Slider to Min
5. Using Slider to Center

### Expected Behavior
Stepper shall be displayed like the following image.
![normal](https://user-images.githubusercontent.com/44393281/64152423-8d5ac400-ce67-11e9-97fa-8dee00c8502d.PNG)

### Actual Behavior
Stepper display error is occured. It looks like the value is Maximum and Minimum.
I can push "+" and "-" to change value, but the backcolor cannot be changed after the error.
![display_error](https://user-images.githubusercontent.com/44393281/64151892-4f10d500-ce66-11e9-8f35-68db8275b53a.PNG)

### Basic Information
Xamarin.Forms: 4.2.0.709249
Platform;UWP
Windows:10

**Comment by samhouts** [comment] 2019-09-10 01:19
@wangguan1888 

This displayed according to your expected behavior for me:

![image](https://user-images.githubusercontent.com/7827070/64576513-c5617b80-d32d-11e9-91e0-404f9eff8b65.png)

Can you please alter the attached project such that it demonstrates the behavior you're experiencing? Thanks!

[Issue7361.zip](https://github.com/xamarin/Xamarin.Forms/files/3593198/Issue7361.zip)

**Comment by ZhuMingHao** [comment] 2019-09-10 07:48
> @wangguan1888
> 
> This displayed according to your expected behavior for me:
> 
> ![image](https://user-images.githubusercontent.com/7827070/64576513-c5617b80-d32d-11e9-91e0-404f9eff8b65.png)
> 
> Can you please alter the attached project such that it demonstrates the behavior you're experiencing? Thanks!
> 
> [Issue7361.zip](https://github.com/xamarin/Xamarin.Forms/files/3593198/Issue7361.zip)

I check your repro demo, please drag the cursor to max then to min, the stepper will dark.

**Comment by samhouts** [comment] 2019-09-10 23:00
@wangguan1888 Ah, got it. Thanks.

Looks like the Stepper doesn't like having a non-integer value assigned to it when the increment is an integer. If you `Math.Round` the value set by the slider, it works as expected.

**Comment by WayaFlyfeather** [comment] 2019-10-24 05:11
> @wangguan1888 Ah, got it. Thanks.
> 
> Looks like the Stepper doesn't like having a non-integer value assigned to it when the increment is an integer. If you `Math.Round` the value set by the slider, it works as expected.

Actually, the problem occurs when the Stepper's buttons are disabled more than once - then it can't become disabled again. This doesn't happen in normal stepper usage, but when set from the slider's movements it does. But your Math.Round prevented this from happening, as the value wasn't changed more than once :)

**Comment by CliffAgius** [comment] 2019-10-25 08:14
I have a PR that should fix this #7383

**Comment by WayaFlyfeather** [comment] 2019-10-25 08:37
@CliffAgius No, that would be unrelated to this issue, I'm pretty sure. This error happens because, in the UWP implementation of the Stepper it kepps an internal cache of the state of the + and - buttons. And when these are disabled more than once, the enabled state is overwritten by the disabled state. So when it should go back to being enabled, the cache with the disabled state is used - and it is never enabled again.

I made a PR, #8191, where it is only disabled once, that should hopefully fix it.

**Comment by CliffAgius** [comment] 2019-10-25 09:35
Ah ok I see the issue now, teach me to jump in ;-)

**Comment by samhouts** [comment] 2019-12-06 19:39
closed by #8191

**Closed by samhouts** 2019-12-06 19:39 UTC
Labels: e/2 :clock2:, i/low, in-progress, p/UWP, t/bug :bug:
