### ISSUE TITLE
Shell: ContentTemplate not firing Appearing on Pages

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#6586] opened 2019-06-19 15:03 UTC
_I'm not sure if this is a bug or feature that I don't understand._
 
I'm experimenting with Shell. In this example I have some pages set to **ContentTemplate**. Only the first page gets it's Appearing event fired.

Shell.xaml clip:

    <FlyoutItem Route="main"
            Title="Main"
            FlyoutDisplayOptions="AsMultipleItems">

    <Tab Title="Animals"
                 Route="animals"
                 Icon="tab_1.png">

                    <ShellContent Route="tags"
                                  Style="{StaticResource MainShell}"
                                  Title="Topics"
                                  Icon="tab_a.png"
                                  ContentTemplate="{DataTemplate prayerviews:TopicPage}" />
                    <ShellContent Route="groups"
                                  Style="{StaticResource MainShell}"
                                  Title="All"
                                  Icon="tab_s.png"
                                  ContentTemplate="{DataTemplate prayerviews:AllPage}" />
    </Tab>
Both pages **TopicPage** and **AllPage** have **Appearing** events handled, but only **TopicPage's**, the first page, gets fired.

How can I be notified that **AllPage** is showing once selected on a top tab so that I can load the time-expensive Model ?

Appearing **is** fired:

    public TopicPage() 
    {
        InitializeComponent();
        BindingContext = App.IoCContainer.GetInstance<TopicViewModel>();

        Appearing += async (sender, args) =>
        {
            await Refresh();
            base.OnAppearing();
        };
    }
Appearing is **NOT** firing:

    public AllPage()
    {
        InitializeComponent();
        BindingContext = App.IoCContainer.GetInstance<AllViewModel>();

        Appearing += async (sender, args) =>
        {
            await Refresh();
            base.OnAppearing();
        };
    }

##Environment

VS 2019 PC
iOS: Newest
Android: Newest

##reproduction

Download Xaminal demo project. Add Appear event handlers.

**Comment by PureWeen** [comment] 2019-06-19 16:51
duplicate of https://github.com/xamarin/Xamarin.Forms/issues/6486 

Should be fixed by https://github.com/xamarin/Xamarin.Forms/pull/6527

**Closed by PureWeen** 2019-06-19 16:51 UTC
Labels: a/shell :shell:, p/iOS 🍎, t/bug :bug:
