### ISSUE TITLE
[Bug] disposed object. Object name: 'Xamarin.Forms.Platform.Android.SwipeViewRenderer

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#11407] opened 2020-07-11 18:39 UTC
### Description

```
<ScrollView>
            <StackLayout VerticalOptions="StartAndExpand" >
                <StackLayout BindableLayout.ItemsSource="{Binding CreditCards}" Padding="8" BindableLayout.ItemTemplate="{StaticResource CreditCardTemplate}"/>
                <StackLayout VerticalOptions="End">
                    <buttons:SfButton Style="{StaticResource GradientButton}" Text="Add Card" Command="{Binding AddCardCommand}" >
                        <buttons:SfButton.BackgroundGradient>
                            <gradient:SfLinearGradientBrush>
                                <gradient:SfLinearGradientBrush.GradientStops>
                                    <gradient:SfGradientStop Color="{StaticResource GradientStartColor}" Offset="0"/>
                                    <gradient:SfGradientStop Color="{StaticResource GradientStopColor}" Offset="1"/>
                                </gradient:SfLinearGradientBrush.GradientStops>
                            </gradient:SfLinearGradientBrush>
                        </buttons:SfButton.BackgroundGradient>
                    </buttons:SfButton>
                </StackLayout>
            </StackLayout>

        </ScrollView>


 <DataTemplate x:DataType="models:CreditCard" x:Key="CreditCardTemplate">
            <SwipeView>
                <SwipeView.LeftItems>
                    <SwipeItems Mode="Execute">
                        <SwipeItem Text="Remove" BackgroundColor="Transparent" IconImageSource="delete.png" Command={Binding RemoveCommand}   />
                    </SwipeItems>
                </SwipeView.LeftItems>
                ... 
            </SwipeView>
        </DataTemplate>`

```
### Steps to Reproduce
Try to remove item form the list, produces exception 

> disposed object. Object name: 'Xamarin.Forms.Platform.Android.SwipeViewRenderer

### Basic Information

- Version with issue: 4.7
- IDE: VS 2019

**Comment by jsuarezruiz** [comment] 2020-07-13 10:47
After complete some test, can confirm the issue is the same as #11262 and will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/11279

**Closed** 2020-07-21 00:05 UTC
Labels: a/bindablelayout, a/swipeview, e/1 :clock1:, i/high, in-progress, p/Android, t/bug :bug:
