### ISSUE TITLE
[Bug] Xamarin.Forms label and button show flashing cursors (before and/or after the controls) when page appearing

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/Xamarin.Forms#10400] opened 2020-04-21 10:34 UTC
### Description
Xamarin.Forms label and button show flashing cursors (before and/or after the controls) for 1-2 secs when page appearing, and disappear after that. The label and button are just regular Xamarin.Forms controls (not 3rd party controls)
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio for mac (8.5.3 build 16)
- Platform Target Frameworks: 
  - Android: 10.0
- Android Support Library Version: 
- Nuget Packages: 28.0.0.3
- Affected Devices: Samsung A20, Samsung S7 and emulators 
Xamarin.Forms: 4.5.0.530

### Screenshots

<
![image](https://user-images.githubusercontent.com/8989917/79856028-20ecff00-840f-11ea-9de9-9cdf3d09b319.png)

!
![image](https://user-images.githubusercontent.com/8989917/79856109-3c580a00-840f-11ea-8af5-bb3fff09567a.png)
-- If the issue is a visual issue, please include screenshots showing the problem if possible -->

### Workaround
Did try make the label/button disabled, not help.

**Comment by jsuarezruiz** [comment] 2020-04-21 11:13
@KevinHu-au Are those labels and buttons inside a template in a CollectionView (or CarouselView)?. In this case, this issue seems to be the same as #7281 or #10294.

**Comment by eriktack** [comment] 2020-04-21 22:44
This happens to me if i have a grid inside a collectionview with any row using GridUnitType.Absolute for height, so labels in this row will have the "cursor":
new RowDefinition{Height = new GridLength(20, GridUnitType.Absolute)}
but not labels inside this:
new RowDefinition{Height = GridLength.Star}, // or auto

**Comment by Kubion70** [comment] 2020-04-22 16:58
This workaround may help you with labels.
Create class in android project:

```csharp
public class CustomLabelRenderer : Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer
{
    public CustomLabelRenderer(Context context)
        : base(context)
    {
    }

    protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
    {
        base.OnElementChanged(e);

        if (Control == null)
        {
            return;
        }

        Control.HorizontalScrollBarEnabled = false;
        Control.VerticalScrollBarEnabled = false;
    }
}
```

Then add to android project AssemblyInfo (or over created class namespace if you wish) following code:

```csharp
[assembly: ExportRenderer(typeof(Label), typeof(CustomLabelRenderer))]
```

**Comment by KevinHu-au** [comment] 2020-04-22 22:09
> @KevinHu-au Are those labels and buttons inside a template in a CollectionView (or CarouselView)?. In this case, this issue seems to be the same as #7281 or #10294.

There is not a CollectionView or CarouselView on this page. But I do use PancakeViews (https://github.com/sthewissen/Xamarin.Forms.PancakeView) for the white blocks.

The above screen has UI hierarchy roughly like this. Each white block is a pancake view with a bunch of labels
<Grid>
    <Grid.RowDefinitions>
         <RowDefinition Height="*"/>
         <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>
     <ScrollView>
          <StackLayout>
                <pancake:PancakeView>
                         <StackLayout> 
                                <Label  ..../>
                         </StackLayout>
                </pancake:PancakeView>

                <pancake:PancakeView>
                         <StackLayout> 
                                <Label  ..../>
                         </StackLayout>
                </pancake:PancakeView>
          </StackLayout>
     </ScrollView>

      
      <Button Grid.Row="1"/>
</Grid>

**Comment by KevinHu-au** [comment] 2020-04-22 22:18
> This workaround may help you with labels.
> Create class in android project:
> 
> ```cs
> public class CustomLabelRenderer : Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer
> {
>     public CustomLabelRenderer(Context context)
>         : base(context)
>     {
>     }
> 
>     protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
>     {
>         base.OnElementChanged(e);
> 
>         if (Control == null)
>         {
>             return;
>         }
> 
>         Control.HorizontalScrollBarEnabled = false;
>         Control.VerticalScrollBarEnabled = false;
>     }
> }
> ```
> 
> Then add to android project AssemblyInfo (or over created class namespace if you wish) following code:
> 
> ```cs
> [assembly: ExportRenderer(typeof(Label), typeof(CustomLabelRenderer))]
> ```

@Kubion70 . Thanks for your recommendation. I definitely will have a try and let you know the result.

**Comment by KevinHu-au** [comment] 2020-04-23 01:41
Did the same for button to fix this issue

**Comment by samhouts** [comment] 2020-04-23 17:22
Duplicate of #9019

**Comment by samhouts** [comment] 2020-04-23 17:22
Duplicate of #9591

**Closed by samhouts** 2020-04-23 17:22 UTC
Labels: p/Android, s/needs-info ❓, s/unverified, t/bug :bug:

**Comment by eriktack** [comment] 2020-04-23 19:09
Thanks @Kubion70, that will work for me until a proper fix is out.
