### ISSUE TITLE
[Bug] Default Picker BackgroundColor doesn't change with Visual.Material

### ISSUE THREAD

**Issue by luismts** [xamarin/Xamarin.Forms#13299] opened 2021-01-06 03:11 UTC
### Description
The default Picker BackgroundColor doesn't change with Visual.Material. Default color is **gray**.

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.1829-pre6
- Last known good version: Xamarin.Forms 4.8
- Platform Target Frameworks: 
  - Android: 11.0
- Android Support Library / AndroidX Version: v1.2

### Workaround
```
[assembly: ExportRenderer(typeof(Picker), typeof(CustomPickerRenderer), new[] { typeof(VisualMarker.MaterialVisual) })]
namespace ProjectName.Droid.Renderers
{
    public class CustomPickerRenderer : MaterialPickerRenderer
    {
        public CustomPickerRenderer(Context context) : base(context) { }

        protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            base.OnElementChanged(e);

            // Workaround: Background doesn't change
            Control?.EditText.SetBackgroundColor(Android.Graphics.Color.Transparent);
        }
    }
}
```

**Comment by rachelkang** [comment] 2021-01-06 16:09
Hi, @luismts - thanks for submitting this issue! This seems like it might be related to #13229 
Could you try reverting to an older version of Xamarin.Google.Android.Material (i.e. v1.0.0.1) for now and seeing if that works? Thanks :)

**Comment by luismts** [comment] 2021-01-06 21:27
Workaround working as expected but got this beautiful warning with Xamarin.Forms 5:
![image](https://user-images.githubusercontent.com/20643876/103821283-4163f480-5044-11eb-98eb-341600d3c8df.png)

**Note**: newest versions don't work. 

Thanks @rachelkang!

**Comment by luismts** [comment] 2021-01-06 21:29
Just to mention: It happens with `Entry `and `Picker`.

**Comment by Juanoxt890** [comment] 2021-01-07 00:17
Same here! 
When update to **Xamarin.Forms 5.0.0.1874** oficial and **Xamarin.Forms.Visual.Material 5.0.0.1874** 

Now can't set Transparent Background Color, it shows by default **White Color** on Light Mode and **Black Color** in Obscure Mode of the device.

I try to  reverting to an older version of Xamarin.Google.Android.Material (i.e. v1.0.0.1) but it result in **failed linking references**.

![image](https://user-images.githubusercontent.com/17001084/103834740-e0d7b600-5049-11eb-9186-16a4b8b8ff68.png)

@samhouts @rachelkang

**Comment by luismts** [comment] 2021-01-07 15:44
yep, @Juanoxt890. You can not use Xamarin.Forms.Visual.Material with Xamarin.Google.Android.Material 1.0.0.1 because of the style references.

You have some options here:

1. Downgrade your Xamarin.Forms.Visual.Material to 4.8 as a workaround with Xamarin.Google.Android.Material 1.0.0.1 too. But you get the little warning in the same way. 
2. Or you can update all your packages and add the renderer. Here we have a weird behavior because it also reduces the spacing between the title and the text.

The library itself seems to have some bugs over there. 

What we can in this case? Scale the issue to the [AndroidX](https://github.com/xamarin/AndroidX/) repository?

@samhouts @rachelkang @jsuarezruiz

**Comment by rachelkang** [comment] 2021-02-02 17:26
Thanks for the updates! Has anyone tried updating to the most recent version of XF? (5.0.0.1931)
If so, are you still experiencing these issues? Please let us know, thanks :)

**Comment by luismts** [comment] 2021-02-03 14:29
The issue is gone with XF 5.0.0.1931

Going to close this issue.

**Comment by YouWannaKnowMySecretIdentity** [comment] 2021-02-05 22:00
I updated to XF 5.0.0.1931 and still hitting this issue with the Entry and Picker controls. Attached is a screenshot and sample project that reproduces the issue.

![image](https://user-images.githubusercontent.com/8899090/107093334-adb05000-67ca-11eb-926e-4516745673dc.png)

[NoItIsnt.zip](https://github.com/xamarin/Xamarin.Forms/files/5935553/NoItIsnt.zip)

**Comment by luismts** [comment] 2021-02-06 05:20
Do you have XF and XF.Visual updated @YouWannaKnowMySecretIdentity?

**Comment by YouWannaKnowMySecretIdentity** [comment] 2021-02-08 13:38
@luismts Yes. I updated whatever was available to update in NuGet.

Xamarin.Essentials 1.6.1
Xamarin.Forms: 5.0.0.1931
Xamarin.Forms.Visual.Material: 5.0.0.1931

![image](https://user-images.githubusercontent.com/8899090/107226877-4bc93380-69e0-11eb-8e97-4d0274d8d4fa.png)

**Comment by matteopiccioni** [comment] 2021-02-12 11:23
I have the same problem. All updated.

**Comment by luismts** [comment] 2021-02-12 13:46
In my case, the background was gray. Now is white as I need. Maybe I need to test again and see

**Comment by JunkyXL86** [comment] 2021-02-18 14:38
Same problem here, transparent background color is not applied to Entry.

Using currently latest Xamarin.Forms and Material packages 5.0.0.2012

![trpcy](https://user-images.githubusercontent.com/3984217/108372585-439e9e80-71ff-11eb-9388-bb59c0a34f07.jpg)

**Comment by luismts** [comment] 2021-02-19 00:33
I haven't tested on my own, but seeing some people having the same problem I'm going to open this issue again.

**Comment by LittleBoxOfChicken** [comment] 2021-03-01 10:51
I'm encountering this issue as well

Xamarin.Forms: 5.0.0.1931
Xamarin.Forms.Visual.Material: 5.0.0.1931

<img width="288" alt="Screen Shot 2021-03-01 at 11 48 02" src="https://user-images.githubusercontent.com/26085789/109487046-fda9cc00-7a83-11eb-9bef-1a9467fe20d6.png">

<details>
<summary></summary>
I can't believe that this has been going on for so long without being fixed... Classic Xamarin really
</details>

**Comment by PureWeen** [comment] 2021-03-04 00:14
Closing for now. The transparent issue is being tracked here https://github.com/xamarin/Xamarin.Forms/issues/13922

**Closed by PureWeen** 2021-03-04 00:14 UTC
Labels: a/picker, a/visual, s/needs-info ❓, s/unverified, t/bug :bug:

**Comment by fabiansanchez18** [comment] 2022-10-24 20:09
Try something like this. It is based on the original workaround from #13229 
### More Cleaner Workaround
I think that this is how it was supposed to be, since original workaround here posted, make default Transparent. This way maintains the theme's background color unless another one is specified. It is based on the original Entry Render.
```
[assembly: ExportRenderer(typeof(Entry), typeof(App.MyMaterialEntryRenderer), new[] {typeof(VisualMarker.MaterialVisual)})]
namespace App.Droid
{
	public class MyMaterialEntryRenderer : MaterialEntryRenderer
	{
		public MyMaterialEntryRenderer(Context context) : base(context)
		{
		}
		protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
		{
			base.OnElementChanged(e);			
			Control?.ApplyBackgroundColor(((VisualElement)((VisualElementRenderer<Entry>)(object)this).Element).BackgroundColor, ((InputView)((VisualElementRenderer<Entry>)(object)this).Element).TextColor);
 		}
	}
}
```
