### ISSUE TITLE
[Enhancement] ListView 'Orientation', 'AnimationFlowLayout', 'NoBounce', 'UnselectableCell',  'SelectColor' features

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#3161] opened 2018-06-27 10:44 UTC
### Description
ListView needs missing features
(Orientation property , NoBounce property, UnselectableCell property, Flow Animation)

We need a customisable List View on smartphones. (RecyclerView and UICollectionView)

### Steps to Reproduce
Implement a ListView
Figure it out that you can't change the Orientation
Realize that you can't stop bouncing when scrolling on IOS
Dawn on that you never gonna have animated scrolling Flow between Cells.

### Expected Behavior
A great implementation, with some customisable properties available
_Orientation
_NoBounce property
_UnselectableCell property
_SelectColor property
_AnimationFlowLayout (we need something to manage the scrolling Flow layout)
_Using RecyclerView and UICollectionView on native side.

### Actual Behavior
We are stuck to do customs renderers for common properties
But the slide gestures is awesome!

### Basic Information
Version with issue: Current
Last known good version:
IDE: Visual Studio for Mac
iOS: Last One
Android: Last One

### Screenshots
none

**Comment by charlesroddie** [comment] 2018-06-27 12:10
The orientation request is a dupe of https://github.com/xamarin/Xamarin.Forms/issues/2680 .

The others could get one or more separate issues, but @clovs please think much harder before posting. This is just a stream of consciousness.

**Comment by clovs** [comment] 2018-06-27 12:32
What about 'AnimationFlowLayout', 'NoBounce', 'UnselectableCell', 'ColorSelection'?

**Comment by charlesroddie** [comment] 2018-06-27 12:39
You haven't described them, haven't described the current status and desired outcome, haven't described what you can do on native platform controls. You mention smartphones and ios without making it clear to what extent your request is phone- or ios-specific.

**Comment by clovs** [comment] 2018-06-27 12:59
First of all i'm sorry for bothering you,
My Issue only refer to ListView.

When I said "Smartphone", is a handheld mobile operating system (know so far IOS and Android)
On native development we use RecyclerView on Android and UICollectionView IOS for hight customisable Horizontal/Vertical ListView. so forget about scrollView.

My issue is about performing ListView Component by adding 
a Bounce property, UnselectableCell property, SelectedCellColor property,
And the best of all is to add a way to customise the AnimationFlowLayout when scrolling
by using UICollectionViewFlowLayout on IOS and extends ViewGroup on Android.

Regards,

**Comment by samhouts** [comment] 2019-02-05 20:17
These features should target CollectionView. We have no plans to add significant features to ListView. If you feel these features are missing from the spec, please leave a comment at #3172. Thank you!

**Closed by samhouts** 2019-02-05 20:17 UTC
Labels: t/enhancement ➕

**Comment by Phenek** [comment] 2019-03-15 15:10
#3172
