### ISSUE TITLE
[Bug] On<iOS>().SetHideNavigationBarSeparator(true) does not work on Xamarin.Forms latest stable version (4.5.0.356) and latest preview version (4.6.379-pre1)

### ISSUE THREAD

**Issue by Carl-Wen** [xamarin/Xamarin.Forms#9952] opened 2020-03-13 04:13 UTC
### Description
[Bug] On<iOS>().SetHideNavigationBarSeparator(true) does not work on Xamarin.Forms latest stable version (4.5.0.356) and latest preview version (4.6.379-pre1), it works well on 4.4.0.991757. The result of two ways below is the same.

``` C#
{
                var x = Xamarin.Forms.Application.Current.MainPage as Xamarin.Forms.MasterDetailPage;
                var y = x.Detail as Xamarin.Forms.NavigationPage;
                y.On<iOS>().SetHideNavigationBarSeparator(true);
}
```
or 
``` C#
using SpeedUp.iOS.Renderers;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(NavigationPage), typeof(MyNavigationRenderer))]
namespace SpeedUp.iOS.Renderers
{
	public class MyNavigationRenderer : NavigationRenderer
	{
		protected override void OnElementChanged(VisualElementChangedEventArgs e)
		{
			base.OnElementChanged(e);

			NavigationBar.ShadowImage = new UIImage();
		}
	}
}
```

- IDE: Visual Studio Community 2019 for Mac
Version 8.4.8 (build 2)
- Platform Target Frameworks: 
  - iOS:  11.3.3

**Comment by StephaneDelcroix** [comment] 2020-03-13 12:40
could you please add a small reproduction project ? thanks

**Comment by Carl-Wen** [comment] 2020-03-14 14:15
@StephaneDelcroix Here it is.
[NavigationBarSeparator.zip](https://github.com/xamarin/Xamarin.Forms/files/4332861/NavigationBarSeparator.zip)

**Comment by beeradmoore** [comment] 2020-03-16 19:58
Duplicate of #9456 ?

**Comment by Carl-Wen** [comment] 2020-03-17 02:07
> Duplicate of #9456 ?

Seems like yes.

**Closed** 2020-03-23 12:20 UTC
Labels: i/regression, in-progress, p/iOS 🍎, s/unverified, t/bug :bug:
