### ISSUE TITLE
[Bug] VS 2019 default Mobile App not rendering correct

### ISSUE THREAD

**Issue by tokotech** [xamarin/Xamarin.Forms#12865] opened 2020-11-16 13:07 UTC
Using VS 2019 16.8.1 with Xamarin.iOS 14.4.1.3.

Start VS and create a new Mobile App (Xamarin Forms) for IPhone

Build and Deploy to IPhone with iOS 14.2

Render like this where eks Label controls is not showing

![xamarinabout](https://user-images.githubusercontent.com/6986751/99255938-f16f6b00-2814-11eb-86e1-5411bd874a5b.jpg)

![xamarinbrowser](https://user-images.githubusercontent.com/6986751/99255959-f6341f00-2814-11eb-8fac-635be5bf2bf9.jpg)

![xamarinadd](https://user-images.githubusercontent.com/6986751/99255982-fc2a0000-2814-11eb-8c45-8e959c4b8e99.jpg)

**Comment by jsuarezruiz** [comment] 2020-11-17 08:49
The issue is related to not changing the background color of the page automatically using the dark theme. Labels use a light color, Entries a dark background, etc. but the page still uses light color. For that reason, no texts etc. are seen.

This issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/12409

**Closed** 2021-02-04 16:40 UTC
Labels: a/darkmode, e/1 :clock1:, p/iOS 🍎, t/bug :bug:
