### ISSUE TITLE
[Bug] CollectionView/CarouselView scrolls not smoothly

### ISSUE THREAD

**Issue by Huaba93** [xamarin/Xamarin.Forms#9556] opened 2020-02-13 12:21 UTC
### Description
The experience with scrolling is very bad because it often bounces/jerks instead of scrolling smoothly. It can already be seen in very simple layouts. For more complex layouts the problem is even worse. The problem also occurs on flagships like the Galaxy S10. These devices should have more than enough power for 100% smooth scrolling.

### Steps to Reproduce
1. Deploy sample project
2. Scroll fast or scroll slow, it will sometimes bounce. Especially when it slowly scrolls out --> See provided screencasts. 

### Expected Behavior
Smooth scrolling.
### Actual Behavior
It's jerking / jumping ... it's just not feeling smooth.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991640
- Last known good version: -
- IDE: Visual Studio Community 2019 for Mac (Version 8.4.3 (build 12))
- Platform Target Frameworks:
  - iOS: it seems to be not a problem on iOS, but I only tested with iPhone 11 Pro
  - Android: 5.0+
- Affected Devices (tested on):
  - Huawei Mate 20 Pro
  - Huawei P9 Plus
  - Samsung Galaxy S10

### Screencasts & Reproduction Link
[See all](https://www.dropbox.com/sh/ves7bed3sret5jo/AACPJmY2V9Cr5wH1pjY7_BCea?dl=0)

**Comment by samhouts** [comment] 2020-02-13 18:01
Duplicate of #8718

**Closed by samhouts** 2020-02-13 18:01 UTC
Labels: a/carouselview, a/collectionview, a/performance, p/Android, s/unverified, t/bug :bug:
