### ISSUE TITLE
[Bug] Xamarin.Forms 4.2 has broken custom animations using Xamarin.Forms.Animation

### ISSUE THREAD

**Issue by radderz** [xamarin/Xamarin.Forms#7417] opened 2019-09-06 04:04 UTC
### Description
On android and possibly others Animations no longer fire after updating to Forms 4.2

### Steps to Reproduce

1. use Animation.commit, animation finishes straight away with a false completion.

### Expected Behavior
Animation would fire action multiple times throughout the animation

### Actual Behavior
Animation ends instantly and calls finished with false completion.

### Basic Information

- Version with issue: 4.2
- Last known good version: 4.1
- IDE:
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Affected Devices: Samsung S10+, maybe others

**Comment by FIELDPOINT** [comment] 2019-09-06 14:30
I am seeing the same problem. I can confirm the error goes away if I revert back to 4.1

**Comment by samhouts** [comment] 2019-09-06 16:12
Duplicate of #7291

**Closed by samhouts** 2019-09-06 16:12 UTC
Labels: a/animation 🎬, i/regression, p/Android, s/unverified, t/bug :bug:
