### ISSUE TITLE
[Bug] [UWP] DisplayAlert renders all controls disabled on a page

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#9756] opened 2020-02-27 16:23 UTC
### Description

DisplayAlert renders all controls disabled on a page in UWP

### Steps to Reproduce

1. Create a blank Xamarin.Forms project with UWP enabled
2. Add a DispalyAlert anywhere
3. Once DisplayAlert is fired, all of the controls are disabled and the prompt never displays. 

### Expected Behavior

Alert should appear and controls shouldn't be disabled

### Actual Behavior

Alert does not appear and controls get disabled

### Basic Information

- Version with issue:  4.5.0.356
- Last known good version: 4.4.0.991757
- IDE: Visual Studio 2019 (Windows)
- Platform Target Frameworks: 

  - UWP:  1803 (Build 17134)

### Screenshots

![image](https://user-images.githubusercontent.com/5879559/75463186-5af4d400-597d-11ea-9e79-4287a54ed9af.png)

![image](https://user-images.githubusercontent.com/5879559/75463225-69db8680-597d-11ea-8a5c-0b15d85938c1.png)

**Comment by bmacombe** [comment] 2020-02-27 20:55
Duplicate of #9606

**Comment by justremotephone** [comment] 2020-02-28 10:11
Oh no....

Normally I do not write such comments,

but how could it be, that the Bug is known 14 days for the pre-release and 4.5 is released with such a show stopper?!!!

We have just updated to 4.5 and now we can perform a rollback to 4.4. How many time is wasted all over the world because of such low quality updates!!!

I am not sure if Xamarin-Forms is the right platform for us. And this after 3 years of coding....

Regards,
Thomas.

**Comment by amirvenus** [comment] 2020-02-28 11:15
> Oh no....
> 
> Normally I do not write such comments,
> 
> but how could it be, that the Bug is known 14 days for the pre-release and 4.5 is released with such a show stopper?!!!
> 
> We have just updated to 4.5 and now we can perform a rollback to 4.4. How many time is wasted all over the world because of such low quality updates!!!
> 
> I am not sure if Xamarin-Forms is the right platform for us. And this after 3 years of coding....
> 
> Regards,
> Thomas.

Hey! 
Look for the bright side of the things! There are many new features in 4.5 including the media player 

I think XF team give little attention and love to UWP, WPF and macOS platforms so it won't surprise me if UWP ends up at the same place as Silverlight

**Comment by jsuarezruiz** [comment] 2020-03-02 13:23
This issue seems to be the same as #9606

**Comment by samhouts** [comment] 2020-07-13 21:04
Duplicate of #9606

**Closed by samhouts** 2020-07-13 21:04 UTC
Labels: 4.5.0, a/alerts, e/2 :clock2:, i/regression, p/UWP, t/bug :bug:
