### ISSUE TITLE
[Bug] Android CollectionView: ObjectDisposedException after changing ItemTemplate

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#8435] opened 2019-11-08 15:13 UTC
### Description
If data in the collection (through binding) changes after the ItemTemplate has been changed, then I get an ObjectDisposedException. 
In the template I use a custom ContentView that has a label. It is this label that generates the exception, if the Text-property is changed.
As long as the template has not yet been changed, you can change data as you like with no exceptions.
But after the template has been changed, you get the exception. This happens not always. 
I finally managed to make a small reproduction project to demonstrate this issue (which already wasted a lot of my time). 
Sometimes by making some (seemingly unrelated) changes, the problem seemed to disappear. This is not well reproducible, but maybe with a little luck… I have commented in code three possible changes that can "solve" the problem, look for "//TODO FIX". At some point in time I could "prove" this very consistently, but afterwards not anymore.
This is very weird. 
Could be related to earlier issues posted by me: #7395 and #7943 (both already solved)
Only tested on an Android device.

### Steps to Reproduce

1. Open attached project
2. Press "Update data" as much as you like (or not). I have put some random numbers in the cells.
3. Press "Smaller Height…" and wait for the update to appear. This can take a few seconds.
4. Press "Update data" again and after one, or sometimes a few times, you get the exception. But again, if it doesn't happen, restart the app until it does.
5. Try to change the code as described in //TODO FIX1, //TODO FIX2 and //TODO FIX3. Maybe you don't get the exceptions anymore (of course this is not really a "fix")

### Expected Behavior
No exceptions
### Actual Behavior
Exception, but not always!
### Basic Information
{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <42bcf67b56bc4c909c2a5edee682522b>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <42bcf67b56bc4c909c2a5edee682522b>:0 
  at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence value) [0x00029] in <11a340ccc8de43f09c97400139266ef5>:0 
  at Android.Widget.TextView.set_Text (System.String value) [0x0000d] in <11a340ccc8de43f09c97400139266ef5>:0 
  at Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.UpdateText () [0x000f3] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:398 
  at Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00123] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:279 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:350 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:461 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x00042] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311 
  at Xamarin.Forms.Label.set_Text (System.String value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Label.cs:139 
  at CollectionViewIssue2.CollectionViewCell.TextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00002] in C:\Users\KM\source\repos\CollectionViewIssue2\CollectionViewIssue2\CollectionViewCell.xaml.cs:21 }

- Version with issue: 4.3.0.908675
- Last known good version:
- IDE: Visual Studio 2019 V16.3.6
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Tested on Samsung SM-T595

### Reproduction Link

[CollectionViewIssue2.zip](https://github.com/xamarin/Xamarin.Forms/files/3825072/CollectionViewIssue2.zip)

**Comment by hudaIT** [comment] 2019-11-08 15:29
Duplicate of #7510

**Comment by hudaIT** [comment] 2019-11-08 15:30
#7529

**Comment by geseru** [comment] 2019-11-22 11:44
I have the same problem with V4.3.0.991211 on Android.

**Comment by pmahend1** [comment] 2019-12-03 19:08
I see the same issue , First I had used label inside a frame

Later changed everything to button still has issues 

`FastRenderer` has to be fixed

**Closed** 2019-12-09 10:55 UTC
Labels: e/5 :clock5:, in-progress, p/Android, t/bug :bug:
