### ISSUE TITLE
Xamarin Forms Button some Shadow above the button on tapping

### ISSUE THREAD

**Issue by ajeetsri2006** [xamarin/Xamarin.Forms#3220] opened 2018-07-05 06:19 UTC
### Description
There is some shadow will come when we tap the button which will half of the button width around and come top left side of that button. This effect is reproducible on Samsung S8 and Samsung Tab S3 as well. 
### Steps to Reproduce

1.  Create as Xamarin form page
2. Create any button and give some dark background color
3.  Tap and hold the button and see the effect

### Expected Behavior
No Overlay shadow should come.
### Actual Behavior
Overlay shadow which comes above the button and cover half of the button width.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  9.0 to latest
  - Android: Android 5.0 To Android 8.1 
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices: Samsung S8 and Samsung Tab S3

### Screenshots
![test project button](https://user-images.githubusercontent.com/40848725/42305621-5a3b3a90-8049-11e8-94ff-8c0f2acad526.jpg)

**Comment by hartez** [comment] 2018-07-05 14:40
@ajeetsri2006 I'm trying to reproduce the behavior you are seeing, but so far I am not able to. Could you post a minimal reproduction project, or at least the XAML you are using to create this layout?

**Comment by hartez** [comment] 2018-07-06 15:46
@ajeetsri2006 Never mind, I stumbled on a way to reproduce it while working on another issue. I'll upload a repro project shortly.

**Comment by hartez** [comment] 2018-07-06 15:51
[_3220 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2171102/_3220.Repro.zip)

**Comment by ajeetsri2006** [comment] 2018-07-17 08:03
Hi,
Is there any update on that? It is resolved or you are not able to reproduce?

**Comment by SokHeangKhun** [comment] 2018-07-26 09:22
Hey there I'm waiting for this fix. Is it done?

**Comment by lake-fall** [comment] 2018-07-26 14:01
Is this bug in Xamarin.Forms? Or is it a Xamarin.Android.Support package that can be rolled back temporarily?

**Comment by ajeetsri2006** [comment] 2018-07-30 11:07
Hi ,
This issue is in Xamarin Forms Button. Even if you create normal Xamarin Forms project with PCL library same issue will be replicated for the mention devices (i.e. Samsung S8 and Samsung Tab S3)

**Comment by georgethms10** [comment] 2018-08-02 14:30
@pauldipietro Is there any workaround for now, any update regarding this bug would be helpful.

**Comment by lake-fall** [comment] 2018-08-14 10:59
Pretty sure this is a duplicate of #2096 .

**Comment by anee146** [comment] 2018-09-14 08:56
Is there any update on this issue?

**Comment by xXdRaGoNrIdDeRXx** [comment] 2018-09-23 17:05
Do we have an eta for this issue fix?

**Comment by leeanpeng** [comment] 2018-09-24 02:26
> Do we have an eta for this issue fix?

I wish to know too, it's been few months

**Comment by mzhukovs** [comment] 2018-10-24 10:04
Any updates?

**Comment by AxelUser** [comment] 2018-10-24 17:47
Hi, I've also faced the same issue on Samsung Galaxy A5.

**Comment by standamikes** [comment] 2018-12-05 11:58
look at here #2096

**Comment by jlzapata** [comment] 2019-07-04 02:35
The issue is still happening.

**Comment by dkarapapas** [comment] 2019-12-05 21:23
With me happens when i add a background color or a Border Radius. (Galaxt S7).

**Comment by xXdRaGoNrIdDeRXx** [comment] 2019-12-06 14:00
happening for me with image buttons

`<ImageButton x:Name="btnContacts" Grid.Column="1" Source="ic_action_contacts" HorizontalOptions="CenterAndExpand" WidthRequest="35" Visual="Material" Command="{Binding NavigationCommand}" CommandParameter="Contacts"/>`

still has issue with latest Xamarin forms / visual.material: 4.3.0.991221

**Comment by PureWeen** [comment] 2020-02-27 00:17
duplicate https://github.com/xamarin/Xamarin.Forms/issues/2096

**Closed by PureWeen** 2020-02-27 00:17 UTC
Labels: e/3 :clock3:, help wanted, p/Android, t/bug :bug:, up-for-grabs
