### ISSUE TITLE
Xaml compilation causes error: "No property, bindable property, or event found for 'DisplayBinding', or mismatching type between value and property.'"

### ISSUE THREAD

**Issue by JayaramanAyyanar** [xamarin/Xamarin.Forms#3814] opened 2018-09-18 06:37 UTC
### Description
When I set the Xaml compilation to compile, it causes the error with " No property, bindable property, or event found for 'DisplayBinding', or mismatching type between value and property". 
### Steps to Reproduce

1. Build the Portable solution Project.
2. You would experience the reported error in the error list.

### Expected Behavior
When building the PCL solution project, it should not cause an error when XamlCompilation is set as Compile.
### Actual Behavior
When building the PCL solution project, it causes an error when XamlCompilation is set as Compile.
### Basic Information

- Version with issue: Xamarin.forms 2.4.0.280
- IDE: Visual Studio 2017

### Screenshots
![image](https://user-images.githubusercontent.com/38308497/45668536-bbea6c80-bb3a-11e8-92b1-da2cfc45fe77.png)

### Reproduction Link
[DataGridSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2391421/DataGridSample.zip)

**Comment by MichaelRumpler** [comment] 2018-10-12 13:33
I get the same error with Xamarin.Forms 3.0.0.561731.

**Comment by StephaneDelcroix** [comment] 2018-10-13 11:36
does this happen with netstandard2.0 projects too ?

**Comment by MichaelRumpler** [comment] 2018-10-13 18:47
Yes. I made a repro project with .NET Standard 2.0 and Xamarin.Forms 3.3.0.893527-pre3 and it behaves the same.

But I also found the problem. The `Syncfusion.SfDataGrid.XForms.GridColumn.DisplayBinding` is of type `Xamarin.Forms.Binding`. It should actually be an `object`.

So IMHO this is a bug in Syncfusions SfDataGrid. But somehow it works without XAMLC.
But I may be wrong.

[Repro_SfDataGrid_DisplayBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/2475732/Repro_SfDataGrid_DisplayBinding.zip)

**Comment by Suhasini-Suresh** [comment] 2018-10-16 07:42
The type of the property Syncfusion.SfDataGrid.XForms.GridColumn.DisplayBinding is “Binding”, as we have taken the source property of the binding and binded it to the UI loaded in each cell of the SfDataGrid. The UI loaded in each column is different, the binding expressions will be processed and set in the run time for the bindable properties in each UI. However if we change its type as object, then also we should cast it as Binding type and then use it. So, it may be a workaround to fix this issue in SfDataGrid, but it is not the solution. 

Since this works without XAMLC. It should also work with XAMLC. So, in our humble request, this is the issue in Xamarin.Forms and we request the Xamarin team to fix this issue.

**Comment by StephaneDelcroix** [comment] 2018-10-16 15:01
I'm going to close this issue for the following reason:

- the repro you provided doesn't contains all the sources I'd need for a full investigation, if you need to report issue in the future, or reopen this one, please create a project that doesn't depend on third party closed nugets, but include the full source in the solution;
- the canonical example for setting a displayBinding is https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ListView.cs#L116-L131 and has been there since forever;
- the `{Binding}` markup extension returns a `BindingBase` since the beginning of times as well;
- the fact that you choose to expose the property with `Binding` as a type prevents any 3rd party Binding system, prevents compiled Bindings from working, prevents future types of Binding as well (think MultiBinding). Incidentally, it prevents being set by a `{Binding}` markup extension, as they're known to return a `BindingBase`, and there's no casting from BindingBase to Binding;
- the fact that it works with non-compiled Xaml is pure luck, and only happens when the BindingExtension returns an actual Binding, and not another subclass of BindingBase (https://github.com/xamarin/Xamarin.Forms/blame/master/Xamarin.Forms.Xaml/MarkupExtensions/BindingExtension.cs#L38);
- we also do not consider this a regression. Even though XamlC used to be turned off in the templates, it has been there since a long time, and you should have tested your control with it.

Hope all of this helps

**Closed by StephaneDelcroix** 2018-10-16 15:01 UTC
Labels: a/Xaml </>, a/binding ⛓, e/7 :clock7:, excellent-report, t/bug :bug:

**Comment by suriyaKalidoss123** [comment] 2019-02-07 11:10
Hi @JayaramanAyyanar ,
Epdee iruka ??
