### ISSUE TITLE
Can't use .NET Standard with MasterDetailPage consistently

### ISSUE THREAD

**Issue by jakubsuchybio** [xamarin/Xamarin.Forms#1787] opened 2018-02-02 22:25 UTC
### Description
When I create blank Xamarin.Forms project with .NET Standard shared library and I replace default MainPage with new MasterDetailPage created from New File selector. Then when I use Live Player it compiles and correctly shows on android phone. HOWEVER, when I create folder for example "Views" and move all classes that were created with MasterDetailPage and try to compile it again I get
```
Start (App1.Android, LGE Nexus 5 Player, ).
Attempting connection to debug address: 192.168.88.227:37847.
Connected to: 192.168.88.227:37847.
Deploying C:\dev\csharp\App1\App1\App1.Android\App1.Android.csproj...
Got device info: LGE Nexus 5 Player (Android) @ 192.168.88.227:37847
Synchronizing files...
Building and running...
Built with 1 messages.
(1,1): error: Dependent project App1.csproj failed to build, using old version.
Failed to debug your app.
```
But the craziest thing is, that when I move those MasterDetailPage files back from Views folder it is still not deployable and gives the same message... REALLY ANNOYING. I just spent 4 hours trying to figure out why my app couldn't be send to Live Player and I narrowed it down to this ridiculousness.

### Steps to Reproduce

1. Create Blank Xamarin Forms with .NET Standard shared library via New Project, Xamarin.Forms Template
2. Remove MainPage.*
3. Add MasterDetailPage named for example AppMasterDetailPage, it creates like 7 files (root, master, detail and menuitem pages and class)
4. Fix reference in App.xaml.cs from removed MainPage to AppMasterDetailPage
5. Deploy via Live Player and verify that it works
6. Create folder "Views" and move all AppMasterDetailPage* files into it
7. Deploy via Live Player and verify that it doesn't work
8. Move AppMasterDetailPage* files from folder "Views" back into projectroot folder
9. Deploy via Live Player and verify that it doesn't work

### Expected Behavior
I would at least expected that when I have it in one state that works and I get it back to that state it works again. And definitely not that it doesn't work afterwards...

### Actual Behavior
Obviously I would expect it to work from projectroot always and also from Views folder. Why doesn't it work?

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: dunno
- IDE: VS2017 15.5.6
- Platform Target Frameworks: 
  - Android: none works, tried few of them
- Nuget Packages: NETStandard.Library, Xamarin.Forms
- Affected Devices: dunno Android LGE Nexus 5 Player

### Screenshots
![](https://i.imgur.com/itpjnGA.png)

**Comment by davidortinau** [comment] 2018-02-03 20:15
Can we see your csproj file? I suspect there may be some bad references in there causing a conflict as a result of the file move.

**Comment by jakubsuchybio** [comment] 2018-02-04 11:00
I don't think that is the case. I just tried it again. Make snapshots of csproj files of shared+android projects. (see the zip file)
zip structure:
clean new - just after xamarin.forms solution creation - working
before moving - after adding MasterDetailPage via Add - working
after moving - after moving MasterDetailPage to folder ```Views``` - not working
after moving back - after moving MasterDetailPage to project root and removing ```Views``` folter - not working

[csproj tests.zip](https://github.com/xamarin/Xamarin.Forms/files/1692704/csproj.tests.zip)

Before moving and after moving back csproj files are identical. So that is why I think that this is not problem with csproj files.
My uneducated guess is, that there are some cached compilation files, that are not updated properly which results in being unable to build. But that is just a guess in the wild.

**Comment by jakubsuchybio** [comment] 2018-02-05 18:21
So after googling again I can see that I am not alone. A LOT of ppl have the same issue...
For example:
https://stackoverflow.com/questions/47872757/xamarin-dependent-project-failed-to-build
https://forums.xamarin.com/discussion/113686/error-on-build-dependent-project-apptest-csproj-failed-to-build-using-old-version

**Comment by jamesmontemagno** [comment] 2018-02-05 18:41
Can you go into the about section of the app and let me know what version you have?

We just rolled out updates this weekend for some fixes to this.

**Comment by jamesmontemagno** [comment] 2018-02-05 18:52
Following the steps I was able to reproduce this when I move the files to "View".

This looks as a cache issue. We seem to not be removing the files on the move so it keeps the files around and thinks there are two instances of it.  Deleting the app from the phone and re-installing will completely clear it out. Today we will get this fixed up and ship an update. Thanks for opening the bugzilla bug.

**Comment by jassmith** [comment] 2018-02-08 18:26
Closing as fixed (and invalid for the forms project)

**Closed by jassmith** 2018-02-08 18:26 UTC
Labels: s/needs-info, s/needs-repro

**Comment by M4gp13** [comment] 2018-02-13 20:33
Hi I believe I'm getting the same issue. I've tried the suggested fixes with no luck. I've attached my csproj. Any ideas?

[Uploading GameHookUP.Android.rar…]()

**Comment by jamesmontemagno** [comment] 2018-02-14 00:10
The latest version 1.5.X has these improvements when moving around files in the IDE

**Comment by dyardyGIT** [comment] 2018-04-03 18:33
Getting these errors
1) Error		Internal Build Error: Sequence point value is out of range.		1		
2) Error		Dependent project Cqrs.csproj failed to build, using old version.		1		
3) Error		The type or namespace name 'App' does not exist in the namespace 'Cqrs' (are you missing an assembly reference?)		1	C:\Temp\xamarin\20180320Cqrs\Cqrs\Cqrs\Cqrs.Android\MainActivity.cs	

Cqrs.App is the shared project and exists
4) Error		The type or namespace name 'Views' does not exist in the namespace 'Cqrs' (are you missing an assembly reference?)		1	C:\Temp\xamarin\20180320Cqrs\Cqrs\Cqrs\Cqrs.Android\Renderers\CustomNavigationPageRenderer.cs	

#3 and #4 are coming from android project...as it is having problem with building/deploying the shared project Cqrs

Xamarin live player is 1.5.196

Microsoft Visual Studio Enterprise 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

My shared project is net standard 2 (with masterdetail page)

**Comment by jamesmontemagno** [comment] 2018-04-03 18:39
See: https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations

**Comment by dyardyGIT** [comment] 2018-04-03 18:56
Looking at those limitations it appears my issue is "Custom Renderers are not supported." - but i just removed this renderer and still have the issue hmm


Based on hotel 360 I was using CustomNavigationPageRenderer. However it appears this customrenderer is in place is for this method (which seems to be redefining the containerarea for some reason)..do you what this renderer would be used for?


 protected override void OnLayout(bool changed, int l, int t, int r, int b)
        {
            base.OnLayout(changed, l, t, r, b);
            int containerHeight = b - t;
            PageController.ContainerArea = new Rectangle(0, 0, Context.FromPixels(r - l), Context.FromPixels(containerHeight));
            for (var i = 0; i < ChildCount; i++)            {
                AView child = GetChildAt(i);
                if (child is Toolbar)                {
                    continue;
                }
                child.Layout(0, 0, r, b);
            }
        }

**Comment by dyardyGIT** [comment] 2018-04-03 19:10
I to not be able to deploy from vs.net to android mot o g (5) plus for the same errors as above (sequence point value is out of range, using old version) errors as well.

**Comment by jamesmontemagno** [comment] 2018-04-03 19:25
I would need to look at the source code.

**Comment by dyardyGIT** [comment] 2018-04-03 19:53
Yes understood.  I have started from patterns within https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps (setting up the TinyIOC and Navigation/locater patters within).  Does this solution work for you in live player? (thanks)

**Comment by jamesmontemagno** [comment] 2018-04-03 20:47
They have a special design build: SmartHotel.Clients.Live.sln

**Comment by jamesmontemagno** [comment] 2018-04-03 20:48
It would be better to use just built in dependency service and features of forms, which is what the live player supports.

**Comment by BradleyEggers** [comment] 2018-06-22 08:16
I’m facing the same bug.
(xxxx.csproj failed to build, using old version.)
I had all my code working, and I decided to do some “cleanup,” and I changed the name of a file.
Ahhhhhh…..
I put it all back together, and the iPad is still good, but the Android won’t behave. 

[brad's.zip](https://github.com/xamarin/Xamarin.Forms/files/2126808/brad.s.zip)

**Comment by BradleyEggers** [comment] 2018-06-22 20:35
Any ideas?  I would love to finish this code.
