### ISSUE TITLE
[Bug] IsEnabled does not work for Button

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#6991] opened 2019-07-27 04:55 UTC
#6772 # Description
I have set IsEnabled="false" to a button. But it doesn't disable the button.

### Steps to Reproduce

1. Create a Button
2. add property **IsEnabled**
3.  set values ="false"

### Expected Behavior
Disable the button and should not fire click events

### Actual Behavior
Fires the click event

### Basic Information

- Version with issue: Xamarin.Forms 4.1
- Last known good version: 3.5
- IDE: Visual Studio 2017 Community/Enterprise
- Platform Target Frameworks: 
  - iOS:  12.3
  - Android: 9.0

- Android Support Library Version: v7
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: All

**Comment by jfversluis** [comment] 2019-07-28 10:43
Could you maybe create a small reproduction project that shows this problem? I’ve tried to create on myself but it seems to work in my case. Maybe we’re doing something different :)

Thanks!

**Comment by dwightbennett** [comment] 2019-07-29 14:56
Do you have a command bound on the button?  I've seen isenabled behave strangely if the button has a bound command. I believe it will look at the CanExcecute property on the command to decide if its enabled or not.

**Comment by JKennedy24** [comment] 2019-08-02 08:26
Heres a repo:

` <Button Text="test" BackgroundColor="Green" Command="{Binding Tapped}" CommandParameter="{Binding .}" **IsEnabled="False"** Margin="5,0,5,0">`

**Comment by jfversluis** [comment] 2019-08-02 08:28
Thanks @JKennedy24 as mentioned in my former comment, I have tried to reproduce it and failed to do so. That is the reason to ask for a small reproduction project so I can determine what I have done wrong and/or what other factors might be of influence here.

**Comment by JKennedy24** [comment] 2019-08-02 08:32
@jfversluis I think the issue you might not be able to replicate it is that the command property needs a valid binding to it. I think @dwightbennett might be right in saying that the command.Canexecute property is interfering.

i.e. in my example make sure the button is bound to a viewmodel with a valid Tapped property in it.

If you then break the binding and rename it to {Binding Tappe} you see the IsEnabled property takes precedence.

Hope that helps

**Comment by jfversluis** [comment] 2019-08-02 08:33
So then 

> the main bit being IsEnabled="False"

Is not the main bit but the binding is 😉

**Comment by JKennedy24** [comment] 2019-08-02 08:39
yep, sorry my bad. If you still can't replicate it give me a shout. I've also got my button in a popup page which may play a part. But I think it's just the button

**Comment by jfversluis** [comment] 2019-08-02 09:00
I think I've managed to reproduce it. However, the initial issue states that it did work in 3.5. I've downgraded this project to the latest 3.5 and it shows the exact same behavior?

[Repro6991.zip](https://github.com/xamarin/Xamarin.Forms/files/3460408/Repro6991.zip)

**Comment by JKennedy24** [comment] 2019-08-02 09:06
I'm testing on latest stable (4.1.0.618606). I downloaded your project and upgraded to that version and can confirm thats the behaviour I'm seeing.

**Comment by jfversluis** [comment] 2019-08-02 09:19
I will close this one, I see there has been an issue recorded for this already. Please follow the progress there.

**Comment by jfversluis** [comment] 2019-08-02 09:19
Duplicate of #4754

**Closed by jfversluis** 2019-08-02 09:19 UTC
Labels: s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:

**Comment by dwightbennett** [comment] 2019-08-02 14:01
So i do think there is a work around for this and its very odd.  You can get the IsEnabled property to bind properly if you put it after the command binding in the xaml.  Super weird right? I added a bindable bool to the project that @jfversluis added and created two buttons, one where the IsEnabled is the first property in the xaml and the one where its the last and when you run the project you'll see one button enabled and one button disabled.  [IsEnabled Example Project](https://primusstudio-my.sharepoint.com/:u:/g/personal/dwight_bennett_primusstudios_com/ESZGp4-rMQBNj1QB9N-dHj0B4Cg_FdhbJrTPW59mvEK6Ag?e=HNnoSw) @kgbuddhima @JKennedy24

**Comment by jfversluis** [comment] 2019-08-05 07:33
I understand how that can seem weird, but I think the explanation is pretty simple. It's all about the order in which the property values are applied. If you look at how the `Command` is implement, it just returns true for `CanExecute` whenever no condition is specified.

If the `Command` is assigned after the `IsEnabled` then it will override the `IsEnabled` value with true. If it is the other way around and `IsEnabled` is evaluated after you assign the `Command` the `IsEnabled` will be false. Good find though!

Please continue any further discussion in the linked issue above so it's easier to track this.

**Comment by tklempay** [comment] 2021-02-28 14:42
Running all of the latest and greatest with VS 2019 16.8.6 and Xamarin.Forms 5.0 and I just hit this bug.  I created a new Xamarin Forms Flyout Menu project and saw this bug as originally reported back in Summer 2019.

My ContentPage is pretty simple with 2 Pickers, a few Labels, an Entry, and a Button.
![image](https://user-images.githubusercontent.com/44921765/109422259-cdd9c600-79a8-11eb-843b-90f9a571b6a2.png)


In my original XAML, the Save button is ALWAYS enabled:
![image](https://user-images.githubusercontent.com/44921765/109422143-4ab87000-79a8-11eb-907d-8e21ca127dac.png)

Changing the order exhibits the same behavior, button is ALWAYS enabled:
![image](https://user-images.githubusercontent.com/44921765/109422116-2d83a180-79a8-11eb-9e14-112fdb000e1b.png)


Added a binding in my ViewModel with VMClass.SaveButtonEnabled always equal to false still leads to the same behavior, Save button is ALWAYS enabled:
![image](https://user-images.githubusercontent.com/44921765/109422063-fc0ad600-79a7-11eb-8777-7c92d56d524f.png)

I changed the order of the XAML and bingo!, the Save button is now correctly disabled!
![image](https://user-images.githubusercontent.com/44921765/109422021-c82fb080-79a7-11eb-91b3-893aed415dd7.png)

![image](https://user-images.githubusercontent.com/44921765/109422311-0b3e5380-79a9-11eb-9676-571b460c881e.png)
