### ISSUE TITLE
[Bug] Intellisense for bindings does not work if BindingContext is not set in Xaml

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Xamarin.Forms#6865] opened 2019-07-13 11:03 UTC
### Description

Intellisense for bindings does not work if BindingContext is not set in Xaml.
However if BindingContext is set in Xaml, autocompletion of binding properties from viewmodel does work.
I'd expect autocompletion to work when x:DataType is set (at page level, in xaml) even if BindingContext is only set in the code-behind, but it's not working.

### Steps to Reproduce

1. New xamarin forms app, new xaml page and its associated viewmodel.
2. Do not set the BindingContext in the xaml page.
3. Enable compiled bindings by setting x:DataType at xaml page level.
4. Try autocomplete when binding a viewmodel property.

### Expected Behavior

Autocomplete should work.

### Actual Behavior

Autocomplete does not work (unless BindingContext is set in xaml).

### Basic Information

- Version with issue: XF 4.1.0.581479
- IDE: VS 2019 16.1.6
- Platform Target Frameworks: N/A (netstandard forms project)

### Screenshots
![xaml-intellisense](https://user-images.githubusercontent.com/12516566/61170775-8782e980-a56e-11e9-81c6-3bed09587f08.png)

**Comment by jsuarezruiz** [comment] 2019-07-15 13:02
I can reproduce the same problem with VS 2019 16.1.6. I attach an example.
[Test6865.zip](https://github.com/xamarin/Xamarin.Forms/files/3392383/Test6865.zip)

**Comment by StephaneDelcroix** [comment] 2019-07-17 13:39
@mgoertz-msft: anything we can do here ??

**Comment by mgoertz-msft** [comment] 2019-07-17 13:52
We are currently investigating how we can make MVVM developers more productive. This could potentially be part of it, but we also want to be able to have a better "connection" (for the lack of a better term) between the view and the view model, which may make this unnecessary.

**Comment by haavamoa** [comment] 2019-08-13 20:03
I would love for you guys to have a look at how we would traditionally do it in WPF. In WPF we would do it by including this in the top of the Xaml file:
https://gist.github.com/haavamoa/494bb5e7786ff341ce3d52982572d3dd
What this give you is full intellisense and ignoring the constructor!

I have actually made it work with the exact same way by doing it in Forms. My problem was that a friend grabbed the forms repository on a Mac, and it would not build there.
So I fear that I have used something from the net framework package (?) that is not available on Mac. 

I totally agree with having this working when doing a `x:DataType` through, it would both force you to use compiled bindings as well as getting intellisense.

I tried to make @jamesmontemagno to use this during a Livestream : http://www.twitch.tv/jamesmontemagno/v/461649019?sr=a&t=4875s

Other sources
- https://stackoverflow.com/questions/29399157/how-do-i-specify-datacontext-viewmodel-type-to-get-design-time-binding-checkin/29399984
-https://adamprescott.net/2012/09/12/design-time-data-binding-in-wpf/

**Comment by haavamoa** [comment] 2019-08-13 20:25
Using `d:ContentPage.BindingContext` is okay in most situstions, but my problem with that way is that the viewmodel needs a empty constructor. This is rarely the case, because you normally would have constructor injection when doing MVVM. Now, you can create an extra constructor that is empty, but for me this is breaking MVVM. You change your viewmodel because the view needs it for intellisense, that makes no sense to me.

**Comment by StephaneDelcroix** [comment] 2019-08-14 09:44
@haavamoa I agree that you usually want ctor injection for your VM in normal forms application, but we dropped that requirement with Shell, as the queryAttributes are injected, by property, to the VM. Best of both world

**Comment by haavamoa** [comment] 2019-08-14 16:20
> @haavamoa I agree that you usually want ctor injection for your VM in normal forms application, but we dropped that requirement with Shell, as the queryAttributes are injected, by property, to the VM. Best of both world

Hello @StephaneDelcroix. That is a fair route to go regarding Shell. I still would love for you guys to check out the stuff that I mentioned in the above post regarding intellisense.

**Comment by InquisitorJax** [comment] 2019-09-05 11:26
@StephaneDelcroix you still need constructor injection with Shell - as there are other dependencies which are not navigation related (Repos / Apis / Services etc.)

**Comment by roubachof** [comment] 2019-09-06 09:29
Would be great if you could implement Blend DesignInstance mecanism to give Intellisense (as @haavamoa wrote it) while the team is taking time to work on the better View/ViewModel connection. For now, a bunch of us are stuck with Resharper on windows cause it's the only tool which implements it, and I will be so glad to uninstall this greedy fellow.

**Comment by ahmedalejo** [comment] 2020-02-21 08:55
Setting `x:DataType` should enable intellisense IMHO

**Comment by tranb3r** [comment] 2020-02-21 08:59
> Setting `x:DataType` should enable intellisense IMHO

Thank you. That's the reason why I've opened this ticket... 7 months ago !

**Comment by haavamoa** [comment] 2020-02-21 18:12
Try `x:DataType{x:Type ViewModel}`, that helps me get intellisense inside of `DataTemplates` now. The intellisense only work for `DataTemplate`  though :(

**Comment by ahmedalejo** [comment] 2020-02-21 20:06
@haavamoa wow that´s new. i thought it didn´t work at all.

thanks for the tip.

**Comment by haavamoa** [comment] 2020-02-21 23:34
Yeah, someone has added something to enable this because it did not work before. I noticed it a couple of weeks ago.

**Comment by ahmedalejo** [comment] 2020-02-22 09:41
@haavamoa by chance do you have link to the change it can help role out a fix for this.

**Comment by haavamoa** [comment] 2020-02-22 11:39
> @haavamoa by chance do you have link to the change it can help role out a fix for this.

I don't, sorry. But I guess we could start a new forms project and roll back Xamarin.Forms versions until it won't give you intellisense. The problem is that I don't know if the change is with Forms or with Visual Studio.

**Comment by ahmedalejo** [comment] 2020-02-22 16:05
Probably in Visual Studio.

**Comment by wrkettlitz** [comment] 2020-03-04 10:18
What is the point of `x:DataType` if it doesn't seem to work on almost anything.

**Comment by StephaneDelcroix** [comment] 2020-03-04 10:21
@wrkettlitz specifying x:DataType all's the Xaml Compiler to compile the binding and skip using runtime reflection

**Comment by wrkettlitz** [comment] 2020-03-04 10:37
@StephaneDelcroix thanks for your quick reply.
So is set it here `<DataTemplate x:DataType="{x:Type models:ExampleModel}">`
And intellisense works fine for the properties of this model. 
However if I try to get a property of an property, intellisense fails. 
Is there a way to fix this?

**Comment by StephaneDelcroix** [comment] 2020-03-04 12:02
@wrkettlitz I can't answer anything about intelisense, @mgoertz-msft is the authority source on this.

**Comment by samhouts** [comment] 2020-05-30 00:04
This should now be a VS Feedback ticket. Closing this issue. Thanks!

**Closed by samhouts** 2020-05-30 00:04 UTC
Labels: a/Xaml </>, a/binding ⛓, external-intellisense, m/high impact :black_large_square:, t/bug :bug:

**Comment by tranb3r** [comment] 2020-05-30 10:02
@samhouts Could you please post the link to the VS feedback ticket ?

**Comment by toomasz** [comment] 2020-10-15 19:57
@samhouts @StephaneDelcroix @mgoertz-msft  Do we have VS ticket for this? 
I remember I was reporting that too in 2018 and my bug was also closed without fix.

Guys, adding autocompletion for x:DataType specified on any element would be great productivity boost for Xamarin.Forms :)

developers. It should also support finding references in XAML by given ViewModelProperty.

**Comment by haavamoa** [comment] 2020-10-16 16:43
@samhouts, please provide a vs feedback link if you have one. Want to follow this progress

**Comment by olitee** [comment] 2020-11-19 11:17
I know it's not the solution - but for the benefit of those who have ended up here looking for a workaround - _**Resharper's**_ intellisense does currently support the x:DataType approach.

`x:DataType="viewmodels:SomeExampleViewModel"`

on any element (ContentPage, or nested element such as a StackPanel) for the element and it's children. 

![image](https://user-images.githubusercontent.com/1835892/99659349-a9408a80-2a58-11eb-835d-94f6866a191d.png)


Visual Studio v16.8.1 (Windows)
Resharper 2020.2.2+

**Comment by GreatBarrier86** [comment] 2020-12-10 18:08
@samhouts, like @haavamoa, I too would appreciate a VS Feedback link. I looked through this [link](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=newest&q=intellisense+%5Bxamarin%5D) but didn't find anything referencing this issue. If there is ANYTHING to follow, that's better than nothing.
