### ISSUE TITLE
[Bug] Box View not visible

### ISSUE THREAD

**Issue by NicolaZuc** [xamarin/Xamarin.Forms#10675] opened 2020-05-13 07:42 UTC
### Description
After upgrading Xamarin.Forms to version v.4.6.0.726 box views in uwp are not visible anymore in bindable layouts. The problem happens only in UWP version, Android is ok, not checked for IOS.

### Steps to Reproduce

1. Run attacched solution

### Expected Behavior
Box views are visible
### Actual Behavior
Box views are not visible
### Basic Information

- Version with issue:
- Last known good version: 4.5.0.725
- IDE: Visual Studio 2019 Professional
- Platform Target Frameworks: 
  - Android:  4.6.0.726
  - UWP:  4.6.0.726
- Nuget Packages: 
  - Xamarin.Essentials v.15.3.2
  - NETStandard.Library v.2.0.3
  - Xamarin.Forms v.4.6.0.726

### Reproduction Link
https://mega.nz/file/8EBBDASD#SoOz4-aJyQz9gSELHoz3CaV4T71QN0XIeP1Cg6fQGjA

**Comment by Happypig375** [comment] 2020-05-14 09:39
Dupe of #10528 and #10535

**Comment by samhouts** [comment] 2020-05-26 22:20
Duplicate of #10528

**Closed by samhouts** 2020-05-26 22:20 UTC
Labels: a/boxview, p/UWP, s/unverified, t/bug :bug:
