### ISSUE TITLE
[iOS] TextChanged event fired continuously

### ISSUE THREAD

**Issue by Sakthivel-sync** [xamarin/Xamarin.Forms#12862] opened 2020-11-16 09:07 UTC
### Description

When we press space for twice TextChanged event is fired continuously in XForms.iOS. 

### Steps to Reproduce

1. Create simple sample with Entry control
2. Trigger TextChanged event 
3. Press space bar twice and check event

### Expected Behavior
Trigger only once when press space bar.

### Actual Behavior

It triggers continuously in iOS

### Basic Information

- Version with issue: 4.8
- Last known good version:
- IDE: VS19

### Reproduction Link

https://www.syncfusion.com/downloads/support/directtrac/general/ze/TestSfAutoComplete33959611.zip

### Workaround

Could not find any workaround

**Comment by jsuarezruiz** [comment] 2020-11-16 09:46
Thanks for the attached sample. I have done tests using the sample:
![issue12862](https://user-images.githubusercontent.com/6755973/99237503-dbec4800-27f8-11eb-81bc-ba3a2e73b855.gif)

But cannot reproduce the issue. @Sakthivel-sync  Could you share more information?, maybe happens with a specific  iOS version?

**Comment by Sakthivel-sync** [comment] 2020-11-16 13:04
Hi @jsuarezruiz ,

Thanks for the info.

We tested this problem with the iPhone 11 version of iOS 14.2. I have attached replication video, in that I pressed the space bar twice in that please note, after that event is fired continuously and the cursor moved the location automatically.

Regards,
Sakthi

**Comment by PureWeen** [comment] 2020-12-09 01:04
@Sakthivel-sync I think what you're seeing is caused by the space not resolving because the break point is hit. When you hit space twice really quickly then it hits the break point and the simulator thinks you are still holding down the space bar. 

If you don't set a break point and just do an output like @jsuarezruiz has then it won't cause it to keep firing

**Closed by PureWeen** 2020-12-09 01:04 UTC
Labels: a/entry, p/iOS 🍎, s/unverified, t/bug :bug:
