### ISSUE TITLE
iOS 13 Changes to UISearchBar tint's, can't achieve the same outcome of iOS 12

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#7846] opened 2019-10-07 02:05 UTC
## Summary
I've been experimenting all day and trying to figure out just how to get my UISearchBar to appear the same in iOS13 as it appears in iOS12/11

## API Changes

IOS Version  : 13
Xamarin Froms : 4.2.0.848062
Visual Stduio : 16.3.1

e.g.

So the way the search bar is added is simply a new UISearchController.

     var searchController = new UISearchController(searchResultsController: null);
     searchController.SearchBar.Placeholder = "Search";
     searchController.SearchResultsUpdater = this;
     searchController.HidesNavigationBarDuringPresentation = false;
     searchController.DimsBackgroundDuringPresentation = false;

     NavigationItem.SearchController = searchController;
     NavigationItem.HidesSearchBarWhenScrolling = false;

The results on iOS 11/12:

![image](https://user-images.githubusercontent.com/7145819/66280455-5013a700-e8e9-11e9-8a75-62c4b387170c.png)

The results on iOS 13:

![image](https://user-images.githubusercontent.com/7145819/66280469-5d309600-e8e9-11e9-805e-8aaae88c0a55.png)

## Intended Use Case
https://stackoverflow.com/questions/58229829/ios-13-changes-to-uisearchbar-tints-cant-achieve-the-same-outcome?noredirect=1#comment102842365_58229829

**Comment by jfversluis** [comment] 2019-10-07 13:41
Hi @john-heaven, thanks for the report!

From what I have gathered from the StackOverflow link this is opened on behalf of someone else and not all details are posted here. Most importantly: what I would like most is a reproduction showing this behavior.

From a first glance I don't see how this is something Xamarin.Forms should solve. It seems this is something that is changed in Apple APIs and the original poster is not able to figure out how to mimic the same functionality from iOS 11/12 in iOS 13. Even more so, the StackOverflow question is opened with a Xamarin.iOS tag, so Xamarin.Forms doesn't even seem to be used.

Because of the above I will close this issue here. If you believe this is still something we need to address here, please ask the original question asker to open an issue themselves with the right amount of data to be able to solve this.

Thanks!

**Closed by jfversluis** 2019-10-07 13:41 UTC
Labels: proposal-open, t/enhancement ➕
