### ISSUE TITLE
Binding with Converter and ConverterParameter is not working at ANY release, higher than *2.5.0.280555*

### ISSUE THREAD

**Issue by Szymaniuk** [xamarin/Xamarin.Forms#2675] opened 2018-05-11 12:04 UTC
### Description
Binding with Converter and ConverterParameter is not working at ANY release, higher than *2.5.0.280555*
The problem occurs only on iOS as well as on Android - working fine at Xamarin Forms 2.5.0.280555, didn't work correctly at Xamarin Forms 2.5.1.317207-pre1 and any higher release (even latest 3.1.0.469394-pre1)

The "tricky" thing, that is inside **MainPage.xaml** is mainly implemented, because of lack of possibility to **Bind** something directly into **ConverterParameter** - https://forums.xamarin.com/discussion/comment/283081/#Comment_283081

```
<Label x:Name="CustomObjectTypeKey" Text="{Binding CustomObjectType}"/>
<Label Text="{Binding Path=BindingContext.ValueAtWholeVmLevel, Source={x:Reference MainPageView}, Converter={StaticResource MyConverter}, ConverterParameter={x:Reference CustomObjectTypeKey}}"/>
```

So I'm defining **CustomObjectTypeKey** (which actually is hidden for the business needs), and using this **Label.Text** only for the next **Label** at **ConverterParameter** - because no able to do something like:
`<Label Text="{Binding Path=BindingContext.ValueAtWholeVmLevel, Source={x:Reference MainPageView}, Converter={StaticResource MyConverter}, ConverterParameter=**{Binding CustomObjectType}**}"/>`

It's working correctly at different customer views, at different business cases, but starting from **2.5.1.317207-pre1** it's just stops working - inside **MyConverter**, **hackyBindedKeyLabel.Text** field is NULL only on this XF release.

### Steps to Reproduce

1. Unpack attached **App2.zip** repo
2. Run project on any iOS/Android simulator (by default it's Xamarin Forms 2.5.0.280555)
3. You will see page with ListView with values like:

> _SomeCustomObject 1 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1* **SomeCustomObject 1 - CustomObjectType**
> 
> _SomeCustomObject 2 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1* **SomeCustomObject 2 - CustomObjectType**

4. Update Xamarin Forms nuget to latest pre-release 2.5.1.317207-pre1
5. Run project on any iOS/Android simulator again
6. You will see list with values like:

> _SomeCustomObject 1 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1*
> 
> _SomeCustomObject 2 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1*

So the **SomeCustomObject X - CustomObjectType** part is missing.

### Basic Information

- Version with issue: 2.5.1.317207-pre1

- Last known good version: 2.5.0.280555
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.1
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms.2.5.1.317207-pre1.nupkg
- Affected Devices:

### Screenshots
**2.5.0.280555 OK:**
![xf_2 5 0 280555](https://user-images.githubusercontent.com/5773539/37096603-6fa87868-2219-11e8-9906-37e1ef0aaf2b.png)

**2.5.1.317207-pre1 NOK:**
![xf_2 5 1 317207-pre1](https://user-images.githubusercontent.com/5773539/37095821-3b6c8d3e-2217-11e8-87d8-519987a4f31d.png)

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/1789319/App2.zip)

See the reported https://github.com/xamarin/Xamarin.Forms/issues/2042

**Comment by StephaneDelcroix** [comment] 2018-05-11 12:45
do not open duplicate bugs. reopen the other one if you think the issue isn't solved.

dupe of #2042

**Closed by StephaneDelcroix** 2018-05-11 12:45 UTC
Labels: duplicate

**Comment by Szymaniuk** [comment] 2018-05-11 13:00
@StephaneDelcroix how can I reopen #2042 as there is no re-open button/feature?
