### ISSUE TITLE
[Bug] DisplayAlert() freezes app on UWP, DisplayPromptAsync crashes app.

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12124] opened 2020-09-15 16:04 UTC
### Description
When you call DisplayAlert() in a UWP app it hangs the app.
I am using Xamarin.Forms version 4.8.0.1364 (latest released).

### Steps to Reproduce

1) Create a new Xamarin Mobile App project with UWP.
2) Add a button with a click event 
3) In the  event, make this call
  await DisplayAlert("Puzzle Saved", "The puzzle was successfully saved to your collection", "OK");
   or
  string result = await DisplayPromptAsync("Question 1", "What's your name?");

### Expected Behavior

Should work

### Actual Behavior

DisplayAlert hangs app (see screenshot)
DisplayPromptAsync causes this exception:

  | Message | "XAML parsing failed." | string
  | Message | "The text associated with this error code could not be found.\r\n\r\nCannot find a Resource with the Name/Key SystemControlPageBackgroundAltHighBrush [Line: 0 Position: 0]" | string

### Basic Information
This works fine in version 4.4.0.991265. I upgraded to 4.8.0.1364 (latest released) and it started failing.

### Screenshots
<img width="396" alt="screenshot2" src="https://user-images.githubusercontent.com/19957937/93235463-71ecef00-f732-11ea-9a31-ec854f249539.png">

**Comment by snowman745** [comment] 2020-09-15 17:15
[CrashRepro4.zip](https://github.com/xamarin/Xamarin.Forms/files/5226601/CrashRepro4.zip)

Attached repro.
1) Open project and run on UWP
2) Go to About pge
3) Click the  "Click for crash on UWP" button.

**Comment by bmacombe** [comment] 2020-09-15 20:59
duplicate of #9606

**Comment by bmacombe** [comment] 2020-09-15 21:01
@snowman745 You can try this workaround.  Have to change the UWP SDK Target.

https://github.com/xamarin/Xamarin.Forms/issues/9606#issuecomment-599566595

**Comment by snowman745** [comment] 2020-09-15 21:05
Thanks. How soon until this is fixed? Looks like #9606 was open ages ago.

**Comment by bmacombe** [comment] 2020-09-15 21:08
@samhouts Any idea when this might make it on the todo list?  I've seen a couple of these issues related to this I'm watching get pinged by people recently.

Thanks!

**Comment by PureWeen** [comment] 2020-09-17 00:51
Closing as duplicate.

@bmacombe it's on the 5.0.0 milestone so should have a fix there

**Closed by PureWeen** 2020-09-17 00:51 UTC
Labels: a/alerts, p/UWP, s/unverified, t/bug :bug:
