### ISSUE TITLE
[Bug] Entry HorizontalTextAlignment does not work

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#8140] opened 2019-10-22 05:53 UTC
### Description
Setting HorizontalTextAlignment in an Entry does not work
### Steps to Reproduce

1. Add an Entry

```
                <Entry
                    Grid.Row="0"
                    Grid.Column="1"
                    FontSize="Large"
                    HorizontalTextAlignment="Center"
                    Keyboard="Numeric"
                    Placeholder="{utility:Translate Quantita}"
                    Text="{Binding Quantita}" />
```

2. Set HotizontalTextAlignment to "Center"

### Expected Behavior
Text should appear centered
### Actual Behavior
It's left aligned

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.xxxxx
- IDE: Visual Studio 2019
- Platform Target Frameworks: 

  - Android:  

- Affected Devices: Zebra TC51

### Reproduction Link

![image](https://user-images.githubusercontent.com/5759350/67261459-05755b80-f4a1-11e9-95fd-a7b0fc153efd.png)

**Comment by xamarindevelopervietnam** [comment] 2019-10-22 07:10
related to https://github.com/xamarin/Xamarin.Forms/issues/8137

**Comment by czuvich** [comment] 2019-10-23 15:05
Is there a workaround?

**Comment by acaliaro** [comment] 2019-10-23 15:35
I think you can try with a CustomRenderer… @czuvich

**Comment by czuvich** [comment] 2019-10-23 16:03
> I think you can try with a CustomRenderer… @czuvich

It looks like Forms needs to set the Gravity along with the TextAlignment on the EditText.  I was able to fix it.

**Comment by Adlorem** [comment] 2019-10-23 16:03
It is working in previous version of Forms.

**Comment by samhouts** [comment] 2019-10-23 23:18
@acaliaro  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Basti82b** [comment] 2019-10-24 13:05
> It is working in previous version of Forms.

I can confirm that. It's a bug in XF 4.3.0.908675.

**Comment by acaliaro** [comment] 2019-10-24 14:10
> @acaliaro  Can you please attach a small project that demonstrates this issue? Thanks!


[HorizontalTextAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/3767957/HorizontalTextAlignment.zip)

**Comment by rotorgames** [comment] 2019-10-30 12:21
I have the same issue with 4.3.0.947036. Android only.

**Comment by AdrianoRochedo** [comment] 2019-10-31 04:00
Same issue for me !

![image](https://user-images.githubusercontent.com/46300640/67918087-b9e64000-fb79-11e9-85a1-f76728c79a94.png)

**Comment by ChaseFlorell** [comment] 2019-11-08 21:37
add me to the list of users running into this same issue.

**Comment by thomasonb** [comment] 2019-11-13 17:42
Add me to the list of users as well.

**Comment by akamud** [comment] 2019-11-13 23:17
Same problem here.

**Comment by veringm** [comment] 2019-11-15 09:44
Also add me to the list of users as well.

**Comment by Xiokraze** [comment] 2019-11-15 14:41
Same here

**Comment by thomasgalliker** [comment] 2019-11-15 20:51
Bug is still present in Xamarin.Forms 4.3.0.991211. Going back to 4.2.0.910310, the Entry texts are aligned again. I wonder how such things can pass a release process? I mean, we all code day and night and mistakes happen - but this one looks like a very fundamental one.

**Comment by czuvich** [comment] 2019-11-15 21:07
The workaround I posted fixed it for me.

**Comment by thomasgalliker** [comment] 2019-11-15 21:47
@czuvich thanks. I already have a bunch of custom renderers for such fixes...

**Comment by ChaseFlorell** [comment] 2019-11-19 17:58
can't roll back, just sold the business on the new CollectionView, and it wasn't quite right in 4.2.
@czuvich if you've been able to successfully resolve this within the renderer, how would you feel about submitting a PR? I'm sure it'd be welcomed by the Forms team.

**Comment by czuvich** [comment] 2019-11-19 18:54
@ChaseFlorell It's just a temporary "hack".  They will likely fix it differently.  I'm not an Android expert :)

**Comment by nkuznetsov** [comment] 2019-11-20 04:38
Things breaking here and there after upgrading to newer version of Forms has been a tradition since the beginning.

Here's a fast fix that worked for me - it was suggested elsewhere (can't remember the ticket #). This is for those who already have a thousand renderers fixing other things and don't want to add another. Add the following to manifest (in the application tag):

android:supportsRtl="true"

**Comment by acaliaro** [comment] 2019-11-20 05:39
> Things breaking here and there after upgrading to newer version of Forms has been a tradition since the beginning.
> Here's a fast fix that worked for me - it was suggested elsewhere (can't remember the ticket #). This is for those who already have a thousand renderers fixing other things and don't want to add another. Add the following to manifest (in the application tag):
> android:supportsRtl="true"

Realy?

**Comment by veringm** [comment] 2019-11-20 10:19
As suggested by @nkuznetsov, android:supportsRtl="true" work for me

**Comment by gceaser** [comment] 2019-12-03 18:40
Yeah the manifest update fixed it for me also:

<application android:label="My App Name" android:supportsRtl="true"></application>

**Comment by stoff99** [comment] 2019-12-04 09:24
Same issue here. Is there a plan to solve it in a Form bugfix version or do we rly need to make some dirty workaround fixes like android:supportsRtl="true" ?

**Comment by akamud** [comment] 2019-12-05 16:40
This has a 4.3 release label but I don't see any PR linked. Is this actually being fixed?

**Comment by cauefelipe11** [comment] 2019-12-10 13:20
Works to me with android:supportsRtl="true" workaround.

**Comment by AdrianoRochedo** [comment] 2019-12-10 22:20
Do not work to me. I am targeting to Android >= 6.

Em ter., 10 de dez. de 2019 às 10:20, cauefelipe11 <notifications@github.com>
escreveu:

**Comment by hartez** [comment] 2019-12-10 23:29
This is fixed by #8658 and should be in an upcoming service release for 4.3.

**Comment by thomasgalliker** [comment] 2019-12-18 16:42
@hartez are you sure it's in 4.3? The bug still appears to be present in 4.4.0.991265.

**Comment by hartez** [comment] 2019-12-18 17:02
> @hartez are you sure it's in 4.3? The bug still appears to be present in 4.4.0.991265.

Yes. The change was merged into the 4.3 branch 8 days ago and the 4.4 branch 6 days ago. 4.4.0.991265 was pushed to NuGet 7 days ago, so if the changes were in that version we'd have bigger problems than text alignment :)

The changes didn't make the last service release for 4.3; they should be in the next one. And an upcoming service release for 4.4.

**Comment by stavroaudi** [comment] 2020-01-03 10:08
I'm on 4.4.0.991265 and the bug is still present. I'm still using the supportsRtl workaround in the meantime.

**Comment by abhibl** [comment] 2020-01-10 10:28
Add the following to manifest (in the application tag):
android:supportsRtl="true"

**Comment by thomasgalliker** [comment] 2020-01-30 08:42
@samhouts will this fix be part of the upcoming stable 4.5.x release? If so, can you assign it the the correct milestone?

**Comment by thomasgalliker** [comment] 2020-01-30 08:59
Hooray! It seems to be solved in Xamarin.Forms 4.4.0.991537 👍

**Comment by samhouts** [comment] 2020-02-04 22:27
huzzah!! closed by https://github.com/xamarin/Xamarin.Forms/pull/8658

**Closed by samhouts** 2020-02-04 22:27 UTC
Labels: 4.3.0, i/regression, p/Android, t/bug :bug:

**Comment by ousspero** [comment] 2020-02-05 16:22
closed 18 hours ago, so i have to update now !, i hope this will not impacts the other features
