### ISSUE TITLE
[Bug] RadioButton not displaying text on Android

### ISSUE THREAD

**Issue by JogyBlack** [xamarin/Xamarin.Forms#11700] opened 2020-08-08 06:34 UTC
### Description
After updating to Xamarin.Forms 4.8, radio buttons no longer display their text under Android. Same code works under 4.7.

### Steps to Reproduce

1. Create new Xamarin.Forms blank page app
2. Add a radio button to the main page:
`<RadioButton Margin="5" Text="Test" />`
3. Make sure the Xamarin.Forms NuGet packages are updated to 4.8.0.1269 and run the app under Android.

### Expected Behavior
The radio button displays the text "Test" to the right.

### Actual Behavior
Only the circle of the radio button is displayed, with no text.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: 4.7.0.1260
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0

### Screenshots

![Screenshot_20200807-233203](https://user-images.githubusercontent.com/1275686/89704168-86092980-d906-11ea-9aff-7b793bbfc84e.png)

**Comment by PureWeen** [comment] 2020-08-08 18:38
Closing for now.

RadioButton is going through a major change on 5.0.0

https://github.com/xamarin/Xamarin.Forms/pull/11628

**Closed by PureWeen** 2020-08-08 18:38 UTC
Labels: s/unverified, t/bug :bug:

**Comment by JogyBlack** [comment] 2020-08-09 04:26
Oh well...at least there an easy workaround till then - put the RadioButton in a horizontal stack panel along with a label, and optionally add a TapGestureRecognizer to the label so tapping it also sets the radio button value.

**Comment by kamalkumar1** [comment] 2020-08-14 17:34
for me also  radio button not working after updated to 4.8 version of xamarin forms. kindly advise me whether i can use it my real time project or not.
![image](https://user-images.githubusercontent.com/7221268/90277053-85324380-de82-11ea-8fc4-ac2812b8cf01.png)

**Comment by JogyBlack** [comment] 2020-08-14 18:52
@kamalkumar1 The radio button works for me, but does not display a label under Android. So I simply put it in a StackPanel with a normal label and added a TapGestureRecognizer to the label, so that tapping it will check the radio button.

```
            <StackLayout Orientation="Horizontal">
              <RadioButton Margin="5" Text="Dark theme" IsChecked="{Binding UseDarkTheme}" />
              <Label VerticalOptions="Center" Text="Dark theme" IsVisible="{OnPlatform Android=true, UWP=false}" >
                <Label.GestureRecognizers>
                  <TapGestureRecognizer Tapped="UseDarkTheme_Tapped" />
                </Label.GestureRecognizers>
              </Label>
            </StackLayout>

```

**Comment by Tommigun1980** [comment] 2020-08-15 03:43
> Closing for now.
> 
> RadioButton is going through a major change on 5.0.0
> 
> #11628

Please don't make anything new, just fix the existing functionality. PLEASE!

**Comment by Munde** [comment] 2020-08-18 09:23
so we expect breaking changes every time this make development experience unpleasing cuz when u update to latest version your not sure what will work and what will not work so its a tiresome

**Comment by Sebastian1989101** [comment] 2020-08-26 18:27
@Munde when you use Microsoft products for a long time you get used to it that it breaks something with every release. But yea it's super annoying for a development framework to break multiple things with each release without even fixing all the old releases...

**Comment by Sebastian1989101** [comment] 2020-08-26 22:42
Quick Workaround for the problem: 

```
<StackLayout Orientation="Horizontal">
    <StackLayout.Spacing>
        <OnPlatform x:TypeArguments="x:Double">
            <On Platform="iOS" Value="-8" />
        </OnPlatform>
    </StackLayout.Spacing>

    <RadioButton x:Name="LocalRadioButton" IsChecked="{Binding IsSelected}"
                 GroupName="{Binding Source={x:Reference EntryGrid}, Path=BindingContext.Identifier}" />

    <Label Text="{Binding SelectionText}" FontSize="Default" LineBreakMode="TailTruncation" VerticalOptions="Center">
        <Label.GestureRecognizers>
            <TapGestureRecognizer Command="{Binding ViewModel.ToggleRadioButtonCommand, Source={x:Reference ContentPage}}"
                CommandParameter="{x:Reference LocalRadioButton}" />
        </Label.GestureRecognizers>
    </Label>
</StackLayout>
```

Yes, I know this increases the VisualTree. Yes, I also know that this requires the ViewModel to reference the RadioButton and do the IsChecked toggle. It's not a clean good solution but at least it is working..

**Comment by hopeko** [comment] 2020-08-28 12:21
I found this problem too. It's so confusing and tired as a new Xamarin-learner.

**Comment by Sebastian1989101** [comment] 2020-08-28 12:22
@hopeko just get used to it, they do it on a regular basis to break stuff on updates. :D

**Comment by Munde** [comment] 2020-08-28 19:27
@Sebastian1989101 I used another way arround using tapGestures but all in all its unpleasant developer experience since i wasted almost 2 hours at first looking for what waswrong withmy code, also on upcoming version there are lot to come on breaking changes am using c# for makeup n we are told its being kicked of xamarin forms so its a trade off to stay with either xf 4.8 or move to 5 when its available there us no smoth transition

**Comment by BurkusCat** [comment] 2020-09-07 17:29
This is an interesting bug to be introduced in Xamarin Forms 4.8 if changes that go in completely different direction are being merged in Forms 5.0. It seems odd for 4.8 to completely break on Android if the other ticket is going to be changing things in 5.0.

**Comment by Midnayt** [comment] 2020-09-09 11:22
For Xamarin dev team, no big deal to broke something, but fixing it took a long time. Question, what a hell are you doing???

**Comment by Midnayt** [comment] 2020-09-09 11:24
@samhouts Maybe, it will be easy to fix this bug, not closing it. Whole month you didn't do nothing.

**Comment by RhomGit** [comment] 2020-10-03 10:26
Aarrrggghhhh, just been wasting my time on this one. Lucky I came across it before we accidentally released with this.
I'll try replacing all of our RadioButtons with the ridiculous StackLayout/OnPlatform/TapGesture/Label workaround, thanks @Sebastian1989101 

Frustrating.

**Comment by kamalkumar1** [comment] 2020-10-03 15:11
Try input control availble  in nuget packge.

Regard

*Kamalkumar.E*
Senior Mobile Application Developer
Mobile:+91-9750461689
Skype:kamalelango15
<https://www.linkedin.com/in/kamal-kumar-39450654/>

**Comment by ymebrugts** [comment] 2020-10-19 14:12
Wtf @PureWeen what do you mean close this for now?? It's literally completely broken and a regression bug. What a fucking joke. Experimental does not mean 'non working'. I'm going back to 4.7

**Comment by RhomGit** [comment] 2020-10-20 10:40
Whilst I don't agree with the language I do agree that this has been extremely inconvenient and pretty poor form.

More issues have arisen recently in our latest production build because of this. Now we need to prepare another build because data entry elements of the UI being unusable. My fault really, we generate some UI elements in code not XAML which I missed when doing the original StackLayout/OnPlatform/TapGesture/Label workaround.

I probably won't bother using experimental features again.

**Comment by IgorKravchenko10** [comment] 2020-10-26 11:59
I have downloaded XF 5.0 and there is no Text property in RadioButton.
No Text - no bug. 
Profit! =)

**Comment by Sebastian1989101** [comment] 2020-10-26 12:23
> I have downloaded XF 5.0 and there is no Text property in RadioButton.
> No Text - no bug.
> Profit! =)

Maybe, just maybe because it has now a Content which can hold everything. See: https://youtu.be/ttF80UnrJAg?t=364

**Comment by mphill** [comment] 2020-10-26 20:55
Switching to https://github.com/enisn/Xamarin.Forms.InputKit  

I understand the feature was experimental - the issue should **not** be closed. Radios without labels is a big problem and just closing it does not leave me with much of any confidence.

**Comment by IgorKravchenko10** [comment] 2020-10-26 21:02
> > I have downloaded XF 5.0 and there is no Text property in RadioButton.
> > No Text - no bug.
> > Profit! =)
> 
> Maybe, just maybe because it has now a Content which can hold everything. See: https://youtu.be/ttF80UnrJAg?t=364

 Thanks. I will check this.

**Comment by Silic0nS0ldier** [comment] 2020-10-29 08:27
I cannot speak to its reliability, but I was able to work around this issue with a custom renderer.

```cs
using Android.Content;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportRenderer(typeof(RadioButton), typeof(ProjectName.Droid.Renderers.PatchedRadioButtonRenderer))]
namespace ProjectName.Droid.Renderers
{
    /// <summary>
    /// A workaround for the issue in the in-box renderer.
    /// https://github.com/xamarin/Xamarin.Forms/issues/11700
    /// </summary>
    public class PatchedRadioButtonRenderer : RadioButtonRenderer
    {
        public PatchedRadioButtonRenderer(Context context) : base(context) {}

        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            // Apply text to native radio button
            this.Control.Text = e.NewElement.Text;

            base.OnElementChanged(e);
        }
    }
}
```

**Comment by KevinAnass** [comment] 2020-11-02 21:37
@IgorKravchenko10  there is value i thing replace the text

**Comment by DopaFiend** [comment] 2020-11-17 14:05
Classic Xamarin!

**Comment by Hokutosei** [comment] 2020-12-28 05:51
yep, experiencing this now. no text displaying to radiobutton

**Comment by njsokalski** [comment] 2020-12-28 15:31
Here is a nice Style I created in case anyone wants it:
<Style x:Key="RadioButtonStyle" TargetType="RadioButton">
	<Setter Property="ControlTemplate">
		<Setter.Value>
			<ControlTemplate>
				<Grid BackgroundColor="Transparent" Padding="0" HorizontalOptions="Fill" Margin="0" VerticalOptions="Fill" ColumnSpacing="5">
					<VisualStateManager.VisualStateGroups>
						<VisualStateGroupList>
							<VisualStateGroup x:Name="CheckedStates">
								<VisualState x:Name="Checked"><VisualState.Setters><Setter TargetName="Check" Property="Opacity" Value="1"/></VisualState.Setters></VisualState>
								<VisualState x:Name="Unchecked"><VisualState.Setters><Setter TargetName="Check" Property="Opacity" Value="0"/></VisualState.Setters></VisualState>
							</VisualStateGroup>
						</VisualStateGroupList>
					</VisualStateManager.VisualStateGroups>
					<Grid.RowDefinitions><RowDefinition Height="*"/></Grid.RowDefinitions>
					<Grid.ColumnDefinitions><ColumnDefinition Width="Auto"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions>
					<Grid BackgroundColor="Transparent" Padding="0" Margin="0" HorizontalOptions="Fill" VerticalOptions="Fill">
						<Ellipse Stroke="Black" WidthRequest="24" HeightRequest="24" StrokeThickness="2" VerticalOptions="Center" HorizontalOptions="Center" Fill="Transparent"/>
						<Ellipse x:Name="Check" WidthRequest="14" HeightRequest="14" Fill="Black" VerticalOptions="Center" HorizontalOptions="Center"/>
					</Grid>
					<ContentPresenter Grid.Column="1" BackgroundColor="Transparent" HorizontalOptions="Fill" Margin="0" Padding="0" VerticalOptions="Fill"/>
				</Grid>
			</ControlTemplate>
		</Setter.Value>
	</Setter>
	<Setter Property="FontFamily" Value="Arial"/>
	<Setter Property="FontSize" Value="24"/>
	<Setter Property="TextColor" Value="Black"/>
	<Setter Property="HorizontalOptions" Value="Start"/>
	<Setter Property="VerticalOptions" Value="Center"/>
	<Setter Property="Margin" Value="0"/>
	<Setter Property="Padding" Value="0"/>
</Style>
This gave a very basic standard Radio Button. You can obviously modify it any way that is appropriate for you.
