### ISSUE TITLE
[Bug] CollectionView includes additional space at the bottom 

### ISSUE THREAD

**Issue by MeikandaNayanar** [xamarin/Xamarin.Forms#6497] opened 2019-06-11 15:05 UTC
### Description
 CollectionView includes additional space at the bottom 
### Steps to Reproduce

1.  Run the attached sample
2. Click the 'Navigate' button
3. You will see an unwanted space is added at the bottom of the CollectionView with MistyRose color

### Expected Behavior
The CollectionView height should end when its child items height ends. 

### Actual Behavior
The CollectionView vertically expands unnecessary even after its child elements which are populated in its ItemTemplate was ended.

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0.483098-pre1
- Last known good version: no
- Android: 8.1 
- Nuget Packages: Xamarin.Forms 4.1.0.483098-pre1

### Screenshots

https://us.v-cdn.net/5019960/uploads/editor/nq/j2wvmwhpkpa4.png

### Reproduction Link
[CollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/3277178/CollectionView.zip)

**Comment by DPY81** [comment] 2019-06-13 02:38
@MeikandaNayanar I think this is expected behaviour because there is not enough elements to fit your device's screen.

You are using scroll view with a grid which in turn has the second and more rows set as
`<RowDefinition Height="*"></RowDefinition>`

Later on the rows are set as `HeightRequest="150"` which means given the `Height="*"` the most each row will be is 150 units.  On smaller screens you wouldn't notice this.

**Comment by MeikandaNayanar** [comment] 2019-06-17 05:43
Hi @DPY81 
I am expecting the layout to fit any mobile screen without any additional spaces since I have used only one grid with '*' and 'Auto' for its height.  I am using the below value to make my image in the desired size (almost square) . 

> HeightRequest="150"

You can also see, I have added another label with that image (having height of 150). Both were in a stack layout which resides in a _DataTemplate_ of _CollectionView_  . This _CollectionView_ is fit inside the first row of a _Grid_ with height specified as '_Auto_'. So I am expecting the collection view to exactly fit the size of the _Grid_'s first row. But here there is additional space. Why?  If you say this is the behavior then can you (or anyone) suggest me a way to achieve this?

**Comment by Lelelo1** [comment] 2019-06-18 19:53
This is the same as #5942?

**Comment by samhouts** [comment] 2019-06-29 00:37
Duplicate of #5942

**Closed by samhouts** 2019-06-29 00:37 UTC
Labels: a/collectionview, s/unverified, t/bug :bug:

**Comment by EvoPulseGaming** [comment] 2019-11-21 06:24
@samhouts You closed this one referencing a duplicate, and then closed the duplicated referencing this as the duplicate. Apparently the default behavior of collectionview and listview is to take up all the space. There appears no way to disable this. Even on latest preview.

**Comment by EvoPulseGaming** [comment] 2019-11-21 06:32
Or at least give us an option to shrink the collectionview if the default is to take up all the space.

If you put collectionview in a scrollview, its will then require scrolling to see anything below the collectionview, even if it would normally fit on a single "page". This prevents me from having a dynamic page that can expand as needed without confusing the user.

**Comment by titoleru** [comment] 2020-02-11 00:14
This is not resolved

**Comment by Kingamattack** [comment] 2020-09-28 08:18
Any update about this bug?

**Comment by HeroSpha** [comment] 2020-10-22 23:08
It the latest Xamarin 4.8.0.1560 u can define your rows to auto, then the Collection view wont have that extra space
`<grid RowDefinitions="auto,auto"></grid>` i have 2 collection views inside a grid works fine

**Comment by 21r8390** [comment] 2021-08-06 09:39
Any update about this bug? ~2021

**Comment by MohanadObiad** [comment] 2021-12-06 10:47
**Hi , I just fix this bug by simple code ...**
Ok , first the CollectionView has a ( HeightRequest) property , so if you set the value to this property the bug will be fixed
- If you have a limit number of items you can directly set the value of (HeightRequest="10xxx") 
- but if you have unknown number of items in the collection view you binding a dynamic (HeightRequest) value
HeightRequest="{Binding myvalue}"
Then in the code behind , first you should calculate the height of a one item and then multiply the number of items by the height 
in my case I calculate the height = 96 
then the myvalue=(number_of_items * 96)
**Note :**  you should define the property with the model of data to binding it directly 
or you can just use the code behind and set the property directly in the runtime.
Thank you.
