### ISSUE TITLE
[Bug] XF displaying UIModalPresentationStyle.PageSheet page on iPad crash on Navigation.PopModalAsync()

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#13748] opened 2021-02-12 18:59 UTC
### Description
If the user taps anywhere outside of the page sheet and then taps the Close button in the navigation toolbar, the app crashes.

### Steps to Reproduce

1. New XF app and replace the MainPage with the following:
```
    public class MainPage : ContentPage
    {
        public MainPage()
        {
            ContentPage page = null;
            Content = new Button()
            {
                Text = "Tap me!",
                Command = new Command(() =>
                {
                    var nav = new Xamarin.Forms.NavigationPage(page = new ContentPage()
                    {
                        Content = new Label()
                        {
                            Text = "Tap the Close button above"
                        }
                    });

                    nav.On<iOS>().SetModalPresentationStyle(UIModalPresentationStyle.PageSheet);

                    nav.ToolbarItems.Add(new ToolbarItem()
                    {
                        Text = "Close",
                        Command = new Command(async ()=> await page.Navigation.PopModalAsync())
                    });

                    Navigation.PushModalAsync(nav);
                })
            };
        }
    }

```
2. Run on an iPad simulator
3. Tap the button
4. Tap outside the displayed window (e.g. the previous background that is still visible around the edge)
5. Tap the Close button
6. **BOOM!**

### Expected Behavior
Should not crash

### Actual Behavior
Crashes

### Exception and stack trace
Message Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
Stacktrace	at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) <0x102a8d060 + 0x00063> in <0c3d4da7367647c9a650750b1a4d0c53#1749e9c0ffffd1117756b28039c9d135>:0 
at Xamarin.Forms.Application+NavigationImpl.OnPopModal (System.Boolean animated) <0x103e678d0 + 0x00097> in <82bf00d73ba84d498079d53808841321#1749e9c0ffffd1117756b28039c9d135>:0 
at Xamarin.Forms.Platform.iOS.ModalWrapper.DidDismiss (UIKit.UIPresentationController presentationController) <0x1041ea540 + 0x0018b> in :0 
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.b__7_0 (System.Object state) <0x1029b01e0 + 0x00053> in <0c3d4da7367647c9a650750b1a4d0c53#1749e9c0ffffd1117756b28039c9d135>:0 
at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () <0x102d0b030 + 0x0002b> in <5e58267d9bbe4b28bbf05fcedb71d37a#1749e9c0ffffd1117756b28039c9d135>:0 
at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x102caff40 + 0x0002f> in <5e58267d9bbe4b28bbf05fcedb71d37a#1749e9c0ffffd1117756b28039c9d135>:0 
at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x102cafeb0 + 0x00043> in <5e58267d9bbe4b28bbf05fcedb71d37a#1749e9c0ffffd1117756b28039c9d135>:0 
at Test2.Application.Main (System.String[] args) <0x102843870 + 0x00027> in <178a22a53cc0468fa1eb4762dc58b26c#1749e9c0ffffd1117756b28039c9d135>:0

### Basic Information

- Version with issue:
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  

- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: iPad

### Workaround
Don't use PageSheet, which leads to a less than perfect UI on iPad devices.

**Comment by JohnHDev** [comment] 2021-02-14 09:39
In case this helps:
I have replicated this issue in the XF.ControlsGallery.iOS project after cloning this repo.
I can see that when tapping outside the popup sheet and tapping Close, Application.NavigationImpl.OnPopModal() is called a twice instead of the normal once. The second call comes from ModalWrapper.DidDismiss(). In the UI test it doesn't crash as there are already 2 pages on the navigation stack, the bug shows as dismissing 2 pages instead of 1. In my example above there is only 1 page on the stack, which crashes.

**Comment by JohnHDev** [comment] 2021-02-14 10:40
The culprit appears to be the XF ModalWrapper.DismissViewController override, I would suggest XF reviews that to see if it is still required.
I modified the code to only not run base.DismissViewController if ModalPresentationStyle is not PageSheet. Obviously I can't use that in our XF solutions as ModalWrapper is internal, which is used by Platform.PresentModal which is private.

**Comment by hartez** [comment] 2021-02-18 23:20
See also: #12300 and #13273.

**Comment by hartez** [comment] 2021-02-18 23:24
Closing this as a duplicate of #12300 so we can track everything in one place.

**Comment by JohnHDev** [comment] 2021-04-25 06:59
@hartez feel free to ignore this, we are dropping Xamarin Forms and moving to better supported technologies.

**Comment by jfversluis** [comment] 2022-05-02 09:04
Was meant to be closed and I think this is fixed by now as well.

**Closed by jfversluis** 2022-05-02 09:04 UTC
Labels: t/bug :bug:, s/unverified
