### ISSUE TITLE
MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild/Microsoft/WindowsXaml/v16.0/Microsoft.Windows.UI.Xaml.CSharp.targets" was not found

### ISSUE THREAD

**Issue by Essaadani** [xamarin/Xamarin.Forms#14725] opened 2021-10-13 07:25 UTC
### Steps to Reproduce

1. Upgrade macOs to the latest version: macOs Monterey (Same problem with previous version Big Sur)
2. Update Visual Studio for Mac 2019
3. Open an existing Xamarin.Forms solution containg (iOS, Andoid and UWP projects)
4. Right click on the solution --> Restore Nuget Packages

### Expected Behavior
The nuget packages are restored successfully and the project can build correctly.

### Actual Behavior
Restoring nuget packages fails and the following error is displayed in the Package Console Window:
`/Users/khalidessaadani/Projects/CygnApp/CygnApp/CygnApp.UWP/CygnApp.UWP.csproj(283,11): error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild/Microsoft/WindowsXaml/v16.0/Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Also, tried to find "Microsoft/WindowsXaml/v16.0/Microsoft.Windows.UI.Xaml.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.`

### Environment
```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.11 (build 8)
Installation UUID: 38c8678d-a0d7-4b42-a980-be4a5470bd59
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.203
	5.0.202
	5.0.201
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.409
	3.1.408
	3.1.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.6
	5.0.5
	5.0.4
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.15
	3.1.14
	3.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.414

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Enterprise)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Enterprise)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/khalidessaadani/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/khalidessaadani/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Build Information ===

Release ID: 810110008
Git revision: 5467245e1f99a0c8ccdd2acea02d16c3fb65c220
Build date: 2021-10-07 10:49:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Thu Sep 30 06:41:59 PDT 2021
    root:xnu-8019.40.96.0.2~12/RELEASE_X86_64 x86_64

```

```
```

### Build Logs
https://gist.github.com/Essaadani/52c3aadbda2fa3d9c5e6053a0f8c207a

**Comment by jfversluis** [comment] 2021-10-13 18:30
@Essaadani you mention "an existing project". I have many of those but never encountered this. Would you be able to share a reproduction sample for this?

**Comment by jfversluis** [comment] 2021-10-14 08:11
> I'm wondering if Visual Studio is using a different MSBuild than the one used by the build agent, if so how can I force the build agent to use Visual Studio MSBuild?

This is definitely possible. Make sure to check your build configuration and compare the build logs from Visual Studio where the build does work with the logs from the CI where it doesn't work.

The build agent downloads custom tasks with custom configurations so it might build your code differently.

This seems to be a configuration/environment issue then and not so much a bug. So closing this one for now :)

**Closed by jfversluis** 2021-10-14 08:11 UTC
