### ISSUE TITLE
TapGestureRecognizer not working on iOS in Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15144] opened 2022-02-10 21:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TapGestureRecognizer-not-working-on-iOS-/1644568)._

---
[severity:I'm unable to use this version]
    Dim tgrSwipe As New TapGestureRecognizer

AddHandler tgrSwipe . Tapped, Sub()
                                                                'Fire Event
                                                              End Sub

imgSwipe.GestureRecognizers.Add(tgrSwipe )

Code worked fine before updating Xamarin Forms. Works as intended on Android.
All Nuget packages are updated.

---
#### Feedback Bot on 1/23/2022, 11:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-02-11 12:40
This is on Windows, so I'm assuming Hot Restart is used. In that case duplicate of #14956

**Closed by jfversluis** 2022-02-11 12:40 UTC
