### ISSUE TITLE
[Bug] NavigationBar has a shadow since v5.0.0.2196

### ISSUE THREAD

**Issue by NPadrutt** [xamarin/Xamarin.Forms#14938] opened 2021-11-30 19:37 UTC
### Description
When I upgrade my Xamarin Forms application with shell from version 5.0.0.2125 to 5.0.0.2196 I have a border under the header of my application.

![image](https://user-images.githubusercontent.com/1764367/144115181-07a41e76-c732-40b1-87e1-2c1a9554b28c.png)

I tried the suggestions from there: https://stackoverflow.com/questions/19226965/how-to-hide-uinavigationbar-1px-bottom-line and the further links there. Specifically adding this to my iOS app:

            UINavigationBar.Appearance.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
            UINavigationBar.Appearance.ShadowImage = new UIImage();

and

            var appearance = new UINavigationBarAppearance()
            {
                BackgroundColor = UIColor.Clear, ShadowColor = null,
            };

            UINavigationBar.Appearance.StandardAppearance = appearance;
            UINavigationBar.Appearance.ScrollEdgeAppearance = appearance;
            UINavigationBar.Appearance.CompactAppearance = appearance;

Both didn't work. From what I found in a [StackOverflow question](https://stackoverflow.com/questions/69933838/header-has-border-with-xf-5-0-0-2196-on-ios/69971727?noredirect=1#comment123927195_69971727) it seems that his is an issue with Shell.

### Expected Behavior
There is no shadow under the navigation bar

![image](https://user-images.githubusercontent.com/1764367/144115161-126b502e-9862-4394-a4cf-a2ed3d9cd70f.png)

### Actual Behavior

see image above

### Basic Information

- Version with issue: 5.0.0.2196
- Last known good version: 5.0.0.2125
- Platform Target Frameworks: 
  - iOS:  15
- iPhone 12, iPad Pro, iPhone 15 Simualtor (probably all other devices with iOS and iPad OS too)

**Comment by jfversluis** [comment] 2021-11-30 19:44
In iOS 15 there have been changes to the Navigation Bar and Tab Bar unfortunately. Would you be able to add a reproduction sample which shows how you have you code setup in your project? Thanks

**Comment by NPadrutt** [comment] 2021-11-30 21:15
Sure, I'll attach a sample in a bit.  But just to say, it does work as expected with version 5.0.0.2125 of Xamarin Forms on iOS 15. I don't know if that was more of a side effect of something else that was fixed in subsequent versions though. But I thought I saw that there was something fixed around the navigation header.

**Comment by NPadrutt** [comment] 2021-11-30 21:32
Here the sample.
With the latest version: 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1764367/144130646-a82c3164-3d6d-4835-9f67-8514db145f02.png">


with version: 5.0.0.2125
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1764367/144130809-1c389500-1bff-4549-a6b2-34099a7e87c4.png">


Funny enough, when you don't pick white as the color it seems the two version do display it a bit different, which would speak for my theory that there was a fix / change in between here.

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/7628992/App1.zip)

**Comment by jfversluis** [comment] 2021-12-01 12:24
> But just to say, it does work as expected with version 5.0.0.2125 of Xamarin Forms on iOS 15.

I highly doubt this because that version doesn't have the fixes to show the navigation bar the right way for iOS 15. So what you are probably seeing is things being broken 😅 have you tried setting a different background color to the navigation bar with version 2125? That probably doesn't work :)

**Comment by bcaceiro** [comment] 2022-01-06 15:41
Is this issue closed? Because I'm getting this problem in v5.0.0.2291

**Comment by jfversluis** [comment] 2022-01-06 15:56
This is not closed, still looking into it, any help is appreciated

**Comment by jfversluis** [comment] 2022-01-07 14:15
Thanks everyone for your patience! Like I already said; this has to do with Apple changing up some iOS APIs here. I've been playing with this and while there is multiple ways to fix this, they're all not great. "Not great" meaning in this case that you will need to change code in your app for every scenario that I can come up with and for some of the scenarios that I came across we need to change code.

Preferably I would like to change as less as possible on our side. And since you need to change something anyway, my proposal is the following.

1. Get rid of the code that has been removing the line so far
2. Replace that with a custom renderer that you can find below

```csharp
using System.ComponentModel;
using App1;
using App1.iOS;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(AppShell), typeof(ShellNavbarRenderer))]

namespace App1.iOS
{
    public class ShellNavbarRenderer : ShellRenderer
    {
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
        }

        protected override IShellNavBarAppearanceTracker CreateNavBarAppearanceTracker()
        {
            return new NoLineAppearanceTracker();
        }
    }

    public class NoLineAppearanceTracker : IShellNavBarAppearanceTracker
    {
        public void Dispose()
        {
        }

        public void ResetAppearance(UINavigationController controller)
        {
        }

        public void SetAppearance(UINavigationController controller, ShellAppearance appearance)
        {
            var navBar = controller.NavigationBar;
            var navigationBarAppearance = new UINavigationBarAppearance();
            navigationBarAppearance.ConfigureWithOpaqueBackground();

            navigationBarAppearance.ShadowColor = UIColor.Clear;
            navBar.ScrollEdgeAppearance = navBar.StandardAppearance = navigationBarAppearance;
        }

        public void SetHasShadow(UINavigationController controller, bool hasShadow)
        {
        }

        public void UpdateLayout(UINavigationController controller)
        {
        }
    }
}
```

This will override the behavior or our default `ShellNavBarAppearanceTracker` with something that removes the line. The alternative would be that you change the code in your `AppDelegate` to something similar like the code in `SetAppearance`, and then in our code we need to check if you have set a value from the `AppDelegate` and we don't override that. To me this feels a bit nicer, but I'm interested to hear your thoughts and if this also works in your scenarios.

Thanks!

**Comment by NPadrutt** [comment] 2022-01-07 17:01
@jfversluis  thanks for your investigation and the workaround. So far it does work as expected. A bit unfortunate is that it also override all styles. So it seems that those have to be set in the custom renderer manually again I presume?

**Comment by jfversluis** [comment] 2022-01-10 19:16
Yeah I would be recommended to then add all the styling that you had before also in there now. Unless you were using styles in Xamarin.Forms, that should still work?

**Comment by jfversluis** [comment] 2022-04-27 11:12
I have merged #15330 that might be fixing this one as well. Make sure to try out Service Release 11 when it comes out. If that still doesn't fix it let me know. Thanks!

**Closed by jfversluis** 2022-04-27 11:12 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/needs-info ❓, a/navbar, iOS 15

**Comment by NPadrutt** [comment] 2022-10-02 20:32
@jfversluis I only just removed my custom renderer from the work around since I migrated to .net maui, but I think this still doesn't work as expected on maui. Just FYI

**Comment by FM1973** [comment] 2023-03-26 12:26
@NPadrutt Can you let us know how you solved this in MAUI, pleas?

**Comment by NPadrutt** [comment] 2023-03-26 12:31
@FM1973 as mentioned in my last comment, I just took the custom renderer of @jfversluis  and registered it as a custom handler:

``` 
builder.ConfigureMauiHandlers(handlers => { handlers.AddHandler(viewType: typeof(Shell), handlerType: typeof(Platforms.iOS.Renderer.CustomShellRenderer)); });
```

**Comment by FM1973** [comment] 2023-03-26 12:33
@NPadrutt Thanks a lot!
