### ISSUE TITLE
[Bug] (regression) macOS: DeviceInfo.ScalingFactor returning 0.0 in Xamarin.Forms 4.0 (last good version: 3.6.709228)

### ISSUE THREAD

**Issue by knocte** [xamarin/Xamarin.Forms#8652] opened 2019-11-25 15:21 UTC
### Steps to Reproduce

1. Retreive Device.Info.ScaleFactor API on macOS

### Expected Behavior

Should return a value higher than 0 (in XFv3.6 it returns 2.0 in my MacBook with Catalina).

### Actual Behavior

Returns 0.0 since the first version of Xamarin Forms 4.0.x.

### Basic Information

- Version with issue: 4.0.0.425677 and newer.
- Last known good version: 3.6.709228
- IDE: VisualStudio for Mac
- Platform Target Frameworks:
  - macOS
- Nuget Packages:
- Affected Devices: macOS Catalina 10.15.1 (MacBook)

### Screenshots

N/A

### Reproduction Link

N/A

**Comment by AndreiMisiukevich** [comment] 2019-11-25 16:42
duplicated: https://github.com/xamarin/Xamarin.Forms/issues/8559

This bug is already fixed by @jfversluis :)

**Comment by jfversluis** [comment] 2019-11-25 17:50
Yep! Fixed and merged, should be part of a future 4.4 release. Might not be the next one, but definitely the one after that which I think should be the final.

Thanks for noticing this @AndreiMisiukevisch!

**Comment by jfversluis** [comment] 2019-11-25 17:50
Duplicate of #8559

**Closed by jfversluis** 2019-11-25 17:50 UTC
Labels: s/unverified, t/bug :bug:
