### ISSUE TITLE
[Enhancement] Add SelectedBarTextColor and UnSelectBarTextColor to TabbedPage

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#8295] opened 2019-10-30 06:41 UTC
Now TabbedPage has feature for changing the SelectedTabColor and UnSelectedTabColor and BarTextColor.
But Now I want a feature after select the tab , change the Selected tab color and Selected bar text color(other unselected bar text color keep default color ).But now no api for changing the color of selected bar text.

**Comment by techduggu** [comment] 2019-10-30 09:05
This will possibly get implemented by https://github.com/xamarin/Xamarin.Forms/pull/7348

**Comment by jingliancui** [comment] 2019-10-30 10:34
great

**Comment by samhouts** [comment] 2020-02-13 01:31
Duplicate of #3281

**Closed by samhouts** 2020-02-13 01:31 UTC
Labels: a/tabbedpage, proposal-open, t/enhancement ➕
