### ISSUE TITLE
[Bug] Build failed on Azure Devops after upgrading to XF 4.2.0.815419

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#7746] opened 2019-09-30 13:08 UTC
### Description

After upgrading to XF 4.2.0.815419 my builds on Azure Devops always fail. It happens both on Android and on iOS.

Here is my log on Android:

```
"/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj" (PackageForAndroid target) (1) ->
(_LinkAssembliesShrink target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly. [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Stack`1' (defined in assembly 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Stack`1 [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType (Mono.Cecil.TypeReference reference) [0x00013] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x0002d] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkGenericArguments (Mono.Cecil.IGenericInstance instance) [0x00016] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.GetOriginalType (Mono.Cecil.TypeReference type) [0x0000c] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00005] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkField (Mono.Cecil.FieldReference reference) [0x0004a] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeFields (Mono.Cecil.TypeDefinition type) [0x00024] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0005d] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x0002f] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Initialize () [0x00014] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00007] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.Process (Mono.Linker.LinkContext context) [0x0000b] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001c] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x002d4] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:    --- End of inner exception stack trace --- [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Java.Interop.Tools.Diagnostics.Diagnostic.Error (System.Int32 code, System.Exception innerException, System.String message, System.Object[] args) [0x00009] in <76956571ad3f4b6489c7b342ba825a27>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x004b5] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x0021f] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <2338fdb301034c1d9c6b95e564d514b0>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in <2338fdb301034c1d9c6b95e564d514b0>:0  [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.Android/MyApp.Android.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:41.89
##[error]Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1
```
and here is the log for iOS:

```
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.iOS/obj/iPhone/Release/response-file.rsp -v -v -v -v --linkskip=MyApp --linkskip=MyApp.iOS --linkskip=MyApp.resources --linkskip=Lottie.Forms.iOS.Renderers --linkskip=Lottie.Forms.iOS --linkskip=Lottie.Forms --linkskip=Com.Airbnb.Xamarin.Forms.Lottie --linkskip=Xam.Plugin.WebView --linkskip=Xam.Plugin.WebView.Abstractions.FormsWebView --linkskip=Xam.Plugin.WebView.iOS --linkskip=Xam.Plugin.WebView.Abstractions "--gcc_flags=-framework AssetsLibrary" 
MTOUCH : error MT2002: Failed to resolve "System.Collections.Generic.Stack`1" reference from "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" [/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.iOS/MyApp.iOS.csproj]
  --- inner exception
  Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Stack`1
    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType (Mono.Cecil.TypeReference reference) [0x0001b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:1821 
    at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00055] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:871 
    at Xamarin.Linker.Steps.MobileMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileMarkStep.cs:71 
    at Xamarin.Linker.Steps.CoreMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00090] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:172 
    at MonoTouch.Tuner.MonoTouchMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs:84 
    at Mono.Linker.Steps.MarkStep.MarkGenericArguments (Mono.Cecil.IGenericInstance instance) [0x00018] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:1365 
    at Mono.Linker.Steps.MarkStep.GetOriginalType (Mono.Cecil.TypeReference type) [0x00013] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:1326 
    at Xamarin.Linker.Steps.MobileMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileMarkStep.cs:71 
    at Xamarin.Linker.Steps.CoreMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00090] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:172 
    at MonoTouch.Tuner.MonoTouchMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs:84 
    at Mono.Linker.Steps.MarkStep.MarkField (Mono.Cecil.FieldReference reference) [0x00051] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:815 
    at Mono.Linker.Steps.MarkStep.InitializeFields (Mono.Cecil.TypeDefinition type) [0x00028] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:116 
    at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0006f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:107 
    at Mono.Linker.Steps.MarkStep.InitializeAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x00034] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:88 
    at Mono.Linker.Steps.MarkStep.Initialize () [0x00016] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:78 
    at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00008] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:71 
    at Xamarin.Linker.Steps.MobileMarkStep.Process (Mono.Linker.LinkContext context) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileMarkStep.cs:33 
    at Xamarin.Linker.Steps.CoreMarkStep.Process (Mono.Linker.LinkContext context) [0x00017] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:32 
    at MonoTouch.Tuner.MonoTouchMarkStep.Process (Mono.Linker.LinkContext context) [0x0001d] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs:36 
    at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker/Pipeline.cs:127 
    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x000e0] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Tuning.cs:80 
  ---
    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x00257] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Tuning.cs:104 
    at Xamarin.Bundler.Target.LinkAssemblies (System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies, System.String output_dir, System.Collections.Generic.IEnumerable`1[T] sharedCodeTargets) [0x00256] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:522 
    at Xamarin.Bundler.Target.ManagedLink () [0x00720] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:669 
    at Xamarin.Bundler.Target.ProcessAssemblies () [0x000c2] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:873 
    at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:1411 
    at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:839 
    at Xamarin.Bundler.Application+<>c.<BuildAll>b__140_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:787 
    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <4ce69280878a4ebdbc54175071d7ecdf>:0 
    at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:787 
    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00423] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:1402 
    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:934 
Done Building Project "/Users/vsts/agent/2.155.1/work/1/s/MyApp/MyApp.iOS/MyApp.iOS.csproj" (default targets) -- FAILED.
Done Building Project "/Users/vsts/agent/2.155.1/work/1/s/MyApp.sln" (default targets) -- FAILED.

Build FAILED.
```

### Steps to Reproduce

1. Build 4.2.0.815419 on Azure Devops
2. Build fails

### Expected Behavior
Build on Azure Devops should be successful.

### Actual Behavior
Build on Azure Devops fails.

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: 4.1.0.555618
- IDE: Azure Devops

**Comment by samhouts** [comment] 2019-09-30 18:00
Duplicate of #7602

**Closed by samhouts** 2019-09-30 18:00 UTC
Labels: s/unverified, t/bug :bug:
