### ISSUE TITLE
Replace application main page with animation

### ISSUE THREAD

**Issue by mo-ah-dawood** [xamarin/Xamarin.Forms#2957] opened 2018-06-06 11:33 UTC
### Description
i know that we can change main page using this
App.Current.MainPage
but is it possible to change main page with some animation

**Comment by adrianknight89** [comment] 2018-06-17 21:20
Can you expand on what kind of animation you're wanting? Would the new MainPage animate onto the existing one? Would it reveal itself atop a blank background (changing opacity from 0 to 1)? Etc. 

I'd also question the need for switching main pages. Whatever you're trying to do can possibly be done with modal pages (e.g. use login page modally without animation while the TabbedPage is the MainPage).

**Comment by m0dawood** [comment] 2018-06-17 22:58
i have 2 application cycles 
1- navigation page that will push security pages(select user type,login, forgot password,verify password, registration page)
2- main cycle that is master details page and many other pages

the two cycles  need navigation bar so i can't use push modal without doing some extra code to handle navigation

i tried to use this method
![capture](https://user-images.githubusercontent.com/31937782/41512895-a188262a-7292-11e8-9959-652662edd9ab.PNG)


i have 2 cases
1- the application is not in background and started
    -  the animation  is slow and uggly
2- the application is in background and started 
   - the animation is good

i used SizeChanged  or LayoutChanged events because its occurs after Appearing event
this video is showing two cases
[https://1drv.ms/v/s!Aqxak4UqqG0AbyK1xXk7Iu798tU](url)

**Comment by m0dawood** [comment] 2018-06-17 23:02
i just want to replace main page with any kind off animation to make the app have a good look in the case i want to replace it

**Comment by m0dawood** [comment] 2018-06-17 23:32
this  video is for same app but with 1000 milliseconds animation
[https://drive.google.com/file/d/1iJJ6-1Lpl0mEQT9D6icohJLnpKKKHybP/view?usp=drivesdk](url)

**Comment by Mikilll94** [comment] 2018-10-09 17:00
I agree that this feature would be very useful because it is common in apps to separate login flow from normal application flow.

**Comment by AndreiMisiukevich** [comment] 2018-10-17 00:50
```csharp
var oldPage = new ContentPage();
var navPage = new NavigationPage(oldPage);
...
navPage.PushAsync(new ContentPage());
navPage.RemovePage(oldPage);
```

**Comment by programmation** [comment] 2018-10-17 03:28
@Mikilll94 I use a `ControlTemplate` for this, with the login view as one of its subviews and the main view as the `ContentPresenter`. I use a `Behavior` to animate between them visible/invisible depending on the user's authentication status.

**Comment by Mikilll94** [comment] 2018-10-17 07:54
@programmation This approach becomes problematic if your app does not have a homepage (i.e. user after launching an app can see many different views)

**Comment by AndreiMisiukevich** [comment] 2018-10-17 08:02
@Mikilll94 why don't you want to use **NavigationPage** ?

**Comment by Mikilll94** [comment] 2018-10-17 09:33
Because I want to have two separate navigation stacks: one for login flow and second for normal flow.

**Comment by GalaxiaGuy** [comment] 2018-10-17 09:43
@Mikilll94 It's not perfect, but when I've needed to do this, I've used a `NavigationPage` and then after pushing, removed the previous page from the stack.

**Comment by AndreiMisiukevich** [comment] 2018-10-17 10:38
@GalaxiaGuy @Mikilll94 Re https://github.com/xamarin/Xamarin.Forms/issues/2957#issuecomment-430450794

**Comment by programmation** [comment] 2018-10-17 22:37
> @programmation This approach becomes problematic if your app does not have a homepage (i.e. user after launching an app can see many different views)

@Mikilll94 I solve that issue by making each of the potential startup views have the same `ControlTemplate`. In fact all pages in the app that require authentication for access have the "authentication" `ControlTemplate`. Then I have a master switch inside the app that toggles true or false to match the user's authenticated status. The `ControlTemplate` shows the content if the user is authenticated, and the login page if not. It's actually a lot simpler than I make it sound here, and with `Behavior`s I can animate transitions between the states.

**Comment by abdu292** [comment] 2019-04-10 04:32
Really looking for this as well!

**Comment by valiman** [comment] 2020-02-07 13:31
Hello, 
I'm not sure if this is a direct answer but try to see how i solved my similar problem:

Navigation.InsertPageBefore(new QuicklookupPage(), this); //Insert page ontop current Main Page
Navigation.RemovePage(Navigation.NavigationStack.First()); //Remove Main Page (root page)
Navigation.PopAsync(); //Pop off current page, there will be an animation here to the new Main Page (root page)

**Comment by samhouts** [comment] 2020-02-13 01:21
Duplicate of #6033

**Closed by samhouts** 2020-02-13 01:21 UTC
Labels: a/transitions, proposal-open, t/enhancement ➕
