### ISSUE TITLE
[Bug] Navigating to another page

### ISSUE THREAD

**Issue by sturlath** [xamarin/Xamarin.Forms#8402] opened 2019-11-06 18:26 UTC
### Description
I can't seem to be able to navigate from a page that is not "set" in the AppShell.xaml  to a shell page (TabPage). 

Is there something I'm doing wrong or and if so **how is this supposed to work**? I'm finding Shell to be totally confusing ... after three days and tree issues...

I have been reading through the [navigation docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation) and I can't understand heads or tails... its missing more examples (and maybe less text?). Searching for examples on navigation has not helped me either...

### Steps to Reproduce

1. Get [my repo with the problem](https://github.com/sturlath/ShellProblem)
2. Run the app
3. Click Add (right top corner)
4. Click the Navigate button
5. Nothing happens. **But** the brake point is hit
6. View the code [NewItemPage.xaml](https://github.com/sturlath/ShellProblem/blob/dbb7e2e5968ed9ed7796becabd3652464743edd9/App2/App2/Views/NewItemPage.xaml#L50) and [NewItemPage.cs](https://github.com/sturlath/ShellProblem/blob/dbb7e2e5968ed9ed7796becabd3652464743edd9/App2/App2/Views/NewItemPage.xaml.cs#L21) to view the code that is hit by a brake point but doesn't navigate!

### Expected Behavior
Able to navigate from a button to what ever page I like.

### Actual Behavior
Can't navigate. Probably my problem but I have no idea what I´m doing wrong!

### Basic Information
    IDE: Visual Studio (16.3.7 and 16.4-prev3)
    Platform Target Frameworks:
        Android: Just tried this on Android
    Android Support Library Version:
    Affected Devices:

### Reproduction Link
[Here is a repo with the problem](https://github.com/sturlath/ShellProblem)

**Comment by jamesmcmenamin** [comment] 2019-11-07 03:03
Have not looked around your sample much BUT....

Moving from non shell to shell (or other way)

                            Application.Current.MainPage = new XcelentShell();

You will find a number of weird things with navigation inside of shell (specificly to tab pages though but it is a HUGE time saver over all)

**Comment by sturlath** [comment] 2019-11-07 11:07
Thanks @jamesmcmenamin 

I tried to get this to work but changing [my code ](https://github.com/sturlath/ShellProblem/blob/f2a868ab7b400e8a428319f1ae13565b16e003c4/App2/App2/Views/NewItemPage.xaml.cs#L21) to the code below, **just freezes up the app** after opening the AboutPage in/(over?) the first tab page.

```csharp 
public ICommand GoToAboutPageCommand => new Command(() => NavigateToAboutPage()));

public void NavigateToAboutPage() => Application.Current.MainPage = new AboutPage();
 ```

**Does this code need to be somewhere else or do I need to "kick off" the change somehow?**

I would have thought that this scenario would be used everywhere in demos and blogs, but I can´t find any information on it anywhere. 

Even the[ official navigation docs ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation) don't speak of it or show any example of how to do this!

**Comment by jamesmcmenamin** [comment] 2019-11-07 17:18
@sturlath I will pull the project and look at it over lunch here.

**Comment by sturlath** [comment] 2019-11-09 09:39
@jamesmcmenamin did you managed to take a look at this? It baffles me how hidden this feature is...

**Comment by PureWeen** [comment] 2019-11-09 17:54
@sturlath so there's a couple things going on here. To get what you want

1) Delete the globalroute you have registered for aboutpage
2) setup a route on your shell for the about page
```XAML
<ShellContent Route="AboutPage" ContentTemplate="{DataTemplate local:AboutPage}" />
```
3) Now there is a bug here on our side but now do your navigation like this
```C#
public async Task NavigateToAboutPageAsync()
        {
            await Navigation.PopModalAsync();
            await Shell.Current.GoToAsync($"///AboutPage").ConfigureAwait(false);
        }
```

You shouldn't need that PopModal forms should just pop the modal itself when you navigate away so that the animation is more fluid

Or you could do it like this which is a little more correct visually
```C#
        public async Task NavigateToAboutPageAsync()
        {
            var section = Shell.Current.CurrentItem.CurrentItem;
            await Shell.Current.GoToAsync($"///AboutPage").ConfigureAwait(false);
            await section.Navigation.PopModalAsync();
        }
```

**Comment by jamesmcmenamin** [comment] 2019-11-09 21:46
So sorry I was in a release cycle and this slipped my mind give me couple
hours I’ll do a quick and dirty sample

**Comment by jamesmcmenamin** [comment] 2019-11-10 00:31
@sturlath @radical 
Here is a working copy of how to move in and out of Shell navigation (yes its probably WAY WAY WAY more than you were asking for but its a great way to see ALOT of core things that should be used in mobile...
*pseudo* DI
IoC
MvvM

There is MANY other ways to get into the pages such as GoToAsync PopModalAsync and others this is just the best way we have found when developing a large enterprise application that is dozens and dozens of pages deep

@PureWeen -- 3 things
1) at XDS you showed us that IsVisible was coming for shell... What is up with that? (I did see you had basicly redesigned the entire navigation stack in the (I want to say hotel's app talk) is that public some were? would LOVE to get my hands on a minimum of that so i can get rid of some blank spaces we MUST have on the flyout because of current resitrictions)
2) Tagged so you have a copy of this for later questions
3) How do we make a suggestion to MS / Xamarin team NOT related to issue's or bugs w xamarin?


[MovingToAndFromShell.zip](https://github.com/xamarin/Xamarin.Forms/files/3827928/MovingToAndFromShell.zip)

**Comment by sturlath** [comment] 2019-11-10 14:07
Thank you @PureWeen I updated the example with your recommendation but I still have a problem with the About tab not being shown as selected.

I also [added some comments in the code](https://github.com/sturlath/ShellProblem/blob/334a9eefd48c41399220f441ba09dcad7a78e3c1/App2/App2/AppShell.xaml#L36) to explain what was causing me problems. 

![AboutTabNotSelected](https://user-images.githubusercontent.com/2386572/68545236-0411c180-03c3-11ea-828e-ca485b2f3189.png)

@jamesmcmenamin thank you so much! I'm going over your code as we speak.

**Comment by PureWeen** [comment] 2019-11-10 19:13
@sturlath I don't think I'm following what you're trying to achieve

I don't know what you mean by this
https://github.com/sturlath/ShellProblem/blob/334a9eefd48c41399220f441ba09dcad7a78e3c1/App2/App2/AppShell.xaml#L36

The reason you aren't seeing the About hiighlighted is because you're adding an additional Tab Here
https://github.com/sturlath/ShellProblem/blob/334a9eefd48c41399220f441ba09dcad7a78e3c1/App2/App2/AppShell.xaml#L51

If you don't wrap something with Tab it'll still implicitly get wrapped in a tab

```XAML
    <TabBar>
        <!-- If you want to see the Tabs they need to be first! />-->
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>

        <ShellContent Route="AboutPage" ContentTemplate="{DataTemplate local:AboutPage}" />
    </TabBar>
```

Is the same thing as doing

```XAML
    <TabBar>
        <!-- If you want to see the Tabs they need to be first! />-->
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
        <Tab>
        <ShellContent Route="AboutPage" ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
    </TabBar>
```

So you're just navigating to a new tab if you want that middle tab to highlight then you need to have

```XAML
    <TabBar>
        <!-- If you want to see the Tabs they need to be first! />-->
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent Route="AboutPage"  ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
    </TabBar>
```

I'm curious why you are thinking you need to specify the About Page twice? I feel like I'm missing what you are trying to do

**Comment by PureWeen** [comment] 2019-11-10 19:16
@jamesmcmenamin 

> at XDS you showed us that IsVisible was coming for shell... What is up with that? (I did see you had basicly redesigned the entire navigation stack in the (I want to say hotel's app talk) is that public some were? would LOVE to get my hands on a minimum of that so i can get rid of some blank spaces we MUST have on the flyout because of current resitrictions)

I'm harassing the team to get this merged for 4.4.0 https://github.com/xamarin/Xamarin.Forms/pull/7847 . :-) 

> Tagged so you have a copy of this for later questions

Sounds good

> How do we make a suggestion to MS / Xamarin team NOT related to issue's or bugs w xamarin?

I would use this https://developercommunity.visualstudio.com/spaces/8/index.html and that should route to the proper teams

**Comment by jamesmcmenamin** [comment] 2019-11-12 07:10
@PureWeen You want some help with that? see alot of failing ui's on it at this point

**Comment by PureWeen** [comment] 2019-11-12 07:12
It just needs to be rebased

The master branch it's based on was failing and a fix for that just got merged in this morning

**Comment by davidortinau** [comment] 2020-02-28 15:47
Based on the original description this is not a bug, at least not now. 

This is the AppShell config. Note the routes.

```
<TabBar Route="home">
        <!-- If you want to see the Tabs they need to be first! />-->
        <Tab Title="Browse" Route="browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Route="about" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
</TabBar>
```

Register the route to NewItem:

```
public AppShell()
        {
            InitializeComponent();

            Routing.RegisterRoute("new", typeof(NewItemPage));
            
        }
```

Navigate to "new" from the add button.

```
async void AddItem_Clicked(object sender, EventArgs e)
        {
            await Shell.Current.GoToAsync("//home/new");
        }
```

Navigate to "about" from the new modal.

```
public static async Task NavigateToAboutPageAsync()
        {
            await Shell.Current.GoToAsync("//home/about");
        }
```

**Closed by davidortinau** 2020-02-28 15:47 UTC
Labels: a/shell :shell:, e/6 :clock6:, p/Android, t/bug :bug:
