### ISSUE TITLE
[Bug] CollectionView VSM selected state does not fire when item initially selected

### ISSUE THREAD

**Issue by Estevete** [xamarin/Xamarin.Forms#11584] opened 2020-07-28 08:04 UTC
### Description
CollectionView Visual State Manager selected state does not apply when an item is initially selected.

**_Haven't tried on Android._**

### Steps to Reproduce

1. Add collectionView with an item initially selected
2. Launch app UWP
3. Launch app iOS

### Expected Behavior
Selected item should have VSM selected state properties applied

### Actual Behavior
Properties are not applied until you select another item

### Basic Information

- Version with issue: 4.8.0.1187-pre2, 4.8.0.1187-pre1, ...
- Last known good version: None
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  iPhone 13.6
  - UWP:  18363.959
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/19273351/88635512-04203180-d0b8-11ea-97dd-c2bf96742414.png)

![image](https://user-images.githubusercontent.com/19273351/88635524-07b3b880-d0b8-11ea-9a02-11ba89b2cb47.png)

### Reproduction Link
[https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/CollectionView-selectedState](https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/CollectionView-selectedState
)

**Comment by MSicc** [comment] 2020-07-30 03:40
I need to confirm this one, but with the latest 4.7 package.

**Comment by MSicc** [comment] 2020-08-01 06:21
There are quite a few issues open already regarding this problem.

The only way I got this working was to add an IsSelected property to my ItemViewModel and Two-Way bind it with a converter in my DataTemplate.

![image](https://user-images.githubusercontent.com/68176309/89095597-ead8f700-d3cf-11ea-855f-bf7c4d99e0a7.jpeg)

**Comment by PureWeen** [comment] 2020-08-05 16:19
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/9511

**Closed by PureWeen** 2020-08-05 16:19 UTC
Labels: s/unverified, t/bug :bug:
