### ISSUE TITLE
[Bug] [Android] missing implementation of GetNamedColor(string) in class Xamarin.Forms.Forms/AndroidPlatformServices

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/Xamarin.Forms#10785] opened 2020-05-20 07:19 UTC
This is generating a crash at Android app's startup:

`VTable setup of type Xamarin.Forms.Forms+AndroidPlatformServices failed Exception`

Please see https://github.com/luberda-molinet/FFImageLoading/issues/1454 where I originally reported the issue.

Seems to have been introduced in XF 4.6 by https://github.com/xamarin/Xamarin.Forms/pull/10008

**Comment by nbsoftware** [comment] 2020-05-20 07:59
And I can confirm that downgrading back to XF 4.5.0.725 makes the application working again

**Comment by PureWeen** [comment] 2020-05-22 00:30
@nbsoftware can you make sure all your projects have the same version of XF installed?

`GetNamedColor` was added in 4.6 but FFImageLoading doesn't utilize it 

This should only cause a break with FFimageLoading if they were implementing `IPlatformServices` but I don't see that they are

Can you attach a repro?

**Comment by nbsoftware** [comment] 2020-05-22 06:33
@PureWeen 

> can you make sure all your projects have the same version of XF installed?

Well, only one referenced project was still on a lower version (4.5).
I'll make some tests to upgrade this one as well, but hey... how on earth is this even remotely possible?
I mean, when all projects are on the same XF 4.5 version, everything is working, but when all projects but one are on the XF 4.6 version, it crashes with the mentioned exception.

How can an Interface implementation be missing a method, and that would be all fine?

> Can you attach a repro?

I can't, just now. Project is too big. I would need some significant amount of time to isolate it.

**Comment by samhouts** [comment] 2020-05-26 23:59
@nbsoftware Can you confirm that updating all projects to the same version resolved the issue? Thanks!

**Comment by Jhultink** [comment] 2020-06-02 14:50
I had this same issue but with iOS: 

`VTable setup of type Xamarin.Forms.Forms+IOSPlatformServices failed`.

Rolling back to XF 4.5.0.725 fixed it for me as well.

**Comment by samhouts** [comment] 2020-06-13 16:41
@Jhultink Can you try updating to 4.6.0 again and ensure that all projects are updated to the same version? If the problem persists, can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Jhultink** [comment] 2020-06-24 18:41
@samhouts It still crashes with 4.6.x as well as 4.7.x. I was able to repro it with the Master-Detail template by adding in the PhantomLib nuget package. 
[CrashTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4827297/CrashTest.zip)

**Comment by samhouts** [comment] 2020-06-26 20:27
I updated the sample app to 4.7, and it did not crash. Can you please confirm that when you do the update, it definitely updates the Android project to 4.7? I suspect that you're using VS Mac, and you may need to explicitly update each project.

**Comment by Jhultink** [comment] 2020-06-26 20:44
It still crashes on 4.7 for me. Just to clarify, the crash is only on iOS, not Android.

**Comment by samhouts** [comment] 2020-06-26 22:25
@MagicAndre1981 had a similar problem that appeared to be resolved by updating Visual Studio. What version of Visual Studio are you using?

**Comment by MagicAndre1981** [comment] 2020-06-29 05:14
> @MagicAndre1981 had a similar problem that appeared to be resolved by updating Visual Studio. 

no, I updated SfDataGrid and XF the same time. I had the issue in my .net core 3.x branch where I have to use VS2019, the main branch where the app is build uses old .net core 2.2 libs (SignalR) and packages.config under VS2017 and here I had no issue after updating to 4.7 (except the [UWP scrollview-click issue](https://github.com/xamarin/Xamarin.Forms/issues/11174) which I have in both branches).

**Comment by Jhultink** [comment] 2020-06-29 15:33
I updated to the most recent version of VS for Mac and am still seeing the exception.

**Comment by thedee** [comment] 2020-07-02 04:01
I have similar error. Application crashes in release mode but not debug mode for Android. We are on Xamarin.Forms 4.6.0.967. Logcat shows:

```
android.runtime.JavaProxyThrowable: System.TypeLoadException: VTable setup of type Xamarin.Forms.Forms+AndroidPlatformServices failed
  at Xamarin.Forms.Forms.Init (Android.Content.Context activity, Android.OS.Bundle bundle) [0x0002e] in <d12be6fea8ff46ae816f5b18676473d5>:0 
  at RPT.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00032] in <10e40b3150e445a2bf0bfe4c242ce9bc>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <eaa205f580954a64824b74a79fa87c62>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.20(intptr,intptr,intptr)
	at crc645841afa52016fd7b.MainActivity.n_onCreate(Native Method)
	at crc645841afa52016fd7b.MainActivity.onCreate(MainActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MagicAndre1981** [comment] 2020-07-02 05:01
@thedee try [4.6.0.1073](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-4.6.0-sr5)

**Comment by thedee** [comment] 2020-07-03 01:57
@MagicAndre1981 thanks that seems to work.

**Comment by PureWeen** [comment] 2020-07-08 17:50
@Jhultink your exception is different 

It looks like your exception is happening because phantomlib is packaged wrong
They are including all the xamarin dlls in the lib folder so then it gets all messed up
If I just delete the xamarin libs from their lib dir in my nuget cache then the exception doesn't happen anymore

**Closed** 2020-07-08 17:50 UTC
Labels: 4.6.0, i/high, i/regression, p/Android, s/needs-info ❓, s/unverified, t/bug :bug:

**Comment by MagicAndre1981** [comment] 2020-07-09 07:16
@PureWeen 

I also [had the issue for Android](https://github.com/xamarin/Xamarin.Forms/issues/11157) and I don't use phantomlib. For me updating sfdatagrid + XF to 4.7 solved it (only update  from XF4.6 to 4.7 triggered the error). They [still link against Xamarin.Forms 3.6.0.344457 (3.6.0 Service Release 3)](https://www.fuget.org/packages/Syncfusion.Xamarin.SfDataGrid/18.2.0.44).

**Comment by PureWeen** [comment] 2020-07-09 15:40
@MagicAndre1981 apologies but I'm a little lost with your descriptions. I know the API in question `RegisterStylesheets` and the change but what combination of sdk versions are you saying are still broken?

**Comment by MagicAndre1981** [comment] 2020-07-10 12:46
@PureWeen as you discovered the issue happens when XF files have version mismatches. 

With packages.config (.net core 2.2 branch which I still use to ship the app with VS2017) I have no issues, but I think this issues is caused by PackageReference Include if you consume a nuget that is linked against an older XF version. In VS2019 I have to use PackageReference Include to [avoid SignalR issue](https://github.com/dotnet/aspnetcore/issues/22891).

**Comment by PureWeen** [comment] 2020-07-10 15:22
@Jhultink FYI
https://github.com/OSTUSA/PhantomLib/issues/50#issuecomment-656653112

**Comment by PureWeen** [comment] 2020-07-10 15:24
@MagicAndre1981 

> I think this issues is caused by PackageReference Include if you consume a nuget that is linked against an older XF version

This is only an issue if there's an ABI mismatch. 

>  if you consume a nuget that is linked against an older XF version.

What's the older version library that you are having issues with against XF?

**Comment by captainjono** [comment] 2020-07-23 03:29
@PureWeen 

Im using VS Mac, Xamarin.Mac and i updated last night to latest stables from previous stables.

im getting a VTable error, but for one of my projects types, not XF's. Are u able to help me understand whats going on here? How this error occours? Im trying to pin-point whats going on before downgrading. I had XF in my solution but i was no longer using it so i removed all the references and this still occours.

```
System.TypeLoadException: VTable setup of type <my-type> failed
  at (wrapper managed-to-native) System.Delegate.CreateDelegate_internal(System.Type,object,System.Reflection.MethodInfo,bool)
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) [0x002f0] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/Delegate.cs:286 
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/Delegate.cs:296 
  at System.Reflection.Emit.DynamicMethod.CreateDelegate (System.Type delegateType, System.Object target) [0x0001a] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs:192 
  at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.cs:261 
  at System.Linq.Expressions.Compiler.LambdaCompiler.Compile (System.Linq.Expressions.LambdaExpression lambda) [0x00019] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.cs:188 
  at System.Linq.Expressions.Expression`1[TDelegate].Compile (System.Boolean preferInterpretation) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs:209 
  at System.Linq.Expressions.Expression`1[TDelegate].Compile () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs:192 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.GetConstructorInvoker (System.Reflection.ConstructorInfo constructorInfo) [0x000d0] in <588c4afa13f141ccb8ad9629124e86a3>:0 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00077] in <588c4afa13f141ccb8ad9629124e86a3>:0 
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00068] in <588c4afa13f141ccb8ad9629124e86a3>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0001a] in <588c4afa13f141ccb8ad9629124e86a3>:0 
   --- End of inner exception stack trace ---
```

```=== Visual Studio Community 2019 for Mac ===

Version 8.6.7 (build 2)
Installation UUID: c6e40464-32b7-4ce2-813c-23f2b9330086
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.1.301
	3.1.300
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.1.5
	3.1.4
	2.1.20
	2.1.19
	2.1.18
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:42:50 UTC

=== Android Device Manager ===

Version: 16.6.0.96
Hash: 6e8b80b
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:43:28 UTC

=== Xamarin.iOS ===

Version: 13.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Build Information ===

Release ID: 806070002
Git revision: f92d3b9b30e8a977be3e2bffa86728c2e38e88c8
Build date: 2020-07-17 09:06:49-04
Build branch: release-8.6
Xamarin extensions: f92d3b9b30e8a977be3e2bffa86728c2e38e88c8

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:47:48 PST 2020
    root:xnu-6153.101.6~16/RELEASE_X86_64 x86_64

```
