### ISSUE TITLE
FlexLayout does not handle InVisible children

### ISSUE THREAD

**Issue by Omarkth** [xamarin/Xamarin.Forms#2698] opened 2018-05-14 11:45 UTC
### Description
FlexLayout does not handle InVisible children properly.

### Steps to Reproduce

Check @davidortinau's flexibility project [https://github.com/davidortinau/flexibility](https://github.com/davidortinau/flexibility)

Open the "ShowPage" and change the poster Image "IsVisible" to "False".

[https://github.com/Omarkth/flexibility/commit/9e9f80ba76988d3e00f504c0d7e1f33fa18ca728](https://github.com/Omarkth/flexibility/commit/9e9f80ba76988d3e00f504c0d7e1f33fa18ca728)

### Expected Behavior
Children with "IsVisible=False" should not be considered for the Flex calcualtions

### Actual Behavior
FlexLayout child still occupy its space even when its "IsVisible" property is set to "False"

### Screenshots

![image](https://user-images.githubusercontent.com/822615/39995417-c9ad6882-5784-11e8-8387-3ba518515125.png)

**Comment by StephaneDelcroix** [comment] 2018-05-14 13:26
duplicate of #2593. This will be fixed in 3.0.0-sr1

**Closed by StephaneDelcroix** 2018-05-14 13:26 UTC
Labels: a/flex, s/duplicate, t/bug :bug:

**Comment by azrinsani** [comment] 2021-05-15 12:55
Hello is this year 2021?
