### ISSUE TITLE
UWP Window resize throws exception 

### ISSUE THREAD

**Issue by seankanderson** [xamarin/Xamarin.Forms#5362] opened 2019-02-24 22:14 UTC
### Description
Exception thrown in UWP project when resizing a window 
MasterBehavior = MasterBehavior.Popover;

Only occurs when set to Popover. 

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Xamarin.Forms.Platform.UAP
  StackTrace:
   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.OnIsPaneOpenChanged(DependencyObject sender, DependencyProperty dp)

### Steps to Reproduce

1. Build and run this XF UWP project: 
https://github.com/seankanderson/XamarinFormsUwpMasterDetailException
2. Navigate to view the masterdetail menu
3. Grab bottom right corner and resize to make the window larger
3. Notice Error/Exception in Output window.

### Expected Behavior
Should not throw an exception 

### Actual Behavior
Exception is thrown (this condition causes the back button to fail, requiring user to hit it a few times to go back once)

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version: ???
- IDE: Visual Studio 2017 15.9.4
- Platform Target Frameworks: 
   - UWP:  target doesnt matter (been using 16299+)

### Screenshots
Screenshots of my main development project/app: 
![image](https://user-images.githubusercontent.com/1112636/53304867-70a25b80-3848-11e9-9a4a-eeeef0cababe.png)

![image](https://user-images.githubusercontent.com/1112636/53304870-7e57e100-3848-11e9-9a75-8f2c9e5e3a5f.png)

### Reproduction Link

https://github.com/seankanderson/XamarinFormsUwpMasterDetailException

**Comment by paymicro** [comment] 2019-03-05 11:28
Hello @seankanderson 
I could not reproduce this issue using your repro steps
![](http://g.recordit.co/Jv8TxphQS6.gif)
Could you describe in more detail how to reproduce it?

**Comment by seankanderson** [comment] 2019-03-06 01:56
It was/is actually due to a bug in visual studio. Not sure what is triggering it but restarting the computer makes it go away for a while.

**Comment by paymicro** [comment] 2019-03-06 09:08
That is, in the release version of the application without debugging this issue does not appear?

**Comment by jfversluis** [comment] 2019-07-23 12:34
Since this issue could not be reproduced for now I will close this. If it happens again and have some more info we will be happy to have another look!

**Closed by jfversluis** 2019-07-23 12:34 UTC
Labels: e/1 :clock1:, p/UWP, s/unverified, t/bug :bug:
