### ISSUE TITLE
[Android] Label's HorizontalTextAlignment resetting after redraw

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/Xamarin.Forms#2759] opened 2018-05-17 19:41 UTC
### Description

When the text of a Label is changed after it's drawn, the `HorizontalTextAlignment` acts strangely. I know its not descriptive enough, but it's better explained in the repro project.

I saw three possibilities when testing this issue:
- The Label appears right, but when the app minimized and opened again, the HorizontalAlignment resets.
- The Label already already appears with the wrong `HorizontalTextAlignment` and, if the app is minimized and opened, it stays wrong.
- The same as before, but when minimized and opened, the `HorizontalTextAlignment` is fixed and goes back to normal.

Basically, run the repro project and you'll see three Labels, all with `HorizontalTextAlignment` set to Center:
- The first one is a single lined Label that has its Text changed 200ms after the Page's constructor is ran.
- The second one is the same as the first, but with a multiline text.
- The third one is a single lined Label that has its Text changed on `OnSizeAllocated` and `VerticalTextAlignment` set to `Center` as well.

The first two Labels are displaying correctly, but the third one will appear with the wrong horizontal alignment (I added the `VerticalTextAlignment` just to show that it doesn't have this issue) right from the start.

After that, minimize and open the app again. The alignments invert, with the first Label resetting to Left and the third Label going to the Center. The second Label is there just to show that this issue is not happening with multiline texts.

Now, if you go back to the project and comment line 38 (remove the second Label from StackLayout's children), open the app again, minimize it and open it again, the third Label, that displayed correctly after the app came back from background with the second Label on the Page, no longer gets fixed, remaining aligned with the Left.

### Steps to Reproduce

1. Run the project and notice the Labels alignment (all should be centered but the third one isn't).
2. Minimize and open the app.
3. The first Label is left-aligned and the third one is fixed.
4. Comment line 38 and re-run the project.
5. The app starts as last time.
6. Minimize and open the app.
7. The "third" Label is not fixed as before.

### Expected Behavior

All Labels get centered.

### Actual Behavior

Sometimes they're centered, other times they are not.

### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: none
- IDE: VS for Mac
- Platform Target Frameworks:
  - Android: 8.1

### Screenshots

With three Labels:
![firstapp](https://user-images.githubusercontent.com/12024080/40199598-6b62e982-59f0-11e8-93cf-ef95eff1c89e.png)

With three Labels after coming from background (the "First label" is wrong and the "Third Label" is fixed):
![firstapp-afterminimize](https://user-images.githubusercontent.com/12024080/40199599-6b88334a-59f0-11e8-89b6-c1a838808be3.png)

With two Labels after coming from background (the "Third label" is not fixed):
![secondapp-afterminimize](https://user-images.githubusercontent.com/12024080/40199600-6bbb05b8-59f0-11e8-94a6-ee687237043e.png)

### Reproduction Link

[LabelAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/2014469/LabelAlignment.zip)

**Comment by hartez** [comment] 2018-05-17 20:53
@pauldipietro This might be a variation of #1396 or #1415, in which case #2215 would fix it.

**Comment by PureWeen** [comment] 2018-05-17 23:01
@pauldipietro  no https://github.com/xamarin/Xamarin.Forms/pull/2743 deals with HorizontalTextAlignment just flat out not working if you don't have RTL enabled inside the ApplicationManifest plus it only deals with Entry type fields not labels

**Comment by tmt242001** [comment] 2018-06-06 01:56
Issue still exist in 3.0.0.530893

**Comment by tmt242001** [comment] 2018-06-07 02:28
It Works now. Tested on 3.0.0.550146 (rebuild after deleting bin and obj folders)

**Comment by luccasclezar** [comment] 2018-06-07 16:42
I tested on 3.0.0.550146 and it's better, but the issue persists if the `thirdLabel.Text` is changed on `OnSizeAllocated`.

If I change all texts inside the `BeginInvokeOnMainThread` after the `Task.Delay`, it works as expected, but when the change happens inside `OnSizeAllocated` (even if wrapped inside a `BeginInvokeOnMainThread`) the thirdLabel's Text becomes left-aligned after reopening the app.

I don't know why the issue persists only when inside `OnSizeAllocated`, but it's a big improvement over the initial issue.

**Comment by PureWeen** [comment] 2018-06-07 20:15
@luccasclezar  I don't think that's related to this issue. Can you create a new issue with your use case with a small repro please?

**Comment by jassmith** [comment] 2018-06-25 23:31
Duplicate of #1557

**Closed by jassmith** 2018-06-25 23:31 UTC
Labels: p/Android, t/bug :bug:
