### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by muhammadghani** [xamarin/Xamarin.Forms#9381] opened 2020-01-31 06:19 UTC
QueryProperty doesn't work with Xamarin Forms 4.5 pre-2. Can't pass string parameter to another page in Shell App.

### Steps to Reproduce

1. Create Shell App upgrade to 4.5 pre-2
2. Add  [QueryProperty("Name", "name")] in ItemDetailViewModel
3. Add Name property  
        private string name;
        public string Name
        {
            set {
                name = Uri.UnescapeDataString(value);
                OnPropertyChanged();
            }
            get => name;
        }
4. Define routes on AppShell.xml.cs
  routes.Add("home", typeof(AboutPage));
            routes.Add("items", typeof(ItemsPage));
            routes.Add("detail", typeof(ItemDetailPage));
            foreach (var item in routes)
            {
                Routing.RegisterRoute(item.Key, item.Value);
            } 
5. From About page    call    await Shell.Current.GoToAsync($"//items/detail?name=HiItem");

### Expected Behavior
 ItemDetail page should appear and name parameter should get pass to ItemDetail page and assinged to Name property.
### Actual Behavior
ItemDetail page appear without parameter value
### Basic Information

- Version with issue: Xamarin Forms 4.5.0.187-pre2 
- Last known good version: same solution works fine with XF 4.3.0.991250
- IDE: Visual Studio 2019 14.4.2
- Platform Target Frameworks:   - Android: 8 and 9  

### Workaround
downgrade to Xamarin Forms 4.3.0.991250

**Comment by samhouts** [comment] 2020-01-31 19:20
Duplicate of #9344

**Closed by samhouts** 2020-01-31 19:20 UTC
Labels: s/unverified, t/bug :bug:
