### ISSUE TITLE
Using "CachingStrategy=RecycleElement" for ListView results in continuous memory allocation on Android app

### ISSUE THREAD

**Issue by sjavashev** [xamarin/Xamarin.Forms#13992] opened 2021-03-11 12:24 UTC
Using a XAML ListView Xamarin Forms control with binded "ItemsSource" to a constant array of string, result in continuous memory allocation, when the ListView has its "CachingStrategy" set to "RecycleElement" or "RecycleElementAndDataTemplate"

Code to reproduce is below. It is based on a newly created blank Xamarin Forms app with VS 16.9.1, targeting only Android. 

The following picture shows the version of the Nuget packages used:
![image](https://user-images.githubusercontent.com/57228456/110786336-b1753d80-8274-11eb-8875-6836041dae06.png)

The following code files were changed:

XAML:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
			 x:Class="AppTestListView.MainPage">

	<StackLayout>

		<ListView ItemsSource="{Binding Names}" SelectionMode="None"
				  CachingStrategy="RecycleElement">
		</ListView>

	</StackLayout>

</ContentPage>`
```

C#:
```
namespace AppTestListView {
	public partial class MainPage : ContentPage {
		public MainPage() {
			InitializeComponent();
			BindingContext = this;
		}

		public string[] Names => new string[] { 
			"Peter",
			"George",
			"Nick",
		};
	}
}
```
Result: Output pane is continuously updated with GC processings, until the app is terminated

![image](https://user-images.githubusercontent.com/57228456/110785419-9bb34880-8273-11eb-8a02-7fd0afe7bbc8.png)

...

![image](https://user-images.githubusercontent.com/57228456/110785458-a79f0a80-8273-11eb-8592-9382809b2c7f.png)

...

![image](https://user-images.githubusercontent.com/57228456/110785897-24ca7f80-8274-11eb-9df3-56632e413cd7.png)

> VS bug [#1315252](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1315252)

**Comment by jtorvald** [comment] 2021-03-16 13:31
Just figured out that I added a duplicate of this issue as #14010 with an iOS example.

**Comment by jsuarezruiz** [comment] 2021-03-24 11:55
Need to investigate more, but, could be related with: https://github.com/xamarin/Xamarin.Forms/issues/14020?

**Comment by sjavashev** [comment] 2021-03-24 12:02
> 
> 
> Need to investigate more, but, could be related with: #14020?

If I could help in some way, just let me know!

**Comment by rmarinho** [comment] 2021-04-20 10:58
@sjavashev  do you have hotreload enabled ?

**Comment by dmariogatto** [comment] 2021-04-20 21:55
@rmarinho @sjavashev 

Disabling Hot Reload does __fix__ the excessive GC collections when displaying a ListView, at least for me. 

VS Windows _16.9.4_
VS macOS _8.9.6_ 
XForms _5.0.0.2012_

**Comment by sjavashev** [comment] 2021-04-21 08:46
> 
> 
> @sjavashev do you have hotreload enabled ?
@rmarinho yes, I do and also, as @dmariogatto mentioned, when I disable it it is OK.

**Comment by wfreeman93** [comment] 2021-07-14 15:30
With this issue still open, what does this entail for the coming release of Visual Studio 2022 and .NET MAUI? Should we expect to see this bug, has anyone confirmed it still an issue in 2022 previews? Although the work around is very simple, we effectively do not get to use hot reload on any of our apps while debugging.

**Comment by Simbaclaws** [comment] 2021-09-28 11:22
This bug appears in visual studio 2022 preview as well.

**Closed** 2021-09-29 04:41 UTC
Labels: t/bug :bug:, s/needs-info ❓, a/listview, s/unverified, external-hotreload
