### ISSUE TITLE
Span's Text Property are not Changing when Binding

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/Xamarin.Forms#4451] opened 2018-11-17 13:39 UTC
### Description

When I tried to bind text property to a string property in the view model, it is working like OneWayToSource, which means if I tried to notify property from the view model, nothing is changing in the view

### Steps to Reproduce

1. Add Entry control to a page
2. Bind TextProperty or PlaceHolderProperty to any string Property in your view model class
3. Change property value in view model and notify the changed (nothing will happen)

### Expected Behavior
Update the Text or PlaceHolderText value if I changed it from the view model class

### Actual Behavior
Text property or Placeholder property are not changed 

### Basic Information
Xamarin Forms Lib: 3.4.0.1
OS: this occurred in Android 8.1, not tested IOS yet

I noticed this issue in Span's Text (inside label control) also

**Comment by rmarinho** [comment] 2018-11-22 12:40
Hi , so can you add a sample showing how you are setting up the Bindings I m not being able to reproduce this.  Here's the code I used on iOS and Android 

```
	var master = new ContentPage
			{
				Title = "Master",
				BackgroundColor = Color.SkyBlue,
				Icon = "menuIcon"
			};
			var layout = new StackLayout { BackgroundColor = Color.Red };
		
			var entry = new Entry();

			entry.SetBinding(Entry.TextProperty, new Binding("Title"));
			entry.SetBinding(Entry.PlaceholderProperty, new Binding("Title"));
			entry.BindingContext = master;


			layout.Children.Add(entry);
			layout.Children.Add(new Button
			{
				Text = "Change image",
				Command = new Command(() =>
				{
					master.Title = "I changed";
				})
			});

			master.Content = layout;
```

**Comment by moustafashaban** [comment] 2018-12-22 08:54
Thanks for working on this, and sorry for my late reply
In terms of Entry I found the issue, it was in my Entry renderer I forgor the base.OnElementPropertyChanged(sender, e); in my OnElementPropertyChanged function

but the span issue is still there, 

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XF_SpanBindTest"
             x:Class="XF_SpanBindTest.MainPage">

    <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
        <Label Text="{Binding Text1}" TextColor="Green"/>
        <Label TextColor="Blue">
            <Label.FormattedText >
                <FormattedString>
                    <Span Text="{Binding Text1}"/>
                </FormattedString>
            </Label.FormattedText>
        </Label>

        <Button Text="Change Texts" Command="{Binding ChangeTextCommand}"/>
    </StackLayout>
</ContentPage>
```

ViewModel:

```
    public class MainPageViewModel : INotifyPropertyChanged
	{
		public MainPageViewModel()
		{
			ChangeTextCommand = new Command(ChangeTextCommand_Execute);
		}

		public string Text1 { get; set; } = "My Text1";

		public ICommand ChangeTextCommand { get; set; }
		void ChangeTextCommand_Execute()
		{
			Text1 += "A";
			NotifyPropertyChanged("Text1");
		}


		#region INotify
		public event PropertyChangedEventHandler PropertyChanged;
		public void NotifyPropertyChanged(string info)
		{
			if (PropertyChanged != null)
			{
				PropertyChanged(this, new PropertyChangedEventArgs(info));
			}
		}
		#endregion
	}
```

and in MainPage.xaml.cs 

```
public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
			BindingContext = new MainPageViewModel();
		}
	}
```
you will find that Labe text is updated while Span Text not

**Comment by PureWeen** [comment] 2019-01-02 20:58
Closing for now as OneTime binding for Spans is currently by design for performance reasons.
We can discuss in the PR if taking on a breaking change to change that will happen but I doubt it.

**Closed by PureWeen** 2019-01-02 20:58 UTC
Labels: s/needs-info ❓, s/needs-repro ❔
