### ISSUE TITLE
[Bug] CarouselView is always taking full vertical space of the page

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8993] opened 2019-12-20 21:27 UTC
### Description
CarouselView is always taking full vertical space of the page even if it has not set
```
VerticalOptions = "FillAndExpand"
```
or something like that

Look at this GIF
![carousel_view_full_space](https://user-images.githubusercontent.com/17653648/71293574-26a9d980-2376-11ea-8680-18d84f0d0c26.gif)

As you can see CarouselView is taking full height of the page. Here is the code for this page:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:viewModels="clr-namespace:CarouselViewTest.ViewModels"
             mc:Ignorable="d"
             x:Class="CarouselViewTest.MainPage">
    <ContentPage.BindingContext>
        <viewModels:MainPageVM/>
    </ContentPage.BindingContext>

    <StackLayout Margin="10">
        <Label Text="Products" FontSize="Large" />
        <CarouselView x:Name="carouselView" ItemsSource="{Binding Products}">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <StackLayout VerticalOptions="Center">
                        <Frame HasShadow="True" CornerRadius="5" BorderColor="DarkGray">
                            <StackLayout>
                                <Image Source="{Binding Image}"/>
                                <Label Text="{Binding Title}" FontAttributes="Bold" FontSize="Title"/>
                                <Label Text="{Binding Description}" FontSize="Subtitle"/>
                            </StackLayout>
                        </Frame>
                    </StackLayout>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
        <IndicatorView ItemsSourceBy="carouselView" IndicatorColor="LightGray" SelectedIndicatorColor="DarkGray"
                   HorizontalOptions="Center" />
        <Button Text="Submit"/>
    </StackLayout>

</ContentPage>

```

As you can see CarouselView has no VerticalOptions set so it should have the default value
```
VerticalOptions = "FillAndExpand"
```
thus it should take a minimum amount of vertical space but instead, it takes full vertical space of the page.

Right now there is no way to make CarouselView to take only the space what it needs

### Steps to Reproduce

1. Run this project on Android
[CarouselViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3990333/CarouselViewTest.zip)

2. As you can see CarouselView is taking full vertical space of the page.

### Expected Behavior
CarouselView should take only the minimum vertical space which it needs

### Actual Behavior
CarouselView is taking full vertical space of the page even though
```
VerticalOptions = "FillAndExpand"
```
is not set

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 16.4.2
- IDE:
- Platform Target Frameworks: 
  - Android: Android: 9.0 (Pie)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment] 2019-12-23 13:53
Duplicate of #8640

**Closed by jfversluis** 2019-12-23 13:53 UTC
Labels: s/unverified, t/bug :bug:
