### ISSUE TITLE
[Bug] Label underline not working on iOS

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8585] opened 2019-11-20 17:07 UTC
### Description

Just create a label with **"TextDecorations="Underline"** .

i.e.
```
<Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" TextDecorations="Underline"/>
```

Underline is visible only on Android. On iOS setting underline for a label has no effect.

### Expected Behavior
Underline should work on Android on iOS.

### Actual Behavior
Underline is only working on Android.

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: Visual Studio 2019 16.3.9

**Comment by jfversluis** [comment] 2019-11-20 18:47
Duplicate of #8272

**Closed by jfversluis** 2019-11-20 18:47 UTC
Labels: s/unverified, t/bug :bug:
