### ISSUE TITLE
[Bug] x:DataType="{x:Null}" results in "x:DataType expects a string literal" error

### ISSUE THREAD

**Issue by SebastianKruseWago** [xamarin/Xamarin.Forms#7423] opened 2019-09-06 13:10 UTC
Using `x:DataType="{x:Null}"` to reset compiled bindings as suggested here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings#combining-compiled-bindings-with-classic-bindings 

Results in a error message saying "x:DataType expects a string literal". Also nested types don't seems to be working...

**Comment by jfversluis** [comment] 2019-09-06 13:14
Could you please provide some more info as requested by the [issue template](https://github.com/xamarin/Xamarin.Forms/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

In particular, which version of Forms are you using? There are a couple of issues that already seem to report this and a [fix has been merged](https://github.com/xamarin/Xamarin.Forms/pull/6822) in 4.2 to solve this.

**Comment by StephaneDelcroix** [comment] 2019-09-09 07:44
actually, it has been fixed in 4.1

I'm closing this as a duplicate of #6648, please reopen if it still happen on newer releases. Please provide a sample project at that time

**Closed by StephaneDelcroix** 2019-09-09 07:44 UTC
Labels: a/Xaml </>, i/high, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
