### ISSUE TITLE
[Bug] Shell Navbar ignoring colors on iOS 15.0

### ISSUE THREAD

**Issue by Lizcq11** [xamarin/Xamarin.Forms#14975] opened 2021-12-09 22:46 UTC
### Description

Hi!
I've been having an issue with the Shell Navbar, I've created a custom shell renderer for the navbar, where I implemented a gradient, I use the interface IShellNavbarAppearanceTracker and set the gradient in the method SetAppearance.
This issue is only happening on devices with iOS 15, I tested my app on a device with iOS 14.8.1 and everything works as expected, the gradient in the navbar works fine.

### Steps to Reproduce

1. Create app from Shell
2. Create a Shell renderer
3.  Implement a custom gradient with IShellNavbarAppareanceTracker, set the gradient in the method SetAppearance.
4. Run app on device/ simulator with iOS 15.0

### Expected Behavior
Shell Navigation bar should implement the gradient in all views, everything works fine on devices with iOS previous version 15.0
I tested on a device with iOS 14.8.1 and it works.

### Actual Behavior
The shell navbar is always  white
### Basic Information

- Version with issue: Xamarin forms 5.0.0.2244

- Platform Target Frameworks:
  - iOS:  iOS 15.0 
- Affected Devices:
- All devices with iOS 15.0

### Environment
I currently have this setup:

Xamarin forms last stable version 5.0.0.2244
Xcode version 13.1 (13A1030d)
Visual studio for Mac version 8.10.14 (build 17)

### Screenshots
This image shows the behavior on Iphone simulator running iOS 15.0, but the same happens on a physical device.
![ErroriOS](https://user-images.githubusercontent.com/95886766/145487172-d13ca104-3cb5-4cfb-9fe4-8df1658418cb.png)

### Workaround
I have tried with the shell renderer posted on this similar issue https://github.com/xamarin/Xamarin.Forms/issues/14505, where a background color is set for the Navbar, but nothing changed.
Please let me know if there is some workaround about this, I really need to get this fixed and realease my app asap. Thanks!

**Comment by jsuarezruiz** [comment] 2021-12-10 08:26
Could you attach a sample with your custom implementation of `IShellNavbarAppareanceTracker`?

**Comment by Lizcq11** [comment] 2021-12-10 16:46
@jsuarezruiz  This is the implementation of the IShellNavbarAppearanceTracker

using MyApp.iOS.Renderers;
using System.ComponentModel;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(AppShell), typeof(ShellNavbarRendereriOS))]

namespace MyApp.iOS.Renderers
{
    public class ShellNavbarRendereriOS : ShellRenderer
    {
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
        }

          protected override IShellNavBarAppearanceTracker CreateNavBarAppearanceTracker()
         {
            return new CustomNavbarAppearance();
         }
   }
}

using CoreAnimation;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

namespace MyApp.iOS
{
         public class CustomNavbarAppearance : IShellNavBarAppearanceTracker
    {
               public void SetAppearance(UINavigationController controller, ShellAppearance appearance)
                    {
                         CAGradientLayer gradient = new CAGradientLayer();
                         gradient.Frame = controller.NavigationBar.Bounds;
                         gradient.Colors = new CoreGraphics.CGColor[] { new UIColor(red: 0.09f, green: 0.83f, blue: 0.92f, alpha: 
                         1.00f).CGColor, new UIColor(red: 0.00f, green: 0.18f, blue: 0.55f, alpha: 1.00f).CGColor };
                         gradient.StartPoint = new CoreGraphics.CGPoint(0, 0);
                        gradient.EndPoint = new CoreGraphics.CGPoint(1, 0);
                       controller.NavigationBar.SetBackgroundImage(ImageFromLayer(gradient), UIBarMetrics.Default);
                       controller.NavigationBar.TintColor = UIColor.White;
        }

        private UIImage ImageFromLayer(CALayer layer)
        {
            UIGraphics.BeginImageContext(layer.Frame.Size);
            layer.RenderInContext(UIGraphics.GetCurrentContext());
            UIImage outputImage = UIGraphics.GetImageFromCurrentImageContext();
            UIGraphics.EndImageContext();
            return outputImage;
        }

        
    }
}

**Comment by muhamadsalibi** [comment] 2021-12-14 10:10
This seems like an issue with Shell. I have this issue without using a custom renderer. I can even reproduce with the default template @jsuarezruiz

iOS - Dark Mode
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-12-14 at 10 53 38](https://user-images.githubusercontent.com/20516755/145977398-df57587e-9454-43ea-908f-a8efdab6d220.png)

iOS - Light Mode
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-12-14 at 11 02 14](https://user-images.githubusercontent.com/20516755/145977407-b07dee6c-bd7e-4d38-a306-815a207f3b68.png)
 
Android
![1639476108164](https://user-images.githubusercontent.com/20516755/145977546-2cba7f18-c688-4eb3-91ad-a5de30ed95e2.jpg)

[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/7710617/TestApp.zip)

**Comment by muhamadsalibi** [comment] 2021-12-14 10:22
Updating Xamarin Forms to 5.0.0.2244 Solves the problem for me.

**Comment by jfversluis** [comment] 2022-01-04 09:39
@Lizcq11 thanks for your patience during the holidays, let's get this fixed!

Would you also be able to put together a little sample how you set the gradient from your app? So ideally a little GitHub repo with just the bits that you have in your app to make this happen. That will greatly help us identify the path through our codebase and see how we can fix it.

**Comment by Lizcq11** [comment] 2022-01-04 22:38
@jfversluis Thanks for your response, I have created a repo with an example of how I am implementing the gradient and the shellnavbar renderer, you can check out both projects Android and iOS and see the behavior.

https://github.com/Lizcq11/ShellNavbarRenderer

**Comment by Lizcq11** [comment] 2022-01-05 15:41
@jfversluis Thanks for your response, I have created a repo with an example of how I am implementing the gradient and the shellnavbar renderer, you can check out both projects Android and iOS and see the behavior.

https://github.com/Lizcq11/ShellNavbarRenderer

**Comment by jfversluis** [comment] 2022-01-06 15:52
Thanks @Lizcq11 !

Because of changes in the iOS APIs you now need to set things through the appearance API.

Change it to this in your renderer:

```csharp
public void SetAppearance(UINavigationController controller,ShellAppearance appearance)
        {
            // Added 3 lines here
            var navBar = controller.NavigationBar;
            var navigationBarAppearance = new UINavigationBarAppearance();
            navigationBarAppearance.ConfigureWithOpaqueBackground();

            CAGradientLayer gradient = new CAGradientLayer();
            gradient.Frame = controller.NavigationBar.Bounds;
            gradient.Colors = new CoreGraphics.CGColor[] { new UIColor(red: 0.09f,green: 0.83f,blue: 0.92f,alpha: 1.00f).CGColor,new UIColor(red: 0.00f,green: 0.18f,blue: 0.55f,alpha: 1.00f).CGColor };
            gradient.StartPoint = new CoreGraphics.CGPoint(0,0);
            gradient.EndPoint = new CoreGraphics.CGPoint(1,0);

            // Changed/Added 2 lines here
            navigationBarAppearance.BackgroundImage = ImageFromLayer(gradient);
            navBar.ScrollEdgeAppearance = navBar.StandardAppearance = navigationBarAppearance;

            controller.NavigationBar.TintColor = UIColor.White;
        }
```

![image](https://user-images.githubusercontent.com/939291/148410593-473b5e23-dea6-4dcf-ac6f-8d6e8a7eba31.png)

Closing this as this should fix it. Ping me if you still have issues with it :)

**Closed by jfversluis** 2022-01-06 15:52 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/shell :shell:, a/customrenderer, s/unverified, iOS 15

**Comment by Lizcq11** [comment] 2022-01-07 16:15
Thank you so much for your help @jfversluis everything works fine!

**Comment by jfversluis** [comment] 2022-01-07 16:17
Glad to hear it!
