### ISSUE TITLE
[Bug] UnVisivle Item still hold space When CollectionView ItemsLayout set to GridItemsLayout

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/Xamarin.Forms#11422] opened 2020-07-14 01:31 UTC
### Description
UnVisivle Item still hold space When CollectionView ItemsLayout set to GridItemsLayout,but when change ItemsLayout to HorizontalList or default,it show ok!

### Expected Behavior
UnVisivle Item not hold space When CollectionView ItemsLayout set to GridItemsLayout

### Basic Information
xamarin forms version : 4.2.0.778463

### Screenshots

![image](https://user-images.githubusercontent.com/1481403/87370060-91419180-c5b4-11ea-8fc4-7b38c3ce9c93.png)

**Comment by samhouts** [comment] 2020-07-14 01:59
Duplicate of #8227

**Closed by samhouts** 2020-07-14 01:59 UTC
Labels: s/unverified, t/bug :bug:

**Comment by llzz19851985** [comment] 2020-08-03 02:21
@samhouts Is there any new progress?
