### ISSUE TITLE
ScrollView IsClippedToBounds="true" not rendering on Android with Forms 3.3, 3.4 and 3.5

### ISSUE THREAD

**Issue by BlueFire-LLC** [xamarin/Xamarin.Forms#5225] opened 2019-02-13 01:29 UTC
I'm reopening this bug since it still exists with Xamarin Forms 3.5. I've attached a sample form.

In Xamarin Forms 3.2 everything works great but starting with Forms 3.3 the first scroll page renders but subsequent pages do not. See the  related closed bug post for screenshots.

When setting IsClippedToBound off, the pages render but overlay the buttons.

This only applies to Android. My iOS and Windows 10 projects render correctly.

[BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2858420/BugTest.zip)

**Comment by samhouts** [comment] 2019-02-13 18:26
Duplicate of #4455

**Closed by samhouts** 2019-02-13 18:26 UTC
Labels: t/bug :bug:
