### ISSUE TITLE
ContentPage Appearing & Disappearing Transition 

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7561] opened 2019-09-18 05:29 UTC
Hi,

It will be great if you add a transition for the PageContent’s OnAppearing and OnDisappearing so page can be opened with Fade, Slide from Top, bottom, right and left, etc

Thanks,
Jassim

**Comment by lavilaso** [comment] 2019-09-18 05:53
They are already working on a specification for this [here](https://github.com/xamarin/Xamarin.Forms/issues/6033)

**Comment by lavilaso** [comment] 2019-09-18 06:17
In the meantime you can try these options:
[AnimationNavigationPage](https://github.com/AlexandrNikulin/AnimationNavigationPage)
[Xamarin.Plugin.SharedTransitions](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions)

**Comment by samhouts** [comment] 2019-09-18 17:41
Duplicate of #6033

**Closed by samhouts** 2019-09-18 17:41 UTC
Labels: proposal-open, t/enhancement ➕
