### ISSUE TITLE
Cannot compile blank Xamarin app after upgrading xamarin stuff

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8678] opened 2019-11-26 18:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/816759/cannot-compile-blank-xamarin-app-after-upgrading-x.html)._

---
Just create blank Xamarin.Forms application using wizard.
Build it.
Next, open NuGet package manager for Xamarin project.
You will see that there are some libs to uprade. Upgrade them and try to build solution. You will see such errors:

1. Error	MSB4064	The "ValidateOnly" parameter is not supported by the "XamlCTask" task. Verify the parameter exists on the task, and it is a settable public instance property.	App4	C:\Users\ajachocki\.nuget\packages\xamarin.forms\4.3.0.947036\build\Xamarin.Forms.targets	116		

2. Error	MSB4063	The "XamlCTask" task could not be initialized with its input parameters. 	App4	C:\Users\ajachocki\.nuget\packages\xamarin.forms\4.3.0.947036\build\Xamarin.Forms.targets	110		

3. Error		The "FilterAssemblies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'D:\ws\App4\App4\App4\bin\Debug\netstandard2.0\App4.dll'.
File name: 'D:\ws\App4\App4\App4\bin\Debug\netstandard2.0\App4.dll'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Xamarin.Android.Tasks.FilterAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask>d__26.MoveNext()	App4.Android

---
#### Visual Studio Feedback System on 11/13/2019, 02:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Khairul on 11/13/2019, 07:04 PM: 

<p>Same here. After upgrade to Xamarin version 4.3.0.991211 - published by Microsoft on Thursday, November 14, 2019 (11/14/2019)</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2019-11-27 16:26
This should not happen when all versions on all projects are inline and you made sure to rebuild and clean, etc. everything.

There is already an issue tracking this as well. I will close this one as a duplicate. If you have anything to add to that, please do it there or reopen if you feel that issue does not describe what you are seeing.

**Comment by jfversluis** [comment] 2019-11-27 16:26
Duplicate of #8209

**Closed by jfversluis** 2019-11-27 16:26 UTC
Labels: feedback-ticket, s/unverified, t/bug :bug:
