### ISSUE TITLE
[Android] xamarin forms webview throws class not found exception on Android 7.0

### ISSUE THREAD

**Issue by KaizerT** [xamarin/Xamarin.Forms#2783] opened 2018-05-19 18:19 UTC
### Description
I am trying to use a webview to display html content on my xamarin forms application, however when the content is loaded I encounter a barrage of errors regarding the default android webview class. I've read that this might be a bug with android 7.0 and above but I just wanted to know if there are fixes/workarounds for this. Thank you.

Device tested on:

HTC One M9 Android 7.0 Nougat

Code:

```
WebView webBody = new WebView();
webBody.BackgroundColor = Color.Red;
webBody.Source = new HtmlWebViewSource { Html = oNotif.Message };
webBody.HeightRequest = stkWeb.Height;
webBody.WidthRequest = Application.Current.MainPage.Width;
stkWeb.Children.Add(webBody);
```
Error

> 05-17 21:46:40.632 I/cr_base (16907): Android Locale: en_US requires .pak files: [en-GB.pak, en-US.pak] 05-17 21:46:40.718 I/art
> (16907): Rejecting re-init on previously-failed class java.lang.Class: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail; 05-17 21:46:40.718 I/art
> (16907): at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:48) 05-17 21:46:40.718 I/art
> (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:635) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:571) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int) (WebView.java:554) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet) (WebView.java:541) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context) (WebView.java:531) 05-17 21:46:40.718 I/art (16907): at void mono.java.lang.RunnableImplementor.n_run() (RunnableImplementor.java:-2) 05-17 21:46:40.718 I/art (16907):
> at void mono.java.lang.RunnableImplementor.run() (RunnableImplementor.java:30) 05-17 21:46:40.718 I/art (16907):
> at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751) 05-17 21:46:40.718 I/art (16907): at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95) 05-17 21:46:40.718 I/art (16907): at void android.os.Looper.loop() (Looper.java:173) 05-17 21:46:40.718 I/art
> (16907): at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523) 05-17 21:46:40.718 I/art (16907): at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2) 05-17 21:46:40.718 I/art
> (16907): at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:938) 05-17 21:46:40.718 I/art (16907): at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:828) 05-17 21:46:40.718 I/art (16907): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/data/app/com.android.chrome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-1/lib/arm, /data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] 05-17 21:46:40.718 I/art (16907): at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56) 05-17 21:46:40.718 I/art (16907):
> at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380) 05-17 21:46:40.718 I/art (16907): at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312) 05-17 21:46:40.718 I/art (16907): at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:48) 05-17 21:46:40.718 I/art
> (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:635) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:571) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int) (WebView.java:554) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet) (WebView.java:541) 05-17 21:46:40.718 I/art (16907): at void android.webkit.WebView.(android.content.Context) (WebView.java:531) 05-17 21:46:40.718 I/art (16907): at void mono.java.lang.RunnableImplementor.n_run() (RunnableImplementor.java:-2) 05-17 21:46:40.718 I/art (16907):
> at void mono.java.lang.RunnableImplementor.run() (RunnableImplementor.java:30) 05-17 21:46:40.718 I/art (16907):
> at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751) 05-17 21:46:40.718 I/art (16907): at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95) 05-17 21:46:40.718 I/art (16907): at void android.os.Looper.loop() (Looper.java:173) 05-17 21:46:40.718 I/art
> (16907): at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523) 05-17 21:46:40.718 I/art (16907): at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2) 05-17 21:46:40.718 I/art
> (16907): at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:938) 05-17 21:46:40.718 I/art (16907): at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:828) 05-17 21:46:40.718 I/art (16907): 05-17 21:46:40.721 I/art (16907): Rejecting re-init on previously-failed class java.lang.Class: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse; 05-17 21:46:40.721 I/art
> (16907): at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:48) 05-17 21:46:40.721 I/art
> (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:635) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:571) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int) (WebView.java:554) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet) (WebView.java:541) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context) (WebView.java:531) 05-17 21:46:40.721 I/art (16907): at void mono.java.lang.RunnableImplementor.n_run() (RunnableImplementor.java:-2) 05-17 21:46:40.721 I/art (16907):
> at void mono.java.lang.RunnableImplementor.run() (RunnableImplementor.java:30) 05-17 21:46:40.721 I/art (16907):
> at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751) 05-17 21:46:40.721 I/art (16907): at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95) 05-17 21:46:40.721 I/art (16907): at void android.os.Looper.loop() (Looper.java:173) 05-17 21:46:40.721 I/art
> (16907): at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523) 05-17 21:46:40.721 I/art (16907): at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2) 05-17 21:46:40.721 I/art
> (16907): at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:938) 05-17 21:46:40.721 I/art (16907): at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:828) 05-17 21:46:40.721 I/art (16907): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.android.chrome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-1/lib/arm, /data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] 05-17 21:46:40.721 I/art (16907): at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56) 05-17 21:46:40.721 I/art (16907):
> at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380) 05-17 21:46:40.721 I/art (16907): at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312) 05-17 21:46:40.721 I/art (16907): at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:48) 05-17 21:46:40.721 I/art
> (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:635) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:571) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet, int) (WebView.java:554) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context, android.util.AttributeSet) (WebView.java:541) 05-17 21:46:40.721 I/art (16907): at void android.webkit.WebView.(android.content.Context) (WebView.java:531) 05-17 21:46:40.721 I/art (16907): at void mono.java.lang.RunnableImplementor.n_run() (RunnableImplementor.java:-2) 05-17 21:46:40.721 I/art (16907):
> at void mono.java.lang.RunnableImplementor.run() (RunnableImplementor.java:30) 05-17 21:46:40.721 I/art (16907):
> at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751) 05-17 21:46:40.721 I/art (16907): at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95) 05-17 21:46:40.721 I/art (16907): at void android.os.Looper.loop() (Looper.java:173) 05-17 21:46:40.721 I/art
> (16907): at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523) 05-17 21:46:40.721 I/art (16907): at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2) 05-17 21:46:40.721 I/art
> (16907): at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:938) 05-17 21:46:40.721 I/art (16907): at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:828) 05-17 21:46:40.721 I/art (16907): 05-17 21:46:40.833 D/AudioManager(16907): isHeadsetPlugged = false 05-17 21:46:40.834 W/cr_media(16907): Requires BLUETOOTH permission 05-17 21:46:40.840 E/libEGL (16907): validate_display:99 error 3008 (EGL_BAD_DISPLAY) 05-17 21:46:40.887 W/VideoCapabilities(16907): Unrecognized profile 2130706433 for video/avc 05-17 21:46:40.920 W/VideoCapabilities(16907): Unsupported mime video/x-ms-wmv 05-17 21:46:40.923 W/VideoCapabilities(16907): Unsupported mime video/x-ms-wmv 05-17 21:46:40.969 I/VideoCapabilities(16907): Unsupported profile 4 for video/mp4v-es 05-17 21:46:40.972 W/AudioCapabilities(16907): Unsupported mime audio/x-ms-wma 05-17 21:46:40.973 W/VideoCapabilities(16907): Unsupported mime video/x-ms-wmv 05-17 21:46:40.974 W/AudioCapabilities(16907): Unsupported mime audio/ac3 05-17 21:46:40.975 W/AudioCapabilities(16907): Unsupported mime audio/eac3 05-17 21:46:40.976 W/AudioCapabilities(16907): Unsupported mime audio/eac3-joc 05-17 21:46:41.055 W/cr_CrashFileManager(16907): /data/user/0/com.PinoyRide.App/cache/WebView/Crash Reports does not exist or is not a directory

### Steps to Reproduce

1.  Add webview to xaml page
2.  Navigate to website or provide htmlwebviewsource
3. Set WebView height and width

### Expected Behavior
WebView renders content
### Actual Behavior
WebView is not rendered into the page
### Basic Information

- Version with issue: Xamarin 4.8.0.756; Xamarin.Forms 2.5.0.121934
- Last known good version: N/A
- IDE: VS 2015
- Platform Target Frameworks: 
  - iOS:  9.0.1
  - Android: 8.0 Oreo
  - UWP:  16299
- Affected Devices: HTC One M9

**Comment by PureWeen** [comment] 2018-05-22 06:43
@KaizerT 

Can you attach a repro project? I tested the code you have pasted in the description and I was able to load up a webview without any issues.  From the exception it looks like maybe this is an issue related to having proguard enabled? Or possibly something is getting linked out?

**Comment by KaizerT** [comment] 2018-05-22 15:37
Hi @PureWeen 

I can try to repro in a sample project in about 8 hours, still at work. Thanks though and I'll update you. I also added information in the issue  in the Basic Information section

**Comment by PureWeen** [comment] 2018-05-22 17:43
Yea let me know. I'm still not able to reproduce.. Can you test on the latest 3.0 version of forms and see if you have an issue?

I tested against oreo and I ran the project from vs 2015 and I'm still not seeing any exceptions

I'd be curious to see what your proguard/multidex/linking settings are

**Comment by KaizerT** [comment] 2018-05-22 17:46
I have both ProGuard and multidex enabled with default settings. I can't seem to update to the latest 3.0 version of forms since I started development on 2.5.0 and when I tried to upgrade it broke the whole project, mainly the link between the xaml partial classes. I tried clearing out the bin and obj folders and rebuilding with no luck.

**Comment by PureWeen** [comment] 2018-05-22 17:54
If you have proguard enabled then you'll need to add a proguard config for the missing classes 
I talk about that here a little bit
https://github.com/xamarin/Xamarin.Forms/issues/2709

that's usually what *NoClassDefFoundError* indicates

so you'll need to indicate to proguard to ignore what looks like *android.webkit.RenderProcessGoneDetail*

Also I wouldn't enable multidex and proguard
Just ProGuard should be enough

I'd also be curious to know about the issues upgrading :-/ if you have a sample for that one though I'm pretty sure that even upgrading to 3.0 that won't fix the issues you talk about here as I'm pretty sure that it's proguard removing the class that is your issue

**Comment by KaizerT** [comment] 2018-05-22 17:57
I was encountering a different error for the firebase api before which prompted me to enable proguard and multidex, when I turned off multidex it would break again and re-enabling multidex would not fix it. I'll try the proguard fix though and update this issue, thanks!

**Comment by KaizerT** [comment] 2018-05-22 18:00
so should I add something along the lines of 
-keep class android.webkit.RenderProcessGoneDetail { *; }

**Comment by PureWeen** [comment] 2018-05-22 18:48
Oh firebase :-) that was definitely my first experience getting multidex/proguard stuff working as well

Here's the proguard file I use and I have firebase working in my apps. 

```
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class com.microsoft.windowsazure.messaging.** { *; }
-dontwarn com.microsoft.windowsazure.messaging.**
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
-keep class android.support.v7.widget.** { *; }
-dontwarn android.support.v7.widget.*
-keep class android.support.v4.widget.Space { *; }
-dontwarn android.support.v4.widget.Space
-keep class net.hockeyapp.android.** { *; }
-dontwarn net.hockeyapp.android.*
```

I'm still not able to get that error to happen though :-/ 
Maybe make sure you have the latest android sdk tools installed?
I have build tools 28 -rc2  and sdk platform 8.1 installed

**Comment by samhouts** [comment] 2018-06-14 16:24
@KaizerT Are you still experiencing this issue? Do you have a sample project you can share? Thank you!

**Comment by PureWeen** [comment] 2018-07-16 23:14
No updates in the last 30 days. If you're still having an issue please let us know and we can re-open

**Closed by PureWeen** 2018-07-16 23:14 UTC
Labels: p/Android, s/needs-repro
