### ISSUE TITLE
[Bug] ScrollView UWP bug in 4.7.0.968!

### ISSUE THREAD

**Issue by mohitatray** [xamarin/Xamarin.Forms#11106] opened 2020-06-18 12:26 UTC
### Description
I recently upgraded my NuGet package from Xamarin.Forms 4.6.0.967 to 4.7.0.968. Microsoft.UI.Xaml package also got upgraded in the process (the issue may be due to Microsoft.UI.Xaml package upgrade). I was working on a UWP and WPF app. I have some Entry, DatePicker and Picker elements inside a FlexLayout in ScrollView. Before the update, it was working fine but when I updated Xamarin.Forms, the scroll view is not working as expected.

When I scroll down and click an entry, the entry is not focused. Some entry above it is focused. It looks like when I scroll down, the actual view scrolls down but the pointer events are not passed to the view at the current position. Instead pointer events are passed to the upper views as if scroll position in ScrollView is not changed (0).

### Steps to Reproduce
1. Create a Xamarin.Forms project and add UWP platform.
2. Make sure you have Xamarin.Forms 4.7.0.968 NuGet package installed in all projects.
3. Add a ScrollView and a StackLayout (or FlexLayout) inside it.
4. Add a lot of Entry elements in the StackLayout such that you need to significantly scroll down to reach the end entry.
5. Run the UWP app and scroll down and try to click on the bottom entry.

### Expected Behavior
The Entry clicked should get focus.

### Actual Behavior
Nothing happens or sometimes the Entry somewhere above the clicked entry gets focus.

### Basic Information

- Version with issue: Xamarin.Forms 4.7.0.968
- Last known good version: Xamarin.Forms 4.6.0.967
- IDE: Visual Studio Community
- Platform Target Frameworks: Problem only in UWP. Nothing wrong in WPF.
- Nuget Packages: Xamarin.Forms, Microsoft.UI.Xaml (in UWP)

**Comment by activa** [comment] 2020-06-18 20:14
I can confirm. Every ScrollView on UWP is now broken.

**Comment by pitMobile** [comment] 2020-06-19 09:23
Confirm. We have the same problem on UWP.

**Comment by jsuarezruiz** [comment] 2020-06-23 12:06
I have created a repro sample using a ScrollView with a StackLayout inside and a good number of Entries.

[Issue11106.zip](https://github.com/xamarin/Xamarin.Forms/files/4819189/Issue11106.zip)

I'm testing but can't reproduce the wrong behavior:

![issue11106](https://user-images.githubusercontent.com/6755973/85401347-29ba9800-b55a-11ea-8efb-845eb6ae907a.gif)

Using Xamarin.Forms 4.7.0.968. @mohitatray Could you take a look to the sample?

**Comment by rmarinho** [comment] 2020-06-23 14:57
@mohitatray  @activa  @pitMobile can you try the sample above to see if we can get a reproduction , i also tried and seems to be working fine the focus.

**Comment by mohitatray** [comment] 2020-06-23 17:25
Hi @jsuarezruiz,
I ran your sample. It doesn't work fine in my PC. Same issue occurs as I mentioned in my post above (after scrolling down, the entry clicked doesn't get focus the entry somewhere above gets focus).
Steps I followed -
1. Downloaded your sample and opened solution in Visual Studio.
2. I was offered to install Android SDK (as it is not installed), I clicked "cancel".
3. I deleted Android and IOS projects.
4. My UWP project didn't load so I right-clicked it and clicked "Reload Project".
5. I got a dialog saying "The project below requires a platform SDK that is either not installed or included as part of a future update to Visual Studio." (screenshot below). I clicked "Ok" to change platform SDK target to 'Windows 10, version 1903 (10.0; Build 18362)' as you can see in the screenshot below.
<img width="403" alt="Capture" src="https://user-images.githubusercontent.com/17984449/85433957-e5071f00-b5a2-11ea-8843-cec52b2afb1f.PNG">

6. My UWP project loaded. I selected UWP project as my startup project and run the app.
7. Same issue occurs as I mentioned in my post above (after scrolling down, the entry clicked doesn't get focus the entry somewhere above gets focus).

Try running your sample targeting newer platform SDK 'Windows 10, version 1903 (10.0; Build 18362)'. That's the only difference I can see between the sample running on your PC and my PC.
Bdw which software did you use for recording screen?

**Comment by jsuarezruiz** [comment] 2020-06-23 18:03
@mohitatray Thanks for the detailed feedback. Now I can reproduce the issue.

**Comment by JKennedy24** [comment] 2020-06-24 07:45
Yep also seeing this bug on UWP

**Comment by AnnieMonk** [comment] 2020-06-24 17:24
This has been an issue for me too, I downgraded the version of Xamarin.Forms so I can work normally.

**Comment by AnnieMonk** [comment] 2020-06-24 17:28
This is my form that doesn't work properly with the 4.0.6.968 version of Xamarin.Forms

[https://github.com/AnnieMonk/getFood_API/blob/master/getFood.Mobile/getFood.Mobile/Views/InfoNarudzbaPage.xaml](url)

**Comment by rmarinho** [comment] 2020-06-25 15:21
Thanks , we identified the issue and working on a fix for it asap.

**Comment by rmarinho** [comment] 2020-06-25 15:31
#11174 is related

**Comment by EmilAlipiev** [comment] 2020-06-26 23:27
I have 2 horizontal Listview using SfListview on my app and On uwp when I click one other one is selected. even sometimes randomly selecting another button, item in the view. it is probably related to this.

**Comment by johnshardman** [comment] 2020-06-30 12:34
Forced to upgrade to 4.7 due to issue with pickers inside ScrollView. Having upgraded to 4.7, every ScrollView is now broken. This is a critical bug that needs fixing asap. Don't really want to downgrade to 4.4 or below, but it looks like I might have to. As three point releases in a row (4-5 - 4.7) all break on UWP with issues around ScrollView.

**Comment by Hopfenspirger** [comment] 2020-06-30 12:59
I have the same problem. Downgrading is solving it... 

By the way: On lower versions I still have the problem, that if I scroll down and than click or tab on an area without controls, the scrollview is scrolling all the way up again ... same happens with pickers.

**Comment by activa** [comment] 2020-06-30 13:29
@Hopfenspirger That's a bug that has been around for ages. See https://github.com/xamarin/Xamarin.Forms/issues/10420

**Comment by EmilAlipiev** [comment] 2020-06-30 14:46
@activa  oh ok this is maybe different issue but there is bigger issue with scrollviews and listviews in general with 4.7 independent from entry.

**Comment by samhouts** [comment] 2020-07-01 16:26
closed by #11207

**Closed by samhouts** 2020-07-01 16:26 UTC
Labels: 4.7.0, a/scrollview, i/regression, in-progress, m/high impact :black_large_square:, p/UWP, t/bug :bug:

**Comment by mdbill** [comment] 2020-07-02 04:21
upgrading to 4.7.0.1080 worked for me...so far.
