### ISSUE TITLE
OnOptionsItemSelected not triggered

### ISSUE THREAD

**Issue by Nickolas-** [xamarin/Xamarin.Forms#2592] opened 2018-05-03 10:47 UTC
OnOptionsItemSelected not triggered never is make OnCreate method async with some delay.

### Steps to Reproduce

1. Mark main activity method OnCreate async
2. Add some delay before or after LoadApplication method

### Expected Behavior

> OnOptionsItemSelected get triggered on back press

### Actual Behavior

> OnOptionsItemSelected not get triggered on back press

### Basic Information

> Visual Studio Community 2017 for Mac
> Version 7.4.2 (build 12)
> Installation UUID: 4de05a84-ef41-40a3-9fbb-488f64868da8
> Runtime:
> 	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
> 	GTK+ 2.24.23 (Raleigh theme)
> 
> 	Package version: 508010000
> 
> NuGet
> Version: 4.3.1.4445
> 
> .NET Core
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Version: 2.0.5
> SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
> SDK Version: 2.1.4
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks
> 
> Xamarin.Profiler
> Version: 1.6.1
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Apple Developer Tools
> Xcode 9.2 (13772)
> Build 9C40b
> 
> Xamarin.Mac
> Version: 4.2.1.28 (Visual Studio Community)
> 
> Xamarin.iOS
> Version: 11.9.1.24 (Visual Studio Community)
> Hash: f62de472
> Branch: xcode9.3
> Build date: 2018-03-29 19:30:53-0400
> 
> Xamarin.Android
> Version: 8.2.0.16 (Visual Studio Community)
> Android SDK: /Users/nickolasshpotenko/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		5.1 (API level 22)
> 		7.1 (API level 25)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 26.0.2
> SDK Build Tools Version: 26.0.3
> 
> Java SDK: /usr
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
> 
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Xamarin Inspector
> Version: 1.4.0
> Hash: b3f92f9
> Branch: master
> Build date: Fri, 19 Jan 2018 22:00:34 GMT
> Client compatibility: 1
> 
> Build Information
> Release ID: 704020012
> Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
> Build date: 2018-03-30 10:45:17-04
> Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
> Build lane: monodevelop-lion-d15-6
> 
> Operating System
> Mac OS X 10.13.3
> Darwin 17.4.0 Darwin Kernel Version 17.4.0
>     Sun Dec 17 09:19:54 PST 2017
>     root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Xamarin.Forms 2.5.0280555

**Comment by samhouts** [comment] 2018-06-12 18:39
Since this issue hasn't been updated in more than 30 days, we will close it now. Please feel free to reopen it if you are still experiencing this issue and have more information. Thank you!

**Closed by samhouts** 2018-06-12 18:39 UTC
Labels: p/Android, s/needs-info, s/needs-repro

**Comment by scriptBoris** [comment] 2019-05-20 03:05
The problem is still relevant

**Comment by hartez** [comment] 2019-05-21 17:24
@scriptBoris If you can upload a small project which reproduces the issue, we can reopen it and add it to the backlog.
