### ISSUE TITLE
OnOptionsItemSelected Never Called when use MasterDetailPage's Detail as NavigationPage

### ISSUE THREAD

**Issue by yanshouwang** [xamarin/Xamarin.Forms#3894] opened 2018-09-25 11:14 UTC
### Description

OnOptionsItemSelected Never Called when use MasterDetailPage's Detail as NavigationPage, and I can't intercept the software back button in the navigation bar.
It's very important to my team to do navigation through WebView and local Pages... 

### Steps to Reproduce

1. Create MasterDetailPage and use Detail as NavigationPage.
2. Use detail page to navigate to other pages, such as a WebView page.
3. can't intercept the software back button click event. So I can't use the back button to navigate with the WebView...This is very common in native hybrid apps.

### Expected Behavior
I want to intercept the software back button event when use MasterDetailPage.
### Actual Behavior
The OnOptionsItemSelected method do triggered when the mainpage is a NavigationPage, but when use MasterDetailPage, it's never called.
### Basic Information

- Version with issue:Latest
- Last known good version:None
- IDE:VS2017 Community
- Platform Target Frameworks: 
  - iOS:  Latest
  - Android: Latest 
  - UWP:  None 
- Android Support Library Version: Latest
- Nuget Packages:Latest
- Affected Devices:All

### Screenshots
None
### Reproduction Link
I wrote a demo [here](https://github.com/yanshouwang/App1)

**Comment by rmarinho** [comment] 2018-09-26 10:15
I think this is not a bug, you will need a CustomRenderer or something similar for a navigation update.

We could make this easy so marking as a enhancement

**Comment by yanshouwang** [comment] 2018-09-26 15:45
Yes, I finally did this through a custom renderer, but I think it’s too complex to implement this

**Comment by rmarinho** [comment] 2018-09-26 15:56
@yanshouwang can you share your implementation so we can try to make it easier ?

**Comment by yanshouwang** [comment] 2018-09-26 16:16
@rmarinho ok, I'll try to write a sample tomorrow~

**Comment by yanshouwang** [comment] 2018-09-27 14:42
@rmarinho Hi, I wrote a sample just now, and I only did this on iOS and Android,
the sample is [here](https://github.com/yanshouwang/InterceptNavigation)

**Comment by eyalkornblut** [comment] 2019-04-14 18:43
Please try and solve this issue, I've just spent too much time trying to add this seminally simple ability to my app.

**Comment by pauldiston** [comment] 2019-06-07 14:48
I am not entirely sure this is only related to the MasterDetailPage, I get the same behaviour when using standard navigation pages.
All was working fine when my MainActivity inherited from FormsApplicationActivity however I am having issues when my MainAcitivity inherits from FormsAppCompatActivity.

**Comment by robsoft** [comment] 2019-08-09 10:40
Just adding a +1 of frustration here too. Chasing round from Udara Alwis' blog post (which I couldn't get to work here) and ultimately realising that there really is no clean/straightforward way of hooking into that back button on the Android Toolbar.

And if not a clean event we can hook, then at least a canonical official Xamarin 'how to do this' blog post would be really welcome.

**Comment by DronemVhl** [comment] 2020-06-30 10:23
Still no solution? +1 frustration

**Comment by acuntex** [comment] 2021-01-03 18:33
@DronemVhl @robsoft 
https://nicksnettravels.builttoroam.com/post-2018-10-01-intercepting-the-android-software-back-button-in-xamarinforms-aspx/
On this blog post is a way to intercept the software back button with a custom navigation page renderer.

**Comment by shalinasanga** [comment] 2021-03-16 11:10
> @DronemVhl @robsoft
> https://nicksnettravels.builttoroam.com/post-2018-10-01-intercepting-the-android-software-back-button-in-xamarinforms-aspx/
> On this blog post is a way to intercept the software back button with a custom navigation page renderer.

Tried this solution, but in latest xamarin (5.0.0.2012) , Not working.
OnOptionsItemSelected is not hit.

**Comment by jfversluis** [comment] 2022-08-23 11:37
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Closed by jfversluis** 2022-08-23 11:37 UTC
Labels: t/enhancement ➕, proposal-open, p/Android, e/5 :clock5:, m/high impact :black_large_square:
