### ISSUE TITLE
ListView default caching strategy results in visual corruption

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5303] opened 2019-02-18 23:01 UTC
### Description
With the default ListView caching strategy (`RetainElement`), adding 100-odd items to a grouped ListView results in visual corruption, with items displayed out of order. Please see the attached repro and screenshot for further details.

Setting `CachingStrategy` to `RecycleElement` fixes the problem. However, it should not be necessary to set this value to avoid visual corruption.

### Steps to Reproduce

1. Set up a grouped ListView, add a hundred items or so
2. Scroll up and down quickly
3. Observe the items rapidly be displayed out of order

### Expected Behavior

Visual order is retained correctly with either caching strategy.

### Actual Behavior

Items are displayed in random order.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: Unknown
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### Screenshots

![screenshot_1550530423](https://user-images.githubusercontent.com/218865/52980133-92ee3200-338d-11e9-8c30-2f63f9fed1ab.png)

### Reproduction Link

[XamarinFormsSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2877641/XamarinFormsSample.zip)

**Comment by samhouts** [comment] 2019-02-19 17:17
Duplicate of #5184

**Closed by samhouts** 2019-02-19 17:17 UTC
Labels: t/bug :bug:
