### ISSUE TITLE
[Bug] Keyboard not showing when placeholder is being set to empty

### ISSUE THREAD

**Issue by jbtamaresgit** [xamarin/Xamarin.Forms#7951] opened 2019-10-11 14:26 UTC
### Description
When setting the placeholder into empty state, needs to double tap the entry for the keyboard to show. Seems like the work around with this is to set a delay which shouldn't be the case.

### Steps to Reproduce

1. Create any entry with focused event
2. On the focused event, set placeholder to empty

Sample Code:

` <Entry x:Name="EntryField"  Focused="EntryField_Focused"/>`
**Code Behind:**
` private async void EntryField_Focused(object sender, FocusEventArgs e)
  {   EntryField.Placeholder = ""; }`
### Expected Behavior
Soft input keyboard should show upon first tap

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.848062
- Last known good version:
- IDE: VS2019 Enterprise 16.3.3
- Platform Target Frameworks: 
  - Android: 9
- Android Support Library Version: Xamarin.Android.Support.v4 (28.0.0.3)
Xamarin.Android.Support.v7.AppCompat (28.0.0.3)

**Comment by NordAlex** [comment] 2019-10-13 21:45
probably related to #7709

**Comment by jfversluis** [comment] 2019-10-14 08:13
Duplicate of #7709

**Closed by jfversluis** 2019-10-14 08:13 UTC
Labels: s/unverified, t/bug :bug:
