### ISSUE TITLE
Why MainPage TitleView not displaying for other pages

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#5995] opened 2019-04-24 13:18 UTC
### Description
I have added `TitleView ` for `MainPage`, it is displaying only on `MainPage's ``Navigationbar`. When I navigate to other pages `TitleView `not showing.

How can I solve this issue?

For more information visit this 

https://stackoverflow.com/questions/55829996/how-to-show-navigationbar-titleview-common-for-all-pages

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment] 2019-04-26 21:37
duplicate of https://github.com/xamarin/Xamarin.Forms/issues/4292

**Closed by PureWeen** 2019-04-26 21:37 UTC
Labels: s/unverified, t/bug :bug:
