### ISSUE TITLE
Blank Space in TabbedPage Xamarin.iOS 13

### ISSUE THREAD

**Issue by pdamco** [xamarin/Xamarin.Forms#8655] opened 2019-11-25 18:03 UTC
Blank Space is showing after installing Xamarin.iOS 13. This is working fine with Xamarin.iOS 12 till now.

Attached is the image.
![Screenshot 2019-11-25 at 11 25 50 PM](https://user-images.githubusercontent.com/40819488/69565905-e310b980-0fdb-11ea-89a3-8e3fac0e6d80.png)

**Comment by jfversluis** [comment] 2019-11-25 18:32
Hi @pdamco thanks for reporting!

Is there any particular reason you are not using the issue template? Because I am missing a ton of info on what XF version you are using, what version of iOS, if you are seeing this on Android, etc. etc. would you be able to provide that?

Also, it would be super awesome if you could show this problem in a reproduction case so we can easily pinpoint the problem. Thanks!

**Comment by pdamco** [comment] 2019-11-26 03:54
XF version is 3.4 but i have tryed to upgrad to 4.3 nothing happened same space is showing.
iOS version is 13
Xcode 11
This is only on iOS not happening on Android.

**Comment by jfversluis** [comment] 2019-11-26 07:51
Thanks for the additional info!

Would you be able to provide us with a reproduction project showing this issue?
It seems there is some customization going on with your tabbar, we'd like to rule out anything that doesn't directly involve the Xamarin.Forms code to see if this is really a bug in our codebase.

Thanks!

**Comment by pdamco** [comment] 2019-11-28 17:54
[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3902722/Sample.zip)


Sample is attached for reproduction.

**Comment by pdamco** [comment] 2019-11-28 18:31
Duplicate of #8710

**Comment by jfversluis** [comment] 2019-11-28 18:49
Since the linked issue holds a bit more info I will close this one in favor of that one. Thanks for the additional info!

**Closed by jfversluis** 2019-11-28 18:49 UTC
Labels: iOS 13, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
