### ISSUE TITLE
[Bug] SwipeView Command not executed when contained in a listview.

### ISSUE THREAD

**Issue by RyanGaudion** [xamarin/Xamarin.Forms#9512] opened 2020-02-11 10:27 UTC
### Description
Swipeview command is not executed when in a ListView but works fine when outside of listview. Tested on UWP only.
### Steps to Reproduce

1. Create a listview and set it's ItemTemplate to the following:
```
<DataTemplate>
     <ViewCell>
          <SwipeView>
              <SwipeView.RightItems>
                   <SwipeItems SwipeBehaviorOnInvoked="Close" Mode="Execute">
                        <SwipeItem Text="Delete" BackgroundColor="OrangeRed"  Command="{Binding Commands[Command1]}"/>
                    </SwipeItems>
                </SwipeView.RightItems>
                <StackLayout Padding="10">
                    <Label Text="Test"/>
                </StackLayout>
           </SwipeView>
       </ViewCell>
</DataTemplate>

```
2. Set the binding context to any list. It doesn't matter what.
3. In the code behind, set the commands up like the following:

```
public Dictionary<string, ICommand> Commands { get; protected set; }
Commands.Add("Command1", new Command(async () => await Command1()));
private async Task Command1()
{
    await _navService.NavigateToAsync<UserPageViewModel>();
}
```
### Expected Behavior
Putting a breakpoint in the Command1 method should be hit when the swipeview is swipped.

### Actual Behavior
Breakpoint is not hit. The swipeview does close automatically but does not hit command. The following code does work though as it is not in a listview:

<SwipeView>
    <SwipeView.RightItems>
        <SwipeItems SwipeBehaviorOnInvoked="Close" Mode="Execute">
             <SwipeItem Text="Delete" BackgroundColor="OrangeRed"  Command="{Binding Commands[Command1]}"/>
        </SwipeItems>
    </SwipeView.RightItems>
    <StackLayout Padding="10">
         <Label Text="123" />
         <Label Text="456" />
     </StackLayout>
</SwipeView>

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: N/A
- IDE: Visual Studio 16.4.4
- Platform Target Frameworks:
  - UWP:  6.2.9
- Affected Devices: Windows 10 Touchscreen Laptop

**Comment by jsuarezruiz** [comment] 2020-02-19 17:55
@RyanGaudion Could you attach a repro sample?

I have done some tests using the example you can see at https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeListViewGallery.xaml#L30

But the command is executed. 
![issue9512](https://user-images.githubusercontent.com/6755973/74860675-53b04380-5349-11ea-8082-9b8570b5fcdc.gif)

**Comment by RyanGaudion** [comment] 2020-02-20 12:28
I don't have access to a touchscreen windows display anymore, so I can't test my solution until #9515 is resolved.

**Comment by Kapusch** [comment] 2020-04-09 21:28
Hello @RyanGaudion 

I've encountered the same bug than yours with the following configuration :
- Xamarin.Forms 4.6.0 (pre-4)
- Visual Studio For Mac (8.6 preview)
- iOS 13.4

But thanks to @jsuarezruiz , I've adapted my XAML code in order to correctly trigger Command execution (as referenced in the "SwipeListViewGallery.xaml" file) :
```
<SwipeView.LeftItems>
    <SwipeItems>
        <SwipeItem
            BackgroundColor="Red"
            Command="{Binding Source={x:Reference SwipeListView}, Path=BindingContext.DeleteCommand}"
            CommandParameter="{Binding .}"
            Text="Delete" />
    </SwipeItems>
</SwipeView.LeftItems>
```

And this works perfectly fine !

I didn't know about Binding Source & [Binding path](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/binding-path) but apparently this is what will fix your issue as it has resolved issue on my side.

**Comment by RyanGaudion** [comment] 2020-04-09 21:37
@Kapusch thank you. Will try!

**Comment by khaledalmolaa** [comment] 2020-04-11 09:56
@Kapusch it works perfect,
thank you

**Comment by jsuarezruiz** [comment] 2020-11-25 11:09
As the issue is resolved, I will close this issue. If it persists in another form or something different is found, let us know and a we can reopened it.

**Closed by jsuarezruiz** 2020-11-25 11:09 UTC
Labels: a/listview, a/swipeview, p/UWP, s/needs-repro ❔, t/bug :bug:
