### ISSUE TITLE
Quick navigation on Android results in ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by RobWos** [xamarin/Xamarin.Forms#5630] opened 2019-03-20 12:00 UTC
### Description
Currently when pushing a mainpage and then quickly navigate to the next page, then navigate back results in an exception.
### Steps to Reproduce

1.  Override the OnAppearing on the mainpage and push the second page 
2.  Call PopToRootAsync 
3.  App crashes

### Expected Behavior
The application navigates back to mainpage.
### Actual Behavior
Throws an exception, however if I add Task.Delay(500) before the push it works normal.
### Basic Information

- Version with issue: Xamarin.Forms 3.3.0.967583
- Last known good version: Xamarin.Forms 2.5.0.280555 (Not sure if any higher versions will work as expected)
- IDE: Visual Studio 2017 15.9.2
          Xamarin 4.12.3.72
- Platform Target Frameworks: 
  - iOS:  Does not affect iOS
  - Android: 8.1
  - UWP:  Did not test UWP.
- Android Support Library Version: 28.0.0.1 (This probably doesnt matters)
- Nuget Packages: Default Xamarin template
- Affected Devices: As far as I know any

### Reproduction Link

Added zip with project & stacktrace.
[XamarinNavigationBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2988006/XamarinNavigationBug.zip)

**Comment by kvpt** [comment] 2019-03-20 14:42
Duplicate of issue #4729.
I made a PR that fix the issue [here](https://github.com/xamarin/Xamarin.Forms/pull/4730) and the Xamarin Team [another ](https://github.com/xamarin/Xamarin.Forms/pull/5047).
We have to wait that one of them is merged.
For now, I use a custom patched version of the framework with this fix. 
If you are interested I can provide it.

**Comment by samhouts** [comment] 2019-03-21 00:32
Duplicate of #4729

**Closed by samhouts** 2019-03-21 00:32 UTC
Labels: t/bug :bug:
