### ISSUE TITLE
Xamarin Forms iOS - Portuguese Brazil folder

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8728] opened 2019-12-02 19:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/632798/xamarin-forms-ios-portuguese-brazil-folder.html)._

---
Hello starting from Xamarin Forms 4.0, if we add resource file for Portuguese Brazil language
  culture as &quot;Resources.pt-BR.resx&quot;, upon compilation the framework creates folder in lowercase &quot;pt-br&quot;, rather in uppercase &quot;pt-BR&quot;, hence the resources for specific culture are ignored by iOS. it is happening only in iOS. Is there any fix available?

---
#### Visual Studio Feedback System on 7/4/2019, 00:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/19/2019, 05:43 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 11/28/2019, 10:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2019-12-02 19:35
Originally https://github.com/xamarin/Xamarin.Forms/issues/6717

**Comment by dhindrik** [comment] 2019-12-05 12:29
I am interested in how this is related to Xamarin.Forms?

**Comment by PureWeen** [comment] 2019-12-06 20:08
Verified this issue by using the following sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UsingResxLocalization

- download the sample
- build
- Folder created: OS\bin\iPhoneSimulator\Debug\pt-br
- downgrade to Xamarin.Forms 3.6
- build
- folder created: OS\bin\iPhoneSimulator\Debug\pt-BR

Assigning to @StephaneDelcroix

**Comment by josipx** [comment] 2020-05-14 09:03
Hi
I have really big problems with this one, because pt-BR ios localization is still not working...

This issue was introduced between xamarin.forms.4.0.0.250467-pre7 and xamarin.forms.4.0.0.304370-pre8.

*-pre7 XF NuGet has iOS pt-BR resources in "xamarin.forms.4.0.0.250467-pre7\lib\Xamarin.iOS10\pt-BR", but *.-pre8 has this located at "xamarin.forms.4.0.0.304370-pre8\lib\Xamarin.iOS10\pt-br" (see folder name case sensitivity change).

IMHO, the problem is with NuGet packing. Can someone change official NuGet creation. I checked XF source code and in .create-stubs.bat file says that this file is not official one, so I assume you build and  pack XF NuGets with different one).

For now I have two "dirty" workarounds: 1) I "rename" this folder in my local nuget cache or 2) I execute extra "rename" MSbuild targed after these aftefacts are copied on build folder (just before build). But both solutions are ugly.

Thanks

**Comment by Sebastian1989101** [comment] 2020-05-28 16:20
@samhouts @PureWeen is there any update on this? A whole "language" not working is not very great for the users.

**Comment by josipx** [comment] 2020-05-28 20:49
@Sebastian1989101 I agree with you totally, fact that the whole "language" is not working is not good sign for XF (and I expect solution should be quite simple)... And, yes, unfortunately,  latest XF 4.6.0.800 version still has this issue.

I described one "dirty problem/solution" to the problem here: [](https://www.jenx.si/2020/05/22/xamarin-forms-brazilian-ios-localization-not-working/)

**Closed** 2020-06-21 16:14 UTC
Labels: 3.5.0, a/buildchain, e/3 :clock3:, feedback-ticket, i/regression, m/high impact :black_large_square:, p/iOS 🍎, t/bug :bug:
