### ISSUE TITLE
[Bug] OnAppearing does not run when App was in background or Screen Off

### ISSUE THREAD

**Issue by brepetti** [xamarin/Xamarin.Forms#7784] opened 2019-10-03 00:50 UTC
OnAppearing does not run when you put the app in background and resume.
The same thing happens if you turn the device screen off and then back on.

### Steps to Reproduce

1. Launch App, Dismiss Dialog
2. Turn Off Device Screen.
3. Turn On Device Screen.

### Expected Behavior
OnAppearing should run when returning to app.

### Actual Behavior
OnAppearing does not run when returning to app.

### Basic Information

- Version with issue: 4.2
- Last known good version: 4.1
- IDE: VS 2019
- Platform Target Frameworks: Android
  - Android: 8.1 

- Affected Devices: ALL
[OnAppearingFailsOnReturn.zip](https://github.com/xamarin/Xamarin.Forms/files/3684034/OnAppearingFailsOnReturn.zip)

**Comment by PureWeen** [comment] 2019-10-03 22:01
Fun fact

These events all fire correctly if you're using shell

**Comment by brepetti** [comment] 2019-10-23 17:09
Is this going to be fixed, or does this "fun fact" mean we are screwed and need to use Shell.  Moving to shell is not much of an option for us at this point.  We have many large apps working this way and are stuck on older version of Forms.

**Comment by lavilaso** [comment] 2019-12-01 19:11
@PureWeen Ping!! My application depends on this working and I see that I will not be able to exit 3.6.x until this is fixed.

**Comment by PureWeen** [comment] 2019-12-01 19:16
@lavilaso it looks like this one didn't get labeled quite right :-/ 

I've marked it as a regression and moved it into todo so it can get addressed

**Comment by lavilaso** [comment] 2020-01-29 20:00
@PureWeen PureWeen @samhouts Ping...

**Comment by samhouts** [comment] 2020-02-04 21:42
closed by #9257

**Closed by samhouts** 2020-02-04 21:42 UTC
Labels: e/2 :clock2:, i/regression, p/Android, t/bug :bug:
