### ISSUE TITLE
[Bug] iOS15 navigation shadow bar (Xamarin shell, XF 5.0.0.x) NavBarHasShadow

### ISSUE THREAD

**Issue by cchmc-ray** [xamarin/Xamarin.Forms#14941] opened 2021-12-01 14:52 UTC
### Description
It appears that on iOS 15 the navigation shadow bar cannot be disabled. 
See image : ios14 vs ios15 running same code. Thing gray line (shadow) is present. 
> NOTE : tweak the color of the navbar and background behind Xamarin image to create contrast

<img width="909" alt="ss" src="https://user-images.githubusercontent.com/47529843/144247737-e82057dc-d762-4c27-abfc-05c185545ec9.png">

<img width="973" alt="ss2" src="https://user-images.githubusercontent.com/47529843/144248546-ad184954-130d-4525-8c66-98ac45bd0db3.png">

NavBarHasShadow property is set to False (explicitly) AppShell.xaml
```xml
<Setter Property="Shell.NavBarHasShadow" Value="False"/>
```
This has been value has been set at various places (code behind etc) per reading and suggestion on other forms/post. 

### Steps to Reproduce

Visual studio Mac: 8.10.14
macOS Big Sur (intel)
Xamarin Forms : 5.x

Created new shell template project from Visual Studio
Change the color contrast to make see the shadower
- update navbar color Primary on the App.xml
- update accent color on AboutPage.xml
- add NavBarHasShadow false to AppShell.xml

### Expected Behavior
When the NavBarHasShadow is false, it should not be visible

### Actual Behavior
Does not matter what this value is set to on iOS15, it appears to always be present.

**Comment by jfversluis** [comment] 2021-12-01 18:43
I'm going to assume this is a duplicate of #14938

**Comment by cchmc-ray** [comment] 2021-12-02 16:01
@jfversluis  yes... it appears to be similar. 
I had search last week and I see that one was just create a day before I open this one. 

This one can be close/ref.

**Comment by jfversluis** [comment] 2021-12-06 19:35
Duplicate of #14938

**Closed by jfversluis** 2021-12-06 19:35 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/unverified, a/navbar, iOS 15
