### ISSUE TITLE
[Bug]  Scrolling of Content does not work, inside a Shell Container

### ISSUE THREAD

**Issue by ashokkumar96** [xamarin/Xamarin.Forms#5900] opened 2019-04-12 09:46 UTC
### Description
Hi Team,
I am facing issue in scrolling the content of WebView, While placing a Web View, as ShellContent of Shell Container.

### Steps to Reproduce

1. Run the sample attached below.
2. Sample will open and loaded with Website on WebView.
3. Now, Scroll the Content of the Website.
4. Scrolling interaction will be restricted.

### Expected Behavior
WebView Content should Scroll without any interaction issue.

### Actual Behavior
WebView Content is not Scrollable.

### Basic Information

- Version with issue:  Xamarin.Forms->  4.0.0.304370-pre8
- Last known good version:
- IDE: Visual Studio 2017 15.9.11.
- Platform Target Frameworks: 
  - iOS:  Not Applicable
  - Android: Samsung Tablet Android version 7.1
  - UWP: Not Applicable
- Android Support Library Version: Version 27.0.2.1
- Nuget Packages: 4.0.0.304370-pre8
- Affected Devices:
All Android Devices.

### Screenshots
Not Applicable

### Reproduction Link
[ShellContainer.zip](https://github.com/xamarin/Xamarin.Forms/files/3072578/ShellContainer.zip)

**Comment by CliffAgius** [comment] 2019-04-12 13:25
This bug report also causes the same issue on the SyncFusion PDF Control on Android Only so looks like inside a Shell Container the Scrolling is very intermittent.  I have found that if you try enough it will scroll a little but it's more off than on.

If I call into a normal View outside of Shell then the controls work as expected so my current work around is for detecting if Android and send the user to a non-Shell page.  Not neat but works for the moment.

**Comment by samhouts** [comment] 2019-04-12 23:28
Duplicate of #5205

**Closed by samhouts** 2019-04-12 23:28 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:
