### ISSUE TITLE
[Bug] GestureRecognizer inside ListView with ViewCell.ContextActions breaks the ListView ItemSelected Event ( Android Only )

### ISSUE THREAD

**Issue by ValonK** [xamarin/Xamarin.Forms#6386] opened 2019-06-03 12:00 UTC
### Description
GestureRecognizer inside ListView with ViewCell.ContextActions breaks the ListView ItemSelected Event

### Steps to Reproduce

Run the attached sample Project. 
Try to hit ItemSelected.

### Expected Behavior
ItemSelected should be fired

### Actual Behavior
ItemSelected doesn't fire

### Basic Information

- Version with issue: **4.0.0.425677**
- Last known good version:
- IDE: **VS 2019**
- Platform Target Frameworks: 
  - Android:  **9.0** 
- Android Support Library Version: **28.0.0.1**
- Nuget Packages:

```
<PackageReference Include="Xamarin.Forms" Version="4.0.0.425677" />
<PackageReference Include="Xamarin.Essentials" Version="1.1.0" />

<PackageReference Include="Xamarin.Forms" Version="4.0.0.425677" />
<PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.1" />
<PackageReference Include="Xamarin.Essentials" Version="1.1.0" />
```
### Reproduction Link
http://ge.tt/2bX03Qw2

**Comment by samhouts** [comment] 2019-06-03 16:21
Duplicate of #2180

**Closed by samhouts** 2019-06-03 16:21 UTC
Labels: a/gestures 🖖, a/listview, p/Android, s/unverified, t/bug :bug:
