### ISSUE TITLE
Xamarin Forms - Image Control not loading remote images in iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10800] opened 2020-05-20 16:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1022635/xamarin-forms-image-control-not-loading-remote-ima.html)._

---
<p>[regression] [worked-in:16.4]<br>
In today’s WTF has randomly been broken;</p><p>Image controls won’t load images from a URL source in iOS:</p><pre>&lt;Image x:Name=&quot;MyImage&quot; Source=“https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1MmB8?ver=6c43g”/&gt;</pre><p>This also no longer works:</p><pre>MyImage.Source = ImageSource.FromUri(new Uri(&quot;https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1MmB8?ver=6c43g&quot;));</pre><p>And this also doesn't work any more:</p><pre>MyImage.Source = &quot;https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1MmB8?ver=6c43g&quot;;</pre><p>It <strong>does </strong>work in Android.  It <strong>did </strong>work in VS 16.4.<br><br>This is a work-around:</p><pre>var client = new System.Net.Http.HttpClient();
System.IO.Stream imagestream = await client.GetStreamAsync(&quot;https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1MmB8?ver=6c43g&quot;);
MyImage.Source = ImageSource.FromStream(() =&gt; imagestream);</pre>

---
#### Visual Studio Feedback System on 5/7/2020, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by wocar** [comment] 2020-05-22 06:06
I confirm this bug.. is there another workarround thank you!

**Comment by samhouts** [comment] 2020-05-26 23:12
What version of Xamarin.Forms are you using? This looks like the bug we fixed in 4.5.0 with https://github.com/xamarin/Xamarin.Forms/pull/9682.

**Comment by wocar** [comment] 2020-05-26 23:16
fixed it by upgrading Xamarin.Forms and Xamarin.iOS thank you! Now works on iOS 13.5

**Comment by samhouts** [comment] 2020-05-26 23:49
Great to hear! We were just as flabbergasted when this bug appeared. We hadn't touched the offending code in years. Turns out, async is hard. 😂 Thanks for confirming!

**Closed by samhouts** 2020-05-26 23:49 UTC
Labels: a/image, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:

**Comment by kantagara** [comment] 2020-10-03 07:20
This is still happening to me (latest xamarin.forms, iOS 14), and  vsfeedback workaround still works, but I'd rather not do it like that :D

**Comment by ls8393** [comment] 2020-10-13 12:20
I am having the same issue too in latest forms and ios 14, just like kantagara stated workaround works but rather not use it.

**Comment by brporter** [comment] 2020-10-18 01:47
I am also reproducing this on Xamarin.Forms 14.

**Comment by Ghadaaldjain** [comment] 2020-10-30 22:44
This bug is still alive, remote images are not loading on IOS 14

**Comment by developerult** [comment] 2021-08-14 10:44
Yes, In xamarin form 4.8. bug still there. Image cannot found.

**Comment by technik5** [comment] 2021-08-29 09:39
I can conferm this bug, still exists and the only workaround seems to be 
`foto.Source = ImageSource.FromStream(() => new MemoryStream(new WebClient().DownloadData(url)));`
mentioned by wocar

**Comment by douglassimaodev** [comment] 2022-02-27 14:15
HI, Any update on this?

on android it works fine, on ios emulator works fine, on ios real phone it does not work

<Image Source="{Binding Source=ThumbnailUrl}" HeightRequest="300"/>

if I use a webview  <WebView Source="{Binding Source=ThumbnailUrl}" HeightRequest="300"/>  then it shows the image

I also added

<key>NSExceptionDomains</key>
		<dict>
			<key>mydomain.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
		
		and no lucky

**Comment by LeoJHarris** [comment] 2022-10-03 04:04
Same problem here... Is there no way to display images in a CollectionView on iOS?

**Comment by LeoJHarris** [comment] 2022-10-03 04:16
Encase others are having the same issue I am now using https://github.com/roubachof/Xamarin.Forms.Nuke which seems to work and images are appearing now. Not sure why images don't work without a 3rd party plugin though 😕

**Comment by douglassimaodev** [comment] 2022-10-03 08:55
it seems to work when you try to load .jpg .jpeg images but not png

**Comment by sharunkumar** [comment] 2023-01-17 18:48
> HI, Any update on this?
> 
> on android it works fine, on ios emulator works fine, on ios real phone it does not work I have this inside a CollectionView
> 
> `<Image Source="{Binding Source=ThumbnailUrl}" HeightRequest="300"/>`
> 
> if I use a webview `<WebView Source="{Binding Source=ThumbnailUrl}" HeightRequest="300"/> ` then it shows the image
> 
> I also added
> 
> ```
> <key>NSExceptionDomains</key>
> 		<dict>
> 			<key>mydomain.com</key>
> 			<dict>
> 				<key>NSExceptionRequiresForwardSecrecy</key>
> 				<true/>
> 				<key>NSIncludesSubdomains</key>
> 				<true/>
> 				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
> 				<true/>
> 			</dict>
> 		</dict>
> ```
> 
> ```
> 	and no lucky
> ```
> 
> I am using VS2022 and XF version 5.0.0.2337+884-sha.8f765bd87-azdo.5638139

issue is still there in <Image> but works with <WebView>. Only an issue on iOS.

**Comment by derekvantonder** [comment] 2023-08-26 02:46
Issue still exists on iOS physical devices, I used the SourceConverter hack to work around this. Only happens in DEBUG configuration on iOS device for me.
