### ISSUE TITLE
[Bug] PanGestureRecognizer - changing direction doesn't work

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/Xamarin.Forms#2408] opened 2018-04-09 15:02 UTC
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
When starting a pan then changing direction, the delta (`TotalX` & `TotalY` of `PanUpdatedEventArgs`), is only indicated by the direction of the first pan action.

So if you start a pan, then change the direction while not releasing the touch, the direc

### Steps to Reproduce

1. Create a Xamarin.Forms app and attach a `PanGestureRecognizer` to a space.
2. Touch down the space and start panning to raise the event
3. Stop the panning, but don't release the touch, instead change the direction of the pan
3. You'll notice that the sign (positive/negative) of the delta does not change, and is same as the first direction.

### Expected Behavior
When changing direction during a pan action, the sign of the delta should also change.

### Actual Behavior
Changing direction during a `Pan` gesture doesn't reflect on the sign of the delta.

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - UWP: 6.08 (targeting Win 16299)
  - Android: 8.1 (with _Android_Accelerated_x86_Nougat_ 7.1 emulator)
  - iOS: Not tested

**Comment by rmarinho** [comment] 2018-04-13 18:58
I can't reproduce this issue, if I start panning right from x , then I start panning left and pass the initial x point I started, I see  negative value.

**Comment by weitzhandler** [comment] 2018-04-14 20:02
Try panning right then **without releasing the touch**, turn your finger/mouse back to the opposite direction.
The values do not change direction.

**Comment by samhouts** [comment] 2018-04-19 18:16
Were you only able to reproduce this on Android? I'm wondering if this is actually fixed by https://github.com/xamarin/Xamarin.Forms/pull/2414. Can you provide a reproduction project to help us diagnose the issue?

**Comment by weitzhandler** [comment] 2018-04-19 23:36
I created [this](https://github.com/weitzhandler/TapBugRepro), but I was unable to make the pan work at all with the Android Emulator (it doesn't respond to click and drag events).
In a different project, the pan worked, and responded the same as in UWP - after touching down and changing direction whilst touched, the delta keeps on pointing in the same direction.

**Comment by weitzhandler** [comment] 2018-04-20 00:01
OK
I made [this](https://github.com/weitzhandler/TapBugRepro) project the repros on Android and UWP.

Honestly I don't think it's related to #2414, I think we're talking about something else.

**Comment by samhouts** [comment] 2018-04-20 21:55
I tried this project on Android, and I see the same thing that @rmarinho did. The delta is calculated based on the starting point of the gesture, not based on the starting point of when the pan changed directions. Once I pass over my initial touch point (where I started the pan gesture), the delta swaps from positive to negative and vice versa. This is expected behavior.

Did you have a different expectation, or are you not experiencing the same behavior?

**Comment by weitzhandler** [comment] 2018-04-21 17:26
Then perhaps I don't know how to use the `PanUpdatedEventArgs`' properties.
Can you please explain in short how I can determine the change? I think you might want to consider updating the documentation for this event, as it's a bit blurry what's going on in there.

**Comment by weitzhandler** [comment] 2018-04-23 18:44
Then perhaps I don't know how to use the `PanUpdatedEventArgs`' properties.

@samhouts, can you please explain in short how I can determine the change? I think you might want to consider updating the documentation for this event, as it's a bit blurry what's going on in there.

**Comment by hartez** [comment] 2018-04-30 19:03
As [the docs state](https://developer.xamarin.com/api/type/Xamarin.Forms.PanUpdatedEventArgs/), TotalX and TotalY are the change in those values _since the beginning of the gesture_; if you never lift your finger, you're still in the same pan gesture.

To accomplish what you're asking for - to be notified when the direction changes _within a single continuous pan gesture_ - you simply need to keep track of the previous reported values for TotalX and TotalY and compute the delta since the last `PanUpdated` event. 

I'm attaching a project which demonstrates this.

[PanDirection.zip](https://github.com/xamarin/Xamarin.Forms/files/1961853/PanDirection.zip)

**Closed by hartez** 2018-04-30 19:03 UTC
Labels: s/needs-info

**Comment by weitzhandler** [comment] 2018-04-30 19:14
Thank you very much and sorry for the hassle!
