### ISSUE TITLE
[Bug] Is the Xamarin.Forms Shell Leaking Memory ? 

### ISSUE THREAD

**Issue by DamienDoumer** [xamarin/Xamarin.Forms#15350] opened 2022-05-04 11:20 UTC
### Description

I have several instances of out-of-memory exceptions for one of my apps that uses the Xamarin Shell in Production, I used the Xamarin Profiler and noticed pages navigated to via Shell were not garbage collected. I then opened visual studio, and created a new project from the template "No additional modifications Made". Then ran the profiler on it, and noticed that neither the pages nor the view-models of this app garbage collected. 

I really hope I'm missing something, or I was wrong somewhere, cause this is kind of bothering me. Is there a way to overcome this, please? Memory leaks are kind of a nightmare to deal with.

### Steps to Reproduce

1. Create an app with the Xamarin Shell
2. Navigate to a page in the app, 
3. Run the Xamarin profiler, 
4. Navigate to a page in the app, (I navigated 5 times in this example, see the image below)
5. create a snapshot to force garbage collection, 
6. The page and viewmodel instances are still present in memory, in the example below, we have 5 pages still present.

### Expected Behavior

Pages and viewmodels should be destroyed when navigated from. 

### Basic Information

- Version with issue: 5.0.2012

### Environment

1. Xamarin Profiler Version 1.0.8.19
2. Xamarin Mac 8.10.22 (build 11)

### Screenshots
![Screenshot 2022-05-04 at 12 45 32](https://user-images.githubusercontent.com/16731017/166669841-6b718324-b8db-4145-9a5c-881da1797d67.png)

**Comment by C0D3On3** [comment] 2022-05-05 15:40
@DamienDoumer I'm right there with you!  I actually created a bug a day before you did with the SAME exact scenario.  I also included a diff using the NavigationPage instead of Xamarin Shell that DOES work hence why I think it's the Xamarin Shell causing the issue.  See here:

https://github.com/xamarin/Xamarin.Forms/issues/15348

**Comment by jfversluis** [comment] 2022-05-10 11:16
Duplicate of #15348

**Closed by jfversluis** 2022-05-10 11:16 UTC
Labels: t/bug :bug:, s/unverified
