### ISSUE TITLE
Crash XF Android Cannot access a disposed object. Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10958] opened 2020-06-04 18:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1060784/crash-xf-android-cannot-access-a-disposed-object-x.html)._

---
Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.
Is back on Android 10, crash reported from OnePlus6 OS 10 , Huawei p 30 PRO OS 10
XF 4.6.0.800 - Android Target build 9.0 Min build 6.0
VS 2019 Version 16.6.0

---
#### Visual Studio Feedback System on 6/3/2020, 01:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment] 2020-06-05 08:15
Could we have an example where reproduce the issue?

**Comment by Sylv1F** [comment] 2020-06-05 09:04
Duplicate of #10159

**Comment by Sylv1F** [comment] 2020-06-05 09:12
Duplicate of #10801

**Closed** 2020-06-10 22:53 UTC
Labels: a/fastrenderers, a/label, feedback-ticket, i/high, s/needs-info ❓, s/unverified, t/bug :bug:
