### ISSUE TITLE
CarouselView Position stops working when the collection updates #11211 is still not working

### ISSUE THREAD

**Issue by jeoffman** [xamarin/Xamarin.Forms#15082] opened 2022-01-21 11:11 UTC
I tried downloading CarouselTest.zip from #11211 and ran it on Android 10 (API 29) but the position does not update.

Also tried sources from Issue11211.xaml.cs ([here](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11211.xaml.cs)) and this behaves the same

**Comment by jfversluis** [comment] 2022-01-21 11:13
Could you please provide some update details and a reproduction?

**Comment by jeoffman** [comment] 2022-01-21 11:19
Download the example code from bug 11211: CarouselTest.zip, open the archive and run it. Click the "Add Item" button - the screen will either not advance or will advance for every-other-one 
![AndroidCarouselPositionUpdate](https://user-images.githubusercontent.com/7606177/150518326-5b1ec0d8-c623-4b1b-8cf0-8a9136aa0b2e.gif)

**Comment by jeoffman** [comment] 2022-01-21 11:27
I bumped the sample "CarouselTest.zip" from Xamarin 4.7 to latest (5.0.0.2291 as of today) and the behavior is different, but still not working. Also bumped API to Android 10:
![AndroidCarouselPositionUpdate](https://user-images.githubusercontent.com/7606177/150519406-095fd411-c728-4dbc-b1d4-46a8500c8b74.gif)

**Comment by jeoffman** [comment] 2022-01-21 11:30
Hmmmm... Something wrong with the Animated GIFs - there should be 2 different behaviors but for some reason adding my second GIF replaced the GIF from the XF 4.7 screenshot too?

**Comment by GalaxiaGuy** [comment] 2022-03-15 15:15
I have also come across this bug recently. In my case it is when using a `CarouselView` inside a `CollectionView`. Once the template gets reused in the `CollectionView`, the `CarouselView.Position` stops working.

Here is a repro:

https://github.com/galaxiaguy/xf-bugs/tree/bug/carouselview-collectionview

Swiping the carousel initially works, and the position updates. Scroll a bit and it stops working. I have reproduced this on __5.0.0.2012__ and __5.0.0.2337__.

**Comment by GalaxiaGuy** [comment] 2022-03-15 15:18
I've stepped through things a little. Once in the broken state

`CarouselViewRenderer.GetVisibleItemsIndex` always returns `(-1, -1, -1)`

This seems to be because inside `GetIndexFromTemplatedCell`, `ItemsViewAdapter` has no items.

**Comment by GalaxiaGuy** [comment] 2022-03-15 16:05
These appears to be the same issue:

#13837
#14265

**Comment by jfversluis** [comment] 2022-05-18 18:44
Should be fixed by #15266 closing under this assumption, let me know if that's not the case

**Closed by jfversluis** 2022-05-18 18:44 UTC
Labels: s/needs-repro ❔, s/needs-info ❓
