### ISSUE TITLE
[Bug]TapGestureRecognizer stopped working with Visual studio For Mac update 8.5.1

### ISSUE THREAD

**Issue by kgouraw** [xamarin/Xamarin.Forms#10178] opened 2020-04-02 03:34 UTC
### Description
TapGestureRecognizer Xamarin.Forms.GestureRecognizer is not detecting any tap event after updating Visual Studio for Mac from 8.5 to current 8.5.1 (build 42)
### Steps to Reproduce

1. UpdateVisual Studio for Mac from 8.5 to current 8.5.1 
2. Not any TapGestureRecognizer of a project is detecting any tap event, those were working with older versions.
3. 

### Expected Behavior
TapGestureRecognizer should work
### Actual Behavior
TapGestureRecognizer is not working
### Basic Information

- Version with issue: Visual Studio for Mac 8.5.1
- Last known good version: Visual Studio for Mac 8.5
- IDE: Visual Studio for mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Installed VS for Mac Preview version 8.6, and all my TapGestureRecognizers started working.

**Comment by mknotzer** [comment] 2020-04-02 10:14
I have the same issue, TapGestureRecognizers are not working on iOS, Android is fine.
https://dl.xamarin.com/VsMac/VisualStudioForMac-8.5.0.3162.dmg: issue is still there
https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-13.18.0.21.pkg

**Comment by FrederikKoers** [comment] 2020-04-02 11:07
Updating to Mac Preview version 8.6 (Xamarin.iOS 13.18.0.21) solved the problem for me. After using VS on Windows, it changed Xamarin.iOS to 13.16.0.11 and the TapGestureRecognizers  didnt work anymore.

**Comment by noxe** [comment] 2020-04-02 11:08
See here - https://developercommunity.visualstudio.com/content/problem/971724/tapgesturerecognizer-in-xamarin-forms-for-ios-not.html

does not work anymore after 16.5.2 update

**Comment by campersau** [comment] 2020-04-02 12:22
Looks similar to https://github.com/xamarin/Xamarin.Forms/issues/10162

**Comment by dalexsoto** [comment] 2020-04-02 15:45
Hello, yes this is the same issue as #10162 see https://github.com/xamarin/Xamarin.Forms/issues/10162#issuecomment-607585466 for a workaround.

**Comment by samhouts** [comment] 2020-04-02 15:58
Duplicate of #10162

**Closed by samhouts** 2020-04-02 15:58 UTC
Labels: s/unverified, t/bug :bug:

**Comment by waheez** [comment] 2020-04-02 21:44
Thank you @mknotzer  Installing the package from 2nd link fixed the issue.
