### ISSUE TITLE
[Bug] Cannot access a disposed object FastRenderers LabelRenderer

### ISSUE THREAD

**Issue by nacompllo** [xamarin/Xamarin.Forms#11661] opened 2020-08-05 14:15 UTC
### Description
When I add a binding to the FontSize property of a Label inside a CollectionView and make rotations with the device (in each rotation change I update the FontSize of the Labels of the CollectionView), there comes a time when the following exception appears:

System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.'

### Steps to Reproduce
Add elements to the Source of the CollectionView while making rotations with the device.

### Basic Information

- I have only tried it on Android since I do not have Apple devices.
- Xamarin.Forms 4.7.0.1239
- Android 10

### Reproduction Link
I have posted a video on YouTube showing how to reproduce the error:
https://www.youtube.com/watch?v=yDhlI4BG8D8&feature=youtu.be

GitHub repo: https://github.com/nacompllo/CannotDisposeLabelRenderer

**Comment by PureWeen** [comment] 2020-08-05 16:26
Closing this one as a duplicate of

https://github.com/xamarin/Xamarin.Forms/issues/10801

The stack trace on both of the exceptions is the same

**Closed by PureWeen** 2020-08-05 16:26 UTC
Labels: s/unverified, t/bug :bug:
