### ISSUE TITLE
[Bug] Clear ItemSource in CollectionView will crash iOS App

### ISSUE THREAD

**Issue by gaocan1992** [xamarin/Xamarin.Forms#6011] opened 2019-04-25 20:53 UTC
### Description
Clear ItemSource in CollectionView will crash iOS App
### Steps to Reproduce
1. XAML has a CollectionView named MyCollectionView

2. 
```
ObservableCollection<XXXViewModel> Models = new ObservableCollection<XXXViewModel>();
MyCollectionView.ItemSource = Models;
Models.Add(model);
... add some data ...
Models.Add(model);

Models.Clear();
```

### Expected Behavior
Models is cleared.
### Actual Behavior
```
NSInternalInconsistencyException
Reason: Invalid update: invalid number of items in section 0. The number of items contained in and existing section after the update (1) must be equal to the number of items contained in that section before the update(4), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).
```
### Basic Information
- Version with issue:
Xamarin.Forms 3.6.0.344457
- Last known good version:
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  12.1 
- Affected Devices:
iPhone XS Max (Simulator)

**Comment by gaocan1992** [comment] 2019-04-25 21:01
I believe this is a similar issue discussed in this thread https://forums.xamarin.com/discussion/19114/invalid-number-of-rows-in-section

iOS doesn't handle batch update properly.

**Comment by PureWeen** [comment] 2019-04-26 20:39
Clear issues a reset so I'm assuming this is a duplicate of

https://github.com/xamarin/Xamarin.Forms/issues/5793

**Closed by PureWeen** 2019-04-26 20:39 UTC
Labels: s/unverified, t/bug :bug:

**Comment by gaocan1992** [comment] 2019-06-03 21:12
@PureWeen  Thanks, I am looking at that issue.

**Comment by jennablackwell** [comment] 2019-09-06 20:19
I am having this issue with the latest stable Xamarin forms.

**Comment by DottorPagliaccius** [comment] 2019-10-15 15:52
same here

**Comment by LJ9999** [comment] 2019-10-19 04:22
Good god is this platform unstable crap.

**Comment by EvoPulseGaming** [comment] 2019-11-16 19:08
Help?

**Comment by JigarM** [comment] 2019-11-26 10:07
Please Check this comment and this solution work for me.
https://github.com/xamarin/Xamarin.Forms/pull/7711#issuecomment-552787208

just add 
```
foreach(var item in items)
{
     observablecollection.add(item)
     await Task.delay(10)
}
```

Thanks

**Comment by EvoPulseGaming** [comment] 2019-11-27 03:27
Doesn't work for everyone, and shouldn't be an actual solution

**Comment by Depechie** [comment] 2019-11-27 10:00
For people facing this, a temp workaround would be to use an AddRange instead of an Add on ObservableCollection.
Just copy paste the extended observablecollection from James: https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/ObservableRangeCollection.cs

**Comment by john-dalsgaard** [comment] 2019-11-27 10:10
@Depechie's suggestion works fine for me 👍
