### ISSUE TITLE
Missing auto generate event handler when editing XAML in VS 2017

### ISSUE THREAD

**Issue by Majirefy** [xamarin/Xamarin.Forms#1527] opened 2018-01-08 11:30 UTC
### Description
When editing XAML in VS 2017 for a .Net Standard Xamarin.Forms project, VS fails to auto generate event handler, such as `Clicked` or `Activated` event.

### Steps to Reproduce

1.  Open an XAML file for UI, such as `MainPage.xaml`.
2.  Add an `<Button />`.
3.  Add `Clicked` event.

### Expected Behavior
VS auto generates a event with name `Button_Clicked` and an method in `MainPage.xaml.cs` file.

### Actual Behavior
VS just treats `Clicked` as a common property of `<Button />`.

### Basic Information

- Version with issue:
- Last known good version: no
- IDE: VS 2017
- Nuget Packages: Xamarin.Forms 2.5.0.121934

### Screenshots

![gmqw21bk8rmx](https://user-images.githubusercontent.com/3023607/34668924-630ec9aa-f4aa-11e7-91b1-6b94c6bc25bc.jpg)

**Comment by Majirefy** [comment] 2018-01-10 05:43
Will be fixed by update NuGet package or we have wait for new update for VS 2017?

**Comment by hartez** [comment] 2018-01-12 16:38
@Majirefy In VS, under `Help`->`About Microsoft Visual Studio`, which version are you running?

**Comment by Majirefy** [comment] 2018-01-12 17:00
@hartez 
Version: 15.5.3


![2018-01-13](https://user-images.githubusercontent.com/3023607/34886124-0aca1c1c-f7fd-11e7-8bdd-2047f2179ea7.png)

**Comment by hartez** [comment] 2018-01-12 17:04
Seems to be an intermittent issue. I can reproduce it, but only occasionally. Most of the time it's working for me.

**Comment by Majirefy** [comment] 2018-01-12 17:07
@hartez It works for most XAML file in WPF, Xamarin shared project. But when it comes to .Net Core Xamarin Project, it fails.

Same error when I was using Version 15.5.2.

**Comment by devandel** [comment] 2018-01-20 12:59
I'm having the same issue with VS 15.5.4 & Xamarin.Forms 2.5.0.122203 with a .NET Standard project. No event handlers are being generated.

The way to reproduce this is to create a new Cross-Platform Project targeting Android & iOS, select Xamarin.Forms and .NET Standard.

Expected behaviour:

<Button Clicked="" will offer to create an event handler

Actual behaviour:

No suggestion appears. In fact even if you create an event handler manually pressing F12 on the handler name in XAML will give "Cannot navigate to definition" error.

**Comment by devandel** [comment] 2018-01-26 10:12
Still does not work with VS 15.5.5

**Comment by Teame81** [comment] 2018-02-21 20:28
Still won't work for me in on Windows in VS 2017 on a crossplatform with Android, iOS and Universal Windows.

**Comment by biapar** [comment] 2018-02-27 15:51
not work.
VS 2017 15.5.7

**Comment by MirzaAm** [comment] 2018-03-16 14:05
I am having the same issue, does anyone managed to get through this?
VS 2017 15.5.0

**Comment by ricardoglc** [comment] 2018-03-18 20:53
Same issue, VS 2017 15.6.2.

**Comment by encrypt0r** [comment] 2018-03-19 06:18
For me, it broke when I migrated to net standard from PCL

**Comment by greedylump** [comment] 2018-03-19 15:33
VS 2017 15.6, specific to Xamarin.forms Xaml files for .net standard projects...UWP/WPF xaml creates auto event handlers fine.

**Comment by JasonLoKiSmith** [comment] 2018-03-23 12:48
I am experiencing the same, running VS 2017 15.6.4 and .net standard

**Comment by avillarubia** [comment] 2018-03-29 13:34
same issue here, anyone can resolve?

**Comment by ernestochaves** [comment] 2018-04-03 15:34
Same issue here

**Comment by khijjawi** [comment] 2018-04-14 14:07
same issue vs 2017 15.6.6

**Comment by supasebie** [comment] 2018-04-24 23:06
Same issue 

Microsoft Visual Studio Community 2017 
Version 15.6.6
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA936
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA936
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40215.0
Azure Functions and Web Jobs Tools

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.6.18072.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.6.18072.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.6.18072.2
Provides templates and integration for the Django web framework.

Python - IronPython support   15.6.18072.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.6.18072.2
Profiling support for Python projects.

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Viasfora   3.9.163
Add color to your Visual Studio editor!

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.6.0.5
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by MarijkeM** [comment] 2018-04-25 06:49
A quick fix for people who want it to work right now: use Resharper, it does generate the function for you and all kinds of other fun stuff!

**Comment by Gusadan** [comment] 2018-04-29 01:04
Still now working here

**Comment by khijjawi** [comment] 2018-05-10 13:13
solved with new update  vs 15.7.1

**Comment by ernestochaves** [comment] 2018-05-10 22:54
Mine is working too now. 15.7.1

**Comment by MirzaAm** [comment] 2018-05-31 16:45
Mine working too with VS Community 15.7.2

**Comment by jassmith** [comment] 2018-06-25 21:59
Closing as fixed in 15.7.1

**Closed by jassmith** 2018-06-25 21:59 UTC
Labels: a/Xaml </>, t/bug :bug:

**Comment by dinobu** [comment] 2018-08-08 21:04
how about VS for Mac?

**Comment by u0107** [comment] 2018-10-04 10:12
Just updated to 15.8.6 and am getting the problem.

**Comment by onurATpiksel** [comment] 2019-06-17 20:09
same problem in vsMac 8.2 build732

**Comment by gabrielheming** [comment] 2020-01-06 10:06
Same problem in vsMac 8.3.11 build 1
