### ISSUE TITLE
Custom EditText value is overwritten by last entry within Carousel Page on Android

### ISSUE THREAD

**Issue by markmuniz** [xamarin/Xamarin.Forms#3670] opened 2018-08-27 15:48 UTC
### Description

I have a CarouselPage with three ContentPages. Each page has a custom text entry added to them. If I enter a value to each text entry and swipe to the last page in the CarouselPage and then swipe back to the first page, all of the text entries on the first page are overwritten with the value of the last text entry on the first page. If the last page's text entries had a value, swiping forward to the last page will yield the same result. The text entries in the middle page are unaffected. The expected result is that swiping back to the first/last page should retain the values for each text entry, rather than overwriting them with the value of the last text entry. This is only occuring on Android with my custom text entry. The Xamarin.Forms Entry works as expected.

### Steps to Reproduce

1. Enter text in the last text field on the first page within CarouselPage.
2. Swipe forward 2 pages.
3. Swipe back to the first and see all text fields being overwritten by the text in the last text field.

### Expected Behavior

Text fields should retain the value entered.

### Actual Behavior

Text fields are overwritten by the value of the last field.

### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: Not sure
- IDE: Visual Studio 15.8.1
- Platform Target Frameworks: 
  - Android: 8.1

### Screenshots

![defectscreencapture](https://user-images.githubusercontent.com/37002446/44669783-81335f80-a9e6-11e8-92f1-74c1bcf0b4fc.gif)

### Reproduction Link

[38499-carouselpagedefect.zip](https://github.com/xamarin/Xamarin.Forms/files/2324589/38499-carouselpagedefect.zip)

See [#671017](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/671017)

**Comment by rmarinho** [comment] 2018-08-29 17:10
I think the problem is in your implementation, and because the CarouselPage uses virtualization on Android. So the pages are destructed when going outside the screen and Android want's to collect some memory. If you don't store your Text in your Forms Model in this case `ExtendedEntry` you have no way to reconstruct the page with the values. 

```
 public class ExtendedEntry : View
  {

		public string Text
		{
			get;
			set;
		}
  }
```

Your CustomRenderer `ExtendedEntryRenderer` will need more work to handle this Text that is saved and PropertyChange updates. 

But this is not a bug on Xamarin.Forms so closing. 

Thanks

**Closed by rmarinho** 2018-08-29 17:10 UTC
