### ISSUE TITLE
[Bug] Android Button align text to left

### ISSUE THREAD

**Issue by Midnayt** [xamarin/Xamarin.Forms#6567] opened 2019-06-18 14:51 UTC
### Steps to Reproduce

``
<Button Grid.Column="1" 
                    Style="{StaticResource BlackButton}"
                    HorizontalOptions="FillAndExpand"
                    Text="{ext:Translate ThingDetail_Buy}"
                    Command="{Binding BuyCommand}">
                <Button.Triggers>
                    <DataTrigger TargetType="Button"
                                 Binding="{Binding ThingDetail.IsSoldOut}"
                                 Value="True">
                        <Setter Property="Text" Value="{ext:Translate ThingDetail_SoldOut}"/>
                        <Setter Property="BackgroundColor" Value="Red"/>
                    </DataTrigger>
                </Button.Triggers>
            </Button>
``
![1](https://user-images.githubusercontent.com/31686881/59677690-236d3f80-91d3-11e9-9518-02e20c52862e.jpg)
![2](https://user-images.githubusercontent.com/31686881/59677708-3253f200-91d3-11e9-82c1-d5f3816c7dd9.jpg)
Expected Behavior
Text remains centered

Actual Behavior
Text align to left side

Basic Information
Version with issue: 4.0.0.497661

if remove this line from a code it works fine

`<Setter Property="BackgroundColor" Value="Red"/>`

**Comment by jennablackwell** [comment] 2019-06-19 18:10
This is happening to me as well after upgrading to Xamarin Forms 4.

**Comment by mtanml** [comment] 2019-06-19 18:49
We are also having this issue... had to rollback to Xamarin Forms 3.6.x

**Comment by bcaceiro** [comment] 2019-06-20 13:00
Changing the Font Attributes also makes this bug.

**Comment by xXdRaGoNrIdDeRXx** [comment] 2019-06-20 14:02
duplicate issue [6561](https://github.com/xamarin/Xamarin.Forms/issues/6561)

**Comment by samhouts** [comment] 2019-06-21 00:56
Duplicate of #6282

**Closed by samhouts** 2019-06-21 00:56 UTC
Labels: s/unverified, t/bug :bug:
