### ISSUE TITLE
[UWP] Xamarin Forms List View SelectedItem is not working when bound to ObservableCollection in UWP

### ISSUE THREAD

**Issue by MrMentos** [xamarin/Xamarin.Forms#3017] opened 2018-06-12 13:03 UTC
### Steps to Reproduce

1. Use a listview
2. Bind ItemsSource to an observableCollection already containing at least 2 items
3. Bind SelectedItem to a property in the view-model
4. Update the observable collection for example by a timer event(just add some items some time later)
5. Try to select one of the items that was added later.

### Expected Behavior
SelectedItem should be updated with the selected item like in Android sample
### Actual Behavior
Selected Item is updated with null when in UWP sample

### Basic Information

- Version with issue: 3.0.0.561731
- Last known good version: 2.3.4.247
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
   - Android: 8.1
   - UWP:  17134

### Reproduction Link

https://github.com/MrMentos/ListViewTest

Android sample: working as expected
UWP/Xamarin Forms sample: with issue

UWP only sample: working as expected

**Comment by ashishm29** [comment] 2018-06-12 13:41
I am Facing same kind of issue and i have reported this issue 3 days ago(#2996). 
It was working in XF 2.4.0.275 - pre3 version.

**Comment by pinoelefante** [comment] 2018-06-13 17:58
I have the same issue.
Tested using using 3.1.0-pre2 & 3.1.0-pre4

**Comment by PureWeen** [comment] 2018-06-14 05:06
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/2996

**Closed by PureWeen** 2018-06-14 05:06 UTC
Labels: i/regression, p/UWP, t/bug :bug:

**Comment by ashishm29** [comment] 2018-06-14 12:21
@PureWeen  @samhouts  In which version will i get this issue fixed?

**Comment by MNHarun** [comment] 2018-06-19 11:16
Reverted to 2.5.1.527436 just now.
Code working again. 
_Dang 48 hours debugging._

**Comment by PureWeen** [comment] 2018-06-19 13:33
It'll be in the upcoming 3.1 release

**Comment by masodev** [comment] 2018-06-19 14:57
@PureWeen any estimates when the 3.1 will be released?
