### ISSUE TITLE
Font Rendering Issues (macOS)

### ISSUE THREAD

**Issue by jcapellman** [xamarin/Xamarin.Forms#2159] opened 2018-03-21 19:29 UTC
### Description
Using Xamarin Forms random labels appear as different font weights (see screenshot).  All of the labels are using the same style also tried inline setting font size, color to no avail.

### Expected Behavior
Labels with the same style settings show the same

### Actual Behavior
Labels randomly do not show the same even though they are styled the same.

### Basic Information
- IDE: Visual Studio for Mac 7.4 (build 1033)
- Platform Target Frameworks:
  - MacOS: Version 4.2.0.20
- Nuget Packages: Only Newtonsoft.JSON
- Affected Devices: MacMini (Late 2014) - (10.13.3)

### Screenshots
![screen shot 2018-03-21 at 2 29 00 pm](https://user-images.githubusercontent.com/11558993/37732873-4e5d1d98-2d14-11e8-9978-862effccdb52.png)

**Comment by pauldipietro** [comment] 2018-03-21 20:05
Can you upload a reproduction rather than a screenshot, and elaborate on scenarios that cause this, if any in particular? There isn't that much visual difference in the screenshot (the color difference also might create an optical effect) and I'm not entirely certain what font is being used.

**Comment by jcapellman** [comment] 2018-03-22 01:28
The scenario in which the screenshot related to was a series of Labels in a StackLayout, the first 10 rows render properly, it's just the bottom row doesn't.

On another View, one of the Label's doesn't render properly, but the same visual cue of what appears to be a different font weight occurs thus why I thought it was somewhat systemic and opened the issue.

I'm using the default font, no font family or name specified, just size and color.

I can throw together a sample app tomorrow (this is for work so I can't simply share the full code).

**Comment by rmarinho** [comment] 2018-03-22 13:12
it this inside a scrollview? listview ?

**Comment by jcapellman** [comment] 2018-03-23 00:35
Didn't have time today to work out an example, but this is only occurring on MacOS 10.13.3.  2 other developer machines running MacOS 10.12.6 (same Visual Studio for mac/Xamarin versions).

@rmarinho -
No these are not.

**Comment by jassmith** [comment] 2018-04-07 04:31
Im pretty sure this is a dupe of #2204 
If you do not believe this to be the case please feel free to reopen. I am making that one the master issue as it has a repro project.

**Closed by jassmith** 2018-04-07 04:31 UTC
Labels: p/macOS, s/needs-repro
