### ISSUE TITLE
[Bug] No intellisense for Expander and occasional red squiggles

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#10397] opened 2020-04-20 20:32 UTC
### Description

In VSMac I'm not getting any intellisense for Expander, and on some files I see red squiggles. App compiles and runs fine.

<img width="756" alt="Screenshot 2020-04-20 15 31 47" src="https://user-images.githubusercontent.com/41873/79796968-14d44500-831c-11ea-84e8-a8eadfac3386.png">

### Basic Information

- Version with issue: 4.6.0.655

**Comment by AndreiMisiukevich** [comment] 2020-04-20 23:03
Hi David,
It's weird because I am not getting any IntelliSense errors

![image](https://user-images.githubusercontent.com/10124814/79807625-2cd7b300-8374-11ea-92e1-a1a0c80c968c.png)

![image](https://user-images.githubusercontent.com/10124814/79807655-3cef9280-8374-11ea-9a9d-cf7db5594e43.png)

**Comment by jsuarezruiz** [comment] 2020-04-21 06:25
I can reproduce the same issue in VS4Mac 8.5.3.
<img width="1760" alt="Captura de pantalla 2020-04-21 a las 8 24 01" src="https://user-images.githubusercontent.com/6755973/79832403-9f16ba80-83a9-11ea-93df-4fc72ef61b7c.png">

**Comment by AndreiMisiukevich** [comment] 2020-04-26 23:25
Cannot replicate this issue on 8.5.**4**

![image](https://user-images.githubusercontent.com/10124814/80322483-3f4b6400-882e-11ea-8c38-2f2c4fb6d76f.png)

Can you try this version as well? @jsuarezruiz @davidortinau

**Comment by jsuarezruiz** [comment] 2020-05-06 15:23
Will be fixed by https://github.com/xamarin/Xamarin.Forms-api-docs/pull/169

**Closed** 2020-05-06 23:44 UTC
Labels: a/expander, blocker, external-intellisense, in-progress, t/bug :bug:
