### ISSUE TITLE
[iOS] ListView does not scroll when a control in listview has a PanGestureRecognizer

### ISSUE THREAD

**Issue by michelmoorlag** [xamarin/Xamarin.Forms#2299] opened 2018-04-05 20:57 UTC
### Description
When a listview has a control that contains a PanGestureRecognizer it will not scroll when you try to scroll and you touch the contol with the PanGestureRecognizer. When you touch outside the contol with PanGestureRecognizer it will scroll fine. It seems that the PanGestureRecognizer blocks the gesture event from bubbeling up to the listview so it won't scroll any more. This is only an issue on iOS, on Android it does work fine.

### Steps to Reproduce

1. Put two labels in a listview viewcell. 
2. Give one label a PanGestureRecognizer.
3. Bind to a list with enough items so that not all items are visible in the listview.
4. Start the iOS simulator.
5. Touch a label without PanGestureRecognizer and try to scroll. It will work fine.
6 Touch a label with PanGestureRecognizer and try to scroll. It will not scroll.

### Expected Behavior
I would expect that when I touch a control in a listview with a PanGestureRecognizer I would still be able to scroll the listview in iOS. Or at least it should work the same on both platforms. In that case we should have control if gesture event must bubble up to listview or not.

### Actual Behavior
When a listview has a control that contains a PanGestureRecognizer it will not scroll when you try to scroll and you touch the contol with the PanGestureRecognizer. 

### Basic Information

- Version with issue: all latest versions
- Last known good version: not known
- IDE: Visual Studio for windows 15.6.5

- Platform Target Frameworks: 
  - iOS:  11.9.1.24
  - Android: 8.2.0.16
- Android Support Library Version: 27.0.2
- Nuget Packages: XF 2.5.1.444934
- Affected Devices: All iOS devices

See the attached zip with a very simple example solution that demonstrates the issue.
[GestureIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1881799/GestureIssue.zip)

**Comment by jassmith** [comment] 2018-04-07 04:43
Yup that sucks that its not consistent, confirmed. Thank you for the repro (though its easily tested without one).

**Comment by michelmoorlag** [comment] 2018-04-09 06:29
Sure, no problem. 
It's kind of blocking for me so it is in my own interest to present this on a silver platter.
I hope this gets fixed hopefully soon :)

**Comment by keertanadapari** [comment] 2018-04-11 10:12
How do we get rid of this?? Do you have any solution? If yes, Can you please tell me

**Comment by keertanadapari** [comment] 2018-04-16 11:14
I have fixed by creating customview in ios native.

**Comment by keertanadapari** [comment] 2018-04-16 11:17
[CustomSwipeGestureView.txt](https://github.com/xamarin/Xamarin.Forms/files/1914999/CustomSwipeGestureView.txt)
You can see my code here.

**Comment by charlesroddie** [comment] 2018-05-11 10:17
@samhouts Is this behavior right? Shouldn't a PanGestureRecognizer on a View - whether by default or as an option - be able to prevent touch events from being received by a containing ScrollView?

E.g. a map or other interactive object that must respond to touches and moves. This should be able to disable touches on the containing ScrollView?

**Comment by samhouts** [comment] 2018-05-11 16:13
@charlesroddie We're aiming for making the behavior consistent between Android and iOS first, and then we're hoping to add API that will allow you to easily disable scrolling on ScrollViews and ListViews. This should offer greater control over the behavior than simply allowing or disallowing the events.

That said, are you depending on the PanGestureRecognizer to disallow touch events of its parent?

**Comment by charlesroddie** [comment] 2018-05-11 16:30
Thanks for the info. We do need to put touch-interactive objects within ScrollViews. Most of the native SkiaSharp.Forms touch events (https://github.com/mono/SkiaSharp/issues/321) get eaten by ScrollViews on iOS. Currently we are looking at PanGestureRecognisers but it looks like these will stop working as of this issue and the related PR.

> @samhouts We're hoping to add API that will allow you to easily disable scrolling on ScrollViews and ListViews

This would be very useful.

If we can get consistency between platforms and a logical way to control how touch events get handled by parents and children that would be great. This has been a problem in Xamarin.Forms for a long time.

cc @mattleibow, @j-sauer

**Comment by samhouts** [comment] 2018-05-11 17:32
@charlesroddie Here's our proposal for the additional API. Please feel free to comment to let us know if this will work for your use cases. Thanks! https://github.com/xamarin/Xamarin.Forms/issues/2680

**Closed** 2018-05-22 08:47 UTC
Labels: p/iOS 🍎, t/bug :bug:

**Comment by jemunk** [comment] 2018-06-20 07:41
I also experienced this isses. So based on the fixes made to the prereleases for XF 3.1, I updated to XF 3.1.0-pre4. But I still have the issue! I can't scroll the ListView when the having applied PanGestureRecognizer to the View of the ViewCell.
In my codebehind of the ViewCell:
```
var panGesture = new PanGestureRecognizer();
panGesture.PanUpdated += PanGesture_PanUpdated;
View.GestureRecognizers.Add(panGesture);
```

**Comment by MarcusSpecht** [comment] 2018-06-22 19:52
I am also having this issue, but I have the PanGestureReconizer on the parent of the Listview or the Listview itself. Neither send PanGestureUpdated once ListView was touched. Outside of Xamarin.Forms I would solve this by also listening to handled events or listening to preview events of bubbling events. It would be nice if Xamarin.Forms GestureRecognizers had a property like `bool UpdateOnHandledEvents` for things like that.

**Comment by samhouts** [comment] 2018-06-22 20:49
@MarcusSpecht Your issue is reported in #2296, if I'm not mistaken. We do have plans to improve the GestureRecognizers to prevent such a collision. Thanks!

**Comment by samhouts** [comment] 2018-06-22 20:51
@jemunk Since the change was potentially breaking, you have to opt-in to the fix via platform specific. (see #2669).

```
using Xamarin.Forms.PlatformConfiguration; 
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
…

Application.Current.On<iOS>().SetPanGestureRecognizerShouldRecognizeSimultaneously(true);
```

**Comment by ihassantariq** [comment] 2018-06-28 12:20
Thanks @samhouts. This one line saved me from a lot of implementation.

**Comment by ihassantariq** [comment] 2018-06-28 12:22
One more thing @samhouts is there a documentation to platforms tweaks like this one?

**Comment by jemunk** [comment] 2018-06-29 10:12
Thanks @samhouts. It works beautifully. Now I will focus on getting it working on android. It does has some quirks.
