### ISSUE TITLE
[Bug] RadioButtons can't be clicked on iOS. At all.

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/Xamarin.Forms#15107] opened 2022-01-31 06:30 UTC
### Description
I feel like I'm losing my mind because there's no way this bug exists, right?

When you click on _any_ RadioButton in iOS, nothing happens.   They never change click-state.

Even when I copy+paste the most basic example from [the documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton) verbatim, it does not work:

```
<StackLayout>
    <Label Text="What's your favorite animal?" />
    <RadioButton Content="Cat" />
    <RadioButton Content="Dog" />
    <RadioButton Content="Elephant" />
    <RadioButton Content="Monkey"
                 IsChecked="true" />
</StackLayout>
```

### Steps to Reproduce

1. Copy + paste above code
2. Click on a RadioButton in iOS

### Expected Behavior
Checked radio button changes

### Actual Behavior
Absolutely nothing.

### Basic Information

- Version with issue: 5.0.0.2196
- Affected Devices: iPod 7th edition

### Environment

I am running iOS ~Hot Reload~ Hot Restart (so, compiling without a Mac).  The experience so far is _extremely_ buggy, and I wouldn't be surprised if that was related to this issue.

**Comment by jfversluis** [comment] 2022-02-02 13:38
As you already pointed out, Hot Restart is probably the cause here. It might link out some things that are needed. I think I got a couple of other issues open for that as well. Sorry about that. Do you have any way of confirming this by going through a Mac machine?

**Comment by BlueRaja** [comment] 2022-02-02 15:46
> Do you have any way of confirming this by going through a Mac machine?

Unfortunately no. That's why I'm using Hot Restart to begin with.

**Comment by BlueRaja** [comment] 2022-02-12 22:39
Well after buying yet another unreasonably priced Apple product, I can confirm this issue does not happen when compiling with a mac.  So it's definitely a Hot Restart issue.

**Comment by jfversluis** [comment] 2022-02-14 12:23
Thanks for confirming @BlueRaja !

**Comment by jfversluis** [comment] 2022-02-14 12:23
To not fragment all the issues, let me close this in favor of #14956

**Closed by jfversluis** 2022-02-14 12:23 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/unverified, external-hotrestart, a/radiobutton :radio_button:
