### ISSUE TITLE
Since Froms 3.0: Mailto URL's no longer working

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#2657] opened 2018-05-10 12:23 UTC
Since the update to Xamarin.Forms 3.0, mailto URL's are no longer working through `Device.OpenUri(new Uri("mailto:test@example.com"));`.

**Comment by samhouts** [comment] 2018-05-10 17:08
duplicate of #2628

**Closed by samhouts** 2018-05-10 17:08 UTC
