### ISSUE TITLE
[Bug] Xamarin.Forms Shell Opener Issue for "RTL Language" when Tap at Hamburger

### ISSUE THREAD

**Issue by ranacodendev** [xamarin/Xamarin.Forms#6227] opened 2019-05-20 08:38 UTC
### Description
using xamarin.forms 4.0.0 -pre9 as Shell App, over all application is working fine, but right now i have one serious issue i.e.
My App is in Arabic Language , so when i Tap at Hamburger to open Shell/Menu it works differently for iPhone/iPad i.e. at iPad it open Shell/Menu Right to Left fine.
but at iPhone it open Shell/Menu Left to Right not acceptable by my Customer.

so please help me in this regards, that its behavior should be same for both Devices i.e. it should be open from Right to Left
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="1317" alt="WithMenu" src="https://user-images.githubusercontent.com/1707247/58007774-a5dee280-7af3-11e9-8630-a0627d3eb76f.png">
<img width="1373" alt="WithoutMenu" src="https://user-images.githubusercontent.com/1707247/58007775-a6777900-7af3-11e9-83b9-414f230650da.png">

**Comment by ranacodendev** [comment] 2019-05-20 09:29
dear @pauldipietro ,
     Is there any way that i can open this Shell/Menu in Standard way, i.e. Right to Left, may be using some Render, please help me in this regards ASAP.
Please share any source code sample if possible,
Thanks,

**Comment by ranacodendev** [comment] 2019-05-22 07:25
hello anybody there to help me PLEASE.

**Comment by Hedyia** [comment] 2019-05-22 10:08
To solve this issue the device should be in Arabic setting. or you could use this plugin.
https://github.com/saeedafshari/RedCorners.Forms

**Comment by mohamadayash** [comment] 2019-05-30 11:55
Hello I have the same problem 
![IMG_1808](https://user-images.githubusercontent.com/11196273/58631354-fcfe6780-82ea-11e9-9733-3a40552d5962.PNG)

**Comment by ranacodendev** [comment] 2019-06-10 07:30
so any update on this issue as explained above, 
is there any way to solve it, i.e. always open menu from RTL in both devices cases iPhone/iPad and also in Android.?

please share any code or any thing which helps me in this regards,
Thanks,
MN

**Comment by mohamadayash** [comment] 2019-09-13 12:30
Hello , any news about this issue ?

**Comment by AmerBakeer** [comment] 2019-09-28 19:21
Hello, 
Please .. any update regarding this BIG issue??  please... !!!

**Comment by balbarak** [comment] 2019-12-28 18:31
Same issue here,

Switch your iphone language to be arabic or any RTL lanugage.

The hamberger menu will be on the right position but when click the menu items or shell items will appear in worng direction

**Comment by AmerBakeer** [comment] 2019-12-28 19:06
It is strange how they keep ignoring bugs like these, we don't need new features while existing are not stable!  I think by continuous ignoring they are pushing us softly and politely to go to another platform like Flutter... I wish i am not correct here ...

**Comment by balbarak** [comment] 2019-12-30 15:06
I found the solution after 2 days of search and investigate


I think `IShellFlyoutTransition` need to be documented with samples

* First create `IShellFlyoutTransition` 
``` C#
public class SlideFlyoutTransitionRtl : IShellFlyoutTransition
    {


        public void LayoutViews(CGRect bounds, nfloat openPercent, UIView flyout, UIView shell, FlyoutBehavior behavior)
        {
            if (behavior == FlyoutBehavior.Locked)
                openPercent = 1;

            nfloat flyoutWidth = (nfloat)(Math.Min(bounds.Width, bounds.Height) * 0.8);
            nfloat openLimit = flyoutWidth;
            nfloat openPixels = openLimit * openPercent;

            if (behavior == FlyoutBehavior.Locked)
                shell.Frame = new CGRect(bounds.X + flyoutWidth, bounds.Y, bounds.Width - flyoutWidth, bounds.Height);
            else
                shell.Frame = bounds;

            var shellWidth = shell.Frame.Width;

            var positionY = shellWidth - openPixels;


            Debug.WriteLine("Y: " + positionY);
            Debug.WriteLine("Width: " + shell.Frame.Width);

            //flyout.Frame = new CGRect(-openLimit + openPixels, 0, flyoutWidth, bounds.Height);

            flyout.Frame = new CGRect(positionY, 0, flyoutWidth, bounds.Height);

            if (behavior != FlyoutBehavior.Locked)
            {
                var shellOpacity = (nfloat)(0.5 + (0.5 * (1 - openPercent)));
                shell.Layer.Opacity = (float)shellOpacity;
            }
        }
```
* Then create `AppShellRenderer` as following

```C#
public class AppShellRenderer : ShellRenderer
    {
        public AppShellRenderer()
        {

        }

        protected override IShellFlyoutRenderer CreateFlyoutRenderer()
        {
            return new ShellFlyoutRenderer()
            {
                FlyoutTransition = new SlideFlyoutTransitionRtl()
            };
        }
    }
```

Thats will solve the issue

Thanks

**Comment by AmerBakeer** [comment] 2019-12-30 17:53
@balbarak Thank you very much for sharing 😍
can you post a small empty project demonstrate this? 🙌🙌🙌 I think it is easier for you that answering many question (what, where , how .. etc) from me and the other readers  .

**Comment by balbarak** [comment] 2019-12-30 23:25
@AmerBakeer you can find the sample project here

https://github.com/balbarak/xamarin-shell-rtl

**Comment by AmerBakeer** [comment] 2019-12-31 19:19
@balbarak Wonderful ⭐⭐⭐⭐⭐
Thank you very much 👍👍

**Comment by mohamadayash** [comment] 2020-01-14 13:44
@balbarak  Thank you

**Comment by PureWeen** [comment] 2020-01-16 22:57
@balbarak Thank you for the initial work on this!!!

It was a great starting off point for this PR

https://github.com/xamarin/Xamarin.Forms/pull/9237

Once this PR gets merged please let me know about additional RTL issues
@mohamadayash @AmerBakeer @ranacodendev @Hedyia 

One question I have for any of you.

How do you expect the tabs to change when you switch to RTL ? Would you expect them to reorder the other direction? Or do you not care so much because they are just tabs? 

I couldn't find a lot of specific guidance about tabs and most things I saw just said if you want to change the tabs based on RTL then just add them in reverse order.

**Comment by AmerBakeer** [comment] 2020-01-17 10:18
Dear Shane,
thank you for your interest in this issue.

Yes, in RTL the Tabs should appear from Right to Left (to meet the read direction), i.e. the first tab should appear at the far right and the last tab at the far left. 

 @PureWeen

**Comment by mohamadayash** [comment] 2020-04-08 18:25
Dear Shane , yes the tabs should be appear from right to left , Thank you for your interest and sorry for answering late

**Comment by PureWeen** [comment] 2020-04-08 18:31
@mohamadayash thank you for the response!

It's interesting because AFAICT UITabBar doesn't automatically relayout based on if the device is RTL

It seems like you have to just do it manually (which is why I asked)

But there is a chance my test was flawed

**Closed** 2020-04-16 16:18 UTC
Labels: a/rtl, a/shell :shell:, e/4 :clock4:, in-progress, t/bug :bug:

**Comment by davidbuckleyni** [comment] 2020-06-09 11:27
For anyone interested I opened an enhancement request for a double flyover which I think people are asking for as well in here. Please vote for it.

https://github.com/xamarin/Xamarin.Forms/issues/10991

**Comment by Srikanth540-L** [comment] 2021-01-13 10:41
@samhouts  the work around mentioned by @balbarak is not working in Xamarin Forms 5  and failing with below error stack:

at Xamarin.Forms.Platform.iOS.ShellFlyoutRenderer.Xamarin.Forms.IAppearanceObserver.OnAppearanceChanged (Xamarin.Forms.ShellAppearance appearance) [0x00022] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellFlyoutRenderer.cs:25 
  at Xamarin.Forms.Shell.Xamarin.Forms.IShellController.AddAppearanceObserver (Xamarin.Forms.IAppearanceObserver observer, Xamarin.Forms.Element pivot) [0x00012] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:311 
  at Xamarin.Forms.Platform.iOS.ShellFlyoutRenderer.Xamarin.Forms.Platform.iOS.IShellFlyoutRenderer.AttachFlyout (Xamarin.Forms.Platform.iOS.IShellContext context, UIKit.UIViewController content) [0x000b5] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellFlyoutRenderer.cs:83 
  at Xamarin.Forms.Platform.iOS.ShellRenderer.get_FlyoutRenderer () [0x00014] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellRenderer.cs:76 
  at Xamarin.Forms.Platform.iOS.ShellRenderer.get_NativeView () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellRenderer.cs:86 
  at Xamarin.Forms.Platform.iOS.Platform.AddChild (Xamarin.Forms.VisualElement view) [0x00035] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:356 
  at Xamarin.Forms.Platform.iOS.Platform.WillAppear () [0x0003c] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:339 
  at Xamarin.Forms.Platform.iOS.PlatformRenderer.ViewWillAppear (System.Boolean animated) [0x00018] in D:\a\1\s\Xamarin.Forms.Platform.iOS\PlatformRenderer.cs:95 
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(intptr,intptr,intptr)
  at UIKit.UIWindow.set_RootViewController (UIKit.UIViewController value) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/src/Xamarin.iOS/UIKit/UIWindow.g.cs:399 
  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate.UpdateMainPage () [0x0002d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\FormsApplicationDelegate.cs:202 
  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate.ApplicationOnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args) [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.iOS\FormsApplicationDelegate.cs:152 
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:266 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:362 
  at Xamarin.Forms.Application.set_MainPage (Xamarin.Forms.Page value) [0x0008b] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:93 
  at AspenConnect.Services.NavigationService.GoToHome () [0x00008] in /Users/733728/Documents/GitHub/AspenConnect/AspenConnect/AspenConnect/Services/NavigationService.cs:217 
  at AspenConnect.ViewModels.LogInPageViewModel.OpenSettings (System.Boolean isFromLogin) [0x00231] in /Users/733728/Documents/GitHub/AspenConnect/AspenConnect/AspenConnect/ViewModels/LogInPageViewModel.cs:360

**Comment by samhouts** [comment] 2021-01-13 17:02
@Srikanth540-L Can you please open a new issue for that? Thank you!

**Comment by Srikanth540-L** [comment] 2021-01-14 17:09
@samhouts I have created the bug for the same please refer the below link
https://github.com/xamarin/Xamarin.Forms/issues/13390

**Comment by ahmeduday** [comment] 2021-05-26 07:14
why is this marked as closed, the problem is still valid as of XF 5 (android)
