### ISSUE TITLE
[Bug] X.F 4.0 Grid inside listview throwing null exception

### ISSUE THREAD

**Issue by rohitvipin** [xamarin/Xamarin.Forms#6300] opened 2019-05-24 10:07 UTC
### Grid.MeasuredStarredColumns (System.Double widthConstraint, System.Double heightConstraint)
D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs, line 436 throws System.NullReferenceException: Object reference not set to an instance of an object.

### Steps to Reproduce

1. Create a listview in XAML
2. Use ViewCell and place a Grid inside it with width *
3. Run and navigate to the view

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: 3.6.0.344457
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: 9.0 
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices: Android

**Comment by TonyC5** [comment] 2019-05-27 21:25
Observed  a related issue in Visual Studio 2019 for Mac / Xamarin.  Reverting to Xamarin.Forms.3.6.0.344457 fixes the problem.

- Exception: System.NullReferenceException
- Message: Object reference not set to an instance of an object.
- Source: Xamarin.Forms.Core
- Stack Trace: See attached
[stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/3224997/stacktrace.txt)

**Comment by jepl4052** [comment] 2019-05-28 07:54
Same issue here, just upgraded to 4.0.0.425677 and app just broke...
D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:436 throws System.NullReferenceException: Object reference not set to an instance of an object.
[stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/3226188/stacktrace.txt)

**Comment by jepl4052** [comment] 2019-05-28 09:07
Stumbled upon the same issue when upgrading Xamarin Forms from 3.6 to 4, setting `Forms.SetFlags("UseLegacyRenderers");` in `MainActivity.cs` solved the issue (for now) for me.

**Comment by TonyC5** [comment] 2019-05-28 12:36
@jepl4052 - Nice work.  I saw this MS doc that discusses backward compatibility of Xamarin.Forms Fast Renderers](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers).  Looks like this "bug" is actually Xamarin.Forms 4 working as intended.

**Comment by samhouts** [comment] 2019-05-28 23:23
[Issue6300.zip](https://github.com/xamarin/Xamarin.Forms/files/3230083/Issue6300.zip)

@rohitvipin  I was unable to reproduce this. Can you please alter the attached solution such that it demonstrates the issue? Thanks!

**Comment by PureWeen** [comment] 2019-05-29 00:31
duplicate of https://github.com/xamarin/Xamarin.Forms/issues/6247

**Closed by PureWeen** 2019-05-29 00:31 UTC
Labels: a/fastrenderers, a/listview, i/high, i/regression, p/Android, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
