### ISSUE TITLE
[Shell, Flyout Header,iOS] Flyout Header have incorrect layout on iOS

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5667] opened 2019-03-22 11:14 UTC
### Description
The Shell Header is too large on iOS. It also put the content on status bar. Whereas the Header displays correct on Android.

**Android**

<img width="355" alt="Screenshot 2019-03-22 at 4 35 30 PM" src="https://user-images.githubusercontent.com/9531864/54819270-63e71b00-4cc1-11e9-9d17-2d46baa13be7.png">

**iOS**

![Simulator Screen Shot - iPhone 8 Plus - 2019-03-22 at 16 35 37](https://user-images.githubusercontent.com/9531864/54819276-6cd7ec80-4cc1-11e9-9f60-e471beda390f.png)

### Basic Information

- Version with issue:Xamarin.Forms-pre7
- IDE:Visual Studio for Mac Preview

- Affected Devices: iOS

### Reproduction Link

[BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2996215/BugTest.zip)

**Comment by samhouts** [comment] 2019-05-07 22:22
Duplicate of #3875

**Closed by samhouts** 2019-05-07 22:22 UTC
Labels: a/shell :shell:, e/3 :clock3:, p/iOS 🍎, t/bug :bug:

**Comment by HobDev** [comment] 2019-05-08 03:51
@samhouts This issue is different from #3875. Issue #3875 is about the flyout menu being overlaped on header. But this issue is about the header size of iOS which is much bigger than the content in it. Whereas the header in Android is taking the space required for the content. 
The header content on iOS was placed on status bar. But now it puts the content below statusbar. So changing the title to match with the issue.

**Comment by PureWeen** [comment] 2019-05-08 04:49
@HobDev when the final release of 4.0 comes out can you test this issue against that please? If that still isn't meeting your requirements let me know

**Comment by HobDev** [comment] 2019-05-08 05:19
@PureWeen  Sure. I am curious about the release date.

**Comment by dwhiteddsoft** [comment] 2019-05-19 16:59
@PureWeen  this issue is marked as closed? Is it? I know in pre10 it is still not working correctly.

**Comment by PureWeen** [comment] 2019-05-19 20:27
@dwhiteddsoft when the final release of 4.0 comes out (soon) please test again and let us know

**Comment by HobDev** [comment] 2019-05-23 05:11
@PureWeen 
I am facing same issue in Xamarin Forms 4 stable release. If there is any content in the header the size of the header is huge in iOS.

**Comment by PureWeen** [comment] 2019-05-23 19:32
@HobDev  can you log an issue?

I'm testing this locally and the headerview sizes to whatever content I have specified. What you might be doing in your case is setting it to a headerview that has infinite height meaning that when it tries to size it it's just going to size to the maximum size it can. 

![image](https://user-images.githubusercontent.com/5375137/58280951-0e7dc780-7d5f-11e9-8878-2c54d470dca6.png)

**Comment by HobDev** [comment] 2019-05-24 01:23
@PureWeen 
Before logging a new issue can you please share the code in the Shell file for the above screenshot. I may be doing something wrong.

**Comment by PureWeen** [comment] 2019-05-24 01:36
@HobDev 

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Sandbox/ShellPage.xaml

**Comment by HobDev** [comment] 2019-05-24 04:55
@PureWeen 
 #6295 new issue logged.
