### ISSUE TITLE
[ANDROID ONLY] System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.

### ISSUE THREAD

**Issue by ngalicoco** [xamarin/Xamarin.Forms#4662] opened 2018-12-06 15:15 UTC
### Description
Related Issue: 
1. [https://github.com/xamarin/Xamarin.Forms/issues/2164]
2. [https://github.com/xamarin/Xamarin.Forms/issues/2829]

This issue is still happening when an Image is used in a ListView ItemTemplate, irrespective of the Caching Strategy.

It crashes even if I use Xamarin.Forms Image or FFCachedImage. For FFCachedIamge I tried to set the caching to none, but still crashes.

### Steps to Reproduce

1. Navigate back and forth to a page with ListView with an Image in an ItemTemplate.
2. The image is hidden/shown based on if the a specific filter is selected. When tapping a selected item, will hide the image and tapping second time will show it and pop the  page.
3. When navigating to the same page and tap on an item, crashes.
 
### Expected Behavior
Should not crash.
### Actual Behavior

Crashes.

**App Center Crash Report**

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_Visibility ()
VisualElementTracker.UpdateIsVisible ()
VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) .invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
BindingExpression.Apply (System.Boolean fromTarget)
BindingExpression+BindingExpressionPart.b__49_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.34(intptr,intptr)

### Basic Information
- Version with issue:  Xamarin.Forms 3.4.0.1008975
- Last known good version: 2.5
- IDE: 15.9.3
- Platform Target Frameworks: 
  - Android: Breaks in both 8.1 and 9.0 
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices: Android 8 and 9 devices.

**Comment by PureWeen** [comment] 2018-12-06 16:58
@ngalicoco  can you try the latest 4.0 pre1 package? or the latest nightly?
https://myget.org/feed/xamarinforms-ci/package/nuget/Xamarin.Forms

And let me know if you see the same exception?

If you do can you create a repro? Or possibly make a gif of the crash happening?

**Comment by ngalicoco** [comment] 2018-12-06 18:58
The latest prerelease version I see in visual studio package manager is 4.0.0.8055-pre1. Will this package work ?

**Comment by PureWeen** [comment] 2018-12-06 18:59
@ngalicoco yes

**Comment by ngalicoco** [comment] 2018-12-06 21:43
I am not able to update straight to 4.0 as I am getting lot of dependency problems with Carousel View and other xam plugins. I need to fix lot of things our in APP to support 4.0. Can we know what is causing this issue, and any intermediate 3.x version that can solve this.

**Comment by PureWeen** [comment] 2018-12-06 23:02
>  I need to fix lot of things in our APP to support 4.0.

you shouldn't have to can you elaborate?

**Comment by ngalicoco** [comment] 2018-12-07 11:35
> > I need to fix lot of things in our APP to support 4.0.
> 
> you shouldn't have to can you elaborate?

We are using alexrainman/CarouselView which is conflicting with Xamarin.Forms.CaourselView control. We are using this control in few pages and renderers.

So repeating my question, what is the root cause for  Android Image renderer crash. Is there a work around for this. Even if X.F 4.0 fixes this issue, we cannot consume a stable version of it till early spring 2019.

**Comment by PureWeen** [comment] 2018-12-07 13:43
> We are using alexrainman/CarouselView which is conflicting with Xamarin.Forms.CaourselView control. We are using this control in few pages and renderers.

how is it conflicting?  It's most likely just the naming and if you fully qualify the name you'll still be able to use the other CarouselView. 

> So repeating my question, what is the root cause for Android Image renderer crash. Is there a work around for this. Even if X.F 4.0 fixes this issue, we cannot consume a stable version of it till early spring 2019.

I don't know at this point. I'm curious if some fixes we applied in 4.0 apply to your situation. If they do then I'll know the root cause and if they don't then I currently don't know

**Comment by ngalicoco** [comment] 2018-12-07 16:51
OK, I was able to upgrade to Xamarin.Forms 4.0.x pre release (fix all compile time errors). I am still seeing the same crash with Image Renderer.

**Comment by PureWeen** [comment] 2018-12-07 17:40
@ngalicoco can you provide a repro at all or send me something privately by chance? 
shneuvil at microsoft.com

**Comment by accent** [comment] 2018-12-19 06:15
I'm getting same issue with Xamarin.Forms 3.3.967583. I checked with 4.0.0.8055-pre1 and it still there.

**Comment by PureWeen** [comment] 2018-12-19 07:12
@accent can you provide a repro at all or send me something privately by chance?
shneuvil at microsoft.com

**Comment by PureWeen** [comment] 2019-02-04 23:01
Closing for now. @ngalicoco if you get a chance to email me the repro then I will test and reopen

**Closed by PureWeen** 2019-02-04 23:01 UTC
Labels: p/Android, s/needs-repro ❔, t/bug :bug:
