### ISSUE TITLE
[Enhancement] Shell custom flyout page

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Xamarin.Forms#9680] opened 2020-02-22 11:10 UTC
## Summary
Shell is awesome for URI navigation and deep linking but currently flyout menu is kinda limited in the way it can look. Would it be possible to define flyout as a separate page that will just get rendered as the side menu?

At the moment you can specify custom header and footer for header but the body is menu items and flyout items. This change would make whole flyout custom and we could make it look like any other page if needed. I understand flyout usually have similar design (A list of links) but is there a technical reason we can't put any page as flyout?

## API Changes

    <Shell.FlyoutContent>
        <page:CustomFlyoutPage />
    </Shell.FlyoutContent>

**Comment by samhouts** [comment] 2020-02-25 01:39
Duplicate of #6293

**Closed by samhouts** 2020-02-25 01:39 UTC
Labels: a/shell :shell:, proposal-open, t/enhancement ➕
