### ISSUE TITLE
[Bug] [Tizen] InvalidOperationException in VisualElementRenderer.Dispose(Boolean disposing)

### ISSUE THREAD

**Issue by SHuygh** [xamarin/Xamarin.Forms#10426] opened 2020-04-23 15:27 UTC
### Description
Tizen watch application crashes in VisualElementRenderer.Dispose(Boolean disposing).
The exception originates in the Tizen.Net package and is fixed starting from Tizen.Net 5.0.0.
https://github.com/Samsung/TizenFX/blob/API5/src/ElmSharp/ElmSharp/EvasObject.cs

Are there any plans to update the dependency in the future?

**Exception:**
"InvalidOperationException Collection was modified; enumeration operation may not execute."

**Stacktrace:**
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at ElmSharp.EvasObject.DisposeEvent()
at ElmSharp.EvasObject.Unrealize()
at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.Dispose(Boolean disposing)
at Xamarin.Forms.Platform.Tizen.LayoutRenderer.Dispose(Boolean disposing)
at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.Dispose()
at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.Dispose(Boolean disposing)
at Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.<>n__0(Boolean disposing)
at Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.<>c__DisplayClass24_0.<Dispose>g__DisposeInternal|1(Boolean isDisposing)
at Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.<>c__DisplayClass24_0.<Dispose>b__0()
at Xamarin.Forms.Platform.Tizen.TizenPlatformServices.<>c__DisplayClass6_0.<BeginInvokeOnMainThread>b__0(Object o)
at Tizen.Applications.TizenSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
at Tizen.Applications.TizenSynchronizationContext.GSourceManager.Handler(IntPtr userData)
at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)\n   at Tizen.Applications.CoreApplication.Run(String[] args)
at Tizen.Applications.CoreUIApplication.Run(String[] args)

### Steps to Reproduce
I was not able to find a reproducible scenario 

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Tizen: tizen40
- Nuget Packages:
  - Autofac "Version="4.8.1"
  - Fody" Version="6.0.4"
  - Newtonsoft.Json Version="12.0.1" 
  - PropertyChanged.Fody Version="3.1.3"
  - Xamarin.Forms Version="4.3.0.947036"
- Affected Devices: Samsung Galaxy Watch

**Comment by rookiejava** [comment] 2020-04-23 23:13
As you know, we are currently referring to `tizen40` (Tizen.NET 4.0.0) for more tizen device compatibility. We plan to update the reference Tizen.NET packagage version when the higher version devices become more active. I'll share you again once the detailed schedule is established. Until then, you can also refer to the version of Tizen.NET directly through the `<PackageReference>` in your app project(*.csproj).

And since the stack trace above is seen as an issue of CirclePage, I've closed this ticket. If it is to be reproduced, please submit it to [CircularUI's home](https://github.com/Samsung/Tizen.CircularUI/issues) with the relevant code.

Thank you!

**Closed by rookiejava** 2020-04-23 23:13 UTC
Labels: p/Tizen, t/bug :bug:
