### ISSUE TITLE
TranslateTo method causes NRE in Xamarin.Forms Version(4.3.0.991211)

### ISSUE THREAD

**Issue by mugundhan-saravanan** [xamarin/Xamarin.Forms#8692] opened 2019-11-27 17:34 UTC
# Description

TranslateTo method causes NRE in Xamarin.Forms Version(4.3.0.991211).

### Steps to Reproduce

1.  Run the sample.
2.  The NRE is reproduced in the TranslateTo method.

### Expected Behavior
The Label should be displayed.

### Actual Behavior
NRE is reproduced.

### Basic Information

- Version with issue: 4.3.0.991211

- Last known good version: 4.3.0.947036
- UWP: 1903 

### Reproduction Link

[XamarinFormsIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3898112/XamarinFormsIssue.zip)
![Screenshot (2)](https://user-images.githubusercontent.com/56623793/69746386-2ac54b80-116a-11ea-8f36-50dfce605b3a.png)

**Comment by TomOnd** [comment] 2019-11-29 19:07
Same issue reason as #8682 Dispatcher is null. Can be resolved by #8696.

**Comment by HemalathaMarikuma-syncfusion** [comment] 2019-12-04 06:30
@samhouts  Any updates ?

**Comment by PureWeen** [comment] 2019-12-04 06:40
https://github.com/xamarin/Xamarin.Forms/pull/8696 is going to be merged soon

Closing this because it's a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/8682

**Closed by PureWeen** 2019-12-04 06:40 UTC
Labels: i/high, i/regression, p/UWP, t/bug :bug:

**Comment by HemalathaMarikuma-syncfusion** [comment] 2019-12-11 06:39
Is this rolled out ? We have checked this with the following pre release version of XF , it seems not fixed.

4.4.0.991220-pre3

4.4.0.991210-pre2

4.4.0.996621-pre1

4.3.0.991221

May I know in which release version will I get the fix  ?
