### ISSUE TITLE
[BUG] Xamarin Shell Navigation Memory leak

### ISSUE THREAD

**Issue by C0D3On3** [xamarin/Xamarin.Forms#15348] opened 2022-05-03 18:45 UTC
While profiling my app which uses the Xamarin Shell for navigation, I noticed unexpected live pages staying in memory even after the pages were popped off the stack.  To recreate the issue, I've created a sample project and used both the Xamarin Shell for navigation and a NavigationPage to see if there was a difference.  The NavigationPage works as expected but the Shell doesn't, keeping around live pages even after the Garbage disposal process(triggered via snapshot on the profiler).

Attached is the project zip file and the log file of my profiling session.

**Steps to reproduce with Shell (with unexpected results):**
1. Profile the app as-is, 
2. Navigate to the second page
3. Use the navbar back button to go back to the first page.  
4. Create a snapshot
5. Do this several times and take snapshots along the way.  
6. You'll see the live count for the second page steadily increase in the profiler

**Steps to reproduce with NavigationPage (with expected results)**
1. Uncomment out the NavigationPage in app.xaml.cs and use that instead of AppShell
2. Uncomment and use the ICommand to navigate instead of Shell navigation in MainPageViewModel.cs
3. Do the other profiling steps above
4. Notice, the live pages for the second page are properly disposed.

**Here's what I'm running:**
Visual Studio for Mac Enterprise (8.10.22 - build 11) - it's the same behavior on my PC
Xamarin Forms 5.0.0.2401
Latest Xamarin Profiler as of 05/02/202

[ProfilerTest.zip](https://github.com/xamarin/Xamarin.Forms/files/8612719/ProfilerTest.zip)
[Profiler.2022-05-03__12-46-36.log](https://github.com/xamarin/Xamarin.Forms/files/8612724/Profiler.2022-05-03__12-46-36.log)
2

**Comment by PureWeen** [comment] 2022-05-07 16:12
@DamienDoumer @C0D3On3 can you see what's staying rooted according to the profiler?

**Comment by DamienDoumer** [comment] 2022-05-07 16:27
@PureWeen the whole page, and its ViewModel. I also reproduced this issue and attached a screenshot of the profiler here: https://github.com/xamarin/Xamarin.Forms/issues/15350

**Comment by PureWeen** [comment] 2022-05-07 18:28
@DamienDoumer can you click through to see why that page is pinned? I don't quite remember the steps but you should be able to find the GC Root of that page to see what's causing it to stick around in memory.

**Comment by C0D3On3** [comment] 2022-05-07 18:47
Same here @PureWeen .  The page and ViewModel stick around.  Below is a video of me going through the profiling session.  It's using the sample project I attached in this issue I reported.  It shows what's happening when the pages stick around in memory, then I change the code to swap the Shell with a NavigationPage instead and you'll see it work as expected.  There's literally only a label on the second page.  Let me know if this helps.

https://youtu.be/AdS-jUbdb2A

**Comment by PureWeen** [comment] 2022-05-07 19:02
@C0D3On3 If you stop the session I think this tab comes back

<img width="329" alt="image" src="https://user-images.githubusercontent.com/5375137/167268246-a6265a88-1eef-460a-9ebc-072f11557dfb.png">

And then you can look at the allocation to see what's keeping it in memory. Ideally you'll be able to see what eventhandler or other thing is holding on to the page reference

**Comment by C0D3On3** [comment] 2022-05-07 19:21
@PureWeen "Paths to root" shows nothing but I took a screenshot of that and the StackTrace tab for the Page and ViewModel.
<img width="1059" alt="Screen Shot 2022-05-07 at 2 20 29 PM" src="https://user-images.githubusercontent.com/21149370/167268829-ef20e893-98d7-425f-85a7-7be89ac33066.png">
<img width="1062" alt="Screen Shot 2022-05-07 at 2 20 44 PM" src="https://user-images.githubusercontent.com/21149370/167268832-e7d97bb5-9034-4a5d-88a9-6c54fbf852cf.png">

<img width="1062" alt="Screen Shot 2022-05-07 at 2 20 59 PM" src="https://user-images.githubusercontent.com/21149370/167268835-7d84ec57-8c53-4ddd-a7c3-1ccbc550519e.png">
<img width="1061" alt="Screen Shot 2022-05-07 at 2 21 14 PM" src="https://user-images.githubusercontent.com/21149370/167268838-916596ab-bc17-4913-b380-2a15919b927b.png">

**Comment by C0D3On3** [comment] 2022-05-07 19:29
Here's another @PureWeen showing all the live allocation addresses.
<img width="1062" alt="Screen Shot 2022-05-07 at 2 29 41 PM" src="https://user-images.githubusercontent.com/21149370/167269057-66991fbe-b898-42d9-a86f-7b0158cb7da0.png">

**Comment by PureWeen** [comment] 2022-05-07 19:58
@C0D3On3 if you take a snap shot does path to roots show anything? If you look at allocation in the snap shot? or if you compare snap shots?

**Comment by C0D3On3** [comment] 2022-05-07 20:43
I can't take a snapshot while the profiler is stopped but I am able to compare snapshots @PureWeen .  I did several comparisons but they all showed nothing.  Here's a screenshot of snapshot0 vs snapshot2.
<img width="1061" alt="Screen Shot 2022-05-07 at 3 38 48 PM" src="https://user-images.githubusercontent.com/21149370/167271054-06415198-6339-4418-bb97-4c69074a9f0c.png">

I did click on the "Roots and Cycles" tab to see if that showed anything, here's the only Xamarin related thing that _may_ show something of interest?
<img width="1436" alt="Screen Shot 2022-05-07 at 3 41 05 PM" src="https://user-images.githubusercontent.com/21149370/167271083-b760735b-6623-4047-9b78-af8cef27b6f6.png">

**Comment by PureWeen** [comment] 2022-05-08 00:51
@C0D3On3 out of curiosity if you nest your Shell Content in a TabBar do you still see this happening?

```XAML
<TabBar>
<ShellContent Title="MainPage"
                  ContentTemplate="{DataTemplate views:MainPage}" />
</TabBar>
```

**Comment by C0D3On3** [comment] 2022-05-08 02:50
Same thing @PureWeen 
<img width="734" alt="Screen Shot 2022-05-07 at 9 49 10 PM" src="https://user-images.githubusercontent.com/21149370/167279608-a54c3d04-76d8-439a-b37c-9fb80a9eabfd.png">
<img width="1055" alt="Screen Shot 2022-05-07 at 9 49 29 PM" src="https://user-images.githubusercontent.com/21149370/167279611-ec3cf493-4ea7-4732-93a5-c62b591a5fb9.png">
.

**Comment by PureWeen** [comment] 2022-05-12 21:45
@C0D3On3 Part of the problem here is that Shell has a bit more going on so things take a couple more passes to get to a point where the GC knows that it can collect up things. For example it uses `AppThemeBindings` which use WeakEventHandlers so those all have to get cleaned up with one pass before subsequent passes will clean things up.

You can see this by adding the following code that goes a little bit overboard inside MainPage

```C#
namespace ProfilerTest.Views
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = new MainPageViewModel { Navigation = this.Navigation }; ;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
            Device.BeginInvokeOnMainThread(async () =>
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                await Task.Delay(1000);
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
            });
        }
    }
}
```

That being said I did notice an interesting thing going on with `SecondPageViewModel`. In both cases with `NavigationPage` and `Shell` the `SecondPageViewmodel` would stick around if you left this code in there

```C#
GoToThirdPage =
    new Command(async () => await Shell.Current.Navigation.PushAsync(new ThirdPage()));
```

If I change the command to remove the closure then `SecondPageViewModel` no longer sticks around
```C#
public SecondPageViewModel()
{

    GoToThirdPage =
        new Command(OnNavigate);
}

async void OnNavigate(object obj)
{
    await Shell.Current.Navigation.PushAsync(new ThirdPage());
}
```

Let me know if you see similar results

**Comment by C0D3On3** [comment] 2022-05-13 13:27
Confirmed @PureWeen .  Removing the lambda from the Command in the constructor did indeed get rid of the .<>c object that was sticking around.  I'll take that as a lesson learned and make sure we make that a best practice in our production code.

Interesting thing of note and why I ignored that object before.  This only happens on my Mac.  When I profile on my PC, that .<>c never appeared.  Nonetheless, I'll make sure we no longer do that.

As far as the other objects are concerned, what would be a reasonable time to wait to ensure the GC did indeed collect?  It does make it challenging to profile an app using the Shell.  Would adding the OnAppearing code you mentioned be something we should look into adding in our framework or do you foresee another Xamarin related solution?

Thanks for taking the time to look into this. We truly appreciate it.

**Comment by PureWeen** [comment] 2022-05-13 14:44
@C0D3On3 a few notes

> Removing the lambda from the Command in the constructor did indeed get rid of the .<>c object that was sticking around. I'll take that as a lesson learned and make sure we make that a best practice in our production code.

After asking around a bit, I don't think this is actually much of a concern.  I think this is more just a product of what the IL generates. If you go back and forth a bunch of times you'll notice the count on this never increases. But you can still use alternate structures just to keep the profiler clean. For example if you store `Shell.Current` to a local variable and use that instead then it also goes away.

> As far as the other objects are concerned, what would be a reasonable time to wait to ensure the GC did indeed collect? 

AFAIK there isn't really a way to achieve this. The GC has algorithms it uses to figure out the most opportune time to run. It's a really heavy operation so it tries to not affect the user. If all of a sudden large memory pressures occur then the GC might run to reorganize the memory. The only way I've found with the profiler to accurately get a perspective on Memory is to have some method you call in code that forces the GC to run and then take a snap shot after that

**Comment by C0D3On3** [comment] 2022-05-13 14:50
Thank you @PureWeen .

**Comment by DamienDoumer** [comment] 2022-05-13 15:03
So, to summarize, the bad practices include; 
- Using lambdas in commands 
- Calling singleton objects directly. (instead, we should use a local variable for reference)

@PureWeen  Do you think it is necessary to call the garbage collector on views like custom renderers to facilitate garbage collection ? or there is a downside to doing this? 

Thanks for the tips. I'll try those in our app, hoping it helps.

**Comment by PureWeen** [comment] 2022-05-13 15:11
> * Using lambdas in commands
> * Calling singleton objects directly. (instead, we should use a local variable for reference)

No I think that was all just a red herring. I updated my notes.

> Do you think it is necessary to call the garbage collector on views like custom renderers to facilitate garbage collection ? or there is a downside to doing this?

There's 100% never a scenario where you should call the GC yourself unless you are just trying to test memory scenarios.  The GC will free up and rearrange memory when it sees fit. If you are getting out of memory errors then that means something completely unrelated to the conversation and examples here is happening

**Comment by PureWeen** [comment] 2022-05-13 15:16
@C0D3On3 @DamienDoumer Normally what I do when I'm trying to track down a memory leak is that I'll add some global button (toolbar item?) that I can use to force a GC with some over the top code like this

```C#
            Device.BeginInvokeOnMainThread(async () =>
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                await Task.Delay(1000);
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
            });
```

And then always click that before taking a snapshot.

**Comment by PureWeen** [comment] 2022-05-13 15:24
Closing this issue for now.

If you come across another scenario that seems to be causing leaks from our side please open a new issue and we'll take a look

**Closed by PureWeen** 2022-05-13 15:24 UTC
Labels: p/Android, a/performance, a/shell :shell:
