### ISSUE TITLE
[iOS] Cannot tap ListView cell after context actions are shown

### ISSUE THREAD

**Issue by VitalyKnyazev** [xamarin/Xamarin.Forms#5064] opened 2019-01-25 21:16 UTC
### Description
In iOS ListView with ContextActions after swiping left to show the actions and swiping right to hide them the cell stops reacting to a tap. Probably caused by #4324 fix.

### Steps to Reproduce

1.  Create ListView with ContextActions
2.  Swipe left to show the actions
3.  Swipe right to hide the actions
4.  Cell cannot be tapped anymore

### Expected Behavior
It must be possible to tap the cell after checking context actions

### Actual Behavior
Tap is not possible until the view is recreated

### Basic Information

- Version with issue: 3.4.0.1009999 and newer including 3.5.0-pre3
- Last known good version: 3.4.0.1008975
- IDE: VS2017 15.9.6
- Platform Target Frameworks:
  - iOS:  12.1.3
- Nuget Packages: Xamarin.Forms 
- Affected Devices: iPhone/iPad

**Comment by samhouts** [comment] 2019-01-26 17:57
Duplicate of #4987

**Closed by samhouts** 2019-01-26 17:57 UTC
Labels: t/bug :bug:
