### ISSUE TITLE
[Spec] CollectionView Refresh Indicator

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#5142] opened 2019-02-05 21:21 UTC
# Summary
Provide the ability for users to define their own template/ContentView for a custom refresh indicator in the CollectionView.

## API
```
<CollectionView>
    <RefreshIndicatorTemplate>
        <ContentView>
            <Label Text="Refreshing..."/>
        </ContentView>
    </RefreshIndicatorTemplate>
</CollectionView>
```

```
var cv = new CollectionView();
cv.RefreshIndicatorTemplate = new ContentView {
    Content = new Label { Text = "Refreshing..." }
};
```

### Properties
| API | Description |
|-----|-------------|
| RefreshIndicatorTemplate | ContentView that appears to indicate that the CollectionView is refreshing. |

## Considerations
The goal is, of course, for the behavior to best match the naming, which is why `RefreshIndicatorTemplate` is being used to start with. Setting it within the CollectionView (such as in the above sample XAML) is consistent with typical Xamarin.Forms concepts. Feedback is welcome as this is still a relatively open enhancement concept.

**Comment by adrianknight89** [comment] 2019-03-30 04:41
Wasn't this decided to be `RefreshView` as discussed in the `CollectionView` spec?

**Comment by samhouts** [comment] 2019-07-16 02:53
Duplicate of #5882

**Closed by samhouts** 2019-07-16 02:53 UTC
Labels: a/collectionview, t/enhancement ➕
