### ISSUE TITLE
Java.Lang.NullPointerException Message=Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference

### ISSUE THREAD

**Issue by Devaraj-Sekar** [xamarin/Xamarin.Forms#9330] opened 2020-01-27 10:48 UTC
### Description

While adding button as child object to a View (Custom control) in xamarin forms throws the mentioned exception. (But works fine untill XForms version 4.2)

### Steps to Reproduce

1.  - Create a simple sample with View as parent element and run android platform
2.  - Add a button/label as child to view object (Without grid or stack as a parent)
3.  - Exception will occur

### Expected Behavior
Child should add as expected.

### Actual Behavior
Null point exception in Xamarin forms Android

### Basic Information

- Version with issue: 4.4.0.991477
- Last known good version: 4.2
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: Latest version - API level latest too.
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:

**Comment by samhouts** [comment] 2020-01-28 00:00
@Devaraj-Sekar  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Devaraj-Sekar** [comment] 2020-02-18 04:44
Hi @samhouts ,

Added re-procedure steps for the issue regards.

Regards,
Devaraj S

**Comment by Devaraj-Sekar** [comment] 2020-02-18 04:45
Hi Team,

On analyzing further found out a similar kind of issue, which has been locked as a bug.
Issue link: https://github.com/xamarin/Xamarin.Forms/issues/8801  

Regards,
Devaraj S

**Comment by PureWeen** [comment] 2020-02-18 22:30
@Devaraj-Sekar I tried your steps but I think I'm not quite following what you're describing.

Can you attach a repro please?

**Comment by PureWeen** [comment] 2020-02-18 23:59
Marking as duplicate of https://github.com/xamarin/Xamarin.Forms/issues/9330 for now

**Comment by samhouts** [comment] 2020-03-20 17:14
Duplicate of #8801

**Closed by samhouts** 2020-03-20 17:14 UTC
Labels: 4.2.0, a/customrenderer, i/high, i/regression, p/Android, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
