### ISSUE TITLE
Xamarin CollectionView fails following update to iOS 15.4: <Xamarin_Forms_Platform_iOS_GroupableItemsViewController is stuck in its update/layout loop

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15241] opened 2022-03-21 18:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-CollectionView-fails-following-u/1693750)._

---
[severity:I'm unable to use this version]
### Overview
Since updating to iOS 15.4 a previously working CollectionView now fails and the app crashes.
The crash is caused by the CollectionView being Grouped (IsGrouped="True") and having a GroupHeaderTemplate, WidthRequest below a specific value and HorizontalOptions (regardless of value) and Vertical GridItemsLayout:

```
<CollectionView ItemsSource="{Binding Animals}"
                        IsGrouped="true"
                        WidthRequest="300"
                        HorizontalOptions="Start">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" 
                                 Span="2" />
            </CollectionView.ItemsLayout>
...
            <CollectionView.GroupHeaderTemplate>
                <DataTemplate>
                    <Label Text="{Binding Name}"
                           BackgroundColor="LightGray"
                           FontSize="Large"
                           FontAttributes="Bold" />
                </DataTemplate>
            </CollectionView.GroupHeaderTemplate>
        </CollectionView>
```

### End of output after crash
(see DebugOutput for full information)
```
2022-03-16 09:45:39.710047+0100 Bikes.iOS[29204:699426] [UICollectionViewRecursion] <UICollectionView: 0x7f90967f8600; frame = (0 0; 275 200); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600002dbeb50>; layer = <CALayer: 0x6000028b
7fa0>; contentOffset: {0, 0}; contentSize: {275, 200.33333333333334}; adjustedContentInset: {0, 0, 0, 0}; layout: <Xamarin_Forms_Platform_iOS_GridViewLayout: 0x7f909d22b960>; dataSource: <Xamarin_Forms_Platform_iOS_GroupableItemsViewController_1: 0x7f9095ebd300>> is stuck in its update/layout loop. See previous logs in the "UICollectionViewRecursion" category to find callers that scheduled a recursive update
2022-03-16 09:45:39.710811+0100 Bikes.iOS[29204:699426]  Assertion failure in -[UICollectionView _setNeedsVisibleCellsUpdate:withLayoutAttributes:], UICollectionView.m:1538
2022-03-16 09:45:39.721630+0100 Bikes.iOS[29204:699426] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2022-03-16 09:45:39.721780+0100 Bikes.iOS[29204:699426] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2022-03-16 09:45:39.721870+0100 Bikes.iOS[29204:699426] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
The app has been terminated.
```
### Environment
Windows 11 PC, VS 17.1.1, Xamarin Forms 5.0.0.2337
XCode 13.3 running on MacOS 12.2.1

### Steps to reproduce
1. Download the CollectionView sample code from GitHub: [https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/CollectionViewDemos]()
2. Update to the current Xamarin.Forms (not sure if this is relevant but it allows Hot Reload)
3. Update the VerticalListEmptyGroupsPage with the changes below
4. Check you have the current version of XCode and iOS (15.4)
4. Run the sample in Debug on iPhone 13 Pro (iOS 15.4) and select the amended page from the demo list.
5. The app breaks.
6. Revert to iOS  15.2 in XCode and the problem goes away
```
        <CollectionView ItemsSource="{Binding Animals}"
                        IsGrouped="true"
                        WidthRequest="350"
                        HorizontalOptions="Start">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" 
                                 Span="2" />
            </CollectionView.ItemsLayout>
...
```

---
#### Feedback Bot on 3/17/2022, 00:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by softlion** [comment] 2022-03-21 19:00
Same issue here.

**Comment by jfversluis** [comment] 2022-03-24 08:07
Duplicate of #15230

**Closed by jfversluis** 2022-03-24 08:07 UTC
