### ISSUE TITLE
[Bug] Wrong anchor behavior when setting HeightRequest and scaling (iOS only)

### ISSUE THREAD

**Issue by DanFunder** [xamarin/Xamarin.Forms#6945] opened 2019-07-22 12:05 UTC
_Taken from this post: [https://forums.xamarin.com/discussion/comment/383414](https://forums.xamarin.com/discussion/comment/383414)_

### Description
If the anchor of an element is set to 0 and then the HeightRequest (or WidthRequest) is changed before or after scaling, the position is off. 
This is even true if the anchors and the translations are set again after the HeightRequest/WidthRequest.

Only happens on iOS. On android we get the expected behaviour.

### Example
Take a look at the below screen shot. The boxes are identical except that red box needs the height to be set to 160.

![alt text](https://us.v-cdn.net/5019960/uploads/editor/40/h1fcrmvpcw4s.png "")

This is the xaml:
```
    <AbsoluteLayout
        Margin="20">
        <Frame
            HeightRequest="160"
            WidthRequest="160"
            BorderColor="Black"
            CornerRadius="0"
            TranslationX="99"
            Padding="1" />

        <BoxView
            x:Name="rightBox"
            AnchorX="0"
            AnchorY="0"
            HeightRequest="160"
            WidthRequest="160"
            TranslationX="100"
            TranslationY="1"
            Color="Green" />



        <Frame
            HeightRequest="160"
            WidthRequest="160"
            BorderColor="Black"
            CornerRadius="0"
            TranslationY="200"
            TranslationX="100"
            Padding="1" />

        <BoxView
            x:Name="wrongBox"
            AnchorX="0"
            AnchorY="0"
            HeightRequest="150"
            WidthRequest="160"
            Color="Red"
            TranslationY="201"
            TranslationX="101" />

        <Button Text="Invoke"
                Clicked="HandleButton"
                TranslationY="400" />

    </AbsoluteLayout>
```
When tapping the "invoke" button we want to scale both elements to 0.5.
It will trigger this code:

```
void HandleButton (Object sender, EventArgs e)
{
    rightBox.Scale = 0.5;
    wrongBox.HeightRequest = 160;
    wrongBox.Scale = 0.5;
}
```

This is the result:
![alt text](https://us.v-cdn.net/5019960/uploads/editor/p7/w7aciff6ciop.png "")

I would expect the red button to be inside the frame like the green box.

It looks like the anchoring is ignored. Even if I set the anchor to zero (again) and set the translation again I get the same result.

This only happens on iOS. On Android I get the expected result.

### Steps to Reproduce

1. Create a new forms project like shown above or clone from: [https://gitlab.com/danfunder/anchorbugtest/tree/master](https://gitlab.com/danfunder/anchorbugtest/tree/master) 
2. Run it in the ios simulator
3. Click the "Invoke" button.

### Expected Behavior
The Red box should be inside the frame just like the green box

### Actual Behavior
The red box is positioned with the middle of the box at the position of the box.

### Basic Information

- Xamarin.Forms: Version 4.1.0.581479 (and older)
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:

**Comment by andreinitescu** [comment] 2019-07-23 05:35
Duplicate of #5610

**Closed** 2019-07-26 10:51 UTC
Labels: p/iOS 🍎, t/bug :bug:
