### ISSUE TITLE
[WPF] Entry Placeholder Text not showing

### ISSUE THREAD

**Issue by tessarolli** [xamarin/Xamarin.Forms#2480] opened 2018-04-16 19:38 UTC
### Description
Entry Placeholder Text not showing in platform.wpf

### Steps to Reproduce

1. Add a entry in a view
2. Set Placeholder text
3. Run

### Expected Behavior
Show Place Holder Text
### Actual Behavior
Empty text box with no information

### Screenshots
UWP
![uwp](https://user-images.githubusercontent.com/11618432/38831005-76920c76-4194-11e8-9d3a-eee93685bfaa.PNG)

WPF
![wpf](https://user-images.githubusercontent.com/11618432/38831007-7a0f7244-4194-11e8-9077-98ba05f89506.PNG)

**Comment by mohachouch** [comment] 2018-04-16 21:38
Bug fixed : see this PR => https://github.com/xamarin/Xamarin.Forms/pull/2211

**Comment by samhouts** [comment] 2018-04-16 22:30
duplicate of #2189

**Closed by samhouts** 2018-04-16 22:30 UTC
Labels: p/WPF
