### ISSUE TITLE
[Bug][Android]Swipe Gestures do not work with Shell 

### ISSUE THREAD

**Issue by jamesmcmenamin** [xamarin/Xamarin.Forms#6310] opened 2019-05-24 23:28 UTC
### Description
SwipeGestureRecognizer does not work with shell.
### Steps to Reproduce

1. Load app.
2. Swipe on Green box
3. Get no popup (If you tap you will get a popup still.)
4. Reset App.cs to MainPage = new SwipedaBox();
5. Load app.
6. Swipe on Green box
7. Get Pop up for direction swiped

### Expected Behavior
When MainPage = AppShell(); you should be able to use Swipe gestures still
Check: Working branch of project below
### Actual Behavior
No SWIPEGestures working

- Version with issue:
- Last known good version: 3.2
- IDE: VS 2019 and Rider
- Platform Target Frameworks: 
 
  - Android: 6.0, 8.0, 8.1, 9.0 
 

- Nuget Packages: Default Xamarin.Forms 4.0 Stable build

### Reproduction Link

Both Non working and the work around are in this Repo
https://github.com/jamesmcmenamin/ShellSwipe.git

**Comment by PureWeen** [comment] 2019-05-24 23:37
Most likely a duplicate of
https://github.com/xamarin/Xamarin.Forms/issues/6060

**Comment by jamesmcmenamin** [comment] 2019-05-24 23:44
Could be same base issue.

I haven't messed about with PanGestures.

Only noticed this for SwipeGesture. And the Up/Down / Left/Right of the movement doesn't matter. Even if you keep the swipe within .2 it doesn't trigger.
Tapped works perfect.

**Comment by PureWeen** [comment] 2019-05-24 23:47
I'm guessing android has issues with these gestures because by default it's nested in a ScrollView

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs#L115

Tap won't be affected by this but scrollview is going to gobble that right up

**Comment by jamesmcmenamin** [comment] 2019-05-24 23:52
Now that you mention that I am putting my 25 cents on that is the cause.

**Comment by PureWeen** [comment] 2019-05-25 00:10
https://github.com/xamarin/Xamarin.Forms/issues/5205

**Comment by jamesmcmenamin** [comment] 2019-05-25 00:18
Great find!!!!! I am going to test this out on the Shell Git and report back if when I get this going.

**Comment by jamesmcmenamin** [comment] 2019-05-25 04:27
Ok here is the skinny. You my friend are 100% correct it is because scrollview is swiping the swiper.

But here is the WORKING work around. Obviously this needs to have OnPlatform done for split views (since swiping is at least mostly working with iOS i haven't touched the renders there.)

Secondly its super super dirty atm I will do some cleaning on it tomorrow after I do some testing with how the Burger handles the reverse thief'n of its drawer pull out. (Have some idea's on how to handle it though)

Here is link again: 
https://github.com/jamesmcmenamin/ShellSwipe.git
Working is in WORKING branch obvi

**Comment by samhouts** [comment] 2019-07-17 22:44
#6310

**Comment by KoenMat** [comment] 2019-07-30 08:47
I hope this issue will be resolved soon. The use of Shell is very limited without working SwipeGestureRecognizer.

**Closed** 2019-08-06 08:08 UTC
Labels: a/gestures 🖖, a/shell :shell:, e/4 :clock4:, p/Android, t/bug :bug:
