### ISSUE TITLE
[Bug] Images are not loaded: Update Xamarin.Forms 4.2

### ISSUE THREAD

**Issue by eincioch** [xamarin/Xamarin.Forms#7264] opened 2019-08-23 19:42 UTC
## Description
The images are not loaded, in this latest version of Xamarin.Forms 4.2.

<Image
                    Source="https://www.ucv.edu.pe/assets/imgs/logo.png"
                    Aspect="AspectFit"/>

**Comment by samhouts** [comment] 2019-08-24 00:12
@eincioch  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by eincioch** [comment] 2019-08-25 16:27
I am attaching the requested Miss Samantha Houts

[AppBugLoadImage.zip](https://github.com/xamarin/Xamarin.Forms/files/3538353/AppBugLoadImage.zip)

**Comment by samhouts** [comment] 2019-09-06 00:44
Duplicate of #7248

**Closed by samhouts** 2019-09-06 00:44 UTC
Labels: i/regression, s/unverified, t/bug :bug:
