### ISSUE TITLE
`x:DataType` attribute breaks xaml binding updates

### ISSUE THREAD

**Issue by alexeystrakh** [xamarin/Xamarin.Forms#3360] opened 2018-07-20 21:01 UTC
### Description

Once the `x:DataType` attribute is specified on a `ContentPage`, any binding defined on a page stops updating. It reads only initial value and then any subsequent update do nothing (iOS) or freezes the app after a few updates (Android)

### Steps to Reproduce

1. Define `x:DataType` attribute
2. Set `BindingContext` to a view model with implemented `INotifyPropertyChanged` with `TestProp` property
3. Add a `Label` which is bound to the `TestProp` property with `Text="{Binding TestProd}"` syntax
4. Add a `Button` and on click update the `ViewModel.TestProp` property a new value

### Expected Behavior

The `Label` reflects the new value set at the step N5

### Actual Behavior

iOS: The initial value is displayed and UI doesn't react on any number of attempt to set a new value
Android: The initial value changed to the new value but after several more clicks it starts to react slower and in 5-6 clicks freezes the UI completely

### Investigation

My research showed that:
- this issue present on both iOS and Android platforms. But the actual behavior varies (described in actual result)
- I was able to reproduce the issue on a sample project (attached below)
- I was able to confirm that without the `x:DataType` attribute everything works as expected on both platforms

### Basic Information

- Version with issue: Last stable: 3.1.0.637273 and Last pre-release: 3.2.0.637422-pre1 both have this issue
- Last known good version: unable to discover
- IDE: Visual Studio
- Platform Target Frameworks:
  - iOS:  8.0
  - Android: 8.1
  - UWP:  N/A
- Android Support Library Version: 27.0.2.1
- Nuget Packages: N/A
- Affected Devices: All tested

### Reproduction Link

[IssueWithBindingAndDataType.zip](https://github.com/xamarin/Xamarin.Forms/files/2215411/IssueWithBindingAndDataType.zip)

**Comment by PureWeen** [comment] 2018-07-20 21:43
I tested this back to 2.5.1 and it had the same issues

**Comment by StephaneDelcroix** [comment] 2018-07-23 13:44
I believe it's related (or a dupe of) #1949

**Comment by samhouts** [comment] 2018-08-15 17:54
Closed by #3387

**Closed by samhouts** 2018-08-15 17:54 UTC
Labels: a/Xaml </>, a/binding ⛓, e/3 :clock3:, i/critical, t/bug :bug:
