### ISSUE TITLE
CollectionView SelectionMode SelectionMode="Multiple" Not working ( #5625 Not Solved) 

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5844] opened 2019-04-08 08:22 UTC
### Description
The issue #5625  was closed but it is not fixed.
In UWP I can't still select more than one item.
In Android I can, but the two way binding is not working (it works in mode= "single" but not in "Multiple") so in the UI I can see more than 1 item selected but it doesnt get reflected in the viewmodel.

**Comment by samhouts** [comment] 2019-04-08 18:26
Duplicate of #5625

**Closed by samhouts** 2019-04-08 18:26 UTC
Labels: t/bug :bug:
