### ISSUE TITLE
Xmarin.Form Image tag can't load image from web with android api 28

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7411] opened 2019-09-05 20:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/705537/xmarinform-image-tag-cant-load-image-from-web-with.html)._

---
<p><strong>I used this xaml as below but that just show label text,not images.</strong></p> <p>&lt;xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;</p> <p>&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot;<br>             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;<br>             x:Class=&quot;WorkingWithImages.DownloadImagesXaml&quot;&gt;<br>    &lt;StackLayout Margin=&quot;20,35,20,20&quot;&gt;<br>        &lt;Label Text=&quot;Image UriSource XAML&quot;<br>               FontAttributes=&quot;Bold&quot;<br>               HorizontalOptions=&quot;Center&quot; /&gt;<br>        &lt;Image Source=&quot;http://pic30.nipic.com/20130619/9885883_210838271000_2.jpg&quot; /&gt;
        &lt;!--- Alternatively you can use attached property to manually alter the cache time--&gt;<br>        &lt;Image IsVisible=&quot;false&quot;&gt;<br>            &lt;Image.Source&gt;<br>                &lt;UriImageSource<br>                    Uri=&quot;http://pic30.nipic.com/20130619/9885883_210838271000_2.jpg&quot;<br>                    CacheValidity=&quot;10:00:00.0&quot; /&gt;<br>            &lt;/Image.Source&gt;<br>        &lt;/Image&gt;
        &lt;Label Text=&quot;This image is downloaded from microsoft.com.&quot; /&gt;<br>    &lt;/StackLayout&gt;<br>&lt;/ContentPage&gt;</p>
</p>

---
#### Visual Studio Feedback System on 8/23/2019, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2019-09-06 00:35
Duplicate of #7248

**Closed by samhouts** 2019-09-06 00:35 UTC
