### ISSUE TITLE
[Question] Xamarin Forms with .NET 6?

### ISSUE THREAD

**Issue by ToolmakerSteve** [xamarin/Xamarin.Forms#14960] opened 2021-12-05 20:09 UTC
Until MAUI reaches RC, it would be good to have an official word on the closest that XF app devs can get to MAUI. (I've been actively answering StackOverflow questions re Xamarin Forms - https://stackoverflow.com/tags/xamarin.forms/topusers)

For testing purposes, I just created a new XF project in VS 2022 Community. (The stable release, not preview - this is for apps that are in or near production release.)

I notice that XF project still won't support anything newer than ".NET Standard 2.0".

Any attempt to use ".NET Core xx" or ".NET 6.0" (on the cross platform project) results in incompatibilities with the mobile (Android and iOS) projects.

Is this expected? Is this going to change in the near future?

**Comment by GalaxiaGuy** [comment] 2021-12-06 08:41
What happens if you update the mobile projects to `net6.0-android` and `net6.0-ios`?

**Comment by jfversluis** [comment] 2021-12-06 14:00
I don't see why we would do that, if you really want to you could take the source here and compile it against .NET 6 I guess. Also this has been asked before.

**Comment by jfversluis** [comment] 2021-12-06 14:00
Duplicate of #14829

**Closed by jfversluis** 2021-12-06 14:00 UTC
Labels: t/bug :bug:, s/unverified
