### ISSUE TITLE
Listview binded to ObservableCollection crashes on Android when selecting item.

### ISSUE THREAD

**Issue by japero** [xamarin/Xamarin.Forms#6487] opened 2019-06-11 06:52 UTC
### Description
Listview binded to ObservableCollection shows data correctly but when selecting item OnItemTapped event crashes app.  I added break to event handler but it is never reach.

Here is the datasource
      public ObservableCollection<ZoneCompinedInfo> ZoneCompinedInfos
        {
            get { return zoneCompinedInfos; }
            set
            {
                zoneCompinedInfos = value;
                this.OnPropertyChanged();
            }
        }

And here is how i fill it when data is updated.

ZoneCompinedInfos = new ObservableCollection<ZoneCompinedInfo>(infos);

Of course I cannot show alldata due it is our app but this should give some idea?

### Steps to Reproduce

1. Listview binded to ObservableCollection<Classs>()
2. Listview shows data using DataTemplates to get binging to class properties.
3. Selecting item crashes app. 

### Expected Behavior
App shows View dispalying details about selected item
### Actual Behavior
App crashes before hitting event handler break point.
### Basic Information

- Version with issue: Latest stable Xamarin version 4.0.0.482894
- Last known good version: 3.5.0.274416 works just fine
- IDE:
- Platform Target Frameworks: tested on Android
  - iOS:  
  - Android: 8.1 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment] 2019-06-11 07:05
Thanks for your report! Might I trouble you to maybe provide a few more things:

* A reproduction sample project showing this issues
* The details of the error message or crash that you are experiencing

I see you only stated Android do you also have any other platforms in there? Are they working as they should?

**Comment by japero** [comment] 2019-06-11 07:21
- I can try to make some kind of mock up app. Quite busy at the moment. 

- I will update nuget later today and see if I can get the error report. It was long! Something related to Fatal signal 11 (SIGSEGV). 
We are only using Android at the moment so now knowledge from other platforms.

**Comment by japero** [comment] 2019-06-11 08:19
I attached the error from visual studio Debug window. Quite impressive :-)

[error.txt](https://github.com/xamarin/Xamarin.Forms/files/3275405/error.txt)

**Comment by jfversluis** [comment] 2019-06-11 11:35
I see! Unfortunately the cause is still not very clear from this logs. If at all possible we would still like to receive a reproduction so we can investigate what exactly is going on.

**Comment by kvpt** [comment] 2019-06-11 11:48
From the log, the issue is not in Xamarin.Forms but in the layer below, Xamarin.Android.
Possibly issue [3112](https://github.com/xamarin/xamarin-android/issues/3112) or issue [3178](https://github.com/xamarin/xamarin-android/issues/3178).
If it's not one of them, open a new issue on the Xamarin.Android repository [here](https://github.com/xamarin/xamarin-android/issues/new).

**Comment by japero** [comment] 2019-06-11 12:18
I made simple testapp that has just listview that is tied to ObservableCollection<Crasher>() but unfortunaltely it works. Might be a sum of things this our application crash because as I said application is quite comblex. It receives  data from server on certain interval and updated among other things this view. That I do not quite understand why it is working just fine with older Xamarin version? All other things are working and data is updated correctly to listview but when I click it to see more info application crashes. I will try to dig deeper but my time is limited for this. If now one other has faced this then there is something else in app causing this? Those issues suggested above do not quite match this one.

**Comment by kvpt** [comment] 2019-06-11 12:25
A SIGSEGV is a crash from the Xamarin.Android/Mono runtime.
Nothing in Xamarin.Forms can cause this. When Xamarin.Android (Forms) fail you will have a JavaException, this is not the case here so the problem is not from your code neither in the Xamarin.Android Framework. The issue is a regression in the runtime layer.
The only thing that you can do, is openning an issue in the Xamarin.Android repository and join your crahs log.

**Comment by japero** [comment] 2019-06-11 12:30
Ok. Copied this there and attached error log. Should I now close this one? Have not used this so often.

**Comment by kvpt** [comment] 2019-06-11 12:55
Yes, you can close it here.

Moved to Xamarin.Android repository [here](https://github.com/xamarin/xamarin-android/issues/3198).

**Closed** 2019-06-11 13:04 UTC
Labels: a/listview, p/Android, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
