### ISSUE TITLE
[Bug] MasterDetail Master width issue.  

### ISSUE THREAD

**Issue by nadkarninaveen** [xamarin/Xamarin.Forms#7224] opened 2019-08-21 10:06 UTC
### Description
Hi Team,

We are using an application that is made up of master detail page, On iOS 13 Beta we found that the master section width of the master detail gets expanded on bringing the application to background and again getting it to foreground after 10 sec. 
 
### Steps to Reproduce

1. Launch the application in landscape mode.
2. Bring the application to background and wait for 10sec.
3. Bring the application to foreground, we could notice that the master detail ,master width is expanded.

### Expected Behavior
Master detail master section width remains the same on getting the application to background and foreground.

### Actual Behavior
Master detail master section width expands on getting the application to background and foreground.

### Basic Information

- Version with issue: iOS 13 Beta 7 and Xamarin Preview 4
- Last known good version: iOS 12 and Xamarin Previous versions
- IDE: Visual Studio 8.2.2 (build 44) 
- Platform Target Frameworks: 
  - iOS:  iOS 13 Beta 7

![IMG_0019](https://user-images.githubusercontent.com/42339813/63418480-c5521800-c420-11e9-9b4c-ff62e9cb6035.PNG)
![IMG_0020](https://user-images.githubusercontent.com/42339813/63418485-c84d0880-c420-11e9-9221-1d9baeb6d0f1.PNG)

- Affected Devices: iPad Air 2 iOS 13 

### Reproduction Link

https://drive.google.com/open?id=1fFpw5p3au2Mbtd3qvEFwvSa6GMwitKW_

**Comment by samhouts** [comment] 2019-08-22 00:30
@nadkarninaveen I was unable to get to your reproduction project. It looks like it doesn't exist. What version of Xamarin.Forms are you using? Thanks!

**Comment by nadkarninaveen** [comment] 2019-08-22 06:43
@samhouts  Thanks for the quick response 
Here is the updated link  : https://drive.google.com/file/d/1fFpw5p3au2Mbtd3qvEFwvSa6GMwitKW_/view?usp=sharing
can you please try with this and Xamarin.Forms we are currently using  3.4.0.1008975 but we also checked out that the issue is still present in the latest version of Xamarin.Forms i.e 4.0 .
Thanks
Naveen M Nadkanri

**Comment by PureWeen** [comment] 2019-08-23 21:21
This is an interesting one. 

On the iPad Air (and only the iPad Air) when you minimize a split view controller iOS sets the bounds on the MainViewController to a value higher than it should display at.  Then when you foreground the app it sets it back to the correct width. Because of some RTL code that we have we pin the width of the master view controller to the heighest width. 

I tested this all using xCode as well and I see the same behavior there with a minimal sample. I'm going to log an issue with Apple. In the mean time we'll see if we can work around it if it looks like something that won't be fixed in the final xcode releases

**Comment by nadkarninaveen** [comment] 2019-08-26 06:29
Thanks PureWeen for testing out the issue, currently we have done some work around from the UI side to fix the issue by adding another dummy container and stacking it horizontally in one container  and restricting the max preferred width to 320.Thanks for the testing on all platforms and letting us know the specific issue :) Looking forward for fix thanks :) 

Regards 
Naveen M Nadkarni

**Closed** 2019-09-05 17:29 UTC
Labels: iOS 13, p/iOS 🍎, t/bug :bug:
