### ISSUE TITLE
[Bug] UWP DispatcherProvider issue

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#8729] opened 2019-12-03 00:13 UTC
### Steps to Reproduce

Sample project: https://github.com/Haapsaari-Juha/DemoApp
Steps:
1. Run UWP project from sample and exception is thrown
2. Run Android project from the sample and no exception and arrows are shown on carousel view
3. Comment left and right arrow controls from MainPage.xaml in the shared project
4. Running with UWP and Android projects both will work

NullReference exception.
Stacktrace:
```
Xamarin.Forms
AnimationExtensions.DoAction (IAnimatable self, Action action)
Xamarin.Forms
AnimationExtensions.Animate[T] (IAnimatable self, String name, Func2 transform, Action1 callback, UInt32 rate, UInt32 length, Easing easing, Action2 finished, Func1 repeat)
Xamarin.Forms
AnimationExtensions.Animate (IAnimatable self, String name, Action1 callback, UInt32 rate, UInt32 length, Easing easing, Action2 finished, Func1 repeat) Xamarin.Forms AnimationExtensions.Animate (IAnimatable self, String name, Animation animation, UInt32 rate, UInt32 length, Easing easing, Action2 finished, Func`1 repeat)
PanCardView.Utility
AnimationWrapper.Commit (View view, String name, UInt32 rate, UInt32 length, Easing easing)
PanCardView.Controls.ArrowControl
d__53.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore
<>c.b__6_0 (Object state)
System.Threading.WinRTSynchronizationContextBase
Invoker.InvokeCore ()
Windows.ApplicationModel.Core
UnhandledError.Propagate ()
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.b__17_1 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

I think this line is the root cause: https://github.com/xamarin/Xamarin.Forms/blob/65bf425a6f8dc748b2fdd64b958a7a2fab873f69/Xamarin.Forms.Platform.UAP/DispatcherProvider.cs#L32

UWP code can return null-dispatcher, that will cause a null-ref crash.

More info: https://github.com/AndreiMisiukevich/CardView/issues/314

### Expected Behavior
No crash on UWP

### Actual Behavior
crash on UWP

### Basic Information
- Version with issue: latest

**Comment by jfversluis** [comment] 2019-12-03 13:02
Probably duplicate of or same cause as #8682

**Comment by AndreiMisiukevich** [comment] 2019-12-03 13:09
> Probably duplicate of or same cause as #8682

seems yes

**Closed** 2019-12-03 19:58 UTC
Labels: s/unverified, t/bug :bug:
