### ISSUE TITLE
BoxView binding to BackgroundColor broken as of XF3.1

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#3557] opened 2018-08-13 20:59 UTC
### Description
As of 3.1 binding to `BackgroundColor` is no longer honored.  Nor is binding to the `Color` property; whatever that is and how it is different than `BackgroundColor` for a box.  Apparantly if you bind both to the same backing property _then_ it works. So maybe the two are ping-ponging against each other.

I don't think there needs to be two color properties.  `BackgroundColor` is the standard for everything else like a `Grid`. And in fact you can replace `BoxView` with `Grid` in the now-broken XAML and it all works fine.

### Steps to Reproduce
Set up a XAML with a `BoxView` and bind to the `BackgroundColor`
https://forums.xamarin.com/discussion/comment/343005
![image](https://user-images.githubusercontent.com/11351506/44057727-0e3e4066-9f1a-11e8-9014-a08f5a0fb8c6.png)

1. 
2. 
3. 

### Expected Behavior
Color should change when binded property updates.

### Actual Behavior
Nope - doesn't change.

### Basic Information
https://forums.xamarin.com/discussion/comment/343005

- Version with issue: XamForms 3.1
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment] 2018-08-13 22:12
As a workaround, use `Color` instead.

duplicate of #3342

**Comment by samhouts** [comment] 2018-08-13 22:14
Apologies, I just read your description more closely. Do you have the same issue with a static color, or is it just binding?

**Comment by tlhintoq** [comment] 2018-08-14 12:17
Good morning @samhouts -
Its binding to a color property on a class.
Scenario:
Custom `ItemView` class that takes an `ObservalbeCollection<Tile>`.  The `PaperColor` property is on the `Tile` class.  Defining the tiles is very straight-forward
```csharp
            tiles[3].PaperColor = Color.FromHex("#96FF00");
            tiles[3].Value = -1;

            tiles[4].PaperColor = Color.FromHex("#ffffff");
            tiles[4].Value = 0;

            tiles[5].PaperColor = Color.FromHex("#FF8DA1");
            tiles[5].Value = 1;
```
This produces an `ItemView` not unlike a `ListView` where each `Tile` has a same color swatch for the `PaperColor`
![image](https://user-images.githubusercontent.com/11351506/44090845-8c9bbf36-9f99-11e8-9781-caf8a28f1418.png)

But I think the important take-away pointer here are:

1.  This worked fine for 2 years, until Xamarin Forms 3.1.  We moved from 2.4 PCL to 3.1 .NET standard in one transition.
2. This works if you bind the `BackgroundColor` and `Color` properties to the same binding property.  One or the other does not work.  And why are there now two properties for the same thing on this control? Adding `Color` makes no sense and the documentation makes no explanation about what this new property is supposed to be.  I _suspect_ it is interfering with `BackgroundColor` and vice versa.
3. Switching from a `BoxView` to a `Grid` and no other changes works perfectly. So its not a problem with any of the classes, properties or bindings.  Presumably the `Grid` is a heavier control and will cost more rendering time, thus the `BoxView`; otherwise I'd have no reason to use it except for a wish to keep every little part as light and fast as possible for the **cumulative** affect on rendering performance.

**Comment by tlhintoq** [comment] 2018-08-14 13:14
Someone on the Xamarin.Form made this observation about a commit that may be the cause, if someone wants to investigate.
https://forums.xamarin.com/discussion/comment/343104#Comment_343104

**Comment by samhouts** [comment] 2018-08-14 16:26
Well, that commit was in 3.2, and it is resolved (see https://github.com/xamarin/Xamarin.Forms/issues/3557#issuecomment-412682680). It does not explain your issue.

**Comment by hartez** [comment] 2018-08-24 22:59
@tlhintoq If I'm understanding your report correctly, when you bind a BoxView's Color or BackgroundColor properties to a Color value from a model, the color value doesn't take. 

I'm trying to reproduce this with 3.1, but so far I'm not having any luck. I'm attaching my attempt at a repro; am I missing something?

Binding Color only works.
Binding BackgroundColor only works.
Bound BackgroundColor vs static Color: Color wins.
Static BackgroundColor vs bound Color: Color wins.
Binding both to the same value works (I'm guessing this is just another case of Color winning).

[_3557 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2320129/_3557.Repro.zip)

**Comment by tlhintoq** [comment] 2018-08-24 23:58
Thanks for the  effort and attempts @hartez .  I'll go over that this weekend and hopefully  have some insight by Monday.

**Comment by PureWeen** [comment] 2018-09-10 20:14
@tlhintoq  were you able to uncover any additional insights?

**Comment by samhouts** [comment] 2018-10-14 21:11
@tlhintoq  Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!

**Closed by samhouts** 2018-10-14 21:11 UTC
Labels: s/needs-info ❓

**Comment by Abhijit-Revamp** [comment] 2018-11-03 10:11
I am seeing exactly the same problem in 3.2.0 (cannot update to 3.3 due to blocking issue of crash)
```
<Label Text="{Binding Label}"  TextColor="{Binding ElementColorSecondary}" 
                   Grid.Row="0" HorizontalOptions="Start" VerticalOptions="Start"/>
<BoxView Grid.Row="1" HorizontalOptions="FillAndExpand" HeightRequest="4"
                     VerticalOptions="FillAndExpand" Color="{Binding ElementColorSecondary}" />
<BoxView Grid.Row="2" HorizontalOptions="FillAndExpand" HeightRequest="4"
                     VerticalOptions="FillAndExpand" BackgroundColor="{Binding ElementColorSecondary}" />
```

In C#
```
public Color ElementColorSecondary { get { return Color.FromHex("#FF006489"); } }
```

The text get the color properly, but the both the BoxViews are transparent (one uses color another backgoundcolor).
