### ISSUE TITLE
picker focus() not show dialog pop-up in just android 9.0 (Xamarin.forms 3.5)

### ISSUE THREAD

**Issue by 1mohmmad4** [xamarin/Xamarin.Forms#5433] opened 2019-03-03 07:19 UTC
### Description
picker in xamarin.forms version 3.5 is not working in android 9.0 but in previous version of android or even all system versions of iOS  it is working good if you are tap on picker or focus on it by focus() function in code behind of from anywhere it will show you the dialog pop-up.

### Expected Behavior
show dialog pop-up when click on picker or focus on it.

### Actual Behavior
not showing dialog pop-up when click on picker or focus.

### Basic Information
- Version with issue: 3.5
- Last known good version: 3.2
- Platform Target Frameworks:
  - Android: 9.0

**Comment by PureWeen** [comment] 2019-03-03 21:11
most likely a duplicate of 
https://github.com/xamarin/Xamarin.Forms/issues/5159

**Comment by 1mohmmad4** [comment] 2019-03-04 07:12
* custom control :

using System;
using Xamarin.Forms;

namespace Common.Localization.Controlls
{
    public class PickerExt : Picker
    {
        public Action ShowPicker;
    }
}

=================================

* Xaml File :

                <controlls:PickerExt  x:Name="PickerList"/>

=================================

code behind:

            if(Device.RuntimePlatform == Device.Android)
                PickerList.ShowPicker?.Invoke();


=================================

Renderer for android 

[assembly: ExportRenderer(typeof(PickerExt), typeof(PickerExtRenderer))]
namespace MainApp.Droid.Renderers
{
    public class PickerExtRenderer : Xamarin.Forms.Platform.Android.AppCompat.PickerRenderer
    {
        protected PickerExt PickerExt { get; private set; }

        public PickerExtRenderer(Context context) : base(context)
        {
            AutoPackage = false;
        }
        protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            base.OnElementChanged(e);
            if (Control == null)
                return;

            PickerExt = (PickerExt)Element;
            PickerExt.ShowPicker = () => Control.PerformClick();
        }
    }
}

**Comment by samhouts** [comment] 2019-03-04 18:13
Duplicate of #5159

**Closed by samhouts** 2019-03-04 18:13 UTC
Labels: t/bug :bug:
