### ISSUE TITLE
[Bug] Frame.CornerRadius and Button.CornerRadius is not equal variable type

### ISSUE THREAD

**Issue by kcrg** [xamarin/Xamarin.Forms#9333] opened 2020-01-27 13:52 UTC
### Description
Button:
https://docs.microsoft.com/pl-pl/dotnet/api/xamarin.forms.button.cornerradius?view=xamarin-forms
Frame:
https://docs.microsoft.com/pl-pl/dotnet/api/xamarin.forms.frame.cornerradius?view=xamarin-forms

### Steps to Reproduce
1. Create Frame and Button in XAML.
2. Add the same StaticResource in CornerRadius for both, Button and Frame.

### Expected Behavior
Button.CornerRadius and Frame.RadiusCorner have the same type of variable.

### Actual Behavior
> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### Basic Information
- Version with issue: 4.3
- IDE: Visual Studio 2019 16.3 

### Workaround
Make two different resources for Button (x:TypeArguments="x:Int32") and Frame (x:TypeArguments="x:Single").

**Comment by StephaneDelcroix** [comment] 2020-01-30 10:47
we know about that, it's this way for historical reasons unfortunately, and it's almost impossible to fix without it being a breaking change

**Comment by samhouts** [comment] 2020-02-12 20:19
Duplicate of #1814

**Closed by samhouts** 2020-02-12 20:19 UTC
Labels: a/button, a/frame, a/style, i/high, s/unverified, t/bug :bug:

**Comment by programmation** [comment] 2020-02-14 03:58
> we know about that, it's this way for historical reasons unfortunately, and it's almost impossible to fix without it being a breaking change

If I can add my $0.02, please ignore the fact that it's a breaking change and consider instead the massive additional value afforded by being able to have rounded corners on _any_ visual element. If you rename the current `CornerRadius` property in the objects that have it (maybe add some runtime flag to say use the old property instead of the new one?), that should get around any naming conflicts, and any die-hards that still want to use the old property can update their code and continue working.
