### ISSUE TITLE
Button.IsEnabled is ignored if Command is set, even if the command doesn't have canExecute Func<> set

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#4754] opened 2018-12-15 22:06 UTC
### Steps to Reproduce

1. Declare a button in XAML and set it's Command and IsEnabled bindings like that:
`<Button Text="[D]atabase" Command="{Binding ShowDb}" IsEnabled="{Binding Source={x:Static vm:ViewModelContainer.ResultsDbViewModel}, Path=Enabled}"/>
`
2. Create command without canExecute delegate being defined:

```
        private ICommand showDb = new Command(() => { ViewModelContainer.ResultsDbViewModel.IsVisible = true; });

        public ICommand ShowDb
        {
            get
            {
                return showDb;
            }
        }

```
3. Set the Enabled value in ViewModel to false

### Expected Behavior

If Command doesn't specify canExecute, then IsEnabled value from binding is used and the button is disabled.

### Actual Behavior

IsEnabled value is ignored, the button is enabled

### Basic Information

- Version with issue: Xamarin.Forms 3.2
- IDE: Visual Studio for Mac 7.7.1
- Platform Target Frameworks: macOS

**Comment by dustin-hitzing** [comment] 2019-02-19 19:53
IsEnabled bindable property is readonly

**Comment by maxim-saplin** [comment] 2019-02-28 14:26
Why is it read-only? Button.IsEnabled property is inherited from VisualElement and it has both getter and setter there: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.isenabled?view=xamarin-forms

**Comment by toomasz** [comment] 2019-06-01 09:47
When this can be fixed?

**Comment by kgbuddhima** [comment] 2019-08-02 11:12
Can you please solve this as soon as possible. 

Because currently we are cheating inside the code like this..

bool isEnabled = true;

if(isEnabled)
{
// some function
Button.Color = "some disabled color" ;
}

**Comment by jfversluis** [comment] 2019-08-19 13:44
Sorry we only found out this late, but this seems to be a duplicate of #2758. Please refer to that issue for progress and read the discussion there on why this is hard to solve at this point. Any input is welcome. I will close this one in favor of the related issue I just mentioned.

**Comment by jfversluis** [comment] 2019-08-19 13:45
Duplicate of #2758

**Closed by jfversluis** 2019-08-19 13:45 UTC
Labels: e/4 :clock4:, t/bug :bug:
