### ISSUE TITLE
[Bug] [Android]Shell crashes when back arrow selected from home screen of template

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/Xamarin.Forms#7572] opened 2019-09-18 13:12 UTC
### Description
Android App crashes when pressing hardware back button

### Steps to Reproduce

1. Create new shell app from project template
2. upgrade all nuget packages
3. Run app, then press the hardware back button in the emulator
![image](https://user-images.githubusercontent.com/1822976/65151530-92eb0900-da26-11e9-97a4-d69809a45e64.png)
reproduced with android API 28 emulator

### Expected Behavior
App shouldn't crash

### Basic Information

- Version with issue: all latest
- Last known good version:
- IDE: VS 2019

**Comment by jfversluis** [comment] 2019-09-18 13:37
Thanks for reporting! It seems there is already an issue open for this. I'll mark this as duplicate, please follow the progress in the linked issue.

**Comment by jfversluis** [comment] 2019-09-18 13:37
Duplicate of #6640

**Closed by jfversluis** 2019-09-18 13:37 UTC
Labels: s/unverified, t/bug :bug:
