### ISSUE TITLE
[Bug] [iOS] Rendering Line shape crashes the app when building using iOS SDK 15.2 with XCode 13.2

### ISSUE THREAD

**Issue by Gayathri-github7** [xamarin/Xamarin.Forms#15200] opened 2022-03-03 13:20 UTC
Description
When using iOS SDK 15.2 (with Xcode 13.2), any Xamarin Forms app that uses Line shapes crashes immediately when the line is rendered.

Steps to Reproduce
Add a Line shape in XAML (or in code)
Compile using iOS SDK 15.2
Run app
For example, this page will crash the app:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XFLineBug.MainPage">

    <Grid>
        <Line X1="10" Y1="10" X2="100" Y2="50" Stroke="Red" StrokeThickness="3"/>
    </Grid>

</ContentPage>
Exception thrown: Could not initialize an instance of the type 'CoreGraphics.CGPath': handle is null.

Repro project: [XFLineBug.zip](https://www.syncfusion.com/downloads/support/directtrac/general/ze/App11830083211)
(this is a clean new Xamarin Forms iOS project with the MainPage changed to show a line shape)

Expected Behavior
Line should render on screen

Actual Behavior
App crashes immediately.

Basic Information
Version with issue: 5.0.0.2125 and 5.0.0.2291 (possibly earlier versions as well)
Last known good version: unknown
Platform Target Frameworks:
iOS: 15.2 (Xamarin.iOS 15.4.0)
Android: N/A
UWP: N/A
Android Support Library / AndroidX Version: N/A
Affected Devices: all iOS devices

Environment
Visual Studio 2019 with Xamarin.iOS 15.4.0, Xcode 13.2 and iOS SDK 15.2 installed on Mac agent

**Comment by jfversluis** [comment] 2022-03-07 09:56
Please use the latest version of Xamarin.Forms, it should be fixed there.

**Comment by jfversluis** [comment] 2022-03-07 09:57
Duplicate of #14986

**Closed by jfversluis** 2022-03-07 09:57 UTC
Labels: t/bug :bug:, s/unverified
