### ISSUE TITLE
[Bug] CollectionView rendering problem

### ISSUE THREAD

**Issue by benas1989** [xamarin/Xamarin.Forms#15125] opened 2022-02-06 21:33 UTC
### Description
Hello,
I found a problem with CollectionView.  For some reason, the right edge is cut off. You can see better in the attached photos.
But it only happens on iOS. I test on iPhone simulator and on my iPhone 12.

### Steps to Reproduce

1. Create new project.
2. Add some data to bind (maybe list of strings ).
3. 

```
    <CollectionView
        ItemsSource="{Binding Test}">
        <CollectionView.ItemsLayout>
            <GridItemsLayout
                Orientation="Vertical"
                Span="2"/>
        </CollectionView.ItemsLayout>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Button
                    BorderColor="Black"
                    BorderWidth="1"
                    Text="{Binding .}"></Button>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```

### Basic Information

- Version with issue: ?
- Last known good version: ?
- Platform Target Frameworks: 
  - iOS:  15.2 
  - Android: 11 
- Affected Devices: iPhone 12

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.17 (build 2)
Installation UUID: d713f8ae-7555-41db-bcee-d275dc7fa217
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/benas/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810170002
Git revision: 58f7763d4d64fcf005a474d25a5d9fd5ce46d7f5
Build date: 2022-01-05 12:51:28-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.2.0
Darwin 21.3.0 Darwin Kernel Version 21.3.0
    Wed Jan  5 21:37:58 PST 2022
    root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64


```

</details>

### Screenshots

![margin10](https://user-images.githubusercontent.com/6152093/152702125-09c6e252-da32-4a32-affb-cabb2624b7a9.jpeg)
![test1](https://user-images.githubusercontent.com/6152093/152702127-9081fa5a-87ab-4ea2-ba67-4a5b47977321.jpeg)
<img width="350" alt="Screenshot 2022-02-06 at 22 48 48" src="https://user-images.githubusercontent.com/6152093/152702161-a32e025d-99d6-44ad-af90-5d60d003db8a.png">

**Comment by anchorit3** [comment] 2022-02-08 19:11
I faced the same problem today, it seems like ItemTemplate adding 1px padding.
For me helped this workaround:
https://github.com/xamarin/Xamarin.Forms/issues/12287#issuecomment-736261988

**Comment by benas1989** [comment] 2022-02-08 19:39
Thank you. I also found this solution. But that doesn’t solve the problem. I don’t see the point in doing a complicated visual tree.

**Comment by jfversluis** [comment] 2022-02-09 09:36
Thanks for the report! I see some issues are already open for this, so closing this as a duplicate for now.

**Comment by jfversluis** [comment] 2022-02-09 09:37
Duplicate of #8961

**Closed by jfversluis** 2022-02-09 09:37 UTC
Labels: t/bug :bug:, s/unverified
