### ISSUE TITLE
[Android] Xamarin.forms ProGuard Enable still App size not reducing

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#3254] opened 2018-07-10 05:40 UTC
I have ask this question in Stackoverflow but couldn't get answer I don't know where I have to ask this Question please check link : [ Xamarin.forms Android Proguard issue](https://stackoverflow.com/questions/51245731/xamarin-forms-android-app-proguard-enable-still-app-size-not-reducing)

### Description
Xamarin.forms Android App I have Enable ProGuard but still my app size is 34 MB it is very huge size, can someone suggest what is going wrong here.
I have Enable Proguard.
I have also Enable Multi-Dex, I have tried without this option as well but nothing is changed.
I have added Custom ProGuard for some of the Class and API which is not working in default one.
Linking Selection I have selected Sdk Assemblies Only
Please find my Custom ProGuard file here:

```
-dontpreverify
-repackageclasses ''
-allowaccessmodification
-optimizations !code/simplification/arithmetic
-keepattributes *Annotation*

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep class android.support.annotation.** { *; }
-dontwarn android.support.annotation.*
-keep class android.support.v7.widget.FitWindowsFrameLayout { *; }
-dontwarn android.support.v7.widget.FitWindowsFrameLayout
-dontwarn com.google.android.gms.**
-keep class com.google.android.gms.**
-dontwarn com.microsoft.appcenter.utils.**
-dontwarn com.microsoft.appcenter.push.**
-keepattributes Signature
-keepattributes InnerClasses
-dontoptimize
-keep class org.apache.** { *; }
-keepnames class com.fasterxml.jackson.** { *; }
-keepnames class javax.servlet.** { *; }
-keepnames class org.ietf.jgss.** { *; }
-dontwarn org.apache.**
-dontwarn org.w3c.dom.**
-dontwarn com.auth0.jwt.**

-dontwarn android.support.v4.**

-keep class * extends com.myCompany.package.flavor.Flavor { *; }
-keep class com.myCompany.** { *; }

-keep class org.spongycastle.** { *; }
-dontwarn org.spongycastle.**

-dontwarn com.google.common.collect.MinMaxPriorityQueue
-dontwarn javax.swing.**
-dontwarn java.awt.**
-dontwarn org.jasypt.encryption.pbe.**
-dontwarn java.beans.**

-dontwarn org.bouncycastle.crypto.**
-dontwarn freemarker.template.**

-keep public class * extends android.view.View {
public <init>(android.content.Context);
public <init>(android.content.Context, android.util.AttributeSet);
public <init>(android.content.Context, android.util.AttributeSet, int);
public void set*(...);
}

-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class * implements android.os.Parcelable {
static android.os.Parcelable$Creator CREATOR;
}

-keepclassmembers class **.R$* {
public static <fields>;
}
```

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
It should be below 15 MB
### Actual Behavior
it is now 32.5 MB
### Basic Information

- Version with issue:
Microsoft Visual Studio Professional 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Android Support Library Version: 
- Nuget Packages:

- Affected Devices:

**Comment by PureWeen** [comment] 2018-07-16 23:39
@jitendrajadav  that's a fairly involved proguard file

If you just delete the proguard file completely does the app size go down? I realize the app probably won't run when you do this but I'm just curious if it does

Also do you have any assemblies ignored by the linker?

If you can create a repro where we can see this effect that would be helpful.

Also I wouldn't recommend having proguard and multidex enabled. Just having proguard is preferred

**Comment by jitendrajadav** [comment] 2018-07-17 11:06
@PureWeen If I remove proguard file completely then my app is not running.
secondly I am not enabling multidex then getting error like

> "java.exe" exited with code 2.

lastly I can't upload repository due to some policy sorry for that.

**Comment by PureWeen** [comment] 2018-07-17 16:38
Can you slim down the proguard file to deal with that exit code
If you set build to verbose it'll show you the warnings you can ignore to get it to compile

You can also unzip the APK file (change the extension to Zip) and then inspect in their to see why it's 34 MB

It's hard to know without having some schematic for your project because you might be using a third party library that's not linker friendly

It might also be that you're including architectures you don't need or if you have AOT enabled that will make the file bigger but it'll perform much faster

there's just a lot of factors that play into that size so it's a bit tricky to orient onto the cause without seeing the project or a repro

**Comment by jitendrajadav** [comment] 2018-07-18 10:29
Hi @PureWeen Please find my App here and let me know what is going wrong here 
[SampleApp](https://github.com/jitendrajadav/KegID.git)


I didn't understand Slid down the proguard file issue please check this file also

**Comment by PureWeen** [comment] 2018-07-18 16:56
@jitendrajadav   so it looks like the majority of the size comes from Realm

![image](https://user-images.githubusercontent.com/5375137/42896000-caa7be78-8a78-11e8-8b0f-86d89aebf3c3.png)

If you link sdk and user assemblies that gets it down to around 26 MBs but you'll probably need to tweak the linker some to make sure the app runs

But that's what I meant earlier about 3rd party libraries. My guess is that Realm is fairly large and is setup to not have its classes removed/linked out. There isn't that much we can do about that

**Comment by jitendrajadav** [comment] 2018-07-19 06:04
@PureWeen thank you for you quick look and suggestion can you explain more or give some help to reduce Realm issue, If I link sdk and user assemblies then app is not going to install its say corrupt setup even I run app in a debug mode app run but very slow and second time while resuming it will take much of time?

**Comment by PureWeen** [comment] 2018-07-19 17:21
I would open an issue with Realm about the size of that file to see if they have any suggestions. They might be shipping a debug library or maybe it's some Realm setting that needs to be disabled? 

As far as the rest of the package you're not going to get this to be below 15 MBs

The assemblies folder is 13.4 MBs and that can't be compresed
Your res folder has about 3.1 MBs of drawables so right there you are at 16.5

If you can get the realm library down then you should be sitting around 18 or 19 if you can get full linking to work

**Comment by jitendrajadav** [comment] 2018-07-24 06:16
@PureWeen  thank you very much

**Comment by PureWeen** [comment] 2018-07-24 16:11
@jitendrajadav  I'm going to close this one for now. If you open an issue over at Realm can you link to it please?

**Closed by PureWeen** 2018-07-24 16:11 UTC
Labels: s/needs-info, s/needs-repro, t/question
