### ISSUE TITLE
Named font sizes applied from static resources using onplatform not being applied

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#2077] opened 2018-03-12 11:49 UTC
### Description
this bug is shown resolved here but it sill avabilable in the latest release
https://bugzilla.xamarin.com/show_bug.cgi?id=54416

### Steps to Reproduce
Add a static resource on a page like below
```

<Style x:Key="lblStyle" TargetType="Label">
                <Setter Property="FontSize">
                    <OnPlatform x:TypeArguments="Font">
                        <OnPlatform.Android>
                            <OnIdiom x:TypeArguments="Font" Phone="Micro" Tablet="Small" />
                        </OnPlatform.Android>
                        <OnPlatform.iOS>
                            <OnIdiom x:TypeArguments="Font" Phone="Micro" Tablet="Small" />
                        </OnPlatform.iOS>
                        <OnPlatform.WinPhone>
                            <OnIdiom x:TypeArguments="Font" Phone="Micro" Tablet="Small" Desktop="Small" />
                        </OnPlatform.WinPhone>
                    </OnPlatform>
                </Setter>
  </Style>

  <Label   Style="{StaticResource lblStyle}"  />
```

### Expected Behavior

that it applies fontsize

### Actual Behavior

Not applying at all

### Basic Information

I tried using x:Double instead of Font as well and it doesnt work. And if you even apply directly on label like below, you get error on build.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		No property, bindable property, or event found for 'FontSize', or mismatching type between value and property.

```
<Label  >
                        <Label.FontSize>
                            <OnPlatform x:TypeArguments="Font">
                                <OnPlatform.Android>
                                    <OnIdiom x:TypeArguments="Font" Phone="Small" Tablet="Medium" />
                                </OnPlatform.Android>
                                <OnPlatform.iOS>
                                    <OnIdiom x:TypeArguments="Font" Phone="Small" Tablet="Medium" />
                                </OnPlatform.iOS>
                                <OnPlatform.WinPhone>
                                    <OnIdiom x:TypeArguments="Font" Phone="Small" Tablet="Medium" Desktop="Large" />
                                </OnPlatform.WinPhone>
                            </OnPlatform>
                        </Label.FontSize>
```

- Version with issue: 2.5.0.280555
- Last known good version: 
- IDE:VS 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment] 2018-03-20 11:41
this is not the same as 54416, we will need a reproduction please @EmilAlipiev , a small project that shows the problem. 

THanks

**Comment by jassmith** [comment] 2018-04-07 04:33
Closing due to lack of reproduction, please reopen if one is provided.

**Closed by jassmith** 2018-04-07 04:33 UTC
Labels: s/needs-info, s/needs-repro, t/bug

**Comment by mos379** [comment] 2019-10-25 09:54
It seems this issue is still not resolved. 
When using 
`<Style x:Key="DropInLabelLayout" TargetType="Label" BaseResourceKey="CaptionStyle">
                <Setter Property="FontSize">
                    <OnIdiom x:TypeArguments="x:String" Tablet="Default" Phone="Small" />
                </Setter>
            </Style>`
Then I get the following error
 SetValue: Can not convert Xamarin.Forms.OnIdiom`1[System.String] to type 'System.Double'
seems like the converter is not used in this scenario to translate the value into double.
