### ISSUE TITLE
Xamarin Forms app crashes on iOS trying to create an Array

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Xamarin.Forms#4245] opened 2018-10-28 16:28 UTC
### Description

I created an app for UWP, Android and iOS. Tested on all environments.
On iOS it runs fine on a simulator or a physical device (iPad) in most modes.
It crashes on the iPad only when not in Debug and when linker options are set the Framework SDK.
When using "Don't Link" it works.

The exception shows

After a machine restart. Re-built with "Link Framework SDK" and it created a smaller ipa which crashes with "System.MissingMethodException - Default constructor not found for type System.Array"

I was able to find the statement where the error occurred and it was happening when the code was creating an instance of a ContentView.
Digging further, the ContentView has declared the following array in XAML
```
<x:Array Type="{x:Type x:Double}" x:Key="ImageOpacity">
     <x:Double>1.0</x:Double>
     <x:Double>0.4</x:Double>
 </x:Array>
```
I removed that item and replaced it by creating a simple class
 `public class ListOfDoubles : List<double>     { } `
Then my xaml changed to 

```
<customTypes:ListOfDoubles x:Key="ImageOpacity">
           <x:Double>1.0</x:Double>
           <x:Double>0.4</x:Double>
</customTypes:ListOfDoubles>
```
I re-ran the program and it does not crash.
Seems like a bug.
The same code works on UWP and Android.
It also works on iOS in Debug mode, or when using the "Don't Link" option.
If anyone can point me as to where to report this bug I would appreciate it.

### Steps to Reproduce

I have tried to create a simple app that does nothing but create an Array within an XAML resource, but could not get it to crash as it consistently does in my app ?
I assume that unless other's report a similar problem, this will need to be closed.
I will keep trying to reproduce the exact issue.

On my app it is consistent, If I include the <Array> resource, it will crash on the iPad. 
If I remove it and replace it with a List, then it will work.
The error "Default constructor not found for type System.Array" seems suspect.

### Basic Information

- Version with issue:
Xamarin 3.3.0912540

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  The version of the iOS SDK you are compiling against, e.g. 12
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

Since I cannot provide a reproducible example, I am uploading the Exception log showing the error.
[log.2018-10-28T10-49-06.txt](https://github.com/xamarin/Xamarin.Forms/files/2522952/log.2018-10-28T10-49-06.txt)

**Comment by pauldipietro** [comment] 2018-10-29 14:47
Until you might be able to provide a reproduction (even if it only crashes a portion of the time) we will move this to needing more info. Please do provide one if you're able, though.

**Comment by valentinba** [comment] 2018-10-29 20:07
Possible duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3790 ?

**Comment by samhouts** [comment] 2018-11-28 01:34
@solomonfried Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2018-11-28 01:34 UTC
Labels: p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔
