### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 2327

### ISSUE THREAD

**Issue by amrkamal1993** [xamarin/Xamarin.Forms#6380] opened 2019-06-01 13:29 UTC
I have a problem in debugging code in android using xamarin forms application crash in master detail and give me this error 
I tried to clean , build and delete bin and obj no solution works

I use xamarin.forms 4.0
vs 2019 16.1.1

### Steps to Reproduce

1. 
2. 
3. 

### Actual Behavior
```
=================================================================
    Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
    Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x7d689fd678):0x7d689fd668  00 1c 40 b9 c0 03 5f d6 fd 7b bf a9 fd 03 00 91  ..@..._..{......
0x7d689fd678  08 20 40 b9 a8 00 c8 37 88 01 e0 37 00 00 40 f9  . @....7...7..@.
0x7d689fd688  fd 7b c1 a8 c0 03 5f d6 60 08 00 b0 01 0a 00 f0  .{...._.`.......
0x7d689fd698  03 0a 00 f0 00 24 06 91 21 80 08 91 63 8c 0a 91  .....$..!...c...

No native Android stacktrace (see debuggerd output).

===============================================06-01 15:23:19.407 E/mono-rt ( 2327): /proc/self/maps:

==================
    Managed Stacktrace:
=================================================================
=================================================================06-01 15:23:19.407 E/mono-rt ( 2327): 12c00000-52c00000 rw-p 00000000 00:01 18226                              /dev/ashmem/dalvik-main space (region space) (deleted)

06-01 15:23:19.407 E/mono-rt ( 2327): 6fdee000-70096000 rw-p 00000000 103:09 28170                             /data/dalvik-cache/arm64/system@framework@boot.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70096000-7019c000 rw-p 00000000 103:09 28174                             /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
06-01 15:23:19.407 E/mono-rt ( 2327): 7019c000-701e6000 rw-p 00000000 103:09 28176                             /data/dalvik-cache/arm64/system@framework@boot-conscrypt.art
06-01 15:23:19.407 E/mono-rt ( 2327): 701e6000-7021c000 rw-p 00000000 103:09 28177                             /data/dalvik-cache/arm64/system@framework@boot-okhttp.art
06-01 15:23:19.407 E/mono-rt ( 2327): 7021c000-70220000 rw-p 00000000 103:09 28180                             /data/dalvik-cache/arm64/system@framework@boot-legacy-test.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70220000-70263000 rw-p 00000000 103:09 28182                             /data/dalvik-cache/arm64/system@framework@boot-bouncycastle.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70263000-7029e000 rw-p 00000000 103:09 28201                             /data/dalvik-cache/arm64/system@framework@boot-ext.art
06-01 15:23:19.407 E/mono-rt ( 2327): 7029e000-70a8b000 rw-p 00000000 103:09 28204                             /data/dalvik-cache/arm64/system@framework@boot-framework.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70a8b000-70b17000 rw-p 00000000 103:09 28316                             /data/dalvik-cache/arm64/system@framework@boot-telephony-common.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b17000-70b20000 rw-p 00000000 103:09 28329                             /data/dalvik-cache/arm64/system@framework@boot-voip-common.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b20000-70b29000 rw-p 00000000 103:09 28350                             /data/dalvik-cache/arm64/system@framework@boot-ims-common.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b29000-70b4d000 rw-p 00000000 103:09 28406                             /data/dalvik-cache/arm64/system@framework@boot-apache-xml.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b4d000-70b75000 rw-p 00000000 103:09 28409                             /data/dalvik-cache/arm64/system@framework@boot-org.apache.http.legacy.boot.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b75000-70b76000 rw-p 00000000 103:09 28414                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.base-V1.0-java.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b76000-70b79000 rw-p 00000000 103:09 28424                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.manager-V1.0-java.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70b79000-70c04000 rw-p 00000000 103:09 28425                             /data/dalvik-cache/arm64/system@framework@boot-hwEmui.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70c04000-70c2b000 rw-p 00000000 103:09 28432                             /data/dalvik-cache/arm64/system@framework@boot-hwTelephony-common.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70c2b000-70c64000 rw-p 00000000 103:09 28494                             /data/dalvik-cache/arm64/system@framework@boot-hwframework.art
06-01 15:23:19.407 E/mono-rt ( 2327): 70c64000-70c66000 rw-p 00000000 103:09 28500                             /data/dalvik-cache/arm64/system@framework@boot-org.simalliance.openmobileapi.art
06-01 15:23:19.408 E/mono-rt ( 2327): 70c66000-70c67000 rw-p 00000000 103:09 28502                             /data/dalvik-cache/arm64/system@framework@boot-org.ifaa.android.manager.art
06-01 15:23:19.408 E/mono-rt ( 2327): 70c67000-70c6d000 rw-p 00000000 103:09 28506                             /data/dalvik-cache/arm64/system@framework@boot-hwaps.art
06-01 15:23:19.408 E/mono-rt ( 2327): 70c6d000-70c73000 rw-p 00000000 103:09 28511                             /data/dalvik-cache/arm64/system@framework@boot-hwcustEmui.art
06-01 15:23:19.408 E/mono-rt ( 2327): 70c73000-70c78000 rw-p 00000000 103:09 28513                             /data/dalvik-cache/arm64/system@framework@boot-hwcustframework.art
06-01 15:23:19.408 E/mono-rt ( 2327): 70c78000-70c7f000 rw-p 00000000 103:09 28524                             /data/dalvik-cache/arm64/system@framework@boot-hwcustTelephony-common.art
06-01 15:23:19.409 F/libc    ( 2327): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 2327 (nyname.Ministry)
```

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment] 2019-06-01 18:47
@amrkamal1993 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by amrkamal1993** [comment] 2019-06-02 07:35
@samhouts  sure here the sample which crash 

https://drive.google.com/file/d/1LOW5dKSnccm5NqY3IbU-Cr_1MINZQw6v/view?usp=sharing

**Comment by amrkamal1993** [comment] 2019-06-02 07:46
Testing Devices Huawei Y9 
and Honor

**Comment by amrkamal1993** [comment] 2019-06-02 08:50
@samhouts  crashing happens in master detail page with huawei , i don't know if it's related or not

**Comment by amrkamal1993** [comment] 2019-06-02 13:16
update : the problem only found in vs 2019 i installed last version from 2017 and it's working

**Comment by brendanzagaeski** [comment] 2019-06-03 16:58
Thanks for the report and the test case! I can confirm that this behavior has the same native backtrace as <https://github.com/xamarin/xamarin-android/issues/3112>, so I will close this Xamarin.Forms issue as a duplicate of that issue. The fix will require a new version of Xamarin.Android that will be based on a new version of the Mono runtime and debugger. (The Xamarin.Forms NuGet package version will not affect this behavior.)

For reference, here's the top of the native backtrace with symbols that I got from this Xamarin.Forms test case after clicking the button on the first screen:

```
  * frame #0: 0x0000007126cf5da8 libart.so`art_sigsegv_fault
    frame #1: 0x0000007126cf62b4 libart.so`art::FaultManager::HandleFault(int, siginfo*, void*) + 356
    frame #2: 0x00000058b5382b5c app_process64`___lldb_unnamed_symbol20$$app_process64 + 572
    frame #3: 0x00000071acbdd870 [vdso]
    frame #4: 0x00000071100bf640 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x0000000000000000) at mini-runtime.h:390
    frame #5: 0x00000071100bf638 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #6: 0x00000071100bf640 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x000000710b01a500) at mini-runtime.h:390
    frame #7: 0x00000071100bf638 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #8: 0x00000071100bf2b8 libmonosgen-2.0.d.so`mono_handle_exception(ctx=<unavailable>, obj=<unavailable>) at mini-exceptions.c:2988
    frame #9: 0x00000071100f701c libmonosgen-2.0.d.so`mono_arm_throw_exception(arg=<unavailable>, pc=<unavailable>, int_regs=0x0000007fcd281f50, fp_regs=0x0000007fcd282050, corlib=<unavailable>, rethrow=0) at exceptions-arm64.c:410
```

**Closed by brendanzagaeski** 2019-06-03 16:58 UTC
Labels: i/high, p/Android, s/unverified, t/bug :bug:

**Comment by amrkamal1993** [comment] 2019-06-12 11:46
So when will xamarin.android update ? that's mean i should waiting for the new release ? any workaround ?
