### ISSUE TITLE
Native Crash Reporting at UIKit.UIApplication:UIApplicationMain <0x00259>

### ISSUE THREAD

**Issue by shugaoye** [xamarin/Xamarin.Forms#9903] opened 2020-03-07 07:52 UTC
### Steps to Reproduce

1. Start application [PassXYZ](https://itunes.apple.com/us/app/passxyz/id1402887274?ls=1&mt=8) version 2.1.3.1 in Login Page
2. Enter username and password
3. Press **Enter** key

I believe this can be repeated by creating a dummy login page and switch to a master detail page. It is something to do with the Enter key handling for **Entry** field.

The current workaround is something like this:

```
                    if (Device.RuntimePlatform == Device.iOS) 
                    {
                        passwordEntry.ReturnType = ReturnType.Next;
                    }
                    else 
                    {
                        passwordEntry.ReturnType = ReturnType.Done;
                        passwordEntry.Completed += OnLoginButtonClicked;
                    }
```

### Expected Behavior
Go to MasterDetailPage
### Actual Behavior
Crashed with the below error message. 

This happen in a login page. There is no problem if the **Login Button** is clicked. If press **Enter** key instead of **Login Button**, the App crashed with this issue.

This issue found after upgraded to Xamarin.Forms 4.4.0.991640. Don't have this issue in Xamarin.Forms 3.1.0.583944.
### Environment

```
Microsoft Visual Studio Community 2019
Version 16.4.4
VisualStudio.16.Release/16.4.4+29728.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA171
Microsoft Visual C++ 2019

Azure App Service Tools v3.0.0   16.4.460.23317
Azure App Service Tools v3.0.0

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.309 (d16-4@1d551f9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs
N/A

### Example Project (If Possible)
This issue can be repeated in a beta build of [PassXYZ](https://itunes.apple.com/us/app/passxyz/id1402887274?ls=1&mt=8). If it is required, the beta build can be provided through TestFlight.

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10e070655 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_dump_native_crash_info
	0x10e064745 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_handle_native_crash
	0x10e0778e8 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_sigsegv_signal_handler_debug
	0x7fff52457b5d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7ffee1d13060 - Unknown
	0x10df63805 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : _ZL32native_to_managed_trampoline_280P11objc_objectP13objc_selectorPP11_MonoMethodP11UITextFieldj
	0x10df63c85 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : -[
UIKit_UITextField__UITextFieldDelegate textFieldShouldReturn:]
	0x7fff4839606f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITextField keyboardInput:shouldInsertText:isMarkedText:]
	0x7fff47e9a7d6 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl callShouldInsertText:]
	0x7fff47eac5d5 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl addWordTerminator:afterSpace:afterAcceptingCandidate:elapsedTime:executionContext:]
	0x7fff47e
d009b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardTaskExecutionContext returnExecutionToParentWithInfo:]
	0x7fff47eab456 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl acceptAutocorrectionForWordTerminator:executionContextPassingTIKeyboardCandidate:]
	0x7fff47eaaca6 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl addInputEvent:executionContext:]
	0x7fff47eaa8a1 - /Applications/Xcode.app/Contents/Developer/Platfo
rms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:executionContext:]
	0x7fff47ebd381 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl handleKeyWithString:forKeyEvent:executionContext:]
	0x7fff47ed1ab1 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardTaskEntry execute:]
	0x7fff47ed05c7 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Conte
nts/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardTaskQueue continueExecutionOnMainThread]
	0x7fff47ebc4e8 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIKeyboardImpl handleKeyEvent:]
	0x7fff23c7820c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __invoking___
	0x7fff23c753af - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : -[NSInvocation invoke]
	0x7fff4841d615 - /Applications/Xcode.app/Contents/De
veloper/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIRepeatedAction invoke]
	0x7fff4841d815 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIRepeatedAction _preInvocationTimerFire]
	0x7fff480acd57 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UI
KitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/C
oreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEven
t:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources
/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer
/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480c29b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIResponder _handleKeyUIEvent:]
	0x7fff480abd5f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.fram
ework/UIKitCore : -[UIApplication handleKeyUIEvent:]
	0x7fff480abcd4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication handleKeyHIDEvent:]
	0x7fff4812b15c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __dispatchPreprocessedEventFromEventQueue
	0x7fff4812f1e0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __handleEventQueueInternal
	0x7fff23bd4471 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimul
ator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	0x7fff23bd439c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0
	0x7fff23bd3b74 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0
	0x7fff23bce87f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x7fff23bc
e066 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x7fff384c0bb0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x7fff48092d4d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x11590d52a - Unknown
	0x11554a8d3 - Unknown
	0x115540dd3 - Unknown
	0x10e07ad09 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/72
2C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_jit_runtime_invoke
	0x10e1a8c37 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_runtime_invoke_checked
	0x10e1af09c - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_runtime_exec_main_checked
	0x10dfda992 - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : mono_jit_exec
	0x10e2da26e - /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : xamarin_main
	0x10df951a7 
- /Users/user1/Library/Developer/CoreSimulator/Devices/4CF51D6F-6966-4AAC-A73A-994131D01A06/data/Containers/Bundle/Application/722C38E8-3BA0-4B7F-AD60-82B1750AB0C4/PassXYZ.iOS.app/PassXYZ.iOS : main
	0x7fff5227ec25 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdyld.dylib : start
	0x3 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10e1b3814):0x10e1b3804  48 8d 05 09 5f 1f 00 48 89 45 f0 e8 1c f6 0c 00  H..._..H.E......
0x10e1b3814  48 8b 0b 48 8b 09 f6 41 20 04 74 1a 48 83 c3 10  H..H...A .t.H...
0x10e1b3824  48 8d 75 e8 48 89 c7 e8 30 fa 0c 00 48 89 d8 48  H.u.H...0...H..H
0x10e1b3834  83 c4 18 5b 5d c3 48 8d 3d 69 ae 1e 00 48 8d 35  ...[].H.=i...H.5

==================================================
===============
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00259>
	  at UIKit.UIApplication:Main <0x000b2>
	  at UIKit.UIApplication:Main <0x00132>
	  at PassXYZ.iOS.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00352>
=================================================================
The app has been terminated.Starting Simulator to launch App...

The Simulator has been started to launch App...
```

**Comment by chamons** [comment] 2020-03-09 14:58
Given the Forms specific nature of this, I'm moving it over there for a first pass.

**Comment by jfversluis** [comment] 2020-03-18 10:57
Hey @shugaoye sorry this happened! While you provided a couple of links to download the app, would you be able to distil a reproduction for this? That will make it much easier to see what is going on here.

**Comment by shugaoye** [comment] 2020-03-19 09:57
It seems I need to create an application for you to reproduce this on iOS. Let me try.

**Comment by jfversluis** [comment] 2020-03-19 10:41
That would really help us identify the issue faster and hopefully get to the root cause of this. Creating and seeing a reproduction without other code involved can be really insightful. 

Thank you!

**Comment by samhouts** [comment] 2020-04-20 18:42
@shugaoye Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2020-04-20 18:42 UTC
Labels: a/entry, has-stacktrace, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
