### ISSUE TITLE
[Bug] Image Control doesn't work

### ISSUE THREAD

**Issue by yinyue200** [xamarin/Xamarin.Forms#9900] opened 2020-03-09 14:44 UTC
### Steps to Reproduce

1. archive https://github.com/yinyue200/xamarinformstest in release mode
2. install the apk
3. go to about page

### Expected Behavior
show the image
### Actual Behavior
can't show the image
### Basic Information

- Version with issue:
- Last known good version:4.4
- IDE:VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:   
- Android Support Library Version: AndroidX
- Nuget Packages:
- Affected Devices:

### Screenshots

![Screenshot_2020-03-09-22-37-01-264_com companynam](https://user-images.githubusercontent.com/13848771/76225429-70a8aa00-6257-11ea-9703-dd5f2e532938.jpg)

### Reproduction Link
https://github.com/yinyue200/xamarinformstest
https://github.com/yinyue200/xamarinformstest/releases/tag/1.0

### Workaround
use FFImageLoading

**Comment by ouma** [comment] 2020-03-10 05:52
same here , toolbar icons not showing after archiving in release mode

**Comment by rasel-tr** [comment] 2020-03-11 08:55
+1, I lost images on the Android platform for my Forms project suddenly after upgraded the Xamarin.Forms package.

**Comment by StephaneDelcroix** [comment] 2020-03-12 14:11
does disabling the linker fixes it for you ?

**Comment by yinyue200** [comment] 2020-03-12 14:21
@StephaneDelcroix It failed to archive if linker set to None.
![devenv_2020-03-12_22-18-35](https://user-images.githubusercontent.com/13848771/76531172-c7102580-64af-11ea-83fc-af4d6fb11a5d.png)

**Comment by ouma** [comment] 2020-03-13 06:44
> does disabling the linker fixes it for you ?

No. The issue still persists

**Comment by nhdanh** [comment] 2020-03-17 09:22
Same Error when update to lastest XF

**Comment by NamCkiku** [comment] 2020-03-17 11:02
same here , toolbar icons and image not showing after archiving in release mode

**Comment by rasel-tr** [comment] 2020-03-19 06:01
Any news for this problem? It is a blocker for my project and I can't release a new version.

**Comment by rasel-tr** [comment] 2020-03-20 09:39
Disabling bundle assemblies into native code option resolves my problem.

**Comment by hig-dev** [comment] 2020-03-23 02:25
I have the same problem and I can confirm that disabling "bundle assemblies into native code" fixes the problem. However, this is not an option for me for the Release build. The bug is maybe related to #1595

**Comment by PaulVrugt** [comment] 2020-03-31 10:55
We are running into the same problem. Disabling "bundle assemblies into native code" fixes it, but we don't want to do this.

**Comment by CNouws** [comment] 2020-03-31 11:05
Here the same problem and indeed disabling "bundle assemblies into native code" fixes the problem. But this is not an option. Any update please?

**Comment by rasel-tr** [comment] 2020-03-31 19:09
With newly released version 16.5.2, the problem still continues. It starts with 16.5.0 and this is the second update ignoring this problem :(

**Comment by samhouts** [comment] 2020-04-06 18:43
It looks like this might be related to https://github.com/xamarin/AndroidX/issues/64#issuecomment-606645412. @mattleibow Can you confirm, please? Thanks!!

**Comment by jonpryor** [comment] 2020-04-06 18:49
@hig-dev mentioned:

> [disabling "bundle assemblies into native code"] is not an option for me for the Release build

Would you mind elaborating on why setting `$(BundleAssemblies)`=False isn't an option?  We are [strongly considering removing support for `$(BundleAssemblies)` in .NET 5](https://github.com/xamarin/AndroidX/issues/64#issuecomment-609970584), and would like to better understand *why* people are using it.  (It's *not* a very good obfuscation technology, and for it not being very good it increases on-device memory usage and slows down app startup times.)

**Comment by nexxuno** [comment] 2020-04-09 23:16
Hello, I guess the reason why we are using these kind of bad obfuscation tecniques is that the only other option (dotfuscator) has a starting price of around 4k$ a year so we do what we can with what we have. Any suggestion of better tecnologies for an affordable / free price with azure CI pipelines integrations on microsoft hosted environments?

Anyway this is a bad regression.

**Comment by tranb3r** [comment] 2020-04-10 12:30
> We would like to better understand _why_ people are using it. 

It's decreasing size of apk a lot.

**Comment by rasel-tr** [comment] 2020-04-11 08:40
Also I don't want all the DLLs of the app to be seen in the /lib folder of the apk

**Comment by ia5634** [comment] 2020-05-07 15:36
the same problem is here. target framework: 10.

**Comment by ia5634** [comment] 2020-05-12 20:13
An update: There is no problem with Xamarin.Forms v4.4.0.991864 (from NuGet)

"Target framework is 10" and "bundle assemblies... = true" = not problem at all.

**Comment by keivaan** [comment] 2020-05-14 18:22
It's been more 2 months now. This bug cannot be solved???

**Comment by tranb3r** [comment] 2020-05-15 07:52
This is clearly a regression, so it should be simple enough for the xamarin team to fix it.
But sadly they don't seem to care at all about it.
It's not even clear to me if this is a Xamarin.Forms or a Xamarin.Android regression ? And starting from which version ?

**Comment by yankarinRG** [comment] 2020-05-22 11:37
I am facing the same problem with the latest version of Xamarin.Forms (4.6.0.800) and targetSdkVersion="29" (Android 10 - Queen Cake): if "Bundle assemblies into native code" is enabled, the `Image` won't show.

**Comment by rasel-tr** [comment] 2020-05-25 05:53
Also there isn't any fix for this in 

4.7.0.773-pre1

4.7.0.813-pre2

Pre Release versions. What a regression is it that can not be fixed for more that 2 months.

**Comment by PureWeen** [comment] 2020-05-25 17:41
Closing in favor of https://github.com/xamarin/AndroidX/pull/106 as this is not a Forms issue

**Closed by PureWeen** 2020-05-25 17:41 UTC
Labels: 4.5.0, external-components, i/regression, m/high impact :black_large_square:, p/Android, t/bug :bug:

**Comment by developer9969** [comment] 2020-06-18 13:39
@PureWeen  hi there need this one fix too and I traced it to  https://github.com/xamarin/AndroidX/pull/106 and last comment by Moljac was 
![image](https://user-images.githubusercontent.com/16970109/85027005-54c77500-b171-11ea-909d-7ff74a395e89.png)

Do you know which package is referring to? 4.7?
thank you.
