### ISSUE TITLE
Xamarin.Build.Forms.Tasks.GetTaskAbi

### ISSUE THREAD

**Issue by CamelCaseMaster** [xamarin/Xamarin.Forms#1586] opened 2018-01-15 15:33 UTC
### Description
I have a solution with multiple projects. the Xamarin.Forms projects use the 2.4.0.280 nuget package version.
I Created a new Xamarin.Forms project with the latest(at time of writing this) Xamarin.Forms nuget package 2.5.0.122203 (consolidated all the IOS UWP AND & Class Library)

when i rebuild this project i get this error 

` "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Repos\Project\packages\Xamarin.Forms.2.5.0.122203\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.Build.Tasks.dll.
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available,
 and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OCPExcellenceHSE (OCPExcellenceHSE\OCPExcellenceHSE)	C:\Repos\Project\packages\Xamarin.Forms.2.5.0.122203\build\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.targets
`

### Steps to Reproduce

1. having existing projects in a solution 
2. updating a project to latest xamarin forms version or creating a new project with the latest nuget
3. rebuilding the project

### Expected Behavior

different xamarin.forms nugets to work separately for different projects inside a solution without any issue 

### Actual Behavior

Failed build

### Basic Information

as a "TEMPORARY" >>>SOLUTION<<< (but I did not try it many times as it is so tiring to do):
-cleaning solution
-removing .nuget folder from C:\Users\User\(here) .nuget
-removing packages folder from solution folder

- Last known good version: for me 2.0.4.280
- IDE:  VS2017 15.5.2
- Nuget Packages: Xamarin.Forms
### Screenshots
[https://imgur.com/a/O2Ksh](Screenshots)

**Comment by owlstack** [comment] 2018-01-15 16:10
Possible duplicate of https://github.com/xamarin/Xamarin.Forms/issues/1573.

With the old version I was running 2.4.0, it was working fine until only the upgrade to 2.5.0. It's definitely reproducible as this other person reported the same thing.

**Comment by CamelCaseMaster** [comment] 2018-01-15 16:27
@owlstack  I believe we're experiencing the same issue. Try the solution I added & see if it works for you.

I got it from here https://forums.xamarin.com/discussion/106784/error-with-latest-nuget-v2-5-0-77-xamarin-forms-build-tasks-gettasksabi-task-could-not-be-loaded?

**Comment by StephaneDelcroix** [comment] 2018-01-15 21:27
having multiple version of XF in the same solution is not, and can not, be supported.

each XF nuget comes with it's own build tasks library and only one can be loaded by the msbuild process in the IDE.

make sure all of your project are using the same version of XF nuget.

**Closed by StephaneDelcroix** 2018-01-15 21:27 UTC
Labels: s/invalid

**Comment by SeppyMoose** [comment] 2018-02-12 07:02
Same issue, been unable to build project due to this issue. It is a complete show stopper for any builds, haven't been able to build for over a month.

**Comment by CamelCaseMaster** [comment] 2018-02-12 11:49
just do this if consolidating forms alone don't work for ya:
-consolidate all forms plugins inside the solution (for each project)
-clean solution
-close vs & delete bin/obj folders manually
-remove packages folder in your solution folder
-remove the .nuget ( local nugets cache usually big in size like +3Gb) folder in C:\User\Username\ or Home location in mac
-open solution & restore nuget packages.
normally this'll work perfectly. I hope it helps.

**Comment by rmarinho** [comment] 2018-02-14 17:14
You shold not need this step:  

> - remove the .nuget ( local nugets cache usually big in size like +3Gb) folder in C:\User\Username\ or Home location in mac

**Comment by OsamaWafy** [comment] 2018-04-19 12:03
Installing .net framework 4.7.1 works for me and solved the problem :)

**Comment by realpinman** [comment] 2018-05-10 17:40
i can confirm installing .net 4.7.1 worked for me as well

**Comment by jaganathkumar013** [comment] 2018-06-10 14:44
have done all the above steps,  i have deleted the  .nuget folder 3 times and rebuilt  and my version and all the  .nuget updates are updated to current version, and yet still the problem persists. im sick of this ... kindly solve this issue. Provide us an update Asap...
[App2.Android_Compile_7fdf89c6.designtime.log](https://github.com/xamarin/Xamarin.Forms/files/2087964/App2.Android_Compile_7fdf89c6.designtime.log)

**Comment by StephaneDelcroix** [comment] 2018-06-11 09:11
@jaganathkumar013 
> have done all the above steps

but your log indicates you're using .net 4.6.1

**Comment by jaganathkumar013** [comment] 2018-06-11 09:46
I had installed latest updates.. Still had those issue and tried some lower version..  If needed i can present updated version logs..

**Comment by tiwari-abhishek** [comment] 2018-07-31 17:06
same issue, create new Xamarin Forms Project from project template "Cross-Platform>>Xamarin Forms", with options 'iOS, Android, .net standard'. 
`Error	MSB4062	The "Xamarin.Forms.Build.Tasks.XamlGTask" task could not be loaded from the assembly C:\Users\<id>\.nuget\packages\xamarin.forms\3.1.0.637273\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	RB.Mfa.Authenticator	C:\Users\<id>\.nuget\packages\xamarin.forms\3.1.0.637273\build\netstandard2.0\Xamarin.Forms.targets	84	
`
I tried installing 4.7.2 but it refused to install on Windows 10 so I dont know what else to do.

**Comment by divyesh008** [comment] 2018-11-25 16:48
Just **install the .net 4.7.1 framework**!
