### ISSUE TITLE
iOS Storyboard Launch Screen color issue

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#1750] opened 2018-01-30 19:15 UTC
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Steps to Reproduce

1. Run the attached project.  Note that, though they are defined the same (#ff093254) the launch screen and page appear different colors. 

### Expected Behavior
Color should be the same.

### Actual Behavior
Loading screen is a lighter color.

### Basic Information
Tint is set to clear or desired color

- Affected Devices:
iOS

### Screenshots
![image](https://user-images.githubusercontent.com/1641428/35585994-823cf18e-05c7-11e8-9586-8f26bf8c5dab.png)

### Reproduction Link
[MasterDetailTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1679057/MasterDetailTest.zip)

**Comment by bholmes** [comment] 2018-02-02 21:37
I do see the difference.  However if I manually set the color in the storyboard editor again I feel I get the correct behavior.  The color element of the view in the storyboard file appears to be the important part of this issue.  Can we find out how this storyboard was created?  Was it on Windows.  I was on Mac.  That could be the difference.  

If I edit the text of the storyboard with the following values I feel the colors are the same.


``` xml

<color key="backgroundColor" colorSpace="calibratedRGB" red="0.0392156862745098" green="0.14117647058823529" blue="0.25882352941176473" alpha="1"/>

```

**Comment by ceblanda** [comment] 2018-02-05 21:00
@bholmes, I am using VS2017 on Windows
The color tag you supplied resulted in a color of 9, 49, 84 which is much closer.  But the storyboard editor shows it as #ff0a2442.  How did you calculate the color number?  Why does the editor show something so different?

**Comment by jassmith** [comment] 2018-02-08 18:25
Assigning almcgo as this is not really a forms issue but more of a storyboard issue. I think this is actually expected behavior as iOS supports different colorspaces.

**Comment by alanmcgovern** [comment] 2018-02-08 18:42
This particular issue does look like a mismatched colorspace. We don't currently expose an easy way to alter the colourspace, but it is on the roadmap.

For now can you can open your storyboard in Xcode and access the colorspace selector like this: http://recordit.co/JAVdR1FHjh . If you want things to match you will have to use the same RGB values and the same colorspace for both controls. There is some more information here about handling colorspaces: https://developer.apple.com/ios/human-interface-guidelines/visual-design/color/

**Comment by jassmith** [comment] 2018-02-08 18:43
Closing as invalid

**Closed by jassmith** 2018-02-08 18:43 UTC
Labels: p/iOS, s/needs-info

**Comment by 1iveowl** [comment] 2019-07-05 14:48
I found that the easiest way to fix this was to edit the storyboard with an xml editor. Specifically change `colorSpace="calibratedRGB"` to `colorSpace="custom" customColorSpace="sRGB"`

**Comment by phil-harmoniq** [comment] 2019-07-19 00:15
Why was this closed? There's *still* no convenient way to change the color-space in Xamarin Forms and this seems to be the only documented place where people are talking about this issue.

**Comment by MSiccDev** [comment] 2019-09-16 06:16
Manual editing the Storyboards XML like @1iveowl recommended did the trick for me. I have an extended Splash in Xamarin.Forms where the BackgroundColor were not equal. After the modification, they are.

**Comment by taublast** [comment] 2020-04-21 07:24
Not getting why they have chosen the have calibratedRGB set as default instead of deviceRGB when we are not supposed to change it..
