### ISSUE TITLE
[Bug] XF 4.8 pre2 - fix provided in #11187 - for RECT API throws error - System.InvalidOperationException Message=The BindableProperty "Width" is readonly.

### ISSUE THREAD

**Issue by IoTFier** [xamarin/Xamarin.Forms#11551] opened 2020-07-24 20:59 UTC
### Description
Fix provided in #11187 throws error at runtime.
 
>System.InvalidOperationException
Message=The BindableProperty "Width" is readonly.

### Steps to Reproduce
1.  Upgrade to XF 4.8, pre2
2.  Define a style in a theme xaml file .. say myTheme.Xaml
3.  Define a `<Rect x:Key="TemplateLayoutBounds" Height="22" Width="{x:Static AbsoluteLayout.AutoSize}" X="1" Y="0.5" />`
4. Create a XAML page with label element and assign a absoluteLayout.LayoutBounds using above style
`<Setter Property="AbsoluteLayout.LayoutBounds" Value="{DynamicResource TemplateLayoutBounds}" />`

Please note this was working using struct API Rectangle - up until XF 4.7 pre3. It was broken in XF 4.7 pre4 until now.

### Expected Behavior

Functionality of the Rectangle API up until 4.7 pre3 to be working in XF 4.8 pre2

### Actual Behavior

Fix provided in #11187 is broken

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 16.6.5
- Platform Target Frameworks: 
  - iOS:   13.6
  - Android:  9, 10 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Both Android and iOS

### Workaround

> VS bug [#1162353](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1162353)

**Comment by hartez** [comment] 2020-07-24 23:43
I believe this is addressed in #11548

**Comment by StephaneDelcroix** [comment] 2020-07-25 08:06
Duplicate of #11541

**Comment by StephaneDelcroix** [comment] 2020-07-25 13:14
reopening for the issue outlined at https://github.com/xamarin/Xamarin.Forms/issues/11541#issuecomment-663850850, and rephrasing the content. the original issue (invalid IL) has been fixed

**Comment by StephaneDelcroix** [comment] 2020-07-25 13:17
@IoTFier do you really mean `<Rect x:Key="TemplateLayoutBounds" HeightRequest="22" WidthRequest="{x:Static AbsoluteLayout.AutoSize}" X="1" Y="0.5" />` or should it be `<Rect x:Key="TemplateLayoutBounds" Height="22" Width="{x:Static AbsoluteLayout.AutoSize}" X="1" Y="0.5" />` ??

**Comment by StephaneDelcroix** [comment] 2020-07-25 13:18
LayoutBounds property type should probably be changed to Rect instead of Rectangle

**Comment by IoTFier** [comment] 2020-07-25 18:41
> LayoutBounds property type should probably be changed to Rect instead of Rectangle

I am using `    <Rect x:Key="TemplateLayoutBounds"
          Width="{x:Static AbsoluteLayout.AutoSize}"
          Height="22"
          X="0"
          Y="0.5" />`

The Rectangle struct up until 4.7 pre3 allowed these bindable property to be editable. Now in the new Rect API it is not allowed.

I am going reiterate my request to all XF leadership panel to consider isolating Shapes API in its own namespace.
Who knows what other thing may break out ?

**Comment by StephaneDelcroix** [comment] 2020-07-26 07:06
> The Rectangle struct up until 4.7 pre3 allowed these bindable property to be editable. Now in the new Rect API it is not allowed.

they are no BP, but should be editable (they have a public setter)

> I am going reiterate my request to all XF leadership panel to consider isolating Shapes API in its own namespace.

Thanks for the recommandation, but this ship has sailed (the API has been in a public release). We can still consider moving it out while moving to Maui

**Comment by StephaneDelcroix** [comment] 2020-07-27 09:18
I tried to reproduce your issue with the following XAML:

```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	x:Class="Xamarin.Forms.Xaml.UnitTests.Gh11551">
    <ContentPage.Resources>
	<Rect x:Key="rect" Height="22" Width="{x:Static AbsoluteLayout.AutoSize}" X="1" Y="0.5"/>
    </ContentPage.Resources>
    <Label x:Name="label">
	<Label.Style>
	    <Style TargetType="Label">
		<Setter Property="AbsoluteLayout.LayoutBounds" Value="{DynamicResource rect}"/>
	    </Style>
	</Label.Style>
    </Label>
</ContentPage>
```

The message `the BP Width is readonly` would only happen if you're trying to assign the Width (vs WidthRequest) of a VisualElement (`Shapes.Rectangle` IS a VisualElement).

I suppose you still have some Rect/Rectangle mixups in your code. We understand this comes from a breaking change we introduced, and we're sorry for the inconvenience it causes to you and your project.

I'm going to:
- commit the unit test to avoid reverting that behaviour
- close this issue as I think it's solved.

If you think it's not fixed, please reopen the issue, and attach a reproduction sample we can run.

Thanks

**Closed by StephaneDelcroix** 2020-07-27 09:18 UTC
Labels: a/Xaml </>, a/shapes, t/bug :bug:

**Comment by IoTFier** [comment] 2020-07-28 01:18
Hi @StephaneDelcroix , I guess my bin/obj folders were corrupt. 
Changing XAML similar to the one in your note above has worked for me.

Thank you all for helping me out.

Thank you
