### ISSUE TITLE
[UWP] Grouped items on Listview show white rows 

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#2486] opened 2018-04-17 12:04 UTC
### Steps to Reproduce

1. Open Control gallery
2. Go to issue 53834
3. Check the empty white rows 

### Expected Behavior

Should show grouped list with all rows 

### Actual Behavior

Shows grouped list with empty white rows 

### Basic Information

- Version with issue: 3.0.0

- Platform Target Frameworks: 
   - UWP:   

### Screenshots

<img width="1416" alt="screenshot 2018-04-17 12 54 31" src="https://user-images.githubusercontent.com/1235097/38868577-658abb20-423f-11e8-8a2b-794b20908d75.png">

<img width="446" alt="screenshot 2018-04-17 12 48 58" src="https://user-images.githubusercontent.com/1235097/38868560-5bdc7db6-423f-11e8-9a05-ec230ee0c9e7.png">

**Comment by kingces95** [comment] 2018-05-08 23:45
![image](https://user-images.githubusercontent.com/4120386/39788389-fef436b0-52c5-11e8-8557-3bb8354d63e6.png)
@rmarinho I see this on master. Looks ok.

**Comment by kingces95** [comment] 2018-05-10 23:37
![image](https://user-images.githubusercontent.com/4120386/39899355-2184e78c-5457-11e8-8a45-a5535ecfeefc.png)

Blanks don't always reproduce but this wrapping error does. See group 3 fails to wrap while 4 does wrap. Also, if you poke at properties, like font size, with the visual tree explorer then that seems to cause the bug...

**Comment by jassmith** [comment] 2018-05-11 22:03
This issue is caused by conflicts with the TIL and the UWP ListView implementation. In particular some == checks fails causing the TIL to short circuit when searching for the proper item to re-use. This is trivially fixed by simply not using strings/value types in your ItemsSource and instead wrapping in objects which will not have comparison collisions.

While it is certainly possible to fix this, it is not worth it for the UWP ListView because ListView2 is a-comin and it will not suffer this issue at all.

Therefor anyone suffering this issue today should be able to trivially work around it until ListView2 releases. This further puts priority on the ListView2 work. Chris will be updating our example with the fix to show others how to fix their issues if they have any.

**Closed by jassmith** 2018-05-11 22:03 UTC
Labels: 3.0.0, i/regression, p/UWP, t/bug :bug:

**Comment by paymicro** [comment] 2018-05-29 08:43
This bug is reproduced if the form is redrawn. (on `master` and `3.0.0` branches)
Redrawing can be caused, for example, by dragging an application onto a monitor with a different scale. 
The last group steals the items of the previous group if these items are equal.
Screencast: http://recordit.co/XlFHQyQ89i
