### ISSUE TITLE
Boilerplate style declaration "| NSWindowStyle.Titled" throws

### ISSUE THREAD

**Issue by spouliot** [xamarin/Xamarin.Forms#4286] opened 2018-11-02 14:25 UTC
_From @HarrisonOfTheNorth on November 2, 2018 13:40_

### Steps to Reproduce
The following `AppDelegate` **boilerplate code** throws on `Mac OS X 10.14.0` **Mojave** but not on `Mac OS X 10.13.6` **High Sierra** (as verified by a Xamarin employee as shown on the following link: https://forums.xamarin.com/discussion/comment/353112 ):

`var style = NSWindowStyle.Closable | NSWindowStyle.Resizable | NSWindowStyle.Titled;`

however if I do this:

`var style = NSWindowStyle.Closable | NSWindowStyle.Resizable;// | NSWindowStyle.Titled;`

the MacOS Xamarin Forms app kicks up, albeit without the title bar.

1. Download the demo app (attached) and run it on a Mac with **Mojave** installed.
2. Run the app with the AppDelegate constructor as is and watch the IDE throw.
3. Comment out `| NSWindowStyle.Titled` in AppDelegate's constructor and watch the app run properly.
4. Repeat the same process on a Mac with **High Sierra** installed and the IDE will not throw on the statement `| NSWindowStyle.Titled`.

### Expected Behavior
The following is Xamarin University Boiler-Plate code for the AppDelegate when wiring a Xamarin Forms project into a Mac OS head project:

```
    [Register("AppDelegate")]
    public class AppDelegate : FormsApplicationDelegate
    {
        NSWindow window;

        public override NSWindow MainWindow
        {
            get
            {
                return window;
            }
        }

        public AppDelegate()
        {
            var style = NSWindowStyle.Closable | NSWindowStyle.Resizable | NSWindowStyle.Titled;
            var rect = new CoreGraphics.CGRect(100, 100, 1024, 768);

            window = new NSWindow(rect, style, NSBackingStore.Buffered, false);

            window.Title = "Some Title";
            window.TitleVisibility = NSWindowTitleVisibility.Hidden;
        }

        public override void DidFinishLaunching(NSNotification notification)
        {
            Forms.Init();
            LoadApplication(new App());

            base.DidFinishLaunching(notification);
        }

        public override void WillTerminate(NSNotification notification)
        {
            // Insert code here to tear down your application
        }
    }
```
It is expected that the Xamarin Forms app will display on Mac OS with a title bar at the specified location.

### Actual Behaviour
On `Mac OS X 10.13.6` **High Sierra** the above expected behaviour works however on `Mac OS X 10.14.0` **Mojave** the IDE throws a `System.NullReferenceException (Object reference not set to an instance of an object)` with the following Stack-trace:

``
at Xamarin.Forms.Platform.MacOS.NativeToolbarTracker.UpdateTitle () [0x00125] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.NativeToolbarTracker.UpdateToolBar () [0x0011b] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.NativeToolbarTracker.set_Navigation (Xamarin.Forms.NavigationPage value) [0x0008d] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.NavigationPageRenderer.Init () [0x00025] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.NavigationPageRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0000e] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.MasterDetailPageRenderer.UpdateControllers () [0x00066] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.MasterDetailPageRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0000e] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.Platform.AddChild (Xamarin.Forms.VisualElement view) [0x00027] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.Platform.WillAppear () [0x0001c] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.PlatformRenderer.ViewWillAppear () [0x00006] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(intptr,intptr,intptr)\n  at AppKit.NSWindow.set_ContentViewController (AppKit.NSViewController value) [0x00025] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.0.0.0/src/Xamarin.Mac/AppKit/NSWindow.g.cs:8937 \n  at Xamarin.Forms.Platform.MacOS.FormsApplicationDelegate.UpdateMainPage () [0x00034] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.FormsApplicationDelegate.SetMainPage () [0x00000] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at Xamarin.Forms.Platform.MacOS.FormsApplicationDelegate.DidFinishLaunching (Foundation.NSNotification notification) [0x00041] in <e8fa852365fa4d5399d580ab2b5d60ba>:0 \n  at SMSApp.MacOS.AppDelegate.DidFinishLaunching (Foundation.NSNotification notification) [0x00013] in /Users/Redacted/Downloads/Demo App/SMSApp.MacOS/AppDelegate.cs:37 \n  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])\n  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.0.0.0/src/Xamarin.Mac/AppKit/NSApplication.cs:100 \n  at SMSApp.MacOS.MainClass.Main (System.String[] args) [0x00017] in /Users/Redacted/Downloads/Demo App/SMSApp.MacOS/Main.cs:11
``

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.10 (build 27)
Installation UUID: 8ce29ded-598c-460c-935b-d4823d293212
Runtime:
Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

Package version: 512000309
=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
2.1.2
2.1.1
2.0.5
2.0.0
1.1.2
1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
2.1.302
2.1.301
2.1.4
2.0.0
1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/Redacted/Library/Android/sdk
Supported Android versions:
2.3 (API level 10)
5.0 (API level 21)
5.1 (API level 22)
6.0 (API level 23)
7.0 (API level 24)
7.1 (API level 25)
8.0 (API level 26)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706100027
Git revision: 94dbd4d35daaa5a2ff6a51c3fd5cbb2308bd83ea
Build date: 2018-10-18 16:34:31+00
Build branch: release-7.6
Xamarin extensions: 3a9afc960ba73e5862829e8a0cd9369bcca43d70

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
Wed Aug 22 20:13:40 PDT 2018
root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.12.6
```

### Example Project (If Possible)

[Demo App.zip](https://github.com/xamarin/xamarin-macios/files/2542527/Demo.App.zip)

_Copied from original issue: xamarin/xamarin-macios#5079_

**Comment by StephaneDelcroix** [comment] 2018-11-28 10:48
this looks like a dupe of #3031, fixed in #4086

**Closed by StephaneDelcroix** 2018-11-28 10:48 UTC
Labels: e/4 :clock4:, p/macOS, t/bug :bug:
