### ISSUE TITLE
[Bug] Command is not working in SwipeItem

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#13232] opened 2020-12-26 07:41 UTC
### Description

Command is not working in a SwipeItem.

### Steps to Reproduce

Please download the repro project from https://github.com/xamarin/Xamarin.Forms/issues/13231.

First to validate how it **should** work:
1. Deploy the repro project to an iOS simulator.
2. Once the repro loads press the 'Reload' button once (this is required due to another issue not related to this).
3. Scroll to any message that starts with 'You:', pull left on it to reveal the SwipeView and click the 'Delete' button.
4. This works, the message is deleted (ignore the messages flying around randomly, that is yet another issue unrelated to this).

Now do the following modifications to the repro project:
1. Open `Views/MainPage.xaml`
2. Locate the comment which says `SwipeView command does nothing - hence also a clicked event. Repro SwipeView problem by removing the 'Clicked' property below.`.
3. Delete the line `Clicked="SwipeItem_Clicked"`.
4. Now run the repro project again - the 'Delete' button no longer does anything.

If the SwipeItem is converted to a regular button inside the data template then it works -- so it seems that only SwipeItem Commands do not work. I only tested this on iOS and don't know if the issue also happens on Android.

### Expected Behavior

SwipeItem commands should work.

### Actual Behavior

SwipeItem commands are not invoked at all.

### Basic Information

- Version with issue: 5.0.0-pre6.
- Last known good version: ?
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: ?
  - UWP:  ?
- NuGet Packages: Xamarin.Forms 5.0.0-pre6.
- Affected Devices: iOS devices

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 964)
Installation UUID: f4c2e8d8-481a-4311-847b-759fa99c5218
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.9.0-2.20573.18+bc20ce579f9b17c9153f3f54a0690d23c482d899

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.99.218 (Visual Studio Community)
Commit: xamarin-android/master/9bc0003
Android SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: ac59637
Java.Interop: xamarin/java.interop/master@99897b2
ProGuard: Guardsquare/proguard/v7.0.0@84e8560
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.19
Hash: 9771026
Branch: remotes/origin/HEAD
Build date: 2020-11-21 02:03:08 UTC

=== Android Device Manager ===

Version: 16.9.0.13
Hash: bbbb387
Branch: remotes/origin/main
Build date: 2020-11-21 02:03:28 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.9.0.27 (Visual Studio Community)
Hash: f4c9327fa
Branch: main
Build date: 2020-11-19 10:57:31-0500

=== Xamarin Designer ===

Version: 16.9.0.105
Hash: f693266a2
Branch: remotes/origin/main
Build date: 2020-12-02 05:56:40 UTC

=== Build Information ===

Release ID: 809000964
Git revision: 0ab5ced8f8f39c1837b5879f51401c6fd1ae41ef
Build date: 2020-12-15 08:05:14-05
Build branch: release-8.9
Xamarin extensions: 0ab5ced8f8f39c1837b5879f51401c6fd1ae41ef

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

</details>

### Screenshots

<img width="560" alt="4" src="https://user-images.githubusercontent.com/60286968/103149578-61a5d080-4773-11eb-8ff6-baa76e50efa2.png">

### Reproduction Link

Repro project available at https://github.com/xamarin/Xamarin.Forms/issues/13231, albeit the above step must be performed in it to reproduce the issue.

### Workaround

Use a `Clicked` event on the SwipeItem instead of a `Command`.

**Comment by Tommigun1980** [comment] 2020-12-26 07:44
Ping @jsuarezruiz.

**Comment by hartez** [comment] 2021-01-07 00:01
@Tommigun1980 I'm trying to reproduce this problem, but so far Commands in SwipeItems seems to be working fine for me. Me repro attempt is linked below. 

I can confirm that they aren't running in your project, but there's too much going on in that project to narrow down where your bug might be. Can you tell me if there's some detail I'm missing in my project to reproduce this issue?

[_13232 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5778753/_13232.Repro.zip)

**Comment by Tommigun1980** [comment] 2021-01-08 00:22
> @Tommigun1980 I'm trying to reproduce this problem, but so far Commands in SwipeItems seems to be working fine for me. Me repro attempt is linked below.
> 
> I can confirm that they aren't running in your project, but there's too much going on in that project to narrow down where your bug might be. Can you tell me if there's some detail I'm missing in my project to reproduce this issue?
> 
> [_13232 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5778753/_13232.Repro.zip)

Hi. Commands have never worked for me properly in SwipeViews inside CollectionViews except in non-real-life test cases, hence the repro project. I think Xamarin has to start using more real life test cases (ie have delays, asynchronous data feeding etc) as that’s where it starts to malbehave, while a single button often works.

If I were to guess it looks to me like the SwipeView closes before it registers the command. I also tried adding an additional button inside the data template with a Command and that works, so the SwipeView seems to close itself before it registers the command.

Thanks.

**Comment by Tommigun1980** [comment] 2021-01-09 12:05
@hartez I need to reiterate that the simulated delays etc. are there for a reason -- a simple button works in Xamarin.Forms, but when adding any real-life concepts to it it often stops working. It is very much intentional to have those in the test app, as I can not reproduce a lot of the issues with just a single button.

I honestly think you guys have to start using more involved test cases, and I did my best to make a very very slim repro case that simulates this **real world** usage. If it is not used I don't think Xamarin.Forms will start to stabilise and that puts us all in a very bad place.

Thanks again.

**Comment by Tommigun1980** [comment] 2021-01-09 12:06
@hartez I need to reiterate that the simulated delays etc. are there for a reason -- a simple button works in Xamarin.Forms, but when adding any real-life concepts to it it often stops working. It is very much intentional to have those in the test app, as I can not reproduce a lot of the issues with just a single button.

I honestly think you guys have to start using more involved test cases, and I did my best to make a very very slim repro case that simulates this real world usage. If Xamarin adamantly refuses to simulate real world usage I don't think Xamarin.Forms will start to stabilise and that puts us all in a very bad place.

Thanks again.

**Comment by Tommigun1980** [comment] 2021-01-09 12:08
@hartez I need to reiterate that the simulated delays etc. are there for a reason -- a simple button works in Xamarin.Forms, but when adding any real-life concepts to it it often stops working. It is very much intentional to have those in the test app, as I can not reproduce a lot of the issues with just a single button.

I honestly think you guys have to start using more involved test cases, and I did my best to make a very very slim repro case that simulates this **real world** usage. If Xamarin adamantly refuses to simulate real world usage I don't think Xamarin.Forms will start to stabilise and that puts us all in a very bad place.

So I think the needs-info tag is misleading, I made a repro project simulating real-world usage where SwipeView Commands don't work. You made another repro where they **do** work. I don't know what more I can do at this point??

Thanks again.

**Comment by Tommigun1980** [comment] 2021-01-11 11:02
The process where a customer provides a repro project and a developer makes another repro project where the issue is **not** reproducible, and then asking the customer why it’s not reproducible in the developer’s project... is one I haven’t encountered before tbh.
Isn’t the repro project I provided plenty to debug with and to isolate the issue? I don’t think it’s my responsibility to figure out why it doesn’t happen in **your** repro project attempt.

**Comment by jsuarezruiz** [comment] 2021-01-13 08:03
I can reproduce the issue with the attached sample.
![issue13232](https://user-images.githubusercontent.com/6755973/104423243-20d4f680-557e-11eb-8562-57e4d2e83227.gif)

**Comment by jsuarezruiz** [comment] 2021-01-13 08:11
@Tommigun1980 We highly value all the feedback with issues, discussions, etc. and the attached examples very much for several reasons: we know that they take precious time, help to detect the problem more quickly, etc.
So, we really appreciate all your time and help in making Xamarin.Forms better!.
I'm going to review the issue today.

**Comment by jsuarezruiz** [comment] 2021-01-13 09:12
@Tommigun1980 The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13385

**Comment by Tommigun1980** [comment] 2021-01-13 09:35
> @Tommigun1980 The issue will be fixed by #13385

Great!! Thank you. Closing the issue.

**Comment by jsuarezruiz** [comment] 2021-01-13 12:51
Let's keep it open until the PR is validated and merged, ok?

**Comment by Tommigun1980** [comment] 2021-01-13 13:21
> Let's keep it open until the PR is validated and merged, ok?

Ah sorry! For sure.

**Comment by love8gege** [comment] 2021-04-09 06:36
The issue will be fixed by #13385???    why it have never worked for me properly in SwipeViews even today?  xamarin.forms 5.0.0.2012 now used!

**Comment by sumantdubey** [comment] 2021-07-30 12:13
This is reproducible on Android as well. Am using Xamarin.Forms (5.0.0.2083). In my scenario, the SwipeView is in a CollectionView DataTemplate. SwipeItem's Command is not triggered when bound to a RelativeSource.

**Comment by jfversluis** [comment] 2021-09-02 20:17
@Tommigun1980 @love8gege @sumantdubey, a PR for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by AlleSchonWeg** [comment] 2021-09-03 07:42
Hi @jfversluis ,
i tested the nuget with hope to fix my problem. But it's another problem with SwipeView and Command: https://github.com/xamarin/Xamarin.Forms/issues/13726. PR already exists. Could you create a test nuget for me?
Thank you!

**Comment by sumantdubey** [comment] 2021-09-03 07:53
@jfversluis This seems to have resolved the issue. The binding started working as expected for me. Thanks.

**Closed** 2021-09-03 09:45 UTC
Labels: t/bug :bug:, e/3 :clock3:, in-progress, a/swipeview
