### ISSUE TITLE
Xamarin Forms deploy on MacOS: TypeInitializationException

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10444] opened 2020-04-24 16:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1005741/xamarin-forms-deploy-on-macos-typeinitializationex.html)._

---
### Hi Xamarin-Developers

The Team is currently adding _MacOS_ to the supported platforms of our _shared Xamarin-Application_. We are facing the following error (See also error log in Attachments):

>**System.TypeinitializationException**
>_The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception._

We are using _SignalR_ inside the App to build a _Hubconnection_ to the Backend-Api. But as far as i have seen on the Xamarin.Forms Git-Repo, macOS is now fully working with Xamarin.Forms shared Projects. So how can such an error message arise?

I've seen this issue on Git-Hub. So it could also just be an error with the Json that is currently not working properly on macOS:
[github.com/dotnet/runtime/issues/1460] (https://github.com/dotnet/runtime/issues/1460)

Kind Regards and Thank you very much for the Support
Remo Schaller

---
#### Visual Studio Feedback System on 4/24/2020, 02:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by r3m0s** [comment] 2020-04-29 09:14
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/61869080/80579469-5f377f00-8a0a-11ea-9d29-06fe93d7fce0.png)

**Comment by rmarinho** [comment] 2020-05-18 17:56
@chamons seems this might be a Xamarin.Mac issue about resolving references. Can you help or move to your repo? 

Thanks

**Comment by chamons** [comment] 2020-05-18 18:31
This appears to be a duplicate of https://github.com/xamarin/xamarin-macios/issues/6412 or similar.

This work around may help:

```
If the project uses packages.config, just delete the System.Memory reference from the CSProj. If the project uses PackageReference, then you can add a System.Memory reference and set IncludeAssets="none" (which will supersede any transitive dependency).
```

If you think it's different issue, let me know and I'll move it over. But I'm 90% sure of ^.

**Comment by samhouts** [comment] 2020-05-30 00:06
Duplicate of xamarin/xamarin-macios#6412

**Closed by samhouts** 2020-05-30 00:06 UTC
Labels: p/macOS, s/unverified, t/bug :bug:
