### ISSUE TITLE
[Enhancement] Support Binding to Attached Property

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#10004] opened 2020-03-18 08:06 UTC
## Summary
Support binding to Attached Property like `{Binding Path=(Grid.Row), Source={x:Reference MyElement}}`.

This is supported on WPF XAML and documented on [Binding Declarations Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/binding-declarations-overview?view=netframework-4.8#binding-path-syntax) and [PropertyPath XAML Syntax](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/propertypath-xaml-syntax?view=netframework-4.8#single-property-attached-or-otherwise-type-qualified).

**Comment by AmrAlSayed0** [comment] 2020-03-18 10:08
There was a very old [issue](#1647) opened by @StephaneDelcroix for this. Seems to be completely forgotten now ¯\\_(ツ)_/¯

**Comment by jfversluis** [comment] 2020-03-18 10:09
Thanks @AmrAlSayed0! Let's follow the progress there. If you want that to be implemented, please give it some emoji and comment love. Closing this one as duplicate.

**Comment by jfversluis** [comment] 2020-03-18 10:10
Duplicate of #1647

**Closed by jfversluis** 2020-03-18 10:10 UTC
Labels: a/Xaml </>, a/binding ⛓, proposal-open, t/enhancement ➕
