### ISSUE TITLE
[Bug] CollectionView on Android intermittently fails to display some items after its ItemsSource's ObservableCollection is emptied with Clear() and then replaced with a new ObservableCollection

### ISSUE THREAD

**Issue by hunsra** [xamarin/Xamarin.Forms#15119] opened 2022-02-02 17:25 UTC
### Description

If a CollectionView's ItemsSource property is set to an ObservableCollection object , filled with items, then emptied using ObservableCollection.Clear(), when a new ObservableCollection is assiged to the CollectionView's ItemsSource property, the CollectionView intermittently fails to show some of the first few items in the collection.

### Steps to Reproduce

1. Clone the repo at [https://github.com/hunsra/CollectionViewTest.git](url)
2. Open the CollectionViewTest solution using Visual Studio 2022.
3. Set the Android project as the startup project.
3. Run the Android app on an emulator or real device.
4. When the app appears, tap on the "SHOW ITEMS" button.
5. A new page will be pushed on the navigation stack and random items will be loaded into an ObservableCollection and displayed a CollectionView.  Items are labeled with their item number, starting at 0.
6. Tap the "REFRESH" button in the toolbar.  This will call Clear() on the ObservableCollection, replace the ObservableCollection with a new ObservableCollection, then load it with new random items.
7. When the new items are displayed by the CollectionView, some of the first few items are missing.
8. Scrolling the CollectionView up and down randomly shows some of the missing items.

### Expected Behavior
The CollectionView should show all items in the ObservableCollection.

### Actual Behavior
The CollectionView fails to display some of the first few items in the ObservableCollection.

### Basic Information

- Version with issue: XF 5.0.0.2337
- Last known good version: Unknown
- Platform Target Frameworks: 
  - iOS:  N/A (works as expected on iOS)
  - Android: Android 12.0  
  - UWP:  N/A (not tried)  
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: NETStandardLibrary 2.0.3, Xamarin.CommunityToolkit 2.0.0, Xamarin.Essentials 1.7.1, Xamarin.Forms 5.0.0.2337
- Affected Devices: Tested on Pixel 5 - API 31 emulator and DragonTouch MAX10 hardware device.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Professional 2022
Version 17.0.5
VisualStudio.17.Release/17.0.5+32112.339
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA561
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.5.0+76d4669002
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.343 (d17-0@fb07a17)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.183 (remotes/origin/d17-0@a351f0f1f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9


Xamarin.iOS and Xamarin.Mac SDK   15.4.0.0 (8fc41ae82)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Screenshots

![android2](https://user-images.githubusercontent.com/746214/152203362-2734adef-eda6-4fca-8953-6cfb75808528.gif)

### Reproduction Link

[https://github.com/hunsra/CollectionViewTest.git](url)

### Workaround

Don't call Clear() on ObservableCollection.

**Comment by jfversluis** [comment] 2022-02-02 19:25
Looks like a duplicate of #15097

**Closed by jfversluis** 2022-02-02 19:25 UTC
Labels: t/bug :bug:, s/unverified
