### ISSUE TITLE
ScrollView IsScrollbarVisible

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3731] opened 2018-09-06 16:09 UTC
Hi,

Please add IsScrollbarVisible property to ScrollView.

Thanks,
Jassim

**Comment by pauldipietro** [comment] 2018-09-06 16:14
Duplicate of #1596. In the future, please follow the link provided under the "Proposals" section [here](https://github.com/xamarin/Xamarin.Forms/blob/master/CONTRIBUTING.md) when submitting enhancement requests.

**Closed by pauldipietro** 2018-09-06 16:14 UTC
