### ISSUE TITLE
[Bug] ImageButton not updating when switching from or to dark mode

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8511] opened 2019-11-14 18:52 UTC
### Description
Image in ImageButton is not getting updated when turning on or off dark mode. When we first launch the app the image is displayed correctly (in dark mode the dark version of image is displayed, otherwise normal version of image). However when we turn on dark mode when app is running, the image is not replaced with dark version. The same applies when turning off dark mode.

Everything is working when we replace **ImageButton** with **Image**

### Steps to Reproduce

1. Run the attached project on iOS device or simulator
2. Turn on "dark mode"
3. As you can see human icon is not updated although it has a "dark" version in image assets.

### Expected Behavior
ImageButton source should be updated with "dark" version.

### Actual Behavior
ImageButton source  is not updating.

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: 16.3.9

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3848143/App1.zip)

**Comment by jfversluis** [comment] 2019-11-14 20:05
Just too late! We already got one of these... ;) Please add your findings in the other issue, thanks!

**Comment by jfversluis** [comment] 2019-11-14 20:05
Duplicate of #8495

**Closed by jfversluis** 2019-11-14 20:05 UTC
Labels: s/unverified, t/bug :bug:
