### ISSUE TITLE
[Bug] [iOS] SwipeView cuts 1px upon swiping in CollectionView

### ISSUE THREAD

**Issue by mduchev** [xamarin/Xamarin.Forms#11788] opened 2020-08-14 16:50 UTC
### Description
When in an ItemTemplate of CollectionView, SwipeView cuts 1px upon swiping.

### Steps to Reproduce
1. Create a CollectionView
2. Add some dummy data to it
3. Add SwipeView to its ItemTemplate
4. Add a 1px BoxView at the bottom of the item template.
5. Swipe any row

### Expected Behavior
The swipe will not cut anything from the layout

### Actual Behavior
As soon as the swipe starts, there is 1 px that is being cut from the bottom of the item template.

### Basic Information
- Version with issue: 4.8.0.1269
- Last known good version: N/A
- IDE: Rider for macOS
- Affected Devices: iOS devices

### Screenshots
![Aug-14-2020 19-39-58](https://user-images.githubusercontent.com/8217099/90273130-24e1d880-de67-11ea-855b-08d59571865f.gif)

### Reproduction Link
[DemoSwipeIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5075857/DemoSwipeIssue.zip)

**Comment by rmarinho** [comment] 2020-08-14 17:01
Duplicate of #11764

**Closed** 2020-08-14 17:01 UTC
Labels: s/unverified, t/bug :bug:
