### ISSUE TITLE
Binding with Converter and ConverterParameter is not working at *2.5.1.317207-pre1* in some case on iOS.

### ISSUE THREAD

**Issue by Szymaniuk** [xamarin/Xamarin.Forms#2042] opened 2018-03-07 14:02 UTC
### Description
Binding with Converter and ConverterParameter is not working at *2.5.1.317207-pre1* in some case on iOS.
On Android there is no problem.
The problem occurs only on iOS - working fine at Xamarin Forms 2.5.0.280555, didn't work correctly at Xamarin Forms 2.5.1.317207-pre1.

The "tricky" thing, that is inside **MainPage.xaml** is mainly implemented, because of lack of possibility to **Bind** something directly into **ConverterParameter** - https://forums.xamarin.com/discussion/comment/283081/#Comment_283081

```
<Label x:Name="CustomObjectTypeKey" Text="{Binding CustomObjectType}"/>
<Label Text="{Binding Path=BindingContext.ValueAtWholeVmLevel, Source={x:Reference MainPageView}, Converter={StaticResource MyConverter}, ConverterParameter={x:Reference CustomObjectTypeKey}}"/>
```

So I'm defining **CustomObjectTypeKey** (which actually is hidden for the business needs), and using this **Label.Text** only for the next **Label** at **ConverterParameter** - because no able to do something like:
`<Label Text="{Binding Path=BindingContext.ValueAtWholeVmLevel, Source={x:Reference MainPageView}, Converter={StaticResource MyConverter}, ConverterParameter=**{Binding CustomObjectType}**}"/>`

It's working correctly at different customer views, at different business cases, but starting from **2.5.1.317207-pre1** it's just stops working on iOS - inside **MyConverter**, **hackyBindedKeyLabel.Text** field is NULL only on iOS and only on this XF release.

### Steps to Reproduce

1. Unpack attached **App2.zip** repo
2. Run project on any iOS simulator (by default it's Xamarin Forms 2.5.0.280555)
3. You will see page with ListView with values like:

> _SomeCustomObject 1 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1* **SomeCustomObject 1 - CustomObjectType**
> 
> _SomeCustomObject 2 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1* **SomeCustomObject 2 - CustomObjectType**

4. Update Xamarin Forms nuget to latest pre-release 2.5.1.317207-pre1
5. Run project on any iOS simulator again
6. You will see list with values like:

> _SomeCustomObject 1 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1*
> 
> _SomeCustomObject 2 - CustomObjectType
> ValueAtWholeVmLevel value *hackyBindedKeyLabel.Text* is NULL at iOS at *2.5.1.317207-pre1*

So the **SomeCustomObject X - CustomObjectType** part is missing.

### Basic Information

- Version with issue: 2.5.1.317207-pre1

- Last known good version: 2.5.0.280555
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.1
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms.2.5.1.317207-pre1.nupkg
- Affected Devices:

### Screenshots
**2.5.0.280555 OK:**
![xf_2 5 0 280555](https://user-images.githubusercontent.com/5773539/37096603-6fa87868-2219-11e8-9906-37e1ef0aaf2b.png)

**2.5.1.317207-pre1 NOK:**
![xf_2 5 1 317207-pre1](https://user-images.githubusercontent.com/5773539/37095821-3b6c8d3e-2217-11e8-87d8-519987a4f31d.png)

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/1789319/App2.zip)

**Comment by StephaneDelcroix** [comment] 2018-03-07 19:46
looks like a dupe of #2019

**Comment by Szymaniuk** [comment] 2018-03-08 07:22
@StephaneDelcroix partially could be duplicate - #2019 also occurs on iOS only and also on the same XF version, also inside ListView, but for **Commands** + **CommandParameter** vs for me for **Converter** + **ConverterParameter** .

**Comment by Szymaniuk** [comment] 2018-05-10 13:52
@StephaneDelcroix it's just simply NOT WORKING starting from *2.5.1.317207-pre1* including newest *3.1.0.469394-pre1*, so it's probably something really affected behind.

Please see this issue, attached reproduction project code.

**Comment by StephaneDelcroix** [comment] 2018-05-23 11:50
This has to do with the order in which Bindings are applied, and that order was never guaranteed. It's not really a bug, it's more like if the hack you were relying on no longer works

you can fix this in your code by either:
- subclassing `Label`, adding 2 bindableproperties. bind one to `BindingContext.ValueAtWholeVmLevel`, the other to `CustomObjectType` and when one of the value changes, update the `Label.Text`
- without subclassing, add attachedBindableProperties to your Label, and again do the conversion there

this way, by having 2 bindable properties, you're sure to update the text regardless of the order the the Bindings are updated.

you could also
- add a converter to the first Label, taking the 2nd one as parameter, and update the 2nd label when the first one changes. This is a bit more dirty, but will be faster to implement given the code you already have.

**Closed by StephaneDelcroix** 2018-05-23 11:50 UTC
Labels: s/invalid
