### ISSUE TITLE
error building application

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11846] opened 2020-08-19 14:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1144288/error-building-application.html)._

---
<p>I am upgrading room vs 2012 to VS 2019. In porting my appication from on environment to the other. When rebuilding the entire application I get the error message </p><p>error XF004: XF requires . NETFramework &gt;= v4.6.1. You have 'v4.5'</p><p>I have .Net version 4.8 installed on my system.</p> <p>Why am I getting this error messgae? What do I have to do to be able to run my application in VS 2019?</p>

---
#### Feedback Bot on 8/11/2020, 01:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 8/11/2020, 11:15 PM: 

<p>Dear customer, thank you for your feedback and taking the time to reach out to us.<br>
Please close the VS 2019 and run the installer as administrator, click More-Modify and go to ‘Individual components’, make sure the .NET Framework 4.6.1 SDK, the .NET Framework 4.6.1 targeting pack and other targeting pack are installed, if not, please select them to install.</p>

#### microsoft sucks on 8/12/2020, 00:08 PM: 

<p>I did this and the error persists. I installed all .Net versions that are availiable. To NO avail.</p>

#### Feedback Bot on 8/13/2020, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-08-20 17:20
What type of project are you using for your shared Xamarin.Forms code? I suspect you're not using netstandard. Are you able to share the project with us? Thanks!

**Comment by jsuarezruiz** [comment] 2020-08-28 09:34
I can compile and execute the App without problems (although when starting I get an error related to the database).

<img width="2140" alt="Captura de pantalla 2020-08-28 a las 11 31 08" src="https://user-images.githubusercontent.com/6755973/91546089-3c6a9800-e922-11ea-8fd9-d66c78b338fd.png">

Do you have the .NET 4.5 compatibility pack installed? (look at the previous screenshot)

I hope it helps, if you have more questions as it is a Windows Forms App, we can move the issue to https://github.com/dotnet/winforms/issues

**Comment by taffybear** [comment] 2020-08-28 19:55
It is good to hear that you were able to compile and run the program
without issues. However my issue does not appear to be resolved. I still
cannot do the same.

Can you tell me what " .NET 4.5 compatibility pack" is. This is not listed
as an option to be installed in the installer. Maybe this is the
difference  between its names in English and Spanish.

How can I move this to another Github area? This problem was moved to
Github by Samantha Hout. I have not used Github to hold my source code.

Art.

**Comment by samhouts** [comment] 2020-09-15 00:21
@taffybear I have reopened the original feedback ticket and moved this to the WinForms team. I'll close this issue, since the problem is not related to Xamarin.Forms. Thanks!

**Closed by samhouts** 2020-09-15 00:21 UTC
Labels: a/buildchain, external-components, feedback-ticket, s/needs-info ❓, s/unverified, t/bug :bug:
