### ISSUE TITLE
Basic functionality - Cut/Copy paste using keys is not working in Xamarin.Mac using Xamarin Forms

### ISSUE THREAD

**Issue by fazil1987** [xamarin/Xamarin.Forms#3181] opened 2018-06-29 06:04 UTC
### Description
Cut/Copy/Paste functionality using keys is not working in Xamarin Mac app built using Xamarin Forms

### Steps to Reproduce

1. Create a hello world Xamarin.Mac app
2. Integrate with Xamarin Forms 
3. Add entry to the main page of Xamarin Forms
4. Run the application
5. Enter some text in Entry 
6. Select the text and press cmd+x or cmd+c

### Expected Behavior
1. If its cmd+x, it should remove the text and copy it to the clipboard
2.  If its cmd+c, it should  not remove the text but just copy it to the clipboard

### Actual Behavior
1. In both the cases, nothing is happening ( neither removing nor getting copied ) 

Note : 
1. This is the case even for pasting text in to the entry. 
2. But all these actions works well, If I right click and perform the actions via mouse.

### Basic Information

- Version with issue: 3.0.0.446417
- Last known good version:
- IDE: Visual studio for mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jvansickle** [comment] 2018-07-03 00:50
Duplicate of #1988 which should be resolved by PR #3202

**Comment by hartez** [comment] 2018-07-06 14:38
Closing as duplicate of #1988.

**Closed by hartez** 2018-07-06 14:38 UTC
Labels: p/macOS, t/enhancement ➕
