### ISSUE TITLE
FocusChanged was called multiple time when we typing in ListView EditText Android

### ISSUE THREAD

**Issue by Chozarajan** [xamarin/Xamarin.Forms#4830] opened 2018-12-20 10:19 UTC
### Description

In list view last row if we type focus the EditText, the focus changed was called multiple time. It's also no problem. If I type any letter the focus changed was called again and again in EditText.

### Steps to Reproduce

1. Run the attached sample
2. Set BreakPoint in FocusChanged method
3. Now Focus the row number 12 EditText in Android
4. If we type any letter the focus changed was called multiple time

### Expected Behavior
If we type any character the focus changed was called multiple time

### Actual Behavior
We have not changed the focus when typing, so focus changed event was never called in typing

### Basic Information

- Version with issue: In all Xamarin Forms versions the issue reproduced
- Last known good version: -
- IDE: VS 17
- Platform Target Frameworks: 
  - Android: API version 7.1 

- Android Support Library Version: None
- Nuget Packages: None
- Affected Devices: Moto G5 

### Screenshots and Videos

Video Link: 
[IssueVideo.zip](https://github.com/xamarin/Xamarin.Forms/files/2698380/IssueVideo.zip)

### Reproduction Link

Sample Link: 
[IssueSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2698412/IssueSample.zip)

**Comment by kingces95** [comment] 2018-12-21 22:31
We do not generally debug custom renderers and instead prefer to file an issue enhancement to add the functionality the prompted the need to create a custom renderer so that the wider community can benefit from the change. Could you elaborate on what functionality is missing? Simply capturing when the view focus changes? 

That said, if you debug the issue and submit a PR we will review that.

**Comment by Chozarajan** [comment] 2018-12-26 05:53
Use case is to format the text based on Focus changes.
Ex:
In focus mode, the text is in **0**. In unfocus mode, the text was formatted and it is in **0.00** 

 It's working fine in normal cases. Inside the ListView bottom items, if we set the formatted text, the focus change was called again and again. Can you provide an alternative solution to overcome this issue? 

Root cause: If we type or set the text in ListView bottom item the focus changed was called again and again.

**Comment by samhouts** [comment] 2019-02-05 20:22
Duplicate of #1600

**Closed by samhouts** 2019-02-05 20:22 UTC
Labels: p/Android, t/enhancement ➕
