### ISSUE TITLE
[Bug] Web View Navigated Event does not work

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#10598] opened 2020-05-07 10:14 UTC
### Description
I want to show a loading indicator until the web view loads.
So I selected OnNavigated event and Onnavigating event.

Onnavigated works but OnNavigated does not trigger.

### Steps to Reproduce

1. Add webView
2. Use custom webView renderer to invoke java scripts
3. Set url on View's constructor to the web view
4. run the app

### Expected Behavior
Trigger the Navigated event after navigating event finished

### Actual Behavior
Triggers navigating event
But does not trigger navigate event

### Basic Information

- Version with issue: 
- Last known good version: N/A
- IDE: VS 2019 Community 16.5.4
- Platform Target Frameworks: 
  - iOS:  13
  - Android: Oreo

- Android Support Library Version: 28
- Nuget Packages:  
Xamarin.Forms:  4.6*
- Affected Devices: Android and iOS Simulators

`public class HybridWebViewRenderer : WebViewRenderer
    {
        private const string JavascriptFunction = "function invokeCSharpAction(data){jsBridge.invokeAction(data);}";
        Context _context;

        public HybridWebViewRenderer(Context context) : base(context)
        {
            _context = context;
        }

        protected override void OnElementChanged(ElementChangedEventArgs<WebView> e)
        {
            try
            {
                base.OnElementChanged(e);

                if (e.OldElement != null)
                {
                    Control.RemoveJavascriptInterface("jsBridge");
                    ((HybridWebView)Element).Cleanup();
                }
                if (e.NewElement != null)
                {
                    Control.SetWebViewClient(new JavascriptWebViewClient($"javascript: {JavascriptFunction}"));
                    Control.AddJavascriptInterface(new JsBridge(this), "jsBridge");
                    //// No need this since we're loading dynamically generated HTML content
                    //Control.LoadUrl($@"file:///android_asset/Content/{((HybridWebView)Element).Uri}");
                    Control.SetBackgroundColor(Android.Graphics.Color.Transparent);

                    Control.Settings.SetEnableSmoothTransition(true);
                    Control.Settings.UseWideViewPort = true;

                    bool isScrollEnabled = false;
                    Control.VerticalScrollBarEnabled = isScrollEnabled;
                    Control.Touch += (senderr, touch) =>
                    {
                        if (!isScrollEnabled)
                        {
                            touch.Handled = touch.Event.Action == MotionEventActions.Move;
                        }
                        else
                        {
                            touch.Handled = false;
                        }
                    };

                }
            }
            catch (Exception ex)
            {
                ExceptionHandler.LogException(ex);
            }            
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            try
            {
                base.OnElementPropertyChanged(sender, e);
                if (Control != null)
                {
                    if (e.PropertyName == nameof(IsFocused))
                    {
                        ((HybridWebView)Element).Unfocus();
                        MessagingCenter.Send<string>(MobileSharedVariables.MsgCenter_SelectedDBodyPartsFromWebView, MobileSharedVariables.MsgCenter_SelectedDBodyPartsFromWebView_Msg);
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

    }`

`public class JavascriptWebViewClient : WebViewClient
    {
        readonly string _javascript;

        public JavascriptWebViewClient(string javascript)
        {
            _javascript = javascript;
        }

        public override void OnPageFinished(WebView view, string url)
        {
            base.OnPageFinished(view, url);
            view.EvaluateJavascript(_javascript, null);
        }
    }`

`public class JsBridge : Java.Lang.Object
    {
        readonly WeakReference<HybridWebViewRenderer> HybridWebViewMainRenderer;

        public JsBridge(HybridWebViewRenderer hybridRenderer)
        {
            HybridWebViewMainRenderer = new WeakReference<HybridWebViewRenderer>(hybridRenderer);
        }

        [JavascriptInterface]
        [Export("invokeAction")]
        public void InvokeAction(string data)
        {
            if (HybridWebViewMainRenderer != null && HybridWebViewMainRenderer.TryGetTarget(out var hybridRenderer))
            {
                ((HybridWebView)hybridRenderer.Element).InvokeAction(data);
            }
        }`

`public class HybridWebView : WebView
    {
        private Action<string> _action;

        public void RegisterAction(Action<string> callback)
        {
            _action = callback;
        }

        public void Cleanup()
        {
            _action = null;
        }

        public void InvokeAction(string data)
        {
            if (_action == null || data == null)
            {
                return;
            }
            _action.Invoke(data);
        }
    }`

**Comment by kgbuddhima** [comment] 2020-05-07 12:15
@jsuarezruiz  @pauldipietro  I could solve it . here is my code now

`public class JavascriptWebViewClient : WebViewClient
    {
        readonly string _javascript;
        HybridWebViewRenderer _renderer;

        public JavascriptWebViewClient(string javascript, HybridWebViewRenderer renderer)
        {
            _javascript = javascript;
            _renderer = renderer;
        }

        public override void OnPageFinished(Android.Webkit.WebView view, string url)
        {
            
            base.OnPageFinished(view, url);
            view.EvaluateJavascript(_javascript, null);

            var source = new UrlWebViewSource { Url = url };
            var args = new WebNavigatedEventArgs(WebNavigationEvent.NewPage, source, url, WebNavigationResult.Success);
            _renderer.ElementController.SendNavigated(args);
        }
    }`

https://forums.xamarin.com/discussion/138821/navigating-on-android-webview-doesnt-always-fire

**Comment by vividos** [comment] 2020-05-16 13:09
This may be the same bug as my issue #10688 (which got closed due to being a duplicate of #10350).

**Comment by rmarinho** [comment] 2020-05-21 14:09
Hi, does this work without the Custom WebView ? 

Do you mind provide a small reproduction example?! 

is this a issue on Android and iOS? or just Android ? 

Thanks

**Comment by vividos** [comment] 2020-05-21 17:25
@rmarinho you could see some steps to reproduce the behavior in my issue #10688

**Comment by PureWeen** [comment] 2020-05-21 23:13
Closing as a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/10350 for now

**Closed by PureWeen** 2020-05-21 23:13 UTC
Labels: a/webview, p/Android, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
