### ISSUE TITLE
[Bug] Android Scrollview vertical Scrollbar is never visible.

### ISSUE THREAD

**Issue by BasileusBasileon** [xamarin/Xamarin.Forms#7569] opened 2019-09-18 10:44 UTC
### Description

On Android, the vertical scrollbar on a Scrollview will never be visible.

### Steps to Reproduce

1. Create a blank Xamarin Forms project with Android.
2. Install any Xamarin Forms version from 3.5.0.129452 onwards.
3. Add a situation where you scroll a Scrollview vertically.

Alternatively, run the attached project.

### Expected Behavior

The vertical Scrollbar of the Scrollview is visible according to the VerticalScrollBarVisibility.

### Actual Behavior

The vertical Scollbar of the Scrollview is never visible.

### Basic Information

- Version with issue: Any version from 3.5.0.129452 onwards
- Last known good version: 3.4.0.1039999
- IDE: Visual Studio 2017 Version 15.9.15
- Platform Target Frameworks:
  - Android: Android 8.1 (Oreo)
- Android Support Library Version: Tested on 27.0.2.1 and 28.0.0.1

### Screenshots
Pre 3.5.0.129452:
![Working](https://user-images.githubusercontent.com/54933586/65141518-16016480-da11-11e9-97d3-ffe61176cf1a.jpg)

3.5.0129452 and onwards:
![Bugged](https://user-images.githubusercontent.com/54933586/65141527-1b5eaf00-da11-11e9-89c0-25861b5a3d3d.jpg)

### Reproduction Link

Repro project:
[MissingScrollbar.zip](https://github.com/xamarin/Xamarin.Forms/files/3625899/MissingScrollbar.zip)

**Comment by samhouts** [comment] 2019-09-18 18:23
Same as https://github.com/xamarin/Xamarin.Forms/issues/7574?

**Comment by BasileusBasileon** [comment] 2019-09-18 18:29
> 
> 
> Same as #7574?

It appears to be the same, yes.

**Comment by samhouts** [comment] 2019-09-18 18:40
I'm going to mark this one as a duplicate, even though it's older, because the other issue has some information about the possible root cause. Thanks!!!

**Comment by samhouts** [comment] 2019-09-18 18:40
Duplicate of #7574

**Closed by samhouts** 2019-09-18 18:40 UTC
Labels: i/regression, p/Android, s/unverified, t/bug :bug:
