### ISSUE TITLE
Regression - Android - Exception thrown during NavigationPage.Navigation.PopAsync

### ISSUE THREAD

**Issue by aquisio** [xamarin/Xamarin.Forms#2837] opened 2018-05-26 06:11 UTC
I am seeing an `ArgumentOutOfRangeException` when executing PopAsync after inserting a page into the navigation stack, which seems to be a regression of [this issue](https://bugzilla.xamarin.com/show_bug.cgi?id=53179) and may be related to #2576 .

The issue can be reproduced by adding a single empty page to an empty template project and then including the following code in an async OnStart() implementation:

```
	var nav = (NavigationPage) MainPage;
	nav.Navigation.InsertPageBefore(new SecondPage(), nav.CurrentPage);
	await nav.Navigation.PopAsync(false);
```

This issue only affects Android projects using Material Design (FormsAppCompatActivity).

- Version with issue: All Xamarin.Forms versions from v2.5.1.444934 onwards
- Last known good version: v2.5.0.280555
- IDE: VS2017 v15.7.1
- Android Target Framework: 7.1, 8.0, 8.1
- Android Support Library Version: v25.4.0.2 and v27.0.2

[StackTrace.txt](https://github.com/xamarin/Xamarin.Forms/files/2041384/StackTrace.txt)
[BugRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/2041385/BugRepro.zip)

**Comment by matteopiccioni** [comment] 2018-05-29 15:02
I seriously believe that this situation is not acceptable...new and old bugs appear with each new release.
When the fix will be released?

**Comment by opcodewriter** [comment] 2018-06-15 08:48
I hope this time unit tests are implemented, so that any further regression gets caught by CI

**Comment by rmarinho** [comment] 2018-06-15 15:06
Hi @opcodewriter that's for your feedback it's hard to unit test platform code, the interation, time on device etc make it super hard. We do write UI Test, and i wrote one in my fix, that's how i found out this seems to be a issue also in iOS :)

**Closed** 2018-06-16 00:01 UTC
Labels: i/critical, i/regression, p/Android, t/bug :bug:

**Comment by jefffhaynes** [comment] 2018-12-31 17:07
This is happening for me as of 3.4.0.1008975

**Comment by kwacks** [comment] 2019-03-13 01:14
@jefffhaynes 
Did you find a workaround to this issue or open another issue? I'm having the same issue - unable to pop after autonavigating  in onAppearing
