### ISSUE TITLE
[Bug][iOS] MediaElement throws ArgumentException in some circumstances

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#9566] opened 2020-02-13 15:09 UTC
### Description

`MediaElement` throws an `ArgumentException` on iOS when rapidly, repeatedly changing the `Source` to different videos.

I've only managed to repro this once on iOS 13.3, but it repros more frequently on 12.2.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the second page in the list (Select Web Video).
3. Select a video. Immediately select another video. Keep on doing this. 

### Expected Behavior

No crashes.

### Actual Behavior

`ArgumentException` with the message: TimeSpan does not accept floating point Not-a-Number values.

Sometimes the crash occurs after 6 selections. Sometimes 12. Sometimes 20. It's difficult to repro.

### Basic Information

- Version with issue: 4.5-pre4
- IDE: VS Mac 8.4.5
- Platform Target Frameworks: 
  - iOS:  12.2

### Screenshots

![Screenshot 2020-02-13 at 15 04 19](https://user-images.githubusercontent.com/8092460/74448126-5a831600-4e72-11ea-97c0-061bd438c092.png)

### Reproduction Link

[WorkingWithMediaElement.zip](https://github.com/xamarin/Xamarin.Forms/files/4198446/WorkingWithMediaElement.zip)

**Comment by samhouts** [comment] 2020-02-13 18:11
Probably the same code causing #9568

**Comment by samhouts** [comment] 2020-02-13 18:11
Duplicate of #9568

**Closed by samhouts** 2020-02-13 18:11 UTC
Labels: a/mediaelement, e/1 :clock1:, i/high, p/iOS 🍎, t/bug :bug:
