### ISSUE TITLE
[Accesibility tags] are not working within any WebView after visual studio 2019 update 

### ISSUE THREAD

**Issue by pamela032709** [xamarin/Xamarin.Forms#6985] opened 2019-07-26 14:10 UTC
### Description
After visual studio update of Xamarin forms , accessibility tags are not working on voice over. WebViews stop working , voice over is not reading anything there. 
This is critical I need to know why stopped working and what can I do to fix this bug.

### Steps to Reproduce

1. Create a new Xamarin Forms Project IOS/ANDROID using the latest NETStandars 2.0
2. Create a WebView 
3. Mainpage.xaml 

    <WebView Source="https://twitter.com" AutomationProperties.IsInAccessibleTree="true" AutomationProperties.HelpText="Tap to toggle the activity indicator" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"></WebView>

<WebView Source="https://twitter.com" AutomationProperties.IsInAccessibleTree="true"        AutomationProperties.HelpText="Tap to toggle the activity indicator" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"></WebView>
4.Activate voice over 
### Expected Behavior
It needs to read any content presented on the screen. 
### Actual Behavior
accesibility tags are not working and voice over is not reading anything . just empty.
### Basic Information
This is very serious , since even before the tags voice over still read WebView contents and after this late update . voice over is failing to read any content on iOS and android. 
- Version with issue:
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.1.5 (build 9)
Installation UUID: 7692fd6e-5645-498f-b996-0c7a5632bf5c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Enterprise)
Commit: HEAD/d0b48056f
Android SDK: /Users/compriop/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/compriop/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 3.8.9

- Last known good version:
- IDE: previous visual studio version to that one I described
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Iphones xr , max , 7 and 8 
Samgung galaxy s10 , s8, s9
### Screenshots

This is vital , I reported this 3 weeks ago and still not answer . 
### Reproduction Link
Please doit yourself , is pretty basic and I added the steps above

**Comment by pamela032709** [comment] 2019-07-26 14:14
Please add this to your MainPage .xaml 
<WebView Source="https://twitter.com" AutomationProperties.IsInAccessibleTree="true"        AutomationProperties.HelpText="Tap to toggle the activity indicator" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"></WebView>

**Comment by samhouts** [comment] 2019-07-26 15:56
Duplicate of #6894

**Closed by samhouts** 2019-07-26 15:56 UTC
Labels: s/unverified, t/bug :bug:
