### ISSUE TITLE
[Android] ListView crashing when updating items just before observable collection operations

### ISSUE THREAD

**Issue by PenguinPero** [xamarin/Xamarin.Forms#5778] opened 2019-04-01 14:53 UTC
### Description
ListView crashes with the following exception:

```
List`1[T].get_Item (System.Int32 index)
IList.get_Item (System.Int32 index)
ListProxy+<>c__DisplayClass36_1.<TryGetValue>b__0 () D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:259
ListProxy.TryGetValue (System.Int32 index, System.Object& value) D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:266
ListProxy.get_Item (System.Int32 index) D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:126
IList.get_Item (System.Int32 index) D:\a\1\s\Xamarin.Forms.Core\ListProxy.cs:444
```
When sorting bound ObservableCollection (multiple Move calls) right after item updating.

```csharp
public void Sort(Comparison<TData> comparison)
{
     var sortedList = new List<TData>(Items);
     sortedList.Sort(comparison);

     for (int i = 0; i < sortedList.Count; i++)
         Move(IndexOf(sortedList[i]), i);
}
```
Or when deleting items from ObservableCollection, right after item updating.

But it is not consistent, it does not happen every time.
Also only happening on Android.

### Steps to Reproduce

1. Create ListView with item template
2. Bind ItemsSource to ObservableCollection
3. Update some item (which implements INotifyPropertyChanged and is bound to item template)
4. Do some ObservableCollection operations like, Delete/Move right after

### Expected Behavior
Not crashing

### Actual Behavior
Crashing

### Basic Information

- Version with issue:
3.5.0.169047

**Comment by samhouts** [comment] 2019-04-01 17:48
@PenguinPero Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by PenguinPero** [comment] 2019-04-02 08:06
I will produce a small project as soon as I can, I am a bit busy at this time, this is happening on the ongoing project I am working on

But I managed to decrease the possibility of this bug by minimizing the amounts of update+sort events sent to UI (didn't happen again after this)
And maybe the issue is with sort -> update, not update -> sort, but not sure yet

**Comment by samhouts** [comment] 2019-04-02 17:39
Great, we'll keep an eye out for the sample project. Thanks!!

**Comment by PenguinPero** [comment] 2019-04-02 20:42
here is the reproduction:
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3035828/ListViewBug.zip)

while creating this reproduction project I realized this might be an issue on our side
when ran on UI thread everything seems to be working, when ran on background thread app crashes after few seconds of running

still I will leave this here, if anyone ever experiences this issue

my solution, considering that I am using IEventAggregator of Prism and events that only notify UI,
will probably be an extension method for PubSubEvent and PubSubEvent<T>which will call Publish on UI thread :)

**Comment by samhouts** [comment] 2019-04-06 01:00
Interesting. If I strip out Prism, it doesn't crash either way.

**Comment by PenguinPero** [comment] 2019-04-06 11:36
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3050414/ListViewBug.zip)
For me it is still failing when stripping out Prism, I attached the new repro project

I suppose this has something to do with INotifyPropertyChanged notification of item and CollectionChanged notifications from collection (maybe if sent from background thread xamarin will internally try to switch these operations required by notifications to UI thread and there could be race conditions? I don't know how this works)

And I don't even know if it is supposed to work from background thread, but since you are still looking into it I suppose it should?

**Comment by samhouts** [comment] 2019-04-08 23:57
Yeah, I can see where it throws that exception now. The problem is that the backing list is changing faster than the callback that tries to populate the ItemsSource can access the items. It's so fast, though, that by the time my debugger hits it, the list is in the proper state.

We could try to implement some retry logic in the Xamarin.Forms code, but I'm not sure that's the right call. It feels like your app should be in charge of throttling the data changes. 

If I set your Delay to 100ms, it doesn't crash anymore, so I think you can get away with implementing a small delay between syncs. Or you could put it on the main thread, which effectively does the same thing, but that might be overkill.

**Comment by samhouts** [comment] 2019-04-09 00:16
I'm going to close this issue for now, but feel free to make a case for us making a change here. We're open to suggestions! Thanks!

**Closed by samhouts** 2019-04-09 00:16 UTC
Labels: a/listview, p/Android, t/bug :bug:
