### ISSUE TITLE
Entry in ListView with DataTemplateSelector refocused after scrolled back onto screen

### ISSUE THREAD

**Issue by HarkerTech** [xamarin/Xamarin.Forms#5076] opened 2019-01-27 22:13 UTC
### Description
On Android, if a DataTemplateSelector is used with a custom ViewCell containing an Entry, the entry will refocus itself after being unfocused and scrolled off and back onto the screen. This will occur to any cell that has had focus previously, and the most recently scrolled onto screen will have the focus.

Issue does not occur when editors are used in place of entries.

### Steps to Reproduce

1. Run attached sample
2. Set focus to an entry
3. Remove focus from the entry (via back button or other method)
4. Scroll previously focused cell off screen
5. Scroll cell back onto screen
6. Entry will have regained focus (without soft input)

### Expected Behavior
Entries in ViewCells do not gain focus after being unfocused

### Actual Behavior
Entry in ViewCell gains focus when scrolled back onto screen after unfocused

### Basic Information

- Version with issue: Xamarin.Forms 3.2.0.839982, Xamarin.Forms 3.5.0.94564-pre3
- Last known good version: Xamarin.Forms 3.1.0.697729
- IDE: Visual Studio for Mac 7.7.3 (Build 43)
- Platform Target Frameworks:
  - Android: API version 9.0
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices: Samsung S9 (API 26), Android 4.4 simulator (API 19)

### Reproduction Link

[ListViewEntryFocusReproduction.zip (custom renderer removed)](https://github.com/xamarin/Xamarin.Forms/files/2806239/ListViewEntryFocusReproduction.zip)

**Comment by kingces95** [comment] 2019-01-28 21:53
We don't typically debug custom renderers. They "void the warrenty" if you will. We will however review PR requests to fix an issue in core that prevents a custom renderer from working. 

Can you reproduce the issue without a custom renderer? When I revert back to the normal renderer it seems to work. 

Is a feature you'd like us to add to the existing renderers that drove you to implement a custom renderer? If so, please elaborate and we'll add it to the backlog.

**Comment by HarkerTech** [comment] 2019-01-29 05:41
Thanks for taking a look at this.

The custom Entry renderer in the reproduction provided was an accidental leftover from when I was debugging/attempting to find a workaround. The ticket description now contains a fresh reproduction case without the customer renderer. I have been able to reproduce the issue in this updated case.

**Comment by samhouts** [comment] 2019-02-05 20:14
Duplicate of #1600

**Closed by samhouts** 2019-02-05 20:14 UTC
Labels: t/bug :bug:

**Comment by HarkerTech** [comment] 2019-02-23 04:38
I have taken a look at the linked ticket and believe it is for a different issue. It has a "Last known good version" of unknown whereas this issue was introduced in Xamarin.Forms v3.2.0. 

From my investigation this appears to have been introduced in https://github.com/xamarin/Xamarin.Forms/pull/3402. My current theory for the cause is the call to "if (Control.RequestFocus())" in the constructor. Now that IsReadOnly has been added to the Entry, this has changed to "if (!Element.IsReadOnly && Control.RequestFocus())". As a result of this change I have been able to create a custom renderer to work around this issue for the latest Xamarin versions containing the IsReadOnly Entry changes.

```
var isReadOnly = Element.IsReadOnly;
if (!Element.IsFocused && Control != null)
    Element.IsReadOnly = true;

base.OnElementChanged(e);

if (Control != null)
    Element.IsReadOnly = isReadOnly;
```

**Comment by maxbromo** [comment] 2019-07-06 14:05
> I have taken a look at the linked ticket and believe it is for a different issue. It has a "Last known good version" of unknown whereas this issue was introduced in Xamarin.Forms v3.2.0.
> 
> From my investigation this appears to have been introduced in #3402. My current theory for the cause is the call to "if (Control.RequestFocus())" in the constructor. Now that IsReadOnly has been added to the Entry, this has changed to "if (!Element.IsReadOnly && Control.RequestFocus())". As a result of this change I have been able to create a custom renderer to work around this issue for the latest Xamarin versions containing the IsReadOnly Entry changes.

Very nice HarkerTech, thanks for saving me a lot of hassle with this idea!

**Comment by nbevans** [comment] 2022-07-15 09:36
> var isReadOnly = Element.IsReadOnly;
> if (!Element.IsFocused && Control != null)
>     Element.IsReadOnly = true;
> 
> base.OnElementChanged(e);
> 
> if (Control != null)
>     Element.IsReadOnly = isReadOnly;

This doesn't fix it.

**Comment by nbevans** [comment] 2022-07-15 10:47
```csharp
public sealed class MyEntryRenderer : EntryRenderer {
        // Hack fix for ListView superfluous multiple Entry focus bug - Main body implementation (start)

        // See bug: https://github.com/xamarin/Xamarin.Forms/issues/5076
        // When these Entry fields are present in a ListView and the user has interacted (focused) many of them at some point, and then
        // they scroll the ListView down and up, the Xamarin Forms erroneously (and superfluously) focuses the re-instantiated Entry fields.
        // This means the screen enters into a bizarre state where multiple Entry fields are selected/focused/cursor-flashing concurrently
        // which is obviously not a valid state of any UI.
        // To workaround this bug in XF, we make use the IsReadOnly property and set this to true when the Entry is being initialised.
        // After initialisation is completed, we reset the IsReadOnly property to whatever it was set to beforehand.
        // We need to listen for the property change event and swallow it to prevent NRE's in certain cases.
        private bool _initializingHackFixForListViewSuperfluousMultipleEntryFocusBug;

        private bool? HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementChanged_Setup(ElementChangedEventArgs<Entry> e) {
            _initializingHackFixForListViewSuperfluousMultipleEntryFocusBug = true;
            bool? isReadOnly = null;
            if (e.NewElement != null) {
                isReadOnly = e.NewElement.IsReadOnly;
                e.NewElement.IsReadOnly = true;
            }
            return isReadOnly;
        }

        private void HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementChanged_Teardown(ElementChangedEventArgs<Entry> e, bool? isReadOnly) {
            _initializingHackFixForListViewSuperfluousMultipleEntryFocusBug = false;
            if (e.NewElement != null && isReadOnly.HasValue) {
                e.NewElement.IsReadOnly = isReadOnly.Value;
            }
        }

        private bool HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementPropertyChanged_Handler(object sender, PropertyChangedEventArgs e) {
            return e.PropertyName == Entry.IsReadOnlyProperty.PropertyName && _initializingHackFixForListViewSuperfluousMultipleEntryFocusBug;
        }
        // Hack fix for ListView superfluous multiple Entry focus bug - Main body implementation (end)

        public MyEntryRenderer(DroidContext context) : base (context) { }

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e) {
            // Hack fix for ListView superfluous multiple Entry focus bug - Part 1 of 3
            var state_HackFixForListViewSuperfluousMultipleEntryFocusBug = HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementChanged_Setup(e);
            base.OnElementChanged(e);
            // Hack fix for ListView superfluous multiple Entry focus bug - Part 2 of 3
            HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementChanged_Teardown(e, state_HackFixForListViewSuperfluousMultipleEntryFocusBug);
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e) {
            if (e.PropertyName == /* your other property change handlers here */) { }
            // Hack fix for ListView superfluous multiple Entry focus bug - Part 3 of 3
            else if (HackFixForListViewSuperfluousMultipleEntryFocusBug_OnElementPropertyChanged_Handler(sender, e)) { /* swallow */ }
            else
                base.OnElementPropertyChanged(sender, e);
        }
    }
```

**Comment by nbevans** [comment] 2022-07-15 11:04
@samhouts Please see above workaround. This bug is indeed caused by the way the Entry calls RequestFocus in the UpdateCursorSelection method when initialising. It seems that when these changes were implemented there was no consideration given to how it might work when Entry's are used in a ListView.

My workaround (which is based on @HarkerTech idea) will disable the RequestFocus behaviour when initialising by enabling the IsReadOnly mode and then reverting it after initialisation is completed. The only downside to this is that when scrolling the ListView substantially, the focused Entry will be lost. But this is a small price to pay compared to a totally broken UI with multiple flashing cursor carets, e.g.:

![image](https://user-images.githubusercontent.com/542188/179210545-a9ca703a-d3f5-4e27-a599-dc6b50024841.png)
