### ISSUE TITLE
[Android] Navigation dont wait initial pages to be loaded on AppCompat

### ISSUE THREAD

**Issue by kvpt** [xamarin/Xamarin.Forms#4729] opened 2018-12-13 23:09 UTC
### Description
If you want to navigate to another page in the OnStart method, auto login for exemple, and if you navigate to fast, the page will load before the MainPage and will be wipped by the MainPage loaded after.
The state of the navigation stack will be inconsistant and it will cause differents issues or crash like IndexOutOfRange.

The FormsApplicationActivity works as excepted.

### Steps to Reproduce

1. Create an Xamarin Forms Android from the template
2. In App class set a NavigationPage as MainPage
2. In the OnStart method push a new page
await Current.MainPage.Navigation.PushAsync(new Page { Title = "New" });
3. Launch application

### Expected Behavior
The page displayed is the page loaded in OnStart
And if you go back it's your MainPage

### Actual Behavior
The page displayed is the original page and the page loaded in OnStart is "phantom", if you press go back it throw an IndexOutOfRangeException.

**Comment by hartez** [comment] 2019-01-14 23:53
@kvpt If I open your repro and make these changes to `NavigationPageRenderer.OnAttachedToWindow()`, I get an `ArgumentOutOfRangeException`.

**Comment by kvpt** [comment] 2019-01-17 00:09
@hartez I fixed it, you can review it again.

**Comment by samhouts** [comment] 2019-04-08 21:54
Duplicate of #3528

**Closed by samhouts** 2019-04-08 21:54 UTC
Labels: p/Android, t/bug :bug:
