### ISSUE TITLE
Errors on Build related to XamlGTask

### ISSUE THREAD

**Issue by Osmosis311** [xamarin/Xamarin.Forms#2975] opened 2018-06-08 00:46 UTC
When I try to build my XF project, I intermittently get two errors.  If I try to rebuild over and over, they _sometimes_ go away and I'm able to build.

Visual Studio Mac 7.5.2 (Build 40)
Xamarin.Forms 3.0.0.550146 or 3.1.0.469394-pre1 (happens on both)

Here are the two errors:

/Users/<redacted>/Projects/MemberApp/packages/Xamarin.Forms.3.1.0.469394-pre1/build/netstandard2.0/Xamarin.Forms.targets(4,4): Error MSB4064: The "OutputPath" parameter is not supported by the "XamlGTask" task. Verify the parameter exists on the task, and it is a settable public instance property. (MSB4064) (MemberApp.Droid)

/Users/<redacted>/Projects/MemberApp/packages/Xamarin.Forms.3.1.0.469394-pre1/build/netstandard2.0/Xamarin.Forms.targets(3,3): Error MSB4063: The "XamlGTask" task could not be initialized with its input parameters.  (MSB4063) (MemberApp.Droid)

**Comment by adrianknight89** [comment] 2018-06-08 01:48
I'm getting these exact errors consistently when I use VS 2017 (15.7.3) for Windows. My workaround is to delete all bin & obj folders and rebuild solution. I think VS is locking a dll somewhere in a debug folder. Cleaning the solution does not delete these folders (tsk tsk VS), so I created a batch file to delete them.

```
FOR /F "tokens=*" %%G IN ('DIR /B /AD /S bin') DO RMDIR /S /Q "%%G"
FOR /F "tokens=*" %%G IN ('DIR /B /AD /S obj') DO RMDIR /S /Q "%%G"
```

Source: https://stackoverflow.com/a/755433

**Comment by jassmith** [comment] 2018-06-08 23:38
I can't reproduce the issue but I believe this is a locking issue

**Comment by StephaneDelcroix** [comment] 2018-06-09 19:31
XamlG parameter (including OutputPath) were changed in one of the -sr for 3.0.0.
The error reported indicate that the .targets file you're using is not of the same version of the build.tasks.dll currently loaded in the appdomain of msbuild.
To fix that:
- make sure ALL of your project targets the same version of the XF nuget
- when you switch XF version in a project, make sure you clean the solution and restart the IDE

If that doesn't help, please report back.

@jassmith unlikely to be a locking issue

**Comment by Asnanon** [comment] 2018-06-13 12:21
I was able to solve the issue after updating all XF nugets to the same version. 
I was building an iOS build, but apparently there were problems with the outdated XF Nuget Package for Android the solution. 
Closing the IDE and then afterwards cleaning the solution made it possible to complete builds again.

Worrisome is just, that it was building just fine several minutes before it started throwing errors, with the only changes being done in one xaml file between builds.

**Closed** 2018-06-14 14:34 UTC
Labels: a/Xaml </>, s/needs-info, t/bug :bug:

**Comment by tudor06** [comment] 2018-09-21 08:43
The issue reappeared - sadly! 
XAMLFiles parameter is not supported by XAMLGTask task. 
I have updated all the XF nuget packages, cleaned obj/bin, restarted VS -> to no avail. 

Please help!
PS: @Asnanon : Same behaviour here, it built a couple of minutes earlier and then started throwing errors. Very worrisome, as I had the false impression I am in control of what happens in terms of updates.

**Comment by mikkeljohnsen** [comment] 2018-10-04 18:30
I'm so sick and tired of this error. When will it be fixed ?
You can change and delete and do all kinds of changes and suddenly it works, but after doing something like adding a Nuget or something else it reappears.

**Comment by D4rkC1own187** [comment] 2018-10-08 18:20
I have the same issue. I have done the above solution and none of them work. I've loyal to XF but all these bug is making it hard to keep using XF. I'm starting to lean towards RN.

**Comment by StephaneDelcroix** [comment] 2018-10-08 18:26
Thanks for the feedback and comments. you should really share your projects that has the issue so we can investigate.

**Comment by wlangendorf** [comment] 2018-10-19 20:57
I've also had a similar experience (mobile project was previously working, suddenly begins to show this error, ensuring that all projects were targetting same XF nuget and deleting all obj and bin directories did not resolve).  

For those presently stuck by this issue:  I have 'fixed' things by commenting out the Target with name of 'XamlG' and 'XamlC' in Xamarin.Forms.Targets.  This lets me build/debug, but I have no doubt it will bite me soon enough.

**Comment by Screech129** [comment] 2018-10-25 20:47
Not sure why this is closed. This is still occurring on Visual Studio for Mac with Xamarin forms  3.3.0.912540 and I don't see a real solution.

**Comment by Eliottiosdevs** [comment] 2018-10-27 07:02
+1 @Screech129

**Comment by Screech129** [comment] 2018-10-27 12:39
So turns out my issue was I had accidentally added a xamarin forms nuget to my core project that didn't contain forms. Hope this helps someone.

**Comment by aquisio** [comment] 2018-10-28 10:34
I'm still seeing this with Visual Studio for Mac v7.6.10 and XF v3.3.0.912540. Very frustrating.

**Comment by wickedw** [comment] 2018-12-05 12:08
I am getting this now after upgrading to XCode 10.1 and latest VS over the weekend.
Previous VS I did not see this.

I had some success yesterday with deleting bin / obj and restarting, but now I seem to be completely jammed this morning, cannot get the droid project to run at all.

Visual Studio Community 2017 for Mac
Version 7.7 (build 1868)
Installation UUID: 6644ddea-b0f9-4b5d-bded-9635a62586be
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.7.0.5148

Could someone advise how I can send more information / open a bug report to help diagnose this?

Thanks

**Comment by yunustunahan** [comment] 2018-12-17 17:08
I had the same issue: XAMLFiles parameter is not supported by XAMLGTask task.
I was using Azure Build Pipeline. After spending several hours I discovered that the issue was being caused by a third party nuget package which was depended on an old version of Xamarin Forms.
I removed the package and the issue resolved.

**Comment by ahmedmehanna** [comment] 2020-03-18 17:20
I had the same issue, I was using Azure Build Pipeline. It's was working locally anyway.
After spending several hours I discovered that not all projects has the same versions of Xamarin Forms
### Solution
You need to check Consolidate tab 
The main solution (Right click) -> Manage NuGet Packages for solution -> Consolidate
Install similar version of Nuget package to all projects

![image](https://user-images.githubusercontent.com/966313/76988064-1638d900-693c-11ea-91be-5b591bd50f6c.png)

**Comment by godboutj** [comment] 2021-05-03 15:01
This is still happening with AppCenter Build, local build seem to be working just fine:
```
/Users/runner/.nuget/packages/xamarin.forms/4.8.0.1821/buildTransitive/Xamarin.Forms.targets(93,4): error MSB4064: The "References" parameter is not supported by the "XamlGTask" task. Verify the parameter exists on the task, and it is a settable public instance property. [/Users/runner/work/1/s/MyApp/MyApp/MyApp.csproj]
  /Users/runner/.nuget/packages/xamarin.forms/4.8.0.1821/buildTransitive/Xamarin.Forms.targets(89,3): error MSB4063: The "XamlGTask" task could not be initialized with its input parameters.  [/Users/runner/work/1/s/MyApp/MyApp/MyApp.csproj]

```
The Xamarin.Forms have been consolidate already (the solution nuget management doesn't report any package with mismatch version).

Everything is up to date (except Prism which we are still using version 6.x). The error is bad because it mask the true problem and we cannot known what is really happening or bothering the build. I don't known why this is close, but a real error for the actual problem would be required to truly fix this issue. It's a huge time waster. I still haven't figure out why it does that this time around.

**Comment by godboutj** [comment] 2021-05-03 15:05
To remove the bin and obj folder under Mac OS, create a script removeBinObj.sh:
```
#!/bin/sh
find . -iname "bin" -o -iname "obj" | xargs rm -rf
```
dont' forget to add the executable flag:
```
chmod +x removeBinObj.sh
```

**Comment by mikkelAtVisma** [comment] 2021-06-17 12:26
@godboutj does your script fix the issue, or?

**Comment by godboutj** [comment] 2021-06-17 13:11
> @godboutj does your script fix the issue, or?

Seem like the VS build can be corrupted some how, cleaning the build folders, fix the issues for me. Fixing different Xamarin.Forms version and then cleaning the build/obj folders and rebuild fix that obscure error.

Same as @adrianknight89  fix but for Mac OS

**Comment by mikkelAtVisma** [comment] 2021-06-18 08:39
Alright, thanks!
