### ISSUE TITLE
[Bug] Binding in ListViews does not work

### ISSUE THREAD

**Issue by Gionson13** [xamarin/Xamarin.Forms#10962] opened 2020-06-04 20:00 UTC
### Description

I'm trying to have a list with items in it but when I show the list i only see the outline of the item but not the content, I tried using hardcoded data and it works so it is the binding that does not work

### Steps to Reproduce

**MainPage.xaml**
```xaml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="MaProject.MainPage">

	 <ListView x:Name="ExercisesList">
		<ListView.ItemTemplate>
			<DataTemplate>
				<TextCell Text="{Binding Name}" Detail="{Binding Detail}"/>
			</DataTemplate>
		</ListView.ItemTemplate>
	</ListView>

</ContentPage>
```

**MainPage.xaml.cs**
```c#
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace MyProject
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MainPage : ContentPage
    {

        private ObservableCollection<Item> items;

        public MainPage()
        {
            InitializeComponent();

            items= new ObservableCollection<Item>();

            ExercisesList.ItemsSource = items;

        }

        private void AddItem(object sender, Item item)
        {
            items.Add(item);
        }
    }
}
```

**Item.cs**
```c#
public class Item : INotifyPropertyChanged
{
        public event PropertyChangedEventHandler PropertyChanged;

        private string detail;
        private string name;

        public string Name
        {
            get { return date; }
            set { SetValue(ref name, value); }
        } 
        public string Detail
        {
            get { return time; }
            set { SetValue(ref detail, value); }
        }

        private void SetValue<T>(ref T backingField, T value, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(backingField, value))
                return;

            backingField = value;

            OnPropertyChanged(propertyName);
        }

        private void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
}
```

### Expected Behavior

Show a list item with a name and some details

### Actual Behavior

show the item but without any information, only the outline

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  10.0
  - Android: 9.0
- Nuget Packages:
  - Newtonsoft.Json
  - sqlite-net-pcl
  - Rg,Plugkîns.Popup
  - Acr,UserDialogs 
### Screenshots

[Screenshot](https://i.ibb.co/v1Jdq76/Screenshot-20200604-213724.jpg)

**Comment by jsuarezruiz** [comment] 2020-06-05 09:09
@Gionson13 I have created a sample using your code:
[Issue10962.zip](https://github.com/xamarin/Xamarin.Forms/files/4735031/Issue10962.zip)

I have made some small changes (for example the property assignment was not correct using a `date` and `time` variable etc).

Tested with Xamarin.Forms 4.4, 4.5 and 4.6:

![Screenshot_1591348016](https://user-images.githubusercontent.com/6755973/83858570-ffc14300-a71c-11ea-8650-44d93e3d4df6.png)

Works fine in all the versions. Could you take a look to the sample?.

**Comment by endwindows07** [comment] 2020-06-08 04:29
I have same your problem. Now i'm can solve it!.
You try this. 
<img width="954" alt="Screen Shot 2563-06-08 at 11 26 00" src="https://user-images.githubusercontent.com/22784672/83992665-44e2b080-a97b-11ea-921d-eaaf0f013447.png">

**Comment by samhouts** [comment] 2020-06-08 22:31
You can also preserve code from the linker specifically so you can still take advantage of the compression benefits. 

Android: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#preserving-code

iOS: https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker

**Comment by jefffhaynes** [comment] 2020-06-15 23:55
I believe I have this same issue in something that was previously working.  I can't tell yet what is responsible for the regression but it does appear to be related to binding.

**Comment by PureWeen** [comment] 2020-06-15 23:58
@jefffhaynes if you try @samhouts suggestion https://github.com/xamarin/Xamarin.Forms/issues/10962#issuecomment-640921711 does that fix? If not can you attach a repro?

**Comment by jefffhaynes** [comment] 2020-06-16 00:06
Turning off linking doesn't appear to fix it if that's what you mean.  I'm trying to come up with a simple example that will repo.

**Comment by PureWeen** [comment] 2020-06-16 00:08
@jefffhaynes 

Specifically this code
https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos#preserving-code

**Comment by jefffhaynes** [comment] 2020-06-16 00:09
I understand the code but that is simply an optimization if you want to turn on linking.  I also don't know which code would need to be preserved since I don't know what the issue is :)

**Comment by jefffhaynes** [comment] 2020-06-16 00:31
Sorry, my issue turned out to be unrelated to this.  Disregard.

**Comment by samhouts** [comment] 2020-06-18 17:11
Okay! I think I'll close this, since this seems to be an issue with configuration, not a bug. Thanks!

**Closed by samhouts** 2020-06-18 17:11 UTC
Labels: a/binding ⛓, a/listview, linker, s/needs-repro ❔, s/unverified, t/bug :bug:
