### ISSUE TITLE
[Bug] iOS Failed to marshal the Objective-C object HeaderWrapperView

### ISSUE THREAD

**Issue by krisurnok** [xamarin/Xamarin.Forms#11807] opened 2020-08-17 04:25 UTC
https://github.com/xamarin/Xamarin.Forms/issues/9711

This bug is not closed reproduced in Xamarin Forms v4.8

- Version with issue:
- Last known good version:
- IDE: Visual Studio MAC
- Platform Target Frameworks: Xamarin.Forms 4.8
  - iOS:  13.5

**Comment by jsuarezruiz** [comment] 2020-08-24 12:23
@krisurnok Do you mean this sample?
[HeaderWrapperView.zip](https://github.com/xamarin/Xamarin.Forms/files/5117710/HeaderWrapperView.zip)

Cannot reproduce the issue using Xamarin.Forms.4.8. Could you try it?

<img width="327" alt="Captura de pantalla 2020-08-24 a las 14 23 29" src="https://user-images.githubusercontent.com/6755973/91044333-687dd480-e615-11ea-82fe-13555e841979.png">

**Comment by krisurnok** [comment] 2020-08-24 13:18
@jsuarezruiz 
I have not used the above sample.
I have given below the stack trace of Crash from my application.
Component: **ListView** IsGroupingEnabled="True"

**ERROR:**
Failed to marshal the Objective-C object 0x7fa8c901f690 (type: Xamarin_Forms_Platform_iOS_HeaderWrapperView). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Xamarin.Forms.Platform.iOS.HeaderWrapperView' does not have a constructor that takes one IntPtr argument)

**Trace:**
at ObjCRuntime.Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution) [0x00039] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1100 \n
at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x00024] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1129 \n  
at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x000d1] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1274 \n  
at UIKit.UIView.get_Superview () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIView.g.cs:4800 \n  
at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].UpdateParentPageAccessibilityElements () [0x0001a] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs:548 \n  
at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0015f] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs:427 \n  
at Xamarin.Forms.Platform.iOS.ViewRenderer`2[TView,TNativeView].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x000aa] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\ViewRenderer.cs:163 \n  
at FFImageLoading.Forms.Platform.CachedImageRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00000] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Forms.Touch\\CachedImageRenderer.cs:143 \n  
at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)\n  
at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs:229 \n  
at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Core\\Element.cs:353 \n  
at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs:461 \n  
at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs:397 \n  
at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x00214] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindingExpression.cs:155 \n  at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindingExpression.cs:53 \n  
at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindingExpression.cs:742 \n  
at Xamarin.Forms.BindingExpression+BindingExpressionPart.PropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args) [0x000cb] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindingExpression.cs:753 \n  
at Xamarin.Forms.BindingExpression+WeakPropertyChangedProxy.OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00012] in D:\\a\\1\\s\\Xamarin.Forms.Core\\BindingExpression.cs:646 \n  
at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)\n  
at TEST.Model.ClassName.OnPropertyChanged (System.String propertyName) [0x00000] in /mobileapp/Core/Model/ClassModel.cs:289 \n  
at TEST.Model.ClassName.SetProperty[T] (T& backingStore, T value, System.String propertyName, System.Action onChanged, System.Func`3[T1,T2,TResult] validateValue) [0x0004f] in /mobileapp/Core/Model/ClassModel.cs:279 \n  
at TEST.Model.ClassName.set_boolProp (System.Boolean value) [0x00001] in /mobileapp/Core/Model/ClassModel.cs:306 \n  
at TEST.ViewModel.ClassViewModel+<>c__DisplayClass21_0.<.ctor>b__0 (System.Object id) [0x000f8] in /mobileapp/Core/ViewModel/ClassViewModel.cs:136 \n  
at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Core\\Command.cs:112 \n  
at Xamarin.Forms.TapGestureRecognizer.SendTapped (Xamarin.Forms.View sender) [0x00018] in D:\\a\\1\\s\\Xamarin.Forms.Core\\TapGestureRecognizer.cs:44 \n  
at Xamarin.Forms.Platform.iOS.EventTracker+<>c__DisplayClass14_0.<CreateRecognizerHandler>b__0 (UIKit.UITapGestureRecognizer sender) [0x0008f] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\EventTracker.cs:203 \n  
at UIKit.UITapGestureRecognizer+Callback.Activated (UIKit.UITapGestureRecognizer sender) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIGestureRecognizer.cs:223 \n  
at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  
at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86 \n  
at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65 \n  
at TEST.iOS.Application.Main (System.String[] args) [0x00001] in /mobileapp/iOS/Main.cs:17

**Comment by hartez** [comment] 2020-09-02 13:53
@krisurnok Can you provide a repro which demonstrates the issue? Or at least show us the code/markup for your CollectionView so that we can see what's different between yours and the one in the original bug report?

**Comment by avatar2012** [comment] 2020-09-17 12:02
I found that although the missing constructor is only missing in the official nuget package when using the nuget package installer.

Investigating Xamarin.Forms.Platform.iOS.dll it was clear that in the official build only one ctor was implemented:

(disassembled by IL DASM)
.method public hidebysig specialname rtspecialname 
        instance void  .ctor(string reuseIdentifier) cil managed
{
  // Code size       13 (0xd)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldarg.1
  IL_0002:  call       class [Xamarin.iOS]Foundation.NSString [Xamarin.iOS]Foundation.NSString::op_Explicit(string)
  IL_0007:  call       instance void [Xamarin.iOS]UIKit.UITableViewHeaderFooterView::.ctor(class [Xamarin.iOS]Foundation.NSString)
  IL_000c:  ret
} // end of method HeaderWrapperView::.ctor

Location: Xamarin.Forms-master\Xamarin.Forms.Platform.iOS\Renderers
File: ListViewRenderer.cs

Code from github:
`class HeaderWrapperView : UITableViewHeaderFooterView
	{
		public HeaderWrapperView(string reuseIdentifier) : base((NSString)reuseIdentifier)
		{
		}

                // Note: this constructor is missing in default nuget package build but available in current github sources
		public HeaderWrapperView(IntPtr handle) : base(handle)
		{
		}`

What helped me was build the nugat package manual from the sources and installing it directly on iOS or Windows by using the custom build nuget.

**Comment by PureWeen** [comment] 2020-09-18 16:52
@avatar2012 we don't add those constructors because they only are used when there's a memory leak and an already disposed of class is trying to be accessed again.

**Comment by avatar2012** [comment] 2020-09-18 17:01
The constructor is already within the official sources. Xamarin forms is used widely in b2b applications and I cannot recommend keep an unwanted issue within a stable release. However this is not what I expect and since the last 10 years it goes more whorse from my personal perspective.

**Comment by PureWeen** [comment] 2020-10-28 23:58
@avatar2012 can you address @hartez 's question please?

https://github.com/xamarin/Xamarin.Forms/issues/11807#issuecomment-685752727

It's hard to narrow this one down without some additional information

**Comment by avatar2012** [comment] 2020-10-29 08:06
I cannot give you an example how to run into this issue but as I wrote fixing it by build the package from original github sources 4.8, does add the missing constructor overload although it is already available in the sources.

I figured out that compared the dll assemblies from nugget repository does not contain the code which confuses.

I want point out that I didn't modify the sources except I build it locally. 

When you read my previous post you see a screenshot from the assemblies opened il disassembled.

**Comment by rmarinho** [comment] 2020-11-02 12:02
What nuget  are you ? what version of Forms?

**Comment by avatar2012** [comment] 2020-11-11 06:53
The Nuggets with Version 4.8 has the issue, missing cto overload discribed  

The github sources v5.0 has the constructor included and no issue build a custom package from this sources

**Comment by PureWeen** [comment] 2020-12-11 04:41
With a repro @avatar2012 @krisurnok I'm not sure if we'll be able to do much here to figure this one out. Can you try moving to CollectionView to see if you have the issue there?

Looking at your stack trace I also see FFImageLoading in there so maybe FFImageLoading is doing something that's causing this? There are a few too many players in your stack trace for us to narrow this one down

If you are building the sources yourself to add that constructor you can breakpoint the constructor and when it gets called follow the stack trace up to see if you can figure out why that constructor is getting called and why something is leaking

**Comment by Redth** [comment] 2021-01-21 14:42
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by Redth** 2021-01-21 14:42 UTC
Labels: a/listview, p/iOS 🍎, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
