### ISSUE TITLE
[Bug] [UWP] PushAsync after PopModalAsync raises unexpected OnDisappearing event

### ISSUE THREAD

**Issue by fragmer** [xamarin/Xamarin.Forms#7483] opened 2019-09-11 23:54 UTC
### Description
We have a [UWP Forms app](https://github.com/Esri/arcgis-runtime-samples-dotnet/tree/master/src/Forms) with NavigationPage as the main page. App shows a modal "loading" page before navigating to certain child pages. We noticed that OnDisappearing event fires unexpectedly on freshly-appeared child pages.

I noticed that unexpected OnDisappearing event is invoked via NavigationPageRenderer.OnUnloaded, so this issue might have a similar fix to https://github.com/xamarin/Xamarin.Forms/issues/1602 @hartez

### Steps to Reproduce
1. PushModal a page ("ModalPage")
2. PopModal
3. Push a different page ("ChildPage")
4. An unexpected OnDisappearing event will fire on ChildPage.

### Expected Behavior
Expected sequence of events is (approximately):
1. MainPage OnAppearing
2. ModalPage OnAppearing
3. MainPage OnDisappearing
4. ModalPage OnDisappearing
5. ChildPage OnAppearing

### Actual Behavior
Actual sequence of events:
1. MainPage OnAppearing
2. ChildPage OnAppearing
3. **ChildPage OnDisappearing**
4. MainPage OnDisappearing

### Workaround
Adding a brief delay (e.g. `await Task.Delay(100)`) between PushModal and PopModal works around the problem, and causes events to happen as expected.

### Basic Information
- Version with issue: 4.1.x, 4.2.x
- Last known good version: N/A
- IDE: VisualStudio 2019 Update 2
- Platform Target Frameworks:
  - UWP: 16299 (SDK 6.1.x and 6.2.x)

### Reproduction Link
Complete reproducer: https://github.com/fragmer/XFOnDisappearingRepro

My App.cs:
```cs
 MainPage = new NavigationPage(new MainPage());
```

My MainPage:
```cs
        public MainPage()
        {
            var button = new Button { Text = "Go to child page" };
            button.Clicked += Button_OnClicked;

            Content = new StackLayout
            {
                Children = { button }
            };
        }

        private async void Button_OnClicked(object sender, EventArgs e)
        {
            await Navigation.PushModalAsync(new ModalPage(), false);
            // await Task.Delay(100); // Uncomment to test a workaround
            await Navigation.PopModalAsync(false);
            await Navigation.PushAsync(new ChildPage(), true);
        }
```

**Comment by PureWeen** [comment] 2019-10-04 01:03
I'm going to close this one as a duplicate of this one
https://github.com/xamarin/Xamarin.Forms/issues/6919

**Closed by PureWeen** 2019-10-04 01:03 UTC
Labels: p/UWP, s/unverified, t/bug :bug:
