### ISSUE TITLE
[Bug] CollectionView + Expander: Expanding one item makes every other X item expand too

### ISSUE THREAD

**Issue by ericlira** [xamarin/Xamarin.Forms#10993] opened 2020-06-09 14:23 UTC
### Description
Expanding a item inside a CollectionView makes every X number of item to expand too. 

Doing some tests I could identify the problem is not Expander itself but CollectionView because I tested using the same layout with Syncfusion expander and the same problem happens, however replacing the CollectionView by a ListView with default caching strategy works fine, but changing ListView caching strategy to RecycleElement or RecycleElementAndDataTemplate causes the same issue as the CollectionView.

PS.: Test done only on Android. I haven't tried the same code on iOS.
### Steps to Reproduce

1. Download attached code 
2. Run on a Android device or simulator
3. Expand any item then scroll down until you see other item expanded. Keep scrolling and you will see other item expanded after the same number of items.

### Expected Behavior
Only tapped item to be expanded

### Actual Behavior
Every X number of items expanded

### Basic Information

- Version with issue: 4.6 and above
- Last known good version: none
- IDE: VS Community 2019 
- Platform Target Frameworks: 
  - Android: 10.0  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: 

### Screenshots
![collectionview+expander](https://user-images.githubusercontent.com/22410658/84159404-609ba300-aab0-11ea-8f28-7a7f288ca859.gif)

### Reproduction Link
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/4752693/Test.zip)

**Comment by hartez** [comment] 2020-06-12 14:26
This is a duplicate of #9200.

**Comment by hartez** [comment] 2020-06-14 21:26
@ericlira 



You need to maintain the `IsExpanded` property's state somewhere in your bound data. For example, you could update your `CollectionItem` class to:

```
public class CollectionItem
{
	public string Name { get; set; }
	public string Description { get; set; }
	public bool Expanded { get; set; }
}
```

and in your DataTemplate, bind the `IsExpanded` property to the value of `Expanded`:

```
	<Expander Padding="10" IsExpanded="{Binding Expanded}">
```

For a more detailed explanation, see https://github.com/xamarin/Xamarin.Forms/issues/9200#issuecomment-643822589

**Closed by hartez** 2020-06-14 21:26 UTC
Labels: a/collectionview, e/5 :clock5:, t/bug :bug:

**Comment by ericlira** [comment] 2020-06-14 23:19
@hartez Thanks for the explanation. Reading #9200 it all makes sense!

**Comment by amiraelsayedbadwy** [comment] 2020-07-04 00:33
ios still has this issue when press on expander a space between items in collection view appear 
![expander](https://user-images.githubusercontent.com/10218465/86501990-a17c9400-bd9e-11ea-810c-9bf4d87748d3.PNG)

**Comment by jonkas2211** [comment] 2020-08-11 14:53
Hallo @hartez,
do you have any suggestion on how do update the expanded state?
Maybe in the view, when the item leaves the screen?

**Comment by hartez** [comment] 2020-08-24 20:59
> ios still has this issue when press on expander a space between items in collection view appear
> ![expander](https://user-images.githubusercontent.com/10218465/86501990-a17c9400-bd9e-11ea-810c-9bf4d87748d3.PNG)
> @hartez

@amiraelsayedbadwy If you're still experiencing this problem please open a new issue and we will take a look. Thanks!

**Comment by SwingsetTheory** [comment] 2020-12-19 09:56
Having this problem too, can't use expander if there's no way around it. Am storing expanded state in the bound item as suggested, doesn't work.
