### ISSUE TITLE
Xamarin HotRestart fails to respond to collectionview's item tapped event

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15042] opened 2022-01-10 17:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-HotRestart-fails-to-respond-to-c/1625308)._

---
[severity:It's more difficult to complete my work]
Xamarin HotRestart fails to to respond to collectionview's item tapped event.

Visual Studio Community 2022, Version 17.0.4
WIndows 10 20H2
Dell XPS desktop 
IPad using IOS 15.2

I created the default project that Visual Studio creates when choosing Mobile App (Xamarin Forms) and accepted all of the defaults. I added NO code of my own. I used an Android emulator created by Visual Studio (Pixel 5 API 28). I connected an IPad which Visual Studio auto provisioned using my Apple development account.
Step 1: Everything worked fine in the Android emulator (About, Add, Logout, Browse, ItemDetails). For IOS, everything worked except selecting an item to get item details. For IOS, selecting an item to get item details did not generate any type of response.
Step 2: Using the debugger, in the ItemsViewModel, I placed breakpoints in both the 'get' & the 'set' of the SelectedItem property. I also placed a breakpoint in the OnItemSelected(Item item) method.

When I ran the Android project: Tapping 'Browse' hits the breakpoint in the 'set' in the viewmodel's SelectedItem property and then hits the breakpoint in the OnItemSelected(Item item) method.
Tapping an item in the CollectionView hits the breakpoint in the viewmodel's OnItemSelected(Item item) method.

When I ran the IOS project: Tapping 'Browse' hits the breakpoint in the 'set' in the viewmodel's SelectedItem property and then hits the breakpoint in the OnItemSelected(Item item) method (as expected).
Tapping an item in the CollectionView does not hit the breakpoint in the viewmodel's OnItemSelected(), nor does it generate any type of response.

---
#### Feedback Bot on 12/29/2021, 10:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Steven Scearce on 1/4/2022, 00:56 PM: 

<p>Still hoping for an update. Please let me know if you need any more information from me.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2022-01-11 10:37
Looks like a duplicate of #14956

**Closed by jfversluis** 2022-01-11 10:37 UTC
