### ISSUE TITLE
[Question] Is it possible to hide a FlyoutItem ?

### ISSUE THREAD

**Issue by TechWatching** [xamarin/Xamarin.Forms#6701] opened 2019-06-28 08:57 UTC
### Description
I am using Xamarin Forms Shell and I want to be able to hide some items of my Flyout depending on some parameters (the current page for instance) but I can't find any method or property to change the visibility of a FlyoutItem.

Is it possible to programmaticaly hide some FlyoutItem (not the complete Flyout just some items) ?

### Expected Behavior
When I navigate to a page, the flyout / menu is still available but with less items on it as navigation to some other pages or executing some commands (from MenuItems) should not be available for this page

### Actual Behavior
The flyout is the same for all pages, I can only choose to display it or not depending on the page.

**Comment by samhouts** [comment] 2019-06-28 17:21
Duplicate of #5232

**Closed by samhouts** 2019-06-28 17:21 UTC
Labels: s/unverified, t/bug :bug:
