### ISSUE TITLE
[Bug] Xamarin Forms crashes on startup after multiple starts after update xamarin 4.4.0.991265

### ISSUE THREAD

**Issue by Swdvader** [xamarin/Xamarin.Forms#8900] opened 2019-12-16 03:59 UTC
### Description
App closing on startup on or before splash screen.  App works fine in prior version. No changes made.
----------What I did.
        Updated xamarin forms to 4.4.0.991265.   App compiled and ran fine.   After entering the app several times, the app closed on splash screen startup and then after that app message app keeps closing.   Its closing on splash screen.  It worked a few times when first deployed.  Then I seen where It dropped to the background process,  The app closes on the splash screen and disappears. I found it using the show apps there and clicked on it.  Then I keep getting message app keeps closing without launching.  There has been no changes to app, I just always compile in the latest when available.  Rolled back to last working project running 4.3.0.991211 and issue is gone app functions as expected.

-------looked through forum for similar
Looked at closed #7301  user stated similar issue with older version,  Said fixed it by changing my splashactivity from FormsAppCompatActivity to AppCompatActivity.   I tried changing the 
 public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
  to
 public class MainActivity : global::Xamarin.Forms.Platform.Android.AppCompatActivity

There is no way to change it,  the class doesn't exist in namespace.  
    

### Expected Behavior
       Application to start 
### Actual Behavior
      Fails after opening several times.
### Basic Information

- Version with issue:  4.4.0.991265
- Last known good version:   4.3.0.991211
- IDE: Visual studio 2019 Version 16.4.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version:   min = API 23 marshmallow  Target 9.0 API PIE
- Nuget Packages:  Only updated xamarin.forms
- Affected Devices:  android galaxy s9+

**Comment by SandipAhluwalia** [comment] 2019-12-16 16:16
I am seeing something similar, our app works fine on v4.1.0778454, but when I upgrade Xamarin.Forms to 4.4.0.991265, the android app gets stuck on app launch after displaying the splashscreen with the logcat showing `android.os.DeadObjectException.` error. On iOS, it fails to even start the app with the following exception shown in the debug output:

> **Foundation.MonoTouchException:** 'Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

Note: for the Android app, if I run it in the Visual Studio debugger, it seems to launch okay and I am also using a splash activity that already derives from `AppCompatActivity.`

If I revert Xamarin.Forms version back to 4.1.0778454, it then all works as normal.

**Comment by Swdvader** [comment] 2019-12-16 23:17
Yes going back to 4.1xxx fixed the problem for me.

**Comment by samhouts** [comment] 2019-12-17 00:58
@Swdvader @SandipAhluwalia   Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Swdvader** [comment] 2019-12-17 04:04
I will try.

**Comment by Swdvader** [comment] 2019-12-17 04:56
I tried stripping everything down, but I cant replicate the problem.  It may be because I removed everything and its not going out to web for data.  I try again tomorrow night to see if I can narrow it down.

**Comment by Swdvader** [comment] 2019-12-17 05:14
Hopefully this helps
So I went to re deployed the full app using 4.4.0.991265, to my phone and the good news it I got it to crash when in debug mode during deployment.   I m getting the follow error when the app crashes :   
Exception Unhandled
System.NotSupportedException: 'Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer from native handle 0x7fcb38ec44(key_handle 0x5c2c1af).

**Comment by bares43** [comment] 2019-12-17 10:22
Same error here.

**Comment by transis2** [comment] 2019-12-17 15:03
Same error here. I've to go back to XF 4.3.*

**Comment by samhouts** [comment] 2019-12-17 18:17
@bares43 @transis2  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Swdvader** [comment] 2019-12-17 22:42
I am trying to make something small that causes the issue.

**Comment by Swdvader** [comment] 2019-12-18 02:51
Ok.  I have a stripped down project. That demonstrates the issue.  I tried to drag it this window, but I wont accept a VS project.  How do I get you the project?

**Comment by Swdvader** [comment] 2019-12-18 03:31
I stripped down a project.  I removed all the api calls, the IOS part and defaulted the local phone database values to null.  I left a lot of the empty pages, models.  There is really only 2 pages and master detail to look at as the issue happens on or between those pages.  Login page calls master detail and load page J.    The login page is the starting screen.  I reset the local db values because there is no api call and then call the master detail page.   When you run the project in debug You will see a mock splash screen.  Sometime it shows the exception on first run,  Sometimes the app will work and you will get to the next screen or login screen.
[JZRP-IssueTest - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/3976521/JZRP-IssueTest.-.Copy.zip)
 (the desired result).  If this happens just refresh  the project  you should eventually see this error.  I am thinking this is the issue.   Exception Unhandled
System.NotSupportedException: 'Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer from native handle.

When I deploy it to my phone and run it from the phone only.  Same thing.  App works a few times and then starts crashing. 

I am ran this on my galaxy s9+ (android)

The solution in zip needs to be rebuilt in VS.

**Comment by Swdvader** [comment] 2019-12-18 03:32
[JZRP-IssueTest - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/3976525/JZRP-IssueTest.-.Copy.zip)

**Comment by Dresel** [comment] 2019-12-20 08:58
We also ran into this issue, the problem is Xamarin.Forms.Visual.Material `4.4.0.991265`.

Downgrading this to `4.3.0.991250` or removing `FormsMaterial.Init(this, savedInstanceState)` stops the application from crashing.

Upgrading both to `4.5.0.74-nightly` seems to work too.

**Comment by samhouts** [comment] 2019-12-31 00:43
I get a different exception when I run the project using either 4.3.0.991211 or 4.4.0.991265.: `No embeddedresource found for JZRP.App`. I have yet to see the `NotSupportedException`.

**Comment by Swdvader** [comment] 2019-12-31 04:20
I just ran the project now.  Using VS 16.4.2 , net framework 4.8.03752 .  Xamarin.Forms 4.4.0.991265 is the one causing the issue, prior version have no issue. See screen shot attached error, I just tested it.  When I deploy it to my phone or tablet I can get the error.  I just hit refresh until it happens. 
Dont know why you getting no embedded  resource.  Check under CrossImage all should have a property of embedded resource.  I am not getting that error.  
![Capture](https://user-images.githubusercontent.com/14371980/71609933-5f0d9c80-2b5a-11ea-8ce2-d814fa62ff16.PNG)

**Comment by Swdvader** [comment] 2019-12-31 04:30
[JZRP-IssueTest - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/4011915/JZRP-IssueTest.-.Copy.zip)
I placed another copy of the one I just ran, just in case.

**Comment by haavamoa** [comment] 2020-01-10 12:42
We have the same issue. It's reproducible in the follow commit : https://github.com/DIPSAS/DIPS.Xamarin.UI/commit/4fc1b46c03425e415060b87311f1a6350d77e71d

**Comment by samhouts** [comment] 2020-01-16 00:00
Duplicate of #9136

**Closed by samhouts** 2020-01-16 00:00 UTC
Labels: e/3 :clock3:, i/high, i/regression, p/Android, t/bug :bug:
