### ISSUE TITLE
Android.AppCompat.NavigationPageRenderer.UpdateToolbar ()System.Null causes ReferenceException

### ISSUE THREAD

**Issue by rkops-bd** [xamarin/Xamarin.Forms#7549] opened 2019-09-17 07:25 UTC
When navigation from a MasterDetailView which is inside a navigationpage, the nullreference accored.

### Steps to Reproduce

1. MasterPage inside navigation
2. Navigate to new page from the masterpage
3. Exception will be thrown

Callstack:
`17 09:07:42.161 E/mono-rt (15817): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.UpdateToolbar () [0x000c9] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:987 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot) [0x0017b] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:858 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPushAsync (Xamarin.Forms.Page view, System.Boolean animated) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:614 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.PushViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:161 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPushed (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:619 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.NavigationPage.PushAsyncInner (Xamarin.Forms.Page page, System.Boolean animated) [0x00059] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:421 
09-17 09:07:42.161 E/mono-rt (15817):   at Xamarin.Forms.NavigationPage.PushAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x0014e] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:242 
09-17 09:07:42.161 E/mono-rt (15817):   at DigiD.Core.NavigationService+<>c__DisplayClass8_0.<PushAsync>b__0 () [0x00180] in C:\Projects\mcc_digid\Source\DigiD.Core.MobileClient\NavigationService.cs:123 
09-17 09:07:42.161 E/mono-rt (15817):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.40(intptr,intptr)
09-17 09:07:42.161 E/mono-rt (15817):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.40(intptr,intptr)`
### Expected Behavior
No nullreference

### Actual Behavior
Null reference
### Solution
extra null check on line 985: -> else if (_masterDetailPage != null && toggle != null)

**Comment by kvpt** [comment] 2019-09-17 08:38
It'a duplicate of #7496.
Fixed by #7513.

**Comment by jfversluis** [comment] 2019-09-17 08:58
As mentioned by @kvpt duplicate and fixed. We've just merged it. Should be included in the next release of 4.2 and up.

Thank you for reporting Reinier!

**Comment by jfversluis** [comment] 2019-09-17 08:58
Duplicate of #7496

**Closed by jfversluis** 2019-09-17 08:58 UTC
Labels: s/unverified, t/bug :bug:

**Comment by rkops-bd** [comment] 2019-09-18 08:09
@jfversluis any idea when this will be released

**Comment by jfversluis** [comment] 2019-09-18 08:43
The new 4.2 version should be out pretty soon, normally within 1 or 2 weeks.
