### ISSUE TITLE
After upgrading to 4.0.0 Service Request 4 getting exception 

### ISSUE THREAD

**Issue by PWaliaDev** [xamarin/Xamarin.Forms#6754] opened 2019-07-02 18:43 UTC
I upgraded Xamarin.Forms to 4.0.0 service request and then getting exception 

No constructor found for Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)

Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer from native handle 0xbfd3900c (key_handle 0xcbe3ef).

StackTrace:

  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at Android.Views.View.n_Invalidate (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.76(intptr,intptr)

Source: Mono.Android

System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer from native handle 0xbfd3900c (key_handle 0xcbe3ef). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
  at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
  at java.lang.Error: Java callstack:
  at at md5f92e0daf340890c9667469657ee2ece8.ImageRenderer.n_invalidate(Native Method)
  at at md5f92e0daf340890c9667469657ee2ece8.ImageRenderer.invalidate(:54)
  at at android.widget.ImageView.invalidateDrawable(ImageView.java:281)
  at at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:450)
  at at android.graphics.drawable.Drawable.setVisible(Drawable.java:859)
  at at android.widget.ImageView.updateDrawable(ImageView.java:1011)
  at at android.widget.ImageView.setImageDrawable(ImageView.java:567)
  at at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(:28)
  at at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(:10)
  at at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(:127)
  at at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(:104)
  at at com.bumptech.glide.request.SingleRequest.onResourceReady(:579)
  at at com.bumptech.glide.request.SingleRequest.onResourceReady(:549)
  at at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(:218)
  at at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(:324)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6494)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at Android.Views.View.n_Invalidate (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <ff9f3f3d4e134974a889db1b532c9b6e>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.76(intptr,intptr)

I was also getting this issue when I was using FastRenderer so I skipped to use them but as now FastRenderers are default so getting this issue.

- Version with issue:
- Last known good version: 3.0.1
- IDE:
- Platform Target Frameworks: 
  - Android: Xamarin.Android 8.1
- Nuget Packages: 4.0.0 Service Request 4
- Affected Devices: Android

**Comment by kingces95** [comment] 2019-07-03 22:00
Could you please attach a reduced reproduction that throws that exception on the 4.0 service release?

**Comment by kvpt** [comment] 2019-07-03 23:13
Another Android dispose issue, it is likely to be fixed by #6467.

The stacktrace provide several interesting informations :
- The first one is that the renderer which was disposed is the FastRenderers ImageRenderer.
So you can for the moment fixe your issue by disable the fastrenderer.
Add this line before Forms.Init call
```cs
Forms.SetFlags("UseLegacyRenderers");
```
- The second one is that the issue is a race condition in the dispose process.

```cs
at android.widget.ImageView.invalidateDrawable(ImageView.java:281)
at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:450)
at android.graphics.drawable.Drawable.setVisible(Drawable.java:859)
at android.widget.ImageView.updateDrawable(ImageView.java:1011)
at android.widget.ImageView.setImageDrawable(ImageView.java:567)
```

The imageView is the renderer, so, the setImageDrawable use it, no error, then the updateDrawable use it, no error too, then the invalidateDrawable use it, and now it crash, because at the same time the renderer has  been disposed.
It's possible because when the image change, it's trigger an event, and this event is processed asynchronously (the setImageDrawable), so if at the same time a dispose is trigerred it's possible to have that issue.

In #6467 I reordered all the dispose process to unsuscribe all the events first, so it will reduce the time window that make this race condition possible.
This may be enough, if not, we will have to use some synchronization mecanism to prevent that.

**Comment by PWaliaDev** [comment] 2019-07-03 23:57
@kingces95 Actually i can not attach because its our customer's project and i can not put out for world.

**Comment by samhouts** [comment] 2019-07-16 03:03
@PWaliaDev Please test with 4.2.0-pre1 and let us know if this resolves the issue. Thanks!

**Comment by samhouts** [comment] 2019-08-16 21:07
@PWaliaDev  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2019-08-16 21:07 UTC
Labels: i/high, i/regression, p/Android, s/needs-repro ❔, s/unverified, t/bug :bug:
