### ISSUE TITLE
[Bug] No URI images in CollectionView iOS app

### ISSUE THREAD

**Issue by aodegov** [xamarin/Xamarin.Forms#15105] opened 2022-01-29 14:35 UTC
### Description

iOS CollectionView images loading issue.
Can't see vast majority images there.

### Steps to Reproduce

1. [Launch the iOS project](https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/Xaminals/Xaminals.iOS)
2. See no loaded URI images into CollectionView  iOS app

### Expected Behavior
Correctly loaded and visible images for the iOS CollectionView
### Actual Behavior
Most of the images are not visible in the iOS CollectionView.  
In addition they're disappearing due to scrolling.
### Basic Information

- Version with issue: XF 5.0.0.2337
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  iPhone 12 Pro on iOS 15.2.1
  - Device or simulator/emulator: iPhone simulator on iOS 15.2
  
### Environment

1. Visual Studio: Microsoft Visual Studio Community 2022 (64-bit) Version 17.0.5

### Screenshots

![image](https://user-images.githubusercontent.com/24685526/151664737-bca8d488-27be-45e4-9943-e8f6f6854cd5.png)

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/Xaminals

**Comment by jfversluis** [comment] 2022-02-02 13:40
Duplicate of #13323

**Closed by jfversluis** 2022-02-02 13:40 UTC
Labels: t/bug :bug:, s/unverified

**Comment by aodegov** [comment] 2022-02-02 17:24
@jfversluis  any updates / fixes for this?
