### ISSUE TITLE
Null reference exception has been thrown while using SearchBar in NavigationPage in Xamarin.Forms.UWP

### ISSUE THREAD

**Issue by PavithraSyncfusion** [xamarin/Xamarin.Forms#2707] opened 2018-05-15 04:36 UTC
Hi, 

While using SearchBar in NavigationPage, Null reference has been thrown from SearchBarRenderer.OnControlLoaded() event.

Xamarin Version: 3.0
Target Platform: Xamarin.Forms.UWP
Platform Target Version: Windows 10 Fall Creators Update (10.0; Build 16299)

I have attached a sample that replicates the issue. 

Procedure to replicate the issue:

 1. Click the SearchBarClass.
 2. Note exception has been thrown. 

Please find the below attached screenshot for further reference.

![searchbarisuue](https://user-images.githubusercontent.com/27993223/40036733-bb79cf88-5826-11e8-88f1-5a9381745a7e.png)

Regards,
Pavithra S

[SearchBarIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2003470/SearchBarIssue.zip)

**Comment by StephaneDelcroix** [comment] 2018-05-15 08:57
dupe of #2633

**Closed by StephaneDelcroix** 2018-05-15 08:57 UTC
Labels: p/UWP, s/duplicate, t/bug :bug:
