### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thales-man** [xamarin/Xamarin.Forms#10200] opened 2020-04-03 15:58 UTC
### Description
list view no longer responds to clicks in Xamarin.IOS.

### Steps to Reproduce
1. fetch: https://github.com/thales-man/tiny-things
2. build solution Hanselman.Forms.Referenced, I believe everything is up to date and ready to run
3. run (in iOS 13.4 simulator, first of all)
3. click on the hamburger and (try to) select another page to view...

### Expected Behaviour
list view is expected to respond to clicks on the menu

### Actual Behaviour
it doesn't

### Basic Information

- Version with issue:
4.5.0.530

- Last known good version:
4.5.396?

- IDE:
VS for Mac (8.5.1, 42)

Platform Target Frameworks: 
iOS:  
doesn't work (13.4)

Android:  
works (pie 9.0)

UWP:   
don't care (does anybody?)

macOS: 
works!! draws really badly, but it doesn't blow up (which I expected it to do)

### Workaround
none

**Comment by GiampaoloGabba** [comment] 2020-04-03 16:57
Please see issue #10162

**Comment by samhouts** [comment] 2020-04-03 17:38
Duplicate of #10162

**Closed by samhouts** 2020-04-03 17:38 UTC
Labels: s/unverified, t/bug :bug:
