### ISSUE TITLE
[Enhancement] Add Title Visible to TabBar

### ISSUE THREAD

**Issue by Mohsnb** [xamarin/Xamarin.Forms#6546] opened 2019-06-16 09:57 UTC
## Summary
Please add a property to hide Title of TabBar and show only icons.

e.g.
```
<TabBar TitleVisible ="false">
    ...

</TabBar>
```
![cats-large](https://user-images.githubusercontent.com/25475989/59562490-bdea4900-9042-11e9-9920-e4002750b852.png)

Thanks.

**Comment by James3UK** [comment] 2019-06-17 07:45
Hi,
Are you setting the tab Title property as it seems you could just not set it, or set the title to an empty string to achieve this?
`<Tab Title="">`
Maybe post your full shell example and more detail about what you are expecting to change if that doesn't work for you.

**Comment by Mohsnb** [comment] 2019-06-17 08:05
> Hi,
> Are you setting the tab Title property as it seems you could just not set it, or set the title to an empty string to achieve this?
> `<Tab Title="">`
> Maybe post your full shell example and more detail about what you are expecting to change if that doesn't work for you.

Hi,
When set to an empty string then space of Title isn't removed and bottom of icons have free space which in mobile this space is important and show bad look with not equal padding in top and bottom of icons.
I edited the image which pasted and removed this space.

**Comment by James3UK** [comment] 2019-06-17 08:17
Is this the same as https://github.com/xamarin/Xamarin.Forms/issues/6220 ?

**Comment by Mohsnb** [comment] 2019-06-17 08:20
Yes, it is.

**Comment by jfversluis** [comment] 2019-06-17 08:23
Duplicate of #6220

**Closed by jfversluis** 2019-06-17 08:23 UTC
Labels: proposal-open, t/enhancement ➕
