### ISSUE TITLE
[Enhancement] Add support for loading and displaying SVG images in Xamarin.Forms

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1863] opened 2018-02-12 19:48 UTC
Migrating this 2+ year old request here - https://bugzilla.xamarin.com/show_bug.cgi?id=29677

### Rationale
There is a long rationale in the bugzilla report for this, but the gist is it is a pain to have to handle multiple image sizes in our projects, using a SVG makes handling images less of a pain.

See this post from 2014 for a discussion on SVG support: https://forums.xamarin.com/discussion/17785/support-for-cross-platform-assets-like-svg-and-9-patch-formats/p1

### Summary
Right now to display images we need to provide multiple PNG files in different sizes, with SVG we would just need to import the SVG.

### API Changes
Not sure how this should look, need input from the community. 

### Intended Use Case
To use a SVG instead of multiple sized PNGs to display images.

**Comment by ddobrev** [comment] 2018-02-12 19:52
To be precise: this works but for Android 5+ only. The reason is that your renderers do not call the necessary compat-code (Android support libraries) for older versions.

**Comment by PureWeen** [comment] 2018-02-13 02:33
@ddobrev   I was able to reproduce the issue you are referring to in pre android 5 but I think this particular issue is more about supporting just straight SVG files and less about the Vector Drawables

I created this issue
https://github.com/xamarin/Xamarin.Forms/issues/1872

around what you are referring to

I'm going to close this particular issue and recommend using 3rd party plugins for straight SVG files as this isn't something that the Core is going to support

**Closed by PureWeen** 2018-02-13 02:33 UTC
