### ISSUE TITLE
Android: MasterDetailPage animation hangs when setting Detail page

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#4400] opened 2018-11-14 15:31 UTC
### Description
On Android the MasterDetailPage animation hangs when setting Detail page. The pages nav bar also flashes when setting the Detail page, that is: the pages nav bar disappears for a split second when setting the details page. If I only set IsPresented = false, I don't see this flashing of the navigation bar and the animation runs smoothly. I have a feeling that this behaviour was introduced in recent version of Xamarin.Forms because I haven't seen this behaviour before.

### Steps to Reproduce

1. Switch between Detail pages in a MasterDetailPage
2. Also try just closing the master page by setting IsPresented to false without setting the Detail page, this goes smooth

### Expected Behavior
Smooth transition of pages, smooth closing animation of nav menu, no flickering of page nav bar

### Actual Behavior
laggy closing animation of nav menu, flickering of page nav bar

### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version:?
- IDE: VS Mac 7.6.10
- Platform Target Frameworks: 
- Android: 8.1

**Comment by kingces95** [comment] 2018-11-14 21:15
see also: https://github.com/xamarin/Xamarin.Forms/issues/4400

**Comment by kingces95** [comment] 2018-11-16 00:30
I don't reproduce this on the nightly. Please include a reproduction and/or a video.

**Comment by samhouts** [comment] 2019-01-24 01:49
Duplicate of #4398

**Closed by samhouts** 2019-01-24 01:49 UTC
Labels: a/animation 🎬, e/5 :clock5:, i/regression, p/Android, s/needs-repro ❔
