### ISSUE TITLE
TapGestureRecognizer not working in windows iOS app development with HotReload

### ISSUE THREAD

**Issue by shraddha-patange** [xamarin/Xamarin.Forms#15157] opened 2022-02-15 16:15 UTC
### Description
Currently using VS2022 with HotReload option for iOS app development
iPhone  - iPhone 12 
iPhone OS Version - 15.1.1
Xamarin forms - 5.0.0.2012

### Expected Behavior
TapGestureRecognizer is invoked
### Actual Behavior
TapGestureRecognizer is not invoked
### Basic Information
Perfectly working with Android

**Comment by jfversluis** [comment] 2022-02-15 18:48
Duplicate of #14956

**Closed by jfversluis** 2022-02-15 18:48 UTC
Labels: t/bug :bug:, s/unverified
