### ISSUE TITLE
Null UIKit.FontDescriptor crashes XF 3.4/3.5

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5148] opened 2019-02-06 17:55 UTC
### Description
In Xaml if the descriptor is null, Forms will crash
### Steps to Reproduce

1.  
2. 
3. 

### Expected Behavior
Not crash
### Actual Behavior
Crash
### Basic Information

- Version with issue:
- Last known good version: Unknown
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:   Any
 
### Screenshots
![image](https://user-images.githubusercontent.com/112916/52362279-0e96c900-29f5-11e9-9bab-dc9857472bc0.png)

Note: Descriptor is null and not checked for Null

**Comment by ianvink** [comment] 2019-02-06 17:57
Note: We are using plain Roboto font, I don't think Roboto has Bold and we in XAML ask for Bold.

**Comment by ianvink** [comment] 2019-02-06 17:58
Android is fine

**Comment by ianvink** [comment] 2019-02-06 20:10
I found this is caused by setting a TextDecoration of StrkeThrough to a Bound value that is NULL on a label.

Android is fine. iOS throws  the error

**Comment by samhouts** [comment] 2019-02-06 22:59
Duplicate of #5003

**Closed by samhouts** 2019-02-06 22:59 UTC
Labels: t/bug :bug:
