### ISSUE TITLE
[Enhancement] interchangeable collection view. 

### ISSUE THREAD

**Issue by levelfivecoder** [xamarin/Xamarin.Forms#8543] opened 2019-11-18 01:53 UTC
## Summary
Enhance the collection view with features like longpress action and able to swap item position by drag and drop. 

## Intended Use Case
More customizable ui

**Comment by samhouts** [comment] 2020-02-13 00:50
Duplicate of #4676 
Duplicate of #5883

**Closed by samhouts** 2020-02-13 00:50 UTC
Labels: proposal-open, t/enhancement ➕
