### ISSUE TITLE
[Bug] IOS app crash when hot reloading to real ios device 14.6

### ISSUE THREAD

**Issue by maximusfatigue** [xamarin/Xamarin.Forms#14356] opened 2021-06-18 11:05 UTC
### Steps to Reproduce

1. build
2. run on real ios device  ,  ios 14.6
2. click app icon on app 
3. auto closes. 

### Expected Behavior

app loads and is usable.

### Actual Behavior

app doesn't open, 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Workaround

> VS bug [#1344788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1344788)

**Comment by jsuarezruiz** [comment] 2021-06-18 17:31
What Visual Studio version are you using?, and what Xamarin.Forms version?.

**Comment by maximusfatigue** [comment] 2021-06-18 19:02
Microsoft Visual Studio Community 2019
Version 16.10.2

xamarin forms version 4.8

**Comment by maximusfatigue** [comment] 2021-06-21 08:17
resolved

**Comment by maximusfatigue** [comment] 2021-06-21 08:42
Well, its working, i can build to a real device, but hot reload isnt working and the device only stays connected for a few months after its built

**Comment by drasticactions** [comment] 2021-07-09 22:51
@maximusfatigue The reason for that is it's not actually connected at all. There was a regression in, I believe, the Xamarin Visual Studio extension that causes the XAML Hot Reload code to not detect when a new iOS app has been deployed. There is currently a fix for this going into versions 16.11 and 17. 

I would close this issue and file feedback against Visual Studio if you have issues with XAML Hot Reload. It's unrelated to Xamarin Forms.

**Closed** 2021-07-10 00:11 UTC
Labels: external-hotreload, s/needs-info ❓, s/unverified, t/bug :bug:
