### ISSUE TITLE
[Bug] [Android] Button HorizontalOptions="Start" display issue - Regression

### ISSUE THREAD

**Issue by BurkusCat** [xamarin/Xamarin.Forms#10340] opened 2020-04-15 10:18 UTC
### Description
A regression occurred with how some buttons are displayed in one of my projects when I updated Xamarin.Forms. Buttons with HorizontalOptions="Start" on Android display wrongly. This issue started occuring when upgrading from version 4.5.0.396 to 4.5.0.495 of Xamarin.Forms. This issue is not fixed in the latest version of Xamarin.Forms.

### Steps to Reproduce
Use the [linked project](https://github.com/xamarin/Xamarin.Forms/files/4480540/ButtonScrollingRepro.zip) or rough steps:

1. Add a button to a page with HorizontalOptions=Start
2. Wrap the first MainPage in a NavigationPage
`MainPage = new NavigationPage(new MainPage());`
3. Upgrade Xamarin.Forms from 4.5.0.396 to 4.5.0.495
4. Run on Android phone

### Expected Behavior
Button displays normally on one line with all text visible.

### Actual Behavior
Button is showing with a scrollbar, text is obscured, text is over two lines, button is too tall and too wide.

### Basic Information

- Version with issue: 4.5.0.495
- Last known good version: 4.5.0.396
- IDE: Visual Studio 16.5.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Several devices incl. Samsung Note 10 Lite

### Screenshots
| **Expected**  | **Regression**  |
|---|---|
| ![image](https://user-images.githubusercontent.com/7528322/79326084-2ecfeb00-7f0a-11ea-8210-a119f1103c0c.png)  | ![image](https://user-images.githubusercontent.com/7528322/79326092-32637200-7f0a-11ea-961b-bd76013e4eab.png) |

### Reproduction Link
[ButtonScrollingRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4480540/ButtonScrollingRepro.zip) - You can downgrade this project to 4.5.0.396 to see the fixed button

### Workaround
Make my own custom button with a frame. Not the best solution.

**Comment by aranor01** [comment] 2020-04-15 11:52
+1
the issue occurs when any layout with expands = false is assigned to HorizontalOptions

**Comment by samhouts** [comment] 2020-04-15 20:32
Duplicate of #10102

**Closed by samhouts** 2020-04-15 20:32 UTC
Labels: 4.5.0, a/button, i/regression, p/Android, s/unverified, t/bug :bug:
