### ISSUE TITLE
[Bug] DatePicker and TimePicker not working on xamarin.forms macOS

### ISSUE THREAD

**Issue by ekrogh** [xamarin/Xamarin.Forms#6817] opened 2019-07-08 14:52 UTC
### Description
The xamarin.forms DatePicker and TimePicker does not work on macOS. A lot of the numbers on the dates and times is not showing.

I have attached a video showing the problem. In the video I click the up- and down arrows to increase and decrease date and time. I doesn't work if I type in the numbers.

### Steps to Reproduce
The Visual Studio solution can be found on GitHub:
https://github.com/ekrogh/DateTimeTestProj.git

1. 
2. 
3. 

### Expected Behavior
on xamarin.forms macOS that all digits in dates and times are showing

### Actual Behavior
Please watch the video
[ScreenCapture_2019-7-8 02.56.06.zip](https://github.com/xamarin/Xamarin.Forms/files/3368881/ScreenCapture_2019-7-8.02.56.06.zip)

## Basic Information

- Version with issue: xamarin.forms Version 4.1.0.555618
- Last known good version: ?
- IDE: Visual Studio for mac 2019 Version 8.1.4 (build 5)
- Platform Target Frameworks: 
 - macOS

- Nuget Packages:
- Affected Devices: mac

### Screenshots
[ScreenCapture_2019-7-8 02.56.06.zip](https://github.com/xamarin/Xamarin.Forms/files/3368881/ScreenCapture_2019-7-8.02.56.06.zip)
!-- If the issue is a visual issue, please include screenshots showing the problem if possible -->

### Reproduction Link
https://github.com/ekrogh/DateTimeTestProj.git

**Comment by jsuarezruiz** [comment] 2019-07-16 09:14
Thanks for the sample. The controls seems to work correctly but visually there are values that are not rendered correctly.
![issue6817](https://user-images.githubusercontent.com/6755973/61281961-cdcc8880-a7ba-11e9-97e3-82ad70b43b24.gif)

**Comment by krdmllr** [comment] 2019-08-16 09:34
The problem is that the control does not adjust its size to different font sizes. I think the native control is supposed to keep its size. I created the PR https://github.com/xamarin/Xamarin.Forms/pull/7183 that ignores the font size and always enforces the default size which fixes the issue.

**Comment by samhouts** [comment] 2019-09-27 00:34
closed by #7183

**Closed by samhouts** 2019-09-27 00:34 UTC
Labels: e/2 :clock2:, p/macOS, t/bug :bug:
