### ISSUE TITLE
WebView Vertical and Horizontal  scrolling not working when page is in shell(Android) 

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/Xamarin.Forms#6838] opened 2019-07-10 10:29 UTC
WebView scrolling stops to working when page is inside shell in android .Note I am not using any scroll view above webview, Plain web view inside Grid .iOS works fine .
You can reflect this scenario easily I don't think repo is needed to attach

Xamarin.Forms Version : Latest Stable Xamarin.Forms version

**Comment by alanag13** [comment] 2019-07-11 02:30
dupe of #5205

**Comment by samhouts** [comment] 2019-07-11 02:40
Duplicate of #5205

**Closed by samhouts** 2019-07-11 02:40 UTC
Labels: s/unverified, t/bug :bug:
