### ISSUE TITLE
ContextAction produces non clickable items on iOS

### ISSUE THREAD

**Issue by Schullebernd** [xamarin/Xamarin.Forms#5130] opened 2019-02-04 15:34 UTC
### Description
I have a listview with uneven rows. The items have a typical context action "delete" with the attribute "IsDescructive="true". Now, when I swipe on an item to open the context menu and then cancel the action, the item is not clickable anymore until the listview is realoaded completely.

This is the XAML code of the listview:

```xaml
<ListView x:Name="listView" Margin="0,0,0,0" HasUnevenRows="True" SelectionMode="None" ItemTapped="ListView_ItemTapped" ItemAppearing="ListView_ItemAppearing" BackgroundColor="{StaticResource StandardBackgroundColor}">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <ViewCell.ContextActions>
                    <MenuItem Clicked="OnDelete" CommandParameter="{Binding .}" Text="Löschen"  />
                </ViewCell.ContextActions>
                <StackLayout Orientation="Vertical" HeightRequest="90" HorizontalOptions="Fill">
                    <StackLayout Orientation="Horizontal" Margin="10,10,10,0" HorizontalOptions="Fill">
                        <Label Text="{Binding Discipline}" VerticalOptions="Center" HorizontalOptions="StartAndExpand" FontSize="Small" FontAttributes="Bold" TextColor="Black" MaxLines="1"/>
                        <Label Text="{Binding Startdate}" VerticalOptions="Center" HorizontalOptions="End" FontSize="Small" MinimumWidthRequest="100" HorizontalTextAlignment="End" MaxLines="1"/>
                    </StackLayout>
                    <StackLayout Orientation="Horizontal" Margin="10,0,10,0" HorizontalOptions="Fill" >
                        <Label Text="{Binding FinalResult}" VerticalOptions="Center" HorizontalOptions="Start" WidthRequest="50" MinimumWidthRequest="50" FontSize="Medium" TextColor="{StaticResource ColorPrimary}" FontAttributes="Bold"/>
                        <Label Text="{Binding PartResults}" VerticalOptions="Center" HorizontalOptions="StartAndExpand" FontSize="Small"/>
                    </StackLayout>
                    <StackLayout Orientation="Horizontal" Margin="10,0,10,10" HorizontalOptions="Fill">
                        <Label Text="{Binding ActivityType}" VerticalOptions="Center" HorizontalOptions="Start" FontSize="Small" TextColor="Gray" FontAttributes="Bold"/>
                    </StackLayout>
                </StackLayout>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
In the ItemAppearing event I load the model from the database to set the labels via the viewmodel. The ItemTabbed event creates and pushes a new viewpage.
The listview ItemSource is set in the constructor of the page and the type is **ObservableCollection**. So not something special.

I posted the problem into the xamarin forum and it was already confirmed as a bug, which should be posted here too.

### Steps to Reproduce

1. Create a new viewpage in xamarin forms with a listview like above.
2. Combile and debug the app with the page on an iPhone (6s)
3. Swipe on a listviewitem to open the context action
4. Abort and close the context menu
5. Try to tab the same item to open the new viewpage

### Expected Behavior
The tab event of the item should be risen to open the new viewpage or do something else.

### Actual Behavior
The tab event of the item is not risen.

### Basic Information

- Version with issue: 
Xamarin 4.12.3.79
- Last known good version: no
- IDE: Visual Studio Community 15.9.6
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS and Xamarin.Mac SDK 12.2.1.12
  - iOS SDK Version 12.1
- Affected Devices:
  - Tested on iPhone 6s with iOS 12.1.3

**Comment by samhouts** [comment] 2019-02-11 18:44
Duplicate of #3217

**Comment by samhouts** [comment] 2019-02-11 18:47
Duplicate of #4987

**Closed by samhouts** 2019-02-11 18:47 UTC
Labels: t/bug :bug:
