### ISSUE TITLE
[Bug] Material Entry sharing parent with button with font icon causes app to crash.

### ISSUE THREAD

**Issue by MathewLC** [xamarin/Xamarin.Forms#6303] opened 2019-05-24 12:06 UTC
### Description
The losing focus of an entry with visual material, sharing the same parent that a button with font icon craches tha app.

### Steps to Reproduce
1. Specify a layout parent in page.
2. Put two or more entry with visual material.
3. Put a button with font icon.
4. Click on entry and after try to click on the other entry in the screen.

### Expected Behavior
The visual material of entry should not affet button with font icon that has visual default or material either.

### Actual Behavior
The app crashes for some reason involving the parent.

### Basic Information

- Version with issue: 4.0.0.425677
- IDE: Visual Studio 2019 
- Platform Target Frameworks:
- Android: 9.0 
- Nuget Packages: Xamarin.Forms.Visual.Material 4.0.0.425677
- Tested Devices: Nokia x9, Android Emulator

```
<StackLayout Visual="Material" VerticalOptions="CenterAndExpand">
        
        <Entry Keyboard="Numeric" />
        <Entry Keyboard="Numeric" />
        <Button Text="Pesquisar"  Visual="Default" >
            <Button.ImageSource>
                <FontImageSource
                    Glyph="&#xf002;"
                    >
                    <FontImageSource.FontFamily>
                        <OnPlatform x:TypeArguments="x:String" 
                                              Default="FontAwesome" 
                                              Android="fontawesome-webfont.ttf#FontAwesome"/>
                    </FontImageSource.FontFamily>
                </FontImageSource>
            </Button.ImageSource>
        </Button>
    </StackLayout>

**Comment by PureWeen** [comment] 2019-05-24 16:16
duplicate of
https://github.com/xamarin/Xamarin.Forms/issues/6260#issuecomment-495490890

There's a nuget in that issue if you want to test the fix

**Closed by PureWeen** 2019-05-24 16:16 UTC
Labels: s/unverified, t/bug :bug:

**Comment by MathewLC** [comment] 2019-05-24 16:30
Thank you, I will going to test. I didn't know if this was co-related.
