### ISSUE TITLE
[Bug] netcoreapp3.1 WPF version causes Could not load file or assembly 'xxx, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by ErikSJan** [xamarin/Xamarin.Forms#11328] opened 2020-07-06 15:57 UTC
### Description
Any software using netcoreapp3.1/WPF and Xamarin.Forms fails to execute since version 4.7.
Usually the error is Could not load file or assembly 'Xamarin.Forms.Platform.WPF, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' but it can be 0.0.0.0 depending on the version of the package.
It's not working either with the project 'Xamarin.Forms.ControlGallery.WPF' included in the repository.

### Steps to Reproduce
1. Download any version of the repository since 4.7
2. Build everything
3. Open Visual Studio 2019 with the Xamarin.Forms.sln
4. Set Xamarin.Forms.ControlGallery.WPF as starting project
5. Execute the project

### Expected Behavior
Should run the application

### Actual Behavior
In case of last version 5 nightly, fails with an error "Could not load file or assembly 'Xamarin.Forms.ControlGallery.WPF, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'".
Any other software made with these packages gives Could not load file or assembly 'Xamarin.Forms.Platform.WPF, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

### I Couldn't find any workaround and had to downgrade to 4.6.0.1073

**Comment by VladislavAntonyuk** [comment] 2020-07-06 21:12
I had this issue and fixed by using new csproj with target framework net5.0 instead of targetframeworks net461;netcoreapp3.1

**Comment by jsuarezruiz** [comment] 2020-07-07 09:28
Verified, can reproduce the issue.

**Comment by VladislavAntonyuk** [comment] 2020-07-08 18:41
@ErikSJan do you use XF.Maps WPF?

**Comment by ErikSJan** [comment] 2020-07-08 19:53
> @ErikSJan do you use XF.Maps WPF?

Hi @VladislavAntonyuk . No I don't use it.
Apart from Xamarin.Forms my projects use MVVMCross and SkiaSharp.

**Comment by VladislavAntonyuk** [comment] 2020-07-08 20:42
Can you reproduce it on a clean project? I think it is because some projects uses net461 which replaces netcore version

**Comment by ErikSJan** [comment] 2020-07-09 11:44
> Can you reproduce it on a clean project? I think it is because some projects uses net461 which replaces netcore version

There is no need to create a new project. Take a brand new PC, install VS2019 on it, git clone any repository since 4.7, try to build the whole set. Launch Xamarin.Forms.Controls.XPF... Crash...

**Comment by VladislavAntonyuk** [comment] 2020-07-09 11:57
Xamarin.Forms.Controls.Gallery uses Maps, which is created for net461

**Closed** 2020-09-10 10:43 UTC
Labels: e/2 :clock2:, i/high, in-progress, p/WPF, t/bug :bug:
