### ISSUE TITLE
Runtime Exception hit in  Xamarin.Forms.Forms.Init() for UWP when theres's no ".xaml" files

### ISSUE THREAD

**Issue by samsnowy** [xamarin/Xamarin.Forms#3282] opened 2018-07-11 22:11 UTC
### Description

We’re hitting an runtime error in Xamarin.Forms.Forms.Init() when we try to call it in a Universal Windows App that doesn’t have any “.xaml” files. (No App.xaml, no Mainpage.xaml, etc)
We attached a minimum repro sln and you should hit the same exception when you build and launch the app.

Do we need to have ".xaml" files to invoke the xaml generated code and resources? 

### Steps to Reproduce

1.  Unzip the repro.zip
2.  Open the sln in visual studio
3.  Debug, Build and Run the App

### Expected Behavior
No runtime exception

### Actual Behavior
Hits a runtime exception with the following call stack:
   at Windows.UI.Xaml.ResourceDictionary.put_Source(Uri value)
   at Xamarin.Forms.Forms.GetTabletResources()
   at Xamarin.Forms.Forms.Init(IActivatedEventArgs launchActivatedEventArgs, IEnumerable`1 rendererAssemblies)
   at TestUWP.App.OnLaunched(LaunchActivatedEventArgs e)
System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'

Native Debugging gives the following exception:
Exception thrown at 0x00007FFAE260A388 (KernelBase.dll) in TestRepro.exe: WinRT originate error - 0x802B000A : 'Cannot deserialize XBF metadata type list as 'PageControl' was not found in namespace 'Xamarin.Forms.Platform.UWP'. [Line: 0 Position: 0]'.

### Basic Information

- Version with issue: 2.5.1.527436
- Last known good version: None
- IDE: Visual Studio 2017 15.7.4
- Platform Target Frameworks:
  - UWP: 
    - Min version: Windows 10 Anniversary Update (10.0; Build 14393)
    - Target version: Windows 10 version 1803 (10.0; Build 17134)

- Nuget Packages:
Microsoft.NETCore.UniversalWindowsPlatform v6.1.5
Xamarin.Forms v2.5.1.527436

### Reproduction Link
[TestRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/2186315/TestRepro.zip)

**Comment by pauldipietro** [comment] 2018-07-11 22:30
Also checked against 3.1

**Comment by nbevans** [comment] 2018-11-23 11:13
Just had this. No idea where it came from. I had to reboot, restart VS, wipe bin/obj folders, load and unload projects from VS Solution Explorer, rebuild projects one by one.... not actually sure what fixed it in the end but it was a 45 minute time sink trying to get to the bottom of it.

**Comment by msc4266** [comment] 2019-02-24 07:28
Same here V15.9.7, Xamarin Forms 3.5  occurs randomly, sometimes second or third subsequent try to run is successful

**Comment by artemious7** [comment] 2020-01-31 13:29
I do have Xaml files, but this happens to me randomly (though quite rare). I use v4.4.0.991537+459-sha.e962467bd-azdo.3397178 of Xamarin.Forms

Here are the exceptions:
One or more errors occurred. (Error HRESULT E_FAIL has been returned from a call to a COM component.)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider.PopulateAssemblies()
   at Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider..ctor()
   at MyProject.MyProject_UWP_XamlTypeInfo.XamlTypeInfoProvider.get_Provider() in C:\Users\me\source\MyProject\MyProject\MyProject.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 123
   
   Error HRESULT E_FAIL has been returned from a call to a COM component.
      at Windows.Storage.StorageFolder.GetFoldersAsync()
   at Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider.<GetAssemblyListAsync>d__6.MoveNext()
   
      at Windows.UI.Xaml.ResourceDictionary.put_Source(Uri value)
   at Xamarin.Forms.Forms.GetTabletResources()
   at Xamarin.Forms.Forms.Init(IActivatedEventArgs launchActivatedEventArgs, IEnumerable`1 rendererAssemblies)
   at MyProject.UWP.App.<OnLaunched>d__1.MoveNext() in C:\Users\me\source\MyProject\MyProject\MyProject.UWP\App.xaml.cs:line 97

**Comment by vinceg433** [comment] 2020-04-08 15:01
I just ran into what appears to be the same issue.  My UWP project has a dependency on class library A.  I added a new dependency class library B to class library A.  When attempting to run the UWP project, it would fail with this exception.

As suggested here, I deleted all of the obj and bin files, cleaned the solution, and rebuilt it.  This time VS gave an error during the build process saying class library B couldn't be found.  I added a dependency on the UWP project to class library B (as well as class library A) and the issue went away.

**Comment by samhouts** [comment] 2020-11-05 23:41
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment] 2020-12-15 16:30
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by Redth** 2020-12-15 16:30 UTC
Labels: a/Xaml </>, e/5 :clock5:, help wanted, p/UWP, s/needs-info ❓, t/bug :bug:, up-for-grabs

**Comment by JonasOberhauser** [comment] 2021-01-02 18:09
@Redth The issue is still there. 
It affects all of my projects, including one created a few days ago on a completely new install of VS 2019 community with all packages updated to the most recent versions. Only other package I'm using is SkiaSharp.

![image](https://user-images.githubusercontent.com/183564/103463541-664b2580-4d2d-11eb-91da-1131b0c46667.png)



(Unfortunately I don't seem to be able to reopen the issue.)
