### ISSUE TITLE
ListView default behaviour does not work

### ISSUE THREAD

**Issue by danardelean** [xamarin/Xamarin.Forms#4721] opened 2018-12-13 08:25 UTC
### Description
The ListView that binds an IEnumerable<T> is to create a label set with the result of T.ToString(). This does not work anymore in the recent versions of Xamarin.Forms 

### Steps to Reproduce

1. Create a project
2. Create a Model and override ToString
3. Create a page with a ListView and set the ListView ItemsSource an IEnumerable<Model>. 

### Expected Behavior
Should see the populated label with the result of the ToString method

### Actual Behavior
The labels are empty

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Mac & Visual Studio Windows 15.9.4
- Platform Target Frameworks: 
  - iOS:  3.4
  - Android: 3.4
  - UWP:  Not Tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
https://1drv.ms/u/s!AuJWJQUKZPJor6dQ7NzeyUH7XngFog

**Comment by hartez** [comment] 2018-12-14 23:40
This is a duplicate of #3715.

**Comment by hartez** [comment] 2018-12-14 23:42
This should be fixed in the next service release for 3.4 or the next full release.

**Closed by hartez** 2018-12-14 23:42 UTC
Labels: t/bug :bug:
