### ISSUE TITLE
[Bug] Xamarin.Android min version 6.0 make app crash

### ISSUE THREAD

**Issue by albilaga** [xamarin/Xamarin.Forms#11719] opened 2020-08-09 14:30 UTC
# Description
Xamarin.Forms with android project set to min version to API level 23 (Android 6.0) is crashing in startup when build using Visual Studio for Mac. Previous Visual Studio for Mac working fine. Not tested in Visual Studio for Windows. 
Xamarin.Android project only also working fine.
### Steps to Reproduce

1. Create new Xamarin.Forms project.
2. Set Android `Minimum Android Version` to API level 23 (Android 6.0)
3. Run the app

### Expected Behavior
Application working as usual
### Actual Behavior
Application Crashes on startup
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio for Mac 8.7 (build 2037)
- Platform Target Frameworks:
  - Android: Android 10.0
### Workaround
Set `Minimum Android Version` to API level 21 (Android 5.0)

**Comment by rmarinho** [comment] 2020-08-10 11:36
Hi @albilaga just tried some samples and seems to work. can you upload a sample for what fails for you so we can identify the issue?

Thanks

**Comment by albilaga** [comment] 2020-08-10 13:07
[test.zip](https://github.com/xamarin/Xamarin.Forms/files/5050910/test.zip)
@rmarinho this is not working (crash on startup) on my machine on android emulator with Android Q . You can try change min version to v21 and it is working again.

**Comment by rmarinho** [comment] 2020-08-10 14:12
```
08-10 15:06:59.225 D/Mono    (10175): Requesting loading reference 4 (of 8) of Mono.Android.dll
08-10 15:06:59.225 D/Mono    (10175): Loading reference 4 of Mono.Android.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
08-10 15:06:59.226 D/Mono    (10175): Image addref System[0xebd587c0] (asmctx DEFAULT) -> System.dll[0xde854b00]: 2
08-10 15:06:59.226 D/Mono    (10175): Prepared to set up assembly 'System' (System.dll)
08-10 15:06:59.226 D/Mono    (10175): Assembly System[0xebd587c0] added to domain RootDomain, ref_count=1
08-10 15:06:59.241 D/Mono    (10175): Config attempting to parse: 'System.dll.config'.
08-10 15:06:59.241 D/Mono    (10175): Assembly Ref addref Mono.Android[0xebd58100] -> System[0xebd587c0]: 2

=================================================================
	Native Crash Reporting
=================================================================
Got a SEGV while executing native code. This usually indicates08-10 15:06:59.243 D/Mono    (10175): Requesting loading reference 0 (of 5) of System.dll

08-10 15:06:59.243 D/Mono    (10175): Loading reference 0 of System.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

No native Android stacktrace (see debuggerd output).

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xf3018dfb):0xf3018deb  
cc cc cc cc cc 8b 54 24 04 8b 44 24 08 0f b6 08  ......T$..D$....
0xf3018dfb  38 0a 0f 85 4d 14 00 00 83 f9 00 0f 84 4e 14 00  8...M........N..
0xf3018e0b  00 0f b6 48 01 38 4a 01 0f 85 37 14 00 00 83 f9  ...H.8J...7.....
0xf3018e1b  00 0f 84 38 14 00 00 0f b6 48 02 38 4a 02 0f 85  ...8.....H.8J...

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
08-10 15:06:59.245 F/libc    (10175): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6f63736d in tid 10175 (om.pradana.test), pid 10175 (om.pradana.test)
```

Seems strange ..
API29 sim doesn't work
API28 sim works
API27 sim doesn't work

**Comment by albilaga** [comment] 2020-08-10 18:02
Yep. Confirmed also working on API28 sim works on VS Mac. Not sure why it is suddenly not working. I remember clearly before it is working on API29 sim with same xamarin.forms version so I suspect it is VS for mac or Android SDK.

**Comment by rmarinho** [comment] 2020-08-11 10:04
@albilaga it might be this issue https://github.com/xamarin/xamarin-android/issues/4983

**Comment by albilaga** [comment] 2020-08-11 10:08
@rmarinho that sound same but then I already tried xamarin.android native it is working fine though?

**Comment by grendello** [comment] 2020-08-11 10:57
@albilaga it will work if you don't use AndroidX components which include manifest merger use. The manifest merger with flip the `extractNativeLibs` to `false` and thus trigger the Android bug. I'm certain this issue is a duplicate of https://github.com/xamarin/xamarin-android/issues/4983 - please use [this workaround](https://github.com/xamarin/xamarin-android/issues/4983#issuecomment-670603943) until the fix is released.

**Closed by grendello** 2020-08-11 10:57 UTC
Labels: a/buildchain, p/Android, t/bug :bug:
