### ISSUE TITLE
PanGestureRecognizer PanUpdated is not fired with StatusType.Completed

### ISSUE THREAD

**Issue by RedasP** [xamarin/Xamarin.Forms#5151] opened 2019-02-06 22:03 UTC
### Description

PanGestureRecognizer PanUpdated is not fired with StatusType.Completed when I swipe out of the view bounds. 

### Steps to Reproduce

1. Add a PanGestureRecognizer to ListView cell
2. Start swiping the item and swipe out of cell bounds
3. Release the finger when out of bounds
4. Tap the cell

### Expected Behavior

Swiping out of cell bounds should fire PanUpdated with StatusType.Completed

### Actual Behavior

Swiping out of cell bounds doesn't fire PanUpdated with StatusType.Completed. It fires the PanUpdated with StatusType.Completed when I swipe out of bounds, release the finger and tap the cell

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 7.0

### Reproduction Link

https://github.com/RedasP/PanGestureRecognizerDemo

**Comment by samhouts** [comment] 2019-02-06 22:55
Duplicate of #1977

**Closed by samhouts** 2019-02-06 22:55 UTC
Labels: t/bug :bug:
