### ISSUE TITLE
ListView should report index of item on all events

### ISSUE THREAD

**Issue by nielsenko** [xamarin/Xamarin.Forms#2811] opened 2018-05-23 14:33 UTC
## Summary
On `ListView`, add a `SelectedIndex` property. Also, add `Index` (of item) property to `ItemTappedEventArgs`, `SelectedItemChangedEventArgs` and `ItemVisibilityEventArgs`, used by `ItemTapped`,  `ItemSelected`, `ItemAppearing` and `ItemDisappearing` respectively.

## Intended Use Case
Today we need to call `IndexOf(item)` to get the index in the list, which is inefficient for most collection types. This can be avoided since the listview must track this information already.

**Comment by nielsenko** [comment] 2018-05-24 06:56
Say fx I wan't to show the item index on the cell, then I could trigger that efficiently from `ItemAppearing`

Another use case could be that I need to now neighbours of selected/tapped item.

I can always get the index by doing a `IndexOf(item)` but that is almost always an `O(n)` operation.

**Comment by tlhintoq** [comment] 2018-07-17 23:20
#3324 was just closed as duplicate of this issue.
However I think the actual purpose of#3324 is a bit different.
So in addition to the "reporting of" that this issue describes, `ListView` should also allow **setting** in the same way that a `Picker` does, and in keeping consistent with WPF ListView.

In other words: We need a matching `SelectedIndex` property that is both `get` and `set`.  Setting to -1 should deselect.

> There is no way to DE-select by index in a ListView like there is in a Picker, or like other Microsoft technologies such as WPF.
> Normally we would de-select in a Picker by setting the SelectedIndex to -1. The same is done in a WPF ListView.
> 
> But this property seems to have been overlooked in the Xamarin ListView.

**Closed** 2019-01-29 03:48 UTC
Labels: API-change, t/enhancement ➕
