### ISSUE TITLE
[Bug][iOS] Concurrent issue leading to crash in SemaphoreSlim.Release in ObservableItemsSource

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#11853] opened 2020-08-19 17:00 UTC
### Description
Calls to `ObservableItemsSource.BatchUpdate` should be synchronized to prevent a crash in _batchUpdating.Release(), because this last one can be called 2 times in a row and will fail the second time.

https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

### Steps to Reproduce
I am able to reproduce this issue easily in my customer's app. 
I've already checked that all calls are done on the main thread.

It happens nearly everytime when updating the bound ObservableCollection 3 times in a row: 
1st deleting some items, 2nd inserting some new items, 3rd moving some existing items (it's an algorithm that compute the changes between an ObservableCollection and a "new" list, and apply the 3 above actions so after the ObservableCollection becomes equal to the list).

I've already checked that all 3 calls are done on the main thread.

### Expected Behavior
don't crash

### Actual Behavior
crash when releasing the SemaphoreSlim because its CurrentCount is already 1.

Stack trace:
```
SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.

  at System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x0004c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/SemaphoreSlim.cs:795 
  at System.Threading.SemaphoreSlim.Release () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/SemaphoreSlim.cs:760 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.Reload () [0x00098] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:146 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.Add (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00037] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:165 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00061] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:117 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x000b7] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:108 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.2.2/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

```

### Basic Information

- Version with issue: 4.8
- Last known good version: 4.5
- IDE: VS Windows
- Platform Target Frameworks:
  - iOS:  latest stable
- Affected Devices: iOS simulator

### Reproduction Link

Repro app: https://github.com/softlion/ReproFormsCollectionViewBug
Run the app on an iOS simulator or device.

Tested on iOS 12.4 / iPhone 6 simulator.
But happens on all iOS OS and devices.

Does not happen on Android / UWP.

This app will trigger one of the 3 above crashes, which comes from different synchronization bugs.
The key is the change of the IsVisible property just before or after items have been added to the collectionviewsource.

### Workaround

None

### Other infos

I've checked the xamarin forms source code.

I'm pretty sure you can fix it easily by making BatchUpdate return a Task, then start BatchUpdate()  with `await _batchUpdating.WaitAsync();` instead of putting `_batchUpdating.Wait()` inside the `PerformBatchUpdates` action parameter.

**Comment by jsuarezruiz** [comment] 2020-08-24 14:09
@softlion Thanks for the feedback. Do you have a small example where reproduce the issue?.

**Comment by jsuarezruiz** [comment] 2020-08-24 14:12
This are the possible changes: https://gist.github.com/jsuarezruiz/341a2eea56dd9205729c317912b0bee5#file-gistfile1-txt-L362

**Comment by softlion** [comment] 2020-08-30 18:14
I'm unable to reproduce the issue in a demo project.
So i'll double check that all calls are done on the main thread.

**Comment by acuntex** [comment] 2020-08-30 18:27
I can also confirm that I have days where it does not happen at all. But suddenly when my system is under load I sometimes get these exceptions in the iOS simulator.

I was using the ObservableRangeCollection by @jamesmontemagno and did add about 25 elements when the error occurs regularly.

It happens during the ItemThresholdCommand of a CollectionView, so my guess was that it's on the main thread anyway.

**Comment by softlion** [comment] 2020-08-31 11:01
Ok I have a repro project ! I'll post it here.

**Comment by softlion** [comment] 2020-08-31 11:26
Repro app: https://github.com/softlion/ReproFormsCollectionViewBug
Run the app on an iOS simulator or device.

Tested on iOS 12.4 / iPhone 6 simulator.
But happens on all iOS OS and devices.

Does not happen on Android / UWP.

**Comment by softlion** [comment] 2020-09-24 12:00
Please fix it fast as i gave you a 1 line change solution + a repro app.

I've PR only once in Forms and it's 4 years ago. I'm not sure how much time it will now require to: clone the repo / build a local nuget / add all forms projects to the repro app / make sure the issue still triggers / fix it / rebase the repo / create a fix branch / push / commit / pr / receive feedbacks / re-rebase / re-commit

**Comment by lafritay** [comment] 2020-10-05 11:02
@samhouts @hartez FWIW, we're seeing this error happen often in production as well on 4.7.0.latest. @softlion Thanks for the great details in the bug. Would really appreciate traction on this bug given a fix has already been proposed.

**Comment by denisgeom** [comment] 2020-10-05 20:59
I also use CollectionView on a ContentPage. When I return to previous Page I always get the exception shown below.
This only happen if the collection has more than one item. This does not happen with just one item and it also works fine with UWP and Android. It only happen with iOS. This is a show stopper and not sure of a work around. Please fix it ASAP or provide a work around. Thanks.

◢ | $exception | {System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.   at System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x0004c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/SemaphoreSlim.cs:795    at System.Threading.SemaphoreSlim.Release () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/SemaphoreSlim.cs:760    at Xamarin.Forms.Platform.iOS.ObservableItemsSource.Reload () [0x00098] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:146    at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00198] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:129    at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x000b7] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:108    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021    at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/Foundation/NSAction.cs:178    at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:86    at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:65    at Geometrics.AtomDownloader.iOS.Application.Main (System.String[] args) [0x00001] in C:\Project\XappsDev\AtomDownloaderXF\AtomDownloader.iOS\Main.cs:12 } | System.Threading.SemaphoreFullException

**Comment by michaelstonis** [comment] 2020-10-06 23:20
We've just updated a handful of apps to 4.8, from 4.4 and 4.5, with no other NuGet packages and we are seeing the same issues.

**Comment by bruzkovsky** [comment] 2020-10-21 13:24
This issue is really easy to reproduce: Just fire one change event (`Add`/`Remove`) and right afterwards a `Reset` -> boom 💣💥. Looking at the implementation of `BatchUpdates`, it becomes very clear as to why that is:

```c#
void BatchUpdate(Action update)
{
	_collectionView.PerformBatchUpdates(() =>
	{
		if (_batchUpdating.CurrentCount > 0) // if the semaphore is empty, just ignore it ¯\_(ツ)_/¯ what bad should happen?
		{
			_batchUpdating.Wait();
		}

		update();
	},
			(_) =>
			{
				if (_batchUpdating.CurrentCount == 0) // anyway, I think we should release it, but only if it is not full already...
				{
					_batchUpdating.Release();
				}
			});
}
```

How on earth did this pass code review?

**Comment by softlion** [comment] 2020-11-01 07:05
@bruzkovsky I do have a clean implementation of this for mvvmcross. Along with a clean implementation of a range observable collection perfectly woirking with that (much older that the one your tech guru created some years ago). My code was started 6 years ago and is fully stable on hundreds on devices.

But this is a code that took me a very long time to architecture and build. I have nights on this. And i'm not 13th anymore (i'm 48 lol).

So i have some difficulties to give it to the open source community. Especially indian peoples that steal my mobile dev job (sorry mates but its true). I'm already an open source contributor with great components i hope, and xamarin forms core code contributions too, so it's not a problem of open source.

**Comment by bruzkovsky** [comment] 2020-11-01 09:04
@softlion I'm sorry I cannot follow you. I didn't mean to suggest that you have to do anything, the problem is entirely on the XF side. I wanted to show that the ObservableItemsSource in its current state does not even work correctly with a plain ObservableCollection. My point is that the problem is more complicated than just the wrong use of `SemaphoreSlim`, therefore I proposed a refactoring of the whole `ObservableItemsSource` class in my PR, which also fixes this issue. It should also work with any `ItemsSource` that implements `INotifyCollectionChanged` correctly.

**Comment by softlion** [comment] 2020-11-10 11:34
@bruzkovsky Any way to get this without waiting for an XF update ? Maybe using a custom renderer ?

**Comment by bruzkovsky** [comment] 2020-11-10 12:56
@softlion I built my own package including the fix, but that's actually pretty easy to do.

```
git clone https://github.com/bruzkovsky/Xamarin.Forms.git
cd Xamarin.Forms
git checkout fix-11853
./build.ps1 -Target NugetPack -ScriptArgs '-packageVersion="4.8.0-custom.1"'
```

Then use the package in a local nuget package source.

**Comment by softlion** [comment] 2020-11-10 16:16
@bruzkovsky I added your version to the Xamarin.iOS project only. It should replace any other versions coming from libraries ?

If yes, it still has the semaphore issue.

**Comment by bruzkovsky** [comment] 2020-11-10 16:31
@softlion ugh, than can only mean that you don't have the right dll, because I deleted the SemaphoreSlim code [here](https://github.com/bruzkovsky/Xamarin.Forms/commit/6925450d2c1e75498c84518332f875f377ba8578#diff-68717d4cab9003e856fc58ef65d30e52a35d8c773a073197b760d5a563edd306L18) and [here](https://github.com/bruzkovsky/Xamarin.Forms/commit/6925450d2c1e75498c84518332f875f377ba8578#diff-c56a9e81e503bf46cc3b4763558b7a6e9359d559471dd2acd7b786fa6f4224aeL19). But nuget should take the version that you have in your .iOS or .Android project, unless it's lower. Maybe you have to rebuild? Sometimes on iOS it just keeps the cached dlls.

**Comment by softlion** [comment] 2020-11-10 16:52
@bruzkovsky rebuild worked. Ty!

**Comment by Elashi** [comment] 2020-11-10 23:16
> @bruzkovsky I do have a clean implementation of this for mvvmcross. Along with a clean implementation of a range observable collection perfectly working with that, much powerful than the one they put in .net5, and much older that the one your tech guru created some years ago. My code was started 6 years ago and is fully stable on hundred devices in a dozen of apps. It would be easy for me to move that to xamarin forms.
> 
> But this is a code that took me a very long time to architecture and build. I have nights on this. And i'm not 13th anymore (i'm 48 lol).
> 
> So i have some difficulties to give it to the open source community. Especially indian peoples that steal my mobile dev job (sorry mates but its true). I'm already an open source contributor with great components i hope, and xamarin forms core code contributions too, so it's not a problem of open source.

Hi @bruzkovsky ,
Today, I got the same exception you found here.  I previously came across other crashes, and I spent long days and nights to trace it, prepare a sample, and I even fixed it and shared it with XF.  But today, I did not have to do all of this work, thanks to you. You saved me a lot of time.

But please, accept my words here.  Xamarin community has offered us piles of free code that a lot of people spent thousands of days on. And they provided it to us for free and probably a lot of them were Indians.  I understand that an 
Indian person had hurt you in the past but remember it is not because he was Indian ;) .

One last thing, last year I submitted a fix that was only one line of code.  Xamarin team spent a lot of time reviewing my code, testing it, refactoring it etc.  At the end, they used different code but still they were kind enough to give me the credit by pulling the commit under my name.  I encourage you to share your code.

I wish you the best.

**Comment by softlion** [comment] 2020-11-11 08:40
@bruzkovsky I still have one crash. 
![image](https://user-images.githubusercontent.com/190756/98788860-bda1d900-2401-11eb-8cf3-2e1b69867f65.png)

```
{System.ObjectDisposedException: Cannot access a disposed object.Object name: 'GroupableItemsViewController`1'.  at Foundation.NSObject.get_SuperHandle () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/Foundation/NSObject2.cs:401   at UIKit.UIViewController.get_IsViewLoaded () [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIViewController.g.cs:2147   at Xamarin.Forms.Platform.iOS.ObservableItemsSource.NotLoadedYet () [0x00001] in D:\repos\_clones\Xamarin.FormsCollectionViewFixed\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:286   at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00001] in D:\repos\_clones\Xamarin.FormsCollectionViewFixed\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:130   at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x000ba] in D:\repos\_clones\Xamarin.FormsCollectionViewFixed\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:124   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/Foundation/NSAction.cs:178   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIApplication.cs:86   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIApplication.cs:65   at WzXam2.iOS.Application.Main (System.String[] args) [0x00001] in C:\Dev\repos\MyApp\MyApp.iOS\Lib\Startup\Main.cs:12 }
```

**Comment by mduchev** [comment] 2020-11-11 08:49
@softlion This is another nasty issue, which doesn't seem to be fixed soon...
https://github.com/xamarin/Xamarin.Forms/issues/8308

**Comment by Elashi** [comment] 2020-11-11 11:00
In my case it happens when I delete entries of a list in a loop as follows:
```
var count = list.Count;
for (int i = 0; i < count; i++)
  list.RemoveAt(0);
```
But if I just call Clear I don't get the error
`list.Clear();`

**Comment by softlion** [comment] 2020-11-16 17:53
Still not fixed in Xamarin Forms 5 prerelease

![image](https://user-images.githubusercontent.com/190756/99289275-06f88b00-283d-11eb-9185-00efccb4fa4b.png)

**Comment by mduchev** [comment] 2020-11-16 17:57
@softlion Yes, the issue #8308 is still open. Please upload a repro there, if you can, so that they can fix it quickly.

**Comment by bruzkovsky** [comment] 2020-11-27 13:46
Hi @softlion , sorry for the delay, busy week...
I still have my fix targeted on 4.8, but I think I'll have to switch to 5.0.0 to get my PR merged anyway. Your error looks like it could be solved by restarting VS or your machine. Did you succeed in applying the change?

**Comment by softlion** [comment] 2020-11-27 20:20
No I have not been able to fix the build issue.

About your workaround, it duplicates the content of the list. This is not optimal.

I do have an implementation of this for mvvmcross which is both efficient and safe.

It does freeze the list state between updates but does not duplicate the items.

**Comment by bruzkovsky** [comment] 2020-11-27 20:37
@softlion so please share it then :)

Strange that the items are duplicated. I tested the fix with a lot of rapid modifications to the list and didn't find any issue. But I still want to test it in our production app next week, maybe I'll find more errors there...

**Comment by mfmadsen** [comment] 2020-12-02 10:01
We are seeing this issue as well using Xamarin.Forms 4.8.
@bruzkovsky Is a fix for this issue expected to be released anytime soon (either for Xamarin.Forms 4.8 (preferably) or for Xamarin.Forms 5)?

**Comment by mfmadsen** [comment] 2020-12-02 14:51
@bruzkovsky I tried following the steps you outlined above to build our own custom nuget version from your branch:
```
git clone https://github.com/bruzkovsky/Xamarin.Forms.git
cd Xamarin.Forms
git checkout fix-11853
./build.ps1 -Target NugetPack -ScriptArgs '-packageVersion="4.8.0-custom.1"'
```
I get the same error as softlion describes above:
```
"C:\Repos\Xamarin.Forms\Xamarin.Forms.sln" (Build target) (1) ->
"C:\Repos\Xamarin.Forms\Xamarin.Forms.ControlGallery.WindowsUniversal\Xamarin.Forms.ControlGallery.WindowsUniversal.csp
roj" (default target) (27) ->
(_ComputeAppxPackagePayload target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Micro
soft.AppXPackage.Targets(1943,5): error APPX1111: Payload contains two or more files with the same destination path 'Xa
marin.Forms.Xaml.pdb', but they are different sizes. Source files:  [C:\Repos\Xamarin.Forms\Xamarin.Forms.ControlGaller
y.WindowsUniversal\Xamarin.Forms.ControlGallery.WindowsUniversal.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microso
ft.AppXPackage.Targets(1943,5): error APPX1111: C:\Repos\Xamarin.Forms\Xamarin.Forms.Controls\bin\Debug\netstandard2.0\
Xamarin.Forms.Xaml.pdb [C:\Repos\Xamarin.Forms\Xamarin.Forms.ControlGallery.WindowsUniversal\Xamarin.Forms.ControlGalle
ry.WindowsUniversal.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microso
ft.AppXPackage.Targets(1943,5): error APPX1111: C:\Repos\Xamarin.Forms\Xamarin.Forms.Platform.UAP\bin\Debug\uap10.0.143
93\Xamarin.Forms.Xaml.pdb [C:\Repos\Xamarin.Forms\Xamarin.Forms.ControlGallery.WindowsUniversal\Xamarin.Forms.ControlGa
llery.WindowsUniversal.csproj]
```

I also tried adding `-Configuration 'Release' to the last command, but get the same result. 

Any thoughts on how to fix this build issue? I did try restarting my machine as you suggested above.

**Comment by mfmadsen** [comment] 2020-12-03 13:08
I have now successfully build a custom nuget package based on newest 4.8.0 branch combined with updates from @bruzkovsky. This fixes the issue we saw. Looking forward to an official update/release though :-)

**Comment by softlion** [comment] 2020-12-08 08:53
@mfmadsen could you share your github/branch with the updates ?

**Comment by mfmadsen** [comment] 2020-12-08 09:23
@softlion, yes that is the repo we are currently using to build our temporary custom nuget package for 4.8 Xamarin.Forms. I was never able to build the repo from @bruzkovsky directly, so instead I cloned the Xamarin.Forms repo and then replaced the contents of the three updated files in Xamarin.Forms.Platform.iOS/CollectionView (ListSource.cs, ObservableGroupedSource.cs and ObservableItemsSource.cs). After that I was able to build. It seems some changes was made in the original Xamarin.Forms repo that fixes the build issues we both were seeing when trying to build the branch from @bruzkovsky.

**Closed** 2020-12-17 00:31 UTC
Labels: a/collectionview, e/5 :clock5:, i/high, p/iOS 🍎, t/bug :bug:

**Comment by Tommigun1980** [comment] 2020-12-18 10:11
I wonder if https://github.com/xamarin/Xamarin.Forms/issues/13126 (ie filling an ObservableCollectionView while is related to this, as it shares several characteristics (toggling IsVisible alters behavior, the ObservableCollection sends only one update event and so on).

Thank you @softlion for your work. It’s discouraging to see how many bugs you found in the “fixes”. Xamarin needs to step up their testing. It’s getting to a point where the expectation is that things won’t work :/

**Comment by Tommigun1980** [comment] 2020-12-18 10:24
> EDIT: the custom code they put in XamarinForms 5 pre5 don't work at all. The one in the 5.0.0 branch don't work at all too. Among the issues: crash when the view is on a page in the stack (ie: another page has been pushed), crash randomly, displays no item (related to offscreen composition too).
> 
> EDIT2: ok you really need me to fix this mess. Ok then i'll take 4 hours to fix this shit.
> 
> EDIT3:
> Console log when no item is displayed (wrongly, as the collection does contain 1 item).
> It's a timing problem. If i add Console.WriteLine calls or ConfigureAwait(false) it works ok.
> 
> ```
> *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:], UICollectionView.m:7088
> dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
> dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
> dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
> ```
> 
> Also this version has a limitation to 1 item added at a time for animations to work. Otherwise it will simply reload the whole list, loosing the current scroll position. Making lazy loading impossible. Especially it does not support AddRange, RemoveRange, ReplaceRange, MoveRange. Nor collection change transactions.
> 
> EDIT 4: easy repro: the collection stays empty if the control is in a page which is not attached to a parent yet, event if the ObservableCollection has data, and stays empty even after the page is attached (for example as a Detail of a MasterDetail page).
> 
> @mfmadsen Good news the fix of your fix is in XamarinForms 5 pre5 (you used async for nothing in your fix).
> 
> ```
> git checkout tags/beta-5.0.0-pre5
> ```
> 
> And to compile it you need a fix to your VS as explained in this solution: https://developercommunity.visualstudio.com/content/problem/1256345/uwp-build-fails-after-update-to-1682-error-msb3774.html

@softlion The regressions you mentioned in the 5.0.0 branch, is there any chance you could make a new bug report about them as I think they’ll get buried as this has now been closed?

**Comment by softlion** [comment] 2020-12-18 10:39
@Tommigun1980 @hartez completely rewrote a fix, removing all the new code from above, and the semaphore and all other thing.

i have not tested it yet as I moved things in my customer app to workaround these issues.

i hope it’s quality is better! ;)

**Comment by Tommigun1980** [comment] 2020-12-18 10:57
> @Tommigun1980 @hartez completely rewrote a fix, removing all the new code from above, and the semaphore and all other thing.
> 
> i have not tested it yet as I moved things in my customer app to workaround these issues.
> 
> i hope it’s quality is better! ;)

Oh good to hear, really looking forward to testing those fixes as there's a good chance they will fix https://github.com/xamarin/Xamarin.Forms/issues/13126 also! Thanks for the info, I appreciate it.
