### ISSUE TITLE
[Bug] The page does not display correctly when searching in Shell.SearchHandler

### ISSUE THREAD

**Issue by MarcoSal** [xamarin/Xamarin.Forms#13650] opened 2021-02-04 08:27 UTC
### Description
after updating to xforms 5, SearchHandler incorrectly displays ...
Tested on emulator and on physical device, with android 9, 10, 11.
I also downloaded the updated xanimals example and the error is present.
It doesn't happen with xforms 4.8.
![image](https://user-images.githubusercontent.com/14003882/106865073-f680df80-66ca-11eb-82af-04a05c75957c.png)

### Steps to Reproduce

1. download above sample ;
2 .run it on device emulator 9.0 or 10.0;
3. and when we enter some key words into above SearchHandler, the page does not display correctly.

### Expected Behavior
![image](https://user-images.githubusercontent.com/14003882/106865120-0a2c4600-66cb-11eb-82a8-c41189cdbf7d.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/14003882/106865144-13b5ae00-66cb-11eb-9cfb-5454e857803d.png)

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment] 2021-02-04 16:12
Hi, @MarcoSal - thanks for submitting this issue!

> download above sample ;

Did you mean to attach a sample? If so, would you mind sharing it again? I'm unfortunately not seeing any link

**Comment by MarcoSal** [comment] 2021-02-04 20:12
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/

**Comment by MarcoSal** [comment] 2021-02-08 16:24
any update?
I have tried in other APPs and it has some strange behavior ...

**Comment by rachelkang** [comment] 2021-02-08 18:30
Hi, @MarcoSal! Yes, we're aware of this issue (i.e. duplicate of #13403) and it will be fixed in #13658 :)

**Closed by rachelkang** 2021-02-08 18:30 UTC
Labels: a/searchbar, a/shell :shell:, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
