### ISSUE TITLE
[Bug] IndicatorView shrinks on iOS 14 for HorizontalOptions Center and CenterAndExpand 

### ISSUE THREAD

**Issue by pmahend1** [xamarin/Xamarin.Forms#12318] opened 2020-09-30 19:54 UTC
### Description
When IndicatorView is set with HorizontalOptions Center or CenterAndExpand it shrinks or hides.
This issue was not there in earlier versions Xamarin iOS. This doesnt happen for Android.

### Steps to Reproduce

1. Create a `CarouselView` and `IndicatorView`
2. Link `IndicatorView` to `CarouselView`
3. Set `HorizontalOptions` to `Center` for `IndicatorView`
3. Run on iOS Simulator with OS 14.0
4. Run on iOS Simulator with OS <14.0

### Expected Behavior

IndicatorView should not shrink

### Actual Behavior

IndicatorView shrinks horizontally for HorizontalOptions Center and CenterAndExpand.

### Basic Information

- Version with issue: 14.0
- Last known good version: Xamarin.iOS < 14.0
- IDE: Visual Studio Windows and Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:   14.0
- Android Support Library Version: 
- Nuget Packages: Xamarin forms 4.8+
- Affected Devices: iPhone and iPads

### Screenshots
<img width="856" alt="image" src="https://user-images.githubusercontent.com/21352870/94732543-643f8800-0334-11eb-886c-d4894284cbcd.png">

### Reproduction Link
[IndicatorViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5307932/IndicatorViewIssue.zip)

### Workaround
Setting HorizontalOptions to Fill or FillAndExpand or dont set at all

**Comment by Tommigun1980** [comment] 2020-10-02 15:34
My indicator views disappeared completely after updating to iOS 14, probably this same issue.

**Comment by Tommigun1980** [comment] 2020-10-02 17:08
My indicator views disappeared completely after updating to iOS 14.

The workaround above works, but only if

The indicator view is not inside a horizontal stack layout.
The indicator view is not inside a grid where the column width is set to auto.
The only way I was able to display the indicator view in iOS 14 was by placing it in a vertical stack layout, or hard-coding a column width if it's inside a grid; neither of which I can really do in my case.

Also, vertical options center on the indicator view no longer centers the indicator view on iOS 14, one has to use FillAndExpand.

**Comment by Tommigun1980** [comment] 2020-10-04 05:22
Is this a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/12028 ?

**Closed** 2020-10-29 15:56 UTC
Labels: a/carouselview, a/indicatorview, e/5 :clock5:, iOS 14, p/iOS 🍎
