### ISSUE TITLE
IsEnabled property being disregarded in button when there is a command

### ISSUE THREAD

**Issue by kevinvella** [xamarin/Xamarin.Forms#5665] opened 2019-03-22 09:57 UTC
### Description
IsEnabled property being disregarded in button when there is a command

### Steps to Reproduce

1. Make a button `<Button Command="{ Binding NextCommand }" Text="Next" IsEnabled="false" />`
2. Click on the button
3. It still executes the command

### Expected Behavior
Button should not execute the command

### Actual Behavior
Button executes the command

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: Not known
- IDE: Visual Studio for MAC Community Edition
- Platform Target Frameworks: 
  - iOS:  12.1
- Nuget Packages:
- Affected Devices: Not known

### Screenshots
NA

### Reproduction Link

[InputKitException.zip](https://github.com/xamarin/Xamarin.Forms/files/2995938/InputKitException.zip)

**Comment by samhouts** [comment] 2019-03-22 21:31
Duplicate of #4754

**Closed by samhouts** 2019-03-22 21:31 UTC
Labels: t/bug :bug:
