### ISSUE TITLE
[Android, iOS] NavigationPage.PopAsync() cause memory leak by still holding on popped Page

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1429] opened 2017-12-20 00:21 UTC
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=31171

### Description
Found with profiler that Task<Page> holds popped Page from the CurrentNavigationTask property of NavigationPage. 

Potential PR was closed and not merged. https://github.com/xamarin/Xamarin.Forms/pull/625

### Steps to Reproduce
Simple test case:
1) get start with Page1
2) navigate to Page2,
3) get back to Page1 with PopAsync() or back button.

### Basic Information

- Version with issue: 1.4.3

### Reproduction Link
[PagePopMemory.zip](https://github.com/xamarin/Xamarin.Forms/files/2369102/PagePopMemory.zip)

[XamarinFormsBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/1573715/XamarinFormsBugs.zip)

**Comment by emmielewis** [comment] 2018-08-01 18:35
What version of Xamarin is this fix in?  We are on 3.0.0.482510 and we are still experiencing the issue.

**Comment by MaxFe** [comment] 2018-08-02 07:59
We are on version 3.1.0.583944 and still have that problem. Has anyone an idea why that is?

**Comment by ewoody** [comment] 2018-08-29 19:15
I can reproduce this issue on iOS and Android with a simple sample in Xamarin.

**Comment by samhouts** [comment] 2018-09-04 20:33
Reopening for further investigation. @emmielewis @MaxFe @ewoody, Does the sample project attached to this ticket still exhibit the issue for you? If not, can you please alter it such that it does, or attach your own sample project to help us see what we missed? Thanks!!

**Comment by MaxFe** [comment] 2018-09-05 05:58
This example is not reproducing the memory leak. I tried to change it so that it will but was not successful in that 30 min. before work. I will try it this weekend.

**Comment by ewoody** [comment] 2018-09-05 13:36
bwn, I have changed the xamarin lib to be

<package id="Xamarin.Forms" version="3.1.0.697729" targetFramework="xamarinios10" />

**Comment by ewoody** [comment] 2018-09-05 13:36
`<package id="Xamarin.Forms" version="3.1.0.697729" targetFramework="xamarinios10" />`

**Comment by PureWeen** [comment] 2018-09-11 02:28
I attached a sample to the original issue with what @ewoody  posted using 3.2 pre 3

I only saw leaks Android related to the GestureManager

When I tested on UWP and iOS it looked like all resources were being collected properly

**Comment by rmarinho** [comment] 2018-09-12 08:45
they are up on Github already

**Comment by ewoody** [comment] 2018-09-12 09:58
![memoryleakpage](https://user-images.githubusercontent.com/6103698/45417560-bdbbb800-b682-11e8-8bd5-1bbbf6e3292c.png)

<packages>
  <package id="Xamarin.Forms" version="3.2.0.809874-pre3" targetFramework="xamarinios10" />
</packages>

No, iOS app, using 3.2 pre 3, after I push page2 and then click back for 13 times, you can see the page2 has 13 instances in Xamarin Profiler and the app memory usage keeps growing.

**Comment by salgiza** [comment] 2019-04-25 08:38
Any news on this bug? Yesterday I posted a question in the Xamarin.Forms forum that might seem related to this: https://forums.xamarin.com/discussion/155697/possible-memory-leak-in-xamarin-forms

There is more info on the post but, the two main things to take from it:
* It can be reproduced running one of the project templates included in VS for macOS.
* I have a project where this only happens when I use toolbar items (what?).

**Comment by vravindranath** [comment] 2019-11-23 07:48
Any update on this. The Xamarin forms 4plus version has also this issue. Even when the page disappears and it is removed from navigation stack the instances are active. This leads to memory crash in iOS. If there are open issues like this I believe Xamarin forms is not preferred for production scenarios. Looks like this bug is still open from last 2 years and there is no response. @samhouts. Any update??

**Comment by JKennedy24** [comment] 2020-01-24 12:21
+1 on this.

It makes it very hard to start looking for memory leaks when `NavigationPage` is holding onto the page when it should be disposed

**Comment by samhouts** [comment] 2020-07-24 20:13
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment] 2020-09-15 00:13
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2020-09-15 00:13 UTC
Labels: a/performance, e/4 :clock4:, i/high, in-progress, p/Android, p/iOS 🍎, s/needs-info ❓, t/bug :bug:

**Comment by javanjoel** [comment] 2021-02-26 21:37
Still an issue @samhouts

**Comment by javanjoel** [comment] 2021-02-26 21:40
@samhouts here's how I found the issue:

Create a page with a webview. 
In the webview there's a page that has an embedded YouTube video
PushModal that Page that contains the webView
Play the YouTube video
Close the modal while the youtube video is playing
You'll still hear the YouTube video playing long after the modal being "Popped" out of the stack.

NOTE that this happened to me in UWP and yet this thread is IOS and Android. So looks like this is across the board
