### ISSUE TITLE
Xamarin Forms increment command ++ increases by 2 instead of one

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14841] opened 2021-11-08 18:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Forms-increment-command--incre/1549312)._

---
Using Visual Studios Community Edition 16.11.4
Following tutorial by James Montemagno YouTube https://www.youtube.com/watch?v=GLfR2uosoSw
This should count the button clicks on the app instead shows double the number, i.e. click once on emulator and shows "you clicked two times". This occurs whether deploying to emulator or actual android device. 
Page copied below:

namespace democoffee. Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class CoffeeEquipmentPage : ContentPage
    {
        public CoffeeEquipmentPage()
        {
            InitializeComponent();
            LabelCount.Text = "Hello From Code Behind";
            ButtonClick.Clicked += ButtonClick_Clicked;

}
        int count = 0;
                private void ButtonClick_Clicked(object sender, EventArgs e)
        {
            count++;
            LabelCount.Text = $"You clicked {count} time(s)";

}
    }
}

---
#### Feedback Bot on 10/10/2021, 07:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment] 2021-11-09 08:51
Tried to reproduce without success:
[Issue14841.zip](https://github.com/xamarin/Xamarin.Forms/files/7503300/Issue14841.zip)

Could you attach a small sample where reproduce the issue?

**Comment by jenscski** [comment] 2021-11-09 13:08
If he have followed the tutorial, the button would be bound to the click handler in the xaml, AND in the code. So it would trigger twice ...

![image](https://user-images.githubusercontent.com/4134254/140929615-2921a6ef-5454-4b66-8d17-07c16c425a3b.png)

**Comment by jfversluis** [comment] 2021-12-23 15:16
Looks like a coding error! Thanks for your help @jenscski closing this for now

**Closed by jfversluis** 2021-12-23 15:16 UTC
Labels: t/bug :bug:, s/needs-repro ❔, s/needs-info ❓, s/unverified
