### ISSUE TITLE
[Forms] After converting to .NET Standart get error "No Bindable propery or type mistmatch"

### ISSUE THREAD

**Issue by Vampire2008** [xamarin/Xamarin.Forms#1368] opened 2017-12-11 07:34 UTC
Hello!
I have this xaml code:
```xml
<ViewCell.View>
      <StackLayout>
            <Label Text="{Binding Source={x:Reference Root},Path=Text}" FontSize="{x:Static modules:FontProvider.InfoUserFontSize}" TextColor="SeaGreen" Margin="5,0"/>
            <Label Text="{Binding Source={x:Reference Root},Path=Detail}" FontSize="{x:Static modules:FontProvider.InfoDetailFontSize}" Margin="5,0"/>
      </StackLayout>
  </ViewCell.View>
```
In PCL library all fine. But in .NET Standart FontSize display error "No property, bindable property, or event found for 'FontSize', or mismatching type between value and property".

Here is FontProvider.cs:
```csharp
public static class FontProvider
{
	public static double? InfoUserFontSize { get; set; }
	public static double InfoFontSize => InfoUserFontSize ?? 16;
	public static double InfoDetailFontSize => InfoFontSize - 2;
}
```
Same with IsVisible property with another element:
```xml
<modules:TimePickerNullable IsEnabled="{Binding Source={x:Reference StartSwitch}, Path=IsToggled}" NullableDate="{Binding StartTimeLabel,Mode=TwoWay}" IsVisible="{x:Static modules:UserSettings.NotUseTimeEntry}"></modules:TimePickerNullable>
```
IsVisible property is from base class TimePicker.

UserSettings.cs:
```csharp
public static class UserSettings
{
	public static bool UseTimeEntry { get; set; }
	public static bool NotUseTimeEntry => !UseTimeEntry;
}
```
### Basic Information

- Version with issue: 2.5.0 .NET Standart
- Last known good version: 2.5.0 PCL
- IDE: Visual Studio 2017 (15.5.1) Professional

**Comment by StephaneDelcroix** [comment] 2017-12-11 13:48
this is fixed in master by either #1281 or #1282

**Comment by StephaneDelcroix** [comment] 2017-12-11 14:40
likely a dupe of #1316

**Comment by dhaligas** [comment] 2017-12-13 03:35
@Vampire2008 i have the same issue.  it is hosed until they release a patch hopefully soon.

The workaround I did for the FontSize was to set that in Application.Resources and then use it in the xaml as a static resource

`` 
      app.Resources = new ResourceDictionary();
            app.Resources.Add("InfoUserFontSize", FontProvider.InfoUserFontSize);

<Label Text="{Binding Source={x:Reference Root},Path=Text}" FontSize="{StaticResource InfoUserFontSize}" TextColor="SeaGreen" Margin="5,0"/>``

**Closed** 2017-12-14 10:53 UTC
Labels: a/netstandard, t/bug

**Comment by NPadrutt** [comment] 2018-01-09 21:34
I get this issue on the current version (2.5.0.121934) with a platformspecific height:

```
<Button Text="foo"
            HorizontalOptions="FillAndExpand"
            Margin="3,0,3,0" >
        <Button.HeightRequest>
            <OnPlatform x:TypeArguments="x:Double">
                <On Platform="iOS" Value="37"/>
            </OnPlatform>
        </Button.HeightRequest>
    </Button>
```
Is that the same issue? Is there a workaround for that?
On a PCL projekt this also works but not in .net standard.
