### ISSUE TITLE
Xamarin.Forms CollectionView GroupHeaderTemplate works different in iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9535] opened 2020-02-12 01:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/903180/xamarinforms-collectionview-groupheadertemplate-wo.html)._

---
<p><a href="https://developercommunity.visualstudio.com/storage/attachments/116677-android.png"> Image:116677-android.png</a></p><p>Android is Correct:</p><p>iOS is Wrong:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/116678-ios.png"> Image:116678-ios.png</a></p><p>&quot;span&quot; is set in ContentPage.OnSizeAllocated()</p><pre><strong></strong><u></u><sub></sub><sup></sup>protected override void OnSizeAllocated(double width, double height)
        {
            base. OnSizeAllocated(width, height);
            var col = width / 90;
            Cll.ItemsLayout = new GridItemsLayout((int)col, ItemsLayoutOrientation.Vertical)
            {
                VerticalItemSpacing = 1,
                HorizontalItemSpacing = 1
            };
        }<br></pre>

---
#### Visual Studio Feedback System on 2/2/2020, 07:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment] 2020-02-12 01:54
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by angryarmyant** [comment] 2020-02-14 11:39
a small project:
https://github.com/angryarmyant/TestCollectionViewGroupHeader

**Comment by PureWeen** [comment] 2020-02-21 03:04
@angryarmyant this looks like this has been fixed with the latest code

I ran your sample and the headers are now going full width can you test on the latest 4.5 prerelease?

If it looks like there is still an issue I will re-open

**Closed by PureWeen** 2020-02-21 03:04 UTC
Labels: a/collectionview, feedback-ticket, p/iOS 🍎, s/unverified, t/bug :bug:

**Comment by angryarmyant** [comment] 2020-02-21 13:39
@PureWeen , I tried v4.5.0.282-pre4, the problem is not fixed!!!

**Comment by PureWeen** [comment] 2020-02-21 17:18
The next 4.5 is coming out soon and when I test there it works

If it's still not working after 4.5 stable we can reopen

![image](https://user-images.githubusercontent.com/5375137/75056048-69318480-5493-11ea-9e57-6396faedd513.png)
