### ISSUE TITLE
[Bug] Xamarin.Forms 4.5 breaks custom frame renderer shadow functionality on iOS

### ISSUE THREAD

**Issue by doriangh** [xamarin/Xamarin.Forms#9774] opened 2020-02-28 14:51 UTC
### Description

When making a custom frame renderer for iOS and changing the shadow properties, they do not get applied on Xamarin 4.5. Moreover, the custom renderer does not extend, but rather overwrite the Xamarin Forms implementation. 

### Steps to Reproduce

1. Make a new Xamarin Forms project
2. Create a custom frame renderer
3. Modify the shadow of the custom frame renderer

### Expected Behavior
The custom frame renderer extends the properties of the current frame, modifying only the shadow.
### Actual Behavior
The custom frame renderer does not affect the shadow, sets the default shadow.
### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: 4.4.0.991757
- IDE: Visual Studio for Mac
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: iOS

### Screenshots

How it should look:
![Screenshot 2020-02-28 at 16 24 45](https://user-images.githubusercontent.com/20998103/75556938-cc00be00-5a47-11ea-8aa2-103857096f14.png)

How it looks in Xamarin.Forms 4.5
![Screenshot 2020-02-28 at 16 37 52](https://user-images.githubusercontent.com/20998103/75557451-b5a73200-5a48-11ea-853e-0cbe61e64559.png)

### Reproduction Link

https://github.com/doriangh/Xamarin-Forms-4.5-issue

**Comment by hartez** [comment] 2020-03-03 00:23
Duplicate of #9265

**Comment by ashleypringle** [comment] 2020-03-03 17:37
We're also experiencing this problem. Reverting to Forms version 4.4.0.991265 fixed the issue.

**Comment by samhouts** [comment] 2020-03-31 21:18
closed by #10023

**Comment by doriangh** [comment] 2020-04-19 08:38
@samhouts I still can't get this to work with the exact definition in the latest XF 4.5 sr4 (4.5.0.617).

**Comment by liveinvarun** [comment] 2020-04-21 13:37
@samhouts This issue is still happening in 4.5.0.617 and pre versions too. Can you confirm which version has the fix and also reopen the ticket.

**Comment by cheles** [comment] 2020-05-04 07:58
it's still present in XF 4.6.0.726

**Comment by irshadka** [comment] 2020-05-14 17:24
Any fixes for this issue?

**Comment by doriangh** [comment] 2020-05-14 20:35
> Any fixes for this issue?

The only one I've been able to find is by following this: https://xamarinhowto.com/customising-ios-frame-shadows-in-xamarin-forms-4-5/
It still has some issues with a list of custom frames (if there are more than 6 custom frames in a list, it tends to alternate the custom shadow).

**Comment by irshadka** [comment] 2020-06-03 04:32
> > Any fixes for this issue?
> 
> The only one I've been able to find is by following this: https://xamarinhowto.com/customising-ios-frame-shadows-in-xamarin-forms-4-5/
> It still has some issues with a list of custom frames (if there are more than 6 custom frames in a list, it tends to alternate the custom shadow).

Yeah that solution is working fine

**Closed** 2020-06-09 14:51 UTC
Labels: a/frame, e/5 :clock5:, in-progress, p/iOS 🍎, t/bug :bug:
