### ISSUE TITLE
[Bug] RefreshView's command's CanExecute doesn't work properly

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#9457] opened 2020-02-07 01:11 UTC
This is not a regression in pre-3, but something I haven't had time to report yet.

Set up a RefreshView with a CollectionView, such as:
```
                <RefreshView IsRefreshing="{Binding IsBusyRefreshingActivityTypeRecommendations, Mode=OneWay}"
                             Command="{Binding RefreshActivityTypeRecommendationsCommand}" >
                    <CollectionView ItemsSource="{Binding ActivityTypeRecommendations}">
```

In the RefreshView's command, add a CanExecute section. No matter if CanExecute returns true or false, the RefreshView doesn't allow refreshing (drag to refresh just scrolls the view without a spinner. In fact the spinner is never shown). Removing the CanExecute section from the command makes the RefreshView work normally again. I have only used RefreshViews with CollectionViews, so I don't know if this is a generic problem (I'd guess it probably is).

**Comment by samhouts** [comment] 2020-02-07 22:48
@Tommigun1980  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by modplug** [comment] 2020-02-09 13:42
Sounds like it might be related to #9326

**Comment by samhouts** [comment] 2020-02-17 17:17
Duplicate of #9326

**Closed by samhouts** 2020-02-17 17:17 UTC
Labels: a/collectionview, a/refreshview :arrows_counterclockwise:, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
