### ISSUE TITLE
SanFrancisco (.SFUIText, .SFUI-Regular) fonts issue in iOS 13

### ISSUE THREAD

**Issue by MJRomka** [xamarin/Xamarin.Forms#8035] opened 2019-10-16 07:05 UTC
After updating to iOS 13 my fonts failed. In my App.xaml I had:

```
<OnPlatform x:Key="FontFamilyRegular" x:TypeArguments="x:String">
   <On Platform="iOS">.SFUIText</On>
</OnPlatform>
<OnPlatform x:Key="FontFamilyMedium" x:TypeArguments="x:String">
   <On Platform="iOS">.SFUIText-Medium</On>
</OnPlatform>
<OnPlatform x:Key="FontFamilyBold" x:TypeArguments="x:String">
   <On Platform="iOS">.SFUIText-Semibold</On>
</OnPlatform>
```
It all worked fine until I updated my device to iOS 13.

I debugged iOS project and find out that font names could be changed to: .SFUI-Regular, .SFUI-Semibold - but these do not work neither. Also I tried updating to the latest Xamarin version - no luck.

How can I use these 3 font families in the newest iOS version?

**Comment by xamarindevelopervietnam** [comment] 2019-10-16 08:26
same here!

**Comment by samhouts** [comment] 2019-10-17 21:22
@MJRomka  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by MJRomka** [comment] 2019-10-18 06:37
[testfonts.zip](https://github.com/xamarin/Xamarin.Forms/files/3742544/testfonts.zip)
As you can see red color is applied, but the font family is broken.

**Comment by kingces95** [comment] 2019-10-18 23:06
We believe you! But could you please attach a reproduction project?

**Comment by MJRomka** [comment] 2019-10-19 05:46
Don’t you see testfonts.zip file I attached to the previous message?

**Comment by hartez** [comment] 2019-10-28 22:38
Okay, the problem is that as of iOS 13, we're not supposed to load system fonts by name anymore. (Technically it's been advised against for a while, but iOS 13 actually enforces it by just giving you back Times New Roman when you ask for a system font.)

So, in Xamarin.Forms.Platform.iOS.FontExtensions.cs in the `_ToNativeFont` method, before we attempt to load the font using `UIFont.FromName`, we should check the family name for the `.SF` prefix; if it's there, we need to parse the UIFontWeight (Regular, Thin, Bold, etc.) and use `UIFont.SystemFontOfSize(size, weight);`.

That should give us the correct fonts going forward while remaining backward-compatible.

**Comment by hartez** [comment] 2019-10-28 22:39
Some reference material: https://developer.apple.com/videos/play/wwdc2019/227/  (relevant bits start around 2:46)

**Comment by MJRomka** [comment] 2019-11-07 09:25
Could you please give an official answer: should I go ahead and change my code overriding setting font family for iOS or you are going to fix it? Any estimations you can give in the second case?

**Comment by JFMG** [comment] 2019-11-07 09:36
@MJRomka I'm not from the official team but I'd suggest you to change your code for now and just leave the font family attribute empty on iOS to use the system font. However, you can set the font attribute **bold** to have at least a bit of differences in your fonts. Another alternative is that you write your own custom renderer to use UIFont.SystemFontOfSize(size, weight) by yourself.

In the meantime I try to contribute to this bug.

**Comment by MJRomka** [comment] 2019-11-07 09:47
Thank you @JFMG
The first option you suggested is actually a workaround I made: leaving a font family blank and using font Bold attribute, but it gives only two options of font weight when I need 3. And this is not a long term approach since I need to have separate branches for Android and iOS.
The second option you suggested sounds like a long term solution, but it requires resources which I'd not spend if Xamarin team is about to fix this really annoying issue.

**Comment by JFMG** [comment] 2019-11-07 15:53
@hartez I provided a fix. Please have a look and let me know if it fits.

**Comment by JFMG** [comment] 2019-11-07 15:58
@MJRomka If my fix is getting accepted, it will be available in XF 4.4.0

**Comment by seanrodda** [comment] 2019-12-03 03:20
@samhouts what needs to be done to get this merged into 4.4.0? I'd like to help out if anything is needed.

**Comment by rmarinho** [comment] 2019-12-10 12:33
Fixed by #8418

**Comment by rmarinho** [comment] 2019-12-10 12:34
Fixed by #8418

**Closed by rmarinho** 2019-12-10 12:34 UTC
Labels: e/2 :clock2:, iOS 13, in-progress, p/iOS 🍎, t/bug :bug:

**Comment by seanrodda** [comment] 2019-12-13 01:47
thanks so much for merging this in @rmarinho 
I'm guessing this will be in the next 4.4 release?

**Comment by JFMG** [comment] 2019-12-13 08:54
@seanrodda The fix should be in the current stable 4.4.0.991265 which was just released.

**Comment by seanrodda** [comment] 2019-12-13 09:52
@JFMG Thanks, I thought so too, however it does not seem to be in that build. I also decompiled and checked the code from the nuget package.

**Comment by JFMG** [comment] 2019-12-13 10:54
@seanrodda Looks like the fix will come in a later 4.4.0 release. Probably @samhouts knows more.

**Comment by jfversluis** [comment] 2019-12-13 11:27
Yeah it seems this just missed the cut for the 4.4 stable release. It should be available in the first 4.4 service release and the 4.5-pre1 which should be available soon.

**Comment by esenciadev** [comment] 2020-03-09 15:59
There appears to be a partial regression in 4.5.0.356, I am getting these messages in the log:

> CoreText note: Client requested name ".SFUIText-Medium", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].

However I don't see anything in my app actually rendering in TimesNewRoman. I will test in a repro project asap.

**Comment by mduchev** [comment] 2020-07-02 17:29
@esenciadev Any progress on the repro project?

**Comment by rscholey** [comment] 2020-07-03 01:34
@samhouts - Any update to this.  It seems to have been forgotten about but messages still appear in the logs.

**Comment by JFMG** [comment] 2020-07-03 05:34
The warning messages are new. But since this is a new behavior and the issue to actually see the Times New Roman font already got fixed, I suggest you to open a new issue.

**Comment by mduchev** [comment] 2020-07-06 10:35
@rscholey Are you seeing the messages in a brand new solution too? I just tried with latest Forms version and no warning messages appear. This sounds like some 3rd-party library, which is using older Forms version (before the fix).

**Comment by RuchiraMedtronic** [comment] 2023-03-06 18:30
I want to use the "**SFProDisplay-Bold**" font in iOS project but without adding the font files in the project as this font file is 2.2 MB and it increases the App size. To see what the default system font is, added the below code in our iOS project:
var systemFont = UIFont.SystemFontOfSize(20, UIFontWeight.Bold).Name; 
Debug.WriteLine($"System: {systemFont.FamilyName}"); 
This above code gave output from our project as follows -> System: .AppleSystemUIFont and the systemFont is **".SFUI-Bold"** I believe that SFUI and SF Pro Display are different fonts(correct me if wrong)as the name and output appearance has slight space difference .
The official site mentions SF Pro as the System font and has no mention for SFUI  https://developer.apple.com/fonts/ . This Wiki link says "SF Pro/SF UI" https://en.wikipedia.org/wiki/San_Francisco_(sans-serif_typeface) . Thus , here I see confusion whether SF Pro is named as SF UI OR both are different,also then what is the name for **SF Pro Display**?
It is not safe to directly use the font name in the code like .SFUI-Bold and I also dont know what is the name for SFProDisplay font.
So may be using renderer would be the other option but here too we need to use the above mentioned method only "UIFont.SystemFontOfSize" which will give me .SFUI .
Need more clarity for ways on how to implement specific font "SF Pro Display" OR what is the name for this font to be used with a "." in xaml (not safe but just need to know).
![Simulator Screen Shot - iPhone 11 - 2023-03-06 at 23 29 29](https://user-images.githubusercontent.com/127139614/223196078-dbe50ead-e6c0-4056-ae41-68d0e84023f2.png)
See above image where first two lines use the font file added in the code and next two lines use ".SFUIDisplay-Bold" which still shows slight space difference .
Font file added in the project is from official site but was added long back and also dont know the exact source.
@joshardt looking forward for your reply , also do we need to add any fix to use "SF Pro Display" as you have done for .SFUI
