### ISSUE TITLE
[Bug] Xamarin.Forms Image not work

### ISSUE THREAD

**Issue by blackcatpolice** [xamarin/Xamarin.Forms#9858] opened 2020-03-05 15:58 UTC
### Description
In some times Image not load image, 
First image : //assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png
this img can show in webbrowser , but not on my Simulator

Second image: http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Papio_anubis_%28Serengeti%2C_2009%29.jpg/200px-Papio_anubis_%28Serengeti%2C_2009%29.jpg
this image is  from official tutor => https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/image/?tutorial-step=1&tabs=vswin
Then , the second imguri is work on my simulator

### Steps to Reproduce

Same code :

>   <Image Source="http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Papio_anubis_%28Serengeti%2C_2009%29.jpg/200px-Papio_anubis_%28Serengeti%2C_2009%29.jpg"
               HeightRequest="300" />

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.908675
- Last known good version: Xamarin.Forms 4.3.0.908675
- IDE: Visuao Studio Mac Community 8.4.7
- Platform Target Frameworks: 
  - iOS:   Simulator iPhone 11 iOS 13.3
  - Android:  None
  - UWP:  None
- Android Support Library Version: None
- Nuget Packages: None
- Affected Devices:None 

### Reproduction Link
![image](https://user-images.githubusercontent.com/4312114/75999422-22d13080-5f3d-11ea-8577-611e316f0dbe.png)

### Workaround
No, I find many answer, like add a convert to Image Source binding , it also not working on my Simulator.

**Comment by blackcatpolice** [comment] 2020-03-05 16:17
##I think this is so funny , why I use your offical image the imagecell is work, I use my own uri it's not work ??

This so basic feature why is so hard to use ??? 

MS is the biggest bug factory, Apple is the second.

<img width="1680" alt="屏幕快照 2020-03-06 上午12 13 01" src="https://user-images.githubusercontent.com/4312114/76001277-d20f0700-5f3f-11ea-9d44-75f7196c0b10.png">

**Comment by blackcatpolice** [comment] 2020-03-05 16:36
![image](https://user-images.githubusercontent.com/4312114/76003031-77c37580-5f42-11ea-9751-cd6ea00e482c.png)


I found this repo with keyworkd "FromUri" , there  is another three isssue , and I ask google also have many items , why you cant fix this bug ???? It's so hard to fix ??? 

I look at you write many test  case for FromUri MediaSrouce , but they were useful truly?? 


Hope you can fix this question , I very very anxious

Thanks so much.

**Comment by PureWeen** [comment] 2020-03-05 16:46
@blackcatpolice this should be fixed on 4.4 and 4.5 can you try there?

**Comment by blackcatpolice** [comment] 2020-03-06 02:52
Thanks your message, I update my nuget package to Xamarin.Forms  4.5 and Xamarin.Essentials 1.5 and I clear my solution and rebuild all solution , it is also not work.

![image](https://user-images.githubusercontent.com/4312114/76045572-7d4baa80-5f98-11ea-9bcc-0f105f3cb59a.png)

**Comment by PureWeen** [comment] 2020-03-06 03:21
@blackcatpolice can you attach a repro?

**Comment by blackcatpolice** [comment] 2020-03-06 03:56
Thanks your message

Here is my code https://github.com/blackcatpolice/XamarinImageFromUriBugIssue

Thanks

**Comment by blackcatpolice** [comment] 2020-03-06 04:12
I try again , and I test tow formats image .

PNG: it's not work 

JPG: It's OK!

So, this Image Cell not work on png ? 
Or I need some special operation for png image?

Thaks ~

**Comment by blackcatpolice** [comment] 2020-03-06 06:58
The latest news !

I try use ffimage load uri : http://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png

it's work! 

And I check the image reponse header, this image format is image/webp , so this is the the reason
？？

But what I found a solution for this bug. And do you plan update this ImageCell class function , let it support all image format? Or can you include some package like ffimageloading to surpport all image formats?

I think display a network image is a basic feature, so if it not work will let me very anxious.

**Comment by jfversluis** [comment] 2020-03-19 21:02
I don't think WebP in a control is supported out of the box on iOS and that is why we don't support it as well. Sorry if that gave you trouble!

I did take a look at your reproduction and it seems that you have the SyncFusion license key in there, so you might want to take that down and see if you can regenerate a key because it's likely other people might have gotten it now.

**Closed by jfversluis** 2020-03-19 21:02 UTC
Labels: s/unverified, t/bug :bug:
