### ISSUE TITLE
[Bug] [macOS] navigation page doesn't hide previous page

### ISSUE THREAD

**Issue by melimion** [xamarin/Xamarin.Forms#7898] opened 2019-10-09 12:28 UTC
### Description

In some cases when you push page to NavigationPage, previous page is partly visible and gestures works on it

### Steps to Reproduce

1. disable animation here https://github.com/xamarin/Xamarin.Forms/blob/6fc502b2f1a4c707183c884fce7e6e46db3e620a/Xamarin.Forms.Controls/CoreGallery.cs#L497
change to 
await Navigation.PushAsync(contentPage, false);
2. open gallery app
3. navigate to "TemplatedTabbedPage Gallery - Legacy"

### Expected Behavior
only new page visible
### Actual Behavior
root page visible under tabs and click on root page parts works

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - macOS

 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![Screenshot 2019-10-09 at 15 27 08](https://user-images.githubusercontent.com/33512073/66481318-5486be00-eaa9-11e9-8032-2af2ebdce623.png)

**Comment by jfversluis** [comment] 2019-10-10 07:06
@melimion thanks for reporting this very specific case! 😄 

I assume that you didn't just find this in the gallery app but also in an app you are working on? It seems to happen mostly because of the segmented (like) control on the top, since I don't see it happening on other pages.

Would you be able to create a small reproduction sample that is more targeted towards how you are using it? That way it's easier to get to the root cause instead of trying to figure out if it's in this demo page or actually somewhere in our SDK code base.

Thanks!

**Comment by melimion** [comment] 2019-10-10 08:42
@jfversluis I think PR is better than repro )
You can find simple reproduction there.

**Comment by jfversluis** [comment] 2019-10-10 08:55
@melimion YES! Much better! Thanks! 😄

**Comment by samhouts** [comment] 2019-10-17 19:07
closed by #7921

**Closed by samhouts** 2019-10-17 19:07 UTC
Labels: in-progress, p/macOS, t/bug :bug:
