### ISSUE TITLE
Not called OnAppearing() in ContentPage included in CarouselPage

### ISSUE THREAD

**Issue by sinappsys** [xamarin/Xamarin.Forms#2985] opened 2018-06-08 11:31 UTC
This is the structure

[CorouselPage]
-> ContentPage 1
-> ContentPage 2
-> ContentPage 3
-> ContentPage 4

If I swipe from a ContentPage 1 to ContentPage 2/3/4 it is not called OnAppearing() in the current ContentPage. In the version of Xamarin.Forms 2.5.0.122203 it worked.
Now I have updated to 3.0.0.530893 and it does not work.

How can I solve?
Thank you

**Comment by jassmith** [comment] 2018-06-08 23:48
Dupe of #2951

**Closed by jassmith** 2018-06-08 23:48 UTC
