### ISSUE TITLE
[Bug] NSInternalInconsistencyException (iOS only) when inserting items into ObservableCollection bound to CollectionView

### ISSUE THREAD

**Issue by agat366** [xamarin/Xamarin.Forms#10025] opened 2020-03-19 13:15 UTC
I receive the following exception:

> Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (22) must be equal to the number of sections contained in the collection view before the update (22), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).

My page layout is:

```
<CollectionView Grid.Row="1" x:Name="lstImages"
                  VerticalOptions="FillAndExpand"
                  ItemsSource="{Binding MediaGroups}" 
                  SelectionMode="None"
                  IsGrouped="True">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" Span="3" HorizontalItemSpacing="0" VerticalItemSpacing="0" />
            </CollectionView.ItemsLayout>

```
The source is an observable collection, which also contains a list of groups as observable collection.

When I am trying to `insert` items into it, the app crashes. It's fine on first insertion, but it doesn't allow any further inserts.

- Xamarin.Forms 4.5.0.396
- Platform Target Frameworks: 
  - iOS:  13.1

**Comment by jfversluis** [comment] 2020-03-19 13:21
Thanks for the report @agat366! I feel bad for closing it so quickly, but this issue has been reported before. To not have information fragmented all over the place, please follow that issue to track the progress. If you have any information to add specific to your case, please feel free to do that!

**Comment by jfversluis** [comment] 2020-03-19 13:21
Duplicate of #9817

**Closed by jfversluis** 2020-03-19 13:21 UTC
Labels: s/unverified, t/bug :bug:

**Comment by agat366** [comment] 2020-03-19 20:13
Thanks @jfversluis for finding the duplicate. (It's strange I couldn't find it by myself. Google didn't provide it when looking with similar description).

**Comment by jfversluis** [comment] 2020-03-19 20:15
No worries, it happens! You could try the search here in the issues as well just to be sure. But don't worry about it. That is also what we are here for 😉 Hope it will be resolved quickly!
