### ISSUE TITLE
Cannot define ShellContent under FlyoutItem

### ISSUE THREAD

**Issue by louiswerth** [xamarin/Xamarin.Forms#6524] opened 2019-06-13 21:19 UTC
I am trying to create a flyout menu using the shell.

When I define the following line of code under <Shell>
`    <FlyoutItem Title="Browse" Icon="tab_feed.png">
        <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}"/>
    </FlyoutItem>`

it gives me the following error: 

> 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0503	A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'.	MyTestSystem	MenuPage.xaml	25	

Only the toolbar works. I do not want a toolbar, it want the items to be present in the flyout menu.

I am using Xamarin.Forms version: 4.0.0.497661
Microsoft Visual Studio Enterprise 2019
Version 16.1.2

Based on all the tutorials I can find on the internet this should be possible
Example: 
https://www.youtube.com/watch?v=BqSlfrsJEns

**Comment by operationslazlo326** [comment] 2019-06-13 22:16
Seeing the same issue as per screenshot below:
![image](https://user-images.githubusercontent.com/26207026/59470918-2d1b2f80-8dee-11e9-8de2-802189cc8d0a.png)

**Comment by jfversluis** [comment] 2019-06-14 08:11
Please do note that you can still run the app and it will work without any problem. This seems to be just a problem with the IntelliSense.

**Comment by jfversluis** [comment] 2019-06-14 08:54
Upon further inspection, this seems to be a duplicate of #3864 

Closing this item, please check the mentioned issue for the actual status. As said: this doesn't prevent you from working with this, just an editor warning.

**Closed by jfversluis** 2019-06-14 08:54 UTC
Labels: a/shell :shell:, external-intellisense, t/bug :bug:
