### ISSUE TITLE
Not able to include shell control 

### ISSUE THREAD

**Issue by jashif** [xamarin/Xamarin.Forms#6251] opened 2019-05-22 03:35 UTC
Hi

I tried the latest forms package in a new forms project . when tried to include shell control and added shellcontent as child . It still says it accept shellitem as its child. while building getting compile error also.

Tried to run the tailwind traders app. 

Error from visual studio 

Error	XLS0503	A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'.	TailwindTraders.Mobile	TheShell.xaml	69	

![image](https://user-images.githubusercontent.com/1052953/58163650-a195ff00-7c84-11e9-9769-46b9bd0c31cb.png)

**Comment by samhouts** [comment] 2019-05-28 20:18
Duplicate of #3864

**Closed by samhouts** 2019-05-28 20:18 UTC
Labels: a/shell :shell:, s/unverified, t/bug :bug:
