### ISSUE TITLE
Transparent Color When i Use LinearGradientBrush in Xamarin.Forms 5 Update in Listview Items

### ISSUE THREAD

**Issue by person2434** [xamarin/Xamarin.Forms#13392] opened 2021-01-13 16:16 UTC
i have the same issue in List View Items in Gradient Frame Control

_Originally posted by @Coding-BookMark in https://github.com/xamarin/Xamarin.Forms/issues/13378#issuecomment-759556439_

**Comment by jsuarezruiz** [comment] 2021-01-13 16:37
@Coding-BookMark Could you share a piece of code to be sure is the same as #13378?

**Comment by Coding-BookMark** [comment] 2021-01-15 17:35
Hello how are you
 Please, what do I do now? Has the problem been solved or not?
Because the problem is still in my Listview

**Comment by jsuarezruiz** [comment] 2021-01-18 12:44
@Coding-BookMark You issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13402

**Comment by DerErbil** [comment] 2023-01-11 11:49
Hello, i have the same issue on "Xamarin.Forms 5.0.0.2545" and "Xamarin Forms 5.0.0.2196"

Can someone tell me which Version includes this fix ? or will this get fixed in the future?

**Closed** 2023-11-09 12:25 UTC
Labels: t/bug :bug:, p/iOS 🍎, in-progress, a/brushes
