### ISSUE TITLE
[Bug] [Grid] Label "HeightRequest" value is not applied in grid cell when we span the row on grid row height of "auto"

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#7387] opened 2019-09-04 22:18 UTC
### Description
Hi Team,

We at Syncfusion develope data visualization controls for Xamarin, Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/introduction/overview
FeatureTour: https://www.syncfusion.com/products/xamarin.

We have noticed a strange behavior of Grid when setting the row span for the grid cell with a loaded element with the HeightRequest value.

-  We have loaded the label in the first row of the second column with defined height request for the label and we have applied the row span for the grid cell but the label didn't get render for the provided height request value.

![image](https://user-images.githubusercontent.com/45868997/64294700-1b7c9a80-cf8d-11e9-8059-ec27a2d500d7.png)

- If We remove the row span from the label the defined height gets applied to the element

![image](https://user-images.githubusercontent.com/45868997/64295112-2126b000-cf8e-11e9-9367-d8aab9d14dbb.png)

### Steps to Reproduce

 1. Please didn't remove the row span value from the label and run the sample
 2. You could able to see the behavior I have defined in the first point
 3. Then stop the application and remove the row span value from the label and run the sample 
 4. You could able to see the behavior I have defined in the second point

### Expected Behavior
If its spanned or else the element must to the renderer for the defined height value of the element.
### Actual Behavior
Spanned get applied to row the loaded view didn't render for the  provided height

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  Didn't checked
  - Android: Didn't checked
  - UWP:  17763  
- Android Support Library Version: 
- Nuget Packages: 4.2.709249

### Reproduction Link
[SfGridSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3576689/SfGridSample.zip)

**Comment by samhouts** [comment] 2019-09-10 21:44
Duplicate of #2137

**Closed by samhouts** 2019-09-10 21:44 UTC
Labels: a/layout, p/UWP, partner, s/unverified, t/bug :bug:
