### ISSUE TITLE
[Bug] ListView ItemSelected not working on iOS

### ISSUE THREAD

**Issue by klogeaage** [xamarin/Xamarin.Forms#10181] opened 2020-04-02 08:09 UTC
### Description
The ListView ItemSelected event handler is not fired after upgrading to VS 16.5.2.

### Steps to Reproduce

1. Load any sample project using ListView ItemSelected, e.g. xamarin-forms-samples/UserInterface/ListView/Interactivity/interactivityListView 
2. Start on an iOS simulator
3. Click on an item in the listview

### Expected Behavior
ItemSelected event handler is called.
### Actual Behavior
Nothing happens on iOS. 
Android is still working.
### Basic Information

- Version with issue: VS16.5.2 with Xamarin.iOS SDK version 13.16.0.11
- Last known good version: VS16.5.1
- IDE: VS16.5.2
- Platform Target Frameworks: 
  - iOS: Default (13.4) & XCode 11.4
  - Android: 10.0 (Pixel) 

- Nuget Packages:
- Affected Devices: Simulators and real devices

### Reproduction Link

As specified above.

### Workaround

Not really a workaround, but the exact same project works in VS 16.6.0 Preview 2.0 (Xamarin.iOS SDK 13.18.0.22)

**Comment by samhouts** [comment] 2020-04-02 15:58
Duplicate of #10162

**Closed by samhouts** 2020-04-02 15:58 UTC
Labels: s/unverified, t/bug :bug:
