### ISSUE TITLE
SupportActionMode Menu not updated in Android when using DataTemplateSelector 

### ISSUE THREAD

**Issue by GuidoNeele** [xamarin/Xamarin.Forms#4041] opened 2018-10-09 15:29 UTC
If a ListView uses a DataTemplateSelector for it's ItemTemplate, with different ContextActions, the SupportActionMode Menu is not updated when the selected item is changed.

Reproduce:
1. Create ListView with DataTemplateSelector and different ContextActions for each template
2. Run app on Android
3. Long press on Item and watch SupportActionMode Menu appear
4. Select another item with a different ItemTemplate (and of course different ContextActions)
5. SupportActionMode Menu buttons aren't updated

Possible solution:
Check if ContextActions collection has changed when ActionModeContext is set. Before setting the backing field to the new value check if collection has changed if so then set field _actionModeNeedsUpdates to true.
https://github.com/xamarin/Xamarin.Forms/blob/f79fc69b9e85ebd946bd7128c414735860bcc9f2/Xamarin.Forms.Platform.Android/CellAdapter.cs#L47

Created a sample project.
[DataTemplateSelector.zip](https://github.com/xamarin/Xamarin.Forms/files/2462031/DataTemplateSelector.zip)

**Comment by ElderLars** [comment] 2018-11-01 12:32
I have similar problem with bound properties to contextactions. The name of the action is bound to a property but the text is not updated when selected item is changed.
I also found this old bug:
https://bugzilla.xamarin.com/show_bug.cgi?id=54447

**Comment by GuidoNeele** [comment] 2018-11-01 20:01
Issue is probably duplicate of #1455

**Comment by goedware** [comment] 2018-11-20 09:38
Any update on this issue?
We are also working with a ListView and context actions and have the same "problem" that the actions are not updated when a different template is selected. As described in the start of this thread.

**Comment by GuidoNeele** [comment] 2018-12-20 23:10
Created a workaround to make sure the correct context actions are being shown. The custom ListViewRenderer makes the ListView activate the SupportActionMode on a single click instead of a long press, like the reactions view in the Instagram app.

This solution isn't perfect because the SupportActionMode is hidden en shown within a second so it looks like a flicker. You can also see it as a benefit because it visually indicates the user that the menu and selected item has changed.

MainActivity.cs
```
using ActionMode = Android.Support.V7.View.ActionMode;
...
public static ActionMode SupportActionMode;

/// <summary>
/// Triggered when SupportActionMode is shown
/// </summary>
/// <param name="mode"></param>
public override void OnSupportActionModeStarted(ActionMode mode)
{
  base.OnSupportActionModeStarted(mode);

  SupportActionMode = mode;
}

/// <summary>
/// Triggered when SupportActionMode is being hidden
/// </summary>
/// <param name="mode"></param>
public override void OnSupportActionModeFinished(ActionMode mode)
{
  base.OnSupportActionModeFinished(mode);

  SupportActionMode = null;
}
```

CustomListViewRenderer.cs
```
[assembly: ExportRenderer(typeof(CustomListView), typeof(CustomListViewRenderer))]

namespace Droid.Renderers
{
  public class CustomListViewRenderer : ListViewRenderer
  {
    private readonly Context context;

    public CustomListViewRenderer(Context context) : base(context)
    {
      this.context = context;
    }

    protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
    {
      base.OnElementChanged(e);

      if (e.OldElement != null)
      {
        Control.ItemClick -= OnItemClick;
      }

      if (e.NewElement != null)
      {
        Control.ItemClick += OnItemClick;
      }
    }

    /// <summary>
    /// Handle item click as a long press
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="e"></param>
    private void OnItemClick(object sender, AdapterView.ItemClickEventArgs e)
    {
      // Hiding SupportActionMode to make sure the correct menu items are being shown
      MainActivity.SupportActionMode?.Finish();

      e.View.PerformLongClick();
    }
  }
}
```

**Comment by samhouts** [comment] 2019-02-02 00:12
Duplicate of #1455

**Closed by samhouts** 2019-02-02 00:12 UTC
Labels: e/3 :clock3:, p/Android, t/bug :bug:
