### ISSUE TITLE
[Bug] Embedded Fonts Not working correctly on iOS

### ISSUE THREAD

**Issue by noxe** [xamarin/Xamarin.Forms#10226] opened 2020-04-06 18:57 UTC
### Description
Please see here for all details!
https://github.com/xamarin/Xamarin.Forms/issues/9190#issuecomment-607709937

### Steps to Reproduce

See sample project

[EmbeddedFontsSample-master.zip](https://github.com/xamarin/Xamarin.Forms/files/4440305/EmbeddedFontsSample-master.zip)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.4
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/158478/78594627-f1ec6000-7848-11ea-8eee-7839edf9487c.png)

### Reproduction Link

https://github.com/xamarin/Xamarin.Forms/issues/9190#issuecomment-607709937

**Comment by noxe** [comment] 2020-04-06 18:58
Alse see this commet https://github.com/xamarin/Xamarin.Forms/issues/9190#issuecomment-609952159

**Comment by zoli13** [comment] 2020-04-10 10:58
I can confirm the same issue, on iOS 13.4, with XF 4.5.0.530
On Android, it works fine.

**Comment by jamesmontemagno** [comment] 2020-04-20 18:30
I am not seeing this issue in 4.6.0

**Comment by Csaba8472** [comment] 2020-04-21 19:13
For me 4.6 pre 4 still doesn't work. I'd like to use FontIconSource as shell tab icon. The funny thing is, if hot reload reloads the view(because I edited the xaml) the icon appears.

**Comment by jfversluis** [comment] 2020-04-21 20:18
@Csaba8472 and others. Would you be able to download the generated NuGet package from this build: https://dev.azure.com/xamarin/public/_build/results?buildId=17285&view=artifacts&type=publishedArtifacts

And test if that fixes it for you?

**Comment by jamesmontemagno** [comment] 2020-04-21 22:28
Ah yes i was using them on labels. Clancey's fix does it for FontIconSource, which I have verified as fixed.

**Comment by Csaba8472** [comment] 2020-04-22 10:35
Tried and it works, thank you @jfversluis!

**Comment by jslachta** [comment] 2020-04-22 12:18
I am not sure whether it is the same issue. Xamarin.Forms on iOS does not like the Fontawesome Pro Regular font (5.0), other fonts are working fine.

`[assembly: ExportFont("Font Awesome 5 Brands-Regular-400.otf", Alias = FontFamilies.FontAwesomeBrandsRegular)]
[assembly: ExportFont("Font Awesome 5 Duotone-Solid-900.otf", Alias = FontFamilies.FontAwesomeDuotoneSolid)]
[assembly: ExportFont("Font Awesome 5 Pro-Light-300.otf", Alias = FontFamilies.FontAwesomeLight)]
[assembly: ExportFont("Font Awesome 5 Pro-Regular-400.otf", Alias = FontFamilies.FontAwesomeRegular)]
[assembly: ExportFont("Font Awesome 5 Pro-Solid-900.otf", Alias = FontFamilies.FontAwesomeSolid)]`

**Comment by samhouts** [comment] 2020-05-01 18:22
closed by  #10227

**Closed by samhouts** 2020-05-01 18:22 UTC
Labels: a/embedded fonts, in-progress, p/iOS 🍎, t/bug :bug:
