### ISSUE TITLE
[Bug] CollectionView: When IsGrouped = true, FirstVisibleItemIndex,CenterItemIndex and LastVisibleItemIndex inside Scrolled event, are incorrect on iOS 

### ISSUE THREAD

**Issue by dbSoft-SoftwareSolutions** [xamarin/Xamarin.Forms#13787] opened 2021-02-17 13:24 UTC
When a CollectionView's IsGrouped property is set to true, the values of FirstVisibleItemIndex, CenterItemIndex, and LastVisibleItemIndex inside Scrolled event are incorrect on iOS Platform. 

It should be noted that the indices are reported correctly on Android.

### Steps to Reproduce

1. Open the attached solution.
2. Create a Scrolled method event

    CollectionViewItems.Scrolled += CollectionViewItems_Scrolled;
    private void CollectionViewItems_Scrolled(object sender, ItemsViewScrolledEventArgs e)
    {
            Console.WriteLine(e.FirstVisibleItemIndex);
            Console.WriteLine(e.CenterItemIndex);
            Console.WriteLine(e.LastVisibleItemIndex);
    }

3. Run application on iOS platform.
4. Scroll the list.

### Expected Behavior
The exprected behaviour is the e.FirstVisibleItemIndex,e.CenterItemIndex and e.LastVisibleItemIndex, to have a continous increment, while scrolling down.

### Actual Behavior
1. e.FirstVisibleItemIndex is always 0.
2. e.CenterItemIndex  while a new Group(i mean GroupTemplate) is appearing in center of the screen the e.CenterItemIndex starts from 0 again.
Wrong behaviour: Collectionview' scrolling example, on iOS:

//Group 1
e.CenterItemIndex is 0 
e.CenterItemIndex is 1
e.CenterItemIndex is 2
e.CenterItemIndex is 3
e.CenterItemIndex is 4
e.CenterItemIndex is 5  //After that e.CenterItemIndex  group will change 
//Group 2
e.CenterItemIndex is 0
e.CenterItemIndex is 1
e.CenterItemIndex is 2 //And after that e.CenterItemIndex group will change again
//Group 3
e.CenterItemIndex is 0
e.CenterItemIndex is 1
e.CenterItemIndex is 2
e.CenterItemIndex is 3
e.CenterItemIndex is 4

Proper behaviour: Collectionview' scrolling example, on Android:

//Group 1
e.CenterItemIndex is 0 
e.CenterItemIndex is 1
e.CenterItemIndex is 2
e.CenterItemIndex is 3
e.CenterItemIndex is 4
e.CenterItemIndex is 5  //After that e.CenterItemIndex  group will change 
//Group 2
e.CenterItemIndex is 6
e.CenterItemIndex is 7
e.CenterItemIndex is 8 //And after that e.CenterItemIndex group will change again
//Group 3
e.CenterItemIndex is 9
e.CenterItemIndex is 10
e.CenterItemIndex is 11
e.CenterItemIndex is 12
e.CenterItemIndex is 13

3. e.LastVisibleItemIndex while a new Group(i mean GroupTemplate) is appearing in last of the screen the e.LastVisibleItemIndex starts from 0 again.

e.FirstVisibleItemIndex,e.CenterItemIndex and e.LastVisibleItemIndex on iOS must have the exactly same value as the android platform.

### Basic Information

Version with issue: 5.0.0.2012
Platform Target Frameworks:
iOS: 11.4

### Environment

Microsoft Visual Studio Enterprise 2019
Version 16.8.5
VisualStudio.16.Release/16.8.5+31005.135
Microsoft .NET Framework
Version 4.8.04084

Xamarin   16.8.000.262 (d16-8@4d60f9c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.10.0.4 (5a05865f6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by hartez** [comment] 2021-02-18 21:57
Duplicate of #10389

**Closed by hartez** 2021-02-18 21:57 UTC
Labels: s/unverified, t/bug :bug:
