### ISSUE TITLE
[Bug] [Core] Grid definitions cant be set with Style.Setter (leaks)

### ISSUE THREAD

**Issue by kicsiede** [xamarin/Xamarin.Forms#6712] opened 2019-06-29 11:11 UTC
### Description

setting column/rowdefinitions on a grid with style causes memoryleak, because the definitioncollection is not cloned but shared accross the app.

ItemSizeChanged eventhandler keeps a strong reference on the grid.

### Steps to Reproduce

1. create a style that sets grid columndefinition
2. the page with the grid stays in memory indefinitely

### Expected Behavior

either the eventhandler should use weak references, or the definitions should be cloned for every grid they are applied to.

### Actual Behavior

leaks

### Basic Information

- Version with issue: Forms 3.6
- Platform Target Frameworks: All

**Comment by StephaneDelcroix** [comment] 2019-07-19 11:37
I can reproduce this, wonder what's wrong...

**Comment by kicsiede** [comment] 2019-07-19 12:17
@StephaneDelcroix if you mean you _can't_ reproduce the bug: of course you must create a global style (aka in App.xaml for example) so that it could survive the Page. Since the style is shared, any strong eventhandlers attached to it will live as long as the app: app->style->definitioncollection->(itemsizechanged/sizechanged)->grid->page.

I've seen in the implementation of Setter that VisualStateGroup is handled specially (cloned), I guess for similar reasons. Of course Setter should not know anything about VisualStateGroup:
The proper solution for these kind of problems would be to have an option for Setter to clone or share its value. (Mutable Setter.Values should be cloned usually)

**Comment by StephaneDelcroix** [comment] 2019-07-19 19:03
@kicsiede we need a repro to make sure we're talking about the same issue. StaticResources, and Styles are shared in XF, but they shouldn't leak.

**Comment by kicsiede** [comment] 2019-07-19 20:22
@StephaneDelcroix 
[AndroidBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3412567/AndroidBug.zip)

after you try this repro, you will come to the same conclusion that i did. :)

**Comment by StephaneDelcroix** [comment] 2019-07-19 20:26
when I said "they shouldn't leak", I meant it as a goal. I'm not saying that, at this time, they don't

**Comment by kicsiede** [comment] 2019-07-19 21:01
now i'm using the following as a workaround. "Clone" does a deep copy, but of course this solution is extremely ugly.
```
        <ColumnDefinitionCollection x:Key="CondensedColumns">
            <ColumnDefinition Width="0.2*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="0.1*"/>
        </ColumnDefinitionCollection>
        
        <Style Class="CondensedHeader" TargetType="Grid">
            <Setter Property="MinimumHeightRequest" Value="85"/>
            <Setter Property="ColumnDefinitions" Value="{Binding Source={StaticResource CondensedColumns}, Converter={StaticResource Clone}}"/>
        </Style>
```
I have repeatedly run into this issue when trying to pass complex data through Setter.Value and ended up cloning myself at the receiver site. :(

i was thinking about this:
```
        <Style Class="CondensedHeader" TargetType="Grid">
            <Setter Property="MinimumHeightRequest" Value="85"/>
            <Setter Property="ColumnDefinitions" Mode="Copy">
                <Setter.Value>
                    <ColumnDefinitionCollection x:Key="CondensedColumns">
                        <ColumnDefinition Width="0.2*"/>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="0.1*"/>
                    </ColumnDefinitionCollection>
                </Setter.Value>
            </Setter>
        </Style>
```

I'd suggest Copy be the default behaviour, and Share can be specified explicitly when the user knows what he is doing.

**Comment by StephaneDelcroix** [comment] 2019-07-20 19:02
@kicsiede what you're looking for is `x:Shard=true` (https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/x-shared-attribute), but that's not (yet) implemented in XF.

If you'd like this to be implemented, please file a feature request. 

But the original problem reported here is the leak, not the lack of sharing.

**Comment by StephaneDelcroix** [comment] 2019-07-20 19:10
At this point, I wonder what the best approach is:
- use a WeakEvent,
- disconnect from event when Dispose()ing the Grid,
- ...

I'll check on Monday

**Comment by StephaneDelcroix** [comment] 2019-07-22 10:56
Grid row/col definitions aren't usually meant to outlive the Grid, this is why we don't use WeakEvents

**Comment by kicsiede** [comment] 2019-07-22 11:11
@StephaneDelcroix imho to fix this problem, it is better to implement the sharing mechanizm that we discussed earlier, as the same problem appears for all objects that create a circular reference with the target object. so you would just solve a single instance of this problem, the griddefinitions.
(as a side note, even if they are defined locally on a page so they avoid the reference problem, I wonder what happens when several grids on a page get the same rowdefinitions applied: they will be "linked", and any mutation to one would be reflected on the other one.)

**Comment by StephaneDelcroix** [comment] 2019-07-22 11:15
@kicsiede we'll fix whatever you need. I'm not a big fan of using WeakEvent for this either, but unless you don't care about the actual leak, there's no way around it.

If you favor the x:Shared solution, and that would solve the problem for you, please close this issue and open a new enhancement request. Thanks

**Comment by samhouts** [comment] 2019-08-23 18:57
@kicsiede  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by samhouts** 2019-08-23 18:57 UTC
Labels: a/performance, a/style, s/needs-repro ❔, t/bug :bug:
