### ISSUE TITLE
[Bug] Xamarin.iOS project not run (The "CompileEntitlements" task was not given a value for the required parameter "SdkDevPath")

### ISSUE THREAD

**Issue by balivo** [xamarin/Xamarin.Forms#12827] opened 2020-11-12 20:01 UTC
### Description

I'm using VS2019 16.9.0 preview 1 and I can't run my Xamarin.iOS project on device (on PC).

The problem starts today, yesterday I update VS to new preview and everything is ok, project runs on VS 2019 16.9.0 preview 1;

### Steps to Reproduce

1. Try Create new XF project;
2. Run iOS project in debug mode on PC with iPhone connected

### Expected Behavior
App runs in debug

### Actual Behavior
Build fails

### Basic Information
- IDE: VS 2019 16.9.0 preview 1
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS and Xamarin.Mac SDK   14.7.0.166 (d91932dcd)

### Buil output

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets(181,3): error MSB4044: The "CompileEntitlements" task was not given a value for the required parameter "SdkDevPath".

**Comment by rachelkang** [comment] 2020-11-13 20:15
Hi, @balivo - I'll be closing this issue now since this issue isn't specific to Xamarin.Forms.

To get help with this issue, I suggest you file this using the Send Feedback feature on Visual Studio, and you'll be able to get more help through there :).  You can do this by going to **Help > Send Feedback > Report a Problem** ([more instructions here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019))

However, if you have reason to believe this is specific to the Xamarin.Forms, please feel free to reopen this issue and share the version of XF you're using as well as a project that reproduces this issue if possible! Thank you :)

**Comment by rachelkang** [comment] 2020-11-13 21:13
@balivo, thanks for submitting this issue - could you please attach a diagnostic build output / the full build logs that captures this error? Thanks :)

(Apologies, I closed this issue on accident!)

**Comment by balivo** [comment] 2020-11-14 01:09
Sure, too long...

Gist link: https://gist.github.com/balivo/8146b3e1389ed95f42e30fc7178b1a69#file-xamarin-forms-issue-12827-diagnostic-log

**Comment by aherrick** [comment] 2020-11-14 16:04
I'm also seeing this. Any work arounds?

**Comment by Rabosa616** [comment] 2020-11-14 19:54
I'm also experiencing the same issue:
[Diagnosis.txt](https://github.com/xamarin/Xamarin.Forms/files/5541377/Diagnosis.txt)

**Comment by rachelkang** [comment] 2020-11-16 18:35
@balivo thanks for sharing! This issue is already being tracked in the dev community [here](https://developercommunity2.visualstudio.com/t/Visual-Studio-1690-shows-Xamarin-local/1254664?preview=true) so I'll be closing this issue here. This is a XamarinVS issue, and as is mentioned there, the fix has already been made! You can expect to see it released in VS 16.9 Preview 2 :)

**Closed by rachelkang** 2020-11-16 18:35 UTC
Labels: external-vs, s/needs-info ❓, s/unverified, t/bug :bug:

**Comment by balivo** [comment] 2020-11-16 18:42
PERFECT @rachelkang !!!!!

**Comment by magoolation** [comment] 2020-12-02 20:25
Any expected date to delivery it?

**Comment by dersia** [comment] 2020-12-06 14:42
There is a Workaround. But do it at your own risk.
Edit File `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets`
look for `ComoileEntitlements` in Line 181 
```
		<CompileEntitlements
			AppBundleDir="$(LocalAppBundlePath)"
			AppIdentifier="$(_AppIdentifier)"
			BundleIdentifier="$(_BundleIdentifier)"
			Entitlements="$(CodesignEntitlements)"
			CompiledEntitlements="$(DeviceSpecificIntermediateOutputPath)Entitlements.xcent"
			IsAppExtension="$(IsAppExtension)"
			ProvisioningProfile="$(_ProvisioningProfileId)"
			SdkIsSimulator="False"
			SdkPlatform="iPhoneOS"
			SdkVersion="12.2"
			TargetFrameworkMoniker="$(TargetFrameworkMoniker)" />
```
Add `SdkDevPaht` as an attribute with the value `$(_SdkDevPath)`.

Final result should look like this:
```
		<CompileEntitlements
			AppBundleDir="$(LocalAppBundlePath)"
			AppIdentifier="$(_AppIdentifier)"
			BundleIdentifier="$(_BundleIdentifier)"
			Entitlements="$(CodesignEntitlements)"
			CompiledEntitlements="$(DeviceSpecificIntermediateOutputPath)Entitlements.xcent"
			IsAppExtension="$(IsAppExtension)"
			ProvisioningProfile="$(_ProvisioningProfileId)"
			SdkIsSimulator="False"
			SdkPlatform="iPhoneOS"
			SdkVersion="12.2"
			SdkDevPath="$(_SdkDevPath)"
			TargetFrameworkMoniker="$(TargetFrameworkMoniker)" />
```

**Comment by balivo** [comment] 2020-12-15 13:12
I made the @rachelkang, restart my PC and works!
