### ISSUE TITLE
Xamarin app localization not working due to lower-case satellite folder names

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15734] opened 2023-05-05 13:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-app-localization-not-working-due/10341829)._

---
[severity:It's more difficult to complete my work]
Our Xamarin app uses localization with satellite assemblies which are packaged in to the apk (Android) and ipa (iOS) packages under sub-folders matching the appropriate culture (e.g. fr-FR for French). This appears to now be broken as the packaging creates lower-case folders (e.g. fr-fr) and then when the package is installed on a device the localization is not working. I have attached a previous package of our app where the folders were the correct case and the localization is working (Ostara5_6.zip) and a recent version where the folders are all lower-case and the localization does not work (Ostara5_7.zip).

Is this something that has changed in the packaging? We use msbuild with the switch /t:PackageForAndroid to build the APK.

---
#### Feedback Bot on 4/18/2023, 06:54 PM: 

(private comment, text removed)
#### v-annajinjin [MSFT] on 4/22/2023, 10:42 PM: 

(private comment, text removed)
#### Simon.Mathews on 4/24/2023, 00:35 AM: 

(private comment, text removed)
#### Feedback Bot on 4/26/2023, 02:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2023-05-08 11:02
Duplicate of #8728

**Closed by jfversluis** 2023-05-08 11:02 UTC

**Comment by mathewssj** [comment] 2023-05-09 06:49
Hi, this has been incorrectly marked as a duplicate of #8728 but it is not. That bug was raised in 2020 and was subsequently fixed (it was also iOS only). This is an issue for us now with Xamarin Forms 5.0.0.2578 in Android and iOS packages.

**Comment by volcano619** [comment] 2023-05-24 12:41
I have a similar issue, where the localization for es-US is not working, other localizations are working fine
