### ISSUE TITLE
[Bug] Different height items inside to a CollectionView - iOS only

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Xamarin.Forms#8616] opened 2019-11-21 20:26 UTC
I working with the Xamarin Forms 4.3.0.991211.

I get the following warning only at the first time where the page open and nothing displayed.

> Warning once only: Detected a case where constraints ambiguously suggest a size of zero for 
a collection view cell's content view. We're considering the collapse unintentional and using standard size instead.

I use all options from ItemSizingStrategy property but i get every time the same result.

Android working perfect !! 

Here is my repo https://github.com/georgemichailou/Xamarin-Galleries
(it's auto height gallery)

**Comment by jfversluis** [comment] 2019-11-28 20:29
When going to the page the first time it indeed gives that console output and then doesn't show anything. Still happening with the latest nightly.

Android also doesn't seem to work, but this seems due to some error the images cannot be loaded. Although, that might have something to do with it... Maybe the images don't load immediately, that's why the size goes to 0 and things get messed up? Just thinking out loud...

> 2019-11-28 21:25:06.117619+0100 XamarinGalleries.iOS[30931:442124] [Warning] Warning once only: Detected a case where constraints ambiguously suggest a size of zero for a collection view cell's content view. We're considering the collapse unintentional and using standard size instead. Cell: <Xamarin_Forms_Platform_iOS_VerticalCell: 0x7fcfd8f2f530; baseClass = UICollectionViewCell; frame = (0 0; 414 0); layer = <CALayer: 0x600001e99500>>

**Comment by samhouts** [comment] 2020-01-03 00:34
Duplicate of #5455

**Closed by samhouts** 2020-01-03 00:34 UTC
Labels: a/collectionview, blocker, p/iOS 🍎, t/bug :bug:
