### ISSUE TITLE
[Bug] [iOS] PushModalAsync failing (Attempt to present modalwrapper on PageRenderer whose view is not in the window hierarchy)

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#7364] opened 2019-09-03 11:09 UTC
### Description
As the user navigates through the app and uses an external file picker to pick an image, the application may stop working with its modal stack, ie pushing pages to the modal stack will fail (the stack will grow but nothing will be displayed).

### Steps to Reproduce

1. Open a modal page that has an image picker action button (using James Montemagno's Media plugin).
1. In the modal page, tap the image picker button, then do a double or triple tap on an image to pick it.
1. If the modal page has strangely been dismissed, continue, otherwise repeat the image picking step until it dismisses the modal page you were in.
1. Try to open the modal page again

### Expected Behavior
The modal page is displayed.
### Actual Behavior
Nothing happens and the debugging output will display a message like
`Attempt to present <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x7fcde9587770> on <Xamarin_Forms_Platform_iOS_PageRenderer: 0x7fcde94155f0> whose view is not in the window hierarchy` everytime you tap the button.

### Basic Information

- Version with issue: 4.2.0
- Last known good version: unknown
- IDE: VS2019 16.2.3
- Platform Target Frameworks: 
  - iOS:  12
- Nuget Packages: Xam.Plugin.Media [4.0.1.5]

### Screenshots

![bug_demo](https://user-images.githubusercontent.com/31066938/64168522-a18cca00-ce43-11e9-9ddb-ec3ad8be583a.gif)

### Reproduction Link

[ModalStackBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3569125/ModalStackBug.zip)

**Comment by samhouts** [comment] 2019-09-10 01:39
It looks like the permissions dialog is causing the modal to close unexpectedly, and then we enter the same bad state that iOS13 modal windows can get into when they are closed unexpectedly. We'll need to address that. However, I did test this with the 4.3.0-pre1 bits, and it looks like the modal doesn't close unexpectedly anymore. Perhaps #7172 is making a positive impact.

In any case, I'm going to close this as a duplicate because it is the same root cause!

Thanks!

**Comment by samhouts** [comment] 2019-09-10 01:39
Duplicate of #7145

**Closed by samhouts** 2019-09-10 01:39 UTC
Labels: i/high, p/iOS 🍎, t/bug :bug:
