### ISSUE TITLE
[Bug] Try/Catch not working as expected using WHEN on Android

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Forms#6320] opened 2019-05-27 12:31 UTC
### Description
Using a try/Catch including WHEN doesn't work as expected on Android. Ending up in unhandled exception

### Steps to Reproduce
```
      private void Button_Clicked(object sender, EventArgs e)
      {
         try
         {
            throw new Exception();
         }
         catch (Exception ex) when (ex.Message.Contains("King"))
         {
            Debug.WriteLine("King");
         }
         catch (Exception ex)
         {
            Debug.WriteLine("Exception");
         }
      }

```

### Expected Behavior
Should end up in second Catch

### Actual Behavior
Doesn't end up in any Catch, causing unhandled exception (terminating the app)

### Basic Information

- Version with issue: XF 4.0.0
- Last known good version: ?
- IDE: Visual Studio 2019 (16.1.0)
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages: -
- Affected Devices: Samsung Galaxy s7

### Screenshots
-
### Reproduction Link
-

**Comment by masonyc** [comment] 2019-05-27 20:06
#6269

**Comment by samhouts** [comment] 2019-05-28 19:50
Duplicate of #6269

**Closed by samhouts** 2019-05-28 19:50 UTC
Labels: s/unverified, t/bug :bug:
