### ISSUE TITLE
[Bug] In Xamarion.forms ListView has some issue with iOS 15

### ISSUE THREAD

**Issue by reddy4** [xamarin/Xamarin.Forms#14674] opened 2021-09-29 18:17 UTC
### Description

In iOS 15 ListView has some default white space at top.

### Steps to Reproduce

Just open existing application which is having ListView  in iOS 15.

**Comment by jsuarezruiz** [comment] 2021-09-30 07:43
Seems to be the same or related with https://github.com/xamarin/Xamarin.Forms/issues/14664

**Comment by jfversluis** [comment] 2021-10-02 19:16
Duplicate of #14664

**Closed by jfversluis** 2021-10-02 19:16 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/listview
