### ISSUE TITLE
[Bug] Inconsistent Behavior of OnAppearing and OnDisappearing Methods on iOS When Minimizing App

### ISSUE THREAD

**Issue by Juvelio** [xamarin/Xamarin.Forms#15807] opened 2023-08-23 16:58 UTC
### Description
Inconsistent Behavior of OnAppearing and OnDisappearing Methods on iOS When Minimizing App

### Steps to Reproduce

1. Open the application on an iOS device.
2. Navigate to the page with the implemented OnAppearing() and OnDisappearing() methods.
3. Observe the correct execution of these methods when navigating between pages.
4. Minimize the application (tap the home button or use the swipe gesture to go to the home screen).
5. Maximize the application from the home screen.

Additional Details:

The issue appears to be specific to the iOS platform.
The OnAppearing() and OnDisappearing() methods behave correctly during page navigation.
It seems that the application lifecycle events might not be triggered appropriately upon minimizing and restoring the app.

**Issue Description:**

**Code Snippet:**

protected override void OnAppearing()
{
    base.OnAppearing();
}

protected override void OnDisappearing()
{
    base.OnDisappearing();
}

### Expected Behavior
The OnAppearing() and OnDisappearing() methods should consistently execute properly, both when navigating between pages and when minimizing and restoring the application on iOS.
### Actual Behavior
After minimizing and then maximizing the application on iOS, the OnAppearing() and OnDisappearing() methods do not execute as expected.
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment] 2023-08-24 17:47
Duplicate of #6919

**Closed as not planned by jfversluis** 2023-08-24 17:47 UTC
Labels: t/bug :bug:, s/unverified
