### ISSUE TITLE
[Bug] There is no way to customize WkWebView

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8708] opened 2019-11-28 16:23 UTC
### Description
On iOS **WKWebView** has **CustomUserAgent** property. I want just to set this property without breaking the functionality of **WKWebView**. How can I do it?

When I created a custom renderer like this:

```
[assembly: ExportRenderer(typeof(MyWebView), typeof(CustomWebViewRenderer))]
namespace App1.iOS.Renderers
{
    public class CustomWebViewRenderer : WkWebViewRenderer
    {
        public CustomWebViewRenderer()
        {
            
        }

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
        }
    }
}
```

I noticed that I have no access to **Control** property I cannot make any customization of the WebView.

if I instead inherit from

```ViewRenderer<MyWebView, WKWebView>```

like this:

```
[assembly: ExportRenderer(typeof(MyWebView), typeof(CustomWebViewRenderer))]
namespace App1.iOS.Renderers
{
    public class CustomWebViewRenderer : ViewRenderer<MyWebView, WKWebView>
    {
        protected override void OnElementChanged(ElementChangedEventArgs<WebView> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null && Control != null)
            {
                Control.CustomUserAgent = "example_user_agent";
            }
        }
    }
}
```

then I can set **CustomUserAgent** but I have broken the functionality of the WebView. Now "Naivigating" and "Navigated" events are not working.

So is there any way to customize **WkWebView**?

### Expected Behavior
There should be a way to customize **WkWebView**

### Actual Behavior
There is no way to customize **WkWebView**

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: Visual Studio 2019 16.3.10

**Comment by GalaxiaGuy** [comment] 2019-11-28 17:15
Looking at the source code, it seems `WkWebViewRenderer` is itself a `WKWebView`.

**Comment by Mikilll94** [comment] 2019-11-28 20:34
@GalaxiaGuy 
Yes. WkWebViewRenderer inherits from WKWebView. But how can I set some properties of WKWebView in my Xamarin.Forms code?

**Comment by jfversluis** [comment] 2019-11-29 09:19
It seems there is indeed at this time no way to do this without breaking the Xamarin.Forms navigation events. I see you already also opened an enhancement for this which I think is more appropriate. Therefore, I will close this one as a duplicate.

Another issue that is relevant to this is #6340 which describes a solution for this.

**Comment by jfversluis** [comment] 2019-11-29 09:19
Duplicate of #8432

**Closed by jfversluis** 2019-11-29 09:19 UTC
Labels: s/unverified, t/bug :bug:
