### ISSUE TITLE
[Bug] Issue with SwipeView not working since Xamarin.Forms update v4.7.0.1080 and above on Android

### ISSUE THREAD

**Issue by krmWorkAccnt** [xamarin/Xamarin.Forms#11496] opened 2020-07-20 23:02 UTC
### Description
Since the update of Xamarin.Forms v4.7.0.1080 and above, Swipe View is no longer working on Android, iOS doesn't have this issue -- this issue isn't in v4.7.0.968.
The issue appears to be with the gesture recognizer attached to a content view -- when the gesture recognizer is commented out the swipe action works correctly.
Download project from https://github.com/krmWorkAccnt/SwipeExampleTwo to replicate -- Initially when starting a new project the version of Xamarin.Forms will be v4.5 and there won't be an issue, If you update Xamarin.Forms to the latest version you will see swipe view doesn't work correctly -- from there you can down-grade the versions of Xamarin.Forms to v4.7.0.968 and see that the bug was introduced in v4.7.0.1080.
NOTE -- when you upgrade to 4.7.0.1080 and notice the issue, comment out the gesture recognizer in TestItemControl.xaml and swipe action will work correctly
### Steps to Reproduce

1: I have uploaded an example project to https://github.com/krmWorkAccnt/SwipeExampleTwo

### Expected Behavior
Swipe View swipe action displays buttons
### Actual Behavior
Swipe view swipe action isn't working
### Basic Information
Download project -- downgrade the Xamarin.Forms version to v4.7.0.968 and see that swipe function works correctly -- Update Xamarin.Forms to latest version or version above 4.7.0.968, swipe view swipe action won't work -- Once you get project not to work after updating to version with bug, comment out the gesture recognizer in TestItemControl.xaml and the swipe action will work correctly

- Version with issue: Xamarin.Forms v4.7.0.1080 and above
- Last known good version: Xamarin.Forms v4.7.0.968
- IDE: Visual Studio Enterprise 2019 v 16.6.1
- Platform Target Frameworks: 
  - iOS:  No Issue with iOS
  - Android: Pie 9.0 Api 28 
  
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials v1.3.1 NETStandardLibrary v2.0.3
- Affected Devices:

### Reproduction Link

Link to example project https://github.com/krmWorkAccnt/SwipeExampleTwo

### Workaround

Downgrade Xamarin.Forms to v4.7.0.968

**Comment by dweyermann** [comment] 2020-07-24 08:57
Same problem here with Xamarin.Forms 4.7.0.1142.

**Comment by hartez** [comment] 2020-07-25 22:35
Looks like the problem started in 4.6.

**Comment by HarryLobster** [comment] 2020-07-26 07:30
Same Problem here. I my case it must have something to do that I am using an ItemTemplateSelector in my Listview.

**Comment by dweyermann** [comment] 2020-08-03 09:20
The problem with the gesture recognizer seems to be resolved with 4.7.0.1239.

**Comment by krmWorkAccnt** [comment] 2020-08-03 21:44
I have updated our project to 4.7.0.1239 and at first glance this does appear to be working, however there does still seem to be issues.
The swipe gestures work regards to exposing the buttons, however the tap gesture for the list item as well as the tap command for the swipe button is now buggy as in you tap on an item and complete a task, then tap on another item and nothing happens -- after tapping on a different item for a few times something may happen -- Likewise after initially completing a task from either a swipe button action, or tap command on a list item, picking another list item and attempting to use the swipe button isn't responsive, this may take a few attempts for the swipe button to become responsive.

**Closed** 2020-09-07 15:01 UTC
Labels: 4.7.0, a/gestures 🖖, a/swipeview, i/regression, in-progress, p/Android, t/bug :bug:

**Comment by JoacimWall** [comment] 2020-09-22 12:12
> I have updated our project to 4.7.0.1239 and at first glance this does appear to be working, however there does still seem to be issues.
> The swipe gestures work regards to exposing the buttons, however the tap gesture for the list item as well as the tap command for the swipe button is now buggy as in you tap on an item and complete a task, then tap on another item and nothing happens -- after tapping on a different item for a few times something may happen -- Likewise after initially completing a task from either a swipe button action, or tap command on a list item, picking another list item and attempting to use the swipe button isn't responsive, this may take a few attempts for the swipe button to become responsive.

We made some change to the code ang got it to work better for Android using  InputTransparent="{OnPlatform iOS='False', Android='True'}" on the controls inside the SwipeView. 

Example below 

<CollectionView.ItemTemplate>
	<DataTemplate x:DataType="models:CheckListItem">
      		<SwipeView  >
                               
                                        </SwipeItemView>
                                    </SwipeItems>
                                </SwipeView.RightItems>
                                <SwipeView.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding BindingContext.ChecklistItemSelectCommand, Source={x:Reference Checklists}}" CommandParameter="{Binding .}"/>
                                </SwipeView.GestureRecognizers>
                            </SwipeView>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>

//regards Joacim

**Comment by luczinski** [comment] 2021-03-12 20:45
Hi guys!
I'm experiencing this bug with Xamarin.Forms 5.0.0.2012 testing on Android. What’s the status of this bug?
Thanks!

**Comment by dylix** [comment] 2021-03-18 15:11
Same here as well. While I can replace the grid tapgesture with the swipeview gesture, and that works as expected, the tapgestures for my stacklayouts do not work.
normally i can click menu,order to do their specific commands, but inside the swipeview they don't work..
https://i.imgur.com/UHiazvI.png

**Comment by luczinski** [comment] 2021-03-18 19:19
> Same here as well. While I can replace the grid tapgesture with the swipeview gesture, and that works as expected, the tapgestures for my stacklayouts do not work.
> normally i can click menu,order to do their specific commands, but inside the swipeview they don't work..
> https://i.imgur.com/UHiazvI.png

Hi! Finally I discovered how to make it work. I couldn't make tapgesture work, but the SwipeItemView Command works perfectly. 
 
`<SwipeView.LeftItems>
                                    <SwipeItemView BackgroundColor="Transparent" Command="{Binding Path=BindingContext.OnEditTransactionClicked, Source={x:Reference Name=TransactionsPage}}" CommandParameter="{Binding .}">
                                        <Grid RowDefinitions="*" ColumnDefinitions="60,40" >
                                            <BoxView CornerRadius="15,0,15,0" Color="#FFA31A" Grid.ColumnSpan="2"/>
                                            <ffSvg:SvgCachedImage Source="resource://LeapFrogApp.Common.Images.Transaction.edit_icon.svg"  
                                                          HeightRequest="25" WidthRequest="25"
                                                          HorizontalOptions="Center" VerticalOptions="Center"/>
                                        </Grid>
                                    </SwipeItemView>
                                </SwipeView.LeftItems>`

Also check this Gerald Versluis article: 
[https://blog.verslu.is/xamarin/xamarin-forms-xamarin/swipeview-interaction-with-xamarin-forms/](url)

**Comment by HuckleChuckleDog** [comment] 2021-03-18 19:48
So apparently they put a fix through for this, however swipe view isn't working as expected for android -- refer to https://github.com/xamarin/Xamarin.Forms/issues/13966 where there is also a sample project loaded.
Since swipe view wasn't working as expected for android, we implemented a double tap gesture recognizer to provide menu options, however that doesn't work for iOS -- it's just mind boggling

**Comment by TobiasBuchholz** [comment] 2022-03-10 09:04
For me the `SwipeView` wasn't working with android as well, until I noticed I haven't put a layout around the `Content` view. For iOS this doesn't seem to be a problem, but for android it seems to be crucial to do that.

```xml
<SwipeView>
    <SwipeView.RightItems>
        <SwipeItems>
            <SwipeItem Text="Hello" BackgroundColor="Red" />
        </SwipeItems>
    </SwipeView.RightItems>
    <StackLayout> <!-- Stacklayout is needed for android to work -->
        <Label Text="Swipe me!" />
    </StackLayout>
</SwipeView>
```

With that I can confirm that the `SwipeView` works with `Xamarin.Forms 5.0.0.2337` for both iOS and android.
