### ISSUE TITLE
[Bug] TabBarTitleColor

### ISSUE THREAD

**Issue by C6H10O5n** [xamarin/Xamarin.Forms#14836] opened 2021-11-06 03:34 UTC
### Description
Shell.TabBarTitleColor property is ignored when in landscape orientation on ios

### Steps to Reproduce

1. open xanimals sample 
2. update XamarinForms pkg to 5.0.0.2196 
3.run on ios simulator 
4. rotate device then tab bar text changes to default blue

- Version with issue: 5.0.0.2196
- Last known good version: 5.0.0.2125

**Comment by jsuarezruiz** [comment] 2021-11-08 09:32
Cannot reproduce the issue on main. I think have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/14775 and is not included yet in a Service Release. @jfversluis Could you confirm this?

**Comment by jfversluis** [comment] 2021-11-08 11:44
I would suspect so... @C6H10O5n would you be able to try the nightly feed and see if it works correctly there?

**Comment by C6H10O5n** [comment] 2021-11-10 05:04
Yes is working in 5.0.1.2031-nightly!!  thanks

**Comment by jfversluis** [comment] 2021-11-10 08:17
Great! That should be released somewhere early next week :)

**Closed by jfversluis** 2021-11-10 08:17 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/shell :shell:, iOS 15
