### ISSUE TITLE
TabbedPage issue while tapping multiple times with user interactive custom control

### ISSUE THREAD

**Issue by Nijamudeen-Mohamed** [xamarin/Xamarin.Forms#1796] opened 2018-02-05 05:12 UTC
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Placing a Customs control in a tabbed page and keep on tapping (different points around 100+ taps) on Custom view (child)  exception thrown and applications crashes.

We suspect that it was an Android framework issue and it was already discussed in the following forums and no solution found.

https://issuetracker.google.com/issues/36931456

https://github.com/chrisbanes/PhotoView/issues/31

### Steps to Reproduce
Create a tab page with 3 tabs
Place any user interactive control (Eg: SfSchedule).
Tap the control  (different points around 100+ taps).

Stack Trace while tapping the application
Java.Lang.IllegalArgumentException: pointerIndex out of range

01-26 11:05:20.736 D/Mono    (32399): DllImport attempting to load: '/system/lib/liblog.so'.
01-26 11:05:20.736 D/Mono    (32399): DllImport loaded library '/system/lib/liblog.so'.
01-26 11:05:20.736 D/Mono    (32399): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
01-26 11:05:20.736 D/Mono    (32399): Searching for '__android_log_print'.
01-26 11:05:20.736 D/Mono    (32399): Probing '__android_log_print'.
01-26 11:05:20.736 D/Mono    (32399): Found as '__android_log_print'.
01-26 11:05:20.743 I/MonoDroid(32399): UNHANDLED EXCEPTION:
01-26 11:05:20.777 I/MonoDroid(32399): Java.Lang.IllegalArgumentException: pointerIndex out of range
01-26 11:05:20.777 I/MonoDroid(32399):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-26 11:05:20.777 I/MonoDroid(32399):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualBooleanMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <54816278eed9488eb28d3597fecd78f8>:0 
01-26 11:05:20.777 I/MonoDroid(32399):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <54816278eed9488eb28d3597fecd78f8>:0 
01-26 11:05:20.777 I/MonoDroid(32399):   at Android.Views.ViewGroup.OnInterceptTouchEvent (Android.Views.MotionEvent ev) [0x00031] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
01-26 11:05:20.777 I/MonoDroid(32399):   at Xamarin.Forms.Platform.Android.AppCompat.FormsViewPager.OnInterceptTouchEvent (Android.Views.MotionEvent ev) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsViewPager.cs:26 
01-26 11:05:20.777 I/MonoDroid(32399):   at Android.Views.ViewGroup.n_OnInterceptTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_ev) [0x0000f] in <28e323a707a2414f8b493f6d4bb27c8d>:0 
01-26 11:05:20.777 I/MonoDroid(32399):   at (wrapper dynamic-method) System.Object:86d9ec6a-643b-4c86-8767-b306c0996837 (intptr,intptr,intptr)
01-26 11:05:20.777 I/MonoDroid(32399):   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
01-26 11:05:20.777 I/MonoDroid(32399): java.lang.IllegalArgumentException: pointerIndex out of range
01-26 11:05:20.777 I/MonoDroid(32399):  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-26 11:05:20.777 I/MonoDroid(32399):  at android.view.MotionEvent.getX(MotionEvent.java:2136)
01-26 11:05:20.777 I/MonoDroid(32399):  at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
01-26 11:05:20.777 I/MonoDroid(32399):  at md5270abb39e60627f0f200893b490a1ade.FormsViewPager.n_onInterceptTouchEvent(Native Method)
01-26 11:05:20.777 I/MonoDroid(32399):  at md5270abb39e60627f0f200893b490a1ade.FormsViewPager.onInterceptTouchEvent(FormsViewPager.java8)
01-26 11:05:20.777 I/MonoDroid(32399):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
01-26 11:05:20.777 I/MonoDroid(32399):  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-26 11:05:20.777 I/MonoDroid(32399):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-26 11:05:20.777 I/MonoDroid(32399):  at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
01-26 11:05:20.777 I/MonoDroid(32399):  at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:64)

### Expected Behavior
Tap must be handled between child and parent.

### Actual Behavior
App crashing.

### Basic Information
- Version with issue: Xamarin 2.4.0
- Last known good version: Android 4.1+
- Platform Target Frameworks: VS 2015
- Android: 4.1 above 

### Reproduction Link
https://issuetracker.google.com/issues/36931456

**Comment by rmarinho** [comment] 2018-02-05 16:53
Hi, we need to see a reproduction so we can take a look at the issue and check  if the issue is fixed with newer versions.

**Comment by Nijamudeen-Mohamed** [comment] 2018-02-08 11:46
Hi Rui Marinho,

**About the attached sample:**
We have added SfSchedule control (Custom Control) in a tabbed page and we have set Month view in that. It has a support to display the appointments/events in the inline view of SfSchedule month view.

You can check our documentation to know further about the inline view of month view in the SfSchedule.
https://help.syncfusion.com/xamarin/sfschedule/monthview#month-inlineview

**Issue replication procedure:**
Once the application is deployed, move to schedule page (available at the center of the tabbed pages in the sample). Then randomly tap different cells in different rows with fingers simultaneously. After several taps on the cells, the application gets crashed with the mentioned exception, "java.lang.IllegalArgumentException: pointerIndex out of range .... ”

**It happens only when we host the control in the tabbed page, other pages are working fine.**

Kindly find the respective sample, .apk and video attached,
**Sample:**[SchedulSample.zip](https://github.com/xamarin/Xamarin.Forms/files/1706863/SchedulSample.zip)

**Sample Apk:** [SfScheduleSample-APK.zip (https://github.com/xamarin/Xamarin.Forms/files/1706845/SfScheduleSample-APK.zip)

**Video:** [SfSchedule_Video.zip](https://github.com/xamarin/Xamarin.Forms/files/1706844/SfSchedule_Video.zip)

Hope above details are enough to replicate the issue. Could you please check the above details and provide us a possible solution for this.
 
Regards,
Nijamudeen M.

**Comment by jassmith** [comment] 2018-02-08 19:03
Thank you :)

**Comment by EmilAlipiev** [comment] 2020-03-16 00:51
wow i have this error also now. i use sfschedule as well but i dont use tabbedpage instead masterdetailpage. Have you reported this to Syncfusion team as well? is it Xamarin issue or Synfusion? any update i appreciate

**Comment by Nijamudeen-Mohamed** [comment] 2020-03-16 06:00
Yes, we are from Syncfusion

**Comment by EmilAlipiev** [comment] 2020-03-16 08:18
And no update? I tried to reproduce myself but I couldn't like your video but I can see same crash logs from other users in my appcenter logs

**Comment by samhouts** [comment] 2020-09-15 00:33
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment] 2020-10-15 19:14
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by Redth** 2020-10-15 19:14 UTC
Labels: e/4 :clock4:, help wanted, p/Android, partner, s/needs-info ❓, t/bug :bug:, up-for-grabs

**Comment by lassana** [comment] 2021-06-28 11:26
We occasionally receive crash reports caused by this. Has anyone managed to solve it in their apps?

Our stacktrace:

```
Java.Lang.IllegalArgumentException

Message: pointerIndex out of range
Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualBooleanMethod(Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) in <245d6604196e4bb3b94db235a27bebae>
Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod(System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) in <245d6604196e4bb3b94db235a27bebae>
Android.Views.ViewGroup.OnInterceptTouchEvent(Android.Views.MotionEvent ev) in <b2471e8396b24c3b808a960b18f1ec75>
Xamarin.Forms.Platform.Android.AppCompat.FormsViewPager.OnInterceptTouchEvent(Android.Views.MotionEvent ev) in <b5522d01ddf343eeb28aa57d909287a4>
Android.Views.ViewGroup.n_OnInterceptTouchEvent_Landroid_view_MotionEvent_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_ev) in <b2471e8396b24c3b808a960b18f1ec75>
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.29(intptr,intptr,intptr)
--- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: pointerIndex out of range
android.view.MotionEvent.nativeGetAxisValue(Native Method)
android.view.MotionEvent.getX in MotionEvent.java:2608
androidx.viewpager.widget.ViewPager.onInterceptTouchEvent in Unknown Source:57
crc64720bb2db43a66fe9.FormsViewPager.n_onInterceptTouchEvent(Native Method)
crc64720bb2db43a66fe9.FormsViewPager.onInterceptTouchEvent in Unknown Source
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2753
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3244
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent in Unknown Source
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent in Unknown Source
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
crc643f46942d9dd1fff9.PlatformRenderer.n_dispatchTouchEvent(Native Method)
crc643f46942d9dd1fff9.PlatformRenderer.dispatchTouchEvent in Unknown Source
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
android.view.ViewGroup.dispatchTransformedTouchEvent in ViewGroup.java:3222
android.view.ViewGroup.dispatchTouchEvent in ViewGroup.java:2904
com.android.internal.policy.DecorView.superDispatchTouchEvent in DecorView.java:752
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent in PhoneWindow.java:1880
android.app.Activity.dispatchTouchEvent in Activity.java:3494
androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent in Unknown Source:2
androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent in Unknown Source:2
com.android.internal.policy.DecorView.dispatchTouchEvent in DecorView.java:704
android.view.View.dispatchPointerEvent in View.java:13723
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent in ViewRootImpl.java:6235
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess in ViewRootImpl.java:6013
android.view.ViewRootImpl$InputStage.deliver in ViewRootImpl.java:5462
android.view.ViewRootImpl$InputStage.onDeliverToNext in ViewRootImpl.java:5515
android.view.ViewRootImpl$InputStage.forward in ViewRootImpl.java:5481
android.view.ViewRootImpl$AsyncInputStage.forward in ViewRootImpl.java:5640
android.view.ViewRootImpl$InputStage.apply in ViewRootImpl.java:5489
android.view.ViewRootImpl$AsyncInputStage.apply in ViewRootImpl.java:5697
android.view.ViewRootImpl$InputStage.deliver in ViewRootImpl.java:5462
android.view.ViewRootImpl$InputStage.onDeliverToNext in ViewRootImpl.java:5515
android.view.ViewRootImpl$InputStage.forward in ViewRootImpl.java:5481
android.view.ViewRootImpl$InputStage.apply in ViewRootImpl.java:5489
android.view.ViewRootImpl$InputStage.deliver in ViewRootImpl.java:5462
android.view.ViewRootImpl.deliverInputEvent in ViewRootImpl.java:8545
android.view.ViewRootImpl.doProcessInputEvents in ViewRootImpl.java:8459
android.view.ViewRootImpl.enqueueInputEvent in ViewRootImpl.java:8412
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent in ViewRootImpl.java:8660
android.view.InputEventReceiver.dispatchInputEvent in InputEventReceiver.java:198
android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
android.view.InputEventReceiver.consumeBatchedInputEvents in InputEventReceiver.java:187
android.view.ViewRootImpl.doConsumeBatchedInput in ViewRootImpl.java:8619
android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run in ViewRootImpl.java:8687
android.view.Choreographer$CallbackRecord.run in Choreographer.java:988
android.view.Choreographer.doCallbacks in Choreographer.java:765
android.view.Choreographer.doFrame in Choreographer.java:694
android.view.Choreographer$FrameDisplayEventReceiver.run in Choreographer.java:967
android.os.Handler.handleCallback in Handler.java:873
android.os.Handler.dispatchMessage in Handler.java:99
android.os.Looper.loop in Looper.java:214
android.app.ActivityThread.main in ActivityThread.java:7156
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run in RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main in ZygoteInit.java:975
```

**Comment by Odmar** [comment] 2022-07-11 10:40
Hello!

we one case of this issue in our AppCenter logs. Is this still an issue?

Version with issue: Xamarin.Forms 5.0.0
Last known good version: Android 4.1+
Platform Target Frameworks: VS 2019

here is our stack trace:
Java.Lang.IllegalArgumentException: pointerIndex out of range
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualBooleanMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00063] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Android.Views.ViewGroup.OnInterceptTouchEvent (Android.Views.MotionEvent ev) [0x00031] in <07581e20e5714fffa8c24503df31b2e9>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.FormsViewPager.OnInterceptTouchEvent (Android.Views.MotionEvent ev) [0x00008] in <a5e986d8b6584931a2ca203c438907dc>:0 
  at Android.Views.ViewGroup.n_OnInterceptTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_ev) [0x0000f] in <07581e20e5714fffa8c24503df31b2e9>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.38(intptr,intptr,intptr)
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2775)
	at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
	at crc64720bb2db43a66fe9.FormsViewPager.n_onInterceptTouchEvent(Native Method)
	at crc64720bb2db43a66fe9.FormsViewPager.onInterceptTouchEvent(FormsViewPager.java:38)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3454)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:68)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at crc643f46942d9dd1fff9.PlatformRenderer.n_dispatchTouchEvent(Native Method)
	at crc643f46942d9dd1fff9.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:55)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8570)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
