### ISSUE TITLE
CarouselView crashing on iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14954] opened 2021-12-03 17:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CarouselView-crashing-on-iOS/1600742)._

---
I have a very simple CarouselView in my forms app

&lt;StackLayout VerticalOptions=&quot;Center&quot; Padding=&quot;16,24&quot; BackgroundColor=&quot;Transparent&quot;&gt;
        &lt;StackLayout VerticalOptions=&quot;Center&quot; Padding=&quot;12&quot; BackgroundColor=&quot;White&quot; 
                     HeightRequest=&quot;350&quot;&gt;
            &lt;CarouselView PeekAreaInsets=&quot;12&quot; ItemTemplate=&quot;{StaticResource templateSelector}&quot; x:Name=&quot;view&quot;
                           ItemsSource=&quot;{Binding ClassNames}&quot; HeightRequest=&quot;320&quot; HorizontalOptions=&quot;FillAndExpand&quot;&gt;
                &lt;CarouselView.ItemsLayout&gt;
                    &lt;LinearItemsLayout Orientation=&quot;Horizontal&quot; /&gt;
                &lt;/CarouselView.ItemsLayout&gt;
            &lt;/CarouselView&gt;
        &lt;/StackLayout&gt;
    &lt;/StackLayout&gt;

The views are pulled in from a TemplatSelector in the code behind. This works fine.

When the view is created, the app crashes with the following in the application output

2021-12-01 13:56:15.183 PureSMS.iOS[567:70015] The behavior of the UICollectionViewFlowLayout is not defined because:
2021-12-01 13:56:15.183 PureSMS.iOS[567:70015] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2021-12-01 13:56:15.183 PureSMS.iOS[567:70015] The relevant UICollectionViewFlowLayout instance is &lt;Xamarin_Forms_Platform_iOS_CarouselViewLayout: 0x14ac19ce0&gt;, and it is attached to &lt;UICollectionView: 0x14db4ae00; frame = (0 0; 358 320); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = &lt;NSArray: 0x280a04420&gt;; layer = &lt;CALayer: 0x280d03600&gt;; contentOffset: {668, 0}; contentSize: {2028, 320}; adjustedContentInset: {0, 0, 0, 0}; layout: &lt;Xamarin_Forms_Platform_iOS_CarouselViewLayout: 0x14ac19ce0&gt;; dataSource: &lt;Xamarin_Forms_Platform_iOS_CarouselViewController: 0x147ff2580&gt;&gt;.
2021-12-01 13:56:15.183 PureSMS.iOS[567:70015] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

This looks to be related to https://github.com/xamarin/Xamarin.Forms/issues/13323

---
#### Feedback Bot on 12/2/2021, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment] 2021-12-06 14:25
Duplicate of #13323

**Closed by jfversluis** 2021-12-06 14:25 UTC
