### ISSUE TITLE
[Bug] Home button crash Xamarin Forms iOS

### ISSUE THREAD

**Issue by procopio** [xamarin/Xamarin.Forms#10715] opened 2020-05-15 17:55 UTC
### Description

After upgrade from XF 4.6.0.726 to XF 4.6.0.772 my app crash when press Home button on iOS.

### Steps to Reproduce

1.  Download and open the sample Xamarin.Forms - Theming from https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-theming/
2.  Update to XF 4.6.0.772
3. Run
4. Press Home button on iOS device

### Expected Behavior

No crash

### Actual Behavior

Crash with error: 
```
System.ArgumentNullException: Value cannot be null.
Parameter name: enumerable
  at Xamarin.Forms.Internals.EnumerableExtensions.IndexOf[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, T item) [0x00003] in D:\a\1\s\Xamarin.Forms.Core\EnumerableExtensions.cs:79
  at Xamarin.Forms.Application.OnRequestedThemeChanged (Xamarin.Forms.AppThemeChangedEventArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:172
  at Xamarin.Forms.Platform.iOS.PageRenderer.TraitCollectionDidChange (UIKit.UITraitCollection previousTraitCollection) [0x00021] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:373
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65
  at Rabbit2.iOS.Application.Main (System.String[] args) [0x00001] in /Users/joaofortes/Documents/Dev/Rabbit2/Rabbit2/Rabbit2.iOS/Main.cs:17
```

### Basic Information

- Version with issue: XF 4.6.0.772
- Last known good version: XF 4.6.0.726
- IDE: VS Mac 8.5.6 (build 11)
- Platform Target Frameworks: 
  - iOS:  13.4.1

**Comment by myonlinegolfclub** [comment] 2020-05-16 09:27
Hi
I am also experiencing the exact same issue.
Thanks

**Comment by richp582** [comment] 2020-05-16 13:29
Same!  Just updated and when I background my app, it dies... worked perfectly prior to .772

**Comment by glintpursuit** [comment] 2020-05-16 18:16
Facing same issue.
When app goes in background it will crash.

**Comment by PureWeen** [comment] 2020-05-16 20:03
Duplicate of this issue. Here's a workaround https://github.com/xamarin/Xamarin.Forms/issues/10712#issuecomment-629394090

We're working to get an SR out for this soon

**Closed by PureWeen** 2020-05-16 20:03 UTC
Labels: s/unverified, t/bug :bug:

**Comment by K232** [comment] 2020-05-24 08:57
Seems that 4.6.0.800 has fixed it 👍

**Comment by glintpursuit** [comment] 2020-05-24 12:16
> Seems that 4.6.0.800 has fixed it 👍

So it's working without below line? 

`  Xamarin.Forms.Forms.SetFlags("anything");`

**Comment by K232** [comment] 2020-05-24 14:28
@glintpursuit Yes, for me it's fine. Tested on simulator, no crash when click on home button.
