### ISSUE TITLE
Xamarin.Forms - programmatically changing CornerRadius of a BoxView causes it to become invisible

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12906] opened 2020-11-19 12:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/XamarinForms---programmatically-changin/1248382?preview=true)._

---
[severity:It's more difficult to complete my work]
Programmatically changing the corner radius of a BoxView in Xamarin Forms causes it to become invisible. It can be set in XAML but setting the CornerRadius property, either to a double or to a CornerRadius struct, causes the BoxView to seem to vanish.

The problem seems to be specific to Xamarin.Forms NuGet packages v4.8.x.x.

Steps to reproduce:
1. Download the BoxView sample solution:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/boxview-basicboxview

2. Add a button that changes the corner radius of the BoxView and run in an emulator (I've reproduced the problem in emulators running Android 7 and 9, but not on a real device).

3. Click the button.

Expected result:
The corner radius should change.

Actual result:
The BoxView becomes invisible. No errors appear to be generated.

It works up to Xamarin.Forms v4.7.0.1351, but the bug appears in all versions from v4.8.0.1269, including the latest v4.8.0.1560.

Running in VS 2019. Everything, including the Android SDKs, etc., are up-to-date.

---
#### Feedback Bot on 11/10/2020, 02:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/12/2020, 10:22 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 11/12/2020, 03:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Robert Palmer on 11/17/2020, 00:49 PM: 

<p>Please can I check if there's any word on this? It's been a week and this is actively preventing me from progressing from Internal Testing to Closed Beta, unless I implement a clunky workaround.</p>

---
### Original Solutions
(no solutions)

**Comment by AndyNetDuma** [comment] 2021-01-07 17:33
We ran into this issue at work too. It happens on forms v5 too.
I found a frame doesn't have the same issue. So for a temp workaround swap boxviews to frames and set padding to 0. It isn't ideal as frames have content but it renders fine for not much extra overhead.

**Comment by AndyNetDuma** [comment] 2021-03-30 13:43
> This is issue for me too. Bug was introduced with XF 4.8. On XF 4.7 it still works. Can we get any feedback on this?

I wouldn't hold out. The xamarin team are generally very slow to fix issues even if they are critical breaking bugs like this.
Using frames instead has been good enough for us to use in production.

**Comment by jfversluis** [comment] 2023-11-09 10:27
Duplicate of #12061

**Closed by jfversluis** 2023-11-09 10:27 UTC
Labels: t/bug :bug:, p/Android, e/2 :clock2:, i/high, s/unverified, in-progress, a/boxview
