### ISSUE TITLE
The type GridLength does not support direct content

### ISSUE THREAD

**Issue by Sonic3R** [xamarin/Xamarin.Forms#4212] opened 2018-10-25 09:11 UTC
### Description
When use 

`<GridLength x:Key="whatever">0</GridLength>`

I got error : 

> The type 'GridLength' does not support direct content.

Same thing happens to `Thickness` too:

`<Thickness x:Key="whatever1">0,0,0,0</Thickness>`

I created `GridLengthConverter` but I don't know how to apply to it

```
public sealed class GridLengthConverter : IValueConverter
  {
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
      return 0;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
      return 0;
    }
  }
```

### Steps to Reproduce

1. Create `<ResourceDictionary>` node in xaml
2. Write `<GridLength x:Key="whatever">0</GridLength>`
3. Close node `<ResourceDictionary>`

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: 2.5.1.527436
- IDE: VS 2017
- Platform Target Frameworks:
  - iOS:  12.0
  - UWP:  16299

**Comment by StephaneDelcroix** [comment] 2018-10-25 09:47
I tested this XAML file:
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="Xamarin.Forms.Xaml.UnitTests.Gh4212">
	<ContentPage.Resources>
		<GridLength x:Key="gl">42</GridLength>
		<Thickness x:Key="thick">42,42,42,42</Thickness>
	</ContentPage.Resources>
</ContentPage>
```
On both 3.3.0 and 3.4.0, with and without XamlC enabled, and was unable to reproduce your issue.
I'm closing this issue. Feel free to reopen with a valid reproduction project.

**Closed by StephaneDelcroix** 2018-10-25 09:47 UTC
Labels: a/Xaml </>, e/4 :clock4:, t/bug :bug:, t/enhancement ➕

**Comment by TheBoJaN** [comment] 2018-11-26 21:31
I'm getting the same issue on 3.4.0, VS would show an error saying 

> The type 'GridLength' does not support direct content.

However, I could still use the property just fine and if I rebuild, the error disappears. I keep getting a similar "error" where, when using a custom type converter, VS complains about the type converter not being found in the namespace and rebuilding fixes that as well.

The errors do seem to come back after a while, I'm not sure what triggers it, maybe editing the xaml or .cs? I've learned to just ignore them for now as they don't seem to be an actual issue but it is a rather odd bug.

**Comment by JayMansel** [comment] 2019-10-10 11:06
Same issue here. Everything still works, I can use the property. If I don't have the XAML file in question open, I don't get the errors in output window.

![image](https://user-images.githubusercontent.com/2752403/66563789-725e2c80-eb56-11e9-8e1c-61619eb5b499.png)

**Comment by BillyMartin1964** [comment] 2019-12-30 18:22
I get the same issue when trying to bind the size of a grid row from the ViewModel.

In Xaml:

```
<Grid.RowDefinitions>
                    <RowDefinition Height="1.5*" />
                    <RowDefinition Height="1.5*" />
                    <RowDefinition Height="1.5*" />
                    <RowDefinition Height="1.5*" />
                    <RowDefinition Height="1.5*" />
                    <RowDefinition Height="1.5*"  />
                    <RowDefinition Height="*" />
                    <RowDefinition Height="{Binding AdRowHeight}" />
                </Grid.RowDefinitions>

```

In the ViewModel:

```
public GamePlayViewModel()
{
 if (App.Premium)
            {
                AdStackLayoutVisible = false;
                AdRowHeight = new GridLength(0, GridUnitType.Star);
            }
            else
            {
                AdStackLayoutVisible = true;
                AdRowHeight = new GridLength(1, GridUnitType.Star);
            }
}


   private GridLength adRowHeight;
        public GridLength AdRowHeight
        {
            get { return adRowHeight; }
            set
            {
                adRowHeight = value;
                OnPropertyChanged();
            }
        }
```
