### ISSUE TITLE
[Bug] Label word wrapped incorrectly on iOS

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11713] opened 2020-08-09 09:09 UTC
Labels get cut off incorrectly on iOS, depending on the exact contents of the string, where exactly it breaks and screen dimensions. I suspect this is the same issue I reported at https://github.com/xamarin/Xamarin.Forms/issues/11633 but manifested in a different way.

Please see the following image:

![Screenshot 2020-08-09 at 13 02 03](https://user-images.githubusercontent.com/60286968/89729694-e603eb00-da40-11ea-9126-12d475599eeb.png)

There are two problems here -- the label is cutting off words too early (more would fit), and it doesn't draw the rest of the string on the second line (even though the label has allocated space there).

Adding a dot at the end of the sentence makes it draw correctly:

![Screenshot 2020-08-09 at 13 02 20](https://user-images.githubusercontent.com/60286968/89729712-07fd6d80-da41-11ea-9885-11c204b25063.png)

```xaml
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span
                                Text="Create a "
                                Style="{StaticResource TitleLabelStyle}" />
                            <Span
                                Text="PUBLIC "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="or "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="FRIENDS "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="activity?"
                                Style="{StaticResource TitleLabelStyle}" />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>

                <!-- and -->

                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span
                                Text="Create a "
                                Style="{StaticResource TitleLabelStyle}" />
                            <Span
                                Text="PUBLIC "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="or "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="FRIENDS "
                                Style="{StaticResource TitleLabelBoldStyle}" />
                            <Span
                                Text="activity? ."
                                Style="{StaticResource TitleLabelStyle}" />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
```

**Comment by Tommigun1980** [comment] 2020-08-09 09:58
EDIT: The last case, a perfectly normal string in a vertical layout sometimes (depending on the exact words and font size) completely cuts off the label. It seems to allocate vertical space but doesn't draw anything there (in addition to cutting it off too early):

![Screenshot 2020-08-09 at 12 56 50](https://user-images.githubusercontent.com/60286968/89729597-fb2c4a00-da3f-11ea-9d8f-6ef9f9303127.png)

**Comment by Tommigun1980** [comment] 2020-08-09 10:11
The problems seem to happen only if the last character in the label would introduce a line break. Depending on the container the results are different but still always wrong.

**Comment by rmarinho** [comment] 2020-08-11 17:20
Can you share the Styles ?

**Comment by rmarinho** [comment] 2020-08-11 17:30
Here's what i ahve now 
```
  <StackLayout>
        <Label>
            <Label.FormattedText>
                <FormattedString>
                    <FormattedString.Spans>
                        <Span
                                Text="Create a " />
                        <Span
                                Text="PUBLIC " />
                        <Span
                                Text="or "/>
                        <Span
                                Text="FRIENDS "
                               />
                        <Span
                                Text="activity?"
                                 />
                    </FormattedString.Spans>
                </FormattedString>
            </Label.FormattedText>
        </Label>
        <Label>
            <Label.FormattedText>
                <FormattedString>
                    <FormattedString.Spans>
                        <Span
                                Text="Create a "
                                 />
                        <Span
                                Text="PUBLIC "
                                />
                        <Span
                                Text="or "
                                 />
                        <Span
                                Text="FRIENDS "
                                />
                        <Span
                                Text="activity? ."
                                />
                    </FormattedString.Spans>
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </StackLayout>
```

**Comment by Tommigun1980** [comment] 2020-08-15 01:17
Hi @rmarinho - I will try to edit the project as soon as I get the chance. One thing I noticed is that it only seems to happen when you have a custom font set -- I don't know if it's related to actually having a custom font, or if the custom font just happens to align so that the issue is exposed. I am using 'Source Sans Pro' for the 'regular' spans, and the Bold font attribute in the capitalised words.

**Comment by Tommigun1980** [comment] 2020-08-19 01:59
Hi @rmarinho. Please find attached the repro project edited with styles that break the labels. It's actually hard not to come up with a permutation that flows the text incorrectly so I have a hard time styling my app atm.

Here is a screenshot of the problem. The first two (red) entries are drawn incorrectly:

<img width="584" alt="Screenshot 2020-08-19 at 4 47 41" src="https://user-images.githubusercontent.com/60286968/90583351-96f44d80-e1d8-11ea-911a-edd52a5d3dfd.png">

1) The first one completely stops drawing the text (albeit it occupies two lines of space - maybe this is the root cause for https://github.com/xamarin/Xamarin.Forms/issues/11729?).
2) The second one draws all text, but puts the line break too early.
3) The third one is drawn correctly.

Repro steps: Run the project in iOS and set the simulator to iPhone 11.

To get the error to happen, just use different fonts (and/or possibly bold/regular text, didn't test all permutations) in different spans in a label. The third one also uses different fonts, but adding some characters at the end magically makes it draw itself properly. Please note that what gets drawn correctly is dependent on the device's screen size, so you might get different results on different simulators, hence please use iPhone 11 for reproduction.

I would really love a resolution to this as I think the following issues may be connected to this bug, and if not, at the very least this bug makes styling apps really difficult:
https://github.com/xamarin/Xamarin.Forms/issues/11633
https://github.com/xamarin/Xamarin.Forms/issues/11634

Thanks.

**Comment by Tommigun1980** [comment] 2020-08-19 02:04
Hi @rmarinho. Please find attached the repro project edited with styles that break the labels. It's actually hard not to come up with a permutation that flows the text incorrectly so I have a hard time styling my app atm.

Here is a screenshot of the problem. The first two (red) entries are drawn incorrectly:

<img width="584" alt="Screenshot 2020-08-19 at 4 47 41" src="https://user-images.githubusercontent.com/60286968/90583650-5a752180-e1d9-11ea-95aa-a9f8fc476b42.png">


1) The first one completely stops drawing the text (albeit it occupies two lines of space - maybe this is the root cause for https://github.com/xamarin/Xamarin.Forms/issues/11729?).
2) The second one draws all text, but puts the line break too early.
3) The third one is drawn correctly.

Repro steps: Run the project in iOS and set the simulator to iPhone 11.

To get the error to happen, just use different fonts (and/or possibly bold/regular text, didn't test all permutations) in different spans in a label. The third one also uses different fonts, but adding some characters at the end magically makes it draw itself properly. Please note that what gets drawn correctly is dependent on the device's screen size, so you might get different results on different simulators, hence please use iPhone 11 for reproduction.

I would really love a resolution to this as I think the following issues may be connected to this bug, and if not, at the very least this bug makes styling apps really difficult:
https://github.com/xamarin/Xamarin.Forms/issues/11633
https://github.com/xamarin/Xamarin.Forms/issues/11634
https://github.com/xamarin/Xamarin.Forms/issues/11729

Thanks.

Repro project:
[Linebreak.zip](https://github.com/xamarin/Xamarin.Forms/files/5093660/Linebreak.zip)

**Comment by Tommigun1980** [comment] 2020-08-19 02:07
So TLDR, this doesn't work:

```xaml
        <Label BackgroundColor="Red">
            <Label.FormattedText>
                <FormattedString>
                    <FormattedString.Spans>
                        <Span
                            Text="Create a "
                            FontSize="Title"/>
                        <Span
                            Text="PUBLIC"
                            FontSize="Title"
                            FontFamily="Source Sans Pro"  />
                        <Span
                            Text=" or "
                            FontSize="Title"/>
                        <Span
                            Text="FRIENDS"
                            FontSize="Title"
                            FontFamily="Source Sans Pro"  />
                        <Span
                            Text=" activity?"
                            FontSize="Title"/>
                    </FormattedString.Spans>
                </FormattedString>
            </Label.FormattedText>
        </Label>
```

**Comment by Tommigun1980** [comment] 2020-08-19 02:37
Hi @rmarinho. Please find attached the repro project edited with styles that break the labels. It's actually hard to come up with a permutation that doesn't flow the the text incorrectly so I have a hard time styling my app atm. Different screens break the text in different places, where some are correct and some are not, hence I can't find anything that works everywhere.

Here is a screenshot of the problem. The first two (red) entries are drawn incorrectly:

<img width="584" alt="Screenshot 2020-08-19 at 4 47 41" src="https://user-images.githubusercontent.com/60286968/90585652-091b6100-e1de-11ea-82ca-1ec84158aef9.png">


The first one completely stops drawing the text (albeit it occupies two lines of space - maybe this is the root cause for #11729?).
The second one draws all text, but puts the line break too early.
The third one is drawn correctly.
Repro steps: Run the project in iOS and set the simulator to iPhone 11.

To get the error to happen, just use different fonts (and/or possibly bold/regular text, didn't test all permutations) in different spans in a label. The third one also uses different fonts, but adding some characters at the end magically makes it draw itself properly. Please note that what gets drawn correctly is dependent on the device's screen size, so you might get different results on different simulators, hence please use iPhone 11 for reproduction.

I would really love a resolution to this as I think the following issues may be connected to this bug, and if not, at the very least this bug makes styling apps really difficult:
#11633
#11634
#11729

Thanks.

Repro project:
[Linebreak.zip](https://github.com/xamarin/Xamarin.Forms/files/5093745/Linebreak.zip)

**Comment by Tommigun1980** [comment] 2020-08-19 02:38
So TLDR, this doesn't work:

```xaml
        <Label BackgroundColor="Red">
            <Label.FormattedText>
                <FormattedString>
                    <FormattedString.Spans>
                        <Span
                            Text="Create a "
                            FontSize="Title"/>
                        <Span
                            Text="PUBLIC"
                            FontSize="Title"
                            FontFamily="Source Sans Pro"  />
                        <Span
                            Text=" or "
                            FontSize="Title"/>
                        <Span
                            Text="FRIENDS"
                            FontSize="Title"
                            FontFamily="Source Sans Pro"  />
                        <Span
                            Text=" activity?"
                            FontSize="Title"/>
                    </FormattedString.Spans>
                </FormattedString>
            </Label.FormattedText>
        </Label>
```

**Comment by jsuarezruiz** [comment] 2020-08-28 10:35
Seems to be related with https://github.com/xamarin/Xamarin.Forms/issues/11729
Could be fixed by: https://github.com/xamarin/Xamarin.Forms/pull/11903 (need to verify)

**Comment by jsuarezruiz** [comment] 2020-08-28 10:46
Ok, I have good news!.

This was the result using 4.8.0.1269:
![Simulator Screen Shot - iPhone 11 - 2020-08-28 at 12 43 47](https://user-images.githubusercontent.com/6755973/91552611-5f9a4500-e92c-11ea-97ab-5a2b368c755e.png)

And, this is the result in 4.8 branch (with the changes from 11903):
![Simulator Screen Shot - iPhone 11 - 2020-08-28 at 12 44 51](https://user-images.githubusercontent.com/6755973/91552605-5d37eb00-e92c-11ea-8849-85ecc2b39677.png)

cc @hartez

**Comment by Tommigun1980** [comment] 2020-08-28 19:32
> @Tommigun1980 Ok, I have good news!.
> 
> This was the result using 4.8.0.1269:
> ![Simulator Screen Shot - iPhone 11 - 2020-08-28 at 12 43 47](https://user-images.githubusercontent.com/6755973/91552611-5f9a4500-e92c-11ea-97ab-5a2b368c755e.png)
> 
> And, this is the result in 4.8 branch (with the changes from 11903):
> ![Simulator Screen Shot - iPhone 11 - 2020-08-28 at 12 44 51](https://user-images.githubusercontent.com/6755973/91552605-5d37eb00-e92c-11ea-8849-85ecc2b39677.png)
> 
> cc @hartez

Hi @rmarinho, great news indeed! I don't think this is 100% fixed yet though, as the first two examples in the repro case still break the string too early. Padding it with "sdf sadf" (or any other string of somewhat equivalent length) makes it flow correctly. In the first two examples, after the fix https://github.com/xamarin/Xamarin.Forms/pull/11903, the word "FRIENDS" should fit on the first line, no? I don't know why, but as I said padding it slightly will "push" it to flow correctly.

Thanks!

**Comment by hartez** [comment] 2020-09-04 20:07
@Tommigun1980 This isn't a Forms bug; it's the underlying UILabel control acting as designed. Somewhere around iOS 11 Apple modified the UILabel's line break code to prevent [orphans (in the typography sense)](http://www.magazinedesigning.com/typographic-widows-and-orphans/). So you're right - the word "FRIENDS" _could_ fit on the first line, but the UILabel drops it to the second line to prevent "activity?" from being orphaned. When you add extra text at the end (like "sdf sadf"), the UILabel no longer needs to drop "FRIENDS" to the second line to prevent orphaning "activity?", so it leaves it on the first line. 

Forms doesn't currently provide a way to disable this behavior (nor, AFAIK, does Apple). But if it's a concern, I would suggest opening an enhancement issue. We'd probably have to add a Platform Specific for disabling this behavior.

**Closed** 2020-09-04 20:07 UTC
Labels: a/label, p/iOS 🍎, s/unverified, t/bug :bug:

**Comment by Tommigun1980** [comment] 2020-10-04 14:12
@hartez I see, thanks for the explanation. And thanks for the fix @rmarinho!

**Comment by somoreingold** [comment] 2021-01-02 08:09
@jsuarezruiz Hello, Is the fix for this included in the latest stable release? I'm still experiencing this issue in Xamarin.Forms 4.8.0.1821.  (the first red label in this screenshot: https://user-images.githubusercontent.com/6755973/91552611-5f9a4500-e92c-11ea-97ab-5a2b368c755e.png ).
