### ISSUE TITLE
[Bug] Frame IsVisible="False" ignored on iOS

### ISSUE THREAD

**Issue by Soccer8** [xamarin/Xamarin.Forms#9892] opened 2020-03-09 09:07 UTC
### Description
The IsVisible setting on a XAML Frame element is ignored on iOS.

### Steps to Reproduce

1.  Create a <Frame IsVisible="False" on a ContentPage
2. Run your App
3. The Frame is still visible in iOS, whereas it is invisible on Android

### Expected Behavior
The Frame element should be hidden

### Actual Behavior
The Frame element is visible (on iOS)

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: 4.4.0.991
- IDE: Visaul Studio 2019
- Platform Target Frameworks: 
  - iOS:  8.0, 13.2 tested (fail)
  - Android: 9.0 OK

### Workaround
Downgrade back to version 4.4.0.991

**Comment by Soccer8** [comment] 2020-03-09 09:11
My specific Frame, 1 of 2 on the page (both incorrectly visible on iOS)
        <Frame
            x:Name="HeaderTooltipHolder"
            IsVisible="False"
            BorderColor="Black"
            AbsoluteLayout.LayoutBounds="0.5, 0.5, 0.9, 60"
            AbsoluteLayout.LayoutFlags="PositionProportional, WidthProportional">

            <Frame.GestureRecognizers>
                <TapGestureRecognizer Tapped="OnMatrixTapped" />
            </Frame.GestureRecognizers>

            <Label
                x:Name="HeaderTooltip"
                HorizontalOptions="CenterAndExpand"
                TextColor="Black" />
        </Frame>

**Comment by GalaxiaGuy** [comment] 2020-03-09 10:21
Appears to be the same issue as https://github.com/xamarin/Xamarin.Forms/issues/9782 and may already be fixed.

Until that is released, I managed to work around it by also removing the shadow when I needed to hide the frame

**Comment by StephaneDelcroix** [comment] 2020-03-12 13:56
duplicate of #9782

**Closed by StephaneDelcroix** 2020-03-12 13:56 UTC
Labels: s/unverified, t/bug :bug:

**Comment by shidem** [comment] 2020-03-13 15:22
The work around setting HasShadow=False did the trick for me as well. Kudos to GalaxiaGuy!
