### ISSUE TITLE
[Bug] CollectionView - iOS - Crash when adding first item to empty item group 

### ISSUE THREAD

**Issue by rroesler** [xamarin/Xamarin.Forms#9580] opened 2020-02-14 03:50 UTC
### Description

CollectionView with Grouping enabled.   When items dynamically added to an empty group (and the collection changed event posted), 

Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
Native stack trace:
	0   CoreFoundation                      0x00007fff23c7127e 

Please note:  Adding items directly to the ObservableCollection instead of to it's Item list does not change the outcome. 
The exception is thrown as soon as OnCollectionChanged is triggered, regardless of how it is triggered.   Tried several variations to see if there was something wrong in the code. 

This same code works as expected on Android 

### Steps to Reproduce

1.  Run the attached example 
2.  Select "Grouping with variable sized items" 
3.  Click/tap any of the displayed group headers.

### Expected Behavior

Tap triggers the adding of the members of the group to the group's ObservableColelction.  
CollectionView then display the expanded group. 

### Actual Behavior

Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
Native stack trace:
	0   CoreFoundation                      0x00007fff23c7127e 

### Basic Information

- Version with issue:  Xamarin.Forms 4.4.0.991265 
- Last known good version: unknown 
- IDE: Visual Studio 2019 with all updates 
- Platform Target Frameworks: 
  - iOS:  iPhone 11 iOS 13.3 
  - Android: Android 9 API 28  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Did not find a work around
[Xamarin_Forms___CollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/4202582/Xamarin_Forms___CollectionView.zip)

**Comment by samhouts** [comment] 2020-02-17 17:28
Duplicate of #8344

**Comment by samhouts** [comment] 2020-02-17 17:31
Actually, I'll reopen this. Might be different!

**Comment by samhouts** [comment] 2020-02-17 17:32
May also be related to #9058

**Comment by kostwald** [comment] 2020-02-18 02:22
I am seeing this issue also

**Comment by lee-m** [comment] 2020-03-09 15:48
I'm seeing the same error but with grouping disabled on version 4.5.0.356. Setting ItemSizingStrategy to MeasureFirstItem managed to workaround the crash for me at least.

**Comment by AdamDiament** [comment] 2020-03-23 09:12
> I also have the same issue on an ungrouped collection view. Changing the item sizing strategy did not change things for me I still get the same crash when adding an item.

**Closed** 2020-04-13 10:54 UTC
Labels: a/collectionview, e/3 :clock3:, i/high, in-progress, p/iOS 🍎, t/bug :bug:
