### ISSUE TITLE
Typing Korean does not work properly on iOS

### ISSUE THREAD

**Issue by AnandRaj32** [xamarin/Xamarin.Forms#10053] opened 2020-03-23 07:47 UTC
### Description

Unable to input the Korean words to the UITextField. When the user types  "ㅅ ㅓ ㄱ ㅇ ㅕ ㄹ", for example,  it should appear as "석열".

But when I try to type in, I unable to get a word in the suggestions in iOS.

In my scenario, I have handled the UITextField typed text on my side. So I have return false in ShouldCharactersChange event. If I have returned true in ShouldCharactersChange event, the keyboard suggested properly. 

### Steps to Reproduce

1. In iOS settings, go to "General -> Keyboards -> Add New Keyboard...". Select "Korean -> Standard".
2. Type ㅅ ㅓ ㄱ ㅇ ㅕ ㄹ  and no words will be suggested.

### Expected Behavior

The Korean words should be suggested based on the input.

### Actual Behavior

No words suggested.

### Basic Information

- Version with issue: 4.4.991640
- Platform Target Frameworks: Xamarin.Forms.iOS
  - iOS:  13.1
- Affected Devices: All devices

### Screenshots

<img width="207" alt="Korean" src="https://user-images.githubusercontent.com/56817178/77293577-9c706900-6d08-11ea-881e-3b5f895b6e34.png">

### Reproduction Link

[Custom_Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/TestSample462004485  
)

**Comment by jfversluis** [comment] 2020-03-24 09:43
Hey @AnandRaj32 I see you already opened a very similar bug but for Chinese. I would propose to stick to that one as it seems to be the exact same case and likely the solution will be the same.

**Comment by jfversluis** [comment] 2020-03-24 09:43
Duplicate of #9918

**Closed by jfversluis** 2020-03-24 09:43 UTC
Labels: s/unverified, t/bug :bug:
