### ISSUE TITLE
[Bug] CarouselView: Current item horizontal position out by 2 pixels

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#13682] opened 2021-02-06 07:41 UTC
### Description
As per title, the default position of the current item is off left centre by 2 pixels
### Steps to Reproduce

New XF project
Replace main page with the following:

```
    public class MainPage : ContentPage
    {
        public MainPage()
        {
            Content = new StackLayout()
            {
                Children =
                {
                    new Label() { Text = "dfgdfgdfg" },
                    new Label() { Text = "dfgdfgdfg" },
                    new Label() { Text = "dfgdfgdfg" },
                    new CarouselView()
                    {
                        ItemTemplate = new DataTemplate(()=> new ContentView() { Content = new BoxView() { BackgroundColor = Color.Red } } ),
                        ItemsSource = new [] { 1, 2, 3 }
                    }
                }
            };
        }
    }
```

Run the app, see that there is a white line on the left of the page.

### Expected Behavior
The current item to always be in the centre
Also expect better QA, how was this released?

### Actual Behavior
The current item is offset by 2 pixels

### Basic Information

- Version with issue: XF 5.0.0
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  14.4
- NuGet Packages:
- Affected Devices:
iPad touch (default simulator in VSforMac for some random reason only known to whomever thought that was a good idea)

### Workaround
Drop Xamarin and migrate to Flutter, we are looking into that

**Comment by jsuarezruiz** [comment] 2021-02-08 11:28
Attached a repro sample:
[Issue13682.zip](https://github.com/xamarin/Xamarin.Forms/files/5943332/Issue13682.zip)
Is the same (or related) as https://github.com/xamarin/Xamarin.Forms/issues/8961 and https://github.com/xamarin/Xamarin.Forms/issues/12287

**Comment by JohnHDev** [comment] 2021-02-08 12:12
Wait, this issue was first reporting December 2019 and it still isn't fixed??

**Comment by JohnHDev** [comment] 2021-02-13 10:13
@kapusch why the thumbs down?

**Comment by JohnHDev** [comment] 2021-04-25 06:58
@hartez feel free to ignore this, we are dropping Xamarin Forms and moving to better supported technologies.

**Comment by jfversluis** [comment] 2022-02-09 09:38
Duplicate of #8961

**Closed by jfversluis** 2022-02-09 09:38 UTC
Labels: t/bug :bug:, p/iOS 🍎, a/carouselview, duplicate
