### ISSUE TITLE
[Enhancement] Add TabbedView

### ISSUE THREAD

**Issue by SymxnCreator** [xamarin/Xamarin.Forms#9258] opened 2020-01-20 13:44 UTC
## Summary
Many people want a TabbedView control. This is like a TabbedPage, only that it can be added into a page.

## Intended Use Case
With the TabbedView controls can be added above and below the tabs. You are no longer so limited in design.

**Comment by samhouts** [comment] 2020-01-22 21:26
Duplicate of #6904

**Closed by samhouts** 2020-01-22 21:26 UTC
Labels: proposal-open, t/enhancement ➕
