### ISSUE TITLE
[Bug] Android Button Text Alignment jumps to left aligned.

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/Xamarin.Forms#6659] opened 2019-06-26 07:48 UTC
### Description
Latest Xamarin Form Button Text Alignment is jumping to be left-aligned.

### Steps to Reproduce
Clone repo https://github.com/InquisitorJax/Xamarin-Forms-Shell
1. Run Android App
2. Tap on Discover Tab, and then back to Home
3. The orange button text alignment jumps to left aligned

### Expected Behavior
The text alignment should remain centered

### Actual Behavior
Text alignment gets left-aligned

### Basic Information

- Version with issue: Latest Xamarin Forms & VS 2017 Xamarin tooling

### Screenshots
![image](https://user-images.githubusercontent.com/1822976/60161218-59c04580-97f7-11e9-831b-735cced21cb5.png)
![image](https://user-images.githubusercontent.com/1822976/60161236-66dd3480-97f7-11e9-84ba-1a945bf4c789.png)

### Reproduction Link
https://github.com/InquisitorJax/Xamarin-Forms-Shell
related?
https://kampeki-factory.blogspot.com/2015/06/xamarin-forms-button-text-alignment.html

**Comment by samhouts** [comment] 2019-06-26 23:09
Thanks! I've verified that this is fixed by #6329, which will be included in 4.0.0 SR4.

**Comment by samhouts** [comment] 2019-06-26 23:09
Duplicate of #6282

**Closed by samhouts** 2019-06-26 23:09 UTC
Labels: p/Android, s/unverified, t/bug :bug:

**Comment by bverp** [comment] 2019-09-05 06:19
Is this problem realy fixed? I have the same issue with the latest Xamarin Forms 4.2 release (709249).

**Comment by hudaIT** [comment] 2019-12-21 17:52
Issue still not fixed for me Version => 4.5.0.74-nightly

**Comment by LeoJHarris** [comment] 2022-11-08 20:21
Still having the same problem...
