### ISSUE TITLE
[Bug] UWP - views wont update correctly while hidden

### ISSUE THREAD

**Issue by Xyotic** [xamarin/Xamarin.Forms#8854] opened 2019-12-11 16:30 UTC
### Description
Some views won't update while hidden.
I have noticed this in particular with entries and switches.
I attached a small test project for you to reproduce the problem.
Might be a race condition?

### Steps to Reproduce

1. Create an entry and switch in xaml and set the IsVisible property to false.
2. Edit the Text property of the entry and the OnColor property of the switch.
3. Set their IsVisible property to true

### Expected Behavior
The view will be visible with the new text and color applied.

### Actual Behavior
Both views will become visible but the entry will be empty and the switches OnColor will eb the default blue one.
If clicked inside the Entry the missing Text will appear.

### Basic Information
- Version with issue: 4.3.0.99.1221
- IDE:  Visual Studio Professional 2019 v 16.4.0
- Platform Target Frameworks:
  - UWP:  < 1803
- Affected Devices: Desktop
[UwpBugReport.zip](https://github.com/xamarin/Xamarin.Forms/files/3951423/UwpBugReport.zip)

**Comment by kingces95** [comment] 2019-12-14 01:11
Reproduces as described.

**Comment by WayaFlyfeather** [comment] 2019-12-14 12:41
Probably same as #8503, and hopefully fixed in #8536.

**Comment by samhouts** [comment] 2020-01-03 00:10
Duplicate of #8503

**Closed by samhouts** 2020-01-03 00:10 UTC
Labels: p/UWP, t/bug :bug:
