### ISSUE TITLE
[Bug] Shell - OnAppearing on Back Navigation not executing in Android

### ISSUE THREAD

**Issue by aryobenholzner** [xamarin/Xamarin.Forms#6861] opened 2019-07-12 12:55 UTC
### Description

When navigating to another page in a ShellSection and then navigating back to the first page the OnAppearing Event is not called in Android.
In iOS it just works fine.
Also in Android it works when using a Tabbed Page.

### Steps to Reproduce

1.  In a ShellSection, e.g. in the Shell Example App navigate to another page via Navigation.PushAsync() or Navigation.PushModalAsync()
2. Navigate back to the previous page

### Expected Behavior

OnAppearing should be called

### Actual Behavior

OnAppearing is not called

### Basic Information

- Version with issue: 4.1
- Last known good version: ???
- Platform Target Frameworks: 
  - Android: 9
- Affected Devices: All Android Devices and Emulators

### Reproduction Link
[shelltest.zip](https://github.com/xamarin/Xamarin.Forms/files/3386469/shelltest.zip)

on first page alert will be displayed in OnAppearing. then navigate away via the add button and navigate back

**Comment by jsuarezruiz** [comment] 2019-07-17 09:20
Thanks for the repro sample!. Indeed, the behavior you describe happens.
However, it is the current expected behavior. If we review the documentation: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal

We can read:
"Popping Pages from the Modal Stack. The page being returned to has its OnAppearing override invoked, provided that the underlying platform isn't Android."

We can improve the life cycle of the pages. Take a look at this Spec https://github.com/xamarin/Xamarin.Forms/issues/2210 and give us your feedback!

**Comment by Robtom5** [comment] 2019-07-17 09:21
This looks like the same bug I've had

It looks like there is a fix in for 4.2.0
https://github.com/xamarin/Xamarin.Forms/pull/6527

**Comment by samhouts** [comment] 2019-07-18 03:08
closed by #6527

**Closed by samhouts** 2019-07-18 03:08 UTC
Labels: a/shell :shell:, p/Android, t/bug :bug:
