### ISSUE TITLE
Failed to execute 'which mono64': ExitStatus = 1

### ISSUE THREAD

**Issue by AceCoderLaura** [xamarin/Xamarin.Forms#5791] opened 2019-04-02 23:36 UTC
### Description
I can't run my Xamarin.iOS application.

### Steps to Reproduce
1. Run the application from the IDE.

### Expected Behavior
Application starts on the iPad Mini connected to the Mac Mini that I connected to.

### Actual Behavior
Build hangs for a bit and then nothing happens.
Works fine on the Mac Mini in Visual Studio for Mac.
Since this appears to be a communication problem I figure this warning is relevant:
```
Xamarin.Messaging.targets(41, 3): [null] C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.Messaging.targets(41,3): warning : Failed to execute 'which mono64': ExitStatus = 1
```

### Basic Information
- Version with issue: 3.4.0.1009999
- Last known good version: There's never been a good version
- IDE: Rider, Visual Studio 2017
- Platform Target Frameworks:
  - iOS: 8.0.30703
- Nuget Packages:
  - Esri.ArcGISRuntime.Xamarin.Forms/100.2.1
  - Esri.ArcGISRuntime.Xamarin.iOS/100.2.1
  - Xamarin.Forms/3.4.0.1009999
- Affected Devices:
  - iPad Mini

**Comment by AceCoderLaura** [comment] 2019-04-02 23:52
If I set ContinueOnDisconnected in my project file to false I get this error:
```
  Xamarin.Messaging.targets(41, 3): [null] No enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The build can't continue without a connection
```

**Comment by AceCoderLaura** [comment] 2019-04-03 03:59
Here's the device log for the Mac Mini for the duration of an attempted build: [device.log](https://github.com/xamarin/Xamarin.Forms/files/3036810/buildlog.log)

**Comment by AceCoderLaura** [comment] 2019-04-03 04:02
Here's the build log from the Windows machine: [BuildLog.zip](https://github.com/xamarin/Xamarin.Forms/files/3036825/BuildLog.zip)

**Comment by AceCoderLaura** [comment] 2019-04-03 05:40
%LOCALAPPDATA%\Xamarin\Logs\15.0\\[2019-04-03_16-23-35.22016.Ide.log](https://github.com/xamarin/Xamarin.Forms/files/3036993/2019-04-03_16-23-35.22016.Ide.log)

**Comment by AceCoderLaura** [comment] 2019-04-03 06:12
Okay I fixed it in Rider by recreating the run config .xml file. It seems that the `TargetiOSDevice` value wasn't being sent to the Mac as a result, although that's just speculation on my part. Visual Studio is still broken since it doesn't use the run config file that Rider does.

**Comment by emaf** [comment] 2019-04-03 15:05
Hi @AceCoderLaura,
It looks like your build is succeeding, but there's no information to identify why the app is failing to launch on attached logs.

Could you report this issue on Visual Studio*? That way we'll get more logs that can help us identify the problem you're facing. It'd be great if you can report it after reproducing it (in the same VS session) while you remain connected to your Mac, so we also get the Mac side logs with a full repro.

[*How to report a problem from Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

Thanks!

**Comment by samhouts** [comment] 2019-04-03 18:50
I'll go ahead and close this issue, since it seems to be outside the scope of Xamarin.Forms. Thanks!!

**Closed by samhouts** 2019-04-03 18:50 UTC
Labels: t/bug :bug:

**Comment by AceCoderLaura** [comment] 2019-04-03 22:56
Reported it to Visual Studio.

![VS Bugs](http://1.bp.blogspot.com/-Rf42FQsW_E8/VFCjoXECO_I/AAAAAAAAAD4/rsw2pFxXvBw/s1600/Futurama_Master_In_Pile.jpg)
