### ISSUE TITLE
[Bug] SwipeView sensitivity

### ISSUE THREAD

**Issue by woinarpepperbits** [xamarin/Xamarin.Forms#12796] opened 2020-11-10 14:11 UTC
### Description
SwipeView sensitivity

Hello,

the SwipeView is much too sensitive. The SelectionChange command is no longer executed. You have to press exactly straight without moving your finger to trigger a SelectionChange command. Otherwise the Swipe will always respond immediately. Unfortunately, the SwipeView is not usable in this way.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rachelkang** [comment] 2020-11-10 15:54
Hi, @woinarpepperbits - thanks for submitting this issue! I'm closing this now as it's a duplicate of #12518 and is being fixed in #12758. If you feel your issue is not represented there, please feel free to let us know and reopen this issue. Thanks again!

**Closed by rachelkang** 2020-11-10 15:54 UTC
Labels: s/unverified, t/bug :bug:

**Comment by Tommigun1980** [comment] 2020-11-19 23:57
Hi @rachelkang! The PR you linked to does not seem to contain a fix for the 'sensitivity' problem this report details (but rather to the UI getting stuck problem). This is still a duplicate of the report though.

**Comment by kaniosm** [comment] 2020-11-22 14:26
Hi @rachelkang! I can confirm the issue as well (both version 4.8.0.1687 - and 5.0.0.1709-pre4.
SwipeView is very sensitive. Many times even a single tab with trigger the swipe view, which leads to the tab being ignored.
When using an emulator the issue is not obvious. It is thought when using a device (tested with several Android devices).

**Comment by Tommigun1980** [comment] 2020-11-22 14:47
> Hi @rachelkang! I can confirm the issue as well (both version 4.8.0.1687 - and 5.0.0.1709-pre4.
> SwipeView is very sensitive. Many times even a single tab with trigger the swipe view, which leads to the tab being ignored.
> When using an emulator the issue is not obvious. It is thought when using a device (tested with several Android devices).

@rachelkang Exactly this. I want to make sure the sensitivity problem also gets addressed as the PR in question only solves the UI getting stuck problem, but not the sensitivity problem.

The sensitivity problem should be imho tackled in to parts:
1) This is most important - a threshold should be added before the 'swipe' invokes.
2) Vertical and horizontal scrolls should be locked - if a vertical pan is in action, a swipe should never invoke even if the threshold is exceeded.

Solving 1) will is most important and should imho be done ASAP to make the swipe view usable but 2) must also be done to make it polished and feel natural.

Thank you.
Ping @jsuarezruiz

**Comment by jsuarezruiz** [comment] 2020-11-23 17:02
@Tommigun1980 I reviewed in #12758 the problem with the scroll first of all, being the most critical one. However, we will not leave sensitivity problem behind. In the next few days there should be a PR (and a NuGet to test). I will notify you and @kaniosm  to receive feedback.

**Comment by Tommigun1980** [comment] 2020-11-23 21:37
> @Tommigun1980 I reviewed in #12758 the problem with the scroll first of all, being the most critical one. However, we will not leave sensitivity problem behind. In the next few days there should be a PR (and a NuGet to test). I will notify you and @kaniosm to receive feedback.

Thank you, I fully agree with your assessment and know that you are on top of things! I decided to chime in here for housekeeping only as this report was closed with the assumption that the referenced pull request also addressed the sensitivity. You are most helpful and I didn't try in any way to insinuate that the other things were not being worked on!

**Comment by kaniosm** [comment] 2020-11-24 06:34
Keep up the good work guys! Xamarin is nowhere close to what it used to be 2 years ago!

**Comment by kaniosm** [comment] 2021-01-03 15:04
Hi @rachelkang 
Do you have any update regarding the sensitivity issue?

**Comment by Tommigun1980** [comment] 2021-01-03 15:37
> Hi @rachelkang
> Do you have any update regarding the sensitivity issue?

Probably best to create a new ticket and refer to this one (which has been incorrectly closed)?

**Comment by kaniosm** [comment] 2021-01-03 16:59
Apparently there are several tickets referring to the same issue!
I found the following two:
[#12518 ](https://github.com/xamarin/Xamarin.Forms/issues/12518)
and 
[#12067](https://github.com/xamarin/Xamarin.Forms/issues/12067)

I'll follow those two instead.

**Comment by decv86** [comment] 2021-02-17 12:57
Is there any solution for ios? Please share
