### ISSUE TITLE
[Bug] RadioButton Doesn't Respect Right To Left FlowDirection

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/Xamarin.Forms#12440] opened 2020-10-10 17:16 UTC
### Description
When the **FlowDirection** property in parent view which contains some **RadioButtons** is set to **RightToLeft** , the RadioButton views aren't laid out correctly:
1-Android: Texts of RadioButton appear before Circle (RadioButton ).(the RadioButton and it's content are laid out from left to right)
2-iOS: the Texts and RadionButton Circles overlaps.
### Steps to Reproduce

1. ِDefine some RadioButtons inside PageContent
2. set PageContent FlowDirection to RightToLeft.

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="xam5_2.Page2" FlowDirection="RightToLeft">
  <ContentPage.Content>
      <StackLayout Orientation="Horizontal">
            <RadioButton Content="111"/>
            <RadioButton Content="222"/>
            <RadioButton Content="333"/>
        </StackLayout>
  </ContentPage.Content>
</ContentPage>
```

### Expected Behavior
When **FlowDirection** Is **RightToLeft** , the **RadioButton** Views must laid out from Right To Left and their Text(or Content) must appear **afte** RadioButton Circle(from Right To Left)
![RadioButtonLTR_RTL_GoodA](https://user-images.githubusercontent.com/57061231/95660985-683f8700-0b38-11eb-8ccf-96deb4572dc3.png)

### Actual Behavior
When **FlowDirection** Is **RightToLeft** :
1-**in Android**:  Texts of RadioButton appear before Circle (RadioButton ).
![RadioButtonLTR_RTL_BadA](https://user-images.githubusercontent.com/57061231/95661068-2d8a1e80-0b39-11eb-8896-720313a2b85d.png)

2-**in iOS**: the Texts and RadionButton Circles overlaps.
![RadioButton_Bad2](https://user-images.githubusercontent.com/57061231/95661096-6aeeac00-0b39-11eb-964e-239c55656e59.png)
### Basic Information

- Version with issue: Xamrin 5.0
- Last known good version:
- IDE:Visual Studio 2019 Version 16.8.0 Preview 3.2
- Platform Target Frameworks: 
  - iOS:  13.5
  - Android: 10
 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android , iOS

### Screenshots

Comparing Flow Direction behavior in Android and iOS in 2 modes:
Android:
![RadioButtonLTR_RTL_BadA](https://user-images.githubusercontent.com/57061231/95661066-2531e380-0b39-11eb-9fea-e2e0b40689c6.png)

iOS: 
![RadioButton_Bad2](https://user-images.githubusercontent.com/57061231/95661088-56aaaf00-0b39-11eb-8923-2088bf35ddee.png)

**Comment by rachelkang** [comment] 2020-10-12 16:40
@hamiddd1980 Thanks for submitting such a detailed issue! Would you also attach a small sample project that reproduces this bug? Thanks :)

**Comment by hamiddd1980** [comment] 2020-10-12 19:59
Hi. Thank you for considering this problem .the following code can describe the problem in **RightToLeft** **FlowDirection**:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="xam5_2.Page2" FlowDirection="RightToLeft">
      <StackLayout Orientation="Horizontal">
            <RadioButton Content="111"/>
            <RadioButton Content="222"/>
            <RadioButton Content="333"/>
        </StackLayout>
</ContentPage.Content>
```
it is also noticeable that **applying a ControlTemplate to RadioButton**  in **RightToLeft** **FlowDirection**,causes the RadioButton not to show(display) its Content correctly(like attached code and picture):
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="xam5_2.Page2" FlowDirection="RightToLeft">
    <ContentPage.Resources>
        <ControlTemplate x:Key="rb">
            <Frame CornerRadius="4" BorderColor="OrangeRed" WidthRequest="60" HeightRequest="60">
                <StackLayout Orientation="Horizontal">
                    <Ellipse WidthRequest="15" HeightRequest="15" Stroke="Blue" StrokeThickness="2" VerticalOptions="Center">            </Ellipse>
                    <ContentPresenter VerticalOptions="Center"/>
                </StackLayout>
            </Frame>
        </ControlTemplate>
    </ContentPage.Resources>
    <ContentPage.Content>
        <StackLayout Orientation="Horizontal">
            <RadioButton Content="111" ControlTemplate="{StaticResource Key=rb}" VerticalOptions="Start"/>
            <RadioButton Content="222" ControlTemplate="{StaticResource Key=rb}" VerticalOptions="Start"/>
            <RadioButton Content="333" ControlTemplate="{StaticResource Key=rb}" VerticalOptions="Start"/>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

```
Thank you once again for your consideration.

![CompareLRwithTemplate](https://user-images.githubusercontent.com/57061231/95785108-028efe80-0ce2-11eb-894c-7ba8c3a1b7dc.png)

**Comment by PureWeen** [comment] 2020-10-31 16:56
Closing for now as a duplicate of 

https://github.com/xamarin/Xamarin.Forms/issues/11324

So we can track this under that issue

**Closed by PureWeen** 2020-10-31 16:56 UTC
Labels: a/radiobutton :radio_button:, s/unverified, t/bug :bug:

**Comment by hamiddd1980** [comment] 2020-11-05 18:15
Hi. I want to get your attention to the fact that these 2 issues are somewhat different . as I mentioned in my issue ,the **Radiobutton** doesn't work at all when a **ControlTemplate** is applied to it in Right to Left mode(iOS and Android). so , should I open a new issue to report this bug?
Thanks.
![RadiobuttonTemplate](https://user-images.githubusercontent.com/57061231/98280089-1875a380-1fb0-11eb-8d76-04173c226661.png)


![CompareLRwithTemplate](https://user-images.githubusercontent.com/57061231/98280130-2aefdd00-1fb0-11eb-8b3f-bddb4293790e.png)

**Comment by mina5500** [comment] 2021-08-03 08:53
same issue till now
