### ISSUE TITLE
[Core] Slider unable to update Maximum , Minimum by binding

### ISSUE THREAD

**Issue by myroot** [xamarin/Xamarin.Forms#2761] opened 2018-05-18 00:15 UTC
### Description
 Can't update the Maximum/Mnimum using binding
 Becuase validateValue
https://github.com/xamarin/Xamarin.Forms/blob/882bf07917bea57b93d0d9becd768dcab739c26f/Xamarin.Forms.Core/Slider.cs#L10-L14

https://github.com/xamarin/Xamarin.Forms/blob/882bf07917bea57b93d0d9becd768dcab739c26f/Xamarin.Forms.Core/Slider.cs#L21-L24

`validateValue` make hard to update value, according to value, Value update order should be changed. like below
```C#
   if (max > Minimum)
   {
        Maximum = max;
        Minimum = min;
   }
   else
   {
        Minimum = min;
        Maximum = max;
   }
```
But it is impossible in binding

So, I propose remove validateValue handler and update coerceValue like below
``` c#
		public static readonly BindableProperty MinimumProperty = BindableProperty.Create("Minimum", typeof(double), typeof(Slider), 0d, BindingMode.OneWay, coerceValue: (bindable, value) =>
		{
			var slider = (Slider)bindable;
			slider.Value = Math.Max((double)value, slider.Value);
			return value;
		}, propertyChanged:(bindable, oldValue, newValue) =>
		{
			var slider = (Slider)bindable;
			slider.SetValueCore(MaximumProperty, Math.Max(slider.Maximum, (double)newValue));
		});

		public static readonly BindableProperty MaximumProperty = BindableProperty.Create("Maximum", typeof(double), typeof(Slider), 1d, BindingMode.OneWay, coerceValue: (bindable, value) =>
		{
			var slider = (Slider)bindable;
			slider.Value = Math.Min((double)value, slider.Value);
			return value;
		}, propertyChanged:(bindable, oldvalue, newValue) =>
		{
			var slider = (Slider)bindable;
			slider.SetValueCore(MinimumProperty, Math.Min(slider.Minimum, (double)newValue));
		});
```

### Steps to Reproduce

``` c#
    class RangeModel
    {
        public double Max { get; set; }
        public double Min { get; set; }
    }

    Slider slider = new Slider();
    slider.SetBinding(Slider.MaximumProperty, new Binding("Max"));
    slider.SetBinding(Slider.MinimumProperty, new Binding("Min"));
    slider.BindingContext = new RangeModel { Min = -100, Max = -1 }; // ArgumentException was thrown
```

### Expected Behavior
 Update Minimum and Maximum
### Actual Behavior
 ArgumentException was thrown (Value was an invalid value for Maximum)

**Comment by pauldipietro** [comment] 2018-05-18 03:50
Behavior is this way as of 3.1-pre

**Comment by StephaneDelcroix** [comment] 2018-05-18 08:00
This has always been the case. we can't really remove the validation. nor can we defer them, in this case, with binding in play...

**Comment by StephaneDelcroix** [comment] 2018-05-18 08:07
dupe of #1943

**Closed** 2018-05-18 08:07 UTC
Labels: s/duplicate, t/bug :bug:
