### ISSUE TITLE
[Bug] iOS FontSize is calculated incorrectly

### ISSUE THREAD

**Issue by RobWos** [xamarin/Xamarin.Forms#7242] opened 2019-08-22 10:33 UTC
### Description
On iOS named fontsizes are calculated incorrectly usually resulting in 1 point less than expected.
### Steps to Reproduce
1.  Executing 
` var result = new FontSizeConverter().ConvertFromInvariantString(nameof(NamedSize.Micro));`
or add a label with fontsize micro

### Expected Behavior
NamedSize.Micro should return 12 with default settings
### Actual Behavior
Returns 11
### Basic Information
I think the issue lies in [https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Forms.cs](url)

The font scaling factor is calculated on line 188 like this.
`_fontScalingFactor = (double)UIFont.PreferredBody.PointSize / 18f;`
I think it should be :
`_fontScalingFactor = (double)UIFont.PreferredBody.PointSize / 17f;`

Why?
The default UIFont.PreferredBody.PointSize is 17 on my emulator iPhone 7 iOS 12.2.
Also on the Apple guidelines [https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/](url)
It states that the default body Size in points is 17.

And on line 224 in the source it is also stated that
`// iOS docs say default button font size is 15, default label font size is 17 so we use those as the defaults.`

- Version with issue: Xamarin.Forms 4.1.0.618606
- Last known good version: Xamarin.Forms 4.0.0.425677
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  8.0
- Nuget Packages: Xamarin.Forms
- Affected Devices: only tested on iPhone 7 iOS 12.2

**Comment by samhouts** [comment] 2019-08-23 18:52
@RobWos  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by RobWos** [comment] 2019-08-26 09:52
[IncorrectFontSize.zip](https://github.com/xamarin/Xamarin.Forms/files/3540581/IncorrectFontSize.zip)
Just checked the last known good Xamarin.Forms version is 4.0.0.709238, the first version with the bug is 4.1.0.555618.

Instructions : 
Run the app on iOS note down the font sizes.
Update Xamarin.Forms to version 4.1.0.555618.
Run the app on iOS note down the font sizes.
Compare the results

**Comment by rmarinho** [comment] 2019-08-28 23:48
This  regression was introduced when we added the scaling  #5985
@Clancey opinions ? 
https://github.com/xamarin/Xamarin.Forms/blame/master/Xamarin.Forms.Platform.iOS/Forms.cs#L188

**Comment by blomman1** [comment] 2020-01-14 08:45
Any news on this?

We need to upgrade Xamarin.Forms to version 4.3 (from 3.6) in our product
because of the relative source binding in 4.3. However, we use named fonts a lot
and are not happy with the smaller fonts on iOS. We need to solve this somehow
but the best thing would be if it was solved in Xamarin.Forms.

**Comment by ekjellberg** [comment] 2020-02-14 09:32
I Agree with Blomman1. We have the same problem.

**Comment by coolfuzz** [comment] 2020-02-14 09:55
We have the same problem as Blomman1. This might delay our next release!

**Comment by zeniya-takeshi** [comment] 2020-02-17 01:29
We are also troubled by this. We can't upgrade Xamarin Forms version.

**Comment by blomman1** [comment] 2020-03-09 13:19
We solved this by disabling the font scaling feature for now.

`Xamarin.Forms.Application.Current.On<iOS>().SetEnableAccessibilityScalingForNamedFontSizes(false);`

**Comment by samhouts** [comment] 2020-03-31 21:15
closed by #9821

**Closed by samhouts** 2020-03-31 21:15 UTC
Labels: 4.1.0, e/4 :clock4:, i/regression, in-progress, p/iOS 🍎, t/bug :bug:
