### ISSUE TITLE
[Bug] When language is set to French, decimal separator is ignored when typing

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#13763] opened 2021-02-15 13:21 UTC
### Description
When launching the app while language is English it fine, but when launching the app while the real device or emulator language is French  the issue occurred.

So I have an Entry bound to a double property with `Keyboard="Numeric"`.

- NO `StringFormat` is used, and not modifying/forcing culture at app level.
- Confirmed that in French `CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator = ","` and in this case "." won't be an allowed character.

The issue is when I type "12,3"  in the property setter the value is equal to 123. And of course at the end displays 123 in the Entry field.

### Steps to Reproduce

1. Change Android device or emulator language to French
2. Launch the repo
3. In the Entry type 12.3 or 12,3
4. Close the app, change back to English and relaunch, redo 1-3, works fine as expected.

### Expected Behavior
Should display and set property to 12,3 as it is the case in English.
### Actual Behavior
Displays and set property to 123
### Basic Information

Tried forcing but didn't work
```
var ci = CultureInfo.InvariantCulture;
Thread.CurrentThread.CurrentCulture = ci;
Thread.CurrentThread.CurrentUICulture = ci;
```

- Version with issue:
- Last known good version: -
- Platform Target Frameworks: Tested on Android only
  - iOS:  -
  - Android: API 29
  - UWP:  - 
- Android Support Library / AndroidX Version: 
- NuGet Packages: -
- Affected Devices: -
### Workaround
Use a value converter 
```
		public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
		        => return value;

		public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
		        => return (value as string)?.Replace(',', '.') ?? value;
```
### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/5981722/App1.zip)

**Comment by hartez** [comment] 2021-02-18 18:35
This is happening because the conversion method in BindingExpression explicitly ignores trailing "." during conversion and then does the final conversion using CultureInfo.InvariantCulture. It should probably be ignoring the decimal separator for the current culture's number format instead, and using the current culture when converting.

**Comment by hartez** [comment] 2021-02-18 18:38
@Cfun1 As a workaround, you can create a proxy string property to bind to the entry; something like this:

```
public class ViewModel : BaseViewModel
{
	private double _MyProp;
	private string _MyProp2;

	public double MyProperty
	{
		get { return _MyProp; }
		set { SetProperty(ref _MyProp, value); }
	}

	public string MyProperty2
	{
		get { return _MyProp2; }
		set 
		{ 
			SetProperty(ref _MyProp2, value);
			if (double.TryParse(value, out double result)) 
			{
				MyProperty = result;
			}
		}
	}

	public ViewModel(){}
}
```

And then bind the Entry to MyProperty2.

**Comment by Cfun1** [comment] 2021-02-18 21:35
@hartez I appreciate the quick reply, thanks for the workaround will stick it with it for now (even that when you have a lot of Entries the code may become a mess). hope a fix will be possible before MAUI.

**Comment by Cfun1** [comment] 2021-02-27 16:12
@hartez in that way the `StringFormat` won't work with this workaround, in my issue I mentioned that I don't use it, in fact I meant to say omitted it for debugging purposes only.

**Comment by emilsteen** [comment] 2021-04-22 16:07
This is a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/7996, which should have been fixed years ago.

**Comment by jfversluis** [comment] 2022-01-03 19:23
Duplicate of #7669

**Closed** 2022-01-03 19:23 UTC
Labels: t/bug :bug:, a/binding ⛓, a/l10n, e/5 :clock5:
