### ISSUE TITLE
[Bug][iOS] MediaElement SIGSEGV

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#9569] opened 2020-02-13 16:01 UTC
### Description

I've got `MediaElement` to result in a SIGSEGV a few times, through different conditions. I finally found a way of reproing it.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the Change Aspect Ratio page and wait for the video frame to appear.
3. Change the Picker to AspectFill then Fill (without hitting the done button).
4. Browse back a page.

### Expected Behavior

Page navigation occurs and the app continues to work.

### Actual Behavior

Page navigation occurs and a SIGSEGV occurs:

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10ba9c8f5 - /Users/davidbritch/Library/Developer/CoreSimulator/Devices/3F0EB30E-6508-42B6-9CE5-FC4156DFAD00/data/Containers/Bundle/Application/FF0212C6-9CBE-4312-8843-E7A2424B25A6/MediaElementDemos.iOS.app/MediaElementDemos.iOS : mono_dump_native_crash_info
	0x10ba910c5 - /Users/davidbritch/Library/Developer/CoreSimulator/Devices/3F0EB30E-6508-42B6-9CE5-FC4156DFAD00/data/Containers/Bundle/Application/FF0212C6-9CBE-4312-8843-E7A2424B25A6/MediaElementDemos.iOS.app/MediaElementDemos.iOS : mono_handle_native_crash
	0x10baa3138 - /Users/davidbritch/Library/Developer/CoreSimulator/Devices/3F0EB30E-6508-42B6-9CE5-FC4156DFAD00/data/Containers/Bundle/Application/FF0212C6-9CBE-4312-8843-E7A2424B25A6/MediaElementDemos.iOS.app/MediaElementDemos.iOS : mono_sigsegv_signal_handler_debug
	0x7fff52457b5d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x10bf45668 - /Users/davidbritch/Library/Developer/CoreSimulator/Devices/3F0EB30E-6508-42B6-9CE5-FC4156DFAD00/data/Containers/Bundle/Application/FF0212C6-9CBE-4312-8843-E7A2424B25A6/MediaElementDemos.iOS.app/MediaElementDemos.iOS : mono_icall_signatures
	0x7fff25723833 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : NSKeyValueWillChangeWithPerThreadPendingNotifications
	0x7fff2093846d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AVFoundation.framework/AVFoundation : -[AVPlayer setRate:withVolumeRampDuration:playImmediately:rateChangeReason:]
	0x7fff20938834 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AVFoundation.framework/AVFoundation : -[AVPlayer setRate:]
	0x10bcd8459 - /Users/davidbritch/Library/Developer/CoreSimulator/Devices/3F0EB30E-6508-42B6-9CE5-FC4156DFAD00/data/Containers/Bundle/Application/FF0212C6-9CBE-4312-8843-E7A2424B25A6/MediaElementDemos.iOS.app/MediaElementDemos.iOS : xamarin_dyn_objc_msgSend
	0x1125d9d0a - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff513fa890):0x7fff513fa880  08 5b 41 5e 41 5f 5d c3 48 85 ff 7e 09 48 8b 07  .[A^A_].H..~.H..
0x7fff513fa890  8a 40 1c 24 01 c3 31 c0 c3 48 85 ff 74 12 78 18  .@.$..1..H..t.x.
0x7fff513fa8a0  48 8b 07 48 85 c0 74 08 48 89 c7 e9 dc c7 00 00  H..H..t.H.......
0x7fff513fa8b0  48 8d 05 6c 09 02 00 c3 48 89 f8 48 c1 e8 3c 48  H..l....H..H..<H

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend <0x000e9>
	  at AVFoundation.AVPlayer:Pause <0x00122>
	  at Xamarin.Forms.Platform.iOS.MediaElementRenderer:Dispose <0x00253>
	  at Foundation.NSObject:Dispose <0x00074>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Dispose <0x002c5>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Dispose <0x00071>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Dispose <0x0024a>
	  at Foundation.NSObject:Dispose <0x00074>
	  at Xamarin.Forms.Platform.iOS.DisposeHelpers:DisposeModalAndChildRenderers <0x0030f>
	  at Xamarin.Forms.Platform.iOS.Platform:HandleChildRemoved <0x000d2>
	  at Xamarin.Forms.Element:OnDescendantRemoved <0x00120>
	  at Xamarin.Forms.Element:OnChildRemoved <0x00182>
	  at Xamarin.Forms.VisualElement:OnChildRemoved <0x00092>
	  at Xamarin.Forms.Page:OnInternalRemoved <0x00140>
	  at Xamarin.Forms.Page:InternalChildrenOnCollectionChanged <0x002c2>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x000fa>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x00103>
	  at System.Collections.ObjectModel.ObservableCollection`1:RemoveItem <0x0018a>
	  at System.Collections.ObjectModel.Collection`1:Remove <0x001e5>
	  at <Xamarin-Forms-INavigationPageController-RemoveAsyncInner>d__72:MoveNext <0x006d2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00222>
	  at Xamarin.Forms.NavigationPage:Xamarin.Forms.INavigationPageController.RemoveAsyncInner <0x0028a>
	  at <UpdateFormsInnerNavigation>d__75:MoveNext <0x0035f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x001fa>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:UpdateFormsInnerNavigation <0x0024a>
	  at <DidMoveToParentViewController>d__41:MoveNext <0x001c2>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x0020a>
	  at ParentingViewController:DidMoveToParentViewController <0x00292>
	  at <Module>:runtime_invoke_void__this___object <0x001ab>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00259>
	  at UIKit.UIApplication:Main <0x000b2>
	  at UIKit.UIApplication:Main <0x00132>
	  at MediaElementDemos.iOS.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00198>
=================================================================

### Basic Information

- Version with issue: 4.5-pre4
- IDE: VS Mac 8.4.5
- Platform Target Frameworks: 
  - iOS:  13.3

### Reproduction Link

[WorkingWithMediaElement.zip](https://github.com/xamarin/Xamarin.Forms/files/4198446/WorkingWithMediaElement.zip)

**Comment by samhouts** [comment] 2020-02-13 18:09
Duplicate of #9525

**Closed by samhouts** 2020-02-13 18:09 UTC
Labels: a/mediaelement, e/2 :clock2:, i/high, p/iOS 🍎, t/bug :bug:
