### ISSUE TITLE
[Bug] UWP DisplayAlert doesn't display dialog using Xamarin.Forms 4.5.0.617

### ISSUE THREAD

**Issue by MattRames** [xamarin/Xamarin.Forms#10332] opened 2020-04-14 19:40 UTC
### Description
Calling DisplayAlert on UWP doesn't display a dialog.

### Steps to Reproduce

1. Create fresh Xamarin.Forms application.
2. Update to latest Xamarin.Forms package version (4.5.0.617)
3. Call DisplayAlert

### Expected Behavior
I expect a dialog to appear.

### Actual Behavior
Dialog is not shown and the page can no longer be interacted with.

### Basic Information

- Version with issue: Xamarin Forms 4.5.0.617
- Last known good version: 4.4.0.991864
- IDE: Visual Studio 16.5.4
- Platform Target Frameworks: 
  - UWP:  Target - 16299 ; Min - 16299
- Nuget Packages: Xamarin.Forms 4.5.0.617

### Screenshots

![AD8D0F92-45C0-495E-A707-E28C66A58C06](https://user-images.githubusercontent.com/9450530/79266361-0fc74f80-7e5d-11ea-9036-b89437900b48.GIF)

### Reproduction Link

[UWPDisplayAlertBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4477351/UWPDisplayAlertBug.zip)

### Workaround

Use https://github.com/rotorgames/Rg.Plugins.Popup to display dialogs.
or
Update the UWP target to build 17763

**Comment by jfversluis** [comment] 2020-04-14 19:49
Hey @MattRames thanks for reporting this! It has been reported already :)

I will close this one as a duplicate. Please track the progress in the linked issue.

Thanks!

**Comment by jfversluis** [comment] 2020-04-14 19:49
Duplicate of #9606

**Closed by jfversluis** 2020-04-14 19:49 UTC
Labels: s/unverified, t/bug :bug:
