### ISSUE TITLE
Bindings ignore the current culture when converting between types

### ISSUE THREAD

**Issue by SamuelDebruyn** [xamarin/Xamarin.Forms#1919] opened 2018-02-19 15:02 UTC
### Description

Bindings ignore the culture set in the current thread when converting a variable to another type if needed. As a result, users with a culture with a decimal separator other than a dot (e.g. a comma) cannot type the decimal separator in an entry bound to a single or a double.

The bug is at [this line](https://github.com/xamarin/Xamarin.Forms/blob/0b2bbb03d497e77b73d4b669ee916e148e3ac8ff/Xamarin.Forms.Core/BindingExpression.cs#L422). The conversion use `CultureInfo.InvariantCulture` instead of the culture of the current thread.

### Steps to Reproduce

Use the repro link below or...

1. Create a new Xamarin.Forms project
1. Create a page (or use the one that was created) with a float property called `Example` with a backing field and implementation of INPC
1. Set the BindingContext of the page to itself
1. Add an entry to the page and set the text property to `{Binding Example} `
1. Set the locales of your iOS app in your Info.plist to `nl_BE`

```
<key>CFBundleLocalizations</key>
<array>
<string>nl_BE</string>
</array>
```

1. Set all the thread cultures to `nl-BE`

```
var culture = new CultureInfo("nl-BE");
CultureInfo.CurrentCulture = culture;
CultureInfo.CurrentUICulture = culture;
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;
```

### Expected Behavior

The user can type a number with a comma, e.g. `1,2`.
Both Android and iOS.

### Actual Behavior

The comma gets removed as soon as the user types the `2`.
Both Android and iOS.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: ???
- IDE: Visual Studio for Mac 7.3.3 (build 17)
- Platform Target Frameworks:
  - iOS:  11.6.1.4
  - Android: 8.1.5.0
- Nuget Packages:
- Affected Devices: all devices

### Reproduction Link

https://github.com/3factr/XamarinForms-ConversionIssue

### Workaround

Use a custom converter to convert the string to a single/double.

### IDE debug info

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.3 (build 17)
Installation UUID: 75a3e4df-6d6e-4364-9dac-61e6293ef1f9
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.1.1
	1.1.0
	1.0.5
	1.0.4
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
	1.0.3
	1.0.0-preview2-1-003177
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.4 (Visual Studio Enterprise)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Enterprise)
Android SDK: /Users/sam/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.3 (API level 18)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.216 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030017
Git revision: 88d62dcf15156ff583f785fa668dbf2a254db12e
Build date: 2018-02-09 08:36:16-05
Xamarin addins: 7c8f967d67207118dd99a1d0cc9c228045b30c5f
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Android Signature Tool 2.1.2
Gist Ide Information 1.1.0
MSBuild Editor 2.0.1
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.6
Redth's Addins 1.0.9
Show in Github 1.0.4
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by samhouts** [comment] 2018-02-22 19:59
Possibly related to #1595

**Comment by SamuelDebruyn** [comment] 2018-02-22 20:03
As far as I understand it's not the same issue. This issue occurs regardless of the bundle assemblies option. In the XF source code, InvariantCulture is used instead of the current thread culture so I guess the bundle assemblies option doesn't affect this?

**Comment by MelbourneDeveloper** [comment] 2018-03-09 00:23
This is probably related to this bug https://github.com/xamarin/Xamarin.Forms/issues/2049

**Comment by jassmith** [comment] 2018-03-09 03:20
Dupe of 2049 (which I know is newer but its the one I am tracking)

**Closed by jassmith** 2018-03-09 03:20 UTC
Labels: a/binding, t/bug
