### ISSUE TITLE
Button raised to top of visual stack on tap

### ISSUE THREAD

**Issue by nwilliams** [xamarin/Xamarin.Forms#8869] opened 2019-12-12 19:58 UTC
### Description
I'm currently simulating a card view using a Grid nested inside a Frame element. At the bottom of the visual stack is a Button to provide simple commanding and tap effects, with everything on top of the Button allowing taps to pass through via the InputTransparent property. This all works as expected in v3.6 of Xamarin.Forms, but after upgrading to v4.3 the Button has started bringing itself above all the other elements in the Grid when tapped. The workaround for the time being is to use a tap gesture recognizer on the Grid, but I then lose the tap effects, which provide important visual feedback to the user. I haven't had a chance to test this on iOS yet, but I suspect it will be a problem there as well.
### Steps to Reproduce

1. Download the [ClickableCardSample_v3.6.zip](https://github.com/xamarin/Xamarin.Forms/files/3957579/ClickableCardSample_v3.6.zip) file
2. Extract, build, and run the sample
3. Observe the desired behavior when clicking on the card sample
4. Upgrade the Xamarin.Forms NuGet package to the latest stable release
5. Build, run, and observe the bugged behavior

### Expected Behavior
When tapped, Button remains below other elements inside the Grid.
### Actual Behavior
When tapped, Button is raised above other elements inside the Grid.
### Basic Information

- Version with issue: 4.4

- Last known good version: 3.6
- IDE: Visual Studio 2019 v16.4.1
- Platform Target Frameworks: 
  - Android: 10.1.1.0
- Affected Devices: Pixel 3 XL Emulator

### Screenshots

Before Tap:
![Screenshot_1576180504](https://user-images.githubusercontent.com/204802/70744467-c076e400-1cef-11ea-8ff7-82020c75c5b8.png)
After Tap:
![Screenshot_1576180507](https://user-images.githubusercontent.com/204802/70744472-c371d480-1cef-11ea-91e7-56dd976f369e.png)

**Comment by MitchBomcanhao** [comment] 2019-12-13 15:24
duplicate of #7300 ?

**Comment by nwilliams** [comment] 2019-12-13 18:56
> 
> 
> duplicate of #7300 ?

It's very likely related to #7300, but the behavior I described is while using the default visual.

If this issue is just going to produce noise for the Xamarin team I'm fine with closing it and monitoring progress in #7300.

**Comment by kingces95** [comment] 2019-12-13 22:56
Hm, master as of this comment exhibits expected behavior for me.

**Comment by rmarinho** [comment] 2019-12-16 13:39
Tried even with nightly and saw the issue.  with the sample code

**Comment by samhouts** [comment] 2020-01-07 22:05
closed by #8917

**Closed by samhouts** 2020-01-07 22:05 UTC
Labels: blocker, i/regression, in-progress, p/Android, t/bug :bug:

**Comment by nwilliams** [comment] 2020-01-12 01:34
I noticed this issue listed under **Issues Fixed** for the 4.4.0-sr1 release notes, but after updating to the latest release (4.4.0-sr2), the bug still seems to be present in the sample application.

**Comment by PureWeen** [comment] 2020-01-12 01:46
@nwilliams We haven't really devised a perfect fix for this issue. The problem is that when you click the button it causes the Androiod.TranslationZ to get set (which is what causes the pressing effect) but then it raises the element above anything that's on top of it. To fix this we'd have to modify the elevation of any elements overlapping the button or just set the elevation on everything that's at the same level in the visual tree. None of this is really that efficient. 

Right now the recommend way to work around this is to set the Elevation on the content you want to stay on top of the button

```
<Image android:VisualElement.Elevation="6" Source="coffee.png" VerticalOptions="Center" HorizontalOptions="Center"></Image>
```

That's what https://github.com/xamarin/Xamarin.Forms/pull/8917 is fixing. Before https://github.com/xamarin/Xamarin.Forms/pull/8917 it was kind of impossible to set an elevation that worked. 

The other fix is to wrap the Button with a StackLayout

Not ideal but so far we haven't been able to devise an efficient plan to make it just work. The best plan would be to just provide you with a Button where you could define the content.

What's your use case? Why doesn't Button work? Can you use  a Grid or SL and add a TapGestureRecognizer?

**Comment by nwilliams** [comment] 2020-01-12 02:07
@PureWeen Thank you for the quick reply. My use case is a more complex version of what is shown in the sample application. Using the BindableLayout attached properties with a FlexLayout I create a series of clickable cards. To work around the issue, I was previously using a TapGestureRecognizer, but the problem with that is you lose the tap effect provided by a Button. Your suggestion to wrap the Button in a StackLayout appears to be working so I may just go that route until something better comes along.
