### ISSUE TITLE
[Bug] White Screen in Android when using NavigationPage 

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/Xamarin.Forms#11993] opened 2020-09-02 08:25 UTC
### Steps to Reproduce

1. Create Xamarin Forms project
2. Add splash screen to Android
3. in App.cs replace MainPage = new MainPage(); 
with 
MainPage = new NavigationPage(new MainPage());

### Expected Behavior
smooth moving from android splash to MainPage

### Actual Behavior
White screen between android splash and MainPage
Note1, if you remove the NavigationPage the white screen will disappear
Note2, the emulator works fine, I found this on physical devices (tested Samsung A7 2018 and OnePlus 6)

### Basic Information
- Version with issue: I tested XF v4.6 and 4.8
- didnt check the ios

### Repo Lnk
> https://github.com/moustafashaban/Test1

**Comment by rmarinho** [comment] 2020-09-22 16:25
I jsut tested on 2 devices, Pixel 2 and Samsung S8 and i can't reproduce the issue. No white screen.

**Comment by ScottishRoss** [comment] 2020-10-03 15:01
I have this issue on the emulator as well as my OnePlus 7 Pro. The white screen be attenuated with setting the Main Theme to have this parameter: 

`<item name="android:windowBackground">@color/window_background</item>`

It is still a blank screen and it is frustrating.

**Comment by jsuarezruiz** [comment] 2020-10-06 11:01
Tested with emulators and Pocophone F2 Pro. Cannot reproduce the issue. 
@ScottishRoss Do you have a different example where reproduce the issue? (you also mention emulator)

**Comment by ScottishRoss** [comment] 2020-10-06 12:36
![SplashScreenTransition gif](https://user-images.githubusercontent.com/25175556/95202173-db639900-07d8-11eb-903b-ddb6bf9e6b67.gif)

As you can see there's a blank screen in between the SplashScreen and the HomePage. It's not white (as I mentioned in my comment I've been able to change the colour) but my logo disappears.

**Comment by dipenbh** [comment] 2020-10-06 17:08
I have Samsung S8 and i am facing this issue. And also their is no error coming, just white screen. Not only for splash screen to main screen. But it randomly happen on any page navigation.  If i rotate my phone, white screen gone and it display original view.

I think other users are experiencing same issue.
https://forums.xamarin.com/discussion/120435/getting-white-screen-while-navigate-to-another-page

**Comment by kerbooo** [comment] 2020-10-23 13:23
Please solve this problem. Same issue is here for me.

**Comment by themronion** [comment] 2020-11-13 12:52
@jsuarezruiz @rmarinho 
This can be observed especially if the root page is a page with a complex ui
```csharp
MainPage = new NavigationPage(new ComplexUIPage()); // here if ComplexUIPage has a lot of views to draw the blank screen will appear firstly and only then the page
```

**Comment by themronion** [comment] 2020-11-13 14:26
@rmarinho , @jsuarezruiz @PureWeen this happens especially when the root page of the navigation page has complex ui.

```csharp 
MainPage = new NavigationPage(new ComplexUIPage()); // here most probably you will observe a white (or whatever color is set in styles and themes) page after splashscreen
```

Can u check if this behaviour will happen when u target android 10 and running on android 10? Because on android 9 i haven't experienced this issue. Maybe it has something to do with the android verision?

**Comment by themronion** [comment] 2020-11-30 20:55
@Redth tagging u here to move from my closed issue to this one

**Comment by brzezinol** [comment] 2021-01-12 11:47
The same behavior on Samsung S20+.
On emulator works fine.

**Comment by OlegZhXam** [comment] 2021-02-16 09:19
What actually helped me with white screen transitions when replacing the MainPage on Android after upgrading to XF 4.8 (and removing deprecated Theme nugets), is setting an implicit global style with transparent BackgroundColor for NavigationPage in App.xaml like this:

`           <Style TargetType="NavigationPage" ApplyToDerivedTypes="True">
                <Setter Property="BackgroundColor" Value="Transparent" />
            </Style>
`

**Comment by samir-dahal** [comment] 2021-03-04 08:39
Ok. I just had this problem a moment ago. I have a workaround for this one. What you have to do is. Set your mainpage without NavigationPage and for other pages to navigate, you have to set other pages as a navigation page. If startup is only your problem then it should work like a charm.

**Comment by knasher** [comment] 2021-03-30 21:55
I'm having the same issue, I've developed an app that's using a MasterDetail which contains a NavigationPage and after the splash screen has been displayed there is a white screen before all the content loads

**Comment by Elinareso** [comment] 2021-05-13 17:41
Facing the same issue in a Samsung A30 device. After the Splash screen get freezing in a black screen for several seconds.

**Comment by samir-dahal** [comment] 2021-05-14 01:50
> Facing the same issue in a Samsung A30 device. After the Splash screen get freezing in a black screen for several seconds.

Did you notice, if you set main page without navigation page you won't see it.

**Comment by lartisanetsonmobile-admin** [comment] 2021-05-14 10:09
Same here on my Honor 10, setting the main page as navigation page causes white screen (or black screen if your are in dark mode) for several seconds.

**Comment by samir-dahal** [comment] 2021-05-14 15:43
I have a work around. You can do something like this.
`<FlyoutPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="Demo.Views">
    <FlyoutPage.Flyout>
        <ContentPage Title=" "/>
    </FlyoutPage.Flyout>
    <FlyoutPage.Detail>
        
        <views:DashboardPage />
    </FlyoutPage.Detail>
</FlyoutPage>
`
Now create a helper function like:
`public static async Task PushDetailPageAsync(Page page)
        {
            if (FlyoutPage.Detail is NavigationPage)
            {
                await FlyoutPage.Detail.Navigation.PushAsync(page);
                return;
            }
            var initialDetailPage = FlyoutPage.Detail;
            FlyoutPage.Detail = new NavigationPage(page);
            FlyoutPage.Detail.Navigation.InsertPageBefore(initialDetailPage, page);
        }
`
That's all!

**Comment by Joren-Thijs** [comment] 2021-05-30 18:47
We are currently facing the same issue in preview versions of .NET MAUI  https://github.com/dotnet/maui/issues/1124#issue-906650058

**Comment by KSchau** [comment] 2021-06-08 18:50
Currently experiencing the same issue. Sometimes it's a few seconds of white screen between the splash screen and the main activity but other times the white screen is indefinite and requires closing the app to use it again. It seems to happen more often when the device sits for some time or ends up locked and then is unlocked.

This has been happening on several different devices including Samsung Galaxy Tab A 10.5's, Samsung Galaxy Tab S5e's, and Samsung Galaxy Tab S6's. All devices are running either Android 10 or 11. I tried downgrading Xamarin.Forms from 5.0.2012 to 4.4.0.991537 as I had been using previously but still encountering the issue. 

It seems to have started when I updated the Xamarin platform to 16.9.000.273.

Is there a way to back up to a previous version of Xamarin to resolve the issue?

Current Versions:
Xamarin - 16.9.000.273
Xamarin Designer - 16.9.0.318
Xamarin Templates - 16.9.72
Xamari.Android SDK - 11.2.2.1
Xamarin.iOS and Xamarin.Mac SDK - 14.14.2.5

Xamarin.Forms NuGet package - 4.4.0.9915

**Comment by AlleSchonWeg** [comment] 2021-06-08 19:12
Hi. I had the same problem. After some research i requested a change in the docs for splash screen. Here are the issue: https://github.com/MicrosoftDocs/xamarin-docs/issues/3296 
There you will find a link for an alternative way to implement a splash screen. This works for me.

**Comment by KSchau** [comment] 2021-06-09 17:07
Hi - I tried your solution (eliminated my splash screen, used a "splash" theme and then set the theme to my app's actual theme) a bit ago and I'm still encountering the issue. It did improve my loading time substantially so I appreciate that!

It seems like something is going wrong when the app resumes - either from warm or cold - especially after it sits for a while. Usually, even if the white screen goes away, Navigation ends up being broken - pushes and pops using Navigation fail.

**Comment by josemtp** [comment] 2021-07-08 22:33
Same problem in XF 5.0.0.2012, using NavigationPage, the problem occurs in Android 11 and Android 10, Samsung S10 +

**Comment by banditoth** [comment] 2021-07-09 07:33
Same problem with Xamarin.Forms 4.8.0.1451, by pushing pages to the navigationstack from a NavigationPage. Android 11, Samsung Galaxy A12

**Comment by luismts** [comment] 2021-07-20 02:21
For me, the white screen appears in android when I am running my app in debug mode. If I close debug mode and open the app again, I can see the normal behavior. 

cc @jsuarezruiz

**Comment by chaoyebugao** [comment] 2021-08-16 09:11
Same problem...

**Comment by chaoyebugao** [comment] 2021-08-16 09:32
> I have a work around. You can do something like this.
> 
> ![image](https://user-images.githubusercontent.com/39849021/118295434-94bae780-b4fb-11eb-9298-250457f6609c.png)
> 
> Now create a helper function like:
> 
> ![image](https://user-images.githubusercontent.com/39849021/118295510-aac8a800-b4fb-11eb-92f9-f99f9aa8a0ed.png)
> 
> That's all!

More detail or demo codes plz

**Comment by samir-dahal** [comment] 2021-08-17 15:40
> > I have a work around. You can do something like this.
> > ![image](https://user-images.githubusercontent.com/39849021/118295434-94bae780-b4fb-11eb-9298-250457f6609c.png)
> > Now create a helper function like:
> > ![image](https://user-images.githubusercontent.com/39849021/118295510-aac8a800-b4fb-11eb-92f9-f99f9aa8a0ed.png)
> > That's all!
> 
> More detail or demo codes plz

You can use this instead.
Edit your values.xml file to this

`<?xml version="1.0" encoding="utf-8" ?>
<resources>

  <style name="MainTheme" parent="Theme.AppCompat.Light.NoActionBar">
    
    
    

    
    
    
    
    
    
  </style>
</resources>`

**Comment by samir-dahal** [comment] 2021-08-17 15:41
Android project => Resources => values => styles.xml
Change the parent to this
` <style name="MainTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by banditoth** [comment] 2021-08-30 12:32
Seems like the error occurs only, when the `INavigation` is used to push or pop pages to a `NavigationPage` in another thread.

**Comment by brzezinol** [comment] 2021-08-30 13:23
I did some investigations, and I finally got state when all seems to be ok.
I changed style:
`<style name="MainTheme" parent="Theme.AppCompat.Light.NoActionBar">`
And changed navigation to following :

var x = await NavigationService.NavigateAsync("NavigationPage/MainPage");
if (!x.Success) {
   await MainPage.DisplayAlert("Alert", x.Exception.Message, "Ok");
}

**Comment by jfversluis** [comment] 2021-09-27 18:42
Possible duplicate of #8436

**Comment by luis95gr** [comment] 2021-09-28 06:27
Is this problem solved?, same issue and in some devices (Huawei) the app get stuck on the white screen.

**Comment by banditoth** [comment] 2021-10-06 11:02
> 
> 
> Is this problem solved?, same issue and in some devices (Huawei) the app get stuck on the white screen.

Hey, I've posted a workaround:
[](https://www.banditoth.hu/2021/10/06/xamarin-forms-white-screen-between-page-push-and-pop-solved/)

**Comment by Adlorem** [comment] 2021-11-03 15:58
I had problems with blank pages in my app on several physical devices including huawei and samsung. In my case problem was related with calling Tasks directly in constructor. When I moved them to separate method, the problem was gone.

**Comment by jfversluis** [comment] 2021-11-17 14:01
Hint for a fix might be in here: https://www.banditoth.hu/2021/10/06/xamarin-forms-white-screen-between-page-push-and-pop-solved/

**Comment by themronion** [comment] 2022-01-27 10:08
@jfversluis I've checked if this issue still exists and discovered this has been somehow magically fixed in 5.0.0.2291. U can close this one and #8436 :) Have a nice day and thanks to the Xamarin team for the work)

**Comment by themronion** [comment] 2022-01-27 10:38
Yeah, i started from the latest version and narrowed it down to 5.0.0.2291 - on earlier version the white flash is still present. I guess #4730 is the one that fixed it?

**Comment by jfversluis** [comment] 2022-01-27 10:41
That seems to make sense... Thanks for the research here! Really appreciated :) Closing this for now then. If anyone else things otherwise, please let me know or open something new!

For now assuming this is fixed by #4730

**Closed by jfversluis** 2022-01-27 10:41 UTC
Labels: t/bug :bug:, p/Android, a/performance, a/navigation

**Comment by alextorres50** [comment] 2022-04-07 19:40
This issue appear again on 5.0.0.2401 on Android API 29,API 30 
I tested on 
 - POCO F3 5g API 30
 - Redmin Note 8 API 29
 - Samsung S21 API 30

**Comment by daviscollins** [comment] 2022-05-06 14:39
I'm seeing this white screen appear using a sample app, Xamarin.Forms 5.0.0.2291, Android SDK 30.

In my sample app I'm simply setting `MainPage = new LandingPage();` in `App.xaml.cs`, and `Application.Current.MainPage = new AppShell();` in `LandingPage.xaml.cs`.

This is enough to cause the white screen to be displayed for 3+ seconds on a fresh start of the app. It seems that the number of "layers" that are setting `MainPage` increases the amount of time the white screen is shown. Also in this example, none of the pages in use are `NavigationPage`, only `ContentPage`.

Here is a link to my sample solution for anyone who'd like to take a look:
https://drive.google.com/file/d/1R6HXEnhPpoIxTY10yNNHlZcrMlDnCKHs/view?usp=sharing

**Comment by ahoke-cr** [comment] 2022-10-20 23:16
To add some more fuel, this only happens to me after popping a modal page wrapped in a navigation page (to add nav bar for toolbar items). It fixes itself when pushing a page normally (i.e., `INavigation.PushAsync(...)`) and then navigating back the page will render correctly. Interestingly, when experiencing the white page, I can still interact with the views on the page as if they were actually there but covered up by an input-transparent sheet of some sort. This is really frustrating as other solutions in this thread have not fixed the issue.

Context:
* Xamarin.Forms 5.0.0.2478
* Tested on a variety of Android devices including Android 9, 10, 11, and 12
* Various debugging to ensure no long-running blocking tasks were interrupting rendering

**Comment by bizmonger** [comment] 2022-12-26 13:37
> To add some more fuel, this only happens to me after popping a modal page wrapped in a navigation page (to add nav bar for toolbar items). It fixes itself when pushing a page normally (i.e., `INavigation.PushAsync(...)`) and then navigating back the page will render correctly. Interestingly, when experiencing the white page, I can still interact with the views on the page as if they were actually there but covered up by an input-transparent sheet of some sort. This is really frustrating as other solutions in this thread have not fixed the issue.
> 
> Context:
> 
> * Xamarin.Forms 5.0.0.2478
> * Tested on a variety of Android devices including Android 9, 10, 11, and 12
> * Various debugging to ensure no long-running blocking tasks were interrupting rendering
> 
> **EDIT: After more testing, I tried installing the Xamarin.AndroidX.Fragment@1.2.5.5 NuGet and that seems to have fixed it.**

How did Xamarin.AndroidX.Fragment address the issue?
What code did you add in addition to installing the package?

**Comment by ahoke-cr** [comment] 2023-01-03 15:41
> How did Xamarin.AndroidX.Fragment address the issue? What code did you add in addition to installing the package?

It actually only fixed the issue on a few Android versions, mainly below Android 10. I made no code changes with the Fragment package indroduction. Users are still experiencing the issue on Android 10 and above.
