### ISSUE TITLE
Grid's Border

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9420] opened 2020-02-04 12:18 UTC
Hi,

Please add Border properties to the Grid so it can also act as a table

This includes BorderWidth and BorderColor

and it should be like this:

BorderWidth="1,2,1,2"

to apply a width for left, top, right and bottom

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by mohachouch** [comment] 2020-02-04 12:38
I think we can hear this request at all layouts (Grid, StackLayout ...)

**Comment by saiyamshah143** [comment] 2020-02-04 12:46
@mohachouch @jrahma In addition, if we can have corner radius to the layouts such as Grid, Stacklayout?

**Comment by samhouts** [comment] 2020-02-04 21:52
Duplicate of #1695

**Closed by samhouts** 2020-02-04 21:52 UTC
Labels: proposal-open, t/enhancement ➕
