### ISSUE TITLE
[Bug] I am getting an issue in Swipe view inside listview , when Itemsource is changed dynamically , the Swipe view Swipe Items is not shown instead it shows the content again.

### ISSUE THREAD

**Issue by AjitKRuin** [xamarin/Xamarin.Forms#13074] opened 2020-12-08 12:33 UTC
### Description
I used Swipe view inside Listview , in swipe view used frame as content and image in swipe right item view . When changed Itemsource dynamically and swipe right , the image is not shown instead another frame is created under this frame.

### Steps to Reproduce

1. create listview with Swipe view in Item templapte ,  frame as content of swipe view.
2. Change item source dynamically.
3. Swipe the item , image is not shown another frame is shown.

### Expected Behavior
The image need to shown

### Actual Behavior
Another frame is shown.

### Basic Information

- Version with issue: 5.0.0.1558 - pre , 4.8.0.1687
- Last known good version: did not checked
- Platform Target Frameworks: 
  - iOS:  
  - Android:  10
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: Emulator Pixel 2

### Environment

```
```

### Screenshots

Expected Behavior

Actual Behavior

**Comment by jsuarezruiz** [comment] 2020-12-09 11:48
@AjitKRuin This issue seems to be fixed by https://github.com/xamarin/Xamarin.Forms/pull/12786 recently merged.
Could you attach a sample where reproduce the issue?. I can do some quick tests with the latests 5.0 version.

**Comment by Redth** [comment] 2021-04-27 17:52
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Closed by Redth** 2021-04-27 17:52 UTC
Labels: a/swipeview, p/Android, s/needs-info ❓, s/needs-repro ❔, t/bug :bug:
