### ISSUE TITLE
AutomationId for ContentPage

### ISSUE THREAD

**Issue by Wolfgang-h** [xamarin/Xamarin.Forms#3799] opened 2018-09-17 09:29 UTC
Hi!
Currently we are Building end-to-end Tests for our Xamarin.Forms App (Android and iOS) with Xamarin.UiTest. and found a problem addressing our Hamburger-Menu:

Definition:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
x:Class="InVidClient.Pages.InVIDMasterDetailMenu"
xmlns:i18n="clr-namespace:InVidClient.Localization"
Title="Master" Icon="hamburger.png" >

```
We have tried to add AutomationId and also ClassId 
`AutomationId ="AIContentPageHamburger" ClassId ="CIContentPageHamburger"`
but neither in Xamarin.UiTest repl or in Android.Studio we find the passed id.

After discussing this point with the Xamarin.uiTest-team, I was asked to generate this issue.

- Version with issue:
- no last known good version:
- IDE: Visual Studio (Windows and Mac) 15.8.4
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: 8.1 (Oreo)
- Nuget Packages:
Microsoft.AppCenter 1.5.0
PInvoke 0.5.134
Xamarin.Android 27.0.2
Xamarin.Forms 2.5.1.444934

- Affected Devices:
Currently verified on Emulator (iOS iPhone X and iPhone 8 Emulator) and Android 7.1 Emulator

If needed apk and ipa file could be uploaded.

**Comment by samhouts** [comment] 2018-09-21 17:47
related to/duplicate of #3795

**Closed by samhouts** 2018-09-21 17:47 UTC
