### ISSUE TITLE
[Bug] Editor's Event Handler inside Xamarin.Forms XAML is Broken

### ISSUE THREAD

**Issue by DamarHardy** [xamarin/Xamarin.Forms#9581] opened 2020-02-14 07:24 UTC
### Description
I make 3 different event hander inside Editor item which are Completed, Focused, and Unfocused. Everytime i did something inside the Editor Box (including tapping and typing word) those 3 events are firing. Those 3 events even fire right after every single character inputted.

### Expected Behavior

The event handler suppose to work accordingly. Completed event handler fires if and only if the user finished their input and so on.

### Actual Behavior
All 3 event handlers fires no matter what i did inside the editor box

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment] 2020-02-17 17:27
@DamarHardy  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by DamarHardy** [comment] 2020-02-18 02:24
@samhouts  so I try to make a small project that demonstrate that, fortunately the event handler works fine. But it still doesn't work in my current project. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42292985/74698437-58350900-5230-11ea-8e50-fcc7b8133777.gif)

do you know why this is happen?

**Comment by samhouts** [comment] 2020-02-20 17:53
1. Check that you're referencing the same version of Xamarin.Forms in both projects.
2. Check if you're using a different layout or if you're embedding the controls into a different kind of control.
3. Check if you're using Shell or a different type of page.
4. Check if you're targeting a different version of Android.

**Comment by DamarHardy** [comment] 2020-02-21 01:24
Hi @samhouts, it seems like this particular bug appears when we are using entry/editor inside a listview. I have seen several people experienced the same bug like in #1600. I already change my xaml using **CollectionView** and it does no problem. Thank you.

But still, i hope you guys fix it

**Comment by PureWeen** [comment] 2020-02-21 18:01
@DamarHardy Is it alright to close this one as a duplicate for now in favor of #1600 which has a repro and discussion already?

**Comment by samhouts** [comment] 2020-03-23 20:45
Duplicate of #1600

**Closed by samhouts** 2020-03-23 20:45 UTC
Labels: a/Xaml </>, a/editor, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:
