### ISSUE TITLE
System.NullReferenceException ListViewRenderer+<OnScrollToRequested>d__43.MoveNext () on iOS

### ISSUE THREAD

**Issue by jordan-surveycom** [xamarin/Xamarin.Forms#2134] opened 2018-03-19 19:04 UTC
### Description
App crashes with NullReferenceException when navigating away from page after attempting to scroll. I am not positive, but this may only happen on iOS 11 (all of the crash reports that we have received with this issue are from users on iOS 11).

Example code:
`
this.Appearing += async (object sender, EventArgs e) =>
{
if (this.scrollItem != null && App.IsIos && this.listView != null)
{
this.listView.ScrollTo(scrollItem, ScrollToPosition.Center, false);
this.scrollItem = null;
}
};
`

[Crash Report](https://github.com/xamarin/Xamarin.Forms/files/1826516/app-24e9f53f-0e00-4ad4-bf1e-79e026c73f92-id-709a7f6b-6f10-4832-aafc-861eabc46269.txt)

### Steps to Reproduce

1. Call ListView.ScrollTo() on a page (within a navigation stack) in the Page.Appearing call
2. Quickly navigate away from the page using the navigation arrow
3. App crashes with the NullReferenceException

### Expected Behavior
App doesn't crash

### Actual Behavior
App hard crashes after attempting to scroll on the page after it has disappeared from view.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: Unknown
- IDE: Visual Studio for Mac Community 7.4
- Platform Target Frameworks: 
  - iOS:  11.8.0.20
- Nuget Packages: Xamarin.Forms
- Affected Devices: iOS devices simulator and actual devices(possibly iOS 11 only)

**Comment by pauldipietro** [comment] 2018-03-19 19:18
Can you please upload a minimized reproduction project (this aids us in having the exact same code you do) and confirm if the issue still occurs as of the latest 2.5.1 prerelease? Any further information/confirmation you can provide on if this is iOS 11 specific or not is very much appreciated.

**Comment by jordan-surveycom** [comment] 2018-03-19 20:18
[ScrollNullReferenceExample.zip](https://github.com/xamarin/Xamarin.Forms/files/1826749/ScrollNullReferenceExample.zip)

Here is a minimized reproduction project. With that project, tap the back arrow on the navigation bar many times as fast as you can and the issue will happen (I was unable to reproduce by popping the page with code instead). Using that reproduction project, I was unable to reproduce on anything but iOS 11.

I was having difficulty reproducing with the latest forms 2.5.1 prerelease, so this could potentially already be fixed.

**Comment by pauldipietro** [comment] 2018-03-21 17:24
I have yet to check the reproduction, but do you mean that you were unable to reproduce it at all with the 2.5.1 prerelease?

**Comment by jordan-surveycom** [comment] 2018-03-21 17:39
Correct, I was unable to reproduce it at all with the 2.5.1 prerelease.

**Comment by PureWeen** [comment] 2018-03-31 17:59
Given that I'm just going to close this one for now. Please comment to reopen if you encounter this issue again in the latest releases

**Closed by PureWeen** 2018-03-31 17:59 UTC
Labels: p/iOS, s/needs-repro, t/bug

**Comment by MJRomka** [comment] 2018-12-13 21:51
Having the same issue right now (Xamarin.Forms 3.4.0.1008975) when doing quick navigations back:

`  at Xamarin.Forms.Platform.iOS.ListViewRenderer+<OnScrollToRequested>d__44.MoveNext () [0x00190] in <18e93b810a4a4e2f919016f742528d37>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1023 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at ***.iOS.Application.Main (System.String[] args) [0x00001] in /***/Main.cs:17 `

**Comment by MJRomka** [comment] 2018-12-18 21:38
Solved. In my case it happened when I started a lot of background operations. They affected scrolling in combination with navigation back somehow.

**Comment by PenguinPero** [comment] 2019-01-11 13:04
could this be reopened, I am getting this error too but didn't find the solution?
