### ISSUE TITLE
DynamicResource does not work with dot-separated keys [Bug] 

### ISSUE THREAD

**Issue by thomasgalliker** [xamarin/Xamarin.Forms#7863] opened 2019-10-07 21:32 UTC
### Description
When I use DynamicResource with a dot-separated key, Xamarin.Forms throws a XamlParseException, complaining that 'the static resource xy could not be found'.

### Steps to Reproduce
1. Create a resource with key "Theme.Spacing.CardSpacing" of type double.
2. Use the defined value, e.g. to set a Grid's Padding: 
`<Grid Padding="{DynamicResource Theme.Padding.CardViewPadding}" `

### Expected Behavior
The DynamicResource defined behind the given key is applied as expected.

### Actual Behavior
Xamarin.Forms.Xaml.XamlParseException: 'Position 85:36. StaticResource not found for key MediumPadding'

### Workaround
When the Key is defined explicitly, the DynamicResource is applied as expected - no exception is thrown:
`<Grid Padding="{DynamicResource Key='Theme.Padding.CardViewPadding'}"`

### Basic Information
- Version with issue: Xamarin.Forms 4.1.0.778454
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android: 9.0
- Nuget Packages: Xamarin.Forms 4.1.0.778454
- Affected Devices: iPhone X, Samsung S10, ...

**Comment by jfversluis** [comment] 2019-10-08 13:09
Hi @thomasgalliker, thanks for reporting this!

What does the definition of this resource look like? It has the actual dots in the key? There is no hierarchy resolving built in for this like with the binding on objects for example. Since the dot might be a special character in this case it makes sense that it is escaped with the quotes.

Would you be able to extract it to a standalone reproduction project to be sure we're talking about the same thing? Is there any other platform where this _is_ working that you know of?

Thanks

**Comment by thomasgalliker** [comment] 2019-10-08 18:38
Hi @jfversluis. It is still quite confusing to me. I'm working on getting a clean picture to reproducte this issue. The thing is, sometimes the DynamicResource binding (or they don't call it binding?) works to dotted resource strings - and sometimes, like in the example above with the Grid.Padding, it doesnt.

The resources are all set to a ResourceDictionary at runtime:
`this[ThemeConstants.Paddings.CardViewPadding] = spacingConfiguration.CardViewPadding;`

Later, in my XAML controls I'm applying the defined resources using DynamicResource bindings. The idea is to have themable/stylable controls which can easily be reused.

The full code as reference: https://github.com/thomasgalliker/CrossPlatformLibrary/blob/2f877f234cd0f335e371a70c26ddc9422c6b52ff/CrossPlatformLibrary.Forms/Resources/UI/ThemeSpacingResources.xaml.cs#L31

I'm trying to prepare a minimal project to reproduce the strange situation.

**Comment by thomasgalliker** [comment] 2019-10-08 19:15
Strange. I wasn't able to reproduce it - not even in the original solution where it happened yesterday. Since I created resources in my local App.xaml first and then moved them to a library's resource dictionary, I guess, there was a caching problem with some lingering compiled xaml views... I don't know.

Fact is: I can now bind dot-separated resources using DynamicResource. The only thing I've done is a complete cleanup of all build artefacts (clean.bat in the attached solution).

I guess we can close this issue for now. When I find new evidence, I'll post it here.

[App7863.zip](https://github.com/xamarin/Xamarin.Forms/files/3704139/App7863.zip)

**Closed** 2019-10-08 19:16 UTC
Labels: a/Xaml </>, s/needs-info ❓, s/needs-repro ❔, s/unverified, t/bug :bug:

**Comment by jfversluis** [comment] 2019-10-09 09:16
Thanks for the updates and your investigation @thomasgalliker !

Glad that it is resolved (for now). Feel free to reopen whenever something else in this regard happens.
