### ISSUE TITLE
Cannot set NavigationPage.Icon to FontImageSource

### ISSUE THREAD

**Issue by frogcrush** [xamarin/Xamarin.Forms#5806] opened 2019-04-04 05:48 UTC
### Description
When trying to set a NavigationPage Icon to a FontImageSource, you receive an error saying "Property 'Icon' does not support values of type 'FontImageSource'.

### Steps to Reproduce

1. Create a NavigationPage
2. Attempt to set Icon property to FontImageSource

### Expected Behavior
Icon will be set to FontImageSource

### Actual Behavior
Above error is thrown and project fails to compile.

### Basic Information

- Version with issue: 3.6.0.293080
- Last known good version: None
- IDE: Visual Studio 15.9.11

**Comment by samhouts** [comment] 2019-04-04 17:50
Duplicate of #5805 3207

**Closed** 2019-04-04 17:50 UTC
Labels: t/bug :bug:
