### ISSUE TITLE
[Bug] [WPF] DatePicker popup open issues

### ISSUE THREAD

**Issue by sanuantony** [xamarin/Xamarin.Forms#14609] opened 2021-09-13 17:32 UTC
Description
An exception "Cannot reopen a popup in the closed event handler."
We have added a trigger in the ControlTemplate of DatePicker to open the calendar popup when clicking on the DatePickerTextbox. Like below 
```
                        <ControlTemplate.Triggers>
                            <Trigger SourceName="PART_TextBox" Property="IsKeyboardFocused" Value="True">
                                <Setter Property="IsDropDownOpen" Value="True" />
                            </Trigger>
```

Steps to Reproduce
0. Create a sample WPF .netFramework app
1. Edit the Control template for the date picker and add the above section in the control trigger.
2. Run app
3. Click on the datepicker.

Expected Behavior
The calendar popup should open.

Actual Behavior
Throwing an exception "Cannot reopen a popup in the closed event handler."
Basic Information

- Version with issue: .net 4.8, windows 10
Environment 
Microsoft Visual Studio Professional 2019
Version 16.11.2

OS Name	Microsoft Windows 10 Pro

Version	10.0.17134 Build 17134

Sample Code
```
<Window
    x:Class="WpfApp3.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:WpfApp3"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="450"
    Height="100"
    mc:Ignorable="d">
    <Window.Resources>
        <Style TargetType="{x:Type DatePicker}">
            <Setter Property="Foreground" Value="#FF333333" />
            <Setter Property="IsTodayHighlighted" Value="True" />
            <Setter Property="SelectedDateFormat" Value="Short" />
            <Setter Property="Background" Value="Transparent" />
            <Setter Property="Padding" Value="2" />
            <Setter Property="BorderThickness" Value="1" />
            <Setter Property="HorizontalContentAlignment" Value="Stretch" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type DatePicker}">
                        <Border
                            Padding="{TemplateBinding Padding}"
                            Background="{TemplateBinding Background}"
                            BorderBrush="{TemplateBinding BorderBrush}"
                            BorderThickness="{TemplateBinding BorderThickness}">
                            <Grid
                                x:Name="PART_Root"
                                HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                VerticalAlignment="{TemplateBinding VerticalContentAlignment}">
                                <Grid.Resources>
                                    <SolidColorBrush x:Key="DisabledBrush" Color="#A5FFFFFF" />
                                    <ControlTemplate x:Key="DropDownButtonTemplate" TargetType="{x:Type Button}">
                                        <Grid>
                                            <Border Padding="2" BorderBrush="Transparent">
                                                <TextBlock FontFamily="Ace-Icon-Font" Text="&#xe928;" />
                                            </Border>
                                        </Grid>
                                    </ControlTemplate>
                                </Grid.Resources>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="Auto" />
                                </Grid.ColumnDefinitions>
                                <Button
                                    x:Name="PART_Button"
                                    Grid.Row="0"
                                    Grid.Column="0"
                                    Width="20"
                                    Margin="3,0,3,0"
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Top"
                                    Focusable="False"
                                    Foreground="{TemplateBinding Foreground}"
                                    Template="{StaticResource DropDownButtonTemplate}" />
                                <DatePickerTextBox
                                    x:Name="PART_TextBox"
                                    Grid.Row="0"
                                    Grid.Column="1"
                                    HorizontalContentAlignment="Stretch"
                                    VerticalContentAlignment="Stretch"
                                    Focusable="{TemplateBinding Focusable}">
                                    <!--<DatePickerTextBox.Style>
                                        <Style>
                                            <Style.Triggers>
                                                <Trigger Property="IsKeyboardFocused" Value="True">
                                                    <Setter TargetName="PART_Popup" Property="IsOpen" Value="True" />
                                                </Trigger>
                                            </Style.Triggers>
                                        </Style>
                                    </DatePickerTextBox.Style>-->
                                </DatePickerTextBox>
                                <Grid
                                    x:Name="PART_DisabledVisual"
                                    Grid.Row="0"
                                    Grid.Column="0"
                                    Grid.ColumnSpan="2"
                                    IsHitTestVisible="False"
                                    Opacity="0">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="*" />
                                        <ColumnDefinition Width="Auto" />
                                    </Grid.ColumnDefinitions>
                                    <Rectangle
                                        Grid.Row="0"
                                        Grid.Column="0"
                                        Fill="#A5FFFFFF"
                                        RadiusX="1"
                                        RadiusY="1" />
                                    <Rectangle
                                        Grid.Row="0"
                                        Grid.Column="1"
                                        Width="19"
                                        Height="18"
                                        Margin="3,0,3,0"
                                        Fill="#A5FFFFFF"
                                        RadiusX="1"
                                        RadiusY="1" />
                                    <Popup
                                        x:Name="PART_Popup"
                                        AllowsTransparency="True"
                                        Placement="Bottom"
                                        PlacementTarget="{Binding ElementName=PART_TextBox}"
                                        StaysOpen="False" />
                                </Grid>
                            </Grid>
                        </Border>
                        <ControlTemplate.Triggers>
                            <Trigger SourceName="PART_TextBox" Property="IsKeyboardFocused" Value="True">
                                <Setter TargetName="PART_Popup" Property="IsOpen" Value="True" />
                                <Setter Property="IsDropDownOpen" Value="True" />
                            </Trigger>
                            <DataTrigger Binding="{Binding Source={x:Static SystemParameters.HighContrast}}" Value="false">
                                <Setter TargetName="PART_TextBox" Property="Foreground" Value="{Binding Foreground, RelativeSource={RelativeSource TemplatedParent}}" />
                            </DataTrigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Style TargetType="{x:Type DatePickerTextBox}">
            <Setter Property="Foreground" Value="{DynamicResource {x:Static SystemColors.WindowTextBrushKey}}" />
            <Setter Property="Background" Value="{DynamicResource {x:Static SystemColors.WindowBrushKey}}" />
            <Setter Property="ScrollViewer.PanningMode" Value="VerticalFirst" />
            <Setter Property="Stylus.IsFlicksEnabled" Value="False" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type DatePickerTextBox}">
                        <Grid>
                            <Grid.Resources>
                                <SolidColorBrush x:Key="WatermarkBrush" Color="#FFAAAAAA" />
                            </Grid.Resources>
                            <Border
                                x:Name="Border"
                                Padding="{TemplateBinding Padding}"
                                Background="{TemplateBinding Background}"
                                BorderBrush="{TemplateBinding BorderBrush}"
                                BorderThickness="{TemplateBinding BorderThickness}"
                                CornerRadius="1"
                                Opacity="1">
                                <Grid
                                    x:Name="WatermarkContent"
                                    HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                    VerticalAlignment="{TemplateBinding VerticalContentAlignment}">
                                    <Border
                                        x:Name="ContentElement"
                                        BorderBrush="#FFFFFFFF"
                                        BorderThickness="1" />
                                    <Border
                                        x:Name="watermark_decorator"
                                        BorderBrush="#FFFFFFFF"
                                        BorderThickness="1">
                                        <ContentControl
                                            x:Name="PART_Watermark"
                                            Padding="2"
                                            Focusable="False"
                                            IsHitTestVisible="False"
                                            Opacity="0">
                                            <TextBlock Text="mm/dd/yyyy" />
                                        </ContentControl>
                                    </Border>
                                    <ScrollViewer
                                        x:Name="PART_ContentHost"
                                        Margin="0"
                                        HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                                        VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}" />
                                    <Border
                                        x:Name="FocusVisual"
                                        BorderBrush="#FF45D6FA"
                                        CornerRadius="1"
                                        IsHitTestVisible="False"
                                        Opacity="0" />
                                </Grid>
                            </Border>
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Window.Resources>
    <Grid>
        <DatePicker
            Margin="28,24,0,0"
            HorizontalAlignment="Left"
            VerticalAlignment="Top" />

    </Grid>
</Window>

```

StackTrace

System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot reopen a popup in the closed event handler.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.DatePicker.OnIsDropDownOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.StyleHelper.InvalidateDependents(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, FrugalStructList`1& dependents, Boolean invalidateOnlyContainer)
   at System.Windows.StyleHelper.OnTriggerSourcePropertyInvalidated(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, DependencyPropertyChangedEventArgs changedArgs, Boolean invalidateOnlyContainer, FrugalStructList`1& triggerSourceRecordFromChildIndex, FrugalMap& propertyTriggersWithActions, Int32 sourceChildIndex)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyPropertyKey key, Object value)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.Input.KeyboardNavigation.Navigate(DependencyObject currentElement, TraversalRequest request, ModifierKeys modifierKeys, DependencyObject firstElement, Boolean fromProcessInputTabKey)
   at System.Windows.FrameworkElement.MoveFocus(TraversalRequest request)
   at System.Windows.Controls.DatePicker.PopUp_Closed(Object sender, EventArgs e)
   at System.Windows.FrameworkElement.RaiseClrEvent(EventPrivateKey key, EventArgs args)
   at System.Windows.Controls.Primitives.Popup.OnClosed(EventArgs e)
   at System.Windows.Controls.Primitives.Popup.DestroyWindow()
   at System.Windows.Controls.Primitives.Popup.<HideWindow>b__130_0(Object sender, EventArgs args)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WpfApp3.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

**Comment by jsuarezruiz** [comment] 2021-10-01 16:14
Could you attach a small sample where reproduce the issue?. Thanks!

**Comment by mayuroozee** [comment] 2021-11-23 12:14
Hello, I'm facing the same exception.

PS. I've loaded Xamarin App in the WPF Window.

Any update so far on this?

**Comment by jfversluis** [comment] 2022-03-31 09:29
Duplicate of #13622

**Closed by jfversluis** 2022-03-31 09:29 UTC
Labels: t/bug :bug:, s/needs-repro ❔, s/needs-info ❓, p/WPF, s/unverified
