### ISSUE TITLE
Crash on IOS when call PopModalAsync [Bug] 

### ISSUE THREAD

**Issue by NasserAssaly** [xamarin/Xamarin.Forms#14534] opened 2021-08-25 11:15 UTC
### Description
When we call  await this.Navigation.PushModalAsync(new NavigationPage(new Page1())); from page 
then click on black transparent area around the modal of Page1 then pop the modal,
App Crash

### Steps to Reproduce

1. Create new Xamarin Application
2.  Add new Page Called Page1 
3. Add button "Pop" to page1 and set this code in Clicked event " this.Navigation.PopModalAsync();"
4.  Add new Button "Push" to MainPage and set this code in Clicked event  " await this.Navigation.PushModalAsync(new NavigationPage(new Page1()));"
5. Add new class inherited from  NavigationRenderer Class in IOS project
6. Override ViewDidLoad and add this code "ViewController.ModalPresentationStyle = UIModalPresentationStyle.PageSheet;"
7. Override DidMoveToParentViewController and add this code " parent.ModalPresentationStyle = ViewController.ModalPresentationStyle;"
8. Run the application in MainPage then click on "Push" button.
9. Once Page1 Modal appear, click anyway around the modal the black space 
10. Click on "Pop" button on page1 
11. Modal disappear and application crash.

### Expected Behavior 
Application should not be crash.

### Actual Behavior
Application Crash once the modal disappeared

- Version with issue: 5.0.0.2083
- Last known good version: Xamarin.Forms 4.5.0.356
- Platform Target Frameworks: 
  - iOS:  14.5

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Microsoft Visual Studio Enterprise 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Screenshots

![03a7676e-6e36-43b8-b0f2-e31bc17d0850](https://user-images.githubusercontent.com/25197598/130780969-00827a18-94ef-40fc-9fea-218dffc644e2.jpg)

### Reproduction Link
[App4.zip](https://github.com/xamarin/Xamarin.Forms/files/7046490/App4.zip)

**Comment by jfversluis** [comment] 2021-09-06 12:17
Duplicate of #12300

**Closed by jfversluis** 2021-09-06 12:17 UTC
Labels: t/bug :bug:, p/iOS 🍎, s/unverified, a/navpage

**Comment by NasserAssaly** [comment] 2021-09-12 14:03
Thanks for replay but "Duplicate of #12300" is merged on 5.0.0.0 but we phased it on Version 5.0.0.2083

**Comment by NasserAssaly** [comment] 2021-09-12 14:04
> Duplicate of #12300

Thanks for replay but "Duplicate of #12300" is merged on 5.0.0.0 but we phased it on Version 5.0.0.2083

**Comment by jfversluis** [comment] 2021-09-13 09:46
Actually it's merged on 5.0.0, the last number is disregarded :) this fix will be part of the next service release
