### ISSUE TITLE
[Bug] Android on some phones when we have more than one ViewCell containing Entry Control in TableView the Unfocused event of first entry cell also triggers Unfocused event of other Entry(Part of ViewCell).

### ISSUE THREAD

**Issue by muffadal53** [xamarin/Xamarin.Forms#6575] opened 2019-06-19 07:44 UTC
### Description
I have two entry controls in my Xamarin forms. I have registered to Unfocused event of both entry control with respective target methods. The Xamarin forms version I am using is "3.6.0.344457". Here, when I Unfocus from first entry control and set focus of second entry control, the Unfocus event of both the entry controls i.e. first and second entry control get called in a Cycle.Whereas, it should only call UnFocus of first entry control. Also, when I erase whole content from second entry control using backspace key of softkeypad, UnFocus event of second entry control gets called for each character. This happens only on certain Android phones like Huawei, Google Pixel with Android version 8.0.

It works perfectly fine on samsung S8 and S10 phones having Android version 9.0.0.

### Steps to Reproduce

1. Create custom ViewCell containing one Entry Control.
2. Create two table section each containing on ViewCell create above.
3. Register "Unfocused" event for each ViewCell with an Alert message of your choice.
4. Add this TableSection to TableRoot and add this TableRoot to TableView.
5. Now type something on first Entry ViewCell and then tap your cursor to second Entry ViewCell.
6.Notice the Display alert messages.

### Expected Behavior
UnFocused event of only first entry viewcell should be called and not the second one.

### Actual Behavior
When we change focus from first Entry ViewCell to another the UnFocused of both entry ViewCell gets called in a cycle on some devices.

### Basic Information

- Version with issue: Xamarin forms version "3.6.0.344457"
- Last known good version: None
- IDE:Visual Studio Professional 2017
- Platform Target Frameworks: 
    - Android: "8.0.0", "8.1.0"  
- Affected Devices: Huawei P20 Lite, Google Pixel 2 XL

### Sample Code

`using Xamarin.Forms;

namespace EntryFocusSample
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            TableView entryTableView = new TableView();
            TableRoot entryTableRoot = new TableRoot();

            entryTableView.Intent = TableIntent.Settings;

            //Entry1 Content.
            var labelEntry1 = new TestLabelCell();
            ((Label)labelEntry1.View).Text = "Entry1";
            TableSection entryLabel1TableSection = new TableSection();
            entryLabel1TableSection.Add(labelEntry1);

            var identifierFromCell = new TestEntryCell();
            identifierFromCell.View.Unfocused += FromCellUnFocused;
            TableSection fromTableSection = new TableSection();
            fromTableSection.Add(identifierFromCell);

            //Entry2 Content.
            var labelEntry2 = new TestLabelCell();
            ((Label)labelEntry2.View).Text = "Entry2";
            TableSection entryLabel2TableSection = new TableSection();
            entryLabel2TableSection.Add(labelEntry2);

            var identifierToCell = new TestEntryCell();
            identifierToCell.View.Unfocused += ToCellUnFocused;
            TableSection toTableSection = new TableSection();
            toTableSection.Add(identifierToCell);

            entryTableRoot.Add(entryLabel1TableSection);
            entryTableRoot.Add(fromTableSection);
            entryTableRoot.Add(entryLabel2TableSection);
            entryTableRoot.Add(toTableSection);

            entryTableView.Root = entryTableRoot;
            Content = entryTableView;
        }

        private void FromCellUnFocused(object sender, FocusEventArgs e)
        {
            DisplayAlert("UnFocus", "Entry1 lost focus", "OK");
        }

        private void ToCellUnFocused(object sender, FocusEventArgs e)
        {
            DisplayAlert("UnFocus", "Entry2 lost focus", "OK");
        }
    }

    internal class TestEntryCell : ViewCell
    {
        public TestEntryCell()
        {
            var entryCellThickness = (Device.RuntimePlatform == Device.iOS)
                ? new Thickness(0)
                : new Thickness(10, 0, 10, 0);

            var entryCell = new Entry
            {
                HorizontalTextAlignment = TextAlignment.Start,
                BackgroundColor = Color.White,
                HeightRequest = 50,
                Margin = entryCellThickness,
                MaxLength = 256,
                FontSize = 16
            };
            View = entryCell;
        }
    }

    internal class TestLabelCell : ViewCell
    {
        public TestLabelCell()
        {
            var titleLabel = new Label
            {
                HorizontalOptions = LayoutOptions.StartAndExpand,
                VerticalOptions = LayoutOptions.End,
                HeightRequest = 40,
                LineBreakMode = LineBreakMode.TailTruncation,
                FontSize = 16
            };
            View = titleLabel;
        }
    }
}
[EntryFocusSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3304955/EntryFocusSample.zip)
`

**Comment by samhouts** [comment] 2019-06-21 01:11
Duplicate of #1906

**Closed by samhouts** 2019-06-21 01:11 UTC
Labels: a/listview, p/Android, s/unverified, t/bug :bug:
