### ISSUE TITLE
[Bug] CarouselView. The view is not updated after the orientation change

### ISSUE THREAD

**Issue by thp1972** [xamarin/Xamarin.Forms#10330] opened 2020-04-14 17:29 UTC
### Description
I'm trying the example for CarouselView. https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/carouselview/. However the CarouselView is not working well because when I change the screen orientation, **_from portrait to landscape and then from landscape to portrait_**, the relative content view is not updated.

### Steps to Reproduce

1. Download the solution from: https://docs.microsoft.com/en-gb/samples/xamarin/xamarin-forms-samples/userinterface-carouselviewdemos/ 
2. Start the app from Visual Studio
3. Select in the app, the item **Horizontal layout data template**
4. rotate the emultator (device) in landscape mode
5. rotate the emulator (device) in portrait mode

### Expected Behavior
the slide (view) should be rendered as it were in portrait mode 

### Actual Behavior
the slide (view) is rendered as if it were still in landscape mode

### Basic Information

- Version with issue: XAMARIN.FORMS 4.5.0.617
- Last known good version: 
- IDE: Visual Studio 2019 16.5.3
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9
- Nuget Packages:
- Affected Devices: All Android devices

### Screenshots

This is the bug...

![qemu-system-x86_64_jjnc7sxiui](https://user-images.githubusercontent.com/31475711/79254159-97748480-7e84-11ea-97c2-144da8068ad2.png)

**Comment by Huaba93** [comment] 2020-04-15 05:36
I guess duplicate of #6869

**Comment by samhouts** [comment] 2020-04-17 22:40
Duplicate of #6869

**Closed by samhouts** 2020-04-17 22:40 UTC
Labels: a/carouselview, p/Android, s/unverified, t/bug :bug:
