### ISSUE TITLE
[Bug] Switch Background can not be seen on black Background in dark mode

### ISSUE THREAD

**Issue by Codelisk** [xamarin/Xamarin.Forms#12545] opened 2020-10-20 17:39 UTC
# Description
When we have a black background in dark mode we can only see the thumb of the switch, however not the background

### Steps to Reproduce

1.  Set Dark Mode Android
2.  Add a switch on a black background
3.  Watch

### Expected Behavior
Switch Off Color should be possible to set to white
### Actual Behavior
Switch Off Color can not be shown

### Basic Information

- Version with issue: Xamarin Forms 4.8.0.1451
- Last known good version: None
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: Android 10
  - UWP:  
- Android Support Library Version: Android X
- Nuget Packages: Xamarin Visual Material
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/51824173/96623306-772df280-130b-11eb-8575-039a8f19554c.png)

### Workaround

No workaround

It would be perfect when there would be a BindableProperty OffColor to set for Switch.

**Comment by StephaneDelcroix** [comment] 2020-10-21 08:56
> It would be perfect when there would be a BindableProperty OffColor to set for Switch.

updating the default theme is also an option

**Comment by Codelisk** [comment] 2020-10-21 12:29
@StephaneDelcroix i miss something, you mean making a custom renderer for the switch control on each platform?
Otherwise do you have any info for me how to "update the default theme"?

**Comment by StephaneDelcroix** [comment] 2020-10-21 13:26
@Codelisk that wasn't meant as a workaround, but as a way for us to fix it in our code

**Comment by transis2** [comment] 2020-10-23 12:25
Same issue with Progressbar and Entry Controls https://github.com/xamarin/Xamarin.Forms/issues/12583 and https://github.com/xamarin/Xamarin.Forms/issues/12584

**Comment by PureWeen** [comment] 2020-10-30 23:26
Same thing here as on the other two issues @transis2 

I think there's something I'm not understanding here on your set of issues.

![image](https://user-images.githubusercontent.com/5375137/97764650-60428980-1add-11eb-8510-3c35e1a57cfa.png)

**Comment by transis2** [comment] 2020-10-31 23:54
@PureWeen sorry guys. 
In My case I wrote projects in 2017 and keeping it until the atual days. 
I wrote custom theme resources because in the past we have no native support to dark theme.
Also theres something wrong with My \Resources\values\styles.xml

My app give Users the option to choose light or dark Mode independent of OS theme. This the cause of confusion. 
If we just change page background color to dark, controls need be set manually to inverse color.

But some controls haven't exposed color properties that Led me to write an issue. 

For example: switch don't expose an property no manually colorize offcolor.

**Comment by jsuarezruiz** [comment] 2020-11-18 10:08
@transis2 I think then the idea would be rather to add an `OffColor` property to Switch? https://github.com/xamarin/Xamarin.Forms/issues/10341

**Comment by transis2** [comment] 2020-11-18 11:44
@jsuarezruiz Yes, it's a enhancement like the proposed by https://github.com/xamarin/Xamarin.Forms/issues/10341

**Comment by PureWeen** [comment] 2020-12-10 00:28
Closing for now since
https://github.com/xamarin/Xamarin.Forms/issues/10341

Seems to cover this

**Closed by PureWeen** 2020-12-10 00:28 UTC
Labels: a/darkmode, a/switch, p/Android, t/enhancement ➕, up-for-grabs
