### ISSUE TITLE
[Bug] Embedded Fonts Not Recognized

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#9190] opened 2020-01-13 21:50 UTC
### Description

Using the Embedded Fonts in Xamarin.Forms 4.5 preview 1, a general TTF font seems to be working fine(*), however when using an OTF font such as Font Awesome it does not get rendered on iOS.

\* NOTE that neither font works on Android

Also related to this... the Font Alias does not work.

### Steps to Reproduce

1. Embed 1:* Fonts 
2. Add the appropriate ExportFont Attribute(s) to the assembly
3. Use the PostScript Name for the font

### Expected Behavior

The specified font should be used

### Actual Behavior

The TTF font works on iOS but not Android. 
The OTF font doesn't work on iOS or Android... 

didn't check UWP.

### Basic Information

- Version with issue: 4.5-pre1
- Last known good version: n/a
- Nuget Packages:

### Screenshots

You can see the recorded stream https://twitch.tv/dansiegel

### Reproduction Link

[App5.zip](https://github.com/xamarin/Xamarin.Forms/files/4055967/App5.zip)

### Workaround

n/a

**Comment by dansiegel** [comment] 2020-01-13 22:35
worth noting btw, I tried this with a regular font, not Font Awesome Free and the OTF font did actually work on iOS..

**Comment by davidortinau** [comment] 2020-01-21 03:26
I tried this PR build with the attached project and it didn't work. I did for a brief build have the material icons appearing, but I cannot reproduce that good luck. 

The Raleway font works flawlessly. 

I tried using `EmbeddedFontResourceId = "ItesaMeDesignio.Styles.Fonts.material.ttf"` and the Alias. 

[CruiseMobileUI.zip](https://github.com/xamarin/Xamarin.Forms/files/4089049/CruiseMobileUI.zip)

**Comment by RedChops** [comment] 2020-02-03 15:13
Oddly enough, I can't get a TTF to work in either platform (Material Icons), but an OTF a friend created works in iOS but not Android

**Comment by jsauve** [comment] 2020-02-15 21:52
I'm seeing something similar. I've tried a few of Google's open fonts. They seem to work on iOS, but not Android. I put together a small sample: [test.zip](https://github.com/xamarin/Xamarin.Forms/files/4209026/test.zip)

**Comment by wagenheimer** [comment] 2020-02-28 22:43
Same problem here! I wasn't able to use FontAwesome fonts at all.

**Comment by BenBtg** [comment] 2020-03-05 13:23
Same issues here. Embedded FontAwesome working great on iOS but not on Android

**Comment by ahmad-crossplatform** [comment] 2020-03-08 22:50
Same here iOS works but not Android 

![image](https://user-images.githubusercontent.com/30656865/76172549-9bcbc480-6197-11ea-8741-a6e7dbb14863.png)

**Comment by noxe** [comment] 2020-03-10 12:42
Any Info about this? Wondering why 4.5 is released with this known issues?

**Comment by zoli13** [comment] 2020-03-13 16:36
Embedded fonts does not work on XF 4.5.0.356.
I tested on Android only.
See attached screenshot + project.

![Screenshot_2020-03-13-16-24-47-877_com companyname fontapp](https://user-images.githubusercontent.com/9251057/76640413-2de51b80-6550-11ea-85d8-93fd128e47e0.jpg)
[FontApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4330562/FontApp.zip)

**Note:** it's really annoying, as SKIA gets the fonts from Embedded Resources, while XF only works with Platform Assets/Resource fonts. So, I need to deploy the fonts two times (one in .NET core shared/Embedded Res + one in the Platform/Assets), what a waste!

**Comment by noxe** [comment] 2020-03-19 06:34
Any Info about this?

**Comment by almirvuk** [comment] 2020-03-20 20:17
It does not work on Android with `4.6.0.379-pre1` as well.

**Comment by JPZV** [comment] 2020-03-22 19:27
Hello, I had the same problem as you and I managed to solved at least some issues that I had:

First: There is an issue with a lot of files where the name is like: MyFont-Regular.ttf, the problem is that Android's asset cannot have the '-' in their file's name, so you should change all the MyFont-Regular.ttf to MyFont.ttf or MyFontRegular.ttf
Second: You _don't_ need to copy the files in the iOS project as it's being copied while compiling (sometimes it could fail though), **but** you will need to copy the font's file to the Droid project because somewhy it's not being copied at all.
Third: The FontFamily stills being used like in the old system. i.e. You will need to set that property to `MyFont.ttf#MyFont-Alias` in Android and just `MyFont` in iOS.

Of course this should not be like intended. Maybe all these points are easy to fix for the Xamarin team as they must be done while compiling.
Also this doesn't work always. My app uses Lato and (just for now) Segoe MDL2 Assets. Lato works fine in both Android and iOS using the steps before. But somewhy Segoe doesn't work in iOS (in Android works, but I think is because I need to copy the file to its project, and that is the only requeriment to use custom fonts in android, so actually the Embedded font is useless for now in Android). The only fix to this is to copy the file into the iOS project **and** add its reference to `info.plist` (I don't know if this is a issue with Segoe, or with having multiple fonts, or if actually the Lato font is included in iOS)

**Comment by dfarrNTST** [comment] 2020-03-30 19:02
Is it possible to get some guidance on how this actually works or doesn't work?  What is supported, what isn't supported?  We have not been able to get any of this working in any solution...new or old based on the documentation in the release notes.  The documentation simply states to add the font file to the shared project, set as Embedded Resource, ExportFont in AssemblyInfo.cs, and use.  This does not work for Font Awesome or Lato font or any other font we typically use.  

Since this is "live", can we please get some detailed guidance on how to properly use this as it exists in the production NuGet package today?  Else remove it completely...its terribly confusing.

**Comment by wagenheimer** [comment] 2020-03-30 19:09
@dansiegel Do you have something to tell about this? It seems that there isn't anybody checking this bug.

**Comment by jfversluis** [comment] 2020-03-30 19:46
@wagenheimer actually, just last week we have merged a PR that should fix the working of this :) if you're feeling adventurous you can check out our nightly feed which should have the fix. If not, within a week there should be a new 4.5 service release which also has this fix.

Please be sure to try it and let us know so we know if this can be closed or we need to fix it some more. Thanks!

**Comment by ahmetkocadogan** [comment] 2020-03-31 08:36
I updated my Xamarin.Forms nuget packages to 4.5.0.495 to try this, and in android emulator, embedded fonts worked like expected. But when i publish the android app (i use aab), and download from google play to device via update, i noticed embedded fonts are not working.

**Comment by VladislavAntonyuk** [comment] 2020-03-31 10:52
I think it would be nice if somebody attach a sample with most popular fonts (e.g. FontAwesome)

**Comment by jfversluis** [comment] 2020-03-31 10:58
@ahmetkocadogan would you be somehow able to verify it does work with an APK? Also I think the new service release coming out this week will have some improvements, when that comes out please try that and let us know if that fixes it.

@VladislavAntonyuk whenever the version comes out with all the latest bits to make this work more stable I have a blogpost ready. The sample is already to be seen here, but note you will need to use the nightly feed for it to work right now: https://github.com/jfversluis/EmbeddedFontsSample

Does that help? Are you missing something from this?

**Comment by ahmetkocadogan** [comment] 2020-03-31 11:47
@jfversluis i published the app as apk, and no difference. Fonts not working in android. Below, i attach screen images, android-aab, android-apk, and iphone, all real devices.

Android - APK
![android-apk](https://user-images.githubusercontent.com/7287309/78022794-3ca83c80-735e-11ea-917e-7eba98a63bfd.jpg)

Android - AAB
![android-aab](https://user-images.githubusercontent.com/7287309/78022818-46ca3b00-735e-11ea-899c-26f555a244c5.jpg)

iPhone
![iphone](https://user-images.githubusercontent.com/7287309/78022839-4f227600-735e-11ea-91ec-bed91baab2c0.jpg)

Font i use is Ubuntu.

I'll try when the next Xamarin.Forms release is available, and i'll update the issue.

**Comment by VladislavAntonyuk** [comment] 2020-03-31 14:27
Thank you @jfversluis , will take a look

**Comment by jfversluis** [comment] 2020-03-31 19:26
@ahmetkocadogan this might be related, could you try the suggestion in this comment: https://github.com/xamarin/Xamarin.Forms/issues/9900#issuecomment-606558093

**Comment by cklenk** [comment] 2020-04-01 20:36
Do you still need to add the font name in the Info.plist UIAppFonts key for iOS?

**Comment by jfversluis** [comment] 2020-04-01 20:37
@cklenk you do not :)

**Comment by noxe** [comment] 2020-04-02 07:15
So this is not available in the latest 4.6.0 Pre Release 3 ?

**Comment by noxe** [comment] 2020-04-02 07:31
Cannot get the working - also tried with latest 4.5.0.530. Tried my application and also the demo application from top -> App5.zip - no chance?

**Comment by jfversluis** [comment] 2020-04-02 08:02
@noxe could you try this; https://github.com/jfversluis/EmbeddedFontsSample

**Comment by noxe** [comment] 2020-04-02 08:07
Hmm - thank you - seems to work - will need to look where the difference now is. i see ExportFont is defined in App.xaml.cs - while i have it in AssemblyInfo.cs ?

**Comment by noxe** [comment] 2020-04-02 08:18
Ok - i am getting closer - this works also in my application -  <Label Text="&#xf584;" FontFamily="FontAwesome5Regular" 

But this one not:

 <Label
                    FontFamily="FontAwesome5Regular"
                    FontSize="24"
                    Text="{x:Static fontawesome:FontAwesomeIcons.Bars}">

/// <summary>
        /// fa-bars unicode value ("\uf0c9").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/bars
        /// </summary>
        public const string Bars = "\uf0c9";

**Comment by noxe** [comment] 2020-04-02 08:18
Sorry - the first line was the icon from the example

![image](https://user-images.githubusercontent.com/158478/78225981-5915b780-74cb-11ea-979b-2da596c4b162.png)

**Comment by noxe** [comment] 2020-04-02 08:19
This does not work:

![image](https://user-images.githubusercontent.com/158478/78226022-66cb3d00-74cb-11ea-8656-a84b81eb5ffb.png)

**Comment by VladislavAntonyuk** [comment] 2020-04-02 08:19
@jfversluis did you make some changes with the font? When I try in your sample FontAwesome Brands or Font Awesome Solid on iOS, it doesn’t render the image

**Comment by jfversluis** [comment] 2020-04-02 08:33
I did not make any changes to the fonts. If one of you could take that code from me, add the things that you don't see working and attach that here I'm happy to take a look.

**Comment by noxe** [comment] 2020-04-02 08:40
I try to isolate currently - really seems to make a difference about FontSize. If i make FontSize 50 - i see the icons, if 24 not?

**Comment by noxe** [comment] 2020-04-02 08:47
Take a look at the attached sample - very strange?
[EmbeddedFontsSample-master.zip](https://github.com/xamarin/Xamarin.Forms/files/4419807/EmbeddedFontsSample-master.zip)

**Comment by noxe** [comment] 2020-04-02 08:48
i tested on iOS

**Comment by noxe** [comment] 2020-04-02 08:51
![image](https://user-images.githubusercontent.com/158478/78229112-d6dbc200-74cf-11ea-82a8-b24a694378c6.png)

**Comment by VladislavAntonyuk** [comment] 2020-04-02 13:00
My attempt with multiple projects: https://github.com/xamarin/Xamarin.Forms/files/4411978/EmbeddedFonts.zip

**Comment by noxe** [comment] 2020-04-03 08:26
@jfversluis could you repro?

**Comment by jjchiw** [comment] 2020-04-04 21:12
It seems it doesn't work well with FontImageSource in iOS

![image](https://user-images.githubusercontent.com/642319/78461473-7ca65100-76c9-11ea-8f7a-d01adb606255.png)

I cloned https://github.com/jfversluis/EmbeddedFontsSample and just added the FontImageSource

**Comment by noxe** [comment] 2020-04-06 12:51
no more updates here?

**Comment by jfversluis** [comment] 2020-04-06 18:08
Hey everyone! Thanks for all the input! I do feel that this issue is getting a bit out of control and we are now describing all kind of issues which makes it hard to track.

@noxe I did see your project and I do see the same thing happening which is really weird. Anything above the size of 24 on iOS will show the question mark. I did verify that with another FontAwesome font that _doesn't_ happen. Can I ask you to open a new issue for this problem? If you're unable to, let me know, I will do it.

@VladislavAntonyuk Same for you. Could you maybe add that in a new issue and describe all the details there?

@jjchiw probably no surprise by this time... Would you be able to open a new issue describing this problem?

If you could fill out the bug report template and add a little reproduction project that would be amazing!

@ahmetkocadogan could you verify if your problem still exists in the latest 4.5.0.530 version? If so, please open a new issue with all the details and we will have a look.

Thank you all!

**Comment by jfversluis** [comment] 2020-04-06 18:29
@dansiegel I pulled down your repro, added the latest 4.5.0.530 and fixed the FontAwesome filename <-> FontFamily attribute value and now it seems to work. I'll close this one for now, if you think otherwise please let me know I'll reopen or open a new issue. Thanks!

**Closed by jfversluis** 2020-04-06 18:29 UTC
Labels: a/fonts, in-progress, p/Android, p/iOS 🍎, s/unverified, t/bug :bug:

**Comment by dansiegel** [comment] 2020-04-06 19:55
actually I was confused why it wasn't closed before... given @Clancey's PR for this issue, continued issues really should be tracked separately.

**Comment by zoli13** [comment] 2020-04-07 10:27
I re-tested my [above attached](https://github.com/xamarin/Xamarin.Forms/issues/9190#issuecomment-598810738) (Android only) sample with 4.5.0.530, and I can confirm it **works**.

**Comment by mohammedmsadiq** [comment] 2020-05-01 00:50
https://www.linkedin.com/pulse/embedded-fonts-mohammed-m-sadiq

**Comment by mishtu123** [comment] 2020-08-19 11:09
I m trying to use NewsSans-Black font and it’s not working for Android. Didnot check iOS

**Comment by jfversluis** [comment] 2020-08-19 11:16
@mishtu123 please see if there is a relevant issue open already and if not open a new one. Thanks!
